-- EngCat — Education (교육) 단어 + 패턴
-- 210 words (35 per CEFR level A1~C2) + 42 patterns (7 per level)
-- Generated: 2026-05-24

-- ══════════════════════════════════════
-- WORDS — A1 (35)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_education_A1_01','school','/skuːl/','noun','학교','A place where children go to learn.','I go to {school} every day.','저는 매일 학교에 가요.','school','A1','education',1,'school building students classroom'),
('w_education_A1_02','teacher','/ˈtiːtʃər/','noun','선생님','A person who teaches, especially in a school.','My {teacher} explains things clearly.','우리 선생님은 설명을 잘 해주세요.','teacher','A1','education',1,'teacher classroom whiteboard students'),
('w_education_A1_03','student','/ˈstjuːdənt/','noun','학생','A person who is studying at a school or college.','She is a hard-working {student}.','그녀는 열심히 공부하는 학생이에요.','student','A1','education',1,'student studying desk books'),
('w_education_A1_04','learn','/lɜːrn/','verb','배우다','To gain knowledge or skill by studying or being taught.','I want to {learn} English every day.','저는 매일 영어를 배우고 싶어요.','learn','A1','education',1,'person learning studying book'),
('w_education_A1_05','book','/bʊk/','noun','책','A set of written or printed pages, usually bound with covers.','I read a {book} before bed.','저는 자기 전에 책을 읽어요.','book','A1','education',1,'open book reading library'),
('w_education_A1_06','class','/klɑːs/','noun','수업','A group of students taught together; a lesson.','English {class} starts at nine.','영어 수업은 9시에 시작해요.','class','A1','education',1,'classroom students lesson teacher'),
('w_education_A1_07','study','/ˈstʌdi/','verb','공부하다','To spend time learning about a subject.','I {study} for two hours every evening.','저는 매일 저녁 두 시간씩 공부해요.','study','A1','education',1,'studying desk lamp notebook'),
('w_education_A1_08','test','/test/','noun','시험','An assessment to measure knowledge or ability.','We have a {test} on Friday.','금요일에 시험이 있어요.','test','A1','education',1,'exam paper pencil test'),
('w_education_A1_09','write','/raɪt/','verb','쓰다','To mark letters or words on paper or a surface.','Please {write} your name here.','여기에 이름을 써 주세요.','write','A1','education',1,'writing pen paper notebook'),
('w_education_A1_10','read','/riːd/','verb','읽다','To look at and understand written words.','Can you {read} this sentence?','이 문장을 읽을 수 있어요?','read','A1','education',1,'reading book open pages'),
('w_education_A1_11','pencil','/ˈpensəl/','noun','연필','A thin stick used for writing or drawing.','I need a {pencil} to write.','쓰려면 연필이 필요해요.','pencil','A1','education',2,'pencil desk writing stationery'),
('w_education_A1_12','pen','/pen/','noun','펜','A device used for writing with ink.','Can I borrow your {pen}?','펜 빌려도 될까요?','pen','A1','education',2,'pen writing ink stationery'),
('w_education_A1_13','question','/ˈkwestʃən/','noun','질문','A sentence asking for information.','Do you have a {question}?','질문이 있으세요?','question','A1','education',1,'person raising hand question classroom'),
('w_education_A1_14','answer','/ˈɑːnsər/','noun','답','A response to a question.','What is the {answer} to this?','이것의 답이 뭐예요?','answer','A1','education',1,'answer sheet test solution'),
('w_education_A1_15','number','/ˈnʌmbər/','noun','숫자','A value used for counting or measuring.','Write the {number} next to each word.','각 단어 옆에 숫자를 쓰세요.','number','A1','education',2,'numbers math counting board'),
('w_education_A1_16','letter','/ˈletər/','noun','글자, 편지','A character representing a sound; also a written message.','The first {letter} of the alphabet is A.','알파벳의 첫 번째 글자는 A예요.','letter','A1','education',2,'alphabet letters writing board'),
('w_education_A1_17','word','/wɜːrd/','noun','단어','A single unit of language with meaning.','What does this {word} mean?','이 단어는 무슨 뜻이에요?','word','A1','education',1,'word dictionary vocabulary language'),
('w_education_A1_18','sentence','/ˈsentəns/','noun','문장','A set of words expressing a complete thought.','Please read the {sentence} aloud.','문장을 소리 내어 읽어 주세요.','sentence','A1','education',1,'sentence writing grammar text'),
('w_education_A1_19','listen','/ˈlɪsən/','verb','듣다','To pay attention to sounds.','Please {listen} carefully.','주의해서 들어주세요.','listen','A1','education',1,'listening headphones audio learning'),
('w_education_A1_20','speak','/spiːk/','verb','말하다','To say words; to communicate verbally.','Don''t be afraid to {speak} English.','영어로 말하는 것을 두려워하지 마세요.','speak','A1','education',1,'speaking conversation talking people'),
('w_education_A1_21','understand','/ˌʌndərˈstænd/','verb','이해하다','To know the meaning of something.','Do you {understand} the rule?','규칙을 이해하셨어요?','understand','A1','education',1,'person thinking understanding light bulb'),
('w_education_A1_22','homework','/ˈhoʊmwɜːrk/','noun','숙제','School work done at home.','I do my {homework} after dinner.','저는 저녁 식사 후에 숙제를 해요.','homework','A1','education',1,'homework books desk studying home'),
('w_education_A1_23','classroom','/ˈklɑːsruːm/','noun','교실','A room used for lessons.','The {classroom} has thirty desks.','교실에 책상이 30개 있어요.','classroom','A1','education',2,'classroom desks chairs teacher board'),
('w_education_A1_24','lesson','/ˈlesən/','noun','수업, 레슨','A period of learning or teaching.','Today''s {lesson} is about animals.','오늘 수업은 동물에 관한 거예요.','lesson','A1','education',1,'lesson classroom teaching board'),
('w_education_A1_25','paper','/ˈpeɪpər/','noun','종이','A thin flat material used for writing.','Write your name on the {paper}.','종이에 이름을 쓰세요.','paper','A1','education',2,'paper writing desk student'),
('w_education_A1_26','correct','/kəˈrekt/','adjective','맞는, 옳은','Free from mistakes; right.','That is the {correct} answer.','그것이 맞는 답이에요.','correct','A1','education',1,'correct answer checkmark right'),
('w_education_A1_27','wrong','/rɒŋ/','adjective','틀린','Not correct; mistaken.','Sorry, that''s {wrong} — try again.','죄송하지만 틀렸어요. 다시 해보세요.','wrong','A1','education',1,'wrong answer incorrect mistake'),
('w_education_A1_28','spell','/spel/','verb','철자를 쓰다','To write the letters of a word in the correct order.','How do you {spell} your name?','이름 철자가 어떻게 되세요?','spell','A1','education',2,'spelling letters alphabet words'),
('w_education_A1_29','repeat','/rɪˈpiːt/','verb','반복하다','To say or do something again.','Please {repeat} after me.','저를 따라 다시 말해 주세요.','repeat','A1','education',2,'repeat practice drilling language'),
('w_education_A1_30','open','/ˈoʊpən/','verb','열다, 펼치다','To move so as to allow access; to turn to a page.','Please {open} your books to page ten.','책 10페이지를 펼쳐 주세요.','open','A1','education',2,'open book page textbook'),
('w_education_A1_31','close','/kloʊz/','verb','닫다','To move so as to cover an opening.','Please {close} your notebooks.','노트를 닫아 주세요.','close','A1','education',2,'close book notebook desk'),
('w_education_A1_32','name','/neɪm/','noun','이름','A word used to identify a person or thing.','What is your {name}?','이름이 어떻게 되세요?','name','A1','education',2,'name tag label identity'),
('w_education_A1_33','grade','/ɡreɪd/','noun','학년, 성적','A class level in school; a mark showing quality of work.','I am in the third {grade}.','저는 3학년이에요.','grade','A1','education',1,'grade school level report card'),
('w_education_A1_34','easy','/ˈiːzi/','adjective','쉬운','Not difficult; achieved without much effort.','This exercise is very {easy}.','이 연습 문제는 매우 쉬워요.','easy','A1','education',2,'easy simple exercise learning'),
('w_education_A1_35','difficult','/ˈdɪfɪkəlt/','adjective','어려운','Needing much effort or skill.','The grammar rule is {difficult}.','그 문법 규칙은 어려워요.','difficult','A1','education',2,'difficult challenge hard studying');

-- ══════════════════════════════════════
-- WORDS — A2 (35)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_education_A2_01','homework','/ˈhoʊmwɜːrk/','noun','숙제','Schoolwork assigned to be done at home.','Did you finish your {homework} last night?','어제 숙제 다 했어요?','homework','A2','education',1,'homework books desk studying'),
('w_education_A2_02','exam','/ɪɡˈzæm/','noun','시험','A formal test of knowledge or ability.','The final {exam} is next week.','기말 시험이 다음 주예요.','exam','A2','education',1,'exam test paper student writing'),
('w_education_A2_03','grade','/ɡreɪd/','noun','성적, 점수','A mark indicating quality of schoolwork.','She got a good {grade} on the test.','그녀는 시험에서 좋은 성적을 받았어요.','grade','A2','education',1,'grade score report card marks'),
('w_education_A2_04','subject','/ˈsʌbdʒɪkt/','noun','과목','A branch of knowledge studied in school.','My favorite {subject} is English.','제가 가장 좋아하는 과목은 영어예요.','subject','A2','education',1,'school subjects textbooks curriculum'),
('w_education_A2_05','university','/ˌjuːnɪˈvɜːrsɪti/','noun','대학교','An institution of higher education and research.','She wants to go to {university} next year.','그녀는 내년에 대학교에 가고 싶어해요.','university','A2','education',1,'university campus building students'),
('w_education_A2_06','library','/ˈlaɪbreri/','noun','도서관','A place where books and other materials are available to borrow.','I study at the {library} every weekend.','저는 매주 주말 도서관에서 공부해요.','library','A2','education',1,'library books shelves studying'),
('w_education_A2_07','lecture','/ˈlektʃər/','noun','강의','A talk given to a group, especially at a university.','The {lecture} starts at ten o''clock.','강의는 10시에 시작해요.','lecture','A2','education',1,'lecture hall professor students university'),
('w_education_A2_08','notes','/noʊts/','noun','필기, 노트','Written records of what was said or learned.','I always take {notes} in class.','저는 항상 수업에서 필기를 해요.','notes','A2','education',1,'notes notebook writing class'),
('w_education_A2_09','pass','/pɑːs/','verb','합격하다, 통과하다','To succeed in an exam or test.','I hope to {pass} the exam.','시험에 합격하면 좋겠어요.','pass','A2','education',1,'pass exam success celebration'),
('w_education_A2_10','fail','/feɪl/','verb','불합격하다, 실패하다','To not succeed in an exam or test.','She didn''t want to {fail} the test.','그녀는 시험에서 떨어지고 싶지 않았어요.','fail','A2','education',1,'fail exam disappointed student'),
('w_education_A2_11','practice','/ˈpræktɪs/','verb','연습하다','To repeat an activity in order to improve.','You need to {practice} speaking every day.','매일 말하기 연습을 해야 해요.','practice','A2','education',1,'practice sports skill learning repetition'),
('w_education_A2_12','review','/rɪˈvjuː/','verb','복습하다','To look at something again to check or improve it.','Let''s {review} what we learned last week.','지난주에 배운 것을 복습해 볼게요.','review','A2','education',1,'review notes studying textbook'),
('w_education_A2_13','dictionary','/ˈdɪkʃəneri/','noun','사전','A book or program listing words with their meanings.','I use a {dictionary} to look up new words.','저는 새 단어를 찾을 때 사전을 사용해요.','dictionary','A2','education',2,'dictionary book reference vocabulary'),
('w_education_A2_14','vocabulary','/voʊˈkæbjʊleri/','noun','어휘','The body of words used in a language or subject.','Building {vocabulary} takes time.','어휘를 쌓는 데는 시간이 걸려요.','vocabulary','A2','education',1,'vocabulary words language learning'),
('w_education_A2_15','grammar','/ˈɡræmər/','noun','문법','The rules governing the use of a language.','English {grammar} can be tricky.','영어 문법은 까다로울 수 있어요.','grammar','A2','education',1,'grammar rules language textbook'),
('w_education_A2_16','score','/skɔːr/','noun','점수','The number of points or marks received.','What {score} did you get on the test?','시험에서 몇 점 받았어요?','score','A2','education',1,'score test results marks paper'),
('w_education_A2_17','report card','/ˈrɪpɔːrt kɑːrd/','noun','성적표','A document showing a student''s grades.','My parents checked my {report card}.','부모님이 제 성적표를 확인하셨어요.','report card','A2','education',2,'report card grades school marks'),
('w_education_A2_18','semester','/sɪˈmestər/','noun','학기','Half of the academic year.','The spring {semester} begins in March.','봄 학기는 3월에 시작해요.','semester','A2','education',1,'semester school year calendar academic'),
('w_education_A2_19','club','/klʌb/','noun','동아리, 클럽','A group that meets regularly for a shared interest.','I joined the English speaking {club}.','저는 영어 회화 동아리에 가입했어요.','club','A2','education',2,'club activity group students school'),
('w_education_A2_20','project','/ˈprɒdʒekt/','noun','과제, 프로젝트','A planned piece of work, often done over time.','We are doing a group {project} this week.','이번 주에 모둠 과제를 하고 있어요.','project','A2','education',1,'project group work students desk'),
('w_education_A2_21','quiz','/kwɪz/','noun','쪽지 시험','A short test to check knowledge.','There is a {quiz} at the end of class.','수업 끝에 쪽지 시험이 있어요.','quiz','A2','education',2,'quiz test paper classroom student'),
('w_education_A2_22','absent','/ˈæbsənt/','adjective','결석한','Not present at school or class.','He was {absent} from class yesterday.','그는 어제 수업에 결석했어요.','absent','A2','education',2,'absent empty seat classroom'),
('w_education_A2_23','present','/ˈprezənt/','adjective','출석한','At school or class; here.','All students are {present} today.','오늘 모든 학생이 출석했어요.','present','A2','education',2,'present attendance classroom students'),
('w_education_A2_24','explain','/ɪkˈspleɪn/','verb','설명하다','To make something clear or understandable.','Can you {explain} the rule again?','규칙을 다시 설명해 주실 수 있어요?','explain','A2','education',1,'explain teacher whiteboard students'),
('w_education_A2_25','example','/ɪɡˈzɑːmpəl/','noun','예, 예시','Something that illustrates a rule or point.','Give me an {example} of that word.','그 단어의 예를 들어 주세요.','example','A2','education',1,'example illustration board teaching'),
('w_education_A2_26','textbook','/ˈtekstbʊk/','noun','교과서','A book used in school for a particular subject.','Open your {textbook} to chapter three.','교과서 3장을 펼쳐 주세요.','textbook','A2','education',1,'textbook open book student desk'),
('w_education_A2_27','worksheet','/ˈwɜːrkʃiːt/','noun','학습지','A printed sheet with exercises for students.','Fill in the {worksheet} before class.','수업 전에 학습지를 작성해 주세요.','worksheet','A2','education',2,'worksheet paper exercises student'),
('w_education_A2_28','tutor','/ˈtjuːtər/','noun','개인 교사, 튜터','A private teacher who teaches one student or a small group.','My {tutor} helps me with math.','튜터가 수학을 도와줘요.','tutor','A2','education',2,'tutor teaching student one on one'),
('w_education_A2_29','certificate','/sərˈtɪfɪkɪt/','noun','자격증, 수료증','An official document proving an achievement.','I got a {certificate} for completing the course.','과정을 이수하고 수료증을 받았어요.','certificate','A2','education',2,'certificate document achievement award'),
('w_education_A2_30','enroll','/ɪnˈroʊl/','verb','등록하다','To register for a course or school.','I want to {enroll} in an English class.','영어 수업에 등록하고 싶어요.','enroll','A2','education',2,'enroll registration school form'),
('w_education_A2_31','attend','/əˈtend/','verb','참석하다, 다니다','To go to or be present at a place regularly.','She {attends} school every day.','그녀는 매일 학교에 다녀요.','attend','A2','education',1,'attend school class students'),
('w_education_A2_32','break','/breɪk/','noun','휴식 시간','A short period of rest during school.','We have a {break} at eleven.','11시에 쉬는 시간이 있어요.','break','A2','education',2,'break recess students playground'),
('w_education_A2_33','schedule','/ˈskedʒuːl/','noun','시간표, 일정','A timetable of classes or events.','Check your {schedule} for tomorrow.','내일 시간표를 확인해 주세요.','schedule','A2','education',2,'schedule timetable planner school'),
('w_education_A2_34','classmate','/ˈklɑːsmeɪt/','noun','반 친구','A member of the same class at school.','My {classmate} helped me with the homework.','반 친구가 숙제를 도와줬어요.','classmate','A2','education',2,'classmates students friends school'),
('w_education_A2_35','knowledge','/ˈnɒlɪdʒ/','noun','지식','Facts and information gained through learning.','Reading builds your {knowledge}.','독서는 지식을 쌓아줘요.','knowledge','A2','education',1,'knowledge books learning brain');

-- ══════════════════════════════════════
-- WORDS — B1 (35)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_education_B1_01','curriculum','/kəˈrɪkjʊləm/','noun','교육 과정','The subjects and content making up a course of study.','The new {curriculum} focuses on critical thinking.','새 교육 과정은 비판적 사고에 초점을 맞춰요.','curriculum','B1','education',1,'curriculum education plan subjects'),
('w_education_B1_02','semester','/sɪˈmestər/','noun','학기','A half-year term in an academic year.','We have exams at the end of every {semester}.','매 학기 말에 시험이 있어요.','semester','B1','education',1,'semester academic year university'),
('w_education_B1_03','scholarship','/ˈskɒlərʃɪp/','noun','장학금','Financial aid given to students based on merit or need.','She received a full {scholarship} to study abroad.','그녀는 해외 유학을 위한 전액 장학금을 받았어요.','scholarship','B1','education',1,'scholarship award money student education'),
('w_education_B1_04','degree','/dɪˈɡriː/','noun','학위','An academic award given by a university.','He earned his {degree} in computer science.','그는 컴퓨터 공학 학위를 받았어요.','degree','B1','education',1,'degree diploma graduation university'),
('w_education_B1_05','research','/rɪˈsɜːrtʃ/','noun','연구','Systematic investigation to discover new knowledge.','She is doing {research} on climate change.','그녀는 기후 변화에 관한 연구를 하고 있어요.','research','B1','education',1,'research laboratory studying data'),
('w_education_B1_06','thesis','/ˈθiːsɪs/','noun','논문(학사/석사)','A long written piece of research for a degree.','He is writing his {thesis} on urban development.','그는 도시 개발에 관한 논문을 쓰고 있어요.','thesis','B1','education',1,'thesis paper writing university research'),
('w_education_B1_07','assignment','/əˈsaɪnmənt/','noun','과제','A task given to students to complete.','The {assignment} is due next Monday.','과제 제출 기한은 다음 주 월요일이에요.','assignment','B1','education',1,'assignment task homework deadline'),
('w_education_B1_08','professor','/prəˈfesər/','noun','교수','A senior university teacher and researcher.','The {professor} gave an inspiring lecture.','교수님이 감동적인 강의를 해주셨어요.','professor','B1','education',1,'professor university lecture teaching'),
('w_education_B1_09','tuition','/tjuːˈɪʃən/','noun','수업료, 등록금','Fees charged for teaching at a school or university.','{Tuition} at private schools can be expensive.','사립학교의 수업료는 비쌀 수 있어요.','tuition','B1','education',1,'tuition fees university money education'),
('w_education_B1_10','campus','/ˈkæmpəs/','noun','캠퍼스','The grounds and buildings of a university.','I walked across {campus} to get to the library.','도서관에 가기 위해 캠퍼스를 가로질러 걸었어요.','campus','B1','education',1,'campus university buildings grounds'),
('w_education_B1_11','graduation','/ˌɡrædʒuˈeɪʃən/','noun','졸업','The ceremony at which degrees are awarded.','Her {graduation} ceremony is in June.','그녀의 졸업식은 6월이에요.','graduation','B1','education',1,'graduation ceremony diploma cap gown'),
('w_education_B1_12','major','/ˈmeɪdʒər/','noun','전공','The main subject studied at university.','His {major} is economics.','그의 전공은 경제학이에요.','major','B1','education',1,'major university subject study'),
('w_education_B1_13','minor','/ˈmaɪnər/','noun','부전공','A secondary subject studied alongside the major.','She chose linguistics as her {minor}.','그녀는 언어학을 부전공으로 선택했어요.','minor','B1','education',2,'minor secondary subject university'),
('w_education_B1_14','deadline','/ˈdedlaɪn/','noun','마감 기한','The last date by which an assignment must be submitted.','The {deadline} for the paper is Thursday.','논문 마감 기한은 목요일이에요.','deadline','B1','education',1,'deadline calendar due date assignment'),
('w_education_B1_15','presentation','/ˌprezənˈteɪʃən/','noun','발표','A talk or demonstration to an audience.','I have to give a {presentation} next week.','다음 주에 발표를 해야 해요.','presentation','B1','education',1,'presentation public speaking audience'),
('w_education_B1_16','essay','/ˈeseɪ/','noun','에세이, 작문','A piece of writing on a particular topic.','The {essay} should be at least five hundred words.','에세이는 최소 500단어 이상이어야 해요.','essay','B1','education',1,'essay writing paper academic'),
('w_education_B1_17','outline','/ˈaʊtlaɪn/','noun','개요','A plan or summary of the main points.','Write an {outline} before you start the essay.','에세이를 시작하기 전에 개요를 작성하세요.','outline','B1','education',2,'outline plan structure writing'),
('w_education_B1_18','debate','/dɪˈbeɪt/','noun','토론, 논쟁','A formal discussion on a topic with opposing arguments.','We had a class {debate} about technology.','기술에 대한 수업 토론을 했어요.','debate','B1','education',1,'debate discussion argument classroom'),
('w_education_B1_19','seminar','/ˈsemɪnɑːr/','noun','세미나','A small group session for discussion and study.','The professor runs a weekly {seminar}.','교수님이 매주 세미나를 진행해요.','seminar','B1','education',2,'seminar group discussion university'),
('w_education_B1_20','internship','/ˈɪntɜːrnʃɪp/','noun','인턴십','A temporary work experience placement for students.','She completed an {internship} at a media company.','그녀는 미디어 회사에서 인턴십을 마쳤어요.','internship','B1','education',2,'internship work experience office student'),
('w_education_B1_21','elective','/ɪˈlektɪv/','noun','선택 과목','A course students can choose to take.','I picked photography as my {elective}.','저는 선택 과목으로 사진을 골랐어요.','elective','B1','education',2,'elective course choice subject'),
('w_education_B1_22','mandatory','/ˈmændətɔːri/','adjective','필수적인','Required; compulsory.','Attendance is {mandatory} for this course.','이 수업은 출석이 필수예요.','mandatory','B1','education',1,'mandatory required rules attendance'),
('w_education_B1_23','extracurricular','/ˌekstrəkəˈrɪkjʊlər/','adjective','과외 활동의','Outside of the regular curriculum.','{extracurricular} activities improve teamwork.','과외 활동은 팀워크를 향상시켜요.','extracurricular','B1','education',2,'extracurricular sports clubs school activities'),
('w_education_B1_24','academic','/ˌækəˈdemɪk/','adjective','학문적인','Relating to education and scholarly activities.','Her {academic} record is excellent.','그녀의 학업 성적은 우수해요.','academic','B1','education',1,'academic university study records'),
('w_education_B1_25','feedback','/ˈfiːdbæk/','noun','피드백','Information given to help improve performance.','The teacher gave useful {feedback} on my essay.','선생님이 에세이에 유용한 피드백을 주셨어요.','feedback','B1','education',1,'feedback review comments paper'),
('w_education_B1_26','assessment','/əˈsesmənt/','noun','평가','The process of evaluating performance or knowledge.','The {assessment} includes both written and oral parts.','평가는 필기와 구술 두 부분을 포함해요.','assessment','B1','education',1,'assessment evaluation test grade'),
('w_education_B1_27','credit','/ˈkredɪt/','noun','학점','A unit used to measure the completion of a course.','This course is worth three {credits}.','이 수업은 3학점이에요.','credit','B1','education',1,'credit academic hours university'),
('w_education_B1_28','apply','/əˈplaɪ/','verb','지원하다, 신청하다','To formally request something such as a place at university.','She plans to {apply} to ten universities.','그녀는 열 개의 대학교에 지원할 계획이에요.','apply','B1','education',1,'apply application form university'),
('w_education_B1_29','scholarship','/ˈskɒlərʃɪp/','noun','장학금','Money given to fund a student''s education.','He applied for a merit-based {scholarship}.','그는 성적 우수 장학금을 신청했어요.','scholarship','B1','education',1,'scholarship money award student'),
('w_education_B1_30','qualify','/ˈkwɒlɪfaɪ/','verb','자격을 갖추다','To meet the necessary conditions for something.','You must pass an exam to {qualify}.','자격을 갖추려면 시험에 합격해야 해요.','qualify','B1','education',2,'qualify exam certificate credential'),
('w_education_B1_31','submit','/səbˈmɪt/','verb','제출하다','To hand in a piece of work for assessment.','Please {submit} your essay by midnight.','에세이를 자정까지 제출해 주세요.','submit','B1','education',1,'submit paper upload assignment deadline'),
('w_education_B1_32','revise','/rɪˈvaɪz/','verb','수정하다, 복습하다','To change or improve written work; to study for an exam.','I need to {revise} my essay before submitting it.','제출 전에 에세이를 수정해야 해요.','revise','B1','education',1,'revise edit paper studying'),
('w_education_B1_33','concentrate','/ˈkɒnsəntreɪt/','verb','집중하다','To focus your thoughts and attention.','It''s hard to {concentrate} when it''s noisy.','시끄러울 때 집중하기 어려워요.','concentrate','B1','education',1,'concentrate focus study quiet'),
('w_education_B1_34','comprehension','/ˌkɒmprɪˈhenʃən/','noun','이해력, 독해','The ability to understand written or spoken language.','The exam includes a {comprehension} passage.','시험에 독해 지문이 포함돼요.','comprehension','B1','education',1,'comprehension reading text understanding'),
('w_education_B1_35','plagiarism','/ˈpleɪdʒərɪzəm/','noun','표절','Using someone else''s work or ideas without permission.','{Plagiarism} can result in failing the course.','표절은 수업 낙제로 이어질 수 있어요.','plagiarism','B1','education',1,'plagiarism copying academic dishonesty');

-- ══════════════════════════════════════
-- WORDS — B2 (35)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_education_B2_01','methodology','/ˌmeθəˈdɒlədʒi/','noun','방법론','A system of methods used in a particular field of study.','The research used a qualitative {methodology}.','연구는 질적 방법론을 사용했어요.','methodology','B2','education',1,'methodology research systematic approach'),
('w_education_B2_02','hypothesis','/haɪˈpɒθɪsɪs/','noun','가설','A proposed explanation made on the basis of limited evidence.','The scientist tested her {hypothesis} carefully.','과학자는 가설을 신중하게 검증했어요.','hypothesis','B2','education',1,'hypothesis experiment science research'),
('w_education_B2_03','peer review','/pɪər rɪˈvjuː/','noun','동료 검토','Evaluation of work by others in the same field.','The article passed {peer review} before publication.','기사는 출판 전에 동료 검토를 통과했어요.','peer review','B2','education',1,'peer review academic journal evaluation'),
('w_education_B2_04','dissertation','/ˌdɪsərˈteɪʃən/','noun','(박사) 학위 논문','A long written work submitted for a doctoral degree.','She spent three years writing her {dissertation}.','그녀는 학위 논문을 쓰는 데 3년을 보냈어요.','dissertation','B2','education',1,'dissertation thesis research university'),
('w_education_B2_05','citation','/saɪˈteɪʃən/','noun','인용','A reference to a source in academic writing.','Every claim needs a {citation} in academic writing.','학술 글쓰기에서는 모든 주장에 인용이 필요해요.','citation','B2','education',1,'citation reference academic paper source'),
('w_education_B2_06','abstract','/ˈæbstrækt/','noun','초록, 요약','A short summary of a research paper.','Read the {abstract} before the full paper.','전체 논문 읽기 전에 초록을 읽으세요.','abstract','B2','education',1,'abstract summary research paper academic'),
('w_education_B2_07','empirical','/ɪmˈpɪrɪkəl/','adjective','경험적인, 실증적인','Based on observation or experiment rather than theory.','The study provides {empirical} evidence.','이 연구는 실증적 증거를 제공해요.','empirical','B2','education',1,'empirical data evidence experiment research'),
('w_education_B2_08','academic','/ˌækəˈdemɪk/','noun','학자','A person who works as a researcher or teacher at a university.','Several {academics} attended the conference.','여러 학자가 학회에 참석했어요.','academic','B2','education',1,'academic professor university scholar'),
('w_education_B2_09','faculty','/ˈfækəlti/','noun','교수진','The teaching staff of a university.','The {faculty} met to discuss the new syllabus.','교수진이 새 강의 계획서를 논의하기 위해 모였어요.','faculty','B2','education',1,'faculty staff university professors meeting'),
('w_education_B2_10','postgraduate','/ˌpoʊstˈɡrædʒuɪt/','noun','대학원생','A student doing advanced study after their first degree.','She is a {postgraduate} student in linguistics.','그녀는 언어학 대학원생이에요.','postgraduate','B2','education',1,'postgraduate university graduate student research'),
('w_education_B2_11','semiotics','/ˌsiːmiˈɒtɪks/','noun','기호학','The study of signs and symbols and their use or interpretation.','Her course introduces {semiotics} and media.','그녀의 강의는 기호학과 미디어를 소개해요.','semiotics','B2','education',2,'semiotics signs symbols language meaning'),
('w_education_B2_12','discourse','/ˈdɪskɔːrs/','noun','담론, 담화','Written or spoken communication and its social context.','Academic {discourse} requires formal language.','학술 담론에는 격식체 언어가 필요해요.','discourse','B2','education',2,'discourse communication language academic'),
('w_education_B2_13','inference','/ˈɪnfərəns/','noun','추론','A conclusion reached on the basis of evidence and reasoning.','Drawing {inference} from data is a key skill.','데이터에서 추론하는 것은 핵심 능력이에요.','inference','B2','education',1,'inference reasoning logic conclusion'),
('w_education_B2_14','synthesis','/ˈsɪnθɪsɪs/','noun','종합, 통합','The combination of elements to form a whole.','The essay requires a {synthesis} of various sources.','이 에세이는 다양한 자료의 통합을 요구해요.','synthesis','B2','education',1,'synthesis combine integrate research'),
('w_education_B2_15','critique','/krɪˈtiːk/','noun','비평, 비판적 분석','A detailed analysis and assessment of something.','Write a {critique} of the article for next week.','다음 주까지 기사 비평을 작성해 주세요.','critique','B2','education',1,'critique analysis review academic'),
('w_education_B2_16','framework','/ˈfreɪmwɜːrk/','noun','틀, 체계','A basic structure underlying a system or concept.','The {framework} guides the analysis.','이 틀이 분석을 이끌어요.','framework','B2','education',1,'framework structure system analysis'),
('w_education_B2_17','variable','/ˈveəriəbəl/','noun','변수','An element that may change in an experiment.','The study controls for several {variables}.','이 연구는 여러 변수를 통제해요.','variable','B2','education',1,'variable experiment research data'),
('w_education_B2_18','quantitative','/ˈkwɒntɪtətɪv/','adjective','양적인','Relating to, measuring, or measured by quantity.','A {quantitative} study uses numerical data.','양적 연구는 수치 데이터를 사용해요.','quantitative','B2','education',1,'quantitative data numbers research statistics'),
('w_education_B2_19','qualitative','/ˈkwɒlɪtətɪv/','adjective','질적인','Relating to or measured by quality rather than quantity.','The {qualitative} approach explores meanings.','질적 접근은 의미를 탐구해요.','qualitative','B2','education',1,'qualitative interview observation research'),
('w_education_B2_20','rhetoric','/ˈretərɪk/','noun','수사학, 수사법','The art of persuasive speaking or writing.','Strong {rhetoric} can win an argument.','강한 수사법은 논쟁을 이길 수 있어요.','rhetoric','B2','education',2,'rhetoric persuasion speech argument'),
('w_education_B2_21','annotate','/ˈænəteɪt/','verb','주석을 달다','To add notes or comments to a text.','Students {annotate} their texts during reading.','학생들은 읽으면서 텍스트에 주석을 달아요.','annotate','B2','education',2,'annotate notes margin text book'),
('w_education_B2_22','rationale','/ˌræʃəˈnɑːl/','noun','근거, 이유','The fundamental reason or basis for something.','Explain the {rationale} behind your argument.','주장의 근거를 설명해 주세요.','rationale','B2','education',2,'rationale reason basis argument'),
('w_education_B2_23','peer','/pɪər/','noun','동료, 동급생','A person of the same age or status.','Discuss your ideas with your {peers}.','동료들과 아이디어를 토론해 보세요.','peer','B2','education',1,'peer colleagues students group discussion'),
('w_education_B2_24','collaborate','/kəˈlæbəreɪt/','verb','협력하다, 공동 연구하다','To work jointly with others on a project.','Students {collaborate} on group assignments.','학생들은 그룹 과제를 위해 협력해요.','collaborate','B2','education',1,'collaborate teamwork group project students'),
('w_education_B2_25','curriculum vitae','/ˌkɜːrɪkjʊləm ˈviːtaɪ/','noun','이력서 (CV)','A written overview of a person''s qualifications and experience.','Submit your {curriculum vitae} with the application.','지원서와 함께 이력서를 제출해 주세요.','curriculum vitae','B2','education',2,'CV resume qualifications academic'),
('w_education_B2_26','bibliography','/ˌbɪbliˈɒɡrəfi/','noun','참고 문헌 목록','A list of books and sources used in a research paper.','Include a full {bibliography} at the end.','마지막에 전체 참고 문헌 목록을 포함하세요.','bibliography','B2','education',1,'bibliography references sources academic paper'),
('w_education_B2_27','syllabus','/ˈsɪləbəs/','noun','강의 계획서','An outline of the topics covered in a course.','Review the {syllabus} on the first day.','첫날 강의 계획서를 검토하세요.','syllabus','B2','education',1,'syllabus course outline plan university'),
('w_education_B2_28','tenure','/ˈtenjər/','noun','종신 재직권','The permanent status granted to a university professor.','She was granted {tenure} last year.','그녀는 작년에 종신 재직권을 받았어요.','tenure','B2','education',2,'tenure professor university permanent position'),
('w_education_B2_29','accreditation','/əˌkredɪˈteɪʃən/','noun','인가, 인증','Official recognition that an institution meets standards.','The university received full {accreditation}.','대학교는 완전한 인증을 받았어요.','accreditation','B2','education',2,'accreditation certification standard quality'),
('w_education_B2_30','transcript','/ˈtrænskrɪpt/','noun','성적 증명서','An official record of a student''s academic performance.','Send your official {transcript} with the application.','공식 성적 증명서를 지원서와 함께 보내주세요.','transcript','B2','education',2,'transcript academic record certificate'),
('w_education_B2_31','grant','/ɡrɑːnt/','noun','연구비, 보조금','Money given for a specific purpose such as research.','She received a research {grant} from the government.','그녀는 정부로부터 연구비를 받았어요.','grant','B2','education',1,'grant funding research money academic'),
('w_education_B2_32','cohort','/ˈkoʊhɔːrt/','noun','(동기) 집단','A group of students who begin study at the same time.','The 2024 {cohort} has fifty students.','2024년 동기는 50명이에요.','cohort','B2','education',2,'cohort group students year class'),
('w_education_B2_33','interdisciplinary','/ˌɪntərdɪˈsɪplɪneri/','adjective','학제 간의','Involving two or more academic disciplines.','The course takes an {interdisciplinary} approach.','이 강의는 학제 간 접근법을 취해요.','interdisciplinary','B2','education',2,'interdisciplinary cross-subject research academic'),
('w_education_B2_34','prerequisite','/ˌpriːˈrekwɪzɪt/','noun','선수 과목, 전제 조건','A required course or condition before another can be taken.','Statistics is a {prerequisite} for this module.','통계학은 이 모듈의 선수 과목이에요.','prerequisite','B2','education',2,'prerequisite requirement course condition'),
('w_education_B2_35','pedagogy','/ˈpedəɡɒdʒi/','noun','교수법','The method and practice of teaching.','Modern {pedagogy} emphasizes active learning.','현대 교수법은 능동적 학습을 강조해요.','pedagogy','B2','education',1,'pedagogy teaching method education practice');

-- ══════════════════════════════════════
-- WORDS — C1 (35)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_education_C1_01','epistemology','/ɪˌpɪstɪˈmɒlədʒi/','noun','인식론','The branch of philosophy concerned with the nature and scope of knowledge.','Her research draws on {epistemology} and cognitive science.','그녀의 연구는 인식론과 인지 과학을 바탕으로 해요.','epistemology','C1','education',1,'epistemology philosophy knowledge mind'),
('w_education_C1_02','pedagogy','/ˈpedəɡɒdʒi/','noun','교육학, 교수법','The art and science of teaching.','Critical {pedagogy} encourages students to question assumptions.','비판적 교수법은 학생들이 가정을 의심하도록 독려해요.','pedagogy','C1','education',1,'pedagogy teaching method classroom'),
('w_education_C1_03','paradigm','/ˈpærədaɪm/','noun','패러다임','A typical example or pattern; a framework of ideas.','Kuhn described scientific revolutions as {paradigm} shifts.','쿤은 과학 혁명을 패러다임 전환으로 설명했어요.','paradigm','C1','education',1,'paradigm shift concept framework science'),
('w_education_C1_04','dialectic','/ˌdaɪəˈlektɪk/','noun','변증법','A method of logical argument through discussion.','Hegel''s {dialectic} moves through thesis, antithesis, and synthesis.','헤겔의 변증법은 정, 반, 합으로 나아가요.','dialectic','C1','education',1,'dialectic argument logic philosophy'),
('w_education_C1_05','hermeneutics','/ˌhɜːrmɪˈnjuːtɪks/','noun','해석학','The theory and methodology of text interpretation.','{Hermeneutics} informs how we read ancient texts.','해석학은 우리가 고대 문헌을 읽는 방식에 영향을 줘요.','hermeneutics','C1','education',1,'hermeneutics interpretation text meaning'),
('w_education_C1_06','constructivism','/kənˈstrʌktɪvɪzəm/','noun','구성주의','The theory that learners actively construct knowledge.','{Constructivism} supports project-based learning.','구성주의는 프로젝트 기반 학습을 지지해요.','constructivism','C1','education',1,'constructivism learning building knowledge'),
('w_education_C1_07','positivism','/ˈpɒzɪtɪvɪzəm/','noun','실증주의','The philosophical view that knowledge comes from empirical evidence.','{Positivism} dominates natural science research.','실증주의는 자연 과학 연구를 지배해요.','positivism','C1','education',1,'positivism evidence science philosophy research'),
('w_education_C1_08','ontology','/ɒnˈtɒlədʒi/','noun','존재론','The branch of philosophy dealing with the nature of being.','The study''s {ontology} assumes social reality is constructed.','이 연구의 존재론은 사회 현실이 구성된다고 가정해요.','ontology','C1','education',1,'ontology being existence philosophy'),
('w_education_C1_09','axiom','/ˈæksiəm/','noun','공리, 자명한 이치','A statement accepted as true without proof.','"All men are mortal" is a classic {axiom}.','"모든 인간은 죽는다"는 고전적인 공리예요.','axiom','C1','education',1,'axiom truth principle self-evident'),
('w_education_C1_10','deductive','/dɪˈdʌktɪv/','adjective','연역적인','Moving from general principles to specific conclusions.','The study uses {deductive} reasoning.','이 연구는 연역적 추론을 사용해요.','deductive','C1','education',1,'deductive reasoning logic conclusion'),
('w_education_C1_11','inductive','/ɪnˈdʌktɪv/','adjective','귀납적인','Moving from specific observations to general principles.','{Inductive} logic moves from data to theory.','귀납적 논리는 데이터에서 이론으로 나아가요.','inductive','C1','education',1,'inductive logic data observation'),
('w_education_C1_12','critical thinking','/ˈkrɪtɪkəl ˈθɪŋkɪŋ/','noun','비판적 사고','The ability to analyse and evaluate information carefully.','{Critical thinking} is the cornerstone of good scholarship.','비판적 사고는 좋은 학문의 초석이에요.','critical thinking','C1','education',1,'critical thinking analysis evaluation'),
('w_education_C1_13','heuristic','/hjʊˈrɪstɪk/','adjective','발견적인, 경험에 기반한','Enabling a person to discover or learn by trial and error.','A {heuristic} approach helps students explore solutions.','발견적 접근은 학생들이 해결책을 탐색하도록 도와요.','heuristic','C1','education',2,'heuristic discovery learning problem solving'),
('w_education_C1_14','metacognition','/ˌmetəkɒɡˈnɪʃən/','noun','메타인지','Awareness and understanding of one''s own thought processes.','{Metacognition} helps learners monitor their progress.','메타인지는 학습자가 자신의 발전을 모니터하도록 도와요.','metacognition','C1','education',1,'metacognition thinking awareness learning'),
('w_education_C1_15','scaffolding','/ˈskæfəldɪŋ/','noun','발판식 교수법','Temporary support given to help a learner achieve a goal.','The teacher used {scaffolding} to guide the group.','선생님은 발판식 교수법을 사용해 그룹을 이끌었어요.','scaffolding','C1','education',2,'scaffolding support teaching learning'),
('w_education_C1_16','autonomy','/ɔːˈtɒnəmi/','noun','자율성','The right or condition of self-governance; independence in learning.','Student {autonomy} improves motivation.','학습자 자율성은 동기를 향상시켜요.','autonomy','C1','education',1,'autonomy independence self-directed learning'),
('w_education_C1_17','acculturation','/əˌkʌltʃəˈreɪʃən/','noun','문화 적응','The process of adapting to a different culture.','{Acculturation} affects international students deeply.','문화 적응은 유학생에게 깊은 영향을 미쳐요.','acculturation','C1','education',2,'acculturation culture adaptation students'),
('w_education_C1_18','triangulation','/traɪˌæŋɡjʊˈleɪʃən/','noun','삼각 검증법','Using multiple methods to validate research findings.','The study used {triangulation} to strengthen reliability.','연구는 신뢰성을 높이기 위해 삼각 검증법을 사용했어요.','triangulation','C1','education',2,'triangulation research method validation'),
('w_education_C1_19','reflexivity','/ˌriːflekˈsɪvɪti/','noun','성찰성','The capacity to reflect on one''s own biases in research.','{eflexivity} is essential in qualitative research.','성찰성은 질적 연구에서 필수적이에요.','reflexivity','C1','education',2,'reflexivity reflection bias research'),
('w_education_C1_20','epistemological','/ɪˌpɪstɪməˈlɒdʒɪkəl/','adjective','인식론적인','Relating to the theory of knowledge.','The paper raises {epistemological} questions.','논문은 인식론적 질문을 제기해요.','epistemological','C1','education',2,'epistemological knowledge philosophy'),
('w_education_C1_21','normative','/ˈnɔːrmətɪv/','adjective','규범적인','Relating to a standard or norm of behaviour.','The study takes a {normative} stance.','이 연구는 규범적 입장을 취해요.','normative','C1','education',2,'normative standard norm behaviour'),
('w_education_C1_22','praxis','/ˈpræksɪs/','noun','실천, 프락시스','The process of translating theory into practice.','Freire''s concept of {praxis} unites reflection and action.','프레이리의 프락시스 개념은 성찰과 행동을 결합해요.','praxis','C1','education',1,'praxis practice theory action education'),
('w_education_C1_23','discourse analysis','/ˈdɪskɔːrs əˈnæləsɪs/','noun','담화 분석','The study of language use in texts and social contexts.','{iscourse analysis} reveals power structures in texts.','담화 분석은 텍스트의 권력 구조를 드러내요.','discourse analysis','C1','education',2,'discourse analysis language text power'),
('w_education_C1_24','generalisability','/ˌdʒenrəlaɪzəˈbɪlɪti/','noun','일반화 가능성','The extent to which findings apply beyond the study sample.','Small samples limit {generalisability}.','작은 표본은 일반화 가능성을 제한해요.','generalisability','C1','education',2,'generalisability research sample findings'),
('w_education_C1_25','validity','/vəˈlɪdɪti/','noun','타당성','The degree to which a test or study measures what it claims to.','Ensure the instrument has strong {validity}.','측정 도구가 강한 타당성을 갖추도록 하세요.','validity','C1','education',1,'validity research measurement testing'),
('w_education_C1_26','reliability','/rɪˌlaɪəˈbɪlɪti/','noun','신뢰성','The consistency of a measure or research result.','Test-retest {reliability} was confirmed.','검사-재검사 신뢰성이 확인됐어요.','reliability','C1','education',1,'reliability consistency research measurement'),
('w_education_C1_27','replication','/ˌreplɪˈkeɪʃən/','noun','재현, 복제','Repeating a study to verify its findings.','{eplication} is central to scientific credibility.','재현은 과학적 신뢰성의 핵심이에요.','replication','C1','education',2,'replication experiment science research'),
('w_education_C1_28','peer-reviewed','/ˈpɪər rɪˌvjuːd/','adjective','동료 심사를 거친','Evaluated by experts before publication.','Only cite {peer-reviewed} sources in your paper.','논문에서는 동료 심사를 거친 자료만 인용하세요.','peer-reviewed','C1','education',1,'peer-reviewed journal academic publication'),
('w_education_C1_29','conceptual framework','/kənˈseptʃuəl ˈfreɪmwɜːrk/','noun','개념적 틀','A structured set of concepts used to guide research.','The {conceptual framework} draws on three theories.','개념적 틀은 세 이론을 바탕으로 해요.','conceptual framework','C1','education',1,'conceptual framework theory research guide'),
('w_education_C1_30','literature review','/ˈlɪtrətʃər rɪˈvjuː/','noun','문헌 검토','A survey of existing research on a topic.','The {literature review} identifies gaps in knowledge.','문헌 검토는 지식의 공백을 파악해요.','literature review','C1','education',1,'literature review research academic sources'),
('w_education_C1_31','sampling','/ˈsæmplɪŋ/','noun','표본 추출','The process of selecting individuals for a study.','Random {sampling} reduces selection bias.','무작위 표본 추출은 선택 편향을 줄여요.','sampling','C1','education',2,'sampling research data population'),
('w_education_C1_32','operationalise','/ˌɒpərˈeɪʃənəlaɪz/','verb','조작화하다','To define a concept in measurable terms for research.','You need to {operationalise} the variable.','변수를 조작화해야 해요.','operationalise','C1','education',2,'operationalise measure define research'),
('w_education_C1_33','posit','/ˈpɒzɪt/','verb','가정하다, 상정하다','To put forward as a fact or basis for argument.','The author {posits} that education shapes identity.','저자는 교육이 정체성을 형성한다고 상정해요.','posit','C1','education',2,'posit argue claim academic'),
('w_education_C1_34','substantiate','/səbˈstænʃieɪt/','verb','입증하다, 뒷받침하다','To provide evidence to support a claim.','You must {substantiate} every claim with evidence.','모든 주장을 증거로 뒷받침해야 해요.','substantiate','C1','education',1,'substantiate evidence support proof'),
('w_education_C1_35','nuanced','/ˈnjuːɑːnst/','adjective','미묘한 차이가 있는','Showing subtle distinctions and complexities.','A {nuanced} reading reveals deeper meaning.','미묘한 독해는 더 깊은 의미를 드러내요.','nuanced','C1','education',2,'nuanced subtle complex analysis');

-- ══════════════════════════════════════
-- WORDS — C2 (35)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_education_C2_01','heuristics','/hjʊˈrɪstɪks/','noun','발견술, 휴리스틱스','Mental shortcuts that enable quick decision-making, especially in learning.','Cognitive {heuristics} can lead to systematic errors.','인지적 발견술은 체계적 오류로 이어질 수 있어요.','heuristics','C2','education',1,'heuristics cognition decision learning'),
('w_education_C2_02','phenomenology','/fɪˌnɒmɪˈnɒlədʒi/','noun','현상학','A philosophical method examining lived experience.','{henomenology} captures the essence of human experience.','현상학은 인간 경험의 본질을 포착해요.','phenomenology','C2','education',1,'phenomenology experience philosophy research'),
('w_education_C2_03','reductionism','/rɪˈdʌkʃənɪzəm/','noun','환원주의','The view that complex phenomena can be explained by simpler parts.','{eductionism} is criticised for oversimplifying social behaviour.','환원주의는 사회 행동을 지나치게 단순화한다는 비판을 받아요.','reductionism','C2','education',1,'reductionism simplify complex system philosophy'),
('w_education_C2_04','falsifiability','/fɔːlsɪfaɪəˈbɪlɪti/','noun','반증 가능성','The capacity for a claim to be proven false by evidence.','Popper argued that {falsifiability} distinguishes science from pseudoscience.','포퍼는 반증 가능성이 과학을 사이비 과학과 구별한다고 주장했어요.','falsifiability','C2','education',1,'falsifiability Popper science research theory'),
('w_education_C2_05','epistemological','/ɪˌpɪstɪməˈlɒdʒɪkəl/','adjective','인식론적인','Relating to the philosophical study of knowledge and its limits.','The article makes an {epistemological} argument about evidence.','이 논문은 증거에 관한 인식론적 주장을 해요.','epistemological','C2','education',1,'epistemological knowledge philosophy limits'),
('w_education_C2_06','praxis','/ˈpræksɪs/','noun','이론과 실천의 통합','The integration of theory and practice in transformative education.','Freire''s {praxis} model challenges oppressive structures.','프레이리의 프락시스 모델은 억압적 구조에 도전해요.','praxis','C2','education',1,'praxis Freire education liberation theory'),
('w_education_C2_07','deconstruction','/ˌdiːkənˈstrʌkʃən/','noun','해체주의','A method of critical analysis that questions fixed meanings.','Derrida''s {deconstruction} destabilises binary oppositions.','데리다의 해체주의는 이항 대립을 불안정하게 해요.','deconstruction','C2','education',1,'deconstruction Derrida postmodern text'),
('w_education_C2_08','semiotic','/ˌsiːmiˈɒtɪk/','adjective','기호학적인','Relating to signs and symbols and their interpretation.','A {semiotic} reading of the curriculum reveals hidden values.','교육 과정의 기호학적 독해는 숨겨진 가치를 드러내요.','semiotic','C2','education',1,'semiotic signs symbols meaning language'),
('w_education_C2_09','poststructuralism','/ˌpoʊstˈstrʌktʃərəlɪzəm/','noun','후기 구조주의','A theoretical approach questioning fixed meanings in language and culture.','{oststructuralism} rejects the idea of a stable text.','후기 구조주의는 안정적인 텍스트라는 개념을 거부해요.','poststructuralism','C2','education',1,'poststructuralism theory language culture'),
('w_education_C2_10','scholasticism','/skəˈlæstɪsɪzəm/','noun','스콜라주의','A medieval theological and philosophical method emphasising systematic reasoning.','{cholasticism} sought to reconcile faith and reason.','스콜라주의는 신앙과 이성을 화해시키려 했어요.','scholasticism','C2','education',1,'scholasticism medieval philosophy theology'),
('w_education_C2_11','ontological','/ˌɒntəˈlɒdʒɪkəl/','adjective','존재론적인','Relating to the nature of being or existence.','The research takes an {ontological} stance on social reality.','이 연구는 사회 현실에 대해 존재론적 입장을 취해요.','ontological','C2','education',2,'ontological being existence philosophy'),
('w_education_C2_12','intersubjectivity','/ˌɪntərsʌbdʒekˈtɪvɪti/','noun','상호 주관성','Shared understanding between different subjects or minds.','{ntersubjectivity} is central to collaborative learning.','상호 주관성은 협력 학습의 핵심이에요.','intersubjectivity','C2','education',2,'intersubjectivity shared understanding learning'),
('w_education_C2_13','logocentrism','/ˌloʊɡoʊˈsentrɪzəm/','noun','로고스 중심주의','The privileging of speech over writing in Western thought.','Derrida critiqued {logocentrism} in philosophical traditions.','데리다는 철학 전통에서 로고스 중심주의를 비판했어요.','logocentrism','C2','education',2,'logocentrism language philosophy Derrida'),
('w_education_C2_14','noumenon','/ˈnuːmɪnɒn/','noun','물자체, 누메논','The thing as it is in itself, independent of perception.','Kant distinguished between phenomenon and {noumenon}.','칸트는 현상과 물자체를 구별했어요.','noumenon','C2','education',2,'noumenon Kant philosophy thing itself'),
('w_education_C2_15','teleology','/ˌteliˈɒlədʒi/','noun','목적론','The explanation of phenomena in terms of goals or purposes.','{eleology} argues that education has an inherent purpose.','목적론은 교육에 내재적 목적이 있다고 주장해요.','teleology','C2','education',2,'teleology purpose goal philosophy'),
('w_education_C2_16','intertextuality','/ˌɪntətekstʃuˈælɪti/','noun','상호 텍스트성','The relationship between texts and their mutual influences.','{ntertextuality} shapes how readers interpret meaning.','상호 텍스트성은 독자가 의미를 해석하는 방식을 형성해요.','intertextuality','C2','education',2,'intertextuality text literature meaning'),
('w_education_C2_17','relativism','/ˈrelətɪvɪzəm/','noun','상대주의','The view that knowledge and truth are relative to context.','{elativism} challenges universal educational standards.','상대주의는 보편적 교육 기준에 도전해요.','relativism','C2','education',2,'relativism truth context culture philosophy'),
('w_education_C2_18','dialectical materialism','/ˌdaɪəˈlektɪkəl məˈtɪəriəlɪzəm/','noun','변증법적 유물론','Marx''s philosophical framework combining dialectics and materialism.','{ialectical materialism} views education as shaped by economic forces.','변증법적 유물론은 교육이 경제적 힘에 의해 형성된다고 봐요.','dialectical materialism','C2','education',2,'dialectical materialism Marx philosophy education'),
('w_education_C2_19','aporia','/əˈpɔːriə/','noun','난제, 아포리아','A philosophical puzzle or state of puzzlement.','The text leaves the reader in a state of {aporia}.','텍스트는 독자를 아포리아 상태에 남겨두어요.','aporia','C2','education',2,'aporia puzzle philosophy doubt'),
('w_education_C2_20','heteroglossia','/ˌhetərəˈɡlɒsiə/','noun','다성성, 이종 언어성','The coexistence of multiple voices or languages in a text.','Bakhtin''s concept of {heteroglossia} challenges monolithic discourse.','바흐친의 다성성 개념은 일원적 담론에 도전해요.','heteroglossia','C2','education',2,'heteroglossia voices language Bakhtin'),
('w_education_C2_21','abduction','/æbˈdʌkʃən/','noun','귀추법','Reasoning from observation to the most likely explanation.','{bduction} generates hypotheses in qualitative research.','귀추법은 질적 연구에서 가설을 생성해요.','abduction','C2','education',2,'abduction reasoning hypothesis research'),
('w_education_C2_22','phronesis','/ˈfrɒnɪsɪs/','noun','실천적 지혜','Aristotle''s concept of practical wisdom in ethical action.','{hronesis} guides teachers in morally complex situations.','실천적 지혜는 도덕적으로 복잡한 상황에서 교사를 이끌어요.','phronesis','C2','education',2,'phronesis wisdom practical Aristotle'),
('w_education_C2_23','liminality','/ˌlɪmɪˈnælɪti/','noun','경계성, 리미널리티','The transitional quality of being between two states.','{iminality} describes the in-between state of new learners.','경계성은 새로운 학습자의 중간 상태를 설명해요.','liminality','C2','education',2,'liminality transition threshold learning'),
('w_education_C2_24','hegemony','/hɪˈdʒeməni/','noun','패권, 헤게모니','Dominant control exerted over others, especially in education.','Gramsci examined {hegemony} in educational institutions.','그람시는 교육 기관의 헤게모니를 검토했어요.','hegemony','C2','education',1,'hegemony power dominance education Gramsci'),
('w_education_C2_25','interlocutor','/ˌɪntəˈlɒkjʊtər/','noun','대화 상대자','A person who participates in a dialogue or interaction.','The {interlocutor} plays a key role in oral assessment.','대화 상대자는 구술 평가에서 핵심 역할을 해요.','interlocutor','C2','education',2,'interlocutor dialogue conversation assessment'),
('w_education_C2_26','verisimilitude','/ˌverɪsɪˈmɪlɪtjuːd/','noun','진실성, 사실성','The appearance of being true or real in research.','{erisimilitude} strengthens the credibility of qualitative findings.','진실성은 질적 연구 결과의 신뢰성을 강화해요.','verisimilitude','C2','education',2,'verisimilitude truth research credibility'),
('w_education_C2_27','episteme','/ˈepɪstiːm/','noun','에피스테메','Foucault''s term for the underlying system of thought in an era.','Each era has its own {episteme} shaping what counts as knowledge.','각 시대는 지식으로 여겨지는 것을 형성하는 자체 에피스테메를 가져요.','episteme','C2','education',2,'episteme Foucault knowledge era'),
('w_education_C2_28','bricolage','/ˌbrɪkəˈlɑːʒ/','noun','브리콜라주','Using whatever tools are available to construct meaning.','Qualitative researchers engage in intellectual {bricolage}.','질적 연구자들은 지적 브리콜라주에 참여해요.','bricolage','C2','education',2,'bricolage construct tools meaning research'),
('w_education_C2_29','sedimentation','/ˌsedɪmenˈteɪʃən/','noun','침전, 층적 형성','The gradual accumulation and layering of cultural meaning.','{edimentation} of beliefs resists change in institutions.','믿음의 침전은 기관의 변화에 저항해요.','sedimentation','C2','education',2,'sedimentation accumulation layer meaning culture'),
('w_education_C2_30','rhizome','/ˈraɪzoʊm/','noun','리좀, 근경','Deleuze and Guattari''s metaphor for non-hierarchical knowledge networks.','{hizome} thinking challenges linear curricula.','리좀적 사고는 선형 교육 과정에 도전해요.','rhizome','C2','education',2,'rhizome network knowledge nonlinear'),
('w_education_C2_31','logomachy','/lɒˈɡɒməki/','noun','말다툼, 언어 논쟁','A dispute over the meaning of words.','The philosophical {logomachy} obscured the real issue.','철학적 말다툼이 진짜 문제를 흐렸어요.','logomachy','C2','education',3,'logomachy debate words philosophy'),
('w_education_C2_32','propaedeutic','/ˌprɒpɪˈdjuːtɪk/','adjective','예비 교육의','Serving as an introduction to further study.','Logic is a {propaedeutic} discipline for philosophy.','논리학은 철학을 위한 예비 교육 분야예요.','propaedeutic','C2','education',3,'propaedeutic preparatory study foundation'),
('w_education_C2_33','catharsis','/kəˈθɑːrsɪs/','noun','카타르시스, 정화','A release of emotion through artistic or learning experience.','Reading great literature can provide {catharsis}.','위대한 문학을 읽으면 카타르시스를 얻을 수 있어요.','catharsis','C2','education',2,'catharsis emotion release learning'),
('w_education_C2_34','cogito','/ˈkɒdʒɪtoʊ/','noun','코기토','Descartes'' principle "I think, therefore I am".','The {cogito} is the foundation of Cartesian philosophy.','코기토는 데카르트 철학의 토대예요.','cogito','C2','education',2,'cogito Descartes thinking existence philosophy'),
('w_education_C2_35','anamnesis','/ˌænæmˈniːsɪs/','noun','상기, 아남네시스','Plato''s theory that learning is a process of recollection.','Plato''s {anamnesis} theory suggests knowledge is innate.','플라톤의 상기 이론은 지식이 내재적이라고 제안해요.','anamnesis','C2','education',2,'anamnesis Plato recollection knowledge');

-- ══════════════════════════════════════
-- PATTERNS (sentences) — A1 (7)
-- 주제: 과목 소개 / 학교생활 기본 표현
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_education_A1_01','What''s your favorite subject?','제일 좋아하는 과목이 뭐예요?','favorite subject','favorite를 써서 선호를 물어볼 수 있어요.','수업 대화','A1','education','pattern',NULL,1),
('s_education_A1_02','I like math because it''s interesting.','수학이 재미있어서 좋아요.','I like ... because','이유를 말할 때 because를 쓰면 자연스러워요.','과목 소개','A1','education','pattern',NULL,2),
('s_education_A1_03','How do you spell that word?','그 단어 철자가 어떻게 돼요?','How do you spell','모르는 단어 철자를 물어볼 때 쓰는 표현이에요.','수업 중 질문','A1','education','pattern',NULL,3),
('s_education_A1_04','Can you say that again, please?','다시 한 번 말씀해 주실 수 있어요?','Can you say that again','이해 못했을 때 정중하게 다시 말해달라고 하는 표현이에요.','수업 중','A1','education','pattern',NULL,4),
('s_education_A1_05','What does this word mean?','이 단어는 무슨 뜻이에요?','What does ... mean','모르는 단어의 뜻을 물어볼 때 가장 기본적인 표현이에요.','어휘 확인','A1','education','pattern',NULL,5),
('s_education_A1_06','I don''t understand. Can you help me?','이해가 안 돼요. 도와주실 수 있어요?','I don''t understand','솔직하게 모른다고 말하는 것이 배움의 첫 걸음이에요.','도움 요청','A1','education','pattern',NULL,6),
('s_education_A1_07','We have a test tomorrow.','내일 시험이 있어요.','We have a test','시험을 안내할 때 쓰는 가장 간단한 표현이에요.','시험 안내','A1','education','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — A2 (7)
-- 주제: 시험 준비 / 성적 표현
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_education_A2_01','I need to study for the exam this weekend.','이번 주말에 시험 공부를 해야 해요.','need to study for','need to를 쓰면 해야 할 일을 자연스럽게 표현할 수 있어요.','시험 준비','A2','education','pattern',NULL,1),
('s_education_A2_02','Did you pass the test? I got a B.','시험 합격했어요? 저는 B 받았어요.','Did you pass','시험 결과를 물어보거나 공유할 때 쓰는 표현이에요.','성적 대화','A2','education','pattern',NULL,2),
('s_education_A2_03','I''m going to review my notes tonight.','오늘 밤에 필기 내용을 복습할 거예요.','review my notes','review를 써서 복습 계획을 말할 수 있어요.','공부 계획','A2','education','pattern',NULL,3),
('s_education_A2_04','What chapter is the exam on?','시험 범위가 몇 장이에요?','What chapter is ... on','시험 범위를 확인할 때 꼭 필요한 표현이에요.','시험 준비','A2','education','pattern',NULL,4),
('s_education_A2_05','The homework is due on Friday.','숙제 제출 기한은 금요일이에요.','is due on','마감일을 표현할 때 be due on을 사용해요.','과제 안내','A2','education','pattern',NULL,5),
('s_education_A2_06','I failed the quiz, so I need to try harder.','쪽지 시험에서 떨어져서 더 열심히 해야 해요.','I failed ... so I need to','결과와 다짐을 연결할 때 so를 사용해요.','자기 반성','A2','education','pattern',NULL,6),
('s_education_A2_07','Can I borrow your notes from yesterday''s class?','어제 수업 필기 빌릴 수 있어요?','Can I borrow','정중하게 빌려달라고 부탁하는 표현이에요.','친구에게 부탁','A2','education','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — B1 (7)
-- 주제: 발표 / 수업 중 질문
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_education_B1_01','I''d like to talk about the importance of lifelong learning.','평생 학습의 중요성에 대해 말씀드리려고 해요.','I''d like to talk about','발표를 시작할 때 I''d like to를 쓰면 공손하고 자연스럽게 들려요.','발표 시작','B1','education','pattern',NULL,1),
('s_education_B1_02','Could you explain that concept in more detail?','그 개념을 좀 더 자세히 설명해 주실 수 있어요?','Could you explain ... in more detail','수업에서 추가 설명을 요청할 때 쓰는 정중한 표현이에요.','수업 중 질문','B1','education','pattern',NULL,2),
('s_education_B1_03','My assignment is to write an essay on climate change.','제 과제는 기후 변화에 관한 에세이를 쓰는 거예요.','My assignment is to','과제 내용을 설명할 때 쓰는 자연스러운 표현이에요.','과제 설명','B1','education','pattern',NULL,3),
('s_education_B1_04','In my presentation, I will cover three main points.','발표에서 세 가지 주요 논점을 다룰 거예요.','I will cover','발표 구조를 미리 안내할 때 쓰는 표현이에요.','발표 구조 안내','B1','education','pattern',NULL,4),
('s_education_B1_05','I''m not sure I understand the difference between these two terms.','이 두 용어의 차이를 잘 모르겠어요.','I''m not sure I understand','확신이 없을 때 부드럽게 물어보는 정중한 표현이에요.','개념 확인','B1','education','pattern',NULL,5),
('s_education_B1_06','To sum up, the evidence suggests that practice improves fluency.','요약하면, 증거는 연습이 유창성을 향상시킨다고 제안해요.','To sum up','발표나 에세이를 마무리할 때 쓰는 전형적인 표현이에요.','발표 마무리','B1','education','pattern',NULL,6),
('s_education_B1_07','I applied for a scholarship and I''m waiting to hear back.','장학금을 신청했고 결과를 기다리고 있어요.','waiting to hear back','결과를 기다리는 상황을 표현할 때 쓰는 관용 표현이에요.','장학금 지원','B1','education','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — B2 (7)
-- 주제: 토론 참여 / 학술 토론
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_education_B2_01','I see your point, but I''d argue that the data supports a different conclusion.','말씀하시는 바는 이해하지만, 데이터는 다른 결론을 지지한다고 생각해요.','I see your point, but I''d argue','반박할 때 상대방을 인정하면서 부드럽게 반론을 제시하는 표현이에요.','학술 토론','B2','education','pattern',NULL,1),
('s_education_B2_02','The methodology used in this study has some significant limitations.','이 연구에 사용된 방법론에는 몇 가지 중요한 한계가 있어요.','significant limitations','연구의 한계를 지적할 때 쓰는 학술적 표현이에요.','연구 비평','B2','education','pattern',NULL,2),
('s_education_B2_03','Could you elaborate on how you operationalised that variable?','그 변수를 어떻게 조작화했는지 좀 더 설명해 주실 수 있어요?','Could you elaborate on','학술 발표에서 방법론을 더 물어볼 때 쓰는 정중한 표현이에요.','연구 방법 질문','B2','education','pattern',NULL,3),
('s_education_B2_04','Building on the previous speaker''s argument, I would like to add that...','이전 발언자의 주장을 바탕으로, 추가하고 싶은 것은...','Building on','토론에서 앞선 의견을 이어받아 자신의 논점을 더할 때 쓰는 표현이에요.','토론 참여','B2','education','pattern',NULL,4),
('s_education_B2_05','The empirical evidence does not fully support this hypothesis.','실증적 증거가 이 가설을 완전히 지지하지는 않아요.','empirical evidence ... does not fully support','학술 글쓰기에서 가설의 한계를 조심스럽게 언급할 때 쓰는 표현이에요.','연구 결과 평가','B2','education','pattern',NULL,5),
('s_education_B2_06','This dissertation critically examines the relationship between pedagogy and identity.','이 논문은 교수법과 정체성의 관계를 비판적으로 검토해요.','critically examines','학위 논문의 목적을 설명할 때 쓰는 학술적 표현이에요.','논문 소개','B2','education','pattern',NULL,6),
('s_education_B2_07','I would contend that peer learning is as effective as direct instruction.','동료 학습이 직접 교수만큼 효과적이라고 주장하고 싶어요.','I would contend that','토론에서 신중하게 주장을 제시할 때 contend를 쓰면 격식 있게 들려요.','학술 주장','B2','education','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — C1 (7)
-- 주제: 논문 표현 / 고급 학술 쓰기
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_education_C1_01','This study seeks to interrogate the epistemological assumptions underlying conventional pedagogy.','이 연구는 전통적 교수법의 기저에 있는 인식론적 가정을 비판적으로 검토하고자 해요.','interrogate the epistemological assumptions','interrogate는 단순한 검토를 넘어 비판적 질문을 던지는 것을 의미해요.','논문 서론','C1','education','pattern',NULL,1),
('s_education_C1_02','The conceptual framework draws on constructivist and sociocultural theories of learning.','개념적 틀은 구성주의와 사회문화적 학습 이론을 바탕으로 해요.','draws on ... theories','draws on은 이론적 토대를 설명할 때 쓰는 학술적 표현이에요.','이론적 배경','C1','education','pattern',NULL,2),
('s_education_C1_03','The findings substantiate the hypothesis that scaffolding enhances learner autonomy.','연구 결과는 발판식 교수법이 학습자 자율성을 향상시킨다는 가설을 뒷받침해요.','substantiate the hypothesis','substantiate는 주장이나 가설을 증거로 뒷받침함을 의미해요.','연구 결과 기술','C1','education','pattern',NULL,3),
('s_education_C1_04','It is worth noting that the sample size limits the generalisability of these findings.','표본 크기가 연구 결과의 일반화 가능성을 제한한다는 점을 언급할 필요가 있어요.','It is worth noting that','학술 글쓰기에서 한계나 주의사항을 부드럽게 제시하는 표현이에요.','연구 한계 기술','C1','education','pattern',NULL,4),
('s_education_C1_05','Reflexivity demands that the researcher acknowledge their own positionality.','성찰성은 연구자가 자신의 위치성을 인정할 것을 요구해요.','demands that the researcher acknowledge','연구 윤리 논의에서 연구자의 성찰을 강조하는 학술 표현이에요.','연구 윤리','C1','education','pattern',NULL,5),
('s_education_C1_06','The literature review reveals a significant lacuna in studies on postgraduate wellbeing.','문헌 검토는 대학원생 복지에 관한 연구의 중요한 공백을 드러내요.','reveals a significant lacuna','lacuna는 지식이나 연구의 빈 공간을 뜻하는 고급 학술 어휘예요.','문헌 검토','C1','education','pattern',NULL,6),
('s_education_C1_07','This paper posits that critical pedagogy must account for the socioeconomic context of learners.','이 논문은 비판적 교수법이 학습자의 사회경제적 맥락을 고려해야 한다고 상정해요.','posits that','posit은 논문에서 핵심 가정이나 전제를 제시할 때 쓰는 정확한 학술어예요.','논문 핵심 주장','C1','education','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — C2 (7)
-- 주제: 최고급 학술 표현 / 철학적 논증
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_education_C2_01','Derrida''s deconstructive reading destabilises the binary between teacher authority and learner agency.','데리다의 해체적 독해는 교사 권위와 학습자 주체성의 이분법을 불안정하게 해요.','destabilises the binary between','destabilise a binary는 후기 구조주의 담론에서 핵심적인 표현이에요.','철학적 비평','C2','education','pattern',NULL,1),
('s_education_C2_02','Foucault''s episteme provides a lens through which to examine the archaeology of educational knowledge.','푸코의 에피스테메는 교육 지식의 고고학을 검토하는 렌즈를 제공해요.','provides a lens through which to examine','provides a lens through which는 고급 학술 글쓰기에서 분석 도구를 소개할 때 쓰는 전형적 표현이에요.','담론 분석','C2','education','pattern',NULL,2),
('s_education_C2_03','The falsifiability criterion challenges normative assumptions embedded in positivist research paradigms.','반증 가능성 기준은 실증주의 연구 패러다임에 내재된 규범적 가정에 도전해요.','challenges normative assumptions embedded in','embedded in은 무언가가 더 큰 구조 속에 깊이 자리 잡고 있음을 표현해요.','과학 철학 논의','C2','education','pattern',NULL,3),
('s_education_C2_04','Hegemonic discourse in curricula reproduces socioeconomic inequalities through the hidden curriculum.','교육 과정의 헤게모니적 담론은 잠재적 교육 과정을 통해 사회경제적 불평등을 재생산해요.','reproduces ... through the hidden curriculum','hidden curriculum은 공식 과목 외에 무의식적으로 전달되는 가치를 뜻하는 교육학 용어예요.','비판 교육학','C2','education','pattern',NULL,4),
('s_education_C2_05','Phenomenological inquiry foregrounds the lived experience of learners as the primary unit of analysis.','현상학적 탐구는 학습자의 살아있는 경험을 분석의 주요 단위로 전면에 내세워요.','foregrounds the lived experience','foreground는 무언가를 중심이나 전면에 배치한다는 의미의 학술적 동사예요.','연구 방법론 논의','C2','education','pattern',NULL,5),
('s_education_C2_06','Rhizomatic learning theory, as advanced by Cormier, resists arborescent models of knowledge transmission.','코미에가 발전시킨 리좀적 학습 이론은 나무형 지식 전달 모델에 저항해요.','resists arborescent models','arborescent은 나무처럼 계층적이고 선형적인 구조를 뜻하는 들뢰즈 철학 용어예요.','교육 이론 논의','C2','education','pattern',NULL,6),
('s_education_C2_07','The praxis-oriented approach collapses the distinction between knowledge production and social transformation.','프락시스 지향 접근은 지식 생산과 사회 변혁 사이의 구분을 무너뜨려요.','collapses the distinction between','collapse a distinction은 두 개념 사이의 경계를 허물 때 쓰는 고급 학술 표현이에요.','비판 이론','C2','education','pattern',NULL,7);
