-- EngCat · Shopping — words examples (example_en_2~5 / example_ko_2~5)
-- 210 UPDATE statements (A1×35, A2×35, B1×35, B2×35, C1×35, C2×35)
-- Generated: 2026-05-26

-- ────────────────────────────────────────────────────────────
-- A1
-- ────────────────────────────────────────────────────────────
UPDATE words SET example_en_2 = 'Did you buy anything at the market?', example_ko_2 = '시장에서 뭔가 사셨나요?', example_en_3 = 'She wants to buy a red dress.', example_ko_3 = '그녀는 빨간 원피스를 사고 싶어해요.', example_en_4 = 'Let''s buy some snacks for the trip.', example_ko_4 = '여행을 위해 간식을 좀 사요.', example_en_5 = 'Can you buy milk on your way home?', example_ko_5 = '집에 오는 길에 우유 사올 수 있어요?' WHERE id = 'w_shopping_A1_01';
UPDATE words SET example_en_2 = 'Do they sell umbrellas here?', example_ko_2 = '여기서 우산도 파나요?', example_en_3 = 'He sells handmade candles online.', example_ko_3 = '그는 온라인으로 손으로 만든 초를 팔아요.', example_en_4 = 'This shop sells books and stationery.', example_ko_4 = '이 가게는 책과 문구류를 팔아요.', example_en_5 = 'They sell coffee at the corner café.', example_ko_5 = '코너 카페에서 커피를 팔아요.' WHERE id = 'w_shopping_A1_02';
UPDATE words SET example_en_2 = 'I love to shop on weekends.', example_ko_2 = '저는 주말에 쇼핑하는 걸 좋아해요.', example_en_3 = 'There is a new shop on the high street.', example_ko_3 = '번화가에 새 가게가 생겼어요.', example_en_4 = 'We shopped for three hours yesterday.', example_ko_4 = '어제 세 시간 동안 쇼핑했어요.', example_en_5 = 'Which shop has the best prices?', example_ko_5 = '어느 가게가 제일 싸요?' WHERE id = 'w_shopping_A1_03';
UPDATE words SET example_en_2 = 'The price is too high for me.', example_ko_2 = '저한테는 가격이 너무 높아요.', example_en_3 = 'Is there a better price for two items?', example_ko_3 = '두 개 사면 더 좋은 가격이 있나요?', example_en_4 = 'The price went down during the sale.', example_ko_4 = '세일 기간 동안 가격이 내려갔어요.', example_en_5 = 'Can you tell me the price of this shirt?', example_ko_5 = '이 셔츠 가격이 얼마인지 알려주실 수 있어요?' WHERE id = 'w_shopping_A1_04';
UPDATE words SET example_en_2 = 'I found a cheap restaurant near here.', example_ko_2 = '근처에 저렴한 식당을 찾았어요.', example_en_3 = 'These shoes look cheap but they''re good quality.', example_ko_3 = '이 신발은 저렴해 보이지만 품질이 좋아요.', example_en_4 = 'Is there a cheap option available?', example_ko_4 = '저렴한 선택지가 있나요?', example_en_5 = 'Fresh vegetables are cheap at the market.', example_ko_5 = '시장에서는 신선한 채소가 저렴해요.' WHERE id = 'w_shopping_A1_05';
UPDATE words SET example_en_2 = 'Why is this so expensive?', example_ko_2 = '왜 이게 이렇게 비싸요?', example_en_3 = 'This restaurant is too expensive for me.', example_ko_3 = '이 식당은 저한테 너무 비싸요.', example_en_4 = 'Organic food is usually more expensive.', example_ko_4 = '유기농 식품은 보통 더 비싸요.', example_en_5 = 'The shoes were expensive, but worth it.', example_ko_5 = '신발이 비쌌지만 그만한 가치가 있었어요.' WHERE id = 'w_shopping_A1_06';
UPDATE words SET example_en_2 = 'Can you lend me some money?', example_ko_2 = '돈 좀 빌려줄 수 있어요?', example_en_3 = 'I need to get some money from the bank.', example_ko_3 = '은행에서 돈을 찾아야 해요.', example_en_4 = 'Save your money for something important.', example_ko_4 = '중요한 것을 위해 돈을 모아요.', example_en_5 = 'How much money do you have with you?', example_ko_5 = '지금 얼마나 가지고 계세요?' WHERE id = 'w_shopping_A1_07';
UPDATE words SET example_en_2 = 'I''ll pay at the counter.', example_ko_2 = '계산대에서 낼게요.', example_en_3 = 'Do I pay here or at the exit?', example_ko_3 = '여기서 내나요, 출구에서 내나요?', example_en_4 = 'She paid for everything with cash.', example_ko_4 = '그녀는 현금으로 전부 냈어요.', example_en_5 = 'You can pay online before you arrive.', example_ko_5 = '도착 전에 온라인으로 결제할 수 있어요.' WHERE id = 'w_shopping_A1_08';
UPDATE words SET example_en_2 = 'The night market is very popular here.', example_ko_2 = '여기 야시장이 매우 인기 있어요.', example_en_3 = 'We buy vegetables at the local market.', example_ko_3 = '동네 시장에서 채소를 사요.', example_en_4 = 'Is there a market near the hotel?', example_ko_4 = '호텔 근처에 시장이 있나요?', example_en_5 = 'The flea market starts at nine.', example_ko_5 = '벼룩시장은 9시에 시작해요.' WHERE id = 'w_shopping_A1_09';
UPDATE words SET example_en_2 = 'What time does the store open?', example_ko_2 = '상점이 몇 시에 열어요?', example_en_3 = 'The store has a wide range of products.', example_ko_3 = '그 상점은 다양한 상품이 있어요.', example_en_4 = 'Is there a convenience store nearby?', example_ko_4 = '근처에 편의점이 있나요?', example_en_5 = 'I went to the store to buy some bread.', example_ko_5 = '빵을 사러 상점에 갔어요.' WHERE id = 'w_shopping_A1_10';
UPDATE words SET example_en_2 = 'I forgot my bag at home.', example_ko_2 = '집에 가방을 두고 왔어요.', example_en_3 = 'Please put it in a paper bag.', example_ko_3 = '종이봉투에 넣어 주세요.', example_en_4 = 'Do you need a bag for those items?', example_ko_4 = '그 물건들을 담을 봉투가 필요하세요?', example_en_5 = 'She carries a big shopping bag.', example_ko_5 = '그녀는 큰 쇼핑백을 들고 다녀요.' WHERE id = 'w_shopping_A1_11';
UPDATE words SET example_en_2 = 'Is this a new product?', example_ko_2 = '이게 새 상품이에요?', example_en_3 = 'I just bought a new phone.', example_ko_3 = '방금 새 휴대폰을 샀어요.', example_en_4 = 'They have new arrivals every week.', example_ko_4 = '매주 새 상품이 들어와요.', example_en_5 = 'The new collection looks amazing.', example_ko_5 = '새 컬렉션이 정말 멋져 보여요.' WHERE id = 'w_shopping_A1_12';
UPDATE words SET example_en_2 = 'This old jacket still looks great.', example_ko_2 = '이 오래된 재킷이 아직도 멋져 보여요.', example_en_3 = 'Do you buy old furniture?', example_ko_3 = '오래된 가구도 사시나요?', example_en_4 = 'The old model is cheaper than the new one.', example_ko_4 = '구형 모델이 신형보다 저렴해요.', example_en_5 = 'I prefer old books to new ones.', example_ko_5 = '저는 새 책보다 오래된 책을 더 좋아해요.' WHERE id = 'w_shopping_A1_13';
UPDATE words SET example_en_2 = 'Do you have this in a big size?', example_ko_2 = '이거 큰 사이즈 있나요?', example_en_3 = 'I need a big box for this.', example_ko_3 = '이걸 담을 큰 상자가 필요해요.', example_en_4 = 'The big sale starts on Friday.', example_ko_4 = '큰 세일이 금요일에 시작해요.', example_en_5 = 'Is there a bigger version of this bag?', example_ko_5 = '이 가방의 더 큰 버전이 있나요?' WHERE id = 'w_shopping_A1_14';
UPDATE words SET example_en_2 = 'The small size is sold out.', example_ko_2 = '작은 사이즈는 품절이에요.', example_en_3 = 'Do you have something smaller?', example_ko_3 = '더 작은 것도 있나요?', example_en_4 = 'This room is a bit small for a store.', example_ko_4 = '이 공간은 가게로는 좀 작아요.', example_en_5 = 'A small gift is always a nice gesture.', example_ko_5 = '작은 선물도 항상 좋은 표현이에요.' WHERE id = 'w_shopping_A1_15';
UPDATE words SET example_en_2 = 'Are you open on public holidays?', example_ko_2 = '공휴일에도 영업하나요?', example_en_3 = 'The store is open until ten tonight.', example_ko_3 = '오늘 밤 10시까지 영업해요.', example_en_4 = 'Is the café open yet?', example_ko_4 = '카페 벌써 문 열었나요?', example_en_5 = 'They are open seven days a week.', example_ko_5 = '주 7일 영업해요.' WHERE id = 'w_shopping_A1_16';
UPDATE words SET example_en_2 = 'Sorry, the bakery is closed now.', example_ko_2 = '죄송해요, 빵집은 지금 문 닫았어요.', example_en_3 = 'The shop is closed on Mondays.', example_ko_3 = '그 가게는 월요일에 쉬어요.', example_en_4 = 'Is the pharmacy closed today?', example_ko_4 = '오늘 약국 문 닫았나요?', example_en_5 = 'We arrived just as the store closed.', example_ko_5 = '가게가 문 닫는 순간 도착했어요.' WHERE id = 'w_shopping_A1_17';
UPDATE words SET example_en_2 = 'What do you want for your birthday?', example_ko_2 = '생일에 뭘 원하세요?', example_en_3 = 'I want to try on those shoes.', example_ko_3 = '저 신발을 신어보고 싶어요.', example_en_4 = 'Do you want a bag with that?', example_ko_4 = '봉투도 드릴까요?', example_en_5 = 'She wants to exchange her jacket.', example_ko_5 = '그녀는 재킷을 교환하고 싶어해요.' WHERE id = 'w_shopping_A1_18';
UPDATE words SET example_en_2 = 'I need to find a pharmacy quickly.', example_ko_2 = '빨리 약국을 찾아야 해요.', example_en_3 = 'Do you need anything from the store?', example_ko_3 = '상점에서 필요한 거 있어요?', example_en_4 = 'We need more bags for all this shopping.', example_ko_4 = '이 쇼핑한 것들 다 담으려면 봉투가 더 필요해요.', example_en_5 = 'I need a medium size, please.', example_ko_5 = '미디엄 사이즈로 부탁드려요.' WHERE id = 'w_shopping_A1_19';
UPDATE words SET example_en_2 = 'Can I look at the menu first?', example_ko_2 = '메뉴를 먼저 봐도 될까요?', example_en_3 = 'Look at those prices — amazing!', example_ko_3 = '저 가격 좀 봐요 — 정말 놀랍죠!', example_en_4 = 'She''s looking for a gift for her mum.', example_ko_4 = '그녀는 엄마 선물을 찾고 있어요.', example_en_5 = 'I''m looking for the shoe section.', example_ko_5 = '신발 코너를 찾고 있어요.' WHERE id = 'w_shopping_A1_20';
UPDATE words SET example_en_2 = 'The gift wrapping is free today.', example_ko_2 = '오늘은 선물 포장이 무료예요.', example_en_3 = 'You can park here for free.', example_ko_3 = '여기 무료로 주차할 수 있어요.', example_en_4 = 'Is the wi-fi free in this café?', example_ko_4 = '이 카페 와이파이 무료예요?', example_en_5 = 'Buy two and get one free.', example_ko_5 = '두 개 사면 하나 무료예요.' WHERE id = 'w_shopping_A1_21';
UPDATE words SET example_en_2 = 'Is this bag a good gift for her?', example_ko_2 = '이 가방이 그녀에게 좋은 선물이 될까요?', example_en_3 = 'Do you have gift wrapping?', example_ko_3 = '선물 포장 해드리나요?', example_en_4 = 'I always bring a small gift when I visit.', example_ko_4 = '저는 방문할 때 항상 작은 선물을 가져가요.', example_en_5 = 'The gift came in a beautiful box.', example_ko_5 = '선물이 예쁜 상자에 담겨 왔어요.' WHERE id = 'w_shopping_A1_22';
UPDATE words SET example_en_2 = 'Can you show me the total on the screen?', example_ko_2 = '화면으로 합계를 보여주실 수 있어요?', example_en_3 = 'The total comes to forty dollars.', example_ko_3 = '합계가 40달러예요.', example_en_4 = 'Please check the total before you pay.', example_ko_4 = '결제 전에 합계를 확인해 주세요.', example_en_5 = 'The total includes tax.', example_ko_5 = '합계에 세금이 포함되어 있어요.' WHERE id = 'w_shopping_A1_23';
UPDATE words SET example_en_2 = 'I only have cash with me today.', example_ko_2 = '오늘은 현금만 가지고 있어요.', example_en_3 = 'Is there a cash machine nearby?', example_ko_3 = '근처에 현금 인출기 있나요?', example_en_4 = 'She paid in cash at the market.', example_ko_4 = '그녀는 시장에서 현금으로 냈어요.', example_en_5 = 'Some small shops only take cash.', example_ko_5 = '일부 작은 가게는 현금만 받아요.' WHERE id = 'w_shopping_A1_24';
UPDATE words SET example_en_2 = 'My card was declined at the checkout.', example_ko_2 = '계산대에서 카드가 거절됐어요.', example_en_3 = 'Can I use a debit card here?', example_ko_3 = '여기서 직불카드 쓸 수 있나요?', example_en_4 = 'Tap your card on the reader.', example_ko_4 = '단말기에 카드를 태그해 주세요.', example_en_5 = 'I lost my card at the store.', example_ko_5 = '상점에서 카드를 잃어버렸어요.' WHERE id = 'w_shopping_A1_25';
UPDATE words SET example_en_2 = 'The staff helped me choose a size.', example_ko_2 = '직원이 사이즈 고르는 걸 도와줬어요.', example_en_3 = 'Can I help you with anything else?', example_ko_3 = '다른 도움이 필요하신가요?', example_en_4 = 'He helped carry the bags to the car.', example_ko_4 = '그가 가방을 차까지 옮기는 걸 도와줬어요.', example_en_5 = 'Is there anyone here who can help me?', example_ko_5 = '여기 저를 도와줄 수 있는 분이 있나요?' WHERE id = 'w_shopping_A1_26';
UPDATE words SET example_en_2 = 'I can''t find the price tag.', example_ko_2 = '가격표를 못 찾겠어요.', example_en_3 = 'Did you find what you were looking for?', example_ko_3 = '찾던 걸 찾으셨나요?', example_en_4 = 'Let me find the right size for you.', example_ko_4 = '맞는 사이즈를 찾아드릴게요.', example_en_5 = 'I found a great deal online.', example_ko_5 = '온라인에서 좋은 가격을 찾았어요.' WHERE id = 'w_shopping_A1_27';
UPDATE words SET example_en_2 = 'Take a number and wait, please.', example_ko_2 = '번호표 뽑고 기다려 주세요.', example_en_3 = 'He took the last item on the shelf.', example_ko_3 = '그는 선반의 마지막 남은 것을 가져갔어요.', example_en_4 = 'Can I take a look at that watch?', example_ko_4 = '저 시계 좀 볼 수 있을까요?', example_en_5 = 'I''ll take both, please.', example_ko_5 = '둘 다 주세요.' WHERE id = 'w_shopping_A1_28';
UPDATE words SET example_en_2 = 'Can I get a discount for this?', example_ko_2 = '이거 할인받을 수 있나요?', example_en_3 = 'I need to get some cash first.', example_ko_3 = '먼저 현금을 찾아야 해요.', example_en_4 = 'Where can I get a trolley?', example_ko_4 = '카트는 어디서 가져올 수 있나요?', example_en_5 = 'She got a great deal on the coat.', example_ko_5 = '그녀는 코트를 정말 싸게 샀어요.' WHERE id = 'w_shopping_A1_29';
UPDATE words SET example_en_2 = 'Give me a moment to check the price.', example_ko_2 = '가격 확인할 시간 좀 주세요.', example_en_3 = 'Can you give me a smaller bag?', example_ko_3 = '더 작은 봉투로 주실 수 있어요?', example_en_4 = 'They give a discount for students.', example_ko_4 = '학생에게는 할인을 해줘요.', example_en_5 = 'Please give me the total.', example_ko_5 = '합계를 알려주세요.' WHERE id = 'w_shopping_A1_30';
UPDATE words SET example_en_2 = 'Where is the food section?', example_ko_2 = '식품 코너가 어디예요?', example_en_3 = 'This store sells organic food.', example_ko_3 = '이 상점은 유기농 식품을 팔아요.', example_en_4 = 'I always buy fresh food at the market.', example_ko_4 = '저는 항상 시장에서 신선한 음식을 사요.', example_en_5 = 'Is the food here good value?', example_ko_5 = '여기 음식이 가성비가 좋나요?' WHERE id = 'w_shopping_A1_31';
UPDATE words SET example_en_2 = 'The clothes on sale are over there.', example_ko_2 = '세일 중인 옷은 저쪽에 있어요.', example_en_3 = 'Do you sell children''s clothes?', example_ko_3 = '아동복도 판매하나요?', example_en_4 = 'I need to buy some warmer clothes.', example_ko_4 = '더 따뜻한 옷을 사야 해요.', example_en_5 = 'Her clothes are always very stylish.', example_ko_5 = '그녀의 옷은 항상 매우 스타일리시해요.' WHERE id = 'w_shopping_A1_32';
UPDATE words SET example_en_2 = 'Is there a book sale on today?', example_ko_2 = '오늘 책 세일 하나요?', example_en_3 = 'I''m looking for a book on cooking.', example_ko_3 = '요리에 관한 책을 찾고 있어요.', example_en_4 = 'Could you recommend a good book?', example_ko_4 = '좋은 책 추천해 주실 수 있어요?', example_en_5 = 'The book was cheaper online.', example_ko_5 = '온라인에서 그 책이 더 저렴했어요.' WHERE id = 'w_shopping_A1_33';
UPDATE words SET example_en_2 = 'What colors does this come in?', example_ko_2 = '이건 어떤 색깔로 나와요?', example_en_3 = 'I prefer a neutral color for everyday use.', example_ko_3 = '저는 일상 사용으로 무채색을 선호해요.', example_en_4 = 'Does this come in a darker color?', example_ko_4 = '이게 더 어두운 색깔로도 있나요?', example_en_5 = 'The color of this jacket is beautiful.', example_ko_5 = '이 재킷 색깔이 정말 예뻐요.' WHERE id = 'w_shopping_A1_34';
UPDATE words SET example_en_2 = 'What number shoe do you wear?', example_ko_2 = '신발 몇 번 신으세요?', example_en_3 = 'Write your phone number on this form.', example_ko_3 = '이 양식에 전화번호를 적어 주세요.', example_en_4 = 'Take a number and the staff will call you.', example_ko_4 = '번호표를 받으면 직원이 불러드릴 거예요.', example_en_5 = 'My lucky number is seven.', example_ko_5 = '제 행운의 숫자는 7이에요.' WHERE id = 'w_shopping_A1_35';

-- ────────────────────────────────────────────────────────────
-- A2
-- ────────────────────────────────────────────────────────────
UPDATE words SET example_en_2 = 'Can I get a discount on this item?', example_ko_2 = '이 상품 할인받을 수 있나요?', example_en_3 = 'The discount code is on the website.', example_ko_3 = '할인 코드는 웹사이트에 있어요.', example_en_4 = 'They offer a ten percent discount for members.', example_ko_4 = '회원에게는 10% 할인을 해줘요.', example_en_5 = 'Is there any discount available today?', example_ko_5 = '오늘 이용 가능한 할인이 있나요?' WHERE id = 'w_shopping_A2_01';
UPDATE words SET example_en_2 = 'The winter sale starts next week.', example_ko_2 = '겨울 세일이 다음 주에 시작해요.', example_en_3 = 'I bought this dress on sale.', example_ko_3 = '이 원피스를 세일할 때 샀어요.', example_en_4 = 'Is the sale still on?', example_ko_4 = '세일이 아직 진행 중인가요?', example_en_5 = 'Everything in the store is on sale today.', example_ko_5 = '오늘 매장 내 모든 것이 세일 중이에요.' WHERE id = 'w_shopping_A2_02';
UPDATE words SET example_en_2 = 'You''ll need the receipt to get a refund.', example_ko_2 = '환불을 받으려면 영수증이 필요해요.', example_en_3 = 'The receipt shows the full breakdown.', example_ko_3 = '영수증에 전체 내역이 나와 있어요.', example_en_4 = 'Can you email me the receipt?', example_ko_4 = '영수증을 이메일로 보내주실 수 있나요?', example_en_5 = 'I lost my receipt for this purchase.', example_ko_5 = '이 구매의 영수증을 잃어버렸어요.' WHERE id = 'w_shopping_A2_03';
UPDATE words SET example_en_2 = 'What size is this in UK sizing?', example_ko_2 = '이게 영국 사이즈로는 몇 사이즈예요?', example_en_3 = 'The size chart is on the back of the label.', example_ko_3 = '사이즈 표는 라벨 뒤에 있어요.', example_en_4 = 'I normally wear a size medium.', example_ko_4 = '저는 보통 미디엄 사이즈를 입어요.', example_en_5 = 'This size is a perfect fit.', example_ko_5 = '이 사이즈가 딱 맞아요.' WHERE id = 'w_shopping_A2_04';
UPDATE words SET example_en_2 = 'Is this brand well known in Korea?', example_ko_2 = '이 브랜드가 한국에서 유명한가요?', example_en_3 = 'I prefer this brand over the others.', example_ko_3 = '저는 다른 것들보다 이 브랜드를 선호해요.', example_en_4 = 'The brand has been around for fifty years.', example_ko_4 = '그 브랜드는 50년의 역사가 있어요.', example_en_5 = 'She always buys the same brand of coffee.', example_ko_5 = '그녀는 항상 같은 브랜드의 커피를 사요.' WHERE id = 'w_shopping_A2_05';
UPDATE words SET example_en_2 = 'Ask the cashier for a receipt.', example_ko_2 = '계산원에게 영수증을 요청하세요.', example_en_3 = 'The cashier scanned the items quickly.', example_ko_3 = '계산원이 물건들을 빠르게 스캔했어요.', example_en_4 = 'There''s a long queue at the cashier.', example_ko_4 = '계산대에 줄이 길어요.', example_en_5 = 'The cashier told me the total was wrong.', example_ko_5 = '계산원이 합계가 잘못됐다고 알려줬어요.' WHERE id = 'w_shopping_A2_06';
UPDATE words SET example_en_2 = 'I don''t have the right change.', example_ko_2 = '거스름돈이 정확하지 않아요.', example_en_3 = 'He gave me the wrong change.', example_ko_3 = '그가 거스름돈을 잘못 줬어요.', example_en_4 = 'Do you have change for a fifty?', example_ko_4 = '50달러짜리 잔돈 있어요?', example_en_5 = 'She counted the change carefully.', example_ko_5 = '그녀는 거스름돈을 꼼꼼하게 세었어요.' WHERE id = 'w_shopping_A2_07';
UPDATE words SET example_en_2 = 'Can I get a refund without a receipt?', example_ko_2 = '영수증 없이도 환불받을 수 있나요?', example_en_3 = 'The refund was processed within three days.', example_ko_3 = '환불이 3일 안에 처리됐어요.', example_en_4 = 'I requested a full refund for the damaged item.', example_ko_4 = '파손된 물건에 대해 전액 환불을 요청했어요.', example_en_5 = 'Is the refund policy flexible here?', example_ko_5 = '여기 환불 정책이 유연한가요?' WHERE id = 'w_shopping_A2_08';
UPDATE words SET example_en_2 = 'My credit card has a spending limit.', example_ko_2 = '제 신용카드에는 사용 한도가 있어요.', example_en_3 = 'Is it safe to use a credit card here?', example_ko_3 = '여기서 신용카드를 사용하는 게 안전한가요?', example_en_4 = 'She applied for a new credit card last month.', example_ko_4 = '그녀는 지난달에 새 신용카드를 신청했어요.', example_en_5 = 'Do I need to sign for credit card payments?', example_ko_5 = '신용카드 결제 시 서명이 필요한가요?' WHERE id = 'w_shopping_A2_09';
UPDATE words SET example_en_2 = 'I''d like to try on the blue jacket.', example_ko_2 = '파란 재킷을 입어보고 싶어요.', example_en_3 = 'Is it okay if I try on a few pairs?', example_ko_3 = '몇 벌 입어봐도 될까요?', example_en_4 = 'You should try on shoes before buying them.', example_ko_4 = '신발은 구매 전에 신어봐야 해요.', example_en_5 = 'She tried on six dresses before choosing.', example_ko_5 = '그녀는 고르기 전에 원피스를 여섯 개 입어봤어요.' WHERE id = 'w_shopping_A2_10';
UPDATE words SET example_en_2 = 'Is there a fitting room on this floor?', example_ko_2 = '이 층에 탈의실이 있나요?', example_en_3 = 'The fitting room is at the back of the store.', example_ko_3 = '탈의실은 매장 뒤쪽에 있어요.', example_en_4 = 'There''s a queue for the fitting room.', example_ko_4 = '탈의실 앞에 줄이 있어요.', example_en_5 = 'How many items can I take into the fitting room?', example_ko_5 = '탈의실에 몇 개까지 가져갈 수 있나요?' WHERE id = 'w_shopping_A2_11';
UPDATE words SET example_en_2 = 'Please join the queue over here.', example_ko_2 = '이쪽으로 줄 서 주세요.', example_en_3 = 'The queue moved very slowly.', example_ko_3 = '줄이 매우 천천히 움직였어요.', example_en_4 = 'Is this the queue for returns?', example_ko_4 = '이게 반품 줄인가요?', example_en_5 = 'We waited in the queue for twenty minutes.', example_ko_5 = '20분 동안 줄을 섰어요.' WHERE id = 'w_shopping_A2_12';
UPDATE words SET example_en_2 = 'Can I borrow a trolley?', example_ko_2 = '카트를 빌릴 수 있나요?', example_en_3 = 'The trolley is full of groceries.', example_ko_3 = '카트가 장보기 물건으로 가득 차 있어요.', example_en_4 = 'I need a coin to unlock the trolley.', example_ko_4 = '카트를 꺼내려면 동전이 필요해요.', example_en_5 = 'She pushed the trolley to the checkout.', example_ko_5 = '그녀가 카트를 계산대로 밀었어요.' WHERE id = 'w_shopping_A2_13';
UPDATE words SET example_en_2 = 'I only grabbed a small basket.', example_ko_2 = '작은 장바구니만 집었어요.', example_en_3 = 'The basket is getting too heavy.', example_ko_3 = '장바구니가 너무 무거워지고 있어요.', example_en_4 = 'Put the vegetables in the basket.', example_ko_4 = '채소를 장바구니에 넣어요.', example_en_5 = 'She filled her basket quickly.', example_ko_5 = '그녀는 장바구니를 빠르게 채웠어요.' WHERE id = 'w_shopping_A2_14';
UPDATE words SET example_en_2 = 'The cereals are in aisle five.', example_ko_2 = '시리얼은 5번 통로에 있어요.', example_en_3 = 'Walk down the aisle to find the toiletries.', example_ko_3 = '통로를 따라 걸어가면 세면용품이 있어요.', example_en_4 = 'Which aisle are the cleaning products in?', example_ko_4 = '청소용품은 몇 번 통로에 있나요?', example_en_5 = 'A child was running down the aisle.', example_ko_5 = '아이가 통로를 뛰어다니고 있었어요.' WHERE id = 'w_shopping_A2_15';
UPDATE words SET example_en_2 = 'The product is on the middle shelf.', example_ko_2 = '그 상품은 중간 선반에 있어요.', example_en_3 = 'Can you reach the shelf at the top?', example_ko_3 = '맨 위 선반에 닿을 수 있어요?', example_en_4 = 'The shelves were almost empty.', example_ko_4 = '선반이 거의 비어 있었어요.', example_en_5 = 'Please put it back on the shelf.', example_ko_5 = '선반에 다시 놓아 주세요.' WHERE id = 'w_shopping_A2_16';
UPDATE words SET example_en_2 = 'The label shows the expiry date.', example_ko_2 = '라벨에 유통기한이 나와 있어요.', example_en_3 = 'Always read the label before using.', example_ko_3 = '사용 전에 항상 라벨을 읽어주세요.', example_en_4 = 'The price label has fallen off.', example_ko_4 = '가격 라벨이 떨어졌어요.', example_en_5 = 'The label says it''s handwash only.', example_ko_5 = '라벨에 손세탁만 된다고 나와 있어요.' WHERE id = 'w_shopping_A2_17';
UPDATE words SET example_en_2 = 'This is a great offer — don''t miss it!', example_ko_2 = '정말 좋은 특가예요 — 놓치지 마세요!', example_en_3 = 'They made me a good offer on the sofa.', example_ko_3 = '소파를 좋은 가격에 제안해줬어요.', example_en_4 = 'The offer expires at midnight.', example_ko_4 = '특가는 자정에 만료돼요.', example_en_5 = 'Can you match this offer from another store?', example_ko_5 = '다른 상점의 이 특가와 맞춰줄 수 있어요?' WHERE id = 'w_shopping_A2_18';
UPDATE words SET example_en_2 = 'I''d like to exchange this for a different color.', example_ko_2 = '다른 색상으로 교환하고 싶어요.', example_en_3 = 'Can I exchange a gift without a receipt?', example_ko_3 = '영수증 없이 선물을 교환할 수 있나요?', example_en_4 = 'They exchanged the broken item without question.', example_ko_4 = '망가진 물건을 아무 말 없이 교환해줬어요.', example_en_5 = 'I need to exchange these shoes.', example_ko_5 = '이 신발을 교환해야 해요.' WHERE id = 'w_shopping_A2_19';
UPDATE words SET example_en_2 = 'The popular sizes sell out fast.', example_ko_2 = '인기 있는 사이즈는 빨리 품절돼요.', example_en_3 = 'This café is very popular with young people.', example_ko_3 = '이 카페는 젊은이들에게 매우 인기 있어요.', example_en_4 = 'Which brand is popular right now?', example_ko_4 = '지금 어떤 브랜드가 인기 있나요?', example_en_5 = 'The popular product is out of stock.', example_ko_5 = '인기 상품이 품절되었어요.' WHERE id = 'w_shopping_A2_20';
UPDATE words SET example_en_2 = 'I judge products by quality, not price.', example_ko_2 = '저는 가격이 아니라 품질로 상품을 판단해요.', example_en_3 = 'The quality has improved a lot this year.', example_ko_3 = '올해 품질이 많이 향상됐어요.', example_en_4 = 'There''s a big difference in quality between the two.', example_ko_4 = '두 개의 품질 차이가 매우 커요.', example_en_5 = 'Good quality doesn''t have to be expensive.', example_ko_5 = '좋은 품질이 반드시 비쌀 필요는 없어요.' WHERE id = 'w_shopping_A2_21';
UPDATE words SET example_en_2 = 'Please choose a size before paying.', example_ko_2 = '결제 전에 사이즈를 선택해 주세요.', example_en_3 = 'It''s difficult to choose between these two brands.', example_ko_3 = '이 두 브랜드 중에서 고르기가 어려워요.', example_en_4 = 'He chose the cheaper option.', example_ko_4 = '그는 더 저렴한 선택지를 골랐어요.', example_en_5 = 'You can choose up to three items.', example_ko_5 = '최대 세 개까지 선택할 수 있어요.' WHERE id = 'w_shopping_A2_22';
UPDATE words SET example_en_2 = 'I need to pay for this at the counter.', example_ko_2 = '이걸 계산대에서 계산해야 해요.', example_en_3 = 'She forgot to pay for the coffee.', example_ko_3 = '그녀는 커피값을 내는 걸 잊어버렸어요.', example_en_4 = 'Can I pay for this online?', example_ko_4 = '온라인으로 계산할 수 있나요?', example_en_5 = 'He paid for the groceries with his card.', example_ko_5 = '그는 카드로 식료품을 계산했어요.' WHERE id = 'w_shopping_A2_23';
UPDATE words SET example_en_2 = 'I spent too much on shoes this month.', example_ko_2 = '이번 달에 신발에 돈을 너무 많이 썼어요.', example_en_3 = 'How much did you spend at the market?', example_ko_3 = '시장에서 얼마를 썼어요?', example_en_4 = 'I don''t want to spend more than fifty dollars.', example_ko_4 = '50달러 이상은 쓰고 싶지 않아요.', example_en_5 = 'She spent hours looking for the right gift.', example_ko_5 = '그녀는 몇 시간 동안 적절한 선물을 찾았어요.' WHERE id = 'w_shopping_A2_24';
UPDATE words SET example_en_2 = 'Save money by buying in bulk.', example_ko_2 = '대량 구매로 돈을 절약하세요.', example_en_3 = 'I save my coupons for the big sale.', example_ko_3 = '큰 세일을 위해 쿠폰을 모아요.', example_en_4 = 'Use this app to save on your shopping.', example_ko_4 = '이 앱을 이용해 쇼핑을 절약하세요.', example_en_5 = 'She saved twenty dollars by using a code.', example_ko_5 = '그녀는 코드를 사용해 20달러를 절약했어요.' WHERE id = 'w_shopping_A2_25';
UPDATE words SET example_en_2 = 'The order will arrive in two days.', example_ko_2 = '주문은 이틀 후에 도착해요.', example_en_3 = 'Can I change my order after placing it?', example_ko_3 = '주문 후에도 변경할 수 있나요?', example_en_4 = 'I placed the order this morning.', example_ko_4 = '오늘 아침에 주문했어요.', example_en_5 = 'Your order number is on the confirmation email.', example_ko_5 = '주문 번호는 확인 이메일에 있어요.' WHERE id = 'w_shopping_A2_26';
UPDATE words SET example_en_2 = 'Is express delivery available?', example_ko_2 = '빠른 배송이 가능한가요?', example_en_3 = 'The delivery was delayed by one day.', example_ko_3 = '배송이 하루 지연됐어요.', example_en_4 = 'I paid extra for same-day delivery.', example_ko_4 = '당일 배송을 위해 추가 비용을 냈어요.', example_en_5 = 'Track your delivery on the website.', example_ko_5 = '웹사이트에서 배송을 추적하세요.' WHERE id = 'w_shopping_A2_27';
UPDATE words SET example_en_2 = 'Can you wrap this as a gift?', example_ko_2 = '선물용으로 포장해 주실 수 있나요?', example_en_3 = 'She wrapped the book in brown paper.', example_ko_3 = '그녀는 책을 갈색 종이로 포장했어요.', example_en_4 = 'Gift wrapping costs an extra two dollars.', example_ko_4 = '선물 포장은 2달러가 추가돼요.', example_en_5 = 'The items were carefully wrapped for shipping.', example_ko_5 = '배송을 위해 물건들이 꼼꼼하게 포장됐어요.' WHERE id = 'w_shopping_A2_28';
UPDATE words SET example_en_2 = 'The warranty covers defects for one year.', example_ko_2 = '보증은 1년 동안 결함을 커버해요.', example_en_3 = 'Is there a warranty on this laptop?', example_ko_3 = '이 노트북에 보증이 있나요?', example_en_4 = 'My warranty expired last month.', example_ko_4 = '제 보증이 지난달에 만료됐어요.', example_en_5 = 'You should register your warranty online.', example_ko_5 = '온라인으로 보증을 등록해야 해요.' WHERE id = 'w_shopping_A2_29';
UPDATE words SET example_en_2 = 'I need to return this coat — it doesn''t fit.', example_ko_2 = '이 코트를 반품해야 해요 — 맞지 않아요.', example_en_3 = 'What is the last day I can return this?', example_ko_3 = '마지막으로 반품할 수 있는 날이 언제예요?', example_en_4 = 'The return process was quick and easy.', example_ko_4 = '반품 절차가 빠르고 쉬웠어요.', example_en_5 = 'She returned the shoes because they were too tight.', example_ko_5 = '너무 작아서 신발을 반품했어요.' WHERE id = 'w_shopping_A2_30';
UPDATE words SET example_en_2 = 'The item arrived damaged in the post.', example_ko_2 = '우편으로 온 물건이 파손된 채로 도착했어요.', example_en_3 = 'Can I get a replacement for a damaged item?', example_ko_3 = '파손된 물건에 대해 교체품을 받을 수 있나요?', example_en_4 = 'The packaging was damaged but the product was fine.', example_ko_4 = '포장은 손상됐지만 제품 자체는 괜찮았어요.', example_en_5 = 'I found a damaged label on this bottle.', example_ko_5 = '이 병에 손상된 라벨이 있는 걸 발견했어요.' WHERE id = 'w_shopping_A2_31';
UPDATE words SET example_en_2 = 'Is this colour available in size small?', example_ko_2 = '이 색상이 스몰 사이즈로도 있나요?', example_en_3 = 'The item is available online only.', example_ko_3 = '그 상품은 온라인에서만 구입할 수 있어요.', example_en_4 = 'Is there a manager available to speak with?', example_ko_4 = '대화할 수 있는 매니저가 있나요?', example_en_5 = 'The product is available in three sizes.', example_ko_5 = '그 제품은 세 가지 사이즈로 구입할 수 있어요.' WHERE id = 'w_shopping_A2_32';
UPDATE words SET example_en_2 = 'We need to reorder stock urgently.', example_ko_2 = '재고를 긴급히 재주문해야 해요.', example_en_3 = 'The stock runs low on weekends.', example_ko_3 = '주말에는 재고가 부족해져요.', example_en_4 = 'Is this item in stock?', example_ko_4 = '이 품목이 재고가 있나요?', example_en_5 = 'They keep a good stock of popular sizes.', example_ko_5 = '그들은 인기 사이즈의 재고를 잘 유지해요.' WHERE id = 'w_shopping_A2_33';
UPDATE words SET example_en_2 = 'Are you a member of this store?', example_ko_2 = '이 매장 회원이세요?', example_en_3 = 'Members get early access to the sale.', example_ko_3 = '회원은 세일에 일찍 접근할 수 있어요.', example_en_4 = 'I signed up as a member to get discounts.', example_ko_4 = '할인을 받으려고 회원으로 가입했어요.', example_en_5 = 'Existing members get an extra ten percent off.', example_ko_5 = '기존 회원은 추가로 10%를 할인받아요.' WHERE id = 'w_shopping_A2_34';
UPDATE words SET example_en_2 = 'You get double points during the sale.', example_ko_2 = '세일 기간 중에는 포인트가 두 배로 쌓여요.', example_en_3 = 'How many points do I have on my account?', example_ko_3 = '제 계정에 포인트가 몇 점 있나요?', example_en_4 = 'Redeem your points at the checkout.', example_ko_4 = '계산할 때 포인트를 사용하세요.', example_en_5 = 'I collected enough points for a free item.', example_ko_5 = '무료 상품을 받을 수 있을 만큼 포인트를 모았어요.' WHERE id = 'w_shopping_A2_35';

-- ────────────────────────────────────────────────────────────
-- B1
-- ────────────────────────────────────────────────────────────
UPDATE words SET example_en_2 = 'That''s a real bargain at that price.', example_ko_2 = '그 가격이면 정말 저렴한 거예요.', example_en_3 = 'I found a bargain at the flea market.', example_ko_3 = '벼룩시장에서 싸게 살 수 있는 걸 찾았어요.', example_en_4 = 'Is there any room to get a bargain here?', example_ko_4 = '여기서 흥정할 여지가 있나요?', example_en_5 = 'She always finds a bargain when she shops.', example_ko_5 = '그녀는 쇼핑할 때 항상 저렴한 걸 찾아요.' WHERE id = 'w_shopping_B1_01';
UPDATE words SET example_en_2 = 'Is there a self-checkout available?', example_ko_2 = '셀프 계산대가 있나요?', example_en_3 = 'Please proceed to the checkout when ready.', example_ko_3 = '준비되시면 계산대로 가세요.', example_en_4 = 'The checkout queue was twenty minutes long.', example_ko_4 = '계산대 줄이 20분이나 됐어요.', example_en_5 = 'I forgot my bag at the checkout.', example_ko_5 = '계산대에 가방을 두고 왔어요.' WHERE id = 'w_shopping_B1_02';
UPDATE words SET example_en_2 = 'She likes to browse online before buying.', example_ko_2 = '그녀는 구매 전에 온라인을 둘러보는 걸 좋아해요.', example_en_3 = 'Feel free to browse as long as you like.', example_ko_3 = '원하시는 만큼 자유롭게 둘러보세요.', example_en_4 = 'I browsed three stores before deciding.', example_ko_4 = '결정하기 전에 세 곳을 둘러봤어요.', example_en_5 = 'He browsed the shelves without buying anything.', example_ko_5 = '그는 아무것도 사지 않고 선반을 둘러봤어요.' WHERE id = 'w_shopping_B1_03';
UPDATE words SET example_en_2 = 'Wholesale prices are much lower than retail.', example_ko_2 = '도매 가격은 소매보다 훨씬 저렴해요.', example_en_3 = 'She buys clothes wholesale and resells them.', example_ko_3 = '그녀는 옷을 도매로 사서 되팔아요.', example_en_4 = 'Is there a wholesale market nearby?', example_ko_4 = '근처에 도매 시장이 있나요?', example_en_5 = 'You need a licence to buy at wholesale rates.', example_ko_5 = '도매 가격으로 구매하려면 허가증이 필요해요.' WHERE id = 'w_shopping_B1_04';
UPDATE words SET example_en_2 = 'Retail prices are set by the manufacturer.', example_ko_2 = '소매 가격은 제조사가 정해요.', example_en_3 = 'She works in retail management.', example_ko_3 = '그녀는 소매 관리 분야에서 일해요.', example_en_4 = 'The retail sector has changed a lot online.', example_ko_4 = '소매 분야는 온라인으로 많이 바뀌었어요.', example_en_5 = 'Retail stores often have seasonal sales.', example_ko_5 = '소매점은 보통 계절별 세일을 해요.' WHERE id = 'w_shopping_B1_05';
UPDATE words SET example_en_2 = 'I have a coupon for twenty percent off.', example_ko_2 = '20% 할인 쿠폰이 있어요.', example_en_3 = 'Can I use more than one coupon?', example_ko_3 = '쿠폰을 두 개 이상 사용할 수 있나요?', example_en_4 = 'The coupon expires at the end of the month.', example_ko_4 = '쿠폰은 이달 말에 만료돼요.', example_en_5 = 'She downloaded a coupon from the app.', example_ko_5 = '그녀는 앱에서 쿠폰을 다운로드했어요.' WHERE id = 'w_shopping_B1_06';
UPDATE words SET example_en_2 = 'Their loyalty programme offers great rewards.', example_ko_2 = '그들의 로열티 프로그램은 훌륭한 보상을 제공해요.', example_en_3 = 'I joined the loyalty scheme to earn points.', example_ko_3 = '포인트를 쌓으려고 로열티 제도에 가입했어요.', example_en_4 = 'Brand loyalty is hard to build.', example_ko_4 = '브랜드 충성도를 쌓기는 어려워요.', example_en_5 = 'Do you reward customer loyalty with discounts?', example_ko_5 = '고객 충성도에 대한 보상으로 할인을 제공하나요?' WHERE id = 'w_shopping_B1_07';
UPDATE words SET example_en_2 = 'Please send me an invoice by email.', example_ko_2 = '이메일로 청구서를 보내주세요.', example_en_3 = 'The invoice shows all items purchased.', example_ko_3 = '청구서에 구매한 모든 항목이 나와 있어요.', example_en_4 = 'I need an invoice for my expense report.', example_ko_4 = '경비 보고서를 위해 청구서가 필요해요.', example_en_5 = 'When will you issue the invoice?', example_ko_5 = '청구서는 언제 발행되나요?' WHERE id = 'w_shopping_B1_08';
UPDATE words SET example_en_2 = 'Which vendor has the best prices here?', example_ko_2 = '여기서 어느 판매자가 가격이 제일 좋아요?', example_en_3 = 'The market has over a hundred vendors.', example_ko_3 = '그 시장에는 100명 이상의 판매자가 있어요.', example_en_4 = 'We need to find a reliable vendor for these goods.', example_ko_4 = '이 상품들을 위한 믿을 수 있는 공급업체를 찾아야 해요.', example_en_5 = 'The vendor offered a bulk discount.', example_ko_5 = '판매자가 대량 할인을 제안했어요.' WHERE id = 'w_shopping_B1_09';
UPDATE words SET example_en_2 = 'He tried to negotiate a lower price.', example_ko_2 = '그는 더 낮은 가격을 협상하려고 했어요.', example_en_3 = 'Can we negotiate the delivery terms?', example_ko_3 = '배송 조건을 협상할 수 있나요?', example_en_4 = 'She negotiated a ten percent discount.', example_ko_4 = '그녀는 10% 할인을 협상했어요.', example_en_5 = 'It''s always worth trying to negotiate.', example_ko_5 = '항상 협상을 시도해볼 가치가 있어요.' WHERE id = 'w_shopping_B1_10';
UPDATE words SET example_en_2 = 'My monthly shopping budget is fixed.', example_ko_2 = '제 월별 쇼핑 예산은 정해져 있어요.', example_en_3 = 'We need to work within a tight budget.', example_ko_3 = '빠듯한 예산 안에서 일해야 해요.', example_en_4 = 'She set a strict budget for the holiday shopping.', example_ko_4 = '그녀는 명절 쇼핑을 위해 엄격한 예산을 정했어요.', example_en_5 = 'There are great options even on a small budget.', example_ko_5 = '적은 예산으로도 훌륭한 선택지가 있어요.' WHERE id = 'w_shopping_B1_11';
UPDATE words SET example_en_2 = 'A price comparison can save you a lot.', example_ko_2 = '가격 비교를 하면 많은 돈을 절약할 수 있어요.', example_en_3 = 'Use a comparison website to find the best deal.', example_ko_3 = '비교 웹사이트를 이용해서 최고의 가격을 찾아보세요.', example_en_4 = 'The comparison showed a big price difference.', example_ko_4 = '비교를 해보니 가격 차이가 컸어요.', example_en_5 = 'She did a careful comparison before buying.', example_ko_5 = '그녀는 구매 전에 꼼꼼하게 비교했어요.' WHERE id = 'w_shopping_B1_12';
UPDATE words SET example_en_2 = 'The purchase was made online last night.', example_ko_2 = '구매는 어젯밤 온라인으로 이루어졌어요.', example_en_3 = 'Can I cancel a purchase after confirming?', example_ko_3 = '확인 후에도 구매를 취소할 수 있나요?', example_en_4 = 'The purchase price includes delivery.', example_ko_4 = '구매 가격에 배송비가 포함돼 있어요.', example_en_5 = 'This purchase qualifies for a free gift.', example_ko_5 = '이 구매는 무료 선물 대상이에요.' WHERE id = 'w_shopping_B1_13';
UPDATE words SET example_en_2 = 'Every transaction is recorded digitally.', example_ko_2 = '모든 거래는 디지털로 기록돼요.', example_en_3 = 'The transaction failed due to a network error.', example_ko_3 = '네트워크 오류로 거래가 실패했어요.', example_en_4 = 'Please confirm the transaction amount.', example_ko_4 = '거래 금액을 확인해 주세요.', example_en_5 = 'The transaction was completed in seconds.', example_ko_5 = '거래가 몇 초 만에 완료됐어요.' WHERE id = 'w_shopping_B1_14';
UPDATE words SET example_en_2 = 'You can pay in six monthly installments.', example_ko_2 = '6개월 할부로 납부할 수 있어요.', example_en_3 = 'Is an installment plan available for this product?', example_ko_3 = '이 제품에 할부 플랜이 가능한가요?', example_en_4 = 'She paid for the fridge in installments.', example_ko_4 = '그녀는 냉장고를 할부로 납부했어요.', example_en_5 = 'The final installment is due next month.', example_ko_5 = '마지막 할부금은 다음 달이 기한이에요.' WHERE id = 'w_shopping_B1_15';
UPDATE words SET example_en_2 = 'Standard shipping takes three to five days.', example_ko_2 = '일반 배송은 3~5일이 걸려요.', example_en_3 = 'Shipping is free on orders over thirty dollars.', example_ko_3 = '30달러 이상 주문 시 배송비가 무료예요.', example_en_4 = 'What are the shipping options available?', example_ko_4 = '어떤 배송 옵션이 있나요?', example_en_5 = 'International shipping may take longer.', example_ko_5 = '국제 배송은 더 오래 걸릴 수 있어요.' WHERE id = 'w_shopping_B1_16';
UPDATE words SET example_en_2 = 'You can use the tracking number to follow your parcel.', example_ko_2 = '운송장 번호로 소포를 추적할 수 있어요.', example_en_3 = 'Tracking shows the parcel is out for delivery.', example_ko_3 = '추적을 보니 소포가 배송 중이에요.', example_en_4 = 'I set up tracking alerts on my phone.', example_ko_4 = '휴대폰에 배송 추적 알림을 설정했어요.', example_en_5 = 'Does your store offer real-time tracking?', example_ko_5 = '매장에서 실시간 추적 서비스를 제공하나요?' WHERE id = 'w_shopping_B1_17';
UPDATE words SET example_en_2 = 'I have a monthly subscription to that service.', example_ko_2 = '그 서비스에 월 구독권이 있어요.', example_en_3 = 'The subscription renews automatically each month.', example_ko_3 = '구독은 매달 자동으로 갱신돼요.', example_en_4 = 'Cancel your subscription before the trial ends.', example_ko_4 = '체험 기간이 끝나기 전에 구독을 취소하세요.', example_en_5 = 'A yearly subscription is cheaper than monthly.', example_ko_5 = '연간 구독이 월별보다 더 저렴해요.' WHERE id = 'w_shopping_B1_18';
UPDATE words SET example_en_2 = 'Buying in bulk saves a lot of money.', example_ko_2 = '대량 구매를 하면 돈을 많이 절약할 수 있어요.', example_en_3 = 'They offer a discount for bulk orders.', example_ko_3 = '대량 주문에는 할인을 제공해요.', example_en_4 = 'We bought paper towels in bulk at the warehouse.', example_ko_4 = '창고형 마트에서 페이퍼 타월을 대량으로 샀어요.', example_en_5 = 'Bulk purchasing reduces the cost per unit.', example_ko_5 = '대량 구매는 단가를 낮춰줘요.' WHERE id = 'w_shopping_B1_19';
UPDATE words SET example_en_2 = 'I prefer buying second-hand to save money.', example_ko_2 = '돈을 절약하기 위해 중고 구매를 선호해요.', example_en_3 = 'This second-hand jacket is in perfect condition.', example_ko_3 = '이 중고 재킷은 상태가 아주 좋아요.', example_en_4 = 'She sells second-hand clothes online.', example_ko_4 = '그녀는 온라인으로 중고 옷을 팔아요.', example_en_5 = 'The second-hand market is growing fast.', example_ko_5 = '중고 시장이 빠르게 성장하고 있어요.' WHERE id = 'w_shopping_B1_20';
UPDATE words SET example_en_2 = 'This brand has an outlet in the city centre.', example_ko_2 = '이 브랜드는 도심에 아웃렛이 있어요.', example_en_3 = 'Outlet prices are lower than regular stores.', example_ko_3 = '아웃렛 가격은 일반 매장보다 저렴해요.', example_en_4 = 'I found amazing deals at the outlet mall.', example_ko_4 = '아웃렛 몰에서 엄청난 거래를 발견했어요.', example_en_5 = 'Is there a factory outlet near here?', example_ko_5 = '근처에 팩토리 아웃렛이 있나요?' WHERE id = 'w_shopping_B1_21';
UPDATE words SET example_en_2 = 'I made an impulse purchase at the airport.', example_ko_2 = '공항에서 충동구매를 했어요.', example_en_3 = 'Try to resist impulse buys at the checkout.', example_ko_3 = '계산대에서 충동 구매를 참으려고 해요.', example_en_4 = 'That was a complete impulse — I didn''t plan it.', example_ko_4 = '그건 완전한 충동이었어요 — 계획에 없었어요.', example_en_5 = 'Shops place candy near checkout to trigger impulse buys.', example_ko_5 = '상점들은 충동 구매를 유발하려고 계산대 근처에 사탕을 놓아요.' WHERE id = 'w_shopping_B1_22';
UPDATE words SET example_en_2 = 'I''d like to make a complaint about my order.', example_ko_2 = '주문에 대해 불만을 제기하고 싶어요.', example_en_3 = 'She filed a complaint with the manager.', example_ko_3 = '그녀는 매니저에게 불만을 제기했어요.', example_en_4 = 'How do I submit a formal complaint?', example_ko_4 = '공식 불만은 어떻게 제출하나요?', example_en_5 = 'His complaint was resolved within two days.', example_ko_5 = '그의 불만은 이틀 안에 해결됐어요.' WHERE id = 'w_shopping_B1_23';
UPDATE words SET example_en_2 = 'Does this product come with a guarantee?', example_ko_2 = '이 제품에 품질 보증이 포함되어 있나요?', example_en_3 = 'The guarantee covers parts and labour.', example_ko_3 = '보증은 부품과 인건비를 포함해요.', example_en_4 = 'I have a money-back guarantee if not satisfied.', example_ko_4 = '만족하지 않으면 환불 보증이 있어요.', example_en_5 = 'The two-year guarantee gave me confidence to buy.', example_ko_5 = '2년 보증이 있어서 안심하고 구매했어요.' WHERE id = 'w_shopping_B1_24';
UPDATE words SET example_en_2 = 'They''re selling off surplus stock at half price.', example_ko_2 = '잉여 재고를 반값에 팔고 있어요.', example_en_3 = 'The warehouse had a surplus of winter coats.', example_ko_3 = '창고에 겨울 코트 잉여분이 있었어요.', example_en_4 = 'A budget surplus allowed them to lower prices.', example_ko_4 = '예산 잉여분이 생겨서 가격을 낮출 수 있었어요.', example_en_5 = 'The surplus was donated to charity.', example_ko_5 = '잉여분은 자선단체에 기부됐어요.' WHERE id = 'w_shopping_B1_25';
UPDATE words SET example_en_2 = 'The clearance sale ends this Sunday.', example_ko_2 = '재고 처분 세일은 이번 일요일에 끝나요.', example_en_3 = 'I got these shoes in the clearance section.', example_ko_3 = '이 신발을 재고 처분 코너에서 샀어요.', example_en_4 = 'Clearance items cannot be returned.', example_ko_4 = '재고 처분 상품은 반품이 안 돼요.', example_en_5 = 'She always checks the clearance rack first.', example_ko_5 = '그녀는 항상 재고 처분 진열대를 먼저 확인해요.' WHERE id = 'w_shopping_B1_26';
UPDATE words SET example_en_2 = 'The merchant offered a fifteen percent deal.', example_ko_2 = '판매자가 15% 할인을 제안했어요.', example_en_3 = 'Several merchants were selling similar goods.', example_ko_3 = '여러 판매자가 비슷한 상품을 팔고 있었어요.', example_en_4 = 'Is this merchant authorised to sell this brand?', example_ko_4 = '이 판매자가 이 브랜드를 판매할 권한이 있나요?', example_en_5 = 'She became a licensed merchant last year.', example_ko_5 = '그녀는 작년에 공인 판매자가 됐어요.' WHERE id = 'w_shopping_B1_27';
UPDATE words SET example_en_2 = 'The checkout process only takes a minute.', example_ko_2 = '결제 과정은 1분밖에 안 걸려요.', example_en_3 = 'The online checkout process was very smooth.', example_ko_3 = '온라인 결제 과정이 매우 매끄러웠어요.', example_en_4 = 'The checkout process requires a valid ID.', example_ko_4 = '결제 과정에 유효한 신분증이 필요해요.', example_en_5 = 'Can you simplify your checkout process?', example_ko_5 = '결제 과정을 간소화할 수 있나요?' WHERE id = 'w_shopping_B1_28';
UPDATE words SET example_en_2 = 'High demand caused prices to rise quickly.', example_ko_2 = '높은 수요로 인해 가격이 빠르게 올랐어요.', example_en_3 = 'There is a huge demand for this product.', example_ko_3 = '이 제품에 대한 수요가 엄청나요.', example_en_4 = 'We couldn''t keep up with demand during the sale.', example_ko_4 = '세일 기간 동안 수요를 따라가지 못했어요.', example_en_5 = 'Demand for eco-friendly products is growing.', example_ko_5 = '친환경 제품에 대한 수요가 증가하고 있어요.' WHERE id = 'w_shopping_B1_29';
UPDATE words SET example_en_2 = 'Supply was limited, so prices went up.', example_ko_2 = '공급이 제한적이어서 가격이 올랐어요.', example_en_3 = 'The supply chain was disrupted by the weather.', example_ko_3 = '날씨로 인해 공급망이 차질을 빚었어요.', example_en_4 = 'We need to increase supply to meet demand.', example_ko_4 = '수요를 충족하기 위해 공급을 늘려야 해요.', example_en_5 = 'The company has a reliable supply of materials.', example_ko_5 = '그 회사는 안정적인 원자재 공급처가 있어요.' WHERE id = 'w_shopping_B1_30';
UPDATE words SET example_en_2 = 'The promotion ends at midnight tonight.', example_ko_2 = '프로모션은 오늘 자정에 종료돼요.', example_en_3 = 'They ran a buy-one-get-one promotion.', example_ko_3 = '하나 사면 하나 무료 프로모션을 진행했어요.', example_en_4 = 'Sign up for emails to receive promotion alerts.', example_ko_4 = '프로모션 알림을 받으려면 이메일을 등록하세요.', example_en_5 = 'The promotion attracted thousands of customers.', example_ko_5 = '그 프로모션은 수천 명의 고객을 끌어들였어요.' WHERE id = 'w_shopping_B1_31';
UPDATE words SET example_en_2 = 'The advertisement was misleading.', example_ko_2 = '그 광고는 오해의 소지가 있었어요.', example_en_3 = 'I saw an advertisement for this product online.', example_ko_3 = '온라인에서 이 제품 광고를 봤어요.', example_en_4 = 'The advertisement made me want to buy it.', example_ko_4 = '그 광고를 보고 사고 싶어졌어요.', example_en_5 = 'Effective advertisements boost sales significantly.', example_ko_5 = '효과적인 광고는 매출을 크게 올려줘요.' WHERE id = 'w_shopping_B1_32';
UPDATE words SET example_en_2 = 'The artist sells her work on consignment.', example_ko_2 = '그 예술가는 위탁 판매로 작품을 팔아요.', example_en_3 = 'We took the furniture on consignment from the seller.', example_ko_3 = '우리는 판매자로부터 가구를 위탁받았어요.', example_en_4 = 'Consignment shops sell goods for a percentage of the price.', example_ko_4 = '위탁 판매점은 가격의 일부를 받고 물건을 팔아요.', example_en_5 = 'This coat is on consignment from a local designer.', example_ko_5 = '이 코트는 지역 디자이너의 위탁 상품이에요.' WHERE id = 'w_shopping_B1_33';
UPDATE words SET example_en_2 = 'The price tag was missing from the shelf.', example_ko_2 = '선반에 가격표가 없었어요.', example_en_3 = 'Always check the price tag before buying.', example_ko_3 = '구매 전에 항상 가격표를 확인하세요.', example_en_4 = 'The price tag says thirty, but I got it for twenty.', example_ko_4 = '가격표는 30이라고 나와 있지만 20에 샀어요.', example_en_5 = 'She removed the price tag before giving the gift.', example_ko_5 = '선물하기 전에 가격표를 뗐어요.' WHERE id = 'w_shopping_B1_34';
UPDATE words SET example_en_2 = 'As an afterthought, I grabbed a bottle of water.', example_ko_2 = '나중에 생각나서 물 한 병을 집어들었어요.', example_en_3 = 'Adding the warranty was almost an afterthought.', example_ko_3 = '보증을 추가한 건 거의 나중에 생각난 거였어요.', example_en_4 = 'She bought a card as an afterthought on the way out.', example_ko_4 = '나가는 길에 나중에 생각나서 카드를 샀어요.', example_en_5 = 'Don''t treat customer service as an afterthought.', example_ko_5 = '고객 서비스를 나중에 생각할 일로 취급하지 마세요.' WHERE id = 'w_shopping_B1_35';

-- ────────────────────────────────────────────────────────────
-- B2
-- ────────────────────────────────────────────────────────────
UPDATE words SET example_en_2 = 'The markup on designer goods is very high.', example_ko_2 = '명품의 마크업은 매우 높아요.', example_en_3 = 'A fifty percent markup is standard in retail.', example_ko_3 = '소매에서 50% 마크업은 표준이에요.', example_en_4 = 'The markup covers overhead costs.', example_ko_4 = '마크업은 간접 비용을 충당해요.', example_en_5 = 'High markup doesn''t always mean high profit.', example_ko_5 = '높은 마크업이 항상 높은 이익을 의미하지는 않아요.' WHERE id = 'w_shopping_B2_01';
UPDATE words SET example_en_2 = 'They target a niche market of eco-conscious shoppers.', example_ko_2 = '그들은 친환경 소비자라는 틈새 시장을 공략해요.', example_en_3 = 'Finding your niche can make a business very successful.', example_ko_3 = '틈새를 찾으면 사업을 매우 성공적으로 만들 수 있어요.', example_en_4 = 'It''s a niche product with a loyal following.', example_ko_4 = '충성 팬층이 있는 틈새 제품이에요.', example_en_5 = 'The brand carved out a niche in sustainable fashion.', example_ko_5 = '그 브랜드는 지속 가능한 패션 분야에서 틈새를 개척했어요.' WHERE id = 'w_shopping_B2_02';
UPDATE words SET example_en_2 = 'This hotel offers a premium service package.', example_ko_2 = '이 호텔은 프리미엄 서비스 패키지를 제공해요.', example_en_3 = 'Premium products justify their higher price.', example_ko_3 = '프리미엄 제품은 더 높은 가격을 정당화해요.', example_en_4 = 'She always chooses the premium option.', example_ko_4 = '그녀는 항상 프리미엄 옵션을 선택해요.', example_en_5 = 'The premium range is sold in flagship stores only.', example_ko_5 = '프리미엄 라인은 플래그십 매장에서만 판매돼요.' WHERE id = 'w_shopping_B2_03';
UPDATE words SET example_en_2 = 'Is this bag authentic or a copy?', example_ko_2 = '이 가방은 정품인가요, 아니면 복제품인가요?', example_en_3 = 'They only sell authentic goods with certificates.', example_ko_3 = '그들은 인증서가 있는 정품만 판매해요.', example_en_4 = 'The authentic version costs three times more.', example_ko_4 = '정품은 세 배 더 비싸요.', example_en_5 = 'How can I tell if this is authentic?', example_ko_5 = '이게 정품인지 어떻게 알 수 있나요?' WHERE id = 'w_shopping_B2_04';
UPDATE words SET example_en_2 = 'Be careful — that market sells counterfeit goods.', example_ko_2 = '조심하세요 — 저 시장은 위조품을 팔아요.', example_en_3 = 'The customs officer seized counterfeit items.', example_ko_3 = '세관원이 위조 품목을 압수했어요.', example_en_4 = 'Buying counterfeit goods is illegal in most countries.', example_ko_4 = '대부분의 나라에서 위조품 구매는 불법이에요.', example_en_5 = 'She unknowingly bought a counterfeit watch.', example_ko_5 = '그녀는 자기도 모르게 위조 시계를 샀어요.' WHERE id = 'w_shopping_B2_05';
UPDATE words SET example_en_2 = 'The procurement department handles all supplier contracts.', example_ko_2 = '조달 부서에서 모든 공급업체 계약을 처리해요.', example_en_3 = 'Efficient procurement reduces overall costs.', example_ko_3 = '효율적인 조달은 전체 비용을 줄여줘요.', example_en_4 = 'She works in procurement for a retail chain.', example_ko_4 = '그녀는 소매 체인의 조달 부서에서 일해요.', example_en_5 = 'The procurement process was delayed by the audit.', example_ko_5 = '감사로 인해 조달 과정이 지연됐어요.' WHERE id = 'w_shopping_B2_06';
UPDATE words SET example_en_2 = 'Modern consumerism encourages overconsumption.', example_ko_2 = '현대 소비주의는 과소비를 부추겨요.', example_en_3 = 'Consumerism drives economic growth but creates waste.', example_ko_3 = '소비주의는 경제 성장을 이끌지만 낭비를 낳아요.', example_en_4 = 'She wrote her thesis on consumerism and identity.', example_ko_4 = '그녀는 소비주의와 정체성에 관한 논문을 썼어요.', example_en_5 = 'Minimalism is a response to consumerism.', example_ko_5 = '미니멀리즘은 소비주의에 대한 반응이에요.' WHERE id = 'w_shopping_B2_07';
UPDATE words SET example_en_2 = 'Impulse buying often leads to regret.', example_ko_2 = '충동구매는 종종 후회로 이어져요.', example_en_3 = 'Shops are designed to encourage impulse buying.', example_ko_3 = '매장은 충동구매를 유도하도록 설계되어 있어요.', example_en_4 = 'I''m trying to reduce my impulse buying habits.', example_ko_4 = '충동구매 습관을 줄이려고 노력 중이에요.', example_en_5 = 'Impulse buying accounts for a large share of sales.', example_ko_5 = '충동구매가 매출의 상당 부분을 차지해요.' WHERE id = 'w_shopping_B2_08';
UPDATE words SET example_en_2 = 'Price elasticity measures how demand changes with price.', example_ko_2 = '가격 탄력성은 가격 변화에 따른 수요 변화를 측정해요.', example_en_3 = 'Luxury goods tend to have low price elasticity.', example_ko_3 = '명품은 가격 탄력성이 낮은 편이에요.', example_en_4 = 'High price elasticity means consumers are very price-sensitive.', example_ko_4 = '가격 탄력성이 높다는 것은 소비자가 가격에 민감하다는 뜻이에요.', example_en_5 = 'The economist studied the price elasticity of staple goods.', example_ko_5 = '경제학자는 필수품의 가격 탄력성을 연구했어요.' WHERE id = 'w_shopping_B2_09';
UPDATE words SET example_en_2 = 'This product offers great value for money.', example_ko_2 = '이 제품은 가성비가 정말 좋아요.', example_en_3 = 'Always check if something is value for money before buying.', example_ko_3 = '구매 전에 항상 가성비를 확인하세요.', example_en_4 = 'Budget brands often offer better value for money.', example_ko_4 = '저가 브랜드가 종종 더 좋은 가성비를 제공해요.', example_en_5 = 'The service wasn''t value for money at all.', example_ko_5 = '그 서비스는 전혀 가성비가 없었어요.' WHERE id = 'w_shopping_B2_10';
UPDATE words SET example_en_2 = 'Comparison shopping helps you find the lowest price.', example_ko_2 = '비교 쇼핑은 최저가를 찾는 데 도움이 돼요.', example_en_3 = 'I spent an hour doing comparison shopping online.', example_ko_3 = '온라인으로 한 시간 동안 비교 쇼핑을 했어요.', example_en_4 = 'Comparison shopping apps make it easy to check prices.', example_ko_4 = '비교 쇼핑 앱으로 가격 확인이 쉬워요.', example_en_5 = 'Do some comparison shopping before you commit.', example_ko_5 = '결정하기 전에 비교 쇼핑을 해보세요.' WHERE id = 'w_shopping_B2_11';
UPDATE words SET example_en_2 = 'The salesperson tried to upsell me on a warranty.', example_ko_2 = '판매원이 저에게 보증 업셀을 시도했어요.', example_en_3 = 'Upselling is a common strategy to increase revenue.', example_ko_3 = '업셀은 수익을 늘리기 위한 일반적인 전략이에요.', example_en_4 = 'Can you upsell customers without being pushy?', example_ko_4 = '강요하지 않고도 고객에게 업셀을 할 수 있나요?', example_en_5 = 'The waiter upsold us on the premium wine.', example_ko_5 = '웨이터가 저희에게 프리미엄 와인을 업셀했어요.' WHERE id = 'w_shopping_B2_12';
UPDATE words SET example_en_2 = 'The website used cross-sell suggestions effectively.', example_ko_2 = '그 웹사이트는 교차 판매 제안을 효과적으로 활용했어요.', example_en_3 = 'Cross-sell complementary products to increase basket size.', example_ko_3 = '장바구니 규모를 늘리기 위해 보완 제품을 교차 판매하세요.', example_en_4 = 'Staff are trained to cross-sell related items.', example_ko_4 = '직원들은 관련 상품을 교차 판매하도록 교육받아요.', example_en_5 = 'Cross-sell strategies boosted their average order value.', example_ko_5 = '교차 판매 전략으로 평균 주문 금액이 올랐어요.' WHERE id = 'w_shopping_B2_13';
UPDATE words SET example_en_2 = 'I think they overcharged me by ten dollars.', example_ko_2 = '10달러를 더 청구한 것 같아요.', example_en_3 = 'Don''t let them overcharge you for delivery.', example_ko_3 = '배송비를 과도하게 청구하도록 내버려두지 마세요.', example_en_4 = 'The hotel overcharged us for the minibar.', example_ko_4 = '호텔에서 미니바 요금을 과도하게 청구했어요.', example_en_5 = 'Always check your bill to avoid being overcharged.', example_ko_5 = '과다 청구를 피하려면 항상 영수증을 확인하세요.' WHERE id = 'w_shopping_B2_14';
UPDATE words SET example_en_2 = 'I claimed a rebate after submitting the form online.', example_ko_2 = '온라인으로 양식을 제출한 후 리베이트를 청구했어요.', example_en_3 = 'The rebate was credited to my account within a week.', example_ko_3 = '리베이트가 일주일 안에 계정에 입금됐어요.', example_en_4 = 'Is there a mail-in rebate available for this product?', example_ko_4 = '이 제품에 우편 리베이트가 가능한가요?', example_en_5 = 'A tax rebate reduced the overall cost significantly.', example_ko_5 = '세금 환급으로 전체 비용이 크게 줄었어요.' WHERE id = 'w_shopping_B2_15';
UPDATE words SET example_en_2 = 'A fuel surcharge was added to the delivery cost.', example_ko_2 = '배송비에 연료 할증료가 추가됐어요.', example_en_3 = 'There''s a surcharge for paying by credit card.', example_ko_3 = '신용카드로 결제하면 할증료가 붙어요.', example_en_4 = 'Weekend service includes a small surcharge.', example_ko_4 = '주말 서비스에는 소액의 할증료가 포함돼요.', example_en_5 = 'Ask about any hidden surcharges before agreeing.', example_ko_5 = '동의하기 전에 숨겨진 할증료가 있는지 물어보세요.' WHERE id = 'w_shopping_B2_16';
UPDATE words SET example_en_2 = 'Import tariffs made those products more expensive.', example_ko_2 = '수입 관세로 인해 그 제품들이 더 비싸졌어요.', example_en_3 = 'The government raised tariffs on foreign goods.', example_ko_3 = '정부가 외국 상품에 대한 관세를 올렸어요.', example_en_4 = 'A high tariff protects domestic manufacturers.', example_ko_4 = '높은 관세는 국내 제조업체를 보호해요.', example_en_5 = 'Trade disputes often involve disputes over tariffs.', example_ko_5 = '무역 분쟁은 종종 관세 분쟁을 수반해요.' WHERE id = 'w_shopping_B2_17';
UPDATE words SET example_en_2 = 'Understanding consumer behaviour helps businesses grow.', example_ko_2 = '소비자 행동을 이해하면 사업 성장에 도움이 돼요.', example_en_3 = 'Consumer behaviour has shifted dramatically online.', example_ko_3 = '소비자 행동이 온라인 쪽으로 크게 변화했어요.', example_en_4 = 'She studied consumer behaviour at university.', example_ko_4 = '그녀는 대학에서 소비자 행동을 공부했어요.', example_en_5 = 'Social media influences consumer behaviour significantly.', example_ko_5 = '소셜 미디어는 소비자 행동에 크게 영향을 미쳐요.' WHERE id = 'w_shopping_B2_18';
UPDATE words SET example_en_2 = 'The profit margin on electronics is thin.', example_ko_2 = '전자제품의 이익 마진은 얇아요.', example_en_3 = 'They managed to increase their profit margin by ten percent.', example_ko_3 = '그들은 이익 마진을 10% 늘리는 데 성공했어요.', example_en_4 = 'A healthy profit margin keeps the business stable.', example_ko_4 = '건전한 이익 마진은 사업을 안정적으로 유지시켜요.', example_en_5 = 'Rising costs are squeezing our profit margin.', example_ko_5 = '비용 상승으로 이익 마진이 줄고 있어요.' WHERE id = 'w_shopping_B2_19';
UPDATE words SET example_en_2 = 'Many customers still prefer brick-and-mortar stores.', example_ko_2 = '많은 고객들이 여전히 오프라인 매장을 선호해요.', example_en_3 = 'Brick-and-mortar retail faces tough competition online.', example_ko_3 = '오프라인 소매업은 온라인의 치열한 경쟁에 직면해 있어요.', example_en_4 = 'They opened a brick-and-mortar store after years online.', example_ko_4 = '수년간의 온라인 운영 후 오프라인 매장을 열었어요.', example_en_5 = 'Brick-and-mortar shops offer a tactile shopping experience.', example_ko_5 = '오프라인 매장은 직접 만져볼 수 있는 쇼핑 경험을 제공해요.' WHERE id = 'w_shopping_B2_20';
UPDATE words SET example_en_2 = 'E-commerce has transformed the way we shop.', example_ko_2 = '전자상거래는 우리의 쇼핑 방식을 바꿔놨어요.', example_en_3 = 'She launched an e-commerce store last year.', example_ko_3 = '그녀는 작년에 전자상거래 매장을 열었어요.', example_en_4 = 'E-commerce sales grow rapidly every year.', example_ko_4 = '전자상거래 매출은 매년 빠르게 성장해요.', example_en_5 = 'Good e-commerce design improves conversion rates.', example_ko_5 = '좋은 전자상거래 디자인은 전환율을 높여요.' WHERE id = 'w_shopping_B2_21';
UPDATE words SET example_en_2 = 'Disruptions in the supply chain caused shortages.', example_ko_2 = '공급망 차질로 인해 부족 현상이 발생했어요.', example_en_3 = 'A transparent supply chain builds consumer trust.', example_ko_3 = '투명한 공급망은 소비자 신뢰를 쌓아요.', example_en_4 = 'They audited the entire supply chain for sustainability.', example_ko_4 = '그들은 지속 가능성을 위해 전체 공급망을 감사했어요.', example_en_5 = 'Managing the supply chain efficiently cuts costs.', example_ko_5 = '공급망을 효율적으로 관리하면 비용이 줄어요.' WHERE id = 'w_shopping_B2_22';
UPDATE words SET example_en_2 = 'The inventory was counted at the end of the month.', example_ko_2 = '재고는 월말에 집계됐어요.', example_en_3 = 'We need to update our inventory system.', example_ko_3 = '재고 시스템을 업데이트해야 해요.', example_en_4 = 'A full inventory check takes all day.', example_ko_4 = '전체 재고 확인은 하루 종일 걸려요.', example_en_5 = 'Out-of-date inventory data leads to stockouts.', example_ko_5 = '최신화되지 않은 재고 데이터는 품절로 이어져요.' WHERE id = 'w_shopping_B2_23';
UPDATE words SET example_en_2 = 'Seasonal items go on sale after the holiday.', example_ko_2 = '시즌 상품은 명절 이후에 세일해요.', example_en_3 = 'The store gets very busy during the seasonal rush.', example_ko_3 = '매장은 시즌 성수기에 매우 바빠져요.', example_en_4 = 'Seasonal trends affect what people buy.', example_ko_4 = '계절적 트렌드는 사람들의 구매에 영향을 미쳐요.', example_en_5 = 'They release seasonal collections twice a year.', example_ko_5 = '그들은 1년에 두 번 시즌 컬렉션을 출시해요.' WHERE id = 'w_shopping_B2_24';
UPDATE words SET example_en_2 = 'The flagship store opened on Fifth Avenue.', example_ko_2 = '플래그십 스토어가 5번가에 문을 열었어요.', example_en_3 = 'The flagship product defines the brand''s identity.', example_ko_3 = '플래그십 제품은 브랜드의 정체성을 정의해요.', example_en_4 = 'They launched a flagship phone with premium features.', example_ko_4 = '프리미엄 기능을 갖춘 플래그십 폰을 출시했어요.', example_en_5 = 'A flagship store often showcases the full product range.', example_ko_5 = '플래그십 스토어는 종종 전체 제품 라인을 선보여요.' WHERE id = 'w_shopping_B2_25';
UPDATE words SET example_en_2 = 'The local currency is the best to use here.', example_ko_2 = '여기서는 현지 통화를 쓰는 게 가장 좋아요.', example_en_3 = 'I need to exchange currency at the airport.', example_ko_3 = '공항에서 환전을 해야 해요.', example_en_4 = 'Which currency do they accept here?', example_ko_4 = '여기서 어떤 통화를 받나요?', example_en_5 = 'The price is listed in the local currency.', example_ko_5 = '가격은 현지 통화로 표시되어 있어요.' WHERE id = 'w_shopping_B2_26';
UPDATE words SET example_en_2 = 'Check the exchange rate before converting money.', example_ko_2 = '돈을 환전하기 전에 환율을 확인하세요.', example_en_3 = 'A poor exchange rate can make shopping expensive.', example_ko_3 = '불리한 환율은 쇼핑 비용을 높일 수 있어요.', example_en_4 = 'The exchange rate is more favourable this week.', example_ko_4 = '이번 주 환율이 더 유리해요.', example_en_5 = 'I use an app to track the exchange rate.', example_ko_5 = '환율을 추적하는 앱을 이용해요.' WHERE id = 'w_shopping_B2_27';
UPDATE words SET example_en_2 = 'Their loyalty programme rewards frequent shoppers.', example_ko_2 = '그들의 로열티 프로그램은 단골 고객에게 보상해요.', example_en_3 = 'The loyalty programme offers exclusive discounts.', example_ko_3 = '로열티 프로그램은 전용 할인을 제공해요.', example_en_4 = 'I collect points through their loyalty programme.', example_ko_4 = '그들의 로열티 프로그램을 통해 포인트를 모아요.', example_en_5 = 'Joining the loyalty programme is free.', example_ko_5 = '로열티 프로그램 가입은 무료예요.' WHERE id = 'w_shopping_B2_28';
UPDATE words SET example_en_2 = 'Know your consumer rights before you complain.', example_ko_2 = '불만을 제기하기 전에 소비자 권리를 알아두세요.', example_en_3 = 'Consumer rights protect you from misleading advertising.', example_ko_3 = '소비자 권리는 오해의 소지가 있는 광고로부터 보호해줘요.', example_en_4 = 'She cited her consumer rights when asking for a refund.', example_ko_4 = '그녀는 환불을 요청할 때 소비자 권리를 언급했어요.', example_en_5 = 'Consumer rights vary from country to country.', example_ko_5 = '소비자 권리는 나라마다 달라요.' WHERE id = 'w_shopping_B2_29';
UPDATE words SET example_en_2 = 'The product recall affected thousands of customers.', example_ko_2 = '그 제품 리콜은 수천 명의 고객에게 영향을 미쳤어요.', example_en_3 = 'Check the website for any active product recall.', example_ko_3 = '현재 진행 중인 제품 리콜이 있는지 웹사이트를 확인하세요.', example_en_4 = 'The company issued a product recall due to a safety defect.', example_ko_4 = '회사는 안전 결함으로 인해 제품 리콜을 발표했어요.', example_en_5 = 'Return the item if you received a product recall notice.', example_ko_5 = '제품 리콜 통지를 받으셨다면 물건을 반납해 주세요.' WHERE id = 'w_shopping_B2_30';
UPDATE words SET example_en_2 = 'I try to buy sustainable products when I can.', example_ko_2 = '저는 가능하면 지속 가능한 제품을 사려고 해요.', example_en_3 = 'Sustainable packaging reduces plastic waste.', example_ko_3 = '지속 가능한 포장은 플라스틱 낭비를 줄여요.', example_en_4 = 'Is this brand truly sustainable?', example_ko_4 = '이 브랜드가 진정으로 지속 가능한가요?', example_en_5 = 'Sustainable fashion is becoming more affordable.', example_ko_5 = '지속 가능한 패션이 점점 더 합리적인 가격에 나오고 있어요.' WHERE id = 'w_shopping_B2_31';
UPDATE words SET example_en_2 = 'Fast fashion trends change every few weeks.', example_ko_2 = '패스트 패션 트렌드는 몇 주마다 바뀌어요.', example_en_3 = 'Fast fashion creates enormous textile waste.', example_ko_3 = '패스트 패션은 엄청난 섬유 폐기물을 만들어요.', example_en_4 = 'She decided to stop buying fast fashion brands.', example_ko_4 = '그녀는 패스트 패션 브랜드 구매를 그만하기로 했어요.', example_en_5 = 'Fast fashion items rarely last more than a season.', example_ko_5 = '패스트 패션 아이템은 한 시즌 이상 가는 경우가 거의 없어요.' WHERE id = 'w_shopping_B2_32';
UPDATE words SET example_en_2 = 'Ethical shopping means checking where products come from.', example_ko_2 = '윤리적 쇼핑은 제품의 출처를 확인하는 것을 의미해요.', example_en_3 = 'More consumers are interested in ethical shopping.', example_ko_3 = '더 많은 소비자들이 윤리적 쇼핑에 관심을 가지고 있어요.', example_en_4 = 'Ethical shopping supports fair trade producers.', example_ko_4 = '윤리적 쇼핑은 공정 무역 생산자를 지원해요.', example_en_5 = 'She started an ethical shopping blog last year.', example_ko_5 = '그녀는 작년에 윤리적 쇼핑 블로그를 시작했어요.' WHERE id = 'w_shopping_B2_33';
UPDATE words SET example_en_2 = 'Price-sensitive buyers always look for the cheapest option.', example_ko_2 = '가격에 민감한 구매자는 항상 가장 저렴한 옵션을 찾아요.', example_en_3 = 'Young shoppers tend to be more price-sensitive.', example_ko_3 = '젊은 구매자들은 가격에 더 민감한 경향이 있어요.', example_en_4 = 'This market segment is highly price-sensitive.', example_ko_4 = '이 시장 세그먼트는 가격에 매우 민감해요.', example_en_5 = 'Price-sensitive customers respond well to promotional offers.', example_ko_5 = '가격에 민감한 고객들은 프로모션에 잘 반응해요.' WHERE id = 'w_shopping_B2_34';
UPDATE words SET example_en_2 = 'Competitive pricing helps attract more customers.', example_ko_2 = '경쟁력 있는 가격 책정은 더 많은 고객을 끌어들이는 데 도움이 돼요.', example_en_3 = 'The company uses competitive pricing to gain market share.', example_ko_3 = '그 회사는 시장 점유율을 높이기 위해 경쟁력 있는 가격 책정을 활용해요.', example_en_4 = 'Competitive pricing requires constant market monitoring.', example_ko_4 = '경쟁력 있는 가격 책정은 지속적인 시장 모니터링이 필요해요.', example_en_5 = 'Their competitive pricing strategy outperformed rivals.', example_ko_5 = '그들의 경쟁력 있는 가격 전략이 경쟁사를 능가했어요.' WHERE id = 'w_shopping_B2_35';

-- ────────────────────────────────────────────────────────────
-- C1
-- ────────────────────────────────────────────────────────────
UPDATE words SET example_en_2 = 'Traders exploit arbitrage opportunities across markets.', example_ko_2 = '트레이더들은 시장 간 차익 거래 기회를 이용해요.', example_en_3 = 'Arbitrage keeps prices consistent across exchanges.', example_ko_3 = '차익 거래는 거래소 간 가격을 일관되게 유지시켜요.', example_en_4 = 'Currency arbitrage requires fast execution.', example_ko_4 = '환율 차익 거래는 빠른 실행이 필요해요.', example_en_5 = 'Retail arbitrage involves buying cheap and reselling at a profit.', example_ko_5 = '소매 차익 거래는 저렴하게 사서 이익을 남기고 되파는 것이에요.' WHERE id = 'w_shopping_C1_01';
UPDATE words SET example_en_2 = 'The retailer underwent liquidation after years of losses.', example_ko_2 = '그 소매업체는 수년간의 손실 후 청산을 했어요.', example_en_3 = 'Liquidation sales offer deeply discounted goods.', example_ko_3 = '청산 세일은 크게 할인된 상품을 제공해요.', example_en_4 = 'The company entered liquidation due to mounting debts.', example_ko_4 = '그 회사는 쌓이는 부채로 인해 청산에 들어갔어요.', example_en_5 = 'Assets were sold off during the liquidation process.', example_ko_5 = '청산 과정에서 자산이 매각됐어요.' WHERE id = 'w_shopping_C1_02';
UPDATE words SET example_en_2 = 'Buying a franchise gives you a proven business model.', example_ko_2 = '프랜차이즈를 구매하면 검증된 비즈니스 모델을 얻어요.', example_en_3 = 'She opened a café franchise in the city centre.', example_ko_3 = '그녀는 도심에 카페 프랜차이즈를 열었어요.', example_en_4 = 'The franchise fee covers training and support.', example_ko_4 = '프랜차이즈 비용에는 교육과 지원이 포함돼요.', example_en_5 = 'A franchise agreement sets out the terms clearly.', example_ko_5 = '프랜차이즈 계약서에는 조건이 명확하게 명시돼요.' WHERE id = 'w_shopping_C1_03';
UPDATE words SET example_en_2 = 'A monopoly gives one seller control over the market.', example_ko_2 = '독점은 한 판매자에게 시장 지배력을 부여해요.', example_en_3 = 'The regulator broke up the telecoms monopoly.', example_ko_3 = '규제 기관이 통신 독점을 해체했어요.', example_en_4 = 'Monopoly power allows companies to set higher prices.', example_ko_4 = '독점력은 기업이 더 높은 가격을 책정할 수 있게 해요.', example_en_5 = 'Antitrust laws prevent any one firm gaining a monopoly.', example_ko_5 = '독과점금지법은 어떤 기업도 독점을 갖지 못하게 해요.' WHERE id = 'w_shopping_C1_04';
UPDATE words SET example_en_2 = 'An oligopoly limits consumer choice and competition.', example_ko_2 = '과점은 소비자 선택과 경쟁을 제한해요.', example_en_3 = 'The airline industry is often described as an oligopoly.', example_ko_3 = '항공 업계는 종종 과점으로 묘사돼요.', example_en_4 = 'In an oligopoly, a few firms dominate the market.', example_ko_4 = '과점 시장에서는 소수의 기업이 시장을 지배해요.', example_en_5 = 'Prices in an oligopoly tend to be higher than in competition.', example_ko_5 = '과점 시장의 가격은 경쟁 시장보다 높은 경향이 있어요.' WHERE id = 'w_shopping_C1_05';
UPDATE words SET example_en_2 = 'She had a bespoke suit made for the occasion.', example_ko_2 = '그녀는 그 자리를 위해 맞춤 정장을 만들었어요.', example_en_3 = 'Bespoke furniture is crafted to the customer''s exact needs.', example_ko_3 = '맞춤 가구는 고객의 정확한 요구에 맞춰 제작돼요.', example_en_4 = 'A bespoke service comes at a premium price.', example_ko_4 = '맞춤 서비스는 프리미엄 가격이 붙어요.', example_en_5 = 'They offer bespoke packaging for corporate clients.', example_ko_5 = '기업 고객을 위한 맞춤 포장을 제공해요.' WHERE id = 'w_shopping_C1_06';
UPDATE words SET example_en_2 = 'She opened a small boutique selling handmade jewellery.', example_ko_2 = '그녀는 손으로 만든 보석을 파는 작은 부티크를 열었어요.', example_en_3 = 'The boutique stocks only limited edition pieces.', example_ko_3 = '그 부티크는 한정판 아이템만 취급해요.', example_en_4 = 'A boutique hotel offers a more personal experience.', example_ko_4 = '부티크 호텔은 더 개인적인 경험을 제공해요.', example_en_5 = 'She prefers boutique brands over mass-market labels.', example_ko_5 = '그녀는 대중 브랜드보다 부티크 브랜드를 선호해요.' WHERE id = 'w_shopping_C1_07';
UPDATE words SET example_en_2 = 'This artisan cheese is made in small batches.', example_ko_2 = '이 장인 치즈는 소량으로 만들어져요.', example_en_3 = 'Artisan coffee is gaining popularity worldwide.', example_ko_3 = '장인이 만든 커피가 전 세계적으로 인기를 얻고 있어요.', example_en_4 = 'She buys artisan bread from the local bakery.', example_ko_4 = '그녀는 동네 빵집에서 장인이 만든 빵을 사요.', example_en_5 = 'The market features artisan crafts from local makers.', example_ko_5 = '그 시장에는 지역 장인의 수공예품이 있어요.' WHERE id = 'w_shopping_C1_08';
UPDATE words SET example_en_2 = 'This design is exclusive to our flagship store.', example_ko_2 = '이 디자인은 저희 플래그십 스토어 전용이에요.', example_en_3 = 'Members get exclusive access to the sale.', example_ko_3 = '회원들은 세일에 단독으로 접근할 수 있어요.', example_en_4 = 'The exclusive collection sold out in minutes.', example_ko_4 = '단독 컬렉션이 몇 분 만에 품절됐어요.', example_en_5 = 'An exclusive deal keeps competitors away.', example_ko_5 = '독점 거래는 경쟁자를 멀리하게 해요.' WHERE id = 'w_shopping_C1_09';
UPDATE words SET example_en_2 = 'The provenance of this antique is well documented.', example_ko_2 = '이 골동품의 출처는 잘 기록되어 있어요.', example_en_3 = 'Buyers want proof of provenance before purchasing.', example_ko_3 = '구매자들은 구매 전에 출처 증명을 원해요.', example_en_4 = 'The wine''s provenance adds to its value.', example_ko_4 = '와인의 출처가 가치를 높여줘요.', example_en_5 = 'Provenance documentation protects against fakes.', example_ko_5 = '출처 문서는 위조품을 방지해요.' WHERE id = 'w_shopping_C1_10';
UPDATE words SET example_en_2 = 'A connoisseur can immediately spot a fake.', example_ko_2 = '감별사는 즉시 위조품을 알아볼 수 있어요.', example_en_3 = 'She is a connoisseur of vintage clothing.', example_ko_3 = '그녀는 빈티지 옷의 감별사예요.', example_en_4 = 'Only a connoisseur would appreciate the difference.', example_ko_4 = '감별사만이 그 차이를 알아볼 수 있을 거예요.', example_en_5 = 'He is considered a connoisseur of fine whisky.', example_ko_5 = '그는 위스키 감별사로 여겨져요.' WHERE id = 'w_shopping_C1_11';
UPDATE words SET example_en_2 = 'A professional valuation is needed before selling.', example_ko_2 = '판매 전에 전문적인 가치 평가가 필요해요.', example_en_3 = 'The valuation came in higher than expected.', example_ko_3 = '평가 금액이 예상보다 높게 나왔어요.', example_en_4 = 'She got a valuation on her vintage watch.', example_ko_4 = '그녀는 빈티지 시계의 가치를 평가받았어요.', example_en_5 = 'Market conditions affect the valuation of assets.', example_ko_5 = '시장 상황이 자산의 평가 가치에 영향을 미쳐요.' WHERE id = 'w_shopping_C1_12';
UPDATE words SET example_en_2 = 'The appraiser valued the painting at fifty thousand.', example_ko_2 = '감정사가 그 그림을 5만 달러로 평가했어요.', example_en_3 = 'I had an independent appraisal done on the property.', example_ko_3 = '그 부동산에 대한 독립적인 감정을 받았어요.', example_en_4 = 'An accurate appraisal helps set the right price.', example_ko_4 = '정확한 감정은 적절한 가격을 설정하는 데 도움이 돼요.', example_en_5 = 'The bank requires an appraisal before approving a loan.', example_ko_5 = '은행은 대출 승인 전에 감정을 요구해요.' WHERE id = 'w_shopping_C1_13';
UPDATE words SET example_en_2 = 'At this price point, quality should be guaranteed.', example_ko_2 = '이 가격대에서는 품질이 보장되어야 해요.', example_en_3 = 'We need to find the right price point for this market.', example_ko_3 = '이 시장에 맞는 적절한 가격대를 찾아야 해요.', example_en_4 = 'A lower price point attracts more budget shoppers.', example_ko_4 = '더 낮은 가격대는 알뜰 소비자를 더 많이 끌어들여요.', example_en_5 = 'The price point positions this as a mid-range product.', example_ko_5 = '이 가격대는 이 제품을 중가 제품으로 위치시켜요.' WHERE id = 'w_shopping_C1_14';
UPDATE words SET example_en_2 = 'Margin compression is a serious challenge for retailers.', example_ko_2 = '마진 압박은 소매업체에 심각한 도전이에요.', example_en_3 = 'Rising costs led to margin compression across the sector.', example_ko_3 = '비용 상승으로 업계 전반에 마진 압박이 생겼어요.', example_en_4 = 'They found ways to counter margin compression through efficiency.', example_ko_4 = '그들은 효율성을 통해 마진 압박에 대응하는 방법을 찾았어요.', example_en_5 = 'Margin compression forced the company to cut costs.', example_ko_5 = '마진 압박으로 인해 회사는 비용을 절감해야 했어요.' WHERE id = 'w_shopping_C1_15';
UPDATE words SET example_en_2 = 'Check the shelf life before you buy fresh food.', example_ko_2 = '신선식품을 구매하기 전에 유통기한을 확인하세요.', example_en_3 = 'The shelf life of this product is six months.', example_ko_3 = '이 제품의 유통기한은 6개월이에요.', example_en_4 = 'Frozen goods have a much longer shelf life.', example_ko_4 = '냉동 식품은 유통기한이 훨씬 길어요.', example_en_5 = 'Proper storage extends the shelf life of cosmetics.', example_ko_5 = '적절한 보관은 화장품의 유통기한을 늘려줘요.' WHERE id = 'w_shopping_C1_16';
UPDATE words SET example_en_2 = 'Strong brand equity allows premium pricing.', example_ko_2 = '강한 브랜드 자산은 프리미엄 가격 책정을 가능하게 해요.', example_en_3 = 'A product scandal can destroy brand equity overnight.', example_ko_3 = '제품 스캔들은 하룻밤 만에 브랜드 자산을 파괴할 수 있어요.', example_en_4 = 'They invested heavily to build brand equity.', example_ko_4 = '그들은 브랜드 자산을 구축하기 위해 많이 투자했어요.', example_en_5 = 'Consistent quality builds brand equity over time.', example_ko_5 = '일관된 품질은 시간이 지남에 따라 브랜드 자산을 쌓아요.' WHERE id = 'w_shopping_C1_17';
UPDATE words SET example_en_2 = 'Market penetration requires competitive pricing.', example_ko_2 = '시장 침투는 경쟁력 있는 가격 책정이 필요해요.', example_en_3 = 'Their market penetration strategy focused on low prices.', example_ko_3 = '그들의 시장 침투 전략은 낮은 가격에 집중했어요.', example_en_4 = 'High market penetration gives a brand dominant position.', example_ko_4 = '높은 시장 침투율은 브랜드에 지배적인 위치를 부여해요.', example_en_5 = 'The company achieved rapid market penetration in Asia.', example_ko_5 = '그 회사는 아시아에서 빠른 시장 침투를 달성했어요.' WHERE id = 'w_shopping_C1_18';
UPDATE words SET example_en_2 = 'The acquisition cost per customer was too high.', example_ko_2 = '고객 한 명당 확보 비용이 너무 높았어요.', example_en_3 = 'Reducing acquisition cost improves profitability.', example_ko_3 = '확보 비용을 줄이면 수익성이 향상돼요.', example_en_4 = 'The acquisition cost includes marketing and onboarding.', example_ko_4 = '확보 비용에는 마케팅과 온보딩이 포함돼요.', example_en_5 = 'Track your acquisition cost per channel carefully.', example_ko_5 = '채널별 확보 비용을 꼼꼼하게 추적하세요.' WHERE id = 'w_shopping_C1_19';
UPDATE words SET example_en_2 = 'Price discrimination charges different customers different amounts.', example_ko_2 = '가격 차별은 고객마다 다른 금액을 청구해요.', example_en_3 = 'Airlines use price discrimination based on booking time.', example_ko_3 = '항공사는 예약 시기에 따라 가격 차별을 적용해요.', example_en_4 = 'Price discrimination is legal if based on cost differences.', example_ko_4 = '비용 차이에 기반한 가격 차별은 합법이에요.', example_en_5 = 'Senior discounts are a form of price discrimination.', example_ko_5 = '노인 할인은 가격 차별의 한 형태예요.' WHERE id = 'w_shopping_C1_20';
UPDATE words SET example_en_2 = 'A vertically integrated company controls all stages.', example_ko_2 = '수직 통합 회사는 모든 단계를 통제해요.', example_en_3 = 'Vertically integrated retailers own their supply chains.', example_ko_3 = '수직 통합 소매업체는 공급망을 소유해요.', example_en_4 = 'Being vertically integrated reduces reliance on suppliers.', example_ko_4 = '수직 통합은 공급업체 의존도를 낮춰요.', example_en_5 = 'The brand is vertically integrated from farm to shelf.', example_ko_5 = '그 브랜드는 농장에서 매장까지 수직 통합되어 있어요.' WHERE id = 'w_shopping_C1_21';
UPDATE words SET example_en_2 = 'E-commerce enables disintermediation of traditional retail.', example_ko_2 = '전자상거래는 기존 소매의 중간 단계 제거를 가능하게 해요.', example_en_3 = 'Disintermediation cuts costs by removing middlemen.', example_ko_3 = '중간 단계 제거는 중개인을 없애서 비용을 줄여요.', example_en_4 = 'The internet has accelerated disintermediation across industries.', example_ko_4 = '인터넷은 다양한 산업에서 중간 단계 제거를 가속화했어요.', example_en_5 = 'Disintermediation benefits both producer and consumer.', example_ko_5 = '중간 단계 제거는 생산자와 소비자 모두에게 이익이에요.' WHERE id = 'w_shopping_C1_22';
UPDATE words SET example_en_2 = 'Ancillary revenue from add-ons boosted total income.', example_ko_2 = '추가 서비스에서 발생한 부가 수익이 총 수입을 올렸어요.', example_en_3 = 'Airlines rely heavily on ancillary revenue from baggage fees.', example_ko_3 = '항공사는 수하물 요금에서 발생하는 부가 수익에 크게 의존해요.', example_en_4 = 'Extended warranties are a major source of ancillary revenue.', example_ko_4 = '연장 보증은 부가 수익의 주요 원천이에요.', example_en_5 = 'Cafés in bookstores generate significant ancillary revenue.', example_ko_5 = '서점 내 카페는 상당한 부가 수익을 창출해요.' WHERE id = 'w_shopping_C1_23';
UPDATE words SET example_en_2 = 'Market segmentation helps target different customer groups.', example_ko_2 = '시장 세분화는 다양한 고객 그룹을 타겟팅하는 데 도움이 돼요.', example_en_3 = 'Effective market segmentation improves campaign results.', example_ko_3 = '효과적인 시장 세분화는 캠페인 결과를 향상시켜요.', example_en_4 = 'Geographic market segmentation divides customers by location.', example_ko_4 = '지리적 시장 세분화는 고객을 위치별로 나눠요.', example_en_5 = 'Pricing strategy depends heavily on market segmentation.', example_ko_5 = '가격 책정 전략은 시장 세분화에 크게 의존해요.' WHERE id = 'w_shopping_C1_24';
UPDATE words SET example_en_2 = 'Supermarkets use bread as a loss leader.', example_ko_2 = '슈퍼마켓은 빵을 미끼 상품으로 사용해요.', example_en_3 = 'A loss leader attracts customers who then buy other items.', example_ko_3 = '미끼 상품은 다른 물건을 사게 되는 고객을 끌어들여요.', example_en_4 = 'Using a loss leader is a common retail strategy.', example_ko_4 = '미끼 상품 전략은 일반적인 소매 전략이에요.', example_en_5 = 'The printer was a loss leader; the ink cartridges were the profit.', example_ko_5 = '프린터는 미끼 상품이었고 잉크 카트리지가 수익이었어요.' WHERE id = 'w_shopping_C1_25';
UPDATE words SET example_en_2 = 'Dynamic pricing adjusts based on demand.', example_ko_2 = '동적 가격 책정은 수요에 따라 조정돼요.', example_en_3 = 'Ride-sharing apps use dynamic pricing during peak times.', example_ko_3 = '라이드셰어링 앱은 피크 시간대에 동적 가격 책정을 사용해요.', example_en_4 = 'Dynamic pricing maximises revenue from high-demand periods.', example_ko_4 = '동적 가격 책정은 수요가 높은 기간의 수익을 극대화해요.', example_en_5 = 'Consumers sometimes feel dynamic pricing is unfair.', example_ko_5 = '소비자들은 동적 가격 책정이 불공평하다고 느끼기도 해요.' WHERE id = 'w_shopping_C1_26';
UPDATE words SET example_en_2 = 'Bundle pricing encourages customers to buy more.', example_ko_2 = '묶음 가격 책정은 고객이 더 많이 사도록 유도해요.', example_en_3 = 'The software company used bundle pricing to increase sales.', example_ko_3 = '그 소프트웨어 회사는 매출 증가를 위해 묶음 가격 책정을 사용했어요.', example_en_4 = 'Bundle pricing offers better value than buying items separately.', example_ko_4 = '묶음 가격 책정은 개별 구매보다 더 좋은 가성비를 제공해요.', example_en_5 = 'A meal deal is a classic example of bundle pricing.', example_ko_5 = '밀 딜은 묶음 가격 책정의 전형적인 예예요.' WHERE id = 'w_shopping_C1_27';
UPDATE words SET example_en_2 = 'Retailers use anchor pricing to make deals look attractive.', example_ko_2 = '소매업체들은 거래를 매력적으로 보이게 하려고 기준 가격을 이용해요.', example_en_3 = 'The original price acts as an anchor price.', example_ko_3 = '원래 가격이 기준 가격 역할을 해요.', example_en_4 = 'Anchor pricing influences what customers consider a fair price.', example_ko_4 = '기준 가격은 고객이 공정한 가격이라고 생각하는 것에 영향을 미쳐요.', example_en_5 = 'She used anchor pricing to justify the premium range.', example_ko_5 = '그녀는 프리미엄 라인을 정당화하기 위해 기준 가격을 사용했어요.' WHERE id = 'w_shopping_C1_28';
UPDATE words SET example_en_2 = 'Shrinkage is a major problem for large retailers.', example_ko_2 = '재고 손실은 대형 소매업체에 큰 문제예요.', example_en_3 = 'Employee theft contributes to shrinkage.', example_ko_3 = '직원 절도도 재고 손실의 원인이에요.', example_en_4 = 'CCTV systems help reduce shrinkage in stores.', example_ko_4 = 'CCTV 시스템은 매장에서 재고 손실을 줄이는 데 도움이 돼요.', example_en_5 = 'Shrinkage can account for a significant percentage of lost profit.', example_ko_5 = '재고 손실은 손실 이익의 상당 부분을 차지할 수 있어요.' WHERE id = 'w_shopping_C1_29';
UPDATE words SET example_en_2 = 'Grey market goods lack official after-sales support.', example_ko_2 = '회색 시장 상품은 공식 애프터서비스가 없어요.', example_en_3 = 'She unknowingly bought from the grey market.', example_ko_3 = '그녀는 모르고 회색 시장에서 구매했어요.', example_en_4 = 'The grey market undermines authorised retailers.', example_ko_4 = '회색 시장은 공인 소매업체를 약화시켜요.', example_en_5 = 'Grey market imports exploit price differences between regions.', example_ko_5 = '회색 시장 수입품은 지역 간 가격 차이를 이용해요.' WHERE id = 'w_shopping_C1_30';
UPDATE words SET example_en_2 = 'A price floor prevents goods being sold too cheaply.', example_ko_2 = '가격 하한선은 상품이 너무 저렴하게 팔리는 걸 방지해요.', example_en_3 = 'The government set a price floor for agricultural products.', example_ko_3 = '정부는 농산물에 가격 하한선을 설정했어요.', example_en_4 = 'A price floor benefits producers but raises costs for consumers.', example_ko_4 = '가격 하한선은 생산자에게 유리하지만 소비자 비용을 높여요.', example_en_5 = 'Minimum wage laws act as a price floor for labour.', example_ko_5 = '최저임금법은 노동에 대한 가격 하한선 역할을 해요.' WHERE id = 'w_shopping_C1_31';
UPDATE words SET example_en_2 = 'A price ceiling limits how much sellers can charge.', example_ko_2 = '가격 상한선은 판매자가 청구할 수 있는 금액을 제한해요.', example_en_3 = 'The government introduced a price ceiling on fuel.', example_ko_3 = '정부가 연료에 가격 상한선을 도입했어요.', example_en_4 = 'Price ceilings protect consumers from exploitation.', example_ko_4 = '가격 상한선은 소비자를 착취로부터 보호해요.', example_en_5 = 'Setting a price ceiling can lead to shortages.', example_ko_5 = '가격 상한선 설정은 부족 현상으로 이어질 수 있어요.' WHERE id = 'w_shopping_C1_32';
UPDATE words SET example_en_2 = 'Improving customer lifetime value requires ongoing engagement.', example_ko_2 = '고객 평생 가치를 높이려면 지속적인 참여가 필요해요.', example_en_3 = 'Calculate customer lifetime value before setting marketing budgets.', example_ko_3 = '마케팅 예산을 설정하기 전에 고객 평생 가치를 계산하세요.', example_en_4 = 'A loyalty programme increases customer lifetime value.', example_ko_4 = '로열티 프로그램은 고객 평생 가치를 높여요.', example_en_5 = 'High customer lifetime value justifies large acquisition costs.', example_ko_5 = '높은 고객 평생 가치는 큰 확보 비용을 정당화해요.' WHERE id = 'w_shopping_C1_33';
UPDATE words SET example_en_2 = 'An omnichannel approach unifies online and offline shopping.', example_ko_2 = '옴니채널 접근 방식은 온라인과 오프라인 쇼핑을 통합해요.', example_en_3 = 'Omnichannel retailing gives customers a seamless experience.', example_ko_3 = '옴니채널 소매는 고객에게 원활한 경험을 제공해요.', example_en_4 = 'The brand invested in an omnichannel strategy last year.', example_ko_4 = '그 브랜드는 작년에 옴니채널 전략에 투자했어요.', example_en_5 = 'Omnichannel consumers tend to spend more than single-channel ones.', example_ko_5 = '옴니채널 소비자는 단일 채널 소비자보다 더 많이 쓰는 경향이 있어요.' WHERE id = 'w_shopping_C1_34';
UPDATE words SET example_en_2 = 'A stockout during the sale cost us many customers.', example_ko_2 = '세일 중 품절로 고객을 많이 잃었어요.', example_en_3 = 'Stockouts damage customer trust and loyalty.', example_ko_3 = '품절은 고객 신뢰와 충성도를 해쳐요.', example_en_4 = 'Better forecasting can prevent stockouts.', example_ko_4 = '더 나은 수요 예측은 품절을 방지할 수 있어요.', example_en_5 = 'The system sends an alert before a stockout occurs.', example_ko_5 = '시스템은 품절이 발생하기 전에 경고를 보내요.' WHERE id = 'w_shopping_C1_35';

-- ────────────────────────────────────────────────────────────
-- C2
-- ────────────────────────────────────────────────────────────
UPDATE words SET example_en_2 = 'The commodification of education concerns many academics.', example_ko_2 = '교육의 상품화는 많은 학자들이 우려하는 문제예요.', example_en_3 = 'Commodification reduces cultural goods to market transactions.', example_ko_3 = '상품화는 문화 상품을 시장 거래로 축소시켜요.', example_en_4 = 'The commodification of art has divided critics.', example_ko_4 = '예술의 상품화는 비평가들 사이에서 의견이 갈려요.', example_en_5 = 'Critics argue that wellness has become a commodification of health.', example_ko_5 = '비평가들은 웰니스가 건강의 상품화가 됐다고 주장해요.' WHERE id = 'w_shopping_C2_01';
UPDATE words SET example_en_2 = 'Mercantilism shaped trade policy for centuries.', example_ko_2 = '중상주의는 수백 년 동안 무역 정책을 형성했어요.', example_en_3 = 'Mercantilism prioritised exports over imports.', example_ko_3 = '중상주의는 수입보다 수출을 우선시했어요.', example_en_4 = 'Critics of mercantilism argue it creates zero-sum trade.', example_ko_4 = '중상주의 비평가들은 그것이 제로섬 무역을 만든다고 주장해요.', example_en_5 = 'Modern trade debates still echo principles of mercantilism.', example_ko_5 = '현대 무역 논쟁은 여전히 중상주의 원칙을 반영해요.' WHERE id = 'w_shopping_C2_02';
UPDATE words SET example_en_2 = 'A skilled arbitrageur exploits price gaps across markets.', example_ko_2 = '숙련된 차익 거래자는 시장 간 가격 차이를 이용해요.', example_en_3 = 'The arbitrageur profited from currency misalignments.', example_ko_3 = '차익 거래자는 통화 불일치에서 이익을 얻었어요.', example_en_4 = 'Being a successful arbitrageur requires lightning-fast decisions.', example_ko_4 = '성공적인 차익 거래자가 되려면 번개 같은 결정이 필요해요.', example_en_5 = 'An arbitrageur monitors multiple markets simultaneously.', example_ko_5 = '차익 거래자는 여러 시장을 동시에 모니터링해요.' WHERE id = 'w_shopping_C2_03';
UPDATE words SET example_en_2 = 'The conglomerate operates across retail, media, and finance.', example_ko_2 = '그 대기업은 소매, 미디어, 금융에 걸쳐 운영돼요.', example_en_3 = 'Forming a conglomerate can spread business risk.', example_ko_3 = '대기업을 형성하면 사업 리스크를 분산할 수 있어요.', example_en_4 = 'The retail conglomerate acquired three smaller brands.', example_ko_4 = '그 소매 대기업이 세 개의 소규모 브랜드를 인수했어요.', example_en_5 = 'Critics say conglomerates stifle market competition.', example_ko_5 = '비평가들은 대기업이 시장 경쟁을 억제한다고 말해요.' WHERE id = 'w_shopping_C2_04';
UPDATE words SET example_en_2 = 'The cartel fixed prices to eliminate competition.', example_ko_2 = '카르텔은 경쟁을 없애기 위해 가격을 담합했어요.', example_en_3 = 'Authorities investigated the suspected cartel.', example_ko_3 = '당국은 의심되는 카르텔을 조사했어요.', example_en_4 = 'A cartel among suppliers can harm consumers.', example_ko_4 = '공급업체 간의 카르텔은 소비자에게 해를 끼칠 수 있어요.', example_en_5 = 'Breaking up a cartel restores fair competition.', example_ko_5 = '카르텔을 해체하면 공정한 경쟁이 회복돼요.' WHERE id = 'w_shopping_C2_05';
UPDATE words SET example_en_2 = 'A monopsony gives buyers enormous negotiating power.', example_ko_2 = '단일 수요 독점은 구매자에게 막대한 협상력을 부여해요.', example_en_3 = 'Large retailers can act as a monopsony over small suppliers.', example_ko_3 = '대형 소매업체는 소규모 공급업체에 대해 단일 수요 독점처럼 행동할 수 있어요.', example_en_4 = 'In a monopsony, suppliers have little bargaining power.', example_ko_4 = '단일 수요 독점에서 공급업체는 협상력이 거의 없어요.', example_en_5 = 'Regulators watch for signs of monopsony behaviour.', example_ko_5 = '규제 기관은 단일 수요 독점 행동의 징후를 주시해요.' WHERE id = 'w_shopping_C2_06';
UPDATE words SET example_en_2 = 'Depreciation reduces the book value of an asset annually.', example_ko_2 = '감가상각은 자산의 장부 가치를 매년 줄여요.', example_en_3 = 'The company accounted for depreciation in its annual report.', example_ko_3 = '회사는 연간 보고서에 감가상각을 포함했어요.', example_en_4 = 'Currency depreciation makes imports more expensive.', example_ko_4 = '통화 가치 하락은 수입품을 더 비싸게 만들어요.', example_en_5 = 'Asset depreciation is a non-cash accounting expense.', example_ko_5 = '자산 감가상각은 비현금 회계 비용이에요.' WHERE id = 'w_shopping_C2_07';
UPDATE words SET example_en_2 = 'Amortization spreads the cost of an asset over time.', example_ko_2 = '상각은 자산의 비용을 시간에 걸쳐 분산시켜요.', example_en_3 = 'The loan is subject to a twenty-year amortization schedule.', example_ko_3 = '그 대출은 20년 상각 일정이 적용돼요.', example_en_4 = 'Amortization of intangible assets follows specific accounting rules.', example_ko_4 = '무형 자산의 상각은 특정 회계 규칙을 따라요.', example_en_5 = 'The amortization period affects monthly payments.', example_ko_5 = '상각 기간이 월 납부금에 영향을 미쳐요.' WHERE id = 'w_shopping_C2_08';
UPDATE words SET example_en_2 = 'Inventory is a key asset on the balance sheet.', example_ko_2 = '재고는 대차대조표에서 핵심 자산이에요.', example_en_3 = 'The company''s assets include property and equipment.', example_ko_3 = '그 회사의 자산에는 부동산과 장비가 포함돼요.', example_en_4 = 'Brand reputation is an intangible asset.', example_ko_4 = '브랜드 평판은 무형 자산이에요.', example_en_5 = 'Acquiring new assets requires significant capital.', example_ko_5 = '새 자산 취득에는 상당한 자본이 필요해요.' WHERE id = 'w_shopping_C2_09';
UPDATE words SET example_en_2 = 'Outstanding debt is recorded as a liability.', example_ko_2 = '미결제 부채는 부채로 기록돼요.', example_en_3 = 'A firm''s liability can affect its credit rating.', example_ko_3 = '회사의 부채는 신용등급에 영향을 미칠 수 있어요.', example_en_4 = 'Product recalls create a significant liability for retailers.', example_ko_4 = '제품 리콜은 소매업체에 상당한 책임을 부여해요.', example_en_5 = 'Reducing liability improves a company''s financial health.', example_ko_5 = '부채를 줄이면 회사의 재무 건전성이 향상돼요.' WHERE id = 'w_shopping_C2_10';
UPDATE words SET example_en_2 = 'An oligopsony limits competition among buyers.', example_ko_2 = '과점 수요 시장은 구매자 간의 경쟁을 제한해요.', example_en_3 = 'In an oligopsony, a few buyers control the market.', example_ko_3 = '과점 수요 시장에서는 소수의 구매자가 시장을 지배해요.', example_en_4 = 'The agricultural sector sometimes functions as an oligopsony.', example_ko_4 = '농업 분야는 때때로 과점 수요 시장처럼 기능해요.', example_en_5 = 'Suppliers struggle to negotiate fairly in an oligopsony.', example_ko_5 = '공급업체들은 과점 수요 시장에서 공정하게 협상하기 어려워요.' WHERE id = 'w_shopping_C2_11';
UPDATE words SET example_en_2 = 'Pollution is a negative externality of manufacturing.', example_ko_2 = '오염은 제조업의 부정적 외부 효과예요.', example_en_3 = 'Externalities are not reflected in the market price.', example_ko_3 = '외부 효과는 시장 가격에 반영되지 않아요.', example_en_4 = 'The government taxes activities that create negative externalities.', example_ko_4 = '정부는 부정적 외부 효과를 일으키는 활동에 세금을 부과해요.', example_en_5 = 'Positive externalities, like education, benefit society broadly.', example_ko_5 = '교육과 같은 긍정적 외부 효과는 사회 전반에 이익을 줘요.' WHERE id = 'w_shopping_C2_12';
UPDATE words SET example_en_2 = 'Price gouging during disasters is illegal.', example_ko_2 = '재난 중 폭리는 불법이에요.', example_en_3 = 'Consumers complained about price gouging on essential goods.', example_ko_3 = '소비자들은 필수품에 대한 폭리를 불만 제기했어요.', example_en_4 = 'Regulators fined the company for price gouging.', example_ko_4 = '규제 기관은 폭리를 이유로 그 회사에 벌금을 부과했어요.', example_en_5 = 'Online resellers were accused of price gouging on limited items.', example_ko_5 = '온라인 재판매자들이 한정 상품에 대한 폭리로 비난받았어요.' WHERE id = 'w_shopping_C2_13';
UPDATE words SET example_en_2 = 'Regulatory arbitrage allows firms to exploit legal loopholes.', example_ko_2 = '규제 차익 거래는 기업이 법적 허점을 이용하게 해요.', example_en_3 = 'Companies use regulatory arbitrage to minimise tax.', example_ko_3 = '기업들은 세금을 최소화하기 위해 규제 차익 거래를 이용해요.', example_en_4 = 'Regulatory arbitrage distorts fair competition.', example_ko_4 = '규제 차익 거래는 공정한 경쟁을 왜곡해요.', example_en_5 = 'Closing loopholes reduces opportunities for regulatory arbitrage.', example_ko_5 = '허점을 막으면 규제 차익 거래 기회가 줄어요.' WHERE id = 'w_shopping_C2_14';
UPDATE words SET example_en_2 = 'Planned obsolescence keeps consumers buying new products.', example_ko_2 = '계획적 노화는 소비자들이 새 제품을 계속 사도록 유도해요.', example_en_3 = 'Critics accuse smartphone makers of planned obsolescence.', example_ko_3 = '비평가들은 스마트폰 제조업체들이 계획적 노화를 쓴다고 비난해요.', example_en_4 = 'Planned obsolescence is environmentally destructive.', example_ko_4 = '계획적 노화는 환경에 해로워요.', example_en_5 = 'France passed a law against planned obsolescence.', example_ko_5 = '프랑스는 계획적 노화에 반대하는 법을 통과시켰어요.' WHERE id = 'w_shopping_C2_15';
UPDATE words SET example_en_2 = 'Conspicuous consumption signals social status.', example_ko_2 = '과시적 소비는 사회적 지위를 드러내요.', example_en_3 = 'Luxury brands depend on conspicuous consumption.', example_ko_3 = '명품 브랜드는 과시적 소비에 의존해요.', example_en_4 = 'Conspicuous consumption is driven by the desire to impress others.', example_ko_4 = '과시적 소비는 남에게 인상을 주고 싶은 욕구에서 비롯돼요.', example_en_5 = 'Social media amplifies conspicuous consumption behaviour.', example_ko_5 = '소셜 미디어는 과시적 소비 행동을 증폭시켜요.' WHERE id = 'w_shopping_C2_16';
UPDATE words SET example_en_2 = 'A Veblen good becomes more desirable as prices rise.', example_ko_2 = '베블런재는 가격이 오를수록 더 탐나는 상품이에요.', example_en_3 = 'Luxury handbags behave as Veblen goods.', example_ko_3 = '명품 핸드백은 베블런재처럼 행동해요.', example_en_4 = 'A price drop can actually reduce demand for a Veblen good.', example_ko_4 = '베블런재는 가격 하락이 오히려 수요를 줄일 수 있어요.', example_en_5 = 'The Veblen good concept challenges traditional economic theory.', example_ko_5 = '베블런재 개념은 전통 경제 이론에 도전해요.' WHERE id = 'w_shopping_C2_17';
UPDATE words SET example_en_2 = 'Moral hazard arises when one party takes on excessive risk.', example_ko_2 = '도덕적 해이는 한 당사자가 과도한 위험을 감수할 때 발생해요.', example_en_3 = 'Insurance can create moral hazard if not structured carefully.', example_ko_3 = '보험은 신중하게 설계되지 않으면 도덕적 해이를 만들 수 있어요.', example_en_4 = 'Bailouts can encourage moral hazard among financial institutions.', example_ko_4 = '구제금융은 금융기관에 도덕적 해이를 조장할 수 있어요.', example_en_5 = 'Policy makers must design rules that reduce moral hazard.', example_ko_5 = '정책 입안자들은 도덕적 해이를 줄이는 규칙을 설계해야 해요.' WHERE id = 'w_shopping_C2_18';
UPDATE words SET example_en_2 = 'Asymmetric information gives sellers an advantage over buyers.', example_ko_2 = '정보 비대칭은 판매자에게 구매자보다 유리한 입장을 줘요.', example_en_3 = 'Used car markets are classic examples of asymmetric information.', example_ko_3 = '중고차 시장은 정보 비대칭의 전형적인 예예요.', example_en_4 = 'Asymmetric information can lead to market failure.', example_ko_4 = '정보 비대칭은 시장 실패로 이어질 수 있어요.', example_en_5 = 'Transparency reduces the effects of asymmetric information.', example_ko_5 = '투명성은 정보 비대칭의 영향을 줄여요.' WHERE id = 'w_shopping_C2_19';
UPDATE words SET example_en_2 = 'Predatory pricing is designed to eliminate competitors.', example_ko_2 = '약탈적 가격 책정은 경쟁자를 없애기 위해 설계됐어요.', example_en_3 = 'The regulator investigated the firm for predatory pricing.', example_ko_3 = '규제 기관이 약탈적 가격 책정으로 그 회사를 조사했어요.', example_en_4 = 'Predatory pricing hurts consumers in the long run.', example_ko_4 = '약탈적 가격 책정은 장기적으로 소비자에게 해를 끼쳐요.', example_en_5 = 'Antitrust laws prohibit predatory pricing practices.', example_ko_5 = '독과점금지법은 약탈적 가격 책정 관행을 금지해요.' WHERE id = 'w_shopping_C2_20';
UPDATE words SET example_en_2 = 'Transfer pricing is used to shift profits between subsidiaries.', example_ko_2 = '이전 가격 책정은 자회사 간에 이익을 이동시키는 데 사용돼요.', example_en_3 = 'Multinationals use transfer pricing to reduce their tax burden.', example_ko_3 = '다국적 기업들은 세금 부담을 줄이기 위해 이전 가격 책정을 이용해요.', example_en_4 = 'Transfer pricing rules vary by jurisdiction.', example_ko_4 = '이전 가격 책정 규칙은 관할 구역마다 달라요.', example_en_5 = 'Tax authorities scrutinise transfer pricing arrangements closely.', example_ko_5 = '세무 당국은 이전 가격 책정 약정을 면밀히 조사해요.' WHERE id = 'w_shopping_C2_21';
UPDATE words SET example_en_2 = 'The demand curve slopes downward for most goods.', example_ko_2 = '대부분의 상품에서 수요 곡선은 아래로 기울어져요.', example_en_3 = 'A shift in the demand curve affects equilibrium price.', example_ko_3 = '수요 곡선의 이동은 균형 가격에 영향을 미쳐요.', example_en_4 = 'The demand curve for Veblen goods slopes upward.', example_ko_4 = '베블런재의 수요 곡선은 위로 기울어져요.', example_en_5 = 'Price changes move quantities along the demand curve.', example_ko_5 = '가격 변화는 수요 곡선을 따라 수량을 이동시켜요.' WHERE id = 'w_shopping_C2_22';
UPDATE words SET example_en_2 = 'Deadweight loss occurs when markets are inefficient.', example_ko_2 = '후생 손실은 시장이 비효율적일 때 발생해요.', example_en_3 = 'A price ceiling creates deadweight loss in the market.', example_ko_3 = '가격 상한선은 시장에 후생 손실을 만들어요.', example_en_4 = 'Taxes can create deadweight loss by distorting incentives.', example_ko_4 = '세금은 인센티브를 왜곡해서 후생 손실을 만들 수 있어요.', example_en_5 = 'Reducing deadweight loss improves overall market efficiency.', example_ko_5 = '후생 손실을 줄이면 전체 시장 효율성이 향상돼요.' WHERE id = 'w_shopping_C2_23';
UPDATE words SET example_en_2 = 'Liquidity is essential for a business to meet short-term obligations.', example_ko_2 = '유동성은 기업이 단기 의무를 이행하는 데 필수적이에요.', example_en_3 = 'Cash is the most liquid asset a business holds.', example_ko_3 = '현금은 기업이 보유하는 가장 유동적인 자산이에요.', example_en_4 = 'A liquidity crisis can force a company into insolvency.', example_ko_4 = '유동성 위기는 회사를 파산으로 몰 수 있어요.', example_en_5 = 'High market liquidity makes it easy to buy and sell assets.', example_ko_5 = '높은 시장 유동성은 자산의 매매를 쉽게 만들어요.' WHERE id = 'w_shopping_C2_24';
UPDATE words SET example_en_2 = 'A solvent company can pay all its debts.', example_ko_2 = '지급 능력 있는 회사는 모든 부채를 갚을 수 있어요.', example_en_3 = 'Solvency ratios indicate a firm''s financial health.', example_ko_3 = '지급 능력 비율은 회사의 재무 건전성을 나타내요.', example_en_4 = 'Maintaining solvency is critical during economic downturns.', example_ko_4 = '경기 침체 시 지급 능력 유지가 매우 중요해요.', example_en_5 = 'Investors assess solvency before buying company bonds.', example_ko_5 = '투자자들은 회사채 구매 전에 지급 능력을 평가해요.' WHERE id = 'w_shopping_C2_25';
UPDATE words SET example_en_2 = 'Calculate the net present value before approving a project.', example_ko_2 = '프로젝트를 승인하기 전에 순현재가치를 계산하세요.', example_en_3 = 'A positive net present value means the investment is worthwhile.', example_ko_3 = '순현재가치가 양수라는 것은 투자할 가치가 있다는 뜻이에요.', example_en_4 = 'The net present value analysis guided our purchase decision.', example_ko_4 = '순현재가치 분석이 구매 결정을 이끌었어요.', example_en_5 = 'Discount rates affect the net present value of future cash flows.', example_ko_5 = '할인율은 미래 현금 흐름의 순현재가치에 영향을 미쳐요.' WHERE id = 'w_shopping_C2_26';
UPDATE words SET example_en_2 = 'Capital expenditure on new equipment was approved.', example_ko_2 = '새 장비에 대한 자본 지출이 승인됐어요.', example_en_3 = 'Capital expenditure is a long-term investment in assets.', example_ko_3 = '자본 지출은 자산에 대한 장기 투자예요.', example_en_4 = 'Reducing capital expenditure helped improve cash flow.', example_ko_4 = '자본 지출을 줄여서 현금 흐름이 개선됐어요.', example_en_5 = 'The retail chain planned major capital expenditure for store upgrades.', example_ko_5 = '소매 체인은 매장 개선을 위한 대규모 자본 지출을 계획했어요.' WHERE id = 'w_shopping_C2_27';
UPDATE words SET example_en_2 = 'Venture capital funded the startup''s expansion.', example_ko_2 = '벤처 캐피탈이 스타트업의 확장을 지원했어요.', example_en_3 = 'Securing venture capital requires a strong business plan.', example_ko_3 = '벤처 캐피탈을 확보하려면 탄탄한 사업 계획이 필요해요.', example_en_4 = 'Venture capital investors expect high returns.', example_ko_4 = '벤처 캐피탈 투자자들은 높은 수익을 기대해요.', example_en_5 = 'The e-commerce brand raised funds through venture capital.', example_ko_5 = '그 전자상거래 브랜드는 벤처 캐피탈을 통해 자금을 조달했어요.' WHERE id = 'w_shopping_C2_28';
UPDATE words SET example_en_2 = 'Due diligence revealed undisclosed liabilities.', example_ko_2 = '실사를 통해 공개되지 않은 부채가 드러났어요.', example_en_3 = 'Always carry out due diligence before signing a contract.', example_ko_3 = '계약에 서명하기 전에 항상 실사를 수행하세요.', example_en_4 = 'The acquisition process included extensive due diligence.', example_ko_4 = '인수 과정에 광범위한 실사가 포함됐어요.', example_en_5 = 'Due diligence protects buyers from hidden risks.', example_ko_5 = '실사는 구매자를 숨겨진 위험으로부터 보호해요.' WHERE id = 'w_shopping_C2_29';
UPDATE words SET example_en_2 = 'Intellectual property rights protect creative work.', example_ko_2 = '지식재산권은 창작물을 보호해요.', example_en_3 = 'Selling counterfeits infringes on intellectual property.', example_ko_3 = '위조품 판매는 지식재산권을 침해해요.', example_en_4 = 'The brand registered its logo as intellectual property.', example_ko_4 = '그 브랜드는 로고를 지식재산으로 등록했어요.', example_en_5 = 'Protecting intellectual property is vital for innovation.', example_ko_5 = '지식재산 보호는 혁신에 매우 중요해요.' WHERE id = 'w_shopping_C2_30';
UPDATE words SET example_en_2 = 'Economies of scale reduce the cost per unit.', example_ko_2 = '규모의 경제는 단위당 비용을 낮춰요.', example_en_3 = 'Large retailers benefit from economies of scale.', example_ko_3 = '대형 소매업체는 규모의 경제 혜택을 받아요.', example_en_4 = 'Achieving economies of scale requires significant investment.', example_ko_4 = '규모의 경제를 달성하려면 상당한 투자가 필요해요.', example_en_5 = 'Bulk purchasing is one way to realise economies of scale.', example_ko_5 = '대량 구매는 규모의 경제를 실현하는 방법 중 하나예요.' WHERE id = 'w_shopping_C2_31';
UPDATE words SET example_en_2 = 'Diseconomies of scale occur when firms become too large.', example_ko_2 = '규모의 불경제는 기업이 너무 커졌을 때 발생해요.', example_en_3 = 'Management complexity can cause diseconomies of scale.', example_ko_3 = '관리 복잡성이 규모의 불경제를 일으킬 수 있어요.', example_en_4 = 'The merger led to unexpected diseconomies of scale.', example_ko_4 = '합병이 예상치 못한 규모의 불경제로 이어졌어요.', example_en_5 = 'Diseconomies of scale reduce the efficiency of expansion.', example_ko_5 = '규모의 불경제는 확장의 효율성을 낮춰요.' WHERE id = 'w_shopping_C2_32';
UPDATE words SET example_en_2 = 'The gig economy has changed how people earn and spend.', example_ko_2 = '긱 경제는 사람들이 버는 방식과 소비 방식을 바꿔놨어요.', example_en_3 = 'Gig economy workers often lack job security.', example_ko_3 = '긱 경제 근로자들은 종종 고용 안정이 부족해요.', example_en_4 = 'Delivery platforms are a key part of the gig economy.', example_ko_4 = '배달 플랫폼은 긱 경제의 핵심 부분이에요.', example_en_5 = 'The gig economy offers flexibility but limited benefits.', example_ko_5 = '긱 경제는 유연성을 제공하지만 혜택은 제한적이에요.' WHERE id = 'w_shopping_C2_33';
UPDATE words SET example_en_2 = 'A trade surplus means a country exports more than it imports.', example_ko_2 = '무역 흑자는 수출이 수입보다 많다는 것을 의미해요.', example_en_3 = 'The country ran a significant trade surplus last year.', example_ko_3 = '그 나라는 작년에 상당한 무역 흑자를 기록했어요.', example_en_4 = 'A persistent trade surplus can cause diplomatic tensions.', example_ko_4 = '지속적인 무역 흑자는 외교적 긴장을 일으킬 수 있어요.', example_en_5 = 'The trade surplus boosted the national currency.', example_ko_5 = '무역 흑자는 국가 통화를 강화시켰어요.' WHERE id = 'w_shopping_C2_34';
UPDATE words SET example_en_2 = 'A trade deficit means imports exceed exports.', example_ko_2 = '무역 적자는 수입이 수출을 초과한다는 것을 의미해요.', example_en_3 = 'A large trade deficit can weaken a country''s currency.', example_ko_3 = '큰 무역 적자는 국가 통화를 약화시킬 수 있어요.', example_en_4 = 'The government introduced tariffs to reduce the trade deficit.', example_ko_4 = '정부는 무역 적자를 줄이기 위해 관세를 도입했어요.', example_en_5 = 'Analysts monitor the trade deficit as a sign of economic health.', example_ko_5 = '분석가들은 무역 적자를 경제 건전성의 징후로 모니터링해요.' WHERE id = 'w_shopping_C2_35';
