-- EngCat · Shopping (쇼핑) seed data
-- Words  : 35 per CEFR level (A1–C2) = 210 total
-- Patterns: 7 per CEFR level (A1–C2) = 42 total
-- Generated : 2026-05-24

-- ============================================================
-- WORDS
-- ============================================================

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES

-- ────────────────────────────────────────────────────────────
-- A1 (35 words)
-- ────────────────────────────────────────────────────────────
('w_shopping_A1_01','buy','/baɪ/','verb','사다','To get something by paying money for it.','I want to {buy} new shoes.','새 신발을 사고 싶어요.','buy','A1','shopping',1,'shopping store buying purchase'),
('w_shopping_A1_02','sell','/sɛl/','verb','팔다','To exchange something for money.','They {sell} fresh fruit here.','여기서 신선한 과일을 팔아요.','sell','A1','shopping',1,'market vendor selling fruit'),
('w_shopping_A1_03','shop','/ʃɒp/','noun/verb','가게 / 쇼핑하다','A place where goods are sold; to visit shops to buy things.','Let''s go to the {shop} after lunch.','점심 식사 후에 가게에 가요.','shop','A1','shopping',1,'retail shop storefront'),
('w_shopping_A1_04','price','/praɪs/','noun','가격','The amount of money for which something is bought or sold.','What is the {price} of this bag?','이 가방의 가격이 얼마예요?','price','A1','shopping',1,'price tag label cost'),
('w_shopping_A1_05','cheap','/tʃiːp/','adjective','저렴한','Low in price; not expensive.','This jacket is very {cheap}.','이 재킷은 매우 저렴해요.','cheap','A1','shopping',1,'sale discount affordable'),
('w_shopping_A1_06','expensive','/ɪkˈspɛnsɪv/','adjective','비싼','Costing a lot of money.','That watch is too {expensive} for me.','저 시계는 저한테 너무 비싸요.','expensive','A1','shopping',1,'luxury expensive watch'),
('w_shopping_A1_07','money','/ˈmʌni/','noun','돈','Coins and paper notes used to buy things.','I don''t have enough {money} today.','오늘 돈이 충분하지 않아요.','money','A1','shopping',1,'cash coins money wallet'),
('w_shopping_A1_08','pay','/peɪ/','verb','지불하다','To give money in exchange for goods or a service.','Can I {pay} by card?','카드로 지불해도 될까요?','pay','A1','shopping',1,'payment card cashier'),
('w_shopping_A1_09','market','/ˈmɑːkɪt/','noun','시장','A place where goods are bought and sold.','The {market} opens at eight.','시장은 8시에 열려요.','market','A1','shopping',1,'outdoor market stalls vendors'),
('w_shopping_A1_10','store','/stɔːr/','noun','상점','A building where goods are sold to customers.','The {store} is closed on Sundays.','그 상점은 일요일에 문을 닫아요.','store','A1','shopping',1,'department store entrance'),
('w_shopping_A1_11','bag','/bæɡ/','noun','가방','A container made of paper, plastic, or leather used to carry things.','Can I have a {bag} for this, please?','이거 봉투에 넣어 주실 수 있어요?','bag','A1','shopping',1,'shopping bag paper bag'),
('w_shopping_A1_12','new','/njuː/','adjective','새로운','Recently made or bought; not used before.','I like your {new} coat.','새 코트 좋아 보여요.','new','A1','shopping',1,'new product unboxing'),
('w_shopping_A1_13','old','/oʊld/','adjective','오래된','Having existed for a long time; not new.','This is an {old} style.','이건 오래된 스타일이에요.','old','A1','shopping',1,'vintage old item secondhand'),
('w_shopping_A1_14','big','/bɪɡ/','adjective','큰','Large in size.','Do you have a {big} size?','큰 사이즈 있나요?','big','A1','shopping',1,'large size clothing'),
('w_shopping_A1_15','small','/smɔːl/','adjective','작은','Little in size.','This is too {small} for me.','이건 저한테 너무 작아요.','small','A1','shopping',1,'small item size comparison'),
('w_shopping_A1_16','open','/ˈoʊpən/','adjective','열린','Not closed; allowing entry.','Is the shop {open} now?','지금 가게 문 열었나요?','open','A1','shopping',1,'open sign store door'),
('w_shopping_A1_17','closed','/kloʊzd/','adjective','닫힌','Not open; not allowing entry.','The mall is {closed} today.','오늘 쇼핑몰이 닫혀 있어요.','closed','A1','shopping',1,'closed sign store'),
('w_shopping_A1_18','want','/wɒnt/','verb','원하다','To feel a desire for something.','I {want} to buy a gift.','선물을 사고 싶어요.','want','A1','shopping',1,'wish list shopping desire'),
('w_shopping_A1_19','need','/niːd/','verb','필요하다','To require something because it is essential.','I {need} new socks.','새 양말이 필요해요.','need','A1','shopping',1,'grocery list essentials'),
('w_shopping_A1_20','look','/lʊk/','verb','보다 / 찾다','To direct your eyes toward something; to search for.','I''m just {looking}, thank you.','그냥 구경하는 거예요, 감사해요.','looking','A1','shopping',1,'browsing window shopping'),
('w_shopping_A1_21','free','/friː/','adjective','무료의','Costing nothing.','Is delivery {free}?','배달은 무료인가요?','free','A1','shopping',1,'free shipping gift'),
('w_shopping_A1_22','gift','/ɡɪft/','noun','선물','Something given to someone without expecting payment.','I bought a {gift} for my friend.','친구에게 선물을 샀어요.','gift','A1','shopping',1,'wrapped gift present'),
('w_shopping_A1_23','total','/ˈtoʊtl/','noun','합계','The complete sum of all amounts.','What is the {total}?','합계가 얼마예요?','total','A1','shopping',1,'receipt total bill'),
('w_shopping_A1_24','cash','/kæʃ/','noun','현금','Money in the form of coins or paper notes.','Do you accept {cash}?','현금도 받나요?','cash','A1','shopping',1,'cash banknotes wallet'),
('w_shopping_A1_25','card','/kɑːrd/','noun','카드','A small plastic card used to pay for things.','I''ll pay by {card}.','카드로 낼게요.','card','A1','shopping',1,'credit card payment'),
('w_shopping_A1_26','help','/hɛlp/','verb','돕다','To make it easier for someone to do something.','Can you {help} me find a shirt?','셔츠 찾는 걸 도와주실 수 있어요?','help','A1','shopping',1,'shop assistant helping customer'),
('w_shopping_A1_27','find','/faɪnd/','verb','찾다','To discover or locate something.','Can you {find} size medium?','미디엄 사이즈 찾아줄 수 있어요?','find','A1','shopping',1,'searching store shelf'),
('w_shopping_A1_28','take','/teɪk/','verb','가져가다','To carry or accept something.','I''ll {take} this one.','이걸로 할게요.','take','A1','shopping',1,'picking item shelf'),
('w_shopping_A1_29','get','/ɡɛt/','verb','얻다 / 사다','To obtain or receive something.','Where can I {get} a map?','지도는 어디서 구할 수 있어요?','get','A1','shopping',1,'obtaining item store'),
('w_shopping_A1_30','give','/ɡɪv/','verb','주다','To hand something to someone.','Can you {give} me a receipt?','영수증을 주실 수 있어요?','give','A1','shopping',1,'handing receipt cashier'),
('w_shopping_A1_31','food','/fuːd/','noun','음식','Things you eat.','I''m looking for {food} items.','식품 코너를 찾고 있어요.','food','A1','shopping',1,'supermarket food aisle'),
('w_shopping_A1_32','clothes','/kloʊðz/','noun','옷','Things you wear on your body.','She loves buying new {clothes}.','그녀는 새 옷 사는 걸 좋아해요.','clothes','A1','shopping',1,'clothing rack fashion'),
('w_shopping_A1_33','book','/bʊk/','noun','책','A written or printed work.','I want to buy a {book}.','책을 사고 싶어요.','book','A1','shopping',1,'bookstore book shelf'),
('w_shopping_A1_34','color','/ˈkʌlər/','noun','색깔','A visual quality such as red, blue, or green.','Do you have this in another {color}?','다른 색깔로도 있나요?','color','A1','shopping',1,'colorful fabric swatches'),
('w_shopping_A1_35','number','/ˈnʌmbər/','noun','번호 / 숫자','A figure representing a quantity; also a shoe/size number.','What {number} is your shoe size?','신발 사이즈가 몇 번이에요?','number','A1','shopping',1,'size chart number label'),

-- ────────────────────────────────────────────────────────────
-- A2 (35 words)
-- ────────────────────────────────────────────────────────────
('w_shopping_A2_01','discount','/ˈdɪskaʊnt/','noun','할인','A reduction in the usual price of something.','Is there a {discount} for students?','학생 할인이 있나요?','discount','A2','shopping',2,'sale discount percent tag'),
('w_shopping_A2_02','sale','/seɪl/','noun','세일','A period when goods are sold at reduced prices.','Everything is on {sale} this weekend.','이번 주말에 모든 게 세일 중이에요.','sale','A2','shopping',2,'sale banner store'),
('w_shopping_A2_03','receipt','/rɪˈsiːt/','noun','영수증','A written acknowledgement of payment.','Please keep your {receipt}.','영수증을 보관해 주세요.','receipt','A2','shopping',2,'paper receipt cashier'),
('w_shopping_A2_04','size','/saɪz/','noun','사이즈','The measurement of how big or small something is.','Do you have this in my {size}?','제 사이즈로 있나요?','size','A2','shopping',2,'size label clothing tag'),
('w_shopping_A2_05','brand','/brænd/','noun','브랜드','A type of product made by a particular company.','What {brand} is this bag?','이 가방은 어느 브랜드예요?','brand','A2','shopping',2,'brand logo label'),
('w_shopping_A2_06','cashier','/kæˈʃɪər/','noun','계산원','A person who takes payments in a shop.','The {cashier} gave me the wrong change.','계산원이 잔돈을 잘못 줬어요.','cashier','A2','shopping',2,'cashier counter checkout'),
('w_shopping_A2_07','change','/tʃeɪndʒ/','noun','거스름돈','Money returned when you pay more than the cost.','Keep the {change}.','거스름돈은 가지세요.','change','A2','shopping',2,'coins change money'),
('w_shopping_A2_08','refund','/ˈriːfʌnd/','noun','환불','Money returned after returning a product.','I''d like a {refund}, please.','환불을 받고 싶어요.','refund','A2','shopping',2,'refund counter service desk'),
('w_shopping_A2_09','credit card','/ˈkrɛdɪt kɑːrd/','noun','신용카드','A card that lets you buy now and pay later.','Can I use a {credit card}?','신용카드 사용할 수 있나요?','credit card','A2','shopping',2,'credit card payment terminal'),
('w_shopping_A2_10','try on','/traɪ ɒn/','phrasal verb','입어보다','To put on clothing to see if it fits.','Can I {try on} this dress?','이 원피스 입어봐도 될까요?','try on','A2','shopping',2,'fitting room mirror clothes'),
('w_shopping_A2_11','fitting room','/ˈfɪtɪŋ ruːm/','noun','탈의실','A small room in a shop where you try on clothes.','Where is the {fitting room}?','탈의실이 어디예요?','fitting room','A2','shopping',2,'fitting room curtain mirror'),
('w_shopping_A2_12','queue','/kjuː/','noun','줄','A line of people waiting for something.','The {queue} is very long today.','오늘 줄이 정말 길어요.','queue','A2','shopping',2,'queue line checkout'),
('w_shopping_A2_13','trolley','/ˈtrɒli/','noun','카트','A large basket on wheels used in supermarkets.','I need a {trolley} for all these items.','이 물건들을 담을 카트가 필요해요.','trolley','A2','shopping',2,'shopping cart supermarket'),
('w_shopping_A2_14','basket','/ˈbɑːskɪt/','noun','장바구니','A container used for carrying shopping.','I only need a small {basket}.','작은 장바구니면 충분해요.','basket','A2','shopping',2,'shopping basket handle'),
('w_shopping_A2_15','aisle','/aɪl/','noun','통로','A passage between shelves in a shop.','Bread is in {aisle} three.','빵은 3번 통로에 있어요.','aisle','A2','shopping',2,'supermarket aisle shelf'),
('w_shopping_A2_16','shelf','/ʃɛlf/','noun','선반','A flat surface fixed to a wall for storing things.','The item is on the top {shelf}.','그 물건은 맨 위 선반에 있어요.','shelf','A2','shopping',2,'store shelf products'),
('w_shopping_A2_17','label','/ˈleɪbl/','noun','라벨','A piece of paper attached to an item with information.','Check the {label} for washing instructions.','세탁 방법은 라벨을 확인해 주세요.','label','A2','shopping',2,'clothing label tag'),
('w_shopping_A2_18','offer','/ˈɒfər/','noun','제안 / 특가','A price reduction or special deal.','This is a limited-time {offer}.','이건 기간 한정 특가 상품이에요.','offer','A2','shopping',2,'special offer promotion sign'),
('w_shopping_A2_19','exchange','/ɪksˈtʃeɪndʒ/','verb','교환하다','To return something and get a different item.','Can I {exchange} this for a larger size?','이걸 더 큰 사이즈로 교환할 수 있나요?','exchange','A2','shopping',2,'exchange return counter'),
('w_shopping_A2_20','popular','/ˈpɒpjʊlər/','adjective','인기 있는','Liked or enjoyed by many people.','This is our most {popular} product.','이게 저희 가장 인기 있는 상품이에요.','popular','A2','shopping',2,'bestseller tag popular item'),
('w_shopping_A2_21','quality','/ˈkwɒlɪti/','noun','품질','The standard of something as measured against others.','The {quality} of this fabric is excellent.','이 원단의 품질이 정말 좋아요.','quality','A2','shopping',2,'quality control fabric'),
('w_shopping_A2_22','choose','/tʃuːz/','verb','선택하다','To pick one from several options.','It''s hard to {choose} between these two.','이 둘 중에서 고르기가 어려워요.','choose','A2','shopping',2,'choosing between products'),
('w_shopping_A2_23','pay for','/peɪ fɔː/','phrasal verb','계산하다','To hand over money in exchange for something.','I''ll {pay for} dinner tonight.','오늘 저녁은 제가 낼게요.','pay for','A2','shopping',2,'paying bill restaurant'),
('w_shopping_A2_24','spend','/spɛnd/','verb','소비하다','To use money to buy something.','I always {spend} too much on clothes.','저는 항상 옷에 돈을 너무 많이 써요.','spend','A2','shopping',2,'spending money shopping'),
('w_shopping_A2_25','save','/seɪv/','verb','절약하다','To keep money instead of spending it.','I''m trying to {save} money this month.','이번 달에 돈을 절약하려고 해요.','save','A2','shopping',2,'piggy bank saving money'),
('w_shopping_A2_26','order','/ˈɔːrdər/','verb','주문하다','To request a product or service.','I''d like to {order} online.','온라인으로 주문하고 싶어요.','order','A2','shopping',2,'online order laptop'),
('w_shopping_A2_27','delivery','/dɪˈlɪvəri/','noun','배달 / 배송','The process of bringing goods to a buyer.','Free {delivery} on orders over fifty dollars.','50달러 이상 주문 시 무료 배송이에요.','delivery','A2','shopping',2,'delivery box parcel'),
('w_shopping_A2_28','wrap','/ræp/','verb','포장하다','To cover something with paper or material.','Could you {wrap} it as a gift?','선물 포장해 주실 수 있어요?','wrap','A2','shopping',2,'gift wrapping ribbon'),
('w_shopping_A2_29','warranty','/ˈwɒrənti/','noun','보증','A written guarantee on a product.','Does this come with a {warranty}?','이 제품에 보증이 포함되어 있나요?','warranty','A2','shopping',2,'warranty card electronics'),
('w_shopping_A2_30','return','/rɪˈtɜːrn/','verb','반품하다','To take a product back to the shop.','I need to {return} this jacket.','이 재킷을 반품해야 해요.','return','A2','shopping',2,'return counter bag'),
('w_shopping_A2_31','damaged','/ˈdæmɪdʒd/','adjective','손상된','Harmed or broken.','This item is {damaged}.','이 물건이 손상되어 있어요.','damaged','A2','shopping',2,'damaged product broken box'),
('w_shopping_A2_32','available','/əˈveɪləbl/','adjective','구매 가능한','In stock; ready to be bought or used.','Is this model {available} in blue?','이 모델 파란색으로 있나요?','available','A2','shopping',2,'in stock available sign'),
('w_shopping_A2_33','stock','/stɒk/','noun','재고','The goods available for sale.','We''re out of {stock} right now.','지금 재고가 없어요.','stock','A2','shopping',2,'out of stock empty shelf'),
('w_shopping_A2_34','member','/ˈmɛmbər/','noun','회원','A person who belongs to a club or loyalty programme.','Are you a {member} of our rewards club?','저희 포인트 클럽 회원이세요?','member','A2','shopping',2,'membership card rewards'),
('w_shopping_A2_35','point','/pɔɪnt/','noun','포인트','A unit in a reward scheme earned by buying things.','You''ve earned 200 {points} today.','오늘 200포인트 적립하셨어요.','point','A2','shopping',2,'loyalty points card app'),

-- ────────────────────────────────────────────────────────────
-- B1 (35 words)
-- ────────────────────────────────────────────────────────────
('w_shopping_B1_01','bargain','/ˈbɑːrɡɪn/','noun','흥정 / 특가품','Something bought at a low price; to negotiate a price.','That coat was a real {bargain}.','그 코트는 정말 특가품이었어요.','bargain','B1','shopping',3,'bargain deal sale price'),
('w_shopping_B1_02','checkout','/ˈtʃɛkaʊt/','noun','계산대','The place in a supermarket where you pay for goods.','Please go to {checkout} number five.','5번 계산대로 가주세요.','checkout','B1','shopping',3,'checkout counter cashier'),
('w_shopping_B1_03','browse','/braʊz/','verb','둘러보다','To look through items in a shop without a specific plan to buy.','I''m just {browsing} for now.','지금은 그냥 둘러보는 중이에요.','browsing','B1','shopping',3,'browsing store window shopping'),
('w_shopping_B1_04','wholesale','/ˈhoʊlseɪl/','adjective','도매의','Relating to selling goods in large quantities at low prices.','We buy goods at {wholesale} prices.','저희는 도매가로 물건을 구입해요.','wholesale','B1','shopping',3,'wholesale warehouse bulk'),
('w_shopping_B1_05','retail','/ˈriːteɪl/','noun','소매','The sale of goods directly to the public.','The {retail} price is higher than the wholesale price.','소매가가 도매가보다 높아요.','retail','B1','shopping',3,'retail store shopping mall'),
('w_shopping_B1_06','coupon','/ˈkuːpɒn/','noun','쿠폰','A voucher giving a discount on a product.','I have a {coupon} for ten percent off.','10% 할인 쿠폰이 있어요.','coupon','B1','shopping',3,'coupon discount voucher'),
('w_shopping_B1_07','loyalty','/ˈlɔɪəlti/','noun','충성도 (고객 충성)','Faithfulness to a brand or company, often rewarded by programmes.','Do you have a {loyalty} card?','포인트 카드 있으세요?','loyalty','B1','shopping',3,'loyalty card rewards programme'),
('w_shopping_B1_08','invoice','/ˈɪnvɔɪs/','noun','청구서 / 인보이스','A document listing goods sold and the amount owed.','Please send me the {invoice} by email.','이메일로 인보이스를 보내 주세요.','invoice','B1','shopping',3,'invoice document billing'),
('w_shopping_B1_09','vendor','/ˈvɛndər/','noun','판매자 / 노점상','A person or company that sells goods.','The street {vendor} sold fresh juice.','노점 판매자가 신선한 주스를 팔았어요.','vendor','B1','shopping',3,'street vendor stall market'),
('w_shopping_B1_10','negotiate','/nɪˈɡoʊʃieɪt/','verb','협상하다','To discuss terms in order to reach an agreement.','Can we {negotiate} the price?','가격을 협상할 수 있을까요?','negotiate','B1','shopping',3,'negotiation business deal'),
('w_shopping_B1_11','budget','/ˈbʌdʒɪt/','noun','예산','The amount of money available to spend.','I''m shopping on a tight {budget}.','빠듯한 예산으로 쇼핑하고 있어요.','budget','B1','shopping',3,'budget planning calculator'),
('w_shopping_B1_12','comparison','/kəmˈpærɪsən/','noun','비교','The act of looking at two or more things to judge similarities.','Price {comparison} apps save a lot of money.','가격 비교 앱으로 돈을 많이 아낄 수 있어요.','comparison','B1','shopping',3,'price comparison chart'),
('w_shopping_B1_13','purchase','/ˈpɜːrtʃəs/','noun/verb','구매 / 구매하다','The act of buying something; to buy.','Keep this as proof of {purchase}.','이걸 구매 증빙으로 보관하세요.','purchase','B1','shopping',3,'purchase receipt confirmation'),
('w_shopping_B1_14','transaction','/trænˈzækʃən/','noun','거래','An instance of buying or selling something.','The {transaction} was completed successfully.','거래가 성공적으로 완료됐어요.','transaction','B1','shopping',3,'transaction payment terminal'),
('w_shopping_B1_15','installment','/ɪnˈstɔːlmənt/','noun','할부','One of several payments made over time.','I''ll pay in twelve {installments}.','12개월 할부로 낼게요.','installment','B1','shopping',3,'installment plan payment'),
('w_shopping_B1_16','shipping','/ˈʃɪpɪŋ/','noun','배송 (비용)','The process of sending goods to a buyer; the cost of sending.','How much is the {shipping} fee?','배송비가 얼마예요?','shipping','B1','shopping',3,'shipping box delivery truck'),
('w_shopping_B1_17','tracking','/ˈtræk ɪŋ/','noun','배송 추적','Following the progress of a shipped order online.','I''m checking the {tracking} status.','배송 추적 상태를 확인하고 있어요.','tracking','B1','shopping',3,'tracking number parcel'),
('w_shopping_B1_18','subscription','/səbˈskrɪpʃən/','noun','구독 / 정기 결제','A regular payment for access to a service or product.','This is a monthly {subscription} box.','이건 월정기 구독 박스예요.','subscription','B1','shopping',3,'subscription box monthly service'),
('w_shopping_B1_19','bulk','/bʌlk/','noun','대량','A large quantity of something.','It''s cheaper to buy in {bulk}.','대량으로 사면 더 저렴해요.','bulk','B1','shopping',3,'bulk buy wholesale warehouse'),
('w_shopping_B1_20','second-hand','/ˌsɛkənd ˈhænd/','adjective','중고의','Previously owned by another person.','I found a {second-hand} camera for half the price.','반값에 중고 카메라를 구했어요.','second-hand','B1','shopping',3,'secondhand thrift store vintage'),
('w_shopping_B1_21','outlet','/ˈaʊtlɛt/','noun','아울렛','A shop selling surplus or discounted goods.','We drove to the {outlet} mall.','아울렛 쇼핑몰로 드라이브했어요.','outlet','B1','shopping',3,'outlet mall shopping'),
('w_shopping_B1_22','impulse','/ˈɪmpʌls/','noun','충동','A sudden desire to do something.','That was an {impulse} buy.','그건 충동구매였어요.','impulse','B1','shopping',3,'impulse buy checkout candy'),
('w_shopping_B1_23','complaint','/kəmˈpleɪnt/','noun','불만 / 항의','A statement that something is unsatisfactory.','I''d like to make a {complaint}.','불만 사항을 접수하고 싶어요.','complaint','B1','shopping',3,'complaint customer service'),
('w_shopping_B1_24','guarantee','/ˌɡærənˈtiː/','noun','보장 / 품질 보증','A formal promise that something will work or be fixed.','This product comes with a two-year {guarantee}.','이 제품은 2년 품질 보증이 있어요.','guarantee','B1','shopping',3,'guarantee certificate product'),
('w_shopping_B1_25','surplus','/ˈsɜːrpləs/','noun','잉여 / 남은 재고','An amount that is more than what is needed.','They sell {surplus} stock at reduced prices.','잉여 재고를 할인된 가격에 팔아요.','surplus','B1','shopping',3,'surplus stock clearance sale'),
('w_shopping_B1_26','clearance','/ˈklɪərəns/','noun','재고 정리 세일','A sale of remaining stock at low prices.','Everything in the {clearance} section is fifty percent off.','재고 정리 구역의 모든 상품이 50% 할인이에요.','clearance','B1','shopping',3,'clearance sale rack'),
('w_shopping_B1_27','merchant','/ˈmɜːrtʃənt/','noun','상인','A person who buys and sells goods.','The {merchant} offered a fair deal.','그 상인이 공정한 거래를 제안했어요.','merchant','B1','shopping',3,'merchant market stall trader'),
('w_shopping_B1_28','checkout process','/ˈtʃɛkaʊt ˈprəʊsɛs/','noun phrase','결제 과정','The steps involved in completing a purchase online or in-store.','The online {checkout process} is very simple.','온라인 결제 과정이 매우 간단해요.','checkout process','B1','shopping',3,'online checkout ecommerce'),
('w_shopping_B1_29','demand','/dɪˈmɑːnd/','noun','수요','The desire of consumers to purchase goods.','High {demand} caused the price to rise.','높은 수요로 가격이 올랐어요.','demand','B1','shopping',3,'demand supply economics'),
('w_shopping_B1_30','supply','/səˈplaɪ/','noun','공급','The amount of goods available for purchase.','The {supply} of masks ran low during the pandemic.','팬데믹 동안 마스크 공급이 부족했어요.','supply','B1','shopping',3,'supply chain warehouse'),
('w_shopping_B1_31','promotion','/prəˈmoʊʃən/','noun','판촉 / 프로모션','An activity to increase sales or awareness of a product.','We have a special {promotion} this week.','이번 주에 특별 프로모션이 있어요.','promotion','B1','shopping',3,'promotion sale advertisement'),
('w_shopping_B1_32','advertisement','/ˌædvərˈtaɪzmənt/','noun','광고','A notice promoting a product or service.','I saw an {advertisement} for this product.','이 제품 광고를 봤어요.','advertisement','B1','shopping',3,'advertisement poster billboard'),
('w_shopping_B1_33','consignment','/kənˈsaɪnmənt/','noun','위탁 판매','Goods sent to a retailer to sell on behalf of the supplier.','This boutique operates on a {consignment} basis.','이 부티크는 위탁 판매 방식으로 운영돼요.','consignment','B1','shopping',3,'consignment shop boutique'),
('w_shopping_B1_34','price tag','/praɪs tæɡ/','noun','가격표','A label attached to an item showing its price.','The {price tag} says it''s on sale.','가격표를 보니 세일 중이네요.','price tag','B1','shopping',3,'price tag label product'),
('w_shopping_B1_35','afterthought','/ˈɑːftərθɔːt/','noun','나중에 든 생각 / 부가품','Something added or considered after the main plan.','I bought the scarf as an {afterthought}.','스카프는 나중에 생각나서 샀어요.','afterthought','B1','shopping',3,'extra purchase addon item'),

-- ────────────────────────────────────────────────────────────
-- B2 (35 words)
-- ────────────────────────────────────────────────────────────
('w_shopping_B2_01','markup','/ˈmɑːrkʌp/','noun','마진 / 가격 인상','The amount added to the cost price to determine the selling price.','The {markup} on designer goods is often over 200%.','디자이너 상품의 마진은 흔히 200%가 넘어요.','markup','B2','shopping',4,'markup pricing profit margin'),
('w_shopping_B2_02','niche','/niːʃ/','adjective','틈새의','Relating to a small, specialised market segment.','They target a {niche} market of eco-conscious consumers.','친환경 소비자라는 틈새 시장을 공략해요.','niche','B2','shopping',4,'niche market specialty store'),
('w_shopping_B2_03','premium','/ˈpriːmiəm/','adjective','프리미엄의','Of higher quality and usually higher price.','This is a {premium} product line.','이건 프리미엄 제품 라인이에요.','premium','B2','shopping',4,'premium luxury product'),
('w_shopping_B2_04','authentic','/ɔːˈθɛntɪk/','adjective','정품의 / 진짜의','Genuine, not a copy or imitation.','Always check that the product is {authentic}.','제품이 정품인지 항상 확인하세요.','authentic','B2','shopping',4,'authentic certificate genuine'),
('w_shopping_B2_05','counterfeit','/ˈkaʊntərfɪt/','adjective','위조품의','Made to look like the real thing in order to deceive.','Be careful of {counterfeit} goods online.','온라인에서 위조품을 조심하세요.','counterfeit','B2','shopping',4,'counterfeit fake product'),
('w_shopping_B2_06','procurement','/prəˈkjʊərmənt/','noun','조달','The process of obtaining goods or services.','The company streamlined its {procurement} process.','회사가 조달 과정을 간소화했어요.','procurement','B2','shopping',4,'procurement supply chain'),
('w_shopping_B2_07','consumerism','/kənˈsjuːmərɪzəm/','noun','소비주의','The theory that increasing consumption is economically desirable.','Modern {consumerism} drives overproduction.','현대 소비주의가 과잉 생산을 초래해요.','consumerism','B2','shopping',4,'consumerism shopping mall crowd'),
('w_shopping_B2_08','impulse buying','/ˈɪmpʌls ˈbaɪɪŋ/','noun phrase','충동구매','Buying something without planning to do so.','{impulse buying} is triggered by clever store layouts.','매장 레이아웃이 충동구매를 유발해요.','impulse buying','B2','shopping',4,'impulse buy checkout display'),
('w_shopping_B2_09','price elasticity','/praɪs ˌɪlæˈstɪsɪti/','noun phrase','가격 탄력성','The degree to which demand changes in response to price changes.','{price elasticity} determines how much demand drops when prices rise.','가격 탄력성은 가격 상승 시 수요 감소 폭을 결정해요.','price elasticity','B2','shopping',4,'price elasticity chart economics'),
('w_shopping_B2_10','value for money','/ˈvæljuː fɔː ˈmʌni/','noun phrase','가성비','The extent to which something is worth what you pay for it.','This product offers great {value for money}.','이 제품은 가성비가 정말 좋아요.','value for money','B2','shopping',4,'value for money rating'),
('w_shopping_B2_11','comparison shopping','/kəmˈpærɪsən ˈʃɒpɪŋ/','noun phrase','비교 쇼핑','Checking prices across multiple stores before buying.','{comparison shopping} helps you find the best deal.','비교 쇼핑을 하면 최상의 거래를 찾을 수 있어요.','comparison shopping','B2','shopping',4,'price comparison website'),
('w_shopping_B2_12','upsell','/ˈʌpsɛl/','verb','추가 판매하다','To persuade a customer to buy something more expensive.','The salesperson tried to {upsell} me to a larger model.','영업 직원이 더 큰 모델을 사도록 유도했어요.','upsell','B2','shopping',4,'upsell upgrade salesperson'),
('w_shopping_B2_13','cross-sell','/ˈkrɒs sɛl/','verb','교차 판매하다','To sell an additional related product to an existing buyer.','The app {cross-sells} accessories with every device purchase.','앱이 기기 구매 시마다 액세서리를 교차 판매해요.','cross-sell','B2','shopping',4,'cross sell bundle deal'),
('w_shopping_B2_14','overcharge','/ˌoʊvərˈtʃɑːrdʒ/','verb','바가지 씌우다','To charge too high a price.','I think they {overcharged} me by ten dollars.','저한테 10달러 바가지를 씌운 것 같아요.','overcharged','B2','shopping',4,'overcharge bill mistake'),
('w_shopping_B2_15','rebate','/ˈriːbeɪt/','noun','리베이트 / 환급금','A partial refund to someone who has paid too much.','You''ll receive a {rebate} after submitting the form.','양식 제출 후 환급금을 받으실 거예요.','rebate','B2','shopping',4,'rebate check refund form'),
('w_shopping_B2_16','surcharge','/ˈsɜːrtʃɑːrdʒ/','noun','추가 요금','An extra charge added to the basic price.','There is a {surcharge} for weekend delivery.','주말 배송에는 추가 요금이 있어요.','surcharge','B2','shopping',4,'surcharge extra fee receipt'),
('w_shopping_B2_17','tariff','/ˈtærɪf/','noun','관세 / 요금표','A tax imposed on imported goods.','The new {tariff} has raised the price of electronics.','새 관세로 전자제품 가격이 올랐어요.','tariff','B2','shopping',4,'tariff customs border'),
('w_shopping_B2_18','consumer behaviour','/kənˈsjuːmər bɪˈheɪvjər/','noun phrase','소비자 행동','The actions and decisions of buyers in the marketplace.','Understanding {consumer behaviour} is key to marketing.','소비자 행동 이해가 마케팅의 핵심이에요.','consumer behaviour','B2','shopping',4,'consumer behaviour research'),
('w_shopping_B2_19','profit margin','/ˈprɒfɪt ˈmɑːrdʒɪn/','noun phrase','이익률','The percentage of revenue that is profit.','High {profit margins} depend on controlling costs.','높은 이익률은 비용 관리에 달려 있어요.','profit margin','B2','shopping',4,'profit margin chart business'),
('w_shopping_B2_20','brick-and-mortar','/ˌbrɪk ən ˈmɔːrtər/','adjective','오프라인 매장의','Relating to a physical shop, not online.','Many {brick-and-mortar} stores are struggling against online retailers.','많은 오프라인 매장들이 온라인 유통업체와의 경쟁으로 어려움을 겪고 있어요.','brick-and-mortar','B2','shopping',4,'physical store retail building'),
('w_shopping_B2_21','e-commerce','/ˈiːkɒmɜːrs/','noun','전자상거래','Buying and selling goods and services over the internet.','{e-commerce} sales have surged in recent years.','최근 몇 년간 전자상거래 매출이 급증했어요.','e-commerce','B2','shopping',4,'ecommerce online shopping laptop'),
('w_shopping_B2_22','supply chain','/səˈplaɪ tʃeɪn/','noun phrase','공급망','The network between a company and its suppliers to produce and distribute goods.','The pandemic disrupted global {supply chains}.','팬데믹이 글로벌 공급망을 교란했어요.','supply chain','B2','shopping',4,'supply chain logistics map'),
('w_shopping_B2_23','inventory','/ˈɪnvəntɔːri/','noun','재고 목록 / 재고','A complete list of goods held in stock.','We do a monthly {inventory} check.','매달 재고 점검을 해요.','inventory','B2','shopping',4,'inventory warehouse stock'),
('w_shopping_B2_24','seasonal','/ˈsiːzənl/','adjective','계절적인','Occurring at or relating to a particular time of year.','{seasonal} discounts are biggest in January.','계절 할인은 1월에 가장 커요.','seasonal','B2','shopping',4,'seasonal sale winter clearance'),
('w_shopping_B2_25','flagship','/ˈflæɡʃɪp/','noun','대표 / 기함 (매장)','The best or most important product or store of a brand.','The brand opened its {flagship} store in Seoul.','브랜드가 서울에 대표 매장을 열었어요.','flagship','B2','shopping',4,'flagship store luxury brand'),
('w_shopping_B2_26','currency','/ˈkʌrənsi/','noun','통화','A system of money used in a country.','The price changes depending on the {currency}.','통화에 따라 가격이 달라져요.','currency','B2','shopping',4,'currency exchange money'),
('w_shopping_B2_27','exchange rate','/ɪksˈtʃeɪndʒ reɪt/','noun phrase','환율','The value of one currency relative to another.','Check the {exchange rate} before shopping abroad.','해외 쇼핑 전에 환율을 확인하세요.','exchange rate','B2','shopping',4,'exchange rate board travel'),
('w_shopping_B2_28','loyalty programme','/ˈlɔɪəlti ˈprəʊɡræm/','noun phrase','고객 충성도 프로그램','A marketing scheme rewarding repeat customers.','Join our {loyalty programme} to earn cashback.','현금 적립을 위해 고객 충성도 프로그램에 가입하세요.','loyalty programme','B2','shopping',4,'loyalty programme card app'),
('w_shopping_B2_29','consumer rights','/kənˈsjuːmər raɪts/','noun phrase','소비자 권리','The rights that protect buyers from unfair business practices.','You should know your {consumer rights}.','소비자 권리를 알고 있어야 해요.','consumer rights','B2','shopping',4,'consumer rights protection law'),
('w_shopping_B2_30','product recall','/ˈprɒdʌkt rɪˈkɔːl/','noun phrase','제품 리콜','The process of taking back defective products from the market.','The company issued a {product recall} for safety reasons.','회사가 안전상의 이유로 제품 리콜을 실시했어요.','product recall','B2','shopping',4,'product recall announcement'),
('w_shopping_B2_31','sustainable','/səˈsteɪnəbl/','adjective','지속 가능한','Causing little or no damage to the environment.','I prefer {sustainable} fashion brands.','저는 지속 가능한 패션 브랜드를 선호해요.','sustainable','B2','shopping',4,'sustainable eco fashion'),
('w_shopping_B2_32','fast fashion','/fɑːst ˈfæʃən/','noun phrase','패스트 패션','Cheaply made clothes produced rapidly to follow trends.','{Fast fashion} creates enormous textile waste.','패스트 패션은 엄청난 섬유 폐기물을 만들어요.','fast fashion','B2','shopping',4,'fast fashion clothing pile'),
('w_shopping_B2_33','ethical shopping','/ˈɛθɪkl ˈʃɒpɪŋ/','noun phrase','윤리적 쇼핑','Buying goods that are produced in socially responsible ways.','{Ethical shopping} considers workers'' conditions and environmental impact.','윤리적 쇼핑은 노동자 환경과 생태적 영향을 고려해요.','ethical shopping','B2','shopping',4,'ethical trade fair fashion'),
('w_shopping_B2_34','price sensitive','/praɪs ˈsɛnsɪtɪv/','adjective','가격에 민감한','Strongly affected by changes in price.','Our customers are very {price sensitive}.','저희 고객들은 가격에 매우 민감해요.','price sensitive','B2','shopping',4,'price sensitive consumer chart'),
('w_shopping_B2_35','competitive pricing','/kəmˈpɛtɪtɪv ˈpraɪsɪŋ/','noun phrase','경쟁력 있는 가격 책정','Setting prices based on what competitors charge.','{Competitive pricing} keeps our market share high.','경쟁력 있는 가격 책정으로 시장 점유율을 유지해요.','competitive pricing','B2','shopping',4,'competitive pricing strategy chart'),

-- ────────────────────────────────────────────────────────────
-- C1 (35 words)
-- ────────────────────────────────────────────────────────────
('w_shopping_C1_01','arbitrage','/ˈɑːrbɪtrɑːʒ/','noun','차익거래','The practice of buying and selling to profit from a price difference.','He profits from currency {arbitrage}.','그는 환율 차익거래로 수익을 올려요.','arbitrage','C1','shopping',5,'arbitrage trade profit'),
('w_shopping_C1_02','liquidation','/ˌlɪkwɪˈdeɪʃən/','noun','청산 / 재고 처분','The process of closing a business and selling all its assets.','The company entered {liquidation} after filing for bankruptcy.','회사가 파산 신청 후 청산에 들어갔어요.','liquidation','C1','shopping',5,'liquidation sale clearance'),
('w_shopping_C1_03','franchise','/ˈfræntʃaɪz/','noun','프랜차이즈','A licence to operate a business using another company''s brand.','She opened a {franchise} of a popular coffee chain.','그녀는 인기 커피 체인의 프랜차이즈를 열었어요.','franchise','C1','shopping',5,'franchise business brand'),
('w_shopping_C1_04','monopoly','/məˈnɒpəli/','noun','독점','Exclusive control of supply of a product or service.','The government broke up the retail {monopoly}.','정부가 소매 독점을 해체했어요.','monopoly','C1','shopping',5,'monopoly market dominance'),
('w_shopping_C1_05','oligopoly','/ˌɒlɪˈɡɒpəli/','noun','과점','A market dominated by a small number of large sellers.','The smartphone market is essentially an {oligopoly}.','스마트폰 시장은 사실상 과점 구조예요.','oligopoly','C1','shopping',5,'oligopoly market few companies'),
('w_shopping_C1_06','bespoke','/bɪˈspoʊk/','adjective','맞춤 제작의','Made to order for a specific customer.','He ordered a {bespoke} suit from the tailor.','그는 재단사에게 맞춤 정장을 주문했어요.','bespoke','C1','shopping',5,'bespoke tailored suit custom'),
('w_shopping_C1_07','boutique','/buːˈtiːk/','noun','부티크','A small shop selling fashionable clothes or luxury goods.','She found a vintage dress in a tiny {boutique}.','그녀는 작은 부티크에서 빈티지 드레스를 발견했어요.','boutique','C1','shopping',5,'boutique fashion store luxury'),
('w_shopping_C1_08','artisan','/ˈɑːrtɪzən/','noun','장인','A skilled craftsman who makes goods by hand.','This bag is handmade by a local {artisan}.','이 가방은 지역 장인이 수작업으로 만든 거예요.','artisan','C1','shopping',5,'artisan craft handmade workshop'),
('w_shopping_C1_09','exclusive','/ɪkˈskluːsɪv/','adjective','독점적인 / 한정판의','Available only to particular people; luxury and restricted.','This is an {exclusive} limited edition release.','이건 한정판 단독 출시예요.','exclusive','C1','shopping',5,'exclusive limited edition luxury'),
('w_shopping_C1_10','provenance','/ˈprɒvənəns/','noun','원산지 / 출처','The place of origin or history of an item.','The {provenance} of this antique is well documented.','이 골동품의 출처가 잘 문서화되어 있어요.','provenance','C1','shopping',5,'provenance antique certificate'),
('w_shopping_C1_11','connoisseur','/ˌkɒnəˈsɜːr/','noun','감정가 / 전문가','An expert judge in matters of taste.','She is a {connoisseur} of Japanese ceramics.','그녀는 일본 도자기 감정가예요.','connoisseur','C1','shopping',5,'connoisseur expert tasting'),
('w_shopping_C1_12','valuation','/ˌvæljuˈeɪʃən/','noun','감정 평가','An estimate of the worth of something.','We need a professional {valuation} of the estate.','부동산의 전문적인 감정 평가가 필요해요.','valuation','C1','shopping',5,'valuation appraisal property'),
('w_shopping_C1_13','appraisal','/əˈpreɪzl/','noun','평가 / 감정','A formal assessment of the value of an item.','The jewellery store offered a free {appraisal}.','귀금속 가게에서 무료 감정을 제공했어요.','appraisal','C1','shopping',5,'appraisal jewelry value'),
('w_shopping_C1_14','price point','/praɪs pɔɪnt/','noun phrase','가격대','A specific price at which something is offered.','This product targets the mid-range {price point}.','이 제품은 중간 가격대를 겨냥하고 있어요.','price point','C1','shopping',5,'price point target market'),
('w_shopping_C1_15','margin compression','/ˈmɑːrdʒɪn kəmˈprɛʃən/','noun phrase','마진 압박','The reduction of the difference between the selling price and the cost.','{Margin compression} forces retailers to cut costs.','마진 압박으로 소매업체들이 비용을 절감해야 해요.','margin compression','C1','shopping',5,'margin squeeze profit decline'),
('w_shopping_C1_16','shelf life','/ʃɛlf laɪf/','noun phrase','유통 기한','The length of time a product remains usable.','Check the {shelf life} before purchasing perishables.','부패하기 쉬운 식품은 구매 전 유통 기한을 확인하세요.','shelf life','C1','shopping',5,'shelf life expiry date food'),
('w_shopping_C1_17','brand equity','/brænd ˈɛkwɪti/','noun phrase','브랜드 가치','The commercial value derived from consumer perception of a brand.','{Brand equity} allows premium pricing.','브랜드 가치는 프리미엄 가격 책정을 가능하게 해요.','brand equity','C1','shopping',5,'brand equity marketing'),
('w_shopping_C1_18','market penetration','/ˈmɑːrkɪt ˌpɛnɪˈtreɪʃən/','noun phrase','시장 침투','A strategy of selling more of an existing product in existing markets.','{Market penetration} pricing uses low prices to gain share.','시장 침투 가격 전략은 점유율을 높이기 위해 낮은 가격을 사용해요.','market penetration','C1','shopping',5,'market penetration strategy'),
('w_shopping_C1_19','acquisition cost','/ˌækwɪˈzɪʃən kɒst/','noun phrase','고객 획득 비용','The cost of gaining a new customer.','Reducing {acquisition cost} improves profitability.','고객 획득 비용을 줄이면 수익성이 개선돼요.','acquisition cost','C1','shopping',5,'customer acquisition marketing'),
('w_shopping_C1_20','price discrimination','/praɪs ˌdɪskrɪmɪˈneɪʃən/','noun phrase','가격 차별','Selling the same product at different prices to different customers.','{Price discrimination} is common in airline ticketing.','가격 차별은 항공권 판매에서 흔해요.','price discrimination','C1','shopping',5,'price discrimination airlines'),
('w_shopping_C1_21','vertically integrated','/ˌvɜːrtɪkli ˈɪntɪɡreɪtɪd/','adjective','수직 통합된','Describing a company that controls multiple stages of production and distribution.','Apple is {vertically integrated} from chip design to retail.','애플은 칩 설계부터 소매까지 수직 통합되어 있어요.','vertically integrated','C1','shopping',5,'vertical integration supply chain'),
('w_shopping_C1_22','disintermediation','/ˌdɪsɪntəˌmiːdiˈeɪʃən/','noun','중간상 제거','Removing intermediaries from a supply chain.','{Disintermediation} allows brands to sell directly to consumers.','중간상 제거로 브랜드가 소비자에게 직접 판매할 수 있어요.','disintermediation','C1','shopping',5,'direct to consumer brand'),
('w_shopping_C1_23','ancillary revenue','/ænˈsɪləri ˈrɛvənjuː/','noun phrase','부가 수익','Income from additional products or services beyond the main offering.','Airlines rely heavily on {ancillary revenue} from baggage fees.','항공사는 수하물 요금 같은 부가 수익에 크게 의존해요.','ancillary revenue','C1','shopping',5,'ancillary revenue airline fees'),
('w_shopping_C1_24','market segmentation','/ˈmɑːrkɪt ˌsɛɡmɛnˈteɪʃən/','noun phrase','시장 세분화','Dividing consumers into groups based on shared characteristics.','{Market segmentation} helps tailor marketing messages.','시장 세분화는 마케팅 메시지를 맞춤화하는 데 도움이 돼요.','market segmentation','C1','shopping',5,'market segmentation demographics'),
('w_shopping_C1_25','loss leader','/lɒs ˈliːdər/','noun phrase','미끼 상품','A product sold at a loss to attract customers who then buy other items.','Supermarkets use milk as a {loss leader}.','슈퍼마켓은 우유를 미끼 상품으로 활용해요.','loss leader','C1','shopping',5,'loss leader grocery sale'),
('w_shopping_C1_26','dynamic pricing','/daɪˈnæmɪk ˈpraɪsɪŋ/','noun phrase','동적 가격 책정','Adjusting prices in real time based on demand and other factors.','{Dynamic pricing} allows airlines to maximise revenue.','동적 가격 책정으로 항공사가 수익을 극대화해요.','dynamic pricing','C1','shopping',5,'dynamic pricing surge algorithm'),
('w_shopping_C1_27','bundle pricing','/ˈbʌndl ˈpraɪsɪŋ/','noun phrase','묶음 가격 책정','Selling multiple products together at a combined price.','{Bundle pricing} increases perceived value.','묶음 가격 책정은 체감 가치를 높여요.','bundle pricing','C1','shopping',5,'bundle deal products package'),
('w_shopping_C1_28','anchor pricing','/ˈæŋkər ˈpraɪsɪŋ/','noun phrase','앵커 가격 전략','Presenting a higher price first to make a lower price seem cheaper.','{Anchor pricing} influences how customers perceive value.','앵커 가격 전략은 고객이 가치를 인식하는 방식에 영향을 줘요.','anchor pricing','C1','shopping',5,'anchor price tag sale'),
('w_shopping_C1_29','shrinkage','/ˈʃrɪŋkɪdʒ/','noun','재고 손실','Retail inventory loss due to theft, damage, or error.','{Shrinkage} costs retailers billions each year.','재고 손실은 소매업체에 매년 수십억의 비용을 발생시켜요.','shrinkage','C1','shopping',5,'shrinkage theft store loss'),
('w_shopping_C1_30','grey market','/ɡreɪ ˈmɑːrkɪt/','noun phrase','회색 시장','The trade of goods through unofficial channels.','He bought the phone through the {grey market}.','그는 회색 시장을 통해 폰을 구입했어요.','grey market','C1','shopping',5,'grey market parallel import'),
('w_shopping_C1_31','price floor','/praɪs flɔːr/','noun phrase','가격 하한선','The minimum price allowed by law or regulation.','The government set a {price floor} for wheat.','정부가 밀에 대한 가격 하한선을 설정했어요.','price floor','C1','shopping',5,'price floor minimum wage'),
('w_shopping_C1_32','price ceiling','/praɪs ˈsiːlɪŋ/','noun phrase','가격 상한선','The maximum price set by law for a product.','Rent control is a type of {price ceiling}.','임대료 통제는 가격 상한선의 한 유형이에요.','price ceiling','C1','shopping',5,'price ceiling regulation'),
('w_shopping_C1_33','customer lifetime value','/ˈkʌstəmər ˈlaɪftaɪm ˈvæljuː/','noun phrase','고객 생애 가치','The total revenue a business can expect from a single customer.','Increasing {customer lifetime value} is a core business goal.','고객 생애 가치를 높이는 것이 핵심 사업 목표예요.','customer lifetime value','C1','shopping',5,'customer value analytics'),
('w_shopping_C1_34','omnichannel','/ˈɒmnɪˌtʃænl/','adjective','옴니채널의','Using all available channels of retail to give customers a seamless experience.','The brand offers an {omnichannel} shopping experience.','브랜드가 옴니채널 쇼핑 경험을 제공해요.','omnichannel','C1','shopping',5,'omnichannel retail digital store'),
('w_shopping_C1_35','stockout','/ˈstɒkaʊt/','noun','품절 / 재고 소진','A situation where a retailer runs out of a product.','Frequent {stockouts} damage brand reputation.','잦은 품절은 브랜드 평판을 손상시켜요.','stockout','C1','shopping',5,'stockout empty shelf sold out'),

-- ────────────────────────────────────────────────────────────
-- C2 (35 words)
-- ────────────────────────────────────────────────────────────
('w_shopping_C2_01','commodification','/kəˌmɒdɪfɪˈkeɪʃən/','noun','상품화','The transformation of something into a commercial product.','{Commodification} of personal data is a modern concern.','개인 데이터의 상품화는 현대의 주요 우려 사항이에요.','commodification','C2','shopping',6,'commodification data digital'),
('w_shopping_C2_02','mercantilism','/ˈmɜːrkəntɪlɪzəm/','noun','중상주의','An economic theory holding that wealth is maximised by exporting more than importing.','{Mercantilism} shaped colonial trade policies.','중상주의가 식민지 무역 정책을 형성했어요.','mercantilism','C2','shopping',6,'mercantilism trade history'),
('w_shopping_C2_03','arbitrageur','/ˌɑːrbɪtrɑːˈʒɜːr/','noun','차익거래자','A person who profits from price differences across markets.','The {arbitrageur} exploited exchange rate discrepancies.','차익거래자가 환율 차이를 이용했어요.','arbitrageur','C2','shopping',6,'arbitrageur trader finance'),
('w_shopping_C2_04','conglomerate','/kənˈɡlɒmərɪt/','noun','대기업 (복합 기업)','A corporation owning a variety of businesses in different sectors.','The retail {conglomerate} operates in twelve countries.','그 유통 대기업은 12개국에서 운영돼요.','conglomerate','C2','shopping',6,'conglomerate corporation multinational'),
('w_shopping_C2_05','cartel','/kɑːrˈtɛl/','noun','카르텔','An association of businesses that agree to fix prices.','The authorities broke up the oil-price {cartel}.','당국이 석유 가격 카르텔을 해체했어요.','cartel','C2','shopping',6,'cartel monopoly price fixing'),
('w_shopping_C2_06','monopsony','/mɒˈnɒpsəni/','noun','수요 독점 (단일 구매자 시장)','A market where there is only one major buyer.','A large retailer can act as a {monopsony} for local suppliers.','대형 소매업체는 지역 공급업체에 대해 수요 독점처럼 행동할 수 있어요.','monopsony','C2','shopping',6,'monopsony market power buyer'),
('w_shopping_C2_07','depreciation','/dɪˌpriːʃiˈeɪʃən/','noun','감가상각','The reduction in value of an asset over time.','Electronics suffer rapid {depreciation}.','전자제품은 빠른 감가상각을 겪어요.','depreciation','C2','shopping',6,'depreciation asset value chart'),
('w_shopping_C2_08','amortization','/əˌmɔːrtɪˈzeɪʃən/','noun','상각 / 분할 상환','The gradual writing off of an asset''s value.','{Amortization} spreads costs over the useful life of an asset.','상각은 자산의 내용 연수에 걸쳐 비용을 배분해요.','amortization','C2','shopping',6,'amortization schedule finance'),
('w_shopping_C2_09','asset','/ˈæsɛt/','noun','자산','A resource owned by a business or individual with economic value.','Brand recognition is an intangible {asset}.','브랜드 인지도는 무형 자산이에요.','asset','C2','shopping',6,'asset balance sheet business'),
('w_shopping_C2_10','liability','/laɪəˈbɪlɪti/','noun','부채 / 법적 책임','A debt or legal obligation owed by a business or individual.','Excess debt is a serious {liability}.','과도한 부채는 심각한 부담이에요.','liability','C2','shopping',6,'liability debt balance sheet'),
('w_shopping_C2_11','oligopsony','/ˌɒlɪˈɡɒpsəni/','noun','소수 구매자 과점','A market in which a small number of buyers control demand.','The fashion industry resembles an {oligopsony} with a few powerful retailers.','패션 업계는 소수의 강력한 소매업체가 지배하는 소수 구매자 과점과 유사해요.','oligopsony','C2','shopping',6,'oligopsony market economics'),
('w_shopping_C2_12','externality','/ˌɛkstɜːrˈnælɪti/','noun','외부 효과','A cost or benefit affecting parties not involved in a transaction.','Pollution from production is a negative {externality}.','생산에서 발생하는 오염은 부정적 외부 효과예요.','externality','C2','shopping',6,'externality pollution economics'),
('w_shopping_C2_13','price gouging','/praɪs ˈɡaʊdʒɪŋ/','noun phrase','폭리 (부당 가격 인상)','Charging excessively high prices during an emergency.','{Price gouging} for medical supplies during a crisis is illegal.','위기 상황에서 의료용품에 폭리를 취하는 건 불법이에요.','price gouging','C2','shopping',6,'price gouging disaster supply'),
('w_shopping_C2_14','regulatory arbitrage','/ˈrɛɡjʊlətɔːri ˈɑːrbɪtrɑːʒ/','noun phrase','규제 차익거래','Taking advantage of differences in regulations between jurisdictions.','{Regulatory arbitrage} allows firms to circumvent local laws.','규제 차익거래로 기업이 현지 법규를 우회할 수 있어요.','regulatory arbitrage','C2','shopping',6,'regulatory arbitrage law finance'),
('w_shopping_C2_15','planned obsolescence','/plænd ˌɒbsəˈlɛsns/','noun phrase','계획적 노후화','Designing products to become obsolete quickly to encourage repurchasing.','{Planned obsolescence} drives consumer electronics sales.','계획적 노후화가 소비자 전자제품 판매를 촉진해요.','planned obsolescence','C2','shopping',6,'planned obsolescence electronics'),
('w_shopping_C2_16','conspicuous consumption','/kənˈspɪkjuəs kənˈsʌmpʃən/','noun phrase','과시적 소비','Buying expensive things to display wealth or status.','{Conspicuous consumption} is central to luxury brand strategy.','과시적 소비는 명품 브랜드 전략의 핵심이에요.','conspicuous consumption','C2','shopping',6,'conspicuous consumption luxury status'),
('w_shopping_C2_17','veblen good','/ˈvɛblən ɡʊd/','noun phrase','베블런 재화','A product for which demand increases as price rises, due to its status symbol.','Luxury handbags are classic {veblen goods}.','명품 핸드백은 전형적인 베블런 재화예요.','veblen good','C2','shopping',6,'veblen good luxury demand'),
('w_shopping_C2_18','moral hazard','/ˈmɒrəl ˈhæzərd/','noun phrase','도덕적 해이','A situation where someone takes risks because others bear the cost.','{Moral hazard} arises when buyers are insured against loss.','구매자가 손실에 대해 보험에 가입되어 있을 때 도덕적 해이가 발생해요.','moral hazard','C2','shopping',6,'moral hazard risk insurance'),
('w_shopping_C2_19','asymmetric information','/eɪˌsɪmɪtrɪk ˌɪnfəˈmeɪʃən/','noun phrase','정보 비대칭','A situation where one party in a transaction has more information than the other.','{Asymmetric information} can lead to market failure.','정보 비대칭은 시장 실패로 이어질 수 있어요.','asymmetric information','C2','shopping',6,'information asymmetry economics'),
('w_shopping_C2_20','predatory pricing','/ˈprɛdətɔːri ˈpraɪsɪŋ/','noun phrase','약탈적 가격 책정','Setting prices very low to drive competitors out of the market.','{Predatory pricing} by dominant firms is often illegal.','지배적 기업의 약탈적 가격 책정은 종종 불법이에요.','predatory pricing','C2','shopping',6,'predatory pricing competition law'),
('w_shopping_C2_21','transfer pricing','/ˈtrænsfɜːr ˈpraɪsɪŋ/','noun phrase','이전 가격 책정','Setting prices for transactions between related business entities.','{Transfer pricing} is used to shift profits to lower-tax jurisdictions.','이전 가격 책정은 이익을 세금이 낮은 지역으로 이전하는 데 사용돼요.','transfer pricing','C2','shopping',6,'transfer pricing tax corporate'),
('w_shopping_C2_22','demand curve','/dɪˈmɑːnd kɜːrv/','noun phrase','수요 곡선','A graph showing the relationship between price and quantity demanded.','The {demand curve} shifts right when consumer income rises.','소비자 소득이 증가하면 수요 곡선이 오른쪽으로 이동해요.','demand curve','C2','shopping',6,'demand curve economics graph'),
('w_shopping_C2_23','deadweight loss','/ˈdɛdweɪt lɒs/','noun phrase','사중손실','The loss of economic efficiency due to market distortion.','{Deadweight loss} occurs when prices are above the competitive equilibrium.','가격이 경쟁 균형보다 높을 때 사중손실이 발생해요.','deadweight loss','C2','shopping',6,'deadweight loss economics chart'),
('w_shopping_C2_24','liquidity','/lɪˈkwɪdɪti/','noun','유동성','The availability of liquid assets to a market or company.','High {liquidity} allows quick asset conversion to cash.','높은 유동성은 자산을 현금으로 빠르게 전환할 수 있게 해요.','liquidity','C2','shopping',6,'liquidity cash flow finance'),
('w_shopping_C2_25','solvency','/ˈsɒlvənsi/','noun','지급 능력','The ability of a business to meet its long-term financial obligations.','Maintaining {solvency} is critical for long-term business survival.','지급 능력 유지는 장기적 사업 생존에 핵심이에요.','solvency','C2','shopping',6,'solvency finance balance sheet'),
('w_shopping_C2_26','net present value','/nɛt ˈprɛznt ˈvæljuː/','noun phrase','순현재가치','The present value of future cash flows minus the initial investment.','{Net present value} guides investment decisions.','순현재가치는 투자 결정을 안내해요.','net present value','C2','shopping',6,'NPV finance investment'),
('w_shopping_C2_27','capital expenditure','/ˈkæpɪtl ɪkˈspɛndɪtʃər/','noun phrase','자본 지출','Money spent on acquiring or upgrading long-term assets.','{Capital expenditure} in new stores improves customer experience.','신규 매장의 자본 지출이 고객 경험을 개선해요.','capital expenditure','C2','shopping',6,'capital expenditure investment business'),
('w_shopping_C2_28','venture capital','/ˈvɛntʃər ˈkæpɪtl/','noun phrase','벤처 캐피탈','Investment provided to start-ups and small businesses with high growth potential.','{Venture capital} fuelled the rise of e-commerce startups.','벤처 캐피탈이 전자상거래 스타트업의 성장을 촉진했어요.','venture capital','C2','shopping',6,'venture capital startup funding'),
('w_shopping_C2_29','due diligence','/djuː ˈdɪlɪdʒəns/','noun phrase','실사 (사전 조사)','Thorough research before signing a business deal.','Conduct full {due diligence} before acquiring a supplier.','공급업체 인수 전 완전한 실사를 수행하세요.','due diligence','C2','shopping',6,'due diligence audit business'),
('w_shopping_C2_30','intellectual property','/ˌɪntəˈlɛktʃuəl ˈprɒpərti/','noun phrase','지식재산권','Creations of the mind protected by law, such as brands and designs.','{Intellectual property} infringement is rampant in fast fashion.','패스트 패션에서 지식재산권 침해가 만연해요.','intellectual property','C2','shopping',6,'intellectual property trademark patent'),
('w_shopping_C2_31','economies of scale','/ɪˈkɒnəmɪz əv skeɪl/','noun phrase','규모의 경제','Cost advantages gained by increased levels of production.','{Economies of scale} allow supermarkets to offer lower prices.','규모의 경제가 슈퍼마켓이 더 낮은 가격을 제공하게 해줘요.','economies of scale','C2','shopping',6,'economies of scale production cost'),
('w_shopping_C2_32','diseconomies of scale','/dɪsɪˈkɒnəmɪz əv skeɪl/','noun phrase','규모의 비경제','The cost disadvantages that arise with increasing scale of production.','{Diseconomies of scale} arise when organisations grow too large.','조직이 너무 커지면 규모의 비경제가 발생해요.','diseconomies of scale','C2','shopping',6,'diseconomies scale management'),
('w_shopping_C2_33','gig economy','/ɡɪɡ ɪˈkɒnəmi/','noun phrase','긱 경제','An economy characterised by short-term contracts rather than permanent jobs.','Many delivery workers are part of the {gig economy}.','많은 배달 종사자가 긱 경제의 일원이에요.','gig economy','C2','shopping',6,'gig economy freelance delivery'),
('w_shopping_C2_34','trade surplus','/treɪd ˈsɜːrpləs/','noun phrase','무역 흑자','When a country exports more than it imports.','South Korea has maintained a {trade surplus} for decades.','한국은 수십 년간 무역 흑자를 유지해왔어요.','trade surplus','C2','shopping',6,'trade surplus export import'),
('w_shopping_C2_35','trade deficit','/treɪd ˈdɛfɪsɪt/','noun phrase','무역 적자','When a country imports more than it exports.','A growing {trade deficit} can weaken a national currency.','무역 적자가 증가하면 자국 통화가 약해질 수 있어요.','trade deficit','C2','shopping',6,'trade deficit import economy')
ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- SENTENCES (PATTERNS)
-- ============================================================

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES

-- ────────────────────────────────────────────────────────────
-- A1 — 가격 문의 & 계산 (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_shopping_A1_01','How much is this?','이거 얼마예요?','How much is this','"How much is this?"는 가격을 물을 때 가장 기본적인 표현이에요. 매장 어디서든 바로 쓸 수 있어요.','가격 문의','A1','shopping','pattern',NULL,1),
('s_shopping_A1_02','How much does this cost?','이게 얼마예요?','How much does this cost','"How much does this cost?"는 "How much is this?"보다 조금 더 격식 있는 표현이에요.','가격 문의','A1','shopping','pattern',NULL,2),
('s_shopping_A1_03','I''ll take this one, please.','이걸로 할게요.','I''ll take this one','"I''ll take this one."은 구매 결정을 표현하는 가장 자연스럽고 예의 바른 방법이에요.','구매 결정','A1','shopping','pattern',NULL,3),
('s_shopping_A1_04','Can I pay by card?','카드로 지불해도 될까요?','Can I pay by card','"Can I pay by card?"는 신용카드·체크카드 모두에 쓸 수 있는 표현이에요.','계산','A1','shopping','pattern',NULL,4),
('s_shopping_A1_05','Do you have this in a bigger size?','이거 더 큰 사이즈 있나요?','bigger size','사이즈를 물을 때 "bigger/smaller/different size"를 함께 기억하면 유용해요.','사이즈 문의','A1','shopping','pattern',NULL,5),
('s_shopping_A1_06','Can I have a bag, please?','봉투 주실 수 있어요?','Can I have a bag','영국식 영어에서는 "carrier bag", 미국식에서는 "shopping bag"이라고도 해요.','쇼핑백 요청','A1','shopping','pattern',NULL,6),
('s_shopping_A1_07','Where is the checkout?','계산대가 어디예요?','Where is the checkout','"checkout"은 대형마트의 계산대, "cash register"는 소규모 매장에서도 쓰여요.','위치 문의','A1','shopping','pattern',NULL,7),

-- ────────────────────────────────────────────────────────────
-- A2 — 사이즈·색상 / 환불 (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_shopping_A2_01','Do you have this in blue?','이거 파란색으로도 있나요?','in blue','색상을 물을 때는 "in + 색깔" 구조를 쓰면 자연스러워요. 예: "in red", "in black".','색상 문의','A2','shopping','pattern',NULL,1),
('s_shopping_A2_02','Can I try this on?','이거 입어봐도 될까요?','Can I try this on','"try on"은 옷·신발을 직접 착용해보는 행위예요. "try out"은 기계·서비스를 시험해볼 때 써요.','착용 요청','A2','shopping','pattern',NULL,2),
('s_shopping_A2_03','Where is the fitting room?','탈의실이 어디예요?','fitting room','"fitting room", "changing room", "dressing room" 모두 같은 의미예요. 나라마다 선호하는 표현이 달라요.','위치 문의','A2','shopping','pattern',NULL,3),
('s_shopping_A2_04','I''d like to return this, please.','이 제품을 반품하고 싶어요.','I''d like to return','"I''d like to ..."는 "I want to ..."보다 더 공손한 표현이에요. 반품·교환 시 꼭 사용하세요.','반품 요청','A2','shopping','pattern',NULL,4),
('s_shopping_A2_05','Can I get a refund?','환불받을 수 있나요?','Can I get a refund','"refund"는 돈을 돌려받는 것, "exchange"는 다른 상품으로 교환하는 것이에요.','환불 요청','A2','shopping','pattern',NULL,5),
('s_shopping_A2_06','Is there a discount for members?','회원 할인이 있나요?','discount for members','포인트 카드나 앱 회원증을 제시하면서 쓰기 좋은 표현이에요.','할인 문의','A2','shopping','pattern',NULL,6),
('s_shopping_A2_07','Do you accept credit cards?','신용카드도 받나요?','Do you accept credit cards','"Do you accept ...?"는 지불 방법을 확인하는 표현이에요. "cash", "contactless" 등으로 바꿔 쓸 수 있어요.','결제 수단 문의','A2','shopping','pattern',NULL,7),

-- ────────────────────────────────────────────────────────────
-- B1 — 흥정 & 할인 요청 (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_shopping_B1_01','Is there any room to negotiate the price?','가격을 좀 조정해 주실 수 있어요?','room to negotiate','"room to negotiate"는 협상 여지가 있는지 부드럽게 묻는 표현이에요. 직접적으로 "Can you lower the price?"보다 자연스러워요.','흥정','B1','shopping','pattern',NULL,1),
('s_shopping_B1_02','Would you be able to give me a discount if I bought two?','두 개 사면 할인해 주실 수 있어요?','give me a discount','수량 할인을 요청할 때 쓰는 표현이에요. "if I bought ..."로 조건부 요청이 가능해요.','수량 할인 요청','B1','shopping','pattern',NULL,2),
('s_shopping_B1_03','I found it cheaper at another store. Can you match the price?','다른 매장에서 더 싸게 봤어요. 가격을 맞춰 주실 수 있어요?','match the price','가격 매칭(price matching)을 요청하는 표현이에요. 대형 소매점에서 특히 효과적이에요.','가격 매칭','B1','shopping','pattern',NULL,3),
('s_shopping_B1_04','I''m a regular customer. Is there any special deal for me?','저 단골 고객이에요. 특별히 해주실 수 있는 게 있나요?','regular customer / special deal','단골임을 강조해 추가 혜택을 요청하는 방법이에요.','특별 혜택 요청','B1','shopping','pattern',NULL,4),
('s_shopping_B1_05','Can I use this coupon with the sale price?','세일가에 이 쿠폰도 같이 쓸 수 있나요?','use this coupon with the sale price','쿠폰과 세일을 중복 적용할 수 있는지 확인하는 표현이에요.','쿠폰 적용 문의','B1','shopping','pattern',NULL,5),
('s_shopping_B1_06','I''d like to pay in installments. Is that possible?','할부로 낼 수 있을까요?','pay in installments','분할 납부를 요청하는 표현이에요. "monthly installments"라고 하면 월별 할부를 뜻해요.','할부 결제 요청','B1','shopping','pattern',NULL,6),
('s_shopping_B1_07','What''s the best price you can do?','제일 낮은 가격이 얼마예요?','the best price you can do','협상할 때 상대방이 제시할 수 있는 최선의 가격을 묻는 표현이에요.','최저가 문의','B1','shopping','pattern',NULL,7),

-- ────────────────────────────────────────────────────────────
-- B2 — 불만 표현 & 비교 쇼핑 (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_shopping_B2_01','I''m not satisfied with the quality of this product. I''d like to speak to a manager.','이 제품의 품질이 만족스럽지 않아요. 매니저와 이야기하고 싶어요.','not satisfied / speak to a manager','불만을 표현하면서도 공손하게 상위 담당자를 요청하는 표현이에요.','불만 제기','B2','shopping','pattern',NULL,1),
('s_shopping_B2_02','This item arrived damaged. What''s your policy on returns?','상품이 파손된 상태로 도착했어요. 반품 정책이 어떻게 되나요?','arrived damaged / returns policy','온라인 구매 후 파손 배송을 신고할 때 쓰는 표현이에요.','파손 상품 신고','B2','shopping','pattern',NULL,2),
('s_shopping_B2_03','I''ve been comparing prices online and found this significantly cheaper elsewhere.','온라인으로 가격을 비교해 봤는데 다른 곳이 훨씬 저렴하더라고요.','comparing prices / significantly cheaper','비교 쇼핑 결과를 근거로 협상하는 고급 표현이에요.','비교 쇼핑 협상','B2','shopping','pattern',NULL,3),
('s_shopping_B2_04','I believe I was overcharged. Could you check the receipt?','제가 바가지를 쓴 것 같아요. 영수증을 확인해 주실 수 있어요?','overcharged / check the receipt','청구 오류를 공손하게 지적하는 표현이에요. "I believe"를 붙이면 단정하지 않아 더 자연스러워요.','청구 오류 지적','B2','shopping','pattern',NULL,4),
('s_shopping_B2_05','I''m torn between these two options. Which one would you recommend?','두 가지 중 어떤 걸 선택해야 할지 모르겠어요. 어떤 걸 추천하세요?','torn between / recommend','"torn between"은 두 가지 사이에서 결정을 못 하는 상황을 표현해요.','구매 추천 요청','B2','shopping','pattern',NULL,5),
('s_shopping_B2_06','Is there an extended warranty available for this product?','이 제품에 연장 보증 서비스가 있나요?','extended warranty','기본 보증 이후 추가 보장을 요청하는 표현이에요. 전자제품 구매 시 유용해요.','연장 보증 문의','B2','shopping','pattern',NULL,6),
('s_shopping_B2_07','I''d like to dispute this charge on my credit card statement.','신용카드 명세서의 이 청구 내역에 이의를 제기하고 싶어요.','dispute this charge','카드 청구 오류나 미승인 결제에 대해 이의를 제기하는 격식 표현이에요.','청구 이의 제기','B2','shopping','pattern',NULL,7),

-- ────────────────────────────────────────────────────────────
-- C1 — 협상 & 비즈니스 구매 (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_shopping_C1_01','We''re looking to establish a long-term procurement relationship and would like to discuss volume pricing.','장기 조달 관계를 구축하고자 하며, 대량 구매 가격에 대해 논의하고 싶습니다.','long-term procurement / volume pricing','B2B 협상에서 장기 거래를 조건으로 단가 인하를 요청하는 고급 비즈니스 표현이에요.','B2B 협상','C1','shopping','pattern',NULL,1),
('s_shopping_C1_02','We need to carry out due diligence on your supply chain before finalising the contract.','계약을 확정하기 전에 귀사의 공급망에 대한 실사를 진행해야 합니다.','due diligence / supply chain','계약 전 공급업체를 검토하는 비즈니스 절차를 표현하는 고급 문장이에요.','계약 전 실사','C1','shopping','pattern',NULL,2),
('s_shopping_C1_03','Could you provide a detailed invoice, including a breakdown of costs?','비용 내역을 포함한 상세 인보이스를 제공해 주실 수 있나요?','detailed invoice / breakdown of costs','비용 구조를 투명하게 요청할 때 쓰는 격식 비즈니스 표현이에요.','인보이스 요청','C1','shopping','pattern',NULL,3),
('s_shopping_C1_04','We''d like to explore whether there''s scope for a bespoke arrangement.','맞춤형 계약 여지가 있는지 검토하고 싶습니다.','bespoke arrangement','"bespoke"는 주로 영국 영어에서 사용하며 "맞춤 제작의"라는 뜻이에요. B2B 협상에서 특별 조건을 협의할 때 씁니다.','맞춤 계약 제안','C1','shopping','pattern',NULL,4),
('s_shopping_C1_05','Our brand''s provenance and artisan heritage justify the premium pricing.','우리 브랜드의 출처와 장인 정신의 역사가 프리미엄 가격을 정당화합니다.','provenance / artisan heritage / premium pricing','프리미엄 가격을 설득력 있게 정당화하는 세일즈 표현이에요.','프리미엄 가격 정당화','C1','shopping','pattern',NULL,5),
('s_shopping_C1_06','We''re concerned about potential grey market activity undermining our exclusive distribution rights.','회색 시장 활동이 저희의 독점 유통권을 약화시킬 것을 우려하고 있어요.','grey market / exclusive distribution rights','독점 유통권 보호를 위한 법적·비즈니스적 표현이에요.','유통 권한 논의','C1','shopping','pattern',NULL,6),
('s_shopping_C1_07','We propose a consignment model to reduce your inventory risk while ensuring product availability.','귀사의 재고 위험을 줄이면서 상품 가용성을 확보하기 위해 위탁 판매 모델을 제안합니다.','consignment model / inventory risk','위탁 판매 계약을 제안하는 비즈니스 협상 표현이에요.','위탁 판매 제안','C1','shopping','pattern',NULL,7),

-- ────────────────────────────────────────────────────────────
-- C2 — 협상 & 비즈니스 구매 (고급) (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_shopping_C2_01','The proposed markup structure fails to account for the asymmetric information between the manufacturer and the end retailer.','제안된 마진 구조는 제조업체와 최종 소매업체 간의 정보 비대칭을 반영하지 못하고 있습니다.','markup structure / asymmetric information','정보 비대칭 이론을 실제 협상에 적용하는 고급 비즈니스 표현이에요.','가격 구조 비판','C2','shopping','pattern',NULL,1),
('s_shopping_C2_02','The cartel-like behaviour among suppliers constitutes a restraint of trade and may attract regulatory scrutiny.','공급업체들의 카르텔과 같은 행동은 거래 제한에 해당하며 규제 당국의 조사를 받을 수 있습니다.','cartel-like behaviour / restraint of trade','공정거래법 위반 가능성을 지적하는 법적·경제적 표현이에요.','공정거래 위반 지적','C2','shopping','pattern',NULL,2),
('s_shopping_C2_03','Commodification of artisan products risks eroding the very brand equity that justifies their premium positioning.','장인 상품의 상품화는 프리미엄 포지셔닝을 정당화하는 브랜드 가치 자체를 훼손할 위험이 있어요.','commodification / brand equity / premium positioning','상품화의 역설적 위험을 설명하는 마케팅 전략 표현이에요.','브랜드 가치 보호 논의','C2','shopping','pattern',NULL,3),
('s_shopping_C2_04','We must factor in both the net present value of the contract and potential depreciation of key assets over the agreement''s lifetime.','계약의 순현재가치와 계약 기간 동안의 핵심 자산 감가상각 가능성 모두를 고려해야 합니다.','net present value / depreciation','재무적 관점에서 계약을 평가하는 고급 비즈니스 표현이에요.','재무 평가 표현','C2','shopping','pattern',NULL,4),
('s_shopping_C2_05','The franchisee''s obligations under the agreement must be clearly delineated to prevent any regulatory arbitrage.','가맹점주의 계약상 의무는 규제 차익거래를 방지하기 위해 명확하게 명시돼야 합니다.','franchisee obligations / regulatory arbitrage','프랜차이즈 계약의 법적 엄밀성을 강조하는 표현이에요.','프랜차이즈 계약 논의','C2','shopping','pattern',NULL,5),
('s_shopping_C2_06','Planned obsolescence strategies, while boosting short-term sales, create negative externalities that increasingly expose brands to reputational and regulatory risk.','계획적 노후화 전략은 단기 매출을 높이는 반면, 브랜드를 평판 및 규제 리스크에 점점 더 노출시키는 부정적 외부 효과를 창출합니다.','planned obsolescence / negative externalities / reputational risk','기업 전략의 장단기 트레이드오프를 분석하는 고급 경영 표현이에요.','기업 전략 비판','C2','shopping','pattern',NULL,6),
('s_shopping_C2_07','As a monopsony buyer, we have significant leverage, but exercising it aggressively risks triggering predatory pricing accusations and antitrust investigations.','수요 독점 구매자로서 우리는 상당한 협상력을 갖지만, 이를 공격적으로 행사하면 약탈적 가격 책정 혐의와 독점금지 조사를 유발할 위험이 있습니다.','monopsony / predatory pricing / antitrust','독점적 구매력의 법적 리스크를 논의하는 최고급 법경제학 표현이에요.','독점금지 리스크 논의','C2','shopping','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;
