-- EngCat — Presentation (발표·프레젠테이션) 단어 + 패턴
-- 210 단어 (A1~C2, 35개 × 6레벨) + 42 패턴 (7개 × 6레벨)
-- 생성일: 2026-05-24

-- ══════════════════════════════════════
-- WORDS — A1 (35개)
-- 핵심 발표 어휘: talk, show, tell, start, end, first, next, last, slide, point + 25개
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_presentation_A1_01','talk','/tɔːk/','verb','말하다','To speak about a subject in a simple and direct way.','I will {talk} about my hobby today.','오늘 제 취미에 대해 말씀드릴게요.','talk','A1','presentation',1,'person talking speaking microphone podium'),
('w_presentation_A1_02','show','/ʃoʊ/','verb','보여 주다','To let someone see something clearly.','Let me {show} you this picture.','이 그림을 보여 드릴게요.','show','A1','presentation',1,'presenter showing screen pointing'),
('w_presentation_A1_03','tell','/tel/','verb','전달하다','To share information with someone by speaking.','I want to {tell} you three things.','세 가지를 말씀드리고 싶어요.','tell','A1','presentation',1,'speaker explaining audience listening'),
('w_presentation_A1_04','start','/stɑːrt/','verb','시작하다','To begin doing something.','Let''s {start} with a short question.','짧은 질문으로 시작해 볼게요.','start','A1','presentation',1,'presentation start opening slide'),
('w_presentation_A1_05','end','/end/','verb','끝내다','To bring something to a finish.','I will {end} with a summary.','요약으로 마무리하겠습니다.','end','A1','presentation',1,'presenter closing slide conclusion'),
('w_presentation_A1_06','first','/fɜːrst/','adverb','먼저, 첫째로','Before anything else in time or order.','{First}, let me introduce myself.','먼저 자기소개를 하겠습니다.','First','A1','presentation',1,'number one first step sequence'),
('w_presentation_A1_07','next','/nekst/','adverb','다음으로','Immediately after the present one.','{Next}, we will look at the data.','다음으로 데이터를 살펴볼게요.','Next','A1','presentation',1,'arrow pointing next step forward'),
('w_presentation_A1_08','last','/læst/','adverb','마지막으로','Coming after all others; final.','{Last}, I will take your questions.','마지막으로 질문을 받겠습니다.','Last','A1','presentation',1,'final step last page checklist'),
('w_presentation_A1_09','slide','/slaɪd/','noun','슬라이드','A single page of a presentation shown on a screen.','Please look at {slide} number two.','슬라이드 2번을 봐 주세요.','slide','A1','presentation',1,'presentation slide screen projector'),
('w_presentation_A1_10','point','/pɔɪnt/','noun','요점','A single idea or fact that you want to express.','My main {point} is very simple.','제 핵심 요점은 아주 간단해요.','point','A1','presentation',1,'whiteboard bullet point key idea'),
('w_presentation_A1_11','say','/seɪ/','verb','말하다','To express something in words.','I want to {say} thank you.','감사하다고 {말하고} 싶어요.','say','A1','presentation',2,'person speaking grateful thank you'),
('w_presentation_A1_12','picture','/ˈpɪktʃər/','noun','그림, 사진','An image that illustrates an idea.','This {picture} shows our goal.','이 그림이 우리의 목표를 보여 줘요.','picture','A1','presentation',2,'illustration diagram visual aid'),
('w_presentation_A1_13','number','/ˈnʌmbər/','noun','숫자','A symbol or word that shows an amount.','The {number} is very big.','그 숫자는 매우 커요.','number','A1','presentation',2,'statistics numbers data chart'),
('w_presentation_A1_14','name','/neɪm/','noun','이름','A word used to identify a person or thing.','My {name} is Kim Jiyeon.','제 이름은 김지연이에요.','name','A1','presentation',2,'name tag speaker badge introduction'),
('w_presentation_A1_15','page','/peɪdʒ/','noun','페이지, 화면','A single side of a document or screen.','Please go to {page} five.','5페이지로 가 주세요.','page','A1','presentation',2,'document page number slide deck'),
('w_presentation_A1_16','look','/lʊk/','verb','보다','To direct your eyes at something.','Please {look} at this chart.','이 차트를 봐 주세요.','look','A1','presentation',2,'audience looking at screen attentive'),
('w_presentation_A1_17','good','/ɡʊd/','adjective','좋은','Of a high quality or standard.','That is a {good} question.','좋은 질문이에요.','good','A1','presentation',2,'thumbs up positive feedback smile'),
('w_presentation_A1_18','big','/bɪɡ/','adjective','중요한, 큰','Of large size or great importance.','This is a {big} idea.','이것은 중요한 아이디어예요.','big','A1','presentation',2,'large important idea concept'),
('w_presentation_A1_19','new','/njuː/','adjective','새로운','Not existing before; recently made or discovered.','This is a {new} product.','이것은 새로운 제품이에요.','new','A1','presentation',2,'new product launch announcement'),
('w_presentation_A1_20','help','/help/','verb','돕다','To make it easier for someone to do something.','This will {help} your team.','이것이 여러분 팀에 도움이 될 거예요.','help','A1','presentation',2,'teamwork helping hands collaboration'),
('w_presentation_A1_21','problem','/ˈprɒbləm/','noun','문제','A matter that is difficult to deal with.','We have one {problem} to solve.','해결해야 할 문제가 하나 있어요.','problem','A1','presentation',2,'problem solving whiteboard challenge'),
('w_presentation_A1_22','idea','/aɪˈdɪə/','noun','아이디어','A thought or plan formed in the mind.','I have a great {idea}.','좋은 아이디어가 있어요.','idea','A1','presentation',2,'lightbulb idea brainstorm creative'),
('w_presentation_A1_23','today','/təˈdeɪ/','adverb','오늘','On the present day.','{Today} I will talk about our plan.','오늘 우리의 계획에 대해 말씀드릴게요.','Today','A1','presentation',3,'calendar today date presentation day'),
('w_presentation_A1_24','question','/ˈkwestʃən/','noun','질문','A sentence that asks for information.','Do you have a {question}?','질문 있으세요?','question','A1','presentation',1,'raised hand question audience'),
('w_presentation_A1_25','answer','/ˈænsər/','verb','대답하다','To respond to a question.','I will {answer} now.','지금 답변드릴게요.','answer','A1','presentation',1,'speaker answering Q&A session'),
('w_presentation_A1_26','ready','/ˈredi/','adjective','준비된','Fully prepared for something.','Are you {ready} to begin?','시작할 준비가 됐나요?','ready','A1','presentation',3,'checklist prepared ready to start'),
('w_presentation_A1_27','done','/dʌn/','adjective','완료된','Having finished something.','We are {done} with this part.','이 부분은 완료했어요.','done','A1','presentation',3,'checkmark done complete task'),
('w_presentation_A1_28','clear','/klɪər/','adjective','명확한','Easy to understand; not confusing.','Is that {clear} to everyone?','모두에게 명확한가요?','clear','A1','presentation',2,'clear message simple explanation'),
('w_presentation_A1_29','main','/meɪn/','adjective','주요한','Most important; principal.','The {main} topic is growth.','주요 주제는 성장이에요.','main','A1','presentation',2,'headline main point spotlight'),
('w_presentation_A1_30','plan','/plæn/','noun','계획','An intention or decision about what to do.','Here is our {plan}.','여기 우리 계획이 있어요.','plan','A1','presentation',2,'planning chart roadmap strategy'),
('w_presentation_A1_31','step','/step/','noun','단계','A stage in a process.','The first {step} is easy.','첫 번째 단계는 쉬워요.','step','A1','presentation',2,'steps process diagram stages'),
('w_presentation_A1_32','part','/pɑːrt/','noun','부분','A section or portion of something.','The next {part} is very important.','다음 부분이 매우 중요해요.','part','A1','presentation',3,'section chapter segment portion'),
('w_presentation_A1_33','way','/weɪ/','noun','방법','A method or manner of doing something.','There is a better {way}.','더 좋은 방법이 있어요.','way','A1','presentation',3,'pathway method solution approach'),
('w_presentation_A1_34','goal','/ɡoʊl/','noun','목표','An aim or desired result.','Our {goal} is to grow.','우리의 목표는 성장이에요.','goal','A1','presentation',1,'target goal achievement success'),
('w_presentation_A1_35','team','/tiːm/','noun','팀','A group of people working together.','Our {team} worked very hard.','우리 팀이 매우 열심히 했어요.','team','A1','presentation',2,'team meeting collaboration office');

-- ══════════════════════════════════════
-- WORDS — A2 (35개)
-- 핵심 발표 어휘: introduce, outline, summary, topic, explain, question, answer, audience, present, conclusion + 25개
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_presentation_A2_01','introduce','/ˌɪntrəˈdjuːs/','verb','소개하다','To present a person or topic for the first time.','Let me {introduce} our project.','저희 프로젝트를 소개해 드릴게요.','introduce','A2','presentation',1,'introduction handshake speaker stage'),
('w_presentation_A2_02','outline','/ˈaʊtlaɪn/','noun','개요','A summary of the main points of a presentation.','Here is the {outline} for today.','오늘의 개요입니다.','outline','A2','presentation',1,'outline agenda overview bullet points'),
('w_presentation_A2_03','summary','/ˈsʌməri/','noun','요약','A brief statement of the main points.','Let me give a quick {summary}.','간단한 요약을 드릴게요.','summary','A2','presentation',1,'summary key points conclusion slide'),
('w_presentation_A2_04','topic','/ˈtɒpɪk/','noun','주제','The subject of a conversation or piece of writing.','Today''s {topic} is renewable energy.','오늘 주제는 재생에너지예요.','topic','A2','presentation',1,'topic subject heading slide title'),
('w_presentation_A2_05','explain','/ɪkˈspleɪn/','verb','설명하다','To make something clear or easy to understand.','Let me {explain} this step.','이 단계를 설명해 드릴게요.','explain','A2','presentation',1,'whiteboard explaining diagram teacher'),
('w_presentation_A2_06','audience','/ˈɔːdiəns/','noun','청중','The people who watch or listen to a presentation.','The {audience} asked many questions.','청중이 많은 질문을 했어요.','audience','A2','presentation',1,'audience seats watching attentive'),
('w_presentation_A2_07','present','/ˈprezənt/','verb','발표하다','To show or describe something to a group.','I will {present} our results.','저희 결과를 발표할게요.','present','A2','presentation',1,'presenter podium stage microphone'),
('w_presentation_A2_08','conclusion','/kənˈkluːʒən/','noun','결론','The final part of something where you reach a decision.','In {conclusion}, we recommend this.','결론적으로 이것을 권장해요.','conclusion','A2','presentation',1,'conclusion final slide summary end'),
('w_presentation_A2_09','section','/ˈsekʃən/','noun','섹션, 항목','A distinct part of something.','Move on to the next {section}.','다음 섹션으로 넘어갈게요.','section','A2','presentation',2,'document section chapter divider'),
('w_presentation_A2_10','title','/ˈtaɪtəl/','noun','제목','The name given to a presentation or document.','The {title} of my talk is "Innovation".','제 발표 제목은 "혁신"이에요.','title','A2','presentation',2,'title slide heading presentation cover'),
('w_presentation_A2_11','prepare','/prɪˈpeər/','verb','준비하다','To make something ready in advance.','I {prepared} this presentation carefully.','이 발표를 꼼꼼하게 준비했어요.','prepared','A2','presentation',2,'preparation notes rehearsal planning'),
('w_presentation_A2_12','example','/ɪɡˈzɑːmpəl/','noun','예시','A thing that illustrates a general rule.','Here is an {example} of this method.','이 방법의 예시입니다.','example','A2','presentation',1,'example case study illustration'),
('w_presentation_A2_13','graph','/ɡrɑːf/','noun','그래프','A diagram showing the relationship between data.','Look at this {graph}.','이 그래프를 보세요.','graph','A2','presentation',2,'bar graph chart data visualization'),
('w_presentation_A2_14','result','/rɪˈzʌlt/','noun','결과','The outcome of an action or process.','The {result} was very positive.','결과는 매우 긍정적이었어요.','result','A2','presentation',1,'results data outcome success metrics'),
('w_presentation_A2_15','important','/ɪmˈpɔːrtənt/','adjective','중요한','Of great significance or value.','This is the most {important} point.','이것이 가장 중요한 요점이에요.','important','A2','presentation',2,'important highlight star key point'),
('w_presentation_A2_16','agree','/əˈɡriː/','verb','동의하다','To have the same opinion as someone else.','Do you {agree} with this idea?','이 아이디어에 동의하세요?','agree','A2','presentation',2,'agreement nodding consensus team'),
('w_presentation_A2_17','suggest','/səˈdʒest/','verb','제안하다','To put forward an idea or plan for consideration.','I {suggest} we start with this.','이것부터 시작하길 제안해요.','suggest','A2','presentation',2,'suggestion proposal idea lightbulb'),
('w_presentation_A2_18','compare','/kəmˈpeər/','verb','비교하다','To examine similarities and differences.','Let''s {compare} the two options.','두 가지 옵션을 비교해 볼게요.','compare','A2','presentation',2,'comparison side by side analysis'),
('w_presentation_A2_19','increase','/ɪnˈkriːs/','verb','증가하다','To become larger in amount or number.','Sales {increased} by twenty percent.','매출이 20% 증가했어요.','increased','A2','presentation',2,'growth increase upward trend chart'),
('w_presentation_A2_20','decrease','/dɪˈkriːs/','verb','감소하다','To become smaller in amount or number.','Costs {decreased} this year.','올해 비용이 감소했어요.','decreased','A2','presentation',2,'decrease downward trend reduction'),
('w_presentation_A2_21','clearly','/ˈklɪərli/','adverb','명확하게','In a way that is easy to see or understand.','I can {clearly} see the difference.','차이를 명확하게 볼 수 있어요.','clearly','A2','presentation',2,'clear diagram simple explanation visual'),
('w_presentation_A2_22','brief','/briːf/','adjective','간략한','Short in time or duration; not detailed.','I''ll give a {brief} overview.','간략한 개요를 드릴게요.','brief','A2','presentation',2,'short summary brief notes bullet'),
('w_presentation_A2_23','data','/ˈdeɪtə/','noun','데이터','Facts and statistics collected for analysis.','This {data} shows a clear trend.','이 데이터는 명확한 추세를 보여 줘요.','data','A2','presentation',1,'data chart statistics analysis'),
('w_presentation_A2_24','chart','/tʃɑːrt/','noun','차트','A visual representation of data.','Look at this {chart}.','이 차트를 보세요.','chart','A2','presentation',2,'bar chart pie chart data visual'),
('w_presentation_A2_25','survey','/ˈsɜːrveɪ/','noun','설문 조사','A study of opinions conducted by asking questions.','According to our {survey}, customers prefer this.','설문 조사에 따르면 고객들은 이것을 선호해요.','survey','A2','presentation',2,'survey questionnaire poll results'),
('w_presentation_A2_26','feedback','/ˈfiːdbæk/','noun','피드백','Comments about performance used to improve it.','The {feedback} from users was helpful.','사용자들의 피드백이 도움이 됐어요.','feedback','A2','presentation',2,'feedback review comments rating'),
('w_presentation_A2_27','project','/ˈprɒdʒekt/','noun','프로젝트','A planned piece of work done over a period of time.','This {project} took six months.','이 프로젝트는 6개월이 걸렸어요.','project','A2','presentation',2,'project plan timeline roadmap'),
('w_presentation_A2_28','background','/ˈbækɡraʊnd/','noun','배경 정보','The situation or events leading to a topic.','Let me give some {background}.','배경 정보를 드릴게요.','background','A2','presentation',2,'background context history information'),
('w_presentation_A2_29','simple','/ˈsɪmpəl/','adjective','간단한','Easy to understand or do; not complex.','Let''s keep this {simple}.','간단하게 유지해요.','simple','A2','presentation',3,'simple clear minimalist diagram'),
('w_presentation_A2_30','message','/ˈmesɪdʒ/','noun','메시지, 요점','The central idea or moral of a presentation.','The {message} is clear.','메시지가 명확해요.','message','A2','presentation',2,'key message speech bubble core idea'),
('w_presentation_A2_31','purpose','/ˈpɜːrpəs/','noun','목적','The reason for doing or making something.','The {purpose} of this talk is to inform.','이 발표의 목적은 정보를 전달하는 것이에요.','purpose','A2','presentation',2,'purpose goal objective target'),
('w_presentation_A2_32','benefit','/ˈbenɪfɪt/','noun','이점, 혜택','An advantage or profit gained from something.','There are three main {benefits}.','세 가지 주요 이점이 있어요.','benefits','A2','presentation',2,'benefits advantages pros checklist'),
('w_presentation_A2_33','fact','/fækt/','noun','사실, 근거','A thing that is known to be true.','Here is an interesting {fact}.','흥미로운 사실이 있어요.','fact','A2','presentation',2,'fact statistics evidence data'),
('w_presentation_A2_34','structure','/ˈstrʌktʃər/','noun','구조','The way in which the parts of something are arranged.','The {structure} of my talk is as follows.','제 발표의 구조는 다음과 같아요.','structure','A2','presentation',2,'outline structure flow diagram'),
('w_presentation_A2_35','review','/rɪˈvjuː/','verb','검토하다','To examine or assess something carefully.','Let''s {review} the main points.','주요 포인트를 검토해 볼게요.','review','A2','presentation',3,'review checklist evaluation assessment');

-- ══════════════════════════════════════
-- WORDS — B1 (35개)
-- 핵심 발표 어휘: highlight, transition, illustrate, emphasize, elaborate, overview, objective, finding, result, recommend + 25개
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_presentation_B1_01','highlight','/ˈhaɪlaɪt/','verb','강조하다, 부각하다','To draw attention to the most important part of something.','I want to {highlight} this key figure.','이 핵심 수치를 강조하고 싶어요.','highlight','B1','presentation',1,'highlight marker emphasis key point'),
('w_presentation_B1_02','transition','/trænˈzɪʃən/','noun','전환, 넘어가기','A change from one subject to another in a presentation.','This is a good {transition} to the next topic.','다음 주제로 넘어가기 좋은 전환이에요.','transition','B1','presentation',1,'transition bridge connection flow'),
('w_presentation_B1_03','illustrate','/ˈɪləstreɪt/','verb','설명하다, 보여 주다','To explain or make clear by using examples or visuals.','This graph {illustrates} the trend perfectly.','이 그래프가 추세를 잘 보여 줘요.','illustrates','B1','presentation',1,'illustration diagram visual example'),
('w_presentation_B1_04','emphasize','/ˈemfəsaɪz/','verb','강조하다','To give special importance to a point.','I want to {emphasize} this finding.','이 발견을 강조하고 싶어요.','emphasize','B1','presentation',1,'emphasis bold underline highlight'),
('w_presentation_B1_05','elaborate','/ɪˈlæbəreɪt/','verb','자세히 설명하다','To explain something in more detail.','Could you {elaborate} on that point?','그 요점을 더 자세히 설명해 주실 수 있나요?','elaborate','B1','presentation',2,'detailed explanation depth analysis'),
('w_presentation_B1_06','overview','/ˈoʊvərvjuː/','noun','개요','A general summary or survey of something.','Let me give you a brief {overview}.','간략한 개요를 드릴게요.','overview','B1','presentation',1,'overview map birds eye view summary'),
('w_presentation_B1_07','objective','/əbˈdʒektɪv/','noun','목표, 목적','A goal that you are trying to achieve.','Our main {objective} is to increase sales.','저희의 주요 목표는 매출 증가예요.','objective','B1','presentation',1,'objective target aim goal bullseye'),
('w_presentation_B1_08','finding','/ˈfaɪndɪŋ/','noun','발견, 조사 결과','A piece of information discovered through research.','Our key {finding} is that costs are rising.','핵심 발견은 비용이 상승하고 있다는 거예요.','finding','B1','presentation',1,'research finding discovery data insight'),
('w_presentation_B1_09','recommend','/ˌrekəˈmend/','verb','권고하다, 추천하다','To suggest something as being good or suitable based on evidence.','We {recommend} adopting this new strategy.','이 새로운 전략 채택을 권고해요.','recommend','B1','presentation',1,'recommendation suggestion proposal'),
('w_presentation_B1_10','expand','/ɪkˈspænd/','verb','확장하다, 자세히 설명하다','To make larger or to discuss in greater detail.','Let me {expand} on this idea.','이 아이디어를 더 자세히 설명할게요.','expand','B1','presentation',2,'expanding growth detail depth'),
('w_presentation_B1_11','approach','/əˈproʊtʃ/','noun','접근 방식','A way of dealing with a situation or problem.','Our {approach} is user-centred.','저희 접근 방식은 사용자 중심이에요.','approach','B1','presentation',2,'approach method strategy process'),
('w_presentation_B1_12','evidence','/ˈevɪdəns/','noun','근거, 증거','Information that supports a claim or conclusion.','The {evidence} supports our theory.','증거가 저희 이론을 뒷받침해요.','evidence','B1','presentation',1,'evidence proof data research support'),
('w_presentation_B1_13','demonstrate','/ˈdemənstreɪt/','verb','보여 주다, 입증하다','To show clearly by using examples or experiments.','These results {demonstrate} the effectiveness.','이 결과들이 효과를 입증해요.','demonstrate','B1','presentation',1,'demonstration proof evidence show'),
('w_presentation_B1_14','indicate','/ˈɪndɪkeɪt/','verb','나타내다','To show or suggest something.','The data {indicates} a positive change.','데이터가 긍정적인 변화를 나타내요.','indicates','B1','presentation',2,'indicator arrow data point'),
('w_presentation_B1_15','clarify','/ˈklærɪfaɪ/','verb','명확히 하다','To make something less confusing and more understandable.','Let me {clarify} what I mean.','제 말을 명확히 하겠습니다.','clarify','B1','presentation',2,'clarification explanation clear simple'),
('w_presentation_B1_16','summarize','/ˈsʌməraɪz/','verb','요약하다','To give a brief description of the main points.','Let me {summarize} the key takeaways.','핵심 요약을 드릴게요.','summarize','B1','presentation',1,'summary bullet points key takeaway'),
('w_presentation_B1_17','challenge','/ˈtʃælɪndʒ/','noun','도전, 어려움','A task or situation that tests skills and determination.','One {challenge} we faced was cost.','저희가 직면한 어려움 중 하나는 비용이었어요.','challenge','B1','presentation',2,'obstacle challenge problem solving'),
('w_presentation_B1_18','solution','/səˈluːʃən/','noun','해결책','A way of solving a problem.','Here is our proposed {solution}.','저희가 제안하는 해결책입니다.','solution','B1','presentation',1,'solution answer problem solved lightbulb'),
('w_presentation_B1_19','trend','/trend/','noun','추세, 경향','A general direction in which something is changing.','This {trend} will continue into next year.','이 추세는 내년에도 계속될 거예요.','trend','B1','presentation',2,'trend upward graph line arrow'),
('w_presentation_B1_20','impact','/ˈɪmpækt/','noun','영향, 효과','The effect or influence of something.','The {impact} on revenue was significant.','수익에 대한 영향은 상당했어요.','impact','B1','presentation',2,'impact effect change result'),
('w_presentation_B1_21','strategy','/ˈstrætədʒi/','noun','전략','A plan of action designed to achieve a goal.','Our {strategy} focuses on customer retention.','저희 전략은 고객 유지에 초점을 맞춰요.','strategy','B1','presentation',2,'strategy plan chess pieces roadmap'),
('w_presentation_B1_22','significant','/sɪɡˈnɪfɪkənt/','adjective','중요한, 의미 있는','Large enough to be noticed or have an effect.','There was a {significant} increase in revenue.','수익에 상당한 증가가 있었어요.','significant','B1','presentation',2,'significant important major bold'),
('w_presentation_B1_23','proposal','/prəˈpoʊzəl/','noun','제안서','A plan or suggestion put forward for consideration.','Our {proposal} offers a clear path forward.','저희 제안서는 명확한 방향을 제시해요.','proposal','B1','presentation',2,'proposal document business plan'),
('w_presentation_B1_24','contribution','/ˌkɒntrɪˈbjuːʃən/','noun','기여, 공헌','Something that helps or adds to something else.','Each team member''s {contribution} was vital.','각 팀원의 기여가 매우 중요했어요.','contribution','B1','presentation',3,'contribution teamwork value add'),
('w_presentation_B1_25','support','/səˈpɔːrt/','verb','뒷받침하다','To provide evidence for a claim or theory.','This data {supports} our hypothesis.','이 데이터가 저희 가설을 뒷받침해요.','supports','B1','presentation',2,'support evidence data pillar'),
('w_presentation_B1_26','assumption','/əˈsʌmpʃən/','noun','가정, 전제','Something accepted as true without proof.','Our first {assumption} was incorrect.','저희의 첫 번째 가정이 틀렸어요.','assumption','B1','presentation',3,'assumption premise hypothesis base'),
('w_presentation_B1_27','outcome','/ˈaʊtkʌm/','noun','결과, 성과','The result or consequence of an action.','The {outcome} exceeded our expectations.','결과가 저희 기대를 넘어섰어요.','outcome','B1','presentation',2,'outcome result achievement success'),
('w_presentation_B1_28','resource','/ˈriːsɔːrs/','noun','자원, 리소스','A stock or supply of money, materials, or people.','We need more {resources} for this project.','이 프로젝트에 더 많은 자원이 필요해요.','resources','B1','presentation',3,'resources team budget tools'),
('w_presentation_B1_29','implementation','/ˌɪmplɪmenˈteɪʃən/','noun','실행, 구현','The process of putting a plan into action.','The {implementation} will begin in Q3.','실행은 3분기에 시작될 거예요.','implementation','B1','presentation',2,'implementation process launch rollout'),
('w_presentation_B1_30','phase','/feɪz/','noun','단계, 페이즈','A distinct period in a process or development.','In the second {phase}, we will test the product.','두 번째 단계에서 제품을 테스트할 거예요.','phase','B1','presentation',2,'phase stage timeline step process'),
('w_presentation_B1_31','timeline','/ˈtaɪmlaɪn/','noun','타임라인, 일정표','A graphical representation of dates and events.','Here is our project {timeline}.','저희 프로젝트 타임라인이에요.','timeline','B1','presentation',2,'timeline schedule gantt chart project'),
('w_presentation_B1_32','stakeholder','/ˈsteɪkhoʊldər/','noun','이해관계자','A person with an interest in a project or organisation.','We need to inform all {stakeholders}.','모든 이해관계자에게 알려야 해요.','stakeholders','B1','presentation',2,'stakeholders team board meeting'),
('w_presentation_B1_33','benchmark','/ˈbentʃmɑːrk/','noun','기준, 벤치마크','A standard against which something is measured.','We used industry {benchmarks} to compare.','비교를 위해 업계 벤치마크를 사용했어요.','benchmarks','B1','presentation',3,'benchmark comparison standard measure'),
('w_presentation_B1_34','forecast','/ˈfɔːrkæst/','noun','예측, 예보','A prediction about future events.','Our sales {forecast} looks optimistic.','저희 매출 예측은 낙관적이에요.','forecast','B1','presentation',2,'forecast prediction future chart'),
('w_presentation_B1_35','insight','/ˈɪnsaɪt/','noun','통찰, 인사이트','A deep understanding of a complex situation.','This gave us a valuable {insight}.','이것이 우리에게 귀중한 통찰을 주었어요.','insight','B1','presentation',2,'insight discovery lightbulb idea');

-- ══════════════════════════════════════
-- WORDS — B2 (35개)
-- 핵심 발표 어휘: quantify, juxtapose, contextualize, articulate, facilitate, compelling, persuasive, coherent, credibility, narrative + 25개
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_presentation_B2_01','quantify','/ˈkwɒntɪfaɪ/','verb','수치화하다','To express or measure the quantity of something.','We need to {quantify} the risk more precisely.','위험을 더 정밀하게 수치화해야 해요.','quantify','B2','presentation',1,'quantify measure numbers data metrics'),
('w_presentation_B2_02','juxtapose','/ˌdʒʌkstəˈpoʊz/','verb','나란히 놓다, 대비하다','To place two things together to highlight contrast or similarity.','The speaker {juxtaposed} old data with new.','발표자가 오래된 데이터와 새로운 데이터를 대비시켰어요.','juxtaposed','B2','presentation',2,'comparison contrast side by side before after'),
('w_presentation_B2_03','contextualize','/kənˈtekstʃuəlaɪz/','verb','맥락화하다','To place something in its context to make it easier to understand.','Let me {contextualize} these figures.','이 수치들을 맥락 안에서 설명해 드릴게요.','contextualize','B2','presentation',2,'context background situate frame'),
('w_presentation_B2_04','articulate','/ɑːrˈtɪkjəleɪt/','verb','명료하게 표현하다','To express an idea clearly and effectively.','She {articulated} the plan with great clarity.','그녀는 계획을 아주 명료하게 표현했어요.','articulated','B2','presentation',1,'clear speech articulate confident speaker'),
('w_presentation_B2_05','facilitate','/fəˈsɪlɪteɪt/','verb','촉진하다, 원활하게 하다','To make a process easier or help it to happen.','Good visuals {facilitate} understanding.','좋은 시각 자료는 이해를 촉진해요.','facilitate','B2','presentation',2,'facilitate smooth process enabler'),
('w_presentation_B2_06','compelling','/kəmˈpelɪŋ/','adjective','설득력 있는, 강렬한','Very interesting or persuasive; hard to resist or ignore.','She gave a {compelling} argument for change.','그녀는 변화에 대한 설득력 있는 주장을 펼쳤어요.','compelling','B2','presentation',1,'compelling powerful persuasive speaker'),
('w_presentation_B2_07','persuasive','/pərˈsweɪsɪv/','adjective','설득력 있는','Good at convincing people to do or believe something.','His presentation was extremely {persuasive}.','그의 발표는 매우 설득력이 있었어요.','persuasive','B2','presentation',1,'persuade convince audience nod agree'),
('w_presentation_B2_08','coherent','/koʊˈhɪərənt/','adjective','일관성 있는, 논리적인','Forming a unified whole; logical and consistent.','Your argument must be {coherent} throughout.','주장은 처음부터 끝까지 일관성이 있어야 해요.','coherent','B2','presentation',1,'logical coherent flow structure order'),
('w_presentation_B2_09','credibility','/ˌkredɪˈbɪlɪti/','noun','신뢰성, 공신력','The quality of being trusted and believed.','Use data to strengthen your {credibility}.','데이터를 사용해 신뢰성을 강화하세요.','credibility','B2','presentation',1,'credibility trust authority expertise'),
('w_presentation_B2_10','narrative','/ˈnærətɪv/','noun','서사, 스토리라인','A story or account used to structure a presentation.','Build a strong {narrative} around your data.','데이터를 중심으로 강한 서사를 구성하세요.','narrative','B2','presentation',1,'story narrative arc presentation flow'),
('w_presentation_B2_11','implication','/ˌɪmplɪˈkeɪʃən/','noun','함의, 시사점','A possible consequence or conclusion from evidence.','The {implications} are significant.','시사점이 상당해요.','implications','B2','presentation',2,'implication consequence meaning insight'),
('w_presentation_B2_12','validate','/ˈvælɪdeɪt/','verb','검증하다, 입증하다','To confirm the accuracy or truth of something.','We need to {validate} these assumptions.','이 가정들을 검증해야 해요.','validate','B2','presentation',2,'validate verify confirm test check'),
('w_presentation_B2_13','leverage','/ˈlevərɪdʒ/','verb','활용하다','To use something to maximum advantage.','We can {leverage} this data to our benefit.','이 데이터를 우리에게 유리하게 활용할 수 있어요.','leverage','B2','presentation',2,'leverage use maximize advantage'),
('w_presentation_B2_14','refine','/rɪˈfaɪn/','verb','다듬다, 정제하다','To improve something by making small changes.','We {refined} the message after user testing.','사용자 테스트 후 메시지를 다듬었어요.','refined','B2','presentation',2,'refine improve polish quality'),
('w_presentation_B2_15','scope','/skoʊp/','noun','범위, 영역','The range of topics or areas covered.','The {scope} of this study is limited to Korea.','이 연구의 범위는 한국으로 제한돼요.','scope','B2','presentation',2,'scope boundary range limit project'),
('w_presentation_B2_16','assumption','/əˈsʌmpʃən/','noun','전제, 가정','A belief taken for granted when drawing a conclusion.','We must challenge our core {assumptions}.','핵심 가정들에 의문을 가져야 해요.','assumptions','B2','presentation',2,'assumption premise hypothesis challenge'),
('w_presentation_B2_17','substantiate','/səbˈstænʃieɪt/','verb','뒷받침하다, 입증하다','To provide evidence to prove the truth of something.','Can you {substantiate} this claim?','이 주장을 뒷받침할 수 있나요?','substantiate','B2','presentation',2,'substantiate evidence prove support'),
('w_presentation_B2_18','nuance','/ˈnjuːɑːns/','noun','뉘앙스, 미묘한 차이','A very slight difference in meaning or expression.','The {nuance} of this term is important.','이 용어의 뉘앙스가 중요해요.','nuance','B2','presentation',2,'nuance subtle difference meaning language'),
('w_presentation_B2_19','diverge','/daɪˈvɜːrdʒ/','verb','갈리다, 분기하다','To separate and go in different directions.','The two trends {diverge} after 2020.','두 추세는 2020년 이후 갈려요.','diverge','B2','presentation',3,'diverge split different path fork'),
('w_presentation_B2_20','converge','/kənˈvɜːrdʒ/','verb','수렴하다, 일치하다','To come together toward a common point.','Both approaches {converge} on the same solution.','두 접근 방식이 같은 해결책으로 수렴해요.','converge','B2','presentation',3,'converge merge combine unite'),
('w_presentation_B2_21','underpin','/ˌʌndərˈpɪn/','verb','뒷받침하다, 기반이 되다','To support or form the basis of something.','Evidence {underpins} every claim we make.','증거가 저희의 모든 주장을 뒷받침해요.','underpins','B2','presentation',2,'foundation support base pillar'),
('w_presentation_B2_22','caveat','/ˈkæviæt/','noun','주의 사항, 경고','A warning that something may not be fully accurate.','There is one important {caveat} to note.','한 가지 중요한 주의 사항이 있어요.','caveat','B2','presentation',3,'warning caveat disclaimer note'),
('w_presentation_B2_23','projection','/prəˈdʒekʃən/','noun','예측치, 추정','An estimate of what will happen in the future based on data.','Our five-year {projection} shows steady growth.','5년 예측치는 꾸준한 성장을 보여요.','projection','B2','presentation',2,'forecast projection future trend graph'),
('w_presentation_B2_24','alignment','/əˈlaɪnmənt/','noun','정렬, 일치','A state of agreement or coordination between things.','There is strong {alignment} across teams.','팀 전체에 강한 일치가 있어요.','alignment','B2','presentation',2,'alignment agreement coordination sync'),
('w_presentation_B2_25','actionable','/ˈækʃənəbəl/','adjective','실행 가능한','Able to be acted upon; practical and useful.','These insights are immediately {actionable}.','이 통찰들은 즉시 실행 가능해요.','actionable','B2','presentation',2,'actionable practical next steps tasks'),
('w_presentation_B2_26','benchmark','/ˈbentʃmɑːrk/','verb','기준을 삼아 비교하다','To measure performance against an established standard.','We {benchmarked} our results against competitors.','경쟁사와 결과를 비교했어요.','benchmarked','B2','presentation',3,'benchmark compare standard performance'),
('w_presentation_B2_27','rhetoric','/ˈretərɪk/','noun','수사법, 설득 기술','The art of effective persuasive speaking.','Strong {rhetoric} can sway an audience.','강한 수사법은 청중을 움직일 수 있어요.','rhetoric','B2','presentation',2,'rhetoric speech persuasion eloquence'),
('w_presentation_B2_28','concise','/kənˈsaɪs/','adjective','간결한','Giving a lot of information clearly with few words.','Your delivery should be {concise} and direct.','전달은 간결하고 직접적이어야 해요.','concise','B2','presentation',2,'concise brief clear sharp words'),
('w_presentation_B2_29','holistic','/hoʊˈlɪstɪk/','adjective','전체적인, 통합적인','Taking everything into account; considering the whole picture.','We need a {holistic} view of the situation.','상황에 대한 전체적인 시각이 필요해요.','holistic','B2','presentation',3,'holistic whole picture overview system'),
('w_presentation_B2_30','mandate','/ˈmændeɪt/','noun','위임, 권한','Official permission or authority to carry out a policy.','Our {mandate} is to reduce costs by 20%.','저희 위임 사항은 비용을 20% 줄이는 거예요.','mandate','B2','presentation',3,'mandate authority directive goal mission'),
('w_presentation_B2_31','transparent','/trænsˈpærənt/','adjective','투명한, 솔직한','Open and honest; easy to understand.','We must be {transparent} about our limitations.','저희 한계에 대해 투명하게 밝혀야 해요.','transparent','B2','presentation',2,'transparency honesty open clear glass'),
('w_presentation_B2_32','scalable','/ˈskeɪləbəl/','adjective','확장 가능한','Capable of being expanded to handle increased demand.','The solution must be {scalable}.','솔루션은 확장 가능해야 해요.','scalable','B2','presentation',3,'scalable growth expand flexible'),
('w_presentation_B2_33','prioritize','/praɪˈɔːrɪtaɪz/','verb','우선순위를 정하다','To treat something as more important than other things.','We need to {prioritize} these initiatives.','이 이니셔티브들의 우선순위를 정해야 해요.','prioritize','B2','presentation',2,'priority ranking order important first'),
('w_presentation_B2_34','mitigate','/ˈmɪtɪɡeɪt/','verb','완화하다, 경감하다','To make something less severe or harmful.','We have steps to {mitigate} the risks.','위험을 완화할 조치가 있어요.','mitigate','B2','presentation',2,'risk mitigation reduce danger safety'),
('w_presentation_B2_35','catalyst','/ˈkætəlɪst/','noun','촉매, 계기','Something that causes or speeds up change.','This event was a {catalyst} for innovation.','이 사건이 혁신의 촉매가 됐어요.','catalyst','B2','presentation',2,'catalyst spark innovation change driver');

-- ══════════════════════════════════════
-- WORDS — C1 (35개)
-- 핵심 발표 어휘: rhetoric, discourse, deconstruct, paradigm, framework, stakeholder, proposition, empirical, analytical, synthesize + 25개
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_presentation_C1_01','rhetoric','/ˈretərɪk/','noun','수사학, 웅변술','The art of effective or persuasive speaking and writing.','His mastery of {rhetoric} captivated the audience.','그의 수사학 능력이 청중을 사로잡았어요.','rhetoric','C1','presentation',1,'rhetoric speech philosophy ancient podium'),
('w_presentation_C1_02','discourse','/ˈdɪskɔːrs/','noun','담론, 담화','A written or spoken communication on a subject, often academic.','The {discourse} on sustainability has shifted.','지속가능성에 대한 담론이 변화했어요.','discourse','C1','presentation',1,'discourse conversation academic debate'),
('w_presentation_C1_03','deconstruct','/ˌdiːkənˈstrʌkt/','verb','해체하다, 분석하다','To analyze by breaking something down into its components.','Let us {deconstruct} this argument.','이 주장을 분해해 분석해 볼게요.','deconstruct','C1','presentation',2,'deconstruct analyze break down components'),
('w_presentation_C1_04','paradigm','/ˈpærədaɪm/','noun','패러다임, 기준 틀','A typical example or model of how something works.','This represents a {paradigm} shift in thinking.','이것은 사고의 패러다임 전환을 나타내요.','paradigm','C1','presentation',1,'paradigm shift model framework thinking'),
('w_presentation_C1_05','framework','/ˈfreɪmwɜːrk/','noun','프레임워크, 틀','A basic structure that underlies a system or concept.','Our analytical {framework} has three pillars.','저희 분석 프레임워크는 세 가지 축이 있어요.','framework','C1','presentation',1,'framework structure pillars model system'),
('w_presentation_C1_06','proposition','/ˌprɒpəˈzɪʃən/','noun','명제, 제안','A statement or assertion to be discussed and proved.','Our central {proposition} is that change is inevitable.','저희 핵심 명제는 변화는 불가피하다는 거예요.','proposition','C1','presentation',1,'proposition statement claim thesis'),
('w_presentation_C1_07','empirical','/ɪmˈpɪrɪkəl/','adjective','경험적인, 실증적인','Based on observation or experience rather than theory.','We base our claims on {empirical} evidence.','저희 주장은 실증적 근거에 기반해요.','empirical','C1','presentation',1,'empirical research data evidence experiment'),
('w_presentation_C1_08','analytical','/ˌænəˈlɪtɪkəl/','adjective','분석적인','Relating to analysis; using logical reasoning.','She took an {analytical} approach to the problem.','그녀는 문제에 분석적으로 접근했어요.','analytical','C1','presentation',2,'analytical thinking data chart logic'),
('w_presentation_C1_09','synthesize','/ˈsɪnθəsaɪz/','verb','종합하다','To combine elements from different sources into a coherent whole.','The speaker {synthesized} decades of research.','발표자가 수십 년간의 연구를 종합했어요.','synthesized','C1','presentation',1,'synthesis combine integrate knowledge'),
('w_presentation_C1_10','rigorous','/ˈrɪɡərəs/','adjective','엄격한, 철저한','Extremely thorough and careful.','Our methodology is {rigorous} and replicable.','저희 방법론은 엄격하고 재현 가능해요.','rigorous','C1','presentation',2,'rigorous research methodology thorough'),
('w_presentation_C1_11','nuanced','/ˈnjuːɑːnst/','adjective','미묘한 차이가 있는','Characterized by subtle distinctions.','The argument is more {nuanced} than it seems.','그 주장은 보이는 것보다 더 미묘한 차이가 있어요.','nuanced','C1','presentation',2,'nuanced subtle complex layered'),
('w_presentation_C1_12','extrapolate','/ɪkˈstræpəleɪt/','verb','추정하다, 외삽하다','To extend known data into unknown situations.','We can {extrapolate} future trends from this data.','이 데이터로 미래 추세를 추정할 수 있어요.','extrapolate','C1','presentation',2,'extrapolate predict estimate future trend'),
('w_presentation_C1_13','correlate','/ˈkɒrəleɪt/','verb','상관관계가 있다','To have a mutual relationship with another variable.','These two factors {correlate} strongly.','이 두 요소는 강한 상관관계가 있어요.','correlate','C1','presentation',2,'correlation relationship scatter plot data'),
('w_presentation_C1_14','substantive','/ˈsʌbstəntɪv/','adjective','실질적인, 핵심적인','Having a firm basis; meaningful and important.','We need a {substantive} debate on this issue.','이 문제에 대한 실질적인 논의가 필요해요.','substantive','C1','presentation',2,'substantive meaningful important core'),
('w_presentation_C1_15','infer','/ɪnˈfɜːr/','verb','추론하다','To reach a conclusion from evidence and reasoning.','What can we {infer} from this pattern?','이 패턴에서 무엇을 추론할 수 있나요?','infer','C1','presentation',2,'inference reasoning conclusion logic'),
('w_presentation_C1_16','premise','/ˈpremɪs/','noun','전제','A statement from which a conclusion is drawn.','The {premise} of our argument is flawed.','저희 주장의 전제에 결함이 있어요.','premise','C1','presentation',2,'premise assumption base argument logic'),
('w_presentation_C1_17','holistic','/hoʊˈlɪstɪk/','adjective','전체론적인','Characterized by consideration of a whole system.','We took a {holistic} view of the data.','데이터에 대해 전체론적 시각을 취했어요.','holistic','C1','presentation',3,'holistic system whole integrated view'),
('w_presentation_C1_18','juxtaposition','/ˌdʒʌkstəpəˈzɪʃən/','noun','대조, 병치','The act of placing two things close together to show contrast.','The {juxtaposition} makes the difference clear.','이 대조가 차이를 명확하게 해 줘요.','juxtaposition','C1','presentation',2,'juxtaposition contrast comparison side by side'),
('w_presentation_C1_19','eloquent','/ˈeləkwənt/','adjective','유창한, 설득력 있는','Fluent, persuasive, and well-expressed in speech.','Her {eloquent} delivery won over the audience.','그녀의 유창한 전달이 청중을 사로잡았어요.','eloquent','C1','presentation',2,'eloquent speaker confident podium articulate'),
('w_presentation_C1_20','credence','/ˈkriːdəns/','noun','신뢰성, 신빙성','Belief in or trust in something.','This data lends {credence} to our theory.','이 데이터가 저희 이론에 신빙성을 더해요.','credence','C1','presentation',3,'credibility trust belief authority'),
('w_presentation_C1_21','assertion','/əˈsɜːrʃən/','noun','주장, 단언','A confident and forceful statement of fact.','Her {assertion} was backed by solid data.','그녀의 주장은 탄탄한 데이터로 뒷받침됐어요.','assertion','C1','presentation',2,'assertion claim statement confident'),
('w_presentation_C1_22','counterargument','/ˈkaʊntərˌɑːrɡjumənt/','noun','반론, 반박','An argument raised against another argument.','We must address the strongest {counterargument}.','가장 강력한 반론을 다뤄야 해요.','counterargument','C1','presentation',2,'debate counterargument rebuttal response'),
('w_presentation_C1_23','delineate','/dɪˈlɪnieɪt/','verb','명확히 기술하다, 설명하다','To describe or indicate something precisely.','Let me {delineate} the three key phases.','세 가지 핵심 단계를 명확히 설명할게요.','delineate','C1','presentation',3,'outline describe delineate clear precise'),
('w_presentation_C1_24','taxonomy','/tækˈsɒnəmi/','noun','분류 체계','A system of classification into ordered categories.','Our {taxonomy} organizes ideas by impact.','저희 분류 체계는 아이디어를 영향력 순으로 정리해요.','taxonomy','C1','presentation',3,'taxonomy classification categories hierarchy'),
('w_presentation_C1_25','iterate','/ˈɪtəreɪt/','verb','반복하다, 되풀이하다','To perform a process repeatedly to improve the result.','We {iterated} on the design based on feedback.','피드백을 바탕으로 디자인을 반복 개선했어요.','iterated','C1','presentation',2,'iteration improve loop cycle agile'),
('w_presentation_C1_26','robust','/roʊˈbʌst/','adjective','견고한, 탄탄한','Strong and effective; not easily broken.','Our methodology is {robust} and defensible.','저희 방법론은 견고하고 논리적으로 방어 가능해요.','robust','C1','presentation',2,'robust strong solid reliable method'),
('w_presentation_C1_27','interpolate','/ɪnˈtɜːrpəleɪt/','verb','삽입하다, 중간 추정하다','To insert or estimate values within a range.','We can {interpolate} the missing data points.','누락된 데이터 포인트를 추정할 수 있어요.','interpolate','C1','presentation',3,'estimate interpolate fill gap data'),
('w_presentation_C1_28','pivotal','/ˈpɪvətəl/','adjective','결정적인, 핵심적인','Of crucial importance in relation to other things.','This is the {pivotal} moment in our argument.','이것이 저희 주장의 결정적인 순간이에요.','pivotal','C1','presentation',2,'pivot key turning point crucial'),
('w_presentation_C1_29','categorical','/ˌkætɪˈɡɒrɪkəl/','adjective','단호한, 명확한','Unambiguous and without conditions.','I can state {categorically} that the data is sound.','데이터가 건전하다고 단호하게 말할 수 있어요.','categorically','C1','presentation',3,'definite clear certain categorical firm'),
('w_presentation_C1_30','overarching','/ˌoʊvərˈɑːrtʃɪŋ/','adjective','포괄적인, 전반적인','Encompassing everything; most important.','Our {overarching} goal is sustainability.','저희 전반적 목표는 지속가능성이에요.','overarching','C1','presentation',2,'overarching umbrella goal strategy broad'),
('w_presentation_C1_31','reconcile','/ˈrekənsaɪl/','verb','조화시키다, 절충하다','To make two different ideas compatible.','How do we {reconcile} these conflicting findings?','이 상충하는 발견들을 어떻게 조화시킬까요?','reconcile','C1','presentation',2,'reconcile balance compromise integrate'),
('w_presentation_C1_32','modality','/moʊˈdælɪti/','noun','방식, 양식','A particular method or procedure for communication or analysis.','Each {modality} has its strengths and weaknesses.','각 방식에는 장단점이 있어요.','modality','C1','presentation',3,'modality method form approach mode'),
('w_presentation_C1_33','epistemology','/ɪˌpɪstɪˈmɒlədʒi/','noun','인식론','The theory of knowledge and how we know what we know.','From an {epistemological} standpoint, this is uncertain.','인식론적 관점에서 이것은 불확실해요.','epistemological','C1','presentation',3,'epistemology knowledge theory philosophy'),
('w_presentation_C1_34','heuristic','/hjʊˈrɪstɪk/','noun','발견법, 경험적 방법','A practical approach using rules of thumb to reach a good enough solution.','This is a useful {heuristic} for decision-making.','이것은 의사결정에 유용한 발견법이에요.','heuristic','C1','presentation',2,'heuristic rule thumb shortcut method'),
('w_presentation_C1_35','longitudinal','/ˌlɒŋɡɪˈtjuːdɪnəl/','adjective','종단적인','Relating to a study conducted over a long period of time.','This is a {longitudinal} study spanning ten years.','이것은 10년에 걸친 종단 연구예요.','longitudinal','C1','presentation',3,'longitudinal study time series research');

-- ══════════════════════════════════════
-- WORDS — C2 (35개)
-- 핵심 발표 어휘: epistemological, heuristic, ontological, phenomenological, dialectical, praxis, hermeneutic, meta-analysis, positivist, constructivist + 25개
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_presentation_C2_01','epistemological','/ɪˌpɪstɪməˈlɒdʒɪkəl/','adjective','인식론적인','Relating to the theory and scope of knowledge.','The {epistemological} assumptions shape the research design.','인식론적 가정이 연구 설계를 형성해요.','epistemological','C2','presentation',1,'epistemology knowledge philosophy research'),
('w_presentation_C2_02','heuristic','/hjʊˈrɪstɪk/','adjective','발견적인, 경험적인','Enabling a person to discover or learn something for themselves.','Her approach was deliberately {heuristic}.','그녀의 접근 방식은 의도적으로 발견적이었어요.','heuristic','C2','presentation',1,'heuristic discovery learning problem solving'),
('w_presentation_C2_03','ontological','/ˌɒntəˈlɒdʒɪkəl/','adjective','존재론적인','Relating to the nature and existence of things.','These are {ontological} questions about reality.','이것은 현실의 본질에 관한 존재론적 질문이에요.','ontological','C2','presentation',2,'ontology existence reality philosophy being'),
('w_presentation_C2_04','phenomenological','/fɪˌnɒmɪnəˈlɒdʒɪkəl/','adjective','현상학적인','Relating to the study of conscious experience.','The {phenomenological} lens reveals lived experience.','현상학적 렌즈가 살아있는 경험을 드러내요.','phenomenological','C2','presentation',2,'phenomenology experience consciousness lived'),
('w_presentation_C2_05','dialectical','/ˌdaɪəˈlektɪkəl/','adjective','변증법적인','Relating to the resolution of opposing ideas through logical argument.','A {dialectical} tension drives innovation.','변증법적 긴장이 혁신을 이끌어요.','dialectical','C2','presentation',2,'dialectical tension thesis antithesis synthesis'),
('w_presentation_C2_06','praxis','/ˈpræksis/','noun','실천, 프락시스','The practice and practical application of a theory or belief.','Theory without {praxis} remains incomplete.','실천 없는 이론은 불완전해요.','praxis','C2','presentation',2,'praxis practice theory action application'),
('w_presentation_C2_07','hermeneutic','/ˌhɜːrmɪˈnjuːtɪk/','adjective','해석학적인','Relating to interpretation, especially of texts or meaning.','We used a {hermeneutic} approach to analyse the data.','데이터를 분석하기 위해 해석학적 접근법을 사용했어요.','hermeneutic','C2','presentation',2,'hermeneutics interpretation meaning text analysis'),
('w_presentation_C2_08','meta-analysis','/ˌmetə əˈnæləsɪs/','noun','메타분석','A statistical technique that combines results of multiple studies.','The {meta-analysis} confirms our hypothesis.','메타분석이 저희 가설을 확인해요.','meta-analysis','C2','presentation',1,'meta analysis research synthesis statistical'),
('w_presentation_C2_09','positivist','/ˈpɒzɪtɪvɪst/','adjective','실증주의적인','Relating to the doctrine that knowledge is based solely on observable phenomena.','A {positivist} researcher relies entirely on measurable data.','실증주의적 연구자는 측정 가능한 데이터에만 의존해요.','positivist','C2','presentation',2,'positivism empirical observable data science'),
('w_presentation_C2_10','constructivist','/kənˈstrʌktɪvɪst/','adjective','구성주의적인','Relating to the view that knowledge is actively constructed by learners.','A {constructivist} paradigm values lived experience.','구성주의적 패러다임은 살아있는 경험을 중시해요.','constructivist','C2','presentation',2,'constructivism learning knowledge build'),
('w_presentation_C2_11','axiomatic','/ˌæksiəˈmætɪk/','adjective','공리적인, 자명한','Self-evidently true; taken as a given.','It is almost {axiomatic} that trust increases engagement.','신뢰가 참여를 높인다는 것은 거의 자명해요.','axiomatic','C2','presentation',3,'axiom truth self evident principle'),
('w_presentation_C2_12','teleological','/ˌtiːliəˈlɒdʒɪkəl/','adjective','목적론적인','Relating to the explanation of phenomena by their purpose or goal.','A {teleological} framework assumes end goals are fixed.','목적론적 프레임워크는 최종 목표가 고정되어 있다고 가정해요.','teleological','C2','presentation',3,'teleology purpose goal directed philosophy'),
('w_presentation_C2_13','reductionist','/rɪˈdʌkʃənɪst/','adjective','환원주의적인','Relating to analysis of complex phenomena by reducing to simpler components.','A {reductionist} view may miss systemic interactions.','환원주의적 관점은 체계적 상호작용을 놓칠 수 있어요.','reductionist','C2','presentation',3,'reductionism simplify components parts system'),
('w_presentation_C2_14','abductive','/æbˈdʌktɪv/','adjective','귀추적인','Relating to reasoning from observation to the most likely explanation.','We applied {abductive} reasoning to identify root causes.','근본 원인을 파악하기 위해 귀추적 추론을 적용했어요.','abductive','C2','presentation',3,'abduction reasoning inference best explanation'),
('w_presentation_C2_15','inductive','/ɪnˈdʌktɪv/','adjective','귀납적인','Moving from specific observations to general conclusions.','The research design is entirely {inductive}.','연구 설계는 완전히 귀납적이에요.','inductive','C2','presentation',2,'inductive reasoning observation general conclusion'),
('w_presentation_C2_16','deductive','/dɪˈdʌktɪv/','adjective','연역적인','Moving from general principles to specific conclusions.','{Deductive} reasoning starts with a hypothesis.','연역적 추론은 가설에서 시작해요.','Deductive','C2','presentation',2,'deductive logic syllogism general specific'),
('w_presentation_C2_17','semiotic','/ˌsiːmiˈɒtɪk/','adjective','기호학적인','Relating to signs and symbols and their meaning.','A {semiotic} reading of the visuals reveals hidden assumptions.','시각 자료의 기호학적 독해가 숨겨진 가정을 드러내요.','semiotic','C2','presentation',3,'semiotics signs symbols meaning language'),
('w_presentation_C2_18','heterogeneous','/ˌhetərəˈdʒiːniəs/','adjective','이질적인, 다양한','Diverse in character or content.','Our sample is highly {heterogeneous}.','저희 표본은 매우 이질적이에요.','heterogeneous','C2','presentation',3,'diversity heterogeneous varied mixed sample'),
('w_presentation_C2_19','homogeneous','/ˌhɒməˈdʒiːniəs/','adjective','동질적인, 균일한','Of the same kind throughout; uniform.','The control group is deliberately {homogeneous}.','통제군은 의도적으로 동질적이에요.','homogeneous','C2','presentation',3,'uniform same consistent homogeneous group'),
('w_presentation_C2_20','triangulation','/traɪˌæŋɡjʊˈleɪʃən/','noun','삼각검증','Using multiple methods to validate a finding.','{Triangulation} of data sources strengthens validity.','데이터 출처의 삼각검증이 타당성을 강화해요.','Triangulation','C2','presentation',2,'triangulation multiple sources validate confirm'),
('w_presentation_C2_21','reflexivity','/ˌriːflekˈsɪvɪti/','noun','성찰성','The awareness and examination of the researcher''s own position and bias.','Researchers must account for their own {reflexivity}.','연구자들은 자신의 성찰성을 고려해야 해요.','reflexivity','C2','presentation',2,'reflexivity self awareness bias researcher'),
('w_presentation_C2_22','epistemics','/ˌepɪˈstemɪks/','noun','인식론적 과정','The study of the grounds and methods of acquiring knowledge.','Advances in {epistemics} challenge older research models.','인식론적 과정의 발전이 기존 연구 모델에 도전해요.','epistemics','C2','presentation',3,'knowledge epistemics science philosophy method'),
('w_presentation_C2_23','exegesis','/ˌeksɪˈdʒiːsɪs/','noun','주석, 해석','A critical explanation or interpretation of a text.','Her {exegesis} of the primary texts was meticulous.','1차 텍스트에 대한 그녀의 주석은 꼼꼼했어요.','exegesis','C2','presentation',3,'exegesis interpretation text analysis commentary'),
('w_presentation_C2_24','apophatic','/ˌæpəˈfætɪk/','adjective','부정 신학적인','Describing something by what it is not rather than what it is.','An {apophatic} framing highlights what the data cannot show.','부정적 구성은 데이터가 보여줄 수 없는 것을 부각해요.','apophatic','C2','presentation',3,'negative definition limitation boundary what not'),
('w_presentation_C2_25','verisimilitude','/ˌverɪsɪˈmɪlɪtjuːd/','noun','개연성, 사실성','The appearance of being true or real.','The model gains {verisimilitude} through detailed calibration.','모델은 세밀한 보정을 통해 개연성을 얻어요.','verisimilitude','C2','presentation',3,'realism truth appearance credibility'),
('w_presentation_C2_26','apodictic','/ˌæpəˈdɪktɪk/','adjective','필연적으로 참인','Clearly established or beyond dispute; necessarily true.','The conclusion is presented as {apodictic}.','결론이 필연적 사실로 제시돼요.','apodictic','C2','presentation',3,'certain necessary true undeniable logic'),
('w_presentation_C2_27','intersubjectivity','/ˌɪntərsʌbdʒekˈtɪvɪti/','noun','상호주관성','Shared understanding between individuals; consensus of perspective.','The findings depend on {intersubjectivity} of the panel.','발견은 패널의 상호주관성에 의존해요.','intersubjectivity','C2','presentation',3,'shared understanding consensus perspective mutual'),
('w_presentation_C2_28','ontogenesis','/ˌɒntəˈdʒenɪsɪs/','noun','개체발생','The development of an individual organism; applied metaphorically to ideas.','The {ontogenesis} of this concept is traced in the paper.','이 개념의 발전이 논문에 추적돼요.','ontogenesis','C2','presentation',3,'development origin genesis evolution idea'),
('w_presentation_C2_29','polyphony','/pəˈlɪfəni/','noun','다성, 복수 담론','A multiplicity of voices or perspectives in a text or discourse.','The presentation embraces {polyphony} rather than singular truth.','발표는 단일한 진실보다 복수 담론을 수용해요.','polyphony','C2','presentation',3,'multiple voices perspectives diversity discourse'),
('w_presentation_C2_30','heuretics','/hjʊˈretɪks/','noun','발견적 방법론','The methodology of discovery and creative invention.','Her methodology is grounded in {heuretics}.','그녀의 방법론은 발견적 방법론에 기반해요.','heuretics','C2','presentation',3,'discovery invention creativity method'),
('w_presentation_C2_31','autopoiesis','/ˌɔːtəʊpɔɪˈiːsɪs/','noun','자기생성','A system capable of reproducing and maintaining itself.','The organisation demonstrates {autopoiesis} through adaptive cycles.','조직은 적응 주기를 통해 자기생성을 보여요.','autopoiesis','C2','presentation',3,'self sustaining system adapt regenerate'),
('w_presentation_C2_32','liminal','/ˈlɪmɪnəl/','adjective','경계선상의, 전환기의','Occupying a position at both sides of a boundary or threshold.','We are at a {liminal} moment in this field.','우리는 이 분야의 경계선상의 순간에 있어요.','liminal','C2','presentation',3,'threshold boundary transition in between'),
('w_presentation_C2_33','bricolage','/ˈbrɪkəlɑːʒ/','noun','브리콜라주, 짜깁기 조합','Construction using diverse available elements; multi-method research.','The study uses {bricolage} to integrate qualitative sources.','연구는 질적 출처를 통합하기 위해 브리콜라주를 활용해요.','bricolage','C2','presentation',3,'multi method combination diverse mixed'),
('w_presentation_C2_34','aporia','/əˈpɔːriə/','noun','아포리아, 근본적 난제','A state of puzzlement or irresolvable paradox in argument.','The speaker acknowledged the {aporia} at the heart of the theory.','발표자가 이론의 핵심에 있는 아포리아를 인정했어요.','aporia','C2','presentation',3,'paradox dilemma unresolvable contradiction'),
('w_presentation_C2_35','noumenal','/ˈnjuːmɪnəl/','adjective','본체적인, 이성으로만 인식되는','Relating to things as they are in themselves, independent of perception.','The {noumenal} reality behind the data remains inaccessible.','데이터 이면의 본체적 현실은 접근 불가능해요.','noumenal','C2','presentation',3,'noumenon Kant reality perception beyond');

-- ══════════════════════════════════════
-- PATTERNS — A1 (7개) : 발표 시작
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_presentation_A1_01','Let me introduce myself.','자기소개를 하겠습니다.','Let me introduce','발표 시작 시 자기소개 표현이에요. "Let me + 동사"는 자신의 행동을 예고하는 공손한 패턴이에요.','발표 시작','A1','presentation','pattern',NULL,1),
('s_presentation_A1_02','Today I will talk about three things.','오늘 세 가지에 대해 말씀드리겠습니다.','Today I will talk about','주제를 숫자로 미리 알려주면 청중이 기대를 가질 수 있어요.','발표 시작','A1','presentation','pattern',NULL,2),
('s_presentation_A1_03','My name is [name] and I work in [team].','제 이름은 [이름]이고 [팀]에서 일해요.','My name is ... and I work in','이름과 소속을 함께 소개하는 기본 패턴이에요.','자기소개','A1','presentation','pattern',NULL,3),
('s_presentation_A1_04','Please look at slide number one.','슬라이드 1번을 봐 주세요.','Please look at slide','청중의 주의를 화면으로 끌 때 쓰는 표현이에요. "Please"를 붙이면 공손해져요.','슬라이드 안내','A1','presentation','pattern',NULL,4),
('s_presentation_A1_05','First, let''s start with the problem.','먼저 문제부터 시작해 볼게요.','First, let''s start with','"First"로 순서를 알리고 "let''s"로 함께한다는 느낌을 줄 수 있어요.','발표 시작','A1','presentation','pattern',NULL,5),
('s_presentation_A1_06','My talk is about [topic].','제 발표는 [주제]에 관한 것이에요.','My talk is about','발표 주제를 한 문장으로 소개하는 가장 간단한 패턴이에요.','주제 소개','A1','presentation','pattern',NULL,6),
('s_presentation_A1_07','Do you have any questions?','질문 있으세요?','Do you have any questions','발표 중 또는 끝에 청중에게 질문을 유도하는 표현이에요.','질의응답','A1','presentation','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — A2 (7개) : 개요 설명
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_presentation_A2_01','I''ll begin with a brief overview of the topic.','주제에 대한 간략한 개요로 시작하겠습니다.','begin with a brief overview','개요(overview)를 먼저 제시하면 청중이 전체 흐름을 파악할 수 있어요.','개요 소개','A2','presentation','pattern',NULL,8),
('s_presentation_A2_02','My presentation is divided into three parts.','제 발표는 세 부분으로 나뉩니다.','divided into three parts','발표 구조를 미리 설명해 주면 청중이 따라오기 쉬워요.','구조 설명','A2','presentation','pattern',NULL,9),
('s_presentation_A2_03','Let me explain why this topic is important.','이 주제가 왜 중요한지 설명해 드릴게요.','Let me explain why','"Let me explain why"는 근거를 제시하기 전에 쓰는 자연스러운 도입 표현이에요.','배경 설명','A2','presentation','pattern',NULL,10),
('s_presentation_A2_04','By the end of this presentation, you will understand...','이 발표가 끝나면 ...을 이해하게 되실 거예요.','By the end of this presentation','발표 학습 목표를 제시하는 표현으로 청중의 기대를 설정해요.','목표 제시','A2','presentation','pattern',NULL,11),
('s_presentation_A2_05','Let me give you some background information first.','먼저 배경 정보를 드릴게요.','Let me give you some background','배경 정보(background)를 제공해 주제의 맥락을 잡아 주는 표현이에요.','배경 소개','A2','presentation','pattern',NULL,12),
('s_presentation_A2_06','The purpose of this presentation is to...','이 발표의 목적은 ...입니다.','The purpose of this presentation is to','목적(purpose)을 명확히 말해 주면 발표의 초점이 분명해져요.','목적 설명','A2','presentation','pattern',NULL,13),
('s_presentation_A2_07','I''d like to summarize what we''ve covered so far.','지금까지 다룬 내용을 요약해 드릴게요.','I''d like to summarize','섹션 사이에 중간 요약을 넣으면 청중의 이해도가 높아져요.','중간 요약','A2','presentation','pattern',NULL,14);

-- ══════════════════════════════════════
-- PATTERNS — B1 (7개) : 전환 표현
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_presentation_B1_01','Moving on to the next point, let''s look at the data.','다음 포인트로 넘어가서 데이터를 살펴볼게요.','Moving on to the next point','"Moving on to..."는 자연스럽게 다음 주제로 전환하는 표현이에요.','주제 전환','B1','presentation','pattern',NULL,15),
('s_presentation_B1_02','This brings me to my second main point.','이것이 저를 두 번째 핵심 요점으로 이끌어요.','This brings me to','앞 내용에서 자연스럽게 다음 주제로 연결하는 우아한 전환 표현이에요.','흐름 연결','B1','presentation','pattern',NULL,16),
('s_presentation_B1_03','With that in mind, let''s turn to the solution.','그 점을 염두에 두고 해결책으로 넘어갈게요.','With that in mind','앞서 제시한 내용을 의식하면서 전환하는 고급 연결 표현이에요.','전환 연결','B1','presentation','pattern',NULL,17),
('s_presentation_B1_04','Let me now turn to the second part of my talk.','이제 발표의 두 번째 부분으로 넘어갈게요.','Let me now turn to','섹션 전환 시 청중에게 구조적 신호를 주는 표현이에요.','섹션 전환','B1','presentation','pattern',NULL,18),
('s_presentation_B1_05','So far we''ve looked at the problem. Now let''s consider the solution.','지금까지 문제를 살펴봤어요. 이제 해결책을 고려해 봐요.','So far ... Now let''s consider','"So far...Now let''s"는 발표 흐름을 명확히 분리해 주는 구조적 표현이에요.','대비 전환','B1','presentation','pattern',NULL,19),
('s_presentation_B1_06','That covers the background. Let''s move on to the findings.','배경 설명을 마쳤어요. 이제 발견으로 넘어갈게요.','That covers the background','앞 섹션을 마무리하고 다음으로 진행할 때 쓰는 표현이에요.','섹션 마무리','B1','presentation','pattern',NULL,20),
('s_presentation_B1_07','Before I move on, does anyone have any questions about this?','넘어가기 전에 이 부분에 대해 질문 있으세요?','Before I move on','섹션 중간에 질문 기회를 줄 때 쓰는 발표 관리 표현이에요.','질문 유도','B1','presentation','pattern',NULL,21);

-- ══════════════════════════════════════
-- PATTERNS — B2 (7개) : 강조 + 마무리
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_presentation_B2_01','What I want to emphasize above all is that...','무엇보다 강조하고 싶은 것은 ...이에요.','What I want to emphasize above all','강조 구문 중 가장 임팩트 있는 표현으로, 청중의 주의를 집중시켜요.','핵심 강조','B2','presentation','pattern',NULL,22),
('s_presentation_B2_02','The data clearly demonstrates that this approach is effective.','데이터는 이 접근법이 효과적임을 명확히 보여 줘요.','The data clearly demonstrates','증거 기반 강조 표현으로 설득력 있는 주장을 만들어요.','근거 강조','B2','presentation','pattern',NULL,23),
('s_presentation_B2_03','It''s worth noting that the margin of improvement is significant.','개선 폭이 상당하다는 점에 주목할 필요가 있어요.','It''s worth noting that','청중이 놓칠 수 있는 중요한 세부 사항을 부각할 때 쓰는 표현이에요.','세부 강조','B2','presentation','pattern',NULL,24),
('s_presentation_B2_04','In conclusion, the evidence strongly supports our recommendation.','결론적으로 증거는 저희 권고안을 강력히 뒷받침해요.','In conclusion, the evidence strongly supports','증거로 결론을 뒷받침하는 설득력 있는 마무리 패턴이에요.','마무리 강조','B2','presentation','pattern',NULL,25),
('s_presentation_B2_05','I''d like to leave you with one key takeaway from today''s presentation.','오늘 발표에서 한 가지 핵심 요점을 가져가셨으면 해요.','leave you with one key takeaway','청중이 기억할 단 하나의 메시지를 남기는 강력한 마무리 표현이에요.','마무리','B2','presentation','pattern',NULL,26),
('s_presentation_B2_06','To put it differently, this is not a cost issue but an investment question.','다르게 표현하면 이것은 비용 문제가 아니라 투자 문제예요.','To put it differently','재구성(reframing)은 B2 이상에서 설득력을 높이는 핵심 기술이에요.','재구성 강조','B2','presentation','pattern',NULL,27),
('s_presentation_B2_07','Thank you for your attention. I''m happy to take any questions now.','경청해 주셔서 감사합니다. 질문을 받겠습니다.','happy to take any questions','발표를 공손하고 열린 자세로 마무리하는 표현이에요.','발표 마무리','B2','presentation','pattern',NULL,28);

-- ══════════════════════════════════════
-- PATTERNS — C1 (7개) : 설득 + 수사학
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_presentation_C1_01','Allow me to challenge what I believe is a commonly held misconception.','흔히 가지고 있는 오해라고 생각하는 것에 도전하겠습니다.','Allow me to challenge a commonly held misconception','청중의 기존 인식을 깨는 설득의 첫 단계로, 강렬한 주의 환기 효과가 있어요.','오해 반박','C1','presentation','pattern',NULL,29),
('s_presentation_C1_02','Rather than accepting the conventional wisdom, we must interrogate its underlying assumptions.','통념을 받아들이기보다 그 기저의 가정들을 검토해야 해요.','we must interrogate its underlying assumptions','비판적 사고를 드러내는 고급 학술 발표 표현이에요.','비판적 논증','C1','presentation','pattern',NULL,30),
('s_presentation_C1_03','The evidence is compelling, but context is equally critical to interpretation.','증거는 설득력이 있지만 맥락도 해석에 똑같이 중요해요.','context is equally critical to interpretation','증거와 맥락의 균형을 강조하는 세련된 학술 표현이에요.','맥락 강조','C1','presentation','pattern',NULL,31),
('s_presentation_C1_04','To synthesize the key threads of this argument: we have demonstrated X, evidenced Y, and concluded Z.','이 주장의 핵심 흐름을 종합하면 X를 보여주고, Y를 근거로, Z를 결론 내렸어요.','To synthesize the key threads','마무리에서 논증 흐름을 종합하는 고급 구조화 표현이에요.','논증 종합','C1','presentation','pattern',NULL,32),
('s_presentation_C1_05','Far from being a linear process, innovation emerges through iterative failure and recalibration.','선형적 과정과 거리가 멀게도 혁신은 반복적 실패와 재조정을 통해 나타나요.','Far from being a linear process','"Far from being..."은 통념을 뒤집는 수사적 패턴으로 C1 설득에 효과적이에요.','통념 반박','C1','presentation','pattern',NULL,33),
('s_presentation_C1_06','What sets this framework apart is not its novelty but its rigorous empirical grounding.','이 프레임워크를 차별화하는 것은 새로움이 아니라 엄격한 실증적 기반이에요.','What sets this framework apart is','설득력 있는 비교 논증을 시작하는 고급 강조 표현이에요.','차별화 강조','C1','presentation','pattern',NULL,34),
('s_presentation_C1_07','I would now invite you to consider the broader implications of these findings for the field.','이제 이 발견들이 해당 분야에 가지는 더 넓은 함의를 생각해 보시길 권해요.','I would invite you to consider the broader implications','청중을 능동적 사고로 초대하는 우아하고 고급스러운 마무리 표현이에요.','함의 초대','C1','presentation','pattern',NULL,35);

-- ══════════════════════════════════════
-- PATTERNS — C2 (7개) : 수사학 + 철학적 논증
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_presentation_C2_01','The epistemological tension at the heart of this debate cannot be resolved through data alone; it demands ontological reflection.','이 논쟁의 핵심에 있는 인식론적 긴장은 데이터만으로는 해결될 수 없어요. 존재론적 성찰이 필요해요.','epistemological tension ... demands ontological reflection','인식론과 존재론을 연결하는 C2 수준의 철학적 수사 표현이에요.','철학적 논증','C2','presentation','pattern',NULL,36),
('s_presentation_C2_02','What the meta-analysis reveals, paradoxically, is the very limits of meta-analytic methodology.','역설적으로 메타분석이 드러내는 것은 바로 메타분석 방법론의 한계예요.','paradoxically, reveals the very limits','역설을 활용한 고급 수사 기법으로 청중의 사고를 자극해요.','역설적 논증','C2','presentation','pattern',NULL,37),
('s_presentation_C2_03','In adopting a constructivist lens, we implicitly reject the positivist assumption that knowledge exists independently of the knower.','구성주의적 렌즈를 채택함으로써 우리는 지식이 인식자와 독립적으로 존재한다는 실증주의적 가정을 묵시적으로 거부해요.','adopting a constructivist lens, we implicitly reject the positivist assumption','두 철학적 입장을 대비시키는 C2 학술 발표의 전형적 논증 패턴이에요.','철학 대비','C2','presentation','pattern',NULL,38),
('s_presentation_C2_04','The dialectical movement from thesis to antithesis does not yield a tidy synthesis; instead, it opens a productive aporia.','테제에서 반테제로의 변증법적 운동은 깔끔한 종합을 낳지 않아요. 대신 생산적 아포리아를 열어요.','dialectical movement ... opens a productive aporia','변증법과 아포리아를 연결하는 최고 수준의 학술 수사 표현이에요.','변증법적 논증','C2','presentation','pattern',NULL,39),
('s_presentation_C2_05','Hermeneutic fidelity to the source material demands that we resist the temptation to over-systematize the findings.','원천 자료에 대한 해석학적 충실성은 발견을 과도하게 체계화하려는 유혹에 저항하도록 요구해요.','Hermeneutic fidelity ... demands that we resist','해석학적 개념을 발표 방법론 비판에 적용하는 C2 수준의 표현이에요.','방법론 비판','C2','presentation','pattern',NULL,40),
('s_presentation_C2_06','To conclude with a provocation: if our framework cannot account for its own conditions of possibility, it undermines itself.','도발적인 결론으로 마치겠어요. 저희 프레임워크가 자체 가능성의 조건을 설명하지 못한다면 스스로를 무너뜨리는 거예요.','conclude with a provocation ... undermines itself','자기지시적 역설로 마무리하는 충격적인 수사 기법이에요.','도발적 마무리','C2','presentation','pattern',NULL,41),
('s_presentation_C2_07','The praxis of transformative rhetoric lies not in winning arguments, but in shifting the very ground on which arguments are made.','변혁적 수사학의 실천은 논증에서 이기는 데 있는 게 아니라 논증이 이루어지는 근거 자체를 바꾸는 데 있어요.','praxis of transformative rhetoric ... shifting the very ground','수사학의 궁극적 목적을 메타적으로 정의하는 C2 최고 수준 마무리 표현이에요.','수사학 정의','C2','presentation','pattern',NULL,42);
