-- EngCat — Transport (교통) 단어 210개 + 패턴 42개
-- CEFR A1~C2, 35 words × 6 levels, 7 patterns × 6 levels
-- Generated: 2026-05-24

-- ══════════════════════════════════════
-- WORDS — A1 (35개)
-- 테마: bus, taxi, train, car, walk, bike, road, stop, ticket, ride
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_transport_A1_01','bus','/bʌs/','noun','버스','A large road vehicle that carries passengers along a fixed route.','I take the {bus} to school every morning.','저는 매일 아침 버스를 타고 학교에 가요.','bus','A1','transport',1,'bus public transport city street'),
('w_transport_A1_02','taxi','/ˈtæksi/','noun','택시','A car with a driver that you pay to take you somewhere.','Let''s take a {taxi} to the hotel.','호텔까지 택시를 타고 가요.','taxi','A1','transport',1,'taxi cab city yellow car'),
('w_transport_A1_03','train','/treɪn/','noun','기차','A vehicle that travels along rails and carries passengers.','The {train} to Seoul leaves at nine.','서울행 기차는 9시에 출발해요.','train','A1','transport',1,'train railway station platform'),
('w_transport_A1_04','car','/kɑːr/','noun','자동차','A road vehicle with an engine, four wheels, and seats for passengers.','My dad drives a red {car}.','아빠는 빨간 자동차를 운전해요.','car','A1','transport',1,'car road drive vehicle'),
('w_transport_A1_05','walk','/wɔːk/','verb','걷다','To move on foot at a normal speed.','I usually {walk} to the park on weekends.','저는 주말에 보통 걸어서 공원에 가요.','walk','A1','transport',1,'walk pedestrian footpath park'),
('w_transport_A1_06','bike','/baɪk/','noun','자전거','A two-wheeled vehicle that you ride by pushing pedals.','She rides her {bike} to work.','그녀는 자전거를 타고 출근해요.','bike','A1','transport',1,'bike bicycle cycling path'),
('w_transport_A1_07','road','/roʊd/','noun','도로','A wide path for vehicles to travel along.','The {road} is very busy in the morning.','그 도로는 아침에 매우 혼잡해요.','road','A1','transport',1,'road street asphalt traffic'),
('w_transport_A1_08','stop','/stɒp/','noun','정류장','A place where a bus or train regularly stops.','Get off at the next {stop}.','다음 정류장에서 내리세요.','stop','A1','transport',1,'bus stop sign street waiting'),
('w_transport_A1_09','ticket','/ˈtɪkɪt/','noun','표, 티켓','A piece of paper that shows you have paid to travel or enter somewhere.','Please buy your {ticket} before boarding.','승차 전에 표를 구매해 주세요.','ticket','A1','transport',1,'ticket booth train metro'),
('w_transport_A1_10','ride','/raɪd/','verb','타다','To sit on a vehicle and travel in or on it.','Can you {ride} a bicycle?','자전거를 탈 줄 알아요?','ride','A1','transport',1,'ride bicycle cycling outdoor'),
('w_transport_A1_11','go','/ɡoʊ/','verb','가다','To move or travel to a place.','How do you {go} to school?','학교에 어떻게 가요?','go','A1','transport',1,'go walk commute city'),
('w_transport_A1_12','come','/kʌm/','verb','오다','To move toward the speaker or a specified place.','How did you {come} here today?','오늘 여기 어떻게 오셨어요?','come','A1','transport',1,'come arrive person walking'),
('w_transport_A1_13','near','/nɪr/','adjective','가까운','Located a short distance away.','Is the station {near} here?','역이 여기서 가까운가요?','near','A1','transport',1,'near close map location'),
('w_transport_A1_14','far','/fɑːr/','adjective','먼','Located at a great distance.','The airport is quite {far} from downtown.','공항은 시내에서 꽤 멀어요.','far','A1','transport',1,'far distance road horizon'),
('w_transport_A1_15','left','/lɛft/','noun','왼쪽','The direction toward the west when facing north.','Turn {left} at the traffic light.','신호등에서 왼쪽으로 도세요.','left','A1','transport',1,'left direction arrow street'),
('w_transport_A1_16','right','/raɪt/','noun','오른쪽','The direction toward the east when facing north.','Turn {right} at the corner.','모퉁이에서 오른쪽으로 도세요.','right','A1','transport',1,'right direction arrow corner'),
('w_transport_A1_17','straight','/streɪt/','adverb','직진으로','In a direct line without turning.','Go {straight} for two blocks.','두 블록 직진해 주세요.','straight','A1','transport',1,'straight ahead road direction'),
('w_transport_A1_18','map','/mæp/','noun','지도','A diagram of a place showing roads, features, and points of interest.','Can I see your {map}?','지도 좀 볼 수 있나요?','map','A1','transport',1,'map navigation directions paper'),
('w_transport_A1_19','station','/ˈsteɪʃən/','noun','역','A place where trains or buses stop for passengers.','Which {station} should I get off at?','어느 역에서 내려야 하나요?','station','A1','transport',1,'train station building platform'),
('w_transport_A1_20','airport','/ˈeərpɔːrt/','noun','공항','A place where aircraft take off and land.','Let''s meet at the {airport} entrance.','공항 입구에서 만나요.','airport','A1','transport',1,'airport terminal planes sky'),
('w_transport_A1_21','boat','/boʊt/','noun','배','A small vessel for traveling on water.','We took a {boat} across the lake.','우리는 배를 타고 호수를 건넜어요.','boat','A1','transport',1,'boat lake water vessel'),
('w_transport_A1_22','plane','/pleɪn/','noun','비행기','A vehicle with wings and engines that flies through the air.','My first {plane} ride was exciting.','첫 비행기 탑승이 정말 설렜어요.','plane','A1','transport',1,'airplane sky clouds flight'),
('w_transport_A1_23','bridge','/brɪdʒ/','noun','다리','A structure built over water or a road to allow people to cross.','Drive over the {bridge} and turn right.','다리를 건넌 후 오른쪽으로 도세요.','bridge','A1','transport',1,'bridge river city crossing'),
('w_transport_A1_24','street','/striːt/','noun','거리, 길','A public road in a city or town.','What {street} do you live on?','어느 거리에 살아요?','street','A1','transport',1,'street city road urban'),
('w_transport_A1_25','corner','/ˈkɔːrnər/','noun','모퉁이','The place where two roads or edges meet.','Wait at the {corner} for me.','모퉁이에서 기다려 주세요.','corner','A1','transport',1,'corner street intersection road'),
('w_transport_A1_26','slow','/sloʊ/','adjective','느린','Not moving quickly.','The bus is very {slow} today.','오늘 버스가 매우 느려요.','slow','A1','transport',2,'slow traffic car street'),
('w_transport_A1_27','fast','/fæst/','adjective','빠른','Moving or able to move quickly.','Take the express — it''s much {faster}.','급행을 타요 — 훨씬 빠르거든요.','faster','A1','transport',2,'fast speed train highway'),
('w_transport_A1_28','free','/friː/','adjective','무료의','Not costing any money.','Children under five ride for {free}.','5세 미만 어린이는 무료로 탑승해요.','free','A1','transport',2,'free sign public transport'),
('w_transport_A1_29','door','/dɔːr/','noun','문','A hinged or sliding barrier at the entrance to a vehicle.','Please stand clear of the {doors}.','문 가까이 서지 마세요.','doors','A1','transport',2,'door metro subway train'),
('w_transport_A1_30','seat','/siːt/','noun','좌석','A place where someone sits on a vehicle or in a venue.','Is this {seat} taken?','이 좌석 비어 있나요?','seat','A1','transport',2,'seat chair bus train'),
('w_transport_A1_31','wait','/weɪt/','verb','기다리다','To stay in one place until something happens.','Please {wait} for the next bus.','다음 버스를 기다려 주세요.','wait','A1','transport',2,'wait bus stop people bench'),
('w_transport_A1_32','help','/hɛlp/','verb','돕다','To make it easier for someone to do something.','Could you {help} me find the station?','역 찾는 것을 도와주실 수 있나요?','help','A1','transport',2,'help assist person direction'),
('w_transport_A1_33','line','/laɪn/','noun','노선, 줄','A route for a bus or train service.','Take the blue {line} to Central Station.','중앙역까지 파란 노선을 타세요.','line','A1','transport',2,'subway line metro map'),
('w_transport_A1_34','number','/ˈnʌmbər/','noun','번호','A numerical label identifying a bus or train route.','Which {number} bus goes to the market?','시장에는 몇 번 버스가 가나요?','number','A1','transport',2,'bus number route sign'),
('w_transport_A1_35','here','/hɪr/','adverb','여기','In, at, or to this place.','Stop {here}, please.','여기서 세워 주세요.','here','A1','transport',2,'here location map spot')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — A2 (35개)
-- 테마: subway, platform, transfer, schedule, fare, route, station, departure, arrival, delay
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_transport_A2_01','subway','/ˈsʌbweɪ/','noun','지하철','An underground railway system in a city.','The {subway} is faster than the bus during rush hour.','러시아워에는 지하철이 버스보다 빨라요.','subway','A2','transport',1,'subway underground metro tunnel'),
('w_transport_A2_02','platform','/ˈplætfɔːrm/','noun','플랫폼, 승강장','The raised area beside the tracks at a station where you board trains.','Please wait on {platform} three.','3번 플랫폼에서 기다려 주세요.','platform','A2','transport',1,'platform train station railway'),
('w_transport_A2_03','transfer','/ˈtrænsfɜːr/','verb','환승하다','To change from one vehicle to another during a journey.','You need to {transfer} at City Hall station.','시청역에서 환승해야 해요.','transfer','A2','transport',1,'transfer subway station commute'),
('w_transport_A2_04','schedule','/ˈskedʒuːl/','noun','시간표, 일정','A timetable showing when vehicles depart and arrive.','Check the {schedule} before you leave.','출발 전에 시간표를 확인해 주세요.','schedule','A2','transport',1,'schedule timetable board station'),
('w_transport_A2_05','fare','/fɛr/','noun','요금','The money you pay to travel on public transport.','The bus {fare} is two dollars.','버스 요금은 2달러예요.','fare','A2','transport',1,'fare ticket machine transport'),
('w_transport_A2_06','route','/ruːt/','noun','노선, 경로','The path taken to get from one place to another.','This {route} avoids the highway.','이 경로는 고속도로를 피해요.','route','A2','transport',1,'route map navigation path'),
('w_transport_A2_07','departure','/dɪˈpɑːrtʃər/','noun','출발','The act of leaving a place, especially to start a journey.','The {departure} board shows gate C4.','출발 안내판에 C4번 게이트가 표시돼요.','departure','A2','transport',1,'departure board airport gate'),
('w_transport_A2_08','arrival','/əˈraɪvəl/','noun','도착','The act of reaching a destination.','The estimated {arrival} time is 6 p.m.','예상 도착 시간은 오후 6시예요.','arrival','A2','transport',1,'arrival airport terminal passengers'),
('w_transport_A2_09','delay','/dɪˈleɪ/','noun','지연, 연착','A period of time by which something is later than expected.','There is a thirty-minute {delay} on the red line.','빨간 노선에 30분 지연이 있어요.','delay','A2','transport',1,'delay board station announcement'),
('w_transport_A2_10','express','/ɪkˈsprɛs/','adjective','급행의','Traveling at high speed with few stops.','Take the {express} train to save time.','시간을 절약하려면 급행 기차를 타세요.','express','A2','transport',1,'express train speed railway'),
('w_transport_A2_11','local','/ˈloʊkəl/','adjective','완행의, 지역의','Stopping at every station along the route.','The {local} bus stops at every corner.','완행 버스는 모든 모퉁이에 서요.','local','A2','transport',1,'local bus route neighborhood'),
('w_transport_A2_12','direction','/dɪˈrɛkʃən/','noun','방향','The course along which someone or something moves.','Am I going in the right {direction}?','제가 올바른 방향으로 가고 있나요?','direction','A2','transport',1,'direction sign road arrow'),
('w_transport_A2_13','distance','/ˈdɪstəns/','noun','거리','The amount of space between two points.','The walking {distance} is about ten minutes.','걸어서 약 10분 거리예요.','distance','A2','transport',1,'distance road map walking'),
('w_transport_A2_14','passenger','/ˈpæsɪndʒər/','noun','승객','A person who travels on a vehicle but is not driving it.','All {passengers} must show their tickets.','모든 승객은 표를 보여주어야 해요.','passengers','A2','transport',1,'passenger bus train crowd'),
('w_transport_A2_15','driver','/ˈdraɪvər/','noun','운전기사','A person who drives a vehicle.','Ask the {driver} which stop to get off at.','어느 정류장에서 내릴지 운전기사에게 물어보세요.','driver','A2','transport',1,'driver bus taxi wheel'),
('w_transport_A2_16','traffic','/ˈtræfɪk/','noun','교통, 차량','Vehicles moving on a road.','There''s heavy {traffic} on the bridge.','다리 위에 교통이 심하게 막혀요.','traffic','A2','transport',1,'traffic jam highway cars road'),
('w_transport_A2_17','parking','/ˈpɑːrkɪŋ/','noun','주차','The act or space of leaving a vehicle in a particular spot.','Is there free {parking} nearby?','근처에 무료 주차가 있나요?','parking','A2','transport',1,'parking lot cars urban'),
('w_transport_A2_18','return','/rɪˈtɜːrn/','adjective','왕복의','Relating to a ticket that covers both going and coming back.','I''d like a {return} ticket to Busan.','부산까지 왕복 표를 주세요.','return','A2','transport',1,'ticket booth return journey'),
('w_transport_A2_19','single','/ˈsɪŋɡəl/','adjective','편도의','Relating to a ticket for a journey in one direction only.','A {single} to the airport, please.','공항까지 편도 한 장 주세요.','single','A2','transport',2,'single ticket one way train'),
('w_transport_A2_20','connection','/kəˈnɛkʃən/','noun','연결편, 환승 연계','A train or bus that you change onto from another service.','I missed my {connection} in Tokyo.','도쿄에서 연결편을 놓쳤어요.','connection','A2','transport',2,'connection transfer airport boarding'),
('w_transport_A2_21','cancel','/ˈkænsəl/','verb','취소하다','To decide that something planned will not happen.','My flight was {cancelled} due to the storm.','폭풍으로 비행편이 취소됐어요.','cancelled','A2','transport',2,'cancel flight board announcement'),
('w_transport_A2_22','board','/bɔːrd/','verb','탑승하다','To get on a plane, ship, bus, or train.','We will begin {boarding} in ten minutes.','10분 후에 탑승을 시작합니다.','boarding','A2','transport',2,'boarding plane gate airport'),
('w_transport_A2_23','luggage','/ˈlʌɡɪdʒ/','noun','짐, 수하물','Bags and suitcases used when travelling.','Where can I store my {luggage}?','짐을 어디에 보관할 수 있나요?','luggage','A2','transport',2,'luggage suitcase travel airport'),
('w_transport_A2_24','taxi rank','/ˈtæksi ræŋk/','noun','택시 승강장','A place where taxis wait to be hired.','There is a {taxi rank} outside the station.','역 밖에 택시 승강장이 있어요.','taxi rank','A2','transport',2,'taxi rank queue street'),
('w_transport_A2_25','overhead','/ˌoʊvərˈhɛd/','adverb','머리 위에','Above your head.','Place your bag in the {overhead} compartment.','가방을 선반 위 칸에 올려놓으세요.','overhead','A2','transport',2,'overhead compartment plane travel'),
('w_transport_A2_26','rush hour','/rʌʃ ˌaʊər/','noun','러시아워','The busiest period of the day for traffic.','Avoid travelling during {rush hour}.','러시아워에는 이동을 피하세요.','rush hour','A2','transport',2,'rush hour commute crowd subway'),
('w_transport_A2_27','pedestrian crossing','/pɪˈdɛstriən ˌkrɔːsɪŋ/','noun','횡단보도','A marked area of road where pedestrians have priority.','Always use the {pedestrian crossing}.','항상 횡단보도를 이용하세요.','pedestrian crossing','A2','transport',2,'pedestrian crossing zebra street'),
('w_transport_A2_28','signal','/ˈsɪɡnəl/','noun','신호','A light or sign that tells drivers or pedestrians when to stop or go.','Wait for the {signal} to turn green.','신호가 초록색으로 바뀔 때까지 기다리세요.','signal','A2','transport',2,'traffic signal light green red'),
('w_transport_A2_29','lane','/leɪn/','noun','차선','A narrow section of a road for a single line of traffic.','Keep in the left {lane}.','왼쪽 차선을 유지하세요.','lane','A2','transport',2,'lane road highway cars'),
('w_transport_A2_30','timetable','/ˈtaɪmˌteɪbəl/','noun','시각표','A printed list of times when buses or trains arrive and depart.','Look at the {timetable} on the wall.','벽에 있는 시각표를 보세요.','timetable','A2','transport',2,'timetable schedule board station'),
('w_transport_A2_31','underground','/ˈʌndərɡraʊnd/','noun','지하철 (영국식)','The underground railway system, especially in London.','Take the {underground} to Oxford Street.','옥스포드 스트리트까지 지하철을 타세요.','underground','A2','transport',2,'underground metro tube london'),
('w_transport_A2_32','carriage','/ˈkærɪdʒ/','noun','객차','One of the separate sections of a train.','Our reserved seats are in {carriage} four.','예약 좌석은 4번 객차에 있어요.','carriage','A2','transport',2,'carriage train seat window'),
('w_transport_A2_33','vehicle','/ˈviːɪkəl/','noun','차량','Any object used for transporting people or goods.','Only authorized {vehicles} are permitted.','허가된 차량만 진입할 수 있어요.','vehicles','A2','transport',2,'vehicle car van road'),
('w_transport_A2_34','arrive','/əˈraɪv/','verb','도착하다','To reach a destination.','What time does the train {arrive}?','기차는 몇 시에 도착하나요?','arrive','A2','transport',2,'arrive station platform train'),
('w_transport_A2_35','depart','/dɪˈpɑːrt/','verb','출발하다','To leave a place, especially at the start of a journey.','The ferry will {depart} in fifteen minutes.','페리는 15분 후에 출발해요.','depart','A2','transport',2,'depart ferry boat dock')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — B1 (35개)
-- 테마: commute, traffic, congestion, carpool, timetable, boarding, express, terminal, junction, pedestrian
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_transport_B1_01','commute','/kəˈmjuːt/','verb','통근하다','To travel regularly between home and work.','He {commutes} two hours each way every day.','그는 매일 편도 두 시간씩 통근해요.','commutes','B1','transport',1,'commute train subway crowd morning'),
('w_transport_B1_02','congestion','/kənˈdʒɛstʃən/','noun','교통 혼잡','A situation where roads are so crowded with vehicles that traffic moves slowly.','Road {congestion} is worst between 8 and 9 a.m.','도로 혼잡은 오전 8시에서 9시 사이가 가장 심해요.','congestion','B1','transport',1,'congestion traffic jam highway cars'),
('w_transport_B1_03','carpool','/ˈkɑːrpuːl/','verb','카풀하다','To travel to work with others, sharing a vehicle to reduce costs.','We {carpool} to save money on petrol.','기름값을 아끼려고 카풀을 해요.','carpool','B1','transport',1,'carpool sharing car commute'),
('w_transport_B1_04','terminal','/ˈtɜːrmɪnəl/','noun','터미널','The main building at an airport or bus station where passengers arrive and depart.','The international {terminal} is in building A.','국제선 터미널은 A동에 있어요.','terminal','B1','transport',1,'terminal airport building passengers'),
('w_transport_B1_05','junction','/ˈdʒʌŋkʃən/','noun','교차로, 분기점','A point where two or more roads or railway lines meet.','Turn left at the {junction} ahead.','앞쪽 교차로에서 왼쪽으로 도세요.','junction','B1','transport',1,'junction road intersection traffic'),
('w_transport_B1_06','pedestrian','/pɪˈdɛstriən/','noun','보행자','A person who is walking, especially in a city or town.','Please watch for {pedestrians} at all times.','항상 보행자를 주의하세요.','pedestrians','B1','transport',1,'pedestrian crosswalk city street'),
('w_transport_B1_07','overtake','/ˌoʊvərˈteɪk/','verb','추월하다','To pass another vehicle that is going in the same direction.','It is dangerous to {overtake} on a bend.','굽은 길에서 추월하는 것은 위험해요.','overtake','B1','transport',1,'overtake car highway speed'),
('w_transport_B1_08','roundabout','/ˈraʊndəbaʊt/','noun','로터리, 회전교차로','A circular junction where traffic flows around a central island.','Take the second exit at the {roundabout}.','로터리에서 두 번째 출구로 나가세요.','roundabout','B1','transport',1,'roundabout circular road traffic'),
('w_transport_B1_09','diversion','/daɪˈvɜːrʒən/','noun','우회로, 우회','An alternative route used when the usual road is closed.','Follow the {diversion} signs past the school.','학교 옆 우회 표지판을 따라가세요.','diversion','B1','transport',2,'diversion sign road construction'),
('w_transport_B1_10','speed limit','/ˈspiːd ˌlɪmɪt/','noun','제한 속도','The maximum speed legally allowed on a particular road.','The {speed limit} on this road is 60 km/h.','이 도로의 제한 속도는 시속 60킬로미터예요.','speed limit','B1','transport',1,'speed limit sign road'),
('w_transport_B1_11','commuter','/kəˈmjuːtər/','noun','통근자','A person who regularly travels to work from outside a city.','The station is packed with {commuters} at 8 a.m.','오전 8시에는 역이 통근자들로 꽉 차요.','commuters','B1','transport',1,'commuter train station busy'),
('w_transport_B1_12','boarding pass','/ˈbɔːrdɪŋ pæs/','noun','탑승권','A document that allows a passenger to board an aircraft.','Please have your {boarding pass} ready at the gate.','게이트에서 탑승권을 준비해 주세요.','boarding pass','B1','transport',1,'boarding pass airport check-in'),
('w_transport_B1_13','platform number','/ˈplætfɔːrm ˌnʌmbər/','noun','플랫폼 번호','The number identifying the specific platform for a train.','The train departs from {platform number} seven.','기차는 7번 플랫폼에서 출발해요.','platform number','B1','transport',2,'platform number train station sign'),
('w_transport_B1_14','direct','/dɪˈrɛkt/','adjective','직행의','Going from one place to another without stopping or changing.','Is there a {direct} bus to the museum?','박물관까지 직행 버스가 있나요?','direct','B1','transport',1,'direct bus route nonstop'),
('w_transport_B1_15','overhead line','/ˈoʊvərˌhɛd laɪn/','noun','전철선, 가선','An electric wire above a railway track that supplies power to trains.','Damage to the {overhead line} has caused delays.','전철선 손상으로 지연이 발생했어요.','overhead line','B1','transport',3,'overhead wire railway electric'),
('w_transport_B1_16','level crossing','/ˈlɛvəl ˌkrɔːsɪŋ/','noun','철도 건널목','A place where a road crosses a railway line.','Stop at the {level crossing} and wait for the barrier.','건널목에서 멈추고 차단기를 기다리세요.','level crossing','B1','transport',2,'level crossing barrier train road'),
('w_transport_B1_17','bypass','/ˈbaɪpæs/','noun','우회 도로','A road that passes around a town to reduce traffic in the center.','Take the {bypass} to avoid the city center.','도심을 피하려면 우회 도로를 이용하세요.','bypass','B1','transport',2,'bypass highway road traffic'),
('w_transport_B1_18','fare card','/fɛr kɑːrd/','noun','교통 카드','A card used to pay for public transport journeys electronically.','Top up your {fare card} before the ride.','탑승 전에 교통 카드를 충전해 주세요.','fare card','B1','transport',1,'fare card transit payment'),
('w_transport_B1_19','tram','/træm/','noun','전차, 트램','An electric vehicle that travels along rails laid in a road.','The {tram} stops right in front of the museum.','전차가 박물관 바로 앞에 서요.','tram','B1','transport',2,'tram city street rails'),
('w_transport_B1_20','ferry','/ˈfɛri/','noun','페리, 여객선','A boat that carries passengers and sometimes vehicles across water.','We took the {ferry} from Busan to Jeju.','부산에서 제주까지 페리를 탔어요.','ferry','B1','transport',1,'ferry boat ocean passengers'),
('w_transport_B1_21','cycle lane','/ˈsaɪkəl leɪn/','noun','자전거 전용 차선','A part of a road set aside for cyclists.','Always use the {cycle lane} when available.','자전거 전용 차선이 있을 때는 반드시 이용하세요.','cycle lane','B1','transport',2,'cycle lane bike road marking'),
('w_transport_B1_22','gridlock','/ˈɡrɪdlɒk/','noun','극심한 교통 정체','A situation in which traffic cannot move in any direction.','The city centre was in complete {gridlock} this morning.','오늘 아침 도심이 완전히 막혔어요.','gridlock','B1','transport',2,'gridlock traffic city downtown'),
('w_transport_B1_23','interchange','/ˈɪntərˌtʃeɪndʒ/','noun','인터체인지, 환승 거점','A road junction where vehicles can change from one road to another without crossing traffic.','The {interchange} at exit 12 can get very busy.','12번 출구 인터체인지는 매우 혼잡해질 수 있어요.','interchange','B1','transport',2,'interchange highway junction aerial'),
('w_transport_B1_24','peak hour','/piːk ˌaʊər/','noun','피크 타임, 혼잡 시간대','The period of the day when most people are travelling.','Fares are higher during {peak hours}.','피크 시간대에는 요금이 더 높아요.','peak hours','B1','transport',2,'peak hour commute busy subway'),
('w_transport_B1_25','pedestrianize','/pɪˈdɛstriənaɪz/','verb','보행자 전용 구역으로 만들다','To make a street accessible only to people on foot.','The council voted to {pedestrianize} the high street.','의회는 중심가를 보행자 전용으로 만들기로 투표했어요.','pedestrianize','B1','transport',3,'pedestrian zone street no cars'),
('w_transport_B1_26','detour','/ˈdiːtʊr/','noun','우회','A longer route taken to avoid a problem on the usual road.','We had to take a {detour} due to road works.','도로 공사 때문에 우회해야 했어요.','detour','B1','transport',2,'detour sign road construction'),
('w_transport_B1_27','yield','/jiːld/','verb','양보하다','To give way to other traffic.','Always {yield} to pedestrians at crossings.','횡단보도에서는 항상 보행자에게 양보하세요.','yield','B1','transport',2,'yield sign road intersection'),
('w_transport_B1_28','carriage way','/ˈkærɪdʒweɪ/','noun','차도','The part of a road intended for vehicles.','Road works have reduced the {carriageway} to one lane.','도로 공사로 차도가 한 차선으로 줄었어요.','carriageway','B1','transport',3,'carriageway road vehicles lane'),
('w_transport_B1_29','sign post','/ˈsaɪnpoʊst/','noun','이정표','A post with signs on it showing directions or distances.','Follow the {signpost} to the city centre.','도심으로 가는 이정표를 따라가세요.','signpost','B1','transport',2,'signpost direction road countryside'),
('w_transport_B1_30','departure lounge','/dɪˈpɑːrtʃər laʊndʒ/','noun','출국 대기실','The area at an airport where passengers wait before boarding.','Please proceed to the {departure lounge}.','출국 대기실로 이동해 주세요.','departure lounge','B1','transport',2,'departure lounge airport waiting'),
('w_transport_B1_31','check-in','/ˈtʃɛkɪn/','noun','체크인','The process of registering for a flight at an airport.','Online {check-in} opens 24 hours before departure.','온라인 체크인은 출발 24시간 전에 열려요.','check-in','B1','transport',1,'check-in airport counter luggage'),
('w_transport_B1_32','seatbelt','/ˈsiːtbɛlt/','noun','안전벨트','A belt worn to keep you safely in your seat in a vehicle.','Please fasten your {seatbelt} before take-off.','이륙 전에 안전벨트를 매주세요.','seatbelt','B1','transport',1,'seatbelt safety car airplane'),
('w_transport_B1_33','harbour','/ˈhɑːrbər/','noun','항구','A place on the coast where ships shelter or load and unload.','The cruise ship docked at the main {harbour}.','크루즈 선박이 주요 항구에 정박했어요.','harbour','B1','transport',2,'harbour port ships dock'),
('w_transport_B1_34','motorway','/ˈmoʊtərweɪ/','noun','고속도로','A wide road designed for fast travel over long distances.','Take the {motorway} for a faster journey.','더 빠른 이동을 위해 고속도로를 이용하세요.','motorway','B1','transport',1,'motorway highway fast cars'),
('w_transport_B1_35','overhead bridge','/ˌoʊvərˈhɛd brɪdʒ/','noun','육교','A bridge built above a road for pedestrians.','Use the {overhead bridge} to cross safely.','안전하게 건너려면 육교를 이용하세요.','overhead bridge','B1','transport',2,'footbridge overpass pedestrian road')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — B2 (35개)
-- 테마: infrastructure, transit, logistics, navigate, detour, itinerary, chartered, shuttle, intercity, toll
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_transport_B2_01','infrastructure','/ˈɪnfrəˌstrʌktʃər/','noun','교통 기반 시설','The basic physical systems of a country, including roads, railways, and airports.','The government plans to invest heavily in transport {infrastructure}.','정부는 교통 기반 시설에 대규모 투자를 계획하고 있어요.','infrastructure','B2','transport',1,'infrastructure road bridge city construction'),
('w_transport_B2_02','transit','/ˈtrænsɪt/','noun','대중교통 시스템','Public transportation systems within a city or area.','The city''s rapid {transit} system carries millions of passengers daily.','그 도시의 고속 대중교통 시스템은 매일 수백만 명을 운송해요.','transit','B2','transport',1,'transit metro city public transport'),
('w_transport_B2_03','logistics','/ləˈdʒɪstɪks/','noun','물류','The detailed coordination of transporting goods or people.','Efficient {logistics} are crucial for same-day delivery.','효율적인 물류는 당일 배송에 필수적이에요.','logistics','B2','transport',1,'logistics warehouse delivery truck'),
('w_transport_B2_04','navigate','/ˈnævɪɡeɪt/','verb','항법으로 이동하다, 길을 찾다','To plan and direct the route of a vehicle or journey.','I used my phone to {navigate} through the city.','스마트폰으로 도시를 탐색했어요.','navigate','B2','transport',1,'navigate GPS map phone driving'),
('w_transport_B2_05','itinerary','/aɪˈtɪnərəri/','noun','여행 일정표','A planned route or schedule for a journey.','Our travel agent prepared a detailed {itinerary}.','여행사에서 상세한 일정표를 준비해 줬어요.','itinerary','B2','transport',1,'itinerary travel plan document'),
('w_transport_B2_06','chartered','/ˈtʃɑːrtərd/','adjective','전세 낸, 대절한','Hired for private use, not part of a regular service.','We booked a {chartered} flight for the corporate trip.','회사 출장을 위해 전세 비행기를 예약했어요.','chartered','B2','transport',2,'chartered plane private jet airport'),
('w_transport_B2_07','shuttle','/ˈʃʌtəl/','noun','셔틀 (정기 왕복 교통편)','A vehicle that travels regularly between two places.','Take the hotel {shuttle} from the airport arrivals hall.','공항 도착 홀에서 호텔 셔틀을 타세요.','shuttle','B2','transport',1,'shuttle bus airport hotel'),
('w_transport_B2_08','intercity','/ˌɪntərˈsɪti/','adjective','도시 간의','Travelling or operating between cities.','The {intercity} train service connects all major cities.','도시 간 기차 서비스는 모든 주요 도시를 연결해요.','intercity','B2','transport',1,'intercity train highspeed city'),
('w_transport_B2_09','toll','/toʊl/','noun','통행료','A charge paid to use a road, bridge, or tunnel.','There is a {toll} at every entrance to the highway.','고속도로 입구마다 통행료가 있어요.','toll','B2','transport',1,'toll booth highway road payment'),
('w_transport_B2_10','congestion charge','/kənˈdʒɛstʃən tʃɑːrdʒ/','noun','혼잡 통행료','A fee charged to drivers entering a busy urban area.','London introduced a daily {congestion charge} in 2003.','런던은 2003년에 일일 혼잡 통행료를 도입했어요.','congestion charge','B2','transport',2,'congestion charge sign city london'),
('w_transport_B2_11','embark','/ɪmˈbɑːrk/','verb','탑승하다, 승선하다','To go on board a ship or aircraft.','Passengers will {embark} from pier seven.','승객들은 7번 부두에서 승선해요.','embark','B2','transport',2,'embark ship dock boarding'),
('w_transport_B2_12','disembark','/ˌdɪsɪmˈbɑːrk/','verb','하선하다, 내리다','To leave a ship, aircraft, or other vehicle.','Please remain seated until the plane has {disembarked}.','비행기가 완전히 멈출 때까지 착석해 주세요.','disembarked','B2','transport',2,'disembark airplane gate passengers'),
('w_transport_B2_13','waybill','/ˈweɪbɪl/','noun','화물 운송장','A document listing the details of goods being transported.','The delivery driver presented a signed {waybill}.','배달 기사가 서명된 화물 운송장을 제시했어요.','waybill','B2','transport',3,'waybill document delivery logistics'),
('w_transport_B2_14','reroute','/ˌriːˈruːt/','verb','경로를 변경하다','To send something by a different route.','Due to flooding, all trains were {rerouted} via the northern line.','홍수로 인해 모든 기차가 북부 노선으로 우회했어요.','rerouted','B2','transport',2,'reroute train map alternative'),
('w_transport_B2_15','concourse','/ˈkɒnkɔːrs/','noun','중앙 홀, 광장','A large open area inside a station or airport where passengers gather.','Meet me in the main {concourse} of Grand Central.','그랜드 센트럴 중앙 홀에서 만나요.','concourse','B2','transport',2,'concourse station airport interior'),
('w_transport_B2_16','cargo','/ˈkɑːrɡoʊ/','noun','화물','Goods carried by a ship, aircraft, or other vehicle.','The airline charges extra for heavy {cargo}.','항공사는 무거운 화물에 추가 요금을 부과해요.','cargo','B2','transport',2,'cargo freight airplane warehouse'),
('w_transport_B2_17','overhead compartment','/ˌoʊvərˈhɛd kəmˈpɑːrtmənt/','noun','기내 선반','A storage area above seats in an aircraft.','Please stow your bag in the {overhead compartment}.','가방을 기내 선반에 넣어 주세요.','overhead compartment','B2','transport',2,'overhead compartment airplane interior'),
('w_transport_B2_18','grid','/ɡrɪd/','noun','도로 격자망','A network of lines crossing each other at right angles, as in a road system.','Chicago is famous for its straight-lined road {grid}.','시카고는 직선형 도로 격자망으로 유명해요.','grid','B2','transport',2,'grid road map aerial city'),
('w_transport_B2_19','accessible','/əkˈsɛsɪbəl/','adjective','접근 가능한, 장애인 편의시설 갖춘','Easy to use or enter, especially for people with disabilities.','All new stations must be fully {accessible}.','모든 새 역은 완전히 접근 가능해야 해요.','accessible','B2','transport',2,'accessible wheelchair ramp station'),
('w_transport_B2_20','hail','/heɪl/','verb','손을 흔들어 세우다 (택시 등)','To signal a passing taxi to stop.','I had to walk three blocks before I could {hail} a cab.','택시를 잡으려면 세 블록을 걸어야 했어요.','hail','B2','transport',2,'hail taxi cab street city'),
('w_transport_B2_21','streamline','/ˈstriːmlaɪn/','verb','효율화하다, 간소화하다','To make a process more efficient or simpler.','The airline is trying to {streamline} check-in procedures.','항공사는 체크인 절차를 간소화하려고 하고 있어요.','streamline','B2','transport',2,'streamline process efficiency workflow'),
('w_transport_B2_22','headway','/ˈhɛdweɪ/','noun','열차 간격, 배차 간격','The time interval between vehicles running on the same route.','The subway runs at a {headway} of four minutes.','지하철은 4분 간격으로 운행해요.','headway','B2','transport',3,'headway train frequency timetable'),
('w_transport_B2_23','freight','/freɪt/','noun','화물 운송','Goods transported in bulk by truck, train, or ship.','The port handles millions of tonnes of {freight} each year.','그 항구는 매년 수백만 톤의 화물을 처리해요.','freight','B2','transport',2,'freight port containers ship cargo'),
('w_transport_B2_24','suspension','/səˈspɛnʃən/','noun','운행 중단','The temporary stopping of a transport service.','A signal fault caused the {suspension} of all services.','신호 장애로 모든 노선 운행이 중단됐어요.','suspension','B2','transport',2,'suspension metro announcement board'),
('w_transport_B2_25','priority lane','/praɪˈɒrɪti leɪn/','noun','우선 차선','A lane reserved for buses, taxis, or emergency vehicles.','Buses run faster in the {priority lane}.','우선 차선에서는 버스가 더 빨리 달려요.','priority lane','B2','transport',2,'priority lane bus road marking'),
('w_transport_B2_26','capacity','/kəˈpæsɪti/','noun','수송 용량','The maximum number of people or things that a vehicle can carry.','The train was running at full {capacity}.','기차는 최대 용량으로 운행하고 있었어요.','capacity','B2','transport',2,'capacity crowd train metro'),
('w_transport_B2_27','interchange hub','/ˈɪntərˌtʃeɪndʒ hʌb/','noun','환승 허브','A major transport junction connecting multiple lines or modes of travel.','The new {interchange hub} will link the airport to the city.','새 환승 허브는 공항과 도시를 연결할 거예요.','interchange hub','B2','transport',2,'hub interchange transit center'),
('w_transport_B2_28','subsidy','/ˈsʌbsɪdi/','noun','보조금','Money given by the government to keep transport fares affordable.','Public buses receive a government {subsidy} to keep fares low.','공공 버스는 요금을 낮게 유지하기 위해 정부 보조금을 받아요.','subsidy','B2','transport',2,'subsidy government funding transport'),
('w_transport_B2_29','multimodal','/ˌmʌltiˈmoʊdəl/','adjective','복합 교통 수단의','Involving more than one form of transportation.','The city promotes a {multimodal} approach to commuting.','그 도시는 복합 교통 수단 방식의 통근을 장려해요.','multimodal','B2','transport',2,'multimodal transport bike train bus'),
('w_transport_B2_30','corridor','/ˈkɒrɪdɔːr/','noun','교통 회랑','A strip of land forming a route for transportation between two points.','The high-speed rail {corridor} links the two major cities.','고속철도 회랑은 두 주요 도시를 연결해요.','corridor','B2','transport',2,'corridor railway highway region map'),
('w_transport_B2_31','accessibility','/əkˌsɛsɪˈbɪlɪti/','noun','접근성','The quality of being easily reached or used by all people.','Improving {accessibility} for wheelchair users is a priority.','휠체어 사용자를 위한 접근성 향상이 우선 과제예요.','accessibility','B2','transport',2,'accessibility ramp disabled transport'),
('w_transport_B2_32','emission','/ɪˈmɪʃən/','noun','배기가스, 배출','The production and discharge of gas from a vehicle or engine.','Stricter {emission} standards apply to all new vehicles.','더 엄격한 배출 기준이 모든 신형 차량에 적용돼요.','emission','B2','transport',2,'emission exhaust car environment'),
('w_transport_B2_33','fleet','/fliːt/','noun','차량 군, 운송 차량단','A number of vehicles owned or operated by an organization.','The company is replacing its entire delivery {fleet} with electric vehicles.','그 회사는 배달 차량단 전체를 전기차로 교체하고 있어요.','fleet','B2','transport',2,'fleet trucks company delivery'),
('w_transport_B2_34','on-demand','/ˌɒn dɪˈmɑːnd/','adjective','수요 응답형의','Available whenever required, not on a fixed schedule.','The city introduced an {on-demand} bus service in rural areas.','그 도시는 농촌 지역에 수요 응답형 버스 서비스를 도입했어요.','on-demand','B2','transport',2,'on demand bus rural flexible'),
('w_transport_B2_35','manifest','/ˈmænɪfɛst/','noun','탑승자 명단, 적하 목록','A list of passengers or cargo on a vehicle.','The airline submitted the passenger {manifest} before takeoff.','항공사는 이륙 전에 탑승자 명단을 제출했어요.','manifest','B2','transport',3,'manifest airline document passengers')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — C1 (35개)
-- 테마: multimodal, intermodal, urban mobility, ridesharing, autonomous, sustainable transport, corridor, network, hubs, freight
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_transport_C1_01','intermodal','/ˌɪntərˈmoʊdəl/','adjective','상호 교통 수단 간의','Involving two or more modes of transport for a single journey.','The port operates an {intermodal} freight terminal.','그 항구는 상호 교통 수단 화물 터미널을 운영해요.','intermodal','C1','transport',2,'intermodal freight container ship train'),
('w_transport_C1_02','urban mobility','/ˈɜːrbən moʊˈbɪlɪti/','noun','도시 이동성','The systems and policies that enable people to move around cities.','Smart apps are transforming {urban mobility}.','스마트 앱이 도시 이동성을 혁신하고 있어요.','urban mobility','C1','transport',1,'urban mobility city scooter bike'),
('w_transport_C1_03','ridesharing','/ˈraɪdʃɛrɪŋ/','noun','승차 공유','A service where people share a vehicle for a journey, often arranged via an app.','The rise of {ridesharing} has reduced private car use.','승차 공유의 확산이 개인 자가용 이용을 줄였어요.','ridesharing','C1','transport',1,'ridesharing app uber lyft city'),
('w_transport_C1_04','autonomous','/ɔːˈtɒnəməs/','adjective','자율 주행의','Operating independently without human control.','The first {autonomous} buses completed trials last year.','최초의 자율 주행 버스가 작년에 시험 운행을 마쳤어요.','autonomous','C1','transport',1,'autonomous self-driving car sensor'),
('w_transport_C1_05','sustainable transport','/səˈsteɪnəbəl ˈtrænsport/','noun','지속 가능한 교통','Transportation that minimizes environmental impact.','Cycling is one of the most effective forms of {sustainable transport}.','자전거는 가장 효과적인 지속 가능한 교통 수단 중 하나예요.','sustainable transport','C1','transport',1,'sustainable transport green bike cycle'),
('w_transport_C1_06','network','/ˈnɛtwɜːrk/','noun','교통망','A system of routes, lines, or services connecting places.','The metro {network} expanded to cover the suburbs.','지하철 교통망이 교외 지역까지 확장됐어요.','network','C1','transport',1,'network metro map lines city'),
('w_transport_C1_07','hub','/hʌb/','noun','허브 (교통 중심지)','A central point from which routes radiate or where services connect.','Heathrow is one of Europe''s busiest aviation {hubs}.','히드로는 유럽에서 가장 바쁜 항공 허브 중 하나예요.','hubs','C1','transport',1,'hub airport transport center'),
('w_transport_C1_08','throughput','/ˈθruːpʊt/','noun','처리량, 수송 처리량','The amount of material or traffic passing through a system.','The new terminal increased passenger {throughput} by 40%.','새 터미널이 승객 처리량을 40% 늘렸어요.','throughput','C1','transport',2,'throughput airport terminal capacity'),
('w_transport_C1_09','electrification','/ɪˌlɛktrɪfɪˈkeɪʃən/','noun','전기화','The conversion of a railway or transport system to use electricity.','Rail {electrification} is central to the green transport strategy.','철도 전기화는 친환경 교통 전략의 핵심이에요.','electrification','C1','transport',1,'electrification railway overhead wire'),
('w_transport_C1_10','dwell time','/dwɛl taɪm/','noun','정차 시간','The time a vehicle spends stationary at a stop to allow passengers to board and alight.','Reducing {dwell time} is key to increasing train frequency.','정차 시간 단축이 열차 빈도를 높이는 핵심이에요.','dwell time','C1','transport',3,'dwell time train platform station'),
('w_transport_C1_11','hinterland','/ˈhɪntərlænd/','noun','배후지, 주변 지역','The areas surrounding and served by a port or city.','The new rail link opened up the port''s {hinterland}.','새 철도 연결로 항구의 배후지가 개방됐어요.','hinterland','C1','transport',3,'hinterland region port rural countryside'),
('w_transport_C1_12','transit-oriented development','/ˈtrænsɪt ˈɔːrientɪd dɪˈvɛləpmənt/','noun','대중교통 중심 개발','Urban planning that integrates housing and services around transport hubs.','The city adopted {transit-oriented development} near metro stations.','그 도시는 지하철역 주변에 대중교통 중심 개발을 채택했어요.','transit-oriented development','C1','transport',2,'transit development station urban planning'),
('w_transport_C1_13','feeder service','/ˈfiːdər ˌsɜːrvɪs/','noun','지선 서비스','A secondary transport service connecting smaller areas to a main line.','The town relies on a {feeder service} to reach the intercity station.','그 마을은 도시 간 역에 연결하는 지선 서비스에 의존해요.','feeder service','C1','transport',2,'feeder bus rural station connection'),
('w_transport_C1_14','modal split','/ˈmoʊdəl splɪt/','noun','교통 수단 분담률','The proportion of travel made by each transport mode.','The city aims to shift the {modal split} toward public transport.','그 도시는 교통 수단 분담률을 대중교통 쪽으로 전환하는 것을 목표로 해요.','modal split','C1','transport',2,'modal split graph transport statistics'),
('w_transport_C1_15','induced demand','/ɪnˈdjuːst dɪˈmɑːnd/','noun','유발 수요','The increase in traffic generated by adding road capacity.','Building more roads may create {induced demand} rather than reduce congestion.','도로를 더 짓는 것은 혼잡을 줄이는 게 아니라 유발 수요를 만들 수 있어요.','induced demand','C1','transport',3,'induced demand highway traffic growth'),
('w_transport_C1_16','right-of-way','/raɪt əv weɪ/','noun','통행 우선권','The legal right to pass through a particular road or path.','Emergency vehicles always have {right-of-way}.','응급 차량은 항상 통행 우선권을 가져요.','right-of-way','C1','transport',2,'right-of-way road priority sign'),
('w_transport_C1_17','viaduct','/ˈvaɪədʌkt/','noun','고가 교량','A long bridge carrying a road or railway across a valley.','The Victorian {viaduct} still carries express trains today.','빅토리아 시대의 고가 교량이 지금도 급행 기차를 운반해요.','viaduct','C1','transport',3,'viaduct bridge railway arch'),
('w_transport_C1_18','decarbonize','/diːˈkɑːrbənaɪz/','verb','탈탄소화하다','To remove or reduce carbon dioxide emissions from transport.','The sector must {decarbonize} rapidly to meet climate targets.','기후 목표를 달성하려면 그 분야가 빠르게 탈탄소화해야 해요.','decarbonize','C1','transport',1,'decarbonize green energy transport electric'),
('w_transport_C1_19','last-mile connectivity','/lɑːst maɪl kəˌnɛktɪˈvɪti/','noun','라스트 마일 연결성','The connection between a main transport hub and a passenger''s final destination.','Bike-sharing schemes improve {last-mile connectivity}.','공유 자전거 제도는 라스트 마일 연결성을 개선해요.','last-mile connectivity','C1','transport',2,'last mile bike scooter station'),
('w_transport_C1_20','grade separation','/ɡreɪd ˌsɛpəˈreɪʃən/','noun','입체 교차','The design of roads or railways so that they cross at different levels.','{Grade separation} eliminates level crossing collisions.','입체 교차는 건널목 충돌 사고를 없애요.','Grade separation','C1','transport',3,'grade separation overpass underpass engineering'),
('w_transport_C1_21','signal priority','/ˈsɪɡnəl praɪˈɒrɪti/','noun','신호 우선권','A system that gives buses or trams priority at traffic lights.','Trams benefit from {signal priority} on most routes.','전차는 대부분의 노선에서 신호 우선권의 혜택을 받아요.','signal priority','C1','transport',3,'signal priority tram traffic light'),
('w_transport_C1_22','zone pricing','/zoʊn ˈpraɪsɪŋ/','noun','구역별 요금제','A fare system where the cost depends on the number of zones crossed.','London''s Tube uses {zone pricing}.','런던 지하철은 구역별 요금제를 사용해요.','zone pricing','C1','transport',2,'zone pricing metro map fare'),
('w_transport_C1_23','operational resilience','/ˌɒpəˈreɪʃənəl rɪˈzɪliəns/','noun','운영 회복력','The ability of a transport system to keep running despite disruptions.','The network demonstrated strong {operational resilience} during the storm.','그 교통망은 폭풍 속에서도 강한 운영 회복력을 보였어요.','operational resilience','C1','transport',3,'resilience transport disruption system'),
('w_transport_C1_24','fleet management','/fliːt ˈmænɪdʒmənt/','noun','차량 관리','The administration of a company''s vehicles to maximize efficiency.','GPS tracking has revolutionized {fleet management}.','GPS 추적이 차량 관리에 혁신을 가져왔어요.','fleet management','C1','transport',2,'fleet management GPS truck logistics'),
('w_transport_C1_25','demand forecasting','/dɪˈmɑːnd ˈfɔːrkæstɪŋ/','noun','수요 예측','Predicting how much transport capacity will be needed in the future.','Accurate {demand forecasting} prevents overcrowding on trains.','정확한 수요 예측이 기차 내 혼잡을 예방해요.','demand forecasting','C1','transport',3,'demand forecasting data analytics'),
('w_transport_C1_26','rolling stock','/ˈroʊlɪŋ stɒk/','noun','철도 차량','The locomotives, carriages, and wagons used on a railway.','The operator is replacing its ageing {rolling stock}.','운영사는 노후화된 철도 차량을 교체하고 있어요.','rolling stock','C1','transport',2,'rolling stock train carriage depot'),
('w_transport_C1_27','transit pass','/ˈtrænsɪt pæs/','noun','정기 교통권','A card or pass allowing unlimited travel on public transport for a set period.','Monthly {transit passes} are cheaper than individual tickets.','월정 정기 교통권은 낱장 티켓보다 저렴해요.','transit passes','C1','transport',2,'transit pass card monthly travel'),
('w_transport_C1_28','trackwork','/ˈtræk wɜːrk/','noun','선로 공사','Maintenance or construction work carried out on railway tracks.','Weekend {trackwork} will suspend services on line 3.','주말 선로 공사로 3호선 운행이 중단돼요.','trackwork','C1','transport',2,'trackwork railway maintenance workers'),
('w_transport_C1_29','interoperability','/ˌɪntərˌɒpərəˈbɪlɪti/','noun','상호 운용성','The ability of different transport systems or tickets to work together.','{Interoperability} allows passengers to use one card across all networks.','상호 운용성 덕분에 승객들은 모든 교통망에서 하나의 카드를 사용할 수 있어요.','Interoperability','C1','transport',3,'interoperability smart card transport system'),
('w_transport_C1_30','paratransit','/ˈpærəˌtrænsɪt/','noun','특별 수송 서비스','Flexible transport services for people who cannot use regular public transport.','The city expanded its {paratransit} fleet for elderly riders.','그 도시는 노인 이용자를 위해 특별 수송 서비스 차량을 늘렸어요.','paratransit','C1','transport',3,'paratransit wheelchair van accessible'),
('w_transport_C1_31','modal shift','/ˈmoʊdəl ʃɪft/','noun','교통 수단 전환','A change in the proportion of travel by different modes of transport.','Policy makers are encouraging a {modal shift} away from private cars.','정책 입안자들은 개인 자가용에서 벗어난 교통 수단 전환을 장려하고 있어요.','modal shift','C1','transport',2,'modal shift bike transit car green'),
('w_transport_C1_32','overshoot','/ˌoʊvərˈʃuːt/','verb','초과하다 (정원, 시간 등)','To go beyond a planned stop or time.','The tram {overshot} the platform by several metres.','전차가 플랫폼을 몇 미터 지나쳤어요.','overshot','C1','transport',3,'overshoot platform tram precision'),
('w_transport_C1_33','interline agreement','/ˈɪntəlaɪn əˈɡriːmənt/','noun','항공사 간 연계 협정','An agreement between airlines to accept each other''s tickets.','Thanks to the {interline agreement}, you can check your bag to the final destination.','항공사 간 연계 협정 덕분에 최종 목적지까지 수하물을 위탁할 수 있어요.','interline agreement','C1','transport',3,'interline airline ticket agreement'),
('w_transport_C1_34','signalling system','/ˈsɪɡnəlɪŋ ˌsɪstəm/','noun','신호 시스템','The electronic system that controls the safe movement of trains.','An upgraded {signalling system} will double capacity on the line.','업그레이드된 신호 시스템이 노선 용량을 두 배로 늘릴 거예요.','signalling system','C1','transport',2,'signalling system railway control room'),
('w_transport_C1_35','curbside management','/ˈkɜːrbsaɪd ˈmænɪdʒmənt/','noun','도로변 관리','The regulation of loading, unloading, and passenger pick-up zones.','Effective {curbside management} reduces double-parking downtown.','효과적인 도로변 관리는 도심의 이중 주차를 줄여요.','curbside management','C1','transport',3,'curbside curb pickup zone parking')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — C2 (35개)
-- 테마: telematics, decarbonization, electrification, micromobility, modal shift, last-mile, hyperloop, geospatial, actuarial
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_transport_C2_01','telematics','/ˌtɛlɪˈmætɪks/','noun','텔레매틱스','The technology of sending, receiving, and storing information about vehicles via telecommunications.','Insurance companies use {telematics} to calculate premiums based on driving behaviour.','보험사는 텔레매틱스를 사용해 운전 습관에 따라 보험료를 산정해요.','telematics','C2','transport',2,'telematics GPS car data technology'),
('w_transport_C2_02','decarbonization','/diːˌkɑːrbənaɪˈzeɪʃən/','noun','탈탄소화','The process of reducing carbon dioxide emissions from transport systems.','The {decarbonization} of aviation presents unique engineering challenges.','항공의 탈탄소화는 독특한 공학적 도전을 제시해요.','decarbonization','C2','transport',1,'decarbonization green energy clean transport'),
('w_transport_C2_03','micromobility','/ˌmaɪkroʊmoʊˈbɪlɪti/','noun','마이크로 모빌리티','Small, lightweight vehicles such as e-scooters and bicycles for short urban trips.','Cities are redesigning streets to accommodate {micromobility}.','도시들은 마이크로 모빌리티를 수용하기 위해 거리를 재설계하고 있어요.','micromobility','C2','transport',1,'micromobility scooter e-bike city street'),
('w_transport_C2_04','hyperloop','/ˈhaɪpərluːp/','noun','하이퍼루프','A proposed high-speed transport system using sealed tubes with low air pressure.','The {hyperloop} could reduce travel time between cities from hours to minutes.','하이퍼루프는 도시 간 이동 시간을 몇 시간에서 몇 분으로 줄일 수 있어요.','hyperloop','C2','transport',2,'hyperloop tube futuristic transport'),
('w_transport_C2_05','geospatial analysis','/ˌdʒiːoʊˈspeɪʃəl əˈnæləsɪs/','noun','지리 공간 분석','The use of geographic data to optimize transport routes and planning.','Transport planners use {geospatial analysis} to identify underserved areas.','교통 계획가들은 지리 공간 분석을 사용해 서비스 취약 지역을 파악해요.','geospatial analysis','C2','transport',3,'geospatial map data urban analysis'),
('w_transport_C2_06','actuarial modelling','/ˌæktʃuˈɛriəl ˈmɒdəlɪŋ/','noun','보험 수리 모델링','Statistical models used to calculate insurance risk for transport.','{Actuarial modelling} is used to price ride-share insurance products.','보험 수리 모델링은 승차 공유 보험 상품 가격 산정에 사용돼요.','Actuarial modelling','C2','transport',3,'actuarial data statistics insurance'),
('w_transport_C2_07','vehicle-to-grid','/ˈviːɪkəl tə ɡrɪd/','noun','차량 대 전력망','A system where electric vehicles can return stored energy to the power grid.','The city is piloting a {vehicle-to-grid} scheme using electric buses.','그 도시는 전기버스를 이용한 차량 대 전력망 시범 사업을 추진하고 있어요.','vehicle-to-grid','C2','transport',3,'vehicle grid electric energy storage'),
('w_transport_C2_08','congestion pricing','/kənˈdʒɛstʃən ˈpraɪsɪŋ/','noun','혼잡 통행료 제도','A demand management policy that charges drivers more during peak hours.','New York implemented {congestion pricing} to fund the subway.','뉴욕은 지하철 재원 마련을 위해 혼잡 통행료 제도를 시행했어요.','congestion pricing','C2','transport',2,'congestion pricing manhattan toll road'),
('w_transport_C2_09','externality','/ˌɛkstɜːrˈnælɪti/','noun','외부 효과 (교통)','Costs or benefits of transport that affect people not directly involved, such as pollution.','The social {externalities} of car use include air pollution and noise.','자동차 이용의 사회적 외부 효과에는 대기 오염과 소음이 포함돼요.','externalities','C2','transport',3,'externality pollution noise city economics'),
('w_transport_C2_10','autonomous vehicle liability','/ɔːˈtɒnəməs ˈviːɪkəl laɪəˈbɪlɪti/','noun','자율 주행 차량 책임','Legal responsibility for accidents caused by self-driving vehicles.','Courts are still debating {autonomous vehicle liability} frameworks.','법원은 아직 자율 주행 차량 책임 프레임워크에 대해 논의 중이에요.','autonomous vehicle liability','C2','transport',3,'autonomous liability legal self-driving law'),
('w_transport_C2_11','propulsion technology','/prəˈpʌlʃən tɛkˈnɒlədʒi/','noun','추진 기술','The engineering systems used to drive vehicles forward.','Hydrogen fuel cells are emerging as a viable {propulsion technology}.','수소 연료 전지가 실행 가능한 추진 기술로 떠오르고 있어요.','propulsion technology','C2','transport',2,'propulsion hydrogen fuel cell vehicle'),
('w_transport_C2_12','smart motorway','/smɑːrt ˈmoʊtərweɪ/','noun','스마트 고속도로','A motorway with technology to manage traffic flow and use the hard shoulder as an extra lane.','{Smart motorway} signs display dynamic speed limits.','스마트 고속도로 표지판은 동적 제한 속도를 표시해요.','smart motorway','C2','transport',2,'smart motorway dynamic sign gantry'),
('w_transport_C2_13','infrastructure deficit','/ˈɪnfrəˌstrʌktʃər ˈdɛfɪsɪt/','noun','기반 시설 부족','A gap between existing transport infrastructure and what is needed.','The region faces a significant transport {infrastructure deficit}.','그 지역은 심각한 교통 기반 시설 부족에 직면해 있어요.','infrastructure deficit','C2','transport',3,'infrastructure deficit rural road old'),
('w_transport_C2_14','MAAS (mobility as a service)','/mæs/','noun','서비스형 모빌리티','A transport model integrating various modes into a single accessible service.','{MaaS} platforms let users plan, book, and pay for all transport in one app.','서비스형 모빌리티 플랫폼은 사용자가 모든 교통을 하나의 앱으로 계획, 예약, 결제할 수 있게 해요.','MaaS','C2','transport',2,'maas mobility app smartphone transport'),
('w_transport_C2_15','regulatory sandbox','/ˈreɡjələtɔːri ˈsændbɒks/','noun','규제 샌드박스','A controlled environment where new transport technologies can be tested without normal regulations.','The government created a {regulatory sandbox} for autonomous vehicles.','정부는 자율 주행 차량을 위한 규제 샌드박스를 만들었어요.','regulatory sandbox','C2','transport',3,'regulatory sandbox innovation pilot'),
('w_transport_C2_16','energy density','/ˈɛnərʤi ˈdɛnsɪti/','noun','에너지 밀도','The amount of energy stored per unit volume in a battery or fuel.','The low {energy density} of current batteries limits electric aircraft range.','현재 배터리의 낮은 에너지 밀도는 전기 항공기 항속 거리를 제한해요.','energy density','C2','transport',3,'energy density battery electric vehicle'),
('w_transport_C2_17','catenation','/ˌkætɪˈneɪʃən/','noun','연장 운행','The practice of linking carriages or trams together for longer trains.','{Catenation} allows the operator to run twelve-carriage trains during peak hours.','연장 운행을 통해 운영사는 피크 시간대에 12량 기차를 운행할 수 있어요.','Catenation','C2','transport',3,'long train carriage platform capacity'),
('w_transport_C2_18','carbon offset','/ˈkɑːrbən ˌɒfset/','noun','탄소 상쇄','A compensatory measure for carbon emissions from transport.','Airlines offer passengers the option to purchase {carbon offsets}.','항공사는 승객들에게 탄소 상쇄권 구매 옵션을 제공해요.','carbon offsets','C2','transport',2,'carbon offset tree forest green'),
('w_transport_C2_19','freight modal split','/freɪt ˈmoʊdəl splɪt/','noun','화물 교통 분담률','The proportion of freight carried by road, rail, sea, and air.','Shifting the {freight modal split} toward rail reduces emissions.','화물 교통 분담률을 철도 쪽으로 전환하면 배출이 줄어요.','freight modal split','C2','transport',3,'freight train truck comparison'),
('w_transport_C2_20','connected vehicle','/kəˈnɛktɪd ˈviːɪkəl/','noun','커넥티드 카','A vehicle that uses internet connectivity to communicate with other vehicles and infrastructure.','A {connected vehicle} can warn drivers of hazards ahead.','커넥티드 카는 운전자에게 전방 위험을 경고할 수 있어요.','connected vehicle','C2','transport',2,'connected vehicle internet smart car'),
('w_transport_C2_21','land use integration','/lænd juːz ˌɪntɪˈɡreɪʃən/','noun','토지 이용 통합','The coordination of transport planning with land use to reduce travel demand.','{Land use integration} reduces the need for long commutes.','토지 이용 통합은 장거리 통근의 필요성을 줄여요.','land use integration','C2','transport',3,'land use planning urban map'),
('w_transport_C2_22','value of time','/ˈvæljuː əv taɪm/','noun','시간 가치 (교통 경제)','An economic measure of how much people value saving travel time.','The {value of time} influences decisions about high-speed rail investment.','시간 가치는 고속철도 투자 결정에 영향을 미쳐요.','value of time','C2','transport',3,'value time economics graph'),
('w_transport_C2_23','peak spreading','/piːk ˈsprɛdɪŋ/','noun','피크 분산','The effect of encouraging travellers to shift journeys away from the busiest times.','Flexible working hours facilitate {peak spreading} on the network.','유연 근무제는 교통망의 피크 분산을 촉진해요.','peak spreading','C2','transport',3,'peak spreading commute flexible hours'),
('w_transport_C2_24','infrastructure bond','/ˈɪnfrəˌstrʌktʃər bɒnd/','noun','인프라 채권','A financial instrument issued to fund transport projects.','The government issued {infrastructure bonds} to finance the new rail line.','정부는 새 철도 노선 건설 자금을 위해 인프라 채권을 발행했어요.','infrastructure bonds','C2','transport',3,'infrastructure bond finance investment'),
('w_transport_C2_25','induced traffic','/ɪnˈdjuːst ˈtræfɪk/','noun','유발 교통량','Additional vehicle traffic created by new road capacity.','Highway expansion often generates {induced traffic} that fills the new lanes.','고속도로 확장은 새 차선을 채우는 유발 교통량을 흔히 만들어요.','induced traffic','C2','transport',3,'induced traffic highway cars congestion'),
('w_transport_C2_26','platooning','/ˈplætuːnɪŋ/','noun','플래투닝 (군집 주행)','The practice of closely grouping vehicles so they travel together as a convoy.','Truck {platooning} can reduce fuel consumption by up to 15%.','트럭 군집 주행은 연료 소비를 최대 15%까지 줄일 수 있어요.','platooning','C2','transport',3,'platooning truck convoy highway'),
('w_transport_C2_27','stochastic demand','/stəˈkæstɪk dɪˈmɑːnd/','noun','확률적 수요','Random variation in transport demand that cannot be precisely predicted.','Operators use modelling to manage {stochastic demand} during events.','운영사는 행사 중 확률적 수요를 관리하기 위해 모델링을 사용해요.','stochastic demand','C2','transport',3,'stochastic demand statistics modelling'),
('w_transport_C2_28','electrolysis','/ɪˈlɛktrɒlɪsɪs/','noun','전기 분해 (수소 생산)','A process using electricity to split water into hydrogen and oxygen for fuel.','Green hydrogen produced by {electrolysis} could power future trains.','전기 분해로 생산된 그린 수소가 미래의 기차를 구동할 수 있어요.','electrolysis','C2','transport',3,'electrolysis hydrogen green energy'),
('w_transport_C2_29','right-of-way acquisition','/raɪt əv weɪ ˌækwɪˈzɪʃən/','noun','용지 취득','The legal process of obtaining land for new transport infrastructure.','Delays in {right-of-way acquisition} pushed back the project timeline.','용지 취득 지연이 프로젝트 일정을 늦췄어요.','right-of-way acquisition','C2','transport',3,'right-of-way land acquisition construction'),
('w_transport_C2_30','operational expenditure','/ˌɒpəˈreɪʃənəl ɪkˈspɛndɪtʃər/','noun','운영 비용','The ongoing costs required to run a transport service.','Rising energy prices have increased {operational expenditure} for train operators.','에너지 가격 상승으로 기차 운영사의 운영 비용이 늘었어요.','operational expenditure','C2','transport',3,'operational expenditure budget finance rail'),
('w_transport_C2_31','catenary','/ˈkætənɛri/','noun','가선 (전차선)','The overhead wire system that supplies electricity to electric trains and trams.','Strong winds damaged the {catenary} and disrupted services.','강풍으로 가선이 손상돼 서비스가 중단됐어요.','catenary','C2','transport',3,'catenary wire overhead railway electric'),
('w_transport_C2_32','modal integration','/ˈmoʊdəl ˌɪntɪˈɡreɪʃən/','noun','교통 수단 통합','The seamless connection between different transport modes for passengers.','The station redesign achieved full {modal integration} between rail and bus.','역 재설계로 철도와 버스 간의 완전한 교통 수단 통합을 이뤘어요.','modal integration','C2','transport',2,'modal integration station bus train'),
('w_transport_C2_33','transport poverty','/ˈtrænsport ˈpɒvərti/','noun','교통 빈곤','The inability to access transport due to cost, availability, or physical barriers.','Rural communities suffer most from {transport poverty}.','농촌 지역 사회가 교통 빈곤으로 가장 많은 어려움을 겪어요.','transport poverty','C2','transport',2,'transport poverty rural isolation'),
('w_transport_C2_34','waypoint','/ˈweɪpɔɪnt/','noun','경유 지점','An intermediate stop or location on a planned route.','The drone delivery system uses GPS {waypoints} to navigate.','드론 배송 시스템은 GPS 경유 지점을 사용해 항법 운행해요.','waypoints','C2','transport',2,'waypoint GPS route navigation drone'),
('w_transport_C2_35','service resilience','/ˈsɜːrvɪs rɪˈzɪliəns/','noun','서비스 회복 탄력성','The capability of a transport service to recover quickly from disruptions.','Investing in redundancy improves {service resilience} during extreme weather.','중복 시스템에 투자하면 극한 날씨 중 서비스 회복 탄력성이 향상돼요.','service resilience','C2','transport',3,'resilience transport weather disruption')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — A1 (7개) : 위치 묻기
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_transport_A1_01','Where is the bus stop?','버스 정류장이 어디예요?','bus stop','"Where is...?" 패턴은 장소를 물을 때 가장 기본적인 표현이에요.','길 찾기','A1','transport','pattern',NULL,1),
('s_transport_A1_02','How do I get to the train station?','기차역에 어떻게 가나요?','How do I get to','"How do I get to...?"는 목적지까지의 방법을 물을 때 쓰는 핵심 표현이에요.','길 찾기','A1','transport','pattern',NULL,2),
('s_transport_A1_03','Is the airport far from here?','공항이 여기서 멀어요?','far from here','"Is... far from here?"로 거리를 확인할 수 있어요.','거리 확인','A1','transport','pattern',NULL,3),
('s_transport_A1_04','Which bus goes to the city centre?','시내 중심까지 몇 번 버스가 가나요?','Which bus goes to','"Which bus goes to...?"는 올바른 버스 노선을 찾을 때 쓰는 표현이에요.','버스 노선 확인','A1','transport','pattern',NULL,4),
('s_transport_A1_05','Turn left at the traffic light.','신호등에서 왼쪽으로 도세요.','Turn left at','"Turn left/right at..."는 방향을 안내할 때 가장 기본적인 표현이에요.','길 안내','A1','transport','pattern',NULL,5),
('s_transport_A1_06','Go straight and then turn right.','직진 후에 오른쪽으로 도세요.','Go straight and then','두 단계 방향을 "and then"으로 자연스럽게 연결할 수 있어요.','길 안내','A1','transport','pattern',NULL,6),
('s_transport_A1_07','Excuse me, can you show me the way to the subway?','실례합니다, 지하철 가는 길을 알려주실 수 있나요?','can you show me the way','"Can you show me the way to...?"는 정중하게 길을 물어볼 때 쓰는 표현이에요.','도움 요청','A1','transport','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — A2 (7개) : 티켓 구매, 환승
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_transport_A2_01','I''d like a single ticket to Busan, please.','부산까지 편도 표 한 장 주세요.','I''d like a single ticket','"I''d like a... ticket to..."는 티켓 구매 시 가장 많이 쓰이는 문형이에요.','티켓 구매','A2','transport','pattern',NULL,1),
('s_transport_A2_02','How much is the fare to the airport?','공항까지 요금이 얼마예요?','How much is the fare','"How much is the fare to...?"로 요금을 정중하게 물어볼 수 있어요.','요금 문의','A2','transport','pattern',NULL,2),
('s_transport_A2_03','Do I need to transfer to get to Gangnam?','강남까지 가려면 환승해야 하나요?','Do I need to transfer','"Do I need to transfer?"는 환승 여부를 확인할 때 유용한 표현이에요.','환승 문의','A2','transport','pattern',NULL,3),
('s_transport_A2_04','Where do I transfer for the red line?','빨간 노선으로 환승하려면 어디서 갈아타나요?','Where do I transfer for','"Where do I transfer for...?"는 환승 위치를 물을 때 쓰는 표현이에요.','환승 위치','A2','transport','pattern',NULL,4),
('s_transport_A2_05','Is there a discount for students?','학생 할인이 있나요?','Is there a discount for','"Is there a discount for...?"는 할인 여부를 물어보는 자연스러운 표현이에요.','할인 문의','A2','transport','pattern',NULL,5),
('s_transport_A2_06','What time is the next train to Seoul?','다음 서울행 기차는 몇 시예요?','What time is the next train','"What time is the next...?"는 다음 교통편 시간을 물을 때 필수 표현이에요.','출발 시간 확인','A2','transport','pattern',NULL,6),
('s_transport_A2_07','Can I use this card to pay for the bus?','이 카드로 버스 요금을 낼 수 있나요?','Can I use this card to pay','"Can I use... to pay?"는 결제 수단을 확인할 때 쓰는 실용적인 표현이에요.','결제 방법','A2','transport','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — B1 (7개) : 길 안내, 늦음
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_transport_B1_01','I''m sorry, I''m going to be a bit late — there''s heavy traffic on the motorway.','죄송해요, 고속도로에 차가 막혀서 조금 늦을 것 같아요.','I''m going to be a bit late','늦을 것 같을 때 이유와 함께 미리 알려주는 게 예의 바른 표현이에요.','지각 예고','B1','transport','pattern',NULL,1),
('s_transport_B1_02','Could you take the main road instead of the highway? It might be quicker.','고속도로 대신 일반 도로로 가주실 수 있나요? 더 빠를 수 있어요.','instead of the highway','"instead of"를 사용하면 대안 경로를 부드럽게 제안할 수 있어요.','경로 제안','B1','transport','pattern',NULL,2),
('s_transport_B1_03','The commute is really getting to me — I spend nearly two hours on the train every day.','통근이 정말 힘들어요 — 매일 기차에서 거의 두 시간을 보내거든요.','getting to me','"Getting to me"는 무언가가 점점 부담이 된다는 뉘앙스를 전달해요.','통근 불만','B1','transport','pattern',NULL,3),
('s_transport_B1_04','I usually carpool with two colleagues to save on fuel costs.','연료비를 아끼려고 동료 두 명과 카풀을 해요.','carpool with... to save on','"carpool with... to save on..."은 카풀 이유를 설명하는 자연스러운 패턴이에요.','카풀 설명','B1','transport','pattern',NULL,4),
('s_transport_B1_05','There are roadworks on the bridge, so we had to take a detour through the town.','다리에 도로 공사가 있어서 마을을 통해 우회해야 했어요.','take a detour through','"take a detour through..."는 우회 경로를 설명할 때 쓰는 표현이에요.','경로 변경 설명','B1','transport','pattern',NULL,5),
('s_transport_B1_06','Is there a more direct route, or do we have to go through the tunnel?','더 직접적인 경로가 있나요, 아니면 터널을 통해야 하나요?','a more direct route','"a more direct route"는 더 효율적인 경로를 물어볼 때 쓰는 표현이에요.','경로 문의','B1','transport','pattern',NULL,6),
('s_transport_B1_07','Watch out — there''s a speed camera just after the junction ahead.','주의하세요 — 바로 앞 교차로 지나서 과속 카메라가 있어요.','Watch out','"Watch out"은 즉각적인 경고를 전달할 때 쓰는 자연스러운 표현이에요.','도로 경고','B1','transport','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — B2 (7개) : 교통 상황
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_transport_B2_01','The congestion on this corridor has reached a critical point and something has to be done.','이 교통 회랑의 혼잡이 임계점에 달했으며 조치가 필요해요.','reached a critical point','"reached a critical point"는 문제가 심각해졌음을 강조하는 표현이에요.','교통 상황 분석','B2','transport','pattern',NULL,1),
('s_transport_B2_02','The delay was caused by an overhead line failure, which disrupted services across the entire network.','지연은 가선 고장으로 발생했으며 전체 교통망에 걸쳐 서비스가 중단됐어요.','overhead line failure','교통 장애를 공식적으로 설명할 때 수동태 구문을 자주 사용해요.','장애 설명','B2','transport','pattern',NULL,2),
('s_transport_B2_03','Despite the disruption, alternative shuttle services were put in place within the hour.','서비스 중단에도 불구하고 한 시간 안에 대체 셔틀 서비스가 마련됐어요.','were put in place within','"put in place"는 대책이 시행됐음을 설명하는 격식체 표현이에요.','대응 조치','B2','transport','pattern',NULL,3),
('s_transport_B2_04','The introduction of congestion charges has significantly reduced traffic in the city centre.','혼잡 통행료 도입이 도심의 교통량을 크게 줄였어요.','significantly reduced traffic','"significantly reduced"는 데이터나 결과를 제시할 때 쓰는 격식체 표현이에요.','정책 효과','B2','transport','pattern',NULL,4),
('s_transport_B2_05','I missed my connecting flight because the first leg arrived over an hour behind schedule.','첫 번째 구간이 예정보다 한 시간 이상 늦게 도착해서 연결 비행편을 놓쳤어요.','behind schedule','"behind schedule"은 지연을 나타내는 격식 있는 표현이에요.','항공 지연','B2','transport','pattern',NULL,5),
('s_transport_B2_06','The infrastructure upgrade will require significant capital investment spread over five years.','기반 시설 업그레이드는 5년에 걸친 상당한 자본 투자가 필요해요.','significant capital investment spread over','"spread over"는 투자나 비용이 기간 전체에 분산됨을 설명해요.','인프라 투자','B2','transport','pattern',NULL,6),
('s_transport_B2_07','Passengers are advised to allow extra travel time due to planned engineering works this weekend.','이번 주말 예정된 공사로 인해 승객들은 여유 있는 이동 시간을 감안하시기 바랍니다.','are advised to allow extra travel time','"are advised to"는 공식 안내문에서 권고 사항을 전달하는 표현이에요.','공식 안내','B2','transport','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — C1 (7개) : 교통 정책, 도시 계획
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_transport_C1_01','A shift toward sustainable transport modes requires not only infrastructure investment but also a fundamental change in commuter behaviour.','지속 가능한 교통 수단으로의 전환은 기반 시설 투자뿐 아니라 통근자 행동의 근본적인 변화도 필요로 해요.','not only... but also a fundamental change','"not only... but also"는 두 가지 조건을 동시에 강조할 때 쓰는 격식체 구문이에요.','교통 정책 토론','C1','transport','pattern',NULL,1),
('s_transport_C1_02','Transit-oriented development has proven effective in cities that have aligned planning decisions with public transport corridors.','대중교통 회랑과 도시 계획 결정을 연계한 도시에서 대중교통 중심 개발이 효과적인 것으로 입증됐어요.','has proven effective in cities that have aligned','"has proven effective"는 정책 효과를 학술적으로 제시하는 표현이에요.','도시 계획 분석','C1','transport','pattern',NULL,2),
('s_transport_C1_03','The challenge lies in achieving modal shift without disproportionately burdening lower-income households.','교통 수단 전환을 달성하면서 저소득 가구에 과도한 부담을 주지 않는 것이 과제예요.','without disproportionately burdening','"without disproportionately burdening"은 형평성 문제를 언급할 때 쓰는 학술적 표현이에요.','교통 형평성','C1','transport','pattern',NULL,3),
('s_transport_C1_04','Electrification of the rail network is central to the government''s strategy for decarbonizing the transport sector.','철도 네트워크 전기화는 교통 부문 탈탄소화를 위한 정부 전략의 핵심이에요.','central to the government''s strategy for','"central to"는 어떤 것이 전략의 핵심임을 나타내는 격식체 표현이에요.','탈탄소 정책','C1','transport','pattern',NULL,4),
('s_transport_C1_05','Autonomous vehicles hold considerable promise, but regulatory frameworks have yet to keep pace with technological development.','자율 주행 차량은 상당한 가능성을 지니고 있지만, 규제 프레임워크는 아직 기술 발전을 따라가지 못하고 있어요.','have yet to keep pace with','"have yet to keep pace with"는 기술과 규제의 간극을 설명하는 고급 표현이에요.','정책 논의','C1','transport','pattern',NULL,5),
('s_transport_C1_06','Improving last-mile connectivity is critical if public transport is to compete effectively with the private car.','라스트 마일 연결성 향상은 대중교통이 자가용과 효과적으로 경쟁하려면 필수적이에요.','is critical if... is to compete effectively','"is to + 동사원형"은 조건부 미래 의무를 나타내는 격식체 구조예요.','경쟁력 분석','C1','transport','pattern',NULL,6),
('s_transport_C1_07','Ridesharing platforms have disrupted traditional taxi markets, compelling regulators to revisit licensing frameworks.','승차 공유 플랫폼이 기존 택시 시장을 혼란에 빠뜨려 규제 당국이 면허 프레임워크를 재검토하도록 압박했어요.','compelling regulators to revisit','"compelling... to"는 어떤 결과가 다른 행위를 강제했음을 나타내는 분사 구문이에요.','플랫폼 규제','C1','transport','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — C2 (7개) : 교통 정책, 도시 계획 (심화)
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_transport_C2_01','The externalities associated with private car use — including congestion, pollution, and noise — are rarely captured in market prices, necessitating corrective policy intervention.','개인 자가용 이용과 관련된 외부 효과(혼잡, 오염, 소음 포함)는 시장 가격에 반영되는 경우가 드물어 교정적 정책 개입이 필요해요.','necessitating corrective policy intervention','분사 구문을 활용해 결과와 당위성을 압축적으로 표현하는 고급 학술 문체예요.','교통 경제학','C2','transport','pattern',NULL,1),
('s_transport_C2_02','Decarbonizing aviation at scale will require breakthroughs in propulsion technology, given that the energy density of current battery systems remains insufficient for long-haul flight.','장거리 비행에 현재 배터리 시스템의 에너지 밀도가 아직 부족하다는 점을 감안할 때, 대규모 항공 탈탄소화는 추진 기술의 혁신이 필요해요.','given that the energy density... remains insufficient','"given that"은 전제 조건을 제시하며 논거를 전개하는 학술적 표현이에요.','항공 탈탄소','C2','transport','pattern',NULL,2),
('s_transport_C2_03','The proliferation of micromobility services demands a rethinking of curbside management and urban streetscape design.','마이크로 모빌리티 서비스의 확산은 도로변 관리와 도시 가로경관 설계의 재고를 요구해요.','demands a rethinking of','"demands a rethinking of"는 패러다임 변화를 촉구하는 논설문에서 자주 쓰이는 표현이에요.','도시 설계','C2','transport','pattern',NULL,3),
('s_transport_C2_04','Realizing the potential of hyperloop technology hinges on resolving both the engineering and the regulatory challenges that currently impede deployment.','하이퍼루프 기술의 잠재력을 실현하는 것은 현재 도입을 방해하는 공학적 과제와 규제적 과제 모두를 해결하는 데 달려 있어요.','hinges on resolving both... and','"hinges on"은 성공이 특정 조건에 달려 있음을 강조하는 격식체 표현이에요.','첨단 교통','C2','transport','pattern',NULL,4),
('s_transport_C2_05','Telematics data, when coupled with geospatial analysis, enables transport authorities to allocate resources with unprecedented precision.','텔레매틱스 데이터는 지리 공간 분석과 결합될 때 교통 당국이 전례 없는 정밀도로 자원을 배분할 수 있게 해요.','when coupled with... enables... to allocate','"when coupled with"는 두 기술이나 방법의 시너지를 설명하는 고급 표현이에요.','데이터 활용','C2','transport','pattern',NULL,5),
('s_transport_C2_06','Transport poverty, often overlooked in urban policy discourse, disproportionately affects peripheral communities with limited access to employment and services.','교통 빈곤은 도시 정책 담론에서 종종 간과되지만, 취업과 서비스 접근이 제한된 주변 지역 사회에 불균형적인 영향을 미쳐요.','disproportionately affects peripheral communities','"disproportionately affects"는 불균형한 영향을 지적할 때 쓰는 학술적 표현이에요.','사회적 형평성','C2','transport','pattern',NULL,6),
('s_transport_C2_07','A comprehensive Mobility as a Service ecosystem presupposes interoperability across competing platforms, a condition that market forces alone are unlikely to deliver without regulatory mandates.','포괄적인 서비스형 모빌리티 생태계는 경쟁 플랫폼 간의 상호 운용성을 전제로 하며, 이는 규제 의무 없이는 시장의 힘만으로 실현되기 어려운 조건이에요.','presupposes interoperability... a condition that market forces alone are unlikely to deliver','"presupposes"와 동격 명사절을 활용한 고도의 학술 논증 문체예요.','MaaS 정책','C2','transport','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;
