-- EngCat — discussion (의견·토론) topic
-- 210 words (35 per CEFR level: A1~C2) + 42 patterns (7 per level)
-- Columns: words(id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword)
-- Columns: sentences(id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order)

-- ══════════════════════════════════════
-- WORDS — A1 (기초 의견 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_A1_01','think','/θɪŋk/','verb','생각하다','To have an opinion or belief about something.','What do you {think}?','어떻게 생각해요?','think','A1','discussion',1,'person thinking pondering idea expression'),
('w_discussion_A1_02','say','/seɪ/','verb','말하다','To utter words; to express a thought or opinion.','What did she {say} about the plan?','그녀가 계획에 대해 뭐라고 했어요?','say','A1','discussion',1,'person speaking talking conversation'),
('w_discussion_A1_03','agree','/əˈɡriː/','verb','동의하다','To have the same opinion as someone else.','Do you {agree} with me?','저와 동의하시나요?','agree','A1','discussion',1,'two people nodding agreement handshake'),
('w_discussion_A1_04','want','/wɒnt/','verb','원하다','To feel a desire or wish for something.','I {want} to share my idea.','제 생각을 나누고 싶어요.','want','A1','discussion',2,'person raising hand wanting to speak'),
('w_discussion_A1_05','know','/nəʊ/','verb','알다','To have information or understanding about something.','I don''t {know} the answer.','저는 답을 모르겠어요.','know','A1','discussion',1,'person thinking question mark idea'),
('w_discussion_A1_06','like','/laɪk/','verb','좋아하다; 생각하다','To enjoy or approve of something; to feel or think in a certain way.','I {like} your idea very much.','당신의 생각이 아주 좋아요.','like','A1','discussion',2,'person smiling positive approval thumbs up'),
('w_discussion_A1_07','maybe','/ˈmeɪbi/','adverb','아마도','Perhaps; possibly.'{Maybe} we should try a different way.','아마 다른 방법을 시도해 봐야 할 것 같아요.','Maybe','A1','discussion',1,'uncertain person thinking maybe perhaps'),
('w_discussion_A1_08','yes','/jes/','interjection','네, 맞아요','Used to express agreement or a positive answer.'{Yes}, I think that''s right.','네, 맞는 것 같아요.','Yes','A1','discussion',1,'person nodding yes agreement positive'),
('w_discussion_A1_09','no','/nəʊ/','interjection','아니요','Used to express disagreement or a negative answer.'{No}, I don''t agree with that.','아니요, 저는 그것에 동의하지 않아요.','No','A1','discussion',1,'person shaking head disagreement no'),
('w_discussion_A1_10','right','/raɪt/','adjective','맞아요, 옳은','Correct; in accordance with the facts.','You are {right} about that.','그 점에서 맞아요.','right','A1','discussion',1,'checkmark correct right answer approval'),
('w_discussion_A1_11','good','/ɡʊd/','adjective','좋은','Of a high quality or positive nature.','That''s a {good} point.','좋은 지적이에요.','good','A1','discussion',2,'good idea lightbulb positive expression'),
('w_discussion_A1_12','bad','/bæd/','adjective','나쁜','Of poor quality; not acceptable.','That''s not a {bad} idea.','나쁜 생각은 아니에요.','bad','A1','discussion',2,'person frowning negative shaking head'),
('w_discussion_A1_13','help','/help/','verb','돕다, 도움이 되다','To make it easier for someone to do something.','Can you {help} me understand this?','이걸 이해할 수 있게 도와주실 수 있나요?','help','A1','discussion',2,'two people helping explaining together'),
('w_discussion_A1_14','tell','/tel/','verb','말해주다, 알려주다','To communicate information or facts to someone.','Please {tell} me your opinion.','의견을 말씀해 주세요.','tell','A1','discussion',1,'person explaining pointing speaking'),
('w_discussion_A1_15','ask','/ɑːsk/','verb','묻다, 질문하다','To request information or an answer from someone.','Can I {ask} a question?','질문해도 될까요?','ask','A1','discussion',1,'person raising hand asking question classroom'),
('w_discussion_A1_16','mean','/miːn/','verb','의미하다','To intend to express or convey a particular idea.','What do you {mean} by that?','그게 무슨 뜻이에요?','mean','A1','discussion',1,'confused person asking meaning question'),
('w_discussion_A1_17','feel','/fiːl/','verb','느끼다, ~인 것 같다','To believe or sense something in an emotional or intuitive way.','I {feel} this is the best choice.','이게 최선의 선택인 것 같아요.','feel','A1','discussion',2,'person touching heart feeling opinion'),
('w_discussion_A1_18','talk','/tɔːk/','verb','이야기하다','To communicate through speech; to discuss.','Let''s {talk} about this later.','이것에 대해 나중에 이야기해요.','talk','A1','discussion',1,'two people talking conversation discussion'),
('w_discussion_A1_19','sure','/ʃʊər/','adjective','확실한, 물론','Completely confident that something is true or will happen.','I''m not {sure} about that.','그것에 대해서는 확실하지 않아요.','sure','A1','discussion',1,'uncertain person thinking unsure expression'),
('w_discussion_A1_20','true','/truː/','adjective','사실인, 진짜의','Consistent with facts; accurate and correct.','Is that {true}?','그게 사실이에요?','true','A1','discussion',1,'fact truth newspaper document proof'),
('w_discussion_A1_21','wrong','/rɒŋ/','adjective','틀린, 잘못된','Not correct; mistaken.','I think that''s {wrong}.','저는 그게 틀렸다고 생각해요.','wrong','A1','discussion',2,'wrong answer X mark incorrect red'),
('w_discussion_A1_22','idea','/aɪˈdɪə/','noun','생각, 아이디어','A thought or suggestion about a possible course of action.','That''s a great {idea}!','정말 좋은 아이디어예요!','idea','A1','discussion',1,'lightbulb idea bright thought innovation'),
('w_discussion_A1_23','try','/traɪ/','verb','시도하다','To make an effort to do something.','Let''s {try} this approach.','이 방법을 시도해봐요.','try','A1','discussion',2,'person trying attempting effort reaching'),
('w_discussion_A1_24','way','/weɪ/','noun','방법, 방식','A method or manner of doing something.','Is there another {way} to do this?','이걸 할 다른 방법이 있나요?','way','A1','discussion',2,'fork in road choice options direction'),
('w_discussion_A1_25','need','/niːd/','verb','필요하다','To require something as essential or important.','We {need} to talk about this.','이것에 대해 이야기해야 해요.','need','A1','discussion',1,'person pointing important urgent need'),
('w_discussion_A1_26','good','','','','','','','','A1','discussion',0,''),  -- placeholder removed below
('w_discussion_A1_26','show','/ʃəʊ/','verb','보여주다','To make something visible; to demonstrate.','Can you {show} me what you mean?','무슨 의미인지 보여주실 수 있나요?','show','A1','discussion',2,'person pointing demonstrating showing explaining'),
('w_discussion_A1_27','same','/seɪm/','adjective','같은','Identical or alike in a way; not different.','I feel the {same} way.','저도 같은 생각이에요.','same','A1','discussion',1,'two matching identical objects same comparison'),
('w_discussion_A1_28','different','/ˈdɪfrənt/','adjective','다른','Not the same as another; distinct.','We have {different} opinions on this.','이것에 대해 우리 의견이 달라요.','different','A1','discussion',1,'contrast two different objects comparison'),
('w_discussion_A1_29','new','/njuː/','adjective','새로운','Not existing before; recently introduced.','Do you have any {new} ideas?','새로운 아이디어가 있나요?','new','A1','discussion',2,'new idea fresh innovation modern'),
('w_discussion_A1_30','problem','/ˈprɒbləm/','noun','문제','A thing that is difficult to deal with or understand.','What is the {problem}?','문제가 무엇인가요?','problem','A1','discussion',1,'person looking at problem obstacle challenge'),
('w_discussion_A1_31','answer','/ˈɑːnsər/','noun','대답, 답','A response to a question or a solution to a problem.','I don''t have a clear {answer}.','명확한 답이 없어요.','answer','A1','discussion',2,'question mark answer solution thinking'),
('w_discussion_A1_32','question','/ˈkwestʃən/','noun','질문','A sentence or phrase seeking information or a response.','That''s a very good {question}.','아주 좋은 질문이에요.','question','A1','discussion',1,'hand raised question classroom curious'),
('w_discussion_A1_33','important','/ɪmˈpɔːtənt/','adjective','중요한','Of great significance or value.','This is an {important} topic.','이것은 중요한 주제예요.','important','A1','discussion',2,'important document star priority highlight'),
('w_discussion_A1_34','or','/ɔːr/','conjunction','또는, 아니면','Used to connect alternatives.','Should we do this {or} that?','이것을 해야 할까요, 아니면 저것을?','or','A1','discussion',3,'two choices fork options or versus'),
('w_discussion_A1_35','point','/pɔɪnt/','noun','요점; 논점','The main idea or purpose of what is being said.','That''s a good {point}.','좋은 지적이에요.','point','A1','discussion',1,'person pointing finger emphasizing key point');

-- ══════════════════════════════════════
-- WORDS — A2 (초급 토론 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_A2_01','opinion','/əˈpɪnjən/','noun','의견','A personal view or judgment that is not necessarily based on fact.','In my {opinion}, we should try again.','제 의견으로는 다시 시도해야 해요.','opinion','A2','discussion',1,'person sharing opinion speech bubble discussion'),
('w_discussion_A2_02','suggest','/səˈdʒest/','verb','제안하다','To put forward an idea for consideration.','I {suggest} we try a different method.','다른 방법을 시도해보자고 제안해요.','suggest','A2','discussion',1,'person suggesting idea whiteboard brainstorm'),
('w_discussion_A2_03','believe','/bɪˈliːv/','verb','믿다, ~라고 생각하다','To accept that something is true; to have an opinion.','I {believe} this approach will work.','이 방법이 효과적일 거라고 생각해요.','believe','A2','discussion',1,'person confident belief conviction opinion'),
('w_discussion_A2_04','understand','/ˌʌndəˈstænd/','verb','이해하다','To comprehend the meaning or cause of something.','I don''t {understand} your point.','당신의 요점을 이해하지 못했어요.','understand','A2','discussion',1,'person confused thinking comprehension understanding'),
('w_discussion_A2_05','disagree','/ˌdɪsəˈɡriː/','verb','동의하지 않다','To have a different opinion from someone.','I''m afraid I {disagree} with that view.','저는 그 의견에 동의하지 않아요.','disagree','A2','discussion',1,'two people debate disagreement opposing views'),
('w_discussion_A2_06','discuss','/dɪˈskʌs/','verb','토론하다, 이야기하다','To talk about a topic in detail.','Let''s {discuss} the pros and cons.','장단점을 이야기해봐요.','discuss','A2','discussion',1,'group people discussing table meeting debate'),
('w_discussion_A2_07','reason','/ˈriːzən/','noun','이유, 근거','A cause, explanation, or justification for an action or belief.','What is your {reason} for thinking that?','그렇게 생각하는 이유가 뭔가요?','reason','A2','discussion',1,'person explaining reasoning logic cause'),
('w_discussion_A2_08','example','/ɪɡˈzɑːmpəl/','noun','예시, 사례','A thing that is representative of its kind; an illustration.','Can you give me an {example}?','예시를 들어줄 수 있나요?','example','A2','discussion',1,'chalkboard example illustration teaching'),
('w_discussion_A2_09','explain','/ɪkˈspleɪn/','verb','설명하다','To make something clear; to give the reasons for something.','Could you {explain} that again?','다시 설명해 주실 수 있나요?','explain','A2','discussion',1,'teacher explaining board instruction clear'),
('w_discussion_A2_10','idea','/aɪˈdɪə/','noun','생각, 아이디어','A thought or concept formed in the mind; a plan or suggestion.','I have an {idea} about how to solve this.','이것을 해결할 아이디어가 있어요.','idea','A2','discussion',1,'lightbulb idea concept creative thinking'),
('w_discussion_A2_11','correct','/kəˈrekt/','adjective','맞는, 정확한','Free from error; conforming to fact.','Are you {correct} about the time?','시간이 맞나요?','correct','A2','discussion',2,'correct answer check right accuracy'),
('w_discussion_A2_12','wrong','/rɒŋ/','adjective','틀린, 잘못된','Not correct; mistaken.','I think you might be {wrong} about that.','그 부분에서 틀린 것 같아요.','wrong','A2','discussion',2,'incorrect wrong answer mistake error'),
('w_discussion_A2_13','both','/bəʊθ/','determiner','둘 다','Two people or things; each of the two.'{Both} sides have valid arguments.','양쪽 모두 타당한 주장이 있어요.','Both','A2','discussion',2,'two sides balance scale both options'),
('w_discussion_A2_14','thought','/θɔːt/','noun','생각, 의견','An idea or opinion produced by thinking.','I''d like to share my {thoughts}.','제 생각을 공유하고 싶어요.','thoughts','A2','discussion',1,'thinking brain thoughts ideas mind map'),
('w_discussion_A2_15','mind','/maɪnd/','noun','생각, 마음','The faculty of thinking; a person''s opinion.','I''ve changed my {mind} about this.','이것에 대해 생각이 바뀌었어요.','mind','A2','discussion',2,'change of mind opinion shift flexible'),
('w_discussion_A2_16','topic','/ˈtɒpɪk/','noun','주제','The subject of a conversation or discussion.','Let''s change the {topic}.','주제를 바꿔요.','topic','A2','discussion',2,'topic subject discussion theme headline'),
('w_discussion_A2_17','clear','/klɪər/','adjective','명확한','Easy to understand; without confusion.','Could you make that more {clear}?','좀 더 명확하게 말씀해 주실 수 있나요?','clear','A2','discussion',1,'clear explanation transparent understanding light'),
('w_discussion_A2_18','share','/ʃeər/','verb','공유하다, 나누다','To tell others about something; to exchange information or feelings.','Please {share} your thoughts with the group.','그룹과 생각을 공유해 주세요.','share','A2','discussion',1,'people sharing ideas circle discussion group'),
('w_discussion_A2_19','listen','/ˈlɪsən/','verb','듣다','To give attention to sound; to pay attention to what someone says.','We need to {listen} to each other.','서로의 말을 들어야 해요.','listen','A2','discussion',2,'person listening attentive ear communication'),
('w_discussion_A2_20','important','/ɪmˈpɔːtənt/','adjective','중요한','Of great significance or value.','It''s {important} to hear both sides.','양쪽 의견을 듣는 것이 중요해요.','important','A2','discussion',2,'important key highlight significant value'),
('w_discussion_A2_21','decide','/dɪˈsaɪd/','verb','결정하다','To make a choice between two or more possibilities.','We need to {decide} together.','함께 결정해야 해요.','decide','A2','discussion',1,'decision crossroads choice path deciding'),
('w_discussion_A2_22','choice','/tʃɔɪs/','noun','선택','An act of choosing between two or more possibilities.','We have to make the right {choice}.','올바른 선택을 해야 해요.','choice','A2','discussion',2,'choices options fork road decision multiple'),
('w_discussion_A2_23','problem','/ˈprɒbləm/','noun','문제','A matter or situation regarded as unwelcome or needing resolution.','I see a {problem} with that idea.','그 아이디어에 문제가 있는 것 같아요.','problem','A2','discussion',2,'problem obstacle challenge issue solution'),
('w_discussion_A2_24','solution','/səˈluːʃən/','noun','해결책','A means of solving a problem or dealing with a situation.','We need to find a {solution}.','해결책을 찾아야 해요.','solution','A2','discussion',1,'solution key puzzle solved light answer'),
('w_discussion_A2_25','together','/təˈɡeðər/','adverb','함께','With another person or group; jointly.','Let''s work on this {together}.','함께 이것을 해결해봐요.','together','A2','discussion',2,'team together collaboration group working'),
('w_discussion_A2_26','often','/ˈɒfən/','adverb','자주','Many times; frequently.','We {often} disagree on small things.','우리는 작은 일에서 자주 의견이 달라요.','often','A2','discussion',3,'frequency often regular repeated pattern'),
('w_discussion_A2_27','actually','/ˈæktʃuəli/','adverb','사실은','In fact; in reality (used to correct a misunderstanding).'{Actually}, I meant something different.','사실은 다른 의미로 말한 거예요.','Actually','A2','discussion',1,'surprised correction actually fact real'),
('w_discussion_A2_28','simple','/ˈsɪmpəl/','adjective','간단한','Easy to understand; not complex.','Let me put it in {simple} terms.','간단하게 설명해 드릴게요.','simple','A2','discussion',2,'simple clear easy plain straightforward'),
('w_discussion_A2_29','strong','/strɒŋ/','adjective','강한, 강력한','Having power or force; convincing.','She made a {strong} argument.','그녀는 강력한 주장을 했어요.','strong','A2','discussion',2,'strong powerful argument convincing debate'),
('w_discussion_A2_30','view','/vjuː/','noun','견해, 시각','A particular way of thinking about something; an opinion.','What is your {view} on this matter?','이 문제에 대한 당신의 견해는 어때요?','view','A2','discussion',1,'perspective viewpoint lens seeing differently'),
('w_discussion_A2_31','side','/saɪd/','noun','입장, 편','One of the positions in a debate or dispute.','I can see both {sides} of the argument.','주장의 양쪽을 모두 이해해요.','sides','A2','discussion',2,'two sides debate balance perspective'),
('w_discussion_A2_32','add','/æd/','verb','덧붙이다, 추가하다','To include or say something extra.','I''d like to {add} something to that.','거기에 한 가지 덧붙이고 싶어요.','add','A2','discussion',1,'adding plus contribution speaking turn'),
('w_discussion_A2_33','possible','/ˈpɒsɪbəl/','adjective','가능한','Able to be done or achieved.','Is it {possible} to change the plan?','계획을 바꾸는 게 가능할까요?','possible','A2','discussion',2,'possible maybe option available feasible'),
('w_discussion_A2_34','result','/rɪˈzʌlt/','noun','결과','An outcome or effect of an action or situation.','What is the {result} of that choice?','그 선택의 결과는 무엇인가요?','result','A2','discussion',2,'result outcome effect consequence arrow'),
('w_discussion_A2_35','change','/tʃeɪndʒ/','verb','바꾸다, 변경하다','To make or become different.','We might need to {change} our approach.','접근 방식을 바꿔야 할 수도 있어요.','change','A2','discussion',2,'change shift transform direction new approach');

-- ══════════════════════════════════════
-- WORDS — B1 (중급 토론 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_B1_01','argue','/ˈɑːɡjuː/','verb','주장하다; 논쟁하다','To give reasons for or against something; to exchange opposing views.','He {argues} that the plan needs more research.','그는 계획에 더 많은 연구가 필요하다고 주장해요.','argues','B1','discussion',1,'debate argue dispute two people opposing'),
('w_discussion_B1_02','perspective','/pəˈspektɪv/','noun','관점, 시각','A particular way of thinking about something; a point of view.','Try to see it from my {perspective}.','제 관점에서 생각해 보세요.','perspective','B1','discussion',1,'perspective viewpoint different angle lens'),
('w_discussion_B1_03','evidence','/ˈevɪdəns/','noun','증거, 근거','Facts indicating whether a belief is true or false.','We need {evidence} to support that claim.','그 주장을 뒷받침할 증거가 필요해요.','evidence','B1','discussion',1,'evidence documents proof data research'),
('w_discussion_B1_04','support','/səˈpɔːt/','verb','지지하다, 뒷받침하다','To give assistance to or approval of; to back up with evidence.','What data can you use to {support} your point?','어떤 데이터로 요점을 뒷받침할 수 있나요?','support','B1','discussion',1,'support backing evidence data chart'),
('w_discussion_B1_05','counter','/ˈkaʊntər/','verb','반박하다','To speak or act in opposition to something.','How can we {counter} that argument?','그 주장을 어떻게 반박할 수 있을까요?','counter','B1','discussion',1,'counterargument debate opposing rebuttal'),
('w_discussion_B1_06','stance','/stæns/','noun','입장, 태도','The attitude or position of a person or organization regarding something.','What is your {stance} on this issue?','이 문제에 대한 당신의 입장은 무엇인가요?','stance','B1','discussion',1,'position stance standing firm opinion'),
('w_discussion_B1_07','elaborate','/ɪˈlæbəreɪt/','verb','자세히 설명하다','To explain something in more detail; to expand on a point.','Could you {elaborate} on that idea?','그 아이디어에 대해 좀 더 자세히 설명해 주실 수 있나요?','elaborate','B1','discussion',1,'explaining detail expanding point talk'),
('w_discussion_B1_08','claim','/kleɪm/','noun/verb','주장 (하다)','An assertion that something is true; to state something without proof.','That is a bold {claim} without evidence.','증거 없이 대담한 주장이에요.','claim','B1','discussion',1,'bold claim statement assertion speech bubble'),
('w_discussion_B1_09','viewpoint','/ˈvjuːpɔɪnt/','noun','시각, 관점','A person''s opinion or way of thinking about something.','I''d like to hear your {viewpoint} on this.','이것에 대한 당신의 시각을 듣고 싶어요.','viewpoint','B1','discussion',1,'viewpoint perspective thought bubble person'),
('w_discussion_B1_10','debate','/dɪˈbeɪt/','noun/verb','토론 (하다)','A formal discussion on a topic where opposing arguments are put forward.','Let''s {debate} the pros and cons of each option.','각 선택지의 장단점을 토론해봐요.','debate','B1','discussion',1,'formal debate podium speech discussion stage'),
('w_discussion_B1_11','convince','/kənˈvɪns/','verb','설득하다','To cause someone to believe something is true through argument.','Can you {convince} me with a better example?','더 좋은 예시로 저를 설득해 주실 수 있나요?','convince','B1','discussion',1,'persuade convince argument convincing speaking'),
('w_discussion_B1_12','conclude','/kənˈkluːd/','verb','결론을 내리다','To bring something to an end; to form an opinion after consideration.','What do you {conclude} from this data?','이 데이터에서 어떤 결론을 내리나요?','conclude','B1','discussion',1,'conclusion end summarize wrap up final'),
('w_discussion_B1_13','assume','/əˈsjuːm/','verb','가정하다, 전제하다','To suppose that something is true without evidence.','Don''t {assume} you know the answer.','답을 안다고 가정하지 마세요.','assume','B1','discussion',2,'assumption suppose presume taking for granted'),
('w_discussion_B1_14','relevant','/ˈreləvənt/','adjective','관련 있는','Closely connected to what is being discussed.','Is that point really {relevant} to our topic?','그 요점이 우리 주제와 정말 관련이 있나요?','relevant','B1','discussion',1,'relevant connected related link theme'),
('w_discussion_B1_15','valid','/ˈvælɪd/','adjective','타당한, 유효한','Well-reasoned or logically sound.','That''s a {valid} concern we should address.','우리가 다뤄야 할 타당한 우려예요.','valid','B1','discussion',1,'valid checkmark approved sound logical'),
('w_discussion_B1_16','raise','/reɪz/','verb','제기하다 (문제를)','To bring something up for discussion or attention.','She {raised} an important concern.','그녀는 중요한 우려를 제기했어요.','raised','B1','discussion',1,'raising hand bringing up issue attention'),
('w_discussion_B1_17','address','/əˈdres/','verb','다루다, 해결하다','To deal with or discuss a topic or problem.','We need to {address} this issue directly.','이 문제를 직접적으로 다뤄야 해요.','address','B1','discussion',1,'addressing issue dealing with problem focus'),
('w_discussion_B1_18','highlight','/ˈhaɪlaɪt/','verb','강조하다','To emphasize or draw attention to a point.','I want to {highlight} two key points.','두 가지 핵심 사항을 강조하고 싶어요.','highlight','B1','discussion',1,'highlight emphasis key point marker important'),
('w_discussion_B1_19','consider','/kənˈsɪdər/','verb','고려하다','To think carefully about a subject; to take into account.','Please {consider} the other possibilities.','다른 가능성들을 고려해 주세요.','consider','B1','discussion',1,'consider think over weigh options thoughtful'),
('w_discussion_B1_20','instead','/ɪnˈsted/','adverb','대신에','As an alternative.','What if we did this {instead}?','대신 이것을 하면 어떨까요?','instead','B1','discussion',2,'alternative instead option replace substitute'),
('w_discussion_B1_21','suggest','/səˈdʒest/','verb','제안하다','To put forward an idea for consideration.','I {suggest} we revisit this tomorrow.','내일 이것을 다시 검토하자고 제안해요.','suggest','B1','discussion',1,'suggesting idea proposal recommend option'),
('w_discussion_B1_22','issue','/ˈɪʃuː/','noun','문제, 사안','An important topic or problem for debate or discussion.','This {issue} requires careful thought.','이 사안은 신중한 검토가 필요해요.','issue','B1','discussion',1,'issue problem topic concern discussion'),
('w_discussion_B1_23','agree','/əˈɡriː/','verb','동의하다','To have the same opinion; to consent.','I {agree} with your reasoning to some extent.','어느 정도 당신의 이유에 동의해요.','agree','B1','discussion',1,'agreement nod approval consensus two people'),
('w_discussion_B1_24','challenge','/ˈtʃælɪndʒ/','verb','이의를 제기하다','To question or dispute a claim or belief.','I want to {challenge} that assumption.','그 가정에 이의를 제기하고 싶어요.','challenge','B1','discussion',1,'challenge dispute question boxing ring debate'),
('w_discussion_B1_25','based on','/beɪst ɒn/','phrase','~에 근거하여','Using something as a foundation or reason.'{Based on} the data, this seems likely.','데이터에 근거하면 그럴 가능성이 높아요.','Based on','B1','discussion',1,'evidence base data foundation research proof'),
('w_discussion_B1_26','generally','/ˈdʒenərəli/','adverb','일반적으로','In most cases; usually.'{Generally} speaking, this method works.','일반적으로 말하면 이 방법이 효과적이에요.','Generally','B1','discussion',2,'general rule usually most cases broadly'),
('w_discussion_B1_27','however','/haʊˈevər/','conjunction','하지만, 그러나','Used to introduce a contrast or exception.','It''s a good idea; {however}, there are risks.','좋은 아이디어예요. 하지만 위험이 있어요.','however','B1','discussion',1,'contrast however but exception opposing turn'),
('w_discussion_B1_28','moreover','/mɔːrˈoʊvər/','adverb','게다가, 더욱이','Used to add information that reinforces a point.'{Moreover}, the evidence strongly supports this.','게다가 증거가 이를 강하게 뒷받침해요.','Moreover','B1','discussion',1,'furthermore moreover additionally plus adding'),
('w_discussion_B1_29','therefore','/ˈðeəfɔː/','adverb','따라서, 그러므로','For that reason; as a result.'{Therefore}, I think we should proceed.','따라서 진행해야 한다고 생각해요.','Therefore','B1','discussion',1,'therefore result conclusion logic arrow flow'),
('w_discussion_B1_30','although','/ɔːlˈðəʊ/','conjunction','비록 ~이지만','In spite of the fact that; even though.'{Although} I see your point, I disagree.','당신의 요점을 이해하지만 동의하지 않아요.','Although','B1','discussion',1,'although despite concession contrast even though'),
('w_discussion_B1_31','overall','/ˌoʊvərˈɔːl/','adverb','전체적으로','Taking everything into account.'{Overall}, I think the plan is solid.','전체적으로 계획이 탄탄하다고 생각해요.','Overall','B1','discussion',2,'overall summary total big picture conclusion'),
('w_discussion_B1_32','particularly','/pəˈtɪkjʊləli/','adverb','특히, 특별히','Especially; to a greater degree than usual.','I am {particularly} concerned about the cost.','특히 비용에 대해 우려돼요.','particularly','B1','discussion',2,'particularly especially specifically emphasize'),
('w_discussion_B1_33','admit','/ədˈmɪt/','verb','인정하다','To accept that something is true, often reluctantly.','I have to {admit} that''s a strong point.','그게 강력한 지적이라는 걸 인정해야겠어요.','admit','B1','discussion',1,'admitting conceding agreeing point honest'),
('w_discussion_B1_34','point out','/pɔɪnt aʊt/','phrase','지적하다, 지목하다','To indicate or direct attention to something.','I''d like to {point out} a few issues.','몇 가지 문제를 지적하고 싶어요.','point out','B1','discussion',1,'pointing out indicating highlighting issues'),
('w_discussion_B1_35','approach','/əˈprəʊtʃ/','noun','접근 방식','A way of dealing with a situation or problem.','We need a more balanced {approach}.','좀 더 균형 잡힌 접근 방식이 필요해요.','approach','B1','discussion',1,'approach method strategy path direction');

-- ══════════════════════════════════════
-- WORDS — B2 (중고급 비판적 사고 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_B2_01','rebut','/rɪˈbʌt/','verb','반박하다, 논박하다','To argue that a claim is wrong or mistaken.','She effectively {rebutted} every counterargument.','그녀는 모든 반론을 효과적으로 반박했어요.','rebutted','B2','discussion',1,'rebuttal argument lawyer court opposing'),
('w_discussion_B2_02','substantiate','/səbˈstænʃieɪt/','verb','입증하다, 뒷받침하다','To provide evidence to prove that something is true.','Can you {substantiate} that claim with data?','그 주장을 데이터로 입증할 수 있나요?','substantiate','B2','discussion',1,'data evidence proof substantiate research charts'),
('w_discussion_B2_03','critique','/krɪˈtiːk/','verb/noun','비판하다; 비판','To analyze and evaluate something in detail.','Let me {critique} the main weaknesses of this plan.','이 계획의 주요 약점을 비판해 볼게요.','critique','B2','discussion',1,'critical review analysis evaluation writing'),
('w_discussion_B2_04','nuance','/ˈnjuːɑːns/','noun','뉘앙스, 미묘한 차이','A subtle difference in meaning, expression, or feeling.','The {nuance} of that phrase is easy to miss.','그 표현의 뉘앙스는 놓치기 쉬워요.','nuance','B2','discussion',1,'subtle difference shades meaning nuance detail'),
('w_discussion_B2_05','premise','/ˈpremɪs/','noun','전제, 가정','A previous statement or proposition from which another is inferred.','Your entire argument rests on a flawed {premise}.','당신의 논거 전체가 결함 있는 전제 위에 있어요.','premise','B2','discussion',1,'foundation premise base assumption argument logic'),
('w_discussion_B2_06','inference','/ˈɪnfərəns/','noun','추론, 결론','A conclusion reached by reasoning from evidence.','That is a reasonable {inference} from the facts.','그것은 사실로부터 합리적인 추론이에요.','inference','B2','discussion',1,'logic inference deduction reasoning brain diagram'),
('w_discussion_B2_07','fallacy','/ˈfæləsi/','noun','오류, 허위 논리','A mistaken belief based on unsound reasoning.','That''s a classic straw man {fallacy}.','그것은 전형적인 허수아비 논리 오류예요.','fallacy','B2','discussion',1,'logical fallacy error mistake reasoning trap'),
('w_discussion_B2_08','rhetoric','/ˈretərɪk/','noun','수사학; 언변','Persuasive language or discourse; the art of using language effectively.','His speech was full of political {rhetoric}.','그의 연설은 정치적 언변으로 가득했어요.','rhetoric','B2','discussion',1,'rhetoric speech debate persuade podium oratory'),
('w_discussion_B2_09','bias','/ˈbaɪəs/','noun','편향, 편견','An inclination toward one view without considering others fairly.','We must acknowledge our own {biases}.','우리 자신의 편향을 인정해야 해요.','biases','B2','discussion',1,'bias scale tipping unbalanced prejudice'),
('w_discussion_B2_10','objectivity','/ˌɒbdʒekˈtɪvɪti/','noun','객관성','The quality of being uninfluenced by personal feelings or opinions.'{Objectivity} is essential in a fair debate.','공정한 토론에서 객관성은 필수예요.','Objectivity','B2','discussion',1,'balance scale objective fair neutral measure'),
('w_discussion_B2_11','acknowledge','/əkˈnɒlɪdʒ/','verb','인정하다, 수긍하다','To recognize the truth or existence of something.','I {acknowledge} that your point is valid.','당신의 지적이 타당하다는 것을 인정해요.','acknowledge','B2','discussion',1,'acknowledge nod recognition accept truth'),
('w_discussion_B2_12','contradict','/ˌkɒntrəˈdɪkt/','verb','모순되다; 반박하다','To assert the opposite of a statement; to be inconsistent with.','These two findings {contradict} each other.','이 두 가지 결론이 서로 모순돼요.','contradict','B2','discussion',1,'contradiction clash opposing statements conflict'),
('w_discussion_B2_13','concede','/kənˈsiːd/','verb','인정하다, 양보하다','To admit that something is true after initially denying it.','I''ll {concede} that point, but let me add...','그 지점은 인정하겠지만, 덧붙이고 싶은 게 있어요.','concede','B2','discussion',1,'conceding accepting point debate gracious'),
('w_discussion_B2_14','imply','/ɪmˈplaɪ/','verb','암시하다, 시사하다','To suggest something without stating it directly.','What exactly are you {implying}?','정확히 무엇을 암시하는 건가요?','implying','B2','discussion',1,'imply hint suggest indirect meaning subtext'),
('w_discussion_B2_15','undermine','/ˌʌndəˈmaɪn/','verb','약화시키다, 훼손하다','To weaken or damage something gradually or insidiously.','This evidence {undermines} your entire argument.','이 증거는 당신의 주장 전체를 약화시켜요.','undermines','B2','discussion',1,'undermine weaken erode foundation crumble'),
('w_discussion_B2_16','inconsistency','/ˌɪnkənˈsɪstənsi/','noun','모순, 일관성 없음','A situation where different parts do not agree with each other.','There is an {inconsistency} in your reasoning.','당신의 논리에 일관성이 없어요.','inconsistency','B2','discussion',1,'inconsistency mismatch conflict logic gap'),
('w_discussion_B2_17','assumption','/əˈsʌmpʃən/','noun','가정, 전제','Something accepted as true without proof.','We must question our {assumptions}.','우리의 가정을 의심해야 해요.','assumptions','B2','discussion',1,'assumption presume take for granted blindspot'),
('w_discussion_B2_18','compelling','/kəmˈpelɪŋ/','adjective','설득력 있는, 강렬한','Evoking interest or attention; very convincing.','She made a {compelling} case for the new policy.','그녀는 새로운 정책에 대한 설득력 있는 주장을 했어요.','compelling','B2','discussion',1,'compelling argument persuasive powerful speech'),
('w_discussion_B2_19','speculate','/ˈspekjʊleɪt/','verb','추측하다, 짐작하다','To form a theory without firm evidence.','We can only {speculate} about the cause.','원인에 대해서는 추측만 할 수 있어요.','speculate','B2','discussion',1,'speculation guess theory uncertain question mark'),
('w_discussion_B2_20','impartial','/ɪmˈpɑːʃəl/','adjective','공정한, 중립적인','Treating all rivals or disputants equally; fair.','A judge must remain {impartial}.','판사는 공정해야 해요.','impartial','B2','discussion',1,'impartial neutral balance fair scales justice'),
('w_discussion_B2_21','verify','/ˈverɪfaɪ/','verb','확인하다, 검증하다','To make sure or demonstrate that something is true.','We need to {verify} these claims independently.','이 주장들을 독립적으로 검증해야 해요.','verify','B2','discussion',1,'verify check fact research document confirm'),
('w_discussion_B2_22','logical','/ˈlɒdʒɪkəl/','adjective','논리적인','Following clear, sound reasoning.','That''s not a very {logical} conclusion.','그것은 그다지 논리적인 결론이 아니에요.','logical','B2','discussion',1,'logic chain diagram reasoning flow steps'),
('w_discussion_B2_23','dispute','/dɪˈspjuːt/','verb/noun','반박하다; 논쟁','To argue about or challenge the truth of something.','I {dispute} the accuracy of those statistics.','그 통계의 정확성에 이의를 제기해요.','dispute','B2','discussion',1,'dispute argument disagreement court challenge'),
('w_discussion_B2_24','balanced','/ˈbælənst/','adjective','균형 잡힌','Keeping or showing a balance; not favoring either side.','A {balanced} argument considers all perspectives.','균형 잡힌 주장은 모든 관점을 고려해요.','balanced','B2','discussion',1,'balance scales equal fair two sides'),
('w_discussion_B2_25','alternative','/ɔːlˈtɜːnətɪv/','noun','대안','One of several possible courses of action.','Have you considered any {alternatives}?','다른 대안을 고려해 보셨나요?','alternatives','B2','discussion',1,'alternative option paths choice fork road'),
('w_discussion_B2_26','profound','/prəˈfaʊnd/','adjective','심오한, 깊은','Very deep or intense in nature; having great insight.','His {profound} observation changed the debate.','그의 심오한 관찰이 토론의 흐름을 바꿨어요.','profound','B2','discussion',2,'profound deep insight wisdom thoughtful'),
('w_discussion_B2_27','persuasive','/pəˈsweɪsɪv/','adjective','설득력 있는','Able to cause someone to do or believe something.','That was a very {persuasive} argument.','아주 설득력 있는 주장이었어요.','persuasive','B2','discussion',1,'persuasive convincing speech argument star'),
('w_discussion_B2_28','distinguish','/dɪˈstɪŋɡwɪʃ/','verb','구별하다, 구분하다','To recognize or point out a difference.','We must {distinguish} between fact and opinion.','사실과 의견을 구별해야 해요.','distinguish','B2','discussion',1,'distinguish separate fact opinion compare'),
('w_discussion_B2_29','reinforce','/ˌriːɪnˈfɔːs/','verb','강화하다, 보강하다','To strengthen or support an argument or idea.','This data {reinforces} our original conclusion.','이 데이터는 우리의 원래 결론을 강화해요.','reinforces','B2','discussion',1,'reinforce strengthen support pillars data'),
('w_discussion_B2_30','evaluate','/ɪˈvæljueɪt/','verb','평가하다','To judge or assess the value or quality of something.','Let''s {evaluate} each option carefully.','각 선택지를 신중하게 평가해봐요.','evaluate','B2','discussion',1,'evaluate assess grade judge score review'),
('w_discussion_B2_31','counterargument','/ˈkaʊntərˌɑːɡjʊmənt/','noun','반론, 반박 논거','An argument made against another argument.','What is your best {counterargument}?','가장 강력한 반론이 무엇인가요?','counterargument','B2','discussion',1,'counterargument rebuttal debate opposing arrow'),
('w_discussion_B2_32','credible','/ˈkredɪbəl/','adjective','신뢰할 수 있는','Able to be believed; convincing.','Is that source {credible}?','그 출처가 신뢰할 수 있나요?','credible','B2','discussion',1,'credible trustworthy source reliable verified'),
('w_discussion_B2_33','consistent','/kənˈsɪstənt/','adjective','일관된','Acting or done in the same way over time; not contradictory.','Your argument should be {consistent}.','당신의 주장은 일관적이어야 해요.','consistent','B2','discussion',1,'consistent pattern logic flow straight line'),
('w_discussion_B2_34','acknowledge','/əkˈnɒlɪdʒ/','verb','인정하다 (한계를)','To recognize the validity of something, including limitations.','We should {acknowledge} the limits of our data.','우리 데이터의 한계를 인정해야 해요.','acknowledge','B2','discussion',1,'acknowledging limitation honest transparent research'),
('w_discussion_B2_35','thorough','/ˈθʌrə/','adjective','철저한, 완전한','Complete in every detail; leaving nothing out.','We need a {thorough} analysis of the evidence.','증거에 대한 철저한 분석이 필요해요.','thorough','B2','discussion',1,'thorough complete detailed checklist analysis');

-- ══════════════════════════════════════
-- WORDS — C1 (고급 논증 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_C1_01','dialectic','/ˌdaɪəˈlektɪk/','noun','변증법','A method of argument and inquiry based on the exchange of opposing views.','Hegel''s {dialectic} shapes much of modern philosophy.','헤겔의 변증법은 현대 철학의 많은 부분을 형성해요.','dialectic','C1','discussion',1,'philosophy dialectic thesis antithesis synthesis'),
('w_discussion_C1_02','proposition','/ˌprɒpəˈzɪʃən/','noun','명제, 제안','A statement or assertion that expresses a judgment or opinion.','Can you defend that {proposition} logically?','그 명제를 논리적으로 옹호할 수 있나요?','proposition','C1','discussion',1,'proposition statement logic argument board'),
('w_discussion_C1_03','syllogism','/ˈsɪlədʒɪzəm/','noun','삼단논법','A form of logical argument that applies deductive reasoning.','That argument follows the structure of a {syllogism}.','그 논거는 삼단논법의 구조를 따르고 있어요.','syllogism','C1','discussion',1,'syllogism logic deduction premises conclusion diagram'),
('w_discussion_C1_04','epistemology','/ɪˌpɪstɪˈmɒlədʒi/','noun','인식론','The branch of philosophy concerned with the nature and scope of knowledge.'{Epistemology} asks how we can know anything at all.','인식론은 우리가 어떻게 무언가를 알 수 있는지를 묻는 학문이에요.','Epistemology','C1','discussion',1,'philosophy knowledge epistemology brain book thinking'),
('w_discussion_C1_05','sophistry','/ˈsɒfɪstri/','noun','궤변, 교묘한 논리','The use of clever but misleading arguments.','His speech was nothing more than polished {sophistry}.','그의 연설은 세련된 궤변에 불과했어요.','sophistry','C1','discussion',1,'sophistry mislead clever trick argument illusion'),
('w_discussion_C1_06','axiom','/ˈæksiəm/','noun','공리, 자명한 이치','A statement taken to be self-evidently true as a basis for reasoning.','That is a philosophical {axiom} most scholars accept.','그것은 대부분의 학자들이 받아들이는 철학적 공리예요.','axiom','C1','discussion',1,'axiom self-evident truth foundation mathematics logic'),
('w_discussion_C1_07','inductive','/ɪnˈdʌktɪv/','adjective','귀납적인','Based on reasoning from specific observations to general principles.','She used {inductive} reasoning to build her theory.','그녀는 귀납적 추론을 사용해 이론을 구축했어요.','inductive','C1','discussion',1,'inductive reasoning observations generalizing science'),
('w_discussion_C1_08','deductive','/dɪˈdʌktɪv/','adjective','연역적인','Based on reasoning from general principles to specific conclusions.'{Deductive} arguments move from the general to the specific.','연역적 논증은 일반에서 특수로 나아가요.','Deductive','C1','discussion',1,'deductive logic tree diagram top down general specific'),
('w_discussion_C1_09','postulate','/ˈpɒstjʊleɪt/','verb/noun','가설을 세우다; 공준','To suggest or assume the existence of something as a basis for reasoning.','We can {postulate} a few principles to guide the discussion.','토론을 이끌 몇 가지 원칙을 가설로 설정할 수 있어요.','postulate','C1','discussion',1,'hypothesis postulate assumption principle research'),
('w_discussion_C1_10','refutation','/ˌrefjʊˈteɪʃən/','noun','반증, 논박','The action of proving a statement or theory to be wrong.','Her {refutation} dismantled the entire argument.','그녀의 반증은 논거 전체를 무너뜨렸어요.','refutation','C1','discussion',1,'refutation disprove demolish argument evidence'),
('w_discussion_C1_11','coherent','/kəʊˈhɪərənt/','adjective','일관성 있는, 논리적인','Logical and consistent; forming a unified whole.','Your argument is well structured and {coherent}.','당신의 주장은 잘 구성되고 일관성 있어요.','coherent','C1','discussion',1,'coherent argument logic organized unified flow'),
('w_discussion_C1_12','extrapolate','/ɪkˈstræpəleɪt/','verb','외삽하다, 추론하다','To extend conclusions beyond the known data.','We cannot safely {extrapolate} those results globally.','그 결과를 전 세계적으로 안전하게 추론할 수는 없어요.','extrapolate','C1','discussion',1,'extrapolate extend graph data projection future'),
('w_discussion_C1_13','conflate','/kənˈfleɪt/','verb','혼동하다, 혼재시키다','To combine two distinct things into one; to confuse two ideas.','Be careful not to {conflate} correlation with causation.','상관관계와 인과관계를 혼동하지 않도록 주의하세요.','conflate','C1','discussion',1,'conflate mixing confused two concepts overlap'),
('w_discussion_C1_14','nuanced','/ˈnjuːɑːnst/','adjective','미묘한 차이를 이해하는','Characterized by subtle distinctions; not black and white.','A {nuanced} reading of the evidence changes everything.','증거에 대한 미묘한 해석이 모든 것을 바꿔요.','nuanced','C1','discussion',1,'nuanced subtle complex shades grey interpretation'),
('w_discussion_C1_15','tautology','/tɔːˈtɒlədʒi/','noun','동어반복','Saying the same thing twice in different words; a circular argument.','That explanation is a {tautology}.','그 설명은 동어반복이에요.','tautology','C1','discussion',1,'circular argument loop tautology logic repeat'),
('w_discussion_C1_16','empirical','/ɪmˈpɪrɪkəl/','adjective','경험적인, 실증적인','Based on observation or experiment rather than theory.','We need {empirical} evidence, not just theory.','이론만이 아닌 실증적 증거가 필요해요.','empirical','C1','discussion',1,'empirical data lab science experiment observation'),
('w_discussion_C1_17','dichotomy','/daɪˈkɒtəmi/','noun','이분법, 이원 대립','A division or contrast between two things that are opposed.','The {dichotomy} between reason and emotion is too simplistic.','이성과 감정의 이분법은 너무 단순해요.','dichotomy','C1','discussion',1,'dichotomy two sides binary split divide'),
('w_discussion_C1_18','pragmatic','/præɡˈmætɪk/','adjective','실용적인','Dealing with things sensibly and practically; results-focused.','We need a more {pragmatic} approach here.','여기서는 더 실용적인 접근 방식이 필요해요.','pragmatic','C1','discussion',1,'pragmatic practical results hands-on approach tool'),
('w_discussion_C1_19','conjecture','/kənˈdʒektʃər/','noun/verb','추측, 억측','An opinion formed without sufficient evidence.','That is pure {conjecture} without supporting data.','그것은 뒷받침 데이터 없는 순전한 억측이에요.','conjecture','C1','discussion',1,'conjecture guess uncertain question cloud foggy'),
('w_discussion_C1_20','normative','/ˈnɔːmətɪv/','adjective','규범적인','Relating to what is considered standard or correct behavior.','This is a {normative} claim, not a factual one.','이것은 사실에 관한 주장이 아니라 규범에 관한 주장이에요.','normative','C1','discussion',1,'normative standard rule guideline social norms'),
('w_discussion_C1_21','stipulate','/ˈstɪpjʊleɪt/','verb','규정하다, 명시하다','To demand or specify as part of an agreement or argument.','Let''s {stipulate} the key terms before we begin.','시작하기 전에 핵심 용어를 명시해 봐요.','stipulate','C1','discussion',1,'stipulate define terms conditions contract formal'),
('w_discussion_C1_22','provisional','/prəˈvɪʒənl/','adjective','잠정적인, 일시적인','Arranged for the present but likely to change; tentative.','This is a {provisional} conclusion pending more data.','이것은 더 많은 데이터가 올 때까지 잠정적인 결론이에요.','provisional','C1','discussion',1,'provisional temporary draft pending update flexible'),
('w_discussion_C1_23','synthesize','/ˈsɪnθəsaɪz/','verb','종합하다','To combine different elements into a coherent whole.','Can you {synthesize} the arguments on both sides?','양쪽 주장을 종합할 수 있나요?','synthesize','C1','discussion',1,'synthesize combine merge integrate whole sum'),
('w_discussion_C1_24','rhetoric','/ˈretərɪk/','noun','수사학; 언변','The art of persuasion through language; sometimes used pejoratively.','That''s just political {rhetoric}, not substance.','그것은 내용이 아니라 정치적 언변일 뿐이에요.','rhetoric','C1','discussion',1,'rhetoric speech podium politician words persuade'),
('w_discussion_C1_25','premise','/ˈpremɪs/','noun','전제','A statement or assumption on which an argument is built.','Question the {premise}, not just the conclusion.','결론만이 아니라 전제를 의문시하세요.','premise','C1','discussion',1,'premise foundation base argument building blocks'),
('w_discussion_C1_26','analogical','/ˌænəˈlɒdʒɪkəl/','adjective','유추적인','Related to or based on comparison of similar cases.','He used an {analogical} argument to make his point.','그는 유추 논증을 사용해 요점을 전달했어요.','analogical','C1','discussion',1,'analogy comparison similar cases matching'),
('w_discussion_C1_27','credence','/ˈkriːdəns/','noun','신빙성, 신뢰','Belief in or acceptance of something as true.','I give little {credence} to that claim.','저는 그 주장에 신빙성을 거의 두지 않아요.','credence','C1','discussion',1,'credence belief trust credibility source'),
('w_discussion_C1_28','contention','/kənˈtenʃən/','noun','주장, 논쟁점','A heated disagreement; a point of contention in a dispute.','My central {contention} is that the data is flawed.','저의 핵심 주장은 그 데이터가 결함이 있다는 거예요.','contention','C1','discussion',1,'contention dispute central claim argument debate'),
('w_discussion_C1_29','underlying','/ˌʌndəˈlaɪɪŋ/','adjective','근본적인, 내재된','Forming a basis; the real cause beneath the surface.','The {underlying} assumption is never questioned.','근본적인 가정은 결코 의문시되지 않아요.','underlying','C1','discussion',1,'underlying foundation hidden below surface root'),
('w_discussion_C1_30','cogent','/ˈkəʊdʒənt/','adjective','설득력 있는, 논리적인','Clear, logical, and convincing.','Present a {cogent} argument and I will reconsider.','설득력 있는 주장을 제시해 주시면 다시 생각해 볼게요.','cogent','C1','discussion',1,'cogent clear sharp convincing logic star'),
('w_discussion_C1_31','hedging','/ˈhedʒɪŋ/','noun/gerund','언급 회피, 완화 표현','Using cautious language to avoid strong commitment.','Academic writing often relies on {hedging} language.','학술 글쓰기는 완화 표현에 자주 의존해요.','hedging','C1','discussion',1,'hedging cautious language qualifier perhaps maybe'),
('w_discussion_C1_32','categorical','/ˌkætɪˈɡɒrɪkəl/','adjective','단언적인, 절대적인','Unambiguous; without exceptions or conditions.','That is a {categorical} statement — are you sure?','그것은 단언적인 진술이에요. 확실한가요?','categorical','C1','discussion',1,'absolute certain definitive black white statement'),
('w_discussion_C1_33','tangential','/tænˈdʒenʃəl/','adjective','지엽적인, 핵심에서 벗어난','Diverging from or not directly relevant to the central point.','That remark is {tangential} to our main argument.','그 발언은 우리의 핵심 주장에서 지엽적이에요.','tangential','C1','discussion',1,'tangential off-topic aside circle diverge'),
('w_discussion_C1_34','mitigate','/ˈmɪtɪɡeɪt/','verb','완화하다, 경감하다','To make something less severe or serious.','That evidence does not fully {mitigate} the criticism.','그 증거가 비판을 완전히 완화하지는 않아요.','mitigate','C1','discussion',2,'mitigate reduce lessen soften effect impact'),
('w_discussion_C1_35','reconcile','/ˈrekənsaɪl/','verb','조화시키다, 화해하다','To make two opposing ideas or accounts consistent with each other.','Can you {reconcile} these two conflicting claims?','이 두 가지 상충하는 주장을 조화시킬 수 있나요?','reconcile','C1','discussion',1,'reconcile two sides bridge merge opposing peace');

-- ══════════════════════════════════════
-- WORDS — C2 (최고급 철학·담론 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_C2_01','hermeneutic','/ˌhɜːmɪˈnjuːtɪk/','adjective','해석학적인','Relating to the theory and methodology of interpretation.','A {hermeneutic} reading focuses on authorial intent.','해석학적 독해는 저자의 의도에 초점을 맞춰요.','hermeneutic','C2','discussion',1,'hermeneutics interpretation text meaning philosophy'),
('w_discussion_C2_02','aporia','/əˈpɔːriə/','noun','아포리아, 논리적 난점','A state of puzzlement; an apparently irresolvable logical difficulty.','The argument leads to an {aporia} that cannot be resolved.','그 논증은 해결할 수 없는 아포리아로 이어져요.','aporia','C2','discussion',1,'aporia deadlock paradox maze unsolvable problem'),
('w_discussion_C2_03','deconstruction','/ˌdiːkənˈstrʌkʃən/','noun','해체주의; 해체','A critical method of analysis that questions fixed meanings.'{Deconstruction} reveals the hidden assumptions in a text.','해체주의는 텍스트에 숨겨진 가정을 드러내요.','Deconstruction','C2','discussion',1,'deconstruction derrida text layers analyzing philosophy'),
('w_discussion_C2_04','logocentrism','/ˌlɒɡəʊˈsentrɪzəm/','noun','로고스중심주의','The assumption that language and written words are primary carriers of meaning.'{Logocentrism} privileges speech over writing, Derrida argued.','로고스중심주의는 데리다에 따르면 문자보다 말을 우선시해요.','Logocentrism','C2','discussion',1,'derrida philosophy language text speech center'),
('w_discussion_C2_05','intersubjectivity','/ˌɪntəˌsʌbdʒekˈtɪvɪti/','noun','상호주관성','The shared understanding and meaning among multiple people.'{Intersubjectivity} is the foundation of genuine dialogue.','상호주관성은 진정한 대화의 근거예요.','Intersubjectivity','C2','discussion',1,'intersubjective shared understanding mutual meaning people'),
('w_discussion_C2_06','discourse','/ˈdɪskɔːs/','noun','담론','A formal extended discussion or debate on a topic in writing or speech.','Power relations shape every {discourse}.','권력 관계는 모든 담론을 형성해요.','discourse','C2','discussion',1,'discourse power language society Foucault text'),
('w_discussion_C2_07','praxis','/ˈpræksis/','noun','실천, 프락시스','The process by which a theory or idea is enacted; practice as opposed to theory.','Theory without {praxis} remains abstract and empty.','실천 없는 이론은 추상적이고 공허해요.','praxis','C2','discussion',1,'praxis practice theory action implementation real'),
('w_discussion_C2_08','ontological','/ˌɒntəˈlɒdʒɪkəl/','adjective','존재론적인','Relating to the branch of philosophy concerned with being and existence.','That is an {ontological} question about the nature of reality.','그것은 현실의 본질에 관한 존재론적 질문이에요.','ontological','C2','discussion',1,'ontology being existence philosophy fundamental reality'),
('w_discussion_C2_09','paradigmatic','/ˌpærədɪɡˈmætɪk/','adjective','패러다임적인','Serving as a typical example or pattern of something.','This debate is {paradigmatic} of all post-modern conflicts.','이 논쟁은 모든 포스트모던 갈등의 패러다임이에요.','paradigmatic','C2','discussion',1,'paradigm shift example model pattern Kuhn'),
('w_discussion_C2_10','phenomenological','/fɪˌnɒmɪˈnɒlədʒɪkəl/','adjective','현상학적인','Relating to the study of conscious experience and how things appear.','A {phenomenological} approach centers lived experience.','현상학적 접근 방식은 살아있는 경험을 중심으로 해요.','phenomenological','C2','discussion',1,'phenomenology experience consciousness Husserl first person'),
('w_discussion_C2_11','teleological','/ˌteliəˈlɒdʒɪkəl/','adjective','목적론적인','Relating to the explanation of things in terms of their purpose or goal.','His {teleological} argument implies a designed universe.','그의 목적론적 논증은 설계된 우주를 암시해요.','teleological','C2','discussion',1,'teleology purpose goal direction arrow design universe'),
('w_discussion_C2_12','hegemony','/hɪˈdʒeməni/','noun','헤게모니, 패권','Leadership or dominance, especially of one country or social group over others.','We must examine the {hegemony} embedded in this narrative.','이 서사에 내재된 헤게모니를 검토해야 해요.','hegemony','C2','discussion',1,'hegemony power dominance ideology culture control'),
('w_discussion_C2_13','dialectical','/ˌdaɪəˈlektɪkəl/','adjective','변증법적인','Relating to the logical discussion of ideas through opposing arguments.','The {dialectical} method moves through contradiction to synthesis.','변증법적 방법은 모순을 통해 종합으로 나아가요.','dialectical','C2','discussion',1,'dialectic thesis antithesis synthesis Hegel flow'),
('w_discussion_C2_14','epistemological','/ɪˌpɪstɪməˈlɒdʒɪkəl/','adjective','인식론적인','Relating to the theory of knowledge and how we come to know things.','That is an {epistemological} claim about the limits of knowledge.','그것은 지식의 한계에 관한 인식론적 주장이에요.','epistemological','C2','discussion',1,'epistemology knowledge limits certainty philosophy books'),
('w_discussion_C2_15','poststructuralism','/ˌpəʊstˈstrʌktʃərəlɪzəm/','noun','포스트구조주의','A theory that questions the idea of fixed meanings and structures.'{Poststructuralism} challenges the stable subject of structuralism.','포스트구조주의는 구조주의의 안정적인 주체에 도전해요.','Poststructuralism','C2','discussion',1,'poststructuralism Derrida Foucault theory text language'),
('w_discussion_C2_16','intentionality','/ɪnˌtenʃəˈnælɪti/','noun','지향성','The property of mental states by which they are directed at something.'{Intentionality} is a key concept in phenomenology.','지향성은 현상학의 핵심 개념이에요.','Intentionality','C2','discussion',1,'intentionality directed mental state consciousness arrow'),
('w_discussion_C2_17','reification','/ˌriːɪfɪˈkeɪʃən/','noun','물상화','The process of treating an abstract concept as if it were a physical object.'{Reification} occurs when we treat society as a thing.','물상화는 사회를 하나의 사물로 취급할 때 발생해요.','Reification','C2','discussion',1,'reification abstract concrete thing object social concept'),
('w_discussion_C2_18','antinomy','/ænˈtɪnəmi/','noun','이율배반','A contradiction between two laws or principles.','Kant''s antinomies expose the limits of pure reason; this {antinomy} is unresolvable.','칸트의 이율배반은 순수 이성의 한계를 드러내요. 이 이율배반은 해결 불가능해요.','antinomy','C2','discussion',1,'kant antinomy contradiction paradox two truths'),
('w_discussion_C2_19','interlocutor','/ˌɪntəˈlɒkjʊtər/','noun','대화 상대자, 대담자','A person who takes part in a dialogue or conversation.','The {interlocutor} must be given space to respond fully.','대화 상대자에게 충분히 응할 공간을 주어야 해요.','interlocutor','C2','discussion',1,'dialogue interlocutor two people talk debate formal'),
('w_discussion_C2_20','verisimilitude','/ˌverɪsɪˈmɪlɪtjuːd/','noun','개연성, 진실다움','The appearance of being true or real.','The argument has {verisimilitude} but lacks proof.','그 논증은 진실다워 보이지만 증거가 없어요.','verisimilitude','C2','discussion',1,'verisimilitude lifelike plausible appearance true real'),
('w_discussion_C2_21','counterfactual','/ˌkaʊntəˈfæktʃuəl/','adjective/noun','반사실적; 반사실적 가정','Relating to what did not happen; a hypothetical contrary to fact.','A {counterfactual} argument imagines an alternative history.','반사실적 논증은 대안적 역사를 상상해요.','counterfactual','C2','discussion',1,'counterfactual what if alternate history hypothetical'),
('w_discussion_C2_22','solipsism','/ˈsɒlɪpsɪzəm/','noun','유아론','The view that only oneself and one''s mind can be known to exist.'{Solipsism} is the philosophical view that only your own mind is real.','유아론은 자신의 마음만이 실재한다는 철학적 관점이에요.','Solipsism','C2','discussion',1,'solipsism alone mind isolation philosophy self mirror'),
('w_discussion_C2_23','semiotics','/ˌsiːmiˈɒtɪks/','noun','기호학','The study of signs and symbols and their use or interpretation.'{Semiotics} examines how meaning is produced through signs.','기호학은 기호를 통해 의미가 어떻게 생성되는지 탐구해요.','Semiotics','C2','discussion',1,'semiotics signs symbols meaning language communication'),
('w_discussion_C2_24','apophenia','/ˌæpəˈfiːniə/','noun','아포피니아 (패턴 오인)','The tendency to perceive meaningful connections between unrelated things.'{Apophenia} can lead to seeing patterns where none exist.','아포피니아는 존재하지 않는 곳에서 패턴을 보게 만들어요.','Apophenia','C2','discussion',1,'apophenia pattern false connection dots brain error'),
('w_discussion_C2_25','qualia','/ˈkweɪliə/','noun','감각질','The internal, subjective conscious experiences — the redness of red.','Explaining {qualia} is the hard problem of consciousness.','감각질을 설명하는 것은 의식의 어려운 문제예요.','qualia','C2','discussion',1,'qualia consciousness subjective experience color sensation'),
('w_discussion_C2_26','metalanguage','/ˈmetəˌlæŋɡwɪdʒ/','noun','메타언어','Language used to describe or analyze another language or system.','We need a {metalanguage} to describe linguistic structure.','언어 구조를 설명하기 위해 메타언어가 필요해요.','metalanguage','C2','discussion',1,'metalanguage language about language abstract system'),
('w_discussion_C2_27','aphorism','/ˈæfərɪzəm/','noun','격언, 경구','A pithy observation expressing a general truth.','He opened the debate with an apt {aphorism}.','그는 적절한 격언으로 토론을 열었어요.','aphorism','C2','discussion',2,'aphorism quote wisdom brevity words profound short'),
('w_discussion_C2_28','equivocate','/ɪˈkwɪvəkeɪt/','verb','애매하게 말하다, 얼버무리다','To use ambiguous language in order to avoid committing to a position.','Stop {equivocating} and give me a direct answer.','애매하게 말하지 말고 직접적인 답을 주세요.','equivocating','C2','discussion',1,'equivocate vague dodge politician unclear hedging'),
('w_discussion_C2_29','polemic','/pəˈlemɪk/','noun','논전, 강한 반론','A strongly critical attack on a specific opinion or position.','The essay was a brilliant {polemic} against reductionism.','그 에세이는 환원주의에 대한 탁월한 논전이었어요.','polemic','C2','discussion',1,'polemic attack argument critique strong opposition text'),
('w_discussion_C2_30','irrefutable','/ɪˈrefjʊtəbəl/','adjective','반박할 수 없는','Impossible to deny or disprove.','The evidence was {irrefutable}.','그 증거는 반박할 수 없었어요.','irrefutable','C2','discussion',1,'irrefutable undeniable solid proof rock wall unshakeable'),
('w_discussion_C2_31','Weltanschauung','/ˌveltˌɑːnˈʃaʊʊŋ/','noun','세계관 (독어 차용)','A comprehensive world view or philosophy of life.','Our disagreement stems from different {Weltanschauungen}.','우리의 의견 충돌은 서로 다른 세계관에서 비롯돼요.','Weltanschauung','C2','discussion',1,'worldview Weltanschauung philosophy culture glasses seeing'),
('w_discussion_C2_32','doxa','/ˈdɒksə/','noun','독사, 통념','Common belief or popular opinion; unexamined assumption.','To challenge {doxa} is the task of critical philosophy.','통념에 도전하는 것이 비판 철학의 과제예요.','doxa','C2','discussion',1,'doxa common opinion Bourdieu belief unquestioned norm'),
('w_discussion_C2_33','heterodox','/ˈhetərədɒks/','adjective','이단적인, 비정통적인','Not conforming to orthodox or established views or beliefs.','That is a {heterodox} position within the field.','그것은 해당 분야에서 비정통적인 입장이에요.','heterodox','C2','discussion',1,'heterodox unorthodox minority view dissent fringe'),
('w_discussion_C2_34','metacognition','/ˌmetəkɒɡˈnɪʃən/','noun','메타인지','Awareness and understanding of one''s own thought processes.'{Metacognition} allows us to evaluate the quality of our own reasoning.','메타인지는 우리 자신의 추론 질을 평가하게 해줘요.','Metacognition','C2','discussion',1,'metacognition thinking about thinking brain self-awareness'),
('w_discussion_C2_35','apodeictic','/ˌæpəˈdaɪktɪk/','adjective','논증적으로 확실한','Clearly established; beyond contradiction; necessarily true.','His {apodeictic} proof left no room for doubt.','그의 논증적으로 확실한 증명에는 의심의 여지가 없었어요.','apodeictic','C2','discussion',1,'certainty proof absolute necessity logic formal demonstration');

-- ══════════════════════════════════════
-- PATTERNS — A1 (기초 의견 말하기)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_A1_01','I think so too.','저도 그렇게 생각해요.','I think so','동의를 표현할 때 "I think so too."는 가장 자연스러운 표현이에요. "Me too."보다 대화가 이어지기 쉬워요.','동의','A1','discussion','pattern',NULL,1),
('s_discussion_A1_02','I don''t think that''s right.','그게 맞지 않는 것 같아요.','I don''t think','부드럽게 반대할 때 "I don''t think ~"를 쓰면 "You''re wrong."보다 훨씬 자연스러워요.','반대','A1','discussion','pattern',NULL,2),
('s_discussion_A1_03','What do you think about this?','이것에 대해 어떻게 생각해요?','What do you think','상대방의 의견을 구할 때 쓰는 가장 기본적인 표현이에요.','의견 묻기','A1','discussion','pattern',NULL,3),
('s_discussion_A1_04','I like your idea.','당신의 생각이 좋아요.','I like your idea','칭찬하며 동의할 때 "I like your idea."는 따뜻하고 간단한 표현이에요.','칭찬','A1','discussion','pattern',NULL,4),
('s_discussion_A1_05','Maybe you are right.','아마 당신이 맞을 수도 있어요.','Maybe you are right','확신이 없지만 상대방의 의견을 인정할 때 쓰는 표현이에요.','부분 동의','A1','discussion','pattern',NULL,5),
('s_discussion_A1_06','Can I say something?','한 마디 해도 될까요?','Can I say something','대화에 끼어들 때 가장 예의 바른 표현 중 하나예요.','발언권','A1','discussion','pattern',NULL,6),
('s_discussion_A1_07','I''m not sure about that.','그것에 대해서는 잘 모르겠어요.','I''m not sure','확신이 없을 때 직접적으로 부정하지 않고 쓸 수 있는 안전한 표현이에요.','불확실','A1','discussion','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — A2 (동의 · 반대 표현)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_A2_01','I agree with you on that point.','그 점에서는 당신과 동의해요.','agree with you on that point','특정 요점에만 동의할 때 "on that point"를 붙이면 더 정확한 표현이 돼요.','부분 동의','A2','discussion','pattern',NULL,1),
('s_discussion_A2_02','I''m afraid I disagree with that.','유감스럽게도 그것에 동의하지 않아요.','I''m afraid I disagree','정중하게 반대할 때 "I''m afraid"를 앞에 붙이면 부드러운 어조가 돼요.','정중한 반대','A2','discussion','pattern',NULL,2),
('s_discussion_A2_03','Could you explain that again, please?','다시 한번 설명해 주실 수 있나요?','explain that again','이해하지 못했을 때 자연스럽게 다시 묻는 표현이에요.','이해 확인','A2','discussion','pattern',NULL,3),
('s_discussion_A2_04','That''s a good point, but I think...','좋은 지적이에요, 하지만 저는...','That''s a good point, but','상대방을 인정하면서 자신의 의견을 제시하는 균형 잡힌 표현이에요.','균형 있는 반론','A2','discussion','pattern',NULL,4),
('s_discussion_A2_05','In my opinion, the best way is...','제 의견으로는 가장 좋은 방법은...','In my opinion','의견을 말할 때 "In my opinion"으로 시작하면 사실이 아닌 의견임을 명확히 해요.','의견 제시','A2','discussion','pattern',NULL,5),
('s_discussion_A2_06','I see your point, but I''m not convinced.','당신의 요점은 이해해요, 하지만 납득은 안 돼요.','I see your point, but','상대방의 관점을 인정하면서도 설득되지 않았을 때 쓰는 표현이에요.','동의 안 됨','A2','discussion','pattern',NULL,6),
('s_discussion_A2_07','Can you give me an example?','예시를 들어줄 수 있나요?','Can you give me an example','추상적인 주장을 구체화해 달라고 요청할 때 쓰는 표현이에요.','예시 요청','A2','discussion','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — B1 (근거 제시 · 토론)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_B1_01','Based on the evidence, I would argue that...','증거에 근거하면, 저는 ~라고 주장하겠어요.','Based on the evidence','근거를 제시할 때 "Based on the evidence"로 시작하면 논리적이고 신뢰감 있는 발언이 돼요.','근거 제시','B1','discussion','pattern',NULL,1),
('s_discussion_B1_02','My main point is that we need to consider both sides.','제 핵심 요점은 양쪽을 모두 고려해야 한다는 거예요.','My main point is that','핵심 논점을 명확히 전달할 때 "My main point is that"으로 강조해요.','핵심 주장','B1','discussion','pattern',NULL,2),
('s_discussion_B1_03','Although I understand your perspective, I believe that...','당신의 관점을 이해하지만, 저는 ~라고 생각해요.','Although I understand your perspective','반론을 제기하면서도 상대를 존중하는 표현이에요.','공손한 반론','B1','discussion','pattern',NULL,3),
('s_discussion_B1_04','Could you elaborate on that point a little more?','그 부분을 좀 더 자세히 설명해 주실 수 있나요?','Could you elaborate','상대방의 주장에 더 깊은 설명을 요청할 때 쓰는 표현이에요.','설명 요청','B1','discussion','pattern',NULL,4),
('s_discussion_B1_05','To support my argument, I would like to point out that...','제 주장을 뒷받침하기 위해, ~라는 점을 지적하고 싶어요.','To support my argument','논거를 제시하면서 구조적인 발언을 할 때 쓰는 표현이에요.','논거 제시','B1','discussion','pattern',NULL,5),
('s_discussion_B1_06','I think we should also consider the other side of the argument.','주장의 반대편도 고려해야 한다고 생각해요.','consider the other side','한쪽 의견에 치우치지 않고 균형을 제안할 때 쓰는 표현이에요.','균형 제안','B1','discussion','pattern',NULL,6),
('s_discussion_B1_07','Let me give you a concrete example to illustrate my point.','제 요점을 설명하기 위해 구체적인 예시를 들어볼게요.','a concrete example to illustrate','추상적인 주장을 예시로 구체화할 때 쓰는 표현이에요.','예시 제공','B1','discussion','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — B2 (반론 · 비판적 사고)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_B2_01','While I appreciate your argument, I would like to challenge the underlying premise.','당신의 주장은 가치 있지만, 근본적인 전제에 이의를 제기하고 싶어요.','challenge the underlying premise','단순 반박이 아니라 전제 자체를 문제 삼는 고급 토론 기술이에요.','전제 도전','B2','discussion','pattern',NULL,1),
('s_discussion_B2_02','There is a logical inconsistency in your reasoning that I think needs to be addressed.','당신의 논리에 다뤄야 할 논리적 모순이 있어요.','logical inconsistency','논리적 결함을 직접 지적할 때 쓰는 표현이에요.','논리적 모순 지적','B2','discussion','pattern',NULL,2),
('s_discussion_B2_03','I would argue that your conclusion does not necessarily follow from the evidence.','당신의 결론이 반드시 증거에서 나온다고 볼 수 없어요.','does not necessarily follow','"necessarily follow"는 논리적 귀결이 약함을 지적하는 표현이에요.','귀결 약점 지적','B2','discussion','pattern',NULL,3),
('s_discussion_B2_04','With all due respect, I think there is a flaw in that reasoning.','정중히 말씀드리지만, 그 논리에 결함이 있다고 생각해요.','With all due respect','격식 있는 자리에서 반박할 때 "With all due respect"로 시작하면 예의를 지킬 수 있어요.','격식 있는 반박','B2','discussion','pattern',NULL,4),
('s_discussion_B2_05','That may be true in some cases, but we need to consider whether it holds universally.','어떤 경우에는 사실일 수 있지만, 보편적으로 적용되는지 고려해야 해요.','holds universally','일반화의 위험을 지적할 때 "holds universally"라는 표현이 효과적이에요.','일반화 경계','B2','discussion','pattern',NULL,5),
('s_discussion_B2_06','I would like to offer a counterargument to what has just been said.','방금 말씀하신 것에 대한 반론을 제시하고 싶어요.','offer a counterargument','반론을 시작하는 격식 있는 표현이에요.','반론 제시','B2','discussion','pattern',NULL,6),
('s_discussion_B2_07','Let''s not conflate correlation with causation — these are two very different things.','상관관계와 인과관계를 혼동하지 말아요. 이 두 가지는 전혀 다른 개념이에요.','conflate correlation with causation','토론에서 자주 발생하는 오류를 지적하는 강력한 표현이에요.','논리 오류 지적','B2','discussion','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — C1 (논증 · 철학적 토론)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_C1_01','Your argument appears to rest on a tautological premise — the conclusion is assumed in the question itself.','당신의 주장은 동어반복적인 전제에 기대는 것 같아요. 결론이 질문 자체에 이미 전제되어 있어요.','tautological premise','동어반복적 전제를 지적하는 것은 고급 논리적 비판 기술이에요.','논리 분석','C1','discussion','pattern',NULL,1),
('s_discussion_C1_02','I think it is important to distinguish between what is normatively desirable and what is empirically demonstrable.','규범적으로 바람직한 것과 경험적으로 입증 가능한 것을 구별하는 것이 중요해요.','normatively desirable and what is empirically demonstrable','사실과 당위를 구별하는 철학적 논의에서 핵심 표현이에요.','사실 vs 규범','C1','discussion','pattern',NULL,2),
('s_discussion_C1_03','Could you clarify whether you are making an inductive or deductive argument here?','여기서 귀납적 논증을 하는 건지, 연역적 논증을 하는 건지 명확히 해줄 수 있나요?','inductive or deductive argument','논증 유형을 묻는 것은 상대방의 논리 구조를 명확히 하는 기술이에요.','논증 유형 확인','C1','discussion','pattern',NULL,3),
('s_discussion_C1_04','To synthesize the arguments on both sides, I would propose the following reconciliation.','양쪽 주장을 종합하기 위해 다음의 화해안을 제안하고 싶어요.','synthesize the arguments on both sides','변증법적 종합을 제안하는 표현이에요.','종합 제안','C1','discussion','pattern',NULL,4),
('s_discussion_C1_05','The strength of your argument is undermined by the lack of empirical evidence.','경험적 증거의 부족이 당신 주장의 강점을 약화시켜요.','undermined by the lack of empirical evidence','주장의 약점을 핵심 단어로 짚어주는 표현이에요.','주장 약점 지적','C1','discussion','pattern',NULL,5),
('s_discussion_C1_06','I would like to postulate three conditions under which this claim holds true.','이 주장이 참인 세 가지 조건을 가설로 설정하고 싶어요.','postulate three conditions under which','조건부 주장을 제시하는 고급 토론 방식이에요.','조건부 주장','C1','discussion','pattern',NULL,6),
('s_discussion_C1_07','It seems to me that you are committing the fallacy of the excluded middle.','중간 배제의 오류를 범하고 있는 것 같아요.','the fallacy of the excluded middle','논리학의 구체적인 오류를 지적할 수 있으면 토론 수준이 크게 높아져요.','논리 오류 명명','C1','discussion','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — C2 (철학적 담론 · 해체적 토론)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_C2_01','The very discourse within which this debate operates already prejudges the answer through its logocentric assumptions.','이 토론이 작동하는 담론 자체가 이미 로고스중심주의적 가정을 통해 답을 미리 결정하고 있어요.','discourse within which this debate operates already prejudges','데리다적 해체 관점에서 담론 구조 자체를 비판하는 고급 표현이에요.','담론 해체','C2','discussion','pattern',NULL,1),
('s_discussion_C2_02','What you are describing is not merely an empirical question but a deeply ontological one about the nature of being itself.','당신이 설명하는 것은 단순한 경험적 질문이 아니라 존재 자체의 본질에 관한 깊은 존재론적 질문이에요.','not merely an empirical question but a deeply ontological one','경험적 질문과 존재론적 질문을 구분하는 철학적 표현이에요.','존재론적 재정의','C2','discussion','pattern',NULL,2),
('s_discussion_C2_03','I would contend that this argument leads us to an aporia — a point at which the very terms of the debate become irresolvably contradictory.','이 논증이 아포리아, 즉 토론의 용어 자체가 해결 불가능하게 모순되는 지점으로 이어진다고 주장하고 싶어요.','leads us to an aporia','아포리아의 개념을 토론에서 직접 활용하는 최고급 표현이에요.','아포리아 지적','C2','discussion','pattern',NULL,3),
('s_discussion_C2_04','The intersubjective validity of your claim depends on whether the shared lifeworld of the participants actually supports it.','당신 주장의 상호주관적 타당성은 참여자들의 공유된 생활세계가 실제로 그것을 지지하는지에 달려 있어요.','intersubjective validity','하버마스의 의사소통 이성을 적용한 고급 철학적 토론 표현이에요.','상호주관성 적용','C2','discussion','pattern',NULL,4),
('s_discussion_C2_05','This apparent antinomy dissolves once we distinguish between the constitutive and regulatory functions of the principle in question.','이 겉보기 이율배반은 문제의 원리의 구성적 기능과 규제적 기능을 구분하면 사라져요.','antinomy dissolves once we distinguish','칸트의 이율배반을 실제 토론에 적용한 심화 표현이에요.','이율배반 해소','C2','discussion','pattern',NULL,5),
('s_discussion_C2_06','What we are witnessing here is a paradigmatic case of reification — we are treating a complex social process as though it were a fixed, natural object.','여기서 우리가 목격하는 것은 물상화의 패러다임적 사례예요. 우리는 복잡한 사회적 과정을 고정된 자연적 대상처럼 취급하고 있어요.','paradigmatic case of reification','마르크스와 루카치의 물상화 개념을 토론에서 활용하는 방법이에요.','물상화 비판','C2','discussion','pattern',NULL,6),
('s_discussion_C2_07','A truly rigorous analysis requires us to suspend our doxa and examine the phenomenological structure of the experience before we theorize about it.','진정으로 엄밀한 분석은 우리의 통념을 중지하고, 이론화하기 전에 경험의 현상학적 구조를 검토하도록 요구해요.','suspend our doxa and examine the phenomenological structure','후설의 현상학적 판단 중지와 부르디외의 독사를 결합한 최고 수준의 토론 표현이에요.','현상학적 판단 중지','C2','discussion','pattern',NULL,7);
