-- EngCat — Negotiation (협상) 단어 & 패턴 데이터
-- 210 words (35 per CEFR level A1~C2) + 42 patterns (7 per level)
-- topic_id: 'negotiation'

-- ══════════════════════════════════════
-- WORDS — A1 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_negotiation_A1_01','want','/wɒnt/','verb','원하다','To feel a desire or wish for something.','What do you {want}?','뭘 원하세요?','want','A1','negotiation',1,'negotiation business handshake agreement'),
('w_negotiation_A1_02','need','/niːd/','verb','필요하다','To require something because it is essential.','I {need} more time, please.','시간이 더 필요해요.','need','A1','negotiation',1,'need requirement essential document'),
('w_negotiation_A1_03','give','/ɡɪv/','verb','주다','To hand something over to someone.','Can you {give} me a better price?','더 좋은 가격을 주실 수 있나요?','give','A1','negotiation',1,'give handover exchange offer table'),
('w_negotiation_A1_04','take','/teɪk/','verb','받다, 가져가다','To receive or accept something offered.','I will {take} the deal.','그 거래로 할게요.','take','A1','negotiation',1,'take accept deal handshake office'),
('w_negotiation_A1_05','agree','/əˈɡriː/','verb','동의하다','To have the same opinion or to accept a proposal.','Do you {agree} with this?','이것에 동의하시나요?','agree','A1','negotiation',1,'agree nod yes handshake meeting'),
('w_negotiation_A1_06','ask','/ɑːsk/','verb','묻다, 요청하다','To request information or a favour from someone.','I want to {ask} for a discount.','할인을 요청하고 싶어요.','ask','A1','negotiation',1,'ask question request office discussion'),
('w_negotiation_A1_07','offer','/ˈɒfər/','noun','제안, 제공','Something presented for acceptance or rejection.','That is a good {offer}.','좋은 제안이에요.','offer','A1','negotiation',1,'offer proposal document business desk'),
('w_negotiation_A1_08','deal','/diːl/','noun','거래','An agreement, especially in business.','Let''s make a {deal}.','거래합시다.','deal','A1','negotiation',1,'deal handshake business contract signing'),
('w_negotiation_A1_09','yes','/jes/','interjection','네','Used to give an affirmative response.','I say {yes} to your offer.','당신의 제안에 동의해요.','yes','A1','negotiation',1,'yes agree nod smile business meeting'),
('w_negotiation_A1_10','no','/nəʊ/','interjection','아니요','Used to give a negative response.','I must say {no} to that price.','그 가격은 거절해야 해요.','no','A1','negotiation',1,'no reject decline gesture business'),
('w_negotiation_A1_11','pay','/peɪ/','verb','지불하다','To give money in exchange for goods or services.','How much do I {pay}?','얼마를 내야 하나요?','pay','A1','negotiation',1,'pay money cash exchange business'),
('w_negotiation_A1_12','buy','/baɪ/','verb','사다','To obtain something by paying money for it.','I want to {buy} this item.','이 물건을 사고 싶어요.','buy','A1','negotiation',1,'buy purchase store shopping decision'),
('w_negotiation_A1_13','sell','/sel/','verb','팔다','To give something in exchange for money.','I want to {sell} at a good price.','좋은 가격에 팔고 싶어요.','sell','A1','negotiation',1,'sell vendor market transaction business'),
('w_negotiation_A1_14','help','/help/','verb','도와주다','To make it easier for someone to do something.','Can you {help} me with this?','이것 좀 도와주실 수 있나요?','help','A1','negotiation',1,'help assist support colleague office'),
('w_negotiation_A1_15','talk','/tɔːk/','verb','이야기하다','To speak or have a conversation.','Let''s {talk} about the price.','가격에 대해 이야기해 봐요.','talk','A1','negotiation',1,'talk conversation meeting discussion business'),
('w_negotiation_A1_16','meet','/miːt/','verb','만나다','To come together with someone.','We need to {meet} and discuss.','만나서 논의해야 해요.','meet','A1','negotiation',1,'meet conference room business handshake'),
('w_negotiation_A1_17','start','/stɑːt/','verb','시작하다','To begin something.','Let''s {start} the discussion.','논의를 시작합시다.','start','A1','negotiation',1,'start begin meeting kickoff business'),
('w_negotiation_A1_18','stop','/stɒp/','verb','멈추다','To cease doing something.','Please {stop} and listen.','멈추고 들어주세요.','stop','A1','negotiation',2,'stop pause listen attention meeting'),
('w_negotiation_A1_19','know','/nəʊ/','verb','알다','To have information about something.','Do you {know} the price?','가격을 알고 계신가요?','know','A1','negotiation',2,'know information data business laptop'),
('w_negotiation_A1_20','think','/θɪŋk/','verb','생각하다','To have a particular opinion or idea.','I {think} we can do better.','더 잘할 수 있다고 생각해요.','think','A1','negotiation',2,'think consider ponder business person'),
('w_negotiation_A1_21','say','/seɪ/','verb','말하다','To express something in words.','What did you {say} about delivery?','납품에 대해 뭐라고 하셨나요?','say','A1','negotiation',2,'say speak communicate conversation business'),
('w_negotiation_A1_22','come','/kʌm/','verb','오다','To move toward or arrive at a place.','Can you {come} to our office?','저희 사무실로 오실 수 있나요?','come','A1','negotiation',2,'come arrive meeting office professional'),
('w_negotiation_A1_23','show','/ʃəʊ/','verb','보여주다','To let someone see something.','Please {show} me the contract.','계약서를 보여 주세요.','show','A1','negotiation',2,'show document present contract office'),
('w_negotiation_A1_24','look','/lʊk/','verb','보다','To direct your eyes toward something.','Please {look} at this proposal.','이 제안서를 봐 주세요.','look','A1','negotiation',2,'look review document proposal office'),
('w_negotiation_A1_25','wait','/weɪt/','verb','기다리다','To stay in one place until something happens.','Please {wait} while I check.','확인하는 동안 잠깐 기다려 주세요.','wait','A1','negotiation',2,'wait patience clock office professional'),
('w_negotiation_A1_26','go','/ɡəʊ/','verb','진행하다','To proceed with something.','Let''s {go} with that plan.','그 계획으로 진행합시다.','go','A1','negotiation',2,'go proceed forward business plan decision'),
('w_negotiation_A1_27','get','/ɡet/','verb','얻다','To receive or obtain something.','I hope we both {get} what we need.','우리 둘 다 필요한 것을 얻으면 좋겠어요.','get','A1','negotiation',2,'get obtain receive result business'),
('w_negotiation_A1_28','try','/traɪ/','verb','시도하다','To make an effort to do something.','I will {try} to lower the price.','가격을 낮춰 보겠습니다.','try','A1','negotiation',2,'try effort attempt business negotiation'),
('w_negotiation_A1_29','open','/ˈəʊpən/','adjective','열린','Willing to consider new ideas or suggestions.','I am {open} to suggestions.','제안에 열려 있어요.','open','A1','negotiation',2,'open door opportunity flexible business'),
('w_negotiation_A1_30','free','/friː/','adjective','무료의','Available without payment.','Is this service {free}?','이 서비스는 무료인가요?','free','A1','negotiation',2,'free no cost service benefit offer'),
('w_negotiation_A1_31','sign','/saɪn/','verb','서명하다','To write your name on a document to authorize it.','Please {sign} here.','여기에 서명해 주세요.','sign','A1','negotiation',1,'sign document contract pen signature'),
('w_negotiation_A1_32','read','/riːd/','verb','읽다','To look at and understand written text.','Please {read} the agreement.','계약서를 읽어 보세요.','read','A1','negotiation',2,'read document agreement paper office'),
('w_negotiation_A1_33','change','/tʃeɪndʒ/','verb','바꾸다','To make something different.','Can we {change} the date?','날짜를 바꿀 수 있나요?','change','A1','negotiation',2,'change adjust modify calendar schedule'),
('w_negotiation_A1_34','best','/best/','adjective','최선의','Of the highest quality or most suitable.','This is our {best} offer.','이것이 저희의 최선의 제안이에요.','best','A1','negotiation',1,'best top quality offer business deal'),
('w_negotiation_A1_35','more','/mɔːr/','determiner','더 많은','A greater amount or degree.','Can we get {more} time?','시간을 더 받을 수 있을까요?','more','A1','negotiation',2,'more extra additional request business');

-- ══════════════════════════════════════
-- WORDS — A2 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_negotiation_A2_01','price','/praɪs/','noun','가격','The amount of money expected or required for something.','Can you lower the {price}?','가격을 낮춰 주실 수 있나요?','price','A2','negotiation',1,'price tag cost money business negotiation'),
('w_negotiation_A2_02','discount','/ˈdɪskaʊnt/','noun','할인','A reduction in the usual price.','I''d like a {discount} on this order.','이번 주문에 할인을 받고 싶어요.','discount','A2','negotiation',1,'discount sale reduction price tag store'),
('w_negotiation_A2_03','accept','/əkˈsept/','verb','수락하다','To agree to receive or take something offered.','I {accept} your proposal.','제안을 수락합니다.','accept','A2','negotiation',1,'accept agree handshake deal business'),
('w_negotiation_A2_04','refuse','/rɪˈfjuːz/','verb','거절하다','To say you will not accept or do something.','I have to {refuse} this offer.','이 제안을 거절해야 해요.','refuse','A2','negotiation',1,'refuse decline reject gesture business'),
('w_negotiation_A2_05','propose','/prəˈpəʊz/','verb','제안하다','To put forward a plan or idea for consideration.','I would like to {propose} a solution.','해결책을 제안하고 싶어요.','propose','A2','negotiation',1,'propose suggest solution meeting whiteboard'),
('w_negotiation_A2_06','condition','/kənˈdɪʃən/','noun','조건','A requirement that must be met for something to happen.','What are your {conditions}?','조건이 어떻게 되나요?','conditions','A2','negotiation',1,'condition requirement checklist contract terms'),
('w_negotiation_A2_07','term','/tɜːm/','noun','조항','A condition or requirement that is part of an agreement.','Let''s review the payment {terms}.','결제 조항을 검토해 봐요.','terms','A2','negotiation',1,'term clause contract document review office'),
('w_negotiation_A2_08','fair','/feər/','adjective','공정한','Treating people equally and according to the rules.','We want a {fair} deal for both sides.','양측 모두에게 공정한 거래를 원해요.','fair','A2','negotiation',1,'fair balance scales justice business equal'),
('w_negotiation_A2_09','both','/bəʊθ/','determiner','양쪽 모두','Two people or things considered together.','This benefits {both} parties.','이것은 양쪽 모두에게 이익이 돼요.','both','A2','negotiation',2,'both parties two sides meeting table agreement'),
('w_negotiation_A2_10','together','/təˈɡeðər/','adverb','함께','With each other or in the same place.','We can work {together} on this.','이것을 함께 해결할 수 있어요.','together','A2','negotiation',2,'together teamwork collaboration business partners'),
('w_negotiation_A2_11','budget','/ˈbʌdʒɪt/','noun','예산','The amount of money available for spending.','We have a limited {budget}.','예산이 제한되어 있어요.','budget','A2','negotiation',1,'budget finance money plan spreadsheet'),
('w_negotiation_A2_12','payment','/ˈpeɪmənt/','noun','결제, 지불','The action of paying for something.','Can we split the {payment}?','결제를 나눌 수 있나요?','payment','A2','negotiation',1,'payment invoice finance transaction business'),
('w_negotiation_A2_13','delivery','/dɪˈlɪvəri/','noun','납품, 배송','The process of bringing goods to a customer.','When can you guarantee {delivery}?','납품을 언제 보장할 수 있나요?','delivery','A2','negotiation',1,'delivery shipping logistics package truck'),
('w_negotiation_A2_14','deadline','/ˈdedlaɪn/','noun','마감일','The latest time for completing something.','The {deadline} is non-negotiable.','마감일은 협상이 안 돼요.','deadline','A2','negotiation',1,'deadline calendar clock urgency office'),
('w_negotiation_A2_15','contract','/ˈkɒntrækt/','noun','계약서','A written agreement that is legally binding.','Please sign the {contract}.','계약서에 서명해 주세요.','contract','A2','negotiation',1,'contract document signature pen legal'),
('w_negotiation_A2_16','agree on','/əˈɡriː ɒn/','phrase','~에 합의하다','To reach a shared decision about something.','Can we {agree on} a price?','가격에 합의할 수 있을까요?','agree on','A2','negotiation',1,'agree consensus decision meeting handshake'),
('w_negotiation_A2_17','reduce','/rɪˈdjuːs/','verb','줄이다','To make something smaller or less.','Can you {reduce} the delivery time?','납품 시간을 줄일 수 있나요?','reduce','A2','negotiation',2,'reduce decrease lower cost business chart'),
('w_negotiation_A2_18','increase','/ɪnˈkriːs/','verb','늘리다','To become or make greater in number or amount.','We need to {increase} the quantity.','수량을 늘려야 해요.','increase','A2','negotiation',2,'increase quantity order growth business chart'),
('w_negotiation_A2_19','option','/ˈɒpʃən/','noun','선택지','A thing that is or may be chosen.','What {options} do we have?','어떤 선택지가 있나요?','options','A2','negotiation',1,'options choices alternatives decision business'),
('w_negotiation_A2_20','flexible','/ˈfleksɪbəl/','adjective','유연한','Willing to change or compromise.','Are you {flexible} on the date?','날짜는 유연하게 조정할 수 있나요?','flexible','A2','negotiation',1,'flexible adjust adapt business negotiation'),
('w_negotiation_A2_21','confirm','/kənˈfɜːm/','verb','확인하다','To state that something is definitely true or agreed.','Please {confirm} the order details.','주문 세부 사항을 확인해 주세요.','confirm','A2','negotiation',2,'confirm check email document office verification'),
('w_negotiation_A2_22','include','/ɪnˈkluːd/','verb','포함하다','To have something as part of a whole.','Does this {include} installation?','이것은 설치가 포함되나요?','include','A2','negotiation',2,'include contain package service checklist'),
('w_negotiation_A2_23','final','/ˈfaɪnəl/','adjective','최종의','Coming at the end; last.','This is our {final} offer.','이것이 저희의 최종 제안이에요.','final','A2','negotiation',1,'final last offer document decision business'),
('w_negotiation_A2_24','extra','/ˈekstrə/','adjective','추가적인','More than is usual, expected, or necessary.','Can you add any {extra} benefits?','추가 혜택을 더해 주실 수 있나요?','extra','A2','negotiation',2,'extra bonus additional benefit offer business'),
('w_negotiation_A2_25','total','/ˈtəʊtəl/','noun','총계','The whole amount.','What is the {total} cost?','총 비용이 얼마인가요?','total','A2','negotiation',2,'total sum cost invoice finance calculation'),
('w_negotiation_A2_26','quickly','/ˈkwɪkli/','adverb','빠르게','At a fast rate.','We need to decide {quickly}.','빨리 결정해야 해요.','quickly','A2','negotiation',2,'quickly fast urgent decision business clock'),
('w_negotiation_A2_27','improve','/ɪmˈpruːv/','verb','개선하다','To make something better.','Can you {improve} the terms?','조건을 개선해 줄 수 있나요?','improve','A2','negotiation',2,'improve better enhance business terms document'),
('w_negotiation_A2_28','package','/ˈpækɪdʒ/','noun','패키지, 묶음 제안','A set of things offered or agreed to as a whole.','We prefer a full service {package}.','전체 서비스 패키지를 선호해요.','package','A2','negotiation',2,'package bundle service offer business deal'),
('w_negotiation_A2_29','cancel','/ˈkænsəl/','verb','취소하다','To decide that something that was arranged will no longer happen.','We may {cancel} if terms don''t improve.','조건이 개선되지 않으면 취소할 수도 있어요.','cancel','A2','negotiation',2,'cancel stop terminate contract business'),
('w_negotiation_A2_30','urgent','/ˈɜːrdʒənt/','adjective','긴급한','Requiring immediate action or attention.','This is an {urgent} matter.','긴급한 사안이에요.','urgent','A2','negotiation',2,'urgent priority alarm clock business deadline'),
('w_negotiation_A2_31','respond','/rɪˈspɒnd/','verb','응답하다','To say something in reply.','Please {respond} by Friday.','금요일까지 응답해 주세요.','respond','A2','negotiation',2,'respond reply email message office'),
('w_negotiation_A2_32','expect','/ɪkˈspekt/','verb','기대하다','To believe something will happen.','We {expect} a 10% discount.','10% 할인을 기대하고 있어요.','expect','A2','negotiation',2,'expect anticipate business meeting discussion'),
('w_negotiation_A2_33','benefit','/ˈbenɪfɪt/','noun','혜택','An advantage or profit gained from something.','What {benefits} are included?','어떤 혜택이 포함되나요?','benefits','A2','negotiation',1,'benefit advantage gain profit business'),
('w_negotiation_A2_34','reach','/riːtʃ/','verb','도달하다','To succeed in achieving something.','We need to {reach} an agreement today.','오늘 합의에 도달해야 해요.','reach','A2','negotiation',1,'reach agreement goal destination business'),
('w_negotiation_A2_35','willing','/ˈwɪlɪŋ/','adjective','기꺼이 하는','Ready to do something.','Are you {willing} to negotiate?','협상할 의사가 있으신가요?','willing','A2','negotiation',1,'willing agree openness discussion business meeting');

-- ══════════════════════════════════════
-- WORDS — B1 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_negotiation_B1_01','negotiate','/nɪˈɡəʊʃieɪt/','verb','협상하다','To discuss something formally to reach an agreement.','We need to {negotiate} the final price.','최종 가격을 협상해야 해요.','negotiate','B1','negotiation',1,'negotiate discuss deal table business professional'),
('w_negotiation_B1_02','compromise','/ˈkɒmprəmaɪz/','noun','타협','An agreement reached by each side making concessions.','A {compromise} is necessary here.','여기서 타협이 필요해요.','compromise','B1','negotiation',1,'compromise balance middle ground business agreement'),
('w_negotiation_B1_03','concession','/kənˈseʃən/','noun','양보','Something given up or conceded in a negotiation.','We can offer one small {concession}.','작은 양보를 제공할 수 있어요.','concession','B1','negotiation',1,'concession give up yield negotiation business table'),
('w_negotiation_B1_04','leverage','/ˈlevərɪdʒ/','noun','협상력','Power to influence a situation, especially in negotiations.','Our data gives us {leverage}.','우리 데이터가 협상력을 줘요.','leverage','B1','negotiation',1,'leverage power advantage negotiation business strategy'),
('w_negotiation_B1_05','counterproposal','/ˌkaʊntərprəˈpəʊzəl/','noun','역제안','An offer made in response to another offer.','They submitted a {counterproposal}.','그들이 역제안을 제출했어요.','counterproposal','B1','negotiation',1,'counterproposal offer document business negotiation reply'),
('w_negotiation_B1_06','stakeholder','/ˈsteɪkhəʊldər/','noun','이해관계자','A person with an interest in a business or project.','All {stakeholders} must approve.','모든 이해관계자가 승인해야 해요.','stakeholders','B1','negotiation',1,'stakeholder team group meeting business decision'),
('w_negotiation_B1_07','agenda','/əˈdʒendə/','noun','안건','A list of items to be discussed at a meeting.','Let''s set the {agenda} for today.','오늘의 안건을 정합시다.','agenda','B1','negotiation',1,'agenda meeting list whiteboard business planning'),
('w_negotiation_B1_08','clause','/klɔːz/','noun','조항','A particular section in a legal document.','The penalty {clause} is strict.','위약 조항이 엄격해요.','clause','B1','negotiation',1,'clause contract document legal review office'),
('w_negotiation_B1_09','binding','/ˈbaɪndɪŋ/','adjective','구속력 있는','Having legal force and must be obeyed.','This agreement is legally {binding}.','이 합의는 법적 구속력이 있어요.','binding','B1','negotiation',1,'binding contract legal document signature official'),
('w_negotiation_B1_10','mutual','/ˈmjuːtʃuəl/','adjective','상호적인','Shared or felt by each of two or more parties.','Let''s find {mutual} benefit.','상호 이익을 찾아봐요.','mutual','B1','negotiation',1,'mutual benefit partnership collaboration business'),
('w_negotiation_B1_11','dispute','/dɪˈspjuːt/','noun','분쟁','A disagreement or conflict between parties.','We hope to resolve this {dispute} quickly.','이 분쟁을 빨리 해결하길 바라요.','dispute','B1','negotiation',1,'dispute conflict disagreement business legal'),
('w_negotiation_B1_12','resolution','/ˌrezəˈluːʃən/','noun','해결','A firm decision to find a solution.','We need a clear {resolution}.','명확한 해결책이 필요해요.','resolution','B1','negotiation',1,'resolution solution agreement outcome business'),
('w_negotiation_B1_13','priority','/praɪˈɒrɪti/','noun','우선순위','Something regarded as more important than others.','Price is our top {priority}.','가격이 최우선 순위예요.','priority','B1','negotiation',2,'priority list important ranking business strategy'),
('w_negotiation_B1_14','transparency','/trænsˈpærənsi/','noun','투명성','The quality of being open and easy to understand.','We expect full {transparency}.','완전한 투명성을 기대해요.','transparency','B1','negotiation',2,'transparency open honest business trust glass'),
('w_negotiation_B1_15','obligation','/ˌɒblɪˈɡeɪʃən/','noun','의무','Something you are required to do legally or morally.','What are our {obligations}?','우리의 의무는 무엇인가요?','obligations','B1','negotiation',2,'obligation duty responsibility contract legal'),
('w_negotiation_B1_16','proposal','/prəˈpəʊzəl/','noun','제안서','A formal suggestion or plan.','Please review the attached {proposal}.','첨부된 제안서를 검토해 주세요.','proposal','B1','negotiation',1,'proposal document business plan presentation'),
('w_negotiation_B1_17','revise','/rɪˈvaɪz/','verb','수정하다','To change something to correct or improve it.','Can you {revise} the quotation?','견적서를 수정해 주실 수 있나요?','revise','B1','negotiation',2,'revise edit document correction business'),
('w_negotiation_B1_18','quotation','/kwəʊˈteɪʃən/','noun','견적','A formal statement of the estimated cost of a job.','Please send us a {quotation}.','견적서를 보내 주세요.','quotation','B1','negotiation',1,'quotation estimate price document business'),
('w_negotiation_B1_19','authorize','/ˈɔːθəraɪz/','verb','승인하다','To give official permission for something.','Only the director can {authorize} this.','이사만이 이것을 승인할 수 있어요.','authorize','B1','negotiation',2,'authorize approve sign official document'),
('w_negotiation_B1_20','penalty','/ˈpenəlti/','noun','위약금, 벌칙','A punishment for breaking a rule or contract.','Late delivery incurs a {penalty}.','납기 지연 시 위약금이 발생해요.','penalty','B1','negotiation',2,'penalty fine contract breach business legal'),
('w_negotiation_B1_21','scope','/skəʊp/','noun','범위','The extent of the area or subject matter covered.','Let''s define the project {scope}.','프로젝트 범위를 정의합시다.','scope','B1','negotiation',2,'scope range boundary project business plan'),
('w_negotiation_B1_22','milestone','/ˈmaɪlstəʊn/','noun','주요 단계','An important point in the progress of a project.','Each {milestone} triggers a payment.','각 주요 단계마다 결제가 이루어져요.','milestone','B1','negotiation',2,'milestone achievement progress project timeline'),
('w_negotiation_B1_23','quotation mark','/kwəʊˈteɪʃən mɑːk/','noun','인용','A firm price submitted for consideration.','We received three competitive {quotations}.','경쟁력 있는 견적 세 개를 받았어요.','quotations','B1','negotiation',2,'quotation offer comparison selection business'),
('w_negotiation_B1_24','approve','/əˈpruːv/','verb','승인하다','To officially agree to or accept something.','Management needs to {approve} this.','경영진이 이것을 승인해야 해요.','approve','B1','negotiation',2,'approve stamp official document management'),
('w_negotiation_B1_25','withdraw','/wɪðˈdrɔː/','verb','철회하다','To take back something previously offered or agreed.','We may {withdraw} the offer.','제안을 철회할 수도 있어요.','withdraw','B1','negotiation',2,'withdraw retract cancel offer business decision'),
('w_negotiation_B1_26','execute','/ˈeksɪkjuːt/','verb','실행하다, 체결하다','To carry out or sign a legal document.','Both parties must {execute} the contract.','양 당사자가 계약을 체결해야 해요.','execute','B1','negotiation',2,'execute contract sign legal business formal'),
('w_negotiation_B1_27','timeline','/ˈtaɪmlaɪn/','noun','일정표','A schedule showing when tasks should be done.','Can we agree on the {timeline}?','일정표에 합의할 수 있을까요?','timeline','B1','negotiation',2,'timeline schedule project plan calendar'),
('w_negotiation_B1_28','party','/ˈpɑːti/','noun','당사자','A person or group involved in an agreement.','Both {parties} have signed.','양 당사자가 서명했어요.','parties','B1','negotiation',1,'parties contract legal business agreement group'),
('w_negotiation_B1_29','outstanding','/aʊtˈstændɪŋ/','adjective','미결된, 미지급의','Not yet paid or resolved.','There are {outstanding} payments.','미지급된 대금이 있어요.','outstanding','B1','negotiation',2,'outstanding pending invoice payment business'),
('w_negotiation_B1_30','exclusive','/ɪkˈskluːsɪv/','adjective','독점적인','Limited to only one person or group.','We want {exclusive} distribution rights.','독점 유통권을 원해요.','exclusive','B1','negotiation',2,'exclusive rights limited access business premium'),
('w_negotiation_B1_31','waive','/weɪv/','verb','포기하다, 면제하다','To choose not to enforce a right or requirement.','Can you {waive} the setup fee?','설치 비용을 면제해 주실 수 있나요?','waive','B1','negotiation',2,'waive exempt fee cost reduction business'),
('w_negotiation_B1_32','extend','/ɪkˈstend/','verb','연장하다','To make something longer or larger.','We need to {extend} the deadline.','마감일을 연장해야 해요.','extend','B1','negotiation',2,'extend deadline calendar time extension business'),
('w_negotiation_B1_33','negotiate down','/nɪˈɡəʊʃieɪt daʊn/','phrase','가격을 낮추다','To reduce a price through discussion.','We managed to {negotiate down} the price.','협상으로 가격을 낮추는 데 성공했어요.','negotiate down','B1','negotiation',2,'negotiate down price reduction bargain business'),
('w_negotiation_B1_34','counter','/ˈkaʊntər/','verb','반박하다, 역제안하다','To respond to an argument or proposal with an opposing one.','They {countered} our offer immediately.','그들이 바로 우리 제안에 역제안을 했어요.','countered','B1','negotiation',1,'counter reply respond negotiation business table'),
('w_negotiation_B1_35','commitment','/kəˈmɪtmənt/','noun','약속, 확약','A firm decision or promise to do something.','We need a firm {commitment} from you.','귀사의 확실한 확약이 필요해요.','commitment','B1','negotiation',1,'commitment promise agreement business handshake');

-- ══════════════════════════════════════
-- WORDS — B2 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_negotiation_B2_01','arbitration','/ˌɑːbɪˈtreɪʃən/','noun','중재','A process in which disputes are settled by an impartial third party.','The contract requires {arbitration} for disputes.','계약서는 분쟁 시 중재를 요구해요.','arbitration','B2','negotiation',1,'arbitration mediation dispute resolution legal neutral'),
('w_negotiation_B2_02','mediation','/ˌmiːdiˈeɪʃən/','noun','조정','A process where a neutral third party helps resolve a dispute.','We propose {mediation} before going to court.','법원에 가기 전에 조정을 제안해요.','mediation','B2','negotiation',1,'mediation neutral third party discussion resolution'),
('w_negotiation_B2_03','litigation','/ˌlɪtɪˈɡeɪʃən/','noun','소송','The process of taking a case to a court of law.','We want to avoid {litigation}.','소송을 피하고 싶어요.','litigation','B2','negotiation',1,'litigation court law legal dispute formal'),
('w_negotiation_B2_04','liability','/ˌlaɪəˈbɪləti/','noun','책임, 배상 의무','The state of being legally responsible for something.','We limit our {liability} to direct losses.','배상 책임을 직접 손실로 제한해요.','liability','B2','negotiation',1,'liability legal responsibility contract business risk'),
('w_negotiation_B2_05','indemnity','/ɪnˈdemnɪti/','noun','면책, 보상','Protection against or compensation for damage or loss.','The contract includes an {indemnity} clause.','계약서에 면책 조항이 있어요.','indemnity','B2','negotiation',1,'indemnity protection compensation insurance contract'),
('w_negotiation_B2_06','warranty','/ˈwɒrənti/','noun','보증','A written guarantee promising to repair or replace if needed.','The product comes with a two-year {warranty}.','제품은 2년 보증이 포함돼요.','warranty','B2','negotiation',1,'warranty guarantee certificate product legal document'),
('w_negotiation_B2_07','escrow','/ˈeskrəʊ/','noun','에스크로','Money held by a third party until a deal is completed.','Payment will be held in {escrow}.','결제금은 에스크로로 보관될 거예요.','escrow','B2','negotiation',1,'escrow third party payment hold secure transaction'),
('w_negotiation_B2_08','contingency','/kənˈtɪndʒənsi/','noun','예비 조항, 불확실성','A provision for an uncertain future event.','We need a {contingency} fund.','예비 자금이 필요해요.','contingency','B2','negotiation',1,'contingency plan risk backup fund business'),
('w_negotiation_B2_09','ratify','/ˈrætɪfaɪ/','verb','비준하다','To give formal consent to make an agreement officially valid.','The board will {ratify} the agreement.','이사회가 합의를 비준할 거예요.','ratify','B2','negotiation',1,'ratify approve official board vote legal'),
('w_negotiation_B2_10','void','/vɔɪd/','adjective','무효인','Not valid or legally binding.','This contract is {void} without signatures.','서명이 없으면 이 계약은 무효예요.','void','B2','negotiation',1,'void invalid null contract legal document stamp'),
('w_negotiation_B2_11','enforce','/ɪnˈfɔːs/','verb','집행하다','To make people obey a rule or agreement.','We will {enforce} the penalty clause.','위약 조항을 집행할 것이에요.','enforce','B2','negotiation',1,'enforce law court legal rights contract'),
('w_negotiation_B2_12','compliance','/kəmˈplaɪəns/','noun','준수','The action of complying with a rule or requirement.','Full {compliance} is required by law.','법적으로 완전한 준수가 요구돼요.','compliance','B2','negotiation',1,'compliance rules regulation document check business'),
('w_negotiation_B2_13','precedent','/ˈpresɪdənt/','noun','선례','An earlier decision used as a guide for future ones.','This would set a bad {precedent}.','이것은 나쁜 선례가 될 거예요.','precedent','B2','negotiation',2,'precedent legal history case law document'),
('w_negotiation_B2_14','termination','/ˌtɜːmɪˈneɪʃən/','noun','해지, 종료','The ending of a contract or agreement.','The {termination} clause allows 30 days'' notice.','해지 조항은 30일 통보를 허용해요.','termination','B2','negotiation',1,'termination end contract notice legal document'),
('w_negotiation_B2_15','disclosure','/dɪˈskləʊʒər/','noun','공개','The action of making information known.','Full {disclosure} is required from both parties.','양측의 완전한 공개가 요구돼요.','disclosure','B2','negotiation',2,'disclosure information reveal document business legal'),
('w_negotiation_B2_16','confidential','/ˌkɒnfɪˈdenʃəl/','adjective','기밀의','Intended to be kept secret.','All discussions are strictly {confidential}.','모든 논의는 철저히 기밀이에요.','confidential','B2','negotiation',1,'confidential secret private document NDA business'),
('w_negotiation_B2_17','due diligence','/ˌdjuː ˈdɪlɪdʒəns/','noun','실사','An investigation conducted before a business deal.','We need to complete {due diligence} first.','먼저 실사를 완료해야 해요.','due diligence','B2','negotiation',1,'due diligence investigation audit business research'),
('w_negotiation_B2_18','force majeure','/ˌfɔːs mæˈʒɜːr/','noun','불가항력','Unforeseeable circumstances that prevent fulfillment.','The flood qualified as {force majeure}.','홍수는 불가항력으로 인정됐어요.','force majeure','B2','negotiation',2,'force majeure natural disaster contract clause'),
('w_negotiation_B2_19','non-disclosure','/ˌnɒndɪˈskləʊʒər/','noun','비밀유지','An agreement to keep information secret.','Please sign the {non-disclosure} agreement.','비밀유지협약서에 서명해 주세요.','non-disclosure','B2','negotiation',1,'non-disclosure NDA agreement signature confidential'),
('w_negotiation_B2_20','intellectual property','/ˌɪntəˈlektʃuəl ˈprɒpəti/','noun','지식재산권','Creations of the mind protected by law.','The {intellectual property} rights belong to us.','지식재산권은 저희에게 있어요.','intellectual property','B2','negotiation',2,'intellectual property IP copyright patent legal'),
('w_negotiation_B2_21','indemnification','/ɪnˌdemnɪfɪˈkeɪʃən/','noun','면책 보상','Compensation for harm or loss suffered.','We require full {indemnification}.','완전한 면책 보상을 요구해요.','indemnification','B2','negotiation',2,'indemnification compensation legal protection contract'),
('w_negotiation_B2_22','clause','/klɔːz/','noun','조항','A particular provision in a legal document.','The penalty {clause} is quite severe.','위약 조항이 꽤 엄격해요.','clause','B2','negotiation',1,'clause provision contract legal document'),
('w_negotiation_B2_23','subcontract','/ˈsʌbkɒntrækt/','noun','하도급 계약','A contract made with a third party to perform part of a project.','We may {subcontract} part of the work.','업무의 일부를 하도급할 수 있어요.','subcontract','B2','negotiation',2,'subcontract outsource third party work business'),
('w_negotiation_B2_24','dispute resolution','/dɪˈspjuːt ˌrezəˈluːʃən/','noun','분쟁 해결','A process for settling disagreements between parties.','The {dispute resolution} clause is on page 4.','분쟁 해결 조항은 4페이지에 있어요.','dispute resolution','B2','negotiation',1,'dispute resolution legal process settlement business'),
('w_negotiation_B2_25','price point','/praɪs pɔɪnt/','noun','가격대','A price at which something can be offered for sale.','We need a competitive {price point}.','경쟁력 있는 가격대가 필요해요.','price point','B2','negotiation',2,'price point competitive market analysis business'),
('w_negotiation_B2_26','renegotiate','/ˌriːnɪˈɡəʊʃieɪt/','verb','재협상하다','To negotiate again, especially to get better terms.','We must {renegotiate} the terms annually.','조건을 매년 재협상해야 해요.','renegotiate','B2','negotiation',1,'renegotiate revise contract business discussion'),
('w_negotiation_B2_27','benchmark','/ˈbentʃmɑːk/','noun','기준, 벤치마크','A standard against which something is compared.','This price is below our {benchmark}.','이 가격은 우리 기준 이하예요.','benchmark','B2','negotiation',2,'benchmark standard comparison analysis business'),
('w_negotiation_B2_28','confidentiality','/ˌkɒnfɪˌdenʃɪˈæləti/','noun','기밀성','The state of being confidential.','We must ensure {confidentiality}.','기밀성을 보장해야 해요.','confidentiality','B2','negotiation',2,'confidentiality secret private legal business trust'),
('w_negotiation_B2_29','damages','/ˈdæmɪdʒɪz/','noun','손해배상금','Money claimed or paid in compensation for a loss.','We will seek {damages} in court.','법원에서 손해배상을 청구할 거예요.','damages','B2','negotiation',2,'damages compensation money legal court business'),
('w_negotiation_B2_30','breach','/briːtʃ/','noun','위반','A failure to observe the terms of a law or agreement.','This constitutes a {breach} of contract.','이것은 계약 위반에 해당해요.','breach','B2','negotiation',1,'breach violation contract law legal business'),
('w_negotiation_B2_31','collateral','/kəˈlætərəl/','noun','담보','Property pledged as security for a loan.','What {collateral} will you provide?','어떤 담보를 제공할 건가요?','collateral','B2','negotiation',2,'collateral asset security loan bank business'),
('w_negotiation_B2_32','provisional','/prəˈvɪʒənəl/','adjective','잠정적인','Arranged or existing for the present, possibly to be changed.','This is a {provisional} agreement.','이것은 잠정 합의예요.','provisional','B2','negotiation',2,'provisional temporary draft agreement business document'),
('w_negotiation_B2_33','amendment','/əˈmendmənt/','noun','수정, 개정','A minor change or addition to an agreement.','We propose an {amendment} to clause 5.','5조항에 수정을 제안해요.','amendment','B2','negotiation',1,'amendment change revision document legal contract'),
('w_negotiation_B2_34','jurisdiction','/ˌdʒʊərɪsˈdɪkʃən/','noun','관할권','The authority to make legal decisions in an area.','This falls under UK {jurisdiction}.','이것은 영국 관할권에 속해요.','jurisdiction','B2','negotiation',2,'jurisdiction law country legal authority court'),
('w_negotiation_B2_35','signatory','/ˈsɪɡnətri/','noun','서명국, 서명인','A person or country that signs an agreement.','All {signatories} must be present.','모든 서명인이 참석해야 해요.','signatories','B2','negotiation',2,'signatory signature contract document formal legal');

-- ══════════════════════════════════════
-- WORDS — C1 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_negotiation_C1_01','fiduciary','/fɪˈdjuːʃiəri/','adjective','신탁의, 수탁자로서의','Relating to a position of trust, especially in financial matters.','Directors have a {fiduciary} duty to shareholders.','이사는 주주에게 신탁 의무가 있어요.','fiduciary','C1','negotiation',1,'fiduciary trust duty responsibility legal finance'),
('w_negotiation_C1_02','due diligence','/ˌdjuː ˈdɪlɪdʒəns/','noun','실사','A comprehensive appraisal before a business transaction.','We cannot proceed without {due diligence}.','실사 없이는 진행할 수 없어요.','due diligence','C1','negotiation',1,'due diligence audit investigation report business'),
('w_negotiation_C1_03','subrogation','/ˌsʌbrəˈɡeɪʃən/','noun','대위권','The substitution of one party for another in a legal claim.','The insurer pursued a right of {subrogation}.','보험사가 대위권을 행사했어요.','subrogation','C1','negotiation',2,'subrogation insurance legal rights transfer claim'),
('w_negotiation_C1_04','indemnification','/ɪnˌdemnɪfɪˈkeɪʃən/','noun','면책 보상','Security or protection against legal liability.','The {indemnification} clause covers third-party claims.','면책 조항은 제3자 청구를 다뤄요.','indemnification','C1','negotiation',1,'indemnification legal protection clause contract'),
('w_negotiation_C1_05','covenant','/ˈkʌvənənt/','noun','규약','A formal agreement or promise in a contract.','The non-compete {covenant} lasts two years.','경쟁 금지 규약은 2년간 지속돼요.','covenant','C1','negotiation',1,'covenant agreement contract clause legal formal'),
('w_negotiation_C1_06','lien','/liːn/','noun','유치권','A right to keep property until a debt is paid.','The bank holds a {lien} on the property.','은행이 그 부동산에 유치권을 보유해요.','lien','C1','negotiation',2,'lien property debt claim legal bank security'),
('w_negotiation_C1_07','injunction','/ɪnˈdʒʌŋkʃən/','noun','금지 명령','A court order requiring a party to do or stop doing something.','We may seek an {injunction}.','금지 명령을 신청할 수도 있어요.','injunction','C1','negotiation',1,'injunction court order legal stop prohibition'),
('w_negotiation_C1_08','breach','/briːtʃ/','noun','위반','A failure to observe the terms of a contract or law.','Any {breach} will trigger the penalty clause.','위반이 발생하면 위약 조항이 발동해요.','breach','C1','negotiation',1,'breach contract violation penalty legal formal'),
('w_negotiation_C1_09','remedy','/ˈremədi/','noun','구제 수단','A legal means of recovering rights or obtaining redress.','What {remedy} do you propose?','어떤 구제 수단을 제안하시나요?','remedy','C1','negotiation',1,'remedy legal solution court rights recovery'),
('w_negotiation_C1_10','jurisdiction','/ˌdʒʊərɪsˈdɪkʃən/','noun','재판 관할권','The official power to make legal decisions in an area.','Which {jurisdiction} governs this contract?','어떤 관할권이 이 계약을 지배하나요?','jurisdiction','C1','negotiation',1,'jurisdiction court legal authority country law'),
('w_negotiation_C1_11','arbitral','/ˈɑːbɪtrəl/','adjective','중재의','Relating to arbitration.','The {arbitral} award is binding.','중재 판정은 구속력이 있어요.','arbitral','C1','negotiation',2,'arbitral award decision tribunal legal official'),
('w_negotiation_C1_12','tort','/tɔːt/','noun','불법 행위','A wrongful act that results in legal liability.','This may constitute a {tort}.','이것은 불법 행위에 해당할 수 있어요.','tort','C1','negotiation',2,'tort civil wrong legal liability court case'),
('w_negotiation_C1_13','statute of limitations','/ˈstætʃuːt əv ˌlɪmɪˈteɪʃənz/','noun','소멸 시효','A law that sets the maximum time to bring legal action.','The {statute of limitations} has expired.','소멸 시효가 만료됐어요.','statute of limitations','C1','negotiation',2,'statute limitations time legal deadline court'),
('w_negotiation_C1_14','recourse','/ˈriːkɔːs/','noun','구제 방법','The option to turn to for help or to take action.','We will have no {recourse} if this fails.','이것이 실패하면 구제 방법이 없어요.','recourse','C1','negotiation',2,'recourse option legal remedy solution business'),
('w_negotiation_C1_15','severability','/ˌsevərəˈbɪlɪti/','noun','분리 가능성','The quality of parts of a contract being valid independently.','The {severability} clause protects remaining terms.','분리 가능성 조항이 나머지 조건을 보호해요.','severability','C1','negotiation',2,'severability contract clause legal document'),
('w_negotiation_C1_16','liquidated damages','/ˈlɪkwɪdeɪtɪd ˈdæmɪdʒɪz/','noun','위약 배상금','A pre-agreed sum payable in the event of a breach.','The contract specifies {liquidated damages}.','계약서에 위약 배상금이 명시되어 있어요.','liquidated damages','C1','negotiation',1,'liquidated damages penalty contract legal business'),
('w_negotiation_C1_17','specific performance','/spɪˈsɪfɪk pəˈfɔːməns/','noun','강제 이행','A court order requiring a party to perform their contract.','The claimant sought {specific performance}.','청구인이 강제 이행을 구했어요.','specific performance','C1','negotiation',2,'specific performance court order contract legal'),
('w_negotiation_C1_18','consideration','/kənˌsɪdəˈreɪʃən/','noun','대가, 약인','Something of value exchanged by each party in a contract.','There must be valid {consideration}.','유효한 대가가 있어야 해요.','consideration','C1','negotiation',1,'consideration value exchange contract legal binding'),
('w_negotiation_C1_19','unilateral','/ˌjuːnɪˈlætərəl/','adjective','일방적인','Performed by or affecting only one party.','A {unilateral} decision is unacceptable.','일방적인 결정은 용납할 수 없어요.','unilateral','C1','negotiation',1,'unilateral one side decision contract legal'),
('w_negotiation_C1_20','good faith','/ɡʊd feɪθ/','noun','선의, 성실한 협상 의지','Honest dealing and sincere intention in a transaction.','We acted in {good faith} throughout.','우리는 처음부터 선의로 행동했어요.','good faith','C1','negotiation',1,'good faith trust honest business negotiation'),
('w_negotiation_C1_21','mutual assent','/ˈmjuːtʃuəl əˈsent/','noun','쌍방 동의','Agreement by all parties to the terms of a contract.','{Mutual assent} is required for validity.','유효성을 위해 쌍방 동의가 필요해요.','mutual assent','C1','negotiation',2,'mutual assent agreement contract both parties legal'),
('w_negotiation_C1_22','consequential loss','/kənˌsekwenʃəl lɒs/','noun','결과적 손실','Loss arising as an indirect result of a breach.','We exclude liability for {consequential loss}.','결과적 손실에 대한 책임을 배제해요.','consequential loss','C1','negotiation',2,'consequential loss indirect damage contract legal'),
('w_negotiation_C1_23','force majeure','/ˌfɔːs mæˈʒɜːr/','noun','불가항력','Events outside human control that prevent contract performance.','The pandemic triggered the {force majeure} clause.','팬데믹이 불가항력 조항을 발동시켰어요.','force majeure','C1','negotiation',1,'force majeure natural disaster clause contract'),
('w_negotiation_C1_24','accrue','/əˈkruː/','verb','발생하다','To accumulate or grow over time.','Interest will {accrue} from the due date.','만기일부터 이자가 발생해요.','accrue','C1','negotiation',2,'accrue interest accumulate finance business'),
('w_negotiation_C1_25','estoppel','/ɪˈstɒpəl/','noun','금반언 원칙','A rule preventing a party from denying prior statements.','The doctrine of {estoppel} applies here.','금반언 원칙이 여기 적용돼요.','estoppel','C1','negotiation',2,'estoppel doctrine legal principle contract'),
('w_negotiation_C1_26','novation','/nəʊˈveɪʃən/','noun','계약 갱신','The replacement of one party or obligation in a contract.','We propose {novation} of the agreement.','계약 갱신을 제안해요.','novation','C1','negotiation',2,'novation replace party contract legal business'),
('w_negotiation_C1_27','quasi-contract','/ˈkweɪzaɪ ˈkɒntrækt/','noun','준계약','An implied legal obligation imposed by courts.','The court recognised a {quasi-contract}.','법원은 준계약을 인정했어요.','quasi-contract','C1','negotiation',2,'quasi-contract implied legal obligation court'),
('w_negotiation_C1_28','indemnitor','/ɪnˈdemnɪtər/','noun','면책 제공자','A party who provides indemnity to another.','The {indemnitor} must cover all costs.','면책 제공자가 모든 비용을 부담해야 해요.','indemnitor','C1','negotiation',3,'indemnitor legal protection coverage business'),
('w_negotiation_C1_29','assignment','/əˈsaɪnmənt/','noun','권리 양도','The transfer of rights or obligations to another party.','Prior consent is required for any {assignment}.','권리 양도에는 사전 동의가 필요해요.','assignment','C1','negotiation',1,'assignment transfer rights contract legal business'),
('w_negotiation_C1_30','cession','/ˈseʃən/','noun','양도','The formal giving up of rights or territory.','The {cession} of patent rights was agreed.','특허권 양도에 합의했어요.','cession','C1','negotiation',3,'cession transfer rights agreement legal formal'),
('w_negotiation_C1_31','parol evidence','/pəˈrɒl ˈevɪdəns/','noun','구두 증거','Oral testimony used to vary or contradict a written contract.','The {parol evidence} rule was invoked.','구두 증거 규칙이 원용됐어요.','parol evidence','C1','negotiation',3,'parol evidence oral contract legal rule'),
('w_negotiation_C1_32','perfection','/pəˈfekʃən/','noun','담보 설정 완료','The process of making a security interest legally valid.','{Perfection} of the security interest is required.','담보 설정 완료가 필요해요.','perfection','C1','negotiation',3,'perfection security interest legal filing registration'),
('w_negotiation_C1_33','standstill agreement','/ˈstændstɪl əˈɡriːmənt/','noun','현상유지 협약','An agreement to pause legal action during negotiations.','The parties signed a {standstill agreement}.','당사자들이 현상유지 협약에 서명했어요.','standstill agreement','C1','negotiation',2,'standstill agreement pause negotiation legal formal'),
('w_negotiation_C1_34','material breach','/məˈtɪəriəl briːtʃ/','noun','중대한 위반','A serious violation that defeats the purpose of a contract.','Non-delivery was a {material breach}.','미납품은 중대한 위반이었어요.','material breach','C1','negotiation',1,'material breach contract violation legal serious'),
('w_negotiation_C1_35','representations','/ˌreprɪzenˈteɪʃənz/','noun','진술','Statements of fact made by a party to induce another.','The seller''s {representations} were misleading.','판매자의 진술이 오해를 불러일으켰어요.','representations','C1','negotiation',2,'representations statements facts contract legal');

-- ══════════════════════════════════════
-- WORDS — C2 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_negotiation_C2_01','estoppel','/ɪˈstɒpəl/','noun','금반언 원칙','A legal principle preventing contradiction of prior statements.','He was barred by {estoppel} from claiming otherwise.','그는 금반언 원칙으로 다른 주장을 할 수 없었어요.','estoppel','C2','negotiation',1,'estoppel legal principle contract bar claim'),
('w_negotiation_C2_02','novation','/nəʊˈveɪʃən/','noun','계약 이전','Substituting a new contract for an old one, releasing the original party.','The {novation} transferred all obligations to the buyer.','계약 이전으로 모든 의무가 매수인에게 이전됐어요.','novation','C2','negotiation',1,'novation substitute contract obligation transfer legal'),
('w_negotiation_C2_03','rescission','/rɪˈsɪʒən/','noun','계약 취소','The cancellation of a contract as if it never existed.','Fraud entitles the claimant to {rescission}.','사기는 청구인에게 계약 취소 권한을 줘요.','rescission','C2','negotiation',1,'rescission cancel void contract fraud legal remedy'),
('w_negotiation_C2_04','quantum meruit','/ˌkwɒntəm ˈmerɪt/','noun','상당한 보상','A reasonable sum paid for work done when no price was fixed.','She claimed payment on a {quantum meruit} basis.','그녀는 상당한 보상을 근거로 대금을 청구했어요.','quantum meruit','C2','negotiation',2,'quantum meruit fair payment work legal reasonable'),
('w_negotiation_C2_05','tortious','/ˈtɔːʃəs/','adjective','불법 행위의','Constituting or involving a civil wrong.','The defendant''s conduct was {tortious}.','피고의 행위는 불법 행위에 해당했어요.','tortious','C2','negotiation',2,'tortious wrong civil liability legal court'),
('w_negotiation_C2_06','mens rea','/ˌmenz ˈriːə/','noun','범의','The mental intention required for a crime.','Proving {mens rea} is essential in criminal law.','범의 증명은 형사법에서 필수예요.','mens rea','C2','negotiation',2,'mens rea intent mental criminal law legal'),
('w_negotiation_C2_07','actus reus','/ˌæktəs ˈreɪəs/','noun','범행','The physical act that constitutes a crime.','Without {actus reus} there is no offence.','범행 없이는 범죄가 없어요.','actus reus','C2','negotiation',2,'actus reus act crime criminal law legal'),
('w_negotiation_C2_08','promissory','/ˈprɒmɪsəri/','adjective','지불 약속의','Conveying or relating to a promise.','The {promissory} note was dishonoured.','지불 약속 어음이 부도났어요.','promissory','C2','negotiation',1,'promissory note payment promise finance legal'),
('w_negotiation_C2_09','executory','/ɪɡˈzekjʊtəri/','adjective','미이행의','Relating to a contract not yet fully performed.','This is an {executory} contract pending delivery.','이것은 납품 대기 중인 미이행 계약이에요.','executory','C2','negotiation',2,'executory pending contract unperformed legal'),
('w_negotiation_C2_10','liquidated','/ˈlɪkwɪdeɪtɪd/','adjective','산정된, 청산된','(Of damages) fixed or determined by agreement or law.','The {liquidated} damages clause is enforceable.','산정 손해 조항은 집행 가능해요.','liquidated','C2','negotiation',1,'liquidated damages fixed amount legal contract'),
('w_negotiation_C2_11','subrogation','/ˌsʌbrəˈɡeɪʃən/','noun','대위 변제','The substitution of one creditor for another.','{Subrogation} allows the insurer to recover losses.','대위 변제는 보험사가 손실을 회수하게 해요.','subrogation','C2','negotiation',2,'subrogation insurer recovery legal rights claim'),
('w_negotiation_C2_12','non est factum','/ˌnɒn est ˈfæktəm/','noun','서명 무효 항변','A plea that a signed document was fundamentally different from expected.','He raised {non est factum} as a defence.','그는 서명 무효를 항변으로 제기했어요.','non est factum','C2','negotiation',3,'non est factum signature defence contract legal'),
('w_negotiation_C2_13','restitution','/ˌrestɪˈtjuːʃən/','noun','원상회복','The restoration of something lost or stolen.','The court ordered {restitution} of the funds.','법원은 자금의 원상회복을 명령했어요.','restitution','C2','negotiation',1,'restitution restore funds court order legal'),
('w_negotiation_C2_14','unjust enrichment','/ʌnˈdʒʌst ɪnˈrɪtʃmənt/','noun','부당 이득','A situation where one party benefits at another''s expense without justification.','The claim was based on {unjust enrichment}.','청구는 부당 이득에 근거했어요.','unjust enrichment','C2','negotiation',2,'unjust enrichment benefit unfair gain legal'),
('w_negotiation_C2_15','frustration of contract','/frʌˈstreɪʃən əv ˈkɒntrækt/','noun','계약 목적 달성 불능','A doctrine terminating a contract when performance becomes impossible.','The doctrine of {frustration of contract} applied.','계약 목적 달성 불능 원칙이 적용됐어요.','frustration of contract','C2','negotiation',2,'frustration contract impossible performance legal'),
('w_negotiation_C2_16','repudiation','/rɪˌpjuːdiˈeɪʃən/','noun','이행 거절','An indication that a party will not perform its obligations.','Their letter constituted {repudiation}.','그들의 서신은 이행 거절에 해당했어요.','repudiation','C2','negotiation',2,'repudiation refuse obligation contract legal'),
('w_negotiation_C2_17','privity','/ˈprɪvɪti/','noun','계약 당사자 관계','The relationship between parties in a contract.','Only parties in {privity} can sue.','계약 당사자만이 소송을 제기할 수 있어요.','privity','C2','negotiation',2,'privity parties contract relationship legal sue'),
('w_negotiation_C2_18','cy-pres','/ˌsiː ˈpreɪ/','noun','근접 원칙','A legal doctrine applying a gift as closely as possible to the original intent.','The trust was modified under the {cy-pres} doctrine.','신탁은 근접 원칙에 따라 수정됐어요.','cy-pres','C2','negotiation',3,'cy-pres doctrine trust modification legal'),
('w_negotiation_C2_19','waiver','/ˈweɪvər/','noun','권리 포기','The act of relinquishing a legal right voluntarily.','Signing constitutes a {waiver} of all claims.','서명은 모든 청구권 포기에 해당해요.','waiver','C2','negotiation',1,'waiver relinquish right legal document formal'),
('w_negotiation_C2_20','interpleader','/ˌɪntəˈpliːdər/','noun','공탁 소송','A process where a third party holding funds asks a court to decide who is entitled.','The bank filed an {interpleader} action.','은행이 공탁 소송을 제기했어요.','interpleader','C2','negotiation',3,'interpleader court funds dispute legal bank'),
('w_negotiation_C2_21','constructive trust','/kənˈstrʌktɪv trʌst/','noun','의제 신탁','An equitable remedy imposed by law to prevent unjust enrichment.','The court imposed a {constructive trust}.','법원은 의제 신탁을 부과했어요.','constructive trust','C2','negotiation',2,'constructive trust equitable remedy legal court'),
('w_negotiation_C2_22','ex parte','/ˌeks ˈpɑːteɪ/','adverb','일방 심리로','Involving only one party without notifying the other.','An {ex parte} injunction was granted.','일방 심리 금지 명령이 내려졌어요.','ex parte','C2','negotiation',2,'ex parte one side court order legal hearing'),
('w_negotiation_C2_23','in pari delicto','/ɪn ˌpɑːri dɪˈlɪktəʊ/','phrase','공동 과실','A doctrine denying relief when both parties are at fault.','The defence relied on {in pari delicto}.','항변은 공동 과실에 의존했어요.','in pari delicto','C2','negotiation',3,'in pari delicto fault defence legal doctrine'),
('w_negotiation_C2_24','ultra vires','/ˌʌltrə ˈvaɪriːz/','adjective','권한 초과의','Beyond the legal authority of a person or organisation.','The resolution was declared {ultra vires}.','그 결의는 권한 초과로 선언됐어요.','ultra vires','C2','negotiation',2,'ultra vires authority beyond legal corporation'),
('w_negotiation_C2_25','accord and satisfaction','/əˈkɔːd ænd ˌsætɪsˈfækʃən/','noun','새로운 합의 이행','An agreement to accept a lesser settlement to discharge a debt.','The dispute ended in {accord and satisfaction}.','분쟁이 새로운 합의 이행으로 끝났어요.','accord and satisfaction','C2','negotiation',2,'accord satisfaction settlement discharge debt legal'),
('w_negotiation_C2_26','equitable estoppel','/ˈekwɪtəbəl ɪˈstɒpəl/','noun','형평법적 금반언','A doctrine preventing inequitable reliance on a legal position.','{Equitable estoppel} prevented him from raising the argument.','형평법적 금반언으로 그는 주장을 제기할 수 없었어요.','equitable estoppel','C2','negotiation',3,'equitable estoppel doctrine legal court principle'),
('w_negotiation_C2_27','laches','/ˈlætʃɪz/','noun','지연에 의한 권리 소멸','Unreasonable delay in pursuing a legal claim.','The claim was barred by {laches}.','청구는 지연에 의한 권리 소멸로 차단됐어요.','laches','C2','negotiation',3,'laches delay claim bar legal equity'),
('w_negotiation_C2_28','quantum','/ˈkwɒntəm/','noun','손해액','The amount of damages claimed or awarded.','The court must assess the {quantum} of loss.','법원은 손해액을 산정해야 해요.','quantum','C2','negotiation',2,'quantum amount damages assessment legal court'),
('w_negotiation_C2_29','without prejudice','/wɪˌðaʊt ˈpredʒʊdɪs/','phrase','편견 없이, 이 조건으로만','A term marking communications that cannot be used as evidence.','This letter is sent {without prejudice}.','이 서신은 편견 없이 발송됩니다.','without prejudice','C2','negotiation',1,'without prejudice letter negotiation legal formal'),
('w_negotiation_C2_30','obiter dictum','/ˌəʊbɪtər ˈdɪktəm/','noun','방론','A judge''s remark not essential to a decision.','The judge''s comment was merely {obiter dictum}.','판사의 발언은 단순한 방론이었어요.','obiter dictum','C2','negotiation',3,'obiter dictum judge remark legal opinion'),
('w_negotiation_C2_31','ratio decidendi','/ˌreɪʃiəʊ ˌdesɪˈdendi/','noun','판결 이유','The binding legal reason for a court decision.','The {ratio decidendi} must be followed.','판결 이유는 따라야 해요.','ratio decidendi','C2','negotiation',3,'ratio decidendi binding precedent legal court'),
('w_negotiation_C2_32','ab initio','/ˌæb ɪˈnɪʃiəʊ/','adverb','처음부터','From the beginning; from when something first started.','The contract was void {ab initio}.','계약은 처음부터 무효였어요.','ab initio','C2','negotiation',2,'ab initio void beginning contract legal'),
('w_negotiation_C2_33','inter partes','/ˌɪntər ˈpɑːtiːz/','adjective','당사자 간의','Between the parties to a dispute or contract.','This order binds the parties {inter partes}.','이 명령은 당사자 간에 구속력이 있어요.','inter partes','C2','negotiation',3,'inter partes parties contract legal binding'),
('w_negotiation_C2_34','causa','/ˈkɔːzə/','noun','원인, 약인','The cause or consideration underlying a legal obligation.','The {causa} of the obligation is unclear.','그 의무의 원인이 불분명해요.','causa','C2','negotiation',3,'causa cause consideration legal civil'),
('w_negotiation_C2_35','nemo dat','/ˌniːməʊ ˈdæt/','noun','무권리자 처분 금지 원칙','The rule that one cannot transfer better title than one possesses.','The {nemo dat} rule applies to stolen goods.','무권리자 처분 금지 원칙은 도난품에 적용돼요.','nemo dat','C2','negotiation',2,'nemo dat title transfer stolen goods legal');

-- ══════════════════════════════════════
-- PATTERNS — A1 (7개): 요청·제안
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_negotiation_A1_01','Can we agree on this?','이걸로 합의할 수 있을까요?','Can we agree','합의를 제안할 때 쓰는 가장 기본적인 표현이에요.','합의 제안','A1','negotiation','pattern',NULL,1),
('s_negotiation_A1_02','I want a better price.','더 좋은 가격을 원해요.','I want','원하는 것을 직접 표현하는 가장 간단한 방법이에요.','가격 요청','A1','negotiation','pattern',NULL,2),
('s_negotiation_A1_03','Can you give me a discount?','할인해 주실 수 있나요?','give me a discount','상점이나 시장에서 할인을 요청할 때 쓸 수 있어요.','할인 요청','A1','negotiation','pattern',NULL,3),
('s_negotiation_A1_04','Is this your best offer?','이것이 최선의 제안인가요?','best offer','상대방이 더 나은 조건을 줄 수 있는지 확인하는 표현이에요.','최선 확인','A1','negotiation','pattern',NULL,4),
('s_negotiation_A1_05','I need more time to decide.','결정하는 데 시간이 더 필요해요.','more time to decide','즉각적인 결정을 피할 때 쓰는 자연스러운 표현이에요.','결정 유보','A1','negotiation','pattern',NULL,5),
('s_negotiation_A1_06','Let''s make a deal.','거래합시다.','make a deal','합의를 마무리할 때 쓰는 간결하고 힘찬 표현이에요.','거래 완료','A1','negotiation','pattern',NULL,6),
('s_negotiation_A1_07','Do you accept this?','이것을 받아들이시겠어요?','Do you accept','상대방의 수락 여부를 묻는 직접적인 표현이에요.','수락 확인','A1','negotiation','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — A2 (7개): 가격 협상
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_negotiation_A2_01','Can you lower the price a little?','가격을 조금 낮춰 주실 수 있나요?','lower the price','가격을 낮춰달라고 정중하게 요청하는 표현이에요.','가격 인하','A2','negotiation','pattern',NULL,8),
('s_negotiation_A2_02','That''s a bit out of our budget.','저희 예산에서 조금 벗어나요.','out of our budget','가격이 예산을 초과할 때 부드럽게 거절하는 표현이에요.','예산 초과','A2','negotiation','pattern',NULL,9),
('s_negotiation_A2_03','What if we order more units?','더 많이 주문하면 어떻게 되나요?','What if we order more','수량을 늘리는 조건으로 협상할 때 쓰는 표현이에요.','수량 협상','A2','negotiation','pattern',NULL,10),
('s_negotiation_A2_04','We''d like to propose a 10% discount.','10% 할인을 제안하고 싶어요.','propose a 10% discount','구체적인 할인율을 제안할 때 쓰는 표현이에요.','할인 제안','A2','negotiation','pattern',NULL,11),
('s_negotiation_A2_05','Is there any flexibility on the delivery date?','납품일에 유연성이 있나요?','flexibility on the delivery date','날짜나 조건의 조정 가능성을 묻는 표현이에요.','일정 유연성','A2','negotiation','pattern',NULL,12),
('s_negotiation_A2_06','Can we agree on a payment plan?','결제 계획에 합의할 수 있을까요?','agree on a payment plan','분할 납부나 결제 일정을 협의할 때 쓰는 표현이에요.','결제 계획','A2','negotiation','pattern',NULL,13),
('s_negotiation_A2_07','We''re willing to meet halfway.','중간선에서 만나겠습니다.','meet halfway','양측이 서로 양보하는 타협 의지를 나타내는 표현이에요.','중간 타협','A2','negotiation','pattern',NULL,14);

-- ══════════════════════════════════════
-- PATTERNS — B1 (7개): 조건 제시
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_negotiation_B1_01','We can agree to that, provided the deadline is extended.','마감일을 연장해 준다면 동의할 수 있어요.','provided the deadline is extended','"provided that ~"는 조건부 동의를 나타내는 격식 있는 표현이에요.','조건부 동의','B1','negotiation','pattern',NULL,15),
('s_negotiation_B1_02','Our position is that the price should remain fixed.','저희 입장은 가격이 고정되어야 한다는 것이에요.','Our position is that','협상에서 자신의 입장을 명확히 밝힐 때 쓰는 표현이에요.','입장 표명','B1','negotiation','pattern',NULL,16),
('s_negotiation_B1_03','We''d be prepared to offer a concession on delivery times.','납품 시간에 양보를 제공할 준비가 되어 있어요.','prepared to offer a concession','"concession(양보)"을 제안할 때 쓰는 격식 있는 표현이에요.','양보 제안','B1','negotiation','pattern',NULL,17),
('s_negotiation_B1_04','Could you walk us through your counterproposal?','역제안을 설명해 주실 수 있나요?','walk us through your counterproposal','"walk someone through ~"는 단계별로 설명해 달라고 할 때 쓰는 자연스러운 표현이에요.','역제안 설명','B1','negotiation','pattern',NULL,18),
('s_negotiation_B1_05','Let''s make sure all stakeholders are aligned before we proceed.','진행하기 전에 모든 이해관계자가 동의하는지 확인합시다.','stakeholders are aligned','"aligned"는 모두가 같은 방향을 향하고 있다는 비즈니스 표현이에요.','이해관계자 정렬','B1','negotiation','pattern',NULL,19),
('s_negotiation_B1_06','The binding clause on page three outlines our obligations.','3페이지의 구속 조항에 우리 의무가 명시되어 있어요.','binding clause','계약서의 특정 조항을 언급할 때 쓰는 정확한 표현이에요.','조항 언급','B1','negotiation','pattern',NULL,20),
('s_negotiation_B1_07','We need to revisit the agenda before making any commitments.','어떤 약속도 하기 전에 안건을 다시 살펴봐야 해요.','revisit the agenda before making any commitments','성급한 결정을 피하는 신중한 협상 표현이에요.','안건 재검토','B1','negotiation','pattern',NULL,21);

-- ══════════════════════════════════════
-- PATTERNS — B2 (7개): 계약 조율
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_negotiation_B2_01','We propose that all disputes be referred to arbitration under ICC rules.','모든 분쟁은 ICC 규칙에 따라 중재에 회부할 것을 제안해요.','referred to arbitration','국제 계약에서 분쟁 해결 방식을 명시하는 표준 표현이에요.','중재 제안','B2','negotiation','pattern',NULL,22),
('s_negotiation_B2_02','The indemnity clause needs to be capped at the contract value.','면책 조항은 계약 금액으로 상한을 정해야 해요.','indemnity clause needs to be capped','배상 한도를 설정할 때 쓰는 계약 협상 표현이에요.','면책 상한','B2','negotiation','pattern',NULL,23),
('s_negotiation_B2_03','Can we agree to place the deposit in escrow until delivery is confirmed?','납품이 확인될 때까지 보증금을 에스크로에 넣는 것에 동의하시겠어요?','place the deposit in escrow','대금 지급 안전을 위한 에스크로 제안 표현이에요.','에스크로 제안','B2','negotiation','pattern',NULL,24),
('s_negotiation_B2_04','We''d like to include a force majeure clause covering supply chain disruptions.','공급망 차질을 포함하는 불가항력 조항을 넣고 싶어요.','force majeure clause covering','최근 중요해진 불가항력 조항을 협상에 포함시킬 때 쓰는 표현이에요.','불가항력 조항','B2','negotiation','pattern',NULL,25),
('s_negotiation_B2_05','The warranty terms must be ratified by our legal team before signing.','보증 조건은 서명 전에 저희 법무팀이 비준해야 해요.','ratified by our legal team','법무 검토를 요구하는 계약 협상 표현이에요.','법무 비준','B2','negotiation','pattern',NULL,26),
('s_negotiation_B2_06','This clause would render the entire agreement void if challenged.','이 조항은 이의가 제기되면 전체 합의를 무효로 만들 수 있어요.','render the entire agreement void','계약의 법적 위험을 설명하는 표현이에요.','무효 위험','B2','negotiation','pattern',NULL,27),
('s_negotiation_B2_07','We require a non-disclosure agreement to be signed prior to any data sharing.','데이터 공유 전에 비밀유지협약서에 서명이 필요해요.','non-disclosure agreement to be signed prior to','기밀 보호를 위한 NDA 요청 표현이에요.','NDA 요청','B2','negotiation','pattern',NULL,28);

-- ══════════════════════════════════════
-- PATTERNS — C1 (7개): 법적 협상
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_negotiation_C1_01','Our fiduciary obligations preclude us from accepting those terms.','저희의 신탁 의무로 인해 그 조건을 수락할 수 없어요.','fiduciary obligations preclude','법적 의무로 특정 조건을 거절할 때 쓰는 격식 있는 표현이에요.','신탁 의무 거절','C1','negotiation','pattern',NULL,29),
('s_negotiation_C1_02','We conducted full due diligence and uncovered several material discrepancies.','전면 실사를 실시한 결과 중요한 불일치가 여러 건 발견됐어요.','conducted full due diligence','실사 결과를 보고하는 고급 비즈니스 표현이에요.','실사 보고','C1','negotiation','pattern',NULL,30),
('s_negotiation_C1_03','The covenant not to compete is enforceable under the governing jurisdiction.','경쟁 금지 규약은 관할 재판권 하에서 집행 가능해요.','covenant not to compete is enforceable','경쟁 금지 조항의 법적 효력을 설명하는 표현이에요.','경쟁 금지','C1','negotiation','pattern',NULL,31),
('s_negotiation_C1_04','Any material breach entitles the non-breaching party to seek a legal remedy.','중대한 위반은 비위반 당사자가 법적 구제 수단을 구할 권리를 줘요.','material breach entitles','계약 위반 시 법적 권리를 명시하는 표현이에요.','위반 구제권','C1','negotiation','pattern',NULL,32),
('s_negotiation_C1_05','We intend to pursue an injunction if the breach continues.','위반이 계속될 경우 금지 명령을 신청할 의사가 있어요.','pursue an injunction','법적 금지 명령으로 위반을 억제하려는 의지를 표현해요.','금지 명령','C1','negotiation','pattern',NULL,33),
('s_negotiation_C1_06','The subrogation clause assigns the insurer''s recovery rights to us.','대위 조항은 보험사의 회수 권리를 저희에게 부여해요.','subrogation clause assigns','보험 계약의 대위 조항을 설명하는 전문 표현이에요.','대위 조항','C1','negotiation','pattern',NULL,34),
('s_negotiation_C1_07','We acted in good faith and are entitled to restitution for losses incurred.','저희는 선의로 행동했으며 발생한 손실에 대한 원상회복을 받을 권리가 있어요.','acted in good faith and are entitled to restitution','선의의 행위에 근거한 원상회복 청구 표현이에요.','선의 원상회복','C1','negotiation','pattern',NULL,35);

-- ══════════════════════════════════════
-- PATTERNS — C2 (7개): 법적 협상 (심화)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_negotiation_C2_01','The doctrine of estoppel prevents you from resiling from your prior representation.','금반언 원칙은 귀사가 이전 진술에서 물러서는 것을 금지해요.','doctrine of estoppel prevents','금반언 원칙을 협상에 적용하는 고급 법률 표현이에요.','금반언 적용','C2','negotiation','pattern',NULL,36),
('s_negotiation_C2_02','We propose novation of the original contract with the acquiring entity as the new obligor.','새로운 의무자로서 인수 법인으로 원계약의 계약 이전을 제안해요.','novation of the original contract','기업 인수합병 시 계약 이전을 제안하는 법률 표현이에요.','계약 이전 제안','C2','negotiation','pattern',NULL,37),
('s_negotiation_C2_03','Rescission ab initio is available given the fraudulent misrepresentation at signing.','서명 시 사기적 허위 진술이 있었으므로 처음부터의 계약 취소가 가능해요.','Rescission ab initio is available','사기에 기반한 계약 취소 권리를 주장하는 표현이에요.','사기 취소 주장','C2','negotiation','pattern',NULL,38),
('s_negotiation_C2_04','In the absence of a fixed fee, we shall claim on a quantum meruit basis.','고정 수수료가 없는 경우 상당한 보상을 근거로 청구할 것이에요.','claim on a quantum meruit basis','가격 약정 없이 이행된 경우 보수를 청구하는 법률 표현이에요.','상당 보상 청구','C2','negotiation','pattern',NULL,39),
('s_negotiation_C2_05','The liquidated damages clause must satisfy the test against being a penalty.','산정 손해 조항은 위약금이 아니라는 기준을 충족해야 해요.','liquidated damages clause must satisfy the test','손해배상 예정액과 위약금의 구별 기준을 설명하는 표현이에요.','위약금 적법성','C2','negotiation','pattern',NULL,40),
('s_negotiation_C2_06','All communications are to be marked without prejudice and inadmissible in any proceedings.','모든 서신은 편견 없이 표시되고 어떠한 소송에서도 증거로 채택될 수 없어요.','marked without prejudice and inadmissible','협상 서신의 증거 배제를 보장하는 법률 관행 표현이에요.','증거 배제','C2','negotiation','pattern',NULL,41),
('s_negotiation_C2_07','The promissory estoppel doctrine may bar our counterparty from withdrawing their undertaking.','약속적 금반언 원칙은 상대방이 약속을 철회하는 것을 막을 수 있어요.','promissory estoppel doctrine may bar','약속 이행을 강제하는 약속적 금반언 원칙을 설명하는 표현이에요.','약속 이행 강제','C2','negotiation','pattern',NULL,42);
