-- EngCat — Cooking topic word examples backfill
-- example_en_2 ~ example_en_5 추가
-- Generated: 2026-05-27
-- Idempotent (UPDATE)

-- A1
UPDATE words SET example_en_2 = 'He learned to cook simple meals when he was a student.', example_ko_2 = '그는 학생 때 간단한 식사를 요리하는 법을 배웠어요.', example_en_3 = 'It takes about twenty minutes to cook this dish.', example_ko_3 = '이 요리를 만드는 데 약 20분이 걸려요.', example_en_4 = 'My mother taught me how to cook when I was young.', example_ko_4 = '어머니께서 어릴 때 요리하는 법을 가르쳐 주셨어요.', example_en_5 = 'Would you like to cook dinner together tonight?', example_ko_5 = '오늘 저녁에 같이 저녁을 만들어 볼까요?' WHERE id = 'w_cooking_A1_01';

UPDATE words SET example_en_2 = 'I found a great recipe for chocolate cake online.', example_ko_2 = '온라인에서 초콜릿 케이크 조리법을 발견했어요.', example_en_3 = 'This recipe requires only five ingredients.', example_ko_3 = '이 조리법에는 재료가 다섯 가지만 필요해요.', example_en_4 = 'She wrote the recipe down in her notebook.', example_ko_4 = '그녀는 조리법을 노트에 적어 두었어요.', example_en_5 = 'The recipe says to bake it for thirty minutes.', example_ko_5 = '조리법에는 30분 동안 굽는다고 나와 있어요.' WHERE id = 'w_cooking_A1_02';

UPDATE words SET example_en_2 = 'Always check that you have every ingredient before you start cooking.', example_ko_2 = '요리를 시작하기 전에 모든 재료가 있는지 확인하세요.', example_en_3 = 'Salt is an ingredient that almost every dish needs.', example_ko_3 = '소금은 거의 모든 요리에 필요한 재료예요.', example_en_4 = 'She bought the ingredients at the supermarket this morning.', example_ko_4 = '그녀는 오늘 아침 슈퍼마켓에서 재료를 샀어요.', example_en_5 = 'Fresh ingredients make the food taste much better.', example_ko_5 = '신선한 재료를 사용하면 음식이 훨씬 맛있어요.' WHERE id = 'w_cooking_A1_03';

UPDATE words SET example_en_2 = 'Tropical fruit is very sweet and full of vitamins.', example_ko_2 = '열대 과일은 매우 달콤하고 비타민이 풍부해요.', example_en_3 = 'He eats a piece of fruit after every meal.', example_ko_3 = '그는 매 식사 후에 과일을 한 조각 먹어요.', example_en_4 = 'We need to buy more fruit from the market today.', example_ko_4 = '오늘 시장에서 과일을 더 사야 해요.', example_en_5 = 'Which fruit do you like best—apples or oranges?', example_ko_5 = '사과와 오렌지 중 어떤 과일을 더 좋아하세요?' WHERE id = 'w_cooking_A1_04';

UPDATE words SET example_en_2 = 'Eating more vegetables is good for your health.', example_ko_2 = '채소를 더 많이 먹으면 건강에 좋아요.', example_en_3 = 'She grills vegetables on the barbecue every summer.', example_ko_3 = '그녀는 매년 여름 바비큐에서 채소를 구워요.', example_en_4 = 'What vegetables do you usually put in your soup?', example_ko_4 = '수프에 보통 어떤 채소를 넣으세요?', example_en_5 = 'Fresh vegetables from the garden taste amazing.', example_ko_5 = '텃밭에서 딴 신선한 채소는 정말 맛있어요.' WHERE id = 'w_cooking_A1_05';

UPDATE words SET example_en_2 = 'She prefers chicken over red meat.', example_ko_2 = '그녀는 붉은 고기보다 닭고기를 더 좋아해요.', example_en_3 = 'The meat was so tender it fell off the bone.', example_ko_3 = '고기가 너무 부드러워서 뼈에서 떨어졌어요.', example_en_4 = 'He buys fresh meat from the butcher every week.', example_ko_4 = '그는 매주 정육점에서 신선한 고기를 사요.', example_en_5 = 'Always cook meat thoroughly to avoid food poisoning.', example_ko_5 = '식중독을 예방하려면 고기를 항상 완전히 익혀 주세요.' WHERE id = 'w_cooking_A1_06';

UPDATE words SET example_en_2 = 'Salmon is a popular fish that is rich in omega-3.', example_ko_2 = '연어는 오메가-3가 풍부한 인기 있는 생선이에요.', example_en_3 = 'She grilled the fish with lemon and herbs.', example_ko_3 = '그녀는 레몬과 허브를 곁들여 생선을 구웠어요.', example_en_4 = 'I prefer fish to meat for dinner.', example_ko_4 = '저는 저녁으로 고기보다 생선을 더 좋아해요.', example_en_5 = 'The fish soup smells delicious from the kitchen.', example_ko_5 = '주방에서 생선 수프 냄새가 정말 맛있게 나요.' WHERE id = 'w_cooking_A1_07';

UPDATE words SET example_en_2 = 'Rice is the main staple food in many Asian countries.', example_ko_2 = '쌀은 많은 아시아 국가의 주요 주식이에요.', example_en_3 = 'He always adds a little salt when cooking rice.', example_ko_3 = '그는 쌀을 지을 때 항상 소금을 조금 넣어요.', example_en_4 = 'Can you serve me a second bowl of rice, please?', example_ko_4 = '밥을 한 그릇 더 주실 수 있을까요?', example_en_5 = 'Leftover rice can be used to make fried rice the next day.', example_ko_5 = '남은 밥은 다음 날 볶음밥을 만드는 데 쓸 수 있어요.' WHERE id = 'w_cooking_A1_08';

UPDATE words SET example_en_2 = 'She toasts the bread before spreading butter on it.', example_ko_2 = '그녀는 버터를 바르기 전에 빵을 구워요.', example_en_3 = 'This bread was baked fresh this morning.', example_ko_3 = '이 빵은 오늘 아침에 갓 구운 거예요.', example_en_4 = 'He makes his own bread every weekend.', example_ko_4 = '그는 매주 주말에 직접 빵을 만들어요.', example_en_5 = 'The bakery sells different types of bread every day.', example_ko_5 = '그 빵집은 매일 다양한 종류의 빵을 팔아요.' WHERE id = 'w_cooking_A1_09';

UPDATE words SET example_en_2 = 'Beat two eggs together with the milk.', example_ko_2 = '달걀 두 개를 우유와 함께 잘 풀어 주세요.', example_en_3 = 'She made a perfect omelette with three eggs.', example_ko_3 = '그녀는 달걀 세 개로 완벽한 오믈렛을 만들었어요.', example_en_4 = 'A boiled egg is a quick and healthy breakfast option.', example_ko_4 = '삶은 달걀은 빠르고 건강한 아침 식사예요.', example_en_5 = 'The recipe calls for two eggs at room temperature.', example_ko_5 = '조리법에는 실온의 달걀 두 개가 필요해요.' WHERE id = 'w_cooking_A1_10';

UPDATE words SET example_en_2 = 'She warms the milk before adding it to the dough.', example_ko_2 = '그녀는 반죽에 넣기 전에 우유를 데워요.', example_en_3 = 'A glass of warm milk helps me sleep at night.', example_ko_3 = '따뜻한 우유 한 잔이 밤에 잠드는 데 도움이 돼요.', example_en_4 = 'This sauce is made with milk and cheese.', example_ko_4 = '이 소스는 우유와 치즈로 만들어요.', example_en_5 = 'Always use full-fat milk for a richer flavour.', example_ko_5 = '더 진한 풍미를 원하면 항상 전유를 사용해 주세요.' WHERE id = 'w_cooking_A1_11';

UPDATE words SET example_en_2 = 'She spread a thick layer of butter on the toast.', example_ko_2 = '그녀는 토스트에 버터를 두껍게 발랐어요.', example_en_3 = 'Butter adds a rich flavour to baked goods.', example_ko_3 = '버터는 구운 음식에 진한 풍미를 더해 줘요.', example_en_4 = 'He uses unsalted butter when baking cakes.', example_ko_4 = '그는 케이크를 구울 때 무염 버터를 사용해요.', example_en_5 = 'The butter melted quickly in the warm pan.', example_ko_5 = '버터가 따뜻한 팬에서 빠르게 녹았어요.' WHERE id = 'w_cooking_A1_12';

UPDATE words SET example_en_2 = 'A little bit of salt can bring out the natural sweetness of vegetables.', example_ko_2 = '소금을 조금 넣으면 채소의 자연스러운 단맛이 살아나요.', example_en_3 = 'Too much salt is not good for your health.', example_ko_3 = '소금을 너무 많이 섭취하면 건강에 좋지 않아요.', example_en_4 = 'He seasoned the soup with salt and pepper.', example_ko_4 = '그는 수프에 소금과 후추로 간을 했어요.', example_en_5 = 'Always taste the dish before adding more salt.', example_ko_5 = '소금을 더 넣기 전에 항상 음식 맛을 먼저 봐 주세요.' WHERE id = 'w_cooking_A1_13';

UPDATE words SET example_en_2 = 'The recipe needs half a cup of sugar.', example_ko_2 = '이 조리법에는 설탕 반 컵이 필요해요.', example_en_3 = 'She reduced the amount of sugar to make it healthier.', example_ko_3 = '그녀는 더 건강하게 만들기 위해 설탕 양을 줄였어요.', example_en_4 = 'Brown sugar gives cookies a deeper flavour.', example_ko_4 = '흑설탕은 쿠키에 더 깊은 풍미를 더해 줘요.', example_en_5 = 'He puts one teaspoon of sugar in his coffee every morning.', example_ko_5 = '그는 매일 아침 커피에 설탕을 한 티스푼 넣어요.' WHERE id = 'w_cooking_A1_14';

UPDATE words SET example_en_2 = 'She adds pepper to almost every dish she makes.', example_ko_2 = '그녀는 거의 모든 요리에 후추를 넣어요.', example_en_3 = 'Freshly ground pepper tastes much better than pre-ground.', example_ko_3 = '갓 간 후추는 미리 간 것보다 훨씬 맛있어요.', example_en_4 = 'He sprinkled a little pepper over the fried eggs.', example_ko_4 = '그는 달걀프라이 위에 후추를 조금 뿌렸어요.', example_en_5 = 'Black pepper and salt are always on the dining table.', example_ko_5 = '식탁에는 항상 검은 후추와 소금이 놓여 있어요.' WHERE id = 'w_cooking_A1_15';

UPDATE words SET example_en_2 = 'Olive oil is popular for cooking and salad dressings.', example_ko_2 = '올리브 오일은 요리와 샐러드 드레싱에 인기가 많아요.', example_en_3 = 'He drizzled oil over the vegetables before roasting them.', example_ko_3 = '그는 채소를 굽기 전에 오일을 뿌렸어요.', example_en_4 = 'Use a small amount of oil so the food does not stick.', example_ko_4 = '음식이 달라붙지 않도록 오일을 조금만 사용해 주세요.', example_en_5 = 'Sesame oil adds a wonderful aroma to the dish.', example_ko_5 = '참기름은 요리에 멋진 향을 더해 줘요.' WHERE id = 'w_cooking_A1_16';

UPDATE words SET example_en_2 = 'She drinks eight glasses of water every day.', example_ko_2 = '그녀는 매일 물을 여덟 잔 마셔요.', example_en_3 = 'Add a cup of water to the sauce and stir well.', example_ko_3 = '소스에 물 한 컵을 넣고 잘 저어 주세요.', example_en_4 = 'Make sure the water is boiling before adding the noodles.', example_ko_4 = '국수를 넣기 전에 물이 끓는지 확인해 주세요.', example_en_5 = 'Cold water is best for washing fruits and vegetables.', example_ko_5 = '과일과 채소를 씻을 때는 찬물이 가장 좋아요.' WHERE id = 'w_cooking_A1_17';

UPDATE words SET example_en_2 = 'Keep the kitchen tidy while you are cooking.', example_ko_2 = '요리하는 동안 주방을 깔끔하게 유지해 주세요.', example_en_3 = 'She installed new shelves in the kitchen last week.', example_ko_3 = '그녀는 지난주에 주방에 새 선반을 설치했어요.', example_en_4 = 'The kitchen smells wonderful when something is baking.', example_ko_4 = '무언가를 구울 때 주방에서 좋은 냄새가 나요.', example_en_5 = 'He reorganised the kitchen to make cooking easier.', example_ko_5 = '그는 요리하기 더 편하도록 주방을 정리했어요.' WHERE id = 'w_cooking_A1_18';

UPDATE words SET example_en_2 = 'Always keep the knife away from children.', example_ko_2 = '칼은 항상 아이들 손에 닿지 않는 곳에 보관해 주세요.', example_en_3 = 'She sharpened the knife before cutting the meat.', example_ko_3 = '그녀는 고기를 자르기 전에 칼을 갈았어요.', example_en_4 = 'A good knife makes cooking much easier.', example_ko_4 = '좋은 칼이 있으면 요리하기가 훨씬 편해요.', example_en_5 = 'Wash the knife carefully after each use.', example_ko_5 = '칼은 사용 후 매번 조심스럽게 씻어 주세요.' WHERE id = 'w_cooking_A1_19';

UPDATE words SET example_en_2 = 'She arranged the vegetables nicely on a large plate.', example_ko_2 = '그녀는 큰 접시에 채소를 예쁘게 담았어요.', example_en_3 = 'He washed the plates before setting the table.', example_ko_3 = '그는 식탁을 차리기 전에 접시를 씻었어요.', example_en_4 = 'The waiter brought a hot plate of pasta.', example_ko_4 = '웨이터가 뜨거운 파스타 접시를 가져왔어요.', example_en_5 = 'Each plate was decorated with a sprig of parsley.', example_ko_5 = '각 접시에는 파슬리 한 가지가 장식되어 있었어요.' WHERE id = 'w_cooking_A1_20';

UPDATE words SET example_en_2 = 'She filled the bowl with warm oatmeal.', example_ko_2 = '그녀는 그릇에 따뜻한 오트밀을 가득 담았어요.', example_en_3 = 'He used a small bowl to mix the dressing.', example_ko_3 = '그는 드레싱을 섞는 데 작은 그릇을 사용했어요.', example_en_4 = 'The salad bowl is in the top cupboard.', example_ko_4 = '샐러드 그릇은 위쪽 찬장에 있어요.', example_en_5 = 'She served the noodles in individual bowls.', example_ko_5 = '그녀는 국수를 각각의 그릇에 담아 냈어요.' WHERE id = 'w_cooking_A1_21';

UPDATE words SET example_en_2 = 'He drank a cup of hot green tea after dinner.', example_ko_2 = '그는 저녁 식사 후 뜨거운 녹차 한 잔을 마셨어요.', example_en_3 = 'Please use a measuring cup for accurate amounts.', example_ko_3 = '정확한 양을 위해 계량컵을 사용해 주세요.', example_en_4 = 'She bought a new set of cups for the kitchen.', example_ko_4 = '그녀는 주방용 컵 세트를 새로 샀어요.', example_en_5 = 'Half a cup of oats is enough for one serving.', example_ko_5 = '귀리 반 컵이면 한 인분에 충분해요.' WHERE id = 'w_cooking_A1_22';

UPDATE words SET example_en_2 = 'The pot of soup has been simmering for an hour.', example_ko_2 = '수프 냄비가 한 시간째 끓고 있어요.', example_en_3 = 'She put the pot on the stove to heat the broth.', example_ko_3 = '그녀는 육수를 데우려고 냄비를 가스레인지에 올렸어요.', example_en_4 = 'He owns a large pot for cooking big batches of rice.', example_ko_4 = '그는 많은 양의 밥을 짓기 위한 큰 냄비를 갖고 있어요.', example_en_5 = 'Wash the pot thoroughly after cooking fatty foods.', example_ko_5 = '기름진 음식을 조리한 후에는 냄비를 깨끗이 씻어 주세요.' WHERE id = 'w_cooking_A1_23';

UPDATE words SET example_en_2 = 'She uses a non-stick pan so food does not burn.', example_ko_2 = '그녀는 음식이 타지 않도록 논스틱 팬을 사용해요.', example_en_3 = 'Heat the pan on medium heat before adding the butter.', example_ko_3 = '버터를 넣기 전에 팬을 중불로 달궈 주세요.', example_en_4 = 'He cooked the steak in a cast-iron pan.', example_ko_4 = '그는 주철 팬에서 스테이크를 요리했어요.', example_en_5 = 'The sizzling sound from the pan means the oil is hot enough.', example_ko_5 = '팬에서 지글거리는 소리가 나면 기름이 충분히 달궈진 거예요.' WHERE id = 'w_cooking_A1_24';

UPDATE words SET example_en_2 = 'Boil the chicken until it is fully cooked inside.', example_ko_2 = '닭고기가 완전히 익을 때까지 끓여 주세요.', example_en_3 = 'She boiled the vegetables to make them softer.', example_ko_3 = '그녀는 채소를 더 부드럽게 만들기 위해 삶았어요.', example_en_4 = 'Bring the milk to a boil and then reduce the heat.', example_ko_4 = '우유를 끓인 다음 불을 줄여 주세요.', example_en_5 = 'It takes about ten minutes to boil potatoes until tender.', example_ko_5 = '감자가 부드러워질 때까지 끓이는 데 약 10분이 걸려요.' WHERE id = 'w_cooking_A1_25';

UPDATE words SET example_en_2 = 'He fried the onions until they were golden brown.', example_ko_2 = '그는 양파가 황금빛 갈색이 될 때까지 볶았어요.', example_en_3 = 'She does not like to fry food because it uses too much oil.', example_ko_3 = '그녀는 기름이 너무 많이 들어서 튀기는 것을 좋아하지 않아요.', example_en_4 = 'Fry the garlic for one minute before adding the tomatoes.', example_ko_4 = '토마토를 넣기 전에 마늘을 1분 동안 볶아 주세요.', example_en_5 = 'He fried fish for the whole family on Friday night.', example_ko_5 = '그는 금요일 저녁에 온 가족을 위해 생선을 튀겼어요.' WHERE id = 'w_cooking_A1_26';

UPDATE words SET example_en_2 = 'He baked fresh bread every Sunday morning.', example_ko_2 = '그는 매주 일요일 아침에 신선한 빵을 구웠어요.', example_en_3 = 'Bake the cookies at 180°C for twelve minutes.', example_ko_3 = '쿠키를 180°C에서 12분 동안 구워 주세요.', example_en_4 = 'She enjoys baking as a relaxing weekend activity.', example_ko_4 = '그녀는 편안한 주말 활동으로 베이킹을 즐겨요.', example_en_5 = 'The muffins are ready when they are golden on top.', example_ko_5 = '머핀은 윗면이 황금빛이 되면 다 된 거예요.' WHERE id = 'w_cooking_A1_27';

UPDATE words SET example_en_2 = 'Mix the eggs and sugar until the mixture is pale.', example_ko_2 = '달걀과 설탕을 혼합물이 연한 색이 될 때까지 섞어 주세요.', example_en_3 = 'She mixed the salad dressing in a small jar.', example_ko_3 = '그녀는 작은 병에 샐러드 드레싱을 섞었어요.', example_en_4 = 'He mixed the spices together before adding them to the pan.', example_ko_4 = '그는 향신료를 팬에 넣기 전에 함께 섞었어요.', example_en_5 = 'Do not overmix the batter or the cake will be tough.', example_ko_5 = '반죽을 너무 많이 섞으면 케이크가 딱딱해질 수 있어요.' WHERE id = 'w_cooking_A1_28';

UPDATE words SET example_en_2 = 'Please cut the bread into thin slices.', example_ko_2 = '빵을 얇은 조각으로 잘라 주세요.', example_en_3 = 'She carefully cut the meat into equal portions.', example_ko_3 = '그녀는 고기를 똑같은 조각으로 신중하게 잘랐어요.', example_en_4 = 'He cut the watermelon and shared it with everyone.', example_ko_4 = '그는 수박을 자르고 모두와 나눠 먹었어요.', example_en_5 = 'Cut the vegetables into bite-sized pieces before stir-frying.', example_ko_5 = '채소는 볶기 전에 한입 크기로 잘라 주세요.' WHERE id = 'w_cooking_A1_29';

UPDATE words SET example_en_2 = 'Wash the grapes before putting them in the fruit bowl.', example_ko_2 = '포도를 과일 그릇에 담기 전에 씻어 주세요.', example_en_3 = 'She always washes her hands before cooking.', example_ko_3 = '그녀는 요리 전에 항상 손을 씻어요.', example_en_4 = 'He washed the strawberries and put them in a bowl.', example_ko_4 = '그는 딸기를 씻어 그릇에 담았어요.', example_en_5 = 'Wash the rice two or three times before cooking it.', example_ko_5 = '쌀은 짓기 전에 두세 번 씻어 주세요.' WHERE id = 'w_cooking_A1_30';

UPDATE words SET example_en_2 = 'The chef tasted the broth and added more salt.', example_ko_2 = '요리사는 육수를 맛보고 소금을 더 넣었어요.', example_en_3 = 'Can I taste the sauce before you serve it?', example_ko_3 = '내기 전에 소스 맛을 봐도 될까요?', example_en_4 = 'She tasted the dough and decided it needed more sugar.', example_ko_4 = '그녀는 반죽을 맛보고 설탕이 더 필요하다고 판단했어요.', example_en_5 = 'It is important to taste your food as you cook.', example_ko_5 = '요리하면서 음식 맛을 보는 것이 중요해요.' WHERE id = 'w_cooking_A1_31';

UPDATE words SET example_en_2 = 'The oven is very hot right now—do not touch it.', example_ko_2 = '오븐이 지금 매우 뜨거워요. 건드리지 마세요.', example_en_3 = 'She served the soup while it was still hot.', example_ko_3 = '그녀는 수프가 아직 뜨거울 때 내놓았어요.', example_en_4 = 'The coffee is too hot to drink right away.', example_ko_4 = '커피가 너무 뜨거워서 바로 마시기 어려워요.', example_en_5 = 'Eat the noodles while they are hot for the best taste.', example_ko_5 = '국수는 뜨거울 때 먹어야 가장 맛있어요.' WHERE id = 'w_cooking_A1_32';

UPDATE words SET example_en_2 = 'A cold glass of water is refreshing on a hot day.', example_ko_2 = '더운 날에는 차가운 물 한 잔이 시원하게 느껴져요.', example_en_3 = 'The cold storage keeps fruits and vegetables fresh longer.', example_ko_3 = '냉장 보관을 하면 과일과 채소가 더 오래 신선하게 유지돼요.', example_en_4 = 'He put the leftovers in the fridge to keep them cold.', example_ko_4 = '그는 남은 음식이 차갑게 유지되도록 냉장고에 넣었어요.', example_en_5 = 'Cold noodles are especially popular in summer.', example_ko_5 = '차가운 국수는 여름에 특히 인기 있어요.' WHERE id = 'w_cooking_A1_33';

UPDATE words SET example_en_2 = 'The bread smells so fresh right out of the oven.', example_ko_2 = '오븐에서 갓 나온 빵에서 신선한 냄새가 나요.', example_en_3 = 'Always choose fresh ingredients when you can.', example_ko_3 = '가능하면 항상 신선한 재료를 선택하세요.', example_en_4 = 'She keeps a supply of fresh herbs on her windowsill.', example_ko_4 = '그녀는 창가에 신선한 허브를 키워요.', example_en_5 = 'Fresh lemon juice brightens the flavour of many dishes.', example_ko_5 = '신선한 레몬즙은 많은 요리의 맛을 살려 줘요.' WHERE id = 'w_cooking_A1_34';

UPDATE words SET example_en_2 = 'She made a sweet syrup from sugar and water.', example_ko_2 = '그녀는 설탕과 물로 달콤한 시럽을 만들었어요.', example_en_3 = 'The sweet smell of fresh pastries filled the bakery.', example_ko_3 = '갓 구운 페이스트리의 달콤한 냄새가 빵집 안을 가득 채웠어요.', example_en_4 = 'He prefers sweet desserts over savoury snacks.', example_ko_4 = '그는 짭짤한 간식보다 달콤한 디저트를 더 좋아해요.', example_en_5 = 'Ripe mangoes are wonderfully sweet.', example_ko_5 = '잘 익은 망고는 정말 달콤해요.' WHERE id = 'w_cooking_A1_35';

-- A2
UPDATE words SET example_en_2 = 'She sifts the flour to remove any lumps.', example_ko_2 = '그녀는 덩어리를 없애기 위해 밀가루를 체로 쳐요.', example_en_3 = 'He uses whole wheat flour for a healthier bread.', example_ko_3 = '그는 더 건강한 빵을 위해 통밀가루를 사용해요.', example_en_4 = 'Dust the work surface lightly with flour before kneading.', example_ko_4 = '반죽하기 전에 작업대에 밀가루를 살짝 뿌려 주세요.', example_en_5 = 'The bag of flour in the cupboard is almost empty.', example_ko_5 = '찬장에 있는 밀가루 봉지가 거의 다 떨어졌어요.' WHERE id = 'w_cooking_A2_01';

UPDATE words SET example_en_2 = 'She makes homemade pasta from scratch every weekend.', example_ko_2 = '그녀는 매주 주말에 처음부터 직접 파스타를 만들어요.', example_en_3 = 'This pasta dish is ready in under fifteen minutes.', example_ko_3 = '이 파스타 요리는 15분 안에 완성돼요.', example_en_4 = 'He adds olive oil to the pasta so it does not stick together.', example_ko_4 = '그는 파스타가 서로 달라붙지 않도록 올리브 오일을 넣어요.', example_en_5 = 'She tossed the pasta with a fresh tomato sauce.', example_ko_5 = '그녀는 파스타를 신선한 토마토소스와 버무렸어요.' WHERE id = 'w_cooking_A2_02';

UPDATE words SET example_en_2 = 'He ordered a bowl of noodle soup for lunch.', example_ko_2 = '그는 점심으로 국수 한 그릇을 주문했어요.', example_en_3 = 'She stirs the noodles so they do not clump together.', example_ko_3 = '그녀는 국수가 뭉치지 않도록 저어요.', example_en_4 = 'Rice noodles cook much faster than wheat noodles.', example_ko_4 = '쌀국수는 밀국수보다 훨씬 빨리 익어요.', example_en_5 = 'He topped the noodles with sliced beef and spring onions.', example_ko_5 = '그는 국수 위에 얇게 썬 소고기와 파를 얹었어요.' WHERE id = 'w_cooking_A2_03';

UPDATE words SET example_en_2 = 'She roasted a whole chicken for Sunday dinner.', example_ko_2 = '그녀는 일요일 저녁 식사를 위해 닭 한 마리를 통째로 구웠어요.', example_en_3 = 'He cut the chicken into pieces before cooking it.', example_ko_3 = '그는 닭고기를 요리하기 전에 조각으로 잘랐어요.', example_en_4 = 'Chicken breast is lower in fat than chicken thigh.', example_ko_4 = '닭 가슴살은 닭 허벅지살보다 지방이 적어요.', example_en_5 = 'The chicken was so tender it fell apart with a fork.', example_ko_5 = '닭고기가 너무 부드러워서 포크로 찔러도 쉽게 부서졌어요.' WHERE id = 'w_cooking_A2_04';

UPDATE words SET example_en_2 = 'He grilled the beef over charcoal for a smoky flavour.', example_ko_2 = '그는 훈제 향을 내기 위해 숯불에 소고기를 구웠어요.', example_en_3 = 'She thinly sliced the beef for the hot pot.', example_ko_3 = '그녀는 샤브샤브를 위해 소고기를 얇게 썰었어요.', example_en_4 = 'Ground beef is used to make burgers and meat sauce.', example_ko_4 = '간 소고기는 버거와 미트소스를 만드는 데 사용해요.', example_en_5 = 'The beef stew was rich and full of flavour.', example_ko_5 = '소고기 스튜는 진하고 풍미가 가득했어요.' WHERE id = 'w_cooking_A2_05';

UPDATE words SET example_en_2 = 'She braised the pork for several hours until it was very tender.', example_ko_2 = '그녀는 돼지고기가 매우 부드러워질 때까지 몇 시간 동안 찜으로 익혔어요.', example_en_3 = 'Pork belly is very popular in Korean cuisine.', example_ko_3 = '삼겹살은 한국 요리에서 매우 인기 있어요.', example_en_4 = 'He mixed ground pork with garlic and ginger for the filling.', example_ko_4 = '그는 속 재료를 위해 간 돼지고기에 마늘과 생강을 섞었어요.', example_en_5 = 'Pork ribs are best cooked slowly over low heat.', example_ko_5 = '돼지 갈비는 약한 불에 천천히 익히는 것이 가장 좋아요.' WHERE id = 'w_cooking_A2_06';

UPDATE words SET example_en_2 = 'She caramelised the onions slowly over low heat.', example_ko_2 = '그녀는 약한 불에서 천천히 양파를 캐러멜화했어요.', example_en_3 = 'Onion adds a savoury depth to any soup or stew.', example_ko_3 = '양파는 어떤 수프나 스튜에도 감칠맛 나는 깊이를 더해 줘요.', example_en_4 = 'He diced the onion very finely to avoid strong bites.', example_ko_4 = '그는 강한 맛이 나지 않도록 양파를 매우 잘게 다졌어요.', example_en_5 = 'Raw onion in a salad gives a sharp, crisp flavour.', example_ko_5 = '샐러드에 생 양파를 넣으면 날카롭고 아삭한 맛이 나요.' WHERE id = 'w_cooking_A2_07';

UPDATE words SET example_en_2 = 'She roasted whole garlic cloves in the oven.', example_ko_2 = '그녀는 오븐에서 마늘을 통째로 구웠어요.', example_en_3 = 'Garlic and ginger are the base of many Asian dishes.', example_ko_3 = '마늘과 생강은 많은 아시아 요리의 기본 재료예요.', example_en_4 = 'He minced the garlic and added it to the hot oil.', example_ko_4 = '그는 마늘을 다져 뜨거운 기름에 넣었어요.', example_en_5 = 'The smell of garlic cooking makes everyone hungry.', example_ko_5 = '마늘 볶는 냄새를 맡으면 누구나 배가 고파져요.' WHERE id = 'w_cooking_A2_08';

UPDATE words SET example_en_2 = 'She made a fresh tomato sauce from scratch.', example_ko_2 = '그녀는 처음부터 직접 신선한 토마토소스를 만들었어요.', example_en_3 = 'Ripe tomatoes are sweeter and juicier than unripe ones.', example_ko_3 = '잘 익은 토마토는 덜 익은 것보다 더 달콤하고 즙이 풍부해요.', example_en_4 = 'He sliced the tomatoes and layered them with mozzarella.', example_ko_4 = '그는 토마토를 슬라이스해서 모차렐라와 겹겹이 쌓았어요.', example_en_5 = 'Cherry tomatoes are great for adding colour to salads.', example_ko_5 = '방울토마토는 샐러드에 색감을 더하는 데 좋아요.' WHERE id = 'w_cooking_A2_09';

UPDATE words SET example_en_2 = 'She adds shredded carrot to the coleslaw.', example_ko_2 = '그녀는 코울슬로에 채 썬 당근을 넣어요.', example_en_3 = 'Roasted carrots become sweet and caramelised.', example_ko_3 = '구운 당근은 달콤하게 캐러멜화돼요.', example_en_4 = 'He juiced the carrots with apples and ginger.', example_ko_4 = '그는 당근을 사과, 생강과 함께 갈아 주스로 만들었어요.', example_en_5 = 'Baby carrots make a healthy and easy snack.', example_ko_5 = '미니 당근은 건강하고 간편한 간식이에요.' WHERE id = 'w_cooking_A2_10';

UPDATE words SET example_en_2 = 'She made crispy potato wedges in the oven.', example_ko_2 = '그녀는 오븐에서 바삭한 감자 웨지를 만들었어요.', example_en_3 = 'Mashed potato goes well with roast chicken.', example_ko_3 = '으깬 감자는 로스트 치킨과 잘 어울려요.', example_en_4 = 'He baked the potatoes whole and topped them with butter.', example_ko_4 = '그는 감자를 통째로 구워 버터를 얹었어요.', example_en_5 = 'Sweet potato is a nutritious alternative to regular potato.', example_ko_5 = '고구마는 일반 감자를 대체할 수 있는 영양가 높은 식품이에요.' WHERE id = 'w_cooking_A2_11';

UPDATE words SET example_en_2 = 'He added cucumber slices to his water for a refreshing taste.', example_ko_2 = '그는 상쾌한 맛을 위해 물에 오이 슬라이스를 넣었어요.', example_en_3 = 'Cucumber and yoghurt make a cool and creamy dip.', example_ko_3 = '오이와 요거트를 섞으면 시원하고 크리미한 딥이 돼요.', example_en_4 = 'She spiralised the cucumber into long, thin noodles.', example_ko_4 = '그녀는 오이를 길고 가는 국수 모양으로 채 썰었어요.', example_en_5 = 'Fresh cucumber from the garden is wonderfully crisp.', example_ko_5 = '텃밭에서 딴 신선한 오이는 정말 아삭아삭해요.' WHERE id = 'w_cooking_A2_12';

UPDATE words SET example_en_2 = 'She uses butter lettuce because it has a soft texture.', example_ko_2 = '그녀는 부드러운 식감 때문에 버터 상추를 사용해요.', example_en_3 = 'He layered the burger with lettuce, tomato, and cheese.', example_ko_3 = '그는 버거에 상추, 토마토, 치즈를 겹겹이 쌓았어요.', example_en_4 = 'Romaine lettuce is crunchier than iceberg lettuce.', example_ko_4 = '로메인 상추는 아이스버그 상추보다 더 아삭해요.', example_en_5 = 'Store lettuce in the fridge to keep it fresh.', example_ko_5 = '상추는 신선하게 유지하려면 냉장고에 보관해 주세요.' WHERE id = 'w_cooking_A2_13';

UPDATE words SET example_en_2 = 'She grated cheese over the pasta before serving.', example_ko_2 = '그녀는 파스타를 내기 전에 치즈를 갈아 뿌렸어요.', example_en_3 = 'Melted cheese on toast is a simple and comforting meal.', example_ko_3 = '토스트 위에 녹인 치즈는 간단하고 위로가 되는 음식이에요.', example_en_4 = 'He used feta cheese to add saltiness to the salad.', example_ko_4 = '그는 샐러드에 짭짤한 맛을 더하기 위해 페타 치즈를 사용했어요.', example_en_5 = 'Aged cheese has a much stronger and deeper flavour.', example_ko_5 = '숙성된 치즈는 훨씬 강하고 깊은 풍미를 가지고 있어요.' WHERE id = 'w_cooking_A2_14';

UPDATE words SET example_en_2 = 'She made a vegetable soup with carrots, onions, and celery.', example_ko_2 = '그녀는 당근, 양파, 셀러리로 채소 수프를 만들었어요.', example_en_3 = 'The soup needs to simmer for at least thirty minutes.', example_ko_3 = '수프는 최소 30분 동안 끓여야 해요.', example_en_4 = 'He blended the soup until it was completely smooth.', example_ko_4 = '그는 수프가 완전히 부드러워질 때까지 갈았어요.', example_en_5 = 'A bowl of hot soup is perfect on a cold winter day.', example_ko_5 = '추운 겨울날에는 뜨거운 수프 한 그릇이 딱이에요.' WHERE id = 'w_cooking_A2_15';

UPDATE words SET example_en_2 = 'She tossed the pasta with a creamy mushroom sauce.', example_ko_2 = '그녀는 파스타를 크리미한 버섯 소스와 버무렸어요.', example_en_3 = 'The sauce is too thick—add a little water to thin it out.', example_ko_3 = '소스가 너무 걸쭉해요. 물을 조금 넣어서 농도를 낮춰 주세요.', example_en_4 = 'He made a spicy chilli sauce to go with the grilled meat.', example_ko_4 = '그는 구운 고기에 곁들일 매운 칠리소스를 만들었어요.', example_en_5 = 'Always stir the sauce over low heat to prevent burning.', example_ko_5 = '소스가 타지 않도록 항상 약한 불에서 저어 주세요.' WHERE id = 'w_cooking_A2_16';

UPDATE words SET example_en_2 = 'She tossed the salad with vinegar and olive oil.', example_ko_2 = '그녀는 샐러드를 식초와 올리브 오일로 버무렸어요.', example_en_3 = 'A green salad is the perfect side dish for grilled fish.', example_ko_3 = '그린 샐러드는 구운 생선에 완벽한 반찬이에요.', example_en_4 = 'He added walnuts and cranberries to the salad for texture.', example_ko_4 = '그는 식감을 위해 샐러드에 호두와 크랜베리를 넣었어요.', example_en_5 = 'Fresh salad is best eaten immediately after making it.', example_ko_5 = '신선한 샐러드는 만든 즉시 먹는 것이 가장 좋아요.' WHERE id = 'w_cooking_A2_17';

UPDATE words SET example_en_2 = 'She always prepares breakfast the night before to save time.', example_ko_2 = '그녀는 시간을 절약하기 위해 항상 전날 밤에 아침을 준비해요.', example_en_3 = 'A healthy breakfast gives you energy for the morning.', example_ko_3 = '건강한 아침 식사는 오전 내내 에너지를 줘요.', example_en_4 = 'He had eggs, toast, and fresh fruit for breakfast.', example_ko_4 = '그는 아침으로 달걀, 토스트, 신선한 과일을 먹었어요.', example_en_5 = 'Breakfast is often called the most important meal of the day.', example_ko_5 = '아침 식사는 흔히 하루 중 가장 중요한 식사라고 해요.' WHERE id = 'w_cooking_A2_18';

UPDATE words SET example_en_2 = 'He takes a packed lunch to work every day.', example_ko_2 = '그는 매일 도시락을 싸서 출근해요.', example_en_3 = 'She had a light lunch of soup and salad.', example_ko_3 = '그녀는 수프와 샐러드로 가볍게 점심을 먹었어요.', example_en_4 = 'We always go out for lunch on Fridays.', example_ko_4 = '우리는 항상 금요일에 점심을 먹으러 나가요.', example_en_5 = 'Lunch is usually served from twelve to two at the cafeteria.', example_ko_5 = '구내식당에서는 보통 12시부터 2시까지 점심을 제공해요.' WHERE id = 'w_cooking_A2_19';

UPDATE words SET example_en_2 = 'She prefers a light dinner so she sleeps better.', example_ko_2 = '그녀는 더 잘 자기 위해 저녁을 가볍게 먹어요.', example_en_3 = 'He cooked a special dinner for their anniversary.', example_ko_3 = '그는 기념일을 위해 특별한 저녁 식사를 요리했어요.', example_en_4 = 'What time do you usually have dinner?', example_ko_4 = '보통 몇 시에 저녁을 드세요?', example_en_5 = 'Dinner with the whole family is a great time to catch up.', example_ko_5 = '온 가족이 함께하는 저녁 식사는 서로의 이야기를 나누기 좋은 시간이에요.' WHERE id = 'w_cooking_A2_20';

UPDATE words SET example_en_2 = 'She made a healthy snack with apple slices and peanut butter.', example_ko_2 = '그녀는 사과 슬라이스와 땅콩 버터로 건강한 간식을 만들었어요.', example_en_3 = 'He bought a bag of mixed nuts as a snack for the trip.', example_ko_3 = '그는 여행용 간식으로 견과류 믹스 한 봉지를 샀어요.', example_en_4 = 'Avoid eating sugary snacks before bedtime.', example_ko_4 = '자기 전에 단 간식을 먹지 않는 것이 좋아요.', example_en_5 = 'Rice cakes are a popular low-calorie snack.', example_ko_5 = '떡은 칼로리가 낮은 인기 있는 간식이에요.' WHERE id = 'w_cooking_A2_21';

UPDATE words SET example_en_2 = 'Three balanced meals a day keep you healthy and focused.', example_ko_2 = '하루 세 끼를 균형 있게 먹으면 건강하고 집중력을 유지할 수 있어요.', example_en_3 = 'She skipped a meal because she was too busy.', example_ko_3 = '그녀는 너무 바빠서 식사를 거르게 됐어요.', example_en_4 = 'Every meal tastes better when shared with family.', example_ko_4 = '모든 식사는 가족과 함께하면 더 맛있어요.', example_en_5 = 'He prepares all his meals for the week on Sunday afternoon.', example_ko_5 = '그는 일요일 오후에 한 주치 식사를 모두 준비해요.' WHERE id = 'w_cooking_A2_22';

UPDATE words SET example_en_2 = 'She asked the deli to slice the ham thinly.', example_ko_2 = '그녀는 델리에 햄을 얇게 잘라 달라고 부탁했어요.', example_en_3 = 'He cut two thick slices of bread for the sandwich.', example_ko_3 = '그는 샌드위치용으로 빵을 두껍게 두 조각 잘랐어요.', example_en_4 = 'Place each slice of cheese on top of a cracker.', example_ko_4 = '크래커 위에 치즈 한 장씩 올려 주세요.', example_en_5 = 'She sliced the brisket against the grain for tenderness.', example_ko_5 = '그녀는 부드럽게 먹기 위해 양지머리를 결 반대 방향으로 썰었어요.' WHERE id = 'w_cooking_A2_23';

UPDATE words SET example_en_2 = 'She learned to peel vegetables quickly with a good peeler.', example_ko_2 = '그녀는 좋은 필러를 사용해 채소 껍질을 빠르게 벗기는 법을 배웠어요.', example_en_3 = 'He peeled and segmented the orange for the fruit salad.', example_ko_3 = '그는 과일 샐러드를 위해 오렌지 껍질을 벗기고 조각냈어요.', example_en_4 = 'Peel the garlic cloves before mincing them.', example_ko_4 = '마늘을 다지기 전에 껍질을 벗겨 주세요.', example_en_5 = 'Leave the skin on the potatoes for extra nutrition.', example_ko_5 = '영양을 더 섭취하려면 감자 껍질을 그대로 두세요.' WHERE id = 'w_cooking_A2_24';

UPDATE words SET example_en_2 = 'She chopped the herbs just before adding them to the dish.', example_ko_2 = '그녀는 허브를 요리에 넣기 직전에 잘게 썰었어요.', example_en_3 = 'He roughly chopped the onions for the stew.', example_ko_3 = '그는 스튜를 위해 양파를 대충 잘게 썰었어요.', example_en_4 = 'Chop the garlic finely for a stronger flavour.', example_ko_4 = '더 강한 풍미를 원하면 마늘을 잘게 다져 주세요.', example_en_5 = 'She chopped all the vegetables in advance to save time.', example_ko_5 = '그녀는 시간을 절약하기 위해 채소를 미리 잘게 썰어 놓았어요.' WHERE id = 'w_cooking_A2_25';

UPDATE words SET example_en_2 = 'He grilled the vegetables on the barbecue until they were charred.', example_ko_2 = '그는 채소가 살짝 탈 때까지 바비큐에서 구웠어요.', example_en_3 = 'She marinated the chicken before grilling it.', example_ko_3 = '그녀는 닭고기를 굽기 전에 재워 두었어요.', example_en_4 = 'Grilled salmon is one of the healthiest meals you can make.', example_ko_4 = '구운 연어는 만들 수 있는 가장 건강한 식사 중 하나예요.', example_en_5 = 'Brush the meat with oil before you grill it.', example_ko_5 = '굽기 전에 고기에 오일을 발라 주세요.' WHERE id = 'w_cooking_A2_26';

UPDATE words SET example_en_2 = 'She roasted the garlic in the oven until it was golden and soft.', example_ko_2 = '그녀는 마늘이 황금빛이 되고 부드러워질 때까지 오븐에서 구웠어요.', example_en_3 = 'He loves roasted pumpkin in autumn soups.', example_ko_3 = '그는 가을 수프에 구운 호박 넣는 것을 좋아해요.', example_en_4 = 'Roast the beef for one hour at 200°C.', example_ko_4 = '소고기를 200°C에서 한 시간 동안 구워 주세요.', example_en_5 = 'Roasting brings out the natural sweetness of root vegetables.', example_ko_5 = '구우면 뿌리채소의 자연스러운 단맛이 살아나요.' WHERE id = 'w_cooking_A2_27';

UPDATE words SET example_en_2 = 'She stirs the risotto constantly to make it creamy.', example_ko_2 = '그녀는 크리미하게 만들기 위해 리소토를 계속 저어요.', example_en_3 = 'He stirs the sauce every few minutes to prevent sticking.', example_ko_3 = '그는 소스가 눌어붙지 않도록 몇 분마다 저어요.', example_en_4 = 'Stir the batter gently until all the flour is mixed in.', example_ko_4 = '밀가루가 모두 섞일 때까지 반죽을 살살 저어 주세요.', example_en_5 = 'She stir-fried the vegetables over high heat.', example_ko_5 = '그녀는 센 불에서 채소를 볶았어요.' WHERE id = 'w_cooking_A2_28';

UPDATE words SET example_en_2 = 'She poured the batter carefully into the muffin tin.', example_ko_2 = '그녀는 반죽을 머핀 틀에 조심스럽게 부었어요.', example_en_3 = 'He poured the gravy over the roasted meat.', example_ko_3 = '그는 구운 고기 위에 그레이비소스를 부었어요.', example_en_4 = 'Pour the dressing over the salad just before serving.', example_ko_4 = '드레싱은 내기 직전에 샐러드 위에 부어 주세요.', example_en_5 = 'She poured warm water into the bowl to dissolve the yeast.', example_ko_5 = '그녀는 이스트를 녹이기 위해 그릇에 따뜻한 물을 부었어요.' WHERE id = 'w_cooking_A2_29';

UPDATE words SET example_en_2 = 'The waiter served the dessert with a smile.', example_ko_2 = '웨이터는 웃으며 디저트를 가져다주었어요.', example_en_3 = 'She served the pasta with a side of garlic bread.', example_ko_3 = '그녀는 파스타를 마늘빵과 함께 냈어요.', example_en_4 = 'Always serve salad chilled for the best taste.', example_ko_4 = '샐러드는 차갑게 해서 내야 가장 맛있어요.', example_en_5 = 'He served the steak on a warm plate to keep it hot.', example_ko_5 = '그는 스테이크가 식지 않도록 따뜻한 접시에 담아 냈어요.' WHERE id = 'w_cooking_A2_30';

UPDATE words SET example_en_2 = 'The rich flavor of the broth comes from hours of simmering.', example_ko_2 = '육수의 진한 풍미는 오랜 시간 끓인 덕분이에요.', example_en_3 = 'She added lemon zest to brighten the flavor of the dish.', example_ko_3 = '그녀는 요리의 맛을 살리기 위해 레몬 제스트를 더했어요.', example_en_4 = 'He described the flavor as both sweet and slightly bitter.', example_ko_4 = '그는 그 맛을 달콤하면서도 약간 씁쓸하다고 표현했어요.', example_en_5 = 'Fresh herbs add wonderful flavor to any dish.', example_ko_5 = '신선한 허브는 어떤 요리에든 훌륭한 풍미를 더해 줘요.' WHERE id = 'w_cooking_A2_31';

UPDATE words SET example_en_2 = 'The dressing has a pleasant sour taste from the lemon juice.', example_ko_2 = '드레싱은 레몬즙 덕분에 상쾌하게 신맛이 나요.', example_en_3 = 'She added a little honey to balance the sour flavour.', example_ko_3 = '그녀는 신맛을 잡기 위해 꿀을 조금 넣었어요.', example_en_4 = 'This yoghurt is quite sour—perfect for cooking.', example_ko_4 = '이 요거트는 꽤 새요. 요리하기에 딱 맞아요.', example_en_5 = 'Sour cream adds a tangy flavour to tacos.', example_ko_5 = '사워크림은 타코에 새콤한 맛을 더해 줘요.' WHERE id = 'w_cooking_A2_32';

UPDATE words SET example_en_2 = 'She prefers salty snacks over sweet ones.', example_ko_2 = '그녀는 단 간식보다 짭짤한 간식을 더 좋아해요.', example_en_3 = 'The soup was too salty, so she added more water.', example_ko_3 = '수프가 너무 짜서 그녀는 물을 더 넣었어요.', example_en_4 = 'He described the cheese as sharp and salty.', example_ko_4 = '그는 그 치즈를 강렬하고 짭짤하다고 표현했어요.', example_en_5 = 'Salty foods can make you feel thirsty very quickly.', example_ko_5 = '짠 음식을 먹으면 금방 목이 말라요.' WHERE id = 'w_cooking_A2_33';

UPDATE words SET example_en_2 = 'The curry is very spicy—be careful if you are sensitive to heat.', example_ko_2 = '카레가 매우 매워요. 매운 음식에 약하면 조심하세요.', example_en_3 = 'She loves spicy food but always keeps yoghurt nearby.', example_ko_3 = '그녀는 매운 음식을 좋아하지만 항상 요거트를 곁에 둬요.', example_en_4 = 'He added extra chilli to make the sauce spicier.', example_ko_4 = '그는 소스를 더 맵게 만들기 위해 고추를 더 넣었어요.', example_en_5 = 'Korean kimchi is famous for its spicy and tangy flavour.', example_ko_5 = '한국의 김치는 매콤하고 새콤한 맛으로 유명해요.' WHERE id = 'w_cooking_A2_34';

UPDATE words SET example_en_2 = 'A mild flavour is best for young children or sensitive stomachs.', example_ko_2 = '순한 맛은 어린아이나 예민한 위장을 가진 사람에게 가장 좋아요.', example_en_3 = 'She chose a mild cheddar for the sauce.', example_ko_3 = '그녀는 소스에 쓸 순한 체다 치즈를 골랐어요.', example_en_4 = 'The soup has a mild flavour with a hint of garlic.', example_ko_4 = '이 수프는 마늘 향이 살짝 나는 순한 맛이에요.', example_en_5 = 'He prefers mild salsa because he cannot handle spicy food.', example_ko_5 = '그는 매운 음식을 못 먹어서 순한 살사를 즐겨요.' WHERE id = 'w_cooking_A2_35';

-- B1
UPDATE words SET example_en_2 = 'She makes her own seasoning blend with herbs and spices.', example_ko_2 = '그녀는 허브와 향신료를 섞어 직접 조미료를 만들어요.', example_en_3 = 'The seasoning gives this dish its distinctive taste.', example_ko_3 = '이 조미료가 이 요리만의 독특한 맛을 만들어 줘요.', example_en_4 = 'He adjusted the seasoning just before serving.', example_ko_4 = '그는 내기 직전에 간을 조절했어요.', example_en_5 = 'Good seasoning is the key to a delicious meal.', example_ko_5 = '좋은 양념이 맛있는 식사의 핵심이에요.' WHERE id = 'w_cooking_B1_01';

UPDATE words SET example_en_2 = 'She left the chicken in the marinade overnight for more flavour.', example_ko_2 = '그녀는 더 깊은 맛을 위해 닭고기를 하룻밤 동안 마리네이드에 재워 두었어요.', example_en_3 = 'The marinade is made with soy sauce, ginger, and garlic.', example_ko_3 = '이 마리네이드는 간장, 생강, 마늘로 만들어요.', example_en_4 = 'Even a short marinade of thirty minutes improves the taste.', example_ko_4 = '30분만 재워도 맛이 훨씬 좋아져요.', example_en_5 = 'He used a citrus marinade to tenderise the pork.', example_ko_5 = '그는 돼지고기를 부드럽게 하기 위해 감귤류 마리네이드를 사용했어요.' WHERE id = 'w_cooking_B1_02';

UPDATE words SET example_en_2 = 'She let the stew simmer for two hours until it was rich and thick.', example_ko_2 = '그녀는 스튜가 진하고 걸쭉해질 때까지 두 시간 동안 끓였어요.', example_en_3 = 'Reduce the heat and let the sauce simmer gently.', example_ko_3 = '불을 줄이고 소스를 약하게 끓여 주세요.', example_en_4 = 'He added stock and left it to simmer on the back burner.', example_ko_4 = '그는 육수를 넣고 뒷쪽 버너에서 은근히 끓였어요.', example_en_5 = 'Let the soup simmer until all the vegetables are tender.', example_ko_5 = '채소가 모두 부드러워질 때까지 수프를 끓여 주세요.' WHERE id = 'w_cooking_B1_03';

UPDATE words SET example_en_2 = 'She prefers to steam vegetables to preserve their vitamins.', example_ko_2 = '그녀는 비타민을 보존하기 위해 채소를 쪄서 먹어요.', example_en_3 = 'Steam the buns for ten minutes until fluffy.', example_ko_3 = '찐빵을 10분 동안 쪄서 폭신하게 만들어 주세요.', example_en_4 = 'He steamed the fish with ginger and soy sauce.', example_ko_4 = '그는 생강과 간장을 넣어 생선을 쪄서 만들었어요.', example_en_5 = 'Steamed rice has a softer and stickier texture.', example_ko_5 = '찐 쌀은 더 부드럽고 찰진 식감이에요.' WHERE id = 'w_cooking_B1_04';

UPDATE words SET example_en_2 = 'She loves to deep-fry doughnuts on the weekend.', example_ko_2 = '그녀는 주말에 도넛을 튀기는 것을 좋아해요.', example_en_3 = 'Deep-fry the tofu until it is golden on the outside.', example_ko_3 = '두부 겉면이 황금빛이 될 때까지 튀겨 주세요.', example_en_4 = 'He uses a thermometer when deep-frying to maintain the right temperature.', example_ko_4 = '그는 튀길 때 온도를 맞추기 위해 온도계를 사용해요.', example_en_5 = 'Deep-fried food should be drained on paper towels.', example_ko_5 = '튀긴 음식은 키친타월 위에 올려 기름을 빼 주세요.' WHERE id = 'w_cooking_B1_05';

UPDATE words SET example_en_2 = 'She sautéed the mushrooms in butter with a pinch of thyme.', example_ko_2 = '그녀는 타임을 조금 넣어 버터에 버섯을 볶았어요.', example_en_3 = 'Sauté the shallots until they are translucent.', example_ko_3 = '샬롯이 투명해질 때까지 볶아 주세요.', example_en_4 = 'He sautéed the spinach quickly over high heat.', example_ko_4 = '그는 센 불에서 시금치를 빠르게 볶았어요.', example_en_5 = 'Sautéed garlic adds great depth to pasta dishes.', example_ko_5 = '볶은 마늘은 파스타 요리에 깊은 맛을 더해 줘요.' WHERE id = 'w_cooking_B1_06';

UPDATE words SET example_en_2 = 'She used a blender to blend the soup until smooth.', example_ko_2 = '그녀는 블렌더로 수프가 부드러워질 때까지 갈았어요.', example_en_3 = 'Blend the berries with yoghurt and honey for a smoothie.', example_ko_3 = '스무디를 만들기 위해 베리류를 요거트와 꿀과 함께 갈아 주세요.', example_en_4 = 'He blended the sauce until there were no lumps left.', example_ko_4 = '그는 덩어리가 없어질 때까지 소스를 갈았어요.', example_en_5 = 'Blend the avocado with lemon juice for a creamy dip.', example_ko_5 = '크리미한 딥을 만들기 위해 아보카도를 레몬즙과 함께 갈아 주세요.' WHERE id = 'w_cooking_B1_07';

UPDATE words SET example_en_2 = 'She whisked the cream until it formed soft peaks.', example_ko_2 = '그녀는 크림이 부드러운 봉우리 모양이 될 때까지 휘저었어요.', example_en_3 = 'Whisk the egg whites until they are stiff.', example_ko_3 = '달걀 흰자가 단단해질 때까지 휘저어 주세요.', example_en_4 = 'He used a whisk to mix the dressing quickly.', example_ko_4 = '그는 거품기를 사용해 드레싱을 빠르게 섞었어요.', example_en_5 = 'Whisk the eggs and milk together before pouring into the pan.', example_ko_5 = '달걀과 우유를 팬에 붓기 전에 함께 휘저어 주세요.' WHERE id = 'w_cooking_B1_08';

UPDATE words SET example_en_2 = 'She kneaded the bread dough for ten minutes by hand.', example_ko_2 = '그녀는 빵 반죽을 손으로 10분 동안 치댔어요.', example_en_3 = 'Knead the dough until it is smooth and elastic.', example_ko_3 = '반죽이 부드럽고 탄력 있어질 때까지 치대 주세요.', example_en_4 = 'He learned the proper technique to knead dough from a baker.', example_ko_4 = '그는 제빵사에게 반죽 치대는 올바른 방법을 배웠어요.', example_en_5 = 'Over-kneading can make the bread too dense.', example_ko_5 = '너무 많이 치대면 빵이 너무 빽빽해질 수 있어요.' WHERE id = 'w_cooking_B1_09';

UPDATE words SET example_en_2 = 'She measures each ingredient carefully to get consistent results.', example_ko_2 = '그녀는 일정한 결과를 얻기 위해 각 재료를 꼼꼼하게 계량해요.', example_en_3 = 'Measure the flour by levelling off the top of the cup.', example_ko_3 = '컵 윗면을 평평하게 깎아 밀가루를 계량해 주세요.', example_en_4 = 'He measured out the spices before adding them.', example_ko_4 = '그는 향신료를 넣기 전에 미리 계량해 두었어요.', example_en_5 = 'It is important to measure liquids at eye level.', example_ko_5 = '액체류는 눈높이에서 계량하는 것이 중요해요.' WHERE id = 'w_cooking_B1_10';

UPDATE words SET example_en_2 = 'She divided the dough into equal portions before shaping.', example_ko_2 = '그녀는 모양을 만들기 전에 반죽을 같은 크기의 부분으로 나눴어요.', example_en_3 = 'Each portion of the meal is carefully calculated for nutrition.', example_ko_3 = '각 식사 부분은 영양을 위해 꼼꼼하게 계산되어 있어요.', example_en_4 = 'He served a generous portion of pasta to each guest.', example_ko_4 = '그는 손님 각자에게 파스타를 넉넉히 담아 주었어요.', example_en_5 = 'Smaller portions can help with managing your calorie intake.', example_ko_5 = '양을 줄이면 칼로리 섭취를 관리하는 데 도움이 돼요.' WHERE id = 'w_cooking_B1_11';

UPDATE words SET example_en_2 = 'She turned the leftover roast chicken into a sandwich filling.', example_ko_2 = '그녀는 남은 로스트 치킨을 샌드위치 속 재료로 활용했어요.', example_en_3 = 'He stores leftovers in airtight containers.', example_ko_3 = '그는 남은 음식을 밀폐 용기에 보관해요.', example_en_4 = 'Leftovers from last night will make a great lunch tomorrow.', example_ko_4 = '어젯밤 남은 음식이 내일 점심으로 훌륭할 거예요.', example_en_5 = 'Never leave leftovers out of the fridge for more than two hours.', example_ko_5 = '남은 음식을 냉장고 밖에 두 시간 이상 방치하지 마세요.' WHERE id = 'w_cooking_B1_12';

UPDATE words SET example_en_2 = 'Refrigerate the dough for at least one hour before rolling it out.', example_ko_2 = '반죽을 펴기 전에 최소 한 시간 동안 냉장 보관해 주세요.', example_en_3 = 'She refrigerates the marinating meat overnight.', example_ko_3 = '그녀는 양념한 고기를 하룻밤 냉장 보관해요.', example_en_4 = 'Always refrigerate dairy products after opening.', example_ko_4 = '유제품은 개봉 후 항상 냉장 보관해 주세요.', example_en_5 = 'Refrigerate the cake for an hour so the frosting sets.', example_ko_5 = '아이싱이 굳도록 케이크를 한 시간 동안 냉장 보관해 주세요.' WHERE id = 'w_cooking_B1_13';

UPDATE words SET example_en_2 = 'She freezes summer berries to use them in the winter.', example_ko_2 = '그녀는 여름 베리류를 겨울에 사용하기 위해 얼려 두어요.', example_en_3 = 'Freeze the soup in individual portions for easy reheating.', example_ko_3 = '수프를 쉽게 데울 수 있도록 한 인분씩 얼려 두세요.', example_en_4 = 'He freezes homemade bread to keep it fresh longer.', example_ko_4 = '그는 직접 만든 빵을 더 오래 신선하게 유지하기 위해 얼려요.', example_en_5 = 'Most soups and stews freeze very well for up to three months.', example_ko_5 = '대부분의 수프와 스튜는 최대 3개월까지 잘 얼려 보관할 수 있어요.' WHERE id = 'w_cooking_B1_14';

UPDATE words SET example_en_2 = 'She thaws frozen meat in the fridge, not on the countertop.', example_ko_2 = '그녀는 냉동 고기를 조리대 위가 아닌 냉장고에서 해동해요.', example_en_3 = 'Thaw the dough overnight in the refrigerator.', example_ko_3 = '반죽은 냉장고에서 하룻밤 동안 해동해 주세요.', example_en_4 = 'It is safest to thaw fish in cold water.', example_ko_4 = '생선은 차가운 물에 해동하는 것이 가장 안전해요.', example_en_5 = 'Never thaw and refreeze meat as it can be unsafe.', example_ko_5 = '고기를 해동 후 다시 얼리는 것은 위험할 수 있으니 피해 주세요.' WHERE id = 'w_cooking_B1_15';

UPDATE words SET example_en_2 = 'She makes a grocery list every Sunday before going shopping.', example_ko_2 = '그녀는 장을 보러 가기 전에 매주 일요일 장보기 목록을 만들어요.', example_en_3 = 'He picked up groceries on the way home from work.', example_ko_3 = '그는 퇴근길에 장을 봤어요.', example_en_4 = 'Fresh grocery shopping twice a week keeps the kitchen well stocked.', example_ko_4 = '일주일에 두 번 신선 식품을 사면 주방을 잘 채울 수 있어요.', example_en_5 = 'Online grocery shopping saves a lot of time.', example_ko_5 = '온라인 장보기는 시간을 많이 절약해 줘요.' WHERE id = 'w_cooking_B1_16';

UPDATE words SET example_en_2 = 'A well-stocked pantry means you can always cook something.', example_ko_2 = '식료품 저장실을 잘 채워 두면 언제든 무언가를 요리할 수 있어요.', example_en_3 = 'She organises her pantry with labels on every shelf.', example_ko_3 = '그녀는 모든 선반에 라벨을 붙여 식료품 저장실을 정리해요.', example_en_4 = 'He checked the pantry before writing his shopping list.', example_ko_4 = '그는 장보기 목록을 작성하기 전에 식료품 저장실을 확인했어요.', example_en_5 = 'Keep canned goods and dried pasta in the pantry.', example_ko_5 = '통조림과 건조 파스타는 식료품 저장실에 보관하세요.' WHERE id = 'w_cooking_B1_17';

UPDATE words SET example_en_2 = 'Fresh herbs like basil and parsley add brightness to pasta.', example_ko_2 = '바질과 파슬리 같은 신선한 허브는 파스타에 생기를 더해 줘요.', example_en_3 = 'She grows herbs on her kitchen windowsill year-round.', example_ko_3 = '그녀는 주방 창가에 일 년 내내 허브를 키워요.', example_en_4 = 'Dried herbs are more concentrated than fresh herbs.', example_ko_4 = '건조 허브는 신선한 허브보다 향이 더 진해요.', example_en_5 = 'Add herbs at the end of cooking to preserve their aroma.', example_ko_5 = '향을 살리려면 요리가 끝날 때 허브를 넣어 주세요.' WHERE id = 'w_cooking_B1_18';

UPDATE words SET example_en_2 = 'She keeps a collection of spices in small labelled jars.', example_ko_2 = '그녀는 라벨이 붙은 작은 병에 각종 향신료를 모아 두어요.', example_en_3 = 'Ground spices lose their potency after about a year.', example_ko_3 = '갈아 놓은 향신료는 약 1년이 지나면 향이 약해져요.', example_en_4 = 'He toasted the spices in a dry pan to bring out their aroma.', example_ko_4 = '그는 향을 살리기 위해 기름 없이 팬에서 향신료를 볶았어요.', example_en_5 = 'A good spice blend is the secret to a great curry.', example_ko_5 = '훌륭한 향신료 조합이 맛있는 카레의 비결이에요.' WHERE id = 'w_cooking_B1_19';

UPDATE words SET example_en_2 = 'She adds a splash of vinegar to brighten up dull sauces.', example_ko_2 = '그녀는 밋밋한 소스를 살리기 위해 식초를 조금 넣어요.', example_en_3 = 'He uses apple cider vinegar in his salad dressings.', example_ko_3 = '그는 샐러드 드레싱에 사과 사이다 식초를 사용해요.', example_en_4 = 'Rice vinegar has a milder flavour than white wine vinegar.', example_ko_4 = '쌀 식초는 화이트 와인 식초보다 맛이 더 순해요.', example_en_5 = 'A dash of vinegar can lift the flavour of a soup.', example_ko_5 = '식초를 조금 넣으면 수프 맛이 살아나요.' WHERE id = 'w_cooking_B1_20';

UPDATE words SET example_en_2 = 'She squeezes fresh lemon over the grilled fish before serving.', example_ko_2 = '그녀는 구운 생선을 내기 전에 신선한 레몬을 짜서 뿌려요.', example_en_3 = 'He adds lemon zest to add brightness to the dessert.', example_ko_3 = '그는 디저트에 생기를 더하기 위해 레몬 제스트를 넣어요.', example_en_4 = 'Lemon juice prevents cut fruits from browning.', example_ko_4 = '레몬즙을 뿌리면 자른 과일이 갈변하는 것을 막아 줘요.', example_en_5 = 'A slice of lemon on the side makes any seafood dish better.', example_ko_5 = '레몬 한 조각을 곁들이면 어떤 해산물 요리든 더 맛있어요.' WHERE id = 'w_cooking_B1_21';

UPDATE words SET example_en_2 = 'She uses lime juice and zest in her guacamole.', example_ko_2 = '그녀는 과카몰레에 라임즙과 제스트를 사용해요.', example_en_3 = 'He squeezes lime over the tacos for a citrusy kick.', example_ko_3 = '그는 타코에 상큼한 향을 더하기 위해 라임을 짜서 뿌려요.', example_en_4 = 'Lime adds a refreshing flavour to cold drinks and desserts.', example_ko_4 = '라임은 차가운 음료와 디저트에 상쾌한 풍미를 더해 줘요.', example_en_5 = 'Lime leaves are a common ingredient in Thai cooking.', example_ko_5 = '라임 잎은 태국 요리에서 흔히 사용되는 재료예요.' WHERE id = 'w_cooking_B1_22';

UPDATE words SET example_en_2 = 'She made a rich broth from chicken bones and vegetables.', example_ko_2 = '그녀는 닭 뼈와 채소로 진한 육수를 만들었어요.', example_en_3 = 'He uses homemade broth instead of store-bought for better flavour.', example_ko_3 = '그는 더 좋은 맛을 위해 사온 육수 대신 직접 만든 육수를 써요.', example_en_4 = 'She simmered the broth for four hours to develop a deep flavour.', example_ko_4 = '그녀는 깊은 맛을 내기 위해 육수를 4시간 동안 끓였어요.', example_en_5 = 'Add the noodles directly into the simmering broth.', example_ko_5 = '국수를 끓고 있는 육수에 바로 넣어 주세요.' WHERE id = 'w_cooking_B1_23';

UPDATE words SET example_en_2 = 'She uses beef stock as the base for her French onion soup.', example_ko_2 = '그녀는 프렌치 어니언 수프의 베이스로 소고기 육수를 사용해요.', example_en_3 = 'He reduced the stock to make a rich, concentrated sauce.', example_ko_3 = '그는 진하고 농축된 소스를 만들기 위해 육수를 졸였어요.', example_en_4 = 'Vegetable stock is a great option for vegetarian dishes.', example_ko_4 = '채소 육수는 채식 요리에 훌륭한 선택이에요.', example_en_5 = 'Store homemade stock in the freezer in ice cube trays.', example_ko_5 = '직접 만든 육수는 얼음 틀에 넣어 냉동 보관해 주세요.' WHERE id = 'w_cooking_B1_24';

UPDATE words SET example_en_2 = 'She made a hearty stew with potatoes, carrots, and beef.', example_ko_2 = '그녀는 감자, 당근, 소고기로 든든한 스튜를 만들었어요.', example_en_3 = 'The stew tastes even better the next day.', example_ko_3 = '스튜는 다음 날 더 맛있어요.', example_en_4 = 'He thickened the stew with a spoonful of cornstarch.', example_ko_4 = '그는 스튜에 녹말가루 한 숟가락을 넣어 걸쭉하게 만들었어요.', example_en_5 = 'A good stew should have tender meat and rich gravy.', example_ko_5 = '좋은 스튜에는 부드러운 고기와 진한 그레이비가 있어야 해요.' WHERE id = 'w_cooking_B1_25';

UPDATE words SET example_en_2 = 'She made a chicken and vegetable casserole for the whole family.', example_ko_2 = '그녀는 온 가족을 위해 닭고기와 채소 캐서롤을 만들었어요.', example_en_3 = 'He left the casserole in the oven for an hour.', example_ko_3 = '그는 캐서롤을 오븐에서 한 시간 동안 두었어요.', example_en_4 = 'Casserole dishes are perfect for feeding a large group.', example_ko_4 = '캐서롤은 많은 사람을 위해 요리할 때 완벽해요.', example_en_5 = 'She covered the casserole dish with foil to keep the moisture in.', example_ko_5 = '그녀는 수분을 유지하기 위해 캐서롤 용기를 호일로 덮었어요.' WHERE id = 'w_cooking_B1_26';

UPDATE words SET example_en_2 = 'She made a light tempura batter with ice-cold water.', example_ko_2 = '그녀는 얼음처럼 차가운 물로 가벼운 튀김 반죽을 만들었어요.', example_en_3 = 'The fish and chips batter should be thin and crispy.', example_ko_3 = '피시 앤드 칩스 반죽은 얇고 바삭해야 해요.', example_en_4 = 'He dipped the onion rings in batter before frying.', example_ko_4 = '그는 튀기기 전에 양파 링을 반죽에 담갔어요.', example_en_5 = 'Let the batter rest in the fridge for thirty minutes before using.', example_ko_5 = '반죽은 사용하기 전에 냉장고에서 30분 동안 쉬게 해 주세요.' WHERE id = 'w_cooking_B1_27';

UPDATE words SET example_en_2 = 'She rolled the dough flat on a floured surface.', example_ko_2 = '그녀는 밀가루를 뿌린 표면에서 반죽을 평평하게 밀었어요.', example_en_3 = 'The dough should be soft and smooth after kneading.', example_ko_3 = '반죽은 치댄 후에 부드럽고 매끄러워야 해요.', example_en_4 = 'He shaped the dough into small rolls before baking.', example_ko_4 = '그는 굽기 전에 반죽을 작은 롤 모양으로 빚었어요.', example_en_5 = 'Cover the dough with a damp cloth while it rests.', example_ko_5 = '반죽을 쉬는 동안 젖은 천으로 덮어 주세요.' WHERE id = 'w_cooking_B1_28';

UPDATE words SET example_en_2 = 'She added a packet of yeast to the warm water before mixing.', example_ko_2 = '그녀는 섞기 전에 따뜻한 물에 이스트 한 봉지를 넣었어요.', example_en_3 = 'Active dry yeast needs to be activated in warm water first.', example_ko_3 = '활성 건조 이스트는 먼저 따뜻한 물에서 활성화해야 해요.', example_en_4 = 'Yeast is the ingredient that makes bread rise and become fluffy.', example_ko_4 = '이스트는 빵을 부풀어 오르고 폭신하게 만드는 재료예요.', example_en_5 = 'Too much yeast can cause the bread to rise too quickly.', example_ko_5 = '이스트를 너무 많이 넣으면 빵이 너무 빨리 부풀 수 있어요.' WHERE id = 'w_cooking_B1_29';

UPDATE words SET example_en_2 = 'She covered the bowl and let the dough rise for one hour.', example_ko_2 = '그녀는 그릇을 덮고 반죽이 한 시간 동안 부풀도록 두었어요.', example_en_3 = 'The bread did not rise well because the yeast was old.', example_ko_3 = '이스트가 오래되어 빵이 잘 부풀지 않았어요.', example_en_4 = 'Let the dough rise in a warm spot in the kitchen.', example_ko_4 = '주방의 따뜻한 곳에서 반죽이 부풀도록 두세요.', example_en_5 = 'The dough doubled in size after an hour of rising.', example_ko_5 = '반죽이 한 시간 부풀고 나서 두 배 크기가 됐어요.' WHERE id = 'w_cooking_B1_30';

UPDATE words SET example_en_2 = 'She always preheats the oven before putting the cake in.', example_ko_2 = '그녀는 항상 케이크를 넣기 전에 오븐을 예열해요.', example_en_3 = 'Preheat the oven to 200°C while you prepare the dough.', example_ko_3 = '반죽을 준비하는 동안 오븐을 200°C로 예열해 주세요.', example_en_4 = 'He always checks that the oven is fully preheated before baking.', example_ko_4 = '그는 굽기 전에 항상 오븐이 완전히 예열됐는지 확인해요.', example_en_5 = 'Skipping the preheat step can lead to uneven baking.', example_ko_5 = '예열 단계를 건너뛰면 고르게 굽기가 어려울 수 있어요.' WHERE id = 'w_cooking_B1_31';

UPDATE words SET example_en_2 = 'The oven timer beeped when the roast was ready.', example_ko_2 = '로스트가 다 됐을 때 오븐 타이머가 울렸어요.', example_en_3 = 'She cleans the oven every month to keep it working well.', example_ko_3 = '그녀는 오븐이 잘 작동하도록 매달 청소해요.', example_en_4 = 'He placed the tray on the middle rack of the oven.', example_ko_4 = '그는 트레이를 오븐의 중간 선반에 넣었어요.', example_en_5 = 'The oven needs about fifteen minutes to reach full temperature.', example_ko_5 = '오븐이 최고 온도에 도달하는 데 약 15분이 걸려요.' WHERE id = 'w_cooking_B1_32';

UPDATE words SET example_en_2 = 'The internal temperature of the chicken should reach 75°C.', example_ko_2 = '닭고기의 내부 온도는 75°C에 도달해야 해요.', example_en_3 = 'She uses a thermometer to check the temperature of the oil.', example_ko_3 = '그녀는 온도계를 사용해 기름 온도를 확인해요.', example_en_4 = 'Keep the milk at a low temperature when making yoghurt.', example_ko_4 = '요거트를 만들 때는 우유를 낮은 온도로 유지해 주세요.', example_en_5 = 'The correct oven temperature makes all the difference when baking.', example_ko_5 = '베이킹에서 올바른 오븐 온도는 매우 중요해요.' WHERE id = 'w_cooking_B1_33';

UPDATE words SET example_en_2 = 'Always check the shelf life before buying packaged food.', example_ko_2 = '포장 식품을 구입하기 전에 항상 유통 기한을 확인하세요.', example_en_3 = 'Freezing extends the shelf life of most foods.', example_ko_3 = '냉동하면 대부분의 식품 유통 기한이 늘어나요.', example_en_4 = 'The shelf life of fresh bread is only two to three days.', example_ko_4 = '신선한 빵의 유통 기한은 이틀에서 사흘밖에 되지 않아요.', example_en_5 = 'Proper storage can significantly extend the shelf life of herbs.', example_ko_5 = '적절한 보관 방법으로 허브의 유통 기한을 크게 늘릴 수 있어요.' WHERE id = 'w_cooking_B1_34';

UPDATE words SET example_en_2 = 'Check the expiry date before using dairy products.', example_ko_2 = '유제품을 사용하기 전에 유통 기한을 확인해 주세요.', example_en_3 = 'She threw away the yoghurt because it was past its expiry date.', example_ko_3 = '그녀는 요거트의 유통 기한이 지나서 버렸어요.', example_en_4 = 'He always buys products with the latest expiry date.', example_ko_4 = '그는 항상 유통 기한이 가장 늦은 제품을 사요.', example_en_5 = 'The expiry date on canned goods is usually several years away.', example_ko_5 = '통조림 식품의 유통 기한은 보통 몇 년 뒤예요.' WHERE id = 'w_cooking_B1_35';
