-- EngCat — Technology (과학·기술) Topic
-- 210 words (35 per CEFR level A1~C2) + 42 patterns (7 per level)
-- IDs: w_technology_{CEFR}_{nn}, s_technology_{CEFR}_{nn}

-- ══════════════════════════════════════
-- WORDS — A1 (기초 기기·화면)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_technology_A1_01','computer','/kəmˈpjuːtər/','noun','컴퓨터','An electronic device for storing and processing data.','I use a {computer} every day.','저는 매일 컴퓨터를 사용해요.','computer','A1','technology',1,'computer laptop desk office workspace'),
('w_technology_A1_02','phone','/foʊn/','noun','전화기, 휴대폰','A device used for talking to someone in another place, now often a smartphone.','Can I borrow your {phone} for a minute?','잠깐 전화기 빌려도 될까요?','phone','A1','technology',1,'smartphone phone hand holding screen'),
('w_technology_A1_03','internet','/ˈɪntərnet/','noun','인터넷','The global network that connects computers worldwide.','I need the {internet} to check my email.','이메일을 확인하려면 인터넷이 필요해요.','internet','A1','technology',1,'internet wifi signal network connected'),
('w_technology_A1_04','app','/æp/','noun','앱, 애플리케이션','A software program designed for a mobile device or computer.','This {app} helps me learn new words.','이 앱은 새로운 단어를 배우는 데 도움이 돼요.','app','A1','technology',1,'mobile app smartphone screen icons'),
('w_technology_A1_05','screen','/skriːn/','noun','화면','The flat surface on a device that displays images or text.','The {screen} is cracked — I need to fix it.','화면이 깨졌어요. 수리해야 해요.','screen','A1','technology',1,'phone screen cracked display close up'),
('w_technology_A1_06','game','/ɡeɪm/','noun','게임','An activity or application for entertainment on a device.','He plays a {game} on his phone every night.','그는 매일 밤 휴대폰으로 게임을 해요.','game','A1','technology',1,'video game controller gaming screen'),
('w_technology_A1_07','email','/ˈiːmeɪl/','noun','이메일','An electronic message sent over the internet.','Please send me the file by {email}.','파일을 이메일로 보내주세요.','email','A1','technology',1,'email inbox laptop message notification'),
('w_technology_A1_08','photo','/ˈfoʊtoʊ/','noun','사진','An image taken with a camera or phone.','I took a {photo} at the park.','공원에서 사진을 찍었어요.','photo','A1','technology',1,'photo camera smartphone taking picture'),
('w_technology_A1_09','video','/ˈvɪdioʊ/','noun','영상, 비디오','A recording of moving images, often with sound.','She posted a {video} of her cat online.','그녀는 고양이 영상을 온라인에 올렸어요.','video','A1','technology',1,'video recording camera phone filming'),
('w_technology_A1_10','button','/ˈbʌtən/','noun','버튼','A small element on a screen or device you press to make something happen.','Press the green {button} to start.','시작하려면 초록 버튼을 누르세요.','button','A1','technology',1,'button power on device press finger'),
('w_technology_A1_11','type','/taɪp/','verb','입력하다, 타이핑하다','To write using a keyboard.','Please {type} your name in the box.','박스에 이름을 입력해 주세요.','type','A1','technology',1,'keyboard typing hands laptop computer'),
('w_technology_A1_12','click','/klɪk/','verb','클릭하다','To press a button on a mouse or tap on a touchscreen.','{Click} on the link to open the page.','링크를 클릭하면 페이지가 열려요.','click','A1','technology',1,'mouse click cursor computer screen'),
('w_technology_A1_13','open','/ˈoʊpən/','verb','열다 (파일·앱)','To start a file, program, or application.','Can you {open} that document for me?','그 문서를 열어줄 수 있어요?','open','A1','technology',2,'opening file folder document computer'),
('w_technology_A1_14','close','/kloʊz/','verb','닫다 (창·앱)','To stop a program or shut a window on a screen.','Please {close} all other apps before you begin.','시작하기 전에 다른 앱을 모두 닫아주세요.','close','A1','technology',2,'closing app window screen x button'),
('w_technology_A1_15','keyboard','/ˈkiːbɔːrd/','noun','키보드','The set of keys used to input text into a computer.','I bought a new wireless {keyboard}.','새 무선 키보드를 샀어요.','keyboard','A1','technology',2,'keyboard wireless typing desk office'),
('w_technology_A1_16','mouse','/maʊs/','noun','마우스','A small device moved by hand to control a pointer on screen.','The {mouse} is not working properly.','마우스가 제대로 작동하지 않아요.','mouse','A1','technology',2,'computer mouse desk hand scroll'),
('w_technology_A1_17','cable','/ˈkeɪbəl/','noun','케이블, 선','A thick wire that carries electricity or data.','I need a {cable} to charge my laptop.','노트북을 충전할 케이블이 필요해요.','cable','A1','technology',2,'cable usb charging desk tangled'),
('w_technology_A1_18','charger','/ˈtʃɑːrdʒər/','noun','충전기','A device that supplies power to a battery.','Have you seen my phone {charger}?','제 휴대폰 충전기를 봤어요?','charger','A1','technology',2,'phone charger cable plug power'),
('w_technology_A1_19','speaker','/ˈspiːkər/','noun','스피커','A device that produces sound from a computer or phone.','Turn up the {speaker} — I can''t hear.','스피커 소리를 키워주세요. 잘 안 들려요.','speaker','A1','technology',2,'bluetooth speaker music sound device'),
('w_technology_A1_20','printer','/ˈprɪntər/','noun','프린터','A machine that produces paper copies of documents.','The {printer} is out of ink.','프린터 잉크가 다 떨어졌어요.','printer','A1','technology',2,'office printer paper document print'),
('w_technology_A1_21','save','/seɪv/','verb','저장하다','To store data so it is not lost.','Don''t forget to {save} your work.','작업 내용을 저장하는 걸 잊지 마세요.','save','A1','technology',2,'save file document icon floppy disk'),
('w_technology_A1_22','send','/send/','verb','보내다 (메시지·파일)','To transmit a message or file electronically.','I will {send} you the report by noon.','정오까지 보고서를 보내드릴게요.','send','A1','technology',2,'send message email smartphone arrow'),
('w_technology_A1_23','call','/kɔːl/','verb','전화하다','To contact someone by phone.','I''ll {call} you when I get home.','집에 도착하면 전화할게요.','call','A1','technology',2,'phone call smartphone ear talking'),
('w_technology_A1_24','message','/ˈmesɪdʒ/','noun','메시지','A short piece of text sent electronically.','Did you get my {message}?','제 메시지 받았어요?','message','A1','technology',3,'text message notification smartphone bubble'),
('w_technology_A1_25','tablet','/ˈtæblɪt/','noun','태블릿','A flat portable computer with a touch screen.','She reads books on her {tablet}.','그녀는 태블릿으로 책을 읽어요.','tablet','A1','technology',3,'tablet ipad reading desk couch'),
('w_technology_A1_26','power','/ˈpaʊər/','noun','전원','The electricity that operates a device.','Press the {power} button to turn it on.','전원 버튼을 누르면 켜져요.','power','A1','technology',3,'power button on off electronics device'),
('w_technology_A1_27','link','/lɪŋk/','noun','링크','A clickable connection to another web page or file.','Click the {link} in the email.','이메일의 링크를 클릭하세요.','link','A1','technology',3,'link url click web browser'),
('w_technology_A1_28','site','/saɪt/','noun','(웹)사이트','A web page or set of pages on the internet.','This {site} has lots of useful information.','이 사이트에는 유용한 정보가 많아요.','site','A1','technology',3,'website browser laptop internet page'),
('w_technology_A1_29','search','/sɜːrtʃ/','verb','검색하다','To look for information online or in a system.','Just {search} for it on the internet.','인터넷에서 검색해 보세요.','search','A1','technology',3,'search bar google browser magnifying glass'),
('w_technology_A1_30','password','/ˈpæswɜːrd/','noun','비밀번호','A secret word or code used to access a system.','You need a {password} to log in.','로그인하려면 비밀번호가 필요해요.','password','A1','technology',3,'password login lock security screen'),
('w_technology_A1_31','volume','/ˈvɒljuːm/','noun','음량','The level of sound produced by a device.','Turn down the {volume}, please.','음량을 낮춰주세요.','volume','A1','technology',3,'volume speaker phone sound level control'),
('w_technology_A1_32','wifi','/ˈwaɪfaɪ/','noun','와이파이','A wireless internet connection.','Is there free {wifi} here?','여기 무료 와이파이 있나요?','wifi','A1','technology',3,'wifi router signal coffee shop internet'),
('w_technology_A1_33','battery','/ˈbætəri/','noun','배터리','The part of a device that stores electrical power.','My phone {battery} is almost dead.','휴대폰 배터리가 거의 다 됐어요.','battery','A1','technology',3,'phone battery low dead charging'),
('w_technology_A1_34','camera','/ˈkæmərə/','noun','카메라','A device for taking photos or videos.','The front {camera} takes great selfies.','전면 카메라로 셀카가 잘 찍혀요.','camera','A1','technology',3,'camera photo smartphone lens taking picture'),
('w_technology_A1_35','download','/ˈdaʊnloʊd/','verb','다운로드하다','To copy data from the internet to your device.','You can {download} the app for free.','앱은 무료로 다운로드할 수 있어요.','download','A1','technology',4,'download arrow phone app install');

-- ══════════════════════════════════════
-- WORDS — A2 (앱·소프트웨어 기초)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_technology_A2_01','software','/ˈsɒftweər/','noun','소프트웨어','Programs and operating information used by a computer.','The {software} needs to be updated.','소프트웨어를 업데이트해야 해요.','software','A2','technology',1,'software code screen laptop update install'),
('w_technology_A2_02','update','/ˈʌpdeɪt/','noun','업데이트','A new version of software that improves or fixes things.','There is a system {update} available.','시스템 업데이트가 있어요.','update','A2','technology',1,'software update progress bar loading screen'),
('w_technology_A2_03','upload','/ˈʌploʊd/','verb','업로드하다','To send data from your device to the internet.','Can you {upload} the photos to the drive?','사진을 드라이브에 업로드해 줄 수 있어요?','upload','A2','technology',1,'upload cloud arrow files sharing'),
('w_technology_A2_04','delete','/dɪˈliːt/','verb','삭제하다','To remove data or a file permanently.','I accidentally {deleted} the wrong file.','실수로 잘못된 파일을 삭제했어요.','delete','A2','technology',1,'delete trash bin file remove recycle'),
('w_technology_A2_05','install','/ɪnˈstɔːl/','verb','설치하다','To put a program onto a device so it is ready to use.','Please {install} the app before the meeting.','회의 전에 앱을 설치해주세요.','install','A2','technology',1,'install app download progress phone'),
('w_technology_A2_06','login','/ˈlɒɡɪn/','noun','로그인','The process of entering a username and password to access a system.','You need to create an account to {login}.','로그인하려면 계정을 만들어야 해요.','login','A2','technology',1,'login screen username password account'),
('w_technology_A2_07','account','/əˈkaʊnt/','noun','계정','A personal record in a system identified by a username.','I forgot the password to my {account}.','제 계정 비밀번호를 잊었어요.','account','A2','technology',1,'account profile user login digital'),
('w_technology_A2_08','notification','/ˌnoʊtɪfɪˈkeɪʃən/','noun','알림','An alert from an app or system to let you know something happened.','{Notifications} from that app keep distracting me.','그 앱 알림이 자꾸 방해가 돼요.','notifications','A2','technology',2,'notification bell phone alert badge pop up'),
('w_technology_A2_09','setting','/ˈsetɪŋ/','noun','설정','An option you can adjust to change how a device or app works.','Go to {settings} to change the language.','언어를 바꾸려면 설정으로 가세요.','settings','A2','technology',2,'settings gear icon phone menu options'),
('w_technology_A2_10','backup','/ˈbækʌp/','noun','백업','A copy of data stored separately in case the original is lost.','Make sure you do a {backup} before updating.','업데이트 전에 꼭 백업하세요.','backup','A2','technology',2,'backup cloud storage data files safe'),
('w_technology_A2_11','storage','/ˈstɔːrɪdʒ/','noun','저장 공간','The space available on a device or cloud for keeping data.','I don''t have enough {storage} for more photos.','사진을 더 저장할 공간이 없어요.','storage','A2','technology',2,'storage hard drive full phone memory'),
('w_technology_A2_12','share','/ʃeər/','verb','공유하다','To send or give access to a file, link, or content.','Can you {share} your screen with me?','화면을 공유해 줄 수 있어요?','share','A2','technology',2,'screen sharing laptop meeting collaboration'),
('w_technology_A2_13','restart','/ˌriːˈstɑːrt/','verb','재시작하다','To switch a device off and on again to solve a problem.','Try to {restart} your phone and see if it works.','전화기를 재시작해보고 되는지 확인해 보세요.','restart','A2','technology',2,'restart phone power off on loading'),
('w_technology_A2_14','error','/ˈerər/','noun','오류, 에러','A mistake or problem in a system or program.','An {error} message appeared on the screen.','화면에 오류 메시지가 떴어요.','error','A2','technology',2,'error message screen warning red alert'),
('w_technology_A2_15','freeze','/friːz/','verb','멈추다, 굳다 (기기)','To stop responding — said of a computer or app.','My laptop {froze} while I was working.','작업 중에 노트북이 멈췄어요.','froze','A2','technology',2,'frozen laptop hang screen buffering stuck'),
('w_technology_A2_16','connect','/kəˈnekt/','verb','연결하다','To link one device or network to another.','I can''t {connect} to the wifi right now.','지금 와이파이에 연결이 안 돼요.','connect','A2','technology',2,'wifi connect signal phone network'),
('w_technology_A2_17','profile','/ˈproʊfaɪl/','noun','프로필','A personal page or record in an online service.','Update your {profile} picture before the call.','통화 전에 프로필 사진을 업데이트하세요.','profile','A2','technology',3,'profile picture social media account user'),
('w_technology_A2_18','comment','/ˈkɒment/','noun','댓글, 코멘트','A written response left on an online post or video.','She left a nice {comment} on my post.','그녀가 제 게시물에 좋은 댓글을 남겼어요.','comment','A2','technology',3,'comment social media post reply notification'),
('w_technology_A2_19','post','/poʊst/','verb','게시하다','To publish a message or photo on an online platform.','He {posted} the video an hour ago.','그는 한 시간 전에 영상을 올렸어요.','posted','A2','technology',3,'social media post upload phone feed'),
('w_technology_A2_20','follow','/ˈfɒloʊ/','verb','팔로우하다','To subscribe to someone''s online updates.','You should {follow} her account for tips.','팁을 얻으려면 그녀의 계정을 팔로우하세요.','follow','A2','technology',3,'follow social media account button subscribe'),
('w_technology_A2_21','stream','/striːm/','verb','스트리밍하다','To watch or listen to media over the internet without downloading.','I {stream} movies instead of buying DVDs.','DVD를 사는 대신 영화를 스트리밍해요.','stream','A2','technology',3,'streaming video netflix tv couch watching'),
('w_technology_A2_22','screenshot','/ˈskriːnʃɒt/','noun','스크린샷','An image captured of what is currently on a screen.','Take a {screenshot} and send it to me.','스크린샷을 찍어서 보내주세요.','screenshot','A2','technology',3,'screenshot phone screen capture share'),
('w_technology_A2_23','browser','/ˈbraʊzər/','noun','브라우저','A program used to access the internet.','Which {browser} do you usually use?','보통 어떤 브라우저를 사용해요?','browser','A2','technology',3,'web browser chrome safari internet laptop'),
('w_technology_A2_24','username','/ˈjuːzərneɪm/','noun','사용자 이름','The name you use to identify yourself on a website or app.','Your {username} must be at least six characters.','사용자 이름은 최소 여섯 글자여야 해요.','username','A2','technology',3,'username login account create registration'),
('w_technology_A2_25','refresh','/rɪˈfreʃ/','verb','새로 고침하다','To reload a web page or update the display.','Just {refresh} the page and it should work.','페이지를 새로 고침하면 될 거예요.','refresh','A2','technology',4,'refresh reload browser page loading circle'),
('w_technology_A2_26','copy','/ˈkɒpi/','verb','복사하다','To duplicate text or a file.','You can {copy} and paste the text.','텍스트를 복사해서 붙여넣을 수 있어요.','copy','A2','technology',4,'copy paste text clipboard keyboard'),
('w_technology_A2_27','paste','/peɪst/','verb','붙여넣다','To insert previously copied text or data.','Now {paste} it into the document.','이제 문서에 붙여넣으세요.','paste','A2','technology',4,'paste text document clipboard keyboard shortcut'),
('w_technology_A2_28','zoom','/zuːm/','verb','확대하다, 줌하다','To enlarge an image or join a video call on Zoom.','Let me {zoom} in on that part.','그 부분을 확대해 볼게요.','zoom','A2','technology',4,'zoom video call meeting screen laptop'),
('w_technology_A2_29','chat','/tʃæt/','verb','채팅하다','To exchange messages in real time online.','We {chat} every evening on the app.','저희는 매일 저녁 앱에서 채팅해요.','chat','A2','technology',4,'chat message bubble phone conversation instant'),
('w_technology_A2_30','filter','/ˈfɪltər/','noun','필터','A feature that changes or sorts content, often in photos or searches.','She used a {filter} to make the photo look brighter.','그녀는 필터를 사용해서 사진을 더 밝게 만들었어요.','filter','A2','technology',4,'photo filter instagram edit bright color'),
('w_technology_A2_31','sync','/sɪŋk/','verb','동기화하다','To make two devices show the same updated data.','Your contacts will {sync} across all devices.','연락처가 모든 기기에서 동기화될 거예요.','sync','A2','technology',4,'sync cloud devices laptop phone tablet'),
('w_technology_A2_32','virus','/ˈvaɪrəs/','noun','바이러스','Malicious software that can damage a computer system.','My computer got a {virus} from that website.','그 웹사이트에서 컴퓨터에 바이러스가 걸렸어요.','virus','A2','technology',4,'computer virus malware warning alert skull'),
('w_technology_A2_33','scan','/skæn/','verb','스캔하다','To examine a document or check a device for threats.','Please {scan} the QR code to enter.','입장하려면 QR코드를 스캔하세요.','scan','A2','technology',4,'qr code scan phone camera barcode'),
('w_technology_A2_34','emoji','/ɪˈmoʊdʒi/','noun','이모지','A small digital image used to express emotion in messages.','She added an {emoji} to make the message friendlier.','그녀는 메시지를 더 친근하게 보이게 하려고 이모지를 추가했어요.','emoji','A2','technology',5,'emoji keyboard phone text message expression'),
('w_technology_A2_35','tag','/tæɡ/','verb','태그하다','To label or link someone in an online post.','Don''t {tag} me in that photo, please.','그 사진에 저를 태그하지 말아주세요.','tag','A2','technology',5,'tag social media photo mention name');

-- ══════════════════════════════════════
-- WORDS — B1 (네트워크·시스템 중급)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_technology_B1_01','algorithm','/ˈælɡərɪðəm/','noun','알고리즘','A set of rules or steps for solving a problem or completing a task.','The recommendation {algorithm} learns from your habits.','추천 알고리즘이 당신의 습관으로부터 학습해요.','algorithm','B1','technology',1,'algorithm flowchart code logic programming'),
('w_technology_B1_02','interface','/ˈɪntərfeɪs/','noun','인터페이스','The point of interaction between a user and a computer system.','The new {interface} is much easier to navigate.','새 인터페이스는 훨씬 사용하기 쉬워요.','interface','B1','technology',1,'user interface ui design app screen mobile'),
('w_technology_B1_03','network','/ˈnetwɜːrk/','noun','네트워크','A system of connected computers or devices.','We need to upgrade the office {network}.','사무실 네트워크를 업그레이드해야 해요.','network','B1','technology',1,'network server rack cables connected datacenter'),
('w_technology_B1_04','database','/ˈdeɪtəbeɪs/','noun','데이터베이스','An organized collection of structured information stored electronically.','All user data is stored in the {database}.','모든 사용자 데이터는 데이터베이스에 저장돼요.','database','B1','technology',1,'database server storage rows columns data'),
('w_technology_B1_05','encryption','/ɪnˈkrɪpʃən/','noun','암호화','The process of converting data into a code to prevent unauthorized access.','End-to-end {encryption} keeps your messages private.','종단간 암호화가 메시지를 비공개로 유지해요.','encryption','B1','technology',1,'encryption security lock code digital data'),
('w_technology_B1_06','server','/ˈsɜːrvər/','noun','서버','A powerful computer that stores and sends data to other devices.','The {server} went down for maintenance last night.','어젯밤 유지보수를 위해 서버가 다운됐어요.','server','B1','technology',1,'server rack data center blinking lights'),
('w_technology_B1_07','cloud','/klaʊd/','noun','클라우드','Internet-based storage and computing services.','I store all my files in the {cloud}.','모든 파일을 클라우드에 저장해요.','cloud','B1','technology',1,'cloud computing storage digital sky abstract'),
('w_technology_B1_08','cybersecurity','/ˌsaɪbərsɪˈkjʊərɪti/','noun','사이버 보안','The practice of protecting systems and networks from digital attacks.','Companies invest heavily in {cybersecurity}.','기업들은 사이버 보안에 많은 투자를 해요.','cybersecurity','B1','technology',1,'cybersecurity hacker shield lock digital protection'),
('w_technology_B1_09','code','/koʊd/','noun','코드','Instructions written in a programming language.','She wrote the {code} for the new feature.','그녀가 새 기능의 코드를 작성했어요.','code','B1','technology',1,'code programming screen dark laptop developer'),
('w_technology_B1_10','developer','/dɪˈveləpər/','noun','개발자','A person who creates software or applications.','The {developer} fixed the bug in an hour.','개발자가 한 시간 만에 버그를 고쳤어요.','developer','B1','technology',2,'developer programmer coding laptop coffee desk'),
('w_technology_B1_11','bug','/bʌɡ/','noun','버그','An error or flaw in a computer program.','There is a {bug} causing the app to crash.','앱이 종료되게 하는 버그가 있어요.','bug','B1','technology',2,'bug software error code screen warning'),
('w_technology_B1_12','feature','/ˈfiːtʃər/','noun','기능','A specific function or capability of software.','The new {feature} allows you to share files instantly.','새 기능으로 파일을 즉시 공유할 수 있어요.','feature','B1','technology',2,'feature app mobile phone new update launch'),
('w_technology_B1_13','platform','/ˈplætfɔːrm/','noun','플랫폼','A base technology or online service on which other applications run.','We launched the product on multiple {platforms}.','여러 플랫폼에서 제품을 출시했어요.','platforms','B1','technology',2,'platform app store digital ecosystem devices'),
('w_technology_B1_14','bandwidth','/ˈbændwɪdθ/','noun','대역폭','The capacity of a network connection to transfer data.','Streaming video requires a lot of {bandwidth}.','영상 스트리밍은 많은 대역폭이 필요해요.','bandwidth','B1','technology',2,'bandwidth internet speed connection data flow'),
('w_technology_B1_15','firewall','/ˈfaɪərwɔːl/','noun','방화벽','A security system that monitors and controls network traffic.','The {firewall} blocked the suspicious connection.','방화벽이 수상한 연결을 차단했어요.','firewall','B1','technology',2,'firewall security network protection digital wall'),
('w_technology_B1_16','protocol','/ˈproʊtəkɒl/','noun','프로토콜','A set of rules governing the transmission of data.','HTTPS is the secure {protocol} for web browsing.','HTTPS는 웹 브라우징을 위한 보안 프로토콜이에요.','protocol','B1','technology',2,'protocol https secure web lock padlock browser'),
('w_technology_B1_17','domain','/doʊˈmeɪn/','noun','도메인','The address of a website on the internet.','They registered a new {domain} for the startup.','스타트업을 위한 새 도메인을 등록했어요.','domain','B1','technology',2,'domain name website address url browser'),
('w_technology_B1_18','cache','/kæʃ/','noun','캐시','Temporary data stored to speed up future loading.','Clear the {cache} if the page does not load correctly.','페이지가 제대로 로드되지 않으면 캐시를 지우세요.','cache','B1','technology',3,'cache browser clear memory loading fast'),
('w_technology_B1_19','pixel','/ˈpɪksəl/','noun','픽셀','The smallest unit of a digital image or screen.','This display has over two million {pixels}.','이 디스플레이는 200만 픽셀 이상이에요.','pixels','B1','technology',3,'pixel display screen resolution close up grid'),
('w_technology_B1_20','resolution','/ˌrezəˈluːʃən/','noun','해상도','The number of pixels in a display, determining image sharpness.','The camera captures video in 4K {resolution}.','카메라가 4K 해상도로 영상을 촬영해요.','resolution','B1','technology',3,'camera resolution 4k sharp image photography'),
('w_technology_B1_21','compatible','/kəmˈpætɪbəl/','adjective','호환 가능한','Able to work together without problems.','Check if the software is {compatible} with your system.','소프트웨어가 시스템과 호환되는지 확인하세요.','compatible','B1','technology',3,'compatible devices connecting adaptor plug tech'),
('w_technology_B1_22','hardware','/ˈhɑːrdweər/','noun','하드웨어','The physical components of a computer system.','The old {hardware} cannot run the new software.','오래된 하드웨어는 새 소프트웨어를 실행할 수 없어요.','hardware','B1','technology',3,'hardware computer parts motherboard components'),
('w_technology_B1_23','operating system','/ˈɒpəreɪtɪŋ ˈsɪstəm/','noun','운영체제','The main software that manages a computer''s resources.','Which {operating system} does your laptop run?','노트북은 어떤 운영체제로 돌아가요?','operating system','B1','technology',3,'operating system windows macos screen desktop'),
('w_technology_B1_24','process','/ˈprɒses/','noun','프로세스, 과정','A program or task running on a computer.','The {process} is taking too long to complete.','프로세스가 완료되는 데 너무 오래 걸려요.','process','B1','technology',3,'process loading computer task bar progress'),
('w_technology_B1_25','automation','/ˌɔːtəˈmeɪʃən/','noun','자동화','The use of technology to perform tasks with minimal human input.','{Automation} has increased productivity in the factory.','자동화로 공장의 생산성이 높아졌어요.','automation','B1','technology',3,'automation robot factory assembly line machine'),
('w_technology_B1_26','version','/ˈvɜːrʒən/','noun','버전','A particular form of something that differs slightly from others.','Please use the latest {version} of the app.','앱의 최신 버전을 사용해주세요.','version','B1','technology',4,'version update software number release history'),
('w_technology_B1_27','virtual','/ˈvɜːrtʃuəl/','adjective','가상의','Existing or occurring on a computer rather than in the physical world.','We held a {virtual} meeting via video call.','화상 통화로 가상 회의를 열었어요.','virtual','B1','technology',4,'virtual meeting video call screen laptop zoom'),
('w_technology_B1_28','wireless','/ˈwaɪərləs/','adjective','무선의','Using radio waves rather than physical cables to connect.','All our office devices are now {wireless}.','사무실 모든 기기가 이제 무선이에요.','wireless','B1','technology',4,'wireless bluetooth earbuds phone connection'),
('w_technology_B1_29','access','/ˈækses/','verb','접근하다, 액세스하다','To obtain or make use of data or a system.','Only authorized users can {access} this folder.','권한이 있는 사용자만 이 폴더에 접근할 수 있어요.','access','B1','technology',4,'access login security door key digital'),
('w_technology_B1_30','log out','/lɒɡ aʊt/','verb','로그아웃하다','To end a session in an app or website.','Always {log out} when using a public computer.','공용 컴퓨터를 사용할 때는 항상 로그아웃하세요.','log out','B1','technology',4,'logout account security public computer sign out'),
('w_technology_B1_31','spam','/spæm/','noun','스팸','Unwanted bulk messages sent over email or social media.','My inbox is full of {spam} emails.','받은 편지함이 스팸 이메일로 가득 찼어요.','spam','B1','technology',4,'spam email junk filter inbox warning'),
('w_technology_B1_32','troubleshoot','/ˈtrʌbəlʃuːt/','verb','문제를 해결하다','To investigate and fix technical problems.','Let me {troubleshoot} the connection issue.','연결 문제를 해결해 볼게요.','troubleshoot','B1','technology',4,'troubleshoot tech support fix repair computer'),
('w_technology_B1_33','load','/loʊd/','verb','불러오다, 로드하다','To transfer and display data on a screen or in memory.','The page takes too long to {load}.','페이지가 로드되는 데 너무 오래 걸려요.','load','B1','technology',5,'loading page website spinner buffering slow'),
('w_technology_B1_34','source code','/sɔːrs koʊd/','noun','소스 코드','The human-readable set of instructions that make up a program.','The developer shared the {source code} on GitHub.','개발자가 GitHub에서 소스 코드를 공유했어요.','source code','B1','technology',5,'source code github programming repository screen'),
('w_technology_B1_35','debug','/diːˈbʌɡ/','verb','디버그하다, 버그를 잡다','To find and fix errors in computer code.','It took two hours to {debug} that function.','그 함수를 디버그하는 데 두 시간이 걸렸어요.','debug','B1','technology',5,'debug code error programming screen terminal');

-- ══════════════════════════════════════
-- WORDS — B2 (AI·빅데이터)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_technology_B2_01','artificial intelligence','/ˌɑːrtɪˈfɪʃəl ɪnˈtelɪdʒəns/','noun','인공지능','The simulation of human intelligence by computer systems.','Companies are using {artificial intelligence} to personalize ads.','기업들은 광고를 개인화하기 위해 인공지능을 사용해요.','artificial intelligence','B2','technology',1,'artificial intelligence robot brain digital neural'),
('w_technology_B2_02','machine learning','/məˈʃiːn ˈlɜːrnɪŋ/','noun','머신러닝','A type of AI that learns from data without being explicitly programmed.','Spam filters use {machine learning} to improve over time.','스팸 필터는 시간이 지나면서 개선되기 위해 머신러닝을 사용해요.','machine learning','B2','technology',1,'machine learning data graph neural network training'),
('w_technology_B2_03','data','/ˈdeɪtə/','noun','데이터','Facts and statistics collected for analysis.','The app collects {data} on user behavior.','이 앱은 사용자 행동 데이터를 수집해요.','data','B2','technology',1,'data analytics graph visualization dashboard screen'),
('w_technology_B2_04','blockchain','/ˈblɒktʃeɪn/','noun','블록체인','A decentralized digital ledger that records transactions securely.','{Blockchain} technology ensures that records cannot be altered.','블록체인 기술은 기록을 변경할 수 없도록 보장해요.','blockchain','B2','technology',1,'blockchain crypto digital ledger chain blocks'),
('w_technology_B2_05','IoT','/ˌaɪ oʊ ˈtiː/','noun','사물인터넷','Internet of Things — everyday objects connected to the internet.','Smart home devices are part of the {IoT} ecosystem.','스마트홈 기기는 사물인터넷 생태계의 일부예요.','IoT','B2','technology',1,'iot smart home devices connected internet living'),
('w_technology_B2_06','API','/ˌeɪ piː ˈaɪ/','noun','API (애플리케이션 프로그래밍 인터페이스)','A set of rules that allows different software to communicate.','The developer connected the app to a weather {API}.','개발자가 날씨 API에 앱을 연결했어요.','API','B2','technology',1,'api integration code developer documentation connect'),
('w_technology_B2_07','open source','/ˌoʊpən ˈsɔːrs/','adjective','오픈소스의','Software with source code that anyone can inspect or modify.','Linux is a popular {open source} operating system.','리눅스는 인기 있는 오픈소스 운영체제예요.','open source','B2','technology',2,'open source github code collaboration community'),
('w_technology_B2_08','neural network','/ˈnjʊərəl ˈnetwɜːrk/','noun','신경망','A computing system modeled loosely after the human brain.','The image classifier uses a {neural network} to identify objects.','이미지 분류기는 객체를 식별하기 위해 신경망을 사용해요.','neural network','B2','technology',2,'neural network brain nodes connections diagram ai'),
('w_technology_B2_09','data mining','/ˈdeɪtə ˈmaɪnɪŋ/','noun','데이터 마이닝','Extracting meaningful patterns and insights from large datasets.'{Data mining} revealed unexpected customer trends.','데이터 마이닝을 통해 예상치 못한 고객 트렌드가 드러났어요.','data mining','B2','technology',2,'data mining analytics patterns insight big data'),
('w_technology_B2_10','deep learning','/diːp ˈlɜːrnɪŋ/','noun','딥러닝','A subtype of machine learning using multi-layered neural networks.'{Deep learning} powers modern voice assistants.','딥러닝이 현대 음성 비서를 구동해요.','deep learning','B2','technology',2,'deep learning neural layers ai training data'),
('w_technology_B2_11','model','/ˈmɒdəl/','noun','모델 (AI)','A mathematical representation trained to make predictions.','They trained a new language {model} on a huge dataset.','그들은 방대한 데이터셋으로 새로운 언어 모델을 학습시켰어요.','model','B2','technology',2,'ai model training data chart compute server'),
('w_technology_B2_12','dataset','/ˈdeɪtəset/','noun','데이터셋','A collection of related data used to train or test a model.','We need a larger {dataset} to improve accuracy.','정확도를 높이려면 더 큰 데이터셋이 필요해요.','dataset','B2','technology',2,'dataset table rows columns data csv spreadsheet'),
('w_technology_B2_13','automation','/ˌɔːtəˈmeɪʃən/','noun','자동화','The use of machines or software to perform tasks automatically.'{Automation} is changing the nature of work.','자동화가 일의 성격을 바꾸고 있어요.','automation','B2','technology',2,'automation robot ai workflow process mechanical'),
('w_technology_B2_14','augmented reality','/ɔːɡˈmentɪd riˈælɪti/','noun','증강현실','Technology that overlays digital information onto the real world.'{Augmented reality} glasses can show navigation directions.','증강현실 안경이 내비게이션 방향을 보여줄 수 있어요.','augmented reality','B2','technology',2,'augmented reality glasses digital overlay world ar'),
('w_technology_B2_15','virtual reality','/ˈvɜːrtʃuəl riˈælɪti/','noun','가상현실','A simulated experience created by computer technology.'{Virtual reality} headsets make games incredibly immersive.','가상현실 헤드셋이 게임을 믿을 수 없을 만큼 몰입감 있게 해요.','virtual reality','B2','technology',2,'virtual reality headset vr game immersive tech'),
('w_technology_B2_16','bias','/ˈbaɪəs/','noun','편향','A systematic error in data or algorithms that leads to unfair outcomes.','Researchers are working to reduce {bias} in AI models.','연구자들이 AI 모델의 편향을 줄이기 위해 노력하고 있어요.','bias','B2','technology',3,'ai bias fairness data algorithm decision making'),
('w_technology_B2_17','inference','/ˈɪnfərəns/','noun','추론','The process of using a trained model to make predictions.','The {inference} time was too slow for real-time use.','추론 시간이 실시간 사용에는 너무 느렸어요.','inference','B2','technology',3,'inference prediction ai model output result'),
('w_technology_B2_18','training','/ˈtreɪnɪŋ/','noun','학습, 훈련 (AI)','The process of teaching a model using data.','The {training} phase took several days on a GPU cluster.','학습 단계는 GPU 클러스터에서 며칠이 걸렸어요.','training','B2','technology',3,'ai training data model gpu compute server'),
('w_technology_B2_19','cloud computing','/klaʊd kəmˈpjuːtɪŋ/','noun','클라우드 컴퓨팅','Delivering computing services over the internet on demand.'{Cloud computing} lets teams collaborate from anywhere.','클라우드 컴퓨팅으로 팀이 어디서든 협업할 수 있어요.','cloud computing','B2','technology',3,'cloud computing server internet data storage sky'),
('w_technology_B2_20','algorithm bias','/ˈælɡərɪðəm ˈbaɪəs/','noun','알고리즘 편향','Systematic unfairness built into a decision-making algorithm.'{Algorithm bias} can reinforce social inequalities.','알고리즘 편향이 사회적 불평등을 강화할 수 있어요.','algorithm bias','B2','technology',3,'algorithm bias fairness code decision inequality'),
('w_technology_B2_21','microchip','/ˈmaɪkrəʊtʃɪp/','noun','마이크로칩','A miniature electronic circuit used in computers and devices.','The new {microchip} processes data ten times faster.','새 마이크로칩은 데이터를 10배 빠르게 처리해요.','microchip','B2','technology',3,'microchip silicon circuit board close up technology'),
('w_technology_B2_22','semiconductor','/ˌsemɪkənˈdʌktər/','noun','반도체','A material used in chips that can conduct electricity under certain conditions.','The global {semiconductor} shortage affected car production.','글로벌 반도체 부족이 자동차 생산에 영향을 미쳤어요.','semiconductor','B2','technology',3,'semiconductor chip factory wafer silicon production'),
('w_technology_B2_23','prototype','/ˈproʊtətaɪp/','noun','프로토타입','An early model of a product used for testing.','The engineers built a {prototype} in two weeks.','엔지니어들이 2주 만에 프로토타입을 만들었어요.','prototype','B2','technology',3,'prototype product design testing engineering lab'),
('w_technology_B2_24','deploy','/dɪˈplɔɪ/','verb','배포하다','To make software available and operational in a live environment.','They plan to {deploy} the update next Tuesday.','다음 화요일에 업데이트를 배포할 계획이에요.','deploy','B2','technology',4,'deploy code server release launch software pipeline'),
('w_technology_B2_25','iteration','/ˌɪtəˈreɪʃən/','noun','반복 (개발 사이클)','One cycle of development or testing in a repeated process.','We improved the design through multiple {iterations}.','여러 번의 반복을 통해 디자인을 개선했어요.','iterations','B2','technology',4,'iteration agile cycle sprint board development'),
('w_technology_B2_26','feedback loop','/ˈfiːdbæk luːp/','noun','피드백 루프','A process in which the output of a system is used as input to improve it.','AI improves through a continuous {feedback loop}.','AI는 지속적인 피드백 루프를 통해 개선돼요.','feedback loop','B2','technology',4,'feedback loop cycle improvement data circular'),
('w_technology_B2_27','user experience','/ˈjuːzər ɪkˈspɪəriəns/','noun','사용자 경험 (UX)','The overall experience of a person using a product or service.','We redesigned the app to improve {user experience}.','사용자 경험을 개선하기 위해 앱을 재설계했어요.','user experience','B2','technology',4,'ux design user interface wireframe mobile app'),
('w_technology_B2_28','scalable','/ˈskeɪləbəl/','adjective','확장 가능한','Able to grow or handle more demand without performance loss.','We need a {scalable} architecture for our growing user base.','늘어나는 사용자 기반을 위한 확장 가능한 아키텍처가 필요해요.','scalable','B2','technology',4,'scalable server architecture cloud growth expansion'),
('w_technology_B2_29','latency','/ˈleɪtənsi/','noun','지연 시간','The delay before data begins to transfer after a request.','High {latency} makes real-time communication difficult.','높은 지연 시간은 실시간 통신을 어렵게 해요.','latency','B2','technology',4,'latency ping network speed real time low delay'),
('w_technology_B2_30','patch','/pætʃ/','noun','패치','A software update that fixes bugs or security vulnerabilities.','Apply the security {patch} immediately.','보안 패치를 즉시 적용하세요.','patch','B2','technology',4,'security patch update software fix vulnerability'),
('w_technology_B2_31','vulnerability','/ˌvʌlnərəˈbɪlɪti/','noun','취약점','A weakness in a system that can be exploited by attackers.','The team found a critical {vulnerability} in the code.','팀이 코드에서 심각한 취약점을 발견했어요.','vulnerability','B2','technology',4,'vulnerability security code hacker exploit software'),
('w_technology_B2_32','agile','/ˈædʒaɪl/','adjective','애자일의 (개발 방법론)','A flexible approach to software development emphasizing iteration.','We work in an {agile} framework with two-week sprints.','우리는 2주 스프린트로 애자일 프레임워크로 일해요.','agile','B2','technology',5,'agile sprint board kanban team software development'),
('w_technology_B2_33','sprint','/sprɪnt/','noun','스프린트 (개발 주기)','A short development cycle in agile methodology.','The team completed the feature in one {sprint}.','팀이 한 스프린트 안에 기능을 완성했어요.','sprint','B2','technology',5,'sprint agile kanban board sticky notes development'),
('w_technology_B2_34','repository','/rɪˈpɒzɪtɔːri/','noun','저장소 (코드)','A storage location for software packages or code.','All our code is stored in a Git {repository}.','모든 코드는 Git 저장소에 저장되어 있어요.','repository','B2','technology',5,'github repository code commit history branches'),
('w_technology_B2_35','microservice','/ˈmaɪkrəʊˌsɜːrvɪs/','noun','마이크로서비스','An architectural style where an app is built as small independent services.','We moved from a monolith to a {microservice} architecture.','모놀리식에서 마이크로서비스 아키텍처로 전환했어요.','microservice','B2','technology',5,'microservice architecture diagram services api cloud');

-- ══════════════════════════════════════
-- WORDS — C1 (첨단 컴퓨팅·AI 이론)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_technology_C1_01','quantum computing','/ˈkwɒntəm kəmˈpjuːtɪŋ/','noun','양자 컴퓨팅','Computing that uses quantum-mechanical phenomena to process data.'{Quantum computing} could break current encryption standards.','양자 컴퓨팅은 현재의 암호화 표준을 무력화할 수 있어요.','quantum computing','C1','technology',1,'quantum computing chip lab abstract physics technology'),
('w_technology_C1_02','edge computing','/edʒ kəmˈpjuːtɪŋ/','noun','엣지 컴퓨팅','Processing data near the source rather than in a central data center.'{Edge computing} reduces latency for IoT devices.','엣지 컴퓨팅은 IoT 기기의 지연 시간을 줄여요.','edge computing','C1','technology',1,'edge computing iot network nodes distributed server'),
('w_technology_C1_03','cryptography','/krɪpˈtɒɡrəfi/','noun','암호학','The science of securing information through mathematical techniques.','Modern internet security relies entirely on {cryptography}.','현대 인터넷 보안은 전적으로 암호학에 의존해요.','cryptography','C1','technology',1,'cryptography code lock math security digital key'),
('w_technology_C1_04','federated learning','/ˈfedəreɪtɪd ˈlɜːrnɪŋ/','noun','연합 학습','A machine learning technique that trains models across devices without sharing raw data.'{Federated learning} enables AI training while preserving privacy.','연합 학습은 프라이버시를 보존하면서 AI 학습을 가능하게 해요.','federated learning','C1','technology',1,'federated learning privacy distributed ai nodes'),
('w_technology_C1_05','reinforcement learning','/rɪˈɪnfɔːrsmənt ˈlɜːrnɪŋ/','noun','강화학습','A type of machine learning where an agent learns by receiving rewards.'{Reinforcement learning} was used to develop the chess AI.','강화학습이 체스 AI를 개발하는 데 사용됐어요.','reinforcement learning','C1','technology',1,'reinforcement learning reward agent game ai training'),
('w_technology_C1_06','transformer model','/trænsˈfɔːrmər ˈmɒdəl/','noun','트랜스포머 모델','A type of neural network architecture used in modern language AI.','Large language models are based on the {transformer model}.','대형 언어 모델은 트랜스포머 모델을 기반으로 해요.','transformer model','C1','technology',1,'transformer model language ai architecture attention'),
('w_technology_C1_07','adversarial','/ˌædvərˈseəriəl/','adjective','적대적인 (AI)','Relating to attacks designed to fool or deceive an AI model.','Researchers study {adversarial} examples to make models more robust.','연구자들은 모델을 더 강건하게 만들기 위해 적대적 예제를 연구해요.','adversarial','C1','technology',2,'adversarial ai attack fool model robustness testing'),
('w_technology_C1_08','latency','/ˈleɪtənsi/','noun','지연 시간','The time delay in data transmission between a request and a response.','Minimizing {latency} is critical for online gaming.','지연 시간을 최소화하는 것이 온라인 게임에서 중요해요.','latency','C1','technology',2,'latency ping network milliseconds server real-time'),
('w_technology_C1_09','throughput','/ˈθruːpʊt/','noun','처리량','The amount of data processed or transmitted in a given time period.','Increasing {throughput} required additional server capacity.','처리량을 늘리기 위해 추가 서버 용량이 필요했어요.','throughput','C1','technology',2,'throughput server data bandwidth network speed flow'),
('w_technology_C1_10','scalability','/ˌskeɪləˈbɪlɪti/','noun','확장성','The ability of a system to handle growing amounts of work.','The startup prioritized {scalability} from day one.','스타트업은 첫날부터 확장성을 우선시했어요.','scalability','C1','technology',2,'scalability cloud server growth architecture infrastructure'),
('w_technology_C1_11','containerization','/kənˌteɪnərɪˈzeɪʃən/','noun','컨테이너화','Packaging software into isolated containers for consistent deployment.'{Containerization} with Docker simplified our deployment pipeline.','도커를 이용한 컨테이너화가 배포 파이프라인을 단순화했어요.','containerization','C1','technology',2,'docker container deployment devops server cloud'),
('w_technology_C1_12','orchestration','/ˌɔːkɪˈstreɪʃən/','noun','오케스트레이션','The automated coordination and management of complex systems.','Kubernetes handles the {orchestration} of our containers.','쿠버네티스가 컨테이너 오케스트레이션을 담당해요.','orchestration','C1','technology',2,'kubernetes orchestration cluster pod container devops'),
('w_technology_C1_13','abstraction','/æbˈstrækʃən/','noun','추상화','The concept of hiding complexity behind a simpler interface.'{Abstraction} allows developers to use libraries without knowing their internals.','추상화 덕분에 개발자들은 내부 구조를 몰라도 라이브러리를 사용할 수 있어요.','abstraction','C1','technology',2,'abstraction layer code programming concept interface'),
('w_technology_C1_14','concurrency','/kənˈkɜːrənsi/','noun','동시성','The ability to execute multiple tasks at the same time.'{Concurrency} is essential for handling many user requests simultaneously.','동시성은 많은 사용자 요청을 동시에 처리하는 데 필수적이에요.','concurrency','C1','technology',3,'concurrency parallel threads code performance system'),
('w_technology_C1_15','idempotent','/ɪˈdempətənt/','adjective','멱등한','Producing the same result regardless of how many times an operation is performed.','API endpoints should be {idempotent} to prevent duplicate actions.','중복 작업을 방지하려면 API 엔드포인트가 멱등해야 해요.','idempotent','C1','technology',3,'idempotent api endpoint design safe http method'),
('w_technology_C1_16','polymorphism','/ˌpɒliˈmɔːrfɪzəm/','noun','다형성','The ability of code to take multiple forms depending on context.'{Polymorphism} allows a single interface to represent different data types.','다형성은 단일 인터페이스가 다양한 데이터 타입을 표현하게 해요.','polymorphism','C1','technology',3,'polymorphism oop class inheritance object programming'),
('w_technology_C1_17','recursion','/rɪˈkɜːrʒən/','noun','재귀','A programming technique where a function calls itself.'{Recursion} is an elegant solution for traversing tree structures.','재귀는 트리 구조를 순회하는 데 우아한 해법이에요.','recursion','C1','technology',3,'recursion function call tree programming code loop'),
('w_technology_C1_18','middleware','/ˈmɪdəlweər/','noun','미들웨어','Software that acts as a bridge between different applications.'{Middleware} handles authentication before requests reach the API.','미들웨어는 요청이 API에 도달하기 전에 인증을 처리해요.','middleware','C1','technology',3,'middleware layer bridge server request api backend'),
('w_technology_C1_19','load balancing','/loʊd ˈbæləntsɪŋ/','noun','로드 밸런싱','Distributing network traffic evenly across multiple servers.'{Load balancing} ensures no single server is overwhelmed.','로드 밸런싱은 단일 서버가 과부하되지 않도록 해요.','load balancing','C1','technology',3,'load balancing server traffic distribute network cloud'),
('w_technology_C1_20','caching strategy','/ˈkæʃɪŋ ˈstrætɪdʒi/','noun','캐싱 전략','A plan for storing frequently accessed data in fast memory.','A good {caching strategy} dramatically cuts response times.','좋은 캐싱 전략은 응답 시간을 크게 줄여요.','caching strategy','C1','technology',4,'caching strategy memory server speed performance fast'),
('w_technology_C1_21','tokenization','/ˌtoʊkənaɪˈzeɪʃən/','noun','토크나이제이션','The process of splitting text into units for language model processing.'{Tokenization} is the first step in any NLP pipeline.','토크나이제이션은 모든 NLP 파이프라인의 첫 번째 단계예요.','tokenization','C1','technology',4,'tokenization nlp text split word language model'),
('w_technology_C1_22','embedding','/ɪmˈbedɪŋ/','noun','임베딩','A numeric representation of data that captures semantic meaning.','Word {embeddings} allow models to understand similarity.','단어 임베딩은 모델이 유사성을 이해하게 해요.','embeddings','C1','technology',4,'embedding vector space word semantic nlp model'),
('w_technology_C1_23','attention mechanism','/əˈtenʃən ˈmekənɪzəm/','noun','어텐션 메커니즘','A method allowing a model to focus on relevant parts of input data.','The {attention mechanism} is the core of transformer models.','어텐션 메커니즘은 트랜스포머 모델의 핵심이에요.','attention mechanism','C1','technology',4,'attention mechanism transformer ai model heatmap'),
('w_technology_C1_24','inference engine','/ˈɪnfərəns ˈendʒɪn/','noun','추론 엔진','The component of an AI system that applies trained logic to new data.','A fast {inference engine} is required for real-time translation.','실시간 번역에는 빠른 추론 엔진이 필요해요.','inference engine','C1','technology',4,'inference engine ai prediction deployment runtime'),
('w_technology_C1_25','fine-tuning','/faɪn ˈtjuːnɪŋ/','noun','파인튜닝','Adapting a pre-trained model to a specific task with additional training.'{Fine-tuning} a large model is cheaper than training from scratch.','대형 모델을 파인튜닝하는 것은 처음부터 학습하는 것보다 저렴해요.','fine-tuning','C1','technology',4,'fine tuning model training data ai adapt task'),
('w_technology_C1_26','generative AI','/ˌdʒenərətɪv eɪ ˈaɪ/','noun','생성형 AI','AI systems that can create new content such as text, images, or code.'{Generative AI} tools are reshaping creative industries.','생성형 AI 도구가 창작 산업을 재편하고 있어요.','generative AI','C1','technology',4,'generative ai image text create design prompt'),
('w_technology_C1_27','hallucination','/həˌluːsɪˈneɪʃən/','noun','환각 (AI)','When an AI model produces confidently stated but factually incorrect output.'{Hallucination} remains a key challenge for large language models.','환각은 대형 언어 모델의 주요 과제로 남아 있어요.','hallucination','C1','technology',4,'ai hallucination wrong answer language model error'),
('w_technology_C1_28','prompt engineering','/prɒmpt ˌendʒɪˈnɪərɪŋ/','noun','프롬프트 엔지니어링','Crafting input instructions to guide AI models toward better outputs.','Good {prompt engineering} can significantly improve AI responses.','좋은 프롬프트 엔지니어링은 AI 응답을 크게 개선할 수 있어요.','prompt engineering','C1','technology',4,'prompt engineering ai chat instruction design language'),
('w_technology_C1_29','retrieval-augmented generation','/rɪˈtriːvəl ˌɔːɡmentɪd ˌdʒenəˈreɪʃən/','noun','검색 증강 생성 (RAG)','An AI technique that retrieves external data to ground generated responses.'{Retrieval-augmented generation} reduces hallucinations significantly.','검색 증강 생성은 환각을 크게 줄여요.','retrieval-augmented generation','C1','technology',5,'rag retrieval augmented generation search ai knowledge'),
('w_technology_C1_30','vector database','/ˈvektər ˈdeɪtəbeɪs/','noun','벡터 데이터베이스','A database optimized for storing and searching high-dimensional vectors.','The chatbot uses a {vector database} for semantic search.','챗봇은 의미 검색을 위해 벡터 데이터베이스를 사용해요.','vector database','C1','technology',5,'vector database semantic search embedding storage query'),
('w_technology_C1_31','multimodal','/ˌmʌltiˈmoʊdəl/','adjective','멀티모달의','Capable of processing and generating multiple types of data (text, image, audio).'{Multimodal} models can understand both pictures and words.','멀티모달 모델은 그림과 글을 모두 이해할 수 있어요.','multimodal','C1','technology',5,'multimodal ai image text audio video model'),
('w_technology_C1_32','large language model','/lɑːrdʒ ˈlæŋɡwɪdʒ ˈmɒdəl/','noun','대형 언어 모델 (LLM)','A very large neural network trained on text to understand and generate language.'{Large language models} are transforming search and productivity tools.','대형 언어 모델이 검색과 생산성 도구를 변혁하고 있어요.','large language model','C1','technology',5,'large language model llm ai training data text'),
('w_technology_C1_33','context window','/ˈkɒntekst ˈwɪndoʊ/','noun','컨텍스트 윈도우','The maximum amount of text a language model can consider at once.','A longer {context window} lets the model handle longer documents.','긴 컨텍스트 윈도우는 모델이 더 긴 문서를 처리하게 해요.','context window','C1','technology',5,'context window tokens llm memory length document'),
('w_technology_C1_34','benchmark','/ˈbentʃmɑːrk/','noun','벤치마크','A standard test used to measure the performance of a system or model.','The new model set a record on every {benchmark}.','새 모델이 모든 벤치마크에서 기록을 세웠어요.','benchmark','C1','technology',5,'benchmark test performance score compare ranking'),
('w_technology_C1_35','explainability','/ɪkˌspleɪnəˈbɪlɪti/','noun','설명 가능성','The ability to interpret and explain how an AI model makes decisions.'{Explainability} is required for AI used in healthcare decisions.','의료 결정에 사용되는 AI에는 설명 가능성이 요구돼요.','explainability','C1','technology',5,'explainability ai interpret decision transparent model');

-- ══════════════════════════════════════
-- WORDS — C2 (최첨단·신흥 기술)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_technology_C2_01','neuromorphic','/ˌnjʊərəˈmɔːrfɪk/','adjective','뉴로모픽의','Relating to hardware or circuits that mimic the structure of the brain.'{Neuromorphic} chips could make AI hardware far more energy-efficient.','뉴로모픽 칩은 AI 하드웨어를 훨씬 더 에너지 효율적으로 만들 수 있어요.','neuromorphic','C2','technology',1,'neuromorphic chip brain inspired hardware circuit'),
('w_technology_C2_02','bioengineering','/ˌbaɪoʊˌendʒɪˈnɪərɪŋ/','noun','생명공학','The application of engineering principles to biological systems.'{Bioengineering} is being used to develop lab-grown tissues.','생명공학이 실험실에서 배양된 조직을 개발하는 데 활용되고 있어요.','bioengineering','C2','technology',1,'bioengineering lab tissue dna biology engineering'),
('w_technology_C2_03','nanotechnology','/ˌnænoʊtekˈnɒlədʒi/','noun','나노기술','The manipulation of matter at an atomic or molecular scale.'{Nanotechnology} may one day deliver drugs directly to cancer cells.','나노기술이 언젠가 암세포에 직접 약을 전달할 수도 있어요.','nanotechnology','C2','technology',1,'nanotechnology nano particles microscope science lab'),
('w_technology_C2_04','quantum entanglement','/ˈkwɒntəm ɪnˈtæŋɡəlmənt/','noun','양자 얽힘','A quantum phenomenon where particles remain interconnected regardless of distance.'{Quantum entanglement} is the basis for future quantum communication networks.','양자 얽힘은 미래 양자 통신 네트워크의 기반이에요.','quantum entanglement','C2','technology',1,'quantum entanglement particles physics abstract science'),
('w_technology_C2_05','topological','/ˌtɒpəˈlɒdʒɪkəl/','adjective','위상학적인','Relating to properties of space that are preserved under continuous deformations.'{Topological} qubits are considered more stable for quantum computers.','위상학적 큐비트는 양자 컴퓨터에서 더 안정적인 것으로 여겨져요.','topological','C2','technology',1,'topological qubit quantum abstract geometry physics'),
('w_technology_C2_06','emergent systems','/ɪˈmɜːrdʒənt ˈsɪstəmz/','noun','창발 시스템','Complex behaviors arising from simple rules at a larger scale.'{Emergent systems} show that the whole can be greater than the sum of its parts.','창발 시스템은 전체가 부분의 합보다 클 수 있음을 보여줘요.','emergent systems','C2','technology',2,'emergent behavior complex system swarm flock pattern'),
('w_technology_C2_07','stochastic','/stəˈkæstɪk/','adjective','확률론적인','Randomly determined, having a probability distribution.'{Stochastic} gradient descent is used to train most neural networks.','확률론적 경사하강법은 대부분의 신경망을 학습시키는 데 사용돼요.','stochastic','C2','technology',2,'stochastic random probability gradient descent mathematics'),
('w_technology_C2_08','probabilistic','/prəˌbæbɪˈlɪstɪk/','adjective','확률적인','Based on or relating to probability rather than certainty.'{Probabilistic} reasoning allows AI to handle uncertain information.','확률적 추론은 AI가 불확실한 정보를 처리할 수 있게 해요.','probabilistic','C2','technology',2,'probabilistic reasoning probability uncertainty ai model'),
('w_technology_C2_09','biomimetic','/ˌbaɪoʊmɪˈmetɪk/','adjective','생체모방의','Imitating the models, systems, and elements of nature.'{Biomimetic} robots copy the movement of insects to navigate rough terrain.','생체모방 로봇은 곤충의 움직임을 모방해 험한 지형을 탐색해요.','biomimetic','C2','technology',2,'biomimetic robot insect nature design engineering lab'),
('w_technology_C2_10','exascale','/ˈeksəskeɪl/','adjective','엑사스케일의','Capable of performing one quintillion (10^18) floating-point operations per second.'{Exascale} computing will accelerate climate modeling and drug discovery.','엑사스케일 컴퓨팅이 기후 모델링과 신약 개발을 가속화할 거예요.','exascale','C2','technology',2,'exascale supercomputer computing power lab science'),
('w_technology_C2_11','agentic AI','/eɪˈdʒentɪk eɪ ˈaɪ/','noun','에이전틱 AI','AI systems that can autonomously take actions to accomplish goals.'{Agentic AI} can browse the web and execute code without human prompting.','에이전틱 AI는 사람의 지시 없이도 웹을 탐색하고 코드를 실행할 수 있어요.','agentic AI','C2','technology',2,'agentic ai autonomous agent robot decision action'),
('w_technology_C2_12','sovereign AI','/ˈsɒvrɪn eɪ ˈaɪ/','noun','소버린 AI','AI infrastructure owned and controlled by a nation or organization for strategic independence.'{Sovereign AI} is a growing priority as nations seek digital independence.','소버린 AI는 국가들이 디지털 독립을 추구하면서 중요성이 커지고 있어요.','sovereign AI','C2','technology',2,'sovereign ai national infrastructure independence data center'),
('w_technology_C2_13','synthetic data','/sɪnˈθetɪk ˈdeɪtə/','noun','합성 데이터','Artificially generated data used to train models when real data is scarce.'{Synthetic data} helps companies train AI without exposing private information.','합성 데이터는 기업이 개인 정보를 노출하지 않고 AI를 학습시킬 수 있게 해요.','synthetic data','C2','technology',3,'synthetic data generation ai training privacy computer'),
('w_technology_C2_14','differential privacy','/ˌdɪfəˈrenʃəl ˈprɪvəsi/','noun','차등 프라이버시','A mathematical technique for sharing statistical information while protecting individual privacy.'{Differential privacy} adds controlled noise to protect user data.','차등 프라이버시는 사용자 데이터를 보호하기 위해 제어된 노이즈를 추가해요.','differential privacy','C2','technology',3,'differential privacy data math noise protection secure'),
('w_technology_C2_15','zero-knowledge proof','/ˌzɪərəʊ ˈnɒlɪdʒ pruːf/','noun','영지식 증명','A cryptographic method to prove knowledge of information without revealing it.'{Zero-knowledge proofs} allow authentication without sharing passwords.','영지식 증명은 비밀번호를 공개하지 않고도 인증을 가능하게 해요.','zero-knowledge proof','C2','technology',3,'zero knowledge proof cryptography math security verify'),
('w_technology_C2_16','homomorphic encryption','/ˌhoʊməˈmɔːrfɪk ɪnˈkrɪpʃən/','noun','동형 암호화','Encryption that allows computation on ciphertext without decrypting it first.'{Homomorphic encryption} enables secure cloud computation on private data.','동형 암호화는 개인 데이터에 대한 안전한 클라우드 연산을 가능하게 해요.','homomorphic encryption','C2','technology',3,'homomorphic encryption secure cloud computation math'),
('w_technology_C2_17','superintelligence','/ˌsuːpərɪnˈtelɪdʒəns/','noun','초지능','A hypothetical AI that would surpass human intelligence across all domains.','The debate about {superintelligence} safety is intensifying.','초지능 안전에 관한 논쟁이 심화되고 있어요.','superintelligence','C2','technology',3,'superintelligence agi robot future ai human beyond'),
('w_technology_C2_18','alignment','/əˈlaɪnmənt/','noun','정렬 (AI 안전)','The challenge of ensuring AI systems pursue goals consistent with human values.'{Alignment} research aims to make AI reliably beneficial.','정렬 연구는 AI를 안정적으로 유익하게 만드는 것을 목표로 해요.','alignment','C2','technology',3,'ai alignment safety research human values goals'),
('w_technology_C2_19','Turing-complete','/ˈtjʊərɪŋ kəmˈpliːt/','adjective','튜링 완전한','Describing a system capable of performing any computation that any other computer can perform.','Any {Turing-complete} language can theoretically simulate any other.','튜링 완전한 언어는 이론적으로 다른 어떤 언어도 시뮬레이션할 수 있어요.','Turing-complete','C2','technology',4,'turing complete computation theory computer science'),
('w_technology_C2_20','entropy','/ˈentrəpi/','noun','엔트로피','A measure of disorder or uncertainty in a system or information theory.','High {entropy} in model outputs suggests lower confidence.','모델 출력의 높은 엔트로피는 낮은 신뢰도를 나타내요.','entropy','C2','technology',4,'entropy information theory disorder uncertainty math'),
('w_technology_C2_21','manifold hypothesis','/ˈmænɪfoʊld haɪˈpɒθɪsɪs/','noun','다양체 가설','The idea that high-dimensional data lies on lower-dimensional structures.','The {manifold hypothesis} explains why deep learning works so well on images.','다양체 가설은 딥러닝이 이미지에서 잘 작동하는 이유를 설명해요.','manifold hypothesis','C2','technology',4,'manifold hypothesis dimension geometry data science'),
('w_technology_C2_22','spiking neural network','/ˈspaɪkɪŋ ˈnjʊərəl ˈnetwɜːrk/','noun','스파이킹 신경망','A type of neural network that processes information using discrete spikes.'{Spiking neural networks} more closely mimic biological neurons.','스파이킹 신경망은 생물학적 뉴런을 더 가깝게 모방해요.','spiking neural network','C2','technology',4,'spiking neural network brain neuron spike bio inspired'),
('w_technology_C2_23','digital twin','/ˈdɪdʒɪtəl twɪn/','noun','디지털 트윈','A virtual replica of a physical system used for simulation.','Engineers use a {digital twin} to test aircraft design virtually.','엔지니어들이 항공기 설계를 가상으로 테스트하기 위해 디지털 트윈을 사용해요.','digital twin','C2','technology',4,'digital twin simulation virtual model factory engineering'),
('w_technology_C2_24','model collapse','/ˈmɒdəl kəˈlæps/','noun','모델 붕괴','Degradation of an AI model trained on data generated by other AI models.'{Model collapse} is a risk when AI-generated text dominates training data.','AI 생성 텍스트가 학습 데이터를 지배하면 모델 붕괴의 위험이 있어요.','model collapse','C2','technology',4,'model collapse ai degradation training data quality'),
('w_technology_C2_25','substrate independence','/ˈsʌbstreɪt ɪnˈdɪpɪndəns/','noun','기질 독립성','The principle that mind or intelligence can exist on any physical substrate.'{Substrate independence} underpins theories of mind uploading.','기질 독립성은 마음 업로드 이론의 근거가 돼요.','substrate independence','C2','technology',5,'substrate independence mind brain upload theory philosophy'),
('w_technology_C2_26','Gödel incompleteness','/ˈɡɜːdəl ˌɪnkəmˈpliːtnɪs/','noun','괴델의 불완전성','The theorem showing no consistent system can prove all truths about itself.'{Gödel incompleteness} sets fundamental limits on formal reasoning systems.','괴델의 불완전성은 형식 추론 시스템의 근본적인 한계를 설정해요.','Gödel incompleteness','C2','technology',5,'godel incompleteness theorem math logic proof formal'),
('w_technology_C2_27','spectral efficiency','/ˈspektrəl ɪˈfɪʃənsi/','noun','주파수 효율','The information rate transmitted over a given bandwidth in communication.','6G aims to achieve far greater {spectral efficiency} than 5G.','6G는 5G보다 훨씬 높은 주파수 효율을 달성하는 것을 목표로 해요.','spectral efficiency','C2','technology',5,'spectral efficiency 6g wireless spectrum radio wave'),
('w_technology_C2_28','photonic computing','/fəˈtɒnɪk kəmˈpjuːtɪŋ/','noun','광자 컴퓨팅','Computing using photons of light instead of electrons for data processing.'{Photonic computing} offers the potential for ultra-high-speed data processing.','광자 컴퓨팅은 초고속 데이터 처리의 가능성을 제공해요.','photonic computing','C2','technology',5,'photonic computing light photon chip speed data'),
('w_technology_C2_29','cognitive architecture','/ˈkɒɡnɪtɪv ˈɑːrkɪtektʃər/','noun','인지 아키텍처','A blueprint for intelligent agents that specifies how cognitive processes interact.'{Cognitive architecture} research bridges neuroscience and AI.','인지 아키텍처 연구는 신경과학과 AI를 연결해요.','cognitive architecture','C2','technology',5,'cognitive architecture brain ai mind model framework'),
('w_technology_C2_30','collective intelligence','/kəˈlektɪv ɪnˈtelɪdʒəns/','noun','집단 지성','Intelligence that emerges from the collaboration of many individuals or systems.'{Collective intelligence} platforms harness the wisdom of crowds.','집단 지성 플랫폼은 집단의 지혜를 활용해요.','collective intelligence','C2','technology',5,'collective intelligence crowd wisdom collaboration network'),
('w_technology_C2_31','causal inference','/ˈkɔːzəl ˈɪnfərəns/','noun','인과 추론','The process of drawing conclusions about cause-and-effect relationships from data.'{Causal inference} goes beyond correlation to find true relationships.','인과 추론은 상관관계를 넘어 진정한 관계를 찾아요.','causal inference','C2','technology',5,'causal inference cause effect data statistics arrows'),
('w_technology_C2_32','continual learning','/kənˈtɪnjuəl ˈlɜːrnɪŋ/','noun','지속적 학습','Training a model on new data without forgetting previously learned knowledge.'{Continual learning} prevents the catastrophic forgetting problem in AI.','지속적 학습은 AI의 파국적 망각 문제를 예방해요.','continual learning','C2','technology',5,'continual learning ai memory knowledge sequential training'),
('w_technology_C2_33','computational irreducibility','/ˌkɒmpjuːˈteɪʃənəl ˌɪrɪˌdjuːsɪˈbɪlɪti/','noun','계산 비가역성','The property of systems whose behavior cannot be predicted without full simulation.'{Computational irreducibility} limits our ability to foresee complex system outcomes.','계산 비가역성은 복잡한 시스템 결과를 예측하는 우리의 능력을 제한해요.','computational irreducibility','C2','technology',5,'computational irreducibility complexity system simulation wolfram'),
('w_technology_C2_34','mesa-optimization','/ˈmesə ˌɒptɪmaɪˈzeɪʃən/','noun','메사 최적화','When a trained model itself becomes an optimizer pursuing its own internal objective.'{Mesa-optimization} is a key alignment risk where inner objectives diverge from intended goals.','메사 최적화는 내부 목표가 의도한 목표와 달라지는 주요 정렬 위험이에요.','mesa-optimization','C2','technology',5,'mesa optimization alignment risk inner objective ai safety'),
('w_technology_C2_35','wetware','/ˈwetweər/','noun','웨트웨어 (생물 기반 컴퓨팅)','Biological neural tissue used as a computing substrate, contrasted with hardware and software.','Researchers grew brain organoids as {wetware} for neuromorphic experiments.','연구자들이 뉴로모픽 실험을 위한 웨트웨어로 뇌 오가노이드를 배양했어요.','wetware','C2','technology',5,'wetware organoid brain computing biology lab neuron');

-- ══════════════════════════════════════
-- PATTERNS — A1 (기기 사용)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_technology_A1_01','How do I use this app?','이 앱 어떻게 사용해요?','How do I use','사용 방법을 물을 때 How do I...?를 써요.','앱 사용','A1','technology','pattern',NULL,1),
('s_technology_A1_02','Where is the power button?','전원 버튼이 어디 있어요?','Where is the','기기 부품을 찾을 때 Where is...?를 써요.','기기 조작','A1','technology','pattern',NULL,2),
('s_technology_A1_03','Can you help me with my phone?','제 휴대폰 도와주실 수 있어요?','Can you help me with','도움을 정중하게 요청할 때 Can you help me with...?를 써요.','기술 도움 요청','A1','technology','pattern',NULL,3),
('s_technology_A1_04','I need to charge my battery.','배터리를 충전해야 해요.','I need to','필요나 의무를 나타낼 때 I need to...를 써요.','기기 관리','A1','technology','pattern',NULL,4),
('s_technology_A1_05','Please send me the photo.','사진을 보내주세요.','Please send me','정중하게 요청할 때 Please send me...를 써요.','파일 전송','A1','technology','pattern',NULL,5),
('s_technology_A1_06','What is your email address?','이메일 주소가 뭐예요?','What is your','상대방의 정보를 물을 때 What is your...?를 써요.','연락처 교환','A1','technology','pattern',NULL,6),
('s_technology_A1_07','I can''t find the app on my phone.','휴대폰에서 앱을 찾을 수 없어요.','I can''t find','어떤 것을 찾지 못했을 때 I can''t find...를 써요.','앱 찾기','A1','technology','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — A2 (기술 문제 해결)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_technology_A2_01','My phone keeps freezing — do you know how to fix it?','제 휴대폰이 계속 멈춰요. 고치는 방법을 알아요?','keeps freezing','keep + -ing는 반복적인 문제를 표현할 때 써요.','기기 오류 설명','A2','technology','pattern',NULL,1),
('s_technology_A2_02','I forgot my password — how can I reset it?','비밀번호를 잊었어요. 어떻게 초기화해요?','forgot my password','forgot는 이미 잊어버린 상태를 나타내요.','비밀번호 문제','A2','technology','pattern',NULL,2),
('s_technology_A2_03','The wifi is not working — can you check the router?','와이파이가 안 돼요. 라우터를 확인해줄 수 있어요?','not working','not working은 기기가 작동하지 않을 때 쓰는 표현이에요.','연결 문제','A2','technology','pattern',NULL,3),
('s_technology_A2_04','Try restarting the device and see if it helps.','기기를 재시작해보고 도움이 되는지 확인해 보세요.','Try restarting','Try + -ing는 해결책을 제안할 때 써요.','문제 해결 제안','A2','technology','pattern',NULL,4),
('s_technology_A2_05','I need to update the app to make it work properly.','제대로 작동하게 하려면 앱을 업데이트해야 해요.','update the app to make it work','to + 동사원형은 목적을 나타낼 때 써요.','앱 업데이트','A2','technology','pattern',NULL,5),
('s_technology_A2_06','Can you show me how to download photos from the cloud?','클라우드에서 사진을 다운로드하는 방법을 알려줄 수 있어요?','show me how to','show me how to는 단계별 설명을 부탁할 때 써요.','클라우드 사용','A2','technology','pattern',NULL,6),
('s_technology_A2_07','I accidentally deleted the file — is there any way to recover it?','파일을 실수로 삭제했어요. 복구할 방법이 있을까요?','Is there any way to','Is there any way to...?는 해결책을 조심스럽게 물을 때 써요.','데이터 복구','A2','technology','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — B1 (새 기술 설명)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_technology_B1_01','Basically, an algorithm is a set of rules that tells the computer what to do step by step.','기본적으로 알고리즘은 컴퓨터에 단계별로 무엇을 해야 할지 알려주는 규칙의 모음이에요.','Basically, ... is a set of rules that','Basically로 시작하면 복잡한 개념을 쉽게 설명할 수 있어요.','기술 개념 설명','B1','technology','pattern',NULL,1),
('s_technology_B1_02','The cloud lets you access your files from any device, so you don''t need to carry a USB.','클라우드를 사용하면 어떤 기기에서든 파일에 접근할 수 있어서 USB를 들고 다닐 필요가 없어요.','lets you access ... so you don''t need to','lets you + 동사원형은 가능하게 해주는 것을 설명해요.','클라우드 설명','B1','technology','pattern',NULL,2),
('s_technology_B1_03','Cybersecurity is becoming more important as more of our daily life moves online.','일상생활의 더 많은 부분이 온라인으로 옮겨지면서 사이버 보안이 점점 더 중요해지고 있어요.','is becoming more important as','as + 문장은 원인이나 상황이 함께 변할 때 써요.','기술 트렌드 설명','B1','technology','pattern',NULL,3),
('s_technology_B1_04','One of the biggest advantages of automation is that it reduces human error.','자동화의 가장 큰 장점 중 하나는 인적 오류를 줄인다는 거예요.','One of the biggest advantages is that','One of the biggest advantages is that...은 기술의 장점을 설명할 때 써요.','기술 장점 설명','B1','technology','pattern',NULL,4),
('s_technology_B1_05','The interface looks complicated at first, but once you get used to it, it''s quite easy.','인터페이스가 처음에는 복잡해 보이지만 익숙해지면 꽤 쉬워요.','looks complicated at first, but once you get used to it','but once you get used to it은 어려운 기술에 적응하는 것을 설명해요.','앱 사용법 설명','B1','technology','pattern',NULL,5),
('s_technology_B1_06','Make sure you back up your data before updating the operating system.','운영체제를 업데이트하기 전에 반드시 데이터를 백업하세요.','Make sure you ... before','Make sure you...before...는 순서를 지켜야 할 때 쓰는 표현이에요.','안전한 업데이트 조언','B1','technology','pattern',NULL,6),
('s_technology_B1_07','If you enable two-factor authentication, your account will be much harder to hack.','이중 인증을 활성화하면 계정을 해킹하기 훨씬 어려워질 거예요.','If you enable ... your account will be','If + 현재시제, will + 동사원형은 조건과 결과를 설명해요.','보안 설정 조언','B1','technology','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — B2 (AI·빅데이터 논의)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_technology_B2_01','Machine learning models improve over time because they learn from new data.','머신러닝 모델은 새로운 데이터로부터 학습하기 때문에 시간이 지남에 따라 개선돼요.','improve over time because they learn from','because는 원인과 결과를 연결하는 가장 명확한 접속사예요.','AI 원리 설명','B2','technology','pattern',NULL,1),
('s_technology_B2_02','There are growing concerns about how companies collect and use our personal data.','기업들이 개인 데이터를 수집하고 사용하는 방식에 대한 우려가 커지고 있어요.','There are growing concerns about how','There are growing concerns about...는 사회적 문제를 소개할 때 써요.','데이터 프라이버시 토론','B2','technology','pattern',NULL,2),
('s_technology_B2_03','Blockchain is often described as a decentralized ledger that cannot be tampered with.','블록체인은 종종 변조할 수 없는 분산형 장부로 설명돼요.','is often described as','is often described as는 기술 개념을 정의할 때 쓰는 패턴이에요.','기술 개념 정의','B2','technology','pattern',NULL,3),
('s_technology_B2_04','The real challenge with AI isn''t making it more powerful — it''s making it safe.','AI의 진짜 과제는 더 강력하게 만드는 것이 아니라 안전하게 만드는 거예요.','The real challenge isn''t ... it''s','The real challenge isn''t X — it''s Y는 핵심 논점을 전환할 때 써요.','AI 토론','B2','technology','pattern',NULL,4),
('s_technology_B2_05','One potential downside of automation is that it could lead to job losses in certain sectors.','자동화의 잠재적인 단점 중 하나는 특정 부문에서 일자리 감소로 이어질 수 있다는 거예요.','One potential downside is that it could lead to','One potential downside is that...은 균형 잡힌 논점을 제시할 때 써요.','자동화 영향 토론','B2','technology','pattern',NULL,5),
('s_technology_B2_06','It''s worth noting that not all AI systems are created equal in terms of accuracy.','모든 AI 시스템이 정확도 면에서 동등하게 만들어지는 것은 아니라는 점을 주목할 가치가 있어요.','It''s worth noting that','It''s worth noting that...은 중요한 세부 사항을 강조할 때 써요.','AI 비교 설명','B2','technology','pattern',NULL,6),
('s_technology_B2_07','The IoT means that everyday objects — from fridges to streetlights — can share data.','사물인터넷은 냉장고부터 가로등까지 일상적인 사물이 데이터를 공유할 수 있다는 걸 의미해요.','means that ... from ... to ... can','means that은 기술 개념의 실질적 의미를 설명할 때 써요.','IoT 설명','B2','technology','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — C1 (기술 미래 논의)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_technology_C1_01','Quantum computing has the potential to render current encryption methods obsolete within a decade.','양자 컴퓨팅은 10년 안에 현재의 암호화 방법을 쓸모없게 만들 잠재력을 가지고 있어요.','has the potential to render ... obsolete','has the potential to는 미래의 혁명적 변화를 예측할 때 써요.','양자 컴퓨팅 전망','C1','technology','pattern',NULL,1),
('s_technology_C1_02','The line between human intelligence and artificial intelligence is becoming increasingly blurred.','인간 지능과 인공지능 사이의 경계가 점점 더 모호해지고 있어요.','The line between ... is becoming increasingly blurred','is becoming increasingly blurred는 경계가 흐려지는 추세를 표현해요.','AI 철학 토론','C1','technology','pattern',NULL,2),
('s_technology_C1_03','Federated learning addresses the privacy paradox by training models without centralizing data.','연합 학습은 데이터를 중앙화하지 않고 모델을 학습시킴으로써 프라이버시 역설을 해결해요.','addresses ... by ... without','addresses...by...without은 문제 해결 방법을 정확하게 설명해요.','기술 솔루션 설명','C1','technology','pattern',NULL,3),
('s_technology_C1_04','Edge computing is gaining traction precisely because it reduces dependency on centralized infrastructure.','엣지 컴퓨팅은 중앙 집중식 인프라에 대한 의존도를 줄이기 때문에 정확히 주목받고 있어요.','is gaining traction precisely because','is gaining traction은 기술이 주목받기 시작할 때 쓰는 표현이에요.','기술 트렌드 분석','C1','technology','pattern',NULL,4),
('s_technology_C1_05','Transformer architectures have fundamentally reshaped how we approach natural language processing.','트랜스포머 아키텍처는 자연어 처리에 접근하는 방식을 근본적으로 재편했어요.','have fundamentally reshaped how we approach','have reshaped는 현재완료로 지속적인 영향을 나타내요.','AI 역사 분석','C1','technology','pattern',NULL,5),
('s_technology_C1_06','One of the most pressing challenges in AI safety is ensuring that models remain aligned with human values over time.','AI 안전에서 가장 긴박한 과제 중 하나는 모델이 시간이 지나도 인간의 가치와 정렬 상태를 유지하도록 보장하는 거예요.','One of the most pressing challenges is ensuring that','One of the most pressing challenges는 중요성을 강조하는 표현이에요.','AI 안전 토론','C1','technology','pattern',NULL,6),
('s_technology_C1_07','Scalability is not merely a technical concern — it fundamentally shapes business strategy and competitive advantage.','확장성은 단순한 기술적 문제가 아니에요. 비즈니스 전략과 경쟁 우위를 근본적으로 형성해요.','is not merely ... it fundamentally shapes','not merely...it fundamentally는 기술적 개념의 더 깊은 의미를 강조해요.','기술 전략 논의','C1','technology','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — C2 (기술 미래 고급 논의)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_technology_C2_01','The emergence of neuromorphic computing suggests we may be approaching the physical limits of silicon-based architectures.','뉴로모픽 컴퓨팅의 등장은 우리가 실리콘 기반 아키텍처의 물리적 한계에 근접하고 있음을 시사해요.','suggests we may be approaching the physical limits of','suggests we may be는 신중하게 미래 가능성을 제시할 때 써요.','컴퓨팅 한계 논의','C2','technology','pattern',NULL,1),
('s_technology_C2_02','The probabilistic nature of large language models means their outputs can never be fully deterministic.','대형 언어 모델의 확률론적 특성은 그 출력이 완전히 결정론적일 수 없음을 의미해요.','The probabilistic nature ... means their outputs can never be fully','The...nature of...means는 본질적 특성을 설명하는 고급 패턴이에요.','AI 한계 토론','C2','technology','pattern',NULL,2),
('s_technology_C2_03','What distinguishes stochastic from deterministic systems is the irreducible role of randomness in their dynamics.','확률론적 시스템이 결정론적 시스템과 다른 점은 그 역학에서 무작위성이 환원 불가능한 역할을 한다는 거예요.','What distinguishes A from B is the irreducible role of','What distinguishes A from B는 두 개념의 핵심 차이를 설명할 때 써요.','과학 개념 비교','C2','technology','pattern',NULL,3),
('s_technology_C2_04','Bioengineering and nanotechnology are converging in ways that could redefine the boundaries of medicine itself.','생명공학과 나노기술은 의학 자체의 경계를 재정의할 수 있는 방식으로 융합되고 있어요.','are converging in ways that could redefine the boundaries of','are converging in ways that는 기술 융합의 심층적 가능성을 표현해요.','기술 융합 논의','C2','technology','pattern',NULL,4),
('s_technology_C2_05','The alignment problem is, at its core, a question of whether we can formalize human values in a mathematically tractable way.','정렬 문제는 핵심적으로 인간의 가치를 수학적으로 다룰 수 있는 방식으로 형식화할 수 있는지의 문제예요.','is, at its core, a question of whether we can formalize','at its core는 문제의 본질을 파고들 때 쓰는 고급 표현이에요.','AI 철학 심층 토론','C2','technology','pattern',NULL,5),
('s_technology_C2_06','Quantum entanglement challenges our intuitions about locality and separability in ways that classical physics simply cannot accommodate.','양자 얽힘은 고전 물리학이 단순히 수용할 수 없는 방식으로 국소성과 분리 가능성에 대한 우리의 직관에 도전해요.','challenges our intuitions ... in ways that ... simply cannot accommodate','challenges our intuitions는 패러다임을 흔드는 개념을 논할 때 써요.','양자 물리학 토론','C2','technology','pattern',NULL,6),
('s_technology_C2_07','Emergent behavior in complex systems implies that reductionist approaches alone are insufficient to predict or explain technological outcomes.','복잡한 시스템에서의 창발적 행동은 환원주의적 접근법만으로는 기술적 결과를 예측하거나 설명하기에 충분하지 않음을 의미해요.','implies that reductionist approaches alone are insufficient to','implies that...alone are insufficient to는 학문적 주장을 제시할 때 써요.','복잡계 이론 토론','C2','technology','pattern',NULL,7);
