-- EngCat · Topic: environment (환경)
-- 210 words (35 per CEFR level A1–C2) + 42 sentence patterns (7 per level)
-- Generated: 2026-05-24

-- ============================================================
-- WORDS
-- ============================================================

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES

-- ────────────────────────────────────────────────────────────
-- A1 (35 words)
-- ────────────────────────────────────────────────────────────
('w_environment_A1_01','tree','/triː/','noun','나무','A tall plant with a trunk and branches.','We planted a {tree} in the garden.','우리는 정원에 나무를 심었어요.','tree','A1','environment',1,'tree nature green forest park'),
('w_environment_A1_02','water','/ˈwɔːtər/','noun','물','A clear liquid that rivers, lakes, and the sea are made of.','Please don''t waste {water}.','물을 낭비하지 마세요.','water','A1','environment',1,'water river lake clean blue'),
('w_environment_A1_03','air','/ɛr/','noun','공기','The mixture of gases that surrounds the Earth.','Fresh {air} is good for your health.','신선한 공기는 건강에 좋아요.','air','A1','environment',1,'air sky wind fresh outdoors'),
('w_environment_A1_04','clean','/kliːn/','adjective','깨끗한','Free from dirt or harmful substances.','We need {clean} water to live.','우리는 살기 위해 깨끗한 물이 필요해요.','clean','A1','environment',1,'clean water pure clear nature'),
('w_environment_A1_05','nature','/ˈneɪtʃər/','noun','자연','The physical world including plants, animals, and the landscape.','I love going for walks in {nature}.','저는 자연 속에서 산책하는 걸 좋아해요.','nature','A1','environment',1,'nature landscape forest mountain scenery'),
('w_environment_A1_06','sun','/sʌn/','noun','태양','The star at the center of our solar system that gives light and heat.','The {sun} gives us light and warmth.','태양은 우리에게 빛과 따뜻함을 줘요.','sun','A1','environment',1,'sun sunshine sky bright warm'),
('w_environment_A1_07','earth','/ɜːrθ/','noun','지구','The planet on which we live.','We must take care of our {earth}.','우리는 지구를 돌봐야 해요.','earth','A1','environment',1,'earth planet globe world space'),
('w_environment_A1_08','green','/ɡriːn/','adjective','초록색의','The colour of grass and leaves; relating to environmental protection.','Let''s keep our city {green}.','우리 도시를 초록색으로 유지해요.','green','A1','environment',1,'green park grass plants nature'),
('w_environment_A1_09','plant','/plænt/','noun','식물','A living thing that grows in soil and uses sunlight for energy.','Every {plant} needs sunlight and water.','모든 식물은 햇빛과 물이 필요해요.','plant','A1','environment',1,'plant flower garden growth green'),
('w_environment_A1_10','animal','/ˈænɪməl/','noun','동물','A living creature that can move and breathe.','Every {animal} has a role in nature.','모든 동물은 자연에서 역할을 맡고 있어요.','animal','A1','environment',1,'animal wildlife nature habitat wild'),
('w_environment_A1_11','flower','/ˈflaʊər/','noun','꽃','The colorful part of a plant that attracts insects.','The {flower} bloomed in the spring.','꽃이 봄에 피었어요.','flower','A1','environment',1,'flower bloom garden colorful spring'),
('w_environment_A1_12','sky','/skaɪ/','noun','하늘','The space above the earth that you see when you look up.','The {sky} was clear and blue today.','오늘 하늘이 맑고 파랬어요.','sky','A1','environment',1,'sky blue cloud sunshine weather'),
('w_environment_A1_13','rain','/reɪn/','noun','비','Water that falls from clouds in small drops.','The {rain} waters the plants.','비가 식물에게 물을 줘요.','rain','A1','environment',1,'rain water cloud weather nature'),
('w_environment_A1_14','snow','/snoʊ/','noun','눈','Small white pieces of frozen water that fall from the sky.','Children love to play in the {snow}.','아이들은 눈 속에서 노는 걸 좋아해요.','snow','A1','environment',1,'snow winter white cold ice'),
('w_environment_A1_15','rock','/rɒk/','noun','바위','A solid piece of stone.','We sat on a big {rock} by the river.','우리는 강가 큰 바위에 앉았어요.','rock','A1','environment',1,'rock stone mountain nature outdoor'),
('w_environment_A1_16','sea','/siː/','noun','바다','The large area of salt water that covers most of the Earth.','The {sea} is home to many creatures.','바다는 많은 생물의 보금자리예요.','sea','A1','environment',1,'sea ocean water wave blue'),
('w_environment_A1_17','fish','/fɪʃ/','noun','물고기','A creature that lives in water and breathes through gills.','There are many {fish} in the river.','강에 물고기가 많아요.','fish','A1','environment',1,'fish ocean water marine nature'),
('w_environment_A1_18','bird','/bɜːrd/','noun','새','A creature with wings and feathers that can usually fly.','The {bird} sings every morning.','새는 매일 아침 노래해요.','bird','A1','environment',1,'bird wing sky feather nature'),
('w_environment_A1_19','leaf','/liːf/','noun','나뭇잎','The flat, green part of a plant that grows from a stem or branch.','A {leaf} fell from the tree.','나뭇잎 하나가 나무에서 떨어졌어요.','leaf','A1','environment',1,'leaf tree green autumn nature'),
('w_environment_A1_20','grass','/ɡræs/','noun','풀','The short green plant that covers the ground in fields and gardens.','The {grass} is soft under your feet.','풀이 발 아래에서 부드러워요.','grass','A1','environment',1,'grass green field meadow nature'),
('w_environment_A1_21','wind','/wɪnd/','noun','바람','The natural movement of air.','The {wind} blew the leaves away.','바람이 나뭇잎들을 날려버렸어요.','wind','A1','environment',1,'wind breeze nature outdoors air'),
('w_environment_A1_22','fire','/faɪər/','noun','불','The heat, light, and flames produced when something burns.','{Fire} can destroy a whole forest.','불은 숲 전체를 태울 수 있어요.','fire','A1','environment',1,'fire flame heat danger forest'),
('w_environment_A1_23','sand','/sænd/','noun','모래','Tiny pieces of rock found on beaches and in deserts.','The {sand} was warm on the beach.','해변의 모래가 따뜻했어요.','sand','A1','environment',1,'sand beach desert warm nature'),
('w_environment_A1_24','lake','/leɪk/','noun','호수','A large area of water surrounded by land.','We went swimming in the {lake}.','우리는 호수에서 수영했어요.','lake','A1','environment',1,'lake water nature reflection mountain'),
('w_environment_A1_25','mountain','/ˈmaʊntɪn/','noun','산','A large, high piece of land with steep sides.','The {mountain} was covered in snow.','산이 눈으로 덮여 있었어요.','mountain','A1','environment',1,'mountain peak snow landscape nature'),
('w_environment_A1_26','cloud','/klaʊd/','noun','구름','A white or grey mass of water vapour in the sky.','A dark {cloud} covered the sun.','검은 구름이 태양을 가렸어요.','cloud','A1','environment',1,'cloud sky weather white grey'),
('w_environment_A1_27','light','/laɪt/','noun','빛','The energy that makes things visible.','Sunlight is natural {light}.','햇빛은 자연 빛이에요.','light','A1','environment',1,'light sunlight bright nature energy'),
('w_environment_A1_28','dark','/dɑːrk/','adjective','어두운','With very little or no light.','It gets {dark} early in winter.','겨울에는 일찍 어두워져요.','dark','A1','environment',1,'dark night sky shadow nature'),
('w_environment_A1_29','hot','/hɒt/','adjective','더운','Having a high temperature.','It is very {hot} in summer.','여름에는 매우 더워요.','hot','A1','environment',1,'hot sun desert summer heat'),
('w_environment_A1_30','cold','/koʊld/','adjective','추운','Having a low temperature.','The water is very {cold} in winter.','겨울에는 물이 매우 차가워요.','cold','A1','environment',1,'cold winter ice snow frost'),
('w_environment_A1_31','ground','/ɡraʊnd/','noun','땅','The solid surface of the Earth.','Seeds grow under the {ground}.','씨앗은 땅 속에서 자라요.','ground','A1','environment',1,'ground soil earth nature field'),
('w_environment_A1_32','river','/ˈrɪvər/','noun','강','A large stream of water that flows to the sea.','We had a picnic by the {river}.','우리는 강가에서 소풍을 즐겼어요.','river','A1','environment',1,'river water stream nature landscape'),
('w_environment_A1_33','forest','/ˈfɔːrɪst/','noun','숲','A large area of land covered with trees.','The {forest} is full of wildlife.','숲에는 야생동물이 가득해요.','forest','A1','environment',1,'forest trees green nature wild'),
('w_environment_A1_34','soil','/sɔɪl/','noun','흙','The top layer of the earth in which plants grow.','Plants need healthy {soil} to grow.','식물이 자라려면 건강한 흙이 필요해요.','soil','A1','environment',1,'soil earth garden plant nature'),
('w_environment_A1_35','wet','/wɛt/','adjective','젖은','Covered with or containing liquid, especially water.','The {wet} ground smells fresh after rain.','비가 온 후 젖은 땅에서 신선한 냄새가 나요.','wet','A1','environment',1,'wet rain water puddle nature'),

-- ────────────────────────────────────────────────────────────
-- A2 (35 words)
-- ────────────────────────────────────────────────────────────
('w_environment_A2_01','recycle','/ˌriːˈsaɪkəl/','verb','재활용하다','To process used materials so they can be used again.','We should {recycle} our bottles and cans.','우리는 병과 캔을 재활용해야 해요.','recycle','A2','environment',1,'recycle bin waste green eco'),
('w_environment_A2_02','pollution','/pəˈluːʃən/','noun','오염','The presence of harmful substances in the environment.','Air {pollution} is bad for our lungs.','대기 오염은 폐에 나빠요.','pollution','A2','environment',1,'pollution smog city factory smoke'),
('w_environment_A2_03','energy','/ˈɛnərdʒi/','noun','에너지','The power from sources such as electricity or fuel.','We should save {energy} at home.','우리는 집에서 에너지를 아껴야 해요.','energy','A2','environment',1,'energy power electricity solar wind'),
('w_environment_A2_04','waste','/weɪst/','noun','쓰레기, 낭비','Materials that are no longer needed and thrown away.','Try not to create too much {waste}.','쓰레기를 너무 많이 만들지 않으려고 노력해요.','waste','A2','environment',1,'waste trash bin rubbish recycle'),
('w_environment_A2_05','solar','/ˈsoʊlər/','adjective','태양의','Relating to or coming from the sun.','{Solar} panels can power a whole house.','태양 전지판은 집 전체에 전력을 공급할 수 있어요.','solar','A2','environment',1,'solar panel sun energy roof'),
('w_environment_A2_06','protect','/prəˈtɛkt/','verb','보호하다','To keep someone or something safe from harm.','We need to {protect} our oceans.','우리는 바다를 보호해야 해요.','protect','A2','environment',1,'protect nature wildlife shield green'),
('w_environment_A2_07','reduce','/rɪˈdjuːs/','verb','줄이다','To make something smaller in size, amount, or degree.','Let''s {reduce} the amount of plastic we use.','플라스틱 사용량을 줄여요.','reduce','A2','environment',1,'reduce waste less eco lifestyle'),
('w_environment_A2_08','reuse','/ˌriːˈjuːz/','verb','재사용하다','To use something again.','I always {reuse} my shopping bags.','저는 항상 장바구니를 재사용해요.','reuse','A2','environment',1,'reuse bag bottle green eco'),
('w_environment_A2_09','plastic','/ˈplæstɪk/','noun','플라스틱','A light, strong material made from chemicals.','Avoid single-use {plastic} products.','일회용 플라스틱 제품을 피해요.','plastic','A2','environment',1,'plastic bottle bag pollution waste'),
('w_environment_A2_10','garbage','/ˈɡɑːrbɪdʒ/','noun','쓰레기','Things that are no longer useful and are thrown away.','Please put your {garbage} in the bin.','쓰레기를 통에 버려주세요.','garbage','A2','environment',1,'garbage trash bin rubbish waste'),
('w_environment_A2_11','electric','/ɪˈlɛktrɪk/','adjective','전기의','Powered by electricity.','An {electric} car produces no exhaust fumes.','전기차는 배기가스를 배출하지 않아요.','electric','A2','environment',1,'electric car vehicle green energy'),
('w_environment_A2_12','smoke','/smoʊk/','noun','연기','The grey or black gas produced when something burns.','Factory {smoke} pollutes the air.','공장 연기가 공기를 오염시켜요.','smoke','A2','environment',1,'smoke factory pollution air dark'),
('w_environment_A2_13','toxic','/ˈtɒksɪk/','adjective','유독한','Poisonous and harmful.','The factory released {toxic} chemicals into the river.','공장이 강에 유독한 화학물질을 방류했어요.','toxic','A2','environment',1,'toxic poison chemical waste danger'),
('w_environment_A2_14','litter','/ˈlɪtər/','verb','쓰레기를 버리다','To throw waste carelessly in a public place.','Please don''t {litter} in the park.','공원에 쓰레기를 버리지 마세요.','litter','A2','environment',1,'litter trash street pollution waste'),
('w_environment_A2_15','save','/seɪv/','verb','절약하다, 구하다','To keep something for future use or to prevent waste.','Remember to {save} water every day.','매일 물을 절약하는 걸 기억해요.','save','A2','environment',1,'save water energy eco green'),
('w_environment_A2_16','natural','/ˈnætʃərəl/','adjective','자연적인','Existing in or produced by nature.','Use {natural} cleaning products at home.','집에서 천연 세정제를 사용해요.','natural','A2','environment',1,'natural organic eco product green'),
('w_environment_A2_17','resource','/ˈriːsɔːrs/','noun','자원','Something available to use or be used for a purpose.','Water is a precious {resource}.','물은 소중한 자원이에요.','resource','A2','environment',1,'resource water energy land eco'),
('w_environment_A2_18','damage','/ˈdæmɪdʒ/','noun','피해, 손상','Physical harm that reduces value or usefulness.','Pollution causes serious {damage} to the environment.','오염은 환경에 심각한 피해를 줘요.','damage','A2','environment',1,'damage destruction pollution nature harm'),
('w_environment_A2_19','dirty','/ˈdɜːrti/','adjective','더러운','Not clean; containing or covered with harmful substances.','The river looks very {dirty} near the factory.','공장 근처의 강이 매우 더러워 보여요.','dirty','A2','environment',1,'dirty river pollution water waste'),
('w_environment_A2_20','plant','/plænt/','verb','심다','To put a seed or plant in the ground so it will grow.','Let''s {plant} more trees this weekend.','이번 주말에 나무를 더 심어요.','plant','A2','environment',1,'plant tree garden seed grow'),
('w_environment_A2_21','light bulb','/laɪt bʌlb/','noun','전구','A glass container that produces light when electricity passes through it.','Switch to LED {light bulbs} to save energy.','에너지 절약을 위해 LED 전구로 바꿔요.','light bulb','A2','environment',1,'light bulb LED energy saving electric'),
('w_environment_A2_22','tap','/tæp/','noun','수도꼭지','A device that controls the flow of liquid from a pipe.','Turn off the {tap} when brushing your teeth.','양치질할 때 수도꼭지를 잠가요.','tap','A2','environment',1,'tap water faucet sink save'),
('w_environment_A2_23','public transport','/ˈpʌblɪk ˈtrænspɔːrt/','noun','대중교통','Buses, trains, and other vehicles available to the public.','Use {public transport} to reduce pollution.','오염을 줄이기 위해 대중교통을 이용해요.','public transport','A2','environment',1,'public transport bus train green city'),
('w_environment_A2_24','beach','/biːtʃ/','noun','해변','An area of sand or small stones near the sea.','We cleaned up the {beach} last Sunday.','지난 일요일에 해변을 청소했어요.','beach','A2','environment',1,'beach clean ocean sand nature'),
('w_environment_A2_25','wildlife','/ˈwaɪldlaɪf/','noun','야생동물','Animals and plants living in their natural environment.','We must protect local {wildlife}.','지역 야생동물을 보호해야 해요.','wildlife','A2','environment',1,'wildlife animal nature habitat wild'),
('w_environment_A2_26','rubbish','/ˈrʌbɪʃ/','noun','쓰레기','Unwanted material or waste.','There is too much {rubbish} on the streets.','거리에 쓰레기가 너무 많아요.','rubbish','A2','environment',1,'rubbish trash bin waste street'),
('w_environment_A2_27','compost','/ˈkɒmpɒst/','noun','퇴비','Decayed plant and food waste used to improve soil.','I add food scraps to the {compost} bin.','음식물 쓰레기를 퇴비통에 넣어요.','compost','A2','environment',1,'compost soil garden organic eco'),
('w_environment_A2_28','flood','/flʌd/','noun','홍수','A large amount of water covering an area that is usually dry.','The {flood} damaged many homes.','홍수로 많은 집이 피해를 입었어요.','flood','A2','environment',1,'flood water disaster rain nature'),
('w_environment_A2_29','storm','/stɔːrm/','noun','폭풍','Severe weather with heavy rain, strong winds, and often thunder.','A big {storm} hit the coast last night.','어젯밤 해안에 큰 폭풍이 몰아쳤어요.','storm','A2','environment',1,'storm rain wind thunder weather'),
('w_environment_A2_30','temperature','/ˈtɛmprɪtʃər/','noun','온도','A measure of how hot or cold something is.','The {temperature} is rising every year.','온도가 매년 오르고 있어요.','temperature','A2','environment',1,'temperature thermometer heat climate global'),
('w_environment_A2_31','fresh','/frɛʃ/','adjective','신선한','Not containing harmful substances; clean and pure.','We need {fresh} air and clean water.','신선한 공기와 깨끗한 물이 필요해요.','fresh','A2','environment',1,'fresh air water clean nature green'),
('w_environment_A2_32','drought','/draʊt/','noun','가뭄','A long period with no rain.','The {drought} dried up the river completely.','가뭄으로 강이 완전히 말라버렸어요.','drought','A2','environment',1,'drought dry land cracked desert'),
('w_environment_A2_33','ocean','/ˈoʊʃən/','noun','해양','The large area of salt water covering most of the earth.','The {ocean} absorbs a lot of carbon dioxide.','해양은 이산화탄소를 많이 흡수해요.','ocean','A2','environment',1,'ocean sea water blue marine'),
('w_environment_A2_34','environment','/ɪnˈvaɪrənmənt/','noun','환경','The natural world in which people, animals, and plants live.','We must care for the {environment}.','우리는 환경을 돌봐야 해요.','environment','A2','environment',1,'environment nature earth green eco'),
('w_environment_A2_35','fuel','/fjuːəl/','noun','연료','A material that produces heat or energy when burned.','Cars burn {fuel} and release gases.','자동차는 연료를 태워 가스를 배출해요.','fuel','A2','environment',1,'fuel gas petrol car energy'),

-- ────────────────────────────────────────────────────────────
-- B1 (35 words)
-- ────────────────────────────────────────────────────────────
('w_environment_B1_01','climate change','/ˈklaɪmɪt tʃeɪndʒ/','noun phrase','기후 변화','Long-term shifts in global temperatures and weather patterns.','Scientists warn that {climate change} is accelerating.','과학자들은 기후 변화가 가속화되고 있다고 경고해요.','climate change','B1','environment',1,'climate change globe heat weather map'),
('w_environment_B1_02','carbon','/ˈkɑːrbən/','noun','탄소','A chemical element that is found in all living things.','We need to cut our {carbon} emissions.','우리는 탄소 배출량을 줄여야 해요.','carbon','B1','environment',1,'carbon molecule element chemistry eco'),
('w_environment_B1_03','emission','/ɪˈmɪʃən/','noun','배출(량)','Gases or other substances released into the air.','Car {emissions} are a major source of pollution.','자동차 배출가스는 주요 오염원이에요.','emission','B1','environment',1,'emission exhaust gas factory smoke'),
('w_environment_B1_04','sustainable','/səˈsteɪnəbəl/','adjective','지속 가능한','Able to be maintained without harming the environment.','We need {sustainable} farming practices.','우리는 지속 가능한 농업 방식이 필요해요.','sustainable','B1','environment',1,'sustainable farm eco green agriculture'),
('w_environment_B1_05','renewable','/rɪˈnjuːəbəl/','adjective','재생 가능한','Coming from a source that will not run out.','Wind power is a {renewable} energy source.','풍력은 재생 가능한 에너지원이에요.','renewable','B1','environment',1,'renewable wind solar energy turbine'),
('w_environment_B1_06','ecosystem','/ˈiːkoʊsɪstəm/','noun','생태계','A community of living organisms and their environment.','The rainforest {ecosystem} is very complex.','열대우림 생태계는 매우 복잡해요.','ecosystem','B1','environment',1,'ecosystem forest wildlife nature complex'),
('w_environment_B1_07','biodiversity','/ˌbaɪoʊdaɪˈvɜːrsɪti/','noun','생물 다양성','The variety of plant and animal life in a habitat.','Protecting {biodiversity} is vital for ecosystems.','생물 다양성 보호는 생태계에 필수적이에요.','biodiversity','B1','environment',1,'biodiversity species animals plants rainforest'),
('w_environment_B1_08','habitat','/ˈhæbɪtæt/','noun','서식지','The natural environment where an organism lives.','Urban expansion destroys animal {habitats}.','도시 확장이 동물 서식지를 파괴해요.','habitat','B1','environment',1,'habitat wildlife forest nature animal'),
('w_environment_B1_09','conservation','/ˌkɒnsəˈveɪʃən/','noun','보전','The protection and management of natural resources.','Wildlife {conservation} is everyone''s responsibility.','야생동물 보전은 모두의 책임이에요.','conservation','B1','environment',1,'conservation wildlife nature protect eco'),
('w_environment_B1_10','deforestation','/diːˌfɒrɪˈsteɪʃən/','noun','삼림 벌채','The process of clearing forests for land use.','{Deforestation} in the Amazon affects the global climate.','아마존 삼림 벌채는 전 세계 기후에 영향을 미쳐요.','deforestation','B1','environment',1,'deforestation logging forest cut land'),
('w_environment_B1_11','greenhouse gas','/ˈɡriːnhaʊs ɡæs/','noun phrase','온실가스','A gas that traps heat in the Earth''s atmosphere.','CO2 is the most common {greenhouse gas}.','이산화탄소는 가장 흔한 온실가스예요.','greenhouse gas','B1','environment',1,'greenhouse gas CO2 atmosphere heat globe'),
('w_environment_B1_12','global warming','/ˌɡloʊbəl ˈwɔːrmɪŋ/','noun phrase','지구 온난화','The gradual increase of the Earth''s average temperature.','{Global warming} is melting Arctic ice.','지구 온난화로 북극 얼음이 녹고 있어요.','global warming','B1','environment',1,'global warming ice melt Arctic temperature'),
('w_environment_B1_13','carbon dioxide','/ˈkɑːrbən daɪˈɒksaɪd/','noun phrase','이산화탄소','A gas produced by burning fuels and by breathing.','Forests absorb {carbon dioxide} from the air.','숲은 공기 중 이산화탄소를 흡수해요.','carbon dioxide','B1','environment',1,'carbon dioxide CO2 gas atmosphere nature'),
('w_environment_B1_14','renewable energy','/rɪˈnjuːəbəl ˈɛnərdʒi/','noun phrase','재생에너지','Energy from sources that are naturally replenished.','Investing in {renewable energy} is crucial.','재생에너지에 투자하는 것이 중요해요.','renewable energy','B1','environment',1,'renewable energy solar wind turbine green'),
('w_environment_B1_15','carbon footprint','/ˈkɑːrbən ˈfʊtprɪnt/','noun phrase','탄소 발자국','The total amount of CO2 produced by a person or activity.','Flying increases your {carbon footprint}.','비행기를 타면 탄소 발자국이 늘어나요.','carbon footprint','B1','environment',1,'carbon footprint CO2 lifestyle travel eco'),
('w_environment_B1_16','species','/ˈspiːʃiːz/','noun','종(種)','A group of animals or plants with similar characteristics.','Many {species} are facing extinction.','많은 종이 멸종 위기에 처해 있어요.','species','B1','environment',1,'species animal plant nature biodiversity'),
('w_environment_B1_17','endangered','/ɪnˈdeɪndʒərd/','adjective','멸종 위기의','At risk of no longer existing.','The tiger is an {endangered} animal.','호랑이는 멸종 위기 동물이에요.','endangered','B1','environment',1,'endangered tiger wildlife protect conservation'),
('w_environment_B1_18','solar panel','/ˈsoʊlər ˈpænəl/','noun phrase','태양 전지판','A device that converts sunlight into electricity.','The school installed {solar panels} on the roof.','학교 지붕에 태양 전지판을 설치했어요.','solar panel','B1','environment',1,'solar panel roof energy house green'),
('w_environment_B1_19','wind turbine','/wɪnd ˈtɜːrbaɪn/','noun phrase','풍력 발전기','A machine that converts wind energy into electricity.','The coast is lined with {wind turbines}.','해안을 따라 풍력 발전기가 늘어서 있어요.','wind turbine','B1','environment',1,'wind turbine energy coast farm green'),
('w_environment_B1_20','fossil fuel','/ˈfɒsəl fjuːəl/','noun phrase','화석 연료','Coal, oil, and gas formed from ancient organisms.','We must reduce our use of {fossil fuels}.','화석 연료 사용을 줄여야 해요.','fossil fuel','B1','environment',1,'fossil fuel coal oil gas energy'),
('w_environment_B1_21','iceberg','/ˈaɪsbɜːrɡ/','noun','빙산','A large floating mass of ice in the sea.','Rising temperatures are melting {icebergs}.','기온 상승으로 빙산이 녹고 있어요.','iceberg','B1','environment',1,'iceberg arctic ocean ice melt'),
('w_environment_B1_22','melt','/mɛlt/','verb','녹다','To change from solid to liquid because of heat.','Glaciers are {melting} faster than ever.','빙하가 그 어느 때보다 빠르게 녹고 있어요.','melt','B1','environment',1,'melt ice glacier water arctic'),
('w_environment_B1_23','atmosphere','/ˈætməsfɪər/','noun','대기','The layer of gases surrounding the Earth.','Greenhouse gases are heating the {atmosphere}.','온실가스가 대기를 가열하고 있어요.','atmosphere','B1','environment',1,'atmosphere earth sky gas layer'),
('w_environment_B1_24','organic','/ɔːrˈɡænɪk/','adjective','유기농의','Produced without artificial chemicals.','I prefer to buy {organic} food.','저는 유기농 식품을 사는 걸 선호해요.','organic','B1','environment',1,'organic food farm natural green eco'),
('w_environment_B1_25','landfill','/ˈlændfɪl/','noun','매립지','A place where waste is buried in the ground.','Most plastic ends up in a {landfill}.','대부분의 플라스틱은 매립지에 가게 돼요.','landfill','B1','environment',1,'landfill waste trash dump pollution'),
('w_environment_B1_26','ozone layer','/ˈoʊzoʊn ˈleɪər/','noun phrase','오존층','A layer in the stratosphere that absorbs UV radiation.','We must protect the {ozone layer}.','오존층을 보호해야 해요.','ozone layer','B1','environment',1,'ozone layer atmosphere UV protection sky'),
('w_environment_B1_27','coral reef','/ˈkɒrəl riːf/','noun phrase','산호초','An underwater ecosystem built from coral.','The {coral reef} is bleaching due to warm water.','따뜻해진 바다로 인해 산호초가 백화현상을 겪고 있어요.','coral reef','B1','environment',1,'coral reef ocean marine underwater color'),
('w_environment_B1_28','sea level','/siː ˈlɛvəl/','noun phrase','해수면','The average height of the sea.','Rising {sea levels} threaten coastal cities.','해수면 상승이 해안 도시들을 위협해요.','sea level','B1','environment',1,'sea level ocean coast flood city'),
('w_environment_B1_29','glacier','/ˈɡleɪʃər/','noun','빙하','A slowly moving mass of ice.','The {glacier} has retreated significantly.','빙하가 크게 후퇴했어요.','glacier','B1','environment',1,'glacier ice mountain arctic melt'),
('w_environment_B1_30','reforestation','/ˌriːfɒrɪˈsteɪʃən/','noun','재조림','The process of planting trees in areas that have lost forest.','{Reforestation} can help reduce CO2 levels.','재조림은 이산화탄소 수치를 줄이는 데 도움이 될 수 있어요.','reforestation','B1','environment',1,'reforestation tree plant forest green'),
('w_environment_B1_31','acid rain','/ˈæsɪd reɪn/','noun phrase','산성비','Rain that contains harmful chemicals from pollution.','{Acid rain} damages forests and buildings.','산성비는 숲과 건물을 손상시켜요.','acid rain','B1','environment',1,'acid rain pollution forest damage water'),
('w_environment_B1_32','pesticide','/ˈpɛstɪsaɪd/','noun','살충제','A chemical used to kill insects that damage crops.','Overusing {pesticides} harms soil health.','살충제를 과도하게 사용하면 토양 건강이 나빠져요.','pesticide','B1','environment',1,'pesticide farm crop chemical green'),
('w_environment_B1_33','water cycle','/ˈwɔːtər ˈsaɪkəl/','noun phrase','물의 순환','The continuous movement of water through the environment.','The {water cycle} distributes freshwater around Earth.','물의 순환은 지구 전체에 민물을 공급해요.','water cycle','B1','environment',1,'water cycle rain evaporation cloud nature'),
('w_environment_B1_34','overpopulation','/ˌoʊvərˌpɒpjʊˈleɪʃən/','noun','과잉 인구','The condition of having too many people for available resources.','{Overpopulation} puts pressure on natural resources.','과잉 인구는 천연자원에 압박을 가해요.','overpopulation','B1','environment',1,'overpopulation city crowd resource pressure'),
('w_environment_B1_35','carbon neutral','/ˈkɑːrbən ˈnjuːtrəl/','adjective','탄소 중립의','Producing no net release of carbon dioxide.','The company aims to be {carbon neutral} by 2030.','그 회사는 2030년까지 탄소 중립을 목표로 해요.','carbon neutral','B1','environment',1,'carbon neutral eco zero emission green'),

-- ────────────────────────────────────────────────────────────
-- B2 (35 words)
-- ────────────────────────────────────────────────────────────
('w_environment_B2_01','mitigation','/ˌmɪtɪˈɡeɪʃən/','noun','완화','Actions taken to reduce the severity of climate change.','{Mitigation} strategies include reducing CO2 emissions.','완화 전략에는 이산화탄소 배출 감축이 포함돼요.','mitigation','B2','environment',1,'mitigation climate policy strategy eco'),
('w_environment_B2_02','adaptation','/ˌædæpˈteɪʃən/','noun','적응','The process of adjusting to changes in the environment.','Coastal {adaptation} plans protect against flooding.','해안 적응 계획은 홍수로부터 보호해줘요.','adaptation','B2','environment',1,'adaptation flood coast plan resilience'),
('w_environment_B2_03','desertification','/dɪˌzɜːrtɪfɪˈkeɪʃən/','noun','사막화','The process by which fertile land turns into desert.','{Desertification} threatens food security in Africa.','사막화는 아프리카의 식량 안보를 위협해요.','desertification','B2','environment',1,'desertification desert dry land erosion'),
('w_environment_B2_04','ozone depletion','/ˈoʊzoʊn dɪˈpliːʃən/','noun phrase','오존층 파괴','The thinning of the Earth''s ozone layer.','{Ozone depletion} allows more UV radiation to reach Earth.','오존층 파괴로 더 많은 자외선이 지구에 도달해요.','ozone depletion','B2','environment',1,'ozone depletion UV atmosphere layer'),
('w_environment_B2_05','toxin','/ˈtɒksɪn/','noun','독소','A poisonous substance produced by organisms or human activity.','Industrial {toxins} pollute waterways.','산업 독소가 수로를 오염시켜요.','toxin','B2','environment',1,'toxin poison chemical water pollution'),
('w_environment_B2_06','greenhouse effect','/ˈɡriːnhaʊs ɪˈfɛkt/','noun phrase','온실 효과','The trapping of heat in the atmosphere by greenhouse gases.','The {greenhouse effect} is intensifying due to CO2.','이산화탄소로 인해 온실 효과가 심화되고 있어요.','greenhouse effect','B2','environment',1,'greenhouse effect heat atmosphere CO2 globe'),
('w_environment_B2_07','biodegradable','/ˌbaɪoʊdɪˈɡreɪdəbəl/','adjective','생분해되는','Able to be broken down naturally by bacteria or fungi.','Choose {biodegradable} packaging to reduce waste.','쓰레기를 줄이기 위해 생분해 포장재를 선택해요.','biodegradable','B2','environment',1,'biodegradable packaging eco green waste'),
('w_environment_B2_08','particulate matter','/pɑːrˈtɪkjʊlɪt ˈmætər/','noun phrase','미세먼지','Tiny particles in the air that can harm human health.','{Particulate matter} from vehicles causes respiratory disease.','차량에서 나오는 미세먼지는 호흡기 질환을 일으켜요.','particulate matter','B2','environment',1,'particulate matter smog air pollution health'),
('w_environment_B2_09','ecological','/ˌiːkəˈlɒdʒɪkəl/','adjective','생태학적','Relating to the relationship between organisms and their environment.','The spill had a severe {ecological} impact.','기름 유출은 심각한 생태학적 영향을 미쳤어요.','ecological','B2','environment',1,'ecological nature ecosystem impact science'),
('w_environment_B2_10','sustainable development','/səˈsteɪnəbəl dɪˈvɛləpmənt/','noun phrase','지속 가능한 개발','Development that meets present needs without harming future generations.','{Sustainable development} balances economy and ecology.','지속 가능한 개발은 경제와 생태를 균형 있게 유지해요.','sustainable development','B2','environment',1,'sustainable development eco policy growth green'),
('w_environment_B2_11','carbon sequestration','/ˈkɑːrbən ˌsɛkwɪˈstreɪʃən/','noun phrase','탄소 격리','The process of capturing and storing carbon dioxide.','Forests are natural {carbon sequestration} systems.','숲은 자연적인 탄소 격리 시스템이에요.','carbon sequestration','B2','environment',1,'carbon sequestration forest storage CO2 eco'),
('w_environment_B2_12','bioaccumulation','/ˌbaɪoʊəˌkjuːmjʊˈleɪʃən/','noun','생물 농축','The gradual buildup of substances in an organism.','{Bioaccumulation} of mercury is dangerous for fish and humans.','수은의 생물 농축은 물고기와 인간에게 위험해요.','bioaccumulation','B2','environment',1,'bioaccumulation mercury fish water toxin'),
('w_environment_B2_13','wetland','/ˈwɛtlænd/','noun','습지','Land that is saturated with water for most of the year.','{Wetlands} filter water and support wildlife.','습지는 물을 걸러내고 야생동물을 부양해요.','wetland','B2','environment',1,'wetland water nature bird habitat'),
('w_environment_B2_14','methane','/ˈmɛθeɪn/','noun','메탄','A powerful greenhouse gas released by livestock and landfills.','{Methane} is a potent contributor to global warming.','메탄은 지구 온난화의 강력한 원인이에요.','methane','B2','environment',1,'methane gas greenhouse cow landfill'),
('w_environment_B2_15','marine pollution','/məˈriːn pəˈluːʃən/','noun phrase','해양 오염','The contamination of the sea with harmful substances.','{Marine pollution} kills thousands of sea creatures annually.','해양 오염으로 매년 수천 마리의 해양 생물이 죽어요.','marine pollution','B2','environment',1,'marine pollution ocean plastic waste sea'),
('w_environment_B2_16','carbon tax','/ˈkɑːrbən tæks/','noun phrase','탄소세','A tax on greenhouse gas emissions to discourage fossil fuel use.','A {carbon tax} incentivises businesses to go green.','탄소세는 기업들이 친환경으로 전환하도록 유도해요.','carbon tax','B2','environment',1,'carbon tax policy money eco government'),
('w_environment_B2_17','deforestation rate','/diːˌfɒrɪˈsteɪʃən reɪt/','noun phrase','삼림 파괴 속도','The speed at which forest cover is being removed.','The {deforestation rate} in the tropics is alarming.','열대 지방의 삼림 파괴 속도는 충격적이에요.','deforestation rate','B2','environment',1,'deforestation logging forest chart data'),
('w_environment_B2_18','habitat loss','/ˈhæbɪtæt lɒs/','noun phrase','서식지 손실','The destruction of environments where animals and plants live.','{Habitat loss} is the leading cause of species extinction.','서식지 손실은 종 멸종의 주요 원인이에요.','habitat loss','B2','environment',1,'habitat loss wildlife forest animal extinction'),
('w_environment_B2_19','invasive species','/ɪnˈveɪsɪv ˈspiːʃiːz/','noun phrase','외래종','Non-native species that damage ecosystems.','{Invasive species} can outcompete native wildlife.','외래종은 토착 야생동물과의 경쟁에서 이길 수 있어요.','invasive species','B2','environment',1,'invasive species plant animal ecosystem damage'),
('w_environment_B2_20','net zero','/nɛt ˈzɪərəʊ/','noun phrase','넷제로','Achieving a balance between emissions produced and removed.','Many governments have pledged to reach {net zero}.','많은 정부가 넷제로를 달성하겠다고 서약했어요.','net zero','B2','environment',1,'net zero carbon policy government eco'),
('w_environment_B2_21','plastic waste','/ˈplæstɪk weɪst/','noun phrase','플라스틱 쓰레기','Discarded plastic products that pollute the environment.','{Plastic waste} is choking our oceans.','플라스틱 쓰레기가 우리 바다를 망가뜨리고 있어요.','plastic waste','B2','environment',1,'plastic waste ocean pollution sea trash'),
('w_environment_B2_22','agroforestry','/ˌæɡroʊˈfɒrɪstri/','noun','농림업','A land use system combining trees with crops or livestock.','{Agroforestry} improves biodiversity and soil health.','농림업은 생물 다양성과 토양 건강을 향상시켜요.','agroforestry','B2','environment',1,'agroforestry tree farm crop eco'),
('w_environment_B2_23','eutrophication','/juːˌtrɒfɪˈkeɪʃən/','noun','부영양화','Excess nutrients causing algae growth in water.','{Eutrophication} depletes oxygen and kills aquatic life.','부영양화는 산소를 고갈시키고 수생 생물을 죽여요.','eutrophication','B2','environment',1,'eutrophication algae water nutrient lake'),
('w_environment_B2_24','atmospheric','/ˌætməsˈfɛrɪk/','adjective','대기의','Relating to the atmosphere.','{Atmospheric} CO2 levels have risen sharply.','대기 이산화탄소 수치가 급격히 상승했어요.','atmospheric','B2','environment',1,'atmospheric CO2 layer science data'),
('w_environment_B2_25','renewable portfolio','/rɪˈnjuːəbəl pɔːrtˈfoʊlioʊ/','noun phrase','재생에너지 포트폴리오','A mix of different renewable energy sources.','The utility expanded its {renewable portfolio}.','그 전력 회사는 재생에너지 포트폴리오를 확대했어요.','renewable portfolio','B2','environment',1,'renewable portfolio energy solar wind power'),
('w_environment_B2_26','permafrost','/ˈpɜːrməfrɒst/','noun','영구 동토층','Ground that stays frozen throughout the year.','Thawing {permafrost} releases methane into the air.','영구 동토층이 녹으면 메탄이 공기 중으로 방출돼요.','permafrost','B2','environment',1,'permafrost frozen ground arctic tundra'),
('w_environment_B2_27','smog','/smɒɡ/','noun','스모그','Thick, dark fog caused by air pollution.','{Smog} makes breathing difficult in some cities.','스모그는 일부 도시에서 호흡을 어렵게 만들어요.','smog','B2','environment',1,'smog city pollution air grey health'),
('w_environment_B2_28','biome','/ˈbaɪoʊm/','noun','생물군계','A large community of plants and animals in a specific region.','The Arctic {biome} is extremely vulnerable.','북극 생물군계는 매우 취약해요.','biome','B2','environment',1,'biome arctic desert forest nature map'),
('w_environment_B2_29','runoff','/ˈrʌnɒf/','noun','유출수','Water from rain or melting snow that flows into rivers.','Agricultural {runoff} carries pesticides into waterways.','농업 유출수는 살충제를 수로로 운반해요.','runoff','B2','environment',1,'runoff water farm river pollution nature'),
('w_environment_B2_30','biomass','/ˈbaɪoʊmæs/','noun','바이오매스','Organic material used as a renewable energy source.','{Biomass} can be converted into biofuel.','바이오매스는 바이오연료로 전환될 수 있어요.','biomass','B2','environment',1,'biomass organic energy plant fuel'),
('w_environment_B2_31','water scarcity','/ˈwɔːtər ˈskeərsɪti/','noun phrase','물 부족','The lack of sufficient access to clean water.','{Water scarcity} affects billions of people worldwide.','물 부족은 전 세계 수십억 명에게 영향을 미쳐요.','water scarcity','B2','environment',1,'water scarcity drought desert crisis global'),
('w_environment_B2_32','food security','/fuːd sɪˈkjʊərɪti/','noun phrase','식량 안보','The ability to have consistent access to sufficient food.','{Food security} is threatened by extreme weather events.','식량 안보는 극단적 기상 현상으로 위협받고 있어요.','food security','B2','environment',1,'food security farm crop drought map'),
('w_environment_B2_33','microplastic','/ˌmaɪkrəʊˈplæstɪk/','noun','미세플라스틱','Tiny plastic particles found in water, soil, and food.','{Microplastics} have been found in human blood.','미세플라스틱이 인간의 혈액에서도 발견됐어요.','microplastic','B2','environment',1,'microplastic ocean water food health pollution'),
('w_environment_B2_34','rewilding','/ˌriːˈwaɪldɪŋ/','noun','야생 복원','The process of restoring natural ecosystems and wildlife.','{Rewilding} projects have reintroduced wolves to national parks.','야생 복원 프로젝트가 국립공원에 늑대를 재도입했어요.','rewilding','B2','environment',1,'rewilding wolf nature forest restore ecosystem'),
('w_environment_B2_35','emission trading','/ɪˈmɪʃən ˈtreɪdɪŋ/','noun phrase','배출권 거래','A market-based system for reducing greenhouse gas emissions.','{Emission trading} creates economic incentives to cut CO2.','배출권 거래는 이산화탄소 감축에 경제적 유인을 만들어요.','emission trading','B2','environment',1,'emission trading market carbon policy eco'),

-- ────────────────────────────────────────────────────────────
-- C1 (35 words)
-- ────────────────────────────────────────────────────────────
('w_environment_C1_01','anthropogenic','/ˌænθrəpəˈdʒɛnɪk/','adjective','인위적인','Caused or produced by human activity.','{Anthropogenic} emissions are the main driver of climate change.','인위적 배출이 기후 변화의 주요 원인이에요.','anthropogenic','C1','environment',1,'anthropogenic human factory emission globe'),
('w_environment_C1_02','biogeochemical','/ˌbaɪoʊˌdʒiːoʊˈkɛmɪkəl/','adjective','생물지구화학적','Relating to chemical cycling through biological and geological systems.','{Biogeochemical} cycles regulate Earth''s climate.','생물지구화학적 순환이 지구의 기후를 조절해요.','biogeochemical','C1','environment',1,'biogeochemical cycle earth science nature'),
('w_environment_C1_03','paleoclimatology','/ˌpeɪlioʊˌklaɪməˈtɒlədʒi/','noun','고기후학','The study of past climates using geological evidence.','{Paleoclimatology} reveals how Earth''s climate has varied.','고기후학은 지구 기후가 어떻게 변화해왔는지 밝혀요.','paleoclimatology','C1','environment',1,'paleoclimatology ice core data science past'),
('w_environment_C1_04','decarbonization','/diːˌkɑːrbənaɪˈzeɪʃən/','noun','탈탄소화','The process of reducing carbon dioxide emissions.','{Decarbonization} of industry is essential for climate targets.','산업의 탈탄소화는 기후 목표 달성에 필수적이에요.','decarbonization','C1','environment',1,'decarbonization factory energy green policy'),
('w_environment_C1_05','geoengineering','/ˌdʒiːoʊˌɛndʒɪˈnɪərɪŋ/','noun','지구공학','Large-scale technological intervention in Earth''s natural systems.','{Geoengineering} proposals include injecting aerosols into the stratosphere.','지구공학 제안에는 성층권에 에어로졸을 주입하는 방법이 포함돼요.','geoengineering','C1','environment',1,'geoengineering technology atmosphere science sky'),
('w_environment_C1_06','biosphere','/ˈbaɪoʊsfɪər/','noun','생물권','The regions of Earth where living organisms exist.','Climate change threatens the entire {biosphere}.','기후 변화는 전체 생물권을 위협해요.','biosphere','C1','environment',1,'biosphere earth life nature layer globe'),
('w_environment_C1_07','ecological resilience','/ˌiːkəˈlɒdʒɪkəl rɪˈzɪlɪəns/','noun phrase','생태적 복원력','The capacity of an ecosystem to recover from disturbances.','{Ecological resilience} decreases as biodiversity is lost.','생물 다양성이 줄어들면 생태적 복원력도 감소해요.','ecological resilience','C1','environment',1,'ecological resilience ecosystem recovery nature'),
('w_environment_C1_08','trophic cascade','/ˈtrɒfɪk kæˈskeɪd/','noun phrase','영양 단계 연쇄반응','A series of changes in an ecosystem caused by predator removal.','Wolf reintroduction triggered a {trophic cascade} in Yellowstone.','늑대 재도입이 옐로스톤에서 영양 단계 연쇄반응을 일으켰어요.','trophic cascade','C1','environment',1,'trophic cascade ecosystem predator wolf nature'),
('w_environment_C1_09','carbon sink','/ˈkɑːrbən sɪŋk/','noun phrase','탄소 흡수원','A natural system that absorbs more CO2 than it releases.','Oceans act as a major {carbon sink}.','바다는 주요 탄소 흡수원 역할을 해요.','carbon sink','C1','environment',1,'carbon sink ocean forest CO2 absorb'),
('w_environment_C1_10','keystone species','/ˈkiːstoʊn ˈspiːʃiːz/','noun phrase','핵심종','A species that has a disproportionate effect on its ecosystem.','The sea otter is a {keystone species} in kelp forests.','해달은 켈프 숲의 핵심종이에요.','keystone species','C1','environment',1,'keystone species ecosystem otter kelp ocean'),
('w_environment_C1_11','albedo','/ælˈbiːdoʊ/','noun','알베도','The proportion of light reflected by a surface.','Snow has a high {albedo}, reflecting sunlight back.','눈은 알베도가 높아 햇빛을 반사해요.','albedo','C1','environment',1,'albedo snow ice reflect sunlight science'),
('w_environment_C1_12','phenology','/fɪˈnɒlədʒi/','noun','계절학','The study of cyclic and seasonal natural phenomena.','{Phenology} records show earlier spring flowering.','계절학 기록에 따르면 봄꽃이 더 일찍 피고 있어요.','phenology','C1','environment',1,'phenology flower spring season nature data'),
('w_environment_C1_13','remediation','/rɪˌmiːdiˈeɪʃən/','noun','정화, 복구','The process of reversing or stopping environmental damage.','Soil {remediation} removed heavy metals from the site.','토양 정화를 통해 그 부지에서 중금속을 제거했어요.','remediation','C1','environment',1,'remediation soil clean pollution technology'),
('w_environment_C1_14','ecosystem services','/ˈiːkoʊsɪstəm ˈsɜːrvɪsɪz/','noun phrase','생태계 서비스','The benefits that ecosystems provide to humans.','{Ecosystem services} include clean air, water, and food.','생태계 서비스에는 깨끗한 공기, 물, 식량이 포함돼요.','ecosystem services','C1','environment',1,'ecosystem services nature benefit food water'),
('w_environment_C1_15','stratospheric','/ˌstrætəˈsfɛrɪk/','adjective','성층권의','Relating to the stratosphere, the layer of atmosphere above the troposphere.','{Stratospheric} aerosols can cool the Earth temporarily.','성층권 에어로졸은 일시적으로 지구를 냉각시킬 수 있어요.','stratospheric','C1','environment',1,'stratospheric atmosphere layer aerosol science'),
('w_environment_C1_16','nutrient cycle','/ˈnjuːtriənt ˈsaɪkəl/','noun phrase','영양 순환','The movement of chemical nutrients through ecosystems.','Decomposers are essential to the {nutrient cycle}.','분해자는 영양 순환에 필수적이에요.','nutrient cycle','C1','environment',1,'nutrient cycle decompose soil nature science'),
('w_environment_C1_17','phytoplankton','/ˌfaɪtoʊˈplæŋktən/','noun','식물성 플랑크톤','Microscopic plants in water that produce oxygen through photosynthesis.','{Phytoplankton} generate about half of Earth''s oxygen.','식물성 플랑크톤은 지구 산소의 약 절반을 만들어요.','phytoplankton','C1','environment',1,'phytoplankton ocean microscope water nature'),
('w_environment_C1_18','ecocide','/ˈiːkoʊsaɪd/','noun','생태계 파괴','The destruction of an ecosystem, sometimes considered a crime.','{Ecocide} laws are being debated internationally.','에코사이드법이 국제적으로 논의되고 있어요.','ecocide','C1','environment',1,'ecocide destruction pollution law environment'),
('w_environment_C1_19','biochar','/ˈbaɪoʊtʃɑːr/','noun','바이오차','Charcoal used as a soil amendment and carbon store.','{Biochar} can improve soil fertility and sequester carbon.','바이오차는 토양 비옥도를 높이고 탄소를 격리할 수 있어요.','biochar','C1','environment',1,'biochar soil carbon farm eco charcoal'),
('w_environment_C1_20','lithostratigraphy','/ˌlɪθoʊstrəˈtɪɡrəfi/','noun','암층서학','The study of rock layers to understand Earth''s history.','{Lithostratigraphy} helps reconstruct past climate conditions.','암층서학은 과거 기후 조건을 재구성하는 데 도움이 돼요.','lithostratigraphy','C1','environment',1,'lithostratigraphy rock layer geology science history'),
('w_environment_C1_21','endocrine disruptor','/ˈɛndoʊkraɪn dɪsˈrʌptər/','noun phrase','내분비 교란물질','A chemical that interferes with hormonal systems.','{Endocrine disruptors} are found in many plastics.','내분비 교란물질은 많은 플라스틱에서 발견돼요.','endocrine disruptor','C1','environment',1,'endocrine disruptor chemical plastic health hormone'),
('w_environment_C1_22','transboundary pollution','/trænzˈbaʊndəri pəˈluːʃən/','noun phrase','국경을 넘는 오염','Pollution that moves across national borders.','{Transboundary pollution} requires international cooperation to address.','국경을 넘는 오염 문제는 국제 협력이 필요해요.','transboundary pollution','C1','environment',1,'transboundary pollution border international air water'),
('w_environment_C1_23','cradle-to-grave','/ˈkreɪdəl tə ɡreɪv/','adjective','요람에서 무덤까지','Relating to the full life cycle of a product.','We need {cradle-to-grave} analysis of product emissions.','제품 배출량의 전 생애주기 분석이 필요해요.','cradle-to-grave','C1','environment',1,'cradle-to-grave lifecycle product eco analysis'),
('w_environment_C1_24','cryosphere','/ˈkraɪoʊsfɪər/','noun','빙권','The parts of Earth''s surface where water is frozen.','The {cryosphere} is shrinking due to warming temperatures.','기온 상승으로 빙권이 줄어들고 있어요.','cryosphere','C1','environment',1,'cryosphere ice arctic glacier frozen earth'),
('w_environment_C1_25','urban heat island','/ˈɜːrbən hiːt ˈaɪlənd/','noun phrase','도시 열섬 현상','The phenomenon where cities are warmer than surrounding areas.','{Urban heat islands} increase energy use for cooling.','도시 열섬 현상은 냉방을 위한 에너지 사용을 늘려요.','urban heat island','C1','environment',1,'urban heat island city temperature map heat'),
('w_environment_C1_26','precautionary principle','/prɪˈkɔːʃənəri ˈprɪnsɪpəl/','noun phrase','사전 예방 원칙','Taking preventive action in the face of scientific uncertainty.','The EU applies the {precautionary principle} to new chemicals.','EU는 신규 화학물질에 사전 예방 원칙을 적용해요.','precautionary principle','C1','environment',1,'precautionary principle policy law eco science'),
('w_environment_C1_27','phytoremediation','/ˌfaɪtoʊrɪˌmiːdiˈeɪʃən/','noun','식물 정화','Using plants to remove pollutants from soil or water.','{Phytoremediation} is a cost-effective way to clean contaminated land.','식물 정화는 오염된 토지를 정화하는 비용 효율적 방법이에요.','phytoremediation','C1','environment',1,'phytoremediation plant soil clean pollution green'),
('w_environment_C1_28','bioremediation','/ˌbaɪoʊrɪˌmiːdiˈeɪʃən/','noun','생물학적 정화','Using microorganisms to break down pollutants.','{Bioremediation} can clean up oil spills in the ocean.','생물학적 정화는 해양 기름 유출을 정화할 수 있어요.','bioremediation','C1','environment',1,'bioremediation bacteria soil clean oil nature'),
('w_environment_C1_29','ecological footprint','/ˌiːkəˈlɒdʒɪkəl ˈfʊtprɪnt/','noun phrase','생태 발자국','The demand placed on Earth''s resources by human activities.','Reducing your {ecological footprint} helps the planet.','생태 발자국을 줄이면 지구에 도움이 돼요.','ecological footprint','C1','environment',1,'ecological footprint earth resource lifestyle eco'),
('w_environment_C1_30','planetary health','/ˈplænɪtɛri hɛlθ/','noun phrase','지구 건강','The health of human civilization and the natural systems it depends on.','{Planetary health} links human wellbeing to Earth''s ecosystems.','지구 건강은 인간의 웰빙과 지구 생태계를 연결해요.','planetary health','C1','environment',1,'planetary health earth ecosystem human wellbeing'),
('w_environment_C1_31','atmospheric river','/ˌætməsˈfɛrɪk ˈrɪvər/','noun phrase','대기의 강','A narrow band of concentrated water vapour in the atmosphere.','{Atmospheric rivers} can deliver extreme rainfall events.','대기의 강은 극단적인 강우 현상을 일으킬 수 있어요.','atmospheric river','C1','environment',1,'atmospheric river rain cloud weather forecast'),
('w_environment_C1_32','carbon budget','/ˈkɑːrbən ˈbʌdʒɪt/','noun phrase','탄소 예산','The maximum amount of CO2 that can be emitted while limiting warming.','We have almost exhausted the global {carbon budget}.','우리는 전 지구적 탄소 예산을 거의 다 소진했어요.','carbon budget','C1','environment',1,'carbon budget CO2 policy limit climate'),
('w_environment_C1_33','deep ecology','/diːp ɪˈkɒlədʒi/','noun phrase','심층 생태학','A philosophy that all life has intrinsic value regardless of human utility.','{Deep ecology} challenges human-centred views of nature.','심층 생태학은 자연에 대한 인간 중심적 관점에 도전해요.','deep ecology','C1','environment',1,'deep ecology philosophy nature value human'),
('w_environment_C1_34','ocean acidification','/ˈoʊʃən əˌsɪdɪfɪˈkeɪʃən/','noun phrase','해양 산성화','The decrease in the pH of the ocean due to CO2 absorption.','{Ocean acidification} harms shell-forming marine organisms.','해양 산성화는 껍데기를 형성하는 해양 생물에게 해를 끼쳐요.','ocean acidification','C1','environment',1,'ocean acidification pH coral shell marine'),
('w_environment_C1_35','solar radiation management','/ˈsoʊlər ˌreɪdiˈeɪʃən ˈmænɪdʒmənt/','noun phrase','태양 복사 관리','A type of geoengineering aimed at reflecting sunlight.','{Solar radiation management} is a controversial climate intervention.','태양 복사 관리는 논란이 많은 기후 개입 방법이에요.','solar radiation management','C1','environment',1,'solar radiation management geoengineering sky reflect'),

-- ────────────────────────────────────────────────────────────
-- C2 (35 words)
-- ────────────────────────────────────────────────────────────
('w_environment_C2_01','radiative forcing','/ˈreɪdiətɪv ˈfɔːrsɪŋ/','noun phrase','복사 강제력','The change in energy in the atmosphere caused by greenhouse gases.','{Radiative forcing} from CO2 is the dominant warming driver.','이산화탄소의 복사 강제력이 온난화의 주된 원인이에요.','radiative forcing','C2','environment',1,'radiative forcing energy atmosphere CO2 science'),
('w_environment_C2_02','thermohaline circulation','/ˌθɜːrmoʊˈheɪlaɪn ˌsɜːrkjʊˈleɪʃən/','noun phrase','열염 순환','The ocean circulation driven by temperature and salinity differences.','{Thermohaline circulation} regulates global climate patterns.','열염 순환은 전 지구적 기후 패턴을 조절해요.','thermohaline circulation','C2','environment',1,'thermohaline ocean current map global climate'),
('w_environment_C2_03','albedo feedback','/ælˈbiːdoʊ ˈfiːdbæk/','noun phrase','알베도 피드백','The amplification of warming as ice loss reduces surface reflectivity.','{Albedo feedback} accelerates Arctic warming.','알베도 피드백이 북극 온난화를 가속화해요.','albedo feedback','C2','environment',1,'albedo feedback ice arctic warming science'),
('w_environment_C2_04','cryosphere dynamics','/ˈkraɪoʊsfɪər daɪˈnæmɪks/','noun phrase','빙권 역학','The physical processes governing ice and frozen water on Earth.','{Cryosphere dynamics} influence sea level projections.','빙권 역학은 해수면 전망에 영향을 미쳐요.','cryosphere dynamics','C2','environment',1,'cryosphere dynamics ice model science arctic'),
('w_environment_C2_05','permafrost thaw','/ˈpɜːrməfrɒst θɔː/','noun phrase','영구 동토층 해빙','The melting of permanently frozen ground.','{Permafrost thaw} releases stored carbon into the atmosphere.','영구 동토층 해빙으로 저장된 탄소가 대기로 방출돼요.','permafrost thaw','C2','environment',1,'permafrost thaw tundra methane arctic carbon'),
('w_environment_C2_06','tipping point','/ˈtɪpɪŋ pɔɪnt/','noun phrase','티핑 포인트','A threshold beyond which a system undergoes irreversible change.','The Amazon may be approaching a {tipping point}.','아마존은 티핑 포인트에 가까워지고 있을 수 있어요.','tipping point','C2','environment',1,'tipping point climate threshold change irreversible'),
('w_environment_C2_07','teleconnection','/ˌtɛlɪkəˈnɛkʃən/','noun','원격 상관','The correlation between weather patterns in distant parts of the world.','{Teleconnections} link El Nino events to global weather anomalies.','원격 상관은 엘니뇨 현상을 전 세계 이상 기상과 연결해요.','teleconnection','C2','environment',1,'teleconnection El Nino weather pattern globe science'),
('w_environment_C2_08','planetary boundary','/ˈplænɪtɛri ˈbaʊndəri/','noun phrase','행성 한계','The safe operating limits within which humanity can thrive.','We have crossed several {planetary boundaries}.','우리는 이미 몇 가지 행성 한계를 넘었어요.','planetary boundary','C2','environment',1,'planetary boundary earth limit science policy'),
('w_environment_C2_09','Holocene','/ˈhɒləsiːn/','noun','홀로세','The current geological epoch, beginning approximately 11,700 years ago.','Modern civilizations developed during the stable {Holocene} climate.','현대 문명은 안정적인 홀로세 기후 속에서 발전했어요.','Holocene','C2','environment',1,'Holocene epoch geology history earth time'),
('w_environment_C2_10','technosphere','/ˈtɛknoʊsfɪər/','noun','기술권','The sphere of human-made objects and infrastructure on Earth.','The growing {technosphere} is a geological force in its own right.','성장하는 기술권은 그 자체로 하나의 지질학적 힘이에요.','technosphere','C2','environment',1,'technosphere technology human infrastructure earth'),
('w_environment_C2_11','stratospheric aerosol injection','/ˌstrætəˈsfɛrɪk ˈɛərəsɒl ɪnˈdʒɛkʃən/','noun phrase','성층권 에어로졸 주입','Injecting particles into the stratosphere to reflect sunlight.','{Stratospheric aerosol injection} could rapidly cool the planet.','성층권 에어로졸 주입은 지구를 빠르게 냉각시킬 수 있어요.','stratospheric aerosol injection','C2','environment',1,'stratospheric aerosol injection sky cool geoengineering'),
('w_environment_C2_12','eddy diffusivity','/ˈɛdi dɪˌfjuːsɪˈvɪti/','noun phrase','와류 확산성','The rate at which turbulent eddies mix atmospheric constituents.','{Eddy diffusivity} affects how pollutants disperse in the atmosphere.','와류 확산성은 대기 중 오염물질이 퍼지는 방식에 영향을 줘요.','eddy diffusivity','C2','environment',1,'eddy diffusivity turbulence atmosphere science model'),
('w_environment_C2_13','isotopic fractionation','/ˌaɪsəˈtɒpɪk ˌfrækʃəˈneɪʃən/','noun phrase','동위원소 분별','The separation of isotopes in a chemical or physical process.','{Isotopic fractionation} helps scientists trace carbon sources.','동위원소 분별은 과학자들이 탄소 출처를 추적하는 데 도움을 줘요.','isotopic fractionation','C2','environment',1,'isotopic fractionation carbon science lab data'),
('w_environment_C2_14','Milankovitch cycle','/mɪˈlænkɒvɪtʃ ˈsaɪkəl/','noun phrase','밀란코비치 주기','Cycles in Earth''s orbital parameters that affect climate.','{Milankovitch cycles} explain ice age timing over millennia.','밀란코비치 주기는 수천 년에 걸친 빙하기 시기를 설명해요.','Milankovitch cycle','C2','environment',1,'Milankovitch cycle orbit earth ice age astronomy'),
('w_environment_C2_15','biogeography','/ˌbaɪoʊdʒiˈɒɡrəfi/','noun','생물지리학','The study of the distribution of species across the Earth.','{Biogeography} reveals how climate change shifts species ranges.','생물지리학은 기후 변화가 종의 분포 범위를 어떻게 바꾸는지 밝혀요.','biogeography','C2','environment',1,'biogeography map species distribution earth science'),
('w_environment_C2_16','anthrome','/ˈænθroʊm/','noun','인간 생태지역','A biome modified by long-term human activity.','Most of Earth''s land surface is now classified as {anthrome}.','지구 육지의 대부분이 이제 인간 생태지역으로 분류돼요.','anthrome','C2','environment',1,'anthrome human land ecology biome earth'),
('w_environment_C2_17','methanogenesis','/ˌmɛθənoʊˈdʒɛnɪsɪs/','noun','메탄 생성','The biological production of methane by archaea.','{Methanogenesis} in wetlands is a major natural methane source.','습지의 메탄 생성은 자연적 메탄의 주요 공급원이에요.','methanogenesis','C2','environment',1,'methanogenesis methane wetland microbe science'),
('w_environment_C2_18','dendroclimatology','/ˌdɛndroʊˌklaɪməˈtɒlədʒi/','noun','수목기후학','The study of past climate using tree ring data.','{Dendroclimatology} has reconstructed 1,000 years of temperature records.','수목기후학은 1,000년간의 기온 기록을 복원했어요.','dendroclimatology','C2','environment',1,'dendroclimatology tree ring data climate science'),
('w_environment_C2_19','xenobiotic','/ˌziːnoʊbaɪˈɒtɪk/','noun','이종생체물질','A chemical not normally found in an organism or ecosystem.','{Xenobiotics} such as pesticides accumulate in food chains.','살충제와 같은 이종생체물질이 먹이사슬에 축적돼요.','xenobiotic','C2','environment',1,'xenobiotic chemical pesticide food chain toxin'),
('w_environment_C2_20','geomorphology','/ˌdʒiːoʊmɔːrˈfɒlədʒi/','noun','지형학','The study of the physical features of Earth''s surface.','{Geomorphology} shows how climate shapes landscapes over time.','지형학은 기후가 시간에 따라 경관을 어떻게 형성하는지 보여줘요.','geomorphology','C2','environment',1,'geomorphology landscape earth rock erosion science'),
('w_environment_C2_21','limnology','/lɪmˈnɒlədʒi/','noun','호소학','The scientific study of freshwater lakes and ponds.','{Limnology} monitors water quality and ecosystem health.','호소학은 수질과 생태계 건강을 모니터링해요.','limnology','C2','environment',1,'limnology lake water freshwater science ecology'),
('w_environment_C2_22','photodegradation','/ˌfoʊtoʊdɛɡrəˈdeɪʃən/','noun','광분해','The breakdown of materials by light, especially sunlight.','{Photodegradation} breaks plastics into microplastics.','광분해는 플라스틱을 미세플라스틱으로 분해해요.','photodegradation','C2','environment',1,'photodegradation plastic sunlight UV science ocean'),
('w_environment_C2_23','carrying capacity','/ˈkæriɪŋ kəˈpæsɪti/','noun phrase','수용 능력','The maximum population size an environment can support.','Human activity has already exceeded Earth''s {carrying capacity}.','인간 활동은 이미 지구의 수용 능력을 초과했어요.','carrying capacity','C2','environment',1,'carrying capacity population earth resource limit'),
('w_environment_C2_24','stoichiometry','/ˌstɔɪkiˈɒmɪtri/','noun','양론','The calculation of quantities in chemical reactions in ecosystems.','{Stoichiometry} explains nutrient cycling imbalances in ecosystems.','양론은 생태계의 영양 순환 불균형을 설명해요.','stoichiometry','C2','environment',1,'stoichiometry chemistry nutrient cycle ecosystem science'),
('w_environment_C2_25','macroecology','/ˌmækroʊɪˈkɒlədʒi/','noun','거시 생태학','The study of large-scale patterns in the distribution of organisms.','{Macroecology} reveals how climate controls biodiversity.','거시 생태학은 기후가 생물 다양성을 어떻게 조절하는지 밝혀요.','macroecology','C2','environment',1,'macroecology pattern species global climate data'),
('w_environment_C2_26','exergy','/ˈɛksɜːrdʒi/','noun','엑서지','The maximum useful work obtainable from a system in a given environment.','{Exergy} analysis optimises energy use in industrial processes.','엑서지 분석은 산업 공정에서의 에너지 사용을 최적화해요.','exergy','C2','environment',1,'exergy energy efficiency thermodynamics industry'),
('w_environment_C2_27','palaeoecology','/ˌpæliɔɪˈkɒlədʒi/','noun','고생태학','The study of ancient ecosystems using fossil evidence.','{Palaeoecology} reconstructs how past species responded to climate change.','고생태학은 과거 종이 기후 변화에 어떻게 반응했는지 재구성해요.','palaeoecology','C2','environment',1,'palaeoecology fossil ancient ecosystem science history'),
('w_environment_C2_28','abiogenesis','/ˌeɪbaɪoʊˈdʒɛnɪsɪs/','noun','무생물 생성','The natural process by which life arises from non-living matter.','{Abiogenesis} is studied to understand early Earth conditions.','무생물 생성은 초기 지구 환경을 이해하기 위해 연구돼요.','abiogenesis','C2','environment',1,'abiogenesis origin life earth science chemistry'),
('w_environment_C2_29','endosymbiosis','/ˌɛndoʊsɪmˈbaɪoʊsɪs/','noun','세포내 공생','A relationship where one organism lives inside another.','{Endosymbiosis} explains the origin of chloroplasts in plants.','세포내 공생은 식물의 엽록체 기원을 설명해요.','endosymbiosis','C2','environment',1,'endosymbiosis cell biology chloroplast evolution'),
('w_environment_C2_30','photochemical smog','/ˌfoʊtoʊˈkɛmɪkəl smɒɡ/','noun phrase','광화학 스모그','Smog formed by sunlight reacting with air pollutants.','{Photochemical smog} is a serious health hazard in many cities.','광화학 스모그는 많은 도시에서 심각한 건강 위협이에요.','photochemical smog','C2','environment',1,'photochemical smog city air pollution health'),
('w_environment_C2_31','volatile organic compound','/ˈvɒlətaɪl ɔːrˈɡænɪk ˈkɒmpaʊnd/','noun phrase','휘발성 유기 화합물','Chemicals that evaporate at room temperature and pollute the air.','{Volatile organic compounds} from paints worsen indoor air quality.','페인트의 휘발성 유기 화합물은 실내 공기 질을 악화시켜요.','volatile organic compound','C2','environment',1,'volatile organic compound paint air indoor health'),
('w_environment_C2_32','coccolithophore','/ˌkɒkəlɪˈθɒfɔːr/','noun','원석조류','Tiny marine algae that produce calcium carbonate plates.','{Coccolithophores} are sensitive indicators of ocean acidification.','원석조류는 해양 산성화의 민감한 지표예요.','coccolithophore','C2','environment',1,'coccolithophore ocean marine algae acid micro'),
('w_environment_C2_33','negative emissions technology','/ˈnɛɡətɪv ɪˈmɪʃənz tɛkˈnɒlədʒi/','noun phrase','네거티브 배출 기술','Technology that removes CO2 from the atmosphere.','{Negative emissions technologies} include direct air capture.','네거티브 배출 기술에는 직접 공기 포집이 포함돼요.','negative emissions technology','C2','environment',1,'negative emissions technology CO2 capture climate'),
('w_environment_C2_34','Earth system science','/ɜːrθ ˈsɪstəm saɪəns/','noun phrase','지구 시스템 과학','The study of Earth as a set of interacting physical, chemical, and biological systems.','{Earth system science} integrates climate, ecology, and geology.','지구 시스템 과학은 기후, 생태학, 지질학을 통합해요.','Earth system science','C2','environment',1,'earth system science climate ecology geology'),
('w_environment_C2_35','refugium','/rɪˈfjuːdʒiəm/','noun','피난처','An area where species survive during adverse environmental conditions.','{Refugia} allow species to persist through climate change.','피난처는 기후 변화 속에서 종이 살아남을 수 있게 해줘요.','refugium','C2','environment',1,'refugium species habitat climate refuge nature')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- SENTENCE PATTERNS
-- ============================================================

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES

-- ────────────────────────────────────────────────────────────
-- A1 · 환경 실천 (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_environment_A1_01','Let''s recycle this.','이거 재활용해요.','Let''s recycle','Let''s...는 함께 무언가를 하자고 제안할 때 써요.','환경 실천','A1','environment','pattern',NULL,1),
('s_environment_A1_02','Don''t waste water.','물을 낭비하지 마세요.','Don''t waste','Don''t + 동사원형은 금지 또는 권고를 나타내요.','환경 실천','A1','environment','pattern',NULL,2),
('s_environment_A1_03','Please pick up the litter.','쓰레기를 주워주세요.','pick up the litter','Please + 명령문은 정중하게 요청할 때 사용해요.','환경 실천','A1','environment','pattern',NULL,3),
('s_environment_A1_04','The sky looks very blue today.','오늘 하늘이 정말 파래 보여요.','looks very blue','look + 형용사는 외관을 묘사할 때 써요.','환경 실천','A1','environment','pattern',NULL,4),
('s_environment_A1_05','I love walking in the forest.','저는 숲속에서 걷는 걸 좋아해요.','love walking','love + -ing는 좋아하는 활동을 말할 때 써요.','환경 실천','A1','environment','pattern',NULL,5),
('s_environment_A1_06','We need clean water to live.','우리는 살기 위해 깨끗한 물이 필요해요.','need clean water','need + 명사는 필요한 것을 표현해요.','환경 실천','A1','environment','pattern',NULL,6),
('s_environment_A1_07','Turn off the light when you leave.','나갈 때 불을 꺼주세요.','Turn off the light','Turn off...는 절전·절약 행동을 권고할 때 흔히 써요.','환경 실천','A1','environment','pattern',NULL,7),

-- ────────────────────────────────────────────────────────────
-- A2 · 재활용·절약 (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_environment_A2_01','You should separate your recyclables.','재활용품을 분리해야 해요.','should separate','should + 동사원형은 의무나 권고를 나타내요.','재활용·절약','A2','environment','pattern',NULL,1),
('s_environment_A2_02','Try to use less plastic every day.','매일 플라스틱을 덜 쓰려고 노력해보세요.','Try to use less','Try to + 동사원형은 노력을 권장할 때 써요.','재활용·절약','A2','environment','pattern',NULL,2),
('s_environment_A2_03','Taking public transport reduces pollution.','대중교통 이용이 오염을 줄여요.','reduces pollution','동명사 주어는 행동 자체의 효과를 설명할 때 자연스러워요.','재활용·절약','A2','environment','pattern',NULL,3),
('s_environment_A2_04','Have you tried composting your food scraps?','음식물 쓰레기 퇴비로 만들어 보셨어요?','tried composting','Have you tried + -ing는 새로운 방법을 제안할 때 써요.','재활용·절약','A2','environment','pattern',NULL,4),
('s_environment_A2_05','It''s important to save energy at home.','집에서 에너지를 절약하는 것이 중요해요.','It''s important to','It''s important to + 동사원형은 중요성을 강조해요.','재활용·절약','A2','environment','pattern',NULL,5),
('s_environment_A2_06','I always bring my own bag to the shop.','저는 항상 가게에 개인 가방을 가져가요.','always bring my own','always + 현재시제는 반복 습관을 나타내요.','재활용·절약','A2','environment','pattern',NULL,6),
('s_environment_A2_07','Why don''t we plant some trees this weekend?','이번 주말에 나무를 심는 건 어때요?','Why don''t we plant','Why don''t we...는 함께 하는 활동을 제안할 때 써요.','재활용·절약','A2','environment','pattern',NULL,7),

-- ────────────────────────────────────────────────────────────
-- B1 · 기후 변화 (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_environment_B1_01','Climate change is affecting every country in the world.','기후 변화는 세계 모든 나라에 영향을 미치고 있어요.','is affecting every country','현재진행형은 지금도 계속되는 변화를 강조해요.','기후 변화','B1','environment','pattern',NULL,1),
('s_environment_B1_02','If we reduce emissions now, we can slow global warming.','지금 배출량을 줄이면 지구 온난화를 늦출 수 있어요.','If we reduce...we can','If + 현재시제, 주어 + can은 현실적 가능성을 나타내요.','기후 변화','B1','environment','pattern',NULL,2),
('s_environment_B1_03','Renewable energy is becoming cheaper every year.','재생에너지는 매년 더 저렴해지고 있어요.','is becoming cheaper','is becoming + 비교급은 점진적 변화를 표현해요.','기후 변화','B1','environment','pattern',NULL,3),
('s_environment_B1_04','Scientists have warned us about the dangers of deforestation.','과학자들은 삼림 벌채의 위험성에 대해 경고해왔어요.','have warned us about','현재완료는 과거부터 지금까지 이어진 경고를 강조해요.','기후 변화','B1','environment','pattern',NULL,4),
('s_environment_B1_05','We need to find a balance between development and conservation.','개발과 보전 사이의 균형을 찾아야 해요.','find a balance between','find a balance between A and B는 균형의 필요성을 논할 때 유용해요.','기후 변화','B1','environment','pattern',NULL,5),
('s_environment_B1_06','Many species are at risk of extinction due to habitat loss.','서식지 손실로 인해 많은 종이 멸종 위기에 처해 있어요.','at risk of extinction due to','due to + 명사는 원인을 간결하게 설명해요.','기후 변화','B1','environment','pattern',NULL,6),
('s_environment_B1_07','Switching to solar energy would significantly cut our carbon footprint.','태양 에너지로 전환하면 탄소 발자국을 크게 줄일 수 있어요.','would significantly cut','조동사 would는 가정적 결과나 권고를 부드럽게 표현해요.','기후 변화','B1','environment','pattern',NULL,7),

-- ────────────────────────────────────────────────────────────
-- B2 · 환경 정책 (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_environment_B2_01','Governments must implement stricter emission controls without delay.','정부는 지체 없이 더 엄격한 배출 규제를 시행해야 해요.','must implement stricter','must + 동사원형은 강한 의무를 나타내고, stricter는 비교급으로 강도를 높여요.','환경 정책','B2','environment','pattern',NULL,1),
('s_environment_B2_02','A carbon tax could incentivise businesses to invest in clean technology.','탄소세는 기업들이 청정 기술에 투자하도록 유도할 수 있어요.','could incentivise businesses to','could + 동사원형은 정책 효과를 신중하게 제안할 때 써요.','환경 정책','B2','environment','pattern',NULL,2),
('s_environment_B2_03','Unless drastic action is taken, we will exceed the 1.5 degree threshold.','과감한 조치가 취해지지 않으면 1.5도 한계를 초과할 거예요.','Unless drastic action is taken','Unless + 수동태 절은 조건의 부정을 강조해요.','환경 정책','B2','environment','pattern',NULL,3),
('s_environment_B2_04','Sustainable development requires balancing economic growth with ecological preservation.','지속 가능한 개발은 경제 성장과 생태 보전의 균형을 필요로 해요.','requires balancing...with','require + 동명사는 필수 조건을 나타내요.','환경 정책','B2','environment','pattern',NULL,4),
('s_environment_B2_05','The treaty obliges all signatories to report their greenhouse gas emissions annually.','그 조약은 모든 서명국이 온실가스 배출량을 매년 보고하도록 의무화해요.','obliges all signatories to','oblige + 목적어 + to 부정사는 공식적 의무를 표현해요.','환경 정책','B2','environment','pattern',NULL,5),
('s_environment_B2_06','By investing in reforestation, we can partially offset our carbon emissions.','재조림에 투자함으로써 탄소 배출량을 부분적으로 상쇄할 수 있어요.','By investing in...we can partially offset','By + -ing는 수단을, partially offset은 현실적 기대치를 표현해요.','환경 정책','B2','environment','pattern',NULL,6),
('s_environment_B2_07','Public awareness campaigns have proven effective in changing consumer behaviour.','공공 인식 제고 캠페인은 소비자 행동 변화에 효과적인 것으로 입증됐어요.','have proven effective in changing','have proven + 형용사 + in + -ing는 증거에 기반한 주장을 나타내요.','환경 정책','B2','environment','pattern',NULL,7),

-- ────────────────────────────────────────────────────────────
-- C1 · 기후 과학 (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_environment_C1_01','Anthropogenic emissions have unequivocally altered the Earth''s energy balance.','인위적 배출이 지구의 에너지 균형을 명백히 변화시켰어요.','have unequivocally altered','현재완료 + 부사(unequivocally)는 과학적 확신을 강조해요.','기후 과학','C1','environment','pattern',NULL,1),
('s_environment_C1_02','The precautionary principle dictates that we act before scientific consensus is fully established.','사전 예방 원칙은 과학적 합의가 완전히 형성되기 전에 행동하도록 요구해요.','dictates that we act before','dictate that + 절은 원칙이나 규범이 요구하는 바를 표현해요.','기후 과학','C1','environment','pattern',NULL,2),
('s_environment_C1_03','Decarbonizing the energy sector is widely regarded as the most urgent priority.','에너지 부문의 탈탄소화는 가장 시급한 과제로 널리 여겨지고 있어요.','is widely regarded as the most urgent','수동태 + widely는 광범위한 전문가 의견을 전달해요.','기후 과학','C1','environment','pattern',NULL,3),
('s_environment_C1_04','Trophic cascades illustrate how the removal of a single species can destabilise an entire ecosystem.','영양 단계 연쇄반응은 단 한 종의 제거가 전체 생태계를 불안정하게 만들 수 있음을 보여줘요.','how the removal of a single species can destabilise','간접의문문 + can은 복잡한 생태적 메커니즘을 설명할 때 유용해요.','기후 과학','C1','environment','pattern',NULL,4),
('s_environment_C1_05','Paleoclimatological records suggest that today''s warming is unprecedented in at least 800,000 years.','고기후학 기록은 오늘날의 온난화가 최소 80만 년 중 전례 없는 것임을 시사해요.','suggest that...is unprecedented in','suggest that + 절은 증거에 기반한 신중한 주장을 나타내요.','기후 과학','C1','environment','pattern',NULL,5),
('s_environment_C1_06','Geoengineering proposals must be evaluated against the risk of unintended ecological consequences.','지구공학 제안은 의도치 않은 생태적 결과의 위험과 대비해 평가돼야 해요.','must be evaluated against the risk of','must be + 과거분사는 필수적 절차를 강조하는 수동태예요.','기후 과학','C1','environment','pattern',NULL,6),
('s_environment_C1_07','Carbon sinks are increasingly being overwhelmed by the volume of anthropogenic emissions.','탄소 흡수원은 인위적 배출량의 규모에 점점 압도당하고 있어요.','are increasingly being overwhelmed','현재진행 수동태 + increasingly는 악화되는 추세를 생생하게 표현해요.','기후 과학','C1','environment','pattern',NULL,7),

-- ────────────────────────────────────────────────────────────
-- C2 · 기후 과학 (7 patterns)
-- ────────────────────────────────────────────────────────────
('s_environment_C2_01','Radiative forcing data confirm that positive feedbacks are amplifying initial warming signals.','복사 강제력 데이터는 양의 피드백이 초기 온난화 신호를 증폭시키고 있음을 확인해줘요.','confirm that positive feedbacks are amplifying','confirm that + 절은 데이터에 근거한 단정적 결론을 표현해요.','기후 과학','C2','environment','pattern',NULL,1),
('s_environment_C2_02','Thermohaline circulation disruption could have cascading consequences for global heat distribution.','열염 순환 붕괴는 전 지구적 열 분배에 연쇄적 결과를 초래할 수 있어요.','could have cascading consequences for','could have + 명사는 잠재적이지만 심각한 결과를 신중하게 표현해요.','기후 과학','C2','environment','pattern',NULL,2),
('s_environment_C2_03','Permafrost thaw is projected to release gigatons of carbon, potentially creating a runaway feedback loop.','영구 동토층 해빙은 수십억 톤의 탄소를 방출해 통제 불가능한 피드백 루프를 만들 가능성이 있어요.','is projected to release...potentially creating','is projected to + 동사원형은 모델 기반 전망을, -ing는 동반 결과를 표현해요.','기후 과학','C2','environment','pattern',NULL,3),
('s_environment_C2_04','Crossing planetary boundaries simultaneously increases the likelihood of abrupt, nonlinear Earth system transitions.','행성 한계를 동시에 넘으면 갑작스럽고 비선형적인 지구 시스템 전환이 발생할 가능성이 높아져요.','increases the likelihood of abrupt, nonlinear','increase the likelihood of + 명사는 확률적 위험을 학술적으로 표현해요.','기후 과학','C2','environment','pattern',NULL,4),
('s_environment_C2_05','Teleconnections demonstrate that seemingly localised climate events can propagate disruptions across hemispheres.','원격 상관은 겉으로 보기에 국지적인 기후 현상이 반구를 가로질러 교란을 전파할 수 있음을 보여줘요.','demonstrate that...can propagate disruptions across','demonstrate that + 절은 메커니즘의 입증을, across는 지리적 범위를 강조해요.','기후 과학','C2','environment','pattern',NULL,5),
('s_environment_C2_06','Dendroclimatological proxies corroborate instrumental records, strengthening confidence in reconstructed temperature anomalies.','수목기후학 대리자료는 기기 기록을 뒷받침하여 재구성된 기온 이상에 대한 신뢰도를 높여요.','corroborate...strengthening confidence in','corroborate + 목적어는 복수의 증거가 일치함을 표현하는 학술적 동사예요.','기후 과학','C2','environment','pattern',NULL,6),
('s_environment_C2_07','Achieving net zero necessitates a systemic transformation of energy, agriculture, and land-use paradigms.','넷제로 달성은 에너지, 농업, 토지 이용 패러다임의 전면적 전환을 필요로 해요.','necessitates a systemic transformation of','necessitate + 명사는 단순한 필요를 넘어 근본적 변화의 불가피성을 나타내요.','기후 과학','C2','environment','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;
