-- EngCat — Sports (스포츠) Topic
-- 210 words (35 per CEFR level A1~C2) + 42 patterns (7 per level)
-- Generated: 2026-05-24

-- ══════════════════════════════════════════════════════════════════════
-- WORDS — A1 (기초)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_sports_A1_01','run','/rʌn/','verb','달리다','To move quickly on foot.','I {run} every morning to stay healthy.','건강을 위해 매일 아침 달려요.','run','A1','sports',1,'running person exercise park morning'),
('w_sports_A1_02','play','/pleɪ/','verb','(스포츠를) 하다','To take part in a sport or game.','Do you {play} any sports after school?','방과 후에 운동을 해요?','play','A1','sports',1,'kids playing sport field outdoor'),
('w_sports_A1_03','win','/wɪn/','verb','이기다','To finish first or be the best in a competition.','We want to {win} the game this weekend.','이번 주말 경기를 이기고 싶어요.','win','A1','sports',1,'athlete winning trophy celebration victory'),
('w_sports_A1_04','lose','/luːz/','verb','지다','To fail to win a game or competition.','It''s okay to {lose} sometimes — it helps you improve.','가끔 지는 것도 괜찮아요. 발전에 도움이 돼요.','lose','A1','sports',1,'athlete disappointed loss game sport'),
('w_sports_A1_05','team','/tiːm/','noun','팀','A group of people who play together on one side.','Our {team} practises every Tuesday evening.','저희 팀은 매주 화요일 저녁에 연습해요.','team','A1','sports',1,'sports team group players huddle field'),
('w_sports_A1_06','ball','/bɔːl/','noun','공','A round object used in many sports.','Kick the {ball} into the net.','공을 네트 안으로 차 넣으세요.','ball','A1','sports',1,'soccer ball grass field sport'),
('w_sports_A1_07','game','/ɡeɪm/','noun','경기, 게임','A form of play or sport with rules.','The {game} starts at seven o''clock tonight.','경기는 오늘 밤 일곱 시에 시작해요.','game','A1','sports',1,'sport game stadium crowd spectators'),
('w_sports_A1_08','swim','/swɪm/','verb','수영하다','To move through water using your body.','She can {swim} very fast.','그녀는 수영을 아주 빠르게 해요.','swim','A1','sports',1,'swimmer pool lane water sport'),
('w_sports_A1_09','jump','/dʒʌmp/','verb','점프하다','To push yourself off the ground into the air.','He can {jump} really high.','그는 아주 높이 점프할 수 있어요.','jump','A1','sports',1,'athlete jumping high jump sport'),
('w_sports_A1_10','fast','/fæst/','adjective','빠른','Moving or able to move at high speed.','That runner is really {fast}.','저 달리기 선수는 정말 빨라요.','fast','A1','sports',1,'sprinter fast running track speed'),
('w_sports_A1_11','sport','/spɔːrt/','noun','스포츠','A physical activity done for exercise or competition.','Which {sport} do you like the most?','어떤 스포츠를 가장 좋아해요?','sport','A1','sports',1,'various sports collage activity'),
('w_sports_A1_12','kick','/kɪk/','verb','차다','To hit something with your foot.','Please {kick} the ball to your teammate.','팀원에게 공을 차 주세요.','kick','A1','sports',1,'soccer player kicking ball field'),
('w_sports_A1_13','throw','/θroʊ/','verb','던지다','To send something through the air using your hand.','{Throw} the ball to me!','저한테 공 던져요!','Throw','A1','sports',1,'baseball pitcher throwing ball sport'),
('w_sports_A1_14','catch','/kætʃ/','verb','잡다','To grab something that is moving through the air.','Can you {catch} the ball?','공을 잡을 수 있어요?','catch','A1','sports',1,'baseball outfielder catching ball glove'),
('w_sports_A1_15','race','/reɪs/','noun','경주','A competition to see who is fastest.','There is a {race} at the school tomorrow.','내일 학교에서 경주가 있어요.','race','A1','sports',1,'runners race start line track'),
('w_sports_A1_16','goal','/ɡoʊl/','noun','골','A point scored in a sport like football or hockey.','He scored an amazing {goal} in the last minute.','그는 마지막 순간에 멋진 골을 넣었어요.','goal','A1','sports',1,'soccer goal net celebration score'),
('w_sports_A1_17','hit','/hɪt/','verb','치다','To strike something with force.','She can {hit} the ball very hard.','그녀는 공을 아주 세게 쳐요.','hit','A1','sports',1,'tennis player hitting ball racket sport'),
('w_sports_A1_18','strong','/strɒŋ/','adjective','강한','Having a lot of physical power.','Athletes need to be {strong} and fit.','운동선수는 강하고 건강해야 해요.','strong','A1','sports',1,'strong athlete muscle fitness gym'),
('w_sports_A1_19','tired','/taɪərd/','adjective','피곤한','Needing rest after effort or exertion.','I feel very {tired} after practice.','연습 후에 아주 피곤해요.','tired','A1','sports',1,'athlete tired exhausted bench rest'),
('w_sports_A1_20','score','/skɔːr/','noun','점수','The number of points achieved in a game.','What is the {score} right now?','지금 점수가 어떻게 돼요?','score','A1','sports',1,'scoreboard game points sport stadium'),
('w_sports_A1_21','watch','/wɒtʃ/','verb','보다, 관람하다','To look at something for a period of time.','I love to {watch} football on TV.','TV로 축구 보는 걸 좋아해요.','watch','A1','sports',1,'fans watching sport TV stadium crowd'),
('w_sports_A1_22','field','/fiːld/','noun','경기장, 필드','An area of ground where a sport is played.','The players are warming up on the {field}.','선수들이 경기장에서 워밍업하고 있어요.','field','A1','sports',1,'football field green grass sport'),
('w_sports_A1_23','exercise','/ˈeksərsaɪz/','noun','운동','Physical activity done to stay healthy.','Daily {exercise} keeps your body healthy.','매일 운동하면 몸을 건강하게 유지할 수 있어요.','exercise','A1','sports',1,'person exercising workout fitness outdoor'),
('w_sports_A1_24','player','/ˈpleɪər/','noun','선수','A person who takes part in a sport or game.','The best {player} on our team scored three goals.','우리 팀에서 가장 잘하는 선수가 세 골을 넣었어요.','player','A1','sports',1,'football player jersey sport action'),
('w_sports_A1_25','water','/ˈwɔːtər/','noun','물','A liquid essential for life, used in swimming sports.','Drink some {water} after you exercise.','운동 후에 물을 마시세요.','water','A1','sports',1,'athlete drinking water bottle sport'),
('w_sports_A1_26','gym','/dʒɪm/','noun','체육관','A room or building with equipment for exercise.','I go to the {gym} three times a week.','일주일에 세 번 체육관에 가요.','gym','A1','sports',1,'gym indoor equipment weights fitness'),
('w_sports_A1_27','bike','/baɪk/','noun','자전거','A two-wheeled vehicle used for cycling.','He rides his {bike} to the park every day.','그는 매일 자전거를 타고 공원에 가요.','bike','A1','sports',1,'cyclist bike riding park outdoor'),
('w_sports_A1_28','fun','/fʌn/','adjective','재미있는','Enjoyable and entertaining.','Sport is really {fun} when you play with friends.','친구들과 함께 하는 운동은 정말 재미있어요.','fun','A1','sports',1,'friends playing sport laughing fun outdoor'),
('w_sports_A1_29','practice','/ˈpræktɪs/','noun','연습','The action of doing something repeatedly to improve.','We have football {practice} after school.','방과 후에 축구 연습이 있어요.','practice','A1','sports',1,'team practice training drill sport field'),
('w_sports_A1_30','swim pool','/swɪm puːl/','noun','수영장','An artificial body of water for swimming.','Let''s meet at the {swim pool} on Saturday.','토요일에 수영장에서 만나요.','swim pool','A1','sports',1,'swimming pool lane water blue'),
('w_sports_A1_31','net','/net/','noun','네트, 골망','A barrier or frame of mesh used in sports.','The ball went straight into the {net}.','공이 곧장 골망으로 들어갔어요.','net','A1','sports',1,'tennis net court sport game'),
('w_sports_A1_32','helmet','/ˈhelmɪt/','noun','헬멧','A hard hat worn to protect the head.','Always wear a {helmet} when you ride a bike.','자전거를 탈 때는 항상 헬멧을 써요.','helmet','A1','sports',1,'cyclist wearing helmet safety sport'),
('w_sports_A1_33','match','/mætʃ/','noun','경기, 시합','A game between two individuals or teams.','The {match} ended in a draw.','경기가 무승부로 끝났어요.','match','A1','sports',1,'tennis match court players sport'),
('w_sports_A1_34','cheer','/tʃɪər/','verb','응원하다','To shout with joy or enthusiasm for a team.','Everyone started to {cheer} when we scored.','우리가 득점하자 모두가 응원하기 시작했어요.','cheer','A1','sports',1,'fans cheering stadium crowd sport'),
('w_sports_A1_35','train','/treɪn/','verb','훈련하다','To practise and prepare for a sport.','Athletes {train} hard every day.','운동선수들은 매일 열심히 훈련해요.','train','A1','sports',1,'athlete training workout hard sport');

-- ══════════════════════════════════════════════════════════════════════
-- WORDS — A2 (초급)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_sports_A2_01','match','/mætʃ/','noun','(수준이 같은) 경기','A formal contest between two teams or players.','Did you watch the football {match} last night?','어젯밤 축구 경기 봤어요?','match','A2','sports',1,'football match stadium crowd night'),
('w_sports_A2_02','score','/skɔːr/','verb','득점하다','To gain a point in a sport or game.','She managed to {score} in the final minutes.','그녀는 마지막 순간에 득점에 성공했어요.','score','A2','sports',1,'athlete scoring point goal celebrate'),
('w_sports_A2_03','practice','/ˈpræktɪs/','verb','연습하다','To do something repeatedly to get better.','You need to {practice} your free throws every day.','매일 자유투 연습을 해야 해요.','practice','A2','sports',1,'basketball player practicing free throw'),
('w_sports_A2_04','athlete','/ˈæθliːt/','noun','운동선수','A person who is good at sport.','She is a very talented {athlete}.','그녀는 아주 재능 있는 운동선수예요.','athlete','A2','sports',1,'professional athlete competition track field'),
('w_sports_A2_05','stadium','/ˈsteɪdiəm/','noun','경기장','A large sports arena with seats for spectators.','The {stadium} holds fifty thousand fans.','그 경기장은 5만 명의 팬을 수용해요.','stadium','A2','sports',1,'large sports stadium crowd aerial view'),
('w_sports_A2_06','coach','/koʊtʃ/','noun','코치','A person who trains athletes or sports teams.','Our {coach} gives us great advice before every game.','우리 코치님은 경기 전마다 좋은 조언을 해줘요.','coach','A2','sports',1,'coach talking players team sideline sport'),
('w_sports_A2_07','train','/treɪn/','verb','훈련시키다','To prepare someone for a sport through practice.','The coach will {train} the team six days a week.','코치는 팀을 일주일에 6일 훈련시킬 거예요.','train','A2','sports',1,'coach training athletes workout field'),
('w_sports_A2_08','compete','/kəmˈpiːt/','verb','경쟁하다','To take part in a competition.','She will {compete} in three events at the championship.','그녀는 선수권 대회에서 세 종목에 출전할 거예요.','compete','A2','sports',1,'athletes competing race championship event'),
('w_sports_A2_09','trophy','/ˈtroʊfi/','noun','트로피','A prize given to the winner of a competition.','The winning team lifted the {trophy} after the final.','우승 팀이 결승전 후 트로피를 들어 올렸어요.','trophy','A2','sports',1,'sports trophy winner celebration lifting'),
('w_sports_A2_10','champion','/ˈtʃæmpiən/','noun','챔피언','A person or team who has won a competition.','She became the national {champion} at the age of seventeen.','그녀는 열일곱 살에 전국 챔피언이 됐어요.','champion','A2','sports',1,'champion winner medal podium sport'),
('w_sports_A2_11','foul','/faʊl/','noun','파울','An unfair action that breaks the rules of a sport.','The referee called a {foul} against our team.','심판이 우리 팀에게 파울을 선언했어요.','foul','A2','sports',1,'referee calling foul basketball sport'),
('w_sports_A2_12','halftime','/ˈhɑːftaɪm/','noun','하프타임','The break between two halves of a game.','The coach gave a speech at {halftime}.','코치가 하프타임에 연설을 했어요.','halftime','A2','sports',1,'halftime players resting locker room sport'),
('w_sports_A2_13','league','/liːɡ/','noun','리그','A group of sports teams that compete against each other.','Our club plays in the local {league}.','우리 클럽은 지역 리그에서 뛰어요.','league','A2','sports',1,'football league table standings sport'),
('w_sports_A2_14','position','/pəˈzɪʃən/','noun','포지션','A player''s role in a sports team.','What {position} do you play on the team?','팀에서 어떤 포지션을 맡고 있어요?','position','A2','sports',1,'football player position formation tactic'),
('w_sports_A2_15','record','/ˈrekərd/','noun','기록','The best performance achieved in a sport.','She broke the school {record} for the 100-metre sprint.','그녀는 100미터 달리기 학교 기록을 깼어요.','record','A2','sports',1,'athlete breaking world record track'),
('w_sports_A2_16','warm up','/wɔːrm ʌp/','verb','준비 운동하다','To do gentle exercises before sport or training.','Always {warm up} for at least ten minutes.','최소 10분 이상 준비 운동을 꼭 하세요.','warm up','A2','sports',1,'athletes warming up stretching field sport'),
('w_sports_A2_17','uniform','/ˈjuːnɪfɔːrm/','noun','유니폼','The special clothes worn by members of a sports team.','All players must wear the team {uniform}.','모든 선수는 팀 유니폼을 입어야 해요.','uniform','A2','sports',1,'sports team uniform jersey colour'),
('w_sports_A2_18','captain','/ˈkæptɪn/','noun','주장','The leader of a sports team.','The {captain} shook hands with the opposing team.','주장이 상대 팀과 악수를 나눴어요.','captain','A2','sports',1,'team captain armband shaking hands sport'),
('w_sports_A2_19','timeout','/ˈtaɪmaʊt/','noun','타임아웃','A short break called by a team during a game.','The coach called a {timeout} to talk to the players.','코치가 선수들과 이야기하려고 타임아웃을 요청했어요.','timeout','A2','sports',1,'coach calling timeout basketball huddle'),
('w_sports_A2_20','defend','/dɪˈfend/','verb','수비하다','To try to stop the other team from scoring.','It is important to {defend} as a unit.','팀 전체가 단합해서 수비하는 것이 중요해요.','defend','A2','sports',1,'defender defending goal football sport'),
('w_sports_A2_21','attack','/əˈtæk/','verb','공격하다','To play aggressively and try to score.','The team loves to {attack} from the wings.','그 팀은 측면 공격을 즐겨 해요.','attack','A2','sports',1,'football player attacking forward goal'),
('w_sports_A2_22','medal','/ˈmedəl/','noun','메달','A metal disc given as a prize in a competition.','She won a gold {medal} at the Olympics.','그녀는 올림픽에서 금메달을 땄어요.','medal','A2','sports',1,'athlete gold medal ceremony podium'),
('w_sports_A2_23','sprint','/sprɪnt/','verb','전력 질주하다','To run as fast as possible over a short distance.','The runners {sprint} to the finish line.','주자들이 결승선을 향해 전력 질주해요.','sprint','A2','sports',1,'sprinters sprint finish line race'),
('w_sports_A2_24','tournament','/ˈtʊrnəmənt/','noun','토너먼트','A series of matches to decide an overall winner.','Twenty teams entered the summer {tournament}.','스무 팀이 여름 토너먼트에 참가했어요.','tournament','A2','sports',1,'sports tournament bracket competition'),
('w_sports_A2_25','bench','/bentʃ/','noun','벤치, 후보 선수석','The seats where substitute players sit during a game.','He sat on the {bench} for most of the game.','그는 경기 대부분의 시간 동안 벤치에 앉아 있었어요.','bench','A2','sports',1,'substitute players bench sideline sport'),
('w_sports_A2_26','qualify','/ˈkwɒlɪfaɪ/','verb','예선을 통과하다','To reach the standard needed to enter a competition.','They worked hard to {qualify} for the final.','그들은 결승에 진출하기 위해 열심히 노력했어요.','qualify','A2','sports',1,'athlete qualifying round competition sport'),
('w_sports_A2_27','opponent','/əˈpoʊnənt/','noun','상대','A person or team that you compete against.','Respect your {opponent} no matter what.','어떤 상황에서도 상대를 존중하세요.','opponent','A2','sports',1,'athletes shaking hands respect opponent sport'),
('w_sports_A2_28','draw','/drɔː/','noun','무승부','A game where both sides finish with the same score.','The game ended in a {draw}, one to one.','경기는 1대1 무승부로 끝났어요.','draw','A2','sports',2,'scoreboard draw equal score football'),
('w_sports_A2_29','substitution','/ˌsʌbstɪˈtjuːʃən/','noun','교체','Replacing one player with another during a game.','The coach made a {substitution} in the second half.','코치가 후반전에 선수 교체를 했어요.','substitution','A2','sports',2,'football player substitution holding sign board'),
('w_sports_A2_30','final','/ˈfaɪnəl/','noun','결승전','The last and most important game in a competition.','Our team reached the {final} for the first time.','우리 팀이 처음으로 결승전에 진출했어요.','final','A2','sports',1,'sports final stadium crowd trophy ceremony'),
('w_sports_A2_31','physical','/ˈfɪzɪkəl/','adjective','신체적인','Relating to the body and its fitness.','Team sports are great for {physical} health.','단체 스포츠는 신체 건강에 아주 좋아요.','physical','A2','sports',2,'athlete physical fitness body training'),
('w_sports_A2_32','fan','/fæn/','noun','팬, 응원자','Someone who supports a particular team or sport.','The fans cheered loudly for their team.','팬들이 자신들의 팀을 위해 크게 응원했어요.','fan','A2','sports',1,'sports fans cheering stadium crowd flags'),
('w_sports_A2_33','gym','/dʒɪm/','noun','헬스장','A place where people go to exercise.','She goes to the {gym} after work every day.','그녀는 매일 퇴근 후 헬스장에 가요.','gym','A2','sports',1,'modern gym equipment workout fitness'),
('w_sports_A2_34','fitness','/ˈfɪtnəs/','noun','체력','The condition of being physically healthy and strong.','Regular sport improves your overall {fitness}.','규칙적인 운동은 전반적인 체력을 향상시켜요.','fitness','A2','sports',1,'fitness training outdoor athlete healthy'),
('w_sports_A2_35','opponent''s goal','/əˈpoʊnənts ɡoʊl/','phrase','상대편 골문','The goal belonging to the opposing team.','Try to kick the ball into the {opponent''s goal}.','공을 상대편 골문으로 차 넣으세요.','opponent''s goal','A2','sports',2,'football attacking opponent goal net');

-- ══════════════════════════════════════════════════════════════════════
-- WORDS — B1 (중급)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_sports_B1_01','tournament','/ˈtʊrnəmənt/','noun','토너먼트','A series of contests in which many players or teams compete to determine an overall winner.','Our club qualified for the regional {tournament} this year.','우리 클럽은 올해 지역 토너먼트에 진출했어요.','tournament','B1','sports',1,'regional tournament bracket matches sport'),
('w_sports_B1_02','strategy','/ˈstrætədʒi/','noun','전략','A plan designed to achieve a goal in a competition.','The coach explained the team''s {strategy} before kick-off.','코치는 킥오프 전에 팀의 전략을 설명했어요.','strategy','B1','sports',1,'coach whiteboard strategy formation tactics'),
('w_sports_B1_03','injury','/ˈɪndʒəri/','noun','부상','Physical damage or harm caused during sport.','He missed three games due to a knee {injury}.','그는 무릎 부상으로 세 경기에 결장했어요.','injury','B1','sports',1,'athlete knee injury treatment medical sport'),
('w_sports_B1_04','sportsmanship','/ˈspɔːrtsmənʃɪp/','noun','스포츠맨십','Fair and respectful behaviour in sport.','True {sportsmanship} means congratulating your opponent.','진정한 스포츠맨십은 상대방을 축하해 주는 것이에요.','sportsmanship','B1','sports',2,'athletes handshake respect sportsmanship field'),
('w_sports_B1_05','referee','/ˌrefəˈriː/','noun','심판','An official who ensures the rules are followed during a game.','The {referee} blew the whistle to stop play.','심판이 호루라기를 불어 경기를 멈췄어요.','referee','B1','sports',1,'referee whistle football yellow card'),
('w_sports_B1_06','penalty','/ˈpenəlti/','noun','패널티, 벌칙','A punishment given to a team or player for breaking the rules.','The player was awarded a {penalty} kick after the foul.','그 선수는 파울 후 페널티 킥을 얻었어요.','penalty','B1','sports',1,'penalty kick football spot goalkeeper'),
('w_sports_B1_07','sponsor','/ˈspɒnsər/','noun','후원자','A company or person who provides money to support a sports team.','The team''s main {sponsor} is a national airline.','팀의 주요 후원자는 국적 항공사예요.','sponsor','B1','sports',2,'sports sponsor logo jersey advertisement'),
('w_sports_B1_08','league','/liːɡ/','noun','리그','An organised competition among a number of teams.','They finished second in the national {league} last season.','그들은 지난 시즌 전국 리그에서 2위를 했어요.','league','B1','sports',1,'football league standings table season'),
('w_sports_B1_09','championship','/ˈtʃæmpiənʃɪp/','noun','선수권 대회','The most important competition in a particular sport.','Winning the {championship} was the team''s dream.','선수권 대회 우승은 팀의 꿈이었어요.','championship','B1','sports',1,'championship title celebration team trophy'),
('w_sports_B1_10','endurance','/ɪnˈdjʊərəns/','noun','지구력','The ability to maintain prolonged physical effort.','Marathon runners need exceptional {endurance}.','마라톤 선수는 뛰어난 지구력이 필요해요.','endurance','B1','sports',1,'marathon runner endurance long distance race'),
('w_sports_B1_11','formation','/fɔːrˈmeɪʃən/','noun','포메이션','The arrangement of players in a sports team.','The coach changed the {formation} at halftime.','코치가 하프타임에 포메이션을 바꿨어요.','formation','B1','sports',2,'football team formation tactical board'),
('w_sports_B1_12','transfer','/ˈtrænsf3ːr/','noun','이적','The movement of a player from one club to another.','The star striker completed a high-profile {transfer}.','그 스타 스트라이커는 주목받는 이적을 완료했어요.','transfer','B1','sports',2,'football player transfer signing pen deal'),
('w_sports_B1_13','suspension','/səˈspenʃən/','noun','출장 정지','A ban preventing a player from taking part in games.','He received a three-match {suspension} for the red card.','그는 레드카드로 3경기 출장 정지를 받았어요.','suspension','B1','sports',2,'referee red card player suspended sport'),
('w_sports_B1_14','substitute','/ˈsʌbstɪtjuːt/','noun','교체 선수','A player who replaces another during a match.','The {substitute} changed the entire game when he came on.','교체 선수가 들어오면서 경기 흐름이 완전히 바뀌었어요.','substitute','B1','sports',2,'substitute player warming up sideline'),
('w_sports_B1_15','consistency','/kənˈsɪstənsi/','noun','일관성','The quality of performing at the same high level.','Great athletes are valued for their {consistency}.','훌륭한 운동선수는 일관성 때문에 높이 평가받아요.','consistency','B1','sports',2,'athlete consistent training performance sport'),
('w_sports_B1_16','possession','/pəˈzeʃən/','noun','공 점유','Control of the ball during a game.','The home team had more {possession} in the second half.','홈팀이 후반전에 공 점유율이 더 높았어요.','possession','B1','sports',2,'football possession ball control midfield'),
('w_sports_B1_17','comeback','/ˈkʌmbæk/','noun','역전, 컴백','A return to success after a period of difficulty.','Down by three goals, the team made an incredible {comeback}.','세 골 뒤지던 팀이 믿을 수 없는 역전을 했어요.','comeback','B1','sports',1,'team celebrating comeback victory sport'),
('w_sports_B1_18','rivalry','/ˈraɪvəlri/','noun','경쟁 관계','A strong competition between two teams or athletes.','The two clubs have a long and fierce {rivalry}.','두 클럽은 오랜 치열한 라이벌 관계가 있어요.','rivalry','B1','sports',2,'rival teams match intense competition'),
('w_sports_B1_19','venue','/ˈvenjuː/','noun','경기 장소','The place where a sports event is held.','The {venue} for the final has not been announced yet.','결승전 장소는 아직 발표되지 않았어요.','venue','B1','sports',2,'sports venue arena stadium exterior'),
('w_sports_B1_20','qualification','/ˌkwɒlɪfɪˈkeɪʃən/','noun','예선 통과, 출전 자격','The process of reaching the required standard to enter a competition.','Their {qualification} for the World Cup was celebrated nationally.','월드컵 출전 자격을 얻은 것을 전국이 축하했어요.','qualification','B1','sports',1,'team qualifying celebration world cup sport'),
('w_sports_B1_21','momentum','/məˈmentəm/','noun','기세','The strength or force gained by doing something repeatedly.','The home side gained {momentum} after the equaliser.','동점 골 이후 홈팀이 기세를 탔어요.','momentum','B1','sports',2,'team celebrating gaining momentum sport'),
('w_sports_B1_22','highlight','/ˈhaɪlaɪt/','noun','하이라이트','The most exciting or memorable part of a game.','The overhead kick was the {highlight} of the match.','오버헤드킥이 경기의 하이라이트였어요.','highlight','B1','sports',1,'sports highlights reel TV broadcast'),
('w_sports_B1_23','knockout','/ˈnɒkaʊt/','noun','녹아웃 라운드','A stage of a competition where the loser is eliminated.','We advanced to the {knockout} stage of the tournament.','우리는 토너먼트 녹아웃 라운드에 진출했어요.','knockout','B1','sports',2,'sports knockout stage elimination bracket'),
('w_sports_B1_24','technique','/tekˈniːk/','noun','기술','A skilful way of doing something in sport.','Good {technique} is more important than raw strength.','좋은 기술은 단순한 힘보다 더 중요해요.','technique','B1','sports',1,'athlete demonstrating technique training sport'),
('w_sports_B1_25','discipline','/ˈdɪsɪplɪn/','noun','절제, 훈련','Training that produces orderly or controlled behaviour.','Success in sport requires tremendous {discipline}.','스포츠에서 성공하려면 엄청난 절제가 필요해요.','discipline','B1','sports',1,'athlete discipline training early morning sport'),
('w_sports_B1_26','offside','/ˈɒfsaɪd/','adjective','오프사이드의','In a position that is not allowed by the rules.','The goal was disallowed because the player was {offside}.','선수가 오프사이드 위치에 있어서 골이 취소됐어요.','offside','B1','sports',2,'offside rule football linesman flag'),
('w_sports_B1_27','assist','/əˈsɪst/','noun','어시스트','A pass or action that directly leads to a goal.','The winger got an {assist} for the winning goal.','윙어가 결승골을 만든 어시스트를 기록했어요.','assist','B1','sports',2,'football player assist pass goal celebrate'),
('w_sports_B1_28','overtime','/ˈoʊvətaɪm/','noun','연장전','Extra time played when a game is tied at the end.','The match went to {overtime} after a late equaliser.','경기는 후반 막판 동점 골 이후 연장전에 들어갔어요.','overtime','B1','sports',2,'extra time overtime football tired players'),
('w_sports_B1_29','recover','/rɪˈkʌvər/','verb','회복하다','To return to normal health or ability after an injury.','She worked hard to {recover} from her ankle injury.','그녀는 발목 부상에서 회복하기 위해 열심히 노력했어요.','recover','B1','sports',1,'athlete recovering physiotherapy treatment'),
('w_sports_B1_30','debut','/ˈdeɪbjuː/','noun','데뷔','The first performance or appearance in a sport.','The young midfielder made his professional {debut} today.','그 어린 미드필더가 오늘 프로 데뷔를 했어요.','debut','B1','sports',2,'young athlete debut first match sport'),
('w_sports_B1_31','spectator','/spekˈteɪtər/','noun','관중','A person who watches a sporting event.','Thousands of {spectators} packed the stadium.','수천 명의 관중이 경기장을 가득 채웠어요.','spectator','B1','sports',2,'spectators stadium crowd watching sport'),
('w_sports_B1_32','upset','/ˈʌpset/','noun','이변','A surprising result where a weaker team beats a stronger one.','The minnows caused a major {upset} by beating the champions.','약체가 챔피언을 꺾는 큰 이변을 일으켰어요.','upset','B1','sports',2,'underdog team celebrating upset victory'),
('w_sports_B1_33','tactical','/ˈtæktɪkəl/','adjective','전술적인','Relating to the plan used to win in a competition.','The coach made a {tactical} substitution to protect the lead.','코치는 리드를 지키기 위해 전술적 교체를 했어요.','tactical','B1','sports',2,'tactical board coach strategy planning'),
('w_sports_B1_34','dominant','/ˈdɒmɪnənt/','adjective','지배적인','More powerful or better than everything else.','The champion was completely {dominant} throughout the match.','챔피언은 경기 내내 완전히 지배적이었어요.','dominant','B1','sports',2,'dominant team winning sport competition'),
('w_sports_B1_35','morale','/məˈrɑːl/','noun','사기','The confidence and enthusiasm of a group.','Team {morale} soared after the unexpected win.','예상치 못한 승리 후 팀 사기가 크게 올랐어요.','morale','B1','sports',2,'team high morale celebrating victory sport');

-- ══════════════════════════════════════════════════════════════════════
-- WORDS — B2 (중상급)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_sports_B2_01','analytics','/ˌænəˈlɪtɪks/','noun','데이터 분석','The use of data to analyse performance in sport.','Modern clubs rely heavily on {analytics} to improve results.','현대 구단들은 성과 향상을 위해 데이터 분석에 크게 의존해요.','analytics','B2','sports',1,'sports analytics data screen laptop statistics'),
('w_sports_B2_02','biomechanics','/ˌbaɪoʊmɪˈkænɪks/','noun','생체역학','The study of the mechanical laws relating to movement of living organisms.','Coaches use {biomechanics} to refine an athlete''s running form.','코치들은 선수의 달리기 자세를 개선하기 위해 생체역학을 활용해요.','biomechanics','B2','sports',2,'biomechanics motion capture sport lab'),
('w_sports_B2_03','doping','/ˈdoʊpɪŋ/','noun','도핑','The use of banned performance-enhancing substances.','The athlete was disqualified after testing positive for {doping}.','그 선수는 도핑 양성 반응 후 자격을 박탈당했어요.','doping','B2','sports',1,'anti doping test sport athlete lab'),
('w_sports_B2_04','physiotherapy','/ˌfɪzioʊˈθerəpi/','noun','물리 치료','Treatment of injury through physical methods such as massage and exercise.','She underwent six weeks of {physiotherapy} after the surgery.','그녀는 수술 후 6주간 물리 치료를 받았어요.','physiotherapy','B2','sports',1,'physiotherapy athlete treatment massage rehab'),
('w_sports_B2_05','periodization','/ˌpɪəriədaɪˈzeɪʃən/','noun','주기화 훈련','The systematic planning of athletic training into cycles.','Elite coaches use {periodization} to peak performance at the right time.','엘리트 코치들은 적절한 시기에 최고 컨디션을 발휘하기 위해 주기화 훈련을 사용해요.','periodization','B2','sports',2,'training schedule plan periodization sport calendar'),
('w_sports_B2_06','agility','/əˈdʒɪlɪti/','noun','민첩성','The ability to move quickly and change direction easily.','Footballers develop their {agility} through ladder drills.','축구 선수들은 사다리 드릴로 민첩성을 키워요.','agility','B2','sports',1,'athlete agility drill ladder cone sport'),
('w_sports_B2_07','stamina','/ˈstæmɪnə/','noun','스태미나, 체력','The ability to sustain prolonged physical effort.','Building {stamina} is key to performing well over a full match.','경기 내내 좋은 퍼포먼스를 위해 스태미나를 키우는 것이 핵심이에요.','stamina','B2','sports',1,'endurance running stamina athlete training'),
('w_sports_B2_08','sprint','/sprɪnt/','noun','단거리 전력 질주','A short burst of running at maximum speed.','His explosive {sprint} in the final metres won the race.','마지막 몇 미터에서의 폭발적인 질주가 경주를 이기게 했어요.','sprint','B2','sports',1,'sprinter explosive start race track sport'),
('w_sports_B2_09','tactical','/ˈtæktɪkəl/','adjective','전술적인 (고급)','Carefully planned to achieve a specific advantage in competition.','A {tactical} foul prevented a clear goal-scoring opportunity.','전술적 파울이 명확한 득점 기회를 막았어요.','tactical','B2','sports',2,'coach tactical board drawing formation'),
('w_sports_B2_10','performance','/pərˈfɔːrməns/','noun','퍼포먼스','How well an athlete or team performs.','The team''s {performance} improved significantly after new training methods.','새로운 훈련 방법 도입 후 팀 퍼포먼스가 크게 향상됐어요.','performance','B2','sports',1,'athlete peak performance training sport data'),
('w_sports_B2_11','concede','/kənˈsiːd/','verb','(골을) 내주다','To allow the opposing team to score.','They {conceded} three goals in the opening twenty minutes.','그들은 전반 20분 만에 세 골을 내줬어요.','concede','B2','sports',2,'goalkeeper conceding goal sad sport'),
('w_sports_B2_12','rehabilitation','/ˌriːhəˌbɪlɪˈteɪʃən/','noun','재활','The process of recovering and restoring full function after injury.','The player''s {rehabilitation} took six months.','선수의 재활은 6개월이 걸렸어요.','rehabilitation','B2','sports',1,'athlete rehabilitation exercises recovery clinic'),
('w_sports_B2_13','conditioning','/kənˈdɪʃənɪŋ/','noun','컨디셔닝, 신체 조련','A training programme to develop physical fitness.','Pre-season {conditioning} is essential for avoiding injuries.','시즌 전 컨디셔닝은 부상 예방에 필수적이에요.','conditioning','B2','sports',2,'athlete conditioning training fitness gym sport'),
('w_sports_B2_14','velocity','/vəˈlɒsɪti/','noun','속도 (물리)','The speed of something in a particular direction.','The ball''s {velocity} was measured at ninety kilometres per hour.','공의 속도는 시속 90킬로미터로 측정됐어요.','velocity','B2','sports',2,'ball velocity speed measurement sport science'),
('w_sports_B2_15','overtraining','/ˌoʊvəˈtreɪnɪŋ/','noun','과훈련','Excessive training that impairs performance and causes health issues.','{Overtraining} can lead to injury and burnout.','과훈련은 부상과 번아웃으로 이어질 수 있어요.','Overtraining','B2','sports',2,'athlete overtraining exhausted injured tired'),
('w_sports_B2_16','pacing','/ˈpeɪsɪŋ/','noun','페이싱','Managing your speed and energy throughout a race.','Good {pacing} is crucial in long-distance events.','장거리 종목에서 좋은 페이싱은 매우 중요해요.','pacing','B2','sports',2,'marathon runner pacing race distance sport'),
('w_sports_B2_17','flexibility','/ˌfleksɪˈbɪlɪti/','noun','유연성','The range of movement in muscles and joints.','Yoga improves {flexibility} for athletes.','요가는 운동선수의 유연성을 향상시켜요.','flexibility','B2','sports',2,'athlete stretching flexibility yoga sport'),
('w_sports_B2_18','acceleration','/əkˌseləˈreɪʃən/','noun','가속','An increase in speed over a short period.','His explosive {acceleration} makes him hard to defend.','그의 폭발적인 가속은 수비하기 어렵게 만들어요.','acceleration','B2','sports',2,'sprinter explosive acceleration start race'),
('w_sports_B2_19','dehydration','/ˌdiːhaɪˈdreɪʃən/','noun','탈수','The condition caused by losing more fluids than you take in.','Athletes must prevent {dehydration} during intense exercise.','운동선수들은 격렬한 운동 중 탈수를 예방해야 해요.','dehydration','B2','sports',1,'athlete drinking water preventing dehydration'),
('w_sports_B2_20','core strength','/kɔːr streŋθ/','noun','코어 근력','The strength of the muscles in the abdomen and back.','Developing {core strength} improves balance and stability.','코어 근력을 키우면 균형과 안정성이 향상돼요.','core strength','B2','sports',1,'athlete core strength exercise plank fitness'),
('w_sports_B2_21','prototype','/ˈproʊtətaɪp/','noun','기술 원형','An original model from which other forms are developed.','This training method is the {prototype} for modern fitness plans.','이 훈련 방법은 현대 체력 훈련의 원형이에요.','prototype','B2','sports',3,'prototype training method sport science'),
('w_sports_B2_22','physiological','/ˌfɪziəˈlɒdʒɪkəl/','adjective','생리적인','Relating to the way living bodies function.','Athletes undergo {physiological} testing before major competitions.','선수들은 주요 대회 전에 생리학적 검사를 받아요.','physiological','B2','sports',2,'physiological testing athlete lab sport'),
('w_sports_B2_23','overload','/ˌoʊvəˈloʊd/','noun','과부하 훈련','Training above the body''s current capacity to stimulate adaptation.','Progressive {overload} is fundamental to strength gains.','점진적 과부하는 근력 향상의 기본이에요.','overload','B2','sports',2,'progressive overload weightlifting gym training'),
('w_sports_B2_24','adaptation','/ˌædæpˈteɪʃən/','noun','적응','The body''s response to a training stimulus over time.','Muscle {adaptation} happens when athletes train consistently.','꾸준히 훈련할 때 근육 적응이 일어나요.','adaptation','B2','sports',2,'muscle adaptation training sport science'),
('w_sports_B2_25','sport psychology','/spɔːrt saɪˈkɒlədʒi/','noun','스포츠 심리학','The study of how mental factors affect physical performance.','Many elite athletes work with a {sport psychology} consultant.','많은 엘리트 선수들이 스포츠 심리학 상담사와 함께 일해요.','sport psychology','B2','sports',2,'athlete sport psychology mental coach'),
('w_sports_B2_26','diet','/ˈdaɪət/','noun','식단','A controlled way of eating to improve performance.','The coach recommended a high-protein {diet} for the athletes.','코치는 선수들에게 고단백 식단을 추천했어요.','diet','B2','sports',1,'athlete healthy diet nutrition meal prep'),
('w_sports_B2_27','reaction time','/riˈækʃən taɪm/','noun','반응 속도','The time taken to respond to a stimulus.','Sprinters work to improve their {reaction time} off the blocks.','단거리 선수들은 출발대에서의 반응 속도를 향상시키기 위해 노력해요.','reaction time','B2','sports',2,'sprinter reaction time start blocks race'),
('w_sports_B2_28','benchmark','/ˈbentʃmɑːrk/','noun','기준점, 벤치마크','A standard used to measure performance.','The player set a new {benchmark} for assists in a single season.','그 선수는 한 시즌 어시스트에서 새로운 기준점을 세웠어요.','benchmark','B2','sports',2,'sport performance benchmark statistics data'),
('w_sports_B2_29','resilience','/rɪˈzɪliəns/','noun','회복 탄력성','The ability to recover quickly from difficulties.','Mental {resilience} separates good athletes from great ones.','정신적 회복 탄력성이 좋은 선수와 훌륭한 선수를 구분해요.','resilience','B2','sports',1,'athlete resilience comeback mental strength sport'),
('w_sports_B2_30','hydration','/haɪˈdreɪʃən/','noun','수분 보충','The process of providing the body with adequate fluids.','Proper {hydration} before a match is essential.','경기 전 적절한 수분 보충은 필수예요.','hydration','B2','sports',1,'athlete hydration water bottle sport'),
('w_sports_B2_31','rotation','/roʊˈteɪʃən/','noun','로테이션, 선수 순환','The regular switching of players to manage fatigue.','Squad {rotation} helps prevent injuries during a long season.','긴 시즌 동안 부상을 예방하기 위해 선수 로테이션이 도움이 돼요.','rotation','B2','sports',2,'squad rotation substitution players sport'),
('w_sports_B2_32','diagnostics','/ˌdaɪəɡˈnɒstɪks/','noun','진단 분석','Tests used to assess an athlete''s physical condition.','Pre-season {diagnostics} revealed muscle imbalances in several players.','시즌 전 진단 분석에서 여러 선수들의 근육 불균형이 발견됐어요.','diagnostics','B2','sports',2,'sports diagnostics testing athlete physical'),
('w_sports_B2_33','intensity','/ɪnˈtensɪti/','noun','강도','The level of effort applied during training or competition.','Training {intensity} should be gradually increased each week.','훈련 강도는 매주 점진적으로 높여야 해요.','intensity','B2','sports',1,'high intensity training athlete workout sport'),
('w_sports_B2_34','load management','/loʊd ˈmænɪdʒmənt/','noun','부하 관리','Controlling an athlete''s workload to prevent injury.','{Load management} is increasingly common among elite basketball players.','부하 관리는 엘리트 농구 선수들 사이에서 점점 더 보편화되고 있어요.','load management','B2','sports',2,'athlete load management rest schedule sport'),
('w_sports_B2_35','counterattack','/ˈkaʊntərətæk/','noun','역습','A sudden attack launched after defending.','The team scored from a swift {counterattack}.','팀은 빠른 역습으로 득점했어요.','counterattack','B2','sports',2,'football counterattack fast break goal sport');

-- ══════════════════════════════════════════════════════════════════════
-- WORDS — C1 (고급)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_sports_C1_01','kinesiology','/kɪˌniːsiˈɒlədʒi/','noun','운동학','The scientific study of human movement.','A degree in {kinesiology} opens careers in coaching and therapy.','운동학 학위는 코칭과 치료 분야의 경력을 열어줘요.','kinesiology','C1','sports',2,'kinesiology lab movement study sport science'),
('w_sports_C1_02','ergodynamics','/ˌɜːrɡoʊdaɪˈnæmɪks/','noun','인체 동역학','The study of energy expenditure and movement efficiency.','Coaches study {ergodynamics} to improve an athlete''s movement economy.','코치들은 선수의 동작 효율성을 높이기 위해 인체 동역학을 연구해요.','ergodynamics','C1','sports',3,'ergodynamics movement efficiency sport science lab'),
('w_sports_C1_03','proprioception','/ˌproʊpriəˈsepʃən/','noun','고유 감각','The body''s sense of its own position and movement.','{Proprioception} training reduces the risk of ankle sprains.','고유 감각 훈련은 발목 염좌 위험을 줄여요.','proprioception','C1','sports',2,'balance training proprioception athlete sport'),
('w_sports_C1_04','VO2 max','/ˌviː oʊ ˈtuː mæks/','noun','최대 산소 섭취량','The maximum rate of oxygen consumption during intense exercise.','Elite endurance athletes have very high {VO2 max} values.','엘리트 지구력 선수들은 매우 높은 최대 산소 섭취량을 가져요.','VO2 max','C1','sports',2,'vo2 max testing athlete treadmill lab oxygen'),
('w_sports_C1_05','lactate threshold','/ˈlækteɪt ˈθreʃhoʊld/','noun','젖산 역치','The exercise intensity at which lactate accumulates in the blood.','Training near the {lactate threshold} improves aerobic capacity.','젖산 역치 근처에서의 훈련은 유산소 능력을 향상시켜요.','lactate threshold','C1','sports',2,'lactate threshold blood test sport science'),
('w_sports_C1_06','periodization','/ˌpɪəriədaɪˈzeɪʃən/','noun','주기화 (고급)','A systematic approach to training cycles including base, peak, and taper phases.','Advanced {periodization} schedules training over an entire quadrennium.','고급 주기화는 4년 전체에 걸쳐 훈련 일정을 계획해요.','periodization','C1','sports',3,'elite training periodization macrocycle planning'),
('w_sports_C1_07','sport psychology','/spɔːrt saɪˈkɒlədʒi/','noun','스포츠 심리학 (고급)','The specialist field examining mental processes in elite performance.','The team''s {sport psychology} consultant improved focus under pressure.','팀의 스포츠 심리학 상담사가 압박 상황에서의 집중력을 높여줬어요.','sport psychology','C1','sports',2,'sport psychology mental training elite athlete'),
('w_sports_C1_08','concussion','/kənˈkʌʃən/','noun','뇌진탕','A brain injury caused by a blow to the head.','Repeated {concussions} can have serious long-term effects.','반복적인 뇌진탕은 심각한 장기적 영향을 미칠 수 있어요.','concussion','C1','sports',1,'concussion protocol sport injury head'),
('w_sports_C1_09','ethics','/ˈeθɪks/','noun','윤리','The moral principles governing behaviour in sport.','Questions of {ethics} arise in debates about doping and fair play.','도핑과 페어플레이에 관한 논쟁에서 윤리적 문제가 제기돼요.','ethics','C1','sports',2,'sport ethics integrity fair play discussion'),
('w_sports_C1_10','governance','/ˈɡʌvənəns/','noun','거버넌스, 관리 체계','The system by which a sports organisation is controlled.','Weak {governance} in governing bodies has led to corruption scandals.','스포츠 단체의 취약한 거버넌스는 부패 스캔들로 이어졌어요.','governance','C1','sports',2,'sports governance organisation board meeting'),
('w_sports_C1_11','neuromuscular','/ˌnjʊəroʊˈmʌskjʊlər/','adjective','신경근의','Relating to both the nervous system and the muscles.','{Neuromuscular} efficiency determines reaction speed.','신경근 효율성이 반응 속도를 결정해요.','neuromuscular','C1','sports',3,'neuromuscular system sport training science'),
('w_sports_C1_12','proprioceptive','/ˌproʊpriəˈseptɪv/','adjective','고유 감각의','Relating to stimuli arising from within the body.','Balance boards develop {proprioceptive} awareness.','밸런스 보드는 고유 감각적 인식을 발달시켜요.','proprioceptive','C1','sports',3,'balance board proprioceptive training sport'),
('w_sports_C1_13','muscle hypertrophy','/ˈmʌsəl haɪˈpɜːtrəfi/','noun','근비대','The increase in muscle size resulting from exercise.','Resistance training causes {muscle hypertrophy} over time.','저항 운동은 시간이 지남에 따라 근비대를 유발해요.','muscle hypertrophy','C1','sports',2,'muscle hypertrophy strength training gym'),
('w_sports_C1_14','anaerobic','/ˌænəˈroʊbɪk/','adjective','무산소의','Relating to exercise that does not rely on oxygen.','Short sprints are an {anaerobic} activity.','단거리 달리기는 무산소 운동이에요.','anaerobic','C1','sports',2,'anaerobic training sprint intense sport'),
('w_sports_C1_15','aerobic','/eɪˈroʊbɪk/','adjective','유산소의','Relating to exercise that uses oxygen to generate energy.','{Aerobic} capacity is vital for distance runners.','유산소 능력은 장거리 선수에게 매우 중요해요.','aerobic','C1','sports',2,'aerobic exercise running cycling endurance'),
('w_sports_C1_16','overreaching','/ˌoʊvərˈriːtʃɪŋ/','noun','단기 과훈련','A short-term training overload that can improve performance if followed by rest.','Planned {overreaching} is different from harmful overtraining.','계획된 단기 과훈련은 해로운 과훈련과는 달라요.','overreaching','C1','sports',3,'athlete overreaching training cycle rest'),
('w_sports_C1_17','detraining','/ˌdiːˈtreɪnɪŋ/','noun','탈훈련','The partial or complete loss of training adaptations due to inactivity.','{Detraining} effects begin within two weeks of stopping exercise.','운동을 중단한 지 2주 이내에 탈훈련 효과가 나타나요.','detraining','C1','sports',3,'athlete rest detraining fitness loss'),
('w_sports_C1_18','kinematic','/ˌkɪnɪˈmætɪk/','adjective','운동학적인','Relating to the geometry and pattern of motion.','{Kinematic} analysis revealed inefficiencies in her throwing technique.','운동학적 분석으로 그녀의 투구 기술에서 비효율성이 드러났어요.','kinematic','C1','sports',3,'kinematic analysis motion capture sport'),
('w_sports_C1_19','isometric','/ˌaɪsəˈmetrɪk/','adjective','등척성의','Relating to muscular contraction where length remains the same.','Wall sits are a common {isometric} exercise.','벽에 기댄 스쿼트는 일반적인 등척성 운동이에요.','isometric','C1','sports',2,'isometric exercise wall sit strength training'),
('w_sports_C1_20','eccentric','/ɪkˈsentrɪk/','adjective','신장성 수축의','Describing muscle contractions that lengthen the muscle under load.','{Eccentric} loading builds tendon strength.','신장성 부하는 힘줄 강도를 키워요.','eccentric','C1','sports',3,'eccentric exercise Nordic hamstring sport'),
('w_sports_C1_21','tendinopathy','/ˌtendɪˈnɒpəθi/','noun','건병증','A condition causing pain and dysfunction in a tendon.','Repeated jumping can cause {tendinopathy} in the knee.','반복적인 점프는 무릎 건병증을 일으킬 수 있어요.','tendinopathy','C1','sports',3,'tendinopathy knee pain athlete treatment'),
('w_sports_C1_22','thermoregulation','/ˌθɜːrmoʊˌreɡjʊˈleɪʃən/','noun','체온 조절','The process by which the body maintains its core temperature.','Athletes train their {thermoregulation} before competing in hot climates.','선수들은 더운 기후에서 경쟁하기 전에 체온 조절 능력을 훈련해요.','thermoregulation','C1','sports',3,'athlete heat training thermoregulation sport'),
('w_sports_C1_23','glycogen','/ˈɡlaɪkədʒən/','noun','글리코겐','A form of glucose stored in muscles and the liver for energy.','Depleting {glycogen} stores causes fatigue during long races.','글리코겐 저장량이 고갈되면 장거리 레이스 중 피로가 생겨요.','glycogen','C1','sports',2,'glycogen energy store muscle sport science'),
('w_sports_C1_24','cognitive load','/ˈkɒɡnɪtɪv loʊd/','noun','인지 부하','The mental effort required to process information under pressure.','High {cognitive load} in elite sport affects decision-making.','엘리트 스포츠에서의 높은 인지 부하는 의사결정에 영향을 미쳐요.','cognitive load','C1','sports',3,'athlete decision making pressure sport psychology'),
('w_sports_C1_25','cardiac output','/ˈkɑːrdiæk ˈaʊtpʊt/','noun','심박출량','The volume of blood the heart pumps per minute.','Endurance training increases {cardiac output}.','지구력 훈련은 심박출량을 증가시켜요.','cardiac output','C1','sports',3,'cardiac output heart rate endurance athlete'),
('w_sports_C1_26','force production','/fɔːrs prəˈdʌkʃən/','noun','힘 생성 능력','The ability of muscles to generate mechanical force.','Weightlifters train specifically to increase {force production}.','역도 선수들은 힘 생성 능력을 높이기 위해 특별히 훈련해요.','force production','C1','sports',3,'force production weightlifting power sport'),
('w_sports_C1_27','anthropometry','/ˌænθrəˈpɒmɪtri/','noun','인체 측정학','The measurement of the human body and its proportions.','Sports teams use {anthropometry} to screen potential recruits.','스포츠 팀은 잠재적 선발 선수를 선별하기 위해 인체 측정학을 활용해요.','anthropometry','C1','sports',3,'anthropometry body measurement sport science'),
('w_sports_C1_28','motor learning','/ˈmoʊtər ˈlɜːrnɪŋ/','noun','운동 학습','The process of acquiring and refining physical skills.','{Motor learning} principles guide coaching methodology.','운동 학습 원리가 코칭 방법론을 안내해요.','motor learning','C1','sports',3,'motor learning skill acquisition sport coaching'),
('w_sports_C1_29','fatigue resistance','/fəˈtiːɡ rɪˈzɪstəns/','noun','피로 저항성','The ability to maintain performance despite accumulating fatigue.','Interval training builds {fatigue resistance} over time.','인터벌 훈련은 시간이 지남에 따라 피로 저항성을 키워요.','fatigue resistance','C1','sports',2,'fatigue resistance training endurance athlete'),
('w_sports_C1_30','power-to-weight ratio','/ˈpaʊər tə weɪt ˈreɪʃioʊ/','noun','체중 대비 파워 비율','The amount of power generated relative to body mass.','Cyclists obsess over their {power-to-weight ratio}.','사이클리스트들은 체중 대비 파워 비율에 집착해요.','power-to-weight ratio','C1','sports',3,'cycling power weight ratio sport science'),
('w_sports_C1_31','deceleration','/diːˌseləˈreɪʃən/','noun','감속','A decrease in speed; also used in injury prevention training.','Controlled {deceleration} training prevents hamstring injuries.','통제된 감속 훈련은 햄스트링 부상을 예방해요.','deceleration','C1','sports',3,'deceleration training sport injury prevention'),
('w_sports_C1_32','sport nutrition','/spɔːrt njuːˈtrɪʃən/','noun','스포츠 영양학','The study and practice of diet in relation to athletic performance.','A qualified {sport nutrition} specialist advises the squad.','자격을 갖춘 스포츠 영양학 전문가가 스쿼드에 자문을 제공해요.','sport nutrition','C1','sports',2,'sport nutrition food planning athlete meal'),
('w_sports_C1_33','maximal strength','/ˈmæksɪməl streŋθ/','noun','최대 근력','The greatest force a muscle can produce in one effort.','Olympic lifters aim to maximise {maximal strength}.','올림픽 역도 선수들은 최대 근력을 극대화하는 것을 목표로 해요.','maximal strength','C1','sports',3,'maximal strength testing weightlifting sport'),
('w_sports_C1_34','reactive strength','/riˈæktɪv streŋθ/','noun','반응 근력','The ability to quickly switch from an eccentric to concentric contraction.','Depth jumps develop {reactive strength} in athletes.','뎁스 점프는 선수들의 반응 근력을 키워요.','reactive strength','C1','sports',3,'reactive strength plyometric jump training'),
('w_sports_C1_35','energy systems','/ˈenədʒi ˈsɪstəmz/','noun','에너지 시스템','The physiological pathways used to produce energy during exercise.','Coaches must understand {energy systems} to design effective training.','코치들은 효과적인 훈련을 설계하기 위해 에너지 시스템을 이해해야 해요.','energy systems','C1','sports',2,'energy systems sport science physiology diagram');

-- ══════════════════════════════════════════════════════════════════════
-- WORDS — C2 (최고급)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_sports_C2_01','anthropometry','/ˌænθrəˈpɒmɪtri/','noun','인체 측정학 (C2)','The precise scientific measurement of body dimensions for performance optimisation.','Longitudinal {anthropometry} data reveal growth patterns in young athletes.','종단적 인체 측정 데이터는 청소년 선수들의 성장 패턴을 밝혀요.','anthropometry','C2','sports',3,'anthropometry precise measurement sport science research'),
('w_sports_C2_02','biomechanical','/ˌbaɪoʊmɪˈkænɪkəl/','adjective','생체역학적','Relating to the mechanical analysis of biological movement.','A {biomechanical} assessment identified asymmetries in her stride.','생체역학적 평가로 그녀의 보폭 비대칭이 확인됐어요.','biomechanical','C2','sports',3,'biomechanical assessment lab motion capture sport'),
('w_sports_C2_03','neuromotor','/ˌnjʊəroʊˈmoʊtər/','adjective','신경운동의','Relating to the interaction between the nervous system and muscle movement.','Elite skill acquisition depends on {neuromotor} plasticity.','엘리트 기술 습득은 신경운동 가소성에 의존해요.','neuromotor','C2','sports',3,'neuromotor training sport science plasticity'),
('w_sports_C2_04','chronobiology','/ˌkrɒnoʊbaɪˈɒlədʒi/','noun','시간생물학','The study of biological rhythms and their effect on performance.','Coaches apply {chronobiology} to schedule optimal training times.','코치들은 최적의 훈련 시간을 정하기 위해 시간생물학을 적용해요.','chronobiology','C2','sports',3,'chronobiology circadian rhythm sport science training'),
('w_sports_C2_05','ergogenic','/ˌɜːrɡəˈdʒenɪk/','adjective','운동 능력 향상의','Tending to enhance physical performance, stamina, or recovery.','Caffeine is a legal {ergogenic} aid used widely in sport.','카페인은 스포츠에서 널리 사용되는 합법적인 운동 능력 향상 보조제예요.','ergogenic','C2','sports',3,'ergogenic aid caffeine sport performance supplement'),
('w_sports_C2_06','myofascial','/ˌmaɪoʊˈfæʃiəl/','adjective','근막의','Relating to the fascia — the connective tissue surrounding muscles.','{Myofascial} release techniques reduce muscle tension after training.','근막 이완 기법은 훈련 후 근육 긴장을 완화해요.','myofascial','C2','sports',3,'myofascial release foam roller muscle recovery'),
('w_sports_C2_07','tensiomyography','/ˌtensiˈɒmɪɒɡrəfi/','noun','근수축 측정법','A non-invasive technique measuring mechanical properties of muscles.','Clubs use {tensiomyography} to monitor muscle fatigue between matches.','구단들은 경기 사이의 근육 피로를 모니터링하기 위해 근수축 측정법을 사용해요.','tensiomyography','C2','sports',3,'tensiomyography muscle measurement sport science'),
('w_sports_C2_08','isometric','/ˌaɪsəˈmetrɪk/','adjective','등척성의 (C2)','Describing contractions in which muscle length does not change, used in injury rehab and strength development.','Heavy {isometric} holds have been shown to reduce tendon pain.','무거운 등척성 유지는 힘줄 통증을 줄이는 것으로 나타났어요.','isometric','C2','sports',3,'isometric hold strength tendon rehab sport'),
('w_sports_C2_09','plyometrics','/ˌplaɪəˈmetrɪks/','noun','플라이오메트릭스','Exercises involving rapid stretching and contracting of muscles to develop explosive power.','The athlete added {plyometrics} to her weekly schedule to improve jumping ability.','그 선수는 점프 능력을 향상시키기 위해 주간 일정에 플라이오메트릭스를 추가했어요.','plyometrics','C2','sports',2,'plyometrics box jump explosive power training'),
('w_sports_C2_10','psychomotor','/ˌsaɪkoʊˈmoʊtər/','adjective','심리운동의','Relating to movement that is initiated or influenced by mental processes.','The drill tested both {psychomotor} and decision-making skills.','그 훈련은 심리운동 능력과 의사결정 능력을 모두 테스트했어요.','psychomotor','C2','sports',3,'psychomotor skill sport decision making training'),
('w_sports_C2_11','epigenetics','/ˌepɪdʒɪˈnetɪks/','noun','후성유전학','The study of changes in gene expression without changes in DNA sequence.','Research into {epigenetics} may explain why some athletes respond better to training.','후성유전학 연구는 일부 선수들이 훈련에 더 잘 반응하는 이유를 설명할 수 있어요.','epigenetics','C2','sports',3,'epigenetics sport science gene expression research'),
('w_sports_C2_12','sarcopenia','/ˌsɑːrkəˈpiːniə/','noun','근감소증','The age-related loss of muscle mass and strength.','Masters athletes train to counteract {sarcopenia}.','마스터스 선수들은 근감소증에 대응하기 위해 훈련해요.','sarcopenia','C2','sports',3,'sarcopenia muscle loss aging sport science'),
('w_sports_C2_13','mechanotransduction','/ˌmekənoʊtrænsˈdʌkʃən/','noun','기계적 자극 전달','The process by which cells convert mechanical stimuli into biological signals.','Understanding {mechanotransduction} informs tendon loading protocols.','기계적 자극 전달을 이해하면 힘줄 부하 프로토콜을 개선할 수 있어요.','mechanotransduction','C2','sports',3,'mechanotransduction tendon cell biology sport'),
('w_sports_C2_14','polyarticular','/ˌpɒliɑːrˈtɪkjʊlər/','adjective','다관절의','Involving multiple joints in a single movement pattern.','Squats are a {polyarticular} exercise that trains the whole lower body.','스쿼트는 하체 전체를 훈련하는 다관절 운동이에요.','polyarticular','C2','sports',3,'polyarticular movement squat strength training'),
('w_sports_C2_15','fascicle','/ˈfæsɪkəl/','noun','근속','A bundle of muscle fibres within a muscle.','Ultrasound imaging measures changes in {fascicle} length during contraction.','초음파 영상은 수축 중 근속 길이 변화를 측정해요.','fascicle','C2','sports',3,'muscle fascicle ultrasound sport science lab'),
('w_sports_C2_16','catecholamines','/kəˈtekələˌmiːnz/','noun','카테콜아민','Stress hormones such as adrenaline that affect exercise performance.','Intense exercise causes a surge in {catecholamines}.','격렬한 운동은 카테콜아민의 급격한 증가를 유발해요.','catecholamines','C2','sports',3,'catecholamines stress hormones exercise science'),
('w_sports_C2_17','lactate kinetics','/ˈlækteɪt kɪˈnetɪks/','noun','젖산 동역학','The rates of lactate production and clearance during exercise.','Elite cyclists have favourable {lactate kinetics} at race pace.','엘리트 사이클리스트들은 레이스 속도에서 유리한 젖산 동역학을 가져요.','lactate kinetics','C2','sports',3,'lactate kinetics blood testing sport science'),
('w_sports_C2_18','neuromuscular junction','/ˌnjʊəroʊˈmʌskjʊlər ˈdʒʌŋkʃən/','noun','신경근 접합부','The synapse between a motor neuron and a muscle fibre.','Signals cross the {neuromuscular junction} in milliseconds.','신호는 신경근 접합부를 밀리초 만에 통과해요.','neuromuscular junction','C2','sports',3,'neuromuscular junction signal muscle sport science'),
('w_sports_C2_19','metabolic equivalent','/ˌmetəˈbɒlɪk ɪˈkwɪvələnt/','noun','대사 당량','A unit of energy expenditure used to classify physical activities.','Running at 10 km/h has a {metabolic equivalent} of around ten.','시속 10km 달리기는 대사 당량이 약 10이에요.','metabolic equivalent','C2','sports',3,'metabolic equivalent exercise intensity sport science'),
('w_sports_C2_20','sport genomics','/spɔːrt dʒɪˈnoʊmɪks/','noun','스포츠 유전체학','The use of genomic data to understand talent and injury susceptibility.','Advances in {sport genomics} may personalise training programmes.','스포츠 유전체학의 발전은 훈련 프로그램을 개인화할 수 있어요.','sport genomics','C2','sports',3,'sport genomics DNA testing athlete research'),
('w_sports_C2_21','fasciotomy','/ˌfæsiˈɒtəmi/','noun','근막 절개술','Surgical incision of the fascia to relieve pressure.','The sprinter required an emergency {fasciotomy} after a muscle compartment syndrome.','단거리 선수는 근육 구획 증후군 후 응급 근막 절개술이 필요했어요.','fasciotomy','C2','sports',3,'fasciotomy surgical sport injury treatment'),
('w_sports_C2_22','neuroendocrine','/ˌnjʊəroʊˈendəkrɪn/','adjective','신경내분비의','Relating to cells that receive neural inputs and release hormones.','{Neuroendocrine} responses to exercise modulate recovery.','운동에 대한 신경내분비 반응이 회복을 조절해요.','neuroendocrine','C2','sports',3,'neuroendocrine response exercise science hormones'),
('w_sports_C2_23','viscoelasticity','/ˌvɪskoʊɪˌlæsˈtɪsɪti/','noun','점탄성','The property of materials that exhibit both viscous and elastic behaviour.','Tendons exhibit {viscoelasticity} which affects how they store energy.','힘줄은 에너지를 저장하는 방식에 영향을 미치는 점탄성을 나타내요.','viscoelasticity','C2','sports',3,'viscoelasticity tendon elastic energy sport science'),
('w_sports_C2_24','somatotype','/ˈsoʊmətətaɪp/','noun','체형 유형','A classification system for body types related to athletic performance.','A mesomorphic {somatotype} is often associated with power athletes.','중배엽형 체형은 파워 종목 선수들과 자주 연관돼요.','somatotype','C2','sports',3,'somatotype body type classification athlete'),
('w_sports_C2_25','electromyography','/ɪˌlektrəˈmaɪɒɡrəfi/','noun','근전도 검사','A technique for measuring electrical activity in muscles.','{Electromyography} reveals which muscles are activated during a throw.','근전도 검사는 투구 동작 중 어떤 근육이 활성화되는지를 밝혀요.','electromyography','C2','sports',3,'electromyography EMG muscle sport science lab'),
('w_sports_C2_26','force-velocity curve','/fɔːrs vɪˈlɒsɪti kɜːrv/','noun','힘-속도 곡선','A graph showing the relationship between muscle force and contraction velocity.','Training aims to shift an athlete''s {force-velocity curve} to the right.','훈련은 선수의 힘-속도 곡선을 오른쪽으로 이동시키는 것을 목표로 해요.','force-velocity curve','C2','sports',3,'force velocity curve graph sport science'),
('w_sports_C2_27','stochastic model','/stəˈkæstɪk ˈmɒdəl/','noun','확률 모델','A mathematical model that incorporates random variables.','A {stochastic model} predicts injury risk across a full season.','확률 모델은 전체 시즌에 걸친 부상 위험을 예측해요.','stochastic model','C2','sports',3,'stochastic model data sport analytics prediction'),
('w_sports_C2_28','thermogenesis','/ˌθɜːrmoʊˈdʒenəsɪs/','noun','열 발생','The production of heat in the body during exercise.','Shivering is a form of {thermogenesis} that keeps the body warm.','떨림은 신체를 따뜻하게 유지하는 열 발생의 한 형태예요.','thermogenesis','C2','sports',3,'thermogenesis heat exercise body temperature sport'),
('w_sports_C2_29','interoperability','/ˌɪntərˌɒpərəˈbɪlɪti/','noun','상호 운용성','The ability of different systems to work together, used in sports tech.','{Interoperability} between wearable devices and coaching platforms improves data use.','웨어러블 기기와 코칭 플랫폼 간의 상호 운용성이 데이터 활용을 향상시켜요.','interoperability','C2','sports',3,'interoperability wearable technology sport data'),
('w_sports_C2_30','proteomics','/ˌproʊtiˈɒmɪks/','noun','단백질체학','The large-scale study of proteins in relation to athletic performance.','Advances in {proteomics} may one day predict injury susceptibility.','단백질체학의 발전은 언젠가 부상 취약성을 예측할 수 있을 거예요.','proteomics','C2','sports',3,'proteomics protein study sport science research'),
('w_sports_C2_31','autoregulation','/ˌɔːtəˌreɡjʊˈleɪʃən/','noun','자동 조절 훈련','Adjusting training intensity based on daily readiness.','{Autoregulation} allows athletes to train as hard as they can each day.','자동 조절 훈련은 선수들이 매일 최대한 열심히 훈련할 수 있게 해줘요.','autoregulation','C2','sports',3,'autoregulation training readiness athlete sport'),
('w_sports_C2_32','actigraphy','/ˈæktɪɡrəfi/','noun','활동기록법','Monitoring rest and activity cycles using a wrist-worn device.','Teams use {actigraphy} to optimise sleep schedules before big matches.','팀들은 큰 경기 전 수면 스케줄을 최적화하기 위해 활동기록법을 사용해요.','actigraphy','C2','sports',3,'actigraphy sleep monitoring athlete wearable'),
('w_sports_C2_33','tribology','/traɪˈbɒlədʒi/','noun','트라이볼로지 (마찰 공학)','The science of friction, lubrication, and wear between surfaces.','{Tribology} informs the design of sports equipment and playing surfaces.','트라이볼로지는 스포츠 장비와 경기 표면 설계에 정보를 제공해요.','tribology','C2','sports',3,'tribology friction surface sport equipment design'),
('w_sports_C2_34','apoptosis','/ˌæpəˈtoʊsɪs/','noun','세포 자멸사','Programmed cell death, relevant to muscle adaptation and overtraining.','Excessive training can trigger {apoptosis} in muscle cells.','과도한 훈련은 근육 세포에서 세포 자멸사를 유발할 수 있어요.','apoptosis','C2','sports',3,'apoptosis cell death muscle overtraining science'),
('w_sports_C2_35','anabolic window','/ˌænəˈbɒlɪk ˈwɪndoʊ/','noun','동화 작용 시간대','The post-exercise period believed to be optimal for muscle-building nutrition.','Many athletes take protein within the {anabolic window} after training.','많은 선수들이 훈련 후 동화 작용 시간대 내에 단백질을 섭취해요.','anabolic window','C2','sports',3,'anabolic window post workout protein nutrition sport');

-- ══════════════════════════════════════════════════════════════════════
-- PATTERNS — A1 (운동 관심 / 기초 대화)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_sports_A1_01','Do you play any sports?','운동 하세요?','Do you play','play는 규칙이 있는 스포츠에 쓰고, do는 개인 운동(do yoga, do exercise)에 써요.','운동 화제','A1','sports','pattern',NULL,1),
('s_sports_A1_02','I like to run in the park every morning.','저는 매일 아침 공원에서 달리기를 좋아해요.','like to run','like to + 동사원형은 자신이 즐겨 하는 활동을 자연스럽게 표현하는 방법이에요.','운동 취미 소개','A1','sports','pattern',NULL,2),
('s_sports_A1_03','What is your favourite sport?','어떤 스포츠를 가장 좋아하세요?','favourite sport','favourite는 영국 영어, favorite은 미국 영어예요. 둘 다 맞아요.','취미 묻기','A1','sports','pattern',NULL,3),
('s_sports_A1_04','I can swim, but I cannot run very fast.','저는 수영은 할 수 있지만 달리기는 그렇게 빠르지 않아요.','can ... cannot','can과 cannot을 함께 쓰면 자신의 능력을 균형 있게 표현할 수 있어요.','능력 표현','A1','sports','pattern',NULL,4),
('s_sports_A1_05','Let''s play football after school!','방과 후에 축구 해요!','Let''s play','Let''s + 동사는 같이 무언가를 하자고 제안하는 가장 간단한 방법이에요.','운동 제안','A1','sports','pattern',NULL,5),
('s_sports_A1_06','Our team won the game yesterday.','우리 팀이 어제 경기에서 이겼어요.','Our team won','won은 win의 과거형이에요. "우리 팀 이겼어요!"는 영어로 "Our team won!" 이라고 해요.','경기 결과 말하기','A1','sports','pattern',NULL,6),
('s_sports_A1_07','I go to the gym three times a week.','저는 일주일에 세 번 헬스장에 가요.','three times a week','빈도를 말할 때는 "번 a week/month/year" 패턴을 기억하세요.','운동 빈도 표현','A1','sports','pattern',NULL,7);

-- ══════════════════════════════════════════════════════════════════════
-- PATTERNS — A2 (경기 결과 / 소감)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_sports_A2_01','Did you watch the match last night?','어젯밤에 경기 봤어요?','Did you watch','과거의 일을 물을 때는 Did you + 동사원형을 써요. watch the match은 경기 관람에 가장 흔한 표현이에요.','경기 화제','A2','sports','pattern',NULL,1),
('s_sports_A2_02','The score was three to one at the end.','최종 점수는 3대 1이었어요.','three to one','점수를 말할 때 영어에서는 "X to Y" 패턴을 써요. "3-1"은 "three to one"이에요.','경기 결과 전달','A2','sports','pattern',NULL,2),
('s_sports_A2_03','She scored the winning goal in the last minute.','그녀가 마지막 순간에 결승골을 넣었어요.','winning goal','winning은 명사 앞에서 "결정적인, 우승을 가져다 준"이라는 뜻으로 쓰여요.','경기 하이라이트','A2','sports','pattern',NULL,3),
('s_sports_A2_04','I can''t believe we lost the game by one point.','한 점 차이로 경기를 졌다는 게 믿기지 않아요.','I can''t believe','I can''t believe + 절은 놀라움이나 실망을 강조할 때 아주 자주 쓰는 표현이에요.','경기 결과 반응','A2','sports','pattern',NULL,4),
('s_sports_A2_05','Which team are you cheering for?','어느 팀을 응원하세요?','cheering for','cheer for는 특정 팀이나 선수를 응원한다는 뜻이에요. "누구 팬이에요?"와 비슷해요.','응원 팀 묻기','A2','sports','pattern',NULL,5),
('s_sports_A2_06','The coach made some great decisions during the match.','코치가 경기 중에 훌륭한 결정들을 내렸어요.','great decisions','make decisions는 중요한 콜로케이션이에요. "결정을 내리다"는 do decisions가 아니에요.','경기 평가','A2','sports','pattern',NULL,6),
('s_sports_A2_07','He has been training really hard for the championship.','그는 선수권 대회를 위해 정말 열심히 훈련해 왔어요.','has been training','현재완료 진행형 "has been + -ing"은 과거부터 지금까지 계속 진행 중인 행동을 표현해요.','선수 이야기','A2','sports','pattern',NULL,7);

-- ══════════════════════════════════════════════════════════════════════
-- PATTERNS — B1 (팀 전략 / 경기 분석)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_sports_B1_01','The coach changed the formation to defend the lead.','코치가 리드를 지키기 위해 포메이션을 바꿨어요.','to defend the lead','to + 동사원형은 목적을 나타내요. "리드를 지키기 위해"처럼 이유를 자연스럽게 덧붙일 수 있어요.','팀 전술','B1','sports','pattern',NULL,1),
('s_sports_B1_02','Their strategy was to keep possession and wait for chances.','그들의 전략은 공 점유를 유지하며 기회를 기다리는 것이었어요.','keep possession','keep + 명사는 어떤 상태를 유지한다는 뜻이에요. keep possession은 축구 전술 설명에 자주 나와요.','전술 분석','B1','sports','pattern',NULL,2),
('s_sports_B1_03','He suffered a knee injury and may miss the next tournament.','그는 무릎 부상을 당해서 다음 토너먼트에 결장할 수도 있어요.','may miss','may + 동사는 가능성이 있지만 확실하지 않을 때 써요. might와 비슷해요.','선수 부상','B1','sports','pattern',NULL,3),
('s_sports_B1_04','She has been recovering from her injury ahead of the championship.','그녀는 선수권 대회를 앞두고 부상에서 회복 중이에요.','recovering from','recover from은 부상·병·어려움에서 회복한다는 표현이에요. 전치사 from을 꼭 기억하세요.','선수 회복 과정','B1','sports','pattern',NULL,4),
('s_sports_B1_05','The referee''s penalty decision sparked a heated debate.','심판의 페널티 결정이 열띤 논쟁을 불러일으켰어요.','sparked a debate','spark a debate는 논쟁을 촉발한다는 자연스러운 표현이에요. 스포츠 뉴스에 자주 등장해요.','경기 논란','B1','sports','pattern',NULL,5),
('s_sports_B1_06','Building endurance is essential if you want to run a marathon.','마라톤을 달리고 싶다면 지구력을 키우는 것이 필수예요.','essential if you want to','"essential if you want to ~"는 조건에 따른 필수 조건을 말할 때 유용한 패턴이에요.','훈련 조언','B1','sports','pattern',NULL,6),
('s_sports_B1_07','The team''s sportsmanship impressed everyone, even after losing.','팀의 스포츠맨십은 패배 후에도 모두를 감동시켰어요.','even after losing','even after + -ing는 예상을 뒤엎는 상황을 강조해요. "패배 후에도"라는 대비를 잘 표현해요.','스포츠맨십','B1','sports','pattern',NULL,7);

-- ══════════════════════════════════════════════════════════════════════
-- PATTERNS — B2 (스포츠 분석 / 데이터)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_sports_B2_01','Modern clubs increasingly rely on data analytics to gain a competitive edge.','현대 구단들은 경쟁 우위를 얻기 위해 데이터 분석에 점점 더 의존하고 있어요.','rely on ... to gain','rely on A to B는 "B를 위해 A에 의존한다"는 구조예요. increasingly를 더하면 변화 추세를 강조할 수 있어요.','스포츠 분석','B2','sports','pattern',NULL,1),
('s_sports_B2_02','His biomechanical assessment revealed inefficiencies in his sprinting technique.','생체역학적 평가로 그의 스프린팅 기술에서 비효율성이 드러났어요.','revealed inefficiencies','reveal은 숨겨진 것을 드러낼 때 쓰는 격식 동사예요. 스포츠 과학 보고서에 자주 나와요.','선수 분석','B2','sports','pattern',NULL,2),
('s_sports_B2_03','Periodization allows coaches to peak their athletes'' performance at the right time.','주기화 훈련은 코치들이 적절한 시기에 선수들의 퍼포먼스를 정점에 달하게 해요.','allows ... to peak','allow A to B는 "A가 B를 할 수 있게 해주다"는 사역 표현이에요. 논리적 설명에 유용해요.','훈련 방법','B2','sports','pattern',NULL,3),
('s_sports_B2_04','Doping not only harms the athlete but also undermines the integrity of the sport.','도핑은 선수를 해칠 뿐만 아니라 스포츠의 청렴성도 훼손해요.','not only ... but also','not only A but also B는 두 가지 결과를 강조하는 고급 패턴이에요. 논문이나 에세이에서 자주 쓰여요.','도핑 문제','B2','sports','pattern',NULL,4),
('s_sports_B2_05','Without adequate physiotherapy, the injury could have ended his career.','적절한 물리 치료가 없었다면 그 부상이 그의 커리어를 끝낼 수도 있었어요.','could have ended','could have + 과거분사는 과거에 일어날 뻔했지만 일어나지 않은 일을 표현해요.','부상 관리','B2','sports','pattern',NULL,5),
('s_sports_B2_06','Tactical awareness is what separates an average player from an elite one.','전술적 인식이 평범한 선수와 엘리트 선수를 구분하는 것이에요.','what separates A from B','what separates A from B는 두 대상의 핵심 차이를 설명하는 강력한 구조예요.','선수 역량 분석','B2','sports','pattern',NULL,6),
('s_sports_B2_07','Agility training has proven to be one of the most effective ways to prevent injuries.','민첩성 훈련은 부상을 예방하는 가장 효과적인 방법 중 하나임이 증명됐어요.','has proven to be','has proven to be는 현재완료로 연구·경험으로 검증된 사실을 말할 때 써요.','훈련 효과','B2','sports','pattern',NULL,7);

-- ══════════════════════════════════════════════════════════════════════
-- PATTERNS — C1 (스포츠 과학 / 전문 토론)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_sports_C1_01','The athlete''s VO2 max is closely correlated with her performance at altitude.','그 선수의 최대 산소 섭취량은 고지대에서의 퍼포먼스와 밀접하게 연관되어 있어요.','closely correlated with','be correlated with는 두 변수 사이의 통계적 관계를 설명할 때 쓰는 학술적 표현이에요.','스포츠 과학','C1','sports','pattern',NULL,1),
('s_sports_C1_02','Proprioception training is increasingly integrated into injury prevention programmes.','고유 감각 훈련은 부상 예방 프로그램에 점점 더 통합되고 있어요.','increasingly integrated into','be integrated into는 어떤 것이 더 큰 시스템의 일부가 됨을 뜻하는 격식 표현이에요.','스포츠 의학','C1','sports','pattern',NULL,2),
('s_sports_C1_03','Sport psychology has transformed how elite athletes approach competition.','스포츠 심리학은 엘리트 선수들이 경쟁에 접근하는 방식을 바꿨어요.','has transformed how','transform은 근본적인 변화를 나타내요. "how + 주어 + 동사" 명사절이 자연스럽게 따라와요.','스포츠 심리','C1','sports','pattern',NULL,3),
('s_sports_C1_04','Repeated concussions raise serious questions about the long-term safety of the sport.','반복적인 뇌진탕은 스포츠의 장기적인 안전성에 대한 심각한 의문을 제기해요.','raise questions about','raise questions about는 문제를 제기한다는 뜻의 격식 표현이에요. bring up과 비슷하지만 더 격식체예요.','스포츠 안전','C1','sports','pattern',NULL,4),
('s_sports_C1_05','The governance of international sports bodies has come under increasing scrutiny.','국제 스포츠 단체의 거버넌스는 점점 더 많은 면밀한 조사를 받고 있어요.','come under scrutiny','come under scrutiny는 조사·비판을 받기 시작하다는 뜻의 고급 관용 표현이에요.','스포츠 거버넌스','C1','sports','pattern',NULL,5),
('s_sports_C1_06','Training at the lactate threshold improves aerobic efficiency without excessive fatigue.','젖산 역치에서 훈련하면 과도한 피로 없이 유산소 효율성이 향상돼요.','without excessive fatigue','without + 명사는 부작용·제약 없이 무언가를 달성한다는 표현이에요. 과학 글에 자주 쓰여요.','운동 생리학','C1','sports','pattern',NULL,6),
('s_sports_C1_07','Ethical dilemmas in sport often reflect broader tensions in society.','스포츠의 윤리적 딜레마는 종종 사회의 더 넓은 갈등을 반영해요.','reflect broader tensions','reflect broader ~는 스포츠 현상이 사회 전반의 문제와 연결됨을 논의할 때 쓰는 세련된 표현이에요.','스포츠 윤리','C1','sports','pattern',NULL,7);

-- ══════════════════════════════════════════════════════════════════════
-- PATTERNS — C2 (스포츠 과학 심화 / 학술적 표현)
-- ══════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_sports_C2_01','Tensiomyography provides a non-invasive means of quantifying neuromuscular fatigue between training sessions.','근수축 측정법은 훈련 세션 사이의 신경근 피로를 비침습적으로 정량화하는 수단을 제공해요.','non-invasive means of quantifying','means of + -ing는 특정 목적을 달성하는 수단을 설명하는 학술적 구조예요.','스포츠 과학 연구','C2','sports','pattern',NULL,1),
('s_sports_C2_02','The interplay between chronobiology and periodization remains an underexplored area of sport science.','시간생물학과 주기화 훈련 사이의 상호작용은 스포츠 과학에서 아직 충분히 탐구되지 않은 영역이에요.','interplay between A and B','interplay는 두 힘이나 요소가 서로 영향을 주고받는 관계를 설명하는 정교한 학술 어휘예요.','스포츠 과학','C2','sports','pattern',NULL,2),
('s_sports_C2_03','Advances in sport genomics may eventually enable truly individualised training prescriptions.','스포츠 유전체학의 발전은 결국 진정으로 개인화된 훈련 처방을 가능하게 할 수 있어요.','may eventually enable','may eventually는 먼 미래에 가능할 수도 있다는 신중한 예측을 나타내요. 학술 글에서 과도한 단정을 피할 때 쓰여요.','스포츠 유전학','C2','sports','pattern',NULL,3),
('s_sports_C2_04','Plyometric protocols are designed to exploit the stretch-shortening cycle of muscle contraction.','플라이오메트릭 프로토콜은 근육 수축의 신장-단축 사이클을 활용하도록 설계돼요.','designed to exploit','be designed to는 특정 목적을 위해 의도적으로 만들어졌음을 나타내요. exploit은 학술적으로 "활용하다"는 뜻이에요.','운동 과학','C2','sports','pattern',NULL,4),
('s_sports_C2_05','The dose-response relationship between training volume and muscle hypertrophy is well-established in the literature.','훈련 볼륨과 근비대 사이의 용량-반응 관계는 문헌에서 잘 확립되어 있어요.','well-established in the literature','well-established in the literature는 과학적으로 충분히 검증된 사실을 가리킬 때 쓰는 학술 표현이에요.','운동 생리학','C2','sports','pattern',NULL,5),
('s_sports_C2_06','Myofascial restrictions, if left untreated, can perpetuate movement dysfunction across multiple joints.','근막 제한이 치료되지 않으면 여러 관절에 걸쳐 운동 기능 장애를 지속시킬 수 있어요.','if left untreated','if left + 과거분사는 조건절을 간결하게 줄인 표현이에요. 의학·과학 글에서 자주 쓰여요.','스포츠 의학','C2','sports','pattern',NULL,6),
('s_sports_C2_07','Psychomotor deterioration under sustained cognitive load is a critical factor in late-game decision-making errors.','지속적인 인지 부하 하에서의 심리운동 저하는 경기 후반 의사결정 오류의 핵심 요인이에요.','under sustained cognitive load','under + 명사구는 특정 조건이나 압박 하에 있음을 나타내요. sustained는 "지속적인"이라는 뜻의 고급 형용사예요.','스포츠 심리학','C2','sports','pattern',NULL,7);
