-- EngCat Idioms — all 23 topics
-- Target: ~345 total, B1-C1 focus

-- GREETING
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_greeting_01', 'break the ice', '어색한 분위기를 깨다', '얼음을 깨다', '처음 만나는 사람들 사이의 어색함을 없앨 때 쓰는 표현이에요.', 'He told a joke to break the ice at the meeting.', '그는 회의에서 어색한 분위기를 깨려고 농담을 했어요.', 'Games are a great way to break the ice with new classmates.', '게임은 새 반 친구들과 어색함을 깨는 좋은 방법이에요.', 'She smiled and introduced herself to break the ice.', '그녀는 미소를 지으며 자기소개를 해서 어색한 분위기를 깼어요.', 'B1', 'greeting', 1, 'two people meeting handshake smile', 1),
('idm_greeting_02', 'warm up to someone', '점차 친해지다', '누군가에게 따뜻해지다', '처음에는 서먹하지만 시간이 지나면서 친해지는 과정을 표현해요.', 'It took a while, but she finally warmed up to her new coworkers.', '시간이 좀 걸렸지만 그녀는 결국 새 동료들과 친해졌어요.', 'The kids warmed up to their new teacher after a few days.', '아이들은 며칠 후 새 선생님과 친해졌어요.', NULL, NULL, 'B1', 'greeting', 2, 'people getting friendly warm conversation', 2),
('idm_greeting_03', 'make someone feel at home', '편안하게 해주다', '집처럼 느끼게 해주다', '손님이나 새로운 사람이 편안함을 느낄 수 있도록 배려할 때 써요.', 'The host made everyone feel at home with food and friendly chat.', '주인은 음식과 친근한 대화로 모두를 편안하게 해줬어요.', 'We tried to make the new employee feel at home on her first day.', '우리는 새 직원이 첫날부터 편안함을 느낄 수 있도록 노력했어요.', NULL, NULL, 'B1', 'greeting', 1, 'welcoming host warm home hospitality', 3),
('idm_greeting_04', 'hit it off', '금세 친해지다', '그것을 맞추다', '처음 만났는데도 바로 잘 통하고 친해질 때 쓰는 표현이에요.', 'We hit it off right away at the party.', '우리는 파티에서 바로 친해졌어요.', 'They hit it off the moment they were introduced.', '그들은 소개받는 순간 바로 친해졌어요.', 'I knew we''d hit it off — we have so much in common.', '우리가 금세 친해질 거라고 알았어요 — 공통점이 너무 많거든요.', 'B1', 'greeting', 1, 'two people laughing getting along well', 4),
('idm_greeting_05', 'get on like a house on fire', '아주 잘 지내다', '불타는 집처럼 잘 지내다', '두 사람이 매우 빠르게 친해지고 사이좋게 지낼 때 쓰는 표현이에요.', 'My sister and her new roommate get on like a house on fire.', '내 여동생과 새 룸메이트는 아주 잘 지내요.', 'The two colleagues got on like a house on fire from day one.', '두 동료는 첫날부터 아주 잘 지냈어요.', NULL, NULL, 'B2', 'greeting', 2, 'two friends laughing bonding friendship', 5),
('idm_greeting_06', 'put your foot in your mouth', '실언하다', '발을 입에 넣다', '실수로 상처가 되는 말을 했을 때 쓰는 표현이에요.', 'I really put my foot in my mouth when I asked about her ex.', '전 남자친구에 대해 물어봤을 때 정말 실언했어요.', 'He put his foot in his mouth by commenting on her age.', '그는 나이에 대해 언급하다가 실언을 했어요.', NULL, NULL, 'B2', 'greeting', 2, 'awkward social situation embarrassed face', 6),
('idm_greeting_07', 'be on first-name terms', '이름을 부르는 친한 사이다', '이름으로 부르는 사이이다', '격식 없이 이름으로 부를 만큼 친밀한 관계임을 나타내요.', 'After a few meetings, we were on first-name terms.', '몇 번 만난 후에는 이름을 부르는 사이가 됐어요.', 'She''s on first-name terms with the CEO.', '그녀는 CEO와 이름을 부르는 친한 사이예요.', NULL, NULL, 'B2', 'greeting', 2, 'colleagues friendly casual relationship', 7),
('idm_greeting_08', 'know someone by sight', '얼굴만 아는 사이다', '눈으로 누군가를 알다', '이름은 모르지만 얼굴은 아는 관계를 표현할 때 써요.', 'I know her by sight, but we''ve never spoken.', '얼굴은 알지만 한 번도 말해본 적이 없어요.', 'We only know each other by sight from the gym.', '헬스장에서 얼굴만 아는 사이예요.', NULL, NULL, 'B1', 'greeting', 3, 'familiar face recognize crowd', 8),
('idm_greeting_09', 'pass the time of day', '가벼운 인사를 나누다', '하루의 시간을 나누다', '특별한 목적 없이 짧게 인사하거나 잡담할 때 써요.', 'We often pass the time of day at the bus stop.', '우리는 버스 정류장에서 자주 가벼운 인사를 나눠요.', 'He stopped to pass the time of day with his neighbor.', '그는 이웃과 가벼운 인사를 나누기 위해 멈췄어요.', NULL, NULL, 'B2', 'greeting', 3, 'casual chat neighbors street', 9),
('idm_greeting_10', 'be a familiar face', '낯익은 얼굴이다', '친숙한 얼굴이다', '어떤 장소나 모임에서 자주 보이는 사람을 가리킬 때 써요.', 'She''s a familiar face at the local café.', '그녀는 동네 카페에서 낯익은 얼굴이에요.', 'He was a familiar face at the weekly meetings.', '그는 주간 회의에서 낯익은 얼굴이었어요.', NULL, NULL, 'B1', 'greeting', 3, 'regular customer familiar person cafe', 10),
('idm_greeting_11', 'a small world', '세상 참 좁다', '작은 세상', '전혀 예상치 못한 곳에서 아는 사람을 만났을 때 놀라움을 표현해요.', 'I ran into my old teacher in Paris — it''s a small world!', '파리에서 옛날 선생님을 만났어요 — 세상 참 좁죠!', 'You know him too? What a small world!', '당신도 그를 알아요? 세상 참 좁네요!', NULL, NULL, 'B1', 'greeting', 1, 'unexpected meeting surprised coincidence', 11),
('idm_greeting_12', 'long time no see', '오랜만이에요', '오랫동안 못 봤어요', '오랫동안 만나지 못했던 사람을 다시 만났을 때 인사처럼 쓰는 표현이에요.', 'Long time no see! How have you been?', '오랜만이에요! 잘 지내셨어요?', '"Long time no see," she said with a big smile.', '"오랜만이에요," 그녀는 환하게 웃으며 말했어요.', NULL, NULL, 'B1', 'greeting', 1, 'old friends reunion happy meeting', 12),
('idm_greeting_13', 'give someone a warm welcome', '따뜻하게 환영하다', '누군가에게 따뜻한 환영을 주다', '새로 온 사람을 진심으로 환영하는 행동이나 말을 묘사해요.', 'The team gave the new member a warm welcome.', '팀은 새 멤버를 따뜻하게 환영했어요.', 'Let''s give our guest speaker a warm welcome.', '초청 강사를 따뜻하게 환영해 드립시다.', NULL, NULL, 'B1', 'greeting', 2, 'welcoming applause warm reception', 13),
('idm_greeting_14', 'get off on the right foot', '좋은 출발을 하다', '오른발로 시작하다', '새로운 관계나 상황을 좋게 시작할 때 쓰는 표현이에요.', 'I want to get off on the right foot with my new boss.', '새 상사와 좋은 출발을 하고 싶어요.', 'We got off on the right foot by being honest from the start.', '처음부터 솔직하게 대함으로써 좋은 출발을 했어요.', NULL, NULL, 'B1', 'greeting', 2, 'good start first impression positive', 14),
('idm_greeting_15', 'keep in touch', '연락하며 지내다', '접촉을 유지하다', '헤어질 때 연락을 끊지 말자고 할 때 쓰는 표현이에요.', 'Let''s keep in touch after you move abroad.', '해외로 이사한 후에도 연락하며 지내요.', '"Keep in touch!" she called as she left the party.', '"연락해요!" 그녀는 파티를 나가며 말했어요.', NULL, NULL, 'B1', 'greeting', 1, 'phone message staying connected friends', 15);

-- EMOTION
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_emotion_01', 'on cloud nine', '매우 행복하다', '구름 아홉 번째 위에 있다', '극도로 행복하거나 기쁜 상태를 표현할 때 써요.', 'She was on cloud nine after getting the job offer.', '취업 제안을 받은 후 그녀는 매우 행복해했어요.', 'He''s been on cloud nine since he got engaged.', '약혼한 이후로 그는 매우 행복해하고 있어요.', NULL, NULL, 'B1', 'emotion', 1, 'happy person jumping joy elation', 1),
('idm_emotion_02', 'down in the dumps', '우울하다', '쓰레기 더미 아래에 있다', '기분이 가라앉거나 우울할 때 쓰는 표현이에요.', 'He''s been down in the dumps since his team lost.', '팀이 진 이후로 그는 우울해하고 있어요.', 'She felt down in the dumps after hearing the bad news.', '나쁜 소식을 들은 후 그녀는 우울해졌어요.', NULL, NULL, 'B1', 'emotion', 1, 'sad person gloomy depressed mood', 2),
('idm_emotion_03', 'at the end of one''s rope', '더 이상 버티기 힘들다', '밧줄 끝에 있다', '인내심의 한계에 달했을 때 쓰는 표현이에요.', 'After three sleepless nights, she was at the end of her rope.', '3일 밤을 못 잔 후 그녀는 더 이상 버티기 힘든 상태였어요.', 'I''m at the end of my rope with this project.', '이 프로젝트로 인해 더 이상 버티기 힘들어요.', NULL, NULL, 'B2', 'emotion', 2, 'exhausted stressed person limit breaking point', 3),
('idm_emotion_04', 'bite the bullet', '참고 견디다', '총알을 깨물다', '힘들지만 어쩔 수 없이 받아들이고 견뎌야 할 때 써요.', 'I hate dentists, but I had to bite the bullet and go.', '치과가 싫지만 참고 가야 했어요.', 'Just bite the bullet and apologize — it''ll feel better after.', '참고 사과해요 — 그러고 나면 더 나을 거예요.', NULL, NULL, 'B2', 'emotion', 2, 'determined face enduring hardship brave', 4),
('idm_emotion_05', 'keep a stiff upper lip', '감정을 억제하다', '윗입술을 굳게 유지하다', '힘든 상황에서도 감정을 드러내지 않고 침착하게 행동할 때 써요.', 'Despite the setback, she kept a stiff upper lip.', '좌절에도 불구하고 그녀는 감정을 억제했어요.', 'He kept a stiff upper lip throughout the difficult negotiation.', '그는 어려운 협상 내내 감정을 드러내지 않았어요.', NULL, NULL, 'B2', 'emotion', 3, 'calm composed face emotional control', 5),
('idm_emotion_06', 'wear one''s heart on one''s sleeve', '감정을 숨기지 않다', '소매 위에 심장을 달고 다니다', '자신의 감정을 솔직하게 드러내는 사람을 묘사할 때 써요.', 'She wears her heart on her sleeve — you always know how she feels.', '그녀는 감정을 숨기지 않아요 — 기분이 어떤지 항상 알 수 있어요.', 'He''s the type who wears his heart on his sleeve.', '그는 감정을 솔직하게 드러내는 타입이에요.', NULL, NULL, 'B2', 'emotion', 2, 'open emotional expressive person', 6),
('idm_emotion_07', 'have butterflies in one''s stomach', '긴장되다', '배 속에 나비가 있다', '설레거나 긴장될 때, 특히 중요한 일을 앞두고 쓰는 표현이에요.', 'I had butterflies in my stomach before the presentation.', '발표 전에 너무 긴장됐어요.', 'She always gets butterflies in her stomach before a performance.', '그녀는 공연 전에 항상 긴장해요.', NULL, NULL, 'B1', 'emotion', 1, 'nervous anxious stomach butterflies performance', 7),
('idm_emotion_08', 'let off steam', '감정을 발산하다', '증기를 내보내다', '쌓인 감정이나 스트레스를 해소할 때 쓰는 표현이에요.', 'He goes for a run to let off steam after work.', '그는 퇴근 후 스트레스를 풀기 위해 달리기를 해요.', 'Let''s talk — you need to let off some steam.', '이야기해요 — 감정을 좀 발산할 필요가 있어요.', NULL, NULL, 'B1', 'emotion', 1, 'exercise venting stress relief release', 8),
('idm_emotion_09', 'in high spirits', '기분이 좋다', '높은 정신 상태에 있다', '매우 기분이 좋고 에너지가 넘치는 상태를 표현해요.', 'Everyone was in high spirits at the celebration.', '모두가 축하 자리에서 기분이 좋았어요.', 'She arrived in high spirits, full of energy.', '그녀는 기분이 매우 좋고 활기차게 도착했어요.', NULL, NULL, 'B1', 'emotion', 2, 'happy energetic cheerful celebration mood', 9),
('idm_emotion_10', 'blow a fuse', '화를 폭발시키다', '퓨즈를 끊다', '갑자기 매우 화를 낼 때 쓰는 표현이에요.', 'He blew a fuse when he found out they lied.', '그들이 거짓말한 것을 알았을 때 그는 화를 폭발시켰어요.', 'Don''t blow a fuse — let''s calmly discuss this.', '화내지 마세요 — 차분하게 이야기해요.', NULL, NULL, 'B2', 'emotion', 2, 'angry explosion furious losing temper', 10),
('idm_emotion_11', 'on the edge of one''s seat', '긴장하며 집중하다', '의자 가장자리에 있다', '흥미롭거나 긴장된 상황에서 몰입해 있을 때 써요.', 'The movie had me on the edge of my seat the whole time.', '영화 내내 긴장하며 집중했어요.', 'The final match kept everyone on the edge of their seats.', '결승전은 모두를 긴장하며 집중하게 했어요.', NULL, NULL, 'B1', 'emotion', 2, 'suspense excited tense watching movie', 11),
('idm_emotion_12', 'feel blue', '우울하다', '파란색을 느끼다', '슬프거나 우울한 기분을 간단하게 표현할 때 써요.', 'I''ve been feeling blue all week for no reason.', '이유 없이 일주일 내내 우울했어요.', 'She feels blue every winter when the days get shorter.', '낮이 짧아지는 겨울마다 그녀는 우울해해요.', NULL, NULL, 'B1', 'emotion', 1, 'sad melancholy blue mood alone', 12),
('idm_emotion_13', 'go through the roof', '매우 흥분하다 / 극도로 화나다', '지붕을 뚫고 올라가다', '분노나 흥분이 극도에 달했을 때 쓰는 표현이에요.', 'When she heard the price, she went through the roof.', '가격을 듣고 그녀는 매우 화를 냈어요.', 'His excitement went through the roof when he saw the surprise.', '깜짝 선물을 보고 그는 매우 흥분했어요.', NULL, NULL, 'B2', 'emotion', 2, 'extreme anger excitement intense reaction', 13),
('idm_emotion_14', 'take heart', '용기를 내다', '마음을 받아들이다', '어려운 상황에서도 희망을 잃지 말라고 격려할 때 써요.', 'Take heart — things will get better soon.', '용기를 내세요 — 곧 나아질 거예요.', 'She took heart from the positive feedback she received.', '그녀는 받은 긍정적인 피드백으로 용기를 냈어요.', NULL, NULL, 'B1', 'emotion', 3, 'encouragement hope courage positive mindset', 14),
('idm_emotion_15', 'mixed feelings', '복잡한 감정', '섞인 감정들', '기쁨과 슬픔이 동시에 드는 복잡한 심정을 표현해요.', 'I have mixed feelings about leaving my job.', '일을 그만두는 것에 대해 복잡한 감정이에요.', 'She had mixed feelings about her daughter moving abroad.', '딸이 해외로 이사 가는 것에 대해 복잡한 감정이었어요.', NULL, NULL, 'B1', 'emotion', 1, 'conflicted emotions bittersweet ambivalent', 15);

-- WEATHER
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_weather_01', 'every cloud has a silver lining', '고생 끝에 낙이 온다', '모든 구름에는 은빛 안감이 있다', '힘든 상황에도 좋은 면이 있다는 희망적인 메시지를 전할 때 써요.', 'I lost my job, but every cloud has a silver lining — now I can travel.', '직장을 잃었지만 고생 끝에 낙이 있어요 — 이제 여행할 수 있거든요.', 'Remember, every cloud has a silver lining.', '고생 끝에 낙이 온다는 걸 기억하세요.', NULL, NULL, 'B1', 'weather', 1, 'silver lining clouds hope optimism', 1),
('idm_weather_02', 'it never rains but it pours', '불행은 겹쳐서 온다', '비가 오면 쏟아진다', '나쁜 일은 한꺼번에 몰려온다는 의미예요.', 'My car broke down, and then I got sick — it never rains but it pours.', '차가 고장 났는데 아프기까지 했어요 — 불행은 겹쳐서 와요.', 'It never rains but it pours — now the printer is broken too.', '불행은 겹쳐서 오네요 — 이제 프린터까지 고장났어요.', NULL, NULL, 'B2', 'weather', 2, 'heavy rain problems troubles piling up', 2),
('idm_weather_03', 'a storm in a teacup', '사소한 일을 크게 부풀리다', '찻잔 속의 폭풍', '별것 아닌 일을 너무 크게 만들 때 쓰는 표현이에요.', 'The argument was just a storm in a teacup.', '그 다툼은 그냥 사소한 일을 크게 부풀린 것이었어요.', 'Don''t worry — it''s a storm in a teacup and will blow over soon.', '걱정 마세요 — 사소한 일이고 곧 지나갈 거예요.', NULL, NULL, 'B2', 'weather', 2, 'overreaction small problem exaggerated drama', 3),
('idm_weather_04', 'under the weather', '몸이 좋지 않다', '날씨 아래에 있다', '가볍게 아프거나 컨디션이 좋지 않을 때 쓰는 표현이에요.', 'I''m feeling a little under the weather today.', '오늘 몸이 좀 좋지 않아요.', 'She''s under the weather and won''t be coming in.', '그녀는 몸이 좋지 않아서 오지 못할 거예요.', NULL, NULL, 'B1', 'weather', 1, 'sick unwell tired ill cold', 4),
('idm_weather_05', 'steal someone''s thunder', '남의 주목을 빼앗다', '누군가의 천둥을 훔치다', '다른 사람이 주목받아야 할 순간에 관심을 빼앗을 때 써요.', 'She stole his thunder by announcing her promotion at his party.', '그의 파티에서 자신의 승진을 발표해 그의 주목을 빼앗았어요.', 'Don''t steal my thunder — let me tell them the news.', '내 주목을 빼앗지 마세요 — 제가 소식을 전할게요.', NULL, NULL, 'B2', 'weather', 2, 'attention spotlight upstaging someone', 5),
('idm_weather_06', 'weather the storm', '어려움을 이겨내다', '폭풍을 견디다', '힘든 시기나 위기를 극복하고 살아남을 때 쓰는 표현이에요.', 'The company weathered the storm of the financial crisis.', '회사는 금융 위기의 어려움을 이겨냈어요.', 'Their relationship weathered many storms over the years.', '그들의 관계는 수년간 많은 어려움을 이겨냈어요.', NULL, NULL, 'B2', 'weather', 2, 'storm survival resilience overcoming crisis', 6),
('idm_weather_07', 'make hay while the sun shines', '기회가 있을 때 최대한 활용하다', '해가 날 때 건초를 만들다', '좋은 기회가 있을 때 적극적으로 활용하라는 의미예요.', 'The market is doing well — let''s make hay while the sun shines.', '시장이 좋을 때 기회를 최대한 활용해요.', 'Make hay while the sun shines — the sale ends tomorrow.', '기회가 있을 때 활용하세요 — 할인은 내일 끝나요.', NULL, NULL, 'B2', 'weather', 2, 'opportunity sunshine harvest take advantage', 7),
('idm_weather_08', 'in a fog', '멍한 상태다', '안개 속에 있다', '집중이 안 되거나 혼란스러운 상태를 표현해요.', 'I''ve been in a fog all morning — not enough sleep.', '잠이 부족해서 오전 내내 멍한 상태였어요.', 'She was in a fog after hearing the unexpected news.', '예상치 못한 소식을 들은 후 그녀는 멍한 상태였어요.', NULL, NULL, 'B1', 'weather', 2, 'confused dazed fog tired unfocused', 8),
('idm_weather_09', 'take a rain check', '다음으로 미루다', '비 수표를 받다', '지금은 참여하기 어려우니 나중에 하자고 정중하게 거절할 때 써요.', 'I can''t make it tonight — can I take a rain check?', '오늘 밤은 안 될 것 같아요 — 다음으로 미룰 수 있을까요?', '"Rain check?" he asked when she declined the invitation.', '"다음에 해요?" 그는 그녀가 초대를 거절하자 물었어요.', NULL, NULL, 'B1', 'weather', 1, 'postpone reschedule decline invitation politely', 9),
('idm_weather_10', 'like a ray of sunshine', '해처럼 밝고 기운을 주는 사람', '햇살 한 줄기처럼', '누군가가 주변을 밝게 하고 기운을 줄 때 쓰는 표현이에요.', 'She''s like a ray of sunshine — always cheerful.', '그녀는 항상 밝아서 해처럼 기운을 줘요.', 'That baby is like a ray of sunshine on a cloudy day.', '그 아기는 흐린 날의 햇살 같은 존재예요.', NULL, NULL, 'B1', 'weather', 2, 'cheerful positive person sunshine bright', 10),
('idm_weather_11', 'a breeze', '쉬운 일', '산들바람', '어떤 일이 매우 쉽게 느껴질 때 쓰는 표현이에요.', 'The exam was a breeze — I finished in 20 minutes.', '시험이 너무 쉬웠어요 — 20분 만에 끝냈어요.', 'For her, learning languages is a breeze.', '그녀에게 언어 배우는 건 쉬운 일이에요.', NULL, NULL, 'B1', 'weather', 1, 'easy simple effortless task breeze', 11),
('idm_weather_12', 'chase rainbows', '비현실적인 꿈을 좇다', '무지개를 쫓다', '달성 불가능한 목표를 무작정 추구할 때 써요.', 'He keeps chasing rainbows instead of taking practical steps.', '그는 실용적인 조치를 취하는 대신 비현실적인 꿈만 좇고 있어요.', 'Don''t chase rainbows — focus on what''s achievable.', '비현실적인 꿈을 쫓지 마세요 — 달성 가능한 것에 집중하세요.', NULL, NULL, 'B2', 'weather', 3, 'unrealistic dream pursuit fantasy goal', 12),
('idm_weather_13', 'snowed under', '일에 파묻히다', '눈 아래에 묻히다', '할 일이 너무 많아 감당하기 힘들 때 쓰는 표현이에요.', 'I''m completely snowed under with work this week.', '이번 주는 일에 완전히 파묻혀 있어요.', 'She was snowed under with emails after her vacation.', '휴가 후 그녀는 이메일에 파묻혔어요.', NULL, NULL, 'B1', 'weather', 2, 'overwhelmed busy buried work emails', 13),
('idm_weather_14', 'lightning fast', '매우 빠르다', '번개처럼 빠르다', '무언가가 매우 빠르게 일어날 때 강조해서 쓰는 표현이에요.', 'The new software processes data at lightning fast speed.', '새 소프트웨어는 번개처럼 빠르게 데이터를 처리해요.', 'She''s a lightning-fast typist.', '그녀는 타이핑이 매우 빨라요.', NULL, NULL, 'B1', 'weather', 2, 'fast speed lightning quick performance', 14),
('idm_weather_15', 'fair-weather friend', '어려울 때 곁에 없는 친구', '맑은 날씨의 친구', '좋을 때만 나타나고 어려울 때는 곁에 없는 사람을 표현해요.', 'He turned out to be a fair-weather friend when I needed help.', '도움이 필요할 때 그는 어려울 때 곁에 없는 친구로 드러났어요.', 'I don''t need fair-weather friends — I need real support.', '좋을 때만 있는 친구는 필요 없어요 — 진짜 지지가 필요해요.', NULL, NULL, 'B2', 'weather', 2, 'fake friend abandonment support trouble', 15);

-- SHOPPING
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_shopping_01', 'cost an arm and a leg', '매우 비싸다', '팔과 다리 하나씩의 값이 들다', '가격이 터무니없이 비쌀 때 쓰는 표현이에요.', 'That handbag costs an arm and a leg.', '저 핸드백은 매우 비싸요.', 'Eating out in the city centre costs an arm and a leg.', '도심에서 외식하는 건 매우 비싸요.', NULL, NULL, 'B1', 'shopping', 1, 'expensive luxury price shocked shopping', 1),
('idm_shopping_02', 'break the bank', '엄청난 돈을 쓰다', '은행을 부수다', '감당하기 어려울 만큼 많은 돈을 쓸 때 써요.', 'A weekend trip doesn''t have to break the bank.', '주말여행이 꼭 엄청난 돈을 써야 하는 건 아니에요.', 'We got beautiful flowers without breaking the bank.', '엄청난 돈을 쓰지 않고도 아름다운 꽃을 샀어요.', NULL, NULL, 'B1', 'shopping', 1, 'expensive budget spending money broke', 2),
('idm_shopping_03', 'pay through the nose', '터무니없는 값을 치르다', '코를 통해 지불하다', '실제 가치보다 훨씬 비싸게 지불했을 때 쓰는 표현이에요.', 'We paid through the nose for seats at the concert.', '콘서트 자리에 터무니없는 값을 치렀어요.', 'Tourists often pay through the nose for taxis near airports.', '관광객들은 공항 근처에서 택시비로 터무니없는 돈을 내는 경우가 많아요.', NULL, NULL, 'B2', 'shopping', 2, 'overpriced ripped off expensive paying', 3),
('idm_shopping_04', 'get a bargain', '싸게 사다', '협상을 얻다', '물건을 매우 싼 가격에 살 때 쓰는 표현이에요.', 'I got a real bargain at the flea market.', '벼룩시장에서 진짜 싸게 샀어요.', 'She always manages to get a bargain in the sales.', '그녀는 세일 때 항상 싸게 사요.', NULL, NULL, 'B1', 'shopping', 1, 'sale discount cheap deal bargain', 4),
('idm_shopping_05', 'go window shopping', '윈도우 쇼핑하다', '창문 쇼핑하러 가다', '살 의도 없이 가게를 둘러볼 때 쓰는 표현이에요.', 'We went window shopping downtown on Saturday.', '토요일에 시내에서 윈도우 쇼핑을 했어요.', 'She went window shopping just to pass the time.', '그녀는 시간을 보내려고 윈도우 쇼핑을 했어요.', NULL, NULL, 'B1', 'shopping', 1, 'window shopping browsing store no purchase', 5),
('idm_shopping_06', 'sell like hotcakes', '불티나게 팔리다', '핫케이크처럼 팔리다', '제품이 매우 빨리 팔릴 때 쓰는 표현이에요.', 'The new phone model is selling like hotcakes.', '새 휴대폰 모델이 불티나게 팔리고 있어요.', 'Her handmade bags sold like hotcakes at the market.', '그녀의 수제 가방은 시장에서 불티나게 팔렸어요.', NULL, NULL, 'B1', 'shopping', 2, 'popular product selling fast demand high', 6),
('idm_shopping_07', 'in the red / in the black', '적자 / 흑자', '빨간색 / 검은색에 있다', '재정 상태가 손해인지 이익인지를 나타낼 때 써요.', 'The shop was in the red for three months straight.', '가게는 3개월 연속으로 적자였어요.', 'After the holiday season, they''re finally in the black.', '연휴 시즌 후 드디어 흑자로 돌아섰어요.', NULL, NULL, 'B2', 'shopping', 2, 'finance profit loss balance money', 7),
('idm_shopping_08', 'cut corners', '비용을 줄이다 / 대충하다', '모서리를 자르다', '비용이나 노력을 아끼기 위해 제대로 하지 않을 때 써요.', 'The company cut corners on safety to save money.', '회사는 비용 절감을 위해 안전을 대충 처리했어요.', 'Don''t cut corners when making important purchases.', '중요한 물건을 살 때 비용을 아끼느라 대충하지 마세요.', NULL, NULL, 'B1', 'shopping', 2, 'shortcuts quality sacrifice cheapest option', 8),
('idm_shopping_09', 'cheap as chips', '매우 저렴하다', '감자칩만큼 싸다', '가격이 매우 저렴하다는 것을 강조할 때 쓰는 표현이에요.', 'That second-hand sofa was cheap as chips.', '저 중고 소파는 매우 저렴했어요.', 'Street food here is cheap as chips.', '여기 길거리 음식은 매우 저렴해요.', NULL, NULL, 'B1', 'shopping', 2, 'cheap affordable inexpensive deal value', 9),
('idm_shopping_10', 'on a tight budget', '빠듯한 예산으로', '빡빡한 예산에 있다', '돈이 많지 않아 절약해야 할 때 쓰는 표현이에요.', 'We redecorated the apartment on a tight budget.', '빠듯한 예산으로 아파트를 재인테리어했어요.', 'She travels on a tight budget by cooking her own meals.', '그녀는 직접 요리하며 빠듯한 예산으로 여행해요.', NULL, NULL, 'B1', 'shopping', 1, 'budget saving frugal spending limit', 10),
('idm_shopping_11', 'a steal', '헐값이다', '훔치는 것 같은 가격이다', '가격이 너무 저렴해서 믿기지 않을 때 써요.', 'This jacket was only $10 — it''s a steal!', '이 재킷이 10달러밖에 안 했어요 — 헐값이에요!', 'At that price, the apartment is an absolute steal.', '그 가격에 그 아파트는 완전히 헐값이에요.', NULL, NULL, 'B1', 'shopping', 2, 'amazing deal cheap price steal value', 11),
('idm_shopping_12', 'splash out', '돈을 아낌없이 쓰다', '물을 튀기다', '특별한 경우에 평소보다 돈을 많이 쓸 때 쓰는 표현이에요.', 'We splashed out on a nice dinner for our anniversary.', '기념일을 위해 좋은 저녁 식사에 아낌없이 돈을 썼어요.', 'He splashed out on the latest gaming console.', '그는 최신 게임 콘솔에 돈을 아낌없이 썼어요.', NULL, NULL, 'B2', 'shopping', 2, 'treat yourself splurge spend celebrate', 12),
('idm_shopping_13', 'get your money''s worth', '돈 값을 하다', '돈의 가치를 얻다', '지불한 가격 대비 충분한 가치를 얻었을 때 쓰는 표현이에요.', 'The buffet was expensive, but we got our money''s worth.', '뷔페가 비쌌지만 돈 값을 했어요.', 'That membership fee is worth it — we definitely get our money''s worth.', '그 회원비는 가치가 있어요 — 확실히 돈 값을 해요.', NULL, NULL, 'B1', 'shopping', 2, 'value for money worth price satisfaction', 13),
('idm_shopping_14', 'put something on hold', '보류해두다', '무언가를 대기 상태에 놓다', '가게에서 물건을 잠시 맡아달라고 하거나 결정을 미룰 때 써요.', 'Can you put this jacket on hold while I check my size?', '사이즈를 확인하는 동안 이 재킷을 보류해 주실 수 있어요?', 'She put the purchase on hold until payday.', '그녀는 월급날까지 구매를 보류해뒀어요.', NULL, NULL, 'B1', 'shopping', 2, 'reservation hold item delay purchase', 14),
('idm_shopping_15', 'shop till you drop', '쓰러질 때까지 쇼핑하다', '쓰러질 때까지 쇼핑하다', '매우 오랫동안 열정적으로 쇼핑할 때 유머러스하게 쓰는 표현이에요.', 'We went to the mall and shopped till we dropped.', '쇼핑몰에 가서 쓰러질 때까지 쇼핑했어요.', 'On her birthday, she planned to shop till she dropped.', '생일에 그녀는 쓰러질 때까지 쇼핑할 계획이었어요.', NULL, NULL, 'B1', 'shopping', 2, 'shopping spree exhausted mall bags full', 15);

-- CAFE
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_cafe_01', 'spill the beans', '비밀을 누설하다', '콩을 쏟다', '비밀이나 숨겨진 정보를 실수로 또는 의도적으로 말할 때 써요.', 'Come on, spill the beans — what''s the surprise?', '어서요, 비밀을 말해줘요 — 깜짝 선물이 뭐예요?', 'She spilled the beans about the party before I could tell everyone.', '내가 모두에게 말하기 전에 그녀가 파티에 대한 비밀을 누설했어요.', NULL, NULL, 'B1', 'cafe', 1, 'secret reveal gossip telling beans spill', 1),
('idm_cafe_02', 'eat humble pie', '자존심을 굽히고 사과하다', '겸손의 파이를 먹다', '틀렸다는 것을 인정하고 사과해야 할 때 쓰는 표현이에요.', 'He had to eat humble pie after his prediction was wrong.', '예측이 틀린 후 그는 자존심을 굽히고 사과해야 했어요.', 'She ate humble pie and admitted she was mistaken.', '그녀는 자존심을 굽히고 실수를 인정했어요.', NULL, NULL, 'B2', 'cafe', 2, 'apology humility admit mistake pride', 2),
('idm_cafe_03', 'in a nutshell', '간단히 말하면', '호두 껍데기 안에', '복잡한 것을 짧고 간결하게 요약할 때 써요.', 'In a nutshell, the project failed because of poor planning.', '간단히 말하면, 프로젝트는 계획 부족으로 실패했어요.', 'Can you explain in a nutshell what the app does?', '앱이 무엇을 하는지 간단히 설명해 주실 수 있어요?', NULL, NULL, 'B1', 'cafe', 1, 'summary brief explanation simple concise', 3),
('idm_cafe_04', 'butter someone up', '아첨하다', '누군가에게 버터를 바르다', '무언가를 원할 때 상대방을 칭찬하며 비위를 맞출 때 써요.', 'She buttered up the manager before asking for a raise.', '그녀는 인상을 요청하기 전에 관리자에게 아첨했어요.', 'Don''t try to butter me up — I can see through it.', '아첨하려 하지 마세요 — 다 보여요.', NULL, NULL, 'B2', 'cafe', 2, 'flattery compliment manipulate charm boss', 4),
('idm_cafe_05', 'food for thought', '생각할 거리', '생각을 위한 음식', '깊이 생각해볼 만한 흥미로운 아이디어나 정보를 가리킬 때 써요.', 'The documentary gave me a lot of food for thought.', '그 다큐멘터리는 많은 생각할 거리를 줬어요.', 'Her comment was certainly food for thought.', '그녀의 말은 분명히 생각할 거리였어요.', NULL, NULL, 'B1', 'cafe', 2, 'ideas thinking reflect consider thought', 5),
('idm_cafe_06', 'bite off more than you can chew', '감당할 수 없는 일을 맡다', '씹을 수 있는 것보다 더 많이 물다', '자신의 능력 이상으로 일을 맡아 버거울 때 쓰는 표현이에요.', 'She bit off more than she could chew by taking three projects at once.', '세 개의 프로젝트를 동시에 맡아 감당하기 어려웠어요.', 'Don''t bite off more than you can chew — start small.', '감당할 수 없는 일을 맡지 마세요 — 작게 시작하세요.', NULL, NULL, 'B1', 'cafe', 2, 'overwhelmed too much workload overcommit', 6),
('idm_cafe_07', 'have a lot on one''s plate', '처리할 일이 많다', '접시에 많은 것이 있다', '해야 할 일이나 걱정이 너무 많을 때 쓰는 표현이에요.', 'I can''t take on another task — I already have a lot on my plate.', '또 다른 일을 맡을 수 없어요 — 이미 처리할 일이 많아요.', 'She has a lot on her plate with work and family.', '일과 가족 때문에 처리할 일이 너무 많아요.', NULL, NULL, 'B1', 'cafe', 1, 'busy overloaded responsibilities too much', 7),
('idm_cafe_08', 'the icing on the cake', '금상첨화', '케이크 위의 아이싱', '이미 좋은 상황에 더 좋은 일이 더해질 때 써요.', 'We won the match, and then it started to snow — the icing on the cake!', '경기에 이겼는데 눈까지 내렸어요 — 금상첨화예요!', 'The bonus was the icing on the cake after a great year.', '좋은 한 해를 보낸 후 보너스는 금상첨화였어요.', NULL, NULL, 'B1', 'cafe', 1, 'bonus extra addition perfect wonderful', 8),
('idm_cafe_09', 'piece of cake', '식은 죽 먹기', '케이크 한 조각', '어떤 일이 매우 쉽다고 표현할 때 써요.', 'The interview was a piece of cake — I was well prepared.', '인터뷰는 식은 죽 먹기였어요 — 잘 준비했거든요.', '"Is it hard?" "No, it''s a piece of cake."', '"어려워요?" "아니요, 식은 죽 먹기예요."', NULL, NULL, 'B1', 'cafe', 1, 'easy simple effortless no problem', 9),
('idm_cafe_10', 'sour grapes', '자신이 가질 수 없는 것을 깎아내리다', '신 포도', '가질 수 없는 것을 마치 필요 없는 척 폄하할 때 써요.', 'Saying the award isn''t important is just sour grapes.', '상이 중요하지 않다고 말하는 건 그냥 신 포도예요.', '"I didn''t want that job anyway." — "That sounds like sour grapes."', '"어차피 그 직장 원하지도 않았어." — "신 포도처럼 들리는데요."', NULL, NULL, 'B2', 'cafe', 2, 'jealousy sour grapes envy pretend not care', 10),
('idm_cafe_11', 'take something with a pinch of salt', '반신반의하다', '소금 한 꼬집과 함께 받아들이다', '누군가의 말을 완전히 믿지 말고 비판적으로 들으라는 뜻이에요.', 'Take his advice with a pinch of salt — he''s not always right.', '그의 조언을 반신반의하세요 — 항상 옳은 건 아니거든요.', 'I take online reviews with a pinch of salt.', '온라인 리뷰는 반신반의하며 봐요.', NULL, NULL, 'B1', 'cafe', 1, 'skeptical doubt critical believe partially', 11),
('idm_cafe_12', 'not my cup of tea', '내 취향이 아니다', '내 찻잔이 아니다', '어떤 것이 자신의 취향이나 관심사가 아닐 때 쓰는 표현이에요.', 'Horror movies are not really my cup of tea.', '공포 영화는 제 취향이 아니에요.', 'Classical music isn''t her cup of tea, but she went to please her mum.', '클래식 음악은 그녀 취향이 아니지만 엄마를 기쁘게 하려고 갔어요.', NULL, NULL, 'B1', 'cafe', 1, 'preference not interested dislike taste', 12),
('idm_cafe_13', 'full plate', '할 일이 가득하다', '가득 찬 접시', '책임지고 처리해야 할 일이 많은 상태예요.', 'I have a full plate this month — three deadlines!', '이번 달은 할 일이 가득해요 — 마감이 세 개나 있어요!', 'She''s got a full plate between work and studying.', '일과 공부 사이에서 할 일이 가득해요.', NULL, NULL, 'B1', 'cafe', 2, 'busy schedule work full plate tasks', 13),
('idm_cafe_14', 'cream of the crop', '최상위 그룹', '작물의 크림', '어떤 분야에서 가장 뛰어난 사람이나 것을 가리킬 때 써요.', 'These graduates are the cream of the crop.', '이 졸업생들은 최상위 그룹이에요.', 'Only the cream of the crop get selected for the program.', '최상위 그룹만 프로그램에 선발돼요.', NULL, NULL, 'B2', 'cafe', 2, 'best top elite excellent selection', 14),
('idm_cafe_15', 'have your cake and eat it too', '두 마리 토끼를 다 잡으려 하다', '케이크를 갖고 먹기도 하다', '서로 양립할 수 없는 두 가지를 동시에 원할 때 쓰는 표현이에요.', 'You can''t have your cake and eat it too — choose one.', '두 마리 토끼를 다 잡을 수는 없어요 — 하나를 선택하세요.', 'He wants a high salary and short hours — you can''t have your cake and eat it.', '높은 급여와 짧은 근무 시간을 원하는데 — 두 마리 토끼를 다 잡을 수는 없어요.', NULL, NULL, 'B2', 'cafe', 2, 'impossible both options greedy dilemma', 15);

-- TRANSPORT
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_transport_01', 'in the fast lane', '빠른 속도로 살다', '빠른 차선에 있다', '바쁘고 흥미롭지만 스트레스가 많은 삶의 방식을 묘사해요.', 'He lives life in the fast lane — always working or traveling.', '그는 항상 일하거나 여행하며 빠르게 살아요.', 'Life in the fast lane can be exhausting.', '빠른 속도로 사는 삶은 지칠 수 있어요.', NULL, NULL, 'B2', 'transport', 2, 'fast lifestyle busy highway speed living', 1),
('idm_transport_02', 'miss the boat', '기회를 놓치다', '배를 놓치다', '좋은 기회를 제때 잡지 못했을 때 쓰는 표현이에요.', 'He missed the boat on that investment opportunity.', '그는 그 투자 기회를 놓쳤어요.', 'If you don''t apply now, you''ll miss the boat.', '지금 지원하지 않으면 기회를 놓칠 거예요.', NULL, NULL, 'B1', 'transport', 1, 'missed opportunity too late chance gone boat', 2),
('idm_transport_03', 'get on the right track', '올바른 방향으로 가다', '올바른 선로에 오르다', '올바른 방향이나 방법으로 진행하고 있을 때 써요.', 'The new manager helped the team get on the right track.', '새 관리자가 팀이 올바른 방향으로 가도록 도왔어요.', 'Now that we have a plan, we''re on the right track.', '계획이 생겼으니 이제 올바른 방향으로 가고 있어요.', NULL, NULL, 'B1', 'transport', 1, 'right direction progress improvement track', 3),
('idm_transport_04', 'hit the road', '출발하다', '도로를 치다', '어딘가로 떠날 준비가 됐을 때 쓰는 표현이에요.', 'It''s getting late — time to hit the road.', '늦어지고 있어요 — 이제 출발할 시간이에요.', 'We hit the road at 6 a.m. to avoid traffic.', '교통 체증을 피하려고 오전 6시에 출발했어요.', NULL, NULL, 'B1', 'transport', 1, 'depart leave start journey travel begin', 4),
('idm_transport_05', 'go off the rails', '엇나가다', '선로를 벗어나다', '계획이나 행동이 통제를 벗어나 잘못된 방향으로 갈 때 써요.', 'The project went off the rails after the budget was cut.', '예산이 삭감된 후 프로젝트가 엇나갔어요.', 'He went off the rails during his teenage years but has improved.', '그는 십대 시절 엇나갔지만 지금은 나아졌어요.', NULL, NULL, 'B2', 'transport', 2, 'derailed failure out of control troubled', 5),
('idm_transport_06', 'in the same boat', '같은 처지에 있다', '같은 배에 있다', '비슷하게 어려운 상황에 있는 사람들을 묘사할 때 써요.', 'We''re all in the same boat here — let''s help each other.', '우리는 모두 같은 처지에 있어요 — 서로 도와요.', 'Don''t worry, you''re not alone — we''re in the same boat.', '걱정 마세요, 혼자가 아니에요 — 같은 처지에 있어요.', NULL, NULL, 'B1', 'transport', 1, 'same situation solidarity together problem', 6),
('idm_transport_07', 'drive someone up the wall', '누군가를 미치게 하다', '누군가를 벽 위로 몰다', '누군가를 몹시 짜증나게 할 때 쓰는 표현이에요.', 'That noise is driving me up the wall.', '그 소음이 저를 미치게 해요.', 'Her constant complaining drives everyone up the wall.', '그녀의 끊임없는 불평이 모두를 미치게 해요.', NULL, NULL, 'B1', 'transport', 2, 'annoying irritating frustrating crazy noise', 7),
('idm_transport_08', 'take the scenic route', '돌아가다 / 여유롭게 가다', '경치 좋은 길로 가다', '목적지까지 빠른 길 대신 더 즐겁거나 여유로운 방법을 선택할 때 써요.', 'We took the scenic route and stopped at a few viewpoints.', '돌아가는 길로 가며 몇 군데 전망 좋은 곳에 들렀어요.', 'Don''t rush — let''s take the scenic route and enjoy it.', '서두르지 말아요 — 여유롭게 가며 즐겨요.', NULL, NULL, 'B1', 'transport', 3, 'scenic road detour enjoy journey slow', 8),
('idm_transport_09', 'get the green light', '허가를 받다', '초록불을 받다', '어떤 일을 진행해도 된다는 승인을 받을 때 써요.', 'We finally got the green light to start the project.', '드디어 프로젝트를 시작해도 된다는 허가를 받았어요.', 'The plan got the green light from the board.', '이사회로부터 계획에 대한 허가를 받았어요.', NULL, NULL, 'B1', 'transport', 1, 'approval permission go ahead start signal', 9),
('idm_transport_10', 'put the brakes on', '제동을 걸다', '브레이크를 밟다', '어떤 일을 늦추거나 멈추게 할 때 쓰는 표현이에요.', 'They put the brakes on expansion when the market slowed.', '시장이 둔화되자 확장에 제동을 걸었어요.', 'She had to put the brakes on her spending.', '그녀는 지출에 제동을 걸어야 했어요.', NULL, NULL, 'B2', 'transport', 2, 'slow down stop halt restrict brakes', 10),
('idm_transport_11', 'run out of steam', '지쳐서 멈추다', '증기가 바닥나다', '에너지나 동기가 다해 더 이상 계속하기 힘들어질 때 써요.', 'The campaign ran out of steam after a few months.', '캠페인은 몇 달 후 지쳐서 멈췄어요.', 'I ran out of steam halfway through the marathon.', '마라톤 중간에 지쳐버렸어요.', NULL, NULL, 'B2', 'transport', 2, 'exhausted energy lost motivation drained', 11),
('idm_transport_12', 'a long shot', '가능성이 낮다', '먼 거리 발사', '성공 가능성이 거의 없지만 시도해볼 만한 것을 가리켜요.', 'It''s a long shot, but I''ll apply for the scholarship anyway.', '가능성이 낮지만 어쨌든 장학금에 지원할게요.', 'Winning was a long shot, but they tried their best.', '이길 가능성은 낮았지만 최선을 다했어요.', NULL, NULL, 'B1', 'transport', 2, 'unlikely chance risk attempt hope', 12),
('idm_transport_13', 'at a crossroads', '기로에 서다', '교차로에 있다', '중요한 결정을 내려야 하는 시점에 있을 때 써요.', 'She''s at a crossroads — stay in her job or start a business.', '그녀는 직장에 남을지, 사업을 시작할지 기로에 서 있어요.', 'The company is at a crossroads after losing its biggest client.', '회사는 가장 큰 고객을 잃은 후 기로에 서 있어요.', NULL, NULL, 'B2', 'transport', 2, 'decision turning point choice crossroads life', 13),
('idm_transport_14', 'backseat driver', '참견하는 사람', '뒷좌석 운전자', '자신이 책임자도 아니면서 이래라저래라 하는 사람을 묘사해요.', 'Don''t be a backseat driver — let me handle it.', '참견하지 마세요 — 제가 처리할게요.', 'She''s a real backseat driver at work — always telling others what to do.', '그녀는 직장에서 정말 참견쟁이에요 — 항상 다른 사람에게 이래라저래라 해요.', NULL, NULL, 'B2', 'transport', 2, 'bossy interfering advice unwanted control', 14),
('idm_transport_15', 'on the right track', '잘 하고 있다', '올바른 선로 위에 있다', '올바른 방향으로 나아가고 있음을 확인할 때 써요.', 'Your analysis is on the right track — keep going.', '분석이 잘 되고 있어요 — 계속하세요.', 'I''m not sure this is the answer, but I think I''m on the right track.', '답이 맞는지는 모르겠지만 잘 하고 있는 것 같아요.', NULL, NULL, 'B1', 'transport', 1, 'progress correct direction heading toward goal', 15);

-- HEALTH
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_health_01', 'under the weather', '몸이 좋지 않다', '날씨 아래에 있다', '가볍게 아프거나 피곤할 때 쓰는 일상적인 표현이에요.', 'I''m feeling under the weather — probably a cold.', '몸이 좋지 않아요 — 아마 감기인 것 같아요.', 'She''s under the weather and has taken the day off.', '그녀는 몸이 좋지 않아서 하루 쉬었어요.', NULL, NULL, 'B1', 'health', 1, 'sick ill unwell cold tired health', 1),
('idm_health_02', 'back on one''s feet', '회복하다', '발로 다시 서다', '병이나 어려움에서 회복하여 정상으로 돌아올 때 써요.', 'She was back on her feet a week after the surgery.', '수술 후 일주일 만에 회복했어요.', 'With rest and good food, you''ll be back on your feet in no time.', '휴식과 좋은 음식으로 곧 회복할 거예요.', NULL, NULL, 'B1', 'health', 1, 'recovery healing better health restored', 2),
('idm_health_03', 'in the pink', '건강하다', '핑크색에 있다', '매우 건강하고 활기찬 상태를 표현할 때 써요.', 'After the vacation, she''s in the pink.', '휴가 후 그녀는 매우 건강해요.', 'Grandpa is in the pink despite his age.', '할아버지는 연세에도 불구하고 매우 건강하세요.', NULL, NULL, 'B2', 'health', 2, 'healthy fit energetic vibrant wellness', 3),
('idm_health_04', 'burn the candle at both ends', '무리하게 일하다', '양쪽에서 양초를 태우다', '잠을 적게 자고 지나치게 많은 일을 하여 몸을 혹사할 때 써요.', 'If you keep burning the candle at both ends, you''ll burn out.', '계속 무리하게 일하면 번아웃이 올 거예요.', 'She''s been burning the candle at both ends — working late and waking early.', '그녀는 늦게까지 일하고 일찍 일어나며 무리하게 일하고 있어요.', NULL, NULL, 'B2', 'health', 2, 'overwork exhaustion burnout tired no sleep', 4),
('idm_health_05', 'on the mend', '회복 중이다', '수선 중이다', '병이나 부상에서 서서히 나아지고 있을 때 써요.', 'Good news — he''s on the mend after the operation.', '좋은 소식이에요 — 수술 후 회복 중이에요.', 'She''s on the mend but still needs to rest.', '회복 중이지만 아직 쉬어야 해요.', NULL, NULL, 'B1', 'health', 2, 'recovering healing improving injury illness', 5),
('idm_health_06', 'keep body and soul together', '간신히 살아가다', '몸과 영혼을 함께 유지하다', '먹고 살기 위해 겨우 버텨나갈 때 쓰는 표현이에요.', 'His part-time job barely keeps body and soul together.', '아르바이트로 겨우 살아가고 있어요.', 'In tough times, we did whatever it took to keep body and soul together.', '힘든 시기에 우리는 간신히 살아가기 위해 무엇이든 했어요.', NULL, NULL, 'B2', 'health', 3, 'survive barely living basic needs minimal', 6),
('idm_health_07', 'fighting fit', '매우 건강하다', '싸울 준비가 된 체력', '완벽하게 건강하고 에너지가 넘치는 상태를 강조해요.', 'He looks fighting fit after his training program.', '그는 훈련 프로그램 후 매우 건강해 보여요.', 'She came back from her holiday looking fighting fit.', '그녀는 휴가에서 돌아와 매우 건강해 보였어요.', NULL, NULL, 'B2', 'health', 2, 'strong fit healthy exercise energy peak', 7),
('idm_health_08', 'catch a bug', '가벼운 병에 걸리다', '벌레를 잡다', '감기나 독감 같은 가벼운 바이러스성 질환에 걸릴 때 써요.', 'I caught a bug from someone on the train.', '기차에서 누군가에게 옮아 가벼운 병에 걸렸어요.', 'Half the office caught a bug last week.', '지난주에 사무실 절반이 병에 걸렸어요.', NULL, NULL, 'B1', 'health', 1, 'sick virus cold flu catching illness', 8),
('idm_health_09', 'a clean bill of health', '건강 이상 없음 판정', '깨끗한 건강 증명서', '의사로부터 건강에 문제없다는 확인을 받을 때 써요.', 'The doctor gave her a clean bill of health.', '의사는 그녀에게 건강 이상 없음 판정을 내렸어요.', 'After all the tests, he got a clean bill of health.', '모든 검사 후 건강 이상 없음 판정을 받았어요.', NULL, NULL, 'B2', 'health', 2, 'healthy checkup doctor medical exam clear', 9),
('idm_health_10', 'an apple a day keeps the doctor away', '건강한 생활습관이 건강을 지킨다', '하루에 사과 하나로 의사를 멀리한다', '규칙적이고 건강한 습관이 건강을 유지시켜 준다는 의미의 속담이에요.', 'An apple a day keeps the doctor away — eat your fruit!', '건강한 습관이 건강을 지켜줘요 — 과일 드세요!', 'She believes in the saying: an apple a day keeps the doctor away.', '그녀는 건강한 습관이 건강을 지킨다는 말을 믿어요.', NULL, NULL, 'B1', 'health', 1, 'apple healthy habit prevention diet nutrition', 10),
('idm_health_11', 'run oneself into the ground', '스스로를 완전히 지치게 하다', '스스로를 땅 속으로 달리다', '너무 많은 일을 해서 완전히 탈진할 때 쓰는 표현이에요.', 'She ran herself into the ground trying to meet every deadline.', '모든 마감을 맞추려다 스스로를 완전히 지치게 했어요.', 'Don''t run yourself into the ground — take a break.', '스스로를 지치게 하지 마세요 — 쉬세요.', NULL, NULL, 'B2', 'health', 2, 'exhausted burnout overwork drain energy', 11),
('idm_health_12', 'as fit as a fiddle', '매우 건강하다', '피들처럼 건강하다', '나이에 비해 매우 건강하거나 최상의 컨디션일 때 써요.', 'My grandfather is 80 and as fit as a fiddle.', '할아버지는 80세인데 매우 건강하세요.', 'After six months of exercise, I feel as fit as a fiddle.', '6개월 운동 후 매우 건강한 느낌이에요.', NULL, NULL, 'B1', 'health', 2, 'very healthy fit strong energetic excellent', 12),
('idm_health_13', 'take a turn for the worse', '상태가 악화되다', '더 나쁜 쪽으로 방향을 틀다', '병이나 상황이 갑자기 나빠질 때 써요.', 'He seemed to be recovering, but then took a turn for the worse.', '회복하는 것 같았는데 갑자기 상태가 악화됐어요.', 'The patient took a turn for the worse overnight.', '환자의 상태가 하룻밤 사이에 악화됐어요.', NULL, NULL, 'B2', 'health', 2, 'deteriorate decline worse condition hospital', 13),
('idm_health_14', 'on one''s last legs', '기력이 다하다', '마지막 다리에 있다', '사람이나 사물이 거의 한계에 달해 더 이상 기능하기 어려울 때 써요.', 'This laptop is on its last legs — I need a new one.', '이 노트북은 기력이 다했어요 — 새것이 필요해요.', 'After the hike, I was on my last legs.', '하이킹 후 기력이 다했어요.', NULL, NULL, 'B2', 'health', 2, 'exhausted barely functioning worn out finished', 14),
('idm_health_15', 'feel like a million dollars', '최상의 컨디션이다', '백만 달러처럼 느끼다', '매우 기분이 좋고 건강하게 느껴질 때 쓰는 표현이에요.', 'After a full night''s sleep, I feel like a million dollars.', '푹 잔 후 최상의 컨디션이에요.', 'That new haircut makes her feel like a million dollars.', '새 헤어스타일로 그녀는 최상의 컨디션을 느껴요.', NULL, NULL, 'B1', 'health', 2, 'great feeling energetic confident beautiful healthy', 15);
