-- EngCat · Shopping — words examples (example_en_2~5 / example_ko_2~5)
-- 210 UPDATE statements (A1×35, A2×35, B1×35, B2×35, C1×35, C2×35)
-- Generated: 2026-05-26

-- ────────────────────────────────────────────────────────────
-- A1
-- ────────────────────────────────────────────────────────────
UPDATE words SET example_en_2 = 'Did you buy anything at the market?', example_ko_2 = '시장에서 뭔가 사셨나요?', example_en_3 = 'She wants to buy a red dress.', example_ko_3 = '그녀는 빨간 원피스를 사고 싶어해요.', example_en_4 = 'Let''s buy some snacks for the trip.', example_ko_4 = '여행을 위해 간식을 좀 사요.', example_en_5 = 'Can you buy milk on your way home?', example_ko_5 = '집에 오는 길에 우유 사올 수 있어요?' WHERE id = 'w_shopping_A1_01';
UPDATE words SET example_en_2 = 'Do they sell umbrellas here?', example_ko_2 = '여기서 우산도 파나요?', example_en_3 = 'He sells handmade candles online.', example_ko_3 = '그는 온라인으로 손으로 만든 초를 팔아요.', example_en_4 = 'This shop sells books and stationery.', example_ko_4 = '이 가게는 책과 문구류를 팔아요.', example_en_5 = 'They sell coffee at the corner café.', example_ko_5 = '코너 카페에서 커피를 팔아요.' WHERE id = 'w_shopping_A1_02';
UPDATE words SET example_en_2 = 'I love to shop on weekends.', example_ko_2 = '저는 주말에 쇼핑하는 걸 좋아해요.', example_en_3 = 'There is a new shop on the high street.', example_ko_3 = '번화가에 새 가게가 생겼어요.', example_en_4 = 'We shopped for three hours yesterday.', example_ko_4 = '어제 세 시간 동안 쇼핑했어요.', example_en_5 = 'Which shop has the best prices?', example_ko_5 = '어느 가게가 제일 싸요?' WHERE id = 'w_shopping_A1_03';
UPDATE words SET example_en_2 = 'The price is too high for me.', example_ko_2 = '저한테는 가격이 너무 높아요.', example_en_3 = 'Is there a better price for two items?', example_ko_3 = '두 개 사면 더 좋은 가격이 있나요?', example_en_4 = 'The price went down during the sale.', example_ko_4 = '세일 기간 동안 가격이 내려갔어요.', example_en_5 = 'Can you tell me the price of this shirt?', example_ko_5 = '이 셔츠 가격이 얼마인지 알려주실 수 있어요?' WHERE id = 'w_shopping_A1_04';
UPDATE words SET example_en_2 = 'I found a cheap restaurant near here.', example_ko_2 = '근처에 저렴한 식당을 찾았어요.', example_en_3 = 'These shoes look cheap but they''re good quality.', example_ko_3 = '이 신발은 저렴해 보이지만 품질이 좋아요.', example_en_4 = 'Is there a cheap option available?', example_ko_4 = '저렴한 선택지가 있나요?', example_en_5 = 'Fresh vegetables are cheap at the market.', example_ko_5 = '시장에서는 신선한 채소가 저렴해요.' WHERE id = 'w_shopping_A1_05';
UPDATE words SET example_en_2 = 'Why is this so expensive?', example_ko_2 = '왜 이게 이렇게 비싸요?', example_en_3 = 'This restaurant is too expensive for me.', example_ko_3 = '이 식당은 저한테 너무 비싸요.', example_en_4 = 'Organic food is usually more expensive.', example_ko_4 = '유기농 식품은 보통 더 비싸요.', example_en_5 = 'The shoes were expensive, but worth it.', example_ko_5 = '신발이 비쌌지만 그만한 가치가 있었어요.' WHERE id = 'w_shopping_A1_06';
UPDATE words SET example_en_2 = 'Can you lend me some money?', example_ko_2 = '돈 좀 빌려줄 수 있어요?', example_en_3 = 'I need to get some money from the bank.', example_ko_3 = '은행에서 돈을 찾아야 해요.', example_en_4 = 'Save your money for something important.', example_ko_4 = '중요한 것을 위해 돈을 모아요.', example_en_5 = 'How much money do you have with you?', example_ko_5 = '지금 얼마나 가지고 계세요?' WHERE id = 'w_shopping_A1_07';
UPDATE words SET example_en_2 = 'I''ll pay at the counter.', example_ko_2 = '계산대에서 낼게요.', example_en_3 = 'Do I pay here or at the exit?', example_ko_3 = '여기서 내나요, 출구에서 내나요?', example_en_4 = 'She paid for everything with cash.', example_ko_4 = '그녀는 현금으로 전부 냈어요.', example_en_5 = 'You can pay online before you arrive.', example_ko_5 = '도착 전에 온라인으로 결제할 수 있어요.' WHERE id = 'w_shopping_A1_08';
UPDATE words SET example_en_2 = 'The night market is very popular here.', example_ko_2 = '여기 야시장이 매우 인기 있어요.', example_en_3 = 'We buy vegetables at the local market.', example_ko_3 = '동네 시장에서 채소를 사요.', example_en_4 = 'Is there a market near the hotel?', example_ko_4 = '호텔 근처에 시장이 있나요?', example_en_5 = 'The flea market starts at nine.', example_ko_5 = '벼룩시장은 9시에 시작해요.' WHERE id = 'w_shopping_A1_09';
UPDATE words SET example_en_2 = 'What time does the store open?', example_ko_2 = '상점이 몇 시에 열어요?', example_en_3 = 'The store has a wide range of products.', example_ko_3 = '그 상점은 다양한 상품이 있어요.', example_en_4 = 'Is there a convenience store nearby?', example_ko_4 = '근처에 편의점이 있나요?', example_en_5 = 'I went to the store to buy some bread.', example_ko_5 = '빵을 사러 상점에 갔어요.' WHERE id = 'w_shopping_A1_10';
UPDATE words SET example_en_2 = 'I forgot my bag at home.', example_ko_2 = '집에 가방을 두고 왔어요.', example_en_3 = 'Please put it in a paper bag.', example_ko_3 = '종이봉투에 넣어 주세요.', example_en_4 = 'Do you need a bag for those items?', example_ko_4 = '그 물건들을 담을 봉투가 필요하세요?', example_en_5 = 'She carries a big shopping bag.', example_ko_5 = '그녀는 큰 쇼핑백을 들고 다녀요.' WHERE id = 'w_shopping_A1_11';
UPDATE words SET example_en_2 = 'Is this a new product?', example_ko_2 = '이게 새 상품이에요?', example_en_3 = 'I just bought a new phone.', example_ko_3 = '방금 새 휴대폰을 샀어요.', example_en_4 = 'They have new arrivals every week.', example_ko_4 = '매주 새 상품이 들어와요.', example_en_5 = 'The new collection looks amazing.', example_ko_5 = '새 컬렉션이 정말 멋져 보여요.' WHERE id = 'w_shopping_A1_12';
UPDATE words SET example_en_2 = 'This old jacket still looks great.', example_ko_2 = '이 오래된 재킷이 아직도 멋져 보여요.', example_en_3 = 'Do you buy old furniture?', example_ko_3 = '오래된 가구도 사시나요?', example_en_4 = 'The old model is cheaper than the new one.', example_ko_4 = '구형 모델이 신형보다 저렴해요.', example_en_5 = 'I prefer old books to new ones.', example_ko_5 = '저는 새 책보다 오래된 책을 더 좋아해요.' WHERE id = 'w_shopping_A1_13';
UPDATE words SET example_en_2 = 'Do you have this in a big size?', example_ko_2 = '이거 큰 사이즈 있나요?', example_en_3 = 'I need a big box for this.', example_ko_3 = '이걸 담을 큰 상자가 필요해요.', example_en_4 = 'The big sale starts on Friday.', example_ko_4 = '큰 세일이 금요일에 시작해요.', example_en_5 = 'Is there a bigger version of this bag?', example_ko_5 = '이 가방의 더 큰 버전이 있나요?' WHERE id = 'w_shopping_A1_14';
UPDATE words SET example_en_2 = 'The small size is sold out.', example_ko_2 = '작은 사이즈는 품절이에요.', example_en_3 = 'Do you have something smaller?', example_ko_3 = '더 작은 것도 있나요?', example_en_4 = 'This room is a bit small for a store.', example_ko_4 = '이 공간은 가게로는 좀 작아요.', example_en_5 = 'A small gift is always a nice gesture.', example_ko_5 = '작은 선물도 항상 좋은 표현이에요.' WHERE id = 'w_shopping_A1_15';
UPDATE words SET example_en_2 = 'Are you open on public holidays?', example_ko_2 = '공휴일에도 영업하나요?', example_en_3 = 'The store is open until ten tonight.', example_ko_3 = '오늘 밤 10시까지 영업해요.', example_en_4 = 'Is the café open yet?', example_ko_4 = '카페 벌써 문 열었나요?', example_en_5 = 'They are open seven days a week.', example_ko_5 = '주 7일 영업해요.' WHERE id = 'w_shopping_A1_16';
UPDATE words SET example_en_2 = 'Sorry, the bakery is closed now.', example_ko_2 = '죄송해요, 빵집은 지금 문 닫았어요.', example_en_3 = 'The shop is closed on Mondays.', example_ko_3 = '그 가게는 월요일에 쉬어요.', example_en_4 = 'Is the pharmacy closed today?', example_ko_4 = '오늘 약국 문 닫았나요?', example_en_5 = 'We arrived just as the store closed.', example_ko_5 = '가게가 문 닫는 순간 도착했어요.' WHERE id = 'w_shopping_A1_17';
UPDATE words SET example_en_2 = 'What do you want for your birthday?', example_ko_2 = '생일에 뭘 원하세요?', example_en_3 = 'I want to try on those shoes.', example_ko_3 = '저 신발을 신어보고 싶어요.', example_en_4 = 'Do you want a bag with that?', example_ko_4 = '봉투도 드릴까요?', example_en_5 = 'She wants to exchange her jacket.', example_ko_5 = '그녀는 재킷을 교환하고 싶어해요.' WHERE id = 'w_shopping_A1_18';
UPDATE words SET example_en_2 = 'I need to find a pharmacy quickly.', example_ko_2 = '빨리 약국을 찾아야 해요.', example_en_3 = 'Do you need anything from the store?', example_ko_3 = '상점에서 필요한 거 있어요?', example_en_4 = 'We need more bags for all this shopping.', example_ko_4 = '이 쇼핑한 것들 다 담으려면 봉투가 더 필요해요.', example_en_5 = 'I need a medium size, please.', example_ko_5 = '미디엄 사이즈로 부탁드려요.' WHERE id = 'w_shopping_A1_19';
UPDATE words SET example_en_2 = 'Can I look at the menu first?', example_ko_2 = '메뉴를 먼저 봐도 될까요?', example_en_3 = 'Look at those prices — amazing!', example_ko_3 = '저 가격 좀 봐요 — 정말 놀랍죠!', example_en_4 = 'She''s looking for a gift for her mum.', example_ko_4 = '그녀는 엄마 선물을 찾고 있어요.', example_en_5 = 'I''m looking for the shoe section.', example_ko_5 = '신발 코너를 찾고 있어요.' WHERE id = 'w_shopping_A1_20';
UPDATE words SET example_en_2 = 'The gift wrapping is free today.', example_ko_2 = '오늘은 선물 포장이 무료예요.', example_en_3 = 'You can park here for free.', example_ko_3 = '여기 무료로 주차할 수 있어요.', example_en_4 = 'Is the wi-fi free in this café?', example_ko_4 = '이 카페 와이파이 무료예요?', example_en_5 = 'Buy two and get one free.', example_ko_5 = '두 개 사면 하나 무료예요.' WHERE id = 'w_shopping_A1_21';
UPDATE words SET example_en_2 = 'Is this bag a good gift for her?', example_ko_2 = '이 가방이 그녀에게 좋은 선물이 될까요?', example_en_3 = 'Do you have gift wrapping?', example_ko_3 = '선물 포장 해드리나요?', example_en_4 = 'I always bring a small gift when I visit.', example_ko_4 = '저는 방문할 때 항상 작은 선물을 가져가요.', example_en_5 = 'The gift came in a beautiful box.', example_ko_5 = '선물이 예쁜 상자에 담겨 왔어요.' WHERE id = 'w_shopping_A1_22';
UPDATE words SET example_en_2 = 'Can you show me the total on the screen?', example_ko_2 = '화면으로 합계를 보여주실 수 있어요?', example_en_3 = 'The total comes to forty dollars.', example_ko_3 = '합계가 40달러예요.', example_en_4 = 'Please check the total before you pay.', example_ko_4 = '결제 전에 합계를 확인해 주세요.', example_en_5 = 'The total includes tax.', example_ko_5 = '합계에 세금이 포함되어 있어요.' WHERE id = 'w_shopping_A1_23';
UPDATE words SET example_en_2 = 'I only have cash with me today.', example_ko_2 = '오늘은 현금만 가지고 있어요.', example_en_3 = 'Is there a cash machine nearby?', example_ko_3 = '근처에 현금 인출기 있나요?', example_en_4 = 'She paid in cash at the market.', example_ko_4 = '그녀는 시장에서 현금으로 냈어요.', example_en_5 = 'Some small shops only take cash.', example_ko_5 = '일부 작은 가게는 현금만 받아요.' WHERE id = 'w_shopping_A1_24';
UPDATE words SET example_en_2 = 'My card was declined at the checkout.', example_ko_2 = '계산대에서 카드가 거절됐어요.', example_en_3 = 'Can I use a debit card here?', example_ko_3 = '여기서 직불카드 쓸 수 있나요?', example_en_4 = 'Tap your card on the reader.', example_ko_4 = '단말기에 카드를 태그해 주세요.', example_en_5 = 'I lost my card at the store.', example_ko_5 = '상점에서 카드를 잃어버렸어요.' WHERE id = 'w_shopping_A1_25';
UPDATE words SET example_en_2 = 'The staff helped me choose a size.', example_ko_2 = '직원이 사이즈 고르는 걸 도와줬어요.', example_en_3 = 'Can I help you with anything else?', example_ko_3 = '다른 도움이 필요하신가요?', example_en_4 = 'He helped carry the bags to the car.', example_ko_4 = '그가 가방을 차까지 옮기는 걸 도와줬어요.', example_en_5 = 'Is there anyone here who can help me?', example_ko_5 = '여기 저를 도와줄 수 있는 분이 있나요?' WHERE id = 'w_shopping_A1_26';
UPDATE words SET example_en_2 = 'I can''t find the price tag.', example_ko_2 = '가격표를 못 찾겠어요.', example_en_3 = 'Did you find what you were looking for?', example_ko_3 = '찾던 걸 찾으셨나요?', example_en_4 = 'Let me find the right size for you.', example_ko_4 = '맞는 사이즈를 찾아드릴게요.', example_en_5 = 'I found a great deal online.', example_ko_5 = '온라인에서 좋은 가격을 찾았어요.' WHERE id = 'w_shopping_A1_27';
UPDATE words SET example_en_2 = 'Take a number and wait, please.', example_ko_2 = '번호표 뽑고 기다려 주세요.', example_en_3 = 'He took the last item on the shelf.', example_ko_3 = '그는 선반의 마지막 남은 것을 가져갔어요.', example_en_4 = 'Can I take a look at that watch?', example_ko_4 = '저 시계 좀 볼 수 있을까요?', example_en_5 = 'I''ll take both, please.', example_ko_5 = '둘 다 주세요.' WHERE id = 'w_shopping_A1_28';
UPDATE words SET example_en_2 = 'Can I get a discount for this?', example_ko_2 = '이거 할인받을 수 있나요?', example_en_3 = 'I need to get some cash first.', example_ko_3 = '먼저 현금을 찾아야 해요.', example_en_4 = 'Where can I get a trolley?', example_ko_4 = '카트는 어디서 가져올 수 있나요?', example_en_5 = 'She got a great deal on the coat.', example_ko_5 = '그녀는 코트를 정말 싸게 샀어요.' WHERE id = 'w_shopping_A1_29';
UPDATE words SET example_en_2 = 'Give me a moment to check the price.', example_ko_2 = '가격 확인할 시간 좀 주세요.', example_en_3 = 'Can you give me a smaller bag?', example_ko_3 = '더 작은 봉투로 주실 수 있어요?', example_en_4 = 'They give a discount for students.', example_ko_4 = '학생에게는 할인을 해줘요.', example_en_5 = 'Please give me the total.', example_ko_5 = '합계를 알려주세요.' WHERE id = 'w_shopping_A1_30';
UPDATE words SET example_en_2 = 'Where is the food section?', example_ko_2 = '식품 코너가 어디예요?', example_en_3 = 'This store sells organic food.', example_ko_3 = '이 상점은 유기농 식품을 팔아요.', example_en_4 = 'I always buy fresh food at the market.', example_ko_4 = '저는 항상 시장에서 신선한 음식을 사요.', example_en_5 = 'Is the food here good value?', example_ko_5 = '여기 음식이 가성비가 좋나요?' WHERE id = 'w_shopping_A1_31';
UPDATE words SET example_en_2 = 'The clothes on sale are over there.', example_ko_2 = '세일 중인 옷은 저쪽에 있어요.', example_en_3 = 'Do you sell children''s clothes?', example_ko_3 = '아동복도 판매하나요?', example_en_4 = 'I need to buy some warmer clothes.', example_ko_4 = '더 따뜻한 옷을 사야 해요.', example_en_5 = 'Her clothes are always very stylish.', example_ko_5 = '그녀의 옷은 항상 매우 스타일리시해요.' WHERE id = 'w_shopping_A1_32';
UPDATE words SET example_en_2 = 'Is there a book sale on today?', example_ko_2 = '오늘 책 세일 하나요?', example_en_3 = 'I''m looking for a book on cooking.', example_ko_3 = '요리에 관한 책을 찾고 있어요.', example_en_4 = 'Could you recommend a good book?', example_ko_4 = '좋은 책 추천해 주실 수 있어요?', example_en_5 = 'The book was cheaper online.', example_ko_5 = '온라인에서 그 책이 더 저렴했어요.' WHERE id = 'w_shopping_A1_33';
UPDATE words SET example_en_2 = 'What colors does this come in?', example_ko_2 = '이건 어떤 색깔로 나와요?', example_en_3 = 'I prefer a neutral color for everyday use.', example_ko_3 = '저는 일상 사용으로 무채색을 선호해요.', example_en_4 = 'Does this come in a darker color?', example_ko_4 = '이게 더 어두운 색깔로도 있나요?', example_en_5 = 'The color of this jacket is beautiful.', example_ko_5 = '이 재킷 색깔이 정말 예뻐요.' WHERE id = 'w_shopping_A1_34';
UPDATE words SET example_en_2 = 'What number shoe do you wear?', example_ko_2 = '신발 몇 번 신으세요?', example_en_3 = 'Write your phone number on this form.', example_ko_3 = '이 양식에 전화번호를 적어 주세요.', example_en_4 = 'Take a number and the staff will call you.', example_ko_4 = '번호표를 받으면 직원이 불러드릴 거예요.', example_en_5 = 'My lucky number is seven.', example_ko_5 = '제 행운의 숫자는 7이에요.' WHERE id = 'w_shopping_A1_35';

-- ────────────────────────────────────────────────────────────
-- A2
-- ────────────────────────────────────────────────────────────
UPDATE words SET example_en_2 = 'Can I get a discount on this item?', example_ko_2 = '이 상품 할인받을 수 있나요?', example_en_3 = 'The discount code is on the website.', example_ko_3 = '할인 코드는 웹사이트에 있어요.', example_en_4 = 'They offer a ten percent discount for members.', example_ko_4 = '회원에게는 10% 할인을 해줘요.', example_en_5 = 'Is there any discount available today?', example_ko_5 = '오늘 이용 가능한 할인이 있나요?' WHERE id = 'w_shopping_A2_01';
UPDATE words SET example_en_2 = 'The winter sale starts next week.', example_ko_2 = '겨울 세일이 다음 주에 시작해요.', example_en_3 = 'I bought this dress on sale.', example_ko_3 = '이 원피스를 세일할 때 샀어요.', example_en_4 = 'Is the sale still on?', example_ko_4 = '세일이 아직 진행 중인가요?', example_en_5 = 'Everything in the store is on sale today.', example_ko_5 = '오늘 매장 내 모든 것이 세일 중이에요.' WHERE id = 'w_shopping_A2_02';
UPDATE words SET example_en_2 = 'You''ll need the receipt to get a refund.', example_ko_2 = '환불을 받으려면 영수증이 필요해요.', example_en_3 = 'The receipt shows the full breakdown.', example_ko_3 = '영수증에 전체 내역이 나와 있어요.', example_en_4 = 'Can you email me the receipt?', example_ko_4 = '영수증을 이메일로 보내주실 수 있나요?', example_en_5 = 'I lost my receipt for this purchase.', example_ko_5 = '이 구매의 영수증을 잃어버렸어요.' WHERE id = 'w_shopping_A2_03';
UPDATE words SET example_en_2 = 'What size is this in UK sizing?', example_ko_2 = '이게 영국 사이즈로는 몇 사이즈예요?', example_en_3 = 'The size chart is on the back of the label.', example_ko_3 = '사이즈 표는 라벨 뒤에 있어요.', example_en_4 = 'I normally wear a size medium.', example_ko_4 = '저는 보통 미디엄 사이즈를 입어요.', example_en_5 = 'This size is a perfect fit.', example_ko_5 = '이 사이즈가 딱 맞아요.' WHERE id = 'w_shopping_A2_04';
UPDATE words SET example_en_2 = 'Is this brand well known in Korea?', example_ko_2 = '이 브랜드가 한국에서 유명한가요?', example_en_3 = 'I prefer this brand over the others.', example_ko_3 = '저는 다른 것들보다 이 브랜드를 선호해요.', example_en_4 = 'The brand has been around for fifty years.', example_ko_4 = '그 브랜드는 50년의 역사가 있어요.', example_en_5 = 'She always buys the same brand of coffee.', example_ko_5 = '그녀는 항상 같은 브랜드의 커피를 사요.' WHERE id = 'w_shopping_A2_05';
UPDATE words SET example_en_2 = 'Ask the cashier for a receipt.', example_ko_2 = '계산원에게 영수증을 요청하세요.', example_en_3 = 'The cashier scanned the items quickly.', example_ko_3 = '계산원이 물건들을 빠르게 스캔했어요.', example_en_4 = 'There''s a long queue at the cashier.', example_ko_4 = '계산대에 줄이 길어요.', example_en_5 = 'The cashier told me the total was wrong.', example_ko_5 = '계산원이 합계가 잘못됐다고 알려줬어요.' WHERE id = 'w_shopping_A2_06';
UPDATE words SET example_en_2 = 'I don''t have the right change.', example_ko_2 = '거스름돈이 정확하지 않아요.', example_en_3 = 'He gave me the wrong change.', example_ko_3 = '그가 거스름돈을 잘못 줬어요.', example_en_4 = 'Do you have change for a fifty?', example_ko_4 = '50달러짜리 잔돈 있어요?', example_en_5 = 'She counted the change carefully.', example_ko_5 = '그녀는 거스름돈을 꼼꼼하게 세었어요.' WHERE id = 'w_shopping_A2_07';
UPDATE words SET example_en_2 = 'Can I get a refund without a receipt?', example_ko_2 = '영수증 없이도 환불받을 수 있나요?', example_en_3 = 'The refund was processed within three days.', example_ko_3 = '환불이 3일 안에 처리됐어요.', example_en_4 = 'I requested a full refund for the damaged item.', example_ko_4 = '파손된 물건에 대해 전액 환불을 요청했어요.', example_en_5 = 'Is the refund policy flexible here?', example_ko_5 = '여기 환불 정책이 유연한가요?' WHERE id = 'w_shopping_A2_08';
UPDATE words SET example_en_2 = 'My credit card has a spending limit.', example_ko_2 = '제 신용카드에는 사용 한도가 있어요.', example_en_3 = 'Is it safe to use a credit card here?', example_ko_3 = '여기서 신용카드를 사용하는 게 안전한가요?', example_en_4 = 'She applied for a new credit card last month.', example_ko_4 = '그녀는 지난달에 새 신용카드를 신청했어요.', example_en_5 = 'Do I need to sign for credit card payments?', example_ko_5 = '신용카드 결제 시 서명이 필요한가요?' WHERE id = 'w_shopping_A2_09';
UPDATE words SET example_en_2 = 'I''d like to try on the blue jacket.', example_ko_2 = '파란 재킷을 입어보고 싶어요.', example_en_3 = 'Is it okay if I try on a few pairs?', example_ko_3 = '몇 벌 입어봐도 될까요?', example_en_4 = 'You should try on shoes before buying them.', example_ko_4 = '신발은 구매 전에 신어봐야 해요.', example_en_5 = 'She tried on six dresses before choosing.', example_ko_5 = '그녀는 고르기 전에 원피스를 여섯 개 입어봤어요.' WHERE id = 'w_shopping_A2_10';
UPDATE words SET example_en_2 = 'Is there a fitting room on this floor?', example_ko_2 = '이 층에 탈의실이 있나요?', example_en_3 = 'The fitting room is at the back of the store.', example_ko_3 = '탈의실은 매장 뒤쪽에 있어요.', example_en_4 = 'There''s a queue for the fitting room.', example_ko_4 = '탈의실 앞에 줄이 있어요.', example_en_5 = 'How many items can I take into the fitting room?', example_ko_5 = '탈의실에 몇 개까지 가져갈 수 있나요?' WHERE id = 'w_shopping_A2_11';
UPDATE words SET example_en_2 = 'Please join the queue over here.', example_ko_2 = '이쪽으로 줄 서 주세요.', example_en_3 = 'The queue moved very slowly.', example_ko_3 = '줄이 매우 천천히 움직였어요.', example_en_4 = 'Is this the queue for returns?', example_ko_4 = '이게 반품 줄인가요?', example_en_5 = 'We waited in the queue for twenty minutes.', example_ko_5 = '20분 동안 줄을 섰어요.' WHERE id = 'w_shopping_A2_12';
UPDATE words SET example_en_2 = 'Can I borrow a trolley?', example_ko_2 = '카트를 빌릴 수 있나요?', example_en_3 = 'The trolley is full of groceries.', example_ko_3 = '카트가 장보기 물건으로 가득 차 있어요.', example_en_4 = 'I need a coin to unlock the trolley.', example_ko_4 = '카트를 꺼내려면 동전이 필요해요.', example_en_5 = 'She pushed the trolley to the checkout.', example_ko_5 = '그녀가 카트를 계산대로 밀었어요.' WHERE id = 'w_shopping_A2_13';
UPDATE words SET example_en_2 = 'I only grabbed a small basket.', example_ko_2 = '작은 장바구니만 집었어요.', example_en_3 = 'The basket is getting too heavy.', example_ko_3 = '장바구니가 너무 무거워지고 있어요.', example_en_4 = 'Put the vegetables in the basket.', example_ko_4 = '채소를 장바구니에 넣어요.', example_en_5 = 'She filled her basket quickly.', example_ko_5 = '그녀는 장바구니를 빠르게 채웠어요.' WHERE id = 'w_shopping_A2_14';
UPDATE words SET example_en_2 = 'The cereals are in aisle five.', example_ko_2 = '시리얼은 5번 통로에 있어요.', example_en_3 = 'Walk down the aisle to find the toiletries.', example_ko_3 = '통로를 따라 걸어가면 세면용품이 있어요.', example_en_4 = 'Which aisle are the cleaning products in?', example_ko_4 = '청소용품은 몇 번 통로에 있나요?', example_en_5 = 'A child was running down the aisle.', example_ko_5 = '아이가 통로를 뛰어다니고 있었어요.' WHERE id = 'w_shopping_A2_15';
UPDATE words SET example_en_2 = 'The product is on the middle shelf.', example_ko_2 = '그 상품은 중간 선반에 있어요.', example_en_3 = 'Can you reach the shelf at the top?', example_ko_3 = '맨 위 선반에 닿을 수 있어요?', example_en_4 = 'The shelves were almost empty.', example_ko_4 = '선반이 거의 비어 있었어요.', example_en_5 = 'Please put it back on the shelf.', example_ko_5 = '선반에 다시 놓아 주세요.' WHERE id = 'w_shopping_A2_16';
UPDATE words SET example_en_2 = 'The label shows the expiry date.', example_ko_2 = '라벨에 유통기한이 나와 있어요.', example_en_3 = 'Always read the label before using.', example_ko_3 = '사용 전에 항상 라벨을 읽어주세요.', example_en_4 = 'The price label has fallen off.', example_ko_4 = '가격 라벨이 떨어졌어요.', example_en_5 = 'The label says it''s handwash only.', example_ko_5 = '라벨에 손세탁만 된다고 나와 있어요.' WHERE id = 'w_shopping_A2_17';
UPDATE words SET example_en_2 = 'This is a great offer — don''t miss it!', example_ko_2 = '정말 좋은 특가예요 — 놓치지 마세요!', example_en_3 = 'They made me a good offer on the sofa.', example_ko_3 = '소파를 좋은 가격에 제안해줬어요.', example_en_4 = 'The offer expires at midnight.', example_ko_4 = '특가는 자정에 만료돼요.', example_en_5 = 'Can you match this offer from another store?', example_ko_5 = '다른 상점의 이 특가와 맞춰줄 수 있어요?' WHERE id = 'w_shopping_A2_18';
UPDATE words SET example_en_2 = 'I''d like to exchange this for a different color.', example_ko_2 = '다른 색상으로 교환하고 싶어요.', example_en_3 = 'Can I exchange a gift without a receipt?', example_ko_3 = '영수증 없이 선물을 교환할 수 있나요?', example_en_4 = 'They exchanged the broken item without question.', example_ko_4 = '망가진 물건을 아무 말 없이 교환해줬어요.', example_en_5 = 'I need to exchange these shoes.', example_ko_5 = '이 신발을 교환해야 해요.' WHERE id = 'w_shopping_A2_19';
UPDATE words SET example_en_2 = 'The popular sizes sell out fast.', example_ko_2 = '인기 있는 사이즈는 빨리 품절돼요.', example_en_3 = 'This café is very popular with young people.', example_ko_3 = '이 카페는 젊은이들에게 매우 인기 있어요.', example_en_4 = 'Which brand is popular right now?', example_ko_4 = '지금 어떤 브랜드가 인기 있나요?', example_en_5 = 'The popular product is out of stock.', example_ko_5 = '인기 상품이 품절되었어요.' WHERE id = 'w_shopping_A2_20';
UPDATE words SET example_en_2 = 'I judge products by quality, not price.', example_ko_2 = '저는 가격이 아니라 품질로 상품을 판단해요.', example_en_3 = 'The quality has improved a lot this year.', example_ko_3 = '올해 품질이 많이 향상됐어요.', example_en_4 = 'There''s a big difference in quality between the two.', example_ko_4 = '두 개의 품질 차이가 매우 커요.', example_en_5 = 'Good quality doesn''t have to be expensive.', example_ko_5 = '좋은 품질이 반드시 비쌀 필요는 없어요.' WHERE id = 'w_shopping_A2_21';
UPDATE words SET example_en_2 = 'Please choose a size before paying.', example_ko_2 = '결제 전에 사이즈를 선택해 주세요.', example_en_3 = 'It''s difficult to choose between these two brands.', example_ko_3 = '이 두 브랜드 중에서 고르기가 어려워요.', example_en_4 = 'He chose the cheaper option.', example_ko_4 = '그는 더 저렴한 선택지를 골랐어요.', example_en_5 = 'You can choose up to three items.', example_ko_5 = '최대 세 개까지 선택할 수 있어요.' WHERE id = 'w_shopping_A2_22';
UPDATE words SET example_en_2 = 'I need to pay for this at the counter.', example_ko_2 = '이걸 계산대에서 계산해야 해요.', example_en_3 = 'She forgot to pay for the coffee.', example_ko_3 = '그녀는 커피값을 내는 걸 잊어버렸어요.', example_en_4 = 'Can I pay for this online?', example_ko_4 = '온라인으로 계산할 수 있나요?', example_en_5 = 'He paid for the groceries with his card.', example_ko_5 = '그는 카드로 식료품을 계산했어요.' WHERE id = 'w_shopping_A2_23';
UPDATE words SET example_en_2 = 'I spent too much on shoes this month.', example_ko_2 = '이번 달에 신발에 돈을 너무 많이 썼어요.', example_en_3 = 'How much did you spend at the market?', example_ko_3 = '시장에서 얼마를 썼어요?', example_en_4 = 'I don''t want to spend more than fifty dollars.', example_ko_4 = '50달러 이상은 쓰고 싶지 않아요.', example_en_5 = 'She spent hours looking for the right gift.', example_ko_5 = '그녀는 몇 시간 동안 적절한 선물을 찾았어요.' WHERE id = 'w_shopping_A2_24';
UPDATE words SET example_en_2 = 'Save money by buying in bulk.', example_ko_2 = '대량 구매로 돈을 절약하세요.', example_en_3 = 'I save my coupons for the big sale.', example_ko_3 = '큰 세일을 위해 쿠폰을 모아요.', example_en_4 = 'Use this app to save on your shopping.', example_ko_4 = '이 앱을 이용해 쇼핑을 절약하세요.', example_en_5 = 'She saved twenty dollars by using a code.', example_ko_5 = '그녀는 코드를 사용해 20달러를 절약했어요.' WHERE id = 'w_shopping_A2_25';
UPDATE words SET example_en_2 = 'The order will arrive in two days.', example_ko_2 = '주문은 이틀 후에 도착해요.', example_en_3 = 'Can I change my order after placing it?', example_ko_3 = '주문 후에도 변경할 수 있나요?', example_en_4 = 'I placed the order this morning.', example_ko_4 = '오늘 아침에 주문했어요.', example_en_5 = 'Your order number is on the confirmation email.', example_ko_5 = '주문 번호는 확인 이메일에 있어요.' WHERE id = 'w_shopping_A2_26';
UPDATE words SET example_en_2 = 'Is express delivery available?', example_ko_2 = '빠른 배송이 가능한가요?', example_en_3 = 'The delivery was delayed by one day.', example_ko_3 = '배송이 하루 지연됐어요.', example_en_4 = 'I paid extra for same-day delivery.', example_ko_4 = '당일 배송을 위해 추가 비용을 냈어요.', example_en_5 = 'Track your delivery on the website.', example_ko_5 = '웹사이트에서 배송을 추적하세요.' WHERE id = 'w_shopping_A2_27';
UPDATE words SET example_en_2 = 'Can you wrap this as a gift?', example_ko_2 = '선물용으로 포장해 주실 수 있나요?', example_en_3 = 'She wrapped the book in brown paper.', example_ko_3 = '그녀는 책을 갈색 종이로 포장했어요.', example_en_4 = 'Gift wrapping costs an extra two dollars.', example_ko_4 = '선물 포장은 2달러가 추가돼요.', example_en_5 = 'The items were carefully wrapped for shipping.', example_ko_5 = '배송을 위해 물건들이 꼼꼼하게 포장됐어요.' WHERE id = 'w_shopping_A2_28';
UPDATE words SET example_en_2 = 'The warranty covers defects for one year.', example_ko_2 = '보증은 1년 동안 결함을 커버해요.', example_en_3 = 'Is there a warranty on this laptop?', example_ko_3 = '이 노트북에 보증이 있나요?', example_en_4 = 'My warranty expired last month.', example_ko_4 = '제 보증이 지난달에 만료됐어요.', example_en_5 = 'You should register your warranty online.', example_ko_5 = '온라인으로 보증을 등록해야 해요.' WHERE id = 'w_shopping_A2_29';
UPDATE words SET example_en_2 = 'I need to return this coat — it doesn''t fit.', example_ko_2 = '이 코트를 반품해야 해요 — 맞지 않아요.', example_en_3 = 'What is the last day I can return this?', example_ko_3 = '마지막으로 반품할 수 있는 날이 언제예요?', example_en_4 = 'The return process was quick and easy.', example_ko_4 = '반품 절차가 빠르고 쉬웠어요.', example_en_5 = 'She returned the shoes because they were too tight.', example_ko_5 = '너무 작아서 신발을 반품했어요.' WHERE id = 'w_shopping_A2_30';
UPDATE words SET example_en_2 = 'The item arrived damaged in the post.', example_ko_2 = '우편으로 온 물건이 파손된 채로 도착했어요.', example_en_3 = 'Can I get a replacement for a damaged item?', example_ko_3 = '파손된 물건에 대해 교체품을 받을 수 있나요?', example_en_4 = 'The packaging was damaged but the product was fine.', example_ko_4 = '포장은 손상됐지만 제품 자체는 괜찮았어요.', example_en_5 = 'I found a damaged label on this bottle.', example_ko_5 = '이 병에 손상된 라벨이 있는 걸 발견했어요.' WHERE id = 'w_shopping_A2_31';
UPDATE words SET example_en_2 = 'Is this colour available in size small?', example_ko_2 = '이 색상이 스몰 사이즈로도 있나요?', example_en_3 = 'The item is available online only.', example_ko_3 = '그 상품은 온라인에서만 구입할 수 있어요.', example_en_4 = 'Is there a manager available to speak with?', example_ko_4 = '대화할 수 있는 매니저가 있나요?', example_en_5 = 'The product is available in three sizes.', example_ko_5 = '그 제품은 세 가지 사이즈로 구입할 수 있어요.' WHERE id = 'w_shopping_A2_32';
UPDATE words SET example_en_2 = 'We need to reorder stock urgently.', example_ko_2 = '재고를 긴급히 재주문해야 해요.', example_en_3 = 'The stock runs low on weekends.', example_ko_3 = '주말에는 재고가 부족해져요.', example_en_4 = 'Is this item in stock?', example_ko_4 = '이 품목이 재고가 있나요?', example_en_5 = 'They keep a good stock of popular sizes.', example_ko_5 = '그들은 인기 사이즈의 재고를 잘 유지해요.' WHERE id = 'w_shopping_A2_33';
UPDATE words SET example_en_2 = 'Are you a member of this store?', example_ko_2 = '이 매장 회원이세요?', example_en_3 = 'Members get early access to the sale.', example_ko_3 = '회원은 세일에 일찍 접근할 수 있어요.', example_en_4 = 'I signed up as a member to get discounts.', example_ko_4 = '할인을 받으려고 회원으로 가입했어요.', example_en_5 = 'Existing members get an extra ten percent off.', example_ko_5 = '기존 회원은 추가로 10%를 할인받아요.' WHERE id = 'w_shopping_A2_34';
UPDATE words SET example_en_2 = 'You get double points during the sale.', example_ko_2 = '세일 기간 중에는 포인트가 두 배로 쌓여요.', example_en_3 = 'How many points do I have on my account?', example_ko_3 = '제 계정에 포인트가 몇 점 있나요?', example_en_4 = 'Redeem your points at the checkout.', example_ko_4 = '계산할 때 포인트를 사용하세요.', example_en_5 = 'I collected enough points for a free item.', example_ko_5 = '무료 상품을 받을 수 있을 만큼 포인트를 모았어요.' WHERE id = 'w_shopping_A2_35';

-- ────────────────────────────────────────────────────────────
-- B1
-- ────────────────────────────────────────────────────────────
UPDATE words SET example_en_2 = 'That''s a real bargain at that price.', example_ko_2 = '그 가격이면 정말 저렴한 거예요.', example_en_3 = 'I found a bargain at the flea market.', example_ko_3 = '벼룩시장에서 싸게 살 수 있는 걸 찾았어요.', example_en_4 = 'Is there any room to get a bargain here?', example_ko_4 = '여기서 흥정할 여지가 있나요?', example_en_5 = 'She always finds a bargain when she shops.', example_ko_5 = '그녀는 쇼핑할 때 항상 저렴한 걸 찾아요.' WHERE id = 'w_shopping_B1_01';
UPDATE words SET example_en_2 = 'Is there a self-checkout available?', example_ko_2 = '셀프 계산대가 있나요?', example_en_3 = 'Please proceed to the checkout when ready.', example_ko_3 = '준비되시면 계산대로 가세요.', example_en_4 = 'The checkout queue was twenty minutes long.', example_ko_4 = '계산대 줄이 20분이나 됐어요.', example_en_5 = 'I forgot my bag at the checkout.', example_ko_5 = '계산대에 가방을 두고 왔어요.' WHERE id = 'w_shopping_B1_02';
UPDATE words SET example_en_2 = 'She likes to browse online before buying.', example_ko_2 = '그녀는 구매 전에 온라인을 둘러보는 걸 좋아해요.', example_en_3 = 'Feel free to browse as long as you like.', example_ko_3 = '원하시는 만큼 자유롭게 둘러보세요.', example_en_4 = 'I browsed three stores before deciding.', example_ko_4 = '결정하기 전에 세 곳을 둘러봤어요.', example_en_5 = 'He browsed the shelves without buying anything.', example_ko_5 = '그는 아무것도 사지 않고 선반을 둘러봤어요.' WHERE id = 'w_shopping_B1_03';
UPDATE words SET example_en_2 = 'Wholesale prices are much lower than retail.', example_ko_2 = '도매 가격은 소매보다 훨씬 저렴해요.', example_en_3 = 'She buys clothes wholesale and resells them.', example_ko_3 = '그녀는 옷을 도매로 사서 되팔아요.', example_en_4 = 'Is there a wholesale market nearby?', example_ko_4 = '근처에 도매 시장이 있나요?', example_en_5 = 'You need a licence to buy at wholesale rates.', example_ko_5 = '도매 가격으로 구매하려면 허가증이 필요해요.' WHERE id = 'w_shopping_B1_04';
UPDATE words SET example_en_2 = 'Retail prices are set by the manufacturer.', example_ko_2 = '소매 가격은 제조사가 정해요.', example_en_3 = 'She works in retail management.', example_ko_3 = '그녀는 소매 관리 분야에서 일해요.', example_en_4 = 'The retail sector has changed a lot online.', example_ko_4 = '소매 분야는 온라인으로 많이 바뀌었어요.', example_en_5 = 'Retail stores often have seasonal sales.', example_ko_5 = '소매점은 보통 계절별 세일을 해요.' WHERE id = 'w_shopping_B1_05';
UPDATE words SET example_en_2 = 'I have a coupon for twenty percent off.', example_ko_2 = '20% 할인 쿠폰이 있어요.', example_en_3 = 'Can I use more than one coupon?', example_ko_3 = '쿠폰을 두 개 이상 사용할 수 있나요?', example_en_4 = 'The coupon expires at the end of the month.', example_ko_4 = '쿠폰은 이달 말에 만료돼요.', example_en_5 = 'She downloaded a coupon from the app.', example_ko_5 = '그녀는 앱에서 쿠폰을 다운로드했어요.' WHERE id = 'w_shopping_B1_06';
UPDATE words SET example_en_2 = 'Their loyalty programme offers great rewards.', example_ko_2 = '그들의 로열티 프로그램은 훌륭한 보상을 제공해요.', example_en_3 = 'I joined the loyalty scheme to earn points.', example_ko_3 = '포인트를 쌓으려고 로열티 제도에 가입했어요.', example_en_4 = 'Brand loyalty is hard to build.', example_ko_4 = '브랜드 충성도를 쌓기는 어려워요.', example_en_5 = 'Do you reward customer loyalty with discounts?', example_ko_5 = '고객 충성도에 대한 보상으로 할인을 제공하나요?' WHERE id = 'w_shopping_B1_07';
UPDATE words SET example_en_2 = 'Please send me an invoice by email.', example_ko_2 = '이메일로 청구서를 보내주세요.', example_en_3 = 'The invoice shows all items purchased.', example_ko_3 = '청구서에 구매한 모든 항목이 나와 있어요.', example_en_4 = 'I need an invoice for my expense report.', example_ko_4 = '경비 보고서를 위해 청구서가 필요해요.', example_en_5 = 'When will you issue the invoice?', example_ko_5 = '청구서는 언제 발행되나요?' WHERE id = 'w_shopping_B1_08';
UPDATE words SET example_en_2 = 'Which vendor has the best prices here?', example_ko_2 = '여기서 어느 판매자가 가격이 제일 좋아요?', example_en_3 = 'The market has over a hundred vendors.', example_ko_3 = '그 시장에는 100명 이상의 판매자가 있어요.', example_en_4 = 'We need to find a reliable vendor for these goods.', example_ko_4 = '이 상품들을 위한 믿을 수 있는 공급업체를 찾아야 해요.', example_en_5 = 'The vendor offered a bulk discount.', example_ko_5 = '판매자가 대량 할인을 제안했어요.' WHERE id = 'w_shopping_B1_09';
UPDATE words SET example_en_2 = 'He tried to negotiate a lower price.', example_ko_2 = '그는 더 낮은 가격을 협상하려고 했어요.', example_en_3 = 'Can we negotiate the delivery terms?', example_ko_3 = '배송 조건을 협상할 수 있나요?', example_en_4 = 'She negotiated a ten percent discount.', example_ko_4 = '그녀는 10% 할인을 협상했어요.', example_en_5 = 'It''s always worth trying to negotiate.', example_ko_5 = '항상 협상을 시도해볼 가치가 있어요.' WHERE id = 'w_shopping_B1_10';
UPDATE words SET example_en_2 = 'My monthly shopping budget is fixed.', example_ko_2 = '제 월별 쇼핑 예산은 정해져 있어요.', example_en_3 = 'We need to work within a tight budget.', example_ko_3 = '빠듯한 예산 안에서 일해야 해요.', example_en_4 = 'She set a strict budget for the holiday shopping.', example_ko_4 = '그녀는 명절 쇼핑을 위해 엄격한 예산을 정했어요.', example_en_5 = 'There are great options even on a small budget.', example_ko_5 = '적은 예산으로도 훌륭한 선택지가 있어요.' WHERE id = 'w_shopping_B1_11';
UPDATE words SET example_en_2 = 'A price comparison can save you a lot.', example_ko_2 = '가격 비교를 하면 많은 돈을 절약할 수 있어요.', example_en_3 = 'Use a comparison website to find the best deal.', example_ko_3 = '비교 웹사이트를 이용해서 최고의 가격을 찾아보세요.', example_en_4 = 'The comparison showed a big price difference.', example_ko_4 = '비교를 해보니 가격 차이가 컸어요.', example_en_5 = 'She did a careful comparison before buying.', example_ko_5 = '그녀는 구매 전에 꼼꼼하게 비교했어요.' WHERE id = 'w_shopping_B1_12';
UPDATE words SET example_en_2 = 'The purchase was made online last night.', example_ko_2 = '구매는 어젯밤 온라인으로 이루어졌어요.', example_en_3 = 'Can I cancel a purchase after confirming?', example_ko_3 = '확인 후에도 구매를 취소할 수 있나요?', example_en_4 = 'The purchase price includes delivery.', example_ko_4 = '구매 가격에 배송비가 포함돼 있어요.', example_en_5 = 'This purchase qualifies for a free gift.', example_ko_5 = '이 구매는 무료 선물 대상이에요.' WHERE id = 'w_shopping_B1_13';
UPDATE words SET example_en_2 = 'Every transaction is recorded digitally.', example_ko_2 = '모든 거래는 디지털로 기록돼요.', example_en_3 = 'The transaction failed due to a network error.', example_ko_3 = '네트워크 오류로 거래가 실패했어요.', example_en_4 = 'Please confirm the transaction amount.', example_ko_4 = '거래 금액을 확인해 주세요.', example_en_5 = 'The transaction was completed in seconds.', example_ko_5 = '거래가 몇 초 만에 완료됐어요.' WHERE id = 'w_shopping_B1_14';
UPDATE words SET example_en_2 = 'You can pay in six monthly installments.', example_ko_2 = '6개월 할부로 납부할 수 있어요.', example_en_3 = 'Is an installment plan available for this product?', example_ko_3 = '이 제품에 할부 플랜이 가능한가요?', example_en_4 = 'She paid for the fridge in installments.', example_ko_4 = '그녀는 냉장고를 할부로 납부했어요.', example_en_5 = 'The final installment is due next month.', example_ko_5 = '마지막 할부금은 다음 달이 기한이에요.' WHERE id = 'w_shopping_B1_15';
UPDATE words SET example_en_2 = 'Standard shipping takes three to five days.', example_ko_2 = '일반 배송은 3~5일이 걸려요.', example_en_3 = 'Shipping is free on orders over thirty dollars.', example_ko_3 = '30달러 이상 주문 시 배송비가 무료예요.', example_en_4 = 'What are the shipping options available?', example_ko_4 = '어떤 배송 옵션이 있나요?', example_en_5 = 'International shipping may take longer.', example_ko_5 = '국제 배송은 더 오래 걸릴 수 있어요.' WHERE id = 'w_shopping_B1_16';
UPDATE words SET example_en_2 = 'You can use the tracking number to follow your parcel.', example_ko_2 = '운송장 번호로 소포를 추적할 수 있어요.', example_en_3 = 'Tracking shows the parcel is out for delivery.', example_ko_3 = '추적을 보니 소포가 배송 중이에요.', example_en_4 = 'I set up tracking alerts on my phone.', example_ko_4 = '휴대폰에 배송 추적 알림을 설정했어요.', example_en_5 = 'Does your store offer real-time tracking?', example_ko_5 = '매장에서 실시간 추적 서비스를 제공하나요?' WHERE id = 'w_shopping_B1_17';
UPDATE words SET example_en_2 = 'I have a monthly subscription to that service.', example_ko_2 = '그 서비스에 월 구독권이 있어요.', example_en_3 = 'The subscription renews automatically each month.', example_ko_3 = '구독은 매달 자동으로 갱신돼요.', example_en_4 = 'Cancel your subscription before the trial ends.', example_ko_4 = '체험 기간이 끝나기 전에 구독을 취소하세요.', example_en_5 = 'A yearly subscription is cheaper than monthly.', example_ko_5 = '연간 구독이 월별보다 더 저렴해요.' WHERE id = 'w_shopping_B1_18';
UPDATE words SET example_en_2 = 'Buying in bulk saves a lot of money.', example_ko_2 = '대량 구매를 하면 돈을 많이 절약할 수 있어요.', example_en_3 = 'They offer a discount for bulk orders.', example_ko_3 = '대량 주문에는 할인을 제공해요.', example_en_4 = 'We bought paper towels in bulk at the warehouse.', example_ko_4 = '창고형 마트에서 페이퍼 타월을 대량으로 샀어요.', example_en_5 = 'Bulk purchasing reduces the cost per unit.', example_ko_5 = '대량 구매는 단가를 낮춰줘요.' WHERE id = 'w_shopping_B1_19';
UPDATE words SET example_en_2 = 'I prefer buying second-hand to save money.', example_ko_2 = '돈을 절약하기 위해 중고 구매를 선호해요.', example_en_3 = 'This second-hand jacket is in perfect condition.', example_ko_3 = '이 중고 재킷은 상태가 아주 좋아요.', example_en_4 = 'She sells second-hand clothes online.', example_ko_4 = '그녀는 온라인으로 중고 옷을 팔아요.', example_en_5 = 'The second-hand market is growing fast.', example_ko_5 = '중고 시장이 빠르게 성장하고 있어요.' WHERE id = 'w_shopping_B1_20';
UPDATE words SET example_en_2 = 'This brand has an outlet in the city centre.', example_ko_2 = '이 브랜드는 도심에 아웃렛이 있어요.', example_en_3 = 'Outlet prices are lower than regular stores.', example_ko_3 = '아웃렛 가격은 일반 매장보다 저렴해요.', example_en_4 = 'I found amazing deals at the outlet mall.', example_ko_4 = '아웃렛 몰에서 엄청난 거래를 발견했어요.', example_en_5 = 'Is there a factory outlet near here?', example_ko_5 = '근처에 팩토리 아웃렛이 있나요?' WHERE id = 'w_shopping_B1_21';
UPDATE words SET example_en_2 = 'I made an impulse purchase at the airport.', example_ko_2 = '공항에서 충동구매를 했어요.', example_en_3 = 'Try to resist impulse buys at the checkout.', example_ko_3 = '계산대에서 충동 구매를 참으려고 해요.', example_en_4 = 'That was a complete impulse — I didn''t plan it.', example_ko_4 = '그건 완전한 충동이었어요 — 계획에 없었어요.', example_en_5 = 'Shops place candy near checkout to trigger impulse buys.', example_ko_5 = '상점들은 충동 구매를 유발하려고 계산대 근처에 사탕을 놓아요.' WHERE id = 'w_shopping_B1_22';
UPDATE words SET example_en_2 = 'I''d like to make a complaint about my order.', example_ko_2 = '주문에 대해 불만을 제기하고 싶어요.', example_en_3 = 'She filed a complaint with the manager.', example_ko_3 = '그녀는 매니저에게 불만을 제기했어요.', example_en_4 = 'How do I submit a formal complaint?', example_ko_4 = '공식 불만은 어떻게 제출하나요?', example_en_5 = 'His complaint was resolved within two days.', example_ko_5 = '그의 불만은 이틀 안에 해결됐어요.' WHERE id = 'w_shopping_B1_23';
UPDATE words SET example_en_2 = 'Does this product come with a guarantee?', example_ko_2 = '이 제품에 품질 보증이 포함되어 있나요?', example_en_3 = 'The guarantee covers parts and labour.', example_ko_3 = '보증은 부품과 인건비를 포함해요.', example_en_4 = 'I have a money-back guarantee if not satisfied.', example_ko_4 = '만족하지 않으면 환불 보증이 있어요.', example_en_5 = 'The two-year guarantee gave me confidence to buy.', example_ko_5 = '2년 보증이 있어서 안심하고 구매했어요.' WHERE id = 'w_shopping_B1_24';
UPDATE words SET example_en_2 = 'They''re selling off surplus stock at half price.', example_ko_2 = '잉여 재고를 반값에 팔고 있어요.', example_en_3 = 'The warehouse had a surplus of winter coats.', example_ko_3 = '창고에 겨울 코트 잉여분이 있었어요.', example_en_4 = 'A budget surplus allowed them to lower prices.', example_ko_4 = '예산 잉여분이 생겨서 가격을 낮출 수 있었어요.', example_en_5 = 'The surplus was donated to charity.', example_ko_5 = '잉여분은 자선단체에 기부됐어요.' WHERE id = 'w_shopping_B1_25';
UPDATE words SET example_en_2 = 'The clearance sale ends this Sunday.', example_ko_2 = '재고 처분 세일은 이번 일요일에 끝나요.', example_en_3 = 'I got these shoes in the clearance section.', example_ko_3 = '이 신발을 재고 처분 코너에서 샀어요.', example_en_4 = 'Clearance items cannot be returned.', example_ko_4 = '재고 처분 상품은 반품이 안 돼요.', example_en_5 = 'She always checks the clearance rack first.', example_ko_5 = '그녀는 항상 재고 처분 진열대를 먼저 확인해요.' WHERE id = 'w_shopping_B1_26';
UPDATE words SET example_en_2 = 'The merchant offered a fifteen percent deal.', example_ko_2 = '판매자가 15% 할인을 제안했어요.', example_en_3 = 'Several merchants were selling similar goods.', example_ko_3 = '여러 판매자가 비슷한 상품을 팔고 있었어요.', example_en_4 = 'Is this merchant authorised to sell this brand?', example_ko_4 = '이 판매자가 이 브랜드를 판매할 권한이 있나요?', example_en_5 = 'She became a licensed merchant last year.', example_ko_5 = '그녀는 작년에 공인 판매자가 됐어요.' WHERE id = 'w_shopping_B1_27';
UPDATE words SET example_en_2 = 'The checkout process only takes a minute.', example_ko_2 = '결제 과정은 1분밖에 안 걸려요.', example_en_3 = 'The online checkout process was very smooth.', example_ko_3 = '온라인 결제 과정이 매우 매끄러웠어요.', example_en_4 = 'The checkout process requires a valid ID.', example_ko_4 = '결제 과정에 유효한 신분증이 필요해요.', example_en_5 = 'Can you simplify your checkout process?', example_ko_5 = '결제 과정을 간소화할 수 있나요?' WHERE id = 'w_shopping_B1_28';
UPDATE words SET example_en_2 = 'High demand caused prices to rise quickly.', example_ko_2 = '높은 수요로 인해 가격이 빠르게 올랐어요.', example_en_3 = 'There is a huge demand for this product.', example_ko_3 = '이 제품에 대한 수요가 엄청나요.', example_en_4 = 'We couldn''t keep up with demand during the sale.', example_ko_4 = '세일 기간 동안 수요를 따라가지 못했어요.', example_en_5 = 'Demand for eco-friendly products is growing.', example_ko_5 = '친환경 제품에 대한 수요가 증가하고 있어요.' WHERE id = 'w_shopping_B1_29';
UPDATE words SET example_en_2 = 'Supply was limited, so prices went up.', example_ko_2 = '공급이 제한적이어서 가격이 올랐어요.', example_en_3 = 'The supply chain was disrupted by the weather.', example_ko_3 = '날씨로 인해 공급망이 차질을 빚었어요.', example_en_4 = 'We need to increase supply to meet demand.', example_ko_4 = '수요를 충족하기 위해 공급을 늘려야 해요.', example_en_5 = 'The company has a reliable supply of materials.', example_ko_5 = '그 회사는 안정적인 원자재 공급처가 있어요.' WHERE id = 'w_shopping_B1_30';
UPDATE words SET example_en_2 = 'The promotion ends at midnight tonight.', example_ko_2 = '프로모션은 오늘 자정에 종료돼요.', example_en_3 = 'They ran a buy-one-get-one promotion.', example_ko_3 = '하나 사면 하나 무료 프로모션을 진행했어요.', example_en_4 = 'Sign up for emails to receive promotion alerts.', example_ko_4 = '프로모션 알림을 받으려면 이메일을 등록하세요.', example_en_5 = 'The promotion attracted thousands of customers.', example_ko_5 = '그 프로모션은 수천 명의 고객을 끌어들였어요.' WHERE id = 'w_shopping_B1_31';
UPDATE words SET example_en_2 = 'The advertisement was misleading.', example_ko_2 = '그 광고는 오해의 소지가 있었어요.', example_en_3 = 'I saw an advertisement for this product online.', example_ko_3 = '온라인에서 이 제품 광고를 봤어요.', example_en_4 = 'The advertisement made me want to buy it.', example_ko_4 = '그 광고를 보고 사고 싶어졌어요.', example_en_5 = 'Effective advertisements boost sales significantly.', example_ko_5 = '효과적인 광고는 매출을 크게 올려줘요.' WHERE id = 'w_shopping_B1_32';
UPDATE words SET example_en_2 = 'The artist sells her work on consignment.', example_ko_2 = '그 예술가는 위탁 판매로 작품을 팔아요.', example_en_3 = 'We took the furniture on consignment from the seller.', example_ko_3 = '우리는 판매자로부터 가구를 위탁받았어요.', example_en_4 = 'Consignment shops sell goods for a percentage of the price.', example_ko_4 = '위탁 판매점은 가격의 일부를 받고 물건을 팔아요.', example_en_5 = 'This coat is on consignment from a local designer.', example_ko_5 = '이 코트는 지역 디자이너의 위탁 상품이에요.' WHERE id = 'w_shopping_B1_33';
UPDATE words SET example_en_2 = 'The price tag was missing from the shelf.', example_ko_2 = '선반에 가격표가 없었어요.', example_en_3 = 'Always check the price tag before buying.', example_ko_3 = '구매 전에 항상 가격표를 확인하세요.', example_en_4 = 'The price tag says thirty, but I got it for twenty.', example_ko_4 = '가격표는 30이라고 나와 있지만 20에 샀어요.', example_en_5 = 'She removed the price tag before giving the gift.', example_ko_5 = '선물하기 전에 가격표를 뗐어요.' WHERE id = 'w_shopping_B1_34';
UPDATE words SET example_en_2 = 'As an afterthought, I grabbed a bottle of water.', example_ko_2 = '나중에 생각나서 물 한 병을 집어들었어요.', example_en_3 = 'Adding the warranty was almost an afterthought.', example_ko_3 = '보증을 추가한 건 거의 나중에 생각난 거였어요.', example_en_4 = 'She bought a card as an afterthought on the way out.', example_ko_4 = '나가는 길에 나중에 생각나서 카드를 샀어요.', example_en_5 = 'Don''t treat customer service as an afterthought.', example_ko_5 = '고객 서비스를 나중에 생각할 일로 취급하지 마세요.' WHERE id = 'w_shopping_B1_35';
