-- EngCat — Weather (날씨) 주제 단어 + 패턴
-- 210 words (35 per CEFR level A1~C2) + 42 patterns (7 per level)
-- Generated: 2026-05-24

-- ══════════════════════════════════════
-- WORDS — A1 (35개)
-- 핵심 날씨 어휘: sunny, rainy, hot, cold, windy, cloudy, snow, warm, cool, weather ...
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_weather_A1_01','sunny','/ˈsʌni/','adjective','화창한','Bright with sunlight and clear skies.','It''s a {sunny} day today.','오늘은 화창한 날이에요.','sunny','A1','weather',1,'sunny day blue sky bright'),
('w_weather_A1_02','rainy','/ˈreɪni/','adjective','비가 오는','Having a lot of rain.','I don''t like {rainy} weather.','저는 비 오는 날씨를 별로 좋아하지 않아요.','rainy','A1','weather',1,'rainy day puddles umbrella'),
('w_weather_A1_03','hot','/hɒt/','adjective','더운, 뜨거운','Having a high temperature.','It is very {hot} outside today.','오늘 밖이 정말 더워요.','hot','A1','weather',1,'hot summer sun heat'),
('w_weather_A1_04','cold','/koʊld/','adjective','추운, 차가운','Having a low temperature.','The weather is {cold} in January.','1월에는 날씨가 추워요.','cold','A1','weather',1,'cold winter snow frost'),
('w_weather_A1_05','windy','/ˈwɪndi/','adjective','바람이 부는','With a lot of wind.','It is very {windy} today.','오늘 바람이 많이 불어요.','windy','A1','weather',1,'windy trees blowing leaves'),
('w_weather_A1_06','cloudy','/ˈklaʊdi/','adjective','흐린','Covered with clouds.','The sky is {cloudy} this morning.','오늘 아침 하늘이 흐려요.','cloudy','A1','weather',1,'cloudy sky grey overcast'),
('w_weather_A1_07','snow','/snoʊ/','noun','눈','Frozen water that falls from the sky as soft white flakes.','The children love to play in the {snow}.','아이들은 눈 속에서 노는 걸 좋아해요.','snow','A1','weather',1,'snow white winter landscape'),
('w_weather_A1_08','warm','/wɔːrm/','adjective','따뜻한','At a comfortably high temperature.','Spring weather is usually {warm}.','봄 날씨는 보통 따뜻해요.','warm','A1','weather',1,'warm sunshine spring flowers'),
('w_weather_A1_09','cool','/kuːl/','adjective','선선한, 시원한','Pleasantly low in temperature.','The evening air feels {cool}.','저녁 공기가 선선하게 느껴져요.','cool','A1','weather',1,'cool breeze evening nature'),
('w_weather_A1_10','weather','/ˈweðər/','noun','날씨','The state of the atmosphere at a place and time.','What is the {weather} like today?','오늘 날씨가 어때요?','weather','A1','weather',1,'weather sky clouds sun'),
('w_weather_A1_11','rain','/reɪn/','noun','비','Water that falls from clouds as drops.','There will be {rain} this afternoon.','오늘 오후에 비가 올 거예요.','rain','A1','weather',1,'rain drops falling puddle'),
('w_weather_A1_12','sun','/sʌn/','noun','태양, 햇빛','The star that gives light and heat to the Earth.','The {sun} is very bright today.','오늘 햇빛이 정말 밝아요.','sun','A1','weather',1,'sun bright sky yellow'),
('w_weather_A1_13','wind','/wɪnd/','noun','바람','Air moving from one place to another.','The {wind} is blowing hard tonight.','오늘 밤 바람이 세게 불고 있어요.','wind','A1','weather',1,'wind trees branches blowing'),
('w_weather_A1_14','cloud','/klaʊd/','noun','구름','A white or grey mass in the sky made of water drops.','There are big {cloud}s in the sky.','하늘에 커다란 구름이 있어요.','cloud','A1','weather',2,'cloud white sky fluffy'),
('w_weather_A1_15','ice','/aɪs/','noun','얼음, 빙판','Frozen water.','Be careful — there is {ice} on the road.','조심하세요. 도로에 빙판이 있어요.','ice','A1','weather',2,'ice frozen road winter'),
('w_weather_A1_16','wet','/wet/','adjective','젖은, 비 오는','Covered with water or another liquid.','My shoes got {wet} in the rain.','빗속에서 신발이 젖었어요.','wet','A1','weather',2,'wet rain shoes puddle'),
('w_weather_A1_17','dry','/draɪ/','adjective','건조한','Free from moisture or liquid.','This summer has been very {dry}.','이번 여름은 정말 건조했어요.','dry','A1','weather',2,'dry cracked earth desert'),
('w_weather_A1_18','storm','/stɔːrm/','noun','폭풍','A period of bad weather with strong winds and rain.','A big {storm} hit the coast last night.','어젯밤 해안에 큰 폭풍이 왔어요.','storm','A1','weather',2,'storm dark clouds lightning'),
('w_weather_A1_19','umbrella','/ʌmˈbrelə/','noun','우산','A device for keeping off rain.','Don''t forget to bring your {umbrella}.','우산 가져가는 거 잊지 마세요.','umbrella','A1','weather',2,'umbrella rain protection'),
('w_weather_A1_20','coat','/koʊt/','noun','코트, 외투','A long outer garment worn to stay warm.','You should wear a {coat} today.','오늘은 코트를 입는 게 좋겠어요.','coat','A1','weather',2,'coat winter warm clothing'),
('w_weather_A1_21','season','/ˈsiːzən/','noun','계절','One of the four parts of the year: spring, summer, autumn, winter.','Summer is my favourite {season}.','여름이 제가 가장 좋아하는 계절이에요.','season','A1','weather',2,'season four spring summer autumn winter'),
('w_weather_A1_22','spring','/sprɪŋ/','noun','봄','The season between winter and summer.','The flowers bloom in {spring}.','봄에 꽃이 피어요.','spring','A1','weather',2,'spring flowers blossoms green'),
('w_weather_A1_23','summer','/ˈsʌmər/','noun','여름','The warmest season of the year.','It is very hot in {summer}.','여름에는 정말 더워요.','summer','A1','weather',2,'summer beach hot sunny'),
('w_weather_A1_24','winter','/ˈwɪntər/','noun','겨울','The coldest season of the year.','I love drinking hot cocoa in {winter}.','저는 겨울에 핫초코 마시는 걸 좋아해요.','winter','A1','weather',2,'winter snow cold cosy'),
('w_weather_A1_25','outside','/ˌaʊtˈsaɪd/','adverb','밖에, 야외에','In or to the open air.','It is raining {outside}.','밖에 비가 오고 있어요.','outside','A1','weather',3,'outside rain street'),
('w_weather_A1_26','sky','/skaɪ/','noun','하늘','The region of the atmosphere seen from Earth.','The {sky} is blue and clear today.','오늘 하늘이 파랗고 맑아요.','sky','A1','weather',3,'sky blue clear horizon'),
('w_weather_A1_27','temperature','/ˈtemprɪtʃər/','noun','기온, 온도','The degree of heat or cold measured on a scale.','The {temperature} will drop tonight.','오늘 밤 기온이 떨어질 거예요.','temperature','A1','weather',3,'temperature thermometer weather'),
('w_weather_A1_28','fog','/fɒɡ/','noun','안개','A thick cloud of water droplets near the ground.','Drive slowly because of the {fog}.','안개 때문에 천천히 운전하세요.','fog','A1','weather',3,'fog misty morning road'),
('w_weather_A1_29','sunshine','/ˈsʌnʃaɪn/','noun','햇살','Direct light from the sun.','We had lovely {sunshine} all weekend.','주말 내내 멋진 햇살이 가득했어요.','sunshine','A1','weather',3,'sunshine bright warm light'),
('w_weather_A1_30','rainbow','/ˈreɪnboʊ/','noun','무지개','An arch of colours in the sky after rain.','Look at that beautiful {rainbow}!','저 예쁜 무지개 좀 봐요!','rainbow','A1','weather',3,'rainbow colourful sky after rain'),
('w_weather_A1_31','hail','/heɪl/','noun','우박','Pellets of frozen rain that fall from the sky.','The {hail} damaged many car rooftops.','우박이 많은 차 지붕을 망가뜨렸어요.','hail','A1','weather',3,'hail ice pellets storm'),
('w_weather_A1_32','thunder','/ˈθʌndər/','noun','천둥','The loud noise heard during a storm.','The {thunder} woke me up last night.','어젯밤에 천둥 소리에 잠이 깼어요.','thunder','A1','weather',3,'thunder storm lightning'),
('w_weather_A1_33','lightning','/ˈlaɪtnɪŋ/','noun','번개','A flash of bright light in the sky during a storm.','We saw {lightning} in the distance.','멀리서 번개가 보였어요.','lightning','A1','weather',3,'lightning flash storm night'),
('w_weather_A1_34','flood','/flʌd/','noun','홍수','An overflow of water over normally dry land.','Heavy rain caused a {flood} in the town.','폭우로 마을에 홍수가 났어요.','flood','A1','weather',3,'flood water street submerged'),
('w_weather_A1_35','autumn','/ˈɔːtəm/','noun','가을','The season between summer and winter.','The leaves turn red in {autumn}.','가을에 나뭇잎이 빨갛게 물들어요.','autumn','A1','weather',3,'autumn leaves red orange fall');

-- ══════════════════════════════════════
-- WORDS — A2 (35개)
-- forecast, temperature, humid, storm, thunder, lightning, fog, frost, drizzle, breeze ...
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_weather_A2_01','forecast','/ˈfɔːrkæst/','noun','일기 예보','A statement about what the weather will be like in the future.','The {forecast} says it will snow tomorrow.','예보에서 내일 눈이 온다고 해요.','forecast','A2','weather',1,'forecast weather map prediction'),
('w_weather_A2_02','temperature','/ˈtemprɪtʃər/','noun','기온','The degree of heat or coldness measured on a specific scale.','The {temperature} reached 35 degrees today.','오늘 기온이 35도까지 올랐어요.','temperature','A2','weather',1,'temperature thermometer heat'),
('w_weather_A2_03','humid','/ˈhjuːmɪd/','adjective','습한','Having a lot of water vapour in the air.','Seoul is very {humid} in August.','서울은 8월에 정말 습해요.','humid','A2','weather',1,'humid sticky air tropics'),
('w_weather_A2_04','thunder','/ˈθʌndər/','noun','천둥','The loud rumbling sound that follows lightning.','There was a big {thunder} storm overnight.','밤새 엄청난 천둥 번개가 쳤어요.','thunder','A2','weather',1,'thunder storm dark sky'),
('w_weather_A2_05','lightning','/ˈlaɪtnɪŋ/','noun','번개','A flash of light caused by electricity in the atmosphere.','The {lightning} lit up the whole sky.','번개가 하늘 전체를 밝혔어요.','lightning','A2','weather',1,'lightning bolt night sky'),
('w_weather_A2_06','fog','/fɒɡ/','noun','안개','A dense cloud of tiny water droplets near the ground.','The airport was closed because of thick {fog}.','짙은 안개로 공항이 폐쇄됐어요.','fog','A2','weather',1,'fog thick misty road'),
('w_weather_A2_07','frost','/frɒst/','noun','서리','A thin layer of ice that forms on surfaces when temperatures drop below freezing.','There was {frost} on the grass this morning.','오늘 아침 풀잎에 서리가 내렸어요.','frost','A2','weather',1,'frost ice grass morning'),
('w_weather_A2_08','drizzle','/ˈdrɪzəl/','noun','이슬비, 부슬비','Light rain falling in very small drops.','It''s just a light {drizzle} — you don''t need an umbrella.','가벼운 이슬비라 우산은 필요 없어요.','drizzle','A2','weather',1,'drizzle light rain mist'),
('w_weather_A2_09','breeze','/briːz/','noun','산들바람','A gentle, light wind.','A cool {breeze} came in through the window.','시원한 산들바람이 창문으로 들어왔어요.','breeze','A2','weather',1,'breeze gentle wind leaves'),
('w_weather_A2_10','shower','/ˈʃaʊər/','noun','소나기','A brief fall of rain.','There will be afternoon {shower}s today.','오늘 오후에 소나기가 내릴 거예요.','shower','A2','weather',2,'shower rain afternoon brief'),
('w_weather_A2_11','overcast','/ˌoʊvərˈkæst/','adjective','잔뜩 흐린','(Of the sky) covered with cloud.','The sky is completely {overcast} today.','오늘 하늘이 완전히 흐려요.','overcast','A2','weather',2,'overcast grey sky clouds'),
('w_weather_A2_12','blizzard','/ˈblɪzərd/','noun','눈보라','A severe snowstorm with strong winds.','The {blizzard} shut down the whole city.','눈보라로 도시 전체가 마비됐어요.','blizzard','A2','weather',2,'blizzard snowstorm winter'),
('w_weather_A2_13','heatwave','/ˈhiːtweɪv/','noun','폭염, 열파','A prolonged period of abnormally hot weather.','Many elderly people suffer during a {heatwave}.','폭염 중에 노인분들이 많이 힘들어하세요.','heatwave','A2','weather',2,'heatwave hot sun dry'),
('w_weather_A2_14','slippery','/ˈslɪpəri/','adjective','미끄러운','Difficult to stand on or hold because of a smooth or wet surface.','The roads are {slippery} after the snow.','눈이 온 후 도로가 미끄러워요.','slippery','A2','weather',2,'slippery road ice winter'),
('w_weather_A2_15','humid','/ˈhjuːmɪd/','adjective','습한, 눅눅한','(Already listed at A2_03 — variant entry for classroom use) Feeling damp and warm.','The air is so {humid} that my hair is frizzy.','공기가 너무 습해서 머리가 부풀었어요.','humid','A2','weather',2,'humid air sticky tropical'),
('w_weather_A2_16','chilly','/ˈtʃɪli/','adjective','쌀쌀한','Unpleasantly cold.','It gets {chilly} in the evening here.','이곳은 저녁에 쌀쌀해져요.','chilly','A2','weather',2,'chilly cold evening autumn'),
('w_weather_A2_17','mild','/maɪld/','adjective','온화한','(Of weather) not extreme; gently warm.','We had a {mild} winter this year.','올해는 겨울이 온화했어요.','mild','A2','weather',2,'mild weather pleasant green'),
('w_weather_A2_18','pour','/pɔːr/','verb','쏟아지다 (비)','(Of rain) to fall heavily.','It is {pour}ing outside right now.','지금 밖에 비가 쏟아지고 있어요.','pouring','A2','weather',2,'pouring rain heavy downpour'),
('w_weather_A2_19','snowfall','/ˈsnoʊfɔːl/','noun','강설, 눈이 내림','Snow falling or the amount of snow that falls.','We had the heaviest {snowfall} in ten years.','10년 만에 가장 많은 눈이 내렸어요.','snowfall','A2','weather',2,'snowfall winter white landscape'),
('w_weather_A2_20','freezing','/ˈfriːzɪŋ/','adjective','얼어붙을 듯이 추운','Extremely cold.','It''s absolutely {freezing} outside today.','오늘 밖이 정말 얼어붙을 듯이 추워요.','freezing','A2','weather',2,'freezing cold ice winter'),
('w_weather_A2_21','humid','/ˈhjuːmɪd/','adjective','습기 많은','Moist and warm, making one feel uncomfortable.','The {humid} heat is very tiring.','습한 더위는 정말 지치게 해요.','humid','A2','weather',3,'humid tropical air green'),
('w_weather_A2_22','gust','/ɡʌst/','noun','돌풍','A sudden strong blast of wind.','A sudden {gust} blew my hat off.','갑자기 불어온 돌풍이 모자를 날려버렸어요.','gust','A2','weather',3,'gust wind strong sudden'),
('w_weather_A2_23','damp','/dæmp/','adjective','축축한','Slightly wet in an unpleasant way.','The ground is still {damp} from last night''s rain.','어젯밤 비로 땅이 아직 축축해요.','damp','A2','weather',3,'damp wet ground rain'),
('w_weather_A2_24','muggy','/ˈmʌɡi/','adjective','무더운, 후덥지근한','Unpleasantly warm and humid.','The weather is so {muggy} today.','오늘 날씨가 너무 무더워요.','muggy','A2','weather',3,'muggy hot humid summer'),
('w_weather_A2_25','clear','/klɪər/','adjective','맑은 (날씨)','(Of the sky or weather) free from cloud or rain.','The weather looks {clear} this afternoon.','오늘 오후에는 날씨가 맑겠어요.','clear','A2','weather',3,'clear sky blue sunny'),
('w_weather_A2_26','sunny spell','/ˈsʌni spel/','noun phrase','맑음 구간','A short period of sunshine.','There will be a {sunny spell} in the morning.','오전에 잠깐 맑겠어요.','sunny spell','A2','weather',3,'sunny spell bright morning'),
('w_weather_A2_27','wind chill','/wɪnd tʃɪl/','noun','체감 온도 (바람으로 낮아진)','The cooling effect of wind on the temperature felt on skin.','The {wind chill} makes it feel like minus fifteen.','체감 온도는 영하 15도예요.','wind chill','A2','weather',3,'wind chill cold winter'),
('w_weather_A2_28','rainfall','/ˈreɪnfɔːl/','noun','강우량','The amount of rain that falls in an area.','This month''s {rainfall} has been above average.','이달 강우량이 평균보다 높아요.','rainfall','A2','weather',3,'rainfall rain gauge measurement'),
('w_weather_A2_29','thunder cloud','/ˈθʌndər klaʊd/','noun','먹구름, 뇌운','A large dark cloud associated with thunder and lightning.','A huge {thunder cloud} is forming in the west.','서쪽에 큰 먹구름이 형성되고 있어요.','thunder cloud','A2','weather',3,'thunder cloud dark storm'),
('w_weather_A2_30','icy','/ˈaɪsi/','adjective','빙판인, 얼음처럼 차가운','Covered with ice or extremely cold.','Watch out — the pavement is {icy}.','조심하세요. 인도가 빙판이에요.','icy','A2','weather',3,'icy pavement winter slippery'),
('w_weather_A2_31','downpour','/ˈdaʊnpɔːr/','noun','폭우','A heavy fall of rain.','We were caught in a sudden {downpour}.','갑자기 쏟아지는 폭우를 맞았어요.','downpour','A2','weather',3,'downpour heavy rain street'),
('w_weather_A2_32','cloudburst','/ˈklaʊdbɜːrst/','noun','집중 호우','A sudden, very heavy shower.','A {cloudburst} flooded the underpass.','집중 호우로 지하차도가 침수됐어요.','cloudburst','A2','weather',3,'cloudburst flash flood rain'),
('w_weather_A2_33','mist','/mɪst/','noun','엷은 안개, 박무','A thin layer of cloud low over land.','The valley was covered in morning {mist}.','계곡이 아침 안개에 덮였어요.','mist','A2','weather',3,'mist morning valley soft'),
('w_weather_A2_34','sleet','/sliːt/','noun','진눈깨비','A mixture of rain and snow.','It''s not quite snow — it''s {sleet}.','완전한 눈은 아니고 진눈깨비예요.','sleet','A2','weather',3,'sleet rain snow mix winter'),
('w_weather_A2_35','hazy','/ˈheɪzi/','adjective','뿌연, 안개 낀','Covered by a thin mist or haze.','The mountains look {hazy} in the distance.','산이 멀리서 뿌옇게 보여요.','hazy','A2','weather',3,'hazy sky mountains distance mist');

-- ══════════════════════════════════════
-- WORDS — B1 (35개)
-- humidity, precipitation, visibility, heatwave, drought, blizzard, overcast, mild, chilly, tropical ...
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_weather_B1_01','humidity','/hjuːˈmɪdɪti/','noun','습도','The amount of water vapour in the air.','The {humidity} today makes it feel hotter than it is.','오늘 습도 때문에 실제보다 더 덥게 느껴져요.','humidity','B1','weather',1,'humidity sticky tropical air'),
('w_weather_B1_02','precipitation','/prɪˌsɪpɪˈteɪʃən/','noun','강수량, 강수','Water that falls from the sky as rain, snow, sleet, or hail.','Monthly {precipitation} levels have been unusually high.','월 강수량이 예년에 비해 유독 높아요.','precipitation','B1','weather',1,'precipitation rain snow measurement'),
('w_weather_B1_03','visibility','/ˌvɪzɪˈbɪlɪti/','noun','가시거리, 시정','The distance at which objects can be clearly seen.','Poor {visibility} is making driving dangerous.','낮은 가시거리로 운전이 위험해요.','visibility','B1','weather',1,'visibility fog road distance'),
('w_weather_B1_04','heatwave','/ˈhiːtweɪv/','noun','폭염','A prolonged period of abnormally hot weather.','The {heatwave} broke records across the country.','폭염이 전국적으로 기록을 깨뜨렸어요.','heatwave','B1','weather',1,'heatwave extreme heat dry summer'),
('w_weather_B1_05','drought','/draʊt/','noun','가뭄','A long period of very little or no rain.','Farmers are struggling because of the {drought}.','농부들이 가뭄 때문에 힘들어하고 있어요.','drought','B1','weather',1,'drought dry cracked earth'),
('w_weather_B1_06','blizzard','/ˈblɪzərd/','noun','눈보라','A severe snowstorm with strong, blinding winds.','Flights were cancelled due to the {blizzard}.','눈보라로 항공편이 취소됐어요.','blizzard','B1','weather',1,'blizzard snowstorm white out'),
('w_weather_B1_07','overcast','/ˌoʊvərˈkæst/','adjective','잔뜩 흐린','(Of the sky) covered with a thick layer of grey cloud.','It''s {overcast} today, so bring a jacket.','오늘 날씨가 흐리니까 재킷을 챙기세요.','overcast','B1','weather',1,'overcast grey sky heavy clouds'),
('w_weather_B1_08','mild','/maɪld/','adjective','온화한','Pleasantly warm and without extreme cold or heat.','The climate here is {mild} all year round.','이곳 기후는 연중 온화해요.','mild','B1','weather',1,'mild weather pleasant countryside'),
('w_weather_B1_09','chilly','/ˈtʃɪli/','adjective','쌀쌀한','Noticeably cold, causing discomfort.','It''s quite {chilly} in the shade.','그늘에는 꽤 쌀쌀해요.','chilly','B1','weather',1,'chilly autumn cold evening'),
('w_weather_B1_10','tropical','/ˈtrɒpɪkəl/','adjective','열대의','Relating to the tropics; very hot and humid.','Seoul summers feel almost {tropical} these days.','요즘 서울 여름은 거의 열대처럼 느껴져요.','tropical','B1','weather',1,'tropical hot humid lush green'),
('w_weather_B1_11','pressure','/ˈpreʃər/','noun','기압','The force exerted by the weight of air.','Low {pressure} systems often bring bad weather.','저기압 시스템은 주로 나쁜 날씨를 가져와요.','pressure','B1','weather',2,'pressure barometer atmosphere'),
('w_weather_B1_12','front','/frʌnt/','noun','전선 (기상)','A boundary between two different air masses.','A cold {front} is moving in from the north.','북쪽에서 한랭 전선이 이동하고 있어요.','front','B1','weather',2,'weather front map cold warm'),
('w_weather_B1_13','gale','/ɡeɪl/','noun','강풍, 돌풍','A very strong wind.','The {gale} blew tiles off the roof.','강풍이 지붕의 기와를 날려버렸어요.','gale','B1','weather',2,'gale strong wind damage'),
('w_weather_B1_14','thunder storm','/ˈθʌndər stɔːrm/','noun','뇌우','A storm with thunder and lightning.','The {thunder storm} last night was terrifying.','어젯밤 뇌우는 정말 무서웠어요.','thunderstorm','B1','weather',2,'thunderstorm lightning dark sky'),
('w_weather_B1_15','scorching','/ˈskɔːrtʃɪŋ/','adjective','작열하는, 몹시 더운','Very hot; burning hot.','The {scorching} sun drove everyone indoors.','작열하는 태양에 모두 실내로 들어갔어요.','scorching','B1','weather',2,'scorching sun hot desert'),
('w_weather_B1_16','breezy','/ˈbriːzi/','adjective','바람이 솔솔 부는','Pleasantly windy.','It''s sunny and {breezy} — perfect for a picnic.','햇살이 나고 바람이 솔솔 불어요. 소풍하기 딱 좋아요.','breezy','B1','weather',2,'breezy wind sunny outdoor'),
('w_weather_B1_17','humid subtropical','/hjuːˈmɪd ˌsʌbˈtrɒpɪkəl/','adjective phrase','고온 다습한 아열대의','Describing a climate type with hot, humid summers and mild winters.','Korea has a {humid subtropical} summer.','한국의 여름은 고온 다습한 아열대성이에요.','humid subtropical','B1','weather',3,'humid subtropical summer green'),
('w_weather_B1_18','slippery road','/ˈslɪpəri roʊd/','noun phrase','미끄러운 도로','A road surface made dangerous by rain or ice.','Slow down — there are {slippery road}s ahead.','속도를 줄이세요. 앞에 미끄러운 도로가 있어요.','slippery road','B1','weather',3,'slippery road rain ice winter'),
('w_weather_B1_19','pollen count','/ˈpɒlən kaʊnt/','noun','꽃가루 농도','A measure of the amount of pollen in the air.','The {pollen count} is very high today.','오늘 꽃가루 농도가 매우 높아요.','pollen count','B1','weather',3,'pollen flowers spring allergy'),
('w_weather_B1_20','heat index','/hiːt ˈɪndeks/','noun','체감 온도 (습도 반영)','A measure of how hot it feels when humidity is combined with temperature.','The {heat index} is 42 degrees today.','오늘 체감 온도가 42도예요.','heat index','B1','weather',3,'heat index summer humidity'),
('w_weather_B1_21','wind speed','/wɪnd spiːd/','noun','풍속','The rate at which air is moving.','The {wind speed} reached 80 km/h during the storm.','폭풍 동안 풍속이 80km/h에 달했어요.','wind speed','B1','weather',3,'wind speed meter anemometer'),
('w_weather_B1_22','barometer','/bəˈrɒmɪtər/','noun','기압계','An instrument for measuring atmospheric pressure.','The {barometer} is falling — bad weather is coming.','기압계가 내려가고 있어요. 날씨가 나빠질 거예요.','barometer','B1','weather',3,'barometer instrument pressure'),
('w_weather_B1_23','UV index','/juː viː ˈɪndeks/','noun','자외선 지수','A measure of the ultraviolet radiation reaching Earth''s surface.','The {UV index} is very high — use sunscreen.','자외선 지수가 매우 높아요. 선크림을 바르세요.','UV index','B1','weather',3,'UV index sun protection summer'),
('w_weather_B1_24','flood warning','/flʌd ˈwɔːrnɪŋ/','noun','홍수 경보','An official alert that flooding is expected.','The government issued a {flood warning} for the region.','정부가 해당 지역에 홍수 경보를 발령했어요.','flood warning','B1','weather',3,'flood warning alert rain'),
('w_weather_B1_25','air quality','/eər ˈkwɒlɪti/','noun','공기질','The degree to which the air is clean or polluted.','The {air quality} index is poor today.','오늘 공기질 지수가 나쁘네요.','air quality','B1','weather',3,'air quality pollution sky'),
('w_weather_B1_26','smog','/smɒɡ/','noun','스모그','A mixture of smoke and fog causing poor air quality.','The city was covered in thick {smog}.','도시 전체가 짙은 스모그에 덮였어요.','smog','B1','weather',3,'smog pollution city haze'),
('w_weather_B1_27','dew point','/djuː pɔɪnt/','noun','이슬점','The temperature at which air becomes saturated with moisture.','When the {dew point} is high, the air feels sticky.','이슬점이 높으면 공기가 끈적하게 느껴져요.','dew point','B1','weather',3,'dew point morning grass droplet'),
('w_weather_B1_28','wind direction','/wɪnd dɪˈrekʃən/','noun','풍향','The direction from which the wind is blowing.','The {wind direction} has shifted to the north.','풍향이 북쪽으로 바뀌었어요.','wind direction','B1','weather',3,'wind direction compass vane'),
('w_weather_B1_29','severe weather','/sɪˈvɪər ˈweðər/','noun phrase','악천후','Dangerous or extreme weather conditions.','Schools closed due to {severe weather}.','악천후로 학교들이 문을 닫았어요.','severe weather','B1','weather',3,'severe weather alert storm damage'),
('w_weather_B1_30','shelter','/ˈʃeltər/','noun','피난처, 대피소','A place giving protection from bad weather.','Everyone ran to {shelter} when the storm hit.','폭풍이 오자 모두 대피소로 달려갔어요.','shelter','B1','weather',3,'shelter protection storm rain'),
('w_weather_B1_31','frost warning','/frɒst ˈwɔːrnɪŋ/','noun','서리 주의보','An advisory that frost may form overnight.','Farmers covered their crops after the {frost warning}.','서리 주의보 후 농부들이 작물을 덮었어요.','frost warning','B1','weather',3,'frost warning cold night crops'),
('w_weather_B1_32','advisory','/ədˈvaɪzəri/','noun','기상 주의보','An official warning about potential weather hazards.','A travel {advisory} was issued for the mountain roads.','산악 도로에 대한 여행 주의보가 발령됐어요.','advisory','B1','weather',3,'advisory warning weather official'),
('w_weather_B1_33','trough','/trɒf/','noun','기압골','An elongated region of low atmospheric pressure.','A weather {trough} is bringing rain to the west.','기압골이 서쪽 지역에 비를 가져오고 있어요.','trough','B1','weather',3,'trough pressure weather map'),
('w_weather_B1_34','ridge','/rɪdʒ/','noun','고기압 마루, 능선','An elongated region of high atmospheric pressure.','A high pressure {ridge} will keep the weather fine.','고기압 마루가 날씨를 좋게 유지해줄 거예요.','ridge','B1','weather',3,'ridge high pressure map clear'),
('w_weather_B1_35','seasonal','/ˈsiːzənəl/','adjective','계절적인, 계절에 따른','Related to or varying with the seasons.','The {seasonal} rains usually begin in June.','계절성 우기는 보통 6월에 시작해요.','seasonal','B1','weather',3,'seasonal rain monsoon cycle');

-- ══════════════════════════════════════
-- WORDS — B2 (35개)
-- meteorology, climate, atmospheric, barometric, cyclone, monsoon, arid, subtropical, gradient, phenomenon ...
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_weather_B2_01','meteorology','/ˌmiːtiəˈrɒlədʒi/','noun','기상학','The scientific study of the atmosphere and weather.','She studied {meteorology} at university.','그녀는 대학에서 기상학을 공부했어요.','meteorology','B2','weather',1,'meteorology science atmosphere'),
('w_weather_B2_02','atmospheric','/ˌætməsˈferɪk/','adjective','대기의','Relating to the atmosphere of the Earth.','{Atmospheric} pressure affects how we feel.','대기압은 우리의 기분에 영향을 미쳐요.','atmospheric','B2','weather',1,'atmospheric pressure sky science'),
('w_weather_B2_03','cyclone','/ˈsaɪkloʊn/','noun','사이클론, 열대 저기압','A system of winds rotating inward to an area of low pressure.','The {cyclone} caused widespread flooding.','사이클론이 광범위한 홍수를 일으켰어요.','cyclone','B2','weather',1,'cyclone storm tropical spinning'),
('w_weather_B2_04','monsoon','/ˌmɒnˈsuːn/','noun','몬순, 우기','A seasonal wind bringing heavy rain to South and Southeast Asia.','The {monsoon} season in India lasts from June to September.','인도의 몬순 시즌은 6월부터 9월까지예요.','monsoon','B2','weather',1,'monsoon rain India tropical'),
('w_weather_B2_05','arid','/ˈærɪd/','adjective','건조한, 불모의','Having very little or no rain; very dry.','Parts of central Australia are extremely {arid}.','호주 중부 일부는 매우 건조해요.','arid','B2','weather',1,'arid desert dry cracked'),
('w_weather_B2_06','subtropical','/ˌsʌbˈtrɒpɪkəl/','adjective','아열대의','Relating to regions adjacent to the tropics.','The island has a {subtropical} climate.','그 섬은 아열대 기후예요.','subtropical','B2','weather',1,'subtropical warm humid island'),
('w_weather_B2_07','barometric','/ˌbærəˈmetrɪk/','adjective','기압의','Relating to barometric (atmospheric) pressure.','A drop in {barometric} pressure usually means rain is coming.','기압이 떨어지면 보통 비가 올 신호예요.','barometric','B2','weather',1,'barometric pressure instrument science'),
('w_weather_B2_08','gradient','/ˈɡreɪdiənt/','noun','기압 경도','A difference in atmospheric pressure over distance.','A steep pressure {gradient} produces stronger winds.','가파른 기압 경도는 더 강한 바람을 만들어요.','gradient','B2','weather',2,'gradient pressure wind map'),
('w_weather_B2_09','phenomenon','/fəˈnɒmɪnən/','noun','현상','An observable event or occurrence in the natural world.','The aurora is a fascinating weather {phenomenon}.','오로라는 매혹적인 기상 현상이에요.','phenomenon','B2','weather',2,'phenomenon aurora natural event'),
('w_weather_B2_10','climate','/ˈklaɪmɪt/','noun','기후','The long-term pattern of weather in a particular area.','The {climate} of the Mediterranean is warm and dry.','지중해의 기후는 따뜻하고 건조해요.','climate','B2','weather',2,'climate map zone Mediterranean'),
('w_weather_B2_11','precipitation pattern','/prɪˌsɪpɪˈteɪʃən ˈpætərn/','noun','강수 패턴','The regular distribution of rainfall across time and space.','Climate change is altering {precipitation pattern}s worldwide.','기후 변화가 전 세계 강수 패턴을 바꾸고 있어요.','precipitation patterns','B2','weather',2,'precipitation pattern rainfall map'),
('w_weather_B2_12','high pressure system','/haɪ ˈpreʃər ˈsɪstəm/','noun','고기압','An area of atmospheric pressure higher than its surroundings, typically bringing fine weather.','A {high pressure system} is keeping the skies clear.','고기압이 하늘을 맑게 유지하고 있어요.','high pressure system','B2','weather',2,'high pressure system clear sky map'),
('w_weather_B2_13','low pressure system','/loʊ ˈpreʃər ˈsɪstəm/','noun','저기압','An area of atmospheric pressure lower than its surroundings, often bringing clouds and rain.','The {low pressure system} brought three days of rain.','저기압이 3일 동안 비를 가져왔어요.','low pressure system','B2','weather',2,'low pressure system clouds rain map'),
('w_weather_B2_14','typhoon','/taɪˈfuːn/','noun','태풍','A tropical cyclone occurring in the western Pacific Ocean.','The {typhoon} made landfall on Friday evening.','태풍이 금요일 저녁에 상륙했어요.','typhoon','B2','weather',2,'typhoon storm Pacific coast'),
('w_weather_B2_15','intertropical convergence zone','/ˌɪntərˌtrɒpɪkəl kənˈvɜːrdʒəns zoʊn/','noun','열대 수렴대','A belt near the equator where northeast and southeast trade winds meet.','The {intertropical convergence zone} shifts seasonally.','열대 수렴대는 계절에 따라 이동해요.','ITCZ','B2','weather',3,'ITCZ equator tropical clouds'),
('w_weather_B2_16','convection','/kənˈvekʃən/','noun','대류','The transfer of heat through the movement of fluids or gases.','Afternoon thunderstorms are caused by {convection}.','오후 뇌우는 대류 현상으로 발생해요.','convection','B2','weather',2,'convection heat rising air'),
('w_weather_B2_17','jet stream','/dʒet striːm/','noun','제트 기류','A fast-flowing, narrow air current in the upper atmosphere.','The {jet stream} guides storm tracks across continents.','제트 기류가 대륙을 가로지르는 폭풍 경로를 안내해요.','jet stream','B2','weather',2,'jet stream atmosphere map wind'),
('w_weather_B2_18','trade winds','/treɪd wɪndz/','noun','무역풍','Steady winds blowing toward the equator from the northeast or southeast.','Sailors relied on the {trade winds} for ocean crossings.','선원들은 대양 횡단에 무역풍을 이용했어요.','trade winds','B2','weather',2,'trade winds map ocean sailing'),
('w_weather_B2_19','humidity index','/hjuːˈmɪdɪti ˈɪndeks/','noun','습도 지수','A combined measure of temperature and humidity.','The {humidity index} today feels oppressive.','오늘 습도 지수가 매우 불쾌하게 느껴져요.','humidity index','B2','weather',3,'humidity index summer measurement'),
('w_weather_B2_20','polar vortex','/ˈpoʊlər ˈvɔːrteks/','noun','극 소용돌이','A large area of low pressure and cold air surrounding the Earth''s poles.','The {polar vortex} brought extreme cold to the Midwest.','극 소용돌이가 중서부에 극심한 추위를 가져왔어요.','polar vortex','B2','weather',2,'polar vortex cold winter Arctic'),
('w_weather_B2_21','heat dome','/hiːt doʊm/','noun','열돔','A region of high atmospheric pressure that traps hot air below.','The {heat dome} pushed temperatures above 40°C.','열돔이 기온을 40도 이상으로 끌어올렸어요.','heat dome','B2','weather',2,'heat dome high pressure extreme heat'),
('w_weather_B2_22','wind shear','/wɪnd ʃɪər/','noun','윈드 시어, 바람 전단','A variation in wind speed or direction over a short distance.','{Wind shear} can be dangerous for aircraft on approach.','바람 전단은 착륙 중인 항공기에 위험할 수 있어요.','wind shear','B2','weather',3,'wind shear aviation danger'),
('w_weather_B2_23','evapotranspiration','/ɪˌvæpəʊˌtrænsˌpɪˈreɪʃən/','noun','증발산','The combined process of evaporation from soil and transpiration from plants.','High {evapotranspiration} dries out the soil quickly.','높은 증발산은 토양을 빠르게 건조시켜요.','evapotranspiration','B2','weather',3,'evapotranspiration plants soil dry'),
('w_weather_B2_24','air mass','/eər mæs/','noun','기단','A large body of air with uniform temperature and humidity.','A cold {air mass} is moving in from Siberia.','시베리아에서 차가운 기단이 이동하고 있어요.','air mass','B2','weather',2,'air mass cold warm map'),
('w_weather_B2_25','squall','/skwɔːl/','noun','스콜, 돌발성 강풍','A sudden, violent gust of wind often with rain or snow.','A {squall} swept across the harbour.','항구를 가로질러 스콜이 몰아쳤어요.','squall','B2','weather',3,'squall sudden storm sea'),
('w_weather_B2_26','microclimate','/ˈmaɪkrəʊˌklaɪmɪt/','noun','미기후','The climate of a small, specific area differing from the surrounding region.','The valley has its own {microclimate} due to the hills.','그 계곡은 언덕 때문에 자체적인 미기후를 가지고 있어요.','microclimate','B2','weather',3,'microclimate valley urban local'),
('w_weather_B2_27','atmosphere','/ˈætməsfɪər/','noun','대기, 대기권','The layer of gases surrounding the Earth.','Human activity is altering the {atmosphere}.','인간 활동이 대기를 변화시키고 있어요.','atmosphere','B2','weather',2,'atmosphere Earth layers science'),
('w_weather_B2_28','temperature anomaly','/ˈtemprɪtʃər əˈnɒməli/','noun','기온 편차','A deviation of temperature from a long-term average.','Scientists recorded a 1.5°C global {temperature anomaly}.','과학자들이 전 세계적으로 1.5도의 기온 편차를 기록했어요.','temperature anomaly','B2','weather',2,'temperature anomaly global warming chart'),
('w_weather_B2_29','condensation','/ˌkɒndənˈseɪʃən/','noun','응결','The process by which water vapour becomes liquid water.','{Condensation} on windows is caused by indoor humidity.','창문의 물방울은 실내 습기로 인한 응결이에요.','condensation','B2','weather',3,'condensation water drops window'),
('w_weather_B2_30','evaporation','/ɪˌvæpəˈreɪʃən/','noun','증발','The process of liquid water turning into water vapour.','{Evaporation} from the lake cools the surrounding air.','호수에서의 증발이 주변 공기를 식혀요.','evaporation','B2','weather',3,'evaporation lake water vapour'),
('w_weather_B2_31','cloud seeding','/klaʊd ˈsiːdɪŋ/','noun','인공 강우','A weather modification technique to induce precipitation.','Dubai uses {cloud seeding} to increase rainfall.','두바이는 강수량을 늘리기 위해 인공 강우를 사용해요.','cloud seeding','B2','weather',3,'cloud seeding aircraft rain artificial'),
('w_weather_B2_32','isobar','/ˈaɪsəʊbɑːr/','noun','등압선','A line on a weather map connecting places of equal atmospheric pressure.','The closely packed {isobar}s indicate strong winds.','촘촘히 모인 등압선은 강한 바람을 나타내요.','isobars','B2','weather',3,'isobar weather map lines pressure'),
('w_weather_B2_33','isotherm','/ˈaɪsəʊθɜːrm/','noun','등온선','A line on a map connecting places of equal temperature.','The {isotherm}s show the north-south temperature gradient.','등온선은 남북 기온 경도를 보여줘요.','isotherms','B2','weather',3,'isotherm temperature map gradient'),
('w_weather_B2_34','anticyclone','/ˌæntiˈsaɪkloʊn/','noun','고기압','A system of winds that spiral outward from a high-pressure centre.','The {anticyclone} over Siberia brings dry, cold air.','시베리아의 고기압이 건조하고 차가운 공기를 가져와요.','anticyclone','B2','weather',2,'anticyclone high pressure map'),
('w_weather_B2_35','ocean current','/ˈoʊʃən ˈkʌrənt/','noun','해류','A continuous, directed movement of seawater.','{Ocean current}s redistribute heat around the globe.','해류는 지구 전체에 열을 재분배해요.','ocean currents','B2','weather',2,'ocean current map sea temperature');

-- ══════════════════════════════════════
-- WORDS — C1 (35개)
-- climatology, microclimate, inversion, stratosphere, El Niño, anomaly, deviation, temperate, oceanic, continental ...
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_weather_C1_01','climatology','/ˌklaɪməˈtɒlədʒi/','noun','기후학','The scientific study of climate.','{Climatology} provides the data needed for climate policy.','기후학은 기후 정책에 필요한 데이터를 제공해요.','climatology','C1','weather',1,'climatology science data research'),
('w_weather_C1_02','microclimate','/ˈmaɪkrəʊˌklaɪmɪt/','noun','미기후','The climate of a very small or restricted area, often different from the surrounding region.','Urban parks can create their own {microclimate}.','도시 공원은 자체적인 미기후를 만들 수 있어요.','microclimate','C1','weather',1,'microclimate urban park local climate'),
('w_weather_C1_03','inversion','/ɪnˈvɜːrʒən/','noun','기온 역전','A reversal of the normal decrease in temperature with altitude.','A temperature {inversion} trapped pollutants near the ground.','기온 역전이 오염 물질을 지표 근처에 가두었어요.','inversion','C1','weather',1,'temperature inversion smog valley'),
('w_weather_C1_04','stratosphere','/ˈstrætəsfɪər/','noun','성층권','The layer of Earth''s atmosphere above the troposphere, extending to about 50 km.','Volcanic ash can reach the {stratosphere}.','화산재가 성층권에 도달할 수 있어요.','stratosphere','C1','weather',1,'stratosphere atmosphere layers'),
('w_weather_C1_05','El Niño','/el ˈniːnjəʊ/','noun','엘니뇨','A periodic warming of ocean surface temperatures in the central and eastern Pacific.','{El Niño} causes droughts in some regions and floods in others.','엘니뇨는 일부 지역에 가뭄을, 다른 지역에 홍수를 가져와요.','El Niño','C1','weather',1,'El Nino Pacific ocean warming'),
('w_weather_C1_06','anomaly','/əˈnɒməli/','noun','편차, 이상','A deviation from the expected or typical pattern.','Scientists recorded a record temperature {anomaly} last year.','과학자들이 지난해 기록적인 기온 편차를 기록했어요.','anomaly','C1','weather',1,'anomaly temperature record data'),
('w_weather_C1_07','deviation','/ˌdiːviˈeɪʃən/','noun','편차','The amount by which a value differs from a standard or average.','A {deviation} of just 2°C can significantly impact ecosystems.','단 2도의 편차도 생태계에 상당한 영향을 미칠 수 있어요.','deviation','C1','weather',1,'deviation chart statistics climate'),
('w_weather_C1_08','temperate','/ˈtempərɪt/','adjective','온대의, 온화한','Having mild temperatures; moderate in terms of climate.','Korea lies within the {temperate} climate zone.','한국은 온대 기후대에 위치해 있어요.','temperate','C1','weather',1,'temperate zone map climate forest'),
('w_weather_C1_09','oceanic','/ˌoʊʃiˈænɪk/','adjective','해양성의','Relating to or influenced by the ocean.','The UK has an {oceanic} climate with mild, wet winters.','영국은 온화하고 습한 겨울의 해양성 기후예요.','oceanic','C1','weather',1,'oceanic climate UK coast mild'),
('w_weather_C1_10','continental','/ˌkɒntɪˈnentəl/','adjective','대륙성의','Relating to inland areas with extreme temperature variations.','Moscow has a {continental} climate with severe winters.','모스크바는 혹독한 겨울의 대륙성 기후예요.','continental','C1','weather',1,'continental climate map extreme'),
('w_weather_C1_11','thermohaline circulation','/ˌθɜːrməʊˈheɪlaɪn ˌsɜːrkjʊˈleɪʃən/','noun','열염 순환','The global ocean circulation driven by temperature and salinity differences.','The {thermohaline circulation} regulates Europe''s climate.','열염 순환은 유럽의 기후를 조절해요.','thermohaline circulation','C1','weather',2,'thermohaline circulation ocean map'),
('w_weather_C1_12','albedo','/ælˈbiːdəʊ/','noun','알베도 (반사율)','The proportion of light reflected by a surface.','Snow has a high {albedo}, reflecting most sunlight back.','눈은 알베도가 높아 햇빛 대부분을 반사해요.','albedo','C1','weather',2,'albedo snow ice reflection'),
('w_weather_C1_13','radiative forcing','/ˈreɪdiətɪv ˈfɔːrsɪŋ/','noun','복사 강제력','The change in energy flux in the atmosphere caused by natural or anthropogenic factors.','CO₂ increases {radiative forcing}, warming the planet.','CO₂ 증가는 복사 강제력을 높여 지구를 온난화해요.','radiative forcing','C1','weather',2,'radiative forcing CO2 energy atmosphere'),
('w_weather_C1_14','permafrost','/ˈpɜːrməfrɒst/','noun','영구 동토층','Ground that remains frozen for at least two consecutive years.','Melting {permafrost} releases methane into the atmosphere.','녹는 영구 동토층은 대기 중으로 메탄을 방출해요.','permafrost','C1','weather',2,'permafrost frozen ground Arctic tundra'),
('w_weather_C1_15','tipping point','/ˈtɪpɪŋ pɔɪnt/','noun','임계점','The critical threshold at which a small change causes a major system shift.','Many scientists warn we are near a climate {tipping point}.','많은 과학자들이 우리가 기후 임계점에 가까워지고 있다고 경고해요.','tipping point','C1','weather',2,'tipping point climate threshold'),
('w_weather_C1_16','aerosol','/ˈeərəsɒl/','noun','에어로졸 (대기 입자)','Tiny particles suspended in the atmosphere that affect climate and visibility.','Volcanic {aerosol}s can cool the planet temporarily.','화산 에어로졸은 일시적으로 지구를 냉각시킬 수 있어요.','aerosols','C1','weather',3,'aerosol particles atmosphere volcano'),
('w_weather_C1_17','meridional flow','/məˈrɪdiənəl fləʊ/','noun','경도 방향 흐름','Large-scale atmospheric circulation moving north or south.','Strong {meridional flow} brings Arctic air to mid-latitudes.','강한 경도 방향 흐름은 북극 공기를 중위도로 가져와요.','meridional flow','C1','weather',3,'meridional flow atmosphere circulation'),
('w_weather_C1_18','zonal flow','/ˈzoʊnəl fləʊ/','noun','대상 흐름','Large-scale atmospheric circulation moving east or west.','Dominant {zonal flow} keeps weather systems moving quickly.','지배적인 대상 흐름은 기상 시스템을 빠르게 이동시켜요.','zonal flow','C1','weather',3,'zonal flow west east wind pattern'),
('w_weather_C1_19','feedback loop','/ˈfiːdbæk luːp/','noun','피드백 루프','A process where an initial change triggers further changes that amplify or reduce the original effect.','Ice melt creates a warming {feedback loop}.','빙하 녹음은 온난화 피드백 루프를 만들어요.','feedback loop','C1','weather',2,'feedback loop ice melt climate'),
('w_weather_C1_20','stratospheric ozone','/ˌstrætəˈsferɪk ˈoʊzoʊn/','noun','성층권 오존','Ozone found in the stratosphere that shields Earth from UV radiation.','Protecting {stratospheric ozone} is critical for life on Earth.','성층권 오존을 보호하는 것은 지구 생명체에 매우 중요해요.','stratospheric ozone','C1','weather',2,'ozone layer stratosphere UV protection'),
('w_weather_C1_21','teleconnection','/ˈteliːkəˌnekʃən/','noun','원격 상관','A statistical relationship between weather patterns in distant regions.','El Niño is the most studied {teleconnection} on Earth.','엘니뇨는 지구에서 가장 많이 연구된 원격 상관이에요.','teleconnection','C1','weather',3,'teleconnection El Nino global pattern'),
('w_weather_C1_22','runoff','/ˈrʌnɒf/','noun','유출수','Water that flows off land into streams or rivers, especially after rain.','Heavy rainfall increases surface {runoff} and flood risk.','폭우는 지표 유출수와 홍수 위험을 높여요.','runoff','C1','weather',3,'runoff rain river flood surface'),
('w_weather_C1_23','glacier retreat','/ˈɡlæsiər rɪˈtriːt/','noun phrase','빙하 후퇴','The shrinking of a glacier due to melting exceeding snowfall accumulation.','Scientists are documenting {glacier retreat} worldwide.','과학자들이 전 세계 빙하 후퇴를 기록하고 있어요.','glacier retreat','C1','weather',2,'glacier retreat melting ice mountain'),
('w_weather_C1_24','sea level rise','/siː ˈlevəl raɪz/','noun phrase','해수면 상승','The increase in the average level of the world''s oceans.','{Sea level rise} threatens low-lying coastal cities.','해수면 상승은 저지대 해안 도시들을 위협해요.','sea level rise','C1','weather',2,'sea level rise coastal flood city'),
('w_weather_C1_25','carbon cycle','/ˈkɑːrbən ˈsaɪkəl/','noun','탄소 순환','The biogeochemical cycle by which carbon is exchanged among Earth''s spheres.','Forests play a key role in the {carbon cycle}.','숲은 탄소 순환에서 핵심적인 역할을 해요.','carbon cycle','C1','weather',2,'carbon cycle forest atmosphere CO2'),
('w_weather_C1_26','greenhouse effect','/ˈɡriːnhaʊs ɪˈfekt/','noun','온실 효과','The process by which greenhouse gases trap heat in the atmosphere.','The natural {greenhouse effect} makes Earth habitable.','자연적인 온실 효과는 지구를 살기 좋게 만들어요.','greenhouse effect','C1','weather',2,'greenhouse effect atmosphere heat trap'),
('w_weather_C1_27','ENSO','/ˈensoʊ/','noun','엔소 (엘니뇨 남방진동)','El Niño-Southern Oscillation; a recurring climate pattern across the Pacific.','Scientists monitor {ENSO} to predict seasonal weather.','과학자들은 계절 날씨 예측을 위해 엔소를 모니터링해요.','ENSO','C1','weather',3,'ENSO El Nino La Nina Pacific'),
('w_weather_C1_28','La Niña','/lɑː ˈniːnjə/','noun','라니냐','The cool phase of ENSO, causing cooler-than-average ocean temperatures in the Pacific.','{La Niña} often brings drought to South America.','라니냐는 종종 남미에 가뭄을 가져와요.','La Niña','C1','weather',2,'La Nina Pacific ocean cooling map'),
('w_weather_C1_29','storm surge','/stɔːrm sɜːrdʒ/','noun','폭풍 해일','An abnormal rise in sea level caused by a storm.','The {storm surge} inundated coastal communities.','폭풍 해일이 해안 마을을 침수시켰어요.','storm surge','C1','weather',2,'storm surge coastal flood hurricane'),
('w_weather_C1_30','deep convection','/diːp kənˈvekʃən/','noun','심층 대류','Vigorous upward movement of air extending to great heights, driving intense storms.','{Deep convection} in the tropics generates most of the world''s rainfall.','열대 지역의 심층 대류가 전 세계 강수량의 대부분을 만들어요.','deep convection','C1','weather',3,'deep convection tropical clouds thunderstorm'),
('w_weather_C1_31','geostrophic wind','/ˌdʒiːəˈstrɒfɪk wɪnd/','noun','지균풍','A wind blowing parallel to isobars, resulting from balance between pressure gradient and Coriolis forces.','The {geostrophic wind} approximates winds above the boundary layer.','지균풍은 경계층 위쪽의 바람을 근사치로 나타내요.','geostrophic wind','C1','weather',3,'geostrophic wind map isobar'),
('w_weather_C1_32','coriolis effect','/ˌkɒriˈoʊlɪs ɪˈfekt/','noun','코리올리 효과','The deflection of moving air or water due to Earth''s rotation.','The {Coriolis effect} causes storms to spin.','코리올리 효과는 폭풍을 회전하게 만들어요.','Coriolis effect','C1','weather',2,'Coriolis effect rotation earth wind'),
('w_weather_C1_33','orographic lift','/ˌɒrəˈɡræfɪk lɪft/','noun','지형성 상승','The forced ascent of air over a mountain range, often causing precipitation.','{Orographic lift} makes the windward side of mountains much wetter.','지형성 상승이 산의 바람받이 쪽을 훨씬 습하게 만들어요.','orographic lift','C1','weather',3,'orographic lift mountain rain windward'),
('w_weather_C1_34','atmospheric river','/ˌætməsˈferɪk ˈrɪvər/','noun','대기천','A narrow band of concentrated moisture transport in the atmosphere.','An {atmospheric river} caused catastrophic flooding.','대기천이 대규모 홍수를 일으켰어요.','atmospheric river','C1','weather',2,'atmospheric river moisture flood map'),
('w_weather_C1_35','climate sensitivity','/ˈklaɪmɪt senˈsɪtɪvɪti/','noun','기후 민감도','The expected rise in global temperature caused by a doubling of atmospheric CO₂.','Estimating {climate sensitivity} is a key challenge in research.','기후 민감도 추정은 연구의 핵심 과제예요.','climate sensitivity','C1','weather',2,'climate sensitivity CO2 temperature rise');

-- ══════════════════════════════════════
-- WORDS — C2 (35개)
-- paleoclimatology, anthropogenic, biogeochemical, teleconnection, thermohaline, albedo,
-- radiative forcing, permafrost, dendroclimatology, proxy ...
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_weather_C2_01','paleoclimatology','/ˌpeɪliəʊˌklaɪməˈtɒlədʒi/','noun','고기후학','The study of past climates through geological, biological, and chemical evidence.','{Paleoclimatology} reveals how Earth''s climate has changed over millennia.','고기후학은 수천 년에 걸친 지구 기후 변화를 밝혀줘요.','paleoclimatology','C2','weather',1,'paleoclimatology ice core fossil climate'),
('w_weather_C2_02','anthropogenic','/ˌænθrəpəˈdʒenɪk/','adjective','인위적인, 인간 활동에 의한','Originating in human activity.','Most of today''s climate change is {anthropogenic}.','오늘날 기후 변화의 대부분은 인위적인 것이에요.','anthropogenic','C2','weather',1,'anthropogenic pollution industry CO2'),
('w_weather_C2_03','biogeochemical','/ˌbaɪəʊˌdʒiːəʊˈkemɪkəl/','adjective','생물 지구 화학적','Relating to the chemical, biological, and geological cycles of the Earth.','{Biogeochemical} cycles control how nutrients move through ecosystems.','생물 지구 화학적 순환은 생태계의 영양소 이동을 조절해요.','biogeochemical','C2','weather',1,'biogeochemical cycle carbon nitrogen'),
('w_weather_C2_04','teleconnection','/ˈteliːkəˌnekʃən/','noun','원격 상관','A correlation between weather or climate anomalies separated by large distances.','{Teleconnection}s help forecast droughts months in advance.','원격 상관은 몇 달 전에 가뭄을 예측하는 데 도움을 줘요.','teleconnections','C2','weather',1,'teleconnection global climate pattern map'),
('w_weather_C2_05','thermohaline','/ˌθɜːrməʊˈheɪlaɪn/','adjective','열염 (온도와 염도에 의한)','Relating to ocean circulation driven by temperature and salinity differences.','The {thermohaline} conveyor belt could weaken with freshwater influx.','담수 유입으로 열염 컨베이어 벨트가 약해질 수 있어요.','thermohaline','C2','weather',1,'thermohaline ocean circulation belt'),
('w_weather_C2_06','albedo','/ælˈbiːdəʊ/','noun','알베도','The fraction of solar energy reflected from the Earth back into space.','Reduced {albedo} from melting ice accelerates warming.','빙하 녹음으로 인한 알베도 감소가 온난화를 가속해요.','albedo','C2','weather',1,'albedo reflection ice surface'),
('w_weather_C2_07','radiative forcing','/ˈreɪdiətɪv ˈfɔːrsɪŋ/','noun','복사 강제력','The imbalance in Earth''s energy budget caused by changes in greenhouse gas concentrations.','Increased {radiative forcing} is the primary driver of climate change.','증가된 복사 강제력이 기후 변화의 주요 원인이에요.','radiative forcing','C2','weather',1,'radiative forcing greenhouse energy'),
('w_weather_C2_08','permafrost','/ˈpɜːrməfrɒst/','noun','영구 동토층','Ground in polar regions that remains continuously frozen for two or more years.','The thawing of {permafrost} releases ancient carbon stores.','영구 동토층의 해빙은 오래된 탄소 저장량을 방출해요.','permafrost','C2','weather',1,'permafrost thaw Arctic tundra methane'),
('w_weather_C2_09','dendroclimatology','/ˌdendrəʊˌklaɪməˈtɒlədʒi/','noun','수목 연륜 기후학','The study of past climates by analysing the annual growth rings of trees.','{Dendroclimatology} can reconstruct 500 years of climate data.','수목 연륜 기후학은 500년간의 기후 데이터를 재구성할 수 있어요.','dendroclimatology','C2','weather',1,'dendroclimatology tree rings climate'),
('w_weather_C2_10','proxy','/ˈprɒksi/','noun','대리 지표','Indirect evidence used to reconstruct past climate conditions.','Ice cores are the most valuable climate {proxy}.','빙하 코어는 가장 귀중한 기후 대리 지표예요.','proxy','C2','weather',1,'proxy ice core climate data'),
('w_weather_C2_11','insolation','/ˌɪnsəˈleɪʃən/','noun','일사량','The amount of solar radiation reaching a surface.','Seasonal changes in {insolation} drive the annual temperature cycle.','일사량의 계절적 변화가 연간 기온 순환을 이끌어요.','insolation','C2','weather',2,'insolation solar radiation surface earth'),
('w_weather_C2_12','Milankovitch cycles','/mɪˈlæŋkəvɪtʃ ˈsaɪkəlz/','noun','밀란코비치 주기','Long-term variations in Earth''s orbital parameters that affect climate.','{Milankovitch cycles} explain the timing of ice ages.','밀란코비치 주기는 빙하기 시기를 설명해요.','Milankovitch cycles','C2','weather',2,'Milankovitch cycles orbit earth ice age'),
('w_weather_C2_13','cryosphere','/ˈkraɪəsfɪər/','noun','빙권','The frozen water parts of Earth, including glaciers, ice sheets, and sea ice.','The {cryosphere} is shrinking at an unprecedented rate.','빙권이 전례 없는 속도로 축소되고 있어요.','cryosphere','C2','weather',2,'cryosphere ice glacier Arctic Antarctic'),
('w_weather_C2_14','hydrological cycle','/ˌhaɪdrəˈlɒdʒɪkəl ˈsaɪkəl/','noun','물 순환 (수문 순환)','The continuous movement of water through Earth''s systems.','Climate change is intensifying the {hydrological cycle}.','기후 변화가 물 순환을 강화하고 있어요.','hydrological cycle','C2','weather',2,'hydrological cycle water rain evaporation'),
('w_weather_C2_15','stratospheric warming','/ˌstrætəˈsferɪk ˈwɔːrmɪŋ/','noun','성층권 온난화','A sudden increase in stratospheric temperature that can disrupt polar vortex.','Sudden {stratospheric warming} events weaken the polar vortex.','갑작스러운 성층권 온난화 사건이 극 소용돌이를 약화시켜요.','stratospheric warming','C2','weather',3,'stratospheric warming polar vortex'),
('w_weather_C2_16','carbon sequestration','/ˈkɑːrbən ˌsiːkwɪˈstreɪʃən/','noun','탄소 격리','The long-term storage of carbon dioxide to reduce greenhouse gas concentrations.','Reforestation is a key strategy for {carbon sequestration}.','산림 복원은 탄소 격리의 핵심 전략이에요.','carbon sequestration','C2','weather',2,'carbon sequestration forest trees soil'),
('w_weather_C2_17','cloud albedo effect','/klaʊd ælˈbiːdəʊ ɪˈfekt/','noun','구름 알베도 효과','The cooling influence of clouds reflecting solar radiation back into space.','The {cloud albedo effect} is a major source of uncertainty in climate models.','구름 알베도 효과는 기후 모델의 주요 불확실성 원인이에요.','cloud albedo effect','C2','weather',3,'cloud albedo reflection climate model'),
('w_weather_C2_18','isotope analysis','/ˈaɪsətəʊp əˈnæləsɪs/','noun','동위원소 분석','The use of stable isotope ratios in ice or sediment cores to reconstruct past climates.','{Isotope analysis} revealed a sudden cooling 12,000 years ago.','동위원소 분석으로 12,000년 전의 갑작스러운 냉각이 밝혀졌어요.','isotope analysis','C2','weather',3,'isotope analysis ice core paleoclimate'),
('w_weather_C2_19','biogenic volatile organic compound','/baɪəˈdʒenɪk vəˈlætaɪl ɔːrˈɡænɪk ˈkɒmpaʊnd/','noun','생물 기원 휘발성 유기화합물','Organic chemicals emitted by vegetation that affect air chemistry and cloud formation.','Forests emit {biogenic volatile organic compound}s that influence regional climate.','숲은 지역 기후에 영향을 미치는 생물 기원 휘발성 유기화합물을 방출해요.','BVOCs','C2','weather',3,'BVOC forest emission aerosol'),
('w_weather_C2_20','abrupt climate change','/əˈbrʌpt ˈklaɪmɪt tʃeɪndʒ/','noun','급격한 기후 변화','A large-scale change in the climate system that takes place over a few decades or less.','Evidence shows {abrupt climate change} has occurred many times in Earth''s history.','지구 역사에서 급격한 기후 변화가 여러 번 발생했다는 증거가 있어요.','abrupt climate change','C2','weather',2,'abrupt climate change sudden shift data'),
('w_weather_C2_21','solar irradiance','/ˈsoʊlər ɪˈreɪdiəns/','noun','태양 복사량','The total power of solar energy received per unit area.','Variations in {solar irradiance} are a natural climate driver.','태양 복사량의 변화는 자연적인 기후 요인이에요.','solar irradiance','C2','weather',2,'solar irradiance sun energy measurement'),
('w_weather_C2_22','feedback mechanism','/ˈfiːdbæk ˈmekənɪzəm/','noun','피드백 메커니즘','A process in which the output of a system influences that system''s future behaviour.','Water vapour is a powerful positive {feedback mechanism} in the climate system.','수증기는 기후 시스템에서 강력한 양의 피드백 메커니즘이에요.','feedback mechanism','C2','weather',2,'feedback mechanism climate water vapour'),
('w_weather_C2_23','global mean surface temperature','/ˈɡloʊbəl miːn ˈsɜːrfɪs ˈtemprɪtʃər/','noun','전 지구 평균 지표 기온','The globally averaged temperature of Earth''s surface.','The {global mean surface temperature} has risen by 1.2°C since pre-industrial times.','전 지구 평균 지표 기온은 산업화 이전보다 1.2도 상승했어요.','GMST','C2','weather',2,'global mean temperature chart rise'),
('w_weather_C2_24','forcing agent','/ˈfɔːrsɪŋ ˈeɪdʒənt/','noun','복사 강제 인자','A factor that causes a change in Earth''s energy balance.','Methane is a potent {forcing agent} in climate change.','메탄은 기후 변화에서 강력한 복사 강제 인자예요.','forcing agent','C2','weather',3,'forcing agent methane CO2 climate'),
('w_weather_C2_25','sea ice extent','/siː aɪs ɪkˈstent/','noun','해빙 면적','The total area of the ocean surface covered by sea ice.','Arctic {sea ice extent} is declining faster than predicted.','북극 해빙 면적이 예측보다 빠르게 줄어들고 있어요.','sea ice extent','C2','weather',2,'sea ice Arctic extent satellite'),
('w_weather_C2_26','ice age','/aɪs eɪdʒ/','noun','빙하기','A period of long-term reduction in global temperature resulting in glaciation.','We are currently in an interglacial period of the current {ice age}.','우리는 현재 빙하기의 간빙기에 살고 있어요.','ice age','C2','weather',2,'ice age glacial period Earth'),
('w_weather_C2_27','water vapour feedback','/ˈwɔːtər ˈveɪpər ˈfiːdbæk/','noun','수증기 피드백','The amplification of warming caused by increased water vapour in the atmosphere.','{Water vapour feedback} more than doubles initial warming from CO₂.','수증기 피드백은 CO₂로 인한 초기 온난화를 두 배 이상으로 증폭시켜요.','water vapour feedback','C2','weather',3,'water vapour feedback climate warming'),
('w_weather_C2_28','palaeotemperature','/ˌpeɪliəʊˈtemprɪtʃər/','noun','고대 기온','A reconstructed temperature of a past period inferred from proxy data.','{Palaeotemperature} records from ice cores show rapid swings.','빙하 코어의 고대 기온 기록은 급격한 변동을 보여줘요.','palaeotemperature','C2','weather',3,'palaeotemperature ice core proxy data'),
('w_weather_C2_29','heterogeneous nucleation','/ˌhetərəˈdʒiːniəs ˌnjuːkliˈeɪʃən/','noun','불균일 핵 생성','The formation of ice crystals or water droplets on aerosol particles.','{Heterogeneous nucleation} is the main process forming cloud droplets.','불균일 핵 생성이 구름 물방울 형성의 주요 과정이에요.','heterogeneous nucleation','C2','weather',3,'nucleation cloud droplets aerosol'),
('w_weather_C2_30','integrated assessment model','/ˈɪntɪɡreɪtɪd əˈsesmənt ˈmɒdəl/','noun','통합 평가 모델','A computer model combining climate science and socioeconomic analysis.','{Integrated assessment model}s project warming under different emission pathways.','통합 평가 모델들은 다양한 배출 경로에서의 온난화를 전망해요.','IAM','C2','weather',3,'integrated assessment model climate projection'),
('w_weather_C2_31','carbon budget','/ˈkɑːrbən ˈbʌdʒɪt/','noun','탄소 예산','The maximum amount of CO₂ that can be emitted to stay within a temperature limit.','The world has used most of its 1.5°C {carbon budget}.','세계는 1.5도 탄소 예산의 대부분을 이미 사용했어요.','carbon budget','C2','weather',2,'carbon budget CO2 budget emissions'),
('w_weather_C2_32','emission pathway','/ɪˈmɪʃən ˈpɑːθweɪ/','noun','배출 경로','A trajectory describing future greenhouse gas emissions over time.','Choosing a steep {emission pathway} reduction is critical.','가파른 배출 경로 감소를 선택하는 것이 매우 중요해요.','emission pathway','C2','weather',2,'emission pathway CO2 reduction graph'),
('w_weather_C2_33','net zero','/net ˈzɪərəʊ/','noun','탄소 중립, 넷 제로','A state in which the greenhouse gases emitted are balanced by those removed from the atmosphere.','Many countries have pledged to achieve {net zero} by 2050.','많은 나라들이 2050년까지 탄소 중립 달성을 약속했어요.','net zero','C2','weather',2,'net zero carbon neutral target'),
('w_weather_C2_34','tectonic influence','/tekˈtɒnɪk ˈɪnfluəns/','noun','지각 변동의 영향','The effect of plate movement on long-term climate by reshaping landmasses and sea levels.','{Tectonic influence} shaped Earth''s climate over geological time.','지각 변동의 영향이 지질학적 시간에 걸쳐 지구 기후를 형성했어요.','tectonic influence','C2','weather',3,'tectonic plates climate geology'),
('w_weather_C2_35','deep time climate','/diːp taɪm ˈklaɪmɪt/','noun phrase','심층 시간 기후 (지질학적 기후)','Climate conditions of geological eons, studied through rock and fossil records.','Understanding {deep time climate} helps contextualise modern warming.','심층 시간 기후를 이해하면 현대 온난화를 더 잘 이해할 수 있어요.','deep time climate','C2','weather',3,'deep time climate fossil geology record');

-- ══════════════════════════════════════
-- SENTENCES / PATTERNS — A1 (7개)
-- 상황: 날씨 묻기
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_weather_A1_01','What''s the weather like today?','오늘 날씨 어때요?','What''s the weather like','"What''s the weather like?"는 날씨를 물을 때 가장 자연스러운 원어민 표현이에요. "How is the weather?"보다 훨씬 자주 쓰여요.','날씨 묻기','A1','weather','pattern',NULL,1),
('s_weather_A1_02','Is it hot or cold outside?','밖에 덥나요, 추운가요?','hot or cold outside','"or"를 사용해 두 가지 선택지를 제시하면 상대방이 대답하기 쉬워요. 날씨를 처음 묻는 기초 표현이에요.','날씨 묻기','A1','weather','pattern',NULL,2),
('s_weather_A1_03','It''s sunny today.','오늘은 화창해요.','It''s sunny','날씨를 말할 때 "It''s + 날씨 형용사" 패턴이 가장 기본이에요. "It"은 특별한 의미 없이 날씨 문장에서 주어로 써요.','날씨 묘사','A1','weather','pattern',NULL,3),
('s_weather_A1_04','It''s raining outside.','밖에 비가 오고 있어요.','It''s raining','동작이 지금 일어나고 있을 때는 "-ing" 형태를 써요. "It rains"보다 "It''s raining"이 지금 이 순간의 날씨를 묘사해요.','날씨 묘사','A1','weather','pattern',NULL,4),
('s_weather_A1_05','Don''t forget your umbrella!','우산 가져가는 거 잊지 마세요!','Don''t forget your umbrella','"Don''t forget your ~!"는 상대방을 걱정해 챙겨주는 표현이에요. 날씨 대화에서 자연스럽게 쓸 수 있어요.','날씨 조언','A1','weather','pattern',NULL,5),
('s_weather_A1_06','What is the weather like in winter?','겨울 날씨는 어때요?','weather like in winter','계절을 붙여 물으면 특정 계절의 날씨 특징을 알 수 있어요. "in + 계절" 조합을 꼭 기억하세요.','계절 날씨 묻기','A1','weather','pattern',NULL,6),
('s_weather_A1_07','It is very cold today, isn''t it?','오늘 정말 춥죠, 그렇지 않나요?','isn''t it','문장 끝에 "isn''t it?"를 붙이면 상대방의 동의를 구하는 부가의문문이 돼요. 영국 영어에서 특히 자주 써요.','날씨 공감 구하기','A1','weather','pattern',NULL,7);

-- ══════════════════════════════════════
-- SENTENCES / PATTERNS — A2 (7개)
-- 상황: 날씨 묘사
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_weather_A2_01','The weather is really nice today, don''t you think?','오늘 날씨가 정말 좋죠, 그렇지 않나요?','don''t you think','"don''t you think?"는 상대방의 의견을 자연스럽게 구하는 표현이에요. 날씨 소재로 대화를 시작할 때 유용해요.','날씨 묘사·공감','A2','weather','pattern',NULL,1),
('s_weather_A2_02','It''s getting colder these days.','요즘 점점 추워지고 있어요.','It''s getting colder','"It''s getting + 비교급"은 날씨 변화를 표현하는 핵심 패턴이에요. "warmer", "cloudier", "wetter" 등 다양한 형용사와 함께 써요.','날씨 변화 묘사','A2','weather','pattern',NULL,2),
('s_weather_A2_03','It looks like it''s going to rain.','비가 올 것 같아요.','It looks like it''s going to','"It looks like + 주어 + be going to + 동사"는 눈에 보이는 단서를 바탕으로 날씨를 예측할 때 써요.','날씨 예측','A2','weather','pattern',NULL,3),
('s_weather_A2_04','The forecast says it will be cloudy all day.','예보에서 하루 종일 흐릴 거라고 해요.','The forecast says it will be','"The forecast says ~"는 일기 예보 내용을 전달할 때 쓰는 패턴이에요. 뉴스나 앱 정보를 공유할 때 자연스러워요.','예보 전달','A2','weather','pattern',NULL,4),
('s_weather_A2_05','It was so foggy this morning that I could barely see.','오늘 아침에 너무 안개가 끼어서 잘 보이지 않았어요.','so foggy that I could barely see','"so + 형용사 + that ~" 패턴은 결과를 강조해요. "barely"는 "거의 ~않다"는 뜻으로 부정적 상황을 강조할 때 써요.','날씨 상황 묘사','A2','weather','pattern',NULL,5),
('s_weather_A2_06','The temperature dropped suddenly overnight.','밤 사이에 기온이 갑자기 떨어졌어요.','temperature dropped suddenly overnight','"overnight"는 "밤 사이에"라는 뜻으로, 날씨가 빠르게 변한 상황을 표현할 때 자주 써요.','기온 변화 묘사','A2','weather','pattern',NULL,6),
('s_weather_A2_07','I prefer sunny weather to rainy weather.','저는 비 오는 날보다 화창한 날을 더 좋아해요.','prefer A to B','"prefer A to B"는 "B보다 A를 더 좋아한다"는 표현이에요. 날씨 취향을 말할 때 자연스럽게 쓸 수 있어요.','날씨 선호 표현','A2','weather','pattern',NULL,7);

-- ══════════════════════════════════════
-- SENTENCES / PATTERNS — B1 (7개)
-- 상황: 날씨 예보, 옷차림 조언
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_weather_B1_01','According to the forecast, there''s a high chance of thunderstorms this evening.','예보에 따르면 오늘 저녁 뇌우가 올 확률이 높아요.','According to the forecast','뉴스나 날씨 앱의 정보를 인용할 때 "According to the forecast"를 쓰면 격식 있고 정확하게 들려요.','날씨 예보 전달','B1','weather','pattern',NULL,1),
('s_weather_B1_02','You should layer up — the temperature is expected to drop significantly later.','껴입는 게 좋겠어요. 나중에 기온이 많이 떨어질 거예요.','layer up, expected to drop significantly','"layer up"는 옷을 겹쳐 입으라는 실용적 조언이에요. "expected to"는 예측을 표현하는 격식체 표현이에요.','옷차림 조언','B1','weather','pattern',NULL,2),
('s_weather_B1_03','The humidity is making it feel much hotter than it actually is.','습도 때문에 실제보다 훨씬 더 덥게 느껴져요.','humidity is making it feel','습도가 체감 온도에 영향을 주는 현상을 설명할 때 쓰는 표현이에요. "make + 목적어 + 동사원형" 구조를 활용해요.','날씨 체감 묘사','B1','weather','pattern',NULL,3),
('s_weather_B1_04','I would recommend bringing a light jacket in case the weather changes.','날씨가 변할 경우를 대비해 얇은 재킷을 챙기길 권해요.','in case the weather changes','"in case"는 "~에 대비해서"라는 뜻으로, 예방적 조언을 줄 때 꼭 쓰는 표현이에요.','옷차림 조언','B1','weather','pattern',NULL,4),
('s_weather_B1_05','The weather has been unusually warm for this time of year.','이맘때치고는 날씨가 유난히 따뜻해요.','unusually warm for this time of year','계절 평균과 비교해 현재 날씨가 특이하다고 말할 때 쓰는 표현이에요. "for this time of year"를 꼭 익혀두세요.','날씨 비교 묘사','B1','weather','pattern',NULL,5),
('s_weather_B1_06','There''s a severe weather warning in place for the northern regions.','북부 지역에 악천후 경보가 발령되어 있어요.','severe weather warning in place','"There''s a ~ warning in place"는 공식 기상 경보를 전달하는 뉴스식 표현이에요.','기상 경보 전달','B1','weather','pattern',NULL,6),
('s_weather_B1_07','With the heat index above 40 degrees, outdoor activities are not advisable.','체감 온도가 40도를 넘으니 야외 활동은 권장하지 않아요.','heat index above, not advisable','체감 온도와 건강 권고를 연결하는 실용적 표현이에요. "not advisable"은 공식 권고문에서 자주 등장해요.','폭염 안전 조언','B1','weather','pattern',NULL,7);

-- ══════════════════════════════════════
-- SENTENCES / PATTERNS — B2 (7개)
-- 상황: 기후 토론
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_weather_B2_01','Climate change is intensifying the frequency and severity of extreme weather events.','기후 변화가 극한 기상 현상의 빈도와 심각성을 증가시키고 있어요.','intensifying the frequency and severity','학술 및 뉴스 토론에서 자주 등장하는 문장 구조예요. "intensify"는 단순히 "심해지다"보다 더 정확하고 강한 표현이에요.','기후 토론','B2','weather','pattern',NULL,1),
('s_weather_B2_02','The monsoon season has become increasingly unpredictable due to shifting weather patterns.','변화하는 기상 패턴으로 인해 몬순 시즌이 점점 더 예측하기 어려워지고 있어요.','increasingly unpredictable due to','"increasingly + 형용사"는 변화의 추세를 강조해요. "due to"는 원인을 격식 있게 표현하는 방법이에요.','기후 변화 토론','B2','weather','pattern',NULL,2),
('s_weather_B2_03','There is growing scientific consensus that anthropogenic emissions are driving global warming.','인간 활동으로 인한 배출이 지구 온난화를 촉진하고 있다는 과학적 공감대가 커지고 있어요.','growing scientific consensus','영어 토론에서 "growing consensus"는 "다수의 의견이 모이고 있다"는 뉘앙스예요. "anthropogenic"은 반드시 알아야 할 기후 관련 단어예요.','기후 과학 토론','B2','weather','pattern',NULL,3),
('s_weather_B2_04','The correlation between rising CO₂ levels and global average temperatures is well established.','CO₂ 수준 상승과 전 지구 평균 기온 사이의 상관관계는 잘 확립되어 있어요.','correlation is well established','"well established"는 과학적으로 검증된 사실을 언급할 때 쓰는 표현이에요. 토론에서 근거를 제시할 때 유용해요.','기후 과학 토론','B2','weather','pattern',NULL,4),
('s_weather_B2_05','Prolonged droughts in sub-Saharan Africa are threatening food security for millions.','사하라 이남 아프리카의 장기 가뭄이 수백만 명의 식량 안보를 위협하고 있어요.','Prolonged droughts threatening food security','사회적 영향을 설명하는 데 쓰는 구조로, "threaten + 명사"는 심각한 위협을 표현해요.','기후·사회 영향 토론','B2','weather','pattern',NULL,5),
('s_weather_B2_06','Rising sea levels pose an existential threat to low-lying island nations.','해수면 상승은 저지대 섬나라들에 실존적 위협을 가하고 있어요.','pose an existential threat','"pose a threat"은 "위협을 제기하다"라는 관용 표현이에요. "existential"은 생존 자체를 위협하는 수준의 위기를 나타내요.','기후·지정학 토론','B2','weather','pattern',NULL,6),
('s_weather_B2_07','Governments must implement ambitious policies to transition to a low-carbon economy.','정부는 저탄소 경제로 전환하기 위한 야심찬 정책을 시행해야 해요.','implement ambitious policies to transition','기후 정책 토론의 핵심 표현이에요. "transition to"는 변화의 방향을 나타내며, 기후 관련 논문·보고서에서 자주 등장해요.','기후 정책 토론','B2','weather','pattern',NULL,7);

-- ══════════════════════════════════════
-- SENTENCES / PATTERNS — C1 (7개)
-- 상황: 기후 변화 논의
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_weather_C1_01','The stratospheric ozone depletion and its recovery illustrate how policy intervention can reverse environmental damage.','성층권 오존 감소와 회복은 정책적 개입이 환경 피해를 되돌릴 수 있다는 것을 보여줘요.','illustrate how policy intervention can reverse','과학적 사례를 들어 정책의 효과를 논증하는 고급 학술 표현이에요. "illustrate"는 구체적 예시로 설명하다는 의미예요.','기후 정책 논의','C1','weather','pattern',NULL,1),
('s_weather_C1_02','The amplification of Arctic warming relative to the global average — often termed Arctic amplification — is accelerating permafrost thaw.','전 지구 평균 대비 북극 온난화 증폭, 즉 북극 증폭 현상이 영구 동토층 해빙을 가속하고 있어요.','Arctic amplification accelerating permafrost thaw','대시(—)로 전문 용어를 삽입하는 학술 문체예요. "relative to"는 "~에 비해"라는 비교 표현으로 논문에서 자주 쓰여요.','기후 과학 심화 논의','C1','weather','pattern',NULL,2),
('s_weather_C1_03','Teleconnections such as El Niño have profound implications for agricultural planning across the globe.','엘니뇨와 같은 원격 상관은 전 세계 농업 계획에 심대한 영향을 미쳐요.','Teleconnections have profound implications for','"have profound implications for"는 중대한 영향을 언급하는 학술 토론의 핵심 표현이에요.','기후·농업 연계 논의','C1','weather','pattern',NULL,3),
('s_weather_C1_04','Without significant reductions in radiative forcing, crossing multiple tipping points becomes increasingly probable.','복사 강제력을 크게 줄이지 않으면 여러 임계점을 넘을 가능성이 점점 높아져요.','Without significant reductions... becomes increasingly probable','조건절로 위험 시나리오를 논증하는 학술 표현이에요. "increasingly probable"은 확률의 점진적 증가를 표현해요.','기후 위험 논의','C1','weather','pattern',NULL,4),
('s_weather_C1_05','The thermohaline circulation is sensitive to freshwater input from melting ice sheets, which could disrupt heat distribution across the North Atlantic.','열염 순환은 빙상 녹음으로 인한 담수 유입에 민감하며, 이는 북대서양 전반의 열 분배를 교란할 수 있어요.','sensitive to freshwater input, could disrupt','"sensitive to"는 특정 요인에 민감하게 반응한다는 표현이에요. 관계절(which)로 결과를 이어 설명하는 학술 문장 구조예요.','해양 기후 논의','C1','weather','pattern',NULL,5),
('s_weather_C1_06','Climate models project a poleward shift of storm tracks, altering precipitation patterns in mid-latitudes.','기후 모델은 폭풍 경로의 극 방향 이동을 예측하며, 이는 중위도 강수 패턴을 변화시킬 거예요.','project a poleward shift, altering precipitation patterns','"project"가 명사가 아닌 동사로 "예측하다"를 뜻하는 학술적 용법이에요. 분사구문(altering)으로 결과를 우아하게 연결해요.','기후 모델 논의','C1','weather','pattern',NULL,6),
('s_weather_C1_07','Robust attribution studies have established that the 2021 Pacific Northwest heat dome was virtually impossible without anthropogenic climate forcing.','강력한 귀인 연구들은 2021년 태평양 연안 북서부의 열돔이 인위적 기후 강제력 없이는 사실상 불가능했음을 규명했어요.','attribution studies, virtually impossible without anthropogenic','기후 귀인 과학(attribution science)의 핵심 표현이에요. "virtually impossible without"은 특정 원인의 결정적 역할을 논증할 때 써요.','기후 귀인 연구 토론','C1','weather','pattern',NULL,7);

-- ══════════════════════════════════════
-- SENTENCES / PATTERNS — C2 (7개)
-- 상황: 기후 변화 논의 (최고급)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_weather_C2_01','Paleoclimatological proxies, including ice cores and dendrochronological records, reveal that current warming rates are anomalous relative to any comparable interval in the Holocene.','빙하 코어와 수목 연륜 연대학 기록을 포함한 고기후학적 대리 지표들은 현재의 온난화 속도가 홀로세의 어떤 유사 구간과 비교해도 이례적임을 보여줘요.','Paleoclimatological proxies reveal anomalous relative to','최고급 학술 작문의 전형으로, 복잡한 명사구를 명사로 쌓는 방식이에요. "anomalous relative to"는 비교 기준을 제시하는 정교한 표현이에요.','고기후학 학술 토론','C2','weather','pattern',NULL,1),
('s_weather_C2_02','The biogeochemical feedbacks triggered by permafrost degradation — notably the release of previously sequestered methane and CO₂ — could render current emission reduction targets insufficient.','영구 동토층 분해로 촉발된 생물 지구 화학적 피드백, 특히 과거에 격리된 메탄과 CO₂의 방출은 현재의 배출 감소 목표를 불충분하게 만들 수 있어요.','biogeochemical feedbacks, render targets insufficient','복잡한 삽입절(—notably~—)과 "render + 목적어 + 형용사" 사역 구조를 활용한 최고급 표현이에요.','기후 과학 최고급 논의','C2','weather','pattern',NULL,2),
('s_weather_C2_03','Disentangling natural climate variability from anthropogenic forcing requires sophisticated attribution methodologies that account for the full breadth of internal climate oscillations.','자연적 기후 변동성과 인위적 강제력을 분리하려면 내부 기후 진동의 전체 범위를 고려하는 정교한 귀인 방법론이 필요해요.','Disentangling natural variability from anthropogenic forcing requires sophisticated methodologies','"Disentangle A from B"는 복잡하게 얽힌 두 요소를 분리한다는 뜻이에요. 동명사로 문장을 시작하는 학술 문체예요.','기후 귀인 방법론 토론','C2','weather','pattern',NULL,3),
('s_weather_C2_04','The convergence of thermohaline circulation weakening, sea ice albedo feedback, and permafrost carbon release represents a compound risk that integrated assessment models may systematically underestimate.','열염 순환 약화, 해빙 알베도 피드백, 영구 동토층 탄소 방출의 수렴은 통합 평가 모델이 체계적으로 과소평가할 수 있는 복합적 위험을 나타내요.','convergence of... represents a compound risk that models may underestimate','세 가지 병렬 명사구를 "The convergence of A, B, and C"로 묶어 논지를 구성하는 고급 학술 구조예요.','기후 복합 위험 논의','C2','weather','pattern',NULL,4),
('s_weather_C2_05','Dendroclimatological reconstructions corroborate instrumentally derived temperature anomalies, lending credibility to projections that current forcing trajectories will breach Holocene temperature bounds within decades.','수목 연륜 기후학적 재구성은 기기로 도출된 기온 편차를 입증하며, 현재 강제력 궤적이 수십 년 내에 홀로세 기온 한계를 돌파할 것이라는 전망에 신뢰성을 부여해요.','corroborate, lending credibility to projections that will breach','"corroborate"는 "입증하다·확증하다"는 C2급 어휘예요. "lending credibility"는 분사구문으로 결과를 연결해요.','고기후 자료 해석 토론','C2','weather','pattern',NULL,5),
('s_weather_C2_06','Radiative forcing from short-lived climate pollutants, particularly black carbon and tropospheric ozone, constitutes a non-trivial fraction of total anthropogenic warming that near-term mitigation could rapidly reverse.','단기 기후 오염 물질, 특히 블랙 카본과 대류권 오존에 의한 복사 강제력은 근기간 완화를 통해 신속하게 되돌릴 수 있는 전체 인위적 온난화의 비무시적 비율을 구성해요.','short-lived climate pollutants, non-trivial fraction, mitigation could rapidly reverse','"non-trivial"은 "무시할 수 없는·상당한"을 뜻하는 학술 부정 수식어예요. 관계절(that near-term mitigation could rapidly reverse)이 핵심 논거를 담아요.','기후 완화 정책 학술 토론','C2','weather','pattern',NULL,6),
('s_weather_C2_07','The epistemological challenge of projecting abrupt, threshold-crossing climate transitions lies in the inherently nonlinear dynamics of Earth system feedbacks, which resist reliable quantification within current modelling frameworks.','임계점을 넘는 갑작스러운 기후 전환을 예측하는 인식론적 과제는 현재 모델링 프레임워크 내에서 신뢰할 수 있는 정량화에 저항하는 지구 시스템 피드백의 본질적으로 비선형적인 역학에 있어요.','epistemological challenge, nonlinear dynamics, resist reliable quantification','"epistemological"은 지식의 한계를 논하는 철학 용어예요. 가장 높은 수준의 기후 과학 담론에서 나타나는 문장 구조와 어휘를 담고 있어요.','기후 과학 철학적 논의','C2','weather','pattern',NULL,7);
