-- EngCat — 미디어·SNS (media) 단어 + 패턴 문장
-- CEFR A1~C2 × 35단어 = 210단어
-- CEFR A1~C2 × 7패턴  =  42패턴

-- ══════════════════════════════════════
-- WORDS — A1
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_media_A1_01','phone','/foʊn/','noun','전화기, 스마트폰','A device used to make calls and access the internet.','She checks her {phone} all day.','그녀는 하루 종일 전화기를 봐요.','phone','A1','media',1,'smartphone phone screen hand scrolling'),
('w_media_A1_02','video','/ˈvɪdioʊ/','noun','동영상','A recording of moving images, often shared online.','Did you watch that funny {video}?','그 웃긴 영상 봤어요?','video','A1','media',1,'phone screen watching video social'),
('w_media_A1_03','photo','/ˈfoʊtoʊ/','noun','사진','A picture taken with a camera.','She posted a {photo} of her lunch.','그녀는 점심 사진을 올렸어요.','photo','A1','media',1,'photo camera picture taking selfie'),
('w_media_A1_04','news','/njuːz/','noun','뉴스','New information about recent events.','I read the {news} every morning.','저는 매일 아침 뉴스를 읽어요.','news','A1','media',1,'news website newspaper headline reading'),
('w_media_A1_05','watch','/wɒtʃ/','verb','시청하다, 보다','To look at something for a period of time.','Let''s {watch} a movie tonight.','오늘 밤 영화 봐요.','watch','A1','media',1,'watching tv couch movie remote control'),
('w_media_A1_06','listen','/ˈlɪsən/','verb','듣다','To pay attention to sound.','I love to {listen} to music on the way to work.','출근길에 음악 듣는 것을 좋아해요.','listen','A1','media',1,'listening music headphones earphones'),
('w_media_A1_07','screen','/skriːn/','noun','화면, 스크린','The flat surface of a phone, TV, or computer that displays images.','My {screen} cracked when I dropped my phone.','폰을 떨어뜨려서 화면이 깨졌어요.','screen','A1','media',1,'cracked phone screen broken smartphone'),
('w_media_A1_08','message','/ˈmesɪdʒ/','noun','메시지','A short piece of text sent to someone.','I got your {message} — I''ll call you back.','메시지 받았어요. 다시 전화할게요.','message','A1','media',1,'text message chat bubble smartphone notification'),
('w_media_A1_09','call','/kɔːl/','noun','전화','A phone conversation with someone.','I''ll give you a {call} later today.','오늘 나중에 전화할게요.','call','A1','media',1,'phone call talking handset conversation'),
('w_media_A1_10','app','/æp/','noun','앱, 애플리케이션','A software program on a phone or computer.','Which {app} do you use for streaming music?','음악 스트리밍할 때 어떤 앱 써요?','app','A1','media',1,'mobile app icons smartphone home screen'),
('w_media_A1_11','read','/riːd/','verb','읽다','To look at and understand written words.','I {read} the article you sent me.','보내준 기사 읽었어요.','read','A1','media',2,'reading article phone news online'),
('w_media_A1_12','picture','/ˈpɪktʃər/','noun','그림, 사진','An image, either drawn or photographed.','Can you take a {picture} of me here?','여기서 사진 찍어줄 수 있어요?','picture','A1','media',2,'taking picture selfie tourist landmark'),
('w_media_A1_13','music','/ˈmjuːzɪk/','noun','음악','Sounds arranged in a pleasant way, often with rhythm.','I always play {music} while studying.','공부할 때 항상 음악을 틀어요.','music','A1','media',1,'music playlist headphones study focus'),
('w_media_A1_14','show','/ʃoʊ/','noun','프로그램, 쇼','A TV or online program with episodes.','Have you seen that new {show} on Netflix?','넷플릭스 그 새 프로그램 봤어요?','show','A1','media',1,'netflix tv show streaming sofa watching'),
('w_media_A1_15','text','/tekst/','noun','문자, 텍스트','A written message sent from a phone.','He sent me a {text} saying he was late.','그는 늦는다는 문자를 보냈어요.','text','A1','media',2,'sms text message phone notification typing'),
('w_media_A1_16','game','/ɡeɪm/','noun','게임','An activity played for fun, often on a device.','She spends hours playing a mobile {game}.','그녀는 모바일 게임을 몇 시간씩 해요.','game','A1','media',2,'mobile game smartphone gaming playing'),
('w_media_A1_17','send','/send/','verb','보내다','To cause something to go to another person.','Can you {send} me the link?','링크 보내줄 수 있어요?','send','A1','media',1,'sending link message email sharing'),
('w_media_A1_18','like','/laɪk/','verb','좋아요를 누르다','To press a button showing approval on social media.','Don''t forget to {like} and subscribe!','좋아요 누르고 구독도 잊지 마세요!','like','A1','media',1,'like button social media thumbs up'),
('w_media_A1_19','post','/poʊst/','noun','게시물','A piece of content published online.','That {post} got thousands of likes.','그 게시물은 수천 개의 좋아요를 받았어요.','post','A1','media',1,'instagram post social media feed likes'),
('w_media_A1_20','clip','/klɪp/','noun','클립, 짧은 영상','A short piece of video.','I saw a funny {clip} this morning.','오늘 아침에 재밌는 클립 봤어요.','clip','A1','media',2,'short video clip funny social media reel'),
('w_media_A1_21','internet','/ˈɪntərnet/','noun','인터넷','A global network connecting computers and devices.','The {internet} is slow today.','오늘 인터넷이 느려요.','internet','A1','media',1,'wifi internet connection router signal'),
('w_media_A1_22','page','/peɪdʒ/','noun','페이지, 채널','A user profile or official account on social media.','Follow our official {page} for updates.','업데이트를 보려면 공식 페이지를 팔로우하세요.','page','A1','media',2,'social media page facebook instagram profile'),
('w_media_A1_23','link','/lɪŋk/','noun','링크','A clickable connection to a website or file.','She shared a {link} to the article.','그녀는 기사 링크를 공유했어요.','link','A1','media',1,'sharing link url website phone screen'),
('w_media_A1_24','play','/pleɪ/','verb','재생하다','To cause audio or video to run.','{Play} the video from the beginning.','영상을 처음부터 재생해 줘요.','play','A1','media',1,'play button video youtube watching'),
('w_media_A1_25','comment','/ˈkɒment/','noun','댓글','A remark left on a post or video.','She left a kind {comment} on my photo.','그녀가 제 사진에 친절한 댓글을 남겼어요.','comment','A1','media',2,'comment section social media reply typing'),
('w_media_A1_26','live','/lɪv/','adjective','라이브의, 실시간의','Happening or shown at the moment, not recorded.','She went {live} on Instagram.','그녀는 인스타그램에서 라이브를 켰어요.','live','A1','media',2,'instagram live streaming broadcast real time'),
('w_media_A1_27','search','/sɜːrtʃ/','verb','검색하다','To look for information online.','Just {search} it on YouTube.','유튜브에서 검색해 봐요.','search','A1','media',1,'search bar google youtube typing query'),
('w_media_A1_28','upload','/ˈʌploʊd/','verb','업로드하다','To transfer a file from a device to the internet.','He {uploaded} the photos after the trip.','그는 여행 후 사진을 업로드했어요.','upload','A1','media',2,'uploading photo cloud phone laptop progress'),
('w_media_A1_29','share','/ʃer/','verb','공유하다','To send or show content to others.','Please {share} this video with your friends.','이 영상을 친구들과 공유해 주세요.','share','A1','media',1,'share button social media repost forwarding'),
('w_media_A1_30','story','/ˈstɔːri/','noun','스토리','A short-lived post visible for 24 hours on social media.','Did you see her {story} this morning?','오늘 아침 그녀 스토리 봤어요?','story','A1','media',2,'instagram story circle phone 24 hours'),
('w_media_A1_31','channel','/ˈtʃænəl/','noun','채널','An account on a platform like YouTube that posts content.','Subscribe to my {channel} for new videos.','새 영상을 보려면 제 채널을 구독하세요.','channel','A1','media',1,'youtube channel subscribe videos creator'),
('w_media_A1_32','subscribe','/səbˈskraɪb/','verb','구독하다','To sign up to receive content from a creator.','I {subscribe} to a lot of cooking channels.','저는 요리 채널을 많이 구독해요.','subscribe','A1','media',1,'youtube subscribe button bell notification'),
('w_media_A1_33','notification','/ˌnoʊtɪfɪˈkeɪʃən/','noun','알림','A message that alerts you to an update.','Turn on {notifications} so you don''t miss anything.','아무것도 놓치지 않도록 알림을 켜 두세요.','notifications','A1','media',2,'phone notification bell alert lock screen'),
('w_media_A1_34','follow','/ˈfɒloʊ/','verb','팔로우하다','To subscribe to someone''s updates on social media.','I {follow} a lot of travel accounts.','저는 여행 계정을 많이 팔로우해요.','follow','A1','media',1,'follow button instagram social media profile'),
('w_media_A1_35','download','/ˈdaʊnloʊd/','verb','다운로드하다','To save a file from the internet to a device.','{Download} the app and sign up for free.','앱을 다운로드하고 무료로 가입하세요.','Download','A1','media',1,'downloading app phone progress bar install');

-- ══════════════════════════════════════
-- WORDS — A2
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_media_A2_01','post','/poʊst/','verb','게시하다','To publish content on social media or a website.','She {posts} photos every single day.','그녀는 매일 사진을 게시해요.','posts','A2','media',1,'posting photo instagram social media creator'),
('w_media_A2_02','comment','/ˈkɒment/','verb','댓글을 달다','To leave a written response on a post or video.','Please {comment} your thoughts below.','아래에 생각을 댓글로 남겨 주세요.','comment','A2','media',1,'commenting reply social media keyboard typing'),
('w_media_A2_03','share','/ʃer/','noun','공유, 공유 횟수','The act of reposting content or the total count of reposts.','This article got over a million {shares}.','이 기사는 백만 건 이상 공유됐어요.','shares','A2','media',1,'sharing viral article social media million'),
('w_media_A2_04','follow','/ˈfɒloʊ/','noun','팔로워','The act of following someone, or one''s follower base.','She gained ten thousand new {follows} overnight.','그녀는 하룻밤 사이 팔로워가 만 명 늘었어요.','follows','A2','media',2,'follower count instagram overnight viral'),
('w_media_A2_05','subscribe','/səbˈskraɪb/','noun (derived)','구독','The action of signing up for regular updates.','Hit the {subscribe} button and the bell icon.','구독 버튼과 벨 아이콘을 눌러 주세요.','subscribe','A2','media',1,'subscribe bell youtube button click'),
('w_media_A2_06','channel','/ˈtʃænəl/','verb','채널을 개설하다 (비유)','To direct something through a particular medium.','She {channeled} her creativity into short films.','그녀는 창의력을 단편 영화로 쏟아부었어요.','channeled','A2','media',2,'creative short film making filming shoot'),
('w_media_A2_07','upload','/ˈʌploʊd/','noun','업로드','A file or piece of content transferred to the internet.','His latest {upload} has a million views already.','그의 최신 업로드가 벌써 백만 조회수예요.','upload','A2','media',1,'youtube million views video upload creator'),
('w_media_A2_08','download','/ˈdaʊnloʊd/','noun','다운로드','A file retrieved from the internet to a local device.','The podcast {download} numbers went up this month.','이번 달 팟캐스트 다운로드 수가 올랐어요.','download','A2','media',1,'podcast download statistics graph trending'),
('w_media_A2_09','stream','/striːm/','verb','스트리밍하다','To watch or listen to media online without downloading it.','I {stream} music instead of buying albums.','앨범을 사지 않고 음악을 스트리밍해요.','stream','A2','media',1,'music streaming app spotify headphones phone'),
('w_media_A2_10','search','/sɜːrtʃ/','noun','검색','The act of looking for information online.','A quick {search} showed me exactly what I needed.','간단히 검색해 보니 필요한 게 바로 나왔어요.','search','A2','media',1,'google search bar result webpage phone'),
('w_media_A2_11','profile','/ˈproʊfaɪl/','noun','프로필','A page showing a user''s personal information on social media.','Update your {profile} picture to a recent one.','프로필 사진을 최근 사진으로 바꿔 보세요.','profile','A2','media',1,'social media profile page picture bio update'),
('w_media_A2_12','feed','/fiːd/','noun','피드','The stream of posts shown on a social media homepage.','My {feed} is full of travel photos lately.','요즘 제 피드는 여행 사진으로 가득해요.','feed','A2','media',1,'instagram feed scroll photos social media'),
('w_media_A2_13','reply','/rɪˈplaɪ/','verb','답장하다, 답글 달다','To respond to a message or comment.','Don''t forget to {reply} to your followers.','팔로워에게 답글 달는 것 잊지 마세요.','reply','A2','media',1,'reply comment message social media engaging'),
('w_media_A2_14','view','/vjuː/','noun','조회수','The number of times a video or post has been seen.','The clip reached one million {views} in a day.','그 클립이 하루 만에 조회수 백만을 달성했어요.','views','A2','media',1,'million views youtube video counter milestone'),
('w_media_A2_15','tag','/tæɡ/','verb','태그하다','To link a person or topic in a post using @.','She {tagged} me in a funny meme.','그녀가 웃긴 밈에서 저를 태그했어요.','tagged','A2','media',2,'tagging instagram mention friend photo tag'),
('w_media_A2_16','meme','/miːm/','noun','밈','A funny image or video that spreads rapidly online.','That {meme} is everywhere this week.','그 밈이 이번 주 어디서나 보여요.','meme','A2','media',2,'meme funny internet viral image caption'),
('w_media_A2_17','reel','/riːl/','noun','릴스, 짧은 영상','A short, edited video posted on social media.','Her {reel} got featured on the Explore page.','그녀의 릴스가 탐색 페이지에 소개됐어요.','reel','A2','media',1,'instagram reels short video explore feature'),
('w_media_A2_18','live','/laɪv/','noun','라이브 방송','A real-time video broadcast on social media.','He did a {live} to announce the big news.','그는 큰 소식을 발표하기 위해 라이브를 켰어요.','live','A2','media',2,'live streaming announce news social media'),
('w_media_A2_19','caption','/ˈkæpʃən/','noun','캡션, 설명글','Text written below a photo or video on social media.','She always writes such clever {captions}.','그녀는 항상 재치 있는 캡션을 써요.','captions','A2','media',2,'instagram caption witty post writing'),
('w_media_A2_20','filter','/ˈfɪltər/','noun','필터','A digital effect applied to a photo or video.','Which {filter} did you use on this photo?','이 사진에 어떤 필터 썼어요?','filter','A2','media',2,'instagram photo filter editing beautiful light'),
('w_media_A2_21','trend','/trend/','noun','트렌드, 유행','A popular topic or style at a given time.','That song is a huge {trend} right now.','그 노래가 지금 엄청난 트렌드예요.','trend','A2','media',1,'trending music tiktok popular chart viral'),
('w_media_A2_22','viral','/ˈvaɪrəl/','adjective','바이럴의, 입소문 난','Spreading rapidly and widely across social media.','The cat video went {viral} overnight.','그 고양이 영상이 하룻밤 사이 바이럴됐어요.','viral','A2','media',1,'viral video cat funny social media shares'),
('w_media_A2_23','username','/ˈjuːzərneɪm/','noun','사용자 이름','The name a user chooses for an online account.','What''s your {username}? I''ll follow you.','사용자 이름이 뭐예요? 팔로우할게요.','username','A2','media',2,'social media account username handle profile'),
('w_media_A2_24','notification','/ˌnoʊtɪfɪˈkeɪʃən/','noun','알림 설정','A system alert about new activity online.','I turned off {notifications} for that app.','그 앱의 알림을 껐어요.','notifications','A2','media',2,'turning off notifications phone settings app'),
('w_media_A2_25','block','/blɒk/','verb','차단하다','To prevent someone from seeing your content.','She had to {block} a rude commenter.','그녀는 무례한 댓글러를 차단해야 했어요.','block','A2','media',2,'blocking user social media rude comment privacy'),
('w_media_A2_26','unfollow','/ˌʌnˈfɒloʊ/','verb','언팔로우하다','To stop following someone on social media.','I had to {unfollow} that account — too many ads.','그 계정 언팔했어요. 광고가 너무 많아서요.','unfollow','A2','media',2,'unfollow button social media account ads'),
('w_media_A2_27','repost','/ˌriːˈpoʊst/','verb','리포스트하다','To share someone else''s post on your own account.','He {reposted} my photo without asking.','그는 허락도 없이 제 사진을 리포스트했어요.','reposted','A2','media',2,'reposting sharing social media content credit'),
('w_media_A2_28','hashtag','/ˈhæʃtæɡ/','noun','해시태그','A word preceded by # used to categorize posts.','Add some {hashtags} to get more reach.','더 많은 도달을 위해 해시태그를 붙여 보세요.','hashtags','A2','media',1,'hashtag instagram trending discover category'),
('w_media_A2_29','creator','/kriˈeɪtər/','noun','크리에이터','Someone who makes content for online platforms.','She became a full-time content {creator}.','그녀는 전업 콘텐츠 크리에이터가 됐어요.','creator','A2','media',1,'content creator filming vlog youtube channel'),
('w_media_A2_30','podcast','/ˈpɒdkæst/','noun','팟캐스트','An audio program available for streaming or download.','I listen to a {podcast} on my morning commute.','아침 출근길에 팟캐스트를 들어요.','podcast','A2','media',1,'podcast headphones commute listening app morning'),
('w_media_A2_31','screenshot','/ˈskriːnʃɒt/','noun','스크린샷','An image captured of what is displayed on a screen.','I took a {screenshot} of the conversation.','대화 내용 스크린샷을 찍었어요.','screenshot','A2','media',2,'screenshot phone screen capture conversation'),
('w_media_A2_32','emoji','/ɪˈmoʊdʒi/','noun','이모지','A small digital image used in messages.','Her message was just three {emojis}.','그녀의 메시지는 이모지 세 개뿐이었어요.','emojis','A2','media',2,'emoji keyboard message phone chat colorful'),
('w_media_A2_33','react','/riˈækt/','verb','반응하다 (이모지로)','To respond to a post with an emoji reaction.','Everyone {reacted} with a heart to her post.','모두가 그녀의 게시물에 하트로 반응했어요.','reacted','A2','media',2,'react heart emoji post facebook reaction'),
('w_media_A2_34','content','/ˈkɒntent/','noun','콘텐츠','Material such as text, images, or video published online.','Good {content} takes time to create.','좋은 콘텐츠를 만드는 데는 시간이 걸려요.','content','A2','media',1,'creating content camera laptop editing desk'),
('w_media_A2_35','account','/əˈkaʊnt/','noun','계정','A personal profile registered on an online platform.','Create a free {account} to get started.','시작하려면 무료 계정을 만드세요.','account','A2','media',1,'social media account signup login phone app');

-- ══════════════════════════════════════
-- WORDS — B1
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_media_B1_01','content','/ˈkɒntent/','noun','콘텐츠, 미디어 소재','Material created for online audiences, including video, text, and images.','Creating quality {content} requires planning and consistency.','양질의 콘텐츠를 만들려면 계획과 꾸준함이 필요해요.','content','B1','media',1,'content strategy planning camera filming studio'),
('w_media_B1_02','influencer','/ˈɪnfluənsər/','noun','인플루언서','A person with many social media followers who can influence buying decisions.','She partnered with a popular {influencer} for the campaign.','그녀는 캠페인을 위해 유명 인플루언서와 협력했어요.','influencer','B1','media',1,'influencer marketing brand deal social media'),
('w_media_B1_03','platform','/ˈplætfɔːrm/','noun','플랫폼','An online service or website where users create and share content.','Which {platform} do you use the most?','어떤 플랫폼을 가장 많이 사용해요?','platform','B1','media',1,'social media platforms icons logos apps'),
('w_media_B1_04','viral','/ˈvaɪrəl/','noun (derived)','바이럴','Something that spreads rapidly across the internet.','The campaign went {viral} within hours.','그 캠페인은 몇 시간 만에 바이럴됐어요.','viral','B1','media',1,'viral campaign trending social media exponential'),
('w_media_B1_05','algorithm','/ˈælɡərɪðəm/','noun','알고리즘','A set of rules a platform uses to decide what content to show users.','The {algorithm} rewards consistent posting.','알고리즘은 꾸준한 게시를 선호해요.','algorithm','B1','media',1,'algorithm recommendation feed content youtube'),
('w_media_B1_06','trending','/ˈtrendɪŋ/','adjective','트렌딩의, 유행하는','Currently popular and widely discussed on social media or news.','That topic has been {trending} all week.','그 주제가 일주일 내내 트렌딩이에요.','trending','B1','media',1,'trending topic twitter hashtag social media'),
('w_media_B1_07','hashtag','/ˈhæʃtæɡ/','noun','해시태그 (전략적 사용)','A labeling tool used to categorize content and improve discoverability.','Use relevant {hashtags} to reach a wider audience.','더 많은 사람들에게 닿으려면 관련 해시태그를 써요.','hashtags','B1','media',1,'hashtag strategy instagram reach discoverability'),
('w_media_B1_08','engagement','/ɪnˈɡeɪdʒmənt/','noun','참여도, 인게이지먼트','The level of interaction (likes, comments, shares) a post receives.','High {engagement} signals quality content to the algorithm.','높은 참여도는 알고리즘에 양질의 콘텐츠라는 신호를 줘요.','engagement','B1','media',1,'engagement rate likes comments shares analytics'),
('w_media_B1_09','broadcast','/ˈbrɔːdkæst/','verb','방송하다','To transmit a programme to many people via radio, TV, or online.','The event was {broadcast} live on all major channels.','그 행사는 모든 주요 채널에서 생방송됐어요.','broadcast','B1','media',1,'live broadcast television news anchor studio'),
('w_media_B1_10','podcast','/ˈpɒdkæst/','verb','팟캐스트로 내보내다','To produce and distribute audio episodes online.','She started {podcasting} about personal finance.','그녀는 개인 재무에 관한 팟캐스트를 시작했어요.','podcasting','B1','media',1,'podcasting microphone recording studio episode'),
('w_media_B1_11','clickbait','/ˈklɪkbeɪt/','noun','낚시성 제목','A sensational or misleading headline designed to attract clicks.','That article headline is pure {clickbait}.','그 기사 제목은 완전 낚시예요.','clickbait','B1','media',1,'clickbait headline sensational news article link'),
('w_media_B1_12','thumbnail','/ˈθʌmbneɪl/','noun','썸네일','A small preview image representing a video or post.','A good {thumbnail} can double your click-through rate.','좋은 썸네일은 클릭률을 두 배로 높일 수 있어요.','thumbnail','B1','media',1,'youtube thumbnail design video preview click'),
('w_media_B1_13','caption','/ˈkæpʃən/','verb','캡션을 달다, 설명하다','To write text describing an image or adding context.','She carefully {captioned} each photo with a story.','그녀는 각 사진에 신중하게 이야기를 담은 캡션을 달았어요.','captioned','B1','media',2,'writing caption instagram storytelling photo post'),
('w_media_B1_14','recommend','/ˌrekəˈmend/','verb','추천하다 (콘텐츠)','To suggest content worth watching or reading.','The app {recommends} videos based on your watch history.','앱은 시청 기록을 바탕으로 영상을 추천해요.','recommends','B1','media',1,'recommendation engine youtube watch history suggest'),
('w_media_B1_15','reaction','/riˈækʃən/','noun','반응 영상','A video in which someone responds to existing content.','His {reaction} video to the trailer got more views than the original.','예고편에 대한 그의 반응 영상이 원본보다 더 많은 조회수를 받았어요.','reaction','B1','media',2,'reaction video youtube trailer watching face'),
('w_media_B1_16','subscriber','/səbˈskraɪbər/','noun','구독자','A person who subscribes to a channel or newsletter.','She reached one million {subscribers} this year.','그녀는 올해 구독자 백만 명을 달성했어요.','subscribers','B1','media',1,'one million subscribers youtube creator celebration'),
('w_media_B1_17','collaboration','/kəˌlæbəˈreɪʃən/','noun','콜라보, 협업','Two or more creators working together on content.','The {collaboration} between the two YouTubers doubled both audiences.','두 유튜버의 콜라보로 양측 시청자가 두 배 늘었어요.','collaboration','B1','media',1,'collaboration youtuber collab filming together studio'),
('w_media_B1_18','monetize','/ˈmɒnɪtaɪz/','verb','수익화하다','To earn money from a channel or online content.','You need 1,000 subscribers before you can {monetize}.','수익화하려면 구독자 천 명이 필요해요.','monetize','B1','media',1,'monetize youtube earnings channel income revenue'),
('w_media_B1_19','analytics','/ˌænəˈlɪtɪks/','noun','분석 데이터','Data showing how content performs (views, reach, retention).','Check your {analytics} to see what your audience enjoys.','어떤 콘텐츠를 좋아하는지 분석 데이터를 확인해 보세요.','analytics','B1','media',1,'analytics dashboard graph data social media insights'),
('w_media_B1_20','reach','/riːtʃ/','noun','도달 범위','The total number of unique people who see a piece of content.','The campaign had a {reach} of over five million.','그 캠페인의 도달 범위는 오백만 이상이었어요.','reach','B1','media',1,'reach metric social media campaign statistics chart'),
('w_media_B1_21','niche','/niːʃ/','noun','틈새 분야','A specialized area of interest that attracts a specific audience.','Finding your {niche} is key to growing an audience.','자신의 틈새 분야를 찾는 것이 청중을 키우는 핵심이에요.','niche','B1','media',1,'niche content creator specific audience hobby channel'),
('w_media_B1_22','format','/ˈfɔːrmæt/','noun','포맷, 형식','The structure and style of a media piece.','Experiment with different {formats} to see what works.','어떤 게 효과적인지 다양한 포맷을 시험해 보세요.','formats','B1','media',2,'video format style different short long tutorial'),
('w_media_B1_23','brand deal','/brænd diːl/','noun','브랜드 딜, 광고 협찬','A paid partnership between a creator and a company.','She disclosed her {brand deal} in the video description.','그녀는 영상 설명에 브랜드 딜을 공개했어요.','brand deal','B1','media',1,'brand deal sponsorship disclosure influencer product'),
('w_media_B1_24','comment section','/ˈkɒment ˌsekʃən/','noun','댓글 창','The area below a video or post where users leave comments.','The {comment section} was filled with debate.','댓글 창은 논쟁으로 가득했어요.','comment section','B1','media',2,'comment section debate youtube controversial'),
('w_media_B1_25','binge','/bɪndʒ/','verb','몰아보다','To watch many episodes of a show in a short time.','I {binged} the whole series in one weekend.','주말 동안 시리즈 전편을 몰아봤어요.','binged','B1','media',1,'binge watching netflix series sofa night cozy'),
('w_media_B1_26','go live','/ɡoʊ laɪv/','phrase','라이브 방송을 시작하다','To begin a real-time broadcast on a social media platform.','She {went live} to answer questions from fans.','그녀는 팬들의 질문에 답하기 위해 라이브를 켰어요.','went live','B1','media',2,'going live instagram fans questions real time'),
('w_media_B1_27','retweet','/ˌriːˈtwiːt/','verb','리트윗하다','To share another user''s tweet to your own followers.','The celebrity {retweeted} the fan''s message.','그 셀럽은 팬의 메시지를 리트윗했어요.','retweeted','B1','media',2,'retweet twitter celebrity fan viral'),
('w_media_B1_28','unboxing','/ˌʌnˈbɒksɪŋ/','noun','언박싱','A type of video showing someone opening a new product.','His {unboxing} video of the new console got five million views.','그의 새 콘솔 언박싱 영상은 오백만 조회수를 받았어요.','unboxing','B1','media',2,'unboxing video product new box opening hands'),
('w_media_B1_29','tutorial','/tjuːˈtɔːriəl/','noun','튜토리얼','An instructional video or guide teaching a skill.','I learned the skill from a YouTube {tutorial}.','유튜브 튜토리얼로 그 기술을 배웠어요.','tutorial','B1','media',1,'tutorial youtube learning skill how-to video'),
('w_media_B1_30','vlog','/vlɒɡ/','noun','브이로그','A video diary or journal shared online.','She documents her travels in a weekly {vlog}.','그녀는 주간 브이로그로 여행을 기록해요.','vlog','B1','media',1,'vlog travel daily life camera selfie stick'),
('w_media_B1_31','demographic','/ˌdeməˈɡræfɪk/','noun','인구통계, 타깃 시청자','A specific group of people sharing characteristics targeted by media.','The show''s {demographic} is mostly teens and young adults.','그 쇼의 타깃 시청자는 주로 10대와 청년층이에요.','demographic','B1','media',2,'target audience demographic age group chart'),
('w_media_B1_32','spoiler','/ˈspɔɪlər/','noun','스포일러','Information that reveals key plot points before someone has seen/read them.','Warning: this review contains {spoilers}.','경고: 이 리뷰에는 스포일러가 포함되어 있어요.','spoilers','B1','media',2,'spoiler warning movie review no spoiler banner'),
('w_media_B1_33','streaming service','/ˈstriːmɪŋ ˈsɜːrvɪs/','noun','스트리밍 서비스','An online platform that provides on-demand audio or video content.','Which {streaming service} do you subscribe to?','어떤 스트리밍 서비스 구독해요?','streaming service','B1','media',1,'netflix spotify streaming service logo subscription'),
('w_media_B1_34','verified','/ˈverɪfaɪd/','adjective','인증된','Having a badge confirming authenticity on a social media account.','Getting {verified} on Instagram boosts credibility.','인스타그램에서 인증 받으면 신뢰도가 올라가요.','verified','B1','media',2,'verified blue checkmark instagram account badge'),
('w_media_B1_35','clip','/klɪp/','verb','클립으로 잘라내다','To extract a short segment from a longer video.','He {clipped} the funniest moments for his highlights.','그는 가장 재미있는 순간들을 클립으로 잘라 하이라이트를 만들었어요.','clipped','B1','media',2,'clipping video highlights editing short cut');

-- ══════════════════════════════════════
-- WORDS — B2
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_media_B2_01','misinformation','/ˌmɪsɪnfərˈmeɪʃən/','noun','잘못된 정보','False or inaccurate information spread without deliberate intent to deceive.','Social media accelerates the spread of {misinformation}.','소셜 미디어는 잘못된 정보의 확산을 가속화해요.','misinformation','B2','media',1,'misinformation fake news spread social media warning'),
('w_media_B2_02','disinformation','/ˌdɪsɪnfərˈmeɪʃən/','noun','허위 정보','False information deliberately spread to deceive people.','State-sponsored {disinformation} campaigns target voters.','국가 주도의 허위 정보 캠페인은 유권자를 타깃으로 해요.','disinformation','B2','media',1,'disinformation propaganda fake news government media'),
('w_media_B2_03','clickbait','/ˈklɪkbeɪt/','verb (derived)','낚시 기사를 쓰다','To produce content with misleading headlines to attract clicks.','Many news outlets resort to {clickbait} to survive.','많은 언론사들이 살아남기 위해 낚시성 기사에 의존해요.','clickbait','B2','media',1,'clickbait headline news outlet sensational media'),
('w_media_B2_04','polarization','/ˌpoʊlərɪˈzeɪʃən/','noun','양극화','The process of dividing into two opposing groups with extreme views.','Social media contributes to political {polarization}.','소셜 미디어는 정치적 양극화에 기여해요.','polarization','B2','media',1,'political polarization divided groups social media debate'),
('w_media_B2_05','narrative','/ˈnærətɪv/','noun','서사, 담론','The particular way a story or series of events is described or interpreted.','The media shapes the {narrative} around public events.','미디어는 공공 사건에 대한 서사를 형성해요.','narrative','B2','media',1,'media narrative storytelling news framing bias'),
('w_media_B2_06','curate','/kjʊˈreɪt/','verb','큐레이션하다','To carefully select and organize content for a specific audience.','She {curates} a daily newsletter of the best tech news.','그녀는 매일 최고의 기술 뉴스 뉴스레터를 큐레이션해요.','curates','B2','media',1,'curating content newsletter best selection editorial'),
('w_media_B2_07','monetize','/ˈmɒnɪtaɪz/','verb','수익화 전략을 세우다','To develop revenue streams from digital content or platforms.','The startup is looking for ways to {monetize} user data.','그 스타트업은 사용자 데이터를 수익화할 방법을 찾고 있어요.','monetize','B2','media',1,'monetize data startup revenue business model digital'),
('w_media_B2_08','analytics','/ˌænəˈlɪtɪks/','noun','고급 분석','Advanced data analysis used to understand audience behaviour.','Deep {analytics} reveal when your audience is most active.','심층 분석을 통해 청중이 가장 활발한 시간대를 알 수 있어요.','analytics','B2','media',1,'deep analytics dashboard data visualization insight'),
('w_media_B2_09','demographic','/ˌdeməˈɡræfɪk/','adjective','인구통계학적인','Relating to the structure of populations in terms of age, gender, etc.','The platform shifted its {demographic} focus to older users.','그 플랫폼은 인구통계학적 초점을 고령층으로 바꿨어요.','demographic','B2','media',1,'demographic shift older users platform age graph'),
('w_media_B2_10','reach','/riːtʃ/','verb','도달하다 (미디어)','To successfully communicate with or influence a target audience.','The campaign aimed to {reach} young voters.','그 캠페인은 젊은 유권자들에게 닿는 것을 목표로 했어요.','reach','B2','media',1,'campaign reaching young voters media strategy'),
('w_media_B2_11','echo chamber','/ˈekoʊ ˌtʃeɪmbər/','noun','에코 챔버, 정보의 거품','An environment where people only encounter views that reinforce their own.','Social media algorithms can trap users in an {echo chamber}.','소셜 미디어 알고리즘이 사용자를 에코 챔버에 가두기도 해요.','echo chamber','B2','media',1,'echo chamber bubble social media algorithm opinions'),
('w_media_B2_12','filter bubble','/ˈfɪltər ˌbʌbəl/','noun','필터 버블','A state of intellectual isolation caused by personalised content.','We need to burst our {filter bubble} and seek diverse news.','필터 버블을 깨고 다양한 뉴스를 접해야 해요.','filter bubble','B2','media',1,'filter bubble personalization algorithm isolation diverse'),
('w_media_B2_13','fact-check','/ˈfækt tʃek/','verb','팩트체크하다','To verify the accuracy of a claim or piece of information.','Always {fact-check} before sharing news online.','온라인에서 뉴스를 공유하기 전에 항상 팩트체크하세요.','fact-check','B2','media',1,'fact checking news media accuracy verification research'),
('w_media_B2_14','media literacy','/ˈmiːdiə ˌlɪtərəsi/','noun','미디어 리터러시','The ability to critically analyze and evaluate media messages.','Schools should teach {media literacy} from an early age.','학교에서는 어릴 때부터 미디어 리터러시를 가르쳐야 해요.','media literacy','B2','media',1,'media literacy education critical thinking news students'),
('w_media_B2_15','algorithm bias','/ˈælɡərɪðəm baɪəs/','noun','알고리즘 편향','When a recommendation system systematically favours certain viewpoints.','Researchers found evidence of {algorithm bias} on the platform.','연구자들은 그 플랫폼에서 알고리즘 편향의 증거를 발견했어요.','algorithm bias','B2','media',1,'algorithm bias AI fairness data skewed results'),
('w_media_B2_16','credibility','/ˌkredɪˈbɪlɪti/','noun','신뢰성','The quality of being trusted and believed as accurate.','A journalist''s {credibility} is their most valuable asset.','저널리스트의 신뢰성은 가장 소중한 자산이에요.','credibility','B2','media',1,'credibility journalist trust media source reliable'),
('w_media_B2_17','bias','/ˈbaɪəs/','noun','편향','Inclination or prejudice in favour of or against something.','Every news outlet has some degree of editorial {bias}.','모든 언론사에는 어느 정도의 편집 편향이 있어요.','bias','B2','media',1,'media bias editorial perspective lean news'),
('w_media_B2_18','censorship','/ˈsensərʃɪp/','noun','검열','The suppression of content deemed objectionable or harmful.','Critics accused the government of internet {censorship}.','비평가들은 정부를 인터넷 검열로 비난했어요.','censorship','B2','media',1,'censorship internet blocked government freedom press'),
('w_media_B2_19','algorithm','/ˈælɡərɪðəm/','noun','알고리즘 (플랫폼 전략)','The complex system determining what content appears in user feeds.','Understanding the {algorithm} is key to growing online.','알고리즘을 이해하는 것이 온라인에서 성장하는 핵심이에요.','algorithm','B2','media',1,'algorithm code data platform content recommendation'),
('w_media_B2_20','influencer marketing','/ˈɪnfluənsər ˈmɑːrkɪtɪŋ/','noun','인플루언서 마케팅','A strategy using popular social media figures to promote products.','Brands now invest heavily in {influencer marketing}.','브랜드들은 이제 인플루언서 마케팅에 대규모 투자를 해요.','influencer marketing','B2','media',1,'influencer marketing brand partnership sponsored content'),
('w_media_B2_21','deepfake','/ˈdiːpfeɪk/','noun','딥페이크','Synthetic media using AI to replace someone''s likeness in video.','A {deepfake} video of the politician circulated online.','그 정치인의 딥페이크 영상이 온라인에 퍼졌어요.','deepfake','B2','media',1,'deepfake AI fake video face swap synthetic media'),
('w_media_B2_22','transparency','/trænsˈpærənsi/','noun','투명성','Openness about how decisions, including content choices, are made.','The platform was called out for a lack of {transparency}.','그 플랫폼은 투명성 부족으로 비난을 받았어요.','transparency','B2','media',1,'transparency platform content policy trust accountability'),
('w_media_B2_23','engagement rate','/ɪnˈɡeɪdʒmənt reɪt/','noun','참여율','The percentage of followers who interact with a post.','An {engagement rate} above 3% is considered healthy.','참여율 3% 이상은 양호한 것으로 여겨져요.','engagement rate','B2','media',1,'engagement rate analytics instagram metric performance'),
('w_media_B2_24','content moderation','/ˈkɒntent ˌmɒdəˈreɪʃən/','noun','콘텐츠 중재','The process of monitoring and enforcing platform rules.','{Content moderation} is increasingly handled by AI.','콘텐츠 중재는 점점 더 AI가 담당하고 있어요.','content moderation','B2','media',1,'content moderation AI flag remove policy platform'),
('w_media_B2_25','virality','/vaɪˈræləti/','noun','바이럴성','The quality of spreading rapidly across social networks.','The ad''s {virality} surprised even the marketing team.','그 광고의 바이럴성은 마케팅 팀조차 놀라게 했어요.','virality','B2','media',1,'virality social media ad campaign surprise spread'),
('w_media_B2_26','cancel culture','/ˈkænsəl ˌkʌltʃər/','noun','캔슬 컬처','The practice of withdrawing support from public figures for offensive behaviour.','The debate around {cancel culture} divides opinions online.','캔슬 컬처를 둘러싼 논쟁이 온라인에서 의견을 나누고 있어요.','cancel culture','B2','media',1,'cancel culture debate social media public figure'),
('w_media_B2_27','comment moderation','/ˈkɒment ˌmɒdəˈreɪʃən/','noun','댓글 관리','The review and removal of harmful or abusive user comments.','Better {comment moderation} could reduce online hate speech.','더 나은 댓글 관리로 온라인 혐오 발언을 줄일 수 있어요.','comment moderation','B2','media',2,'comment moderation hate speech online safety platform'),
('w_media_B2_28','algorithm-driven','/ˈælɡərɪðəm ˌdrɪvən/','adjective','알고리즘 기반의','Controlled or determined by automated computational rules.','Our news experience has become entirely {algorithm-driven}.','우리의 뉴스 경험은 완전히 알고리즘 기반이 됐어요.','algorithm-driven','B2','media',2,'algorithm driven news feed automated personalised'),
('w_media_B2_29','news cycle','/njuːz ˈsaɪkəl/','noun','뉴스 사이클','The time it takes for a story to appear, peak, and disappear from media.','Politicians now exploit the 24-hour {news cycle}.','정치인들은 이제 24시간 뉴스 사이클을 이용해요.','news cycle','B2','media',1,'24 hour news cycle media coverage fast changing'),
('w_media_B2_30','platform economy','/ˈplætfɔːrm ɪˈkɒnəmi/','noun','플랫폼 경제','An economic model where value is created through digital platforms.','The {platform economy} has disrupted traditional industries.','플랫폼 경제가 전통 산업을 혁신해 왔어요.','platform economy','B2','media',1,'platform economy disruption digital gig creator'),
('w_media_B2_31','data privacy','/ˈdeɪtə ˈprɪvəsi/','noun','데이터 프라이버시','The right of individuals to control how their personal data is used.','Users are increasingly concerned about {data privacy}.','사용자들은 데이터 프라이버시에 대한 우려가 점점 커지고 있어요.','data privacy','B2','media',1,'data privacy GDPR personal information protection'),
('w_media_B2_32','sensationalism','/senˈseɪʃənəlɪzəm/','noun','선정주의','The use of shocking or exaggerated stories to attract attention.','Tabloid journalism often relies on {sensationalism}.','타블로이드 저널리즘은 종종 선정주의에 의존해요.','sensationalism','B2','media',1,'sensationalism tabloid headline shocking exaggerated news'),
('w_media_B2_33','public opinion','/ˈpʌblɪk əˈpɪnjən/','noun','여론','The collective views held by a large number of people on a topic.','Social media now shapes {public opinion} faster than ever.','소셜 미디어가 이제 그 어느 때보다 빠르게 여론을 형성해요.','public opinion','B2','media',1,'public opinion poll social media influence speed'),
('w_media_B2_34','editorial','/ˌedɪˈtɔːriəl/','noun','사설, 편집의','An article expressing the opinion of a publication.','The newspaper ran a critical {editorial} on the policy.','그 신문은 정책에 비판적인 사설을 실었어요.','editorial','B2','media',1,'editorial newspaper opinion page critical analysis'),
('w_media_B2_35','press freedom','/pres ˈfriːdəm/','noun','언론의 자유','The freedom of journalists and news organisations to report without restriction.','Journalists worldwide fight to protect {press freedom}.','전 세계 기자들은 언론의 자유를 지키기 위해 싸우고 있어요.','press freedom','B2','media',1,'press freedom journalism protest newspaper freedom');

-- ══════════════════════════════════════
-- WORDS — C1
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_media_C1_01','media literacy','/ˈmiːdiə ˌlɪtərəsi/','noun','미디어 리터러시','The capacity to access, analyze, evaluate, and create media messages.','Developing {media literacy} is essential in today''s information landscape.','오늘날의 정보 환경에서 미디어 리터러시를 키우는 것은 필수예요.','media literacy','C1','media',1,'media literacy critical thinking news analysis skills'),
('w_media_C1_02','propaganda','/ˌprɒpəˈɡændə/','noun','선전, 프로파간다','Information, especially biased, used to promote a political cause.','State-run media often functions as a vehicle for {propaganda}.','국가 운영 미디어는 종종 선전의 수단으로 기능해요.','propaganda','C1','media',1,'propaganda poster government media bias political'),
('w_media_C1_03','surveillance','/sərˈveɪləns/','noun','감시 (디지털)','The monitoring of behaviour and communications, especially online.','Mass digital {surveillance} raises serious privacy concerns.','대규모 디지털 감시는 심각한 프라이버시 우려를 낳아요.','surveillance','C1','media',1,'surveillance cameras CCTV digital monitoring privacy'),
('w_media_C1_04','censorship','/ˈsensərʃɪp/','noun','검열 (비판적 관점)','The suppression of speech or information considered harmful or politically inconvenient.','Internet {censorship} is expanding in authoritarian states.','인터넷 검열이 권위주의 국가에서 확대되고 있어요.','censorship','C1','media',1,'internet censorship authoritarian block firewall freedom'),
('w_media_C1_05','epistemology','/ɪˌpɪstɪˈmɒlədʒi/','noun','인식론','The branch of philosophy concerned with how we know what we know.','The post-truth era challenges our media {epistemology}.','탈진실 시대는 우리의 미디어 인식론에 도전장을 내밀어요.','epistemology','C1','media',1,'epistemology knowledge philosophy truth media information'),
('w_media_C1_06','discourse','/ˈdɪskɔːrs/','noun','담론','A way of talking about or representing a subject that shapes understanding.','The public {discourse} around AI is often distorted by media.','AI에 관한 공론장 담론은 미디어에 의해 종종 왜곡돼요.','discourse','C1','media',1,'public discourse debate media analysis social conversation'),
('w_media_C1_07','hegemony','/hɪˈɡeməni/','noun','헤게모니','Dominance by one group over others, especially in cultural or media terms.','Media {hegemony} shapes which stories get told globally.','미디어 헤게모니는 어떤 이야기가 전 세계적으로 전달될지 형성해요.','hegemony','C1','media',1,'media hegemony global dominance power cultural influence'),
('w_media_C1_08','gatekeeping','/ˈɡeɪtkiːpɪŋ/','noun','게이트키핑','The process of controlling access to information in the media.','Social media has disrupted traditional journalistic {gatekeeping}.','소셜 미디어는 전통적인 저널리즘의 게이트키핑을 혼란에 빠뜨렸어요.','gatekeeping','C1','media',1,'gatekeeping journalism editor media power information'),
('w_media_C1_09','framing','/ˈfreɪmɪŋ/','noun','프레이밍, 틀짓기','The process by which media shapes how issues are perceived.','The {framing} of immigration as a crisis influences public opinion.','이민을 위기로 프레이밍하는 것이 여론에 영향을 줘요.','framing','C1','media',1,'media framing immigration news coverage bias perspective'),
('w_media_C1_10','agenda-setting','/əˈdʒendə ˌsetɪŋ/','noun','의제 설정','The media''s power to influence which issues the public considers important.','News editors engage in {agenda-setting} every day.','뉴스 편집자들은 매일 의제 설정을 해요.','agenda-setting','C1','media',1,'agenda setting media power news editorial priority'),
('w_media_C1_11','manufactured consent','/ˌmænjʊˈfæktʃərd kənˈsent/','noun','동의 조작','The systematic shaping of public opinion by elites through media.','Noam Chomsky described {manufactured consent} in mass media.','노암 촘스키는 대중 매체에서의 동의 조작을 설명했어요.','manufactured consent','C1','media',1,'manufactured consent Chomsky media elite propaganda'),
('w_media_C1_12','disinformation warfare','/ˌdɪsɪnfərˈmeɪʃən ˈwɔːrfer/','noun','허위정보 전쟁','The strategic use of false information as a tool of geopolitical conflict.','Several nations engage in {disinformation warfare} online.','여러 국가들이 온라인에서 허위정보 전쟁을 벌이고 있어요.','disinformation warfare','C1','media',1,'information warfare geopolitics online fake news strategy'),
('w_media_C1_13','participatory media','/pɑːˌtɪsɪpətɔːri ˈmiːdiə/','noun','참여적 미디어','Media forms that enable active audience engagement and content creation.','Blogs were the first wave of {participatory media}.','블로그는 참여적 미디어의 첫 번째 물결이었어요.','participatory media','C1','media',2,'participatory media blog user generated content web'),
('w_media_C1_14','algorithmic amplification','/ˌælɡərɪðmɪk ˌæmplɪfɪˈkeɪʃən/','noun','알고리즘 증폭','The process by which platforms boost the spread of certain content.','Outrage content benefits from {algorithmic amplification}.','분노 유발 콘텐츠는 알고리즘 증폭으로 이득을 봐요.','algorithmic amplification','C1','media',1,'algorithm amplification outrage viral spread content boost'),
('w_media_C1_15','media convergence','/ˈmiːdiə kənˈvɜːrdʒəns/','noun','미디어 융합','The merging of different media forms through digital technology.','The smartphone is a symbol of {media convergence}.','스마트폰은 미디어 융합의 상징이에요.','media convergence','C1','media',2,'media convergence smartphone digital all-in-one platform'),
('w_media_C1_16','infodemic','/ˌɪnfoʊˈdemɪk/','noun','인포데믹','An overabundance of information, especially online misinformation during a crisis.','The WHO warned of an {infodemic} alongside the pandemic.','WHO는 팬데믹과 함께 인포데믹을 경고했어요.','infodemic','C1','media',1,'infodemic misinformation pandemic overload news'),
('w_media_C1_17','platform governance','/ˈplætfɔːrm ˈɡʌvərnəns/','noun','플랫폼 거버넌스','The rules and systems by which online platforms manage their communities.','Calls for better {platform governance} are growing louder.','더 나은 플랫폼 거버넌스를 요구하는 목소리가 커지고 있어요.','platform governance','C1','media',1,'platform governance regulation tech policy law rules'),
('w_media_C1_18','soft power','/sɒft ˈpaʊər/','noun','소프트 파워','The ability to influence others through cultural appeal rather than force.','Global streaming platforms are tools of cultural {soft power}.','글로벌 스트리밍 플랫폼은 문화적 소프트 파워의 도구예요.','soft power','C1','media',1,'soft power culture Netflix streaming global influence'),
('w_media_C1_19','attention economy','/əˈtenʃən ɪˈkɒnəmi/','noun','관심 경제','An economic model based on capturing and monetizing users'' attention.','Platforms compete fiercely in the {attention economy}.','플랫폼들은 관심 경제에서 치열하게 경쟁해요.','attention economy','C1','media',1,'attention economy screen time engagement addictive design'),
('w_media_C1_20','digital colonialism','/ˈdɪdʒɪtəl kəˈloʊniəlɪzəm/','noun','디지털 식민주의','The dominance of Western tech companies over global digital infrastructure.','Critics warn of {digital colonialism} by Silicon Valley giants.','비평가들은 실리콘 밸리 거대 기업들의 디지털 식민주의를 경고해요.','digital colonialism','C1','media',1,'digital colonialism silicon valley global tech power'),
('w_media_C1_21','counter-narrative','/ˈkaʊntər ˌnærətɪv/','noun','대항 서사','A competing story that challenges the dominant media narrative.','Activists use social media to spread {counter-narratives}.','활동가들은 소셜 미디어를 이용해 대항 서사를 퍼뜨려요.','counter-narratives','C1','media',2,'counter narrative activism social media alternative story'),
('w_media_C1_22','media pluralism','/ˈmiːdiə ˈplʊərəlɪzəm/','noun','미디어 다원주의','A diversity of independent media outlets presenting different viewpoints.','True democracy requires {media pluralism}.','진정한 민주주의는 미디어 다원주의를 필요로 해요.','media pluralism','C1','media',2,'media pluralism diversity news outlets viewpoints democracy'),
('w_media_C1_23','techno-optimism','/ˈteknəʊ ˈɒptɪmɪzəm/','noun','기술 낙관주의','The belief that technology will solve social and media problems.','Critics argue that {techno-optimism} ignores structural harms.','비평가들은 기술 낙관주의가 구조적 해악을 외면한다고 주장해요.','techno-optimism','C1','media',2,'techno optimism silicon valley future technology belief'),
('w_media_C1_24','news deserts','/njuːz ˈdezərts/','noun','뉴스 사막','Areas with little or no local journalism coverage.','Hundreds of US counties have become {news deserts}.','미국 수백 개 군이 뉴스 사막이 됐어요.','news deserts','C1','media',2,'news deserts local journalism decline community newspaper'),
('w_media_C1_25','moral panic','/ˈmɒrəl ˈpænɪk/','noun','도덕적 공황','An exaggerated social reaction to a perceived threat driven by media coverage.','Each new social media platform causes a {moral panic}.','새로운 소셜 미디어 플랫폼이 나올 때마다 도덕적 공황이 생겨요.','moral panic','C1','media',2,'moral panic social media technology fear parents media'),
('w_media_C1_26','co-creation','/ˌkoʊ kriˈeɪʃən/','noun','공동 창작','The joint production of content by creators and their audiences.','Fan fiction is a form of {co-creation} with media properties.','팬픽션은 미디어 자산과의 공동 창작 형태예요.','co-creation','C1','media',2,'co-creation fan fiction collaboration community content'),
('w_media_C1_27','cross-platform strategy','/krɒs ˈplætfɔːrm ˈstrætədʒi/','noun','크로스 플랫폼 전략','A content plan that distributes material across multiple channels.','A successful {cross-platform strategy} maximizes audience reach.','성공적인 크로스 플랫폼 전략은 청중 도달 범위를 극대화해요.','cross-platform strategy','C1','media',2,'cross platform strategy social media distribution channels'),
('w_media_C1_28','mediatization','/ˌmiːdiətaɪˈzeɪʃən/','noun','미디어화','The process by which society is increasingly shaped by media logic.','Politics has undergone profound {mediatization} since the 1990s.','정치는 1990년대 이후 깊은 미디어화를 겪어왔어요.','mediatization','C1','media',2,'mediatization politics society media logic television'),
('w_media_C1_29','networked journalism','/ˈnetwɜːrkt ˈdʒɜːrnəlɪzəm/','noun','네트워크 저널리즘','Journalism that involves collaboration between professionals and citizens online.','{Networked journalism} blurs the line between reporter and public.','네트워크 저널리즘은 기자와 대중 사이의 경계를 흐려요.','networked journalism','C1','media',2,'networked journalism citizen reporter online collaboration'),
('w_media_C1_30','digital public sphere','/ˈdɪdʒɪtəl ˌpʌblɪk sfɪər/','noun','디지털 공론장','An online space where citizens debate and form public opinion.','Twitter once promised to be a {digital public sphere}.','트위터는 한때 디지털 공론장이 될 것을 약속했어요.','digital public sphere','C1','media',1,'digital public sphere twitter debate democratic opinion'),
('w_media_C1_31','surveillance capitalism','/sərˈveɪləns ˈkæpɪtəlɪzəm/','noun','감시 자본주의','An economic system built on collecting and selling personal data.','Shoshana Zuboff coined the term {surveillance capitalism}.','쇼샤나 주보프는 감시 자본주의라는 용어를 만들었어요.','surveillance capitalism','C1','media',1,'surveillance capitalism data harvesting Zuboff platform'),
('w_media_C1_32','weaponized information','/ˈwepənaɪzd ɪnfərˈmeɪʃən/','noun','무기화된 정보','Information deliberately distorted to destabilize societies.','Democracies struggle to defend against {weaponized information}.','민주주의는 무기화된 정보에 맞서 싸우고 있어요.','weaponized information','C1','media',1,'weaponized information democracy defense disinformation'),
('w_media_C1_33','credibility cues','/ˌkredɪˈbɪlɪti kjuːz/','noun','신뢰성 단서','Visual or contextual signals that indicate whether information is trustworthy.','Readers use {credibility cues} to judge news reliability.','독자들은 신뢰성 단서를 이용해 뉴스 신뢰도를 판단해요.','credibility cues','C1','media',2,'credibility cues news source trust signal evaluation'),
('w_media_C1_34','transparency reporting','/trænsˈpærənsi rɪˈpɔːrtɪŋ/','noun','투명성 보고','Public disclosure by platforms about their moderation and ad policies.','Regulators now require quarterly {transparency reporting}.','규제당국은 이제 분기별 투명성 보고를 요구해요.','transparency reporting','C1','media',2,'transparency reporting regulation platform accountability'),
('w_media_C1_35','editorial independence','/ˌedɪˈtɔːriəl ˌɪndɪˈpendəns/','noun','편집권 독립','The freedom of journalists to report without interference from owners or advertisers.','Public broadcasters must protect {editorial independence}.','공영 방송은 편집권 독립을 지켜야 해요.','editorial independence','C1','media',1,'editorial independence journalism freedom owner advertiser');

-- ══════════════════════════════════════
-- WORDS — C2
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_media_C2_01','semiotics','/ˌsiːmiˈɒtɪks/','noun','기호학','The study of signs, symbols, and their meaning in communication.','Applying {semiotics} to advertising reveals hidden messages.','광고에 기호학을 적용하면 숨겨진 메시지가 드러나요.','semiotics','C2','media',1,'semiotics signs symbols advertising hidden meaning'),
('w_media_C2_02','commodification','/kəˌmɒdɪfɪˈkeɪʃən/','noun','상품화','The process of turning something non-commercial into a market commodity.','The {commodification} of personal data is a defining feature of the internet age.','개인 데이터의 상품화는 인터넷 시대의 결정적 특징이에요.','commodification','C2','media',1,'commodification data personal information market internet'),
('w_media_C2_03','hyperreality','/ˌhaɪpərriˈæləti/','noun','초현실','A condition where the distinction between reality and simulation collapses.','Baudrillard argued that media creates a state of {hyperreality}.','보드리야르는 미디어가 초현실 상태를 만들어낸다고 주장했어요.','hyperreality','C2','media',1,'hyperreality Baudrillard simulation reality media philosophy'),
('w_media_C2_04','simulacrum','/ˌsɪmjʊˈlɑːkrəm/','noun','시뮬라크르','A copy or representation that has no original, replacing reality itself.','Social media presents a {simulacrum} of authentic social life.','소셜 미디어는 진정한 사회생활의 시뮬라크르를 제시해요.','simulacrum','C2','media',1,'simulacrum copy representation social media fake authentic'),
('w_media_C2_05','technocracy','/tekˈnɒkrəsi/','noun','기술 관료제','A system of governance where technology experts hold power.','Silicon Valley''s rise reflects a new digital {technocracy}.','실리콘 밸리의 부상은 새로운 디지털 기술 관료제를 반영해요.','technocracy','C2','media',1,'technocracy silicon valley power governance engineers'),
('w_media_C2_06','post-truth','/poʊst truːθ/','adjective','탈진실의','Relating to circumstances where emotion and belief override objective facts.','We live in a {post-truth} media environment.','우리는 탈진실 미디어 환경 속에 살고 있어요.','post-truth','C2','media',1,'post-truth media era emotion facts belief politics'),
('w_media_C2_07','infosphere','/ˈɪnfoʊsfɪər/','noun','인포스피어','The global environment of information and communication systems.','Luciano Floridi conceptualizes the {infosphere} as our new habitat.','루치아노 플로리디는 인포스피어를 우리의 새로운 서식지로 개념화해요.','infosphere','C2','media',1,'infosphere information environment global digital Floridi'),
('w_media_C2_08','algorithmic governance','/ˌælɡərɪðmɪk ˈɡʌvərnəns/','noun','알고리즘 통치','The use of automated systems to make decisions with public consequences.','Critics argue that {algorithmic governance} lacks democratic accountability.','비평가들은 알고리즘 통치가 민주적 책임을 결여한다고 주장해요.','algorithmic governance','C2','media',1,'algorithmic governance automation policy accountability'),
('w_media_C2_09','deepfake epistemics','/ˈdiːpfeɪk ˌepɪˈstemɪks/','noun','딥페이크 인식론','The study of how synthetic media affects our ability to trust what we perceive.','Scholars of {deepfake epistemics} question the evidentiary value of video.','딥페이크 인식론 학자들은 영상의 증거적 가치에 의문을 제기해요.','deepfake epistemics','C2','media',1,'deepfake truth evidence epistemics philosophy media'),
('w_media_C2_10','Habermasian','/ˌhɑːbərˈmɑːziən/','adjective','하버마스적','Relating to the ideas of Jürgen Habermas, especially the public sphere.','A {Habermasian} analysis reveals how platforms distort rational discourse.','하버마스적 분석은 플랫폼이 어떻게 합리적 담론을 왜곡하는지 드러내요.','Habermasian','C2','media',1,'Habermas public sphere rational discourse philosophy'),
('w_media_C2_11','ontological security','/ˌɒntəˈlɒdʒɪkəl sɪˈkjʊərɪti/','noun','존재론적 안정성','The sense of order and continuity in one''s world, which media can disrupt.','Constant news overload threatens individuals'' {ontological security}.','끊임없는 뉴스 과부하는 개인의 존재론적 안정성을 위협해요.','ontological security','C2','media',1,'ontological security media anxiety information overload'),
('w_media_C2_12','discursive formation','/dɪˈskɜːrsɪv fɔːˈmeɪʃən/','noun','담론 형성체','A group of statements that systematically form the objects they describe (Foucault).','The coverage constitutes a {discursive formation} around criminality.','그 보도는 범죄성에 관한 담론 형성체를 구성해요.','discursive formation','C2','media',1,'discursive formation Foucault media discourse analysis'),
('w_media_C2_13','ideological state apparatus','/ˌaɪdiəˈlɒdʒɪkəl steɪt ˈæpərətəs/','noun','이데올로기적 국가 기구','Althusser''s concept of institutions (including media) that reproduce ruling ideology.','Mass media functions as an {ideological state apparatus}.','대중 매체는 이데올로기적 국가 기구로 기능해요.','ideological state apparatus','C2','media',1,'Althusser ideology state apparatus media television'),
('w_media_C2_14','mediatized politics','/ˈmiːdiətaɪzd ˈpɒlɪtɪks/','noun','미디어화된 정치','The phenomenon of political life being fundamentally shaped by media formats.','Image management is central to {mediatized politics}.','이미지 관리는 미디어화된 정치의 핵심이에요.','mediatized politics','C2','media',1,'mediatized politics image management spin media campaign'),
('w_media_C2_15','networked individualism','/ˈnetwɜːrkt ˌɪndɪˈvɪdʒuəlɪzəm/','noun','네트워크화된 개인주의','A social pattern where people maintain connections through personal networks rather than groups.','Castells described {networked individualism} as the new social operating system.','카스텔스는 네트워크화된 개인주의를 새로운 사회 운영 체계라고 설명했어요.','networked individualism','C2','media',1,'networked individualism Castells social network personal'),
('w_media_C2_16','attention fragmentation','/əˈtenʃən ˌfræɡmenˈteɪʃən/','noun','주의 분산','The breaking up of audience attention across many competing media channels.','{Attention fragmentation} has made mass broadcasting obsolete.','주의 분산은 대규모 방송을 구식으로 만들었어요.','attention fragmentation','C2','media',1,'attention fragmentation multiple screens media distracted'),
('w_media_C2_17','parasocial relationship','/ˌpærəˈsoʊʃəl rɪˈleɪʃənʃɪp/','noun','의사 사회적 관계','A one-sided emotional bond viewers form with media figures.','Audiences form deep {parasocial relationships} with podcasters.','청중은 팟캐스터와 깊은 의사 사회적 관계를 형성해요.','parasocial relationships','C2','media',1,'parasocial relationship youtube podcaster fan bond'),
('w_media_C2_18','technodeterminism','/ˌteknəʊdɪˈtɜːrmɪnɪzəm/','noun','기술 결정론','The belief that technology autonomously drives social and cultural change.','McLuhan''s "the medium is the message" exemplifies {technodeterminism}.','맥루한의 "미디어가 메시지다"는 기술 결정론의 예시예요.','technodeterminism','C2','media',1,'technodeterminism McLuhan medium message technology change'),
('w_media_C2_19','platform imperialism','/ˈplætfɔːrm ɪmˈpɪəriəlɪzəm/','noun','플랫폼 제국주의','The dominance of Western digital platforms over global information flows.','Scholars debate whether TikTok challenges {platform imperialism}.','학자들은 틱톡이 플랫폼 제국주의에 도전하는지 논쟁해요.','platform imperialism','C2','media',1,'platform imperialism TikTok Western digital global power'),
('w_media_C2_20','noise-to-signal ratio','/nɔɪz tə ˈsɪɡnəl ˈreɪʃioʊ/','noun','잡음 대 신호 비율','The proportion of irrelevant or low-quality content relative to valuable information.','The high {noise-to-signal ratio} online makes quality journalism vital.','온라인의 높은 잡음 대 신호 비율은 양질의 저널리즘을 필수로 만들어요.','noise-to-signal ratio','C2','media',1,'noise signal ratio information quality journalism online'),
('w_media_C2_21','second-order media effects','/ˈsekənd ˈɔːrdər ˈmiːdiə ɪˈfekts/','noun','2차 미디어 효과','Indirect social changes caused by media exposure beyond the intended message.','Long-term {second-order media effects} are difficult to measure.','장기적인 2차 미디어 효과는 측정하기 어려워요.','second-order media effects','C2','media',2,'second order effects media long term social change'),
('w_media_C2_22','performative contradiction','/pərˈfɔːrmətɪv ˌkɒntrəˈdɪkʃən/','noun','수행적 자기 모순','A statement that undermines the very norms it appeals to in order to be made.','A media company claiming to fight censorship while blocking content commits a {performative contradiction}.','검열과 싸운다고 주장하면서 콘텐츠를 차단하는 미디어 기업은 수행적 자기 모순을 범해요.','performative contradiction','C2','media',2,'performative contradiction hypocrisy media platform censorship'),
('w_media_C2_23','digital hermeneutics','/ˈdɪdʒɪtəl ˌhɜːrməˈnjuːtɪks/','noun','디지털 해석학','The interpretation of digital texts and media in cultural context.','Scholars of {digital hermeneutics} study how algorithms shape reading.','디지털 해석학 학자들은 알고리즘이 독서를 어떻게 형성하는지 연구해요.','digital hermeneutics','C2','media',2,'digital hermeneutics text meaning algorithm reading culture'),
('w_media_C2_24','epistemic crisis','/ˌepɪˈstiːmɪk ˈkraɪsɪs/','noun','인식론적 위기','A breakdown in shared standards for establishing truth or knowledge.','Widespread disinformation has produced an {epistemic crisis}.','광범위한 허위정보가 인식론적 위기를 초래했어요.','epistemic crisis','C2','media',1,'epistemic crisis truth knowledge breakdown disinformation'),
('w_media_C2_25','communicative capitalism','/kəˈmjuːnɪkətɪv ˈkæpɪtəlɪzəm/','noun','소통적 자본주의','The idea that digital communication has been absorbed into capitalist exchange.','Jodi Dean''s concept of {communicative capitalism} explains the addictive logic of social media.','조디 딘의 소통적 자본주의 개념은 소셜 미디어의 중독 논리를 설명해요.','communicative capitalism','C2','media',2,'communicative capitalism social media engagement addiction loop'),
('w_media_C2_26','ideological interpellation','/ˌaɪdiəˈlɒdʒɪkəl ˌɪntɜːrpəˈleɪʃən/','noun','이데올로기적 호명','Althusser''s concept of how media "hails" individuals into ideological subject positions.','Advertising functions through {ideological interpellation}.','광고는 이데올로기적 호명을 통해 작동해요.','ideological interpellation','C2','media',2,'interpellation Althusser ideology advertising subject media'),
('w_media_C2_27','cultural hegemony','/ˈkʌltʃərəl hɪˈɡeməni/','noun','문화적 헤게모니','Gramsci''s concept of how a dominant class maintains power through cultural institutions including media.','Television historically reinforced {cultural hegemony}.','텔레비전은 역사적으로 문화적 헤게모니를 강화해왔어요.','cultural hegemony','C2','media',1,'cultural hegemony Gramsci media television dominant ideology'),
('w_media_C2_28','media ecology','/ˈmiːdiə ɪˈkɒlədʒi/','noun','미디어 생태학','The study of media environments and how they affect human perception and society.','{Media ecology} examines how screens reshape attention spans.','미디어 생태학은 화면이 어떻게 주의력 범위를 재형성하는지 검토해요.','media ecology','C2','media',2,'media ecology environment screen attention McLuhan society'),
('w_media_C2_29','semiotic democracy','/ˌsiːmiˈɒtɪk dɪˈmɒkrəsi/','noun','기호학적 민주주의','The idea that audiences actively reinterpret media texts for their own purposes.','Fan communities enact a kind of {semiotic democracy}.','팬 커뮤니티는 일종의 기호학적 민주주의를 실천해요.','semiotic democracy','C2','media',2,'semiotic democracy fan interpretation media text audience'),
('w_media_C2_30','hyper-personalization','/ˌhaɪpər ˌpɜːrsənəlaɪˈzeɪʃən/','noun','초개인화','Extreme tailoring of media content to individual users via data analysis.','The danger of {hyper-personalization} is the collapse of shared reality.','초개인화의 위험은 공유된 현실의 붕괴예요.','hyper-personalization','C2','media',1,'hyper personalization algorithm individual reality collapse'),
('w_media_C2_31','digital sovereignty','/ˈdɪdʒɪtəl ˈsɒvrənti/','noun','디지털 주권','The right of states or individuals to control their own digital environments.','European regulation is driven by a vision of {digital sovereignty}.','유럽의 규제는 디지털 주권 비전에 의해 추진되고 있어요.','digital sovereignty','C2','media',1,'digital sovereignty Europe regulation data control GDPR'),
('w_media_C2_32','technological solutionism','/ˌteknəˈlɒdʒɪkəl ˈsoʊluːʃənɪzəm/','noun','기술 만능주의','The belief that every social problem can be solved with a technological fix.','Morozov criticized Silicon Valley''s {technological solutionism}.','모로조프는 실리콘 밸리의 기술 만능주의를 비판했어요.','technological solutionism','C2','media',2,'technological solutionism Morozov Silicon Valley fix problem'),
('w_media_C2_33','critical data studies','/ˈkrɪtɪkəl ˈdeɪtə ˈstʌdiz/','noun','비판적 데이터 연구','An academic field examining the political and ethical dimensions of data collection.','Scholars in {critical data studies} interrogate platform surveillance.','비판적 데이터 연구 학자들은 플랫폼 감시를 문제 삼아요.','critical data studies','C2','media',2,'critical data studies surveillance platform ethics academic'),
('w_media_C2_34','post-digital','/poʊst ˈdɪdʒɪtəl/','adjective','포스트디지털의','Relating to a culture where digital technology is so pervasive it is no longer remarkable.','We live in a {post-digital} media landscape.','우리는 포스트디지털 미디어 환경 속에 살고 있어요.','post-digital','C2','media',2,'post-digital ubiquitous technology pervasive media culture'),
('w_media_C2_35','legitimation crisis','/ˌledʒɪtɪˈmeɪʃən ˈkraɪsɪs/','noun','정당성 위기','A breakdown of trust in social institutions, accelerated by media exposure.','Social media has triggered a {legitimation crisis} for mainstream journalism.','소셜 미디어가 주류 저널리즘의 정당성 위기를 촉발했어요.','legitimation crisis','C2','media',1,'legitimation crisis journalism trust mainstream media decline');

-- ══════════════════════════════════════
-- PATTERNS — A1 (영상·뉴스 공유)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_media_A1_01','Did you see that video?','그 영상 봤어요?','Did you see','과거에 이미 일어난 일을 물을 때는 Did you see...?를 써요. Have you seen...?보다 더 캐주얼해요.','영상 공유','A1','media','pattern',NULL,1),
('s_media_A1_02','You should watch this — it''s really funny.','이거 봐요. 정말 웃겨요.','You should watch','상대방에게 뭔가를 추천할 때 You should + 동사가 가장 간단하고 자연스러운 표현이에요.','콘텐츠 추천','A1','media','pattern',NULL,2),
('s_media_A1_03','I''ll send you the link right now.','지금 링크 보내 줄게요.','I''ll send you','즉각적인 행동을 약속할 때는 I''ll + 동사를 써요. 대화할 때 자주 쓰이는 패턴이에요.','링크 공유','A1','media','pattern',NULL,3),
('s_media_A1_04','What are you watching?','뭐 보고 있어요?','What are you watching','상대방이 지금 하고 있는 행동을 물을 때는 What are you + -ing?를 써요.','일상 대화','A1','media','pattern',NULL,4),
('s_media_A1_05','Have you heard the news today?','오늘 뉴스 들었어요?','Have you heard','최근 소식을 아는지 확인할 때는 Have you heard...?를 써요.','뉴스 확인','A1','media','pattern',NULL,5),
('s_media_A1_06','This photo is amazing — where did you take it?','이 사진 정말 대단해요. 어디서 찍었어요?','where did you take it','사진을 칭찬하며 장소를 물을 때 자연스러운 표현이에요. where did you + 동사 패턴이에요.','사진 감상','A1','media','pattern',NULL,6),
('s_media_A1_07','I listen to music on my phone every day.','저는 매일 휴대폰으로 음악을 들어요.','listen to music on my phone','습관을 말할 때는 현재 시제를 써요. on my phone은 기기를 나타낼 때 유용한 표현이에요.','음악 습관','A1','media','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — A2 (SNS 활동)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_media_A2_01','I just posted a photo — go check it out!','방금 사진 올렸어요. 가서 확인해 봐요!','go check it out','I just + 과거형은 방금 한 행동을 알릴 때 써요. go check it out은 친근하게 행동을 유도하는 표현이에요.','SNS 게시','A2','media','pattern',NULL,1),
('s_media_A2_02','Don''t forget to like and subscribe!','좋아요 누르고 구독도 잊지 마세요!','Don''t forget to','Don''t forget to + 동사는 무언가를 상기시킬 때 써요. 유튜브 영상에서 자주 들을 수 있어요.','채널 홍보','A2','media','pattern',NULL,2),
('s_media_A2_03','I''ve been following her for years — her content is great.','몇 년째 팔로우하고 있어요. 콘텐츠가 정말 좋아요.','I''ve been following','I''ve been + -ing는 과거부터 현재까지 계속된 행동을 나타내요.','팔로우 추천','A2','media','pattern',NULL,3),
('s_media_A2_04','Have you seen what''s trending today?','오늘 트렌딩에 뭐 있는지 봤어요?','Have you seen what''s trending','최근 유행 중인 것을 묻는 표현이에요. trending은 SNS에서 핵심 키워드예요.','트렌딩 화제','A2','media','pattern',NULL,4),
('s_media_A2_05','She uploaded a new video — it already has a million views.','그녀가 새 영상을 올렸어요. 벌써 조회수가 백만이에요.','already has a million views','already는 예상보다 일찍 일어난 일에 대한 놀라움을 강조해요.','조회수 화제','A2','media','pattern',NULL,5),
('s_media_A2_06','You can find me on Instagram at @username.','인스타그램에서 @username으로 찾을 수 있어요.','You can find me on','SNS 계정을 알려줄 때 You can find me on + 플랫폼 at + @계정명 패턴을 써요.','계정 소개','A2','media','pattern',NULL,6),
('s_media_A2_07','I''ve been spending too much time scrolling lately.','요즘 스크롤하면서 시간을 너무 많이 보내고 있어요.','spending too much time scrolling','I''ve been + -ing는 최근의 습관이나 상태를 반성할 때 유용해요.','SNS 과다 사용','A2','media','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — B1 (콘텐츠 추천 및 알고리즘)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_media_B1_01','The algorithm keeps recommending the same type of content.','알고리즘이 계속 같은 유형의 콘텐츠를 추천해요.','keeps recommending','keep + -ing는 어떤 행동이 반복되거나 계속됨을 나타내요. 알고리즘을 주어로 쓰는 것이 자연스러워요.','알고리즘 불만','B1','media','pattern',NULL,1),
('s_media_B1_02','I''ve been trying to grow my channel for about six months now.','채널을 키우려고 약 6개월째 노력 중이에요.','I''ve been trying to grow','I''ve been trying to + 동사는 어느 시점부터 계속 노력 중임을 표현해요. for about은 대략적인 기간에 써요.','채널 운영','B1','media','pattern',NULL,2),
('s_media_B1_03','If you want more reach, you need to post consistently.','도달 범위를 늘리려면 꾸준히 게시해야 해요.','If you want ... you need to','조건절 if를 이용해 실용적인 조언을 전달할 때 쓰는 패턴이에요.','SNS 성장 조언','B1','media','pattern',NULL,3),
('s_media_B1_04','The engagement rate tells you whether the content is working.','참여율이 콘텐츠가 효과적인지 알려줘요.','tells you whether','whether는 두 가지 가능성이 있을 때 써요. tell you whether는 분석을 설명할 때 유용해요.','콘텐츠 분석','B1','media','pattern',NULL,4),
('s_media_B1_05','I''m thinking of starting a podcast — what do you think?','팟캐스트를 시작할까 생각 중이에요. 어떻게 생각해요?','I''m thinking of starting','I''m thinking of + -ing는 아직 결정하지 않은 계획을 조심스럽게 꺼낼 때 써요.','미디어 창작 계획','B1','media','pattern',NULL,5),
('s_media_B1_06','Did you see that video went viral overnight?','그 영상이 하룻밤 사이에 바이럴된 거 봤어요?','went viral overnight','go viral은 콘텐츠가 폭발적으로 퍼지는 것을 뜻해요. overnight은 매우 빠른 확산을 강조해요.','바이럴 화제','B1','media','pattern',NULL,6),
('s_media_B1_07','I always check the analytics before deciding what to post next.','다음에 뭘 올릴지 결정하기 전에 항상 분석 데이터를 확인해요.','before deciding what to post','before + -ing는 어떤 행동을 하기 전의 습관을 나타내요. 콘텐츠 전략 설명에 유용해요.','콘텐츠 전략','B1','media','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — B2 (미디어 비평)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_media_B2_01','The headline is clearly designed to be clickbait.','그 제목은 명백히 낚시성으로 설계된 거예요.','clearly designed to be','is designed to + 동사는 의도된 목적을 비판할 때 효과적인 표현이에요. clearly가 확신의 강도를 높여요.','미디어 비판','B2','media','pattern',NULL,1),
('s_media_B2_02','I''m concerned about how misinformation spreads so quickly on social media.','소셜 미디어에서 잘못된 정보가 이렇게 빨리 퍼지는 게 걱정돼요.','I''m concerned about how','I''m concerned about how + 절은 사회적 문제에 대한 우려를 표명할 때 격식적이고 자연스러운 패턴이에요.','미디어 우려','B2','media','pattern',NULL,2),
('s_media_B2_03','You need to fact-check before you share anything online.','온라인에서 무언가를 공유하기 전에 팩트체크를 해야 해요.','fact-check before you share','You need to + 동사는 강한 필요성을 나타내요. before you + 동사는 순서를 강조해요.','팩트체크 조언','B2','media','pattern',NULL,3),
('s_media_B2_04','The way the story was framed really influenced how I felt about it.','그 이야기가 프레이밍된 방식이 제 감정에 정말 큰 영향을 줬어요.','The way ... was framed','The way + 절은 어떤 사건이 제시된 방식을 분석할 때 쓰는 고급 패턴이에요.','미디어 프레이밍','B2','media','pattern',NULL,4),
('s_media_B2_05','It''s hard to tell whether a source is reliable these days.','요즘에는 출처가 신뢰할 수 있는지 판단하기 어려워요.','It''s hard to tell whether','It''s hard to + 동사 패턴은 어려움을 공유할 때 써요. whether는 두 가능성 사이의 불확실성을 나타내요.','정보 신뢰성','B2','media','pattern',NULL,5),
('s_media_B2_06','Social media algorithms tend to reinforce our existing beliefs.','소셜 미디어 알고리즘은 우리의 기존 믿음을 강화하는 경향이 있어요.','tend to reinforce','tend to + 동사는 일반적인 경향이나 패턴을 말할 때 써요. 분석적인 주장을 부드럽게 만들어줘요.','에코 챔버 논의','B2','media','pattern',NULL,6),
('s_media_B2_07','What concerns me most is the lack of transparency in how these platforms operate.','가장 걱정되는 건 이 플랫폼들이 운영되는 방식의 투명성 부재예요.','What concerns me most is','What concerns me most is + 절은 자신의 핵심 우려를 강조하며 시작하는 고급 문어체 패턴이에요.','플랫폼 비판','B2','media','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — C1 (미디어 영향력 논의)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_media_C1_01','The media''s agenda-setting power shapes which issues we consider worth discussing.','미디어의 의제 설정 능력은 우리가 논의할 가치가 있다고 여기는 사안을 형성해요.','agenda-setting power shapes','agenda-setting power는 미디어 이론의 핵심 개념이에요. shapes + 절은 인과 관계를 설명해요.','미디어 권력 분석','C1','media','pattern',NULL,1),
('s_media_C1_02','The proliferation of social media has fundamentally disrupted traditional gatekeeping.','소셜 미디어의 확산은 전통적인 게이트키핑을 근본적으로 혼란에 빠뜨렸어요.','fundamentally disrupted','fundamentally + 과거분사는 심층적인 구조 변화를 강조해요. disrupted는 혁신 담론에서 핵심 동사예요.','미디어 구조 변화','C1','media','pattern',NULL,2),
('s_media_C1_03','One could argue that the attention economy is designed to undermine our cognitive autonomy.','관심 경제는 우리의 인지적 자율성을 약화시키도록 설계되어 있다고 주장할 수 있어요.','One could argue that','One could argue that...은 논쟁의 여지 있는 주장을 조심스럽게 제시할 때 쓰는 학술적 패턴이에요.','관심 경제 비판','C1','media','pattern',NULL,3),
('s_media_C1_04','What''s particularly troubling is the way disinformation campaigns exploit our confirmation bias.','특히 걱정스러운 것은 허위정보 캠페인이 우리의 확증 편향을 악용하는 방식이에요.','What''s particularly troubling is','What''s + 형용사 + is는 핵심 문제를 강조하는 C1 수준 강조 구문이에요.','허위정보 분석','C1','media','pattern',NULL,4),
('s_media_C1_05','Platform governance needs to balance free expression with accountability.','플랫폼 거버넌스는 표현의 자유와 책임 사이의 균형을 잡아야 해요.','needs to balance ... with','need to balance A with B는 두 가지 상충하는 가치를 논의할 때 쓰는 고급 표현이에요.','플랫폼 정책 논의','C1','media','pattern',NULL,5),
('s_media_C1_06','The erosion of editorial independence poses a long-term threat to democratic discourse.','편집권 독립의 침식은 민주적 담론에 장기적인 위협이 돼요.','poses a long-term threat to','pose a threat to는 위험을 공식적으로 서술할 때 써요. erosion은 점진적 약화를 나타내는 핵심 명사예요.','언론 자유 논의','C1','media','pattern',NULL,6),
('s_media_C1_07','Unless we develop robust media literacy education, we will remain vulnerable to manipulation.','탄탄한 미디어 리터러시 교육을 개발하지 않으면 조작에 취약한 상태가 지속돼요.','Unless we develop ... we will remain','Unless + 현재형은 조건의 부재를 강조해요. remain vulnerable to는 위험 상태의 지속성을 표현해요.','미디어 교육 필요성','C1','media','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — C2 (미디어 영향력 심화 논의)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_media_C2_01','Baudrillard''s concept of hyperreality suggests that media no longer represents reality but has replaced it.','보드리야르의 초현실 개념은 미디어가 더 이상 현실을 재현하지 않고 현실 자체를 대체했음을 시사해요.','no longer represents ... but has replaced','no longer A but has B 구조는 근본적인 전환을 표현하는 학술적 패턴이에요.','미디어 철학 논의','C2','media','pattern',NULL,1),
('s_media_C2_02','From a Habermasian perspective, algorithmic curation fundamentally distorts the conditions for rational public discourse.','하버마스적 관점에서 보면 알고리즘 큐레이션은 합리적 공론장 담론의 조건을 근본적으로 왜곡해요.','From a Habermasian perspective','From a [이론가/학파] perspective는 학술 토론에서 이론적 입장을 명확히 밝히는 패턴이에요.','미디어 이론 적용','C2','media','pattern',NULL,2),
('s_media_C2_03','The commodification of attention is arguably the defining logic of twenty-first-century media capitalism.','관심의 상품화는 21세기 미디어 자본주의의 결정적 논리라고 볼 수 있어요.','The commodification of ... is arguably the defining logic','is arguably the defining logic of는 핵심 특성을 주장하는 강력한 학술적 술어예요.','미디어 경제 비판','C2','media','pattern',NULL,3),
('s_media_C2_04','One cannot disentangle the question of media power from broader structures of political and economic hegemony.','미디어 권력의 문제는 정치·경제적 헤게모니의 광범위한 구조에서 분리할 수 없어요.','One cannot disentangle ... from','One cannot disentangle A from B는 두 개념이 불가분의 관계임을 주장하는 학술적 패턴이에요.','구조적 분석','C2','media','pattern',NULL,4),
('s_media_C2_05','The epistemological implications of deepfake technology call into question the evidentiary status of audiovisual media.','딥페이크 기술의 인식론적 함의는 시청각 미디어의 증거적 지위에 의문을 제기해요.','call into question the ... status of','call into question은 근본 전제에 이의를 제기할 때 쓰는 학술 필수 표현이에요.','딥페이크 철학','C2','media','pattern',NULL,5),
('s_media_C2_06','Semiotics reveals how media texts encode ideological assumptions that audiences may naturalise without critical reflection.','기호학은 미디어 텍스트가 비판적 성찰 없이 수용자가 자연스럽게 받아들일 수 있는 이데올로기적 가정을 어떻게 코드화하는지 드러내요.','encode ideological assumptions that audiences may naturalise','encode + 목적어 + that절은 숨겨진 의미 구조를 분석하는 기호학적 패턴이에요.','기호학적 분석','C2','media','pattern',NULL,6),
('s_media_C2_07','To the extent that platforms function as ideological state apparatuses, regulating them is not merely a technical but a deeply political project.','플랫폼이 이데올로기적 국가 기구로 기능하는 한, 플랫폼 규제는 단순히 기술적인 것이 아니라 깊이 정치적인 프로젝트예요.','To the extent that ... not merely ... but','To the extent that는 조건의 범위를 한정하는 C2 수준 패턴이에요. not merely A but B는 더 깊은 차원을 강조해요.','플랫폼 규제 논쟁','C2','media','pattern',NULL,7);
