-- EngCat — 시사·뉴스 (news) 단어 + 패턴 데이터
-- 210 words (35 per CEFR A1~C2) + 42 patterns (7 per CEFR A1~C2)
-- Schema: words v2 (cefr, priority, image_keyword) + sentences v2 (type, cefr)

-- ══════════════════════════════════════
-- WORDS — A1
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_news_A1_01','news','/njuːz/','noun','뉴스','New information about recent events or happenings.','Did you watch the {news} last night?','어젯밤 뉴스 봤어요?','news','A1','news',1,'news television broadcast anchor'),
('w_news_A1_02','report','/rɪˈpɔːrt/','noun','보도, 보고서','A spoken or written account of an event or situation.','The {report} says the storm will arrive tomorrow.','보도에 따르면 내일 폭풍이 온대요.','report','A1','news',1,'newspaper reporter microphone'),
('w_news_A1_03','country','/ˈkʌntri/','noun','나라, 국가','A nation with its own government and territory.','Which {country} is hosting the next World Cup?','다음 월드컵은 어느 나라에서 열려요?','country','A1','news',1,'world map flag nation'),
('w_news_A1_04','people','/ˈpiːpəl/','noun','사람들','A group of human beings in general.','Many {people} are watching the news online now.','이제 많은 사람들이 온라인으로 뉴스를 봐요.','people','A1','news',1,'crowd public gathering community'),
('w_news_A1_05','government','/ˈɡʌvərnmənt/','noun','정부','The group of people who officially lead a country.','The {government} announced a new health plan.','정부가 새로운 보건 계획을 발표했어요.','government','A1','news',1,'parliament building official policy'),
('w_news_A1_06','war','/wɔːr/','noun','전쟁','Armed conflict between nations or groups.','The {war} ended after many years of fighting.','긴 전투 끝에 전쟁이 끝났어요.','war','A1','news',1,'soldier military conflict battlefield'),
('w_news_A1_07','election','/ɪˈlekʃən/','noun','선거','A formal process in which people vote to choose a leader.','The {election} will be held next month.','선거는 다음 달에 열려요.','election','A1','news',1,'ballot voting booth democracy'),
('w_news_A1_08','money','/ˈmʌni/','noun','돈, 자금','A medium of exchange used to buy goods or services.','The government is spending a lot of {money} on hospitals.','정부가 병원에 많은 돈을 쓰고 있어요.','money','A1','news',1,'coins currency economy finance'),
('w_news_A1_09','event','/ɪˈvent/','noun','사건, 행사','A thing that happens, especially one of importance.','This {event} changed the history of the country.','이 사건은 나라의 역사를 바꿨어요.','event','A1','news',1,'newspaper headline breaking news'),
('w_news_A1_10','world','/wɜːrld/','noun','세계','The earth and all the people and things on it.','The {world} is watching what happens next.','세계가 다음에 무슨 일이 일어날지 지켜보고 있어요.','world','A1','news',1,'globe earth international satellite'),
('w_news_A1_11','story','/ˈstɔːri/','noun','기사, 이야기','A news article or broadcast report about an event.','This {story} is on the front page today.','이 기사가 오늘 1면에 실렸어요.','story','A1','news',2,'newspaper front page article'),
('w_news_A1_12','today','/təˈdeɪ/','adverb','오늘','On this present day.','What happened in the news {today}?','오늘 뉴스에서 무슨 일이 있었어요?','today','A1','news',2,'calendar morning daily current'),
('w_news_A1_13','live','/lɪv/','adjective','생방송의','Broadcast at the time of happening, not pre-recorded.','We are watching the speech {live}.','연설을 생방송으로 보고 있어요.','live','A1','news',2,'broadcast television camera live stream'),
('w_news_A1_14','fire','/faɪər/','noun','화재','The rapid burning of something, especially a building.','A big {fire} destroyed the building last night.','어젯밤 큰 화재가 건물을 태웠어요.','fire','A1','news',2,'firefighter flames smoke emergency'),
('w_news_A1_15','police','/pəˈliːs/','noun','경찰','The civil force responsible for law and order.','The {police} arrived at the scene quickly.','경찰이 현장에 빠르게 도착했어요.','police','A1','news',2,'police car siren officer badge'),
('w_news_A1_16','flood','/flʌd/','noun','홍수','An overflow of water onto normally dry land.','The {flood} damaged hundreds of homes.','홍수가 수백 채의 집을 손상시켰어요.','flood','A1','news',2,'flood water disaster rescue'),
('w_news_A1_17','city','/ˈsɪti/','noun','도시','A large and important town.','The {city} held a public meeting about the news.','그 도시는 뉴스에 대한 공개 회의를 열었어요.','city','A1','news',2,'cityscape urban buildings downtown'),
('w_news_A1_18','year','/jɪər/','noun','해, 연도','A period of twelve months.','This has been a historic {year} for the country.','올해는 나라에 역사적인 해였어요.','year','A1','news',2,'calendar timeline annual'),
('w_news_A1_19','help','/help/','verb','돕다','To make it easier for someone to do something.','Volunteers came to {help} after the disaster.','재난 후 자원봉사자들이 도우러 왔어요.','help','A1','news',2,'volunteer aid relief charity'),
('w_news_A1_20','new','/njuː/','adjective','새로운','Not existing before; recently made or discovered.','A {new} law was passed in the parliament.','의회에서 새로운 법이 통과됐어요.','new','A1','news',2,'announcement fresh update policy'),
('w_news_A1_21','true','/truː/','adjective','사실인','In accordance with fact or reality.','Is this news story {true}?','이 뉴스 기사가 사실인가요?','true','A1','news',2,'fact verification truth check'),
('w_news_A1_22','press','/pres/','noun','언론','Newspapers and journalists considered as a group.','The {press} was not allowed at the meeting.','회의에 언론이 허용되지 않았어요.','press','A1','news',2,'journalist camera microphone media'),
('w_news_A1_23','leader','/ˈliːdər/','noun','지도자, 대표','A person who leads a group or country.','The world {leader} spoke at the United Nations.','세계 지도자가 유엔에서 연설했어요.','leader','A1','news',2,'president podium speech flag'),
('w_news_A1_24','army','/ˈɑːrmi/','noun','군대','The military forces of a country.','The {army} was sent to the border.','군대가 국경으로 파견됐어요.','army','A1','news',2,'military soldiers uniform base'),
('w_news_A1_25','attack','/əˈtæk/','noun','공격','A violent action against a person or place.','The {attack} happened in the capital city.','공격은 수도에서 일어났어요.','attack','A1','news',3,'security threat defense emergency'),
('w_news_A1_26','meeting','/ˈmiːtɪŋ/','noun','회의, 회담','A gathering of people for discussion.','The leaders held an emergency {meeting} today.','지도자들이 오늘 긴급 회의를 열었어요.','meeting','A1','news',2,'conference table leaders discussion'),
('w_news_A1_27','food','/fuːd/','noun','식량','Substances eaten to provide energy and nutrition.','Many people do not have enough {food} after the disaster.','재난 후 많은 사람들이 충분한 식량이 없어요.','food','A1','news',2,'aid food relief supply'),
('w_news_A1_28','school','/skuːl/','noun','학교','A place where children are educated.','The government will build more {schools} next year.','정부가 내년에 학교를 더 지을 거예요.','school','A1','news',2,'education children classroom building'),
('w_news_A1_29','hospital','/ˈhɒspɪtəl/','noun','병원','A place where sick or injured people receive medical care.','Three new {hospitals} will open this year.','올해 세 곳의 새 병원이 문을 열어요.','hospital','A1','news',2,'medical care healthcare building'),
('w_news_A1_30','power','/ˈpaʊər/','noun','권력, 전력','The ability to control people or events; also electricity.','The storm cut the {power} for thousands of homes.','폭풍이 수천 채의 집의 전력을 끊었어요.','power','A1','news',2,'electricity grid blackout energy'),
('w_news_A1_31','north','/nɔːrθ/','noun','북쪽, 북부','The direction toward the North Pole; the northern part of a region.','The storm is moving toward the {north}.','폭풍이 북쪽으로 이동하고 있어요.','north','A1','news',3,'compass map direction region'),
('w_news_A1_32','winner','/ˈwɪnər/','noun','승자, 당선자','A person or group that wins an election or competition.','The {winner} of the election was announced this morning.','선거 당선자가 오늘 아침 발표됐어요.','winner','A1','news',2,'election result vote celebrate'),
('w_news_A1_33','dead','/ded/','adjective','사망한','No longer living.','The official said ten people are {dead}.','관리는 열 명이 사망했다고 말했어요.','dead','A1','news',2,'memorial funeral tragedy loss'),
('w_news_A1_34','safe','/seɪf/','adjective','안전한','Protected from danger or risk.','Rescue teams confirmed all passengers are {safe}.','구조대는 모든 승객이 안전하다고 확인했어요.','safe','A1','news',2,'rescue safety relief team'),
('w_news_A1_35','map','/mæp/','noun','지도','A diagram representing the geographic features of an area.','The news showed a {map} of the affected regions.','뉴스에서 피해 지역의 지도를 보여줬어요.','map','A1','news',2,'geography region area borders')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — A2
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_news_A2_01','politics','/ˈpɒlɪtɪks/','noun','정치','Activities associated with governing a country or area.','She is very interested in {politics} and current affairs.','그녀는 정치와 시사에 매우 관심이 있어요.','politics','A2','news',1,'parliament politics debate vote'),
('w_news_A2_02','economy','/ɪˈkɒnəmi/','noun','경제','The system of trade and industry in a country.','The {economy} grew by three percent last year.','경제는 지난해 3% 성장했어요.','economy','A2','news',1,'chart growth finance money'),
('w_news_A2_03','protest','/ˈprəʊtest/','noun','시위','A public demonstration against a policy or action.','Thousands joined the {protest} in the capital.','수천 명이 수도에서 시위에 참가했어요.','protest','A2','news',1,'crowd sign banner street march'),
('w_news_A2_04','vote','/vəʊt/','verb','투표하다','To express a choice in an election or poll.','Citizens went to the polls to {vote} yesterday.','시민들이 어제 투표하러 투표소에 갔어요.','vote','A2','news',1,'ballot box election democracy'),
('w_news_A2_05','president','/ˈprezɪdənt/','noun','대통령','The elected head of a republic.','The {president} gave a speech about national security.','대통령이 국가 안보에 대한 연설을 했어요.','president','A2','news',1,'flag podium speech official'),
('w_news_A2_06','law','/lɔː/','noun','법률','A rule made by a government that must be obeyed.','A new {law} banning single-use plastics was passed.','일회용 플라스틱을 금지하는 새 법이 통과됐어요.','law','A2','news',1,'gavel justice legal court'),
('w_news_A2_07','crime','/kraɪm/','noun','범죄','An illegal act that can be punished by law.','The government promised to reduce {crime} in cities.','정부는 도시 범죄를 줄이겠다고 약속했어요.','crime','A2','news',1,'police handcuffs justice court'),
('w_news_A2_08','health','/helθ/','noun','건강, 보건','The state of physical and mental well-being.','The ministry of {health} released new guidelines.','보건부가 새 지침을 발표했어요.','health','A2','news',1,'hospital medical healthcare policy'),
('w_news_A2_09','disaster','/dɪˈzɑːstər/','noun','재난','A sudden event causing great damage or suffering.','International aid arrived after the natural {disaster}.','자연재난 이후 국제 원조가 도착했어요.','disaster','A2','news',1,'earthquake flood rescue emergency'),
('w_news_A2_10','international','/ˌɪntəˈnæʃənəl/','adjective','국제적인','Involving two or more countries.','The summit attracted {international} media coverage.','정상 회담은 국제 언론의 주목을 받았어요.','international','A2','news',1,'globe flag summit diplomacy'),
('w_news_A2_11','minister','/ˈmɪnɪstər/','noun','장관','A senior government official in charge of a department.','The finance {minister} announced a new budget plan.','재무 장관이 새로운 예산안을 발표했어요.','minister','A2','news',1,'government official suit briefing'),
('w_news_A2_12','agreement','/əˈɡriːmənt/','noun','합의, 협정','A negotiated arrangement between parties.','The two countries signed a trade {agreement}.','두 나라가 무역 협정에 서명했어요.','agreement','A2','news',1,'handshake signing document treaty'),
('w_news_A2_13','border','/ˈbɔːrdər/','noun','국경','A line dividing two countries or regions.','Thousands of refugees are waiting at the {border}.','수천 명의 난민이 국경에서 기다리고 있어요.','border','A2','news',2,'fence gate border checkpoint'),
('w_news_A2_14','refugee','/ˌrefjʊˈdʒiː/','noun','난민','A person who has fled their home country due to danger.','The UN is helping {refugees} find safe shelter.','유엔이 난민들이 안전한 피난처를 찾도록 돕고 있어요.','refugees','A2','news',2,'camp shelter aid UN'),
('w_news_A2_15','statement','/ˈsteɪtmənt/','noun','성명','A formal declaration made by an official or organization.','The president released a {statement} on the crisis.','대통령이 위기에 대한 성명을 발표했어요.','statement','A2','news',2,'press conference podium microphone'),
('w_news_A2_16','announce','/əˈnaʊns/','verb','발표하다','To make a public declaration about something.','The prime minister will {announce} new measures today.','총리가 오늘 새로운 조치를 발표할 거예요.','announce','A2','news',2,'microphone podium press briefing'),
('w_news_A2_17','tax','/tæks/','noun','세금','A compulsory payment to the government.','The new budget will raise income {tax}.','새 예산은 소득세를 올릴 거예요.','tax','A2','news',2,'money finance government revenue'),
('w_news_A2_18','trade','/treɪd/','noun','무역','The buying and selling of goods between countries.','The new deal will boost {trade} between the two nations.','새 협정이 두 나라 사이의 무역을 촉진할 거예요.','trade','A2','news',2,'cargo ship port exchange'),
('w_news_A2_19','climate','/ˈklaɪmɪt/','noun','기후','The weather conditions of a region over a long period.','World leaders discussed {climate} change at the summit.','세계 지도자들이 정상 회담에서 기후 변화를 논의했어요.','climate','A2','news',2,'environment earth green energy'),
('w_news_A2_20','victim','/ˈvɪktɪm/','noun','피해자, 희생자','A person who suffers as a result of an event.','Aid organizations are helping the {victims} of the flood.','구호 단체들이 홍수 피해자들을 돕고 있어요.','victims','A2','news',2,'rescue aid relief flood'),
('w_news_A2_21','judge','/dʒʌdʒ/','noun','판사','An official who decides cases in a court of law.','The {judge} sentenced the man to five years in prison.','판사가 그 남자에게 5년 징역형을 선고했어요.','judge','A2','news',2,'court gavel justice legal'),
('w_news_A2_22','survey','/ˈsɜːrveɪ/','noun','여론 조사','A study of people''s opinions on a particular topic.','A recent {survey} shows most people support the new law.','최근 여론 조사에 따르면 대부분의 사람들이 새 법을 지지해요.','survey','A2','news',2,'poll data chart statistics'),
('w_news_A2_23','official','/əˈfɪʃəl/','noun','관리, 공무원','A person holding a position of authority in an organization.','A government {official} confirmed the news.','정부 관리가 소식을 확인해 줬어요.','official','A2','news',2,'suit badge authority government'),
('w_news_A2_24','peace','/piːs/','noun','평화','A state of freedom from war or conflict.','Both sides agreed to work toward {peace}.','양측이 평화를 향해 노력하기로 합의했어요.','peace','A2','news',1,'dove hands flag diplomacy'),
('w_news_A2_25','poverty','/ˈpɒvərti/','noun','빈곤','The state of being extremely poor.','The new policy aims to reduce {poverty} in rural areas.','새 정책은 농촌 지역의 빈곤을 줄이는 것을 목표로 해요.','poverty','A2','news',2,'village aid development charity'),
('w_news_A2_26','media','/ˈmiːdiə/','noun','미디어, 언론','Television, radio, newspapers, and the internet as a group.','The {media} reported on the scandal all week.','미디어가 일주일 내내 스캔들을 보도했어요.','media','A2','news',2,'television newspaper internet broadcast'),
('w_news_A2_27','population','/ˌpɒpjʊˈleɪʃən/','noun','인구','All the people living in a particular country or area.','The {population} of the city grew by five percent.','그 도시 인구가 5% 증가했어요.','population','A2','news',2,'crowd city demographic growth'),
('w_news_A2_28','education','/ˌedʒʊˈkeɪʃən/','noun','교육','The process of teaching and learning in a society.','The government will invest more in {education} this year.','정부가 올해 교육에 더 많이 투자할 거예요.','education','A2','news',2,'school books children classroom'),
('w_news_A2_29','security','/sɪˈkjʊərɪti/','noun','보안, 안보','The state of being free from danger or threat.','The summit required tight {security} measures.','정상 회담에는 엄격한 보안 조치가 필요했어요.','security','A2','news',2,'guard gate camera safety'),
('w_news_A2_30','injury','/ˈɪndʒəri/','noun','부상','Physical harm or damage to a person''s body.','The report confirmed twelve {injuries} in the accident.','보도는 사고에서 12명의 부상을 확인했어요.','injuries','A2','news',2,'ambulance hospital medical emergency'),
('w_news_A2_31','crisis','/ˈkraɪsɪs/','noun','위기','A time of intense difficulty or danger.','The government is responding to the economic {crisis}.','정부가 경제 위기에 대응하고 있어요.','crisis','A2','news',1,'alarm emergency red alert warning'),
('w_news_A2_32','army','/ˈɑːrmi/','noun','군대','The land-based armed forces of a country.','The {army} was deployed to control the situation.','군대가 상황을 통제하기 위해 배치됐어요.','army','A2','news',2,'military soldiers uniform patrol'),
('w_news_A2_33','protest','/prəˈtest/','verb','항의하다','To express strong objection to something publicly.','Students {protested} outside the parliament building.','학생들이 의회 건물 밖에서 항의했어요.','protested','A2','news',2,'rally sign banner street'),
('w_news_A2_34','prime','/praɪm/','adjective','주요한, 최고의','Of first importance; most excellent.','The {prime} minister addressed the nation on television.','총리가 텔레비전으로 국민에게 연설했어요.','prime','A2','news',1,'parliament speech podium flag'),
('w_news_A2_35','budget','/ˈbʌdʒɪt/','noun','예산','An estimate of income and expenditure for a set period.','The government presented its annual {budget} today.','정부가 오늘 연간 예산을 발표했어요.','budget','A2','news',1,'finance money chart government')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — B1
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_news_B1_01','policy','/ˈpɒlɪsi/','noun','정책','A course of action adopted by a government or organization.','The new energy {policy} will reduce carbon emissions.','새 에너지 정책이 탄소 배출을 줄일 거예요.','policy','B1','news',1,'document government plan strategy'),
('w_news_B1_02','reform','/rɪˈfɔːrm/','noun','개혁','A change made to improve a system or institution.','The party is pushing for major economic {reforms}.','그 정당은 주요 경제 개혁을 추진하고 있어요.','reforms','B1','news',1,'parliament chart change progress'),
('w_news_B1_03','parliament','/ˈpɑːrləmənt/','noun','의회','The group of elected representatives who make the laws.','The bill passed through {parliament} with a large majority.','그 법안은 큰 다수결로 의회를 통과했어요.','parliament','B1','news',1,'legislative building democracy vote'),
('w_news_B1_04','controversy','/ˈkɒntrəvɜːrsi/','noun','논란','Prolonged public disagreement or heated debate.','The decision sparked {controversy} across the country.','그 결정은 전국적으로 논란을 일으켰어요.','controversy','B1','news',2,'debate protest media opinion'),
('w_news_B1_05','scandal','/ˈskændəl/','noun','스캔들, 추문','An action or event causing public outrage or shock.','The financial {scandal} forced the minister to resign.','금융 스캔들로 장관이 사임해야 했어요.','scandal','B1','news',2,'headlines media expose tabloid'),
('w_news_B1_06','minister','/ˈmɪnɪstər/','noun','장관','A member of the cabinet in charge of a government department.','The defense {minister} briefed the parliament on the threat.','국방 장관이 의회에 위협에 대해 브리핑했어요.','minister','B1','news',1,'suit official parliament policy'),
('w_news_B1_07','legislation','/ˌledʒɪˈsleɪʃən/','noun','입법, 법률','Laws that have been enacted by a legislature.','New {legislation} on data privacy was introduced this week.','이번 주 데이터 프라이버시에 관한 새 입법이 도입됐어요.','legislation','B1','news',1,'law book parliament document'),
('w_news_B1_08','opposition','/ˌɒpəˈzɪʃən/','noun','야당, 반대 세력','The political parties that are not in government.','The {opposition} called for an independent inquiry.','야당이 독립 조사를 요구했어요.','opposition','B1','news',2,'parliament debate politics dissent'),
('w_news_B1_09','coalition','/ˌkəʊəˈlɪʃən/','noun','연립 정부','A temporary union of political parties to form a government.','The two parties formed a {coalition} government.','두 정당이 연립 정부를 구성했어요.','coalition','B1','news',2,'handshake agreement politics alliance'),
('w_news_B1_10','bilateral','/ˌbaɪˈlætərəl/','adjective','양자 간의','Involving two parties, especially two countries.','The presidents met for {bilateral} trade talks.','대통령들이 양자 무역 회담을 위해 만났어요.','bilateral','B1','news',2,'flags handshake diplomacy summit'),
('w_news_B1_11','inquiry','/ɪnˈkwaɪəri/','noun','조사, 심의','An official investigation into something.','A public {inquiry} was opened into the accident.','사고에 대한 공개 조사가 시작됐어요.','inquiry','B1','news',2,'investigation report judge committee'),
('w_news_B1_12','campaign','/kæmˈpeɪn/','noun','선거 운동, 캠페인','A series of planned activities to achieve a particular goal.','She launched a {campaign} to raise awareness of poverty.','그녀는 빈곤 인식 제고를 위한 캠페인을 시작했어요.','campaign','B1','news',2,'poster rally vote awareness'),
('w_news_B1_13','resign','/rɪˈzaɪn/','verb','사임하다','To officially leave a job or position.','The minister was forced to {resign} over the scandal.','장관은 스캔들로 인해 사임해야 했어요.','resign','B1','news',2,'press conference exit politics'),
('w_news_B1_14','corruption','/kəˈrʌpʃən/','noun','부패','Dishonest or illegal behavior, especially by those in power.','The investigation exposed widespread {corruption} in the ministry.','조사는 부처 내 광범위한 부패를 드러냈어요.','corruption','B1','news',2,'money briefcase bribe illegal'),
('w_news_B1_15','inflation','/ɪnˈfleɪʃən/','noun','인플레이션','A general increase in prices over time.','High {inflation} is making everyday goods more expensive.','높은 인플레이션이 일상 용품을 더 비싸게 만들고 있어요.','inflation','B1','news',2,'price chart rising cost money'),
('w_news_B1_16','treaty','/ˈtriːti/','noun','조약','A formal agreement between countries.','The two nations signed a historic peace {treaty}.','두 나라가 역사적인 평화 조약에 서명했어요.','treaty','B1','news',2,'document signing ceremony flag'),
('w_news_B1_17','ceasefire','/ˈsiːsfaɪər/','noun','휴전','A temporary stop of fighting, agreed between warring sides.','Both sides agreed to a {ceasefire} starting at midnight.','양측이 자정부터 시작하는 휴전에 합의했어요.','ceasefire','B1','news',2,'soldiers white flag peace calm'),
('w_news_B1_18','summit','/ˈsʌmɪt/','noun','정상 회담','A meeting between the leaders of two or more countries.','The G7 {summit} will address climate change this year.','G7 정상 회담이 올해 기후 변화를 다룰 거예요.','summit','B1','news',2,'leaders flags conference table'),
('w_news_B1_19','sanction','/ˈsæŋkʃən/','noun','제재','A penalty or restriction imposed against a country or entity.','New economic {sanctions} were imposed on the regime.','그 정권에 새로운 경제 제재가 부과됐어요.','sanctions','B1','news',2,'trade restriction penalty embargo'),
('w_news_B1_20','humanitarian','/hjuːˌmænɪˈteəriən/','adjective','인도주의적','Concerned with or seeking to promote human welfare.','The UN called for {humanitarian} aid to be allowed in.','유엔은 인도주의적 지원이 허용되어야 한다고 촉구했어요.','humanitarian','B1','news',2,'aid relief UN charity'),
('w_news_B1_21','infrastructure','/ˈɪnfrəstrʌktʃər/','noun','사회 기반 시설','The basic physical systems of a country or region.','The government plans to invest in {infrastructure} projects.','정부가 사회 기반 시설 프로젝트에 투자할 계획이에요.','infrastructure','B1','news',2,'bridge road construction building'),
('w_news_B1_22','negotiation','/nɪˌɡəʊʃiˈeɪʃən/','noun','협상','Discussion aimed at reaching an agreement.','Peace {negotiations} are expected to resume next week.','평화 협상이 다음 주에 재개될 것으로 예상돼요.','negotiations','B1','news',2,'table diplomacy handshake talk'),
('w_news_B1_23','demonstrate','/ˈdemənstreɪt/','verb','시위하다','To publicly protest or show support for a cause.','Thousands {demonstrated} against the new tax policy.','수천 명이 새 세금 정책에 반대하여 시위했어요.','demonstrated','B1','news',2,'march banner protest crowd'),
('w_news_B1_24','unemployment','/ˌʌnɪmˈplɔɪmənt/','noun','실업','The condition of being without a paid job.','The latest figures show {unemployment} has risen to 8%.','최신 수치에 따르면 실업률이 8%로 올랐어요.','unemployment','B1','news',2,'job center queue line economy'),
('w_news_B1_25','verdict','/ˈvɜːrdɪkt/','noun','평결, 판결','A decision reached by a jury or judge in a legal trial.','The court delivered its {verdict} this morning.','법원이 오늘 아침 판결을 내렸어요.','verdict','B1','news',2,'courtroom gavel judge jury'),
('w_news_B1_26','press conference','/pres ˈkɒnfərəns/','noun','기자 회견','A meeting at which an official speaks to journalists.','The prime minister held a {press conference} after the vote.','총리가 투표 후 기자 회견을 열었어요.','press conference','B1','news',2,'microphone journalist podium camera'),
('w_news_B1_27','majority','/məˈdʒɒrɪti/','noun','과반수, 다수','The greater number or part of something.','The bill passed with a narrow {majority} in parliament.','그 법안은 의회에서 간신히 과반수로 통과됐어요.','majority','B1','news',2,'vote election graph result'),
('w_news_B1_28','accusation','/ˌækjʊˈzeɪʃən/','noun','고발, 혐의','A claim that someone has done something wrong or illegal.','He denied all {accusations} of wrongdoing.','그는 모든 비리 혐의를 부인했어요.','accusations','B1','news',2,'court legal press denial'),
('w_news_B1_29','turnout','/ˈtɜːrnaʊt/','noun','투표율, 참여율','The number of people attending or participating in an event.','Voter {turnout} reached a record high this election.','이번 선거에서 투표율이 역대 최고를 기록했어요.','turnout','B1','news',2,'ballot box queue voters'),
('w_news_B1_30','impose','/ɪmˈpəʊz/','verb','부과하다','To establish a rule, tax, or restriction by authority.','The government will {impose} stricter penalties for tax evasion.','정부가 탈세에 더 엄격한 처벌을 부과할 거예요.','impose','B1','news',2,'authority law gavel penalty'),
('w_news_B1_31','ally','/ˈælaɪ/','noun','동맹국','A country formally cooperating with another for a common goal.','The US called on its {allies} to support the resolution.','미국이 결의안을 지지해 달라고 동맹국들에 촉구했어요.','allies','B1','news',2,'flags alliance partnership military'),
('w_news_B1_32','evidence','/ˈevɪdəns/','noun','증거','Facts or information showing whether something is true.','The court examined new {evidence} in the case.','법원이 사건에서 새로운 증거를 검토했어요.','evidence','B1','news',2,'courtroom document investigation files'),
('w_news_B1_33','democracy','/dɪˈmɒkrəsi/','noun','민주주의','A system of government in which people vote for their leaders.','Protecting {democracy} requires active citizen participation.','민주주의를 보호하려면 시민의 적극적인 참여가 필요해요.','democracy','B1','news',1,'ballot box flag parliament constitution'),
('w_news_B1_34','refugee','/ˌrefjʊˈdʒiː/','noun','난민','A person forced to flee their country due to conflict or disaster.','The crisis has created over a million {refugees}.','위기로 인해 백만 명 이상의 난민이 생겼어요.','refugees','B1','news',2,'camp tent border UNHCR'),
('w_news_B1_35','deadline','/ˈdedlaɪn/','noun','시한, 기한','A point in time by which something must be done.','The government missed the {deadline} for submitting the budget.','정부가 예산 제출 시한을 놓쳤어요.','deadline','B1','news',2,'clock calendar urgent time')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — B2
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_news_B2_01','geopolitics','/ˌdʒiːəʊˈpɒlɪtɪks/','noun','지정학','The study of how geography and power shape world affairs.','{Geopolitics} in East Asia has shifted significantly this decade.','이번 십 년간 동아시아 지정학이 크게 변했어요.','Geopolitics','B2','news',1,'map region power rivalry strategy'),
('w_news_B2_02','sanctions','/ˈsæŋkʃənz/','noun','제재 조치','Economic or political penalties imposed by one country on another.','The UN imposed sweeping {sanctions} on the regime.','유엔이 그 정권에 광범위한 제재를 부과했어요.','sanctions','B2','news',1,'trade restriction penalty embargo'),
('w_news_B2_03','diplomatic','/ˌdɪpləˈmætɪk/','adjective','외교적인','Relating to the management of international relations.','Both governments agreed to resume {diplomatic} ties.','두 정부가 외교 관계를 재개하기로 합의했어요.','diplomatic','B2','news',1,'embassy flag handshake diplomat'),
('w_news_B2_04','incumbent','/ɪnˈkʌmbənt/','adjective','현직의','Currently holding a particular office or position.','The {incumbent} president won re-election by a wide margin.','현직 대통령이 큰 차이로 재선에 성공했어요.','incumbent','B2','news',2,'election result president podium'),
('w_news_B2_05','sovereignty','/ˈsɒvrɪnti/','noun','주권','The full right and power of a country to govern itself.','The treaty was seen as a threat to national {sovereignty}.','그 조약은 국가 주권에 대한 위협으로 여겨졌어요.','sovereignty','B2','news',2,'flag border constitution nation'),
('w_news_B2_06','multilateral','/ˌmʌltiˈlætərəl/','adjective','다자간의','Involving three or more parties, especially countries.','A {multilateral} approach is needed to solve the climate crisis.','기후 위기를 해결하려면 다자간 접근이 필요해요.','multilateral','B2','news',2,'UN globe summit delegates'),
('w_news_B2_07','referendum','/ˌrefəˈrendəm/','noun','국민 투표','A direct vote by the electorate on a single political question.','Citizens voted in a {referendum} on independence.','시민들이 독립에 관한 국민 투표에 참여했어요.','referendum','B2','news',2,'ballot box vote democracy flag'),
('w_news_B2_08','austerity','/ɒˈsterɪti/','noun','긴축 재정','Difficult economic conditions created by government spending cuts.','The {austerity} measures triggered widespread protests.','긴축 조치가 광범위한 시위를 촉발했어요.','austerity','B2','news',2,'budget cuts economy protest'),
('w_news_B2_09','coup','/kuː/','noun','쿠데타','A sudden, violent seizure of power from a government.','The military staged a {coup} in the early hours of the morning.','군이 이른 아침에 쿠데타를 일으켰어요.','coup','B2','news',2,'military tanks government overthrow'),
('w_news_B2_10','insurgency','/ɪnˈsɜːrdʒənsi/','noun','반란','An active revolt or uprising against an authority or government.','The army is battling a long-running {insurgency} in the north.','군은 북부에서 오래 지속된 반란과 싸우고 있어요.','insurgency','B2','news',3,'soldiers jungle conflict militia'),
('w_news_B2_11','accountability','/əˌkaʊntəˈbɪlɪti/','noun','책임 (제도적)','The fact of being held responsible for one''s actions or decisions.','There is growing demand for political {accountability}.','정치적 책임에 대한 요구가 높아지고 있어요.','accountability','B2','news',2,'audit investigation report committee'),
('w_news_B2_12','populism','/ˈpɒpjʊlɪzəm/','noun','포퓰리즘','A political approach that appeals to ordinary people''s concerns against elites.','The rise of {populism} has reshaped politics in many countries.','포퓰리즘의 부상이 많은 나라의 정치를 바꿔놓았어요.','populism','B2','news',2,'rally crowd speech election'),
('w_news_B2_13','authoritarian','/ɔːˌθɒrɪˈteəriən/','adjective','권위주의적인','Favoring or enforcing strict obedience to authority.','Critics say the new laws are {authoritarian} in nature.','비평가들은 새 법이 권위주의적 성격이라고 말해요.','authoritarian','B2','news',2,'control surveillance power state'),
('w_news_B2_14','propaganda','/ˌprɒpəˈɡændə/','noun','선전','Information spread to promote a particular political agenda.','The report accused the government of spreading {propaganda}.','그 보도는 정부가 선전을 퍼뜨리고 있다고 비난했어요.','propaganda','B2','news',2,'poster media broadcast bias'),
('w_news_B2_15','disinformation','/dɪsˌɪnfəˈmeɪʃən/','noun','허위 정보','False information spread deliberately to deceive people.','Social media has become a major source of {disinformation}.','소셜 미디어가 허위 정보의 주요 출처가 됐어요.','disinformation','B2','news',2,'fake news screen social media'),
('w_news_B2_16','embargo','/ɪmˈbɑːrɡəʊ/','noun','금수 조치','An official ban on trade with a particular country.','An arms {embargo} was placed on the country by the UN.','유엔이 그 나라에 무기 금수 조치를 부과했어요.','embargo','B2','news',2,'trade ban cargo ship restriction'),
('w_news_B2_17','mediation','/ˌmiːdiˈeɪʃən/','noun','조정, 중재','Intervention in a dispute to bring about a settlement.','International {mediation} helped end the conflict.','국제 조정이 분쟁 종식에 도움이 됐어요.','mediation','B2','news',2,'diplomacy negotiation peace table'),
('w_news_B2_18','polarization','/ˌpəʊlərɪˈzeɪʃən/','noun','양극화','The division of something into two sharply contrasting groups.','Political {polarization} has deepened in recent years.','최근 몇 년간 정치적 양극화가 심화됐어요.','polarization','B2','news',2,'divide society left right politics'),
('w_news_B2_19','narrative','/ˈnærətɪv/','noun','서사, 담론','A story or explanation that shapes how people understand events.','Both sides tried to control the public {narrative}.','양측이 공적 담론을 통제하려고 했어요.','narrative','B2','news',2,'media story framing perspective'),
('w_news_B2_20','transparency','/trænsˈpærənsi/','noun','투명성','The quality of being open and not concealing information.','Citizens are demanding greater {transparency} in government.','시민들이 정부의 더 큰 투명성을 요구하고 있어요.','transparency','B2','news',2,'glass open document accountability'),
('w_news_B2_21','allegation','/ˌælɪˈɡeɪʃən/','noun','혐의, 주장','A claim that someone has done something wrong or illegal.','The minister denied all {allegations} of corruption.','장관은 모든 부패 혐의를 부인했어요.','allegations','B2','news',2,'court legal press accusation'),
('w_news_B2_22','ratification','/ˌrætɪfɪˈkeɪʃən/','noun','비준','The official confirmation or approval of a treaty or agreement.','The treaty awaits {ratification} by all member states.','조약은 모든 회원국의 비준을 기다리고 있어요.','ratification','B2','news',2,'signing document ceremony flag'),
('w_news_B2_23','veto','/ˈviːtəʊ/','noun','거부권','The right to reject a decision or proposal unilaterally.','Russia used its {veto} power to block the UN resolution.','러시아가 거부권을 사용해 유엔 결의안을 막았어요.','veto','B2','news',2,'UN Security Council vote power'),
('w_news_B2_24','credibility','/ˌkredɪˈbɪlɪti/','noun','신뢰성','The quality of being trusted and believed by others.','The scandal damaged the government''s {credibility}.','스캔들이 정부의 신뢰성을 훼손했어요.','credibility','B2','news',2,'trust press opinion poll'),
('w_news_B2_25','mandate','/ˈmændeɪt/','noun','권한 위임, 임무','An official order or authorization given to a party by voters.','The new leader claimed a strong {mandate} from voters.','새 지도자는 유권자들로부터 강력한 권한을 받았다고 주장했어요.','mandate','B2','news',2,'election result vote authority'),
('w_news_B2_26','dissent','/dɪˈsent/','noun','반대 의견','The holding or expression of opinions contrary to authority.','Political {dissent} is suppressed in authoritarian states.','권위주의 국가에서 정치적 반대 의견은 탄압돼요.','dissent','B2','news',2,'protest speech freedom opposition'),
('w_news_B2_27','broker','/ˈbrəʊkər/','verb','중재하다','To arrange or negotiate an agreement between parties.','The US agreed to {broker} a peace deal between the two nations.','미국이 두 나라 간의 평화 협상을 중재하기로 했어요.','broker','B2','news',2,'diplomacy negotiation mediation handshake'),
('w_news_B2_28','consensus','/kənˈsensəs/','noun','합의, 컨센서스','General agreement among a group of people or states.','There is growing {consensus} on the need for climate action.','기후 행동의 필요성에 대한 공감대가 커지고 있어요.','consensus','B2','news',2,'agreement UN summit delegates'),
('w_news_B2_29','intervention','/ˌɪntəˈvenʃən/','noun','개입','The act of becoming involved in a situation to alter its course.','Military {intervention} was debated at the UN Security Council.','유엔 안보리에서 군사적 개입이 논의됐어요.','intervention','B2','news',2,'UN military peacekeeping security'),
('w_news_B2_30','impasse','/ˈɪmpæs/','noun','교착 상태','A situation in which no progress is possible; deadlock.','Negotiations reached an {impasse} after three days of talks.','3일간의 회담 끝에 협상이 교착 상태에 빠졌어요.','impasse','B2','news',2,'deadlock negotiation stalled diplomacy'),
('w_news_B2_31','annexation','/ˌænɪkˈseɪʃən/','noun','합병, 병합','The action of taking over a territory by a country.','The international community condemned the {annexation} of the territory.','국제 사회가 그 영토 합병을 규탄했어요.','annexation','B2','news',3,'border map territory flag'),
('w_news_B2_32','faction','/ˈfækʃən/','noun','파벌','A small, dissenting group within a larger political party.','A rebel {faction} within the party opposed the leader''s plans.','당 내 반대 파벌이 지도자의 계획에 반대했어요.','faction','B2','news',3,'politics party divide group'),
('w_news_B2_33','cease','/siːs/','verb','중단하다','To come to an end or bring something to an end.','Fighting must {cease} immediately, the UN demanded.','유엔은 전투가 즉각 중단되어야 한다고 요구했어요.','cease','B2','news',2,'stop end peacekeeping soldiers'),
('w_news_B2_34','denounce','/dɪˈnaʊns/','verb','규탄하다','To publicly declare something to be wrong or evil.','The opposition {denounced} the new law as unconstitutional.','야당은 새 법을 위헌이라고 규탄했어요.','denounced','B2','news',2,'protest speech condemnation press'),
('w_news_B2_35','coalition','/ˌkəʊəˈlɪʃən/','noun','연합, 연립','A temporary alliance of distinct political parties or groups.','A {coalition} of opposition parties challenged the government.','야당 연합이 정부에 도전했어요.','coalition','B2','news',2,'alliance partnership politics flag')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — C1
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_news_C1_01','hegemony','/hɪˈdʒeməni/','noun','패권','Leadership or dominance, especially of one country over others.','American {hegemony} in the post-Cold War era is being challenged.','냉전 이후 미국 패권이 도전받고 있어요.','hegemony','C1','news',1,'power globe superpower dominance'),
('w_news_C1_02','realpolitik','/reɪˈɑːlpɒlɪtɪk/','noun','현실 정치','Politics based on practical considerations rather than moral norms.','The decision to ally with the regime reflected pure {realpolitik}.','그 정권과의 동맹 결정은 순수한 현실 정치를 반영했어요.','realpolitik','C1','news',2,'strategy power diplomacy chess'),
('w_news_C1_03','extraterritorial','/ˌekstrəˌterɪˈtɔːriəl/','adjective','역외적인','Existing or taking effect outside the territory of a state.','The law has {extraterritorial} jurisdiction over its citizens abroad.','그 법은 해외 자국 시민에 대한 역외 관할권을 가지고 있어요.','extraterritorial','C1','news',3,'law border international jurisdiction'),
('w_news_C1_04','jurisprudence','/ˌdʒʊərɪsˈpruːdəns/','noun','법리학','The theory and practice of law; a body of legal decisions.','The ruling set a new precedent in international {jurisprudence}.','그 판결은 국제 법리학에 새로운 선례를 세웠어요.','jurisprudence','C1','news',2,'law books court legal theory'),
('w_news_C1_05','multilateralism','/ˌmʌltiˈlætərəlɪzəm/','noun','다자주의','The practice of diplomacy involving multiple countries.','The summit reaffirmed a commitment to {multilateralism}.','정상 회담은 다자주의에 대한 의지를 재확인했어요.','multilateralism','C1','news',2,'UN globe summit cooperation'),
('w_news_C1_06','precedent','/ˈpresɪdənt/','noun','선례','An earlier event or ruling used as an example for later situations.','The court''s decision set a dangerous {precedent} for press freedom.','법원의 결정은 언론 자유에 위험한 선례를 남겼어요.','precedent','C1','news',2,'court legal history ruling'),
('w_news_C1_07','jurisdiction','/ˌdʒʊərɪsˈdɪkʃən/','noun','관할권','The official power to make legal decisions in a given area.','The crime falls outside this court''s {jurisdiction}.','그 범죄는 이 법원의 관할권 밖이에요.','jurisdiction','C1','news',2,'court law territory authority'),
('w_news_C1_08','ratification','/ˌrætɪfɪˈkeɪʃən/','noun','비준','Formal confirmation or approval of an international agreement.','The climate accord requires {ratification} by 55 countries.','그 기후 협약은 55개국의 비준이 필요해요.','ratification','C1','news',2,'treaty signing ceremony document'),
('w_news_C1_09','embargo','/ɪmˈbɑːrɡəʊ/','noun','수출입 금지령','An official ban on trade or other commercial activity with a country.','The oil {embargo} crippled the nation''s economy.','석유 금수 조치가 국가 경제를 무력화했어요.','embargo','C1','news',2,'trade ban ship cargo oil'),
('w_news_C1_10','deterrence','/dɪˈterəns/','noun','억제력','The action of discouraging an action through fear of consequences.','Nuclear {deterrence} has prevented major wars for decades.','핵 억제력은 수십 년 동안 대규모 전쟁을 막아왔어요.','deterrence','C1','news',2,'nuclear missile defense shield'),
('w_news_C1_11','geopolitical','/ˌdʒiːəʊpəˈlɪtɪkəl/','adjective','지정학적','Relating to politics affected by geographical factors.','The pipeline holds enormous {geopolitical} significance.','그 파이프라인은 엄청난 지정학적 의미를 가지고 있어요.','geopolitical','C1','news',2,'map energy pipeline power'),
('w_news_C1_12','bellicose','/ˈbelɪkəʊs/','adjective','호전적인','Demonstrating aggression and willingness to fight.','The government''s {bellicose} rhetoric alarmed its neighbors.','정부의 호전적인 수사가 이웃 나라들을 불안하게 했어요.','bellicose','C1','news',3,'military threat tension hostility'),
('w_news_C1_13','oligarchy','/ˈɒlɪɡɑːki/','noun','과두 정치','A system in which power is held by a small number of people.','Critics accuse the ruling elite of establishing an {oligarchy}.','비평가들은 집권 엘리트가 과두 정치를 수립했다고 비난해요.','oligarchy','C1','news',2,'power elite wealth control'),
('w_news_C1_14','reprisal','/rɪˈpraɪzəl/','noun','보복 행위','An act of retaliation against an enemy or opponent.','The strike was carried out in {reprisal} for the earlier attack.','그 공격은 이전 공격에 대한 보복으로 감행됐어요.','reprisal','C1','news',3,'retaliation military response strike'),
('w_news_C1_15','subversion','/səbˈvɜːrʒən/','noun','전복, 체제 해체','The undermining of the power and authority of an established system.','He was charged with {subversion} of the state.','그는 국가 전복 혐의로 기소됐어요.','subversion','C1','news',3,'underground threat security law'),
('w_news_C1_16','proxy','/ˈprɒksi/','noun','대리인, 위임','A person or group acting on behalf of another, especially in conflict.','The two superpowers fought a {proxy} war through local factions.','두 강대국이 지역 파벌을 통해 대리전을 치렀어요.','proxy','C1','news',2,'war factions superpower conflict'),
('w_news_C1_17','ostracize','/ˈɒstrəsaɪz/','verb','추방하다, 따돌리다','To exclude someone from a society or community by consensus.','The regime was {ostracized} by the international community.','그 정권은 국제 사회에서 추방당했어요.','ostracized','C1','news',2,'isolation exclusion sanctions community'),
('w_news_C1_18','proliferation','/prəˌlɪfəˈreɪʃən/','noun','확산','A rapid increase in the number of something, especially weapons.','Nuclear {proliferation} remains one of the world''s gravest threats.','핵 확산은 여전히 세계에서 가장 심각한 위협 중 하나예요.','proliferation','C1','news',2,'nuclear weapons spread global'),
('w_news_C1_19','junta','/ˈhʊntə/','noun','군사 정권','A military group that has seized power following a coup.','The military {junta} suspended the constitution.','군사 정권이 헌법을 정지시켰어요.','junta','C1','news',2,'military coup power governance'),
('w_news_C1_20','disenfranchise','/ˌdɪsɪnˈfræntʃaɪz/','verb','선거권을 박탈하다','To deprive someone of the right to vote or participate.','Critics say the new law will {disenfranchise} millions of voters.','비평가들은 새 법이 수백만 명의 유권자의 선거권을 박탈할 것이라고 말해요.','disenfranchise','C1','news',2,'vote election rights democracy'),
('w_news_C1_21','tribunal','/traɪˈbjuːnəl/','noun','재판소, 심판소','A court or committee appointed to deal with a specific issue.','The war crimes {tribunal} handed down its verdict.','전쟁 범죄 재판소가 판결을 내렸어요.','tribunal','C1','news',2,'court justice international legal'),
('w_news_C1_22','culpability','/ˌkʌlpəˈbɪlɪti/','noun','유책성','Responsibility for a fault or wrong; blameworthiness.','The inquiry examined the {culpability} of senior officials.','조사는 고위 관리들의 유책성을 검토했어요.','culpability','C1','news',3,'responsibility blame inquiry legal'),
('w_news_C1_23','capitulation','/kəˌpɪtʃʊˈleɪʃən/','noun','항복, 굴복','The act of surrendering or giving in to demands or pressure.','Critics called the government''s response a {capitulation} to pressure.','비평가들은 정부의 반응을 압력에 대한 굴복이라고 불렀어요.','capitulation','C1','news',3,'surrender defeat compromise pressure'),
('w_news_C1_24','reparation','/ˌrepəˈreɪʃən/','noun','배상','Compensation for war damage paid by a defeated country.','The debate over war {reparations} resurfaced this year.','올해 전쟁 배상금 논쟁이 다시 불거졌어요.','reparations','C1','news',2,'history war justice compensation'),
('w_news_C1_25','acquittal','/əˈkwɪtəl/','noun','무죄 선고','A formal judicial finding of not guilty.','The {acquittal} shocked the victims'' families.','무죄 선고는 피해자 가족들에게 충격을 줬어요.','acquittal','C1','news',2,'court verdict judge jury not guilty'),
('w_news_C1_26','complicity','/kəmˈplɪsɪti/','noun','공모, 연루','Partnership in a wrongdoing or crime; being involved in guilt.','The report alleged government {complicity} in the cover-up.','보고서는 정부의 은폐 공모를 주장했어요.','complicity','C1','news',2,'corruption crime involvement investigation'),
('w_news_C1_27','rapprochement','/ˌræprəʊʃˈmɒŋ/','noun','화해, 관계 개선','The establishment of harmonious relations between countries.','The two nations are moving toward diplomatic {rapprochement}.','두 나라가 외교적 화해를 향해 나아가고 있어요.','rapprochement','C1','news',2,'diplomacy flag handshake peace'),
('w_news_C1_28','coercive','/kəʊˈɜːrsɪv/','adjective','강압적인','Using force or threats to make someone act in a certain way.','The opposition condemned the government''s {coercive} tactics.','야당은 정부의 강압적인 전술을 규탄했어요.','coercive','C1','news',2,'force authority control pressure'),
('w_news_C1_29','demagogue','/ˈdeməɡɒɡ/','noun','선동가','A political leader who gains support through emotional appeals.','The opposition accused the president of being a {demagogue}.','야당은 대통령이 선동가라고 비난했어요.','demagogue','C1','news',3,'speech crowd politics emotion'),
('w_news_C1_30','intransigence','/ɪnˈtrænsɪdʒəns/','noun','완고함, 비타협성','Refusal to change one''s views or to reach a compromise.','The talks collapsed due to both sides'' {intransigence}.','양측의 비타협적인 태도로 회담이 결렬됐어요.','intransigence','C1','news',3,'deadlock negotiation stalemate rigid'),
('w_news_C1_31','concession','/kənˈseʃən/','noun','양보','A thing granted in response to demands during negotiation.','The government offered {concessions} to end the strike.','정부가 파업을 끝내기 위해 양보를 제시했어요.','concessions','C1','news',2,'negotiation compromise offer deal'),
('w_news_C1_32','asymmetric','/ˌeɪsɪˈmetrɪk/','adjective','비대칭적인','Having unequal distribution of power or strategy between parties.','The conflict has become an {asymmetric} guerrilla war.','분쟁이 비대칭적인 게릴라 전쟁이 됐어요.','asymmetric','C1','news',3,'war strategy power difference'),
('w_news_C1_33','incendiary','/ɪnˈsendiəri/','adjective','선동적인, 도발적인','Tending to stir up conflict or strong reactions.','The senator''s {incendiary} remarks caused national outrage.','상원 의원의 선동적인 발언이 국가적 분노를 일으켰어요.','incendiary','C1','news',3,'speech protest fire rhetoric'),
('w_news_C1_34','sequestration','/ˌsiːkwɪˈstreɪʃən/','noun','자산 동결, 강제 삭감','The seizure or holding of assets, or automatic budget cuts by authority.','Budget {sequestration} resulted in automatic spending cuts.','예산 강제 삭감으로 자동적인 지출 삭감이 발생했어요.','sequestration','C1','news',3,'budget finance government cut'),
('w_news_C1_35','peremptory','/pəˈremptəri/','adjective','강압적이고 단호한','Insisting on immediate compliance without allowing debate.','The court issued a {peremptory} demand for documents.','법원이 서류에 대한 강압적인 요구를 내렸어요.','peremptory','C1','news',3,'court order authority legal command')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — C2
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_news_C2_01','epistemic','/ˌepɪˈstiːmɪk/','adjective','인식론적인','Relating to knowledge or the degree of its validation.','The article examines {epistemic} challenges in journalism.','그 기사는 저널리즘의 인식론적 도전을 다뤄요.','epistemic','C2','news',2,'knowledge theory truth philosophy'),
('w_news_C2_02','Westphalian','/westˈfeɪliən/','adjective','베스트팔렌적인','Relating to the Westphalian system of sovereign nation-states.','The humanitarian intervention challenged {Westphalian} norms.','인도주의적 개입이 베스트팔렌적 규범에 도전했어요.','Westphalian','C2','news',3,'sovereignty international law norms'),
('w_news_C2_03','securitization','/sɪˌkjʊərɪtɪˈzeɪʃən/','noun','안보화','The process of framing an issue as a security threat to justify emergency measures.','The {securitization} of migration has dominated political debates.','이주의 안보화가 정치 논쟁을 지배하고 있어요.','securitization','C2','news',3,'security border threat policy'),
('w_news_C2_04','normative','/ˈnɔːrmətɪv/','adjective','규범적인','Relating to or deriving from a standard or norm of expected behavior.','The UN Charter established a {normative} framework for world order.','유엔 헌장은 세계 질서의 규범적 틀을 확립했어요.','normative','C2','news',2,'law standard framework international'),
('w_news_C2_05','constructivist','/kənˈstrʌktɪvɪst/','adjective','구성주의적인','Relating to the theory that social reality is constructed through ideas and norms.','A {constructivist} reading of the crisis focuses on shared identities.','위기에 대한 구성주의적 해석은 공유된 정체성에 집중해요.','constructivist','C2','news',3,'theory identity norms society'),
('w_news_C2_06','ontological','/ˌɒntəˈlɒdʒɪkəl/','adjective','존재론적인','Relating to the branch of philosophy concerned with the nature of being.','The annexation threatened the country''s {ontological} security.','합병은 그 나라의 존재론적 안보감을 위협했어요.','ontological','C2','news',3,'identity state theory security'),
('w_news_C2_07','postcolonial','/ˌpəʊstˈkɒləniəl/','adjective','탈식민적인','Relating to the period after colonial rule ended and its lingering effects.','The conflict has deep {postcolonial} roots.','그 분쟁은 깊은 탈식민적 뿌리가 있어요.','postcolonial','C2','news',2,'history empire colony Africa Asia'),
('w_news_C2_08','subaltern','/ˈsʌbəltɜːrn/','adjective','하위 주체적인','Relating to those whose voices are marginalized or suppressed in society.','The report amplifies {subaltern} perspectives often ignored by media.','그 보고서는 미디어에서 종종 무시되는 하위 주체적 관점을 증폭시켜요.','subaltern','C2','news',3,'minority voice marginalized society'),
('w_news_C2_09','neocolonialism','/ˌniːəʊˈkɒləniəlɪzəm/','noun','신식민주의','The use of economic or political pressure to control developing countries.','Critics accuse wealthy nations of practicing {neocolonialism}.','비평가들은 부유한 나라들이 신식민주의를 실천한다고 비난해요.','neocolonialism','C2','news',3,'power Africa dependency aid'),
('w_news_C2_10','intergovernmentalism','/ˌɪntəˌɡʌvənˈmentəlɪzəm/','noun','정부 간주의','A theory of international cooperation in which states retain sovereignty.','{Intergovernmentalism} limits the EU''s ability to act as a single entity.','정부 간주의는 EU가 단일 주체로 행동하는 능력을 제한해요.','Intergovernmentalism','C2','news',3,'EU Europe cooperation sovereignty'),
('w_news_C2_11','liminality','/ˌlɪmɪˈnælɪti/','noun','경계성, 과도기 상태','The quality of being in an ambiguous transitional state between two phases.','The country exists in political {liminality} between democracy and authoritarianism.','그 나라는 민주주의와 권위주의 사이의 정치적 경계성 속에 있어요.','liminality','C2','news',3,'transition threshold ambiguity change'),
('w_news_C2_12','praxis','/ˈpræksɪs/','noun','실천 (이론 대비)','The practice and practical application of a theory or belief.','The movement struggled to convert ideology into {praxis}.','그 운동은 이념을 실천으로 전환하는 데 어려움을 겪었어요.','praxis','C2','news',3,'action theory practice policy'),
('w_news_C2_13','polity','/ˈpɒlɪti/','noun','정치 공동체','A form of government or political organization of a state.','The question is whether the EU constitutes a single {polity}.','문제는 EU가 단일 정치 공동체를 구성하는지 여부예요.','polity','C2','news',3,'governance state EU community'),
('w_news_C2_14','hegemon','/ˈheɡɪmɒn/','noun','패권국','A dominant state exercising preponderant power over others.','The US remains the world''s sole military {hegemon}.','미국은 여전히 세계 유일의 군사적 패권국이에요.','hegemon','C2','news',3,'superpower dominance military power'),
('w_news_C2_15','legitimation','/lɪˌdʒɪtɪˈmeɪʃən/','noun','정당화','The process of making something legitimate or lawful in others'' eyes.','The regime sought international {legitimation} through elections.','그 정권은 선거를 통해 국제적 정당화를 추구했어요.','legitimation','C2','news',2,'election credibility recognition power'),
('w_news_C2_16','heterodox','/ˈhetərədɒks/','adjective','이단적인, 비정통적인','Not conforming with accepted or orthodox standards or beliefs.','His {heterodox} interpretation of the treaty provoked debate.','그의 비정통적인 조약 해석이 논쟁을 불러일으켰어요.','heterodox','C2','news',3,'unusual theory challenge orthodox'),
('w_news_C2_17','dialectical','/ˌdaɪəˈlektɪkəl/','adjective','변증법적인','Relating to inquiry into truth by discussion and logical argument.','The analyst offered a {dialectical} reading of the peace process.','분석가는 평화 프로세스에 대한 변증법적 해석을 제공했어요.','dialectical','C2','news',3,'argument theory logic analysis'),
('w_news_C2_18','reification','/ˌriːɪfɪˈkeɪʃən/','noun','물화, 실체화','The process of treating an abstraction as if it were a concrete thing.','The speech was criticized for its {reification} of national identity.','그 연설은 국가 정체성의 물화로 비판받았어요.','reification','C2','news',3,'abstract concept identity society'),
('w_news_C2_19','exceptionalism','/ɪkˈsepʃənəlɪzəm/','noun','예외주의','The belief that a nation is exceptional and not bound by normal rules.','American {exceptionalism} has long shaped its foreign policy.','미국 예외주의는 오랫동안 미국 외교 정책을 형성해 왔어요.','exceptionalism','C2','news',3,'national identity foreign policy US'),
('w_news_C2_20','transnational','/trænsˈnæʃənəl/','adjective','초국가적인','Extending or operating across national boundaries.','The campaign is a {transnational} effort to combat misinformation.','그 캠페인은 허위 정보와 싸우기 위한 초국가적 노력이에요.','transnational','C2','news',2,'global cooperation border internet'),
('w_news_C2_21','agonistic','/ˌæɡəˈnɪstɪk/','adjective','투쟁적인, 갈등 지향적인','Relating to the view that political conflict is inherently productive.','Mouffe''s {agonistic} model sees disagreement as essential to democracy.','무페의 투쟁적 모델은 의견 불일치를 민주주의의 본질로 봐요.','agonistic','C2','news',3,'democracy conflict theory politics'),
('w_news_C2_22','discursive','/dɪˈskɜːrsɪv/','adjective','담론적인','Relating to discourse; proceeding by argument rather than intuition.','The editorial took a {discursive} approach to the crisis.','그 사설은 위기에 대한 담론적 접근을 취했어요.','discursive','C2','news',3,'language analysis text theory'),
('w_news_C2_23','counterfactual','/ˌkaʊntəˈfæktʃʊəl/','adjective','반사실적인','Relating to what might have happened under different circumstances.','Historians offer a {counterfactual} view of the failed negotiations.','역사가들은 실패한 협상에 대한 반사실적 관점을 제시해요.','counterfactual','C2','news',3,'history analysis alternative scenario'),
('w_news_C2_24','semiotic','/ˌsiːmiˈɒtɪk/','adjective','기호학적인','Relating to the study of signs and symbols and their meanings.','The flag-burning carries powerful {semiotic} significance.','국기 소각은 강력한 기호학적 의미를 지니고 있어요.','semiotic','C2','news',3,'symbol meaning sign analysis'),
('w_news_C2_25','extrapolate','/ɪkˈstræpəleɪt/','verb','외삽하다, 추론하다','To extend data or conclusions into unknown areas by inference.','Analysts {extrapolate} future trends from current data.','분석가들은 현재 데이터에서 미래 추세를 추론해요.','extrapolate','C2','news',2,'data analysis forecast prediction'),
('w_news_C2_26','temporality','/ˌtempəˈrælɪti/','noun','시간성, 임시성','The state of existing within or having some relationship with time.','The analyst explored the {temporality} of the political crisis.','분석가는 정치 위기의 시간성을 탐구했어요.','temporality','C2','news',3,'time theory analysis phase'),
('w_news_C2_27','ideological','/ˌaɪdiəˈlɒdʒɪkəl/','adjective','이데올로기적인','Based on or relating to a system of ideas and ideals forming a worldview.','The conflict has deep {ideological} roots.','그 분쟁은 깊은 이데올로기적 뿌리가 있어요.','ideological','C2','news',2,'ideas belief system politics'),
('w_news_C2_28','genealogy','/ˌdʒiːniˈælədʒi/','noun','계보, 기원 추적','The study of the origin and historical development of something.','Foucault''s {genealogy} of power influenced media criticism.','푸코의 권력 계보학은 미디어 비평에 영향을 미쳤어요.','genealogy','C2','news',3,'history origin theory Foucault'),
('w_news_C2_29','hermeneutic','/ˌhɜːrmɪˈnjuːtɪk/','adjective','해석학적인','Relating to the interpretation of texts, especially political or legal ones.','A {hermeneutic} reading of the resolution reveals ambiguities.','결의문의 해석학적 독해는 모호성을 드러내요.','hermeneutic','C2','news',3,'interpretation text law analysis'),
('w_news_C2_30','hegemonic','/ˌheɡɪˈmɒnɪk/','adjective','패권적인','Relating to the exercise of hegemony; dominant in power or influence.','The US sought to preserve its {hegemonic} position in the Pacific.','미국은 태평양에서 패권적 위치를 유지하려 했어요.','hegemonic','C2','news',3,'superpower dominance power Pacific'),
('w_news_C2_31','intersubjectivity','/ˌɪntəsʌbdʒekˈtɪvɪti/','noun','상호주관성','The sharing of cognitive or subjective states between individuals or groups.','Diplomatic norms emerge from {intersubjectivity} among states.','외교 규범은 국가들 간의 상호주관성에서 나와요.','intersubjectivity','C2','news',3,'theory norms shared understanding'),
('w_news_C2_32','deterritorialization','/diːˌterɪtɔːriəlaɪˈzeɪʃən/','noun','탈영토화','The loosening of the connection between culture and geographic territory.','Globalization has accelerated the {deterritorialization} of political identity.','세계화가 정치적 정체성의 탈영토화를 가속화했어요.','deterritorialization','C2','news',3,'globalization identity border culture'),
('w_news_C2_33','dialectic','/ˌdaɪəˈlektɪk/','noun','변증법','A method of examining opposing ideas to reach the truth.','The editorial used a {dialectic} of freedom versus security.','그 사설은 자유 대 안보의 변증법을 사용했어요.','dialectic','C2','news',3,'logic argument theory analysis'),
('w_news_C2_34','disarticulation','/dɪsɑːˌtɪkjʊˈleɪʃən/','noun','연결 해체','The unraveling of coherent political or social structures.','The crisis led to the {disarticulation} of the ruling coalition.','위기는 집권 연합의 연결 해체로 이어졌어요.','disarticulation','C2','news',3,'collapse breakdown coalition fragmentation'),
('w_news_C2_35','epistemocracy','/ɪˌpiːstɪˈmɒkrəsi/','noun','지식 기반 정치 체제','A form of government where political power rests on epistemic competence.','Advocates argue that {epistemocracy} can improve policy quality.','지지자들은 지식 기반 정치 체제가 정책 품질을 높일 수 있다고 주장해요.','epistemocracy','C2','news',3,'expertise knowledge governance theory')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — A1 (뉴스 공유)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_news_A1_01','Did you hear about...?','...에 대해 들었어요?','Did you hear about','최근 소식이나 뉴스를 자연스럽게 공유할 때 쓰는 첫 마디예요. "Did you hear about the fire?" 처럼 명사를 바로 이어 붙여요.','뉴스 공유','A1','news','pattern',NULL,1),
('s_news_A1_02','I saw on the news that...','뉴스에서 ...라는 걸 봤어요.','I saw on the news','TV나 온라인 뉴스에서 본 내용을 전달할 때 써요. "I saw on the news that there was a big flood." 처럼 that절을 이어요.','뉴스 전달','A1','news','pattern',NULL,2),
('s_news_A1_03','What happened?','무슨 일이 있었어요?','What happened','사건에 대해 더 알고 싶을 때 쓰는 가장 기본적인 질문이에요. 간단하지만 어디서든 쓸 수 있어요.','사건 질문','A1','news','pattern',NULL,3),
('s_news_A1_04','Is it true that...?','...가 사실이에요?','Is it true that','들은 이야기가 사실인지 확인할 때 써요. "Is it true that the president resigned?" 처럼 that절을 이어요.','사실 확인','A1','news','pattern',NULL,4),
('s_news_A1_05','They said on the news that...','뉴스에서 ...라고 했어요.','They said on the news','불특정 뉴스 출처를 인용할 때 "They said"를 써요. 구어체에서 아주 자주 쓰이는 표현이에요.','뉴스 인용','A1','news','pattern',NULL,5),
('s_news_A1_06','A lot of people were hurt.','많은 사람들이 다쳤어요.','A lot of people were hurt','사고나 재난 보도에서 자주 나오는 문장 구조예요. "were hurt"는 수동태로 피해를 표현해요.','피해 상황','A1','news','pattern',NULL,6),
('s_news_A1_07','The government said...','정부가 ...라고 했어요.','The government said','공식 발표나 성명을 인용할 때 가장 기본적인 구조예요. 뒤에 직접 또는 간접 인용을 붙여요.','공식 발표 인용','A1','news','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — A2 (사건 설명)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_news_A2_01','According to reports, ...','보도에 따르면, ...','According to reports','뉴스 출처를 인용할 때 쓰는 표현이에요. 좀 더 격식 있는 느낌이 나고 사실 여부를 단정하지 않는 표현이에요.','출처 인용','A2','news','pattern',NULL,1),
('s_news_A2_02','The police are investigating...','경찰이 ...을 조사하고 있어요.','are investigating','범죄나 사고에 관한 뉴스에서 매우 자주 나오는 표현이에요. 현재진행형으로 진행 중임을 나타내요.','사건 보도','A2','news','pattern',NULL,2),
('s_news_A2_03','It is believed that...','...라고 여겨져요.','It is believed that','확실하지 않은 정보를 전달할 때 쓰는 수동태 표현이에요. 직접 단정하는 것을 피할 수 있어요.','불확실 정보','A2','news','pattern',NULL,3),
('s_news_A2_04','Protests broke out in...','...에서 시위가 발생했어요.','broke out','갑작스럽게 시작된 시위나 사건을 설명할 때 "break out"을 써요. 폭동, 화재, 전쟁 등에도 써요.','시위·사건 발생','A2','news','pattern',NULL,4),
('s_news_A2_05','The government has announced that...','정부는 ...라고 발표했어요.','has announced','현재완료형으로 방금 또는 최근에 이루어진 공식 발표를 자연스럽게 표현해요.','공식 발표','A2','news','pattern',NULL,5),
('s_news_A2_06','Thousands of people took to the streets.','수천 명이 거리로 나왔어요.','took to the streets','많은 사람들이 시위를 위해 나온 것을 표현할 때 "take to the streets"를 써요. 뉴스에서 자주 보이는 관용 표현이에요.','시위 묘사','A2','news','pattern',NULL,6),
('s_news_A2_07','A ceasefire has been agreed.','휴전이 합의됐어요.','has been agreed','수동태로 협상 결과를 간결하게 전달하는 뉴스 문체 표현이에요. 주어가 누구인지 모르거나 중요하지 않을 때 써요.','협상 결과','A2','news','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — B1 (정치·경제 논의)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_news_B1_01','The government is under pressure to...','정부가 ...에 대한 압박을 받고 있어요.','is under pressure to','정치·외교 논의에서 자주 쓰이는 표현이에요. "under pressure to reform" 처럼 동사 원형을 이어 써요.','정치 논의','B1','news','pattern',NULL,1),
('s_news_B1_02','Critics have accused the minister of...','비평가들이 장관을 ...혐의로 비난했어요.','Critics have accused','현재완료형으로 최근의 비난·고발을 전달해요. "of + 동명사" 패턴을 외워두면 편리해요.','비난·고발','B1','news','pattern',NULL,2),
('s_news_B1_03','The opposition has called for an inquiry into...','야당이 ...에 대한 조사를 요구했어요.','has called for an inquiry into','야당의 공식 요구를 표현할 때 써요. "call for"는 공식적으로 요구하다는 뜻이에요.','야당 성명','B1','news','pattern',NULL,3),
('s_news_B1_04','Unemployment figures rose to... percent.','실업률이 ...%로 올랐어요.','rose to','경제 지표를 보도할 때 쓰는 패턴이에요. "rose to", "fell to", "hit a record high/low"와 함께 외워두세요.','경제 지표','B1','news','pattern',NULL,4),
('s_news_B1_05','The legislation was passed by a majority of...','법안이 ...의 다수결로 통과됐어요.','was passed by a majority','의회에서 법안이 통과됐을 때 쓰는 수동태 표현이에요. "slim majority(근소한 다수)" 등의 수식어를 붙여요.','입법 보도','B1','news','pattern',NULL,5),
('s_news_B1_06','The minister resigned amid allegations of...','장관이 ...혐의 속에 사임했어요.','resigned amid allegations of','스캔들로 인한 사임 보도에서 자주 나오는 구조예요. "amid"는 "~속에/~가운데"라는 뜻이에요.','스캔들 보도','B1','news','pattern',NULL,6),
('s_news_B1_07','Inflation has reached its highest level in... years.','인플레이션이 ...년 만에 최고치에 달했어요.','has reached its highest level','경제 기사에서 최고점을 강조할 때 쓰는 현재완료 표현이에요. "lowest level", "highest point" 등을 바꿔 써요.','경제 보도','B1','news','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — B2 (국제 정세)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_news_B2_01','Diplomatic tensions have escalated between... and...','...와 ... 사이의 외교적 긴장이 고조됐어요.','Diplomatic tensions have escalated','두 나라 간의 갈등 고조를 표현할 때 써요. "escalate"는 상황이 점점 심각해지는 것을 나타내요.','국제 분쟁','B2','news','pattern',NULL,1),
('s_news_B2_02','Sanctions have been imposed on... in response to...','...에 대응해 ...에 제재가 부과됐어요.','Sanctions have been imposed on','제재 부과를 수동태로 표현하는 국제 뉴스 정형 문구예요. "in response to"는 이유를 나타내요.','제재 보도','B2','news','pattern',NULL,2),
('s_news_B2_03','The two nations agreed to resume diplomatic talks.','두 나라가 외교 회담 재개에 합의했어요.','agreed to resume diplomatic talks','관계 정상화를 향한 첫 걸음을 표현할 때 써요. "resume"은 중단됐다가 다시 시작함을 의미해요.','외교 관계','B2','news','pattern',NULL,3),
('s_news_B2_04','The international community has condemned the attack.','국제 사회가 공격을 규탄했어요.','has condemned','규탄 성명에서 항상 나오는 표현이에요. "condemn"은 "강하게 비난하다"는 뜻이에요.','국제 규탄','B2','news','pattern',NULL,4),
('s_news_B2_05','A multilateral agreement was reached at the summit.','정상 회담에서 다자간 합의가 이루어졌어요.','multilateral agreement was reached','다자 외교의 결과를 보도할 때 쓰는 표현이에요. "bilateral"(양자), "multilateral"(다자)을 구분해서 써요.','정상 회담','B2','news','pattern',NULL,5),
('s_news_B2_06','The regime faces growing pressure from the international community.','그 정권은 국제 사회로부터 점점 커지는 압박에 직면해 있어요.','faces growing pressure','정권이 국내외 압박을 받는 상황을 설명할 때 써요. "growing"은 압박이 점점 강해지고 있음을 나타내요.','국제 압박','B2','news','pattern',NULL,6),
('s_news_B2_07','The referendum resulted in a vote for independence.','국민 투표 결과 독립 찬성으로 나왔어요.','referendum resulted in','국민 투표 결과를 보도할 때 쓰는 표현이에요. "result in"은 특정 결과로 이어짐을 나타내요.','국민 투표','B2','news','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — C1 (외교·정책 분석)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_news_C1_01','The decision sets a significant precedent for international law.','그 결정은 국제법에 중요한 선례를 남겨요.','sets a significant precedent','법적·외교적 판단이 미래에 미치는 영향을 설명할 때 써요. "landmark precedent", "dangerous precedent"도 자주 쓰여요.','국제법 분석','C1','news','pattern',NULL,1),
('s_news_C1_02','The sanctions regime has failed to achieve its stated objectives.','제재 체제가 명시된 목표를 달성하는 데 실패했어요.','has failed to achieve its stated objectives','정책 효과를 비판적으로 분석할 때 쓰는 표현이에요. "stated objectives"는 공식적으로 밝힌 목표를 뜻해요.','정책 비판 분석','C1','news','pattern',NULL,2),
('s_news_C1_03','The bilateral relationship has deteriorated significantly in recent months.','양자 관계가 최근 몇 달 동안 크게 악화됐어요.','has deteriorated significantly','관계 악화를 표현할 때 "deteriorate"를 써요. "improve dramatically", "stabilize gradually"와 반대 표현으로 외워요.','외교 분석','C1','news','pattern',NULL,3),
('s_news_C1_04','There are growing concerns about the erosion of democratic norms.','민주주의 규범 침식에 대한 우려가 커지고 있어요.','growing concerns about the erosion of','추상적인 제도나 가치의 약화를 표현할 때 써요. "erosion of"는 서서히 무너지는 것을 나타내요.','민주주의 분석','C1','news','pattern',NULL,4),
('s_news_C1_05','The court''s ruling may have far-reaching implications for...','법원의 판결은 ...에 광범위한 영향을 미칠 수 있어요.','may have far-reaching implications for','법적 판결이 더 넓은 영역에 미치는 파급 효과를 분석할 때 써요. "far-reaching"은 "광범위한"이라는 뜻이에요.','사법 분석','C1','news','pattern',NULL,5),
('s_news_C1_06','The government invoked emergency powers to suppress dissent.','정부가 반대 의견을 억압하기 위해 비상 권한을 발동했어요.','invoked emergency powers to suppress','강압적 통치를 보도하거나 분석할 때 쓰는 표현이에요. "invoke"는 법이나 권한을 공식 발동하는 뜻이에요.','권위주의 분석','C1','news','pattern',NULL,6),
('s_news_C1_07','Analysts warn of the risk of further escalation in the region.','분석가들은 지역 내 추가 확전 위험을 경고해요.','warn of the risk of further escalation','분쟁 지역 상황 분석에서 자주 쓰이는 표현이에요. "escalation"은 갈등 심화를, "further"는 추가적임을 나타내요.','분쟁 분석','C1','news','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — C2 (외교·정책 심층 분석)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_news_C2_01','The hegemon''s unilateral actions undermine the multilateral rules-based order.','패권국의 일방적 행동이 다자 규칙 기반 질서를 약화시켜요.','unilateral actions undermine the multilateral rules-based order','국제 정치 분석에서 핵심 패턴이에요. "rules-based order"는 현 국제 체계를 가리키는 전문 용어예요.','국제 질서 분석','C2','news','pattern',NULL,1),
('s_news_C2_02','The conflict can be read as a manifestation of postcolonial tensions.','그 분쟁은 탈식민적 긴장의 표현으로 읽힐 수 있어요.','can be read as a manifestation of','학문적·비판적 분석에서 쓰이는 표현이에요. "manifestation of"는 어떤 현상의 구체적 발현을 뜻해요.','탈식민 분석','C2','news','pattern',NULL,2),
('s_news_C2_03','Securitization of the issue has foreclosed alternative policy responses.','그 문제의 안보화가 대안적 정책 대응을 차단했어요.','Securitization of the issue has foreclosed','코펜하겐 학파의 안보화 이론을 적용한 분석 표현이에요. "foreclose"는 가능성을 원천 봉쇄하는 것을 뜻해요.','안보화 이론','C2','news','pattern',NULL,3),
('s_news_C2_04','The normative framework underpinning the international order is being contested.','국제 질서를 뒷받침하는 규범적 틀이 도전받고 있어요.','normative framework underpinning the international order is being contested','국제 규범의 위기를 설명하는 학술적 표현이에요. "underpin"은 "뒷받침하다", "contest"는 "이의를 제기하다"는 뜻이에요.','규범 분석','C2','news','pattern',NULL,4),
('s_news_C2_05','The crisis exposes the epistemic limits of mainstream IR theory.','위기는 주류 국제 관계 이론의 인식론적 한계를 드러내요.','exposes the epistemic limits of','국제 관계(IR) 학문에서 이론의 설명력 한계를 비판할 때 써요. "epistemic"은 지식·인식에 관련된 형용사예요.','IR 이론 비판','C2','news','pattern',NULL,5),
('s_news_C2_06','Subaltern voices remain systematically excluded from diplomatic discourse.','하위 주체의 목소리는 외교 담론에서 체계적으로 배제돼요.','Subaltern voices remain systematically excluded','탈식민 이론과 비판 IR에서 쓰이는 표현이에요. "subaltern"은 권력 구조에서 소외된 주체를 뜻해요.','탈식민 비판','C2','news','pattern',NULL,6),
('s_news_C2_07','The state''s ontological security imperative drove its foreign policy choices.','국가의 존재론적 안보 요구가 외교 정책 선택을 이끌었어요.','ontological security imperative drove its foreign policy choices','미어샤이머나 스틸(Steele) 등의 이론에서 나온 분석 틀이에요. "ontological security"는 국가의 정체성 안정감을 뜻해요.','존재론적 안보','C2','news','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;
