-- EngCat — Cafe topic word examples backfill
-- example_en_2 ~ example_en_5 추가
-- 톤: 공손한 존댓말, B1-B2 학습자 친화 단순 문장
-- Idempotent (UPDATE)

-- ══════════════════════════════════════
-- A1 (35단어)
-- ══════════════════════════════════════
UPDATE words SET example_en_2 = 'We usually eat dinner around seven.', example_ko_2 = '우리는 보통 7시쯤 저녁을 먹어요.', example_en_3 = 'Don''t forget to eat breakfast.', example_ko_3 = '아침 먹는 거 잊지 마세요.', example_en_4 = 'She loves to eat sushi.', example_ko_4 = '그녀는 초밥 먹는 걸 좋아해요.', example_en_5 = 'What do you want to eat tonight?', example_ko_5 = '오늘 저녁 뭐 먹고 싶어요?' WHERE id = 'w_cafe_A1_01';
UPDATE words SET example_en_2 = 'I always drink water with my meals.', example_ko_2 = '저는 항상 식사할 때 물을 마셔요.', example_en_3 = 'Would you like something to drink?', example_ko_3 = '마실 것 좀 드릴까요?', example_en_4 = 'He drinks coffee every morning.', example_ko_4 = '그는 매일 아침 커피를 마셔요.', example_en_5 = 'This drink is very sweet.', example_ko_5 = '이 음료 정말 달아요.' WHERE id = 'w_cafe_A1_02';
UPDATE words SET example_en_2 = 'The food here is amazing.', example_ko_2 = '여기 음식 정말 맛있어요.', example_en_3 = 'I love Korean food.', example_ko_3 = '저는 한국 음식을 좋아해요.', example_en_4 = 'We need to buy some food for dinner.', example_ko_4 = '저녁에 먹을 음식을 좀 사야 해요.', example_en_5 = 'Can I order more food?', example_ko_5 = '음식을 더 주문할 수 있을까요?' WHERE id = 'w_cafe_A1_03';
UPDATE words SET example_en_2 = 'A glass of water, please.', example_ko_2 = '물 한 잔 주세요.', example_en_3 = 'I drink eight glasses of water a day.', example_ko_3 = '저는 하루에 물을 여덟 잔 마셔요.', example_en_4 = 'The water here is too cold.', example_ko_4 = '여기 물은 너무 차가워요.', example_en_5 = 'Is the water safe to drink?', example_ko_5 = '이 물 마셔도 괜찮아요?' WHERE id = 'w_cafe_A1_04';
UPDATE words SET example_en_2 = 'Two coffees, please.', example_ko_2 = '커피 두 잔 부탁해요.', example_en_3 = 'How would you like your coffee?', example_ko_3 = '커피 어떻게 드릴까요?', example_en_4 = 'This coffee shop has the best lattes.', example_ko_4 = '이 카페 라떼가 제일 맛있어요.', example_en_5 = 'I need a coffee to wake up.', example_ko_5 = '잠 깨려면 커피가 필요해요.' WHERE id = 'w_cafe_A1_05';
UPDATE words SET example_en_2 = 'Would you like some green tea?', example_ko_2 = '녹차 좀 드시겠어요?', example_en_3 = 'She drinks tea instead of coffee.', example_ko_3 = '그녀는 커피 대신 차를 마셔요.', example_en_4 = 'Tea helps me relax in the evening.', example_ko_4 = '저녁에 차를 마시면 마음이 편해져요.', example_en_5 = 'Could I get a hot tea, please?', example_ko_5 = '따뜻한 차 한 잔 주실 수 있나요?' WHERE id = 'w_cafe_A1_06';
UPDATE words SET example_en_2 = 'The menu has so many options.', example_ko_2 = '메뉴에 종류가 정말 많아요.', example_en_3 = 'Is there an English menu?', example_ko_3 = '영어 메뉴 있나요?', example_en_4 = 'I''m still looking at the menu.', example_ko_4 = '아직 메뉴 보고 있어요.', example_en_5 = 'Their lunch menu changes daily.', example_ko_5 = '점심 메뉴는 매일 바뀌어요.' WHERE id = 'w_cafe_A1_07';
UPDATE words SET example_en_2 = 'We need a table for four.', example_ko_2 = '네 명이 앉을 테이블 필요해요.', example_en_3 = 'The table by the window is nice.', example_ko_3 = '창가 자리 좋아요.', example_en_4 = 'Could we move to a quieter table?', example_ko_4 = '더 조용한 자리로 옮길 수 있을까요?', example_en_5 = 'Please clean the table when you''re done.', example_ko_5 = '다 드시고 테이블 좀 정리해 주세요.' WHERE id = 'w_cafe_A1_08';
UPDATE words SET example_en_2 = 'I get hungry around three.', example_ko_2 = '저는 3시쯤 배고파져요.', example_en_3 = 'Are you hungry yet?', example_ko_3 = '벌써 배고파요?', example_en_4 = 'He was hungry after the long walk.', example_ko_4 = '그는 오래 걷고 나서 배가 고팠어요.', example_en_5 = 'If you''re hungry, we can order something.', example_ko_5 = '배고프면 뭐 시켜도 돼요.' WHERE id = 'w_cafe_A1_09';
UPDATE words SET example_en_2 = 'The pasta was absolutely delicious.', example_ko_2 = '파스타 정말 맛있었어요.', example_en_3 = 'Everything smells delicious in here.', example_ko_3 = '여기 모든 게 다 맛있는 냄새가 나요.', example_en_4 = 'My grandmother makes delicious soup.', example_ko_4 = '우리 할머니가 맛있는 수프를 만드세요.', example_en_5 = 'Have you tried their delicious cheesecake?', example_ko_5 = '거기 맛있는 치즈케이크 먹어봤어요?' WHERE id = 'w_cafe_A1_10';
UPDATE words SET example_en_2 = 'Could you bring more water, please?', example_ko_2 = '물 좀 더 주실 수 있나요?', example_en_3 = 'Please take a seat.', example_ko_3 = '자리에 앉아 주세요.', example_en_4 = 'Two iced coffees, please.', example_ko_4 = '아이스 커피 두 잔 부탁해요.', example_en_5 = 'Please pass me the salt.', example_ko_5 = '소금 좀 건네주세요.' WHERE id = 'w_cafe_A1_11';
UPDATE words SET example_en_2 = 'Be careful, the plate is hot.', example_ko_2 = '조심하세요, 접시가 뜨거워요.', example_en_3 = 'I''d like a hot chocolate.', example_ko_3 = '핫초콜릿 주세요.', example_en_4 = 'The soup is too hot to eat right now.', example_ko_4 = '수프가 너무 뜨거워서 지금 못 먹어요.', example_en_5 = 'I prefer hot coffee in the morning.', example_ko_5 = '아침에는 뜨거운 커피가 좋아요.' WHERE id = 'w_cafe_A1_12';
UPDATE words SET example_en_2 = 'This coffee got cold.', example_ko_2 = '커피가 식었어요.', example_en_3 = 'A cold drink would be perfect now.', example_ko_3 = '지금 시원한 음료 한 잔이면 딱이에요.', example_en_4 = 'I prefer cold drinks in summer.', example_ko_4 = '여름엔 차가운 음료가 더 좋아요.', example_en_5 = 'The water is ice cold.', example_ko_5 = '물이 얼음처럼 차가워요.' WHERE id = 'w_cafe_A1_13';
UPDATE words SET example_en_2 = 'Could I get a big cup, please?', example_ko_2 = '큰 컵으로 주실 수 있나요?', example_en_3 = 'That cake is too big for one person.', example_ko_3 = '그 케이크는 한 명이 먹기엔 너무 커요.', example_en_4 = 'They serve big portions here.', example_ko_4 = '여기는 양을 푸짐하게 줘요.', example_en_5 = 'I''d like the big size, please.', example_ko_5 = '큰 사이즈로 주세요.' WHERE id = 'w_cafe_A1_14';
UPDATE words SET example_en_2 = 'A small coffee is enough for me.', example_ko_2 = '저는 작은 커피로 충분해요.', example_en_3 = 'This café is small but cozy.', example_ko_3 = '이 카페 작지만 아늑해요.', example_en_4 = 'Can I have a small piece?', example_ko_4 = '조금만 주실 수 있나요?', example_en_5 = 'They only have small tables left.', example_ko_5 = '작은 테이블만 남아 있어요.' WHERE id = 'w_cafe_A1_15';
UPDATE words SET example_en_2 = 'Would you like some more?', example_ko_2 = '좀 더 드시겠어요?', example_en_3 = 'Can I have more rice, please?', example_ko_3 = '밥 좀 더 주실 수 있나요?', example_en_4 = 'I''d like one more cup of coffee.', example_ko_4 = '커피 한 잔만 더 주세요.', example_en_5 = 'There''s more cake in the fridge.', example_ko_5 = '냉장고에 케이크가 더 있어요.' WHERE id = 'w_cafe_A1_16';
UPDATE words SET example_en_2 = 'Your order is ready.', example_ko_2 = '주문하신 거 나왔어요.', example_en_3 = 'I''m ready to order now.', example_ko_3 = '이제 주문할 준비 됐어요.', example_en_4 = 'Are you ready for dessert?', example_ko_4 = '디저트 드실 준비 됐어요?', example_en_5 = 'The table is ready for you.', example_ko_5 = '자리 준비됐어요.' WHERE id = 'w_cafe_A1_17';
UPDATE words SET example_en_2 = 'This cake is really good.', example_ko_2 = '이 케이크 정말 맛있어요.', example_en_3 = 'Have a good meal.', example_ko_3 = '맛있게 드세요.', example_en_4 = 'That sounds good — I''ll have one.', example_ko_4 = '좋네요, 그걸로 할게요.', example_en_5 = 'Their service is always good.', example_ko_5 = '서비스가 항상 좋아요.' WHERE id = 'w_cafe_A1_18';
UPDATE words SET example_en_2 = 'Are you open on Sundays?', example_ko_2 = '일요일에도 영업하나요?', example_en_3 = 'The bakery opens at seven.', example_ko_3 = '빵집은 7시에 문을 열어요.', example_en_4 = 'I''m glad they''re open late.', example_ko_4 = '늦게까지 영업해서 다행이에요.', example_en_5 = 'This café is open 24 hours.', example_ko_5 = '이 카페 24시간 영업해요.' WHERE id = 'w_cafe_A1_19';
UPDATE words SET example_en_2 = 'What time do you close tonight?', example_ko_2 = '오늘 몇 시에 문 닫아요?', example_en_3 = 'The kitchen closes at ten.', example_ko_3 = '주방은 10시에 닫아요.', example_en_4 = 'They closed early today.', example_ko_4 = '오늘은 일찍 문 닫았어요.', example_en_5 = 'Please close the door behind you.', example_ko_5 = '들어와서 문 좀 닫아 주세요.' WHERE id = 'w_cafe_A1_20';
UPDATE words SET example_en_2 = 'The price includes service.', example_ko_2 = '가격에 서비스 포함이에요.', example_en_3 = 'That''s a good price for lunch.', example_ko_3 = '점심 가격으로 괜찮네요.', example_en_4 = 'What''s the price of the daily special?', example_ko_4 = '오늘의 메뉴 얼마예요?', example_en_5 = 'The prices went up last month.', example_ko_5 = '지난달에 가격이 올랐어요.' WHERE id = 'w_cafe_A1_21';
UPDATE words SET example_en_2 = 'Could I have milk with my coffee?', example_ko_2 = '커피에 우유 좀 넣어 주실 수 있나요?', example_en_3 = 'This bread is made with milk.', example_ko_3 = '이 빵은 우유로 만들어요.', example_en_4 = 'I''ll have oat milk instead.', example_ko_4 = '귀리 우유로 주세요.', example_en_5 = 'The milk is fresh today.', example_ko_5 = '오늘 우유는 신선해요.' WHERE id = 'w_cafe_A1_22';
UPDATE words SET example_en_2 = 'No sugar in my coffee, please.', example_ko_2 = '커피에 설탕 빼고 주세요.', example_en_3 = 'How much sugar would you like?', example_ko_3 = '설탕 얼마나 넣을까요?', example_en_4 = 'Brown sugar tastes a bit different.', example_ko_4 = '흑설탕은 맛이 좀 달라요.', example_en_5 = 'This cake has too much sugar.', example_ko_5 = '이 케이크는 설탕이 너무 많아요.' WHERE id = 'w_cafe_A1_23';
UPDATE words SET example_en_2 = 'Fresh bread comes out at six.', example_ko_2 = '갓 구운 빵이 6시에 나와요.', example_en_3 = 'I''d like some bread with my soup.', example_ko_3 = '수프랑 같이 빵 좀 주세요.', example_en_4 = 'They bake their bread every morning.', example_ko_4 = '매일 아침 빵을 구워요.', example_en_5 = 'Bread and butter is my favorite.', example_ko_5 = '빵에 버터 발라 먹는 게 제일 좋아요.' WHERE id = 'w_cafe_A1_24';
UPDATE words SET example_en_2 = 'Could I see the cakes in the display?', example_ko_2 = '진열대에 있는 케이크 좀 볼 수 있을까요?', example_en_3 = 'Their chocolate cake is the best.', example_ko_3 = '거기 초콜릿 케이크가 최고예요.', example_en_4 = 'I''ll have one slice of cake, please.', example_ko_4 = '케이크 한 조각 부탁해요.', example_en_5 = 'The cake melts in your mouth.', example_ko_5 = '케이크가 입에서 살살 녹아요.' WHERE id = 'w_cafe_A1_25';
UPDATE words SET example_en_2 = 'I''d like the tomato soup, please.', example_ko_2 = '토마토 수프 주세요.', example_en_3 = 'This soup is too salty for me.', example_ko_3 = '이 수프 저한테는 너무 짜요.', example_en_4 = 'Soup is perfect for cold weather.', example_ko_4 = '추울 때는 수프가 딱이에요.', example_en_5 = 'They make their soup from scratch.', example_ko_5 = '수프를 직접 만들어요.' WHERE id = 'w_cafe_A1_26';
UPDATE words SET example_en_2 = 'A glass of orange juice, please.', example_ko_2 = '오렌지 주스 한 잔 주세요.', example_en_3 = 'This juice is freshly squeezed.', example_ko_3 = '이거 갓 짠 주스예요.', example_en_4 = 'I don''t drink juice with added sugar.', example_ko_4 = '설탕 들어간 주스는 안 마셔요.', example_en_5 = 'Apple juice is my kid''s favorite.', example_ko_5 = '우리 애는 사과 주스를 제일 좋아해요.' WHERE id = 'w_cafe_A1_27';
UPDATE words SET example_en_2 = 'Could I have the bill, please?', example_ko_2 = '계산서 주실 수 있나요?', example_en_3 = 'The bill came to thirty dollars.', example_ko_3 = '계산서가 30달러 나왔어요.', example_en_4 = 'Let me pay the bill this time.', example_ko_4 = '이번엔 제가 낼게요.', example_en_5 = 'We split the bill evenly.', example_ko_5 = '계산서를 똑같이 나눠 냈어요.' WHERE id = 'w_cafe_A1_28';
UPDATE words SET example_en_2 = 'The coffee refills are free.', example_ko_2 = '커피 리필은 무료예요.', example_en_3 = 'They offer free water with every meal.', example_ko_3 = '식사할 때마다 물은 무료로 줘요.', example_en_4 = 'Is this table free?', example_ko_4 = '이 테이블 비어 있나요?', example_en_5 = 'Wi-Fi is free for customers.', example_ko_5 = '손님은 와이파이 무료예요.' WHERE id = 'w_cafe_A1_29';
UPDATE words SET example_en_2 = 'How long do we have to wait?', example_ko_2 = '얼마나 기다려야 해요?', example_en_3 = 'Could you wait a few minutes?', example_ko_3 = '몇 분만 기다려 주실 수 있나요?', example_en_4 = 'I don''t mind waiting for good food.', example_ko_4 = '맛있는 음식이라면 기다려도 괜찮아요.', example_en_5 = 'We waited an hour for a table.', example_ko_5 = '자리 잡으려고 한 시간 기다렸어요.' WHERE id = 'w_cafe_A1_30';
UPDATE words SET example_en_2 = 'This seat by the window is nice.', example_ko_2 = '창가 자리 좋네요.', example_en_3 = 'Please take a seat over there.', example_ko_3 = '저쪽 자리에 앉아 주세요.', example_en_4 = 'Is this seat taken?', example_ko_4 = '이 자리 다른 분 계세요?', example_en_5 = 'All the seats are full right now.', example_ko_5 = '지금 자리가 다 찼어요.' WHERE id = 'w_cafe_A1_31';
UPDATE words SET example_en_2 = 'Could we sit outside?', example_ko_2 = '바깥 자리에 앉을 수 있을까요?', example_en_3 = 'The outside seats have a great view.', example_ko_3 = '바깥 자리는 전망이 좋아요.', example_en_4 = 'It''s nice enough to eat outside today.', example_ko_4 = '오늘은 바깥에서 먹기 좋은 날씨예요.', example_en_5 = 'They have a small garden outside.', example_ko_5 = '바깥에 작은 정원이 있어요.' WHERE id = 'w_cafe_A1_32';
UPDATE words SET example_en_2 = 'Let''s sit inside — it''s cooler.', example_ko_2 = '안쪽에 앉아요, 시원해서.', example_en_3 = 'It''s more comfortable inside.', example_ko_3 = '안쪽이 더 편해요.', example_en_4 = 'Inside dining starts at five.', example_ko_4 = '안쪽 좌석은 5시부터 시작해요.', example_en_5 = 'The bakery is right inside the building.', example_ko_5 = '빵집은 건물 바로 안에 있어요.' WHERE id = 'w_cafe_A1_33';
UPDATE words SET example_en_2 = 'These pastries are fresh out of the oven.', example_ko_2 = '이 페이스트리는 갓 구워 나왔어요.', example_en_3 = 'Their fruit is always fresh.', example_ko_3 = '거기 과일은 항상 신선해요.', example_en_4 = 'I like fresh juice in the morning.', example_ko_4 = '아침에 신선한 주스 좋아해요.', example_en_5 = 'Fresh bread smells so good.', example_ko_5 = '갓 구운 빵 냄새 정말 좋아요.' WHERE id = 'w_cafe_A1_34';
UPDATE words SET example_en_2 = 'This dessert is too sweet for me.', example_ko_2 = '이 디저트 저한테는 너무 달아요.', example_en_3 = 'Could I have something less sweet?', example_ko_3 = '덜 단 거 있을까요?', example_en_4 = 'The cake has a sweet aroma.', example_ko_4 = '케이크에서 달콤한 향이 나요.', example_en_5 = 'She has a sweet tooth.', example_ko_5 = '그녀는 단 거 정말 좋아해요.' WHERE id = 'w_cafe_A1_35';
