-- EngCat — Travel topic word examples backfill
-- example_en_2 ~ example_en_5 + example_ko_2 ~ example_ko_5 추가
-- 210 words × 4 new examples each
-- Idempotent (UPDATE only)
-- Generated: 2026-05-26

-- ══════════════════════════════════════
-- A1 — 35 WORDS
-- ══════════════════════════════════════
UPDATE words SET example_en_2 = 'Did you enjoy your trip to Japan?', example_ko_2 = '일본 여행 즐거우셨나요?', example_en_3 = 'We are planning a road trip next month.', example_ko_3 = '다음 달에 자동차 여행을 계획하고 있어요.', example_en_4 = 'It was a short trip but very memorable.', example_ko_4 = '짧은 여행이었지만 정말 기억에 남아요.', example_en_5 = 'How long was your trip?', example_ko_5 = '여행이 얼마나 됐어요?' WHERE id = 'w_travel_A1_01';
UPDATE words SET example_en_2 = 'Is breakfast included at the hotel?', example_ko_2 = '호텔에 아침 식사가 포함되어 있나요?', example_en_3 = 'The hotel has a swimming pool on the roof.', example_ko_3 = '그 호텔에는 옥상에 수영장이 있어요.', example_en_4 = 'Can I book a hotel room online?', example_ko_4 = '호텔 방을 온라인으로 예약할 수 있나요?', example_en_5 = 'The hotel is a short walk from the station.', example_ko_5 = '호텔은 역에서 걸어서 금방이에요.' WHERE id = 'w_travel_A1_02';
UPDATE words SET example_en_2 = 'Do you have a map of the city?', example_ko_2 = '시내 지도 있으세요?', example_en_3 = 'I downloaded a map before leaving home.', example_ko_3 = '집을 나서기 전에 지도를 내려받았어요.', example_en_4 = 'The map shows all the bus stops.', example_ko_4 = '지도에 모든 버스 정류장이 나와 있어요.', example_en_5 = 'Could you mark it on the map, please?', example_ko_5 = '지도에 표시해 주실 수 있나요?' WHERE id = 'w_travel_A1_03';
UPDATE words SET example_en_2 = 'Our plane was delayed by two hours.', example_ko_2 = '비행기가 두 시간 연착됐어요.', example_en_3 = 'I get nervous every time I board a plane.', example_ko_3 = '비행기에 탈 때마다 긴장돼요.', example_en_4 = 'The plane landed safely in London.', example_ko_4 = '비행기가 런던에 안전하게 착륙했어요.', example_en_5 = 'Which plane are you taking to Seoul?', example_ko_5 = '서울로 어떤 비행기를 타세요?' WHERE id = 'w_travel_A1_04';
UPDATE words SET example_en_2 = 'My passport is valid for ten years.', example_ko_2 = '제 여권은 10년 동안 유효해요.', example_en_3 = 'Please show your passport at the border.', example_ko_3 = '국경에서 여권을 보여 주세요.', example_en_4 = 'I renewed my passport last year.', example_ko_4 = '작년에 여권을 갱신했어요.', example_en_5 = 'Where can I apply for a passport?', example_ko_5 = '여권은 어디서 신청할 수 있나요?' WHERE id = 'w_travel_A1_05';
UPDATE words SET example_en_2 = 'Is your bag too heavy to carry?', example_ko_2 = '가방이 너무 무거워서 들기 힘드세요?', example_en_3 = 'I left my bag on the bus by mistake.', example_ko_3 = '실수로 버스에 가방을 두고 내렸어요.', example_en_4 = 'Pack only what fits in your bag.', example_ko_4 = '가방에 들어가는 것만 챙기세요.', example_en_5 = 'Your bag is over the weight limit.', example_ko_5 = '가방이 무게 제한을 초과했어요.' WHERE id = 'w_travel_A1_06';
UPDATE words SET example_en_2 = 'I forgot to book a seat in advance.', example_ko_2 = '미리 좌석을 예약하는 걸 깜빡했어요.', example_en_3 = 'Book early to get a cheaper price.', example_ko_3 = '일찍 예약할수록 더 저렴해요.', example_en_4 = 'Did you book the tickets online?', example_ko_4 = '티켓 온라인으로 예약하셨어요?', example_en_5 = 'You can book a tour at the front desk.', example_ko_5 = '프런트에서 투어를 예약할 수 있어요.' WHERE id = 'w_travel_A1_07';
UPDATE words SET example_en_2 = 'We are going to stay at a hostel.', example_ko_2 = '호스텔에 머물 거예요.', example_en_3 = 'How many nights would you like to stay?', example_ko_3 = '몇 박 머무실 건가요?', example_en_4 = 'She decided to stay one more day.', example_ko_4 = '그녀는 하루 더 머물기로 했어요.', example_en_5 = 'I always stay near the city centre.', example_ko_5 = '저는 항상 시내 중심가 근처에 머물러요.' WHERE id = 'w_travel_A1_08';
UPDATE words SET example_en_2 = 'Let''s go to the beach this afternoon.', example_ko_2 = '오늘 오후에 해변에 가요.', example_en_3 = 'We go abroad at least once a year.', example_ko_3 = '저희는 일 년에 적어도 한 번은 해외에 가요.', example_en_4 = 'Which way should we go?', example_ko_4 = '어느 쪽으로 가야 하나요?', example_en_5 = 'I go for a walk every morning.', example_ko_5 = '저는 매일 아침 산책을 가요.' WHERE id = 'w_travel_A1_09';
UPDATE words SET example_en_2 = 'Have you ever visited New York?', example_ko_2 = '뉴욕을 방문해 본 적 있으세요?', example_en_3 = 'We plan to visit as many countries as possible.', example_ko_3 = '가능한 한 많은 나라를 방문할 계획이에요.', example_en_4 = 'You should visit the local market.', example_ko_4 = '현지 시장을 방문해 보세요.', example_en_5 = 'How long did you visit for?', example_ko_5 = '얼마 동안 방문하셨어요?' WHERE id = 'w_travel_A1_10';
UPDATE words SET example_en_2 = 'I need to print my ticket before boarding.', example_ko_2 = '탑승 전에 티켓을 출력해야 해요.', example_en_3 = 'Can I show my ticket on my phone?', example_ko_3 = '티켓을 휴대폰으로 보여드려도 되나요?', example_en_4 = 'The ticket includes a free meal.', example_ko_4 = '티켓에 무료 식사가 포함되어 있어요.', example_en_5 = 'I lost my ticket — what should I do?', example_ko_5 = '티켓을 잃어버렸는데 어떻게 해야 하나요?' WHERE id = 'w_travel_A1_11';
UPDATE words SET example_en_2 = 'Does this bus stop at the museum?', example_ko_2 = '이 버스 박물관에서 서나요?', example_en_3 = 'The last bus leaves at midnight.', example_ko_3 = '막차는 자정에 출발해요.', example_en_4 = 'Buses run every fifteen minutes here.', example_ko_4 = '여기서는 버스가 15분마다 다녀요.', example_en_5 = 'Is there a bus to the airport?', example_ko_5 = '공항 가는 버스 있나요?' WHERE id = 'w_travel_A1_12';
UPDATE words SET example_en_2 = 'Which train goes to Edinburgh?', example_ko_2 = '에든버러 가는 기차가 어떤 건가요?', example_en_3 = 'The train journey takes about three hours.', example_ko_3 = '기차로 약 3시간 걸려요.', example_en_4 = 'I prefer travelling by train to flying.', example_ko_4 = '저는 비행기보다 기차 여행을 더 좋아해요.', example_en_5 = 'The train arrives on platform four.', example_ko_5 = '기차가 4번 플랫폼에 도착해요.' WHERE id = 'w_travel_A1_13';
UPDATE words SET example_en_2 = 'The road to the village is very narrow.', example_ko_2 = '마을로 가는 길이 정말 좁아요.', example_en_3 = 'Take this road and you will see the hotel on your left.', example_ko_3 = '이 길을 따라가면 왼쪽에 호텔이 보여요.', example_en_4 = 'The road was closed because of snow.', example_ko_4 = '눈 때문에 길이 막혔어요.', example_en_5 = 'Is this road safe to drive at night?', example_ko_5 = '이 길은 밤에 운전해도 안전한가요?' WHERE id = 'w_travel_A1_14';
UPDATE words SET example_en_2 = 'The post office is on your left after the bridge.', example_ko_2 = '다리를 지나면 왼쪽에 우체국이 있어요.', example_en_3 = 'Keep going left until you reach the park.', example_ko_3 = '공원이 나올 때까지 왼쪽으로 계속 가세요.', example_en_4 = 'Take the first left after the traffic lights.', example_ko_4 = '신호등 지나서 첫 번째에서 왼쪽으로 도세요.', example_en_5 = 'Is it on the left or the right?', example_ko_5 = '왼쪽이에요, 아니면 오른쪽이에요?' WHERE id = 'w_travel_A1_15';
UPDATE words SET example_en_2 = 'Turn right at the roundabout.', example_ko_2 = '로터리에서 오른쪽으로 도세요.', example_en_3 = 'The café is on the right side of the street.', example_ko_3 = '카페는 길 오른쪽에 있어요.', example_en_4 = 'Go straight and then turn right.', example_ko_4 = '직진하다가 오른쪽으로 도세요.', example_en_5 = 'Make sure you turn right at the junction.', example_ko_5 = '교차로에서 반드시 오른쪽으로 도세요.' WHERE id = 'w_travel_A1_16';
UPDATE words SET example_en_2 = 'The next town is quite far from here.', example_ko_2 = '다음 마을은 여기서 꽤 멀어요.', example_en_3 = 'How far is it to the nearest petrol station?', example_ko_3 = '가장 가까운 주유소까지 얼마나 멀어요?', example_en_4 = 'She walked far without stopping.', example_ko_4 = '그녀는 쉬지 않고 멀리 걸었어요.', example_en_5 = 'The resort is far from the city but worth the journey.', example_ko_5 = '리조트는 도시에서 멀지만 가볼 만해요.' WHERE id = 'w_travel_A1_17';
UPDATE words SET example_en_2 = 'The nearest ATM is just around the corner.', example_ko_2 = '가장 가까운 ATM은 바로 모퉁이 돌면 있어요.', example_en_3 = 'Is the train station near the hotel?', example_ko_3 = '기차역이 호텔 근처에 있나요?', example_en_4 = 'We found a nice restaurant near the square.', example_ko_4 = '광장 근처에서 좋은 식당을 발견했어요.', example_en_5 = 'Stay near the group so you don''t get lost.', example_ko_5 = '길 잃지 않도록 그룹 근처에 있으세요.' WHERE id = 'w_travel_A1_18';
UPDATE words SET example_en_2 = 'The park is open from eight to six.', example_ko_2 = '공원은 8시부터 6시까지 열어요.', example_en_3 = 'Is the gift shop open on Mondays?', example_ko_3 = '기념품 가게 월요일에 열어요?', example_en_4 = 'They open the gates at nine sharp.', example_ko_4 = '정각 9시에 문을 열어요.', example_en_5 = 'The café stays open until late.', example_ko_5 = '카페는 늦게까지 영업해요.' WHERE id = 'w_travel_A1_19';
UPDATE words SET example_en_2 = 'The tourist office is closed on Mondays.', example_ko_2 = '관광 안내소는 월요일에 닫아요.', example_en_3 = 'The road is closed for repairs.', example_ko_3 = '도로가 공사로 통제되고 있어요.', example_en_4 = 'Unfortunately, the museum is closed today.', example_ko_4 = '안타깝게도 박물관이 오늘은 문을 닫았어요.', example_en_5 = 'Check the website to see if they are closed.', example_ko_5 = '웹사이트에서 휴무 여부를 확인하세요.' WHERE id = 'w_travel_A1_20';
UPDATE words SET example_en_2 = 'Children under five travel free.', example_ko_2 = '5세 미만 어린이는 무료로 이용할 수 있어요.', example_en_3 = 'Is the Wi-Fi free in this hotel?', example_ko_3 = '이 호텔 와이파이 무료인가요?', example_en_4 = 'The map is free — take one.', example_ko_4 = '지도는 무료예요. 하나 가져가세요.', example_en_5 = 'Entry to the cathedral is free.', example_ko_5 = '성당 입장은 무료예요.' WHERE id = 'w_travel_A1_21';
UPDATE words SET example_en_2 = 'The price of petrol is very high here.', example_ko_2 = '여기 기름값이 정말 비싸요.', example_en_3 = 'Can you tell me the price per night?', example_ko_3 = '1박 가격을 알려주실 수 있나요?', example_en_4 = 'The price went down during low season.', example_ko_4 = '비수기에는 가격이 내려가요.', example_en_5 = 'What is the price for a family ticket?', example_ko_5 = '가족 티켓 가격이 얼마예요?' WHERE id = 'w_travel_A1_22';
UPDATE words SET example_en_2 = 'This city is famous for its festivals.', example_ko_2 = '이 도시는 축제로 유명해요.', example_en_3 = 'I love exploring a new city on foot.', example_ko_3 = '새로운 도시를 걸어서 탐험하는 걸 좋아해요.', example_en_4 = 'The city centre is very busy at weekends.', example_ko_4 = '주말에는 시내 중심가가 매우 붐벼요.', example_en_5 = 'Which city are you flying to?', example_ko_5 = '어느 도시로 비행기를 타세요?' WHERE id = 'w_travel_A1_23';
UPDATE words SET example_en_2 = 'Which country do you want to visit most?', example_ko_2 = '가장 방문하고 싶은 나라가 어디예요?', example_en_3 = 'Every country has its own culture.', example_ko_3 = '모든 나라에는 고유한 문화가 있어요.', example_en_4 = 'This country is known for its beautiful scenery.', example_ko_4 = '이 나라는 아름다운 풍경으로 유명해요.', example_en_5 = 'I have travelled to over twenty countries.', example_ko_5 = '저는 20개가 넘는 나라를 여행했어요.' WHERE id = 'w_travel_A1_24';
UPDATE words SET example_en_2 = 'Can you call a taxi for me, please?', example_ko_2 = '택시 좀 불러 주실 수 있나요?', example_en_3 = 'The taxi driver knew every street in the city.', example_ko_3 = '그 택시 기사는 시내 모든 길을 알고 있었어요.', example_en_4 = 'How much does a taxi to the airport cost?', example_ko_4 = '공항까지 택시비가 얼마예요?', example_en_5 = 'I took a taxi because the metro was crowded.', example_ko_5 = '지하철이 너무 붐벼서 택시를 탔어요.' WHERE id = 'w_travel_A1_25';
UPDATE words SET example_en_2 = 'We decided to walk instead of taking the bus.', example_ko_2 = '버스 대신 걷기로 했어요.', example_en_3 = 'It takes about twenty minutes to walk there.', example_ko_3 = '걸어서 거기까지 약 20분 걸려요.', example_en_4 = 'I love to walk along the seafront.', example_ko_4 = '해안가를 따라 걷는 걸 좋아해요.', example_en_5 = 'Is it safe to walk here at night?', example_ko_5 = '여기 밤에 걸어다녀도 안전한가요?' WHERE id = 'w_travel_A1_26';
UPDATE words SET example_en_2 = 'Could you help me with my luggage?', example_ko_2 = '짐 옮기는 것 좀 도와주실 수 있나요?', example_en_3 = 'The locals were very happy to help tourists.', example_ko_3 = '현지인들이 여행객들을 기꺼이 도와줬어요.', example_en_4 = 'Is there anyone who can help me find my hotel?', example_ko_4 = '호텔 찾는 것 좀 도와주실 분 계세요?', example_en_5 = 'The information desk staff helped us plan our day.', example_ko_5 = '안내 데스크 직원이 하루 일정을 짜는 것을 도와줬어요.' WHERE id = 'w_travel_A1_27';
UPDATE words SET example_en_2 = 'My camera battery is dead.', example_ko_2 = '카메라 배터리가 방전됐어요.', example_en_3 = 'Can I use your camera for a moment?', example_ko_3 = '카메라 잠깐 써도 될까요?', example_en_4 = 'I bought a new camera for this trip.', example_ko_4 = '이번 여행을 위해 새 카메라를 샀어요.', example_en_5 = 'The photos from my camera came out beautifully.', example_ko_5 = '카메라로 찍은 사진이 정말 잘 나왔어요.' WHERE id = 'w_travel_A1_28';
UPDATE words SET example_en_2 = 'I don''t have enough money for a taxi.', example_ko_2 = '택시를 탈 돈이 충분하지 않아요.', example_en_3 = 'Do they accept foreign money here?', example_ko_3 = '여기서 외국 화폐를 받나요?', example_en_4 = 'Save your money for the shopping district.', example_ko_4 = '쇼핑 구역을 위해 돈을 아껴두세요.', example_en_5 = 'Where can I exchange my money?', example_ko_5 = '환전은 어디서 할 수 있나요?' WHERE id = 'w_travel_A1_29';
UPDATE words SET example_en_2 = 'I can''t find the key to my room.', example_ko_2 = '방 열쇠를 찾을 수가 없어요.', example_en_3 = 'Please hand in your key when you check out.', example_ko_3 = '체크아웃할 때 열쇠를 반납해 주세요.', example_en_4 = 'The key card stopped working.', example_ko_4 = '카드 키가 작동하지 않아요.', example_en_5 = 'Did you leave the key at reception?', example_ko_5 = '프런트에 열쇠를 맡겨두셨나요?' WHERE id = 'w_travel_A1_30';
UPDATE words SET example_en_2 = 'Make sure you drink enough water in the heat.', example_ko_2 = '더운 날씨에 물을 충분히 마시세요.', example_en_3 = 'Is the tap water safe to drink here?', example_ko_3 = '여기 수돗물 마셔도 괜찮나요?', example_en_4 = 'I always carry a bottle of water with me.', example_ko_4 = '항상 물 한 병을 들고 다녀요.', example_en_5 = 'Where can I fill up my water bottle?', example_ko_5 = '물병은 어디서 채울 수 있나요?' WHERE id = 'w_travel_A1_31';
UPDATE words SET example_en_2 = 'Street food in Bangkok is amazing.', example_ko_2 = '방콕의 길거리 음식은 정말 맛있어요.', example_en_3 = 'Can you recommend any local food?', example_ko_3 = '현지 음식 추천해 주실 수 있나요?', example_en_4 = 'The hotel serves food all day.', example_ko_4 = '그 호텔은 하루 종일 음식을 제공해요.', example_en_5 = 'I always try the local food wherever I go.', example_ko_5 = '어디를 가든 항상 현지 음식을 먹어봐요.' WHERE id = 'w_travel_A1_32';
UPDATE words SET example_en_2 = 'The airport has four international terminals.', example_ko_2 = '공항에 국제선 터미널이 네 개 있어요.', example_en_3 = 'How far is the hotel from the airport?', example_ko_3 = '호텔에서 공항까지 얼마나 멀어요?', example_en_4 = 'I always get nervous at the airport.', example_ko_4 = '공항에만 오면 항상 긴장돼요.', example_en_5 = 'Is there a free shuttle from the airport?', example_ko_5 = '공항에서 무료 셔틀버스가 있나요?' WHERE id = 'w_travel_A1_33';
UPDATE words SET example_en_2 = 'We arrived late and missed the last train.', example_ko_2 = '늦게 도착해서 막차를 놓쳤어요.', example_en_3 = 'I was late because of the traffic.', example_ko_3 = '교통 체증 때문에 늦었어요.', example_en_4 = 'Don''t be late for your flight.', example_ko_4 = '비행기 시간에 늦지 마세요.', example_en_5 = 'The hotel is still open, even if you arrive late.', example_ko_5 = '늦게 도착하더라도 호텔은 열려 있어요.' WHERE id = 'w_travel_A1_34';
UPDATE words SET example_en_2 = 'It is better to arrive early at the airport.', example_ko_2 = '공항에는 일찍 도착하는 게 좋아요.', example_en_3 = 'We woke up early to catch the sunrise.', example_ko_3 = '일출을 보려고 일찍 일어났어요.', example_en_4 = 'The early bus is less crowded.', example_ko_4 = '일찍 출발하는 버스는 덜 붐벼요.', example_en_5 = 'Book early and save money on flights.', example_ko_5 = '일찍 예약하면 항공권을 저렴하게 살 수 있어요.' WHERE id = 'w_travel_A1_35';

-- ══════════════════════════════════════
-- A2 — 35 WORDS
-- ══════════════════════════════════════
UPDATE words SET example_en_2 = 'I booked a sightseeing tour of the city.', example_ko_2 = '시내 관광 투어를 예약했어요.', example_en_3 = 'The guided tour lasts about two hours.', example_ko_3 = '가이드 투어는 약 두 시간 걸려요.', example_en_4 = 'Do you offer a tour in Korean?', example_ko_4 = '한국어로 진행되는 투어가 있나요?', example_en_5 = 'The tour included entrance to all the major sites.', example_ko_5 = '투어에 주요 명소 입장이 모두 포함되어 있었어요.' WHERE id = 'w_travel_A2_01';
UPDATE words SET example_en_2 = 'The tourist information centre is near the station.', example_ko_2 = '관광 안내소가 역 근처에 있어요.', example_en_3 = 'As a tourist, I found the city very easy to navigate.', example_ko_3 = '관광객으로서 이 도시는 정말 다니기 편했어요.', example_en_4 = 'The local market is popular with tourists.', example_ko_4 = '현지 시장은 관광객들에게 인기가 많아요.', example_en_5 = 'Many tourists visit this temple every year.', example_ko_5 = '매년 많은 관광객이 이 사원을 방문해요.' WHERE id = 'w_travel_A2_02';
UPDATE words SET example_en_2 = 'Do I need a visa to enter this country?', example_ko_2 = '이 나라에 입국하려면 비자가 필요한가요?', example_en_3 = 'I applied for my visa three weeks in advance.', example_ko_3 = '3주 전에 비자를 신청했어요.', example_en_4 = 'My visa is valid for thirty days.', example_ko_4 = '제 비자는 30일간 유효해요.', example_en_5 = 'You can get a visa on arrival at the airport.', example_ko_5 = '공항에서 도착 비자를 받을 수 있어요.' WHERE id = 'w_travel_A2_03';
UPDATE words SET example_en_2 = 'We spent the whole day sightseeing.', example_ko_2 = '하루 종일 관광을 했어요.', example_en_3 = 'What sightseeing spots do you recommend?', example_ko_3 = '어떤 관광 명소를 추천하세요?', example_en_4 = 'The sightseeing bus stops at all the main attractions.', example_ko_4 = '관광 버스는 주요 명소에 모두 서요.', example_en_5 = 'Is sightseeing by boat possible here?', example_ko_5 = '여기서 보트로 관광하는 것도 가능한가요?' WHERE id = 'w_travel_A2_04';
UPDATE words SET example_en_2 = 'I bought a souvenir for my parents.', example_ko_2 = '부모님께 드릴 기념품을 샀어요.', example_en_3 = 'The souvenir shop is near the main entrance.', example_ko_3 = '기념품 가게는 정문 근처에 있어요.', example_en_4 = 'What is a typical souvenir from this region?', example_ko_4 = '이 지역의 대표적인 기념품이 뭐예요?', example_en_5 = 'She collects fridge magnets as souvenirs.', example_ko_5 = '그녀는 기념품으로 냉장고 자석을 수집해요.' WHERE id = 'w_travel_A2_05';
UPDATE words SET example_en_2 = 'Where can I exchange currency around here?', example_ko_2 = '이 근처에서 환전할 수 있는 곳이 어디예요?', example_en_3 = 'The exchange rate today is quite good.', example_ko_3 = '오늘 환율이 꽤 좋아요.', example_en_4 = 'I want to exchange pounds for euros.', example_ko_4 = '파운드를 유로로 환전하고 싶어요.', example_en_5 = 'Is there a currency exchange desk at the airport?', example_ko_5 = '공항에 환전 데스크가 있나요?' WHERE id = 'w_travel_A2_06';
UPDATE words SET example_en_2 = 'Online check-in saves a lot of time.', example_ko_2 = '온라인 체크인을 하면 시간을 많이 절약할 수 있어요.', example_en_3 = 'What time does check-in start?', example_ko_3 = '체크인은 몇 시부터 시작하나요?', example_en_4 = 'I completed check-in from my phone.', example_ko_4 = '휴대폰으로 체크인을 완료했어요.', example_en_5 = 'The check-in desk is on the second floor.', example_ko_5 = '체크인 데스크는 2층에 있어요.' WHERE id = 'w_travel_A2_07';
UPDATE words SET example_en_2 = 'The hostel has shared dormitory rooms.', example_ko_2 = '그 호스텔에는 공용 도미토리 방이 있어요.', example_en_3 = 'Staying at a hostel is a great way to meet other travellers.', example_ko_3 = '호스텔에 머무는 것은 다른 여행자들을 만나기에 좋아요.', example_en_4 = 'The hostel was clean and well located.', example_ko_4 = '호스텔이 깨끗하고 위치도 좋았어요.', example_en_5 = 'I prefer a hostel to a hotel when I travel alone.', example_ko_5 = '혼자 여행할 때는 호텔보다 호스텔을 선호해요.' WHERE id = 'w_travel_A2_08';
UPDATE words SET example_en_2 = 'Our guide spoke English and French.', example_ko_2 = '가이드가 영어와 프랑스어를 했어요.', example_en_3 = 'The audio guide costs five euros.', example_ko_3 = '오디오 가이드는 5유로예요.', example_en_4 = 'Do you need a guide for the cave tour?', example_ko_4 = '동굴 투어에 가이드가 필요한가요?', example_en_5 = 'The guidebook was more helpful than the guide.', example_ko_5 = '가이드보다 여행 안내서가 더 도움이 됐어요.' WHERE id = 'w_travel_A2_09';
UPDATE words SET example_en_2 = 'I love to explore local neighbourhoods.', example_ko_2 = '현지 동네를 탐험하는 걸 좋아해요.', example_en_3 = 'We explored the ruins on our own.', example_ko_3 = '유적지를 직접 둘러봤어요.', example_en_4 = 'It is fun to explore a city without a map.', example_ko_4 = '지도 없이 도시를 돌아다니는 것도 재미있어요.', example_en_5 = 'Are there any hidden spots worth exploring nearby?', example_ko_5 = '근처에 탐험해 볼 만한 숨겨진 장소가 있나요?' WHERE id = 'w_travel_A2_10';
UPDATE words SET example_en_2 = 'What time does the ferry arrive?', example_ko_2 = '페리는 몇 시에 도착하나요?', example_en_3 = 'We arrive in Rome at midday.', example_ko_3 = '저희는 정오에 로마에 도착해요.', example_en_4 = 'Please inform us when you arrive.', example_ko_4 = '도착하면 알려 주세요.', example_en_5 = 'The guests are expected to arrive by evening.', example_ko_5 = '손님들은 저녁까지 도착할 예정이에요.' WHERE id = 'w_travel_A2_11';
UPDATE words SET example_en_2 = 'What time does the last train depart?', example_ko_2 = '막차는 몇 시에 출발하나요?', example_en_3 = 'We depart for Paris tomorrow morning.', example_ko_3 = '내일 아침에 파리로 출발해요.', example_en_4 = 'The ship will depart from pier six.', example_ko_4 = '배는 6번 부두에서 출발해요.', example_en_5 = 'Please be at the gate before the flight departs.', example_ko_5 = '비행기 출발 전에 게이트에 와 계세요.' WHERE id = 'w_travel_A2_12';
UPDATE words SET example_en_2 = 'Which platform does the London train leave from?', example_ko_2 = '런던행 기차는 몇 번 플랫폼에서 출발하나요?', example_en_3 = 'The departure platform was changed at the last minute.', example_ko_3 = '출발 플랫폼이 막판에 바뀌었어요.', example_en_4 = 'I waited on the platform for twenty minutes.', example_ko_4 = '플랫폼에서 20분 동안 기다렸어요.', example_en_5 = 'Please stand back from the edge of the platform.', example_ko_5 = '플랫폼 가장자리에서 뒤로 물러서 주세요.' WHERE id = 'w_travel_A2_13';
UPDATE words SET example_en_2 = 'I''d like a single room for two nights.', example_ko_2 = '1인실 2박 예약하고 싶어요.', example_en_3 = 'A single ticket to Edinburgh, please.', example_ko_3 = '에든버러까지 편도 티켓 한 장 주세요.', example_en_4 = 'Is the single room cheaper than the double?', example_ko_4 = '1인실이 2인실보다 저렴한가요?', example_en_5 = 'She prefers travelling single to joining a group tour.', example_ko_5 = '그녀는 단체 투어보다 혼자 여행하는 걸 선호해요.' WHERE id = 'w_travel_A2_14';
UPDATE words SET example_en_2 = 'A return ticket is cheaper than two singles.', example_ko_2 = '왕복 티켓이 편도 두 장보다 저렴해요.', example_en_3 = 'I need to return to the hotel by noon.', example_ko_3 = '정오까지 호텔로 돌아와야 해요.', example_en_4 = 'When does the tour group return?', example_ko_4 = '투어 그룹은 언제 돌아오나요?', example_en_5 = 'She decided not to return — she loved it there too much.', example_ko_5 = '그녀는 거기가 너무 좋아서 돌아오지 않기로 했어요.' WHERE id = 'w_travel_A2_15';
UPDATE words SET example_en_2 = 'Please check the schedule before you book.', example_ko_2 = '예약 전에 일정을 확인해 주세요.', example_en_3 = 'The bus schedule changes on weekends.', example_ko_3 = '버스 시간표는 주말에 바뀌어요.', example_en_4 = 'Our schedule is very busy this week.', example_ko_4 = '이번 주는 일정이 아주 빡빡해요.', example_en_5 = 'Is there a schedule available in English?', example_ko_5 = '영어로 된 시간표가 있나요?' WHERE id = 'w_travel_A2_16';
UPDATE words SET example_en_2 = 'I had to cancel my trip because of work.', example_ko_2 = '일 때문에 여행을 취소해야 했어요.', example_en_3 = 'Can I cancel my reservation without a fee?', example_ko_3 = '수수료 없이 예약을 취소할 수 있나요?', example_en_4 = 'The event was cancelled due to bad weather.', example_ko_4 = '행사가 악천후로 취소됐어요.', example_en_5 = 'You must cancel at least 48 hours in advance.', example_ko_5 = '최소 48시간 전에 취소하셔야 해요.' WHERE id = 'w_travel_A2_17';
UPDATE words SET example_en_2 = 'Please confirm your booking by email.', example_ko_2 = '이메일로 예약을 확인해 주세요.', example_en_3 = 'Can you confirm the check-in time?', example_ko_3 = '체크인 시간을 확인해 주실 수 있나요?', example_en_4 = 'We will confirm your reservation within 24 hours.', example_ko_4 = '24시간 이내에 예약을 확인해 드릴게요.', example_en_5 = 'I need to confirm my flight details.', example_ko_5 = '항공편 세부 정보를 확인해야 해요.' WHERE id = 'w_travel_A2_18';
UPDATE words SET example_en_2 = 'The entrance to the park is around the corner.', example_ko_2 = '공원 입구가 모퉁이 돌면 있어요.', example_en_3 = 'Entrance is free for children under twelve.', example_ko_3 = '12세 미만 어린이는 입장이 무료예요.', example_en_4 = 'You must show your ticket at the entrance.', example_ko_4 = '입구에서 티켓을 보여줘야 해요.', example_en_5 = 'The main entrance is on the north side.', example_ko_5 = '정문은 북쪽에 있어요.' WHERE id = 'w_travel_A2_19';
UPDATE words SET example_en_2 = 'The exit is at the back of the building.', example_ko_2 = '출구는 건물 뒤편에 있어요.', example_en_3 = 'Please use the emergency exit if needed.', example_ko_3 = '필요하면 비상구를 이용하세요.', example_en_4 = 'I could not find the exit from the station.', example_ko_4 = '역에서 출구를 찾을 수가 없었어요.', example_en_5 = 'Follow the exit signs to leave the building.', example_ko_5 = '건물을 나가려면 출구 표지판을 따라가세요.' WHERE id = 'w_travel_A2_20';
UPDATE words SET example_en_2 = 'Can you take a photo of us, please?', example_ko_2 = '저희 사진 좀 찍어 주실 수 있나요?', example_en_3 = 'This photo turned out really well.', example_ko_3 = '이 사진 정말 잘 나왔어요.', example_en_4 = 'Photography is not allowed inside the museum.', example_ko_4 = '박물관 내부에서는 사진 촬영이 금지돼 있어요.', example_en_5 = 'I posted all my travel photos online.', example_ko_5 = '여행 사진을 전부 온라인에 올렸어요.' WHERE id = 'w_travel_A2_21';
UPDATE words SET example_en_2 = 'Would you like to share a taxi?', example_ko_2 = '택시를 같이 탈까요?', example_en_3 = 'She loves to share travel tips online.', example_ko_3 = '그녀는 온라인에 여행 팁을 공유하는 걸 좋아해요.', example_en_4 = 'We can share a room to save money.', example_ko_4 = '돈을 아끼려고 방을 같이 쓸 수 있어요.', example_en_5 = 'Please share the location of the hotel with me.', example_ko_5 = '호텔 위치를 저에게 공유해 주세요.' WHERE id = 'w_travel_A2_22';
UPDATE words SET example_en_2 = 'Is this neighbourhood safe at night?', example_ko_2 = '이 동네 밤에 안전한가요?', example_en_3 = 'Keep your passport in a safe place.', example_ko_3 = '여권을 안전한 곳에 보관하세요.', example_en_4 = 'The hotel has a safe in every room.', example_ko_4 = '모든 방에 금고가 있어요.', example_en_5 = 'Is it safe to drink the water here?', example_ko_5 = '여기 물 마셔도 안전한가요?' WHERE id = 'w_travel_A2_23';
UPDATE words SET example_en_2 = 'Can you recommend a good restaurant nearby?', example_ko_2 = '근처에 좋은 식당 추천해 주실 수 있나요?', example_en_3 = 'I always ask locals for recommendations.', example_ko_3 = '저는 항상 현지인에게 추천을 받아요.', example_en_4 = 'Highly recommended — do not miss it.', example_ko_4 = '강력 추천이에요. 꼭 가보세요.', example_en_5 = 'Which area of the city would you recommend for sightseeing?', example_ko_5 = '관광하기에 어느 지역을 추천하세요?' WHERE id = 'w_travel_A2_24';
UPDATE words SET example_en_2 = 'I got lost in the old part of town.', example_ko_2 = '구시가지에서 길을 잃었어요.', example_en_3 = 'My wallet was lost during the tour.', example_ko_3 = '투어 중에 지갑을 잃어버렸어요.', example_en_4 = 'Do you have a lost and found office here?', example_ko_4 = '여기 분실물 보관소가 있나요?', example_en_5 = 'He felt completely lost without a map.', example_ko_5 = '지도 없이는 완전히 길을 잃은 것 같았어요.' WHERE id = 'w_travel_A2_25';
UPDATE words SET example_en_2 = 'Go straight ahead and you will see the square.', example_ko_2 = '직진하면 광장이 나와요.', example_en_3 = 'The road runs straight for about five kilometres.', example_ko_3 = '도로가 약 5킬로미터 직선으로 이어져요.', example_en_4 = 'Keep going straight until the traffic lights.', example_ko_4 = '신호등까지 계속 직진하세요.', example_en_5 = 'The path is straight and easy to follow.', example_ko_5 = '길이 직선이라 따라가기 쉬워요.' WHERE id = 'w_travel_A2_26';
UPDATE words SET example_en_2 = 'Turn left at the corner of the street.', example_ko_2 = '길 모퉁이에서 왼쪽으로 도세요.', example_en_3 = 'The café is just around the corner.', example_ko_3 = '카페가 모퉁이 바로 돌면 있어요.', example_en_4 = 'Wait for me on the corner by the bank.', example_ko_4 = '은행 옆 모퉁이에서 기다려 주세요.', example_en_5 = 'I bumped into an old friend on the corner.', example_ko_5 = '모퉁이에서 옛 친구를 우연히 만났어요.' WHERE id = 'w_travel_A2_27';
UPDATE words SET example_en_2 = 'Could I have a receipt for that?', example_ko_2 = '영수증 받을 수 있을까요?', example_en_3 = 'Keep your receipt in case you need a refund.', example_ko_3 = '환불이 필요할 경우를 대비해 영수증을 보관하세요.', example_en_4 = 'The receipt shows all the charges clearly.', example_ko_4 = '영수증에 모든 요금이 명확하게 나와 있어요.', example_en_5 = 'I lost my receipt for the tour.', example_ko_5 = '투어 영수증을 잃어버렸어요.' WHERE id = 'w_travel_A2_28';
UPDATE words SET example_en_2 = 'Is airport transfer included in the package?', example_ko_2 = '패키지에 공항 이동이 포함되어 있나요?', example_en_3 = 'Taxes are included in the price.', example_ko_3 = '세금은 가격에 포함되어 있어요.', example_en_4 = 'Is Wi-Fi included in the room rate?', example_ko_4 = '객실 요금에 와이파이가 포함되어 있나요?', example_en_5 = 'All meals are included in the tour price.', example_ko_5 = '투어 가격에 모든 식사가 포함되어 있어요.' WHERE id = 'w_travel_A2_29';
UPDATE words SET example_en_2 = 'Is there a direct train to the airport?', example_ko_2 = '공항까지 직행 기차가 있나요?', example_en_3 = 'I prefer a direct flight even if it costs more.', example_ko_3 = '더 비싸더라도 직항을 선호해요.', example_en_4 = 'The direct route saves about an hour.', example_ko_4 = '직행 경로로 가면 약 한 시간이 절약돼요.', example_en_5 = 'There is no direct bus — you need to change.', example_ko_5 = '직행 버스가 없어서 환승해야 해요.' WHERE id = 'w_travel_A2_30';
UPDATE words SET example_en_2 = 'My connecting flight was cancelled.', example_ko_2 = '환승 항공편이 취소됐어요.', example_en_3 = 'I missed the connection because of the delay.', example_ko_3 = '지연 때문에 연결 편을 놓쳤어요.', example_en_4 = 'The bus connection is at the central terminal.', example_ko_4 = '버스 환승은 중앙 터미널에서 해요.', example_en_5 = 'There is a good train connection every two hours.', example_ko_5 = '두 시간마다 좋은 기차 연결편이 있어요.' WHERE id = 'w_travel_A2_31';
UPDATE words SET example_en_2 = 'Our flight was delayed by three hours.', example_ko_2 = '항공편이 세 시간 지연됐어요.', example_en_3 = 'Bad weather caused a major delay.', example_ko_3 = '악천후로 큰 지연이 발생했어요.', example_en_4 = 'Is there any delay on the metro today?', example_ko_4 = '오늘 지하철 지연이 있나요?', example_en_5 = 'We apologise for the delay in departure.', example_ko_5 = '출발 지연에 대해 사과드려요.' WHERE id = 'w_travel_A2_32';
UPDATE words SET example_en_2 = 'The beds in this hostel are very comfortable.', example_ko_2 = '이 호스텔 침대가 정말 편안해요.', example_en_3 = 'I want a comfortable seat for the long journey.', example_ko_3 = '긴 여정을 위해 편안한 좌석을 원해요.', example_en_4 = 'The first-class carriage is more comfortable.', example_ko_4 = '일등석이 더 편안해요.', example_en_5 = 'Are you comfortable with the room temperature?', example_ko_5 = '실내 온도가 편안하세요?' WHERE id = 'w_travel_A2_33';
UPDATE words SET example_en_2 = 'The beach was extremely crowded in August.', example_ko_2 = '8월에 해변이 너무 붐볐어요.', example_en_3 = 'The platform is very crowded during rush hour.', example_ko_3 = '출퇴근 시간에 플랫폼이 매우 붐벼요.', example_en_4 = 'I try to avoid crowded tourist spots.', example_ko_4 = '붐비는 관광지는 피하려고 해요.', example_en_5 = 'The market is less crowded in the morning.', example_ko_5 = '시장은 오전에 덜 붐벼요.' WHERE id = 'w_travel_A2_34';
UPDATE words SET example_en_2 = 'I prefer to eat at local restaurants, not tourist traps.', example_ko_2 = '관광객 식당보다 현지 식당에서 먹는 게 좋아요.', example_en_3 = 'Ask a local — they always know best.', example_ko_3 = '현지인에게 물어보세요. 항상 제일 잘 알아요.', example_en_4 = 'The local bus is cheaper than a taxi.', example_ko_4 = '현지 버스가 택시보다 저렴해요.', example_en_5 = 'What is the local food specialty here?', example_ko_5 = '여기 현지 음식 특산물이 뭐예요?' WHERE id = 'w_travel_A2_35';

-- ══════════════════════════════════════
-- B1 — 35 WORDS
-- ══════════════════════════════════════
UPDATE words SET example_en_2 = 'We have not sorted out accommodation yet.', example_ko_2 = '아직 숙소를 정하지 못했어요.', example_en_3 = 'The accommodation is included in the tour price.', example_ko_3 = '숙박은 투어 가격에 포함되어 있어요.', example_en_4 = 'Budget accommodation can still be comfortable.', example_ko_4 = '저렴한 숙소도 충분히 편안할 수 있어요.', example_en_5 = 'Have you found suitable accommodation for your stay?', example_ko_5 = '숙박할 적절한 숙소를 찾으셨나요?' WHERE id = 'w_travel_B1_01';
UPDATE words SET example_en_2 = 'Our itinerary includes three cities in five days.', example_ko_2 = '일정에 5일 동안 세 도시가 포함되어 있어요.', example_en_3 = 'I like to keep a flexible itinerary when I travel.', example_ko_3 = '여행할 때 유연한 일정을 유지하는 걸 좋아해요.', example_en_4 = 'The tour operator sent us the full itinerary.', example_ko_4 = '여행사에서 전체 일정을 보내줬어요.', example_en_5 = 'Can you adjust the itinerary to include a day trip?', example_ko_5 = '당일치기 여행을 포함하도록 일정을 조정할 수 있나요?' WHERE id = 'w_travel_B1_02';
UPDATE words SET example_en_2 = 'Jet lag made it hard to sleep at night.', example_ko_2 = '시차 적응이 안 돼서 밤에 잠들기 힘들었어요.', example_en_3 = 'It took me three days to recover from jet lag.', example_ko_3 = '시차 적응에 3일이 걸렸어요.', example_en_4 = 'Drinking plenty of water helps with jet lag.', example_ko_4 = '물을 충분히 마시면 시차 극복에 도움이 돼요.', example_en_5 = 'Do you have any tips for dealing with jet lag?', example_ko_5 = '시차 적응하는 데 도움이 되는 팁이 있나요?' WHERE id = 'w_travel_B1_03';
UPDATE words SET example_en_2 = 'Always carry some local currency when travelling.', example_ko_2 = '여행할 때는 항상 현지 화폐를 좀 가지고 다니세요.', example_en_3 = 'What is the local currency in Thailand?', example_ko_3 = '태국의 현지 화폐가 뭐예요?', example_en_4 = 'The currency exchange rate changes daily.', example_ko_4 = '환율은 매일 바뀌어요.', example_en_5 = 'I prefer to carry currency rather than rely on cards.', example_ko_5 = '카드보다는 현금을 가지고 다니는 걸 선호해요.' WHERE id = 'w_travel_B1_04';
UPDATE words SET example_en_2 = 'Customs officers checked our bags at the border.', example_ko_2 = '세관 직원이 국경에서 짐을 검사했어요.', example_en_3 = 'Do I need to declare anything at customs?', example_ko_3 = '세관에서 신고해야 하는 것이 있나요?', example_en_4 = 'The customs process took over an hour.', example_ko_4 = '세관 절차가 한 시간이 넘게 걸렸어요.', example_en_5 = 'He had to pay customs duty on the goods.', example_ko_5 = '그는 물품에 대한 관세를 내야 했어요.' WHERE id = 'w_travel_B1_05';
UPDATE words SET example_en_2 = 'Boarding will begin thirty minutes before departure.', example_ko_2 = '탑승은 출발 30분 전에 시작해요.', example_en_3 = 'Please have your boarding pass ready.', example_ko_3 = '탑승권을 준비해 주세요.', example_en_4 = 'The boarding gate is at the far end of the terminal.', example_ko_4 = '탑승 게이트는 터미널 맨 끝에 있어요.', example_en_5 = 'Priority boarding is available for families with children.', example_ko_5 = '어린이를 동반한 가족은 우선 탑승이 가능해요.' WHERE id = 'w_travel_B1_06';
UPDATE words SET example_en_2 = 'We booked an excursion to the volcano.', example_ko_2 = '화산 탐방 소풍을 예약했어요.', example_en_3 = 'The excursion lasted a full day.', example_ko_3 = '소풍은 하루 종일 이어졌어요.', example_en_4 = 'Is this excursion suitable for children?', example_ko_4 = '이 소풍은 어린이에게 적합한가요?', example_en_5 = 'The boat excursion around the island was unforgettable.', example_ko_5 = '섬을 도는 보트 투어는 정말 잊을 수 없었어요.' WHERE id = 'w_travel_B1_07';
UPDATE words SET example_en_2 = 'I travelled across Europe with just a backpack.', example_ko_2 = '배낭 하나만 들고 유럽을 여행했어요.', example_en_3 = 'My backpack weighs twelve kilograms.', example_ko_3 = '배낭 무게가 12킬로그램이에요.', example_en_4 = 'Pack light — you only need a backpack.', example_ko_4 = '짐을 가볍게 챙기세요. 배낭 하나면 충분해요.', example_en_5 = 'He carried his laptop in his backpack everywhere.', example_ko_5 = '그는 어디에나 배낭에 노트북을 넣고 다녔어요.' WHERE id = 'w_travel_B1_08';
UPDATE words SET example_en_2 = 'The Eiffel Tower is a famous landmark.', example_ko_2 = '에펠탑은 유명한 랜드마크예요.', example_en_3 = 'Use the landmark as a meeting point.', example_ko_3 = '그 랜드마크를 만남의 장소로 이용하세요.', example_en_4 = 'The new bridge has become a local landmark.', example_ko_4 = '그 새 다리가 지역 랜드마크가 됐어요.', example_en_5 = 'I navigated the city using famous landmarks.', example_ko_5 = '유명한 랜드마크를 이용해 도시를 돌아다녔어요.' WHERE id = 'w_travel_B1_09';
UPDATE words SET example_en_2 = 'I bought a phrase book at the airport.', example_ko_2 = '공항에서 여행 회화책을 샀어요.', example_en_3 = 'A phrase book is essential for first-time visitors.', example_ko_3 = '처음 방문하는 분들에게 여행 회화책은 필수예요.', example_en_4 = 'The phrase book had useful expressions for the restaurant.', example_ko_4 = '여행 회화책에 식당에서 쓸 수 있는 유용한 표현이 있었어요.', example_en_5 = 'A good phrase book can help you connect with locals.', example_ko_5 = '좋은 여행 회화책은 현지인과 소통하는 데 도움이 돼요.' WHERE id = 'w_travel_B1_10';
UPDATE words SET example_en_2 = 'Make sure your travel insurance covers medical costs.', example_ko_2 = '여행자 보험이 의료비를 보장하는지 확인하세요.', example_en_3 = 'I always buy travel insurance before going abroad.', example_ko_3 = '해외에 나가기 전에 항상 여행자 보험에 가입해요.', example_en_4 = 'My insurance covered the cost of the cancelled flight.', example_ko_4 = '보험 덕분에 취소된 항공편 비용을 보상받았어요.', example_en_5 = 'Do not travel without insurance.', example_ko_5 = '보험 없이는 여행하지 마세요.' WHERE id = 'w_travel_B1_11';
UPDATE words SET example_en_2 = 'We crossed the border by train.', example_ko_2 = '기차로 국경을 넘었어요.', example_en_3 = 'There was a long queue at the border crossing.', example_ko_3 = '국경 검문소에 줄이 길게 늘어서 있었어요.', example_en_4 = 'The border between the two countries is open.', example_ko_4 = '두 나라 사이의 국경이 열려 있어요.', example_en_5 = 'Make sure you have the correct documents at the border.', example_ko_5 = '국경에서 올바른 서류를 갖추고 있는지 확인하세요.' WHERE id = 'w_travel_B1_12';
UPDATE words SET example_en_2 = 'Do I need a work permit to stay longer?', example_ko_2 = '더 오래 머물려면 취업 허가증이 필요한가요?', example_en_3 = 'I applied for a residence permit last week.', example_ko_3 = '지난주에 거주 허가증을 신청했어요.', example_en_4 = 'A fishing permit is required in this area.', example_ko_4 = '이 지역에서는 낚시 허가증이 필요해요.', example_en_5 = 'How long does it take to get a travel permit?', example_ko_5 = '여행 허가증을 받는 데 얼마나 걸리나요?' WHERE id = 'w_travel_B1_13';
UPDATE words SET example_en_2 = 'We had to take a detour because of roadworks.', example_ko_2 = '공사 때문에 우회로를 이용해야 했어요.', example_en_3 = 'The detour added an extra hour to our journey.', example_ko_3 = '우회로 때문에 여정이 한 시간 더 걸렸어요.', example_en_4 = 'A small detour took us to a beautiful waterfall.', example_ko_4 = '작은 우회로가 우리를 아름다운 폭포로 이끌었어요.', example_en_5 = 'Is there a detour around the flooded area?', example_ko_5 = '침수 지역을 우회할 수 있는 길이 있나요?' WHERE id = 'w_travel_B1_14';
UPDATE words SET example_en_2 = 'We kept to a strict budget throughout the trip.', example_ko_2 = '여행 내내 엄격한 예산을 지켰어요.', example_en_3 = 'I am travelling on a tight budget this year.', example_ko_3 = '올해는 빠듯한 예산으로 여행하고 있어요.', example_en_4 = 'Budget airlines are popular with backpackers.', example_ko_4 = '저가 항공사는 배낭여행자들에게 인기가 많아요.', example_en_5 = 'What is your budget for accommodation per night?', example_ko_5 = '1박 숙박 예산이 얼마예요?' WHERE id = 'w_travel_B1_15';
UPDATE words SET example_en_2 = 'I found a great guidebook for Southeast Asia.', example_ko_2 = '동남아시아에 대한 훌륭한 여행 안내서를 찾았어요.', example_en_3 = 'The guidebook rated this restaurant very highly.', example_ko_3 = '여행 안내서에서 이 식당을 매우 높게 평가했어요.', example_en_4 = 'My guidebook says the museum is free on Sundays.', example_ko_4 = '제 여행 안내서에는 박물관이 일요일에 무료라고 나와 있어요.', example_en_5 = 'A local guidebook is more reliable than online reviews.', example_ko_5 = '현지 여행 안내서가 온라인 리뷰보다 더 믿을 만해요.' WHERE id = 'w_travel_B1_16';
UPDATE words SET example_en_2 = 'We embark on the cruise at six in the evening.', example_ko_2 = '저녁 6시에 크루즈에 탑승해요.', example_en_3 = 'I am about to embark on the longest journey of my life.', example_ko_3 = '인생에서 가장 긴 여정을 시작하려고 해요.', example_en_4 = 'Passengers should embark from the lower deck.', example_ko_4 = '승객들은 아래층 갑판에서 탑승해야 해요.', example_en_5 = 'We will embark as soon as the weather clears.', example_ko_5 = '날씨가 맑아지는 즉시 출발할 거예요.' WHERE id = 'w_travel_B1_17';
UPDATE words SET example_en_2 = 'Passengers are asked to disembark in an orderly manner.', example_ko_2 = '승객들은 질서 있게 하선해 주시기 바랍니다.', example_en_3 = 'We disembarked at the port and took a taxi.', example_ko_3 = '항구에서 하선한 뒤 택시를 탔어요.', example_en_4 = 'All passengers must disembark before the ship is cleaned.', example_ko_4 = '배를 청소하기 전에 모든 승객이 하선해야 해요.', example_en_5 = 'When do we disembark at our next port of call?', example_ko_5 = '다음 기항지에서 언제 하선하나요?' WHERE id = 'w_travel_B1_18';
UPDATE words SET example_en_2 = 'Where is the baggage claim area?', example_ko_2 = '수하물 찾는 곳이 어디예요?', example_en_3 = 'My suitcase did not arrive at baggage claim.', example_ko_3 = '수하물 찾는 곳에 제 여행 가방이 나오지 않았어요.', example_en_4 = 'Baggage claim is on the ground floor of the terminal.', example_ko_4 = '수하물 찾는 곳은 터미널 1층에 있어요.', example_en_5 = 'Expect a wait of around twenty minutes at baggage claim.', example_ko_5 = '수하물 찾는 곳에서 약 20분 정도 기다려야 해요.' WHERE id = 'w_travel_B1_19';
UPDATE words SET example_en_2 = 'What time is the latest I can check out?', example_ko_2 = '가장 늦게 체크아웃할 수 있는 시간이 언제예요?', example_en_3 = 'We checked out early to catch our flight.', example_ko_3 = '비행기를 타기 위해 일찍 체크아웃했어요.', example_en_4 = 'Can I store my bags after I check out?', example_ko_4 = '체크아웃 후에 짐을 맡길 수 있나요?', example_en_5 = 'Late check-out is available for an additional fee.', example_ko_5 = '추가 요금을 내면 늦은 체크아웃이 가능해요.' WHERE id = 'w_travel_B1_20';
UPDATE words SET example_en_2 = 'My layover in Dubai is eight hours long.', example_ko_2 = '두바이에서의 경유 시간이 8시간이에요.', example_en_3 = 'A long layover gave us time to explore the city.', example_ko_3 = '긴 경유 시간 덕분에 도시를 둘러볼 수 있었어요.', example_en_4 = 'I used the layover to visit a nearby museum.', example_ko_4 = '경유 시간을 이용해 근처 박물관에 다녀왔어요.', example_en_5 = 'Is there a lounge I can use during my layover?', example_ko_5 = '경유 중에 이용할 수 있는 라운지가 있나요?' WHERE id = 'w_travel_B1_21';
UPDATE words SET example_en_2 = 'This ticket is valid for domestic travel only.', example_ko_2 = '이 티켓은 국내 여행에만 유효해요.', example_en_3 = 'Domestic flights are usually cheaper.', example_ko_3 = '국내선 항공편이 보통 더 저렴해요.', example_en_4 = 'Is there a domestic terminal at this airport?', example_ko_4 = '이 공항에 국내선 터미널이 있나요?', example_en_5 = 'We took a domestic train to reach the coast.', example_ko_5 = '해안에 가기 위해 국내 기차를 탔어요.' WHERE id = 'w_travel_B1_22';
UPDATE words SET example_en_2 = 'You need a valid passport for international travel.', example_ko_2 = '국제 여행에는 유효한 여권이 필요해요.', example_en_3 = 'The conference attracted international participants.', example_ko_3 = '그 컨퍼런스에는 국제 참가자들이 모였어요.', example_en_4 = 'International arrivals are on the second floor.', example_ko_4 = '국제선 도착은 2층이에요.', example_en_5 = 'My work involves a lot of international travel.', example_ko_5 = '제 일은 해외 출장이 많아요.' WHERE id = 'w_travel_B1_23';
UPDATE words SET example_en_2 = 'The transfer takes about thirty minutes by bus.', example_ko_2 = '버스로 환승하는 데 약 30분 걸려요.', example_en_3 = 'I missed my transfer because the first flight was late.', example_ko_3 = '첫 번째 항공편이 늦어서 환승을 놓쳤어요.', example_en_4 = 'The hotel offers a free transfer from the airport.', example_ko_4 = '호텔에서 공항 무료 셔틀을 제공해요.', example_en_5 = 'Is the transfer to the hotel included in the package?', example_ko_5 = '호텔까지 이동이 패키지에 포함되어 있나요?' WHERE id = 'w_travel_B1_24';
UPDATE words SET example_en_2 = 'The airline tends to overbook during peak season.', example_ko_2 = '그 항공사는 성수기에 초과 예약을 하는 경향이 있어요.', example_en_3 = 'I was told the flight was overbooked.', example_ko_3 = '항공편이 초과 예약됐다는 말을 들었어요.', example_en_4 = 'Hotels often overbook to compensate for no-shows.', example_ko_4 = '호텔들은 종종 노쇼를 대비해 초과 예약을 받아요.', example_en_5 = 'If the flight is overbooked, you may get a voucher.', example_ko_5 = '항공편이 초과 예약된 경우 바우처를 받을 수도 있어요.' WHERE id = 'w_travel_B1_25';
UPDATE words SET example_en_2 = 'Cancellation fees apply if you cancel within 24 hours.', example_ko_2 = '24시간 이내에 취소하면 취소 수수료가 발생해요.', example_en_3 = 'The cancellation policy was clearly explained.', example_ko_3 = '취소 정책이 명확하게 설명되어 있었어요.', example_en_4 = 'I received a full refund after the cancellation.', example_ko_4 = '취소 후 전액 환불을 받았어요.', example_en_5 = 'Trip cancellation insurance is worth having.', example_ko_5 = '여행 취소 보험에 가입해 두는 것이 좋아요.' WHERE id = 'w_travel_B1_26';
UPDATE words SET example_en_2 = 'I requested a refund for the cancelled tour.', example_ko_2 = '취소된 투어에 대한 환불을 요청했어요.', example_en_3 = 'The refund was processed within five business days.', example_ko_3 = '환불은 영업일 기준 5일 이내에 처리됐어요.', example_en_4 = 'Am I entitled to a refund if my flight is delayed?', example_ko_4 = '항공편이 지연되면 환불을 받을 수 있나요?', example_en_5 = 'They offered a partial refund, not a full one.', example_ko_5 = '전액이 아닌 부분 환불을 제공했어요.' WHERE id = 'w_travel_B1_27';
UPDATE words SET example_en_2 = 'I was offered a free upgrade to business class.', example_ko_2 = '비즈니스 클래스로 무료 업그레이드를 받았어요.', example_en_3 = 'Can I upgrade my room for an extra charge?', example_ko_3 = '추가 요금을 내고 객실을 업그레이드할 수 있나요?', example_en_4 = 'The airline upgraded us because the flight was full.', example_ko_4 = '항공편이 만석이어서 항공사가 업그레이드를 해줬어요.', example_en_5 = 'An upgrade to a sea-view room was available.', example_ko_5 = '바다 전망 객실로 업그레이드가 가능했어요.' WHERE id = 'w_travel_B1_28';
UPDATE words SET example_en_2 = 'The expedition set out before dawn.', example_ko_2 = '탐험대는 동이 트기 전에 출발했어요.', example_en_3 = 'Joining a polar expedition has always been my dream.', example_ko_3 = '극지방 탐험대에 참가하는 것이 항상 제 꿈이었어요.', example_en_4 = 'The expedition took three weeks to complete.', example_ko_4 = '탐험은 완료하는 데 3주가 걸렸어요.', example_en_5 = 'She wrote a book about her Amazon expedition.', example_ko_5 = '그녀는 아마존 탐험에 대한 책을 썼어요.' WHERE id = 'w_travel_B1_29';
UPDATE words SET example_en_2 = 'This site is a UNESCO World Heritage site.', example_ko_2 = '이곳은 유네스코 세계문화유산이에요.', example_en_3 = 'The city is proud of its cultural heritage.', example_ko_3 = '그 도시는 문화적 유산을 자랑스러워해요.', example_en_4 = 'Protecting heritage buildings is important.', example_ko_4 = '유산 건물을 보존하는 것이 중요해요.', example_en_5 = 'The museum preserves the region''s heritage.', example_ko_5 = '박물관이 그 지역의 유산을 보존해요.' WHERE id = 'w_travel_B1_30';
UPDATE words SET example_en_2 = 'What is the standard bus fare in this city?', example_ko_2 = '이 도시의 기본 버스 요금이 얼마예요?', example_en_3 = 'The train fare increased last year.', example_ko_3 = '기차 요금이 작년에 올랐어요.', example_en_4 = 'Children under five travel at half fare.', example_ko_4 = '5세 미만 어린이는 반값 요금으로 이용할 수 있어요.', example_en_5 = 'The fare includes a free transfer to the bus.', example_ko_5 = '요금에 버스 환승이 포함되어 있어요.' WHERE id = 'w_travel_B1_31';
UPDATE words SET example_en_2 = 'Our stopover in Singapore lasted twelve hours.', example_ko_2 = '싱가포르에서의 경유는 12시간이었어요.', example_en_3 = 'I booked a stopover to explore an extra city.', example_ko_3 = '한 도시를 더 탐험하기 위해 경유를 예약했어요.', example_en_4 = 'A long stopover can be a great mini-holiday.', example_ko_4 = '긴 경유 시간은 작은 미니 여행이 될 수 있어요.', example_en_5 = 'Which stopover cities are available on this route?', example_ko_5 = '이 노선에서 경유할 수 있는 도시가 어디예요?' WHERE id = 'w_travel_B1_32';
UPDATE words SET example_en_2 = 'I need to complain about the noise in my room.', example_ko_2 = '제 방의 소음에 대해 불만을 제기해야 해요.', example_en_3 = 'Don''t be afraid to complain if the service is poor.', example_ko_3 = '서비스가 나쁘면 망설이지 말고 불만을 제기하세요.', example_en_4 = 'She complained to the airline about the lost luggage.', example_ko_4 = '그녀는 분실된 짐에 대해 항공사에 항의했어요.', example_en_5 = 'How do I complain about a booking error?', example_ko_5 = '예약 오류에 대해 어떻게 불만을 제기하나요?' WHERE id = 'w_travel_B1_33';
UPDATE words SET example_en_2 = 'Learning a few local phrases goes a long way.', example_ko_2 = '현지 표현을 몇 가지 배워두면 큰 도움이 돼요.', example_en_3 = 'Could you teach me a useful phrase in Japanese?', example_ko_3 = '일본어 유용한 표현 하나 가르쳐 주실 수 있나요?', example_en_4 = 'The phrase "excuse me" works in almost any situation.', example_ko_4 = '"실례합니다"라는 표현은 거의 모든 상황에서 통해요.', example_en_5 = 'Write down the phrase so you can show it to the driver.', example_ko_5 = '기사에게 보여줄 수 있도록 그 표현을 적어두세요.' WHERE id = 'w_travel_B1_34';
UPDATE words SET example_en_2 = 'The scenic coastline stretched for miles.', example_ko_2 = '아름다운 해안선이 수 킬로미터 이어졌어요.', example_en_3 = 'We took the scenic train route through the mountains.', example_ko_3 = '산 사이를 통과하는 경치 좋은 기차 노선을 이용했어요.', example_en_4 = 'The drive is long but incredibly scenic.', example_ko_4 = '드라이브 거리는 길지만 경치가 정말 아름다워요.', example_en_5 = 'Choose the scenic path for the most memorable walk.', example_ko_5 = '가장 기억에 남는 산책을 위해 경치 좋은 길을 선택하세요.' WHERE id = 'w_travel_B1_35';

-- ══════════════════════════════════════
-- B2 — 35 WORDS
-- ══════════════════════════════════════
UPDATE words SET example_en_2 = 'She has lived a nomadic life for over a decade.', example_ko_2 = '그녀는 10년 넘게 유목민처럼 생활했어요.', example_en_3 = 'His nomadic upbringing shaped his love of travel.', example_ko_3 = '유목민 같은 성장 환경이 그의 여행 사랑을 만들었어요.', example_en_4 = 'The tribe maintained its nomadic traditions.', example_ko_4 = '그 부족은 유목 전통을 유지했어요.', example_en_5 = 'A nomadic lifestyle requires adaptability.', example_ko_5 = '유목적 생활 방식은 적응력이 필요해요.' WHERE id = 'w_travel_B2_01';
UPDATE words SET example_en_2 = 'Her wanderlust drove her to quit her job and travel.', example_ko_2 = '여행에 대한 갈망이 그녀를 회사를 그만두고 여행하게 만들었어요.', example_en_3 = 'I have had wanderlust since I was a teenager.', example_ko_3 = '10대 때부터 방랑 기질이 있었어요.', example_en_4 = 'Social media fuels wanderlust in many young people.', example_ko_4 = '소셜 미디어가 많은 젊은이들의 여행 욕구를 불러일으켜요.', example_en_5 = 'Wanderlust is more than just wanting a holiday.', example_ko_5 = '방랑벽은 단순히 휴가를 원하는 것 이상이에요.' WHERE id = 'w_travel_B2_02';
UPDATE words SET example_en_2 = 'The polar expedition lasted ninety days.', example_ko_2 = '극지방 탐험은 90일간 이어졌어요.', example_en_3 = 'We joined a scientific expedition to the rainforest.', example_ko_3 = '열대우림으로 가는 과학 탐험에 참가했어요.', example_en_4 = 'Planning an expedition requires months of preparation.', example_ko_4 = '탐험을 계획하려면 몇 달의 준비가 필요해요.', example_en_5 = 'Their expedition was funded by a university grant.', example_ko_5 = '그들의 탐험은 대학 지원금으로 자금을 지원받았어요.' WHERE id = 'w_travel_B2_03';
UPDATE words SET example_en_2 = 'We traversed the entire length of the country by train.', example_ko_2 = '기차로 나라 전체를 횡단했어요.', example_en_3 = 'The hikers traversed the mountain in poor visibility.', example_ko_3 = '등산객들이 시야가 좋지 않은 상황에서 산을 가로질렀어요.', example_en_4 = 'The road traverses some of the most remote landscapes.', example_ko_4 = '그 도로는 가장 외딴 풍경 속을 가로질러요.', example_en_5 = 'It took a week to traverse the desert on foot.', example_ko_5 = '걸어서 사막을 횡단하는 데 일주일이 걸렸어요.' WHERE id = 'w_travel_B2_04';
UPDATE words SET example_en_2 = 'Many people make a pilgrimage to Santiago de Compostela.', example_ko_2 = '많은 사람들이 산티아고 데 콤포스텔라로 성지 순례를 떠나요.', example_en_3 = 'Her journey was more of a personal pilgrimage than a holiday.', example_ko_3 = '그녀의 여정은 휴가라기보다는 개인적인 순례에 가까웠어요.', example_en_4 = 'The pilgrimage attracts thousands of visitors each year.', example_ko_4 = '그 성지 순례에는 매년 수천 명이 찾아와요.', example_en_5 = 'He completed the pilgrimage despite his injury.', example_ko_5 = '그는 부상에도 불구하고 순례를 완주했어요.' WHERE id = 'w_travel_B2_05';
UPDATE words SET example_en_2 = 'The region is known for its rich cultural heritage.', example_ko_2 = '그 지역은 풍부한 문화유산으로 유명해요.', example_en_3 = 'Visiting heritage sites is a priority for me.', example_ko_3 = '유산 유적지 방문이 저의 우선순위예요.', example_en_4 = 'The heritage trail covers twelve historic buildings.', example_ko_4 = '유산 탐방로는 12개의 역사적 건물을 포함해요.', example_en_5 = 'Our shared heritage connects us despite the distance.', example_ko_5 = '거리가 멀어도 우리의 공유된 유산이 우리를 연결해요.' WHERE id = 'w_travel_B2_06';
UPDATE words SET example_en_2 = 'The cooking class offered an immersive cultural experience.', example_ko_2 = '요리 수업은 몰입감 있는 문화 체험을 제공했어요.', example_en_3 = 'I prefer immersive travel to simply sightseeing.', example_ko_3 = '단순한 관광보다 몰입형 여행을 선호해요.', example_en_4 = 'The festival was an immersive sensory experience.', example_ko_4 = '그 축제는 몰입감 있는 감각 경험이었어요.', example_en_5 = 'An immersive language programme helped her progress quickly.', example_ko_5 = '몰입식 언어 프로그램이 그녀의 빠른 발전에 도움이 됐어요.' WHERE id = 'w_travel_B2_07';
UPDATE words SET example_en_2 = 'We made a spontaneous decision to extend our trip.', example_ko_2 = '여행을 연장하기로 즉흥적으로 결정했어요.', example_en_3 = 'She is the most spontaneous traveller I know.', example_ko_3 = '그녀는 제가 아는 가장 즉흥적인 여행자예요.', example_en_4 = 'A spontaneous detour led us to a hidden beach.', example_ko_4 = '즉흥적인 우회로가 숨겨진 해변으로 우리를 이끌었어요.', example_en_5 = 'Being spontaneous can make travel more exciting.', example_ko_5 = '즉흥적으로 행동하면 여행이 더 흥미로워질 수 있어요.' WHERE id = 'w_travel_B2_08';
UPDATE words SET example_en_2 = 'We stayed in an off-grid cabin with no electricity.', example_ko_2 = '전기도 없는 그리드 밖 오두막에서 묵었어요.', example_en_3 = 'Going off-grid for a week completely changed my mindset.', example_ko_3 = '일주일 동안 디지털 세상과 단절하니 사고방식이 완전히 바뀌었어요.', example_en_4 = 'An off-grid retreat is the ultimate digital detox.', example_ko_4 = '그리드 밖 휴양은 최고의 디지털 디톡스예요.', example_en_5 = 'More travellers are choosing off-grid destinations.', example_ko_5 = '점점 더 많은 여행자들이 그리드 밖 여행지를 선택하고 있어요.' WHERE id = 'w_travel_B2_09';
UPDATE words SET example_en_2 = 'I always look for authentic local experiences.', example_ko_2 = '항상 진정한 현지 체험을 찾아요.', example_en_3 = 'The market sells authentic handmade crafts.', example_ko_3 = '시장에서 진짜 수제 공예품을 팔아요.', example_en_4 = 'Is the food here authentic or just tourist-friendly?', example_ko_4 = '여기 음식이 정통인가요, 아니면 관광객용인가요?', example_en_5 = 'Authentic travel means stepping outside your comfort zone.', example_ko_5 = '진정한 여행은 편안함의 영역 밖으로 나오는 것을 의미해요.' WHERE id = 'w_travel_B2_10';
UPDATE words SET example_en_2 = 'He lived as an itinerant musician for several years.', example_ko_2 = '그는 몇 년 동안 유랑 음악가로 살았어요.', example_en_3 = 'The itinerant workers moved from region to region.', example_ko_3 = '유랑 노동자들은 지역을 옮겨 다녔어요.', example_en_4 = 'An itinerant lifestyle can be both liberating and lonely.', example_ko_4 = '유랑적인 생활 방식은 해방감과 동시에 외로움을 줄 수 있어요.', example_en_5 = 'She admired the itinerant storytellers she met in the market.', example_ko_5 = '그녀는 시장에서 만난 유랑 이야기꾼들에게 감탄했어요.' WHERE id = 'w_travel_B2_11';
UPDATE words SET example_en_2 = 'The village is so remote that few tourists reach it.', example_ko_2 = '그 마을은 너무 외져서 관광객이 거의 없어요.', example_en_3 = 'Remote locations often have the most breathtaking scenery.', example_ko_3 = '외딴 장소에 가장 숨 막히는 경치가 있는 경우가 많아요.', example_en_4 = 'The cabin was in a remote forest, far from any town.', example_ko_4 = '그 오두막은 어떤 마을에서도 멀리 떨어진 외딴 숲속에 있었어요.', example_en_5 = 'Working remotely means I can travel more freely.', example_ko_5 = '원격 근무 덕분에 더 자유롭게 여행할 수 있어요.' WHERE id = 'w_travel_B2_12';
UPDATE words SET example_en_2 = 'We chose a sustainable hotel that uses solar energy.', example_ko_2 = '태양 에너지를 사용하는 친환경 호텔을 선택했어요.', example_en_3 = 'Sustainable tourism benefits local communities.', example_ko_3 = '지속 가능한 관광은 지역 사회에 도움이 돼요.', example_en_4 = 'How can I make my travels more sustainable?', example_ko_4 = '여행을 어떻게 하면 더 친환경적으로 만들 수 있나요?', example_en_5 = 'Flying less is one way to travel more sustainably.', example_ko_5 = '비행 횟수를 줄이는 것이 더 지속 가능하게 여행하는 방법 중 하나예요.' WHERE id = 'w_travel_B2_13';
UPDATE words SET example_en_2 = 'Our detailed itinerary helped us make the most of every day.', example_ko_2 = '세부 일정 덕분에 매일 최대한 알차게 보낼 수 있었어요.', example_en_3 = 'She shared her itinerary on her travel blog.', example_ko_3 = '그녀는 여행 블로그에 일정을 공유했어요.', example_en_4 = 'The itinerary was too packed — we were exhausted.', example_ko_4 = '일정이 너무 빡빡해서 지쳤어요.', example_en_5 = 'I prefer a loose itinerary with room to explore.', example_ko_5 = '저는 탐험할 여지가 있는 느슨한 일정을 선호해요.' WHERE id = 'w_travel_B2_14';
UPDATE words SET example_en_2 = 'The passport control queue was very long.', example_ko_2 = '여권 심사 줄이 매우 길었어요.', example_en_3 = 'Please have your documents ready at passport control.', example_ko_3 = '여권 심사대에서 서류를 준비해 주세요.', example_en_4 = 'Passport control took forty minutes at the busy airport.', example_ko_4 = '붐비는 공항에서 여권 심사가 40분 걸렸어요.', example_en_5 = 'There are separate passport control lanes for EU citizens.', example_ko_5 = 'EU 시민을 위한 별도의 여권 심사 통로가 있어요.' WHERE id = 'w_travel_B2_15';
UPDATE words SET example_en_2 = 'We took an overland route across Central Asia.', example_ko_2 = '중앙아시아를 가로지르는 육로 경로를 이용했어요.', example_en_3 = 'Overland travel is slower but more rewarding.', example_ko_3 = '육로 여행은 느리지만 더 보람이 있어요.', example_en_4 = 'The overland crossing from Turkey to Iran is stunning.', example_ko_4 = '터키에서 이란으로의 육로 이동은 정말 멋져요.', example_en_5 = 'She documented her overland journey in a series of videos.', example_ko_5 = '그녀는 육로 여행을 영상 시리즈로 기록했어요.' WHERE id = 'w_travel_B2_16';
UPDATE words SET example_en_2 = 'The hostel was full of backpackers from around the world.', example_ko_2 = '호스텔은 전 세계에서 온 배낭여행자들로 가득했어요.', example_en_3 = 'As a backpacker, I always travel light.', example_ko_3 = '배낭여행자로서 항상 가볍게 여행해요.', example_en_4 = 'The backpacker trail through Southeast Asia is well established.', example_ko_4 = '동남아시아를 통과하는 배낭여행자 루트는 잘 알려져 있어요.', example_en_5 = 'Being a backpacker taught me how to live simply.', example_ko_5 = '배낭여행을 통해 단순하게 사는 법을 배웠어요.' WHERE id = 'w_travel_B2_17';
UPDATE words SET example_en_2 = 'Cultural immersion requires patience and humility.', example_ko_2 = '문화 몰입에는 인내심과 겸손이 필요해요.', example_en_3 = 'The programme offers complete cultural immersion.', example_ko_3 = '그 프로그램은 완전한 문화 몰입을 제공해요.', example_en_4 = 'Living with a local family is the best cultural immersion.', example_ko_4 = '현지 가정에서 생활하는 것이 최고의 문화 몰입이에요.', example_en_5 = 'Language learning is accelerated by cultural immersion.', example_ko_5 = '문화 몰입을 하면 언어 학습이 빨라져요.' WHERE id = 'w_travel_B2_18';
UPDATE words SET example_en_2 = 'The desolate landscape was hauntingly beautiful.', example_ko_2 = '황량한 풍경이 묘하게 아름다웠어요.', example_en_3 = 'We drove through a desolate stretch of desert.', example_ko_3 = '황량한 사막 구간을 드라이브했어요.', example_en_4 = 'The town felt desolate after the festival ended.', example_ko_4 = '축제가 끝나고 나서 그 마을이 황량하게 느껴졌어요.', example_en_5 = 'I was drawn to the desolate beauty of the Arctic.', example_ko_5 = '북극의 황량한 아름다움에 끌렸어요.' WHERE id = 'w_travel_B2_19';
UPDATE words SET example_en_2 = 'The altitude made breathing difficult.', example_ko_2 = '고도가 높아서 호흡이 힘들었어요.', example_en_3 = 'We acclimatised slowly to the high altitude.', example_ko_3 = '높은 고도에 천천히 적응했어요.', example_en_4 = 'Flying at high altitude for hours can cause dehydration.', example_ko_4 = '몇 시간 동안 고도에서 비행하면 탈수가 올 수 있어요.', example_en_5 = 'The altitude sickness passed after a day of rest.', example_ko_5 = '하루 쉬고 나서 고산병이 나았어요.' WHERE id = 'w_travel_B2_20';
UPDATE words SET example_en_2 = 'We went trekking through the jungle for three days.', example_ko_2 = '3일 동안 정글을 트레킹했어요.', example_en_3 = 'Trekking in Nepal is a once-in-a-lifetime experience.', example_ko_3 = '네팔 트레킹은 일생에 한 번의 경험이에요.', example_en_4 = 'You need good boots for trekking in the mountains.', example_ko_4 = '산악 트레킹에는 좋은 등산화가 필요해요.', example_en_5 = 'Is trekking alone safe in this national park?', example_ko_5 = '이 국립공원에서 혼자 트레킹하는 것이 안전한가요?' WHERE id = 'w_travel_B2_21';
UPDATE words SET example_en_2 = 'The shore excursion included a visit to ancient ruins.', example_ko_2 = '항구 관광에 고대 유적지 방문이 포함되어 있었어요.', example_en_3 = 'We booked a shore excursion in advance through the cruise line.', example_ko_3 = '크루즈사를 통해 미리 항구 관광을 예약했어요.', example_en_4 = 'The shore excursion lasted about four hours.', example_ko_4 = '항구 관광은 약 4시간 걸렸어요.', example_en_5 = 'Which shore excursion would you recommend at this port?', example_ko_5 = '이 항구에서 어떤 항구 관광을 추천하나요?' WHERE id = 'w_travel_B2_22';
UPDATE words SET example_en_2 = 'The museum offers a self-guided audio tour.', example_ko_2 = '박물관에서 자유 오디오 투어를 제공해요.', example_en_3 = 'I prefer self-guided travel to organised tours.', example_ko_3 = '단체 투어보다 자유 여행을 선호해요.', example_en_4 = 'The self-guided trail is about five kilometres long.', example_ko_4 = '자유 탐방로는 약 5킬로미터예요.', example_en_5 = 'A self-guided walking map is available at reception.', example_ko_5 = '프런트에서 자유 도보 지도를 받을 수 있어요.' WHERE id = 'w_travel_B2_23';
UPDATE words SET example_en_2 = 'We took the scenic route along the coast.', example_ko_2 = '해안을 따라 경치 좋은 길을 달렸어요.', example_en_3 = 'The scenic route adds two hours to the journey.', example_ko_3 = '경치 좋은 길로 가면 두 시간이 더 걸려요.', example_en_4 = 'I always choose the scenic route when I have time.', example_ko_4 = '시간이 있을 때는 항상 경치 좋은 길을 선택해요.', example_en_5 = 'The scenic route through the valley is breathtaking.', example_ko_5 = '계곡을 통과하는 경치 좋은 길은 정말 숨막혀요.' WHERE id = 'w_travel_B2_24';
UPDATE words SET example_en_2 = 'The café was completely off the beaten track.', example_ko_2 = '그 카페는 완전히 외진 곳에 있었어요.', example_en_3 = 'I enjoy finding places that are off the beaten track.', example_ko_3 = '사람들이 잘 가지 않는 곳을 찾는 걸 즐겨요.', example_en_4 = 'The village is firmly off the beaten track.', example_ko_4 = '그 마을은 완전히 외진 곳에 있어요.', example_en_5 = 'Travelling off the beaten track requires more planning.', example_ko_5 = '외진 곳을 여행하려면 더 많은 준비가 필요해요.' WHERE id = 'w_travel_B2_25';
UPDATE words SET example_en_2 = 'New York is one of the most cosmopolitan cities in the world.', example_ko_2 = '뉴욕은 세계에서 가장 국제적인 도시 중 하나예요.', example_en_3 = 'The restaurant had a cosmopolitan atmosphere.', example_ko_3 = '그 레스토랑은 세계적인 분위기가 있었어요.', example_en_4 = 'She has a cosmopolitan outlook from years of travel.', example_ko_4 = '그녀는 오랜 여행을 통해 세계적인 시각을 갖게 됐어요.', example_en_5 = 'The city''s cosmopolitan culture attracts many visitors.', example_ko_5 = '그 도시의 세계적인 문화가 많은 방문객을 끌어요.' WHERE id = 'w_travel_B2_26';
UPDATE words SET example_en_2 = 'Could you orient me on this map?', example_ko_2 = '이 지도에서 방향을 알려주실 수 있나요?', example_en_3 = 'I need a few days to orient myself in a new city.', example_ko_3 = '새 도시에 익숙해지는 데 며칠이 걸려요.', example_en_4 = 'The guide helped us orient ourselves in the old quarter.', example_ko_4 = '가이드가 구시가지에서 방향을 잡는 데 도움을 줬어요.', example_en_5 = 'She struggled to orient herself after arriving at night.', example_ko_5 = '그녀는 밤에 도착한 뒤 방향을 잡기가 힘들었어요.' WHERE id = 'w_travel_B2_27';
UPDATE words SET example_en_2 = 'The travel voucher covered one night at the hotel.', example_ko_2 = '여행 바우처로 호텔 1박이 해결됐어요.', example_en_3 = 'I received a voucher as compensation for the delay.', example_ko_3 = '지연에 대한 보상으로 바우처를 받았어요.', example_en_4 = 'Can I use this voucher at any hotel in the chain?', example_ko_4 = '이 바우처를 체인 내 모든 호텔에서 사용할 수 있나요?', example_en_5 = 'The voucher is valid for six months.', example_ko_5 = '바우처는 6개월간 유효해요.' WHERE id = 'w_travel_B2_28';
UPDATE words SET example_en_2 = 'Her journey seemed to embody the spirit of adventure.', example_ko_2 = '그녀의 여정은 모험 정신을 그대로 보여주는 것 같았어요.', example_en_3 = 'The festival embodies the local cultural identity.', example_ko_3 = '그 축제는 지역 문화 정체성을 구현해요.', example_en_4 = 'He tried to embody the values of the place he visited.', example_ko_4 = '그는 방문한 곳의 가치관을 구현하려 했어요.', example_en_5 = 'Slow travel embodies the idea that the journey matters.', example_ko_5 = '느린 여행은 여정 그 자체가 중요하다는 생각을 구현해요.' WHERE id = 'w_travel_B2_29';
UPDATE words SET example_en_2 = 'Good itinerary planning saves time and money.', example_ko_2 = '여행 일정을 잘 계획하면 시간과 돈을 절약할 수 있어요.', example_en_3 = 'She specialises in itinerary planning for solo travellers.', example_ko_3 = '그녀는 혼자 여행자를 위한 일정 계획을 전문으로 해요.', example_en_4 = 'Itinerary planning becomes easier with the right apps.', example_ko_4 = '적절한 앱을 사용하면 일정 계획이 더 쉬워져요.', example_en_5 = 'We spent an evening on itinerary planning for our trip.', example_ko_5 = '여행 일정을 계획하는 데 저녁 시간을 보냈어요.' WHERE id = 'w_travel_B2_30';
UPDATE words SET example_en_2 = 'Culture shock hit me harder in my first week abroad.', example_ko_2 = '해외에서의 첫 주에 문화 충격이 더 크게 왔어요.', example_en_3 = 'Experiencing culture shock is a normal part of travel.', example_ko_3 = '문화 충격을 경험하는 것은 여행의 자연스러운 과정이에요.', example_en_4 = 'She overcame culture shock by making local friends.', example_ko_4 = '그녀는 현지 친구를 사귀면서 문화 충격을 극복했어요.', example_en_5 = 'Even experienced travellers can face culture shock.', example_ko_5 = '경험 많은 여행자도 문화 충격을 받을 수 있어요.' WHERE id = 'w_travel_B2_31';
UPDATE words SET example_en_2 = 'Crossing multiple time zones can be exhausting.', example_ko_2 = '여러 시간대를 넘나드는 것은 피곤할 수 있어요.', example_en_3 = 'Japan and the UK are in very different time zones.', example_ko_3 = '일본과 영국은 시간대가 매우 달라요.', example_en_4 = 'Try to adjust your schedule to the local time zone immediately.', example_ko_4 = '도착하자마자 현지 시간대에 맞게 일정을 조정하세요.', example_en_5 = 'Which time zone should I use for the booking?', example_ko_5 = '예약할 때 어떤 시간대를 사용해야 하나요?' WHERE id = 'w_travel_B2_32';
UPDATE words SET example_en_2 = 'She completed a round-the-world trip in eighty days.', example_ko_2 = '그녀는 80일 만에 세계 일주 여행을 마쳤어요.', example_en_3 = 'A round-the-world ticket can be surprisingly affordable.', example_ko_3 = '세계 일주 티켓은 생각보다 저렴할 수 있어요.', example_en_4 = 'Completing a round-the-world journey is a lifelong dream.', example_ko_4 = '세계 일주 여행을 완주하는 것은 평생의 꿈이에요.', example_en_5 = 'He quit his job to start a round-the-world adventure.', example_ko_5 = '그는 세계 일주 모험을 시작하기 위해 직장을 그만뒀어요.' WHERE id = 'w_travel_B2_33';
UPDATE words SET example_en_2 = 'She works as an expedition planner for adventure groups.', example_ko_2 = '그녀는 모험 그룹의 탐험 기획자로 일해요.', example_en_3 = 'An expedition planner must consider every possible risk.', example_ko_3 = '탐험 기획자는 모든 가능한 위험을 고려해야 해요.', example_en_4 = 'I used an online expedition planner for the trek.', example_ko_4 = '트레킹에 온라인 탐험 기획 도구를 활용했어요.', example_en_5 = 'A good expedition planner saves you from costly mistakes.', example_ko_5 = '좋은 탐험 기획자가 있으면 비용이 많이 드는 실수를 막을 수 있어요.' WHERE id = 'w_travel_B2_34';
UPDATE words SET example_en_2 = 'We sought out uncharted paths far from the tourist trail.', example_ko_2 = '관광 루트에서 멀리 떨어진 미지의 길을 찾아 나섰어요.', example_en_3 = 'The documentary crew ventured into uncharted territory.', example_ko_3 = '다큐멘터리 팀이 미지의 영역으로 들어갔어요.', example_en_4 = 'Exploring uncharted regions requires expert planning.', example_ko_4 = '미지의 지역을 탐험하려면 전문적인 계획이 필요해요.', example_en_5 = 'For her, every journey into the unknown was uncharted.', example_ko_5 = '그녀에게는 미지의 세계로의 모든 여정이 새로운 탐험이었어요.' WHERE id = 'w_travel_B2_35';
