-- EngCat — 시사·뉴스 (news) 단어 예문 추가
-- example_en_2~5 + example_ko_2~5 for all 210 words
-- Generated: 2026-05-27

-- ══════════════════════════════════════
-- A1 (35 words)
-- ══════════════════════════════════════

UPDATE words SET example_en_2 = 'She reads the news every morning before work.', example_ko_2 = '그녀는 매일 아침 출근 전에 뉴스를 읽어요.', example_en_3 = 'The news about the storm surprised everyone.', example_ko_3 = '폭풍에 관한 뉴스가 모든 사람을 놀라게 했어요.', example_en_4 = 'He shared the news with his family at dinner.', example_ko_4 = '그는 저녁 식사 때 가족들과 뉴스를 나눴어요.', example_en_5 = 'Breaking news appeared on the screen suddenly.', example_ko_5 = '속보가 갑자기 화면에 나타났어요.' WHERE id = 'w_news_A1_01';

UPDATE words SET example_en_2 = 'The teacher asked students to write a report about the event.', example_ko_2 = '선생님이 학생들에게 그 사건에 대한 보고서를 쓰라고 했어요.', example_en_3 = 'The weather report says it will rain tomorrow.', example_ko_3 = '날씨 보도에 따르면 내일 비가 온대요.', example_en_4 = 'She gave a report on the accident to the police.', example_ko_4 = '그녀는 경찰에게 사고 보고서를 제출했어요.', example_en_5 = 'The hospital report showed that everyone was safe.', example_ko_5 = '병원 보고서에는 모두 안전하다고 나왔어요.' WHERE id = 'w_news_A1_02';

UPDATE words SET example_en_2 = 'He wants to travel to every country in the world.', example_ko_2 = '그는 세계 모든 나라를 여행하고 싶어요.', example_en_3 = 'This country has a very large population.', example_ko_3 = '이 나라는 인구가 매우 많아요.', example_en_4 = 'The two countries signed a new agreement.', example_ko_4 = '두 나라가 새로운 협정에 서명했어요.', example_en_5 = 'Which country do you want to visit next?', example_ko_5 = '다음에 어느 나라를 방문하고 싶어요?' WHERE id = 'w_news_A1_03';

UPDATE words SET example_en_2 = 'The people in this city are very friendly.', example_ko_2 = '이 도시 사람들은 매우 친절해요.', example_en_3 = 'Many people lost their homes in the flood.', example_ko_3 = '많은 사람들이 홍수로 집을 잃었어요.', example_en_4 = 'People around the world watched the game on TV.', example_ko_4 = '전 세계 사람들이 TV로 경기를 봤어요.', example_en_5 = 'The government is listening to what people want.', example_ko_5 = '정부는 사람들이 원하는 것을 듣고 있어요.' WHERE id = 'w_news_A1_04';

UPDATE words SET example_en_2 = 'The government is building new hospitals this year.', example_ko_2 = '정부가 올해 새 병원을 짓고 있어요.', example_en_3 = 'People are angry at the government''s decision.', example_ko_3 = '사람들은 정부의 결정에 화가 났어요.', example_en_4 = 'The government sent help to the flood victims.', example_ko_4 = '정부가 홍수 피해자들에게 도움을 보냈어요.', example_en_5 = 'The new government wants to improve schools.', example_ko_5 = '새 정부는 학교를 개선하고 싶어해요.' WHERE id = 'w_news_A1_05';

UPDATE words SET example_en_2 = 'The war caused many people to leave their homes.', example_ko_2 = '전쟁으로 많은 사람들이 집을 떠나야 했어요.', example_en_3 = 'Both sides agreed to stop the war.', example_ko_3 = '양측이 전쟁을 멈추기로 합의했어요.', example_en_4 = 'Children suffer the most during a war.', example_ko_4 = '전쟁 중에 아이들이 가장 많이 고통받아요.', example_en_5 = 'The country has been at war for three years.', example_ko_5 = '그 나라는 3년 동안 전쟁 중이에요.' WHERE id = 'w_news_A1_06';

UPDATE words SET example_en_2 = 'Millions of people voted in the election today.', example_ko_2 = '수백만 명이 오늘 선거에서 투표했어요.', example_en_3 = 'The election result was very close this time.', example_ko_3 = '이번 선거 결과는 매우 박빙이었어요.', example_en_4 = 'She is running in the election for mayor.', example_ko_4 = '그녀는 시장 선거에 출마하고 있어요.', example_en_5 = 'The election was free and fair, observers said.', example_ko_5 = '관찰자들은 선거가 자유롭고 공정했다고 말했어요.' WHERE id = 'w_news_A1_07';

UPDATE words SET example_en_2 = 'The city needs more money to fix the roads.', example_ko_2 = '그 도시는 도로를 고치기 위해 더 많은 돈이 필요해요.', example_en_3 = 'He saved money every month to buy a house.', example_ko_3 = '그는 집을 사기 위해 매달 돈을 모았어요.', example_en_4 = 'The charity raised a lot of money for the victims.', example_ko_4 = '자선단체가 피해자들을 위해 많은 돈을 모았어요.', example_en_5 = 'Without money, the hospital cannot buy medicine.', example_ko_5 = '돈이 없으면 병원이 약을 살 수 없어요.' WHERE id = 'w_news_A1_08';

UPDATE words SET example_en_2 = 'The sports event attracted thousands of fans.', example_ko_2 = '스포츠 행사에 수천 명의 팬이 몰렸어요.', example_en_3 = 'A serious event happened in the city last night.', example_ko_3 = '어젯밤 도시에서 심각한 사건이 일어났어요.', example_en_4 = 'The news covered the event for several days.', example_ko_4 = '뉴스가 며칠 동안 그 사건을 다뤘어요.', example_en_5 = 'Nobody expected this event to happen so quickly.', example_ko_5 = '아무도 이 사건이 이렇게 빨리 일어날 줄 몰랐어요.' WHERE id = 'w_news_A1_09';

UPDATE words SET example_en_2 = 'The world needs to work together to stop climate change.', example_ko_2 = '기후 변화를 막으려면 세계가 함께 협력해야 해요.', example_en_3 = 'People all over the world watched the ceremony live.', example_ko_3 = '전 세계 사람들이 행사를 생방송으로 봤어요.', example_en_4 = 'The disaster shocked the whole world.', example_ko_4 = '재난이 온 세계를 충격에 빠뜨렸어요.', example_en_5 = 'This invention changed the world forever.', example_ko_5 = '이 발명은 세상을 영원히 바꿨어요.' WHERE id = 'w_news_A1_10';

UPDATE words SET example_en_2 = 'She wrote a story about the accident for the newspaper.', example_ko_2 = '그녀는 신문에 실을 사고 기사를 썼어요.', example_en_3 = 'The story about the fire was on every channel.', example_ko_3 = '화재 기사가 모든 채널에 나왔어요.', example_en_4 = 'The reporter worked hard to get the full story.', example_ko_4 = '기자는 전체 기사를 얻기 위해 열심히 일했어요.', example_en_5 = 'That story about the missing children moved everyone.', example_ko_5 = '실종 어린이들에 관한 그 기사는 모든 사람을 감동시켰어요.' WHERE id = 'w_news_A1_11';

UPDATE words SET example_en_2 = 'Today is a very important day for the country.', example_ko_2 = '오늘은 나라에 매우 중요한 날이에요.', example_en_3 = 'The news today is all about the election.', example_ko_3 = '오늘 뉴스는 온통 선거에 관한 것이에요.', example_en_4 = 'The president will speak to the nation today.', example_ko_4 = '대통령이 오늘 국민에게 연설할 거예요.', example_en_5 = 'We learned today that the ceasefire has begun.', example_ko_5 = '우리는 오늘 휴전이 시작됐다는 것을 알게 됐어요.' WHERE id = 'w_news_A1_12';

UPDATE words SET example_en_2 = 'The reporter spoke live from the scene of the fire.', example_ko_2 = '기자가 화재 현장에서 생방송으로 말했어요.', example_en_3 = 'Millions watched the ceremony live on television.', example_ko_3 = '수백만 명이 텔레비전으로 행사를 생방송으로 봤어요.', example_en_4 = 'The press conference was broadcast live.', example_ko_4 = '기자 회견이 생방송으로 중계됐어요.', example_en_5 = 'She went live on social media to share the news.', example_ko_5 = '그녀는 소셜 미디어에서 생방송으로 소식을 전했어요.' WHERE id = 'w_news_A1_13';

UPDATE words SET example_en_2 = 'Firefighters worked all night to put out the fire.', example_ko_2 = '소방관들이 화재를 진화하기 위해 밤새 일했어요.', example_en_3 = 'The fire destroyed several houses in the area.', example_ko_3 = '화재로 그 지역의 여러 집이 불에 탔어요.', example_en_4 = 'Nobody was hurt in the fire, police confirmed.', example_ko_4 = '경찰이 화재에서 아무도 다치지 않았다고 확인했어요.', example_en_5 = 'The cause of the fire is still under investigation.', example_ko_5 = '화재 원인은 아직 조사 중이에요.' WHERE id = 'w_news_A1_14';

UPDATE words SET example_en_2 = 'The police are looking for the missing child.', example_ko_2 = '경찰이 실종된 아이를 찾고 있어요.', example_en_3 = 'Police stopped the car at the border checkpoint.', example_ko_3 = '경찰이 국경 검문소에서 차를 세웠어요.', example_en_4 = 'The police made an announcement about the investigation.', example_ko_4 = '경찰이 조사에 대한 발표를 했어요.', example_en_5 = 'More police were sent to control the large crowd.', example_ko_5 = '큰 군중을 통제하기 위해 더 많은 경찰이 파견됐어요.' WHERE id = 'w_news_A1_15';

UPDATE words SET example_en_2 = 'The flood left many families with nothing.', example_ko_2 = '홍수는 많은 가족을 빈손으로 만들었어요.', example_en_3 = 'Rescue teams saved people trapped by the flood.', example_ko_3 = '구조대가 홍수에 갇힌 사람들을 구했어요.', example_en_4 = 'The flood destroyed roads and bridges in the region.', example_ko_4 = '홍수로 그 지역의 도로와 다리가 파괴됐어요.', example_en_5 = 'Aid workers are helping those affected by the flood.', example_ko_5 = '구호 요원들이 홍수 피해자들을 돕고 있어요.' WHERE id = 'w_news_A1_16';

UPDATE words SET example_en_2 = 'The city announced new plans for public transportation.', example_ko_2 = '그 도시는 대중교통에 대한 새로운 계획을 발표했어요.', example_en_3 = 'Thousands of people in the city came out to protest.', example_ko_3 = '도시에서 수천 명이 시위를 위해 나왔어요.', example_en_4 = 'The city is growing fast and needs more schools.', example_ko_4 = '도시가 빠르게 성장하고 있어서 학교가 더 필요해요.', example_en_5 = 'Pollution is a big problem in this city.', example_ko_5 = '오염은 이 도시의 큰 문제예요.' WHERE id = 'w_news_A1_17';

UPDATE words SET example_en_2 = 'The law was changed for the first time in ten years.', example_ko_2 = '법이 10년 만에 처음으로 바뀌었어요.', example_en_3 = 'The economy grew faster this year than last year.', example_ko_3 = '올해 경제는 지난해보다 더 빠르게 성장했어요.', example_en_4 = 'Next year, the government plans to increase spending.', example_ko_4 = '내년에 정부는 지출을 늘릴 계획이에요.', example_en_5 = 'The disaster happened exactly one year ago today.', example_ko_5 = '재난은 정확히 1년 전 오늘 일어났어요.' WHERE id = 'w_news_A1_18';

UPDATE words SET example_en_2 = 'Many countries sent money to help after the earthquake.', example_ko_2 = '지진 이후 많은 나라들이 돕기 위해 돈을 보냈어요.', example_en_3 = 'Neighbors helped each other after the storm.', example_ko_3 = '이웃들이 폭풍 이후 서로 도왔어요.', example_en_4 = 'The government called on citizens to help the victims.', example_ko_4 = '정부는 시민들에게 피해자들을 돕도록 촉구했어요.', example_en_5 = 'She volunteers every weekend to help at the shelter.', example_ko_5 = '그녀는 매주 주말 대피소에서 봉사해요.' WHERE id = 'w_news_A1_19';

UPDATE words SET example_en_2 = 'The government introduced a new tax on sugary drinks.', example_ko_2 = '정부가 설탕이 든 음료에 새로운 세금을 도입했어요.', example_en_3 = 'A new report says air quality is improving.', example_ko_3 = '새 보고서에 따르면 대기 질이 개선되고 있어요.', example_en_4 = 'The new bridge will open next month.', example_ko_4 = '새 다리가 다음 달에 개통할 거예요.', example_en_5 = 'Voters chose a new leader in yesterday''s election.', example_ko_5 = '유권자들이 어제 선거에서 새 지도자를 선택했어요.' WHERE id = 'w_news_A1_20';

UPDATE words SET example_en_2 = 'The reporter confirmed that the story was true.', example_ko_2 = '기자가 그 기사가 사실임을 확인했어요.', example_en_3 = 'It is not true that the minister resigned.', example_ko_3 = '장관이 사임했다는 것은 사실이 아니에요.', example_en_4 = 'Everything in the report was found to be true.', example_ko_4 = '보고서의 모든 내용이 사실로 밝혀졌어요.', example_en_5 = 'People want to know if the information is true.', example_ko_5 = '사람들은 그 정보가 사실인지 알고 싶어해요.' WHERE id = 'w_news_A1_21';

UPDATE words SET example_en_2 = 'The press was invited to the official announcement.', example_ko_2 = '공식 발표에 언론이 초대됐어요.', example_en_3 = 'Freedom of the press is important in a democracy.', example_ko_3 = '언론의 자유는 민주주의에서 중요해요.', example_en_4 = 'The leader spoke to the press after the meeting.', example_ko_4 = '지도자가 회의 후 언론에 말했어요.', example_en_5 = 'The press reported the scandal in great detail.', example_ko_5 = '언론이 스캔들을 매우 자세히 보도했어요.' WHERE id = 'w_news_A1_22';

UPDATE words SET example_en_2 = 'The leader gave a strong speech about the economy.', example_ko_2 = '지도자가 경제에 대해 강력한 연설을 했어요.', example_en_3 = 'People are looking for a new leader for the country.', example_ko_3 = '사람들은 나라를 이끌 새 지도자를 찾고 있어요.', example_en_4 = 'The leader met with foreign officials today.', example_ko_4 = '지도자가 오늘 외국 관리들과 만났어요.', example_en_5 = 'The world leader arrived in the capital this morning.', example_ko_5 = '세계 지도자가 오늘 아침 수도에 도착했어요.' WHERE id = 'w_news_A1_23';

UPDATE words SET example_en_2 = 'The army was called in to help with flood relief.', example_ko_2 = '홍수 구호를 위해 군대가 투입됐어요.', example_en_3 = 'The army protected the city from attack.', example_ko_3 = '군대가 공격으로부터 도시를 보호했어요.', example_en_4 = 'Thousands of young people joined the army.', example_ko_4 = '수천 명의 젊은이들이 군대에 입대했어요.', example_en_5 = 'The army set up camps for displaced families.', example_ko_5 = '군대가 피난민 가족들을 위한 캠프를 설치했어요.' WHERE id = 'w_news_A1_24';

UPDATE words SET example_en_2 = 'Police are investigating the attack on the marketplace.', example_ko_2 = '경찰이 시장 공격을 조사하고 있어요.', example_en_3 = 'The attack left several people injured.', example_ko_3 = '공격으로 여러 명이 부상을 입었어요.', example_en_4 = 'Security was increased after the attack.', example_ko_4 = '공격 이후 보안이 강화됐어요.', example_en_5 = 'No group has claimed responsibility for the attack yet.', example_ko_5 = '아직 어떤 단체도 공격에 대한 책임을 주장하지 않았어요.' WHERE id = 'w_news_A1_25';

UPDATE words SET example_en_2 = 'The two leaders held a meeting to discuss the crisis.', example_ko_2 = '두 지도자가 위기를 논의하기 위한 회의를 열었어요.', example_en_3 = 'The meeting lasted three hours and ended without a deal.', example_ko_3 = '회의는 세 시간 동안 진행됐고 합의 없이 끝났어요.', example_en_4 = 'The UN called an emergency meeting about the conflict.', example_ko_4 = '유엔이 분쟁에 대한 긴급 회의를 소집했어요.', example_en_5 = 'All ministers attended the meeting at the parliament.', example_ko_5 = '모든 장관이 의회에서 열린 회의에 참석했어요.' WHERE id = 'w_news_A1_26';

UPDATE words SET example_en_2 = 'Aid organizations are delivering food to the affected areas.', example_ko_2 = '구호 단체들이 피해 지역에 식량을 전달하고 있어요.', example_en_3 = 'The lack of food is causing a serious crisis.', example_ko_3 = '식량 부족이 심각한 위기를 일으키고 있어요.', example_en_4 = 'The government promised to provide food for all families.', example_ko_4 = '정부가 모든 가정에 식량을 제공하겠다고 약속했어요.', example_en_5 = 'Food prices have risen sharply due to the conflict.', example_ko_5 = '분쟁으로 인해 식량 가격이 급격히 올랐어요.' WHERE id = 'w_news_A1_27';

UPDATE words SET example_en_2 = 'Schools were closed for two weeks after the disaster.', example_ko_2 = '재난 이후 학교가 2주 동안 문을 닫았어요.', example_en_3 = 'The government is building new schools in rural areas.', example_ko_3 = '정부가 농촌 지역에 새 학교를 짓고 있어요.', example_en_4 = 'Children are returning to school after the ceasefire.', example_ko_4 = '휴전 이후 아이들이 학교로 돌아오고 있어요.', example_en_5 = 'The school was used as a shelter during the flood.', example_ko_5 = '홍수 동안 학교가 대피소로 사용됐어요.' WHERE id = 'w_news_A1_28';

UPDATE words SET example_en_2 = 'The nearest hospital is forty kilometers away.', example_ko_2 = '가장 가까운 병원까지 40킬로미터예요.', example_en_3 = 'Injured people were rushed to the hospital after the attack.', example_ko_3 = '공격 이후 부상자들이 병원으로 급히 이송됐어요.', example_en_4 = 'The hospital is treating hundreds of patients a day.', example_ko_4 = '병원이 하루에 수백 명의 환자를 치료하고 있어요.', example_en_5 = 'More doctors are needed at the hospital in the north.', example_ko_5 = '북부 병원에 더 많은 의사가 필요해요.' WHERE id = 'w_news_A1_29';

UPDATE words SET example_en_2 = 'The army gained more power after the election.', example_ko_2 = '선거 이후 군대가 더 많은 권력을 얻었어요.', example_en_3 = 'The power went out during the storm last night.', example_ko_3 = '어젯밤 폭풍 동안 전력이 나갔어요.', example_en_4 = 'Citizens want to limit the power of the government.', example_ko_4 = '시민들은 정부의 권력을 제한하고 싶어해요.', example_en_5 = 'The president used emergency power to pass the law.', example_ko_5 = '대통령이 법을 통과시키기 위해 비상 권한을 사용했어요.' WHERE id = 'w_news_A1_30';

UPDATE words SET example_en_2 = 'Temperatures in the north dropped to minus twenty degrees.', example_ko_2 = '북쪽 기온이 영하 20도까지 떨어졌어요.', example_en_3 = 'Fighting was reported in the north of the country.', example_ko_3 = '나라 북쪽에서 전투가 보고됐어요.', example_en_4 = 'The north and south of the country have different climates.', example_ko_4 = '나라의 북쪽과 남쪽은 기후가 달라요.', example_en_5 = 'Troops are moving toward the north of the border.', example_ko_5 = '군대가 국경 북쪽으로 이동하고 있어요.' WHERE id = 'w_news_A1_31';

UPDATE words SET example_en_2 = 'The winner of the prize will be announced tomorrow.', example_ko_2 = '상의 수상자는 내일 발표될 거예요.', example_en_3 = 'The winner gave a short speech after the result.', example_ko_3 = '당선자가 결과 이후 짧은 연설을 했어요.', example_en_4 = 'There was no clear winner after the first round of voting.', example_ko_4 = '첫 번째 투표 라운드 후 명확한 승자가 없었어요.', example_en_5 = 'The winner promised to lead the country with honesty.', example_ko_5 = '당선자는 정직하게 나라를 이끌겠다고 약속했어요.' WHERE id = 'w_news_A1_32';

UPDATE words SET example_en_2 = 'Rescue workers found many people dead at the scene.', example_ko_2 = '구조대원들이 현장에서 많은 사람이 사망한 것을 발견했어요.', example_en_3 = 'The report says at least five people are dead.', example_ko_3 = '보도에 따르면 최소 5명이 사망했어요.', example_en_4 = 'The soldier died a hero protecting his country.', example_ko_4 = '그 군인은 나라를 지키다 영웅으로 사망했어요.', example_en_5 = 'The number of dead has risen to over a hundred.', example_ko_5 = '사망자 수가 100명을 넘어섰어요.' WHERE id = 'w_news_A1_33';

UPDATE words SET example_en_2 = 'The government said all hostages are now safe.', example_ko_2 = '정부는 모든 인질이 이제 안전하다고 말했어요.', example_en_3 = 'People are not safe walking alone at night there.', example_ko_3 = '그곳에서 밤에 혼자 걷는 것은 안전하지 않아요.', example_en_4 = 'Aid workers tried to move people to a safe location.', example_ko_4 = '구호 요원들이 사람들을 안전한 장소로 이동시키려고 했어요.', example_en_5 = 'The children were kept safe during the emergency.', example_ko_5 = '비상 사태 동안 아이들이 안전하게 보호됐어요.' WHERE id = 'w_news_A1_34';

UPDATE words SET example_en_2 = 'Reporters used a map to show where the attack happened.', example_ko_2 = '기자들이 공격이 일어난 곳을 보여주기 위해 지도를 사용했어요.', example_en_3 = 'The map shows all the areas hit by the storm.', example_ko_3 = '지도에는 폭풍이 강타한 모든 지역이 나와 있어요.', example_en_4 = 'They looked at a map to plan the evacuation route.', example_ko_4 = '그들은 대피 경로를 계획하기 위해 지도를 봤어요.', example_en_5 = 'The map on the screen showed where the flood was worst.', example_ko_5 = '화면의 지도는 홍수가 가장 심각한 곳을 보여줬어요.' WHERE id = 'w_news_A1_35';

-- ══════════════════════════════════════
-- A2 (35 words)
-- ══════════════════════════════════════

UPDATE words SET example_en_2 = 'She is very interested in politics and reads the news every day.', example_ko_2 = '그녀는 정치에 매우 관심이 있어서 매일 뉴스를 읽어요.', example_en_3 = 'Young people are becoming more engaged in politics.', example_ko_3 = '젊은이들이 정치에 더 많이 참여하고 있어요.', example_en_4 = 'The scandal affected politics in the country for years.', example_ko_4 = '스캔들이 몇 년 동안 그 나라의 정치에 영향을 미쳤어요.', example_en_5 = 'Politics can be difficult to understand for many people.', example_ko_5 = '정치는 많은 사람들이 이해하기 어려울 수 있어요.' WHERE id = 'w_news_A2_01';

UPDATE words SET example_en_2 = 'The economy is growing slowly after the pandemic.', example_ko_2 = '팬데믹 이후 경제가 천천히 성장하고 있어요.', example_en_3 = 'Many families struggled when the economy was weak.', example_ko_3 = '경제가 약했을 때 많은 가족들이 힘들었어요.', example_en_4 = 'The government has a plan to improve the economy.', example_ko_4 = '정부는 경제를 개선할 계획이 있어요.', example_en_5 = 'A strong economy means more jobs for people.', example_ko_5 = '강한 경제는 사람들에게 더 많은 일자리를 의미해요.' WHERE id = 'w_news_A2_02';

UPDATE words SET example_en_2 = 'The protest lasted for three days in the capital.', example_ko_2 = '수도에서 시위가 3일간 계속됐어요.', example_en_3 = 'Workers organized a protest against the new law.', example_ko_3 = '노동자들이 새 법에 반대하는 시위를 조직했어요.', example_en_4 = 'The protest was mostly peaceful but some violence was reported.', example_ko_4 = '시위는 대체로 평화로웠지만 일부 폭력이 보고됐어요.', example_en_5 = 'Students joined the protest to demand better education.', example_ko_5 = '학생들이 더 나은 교육을 요구하는 시위에 합류했어요.' WHERE id = 'w_news_A2_03';

UPDATE words SET example_en_2 = 'Citizens can vote online in this country.', example_ko_2 = '이 나라에서는 시민들이 온라인으로 투표할 수 있어요.', example_en_3 = 'Young people are encouraged to vote in every election.', example_ko_3 = '젊은이들이 모든 선거에서 투표하도록 권장돼요.', example_en_4 = 'The candidate asked everyone to vote for change.', example_ko_4 = '후보자는 모두에게 변화를 위해 투표해 달라고 요청했어요.', example_en_5 = 'About sixty percent of voters chose to vote in the referendum.', example_ko_5 = '유권자의 약 60퍼센트가 국민 투표에 참여하기로 했어요.' WHERE id = 'w_news_A2_04';

UPDATE words SET example_en_2 = 'The president visited the disaster area to show support.', example_ko_2 = '대통령이 지지를 보여주기 위해 재난 지역을 방문했어요.', example_en_3 = 'The president''s speech was watched by millions of people.', example_ko_3 = '대통령의 연설을 수백만 명이 시청했어요.', example_en_4 = 'The two presidents met to discuss the peace agreement.', example_ko_4 = '두 대통령이 평화 협정을 논의하기 위해 만났어요.', example_en_5 = 'The president declared a state of emergency after the flood.', example_ko_5 = '대통령이 홍수 이후 비상사태를 선포했어요.' WHERE id = 'w_news_A2_05';

UPDATE words SET example_en_2 = 'The new law requires all drivers to wear seatbelts.', example_ko_2 = '새 법은 모든 운전자가 안전벨트를 착용하도록 요구해요.', example_en_3 = 'The court decided the law was unfair.', example_ko_3 = '법원은 그 법이 불공평하다고 판결했어요.', example_en_4 = 'People must follow the law or face punishment.', example_ko_4 = '사람들은 법을 따르지 않으면 처벌을 받아요.', example_en_5 = 'A new law was introduced to protect the environment.', example_ko_5 = '환경을 보호하기 위한 새 법이 도입됐어요.' WHERE id = 'w_news_A2_06';

UPDATE words SET example_en_2 = 'Crime rates have fallen in the city over the past year.', example_ko_2 = '지난 한 해 동안 도시의 범죄율이 감소했어요.', example_en_3 = 'She reported the crime to the police immediately.', example_ko_3 = '그녀는 즉시 경찰에 범죄를 신고했어요.', example_en_4 = 'The documentary explored crime in the city''s poorest areas.', example_ko_4 = '다큐멘터리는 도시의 가장 빈곤한 지역의 범죄를 탐구했어요.', example_en_5 = 'Preventing crime requires cooperation between police and communities.', example_ko_5 = '범죄를 예방하려면 경찰과 지역 사회의 협력이 필요해요.' WHERE id = 'w_news_A2_07';

UPDATE words SET example_en_2 = 'Good health is the most important thing in life.', example_ko_2 = '건강은 인생에서 가장 중요한 것이에요.', example_en_3 = 'The government increased spending on health care this year.', example_ko_3 = '정부가 올해 의료에 대한 지출을 늘렸어요.', example_en_4 = 'Air pollution has a negative effect on public health.', example_ko_4 = '대기 오염은 공중 보건에 부정적인 영향을 미쳐요.', example_en_5 = 'The charity works to improve health in developing countries.', example_ko_5 = '자선단체는 개발도상국의 건강을 개선하기 위해 노력해요.' WHERE id = 'w_news_A2_08';

UPDATE words SET example_en_2 = 'The natural disaster caused billions of dollars in damage.', example_ko_2 = '자연재난으로 수십억 달러의 피해가 발생했어요.', example_en_3 = 'Countries around the world helped after the disaster.', example_ko_3 = '재난 이후 전 세계 나라들이 도움을 주었어요.', example_en_4 = 'The disaster left thousands of people without homes.', example_ko_4 = '재난으로 수천 명이 집을 잃었어요.', example_en_5 = 'The government declared the area a disaster zone.', example_ko_5 = '정부가 그 지역을 재난 지역으로 선포했어요.' WHERE id = 'w_news_A2_09';

UPDATE words SET example_en_2 = 'The agreement has the support of the international community.', example_ko_2 = '그 협정은 국제 사회의 지지를 받고 있어요.', example_en_3 = 'An international team of doctors arrived to help.', example_ko_3 = '국제 의사 팀이 도움을 위해 도착했어요.', example_en_4 = 'The issue requires an international solution.', example_ko_4 = '그 문제는 국제적인 해결책이 필요해요.', example_en_5 = 'International pressure is growing on the government to act.', example_ko_5 = '정부가 행동하도록 국제적 압력이 커지고 있어요.' WHERE id = 'w_news_A2_10';

UPDATE words SET example_en_2 = 'The prime minister and her cabinet ministers met this morning.', example_ko_2 = '총리와 내각 장관들이 오늘 아침 만났어요.', example_en_3 = 'The foreign minister flew to the capital for talks.', example_ko_3 = '외무 장관이 회담을 위해 수도로 비행했어요.', example_en_4 = 'The minister of education announced free school meals.', example_ko_4 = '교육부 장관이 무상 급식을 발표했어요.', example_en_5 = 'Three ministers resigned after the scandal became public.', example_ko_5 = '스캔들이 공개된 후 장관 세 명이 사임했어요.' WHERE id = 'w_news_A2_11';

UPDATE words SET example_en_2 = 'The agreement will come into force next January.', example_ko_2 = '협정은 내년 1월에 발효될 거예요.', example_en_3 = 'Reaching an agreement took more than six months of talks.', example_ko_3 = '합의에 도달하는 데 6개월 이상의 회담이 걸렸어요.', example_en_4 = 'Both sides broke the agreement within a week.', example_ko_4 = '양측이 일주일 이내에 합의를 어겼어요.', example_en_5 = 'The trade agreement will benefit farmers on both sides.', example_ko_5 = '무역 협정은 양측 농민들에게 이익이 될 거예요.' WHERE id = 'w_news_A2_12';

UPDATE words SET example_en_2 = 'Soldiers guarded the border to prevent illegal crossings.', example_ko_2 = '군인들이 불법 월경을 막기 위해 국경을 지켰어요.', example_en_3 = 'The border between the two countries was closed suddenly.', example_ko_3 = '두 나라 사이의 국경이 갑자기 폐쇄됐어요.', example_en_4 = 'Many families were separated at the border.', example_ko_4 = '많은 가족이 국경에서 헤어졌어요.', example_en_5 = 'The two sides agreed to open the border for trade.', example_ko_5 = '양측이 무역을 위해 국경을 열기로 합의했어요.' WHERE id = 'w_news_A2_13';

UPDATE words SET example_en_2 = 'The camp provides shelter and food for thousands of refugees.', example_ko_2 = '캠프는 수천 명의 난민에게 피난처와 식량을 제공해요.', example_en_3 = 'Refugees face many difficulties in their new countries.', example_ko_3 = '난민들은 새 나라에서 많은 어려움에 직면해요.', example_en_4 = 'The government promised to accept five thousand refugees.', example_ko_4 = '정부가 5,000명의 난민을 수용하겠다고 약속했어요.', example_en_5 = 'Aid workers are distributing blankets to refugees at the border.', example_ko_5 = '구호 요원들이 국경의 난민들에게 담요를 나눠주고 있어요.' WHERE id = 'w_news_A2_14';

UPDATE words SET example_en_2 = 'The government issued a statement apologizing for the mistake.', example_ko_2 = '정부가 실수에 대해 사과하는 성명을 발표했어요.', example_en_3 = 'The leader''s statement caused anger among opposition parties.', example_ko_3 = '지도자의 성명이 야당 사이에서 분노를 일으켰어요.', example_en_4 = 'She read a prepared statement to the reporters.', example_ko_4 = '그녀는 기자들에게 준비된 성명을 낭독했어요.', example_en_5 = 'The statement confirmed that elections will be held in June.', example_ko_5 = '성명은 선거가 6월에 열릴 것임을 확인했어요.' WHERE id = 'w_news_A2_15';

UPDATE words SET example_en_2 = 'The mayor will announce a new transport plan next week.', example_ko_2 = '시장이 다음 주에 새로운 교통 계획을 발표할 거예요.', example_en_3 = 'The company announced that it would close three factories.', example_ko_3 = '회사가 공장 세 곳을 폐쇄할 것이라고 발표했어요.', example_en_4 = 'She announced her decision to run in the election.', example_ko_4 = '그녀가 선거에 출마하기로 한 결정을 발표했어요.', example_en_5 = 'The UN announced emergency aid for the flood victims.', example_ko_5 = '유엔이 홍수 피해자들을 위한 긴급 지원을 발표했어요.' WHERE id = 'w_news_A2_16';

UPDATE words SET example_en_2 = 'Millions of people must pay more tax under the new plan.', example_ko_2 = '새 계획 아래 수백만 명이 더 많은 세금을 내야 해요.', example_en_3 = 'The opposition says the new tax is unfair to poor families.', example_ko_3 = '야당은 새 세금이 가난한 가족에게 불공평하다고 말해요.', example_en_4 = 'The government uses tax money to pay for schools and hospitals.', example_ko_4 = '정부는 세금을 학교와 병원에 사용해요.', example_en_5 = 'A tax on carbon emissions was introduced this year.', example_ko_5 = '올해 탄소 배출에 대한 세금이 도입됐어요.' WHERE id = 'w_news_A2_17';

UPDATE words SET example_en_2 = 'Trade between the two countries increased by ten percent.', example_ko_2 = '두 나라 사이의 무역이 10퍼센트 증가했어요.', example_en_3 = 'The conflict has badly affected trade in the region.', example_ko_3 = '분쟁이 지역 무역에 심각한 영향을 미쳤어요.', example_en_4 = 'Both sides hope to expand trade after the agreement.', example_ko_4 = '양측은 협정 이후 무역을 확대하기를 희망해요.', example_en_5 = 'The port is one of the busiest trade centers in Asia.', example_ko_5 = '그 항구는 아시아에서 가장 바쁜 무역 중심지 중 하나예요.' WHERE id = 'w_news_A2_18';

UPDATE words SET example_en_2 = 'The climate in this region has become drier over decades.', example_ko_2 = '이 지역의 기후가 수십 년에 걸쳐 더 건조해졌어요.', example_en_3 = 'Scientists are warning about rapid climate change.', example_ko_3 = '과학자들이 급격한 기후 변화에 대해 경고하고 있어요.', example_en_4 = 'The government signed an agreement to fight climate change.', example_ko_4 = '정부가 기후 변화에 맞서 싸우기 위한 협정에 서명했어요.', example_en_5 = 'Climate change is causing more frequent and severe floods.', example_ko_5 = '기후 변화로 인해 홍수가 더 자주, 더 심하게 발생하고 있어요.' WHERE id = 'w_news_A2_19';

UPDATE words SET example_en_2 = 'The charity set up centers to help victims of the disaster.', example_ko_2 = '자선단체가 재난 피해자들을 돕기 위한 센터를 세웠어요.', example_en_3 = 'Victims of the crime received support from the government.', example_ko_3 = '범죄 피해자들이 정부로부터 지원을 받았어요.', example_en_4 = 'The victims spoke about their experiences at the hearing.', example_ko_4 = '피해자들이 청문회에서 자신들의 경험에 대해 이야기했어요.', example_en_5 = 'International organizations are helping victims rebuild their lives.', example_ko_5 = '국제 단체들이 피해자들이 삶을 재건하도록 돕고 있어요.' WHERE id = 'w_news_A2_20';

UPDATE words SET example_en_2 = 'The judge asked both sides to present their evidence.', example_ko_2 = '판사는 양측에게 증거를 제출하라고 요청했어요.', example_en_3 = 'The judge delayed the verdict until next month.', example_ko_3 = '판사가 다음 달까지 판결을 연기했어요.', example_en_4 = 'Both sides argued their cases in front of the judge.', example_ko_4 = '양측이 판사 앞에서 자신들의 사건을 주장했어요.', example_en_5 = 'The judge ruled that the new law was unconstitutional.', example_ko_5 = '판사는 새 법이 위헌이라고 판결했어요.' WHERE id = 'w_news_A2_21';

UPDATE words SET example_en_2 = 'The survey found that most people support the new policy.', example_ko_2 = '여론 조사에 따르면 대부분의 사람들이 새 정책을 지지해요.', example_en_3 = 'A government survey showed rising levels of dissatisfaction.', example_ko_3 = '정부 여론 조사에서 불만족 수준이 높아지고 있는 것으로 나타났어요.', example_en_4 = 'The survey was conducted online with five thousand people.', example_ko_4 = '여론 조사는 5,000명을 대상으로 온라인으로 실시됐어요.', example_en_5 = 'Survey results show more people want stricter environmental laws.', example_ko_5 = '여론 조사 결과 더 많은 사람들이 더 엄격한 환경법을 원한다는 것을 보여줘요.' WHERE id = 'w_news_A2_22';

UPDATE words SET example_en_2 = 'A senior official from the ministry spoke to reporters.', example_ko_2 = '부처의 고위 관리가 기자들에게 이야기했어요.', example_en_3 = 'The official denied any connection to the scandal.', example_ko_3 = '관리는 스캔들과의 어떤 연관도 부인했어요.', example_en_4 = 'Local officials are working to repair the flood damage.', example_ko_4 = '지역 관리들이 홍수 피해를 수리하기 위해 노력하고 있어요.', example_en_5 = 'The official said the investigation would take several weeks.', example_ko_5 = '관리는 조사에 몇 주가 걸릴 것이라고 말했어요.' WHERE id = 'w_news_A2_23';

UPDATE words SET example_en_2 = 'The two leaders spoke about the need for lasting peace.', example_ko_2 = '두 지도자는 지속적인 평화의 필요성에 대해 이야기했어요.', example_en_3 = 'The region has enjoyed peace for twenty years now.', example_ko_3 = '그 지역은 이제 20년 동안 평화를 누리고 있어요.', example_en_4 = 'Citizens marched in the streets to call for peace.', example_ko_4 = '시민들이 평화를 요구하기 위해 거리를 행진했어요.', example_en_5 = 'A peace deal was reached after months of negotiation.', example_ko_5 = '수개월의 협상 끝에 평화 협정이 타결됐어요.' WHERE id = 'w_news_A2_24';

UPDATE words SET example_en_2 = 'The charity works to lift families out of poverty.', example_ko_2 = '자선단체는 가족들을 빈곤에서 구제하기 위해 노력해요.', example_en_3 = 'Poverty in the region increased after the conflict.', example_ko_3 = '분쟁 이후 그 지역의 빈곤이 증가했어요.', example_en_4 = 'The government has a ten-year plan to end poverty.', example_ko_4 = '정부는 빈곤을 종식시키기 위한 10년 계획을 가지고 있어요.', example_en_5 = 'Children living in poverty often lack access to education.', example_ko_5 = '빈곤 속에서 사는 아이들은 종종 교육을 받을 수 없어요.' WHERE id = 'w_news_A2_25';

UPDATE words SET example_en_2 = 'Social media has changed the way people consume news media.', example_ko_2 = '소셜 미디어는 사람들이 뉴스 미디어를 소비하는 방식을 바꿨어요.', example_en_3 = 'The media focused heavily on the election results.', example_ko_3 = '미디어가 선거 결과에 집중적으로 초점을 맞췄어요.', example_en_4 = 'The government accused the media of being biased.', example_ko_4 = '정부는 미디어가 편향됐다고 비난했어요.', example_en_5 = 'Media freedom is protected by the constitution in this country.', example_ko_5 = '이 나라에서는 헌법이 미디어의 자유를 보호해요.' WHERE id = 'w_news_A2_26';

UPDATE words SET example_en_2 = 'The population of the country is expected to decline by 2050.', example_ko_2 = '그 나라 인구는 2050년까지 감소할 것으로 예상돼요.', example_en_3 = 'A large population makes it harder to provide public services.', example_ko_3 = '인구가 많으면 공공 서비스를 제공하기가 더 어려워요.', example_en_4 = 'The disaster forced a large part of the population to flee.', example_ko_4 = '재난으로 인해 인구의 많은 부분이 피난해야 했어요.', example_en_5 = 'The aging population is putting pressure on health services.', example_ko_5 = '고령화 인구가 의료 서비스에 압박을 주고 있어요.' WHERE id = 'w_news_A2_27';

UPDATE words SET example_en_2 = 'Better education leads to better job opportunities.', example_ko_2 = '더 나은 교육은 더 나은 취업 기회로 이어져요.', example_en_3 = 'The government doubled its budget for education.', example_ko_3 = '정부가 교육 예산을 두 배로 늘렸어요.', example_en_4 = 'Children in conflict zones often miss out on education.', example_ko_4 = '분쟁 지역의 아이들은 종종 교육을 받지 못해요.', example_en_5 = 'Access to quality education is a basic human right.', example_ko_5 = '양질의 교육에 대한 접근은 기본적인 인권이에요.' WHERE id = 'w_news_A2_28';

UPDATE words SET example_en_2 = 'The country improved its security after the series of attacks.', example_ko_2 = '그 나라는 일련의 공격 이후 보안을 강화했어요.', example_en_3 = 'Security cameras were installed throughout the city center.', example_ko_3 = '도시 중심부 전역에 보안 카메라가 설치됐어요.', example_en_4 = 'The summit required thousands of security personnel.', example_ko_4 = '정상 회담에는 수천 명의 보안 인력이 필요했어요.', example_en_5 = 'National security is a top priority for the government.', example_ko_5 = '국가 안보는 정부의 최우선 과제예요.' WHERE id = 'w_news_A2_29';

UPDATE words SET example_en_2 = 'The player suffered a serious injury and left the field.', example_ko_2 = '선수가 심각한 부상을 입고 경기장을 떠났어요.', example_en_3 = 'The government counted the number of injuries in the disaster.', example_ko_3 = '정부가 재난에서 부상자 수를 집계했어요.', example_en_4 = 'Injuries from the accident were treated at the local hospital.', example_ko_4 = '사고 부상자들이 지역 병원에서 치료를 받았어요.', example_en_5 = 'Several road workers suffered injuries in the construction accident.', example_ko_5 = '여러 도로 노동자들이 공사 사고로 부상을 입었어요.' WHERE id = 'w_news_A2_30';

UPDATE words SET example_en_2 = 'The country is facing a political crisis after the election.', example_ko_2 = '그 나라는 선거 이후 정치 위기에 직면해 있어요.', example_en_3 = 'The crisis led to emergency talks between the two leaders.', example_ko_3 = '위기로 인해 두 지도자 사이에 긴급 회담이 열렸어요.', example_en_4 = 'International aid arrived to help during the humanitarian crisis.', example_ko_4 = '인도주의적 위기 동안 국제 원조가 도착했어요.', example_en_5 = 'The banking crisis caused millions of people to lose their savings.', example_ko_5 = '금융 위기로 수백만 명이 저축을 잃었어요.' WHERE id = 'w_news_A2_31';

UPDATE words SET example_en_2 = 'The army was placed on high alert after the border incident.', example_ko_2 = '국경 사건 이후 군대가 최고 경계 태세에 들어갔어요.', example_en_3 = 'The army helped build shelters for flood survivors.', example_ko_3 = '군대가 홍수 생존자들을 위해 대피소를 짓는 것을 도왔어요.', example_en_4 = 'The size of the army was reduced after the peace agreement.', example_ko_4 = '평화 협정 이후 군대 규모가 줄었어요.', example_en_5 = 'Both countries agreed not to move their armies closer to the border.', example_ko_5 = '양국은 군대를 국경에 더 가까이 이동하지 않기로 합의했어요.' WHERE id = 'w_news_A2_32';

UPDATE words SET example_en_2 = 'Workers protested outside the factory for three days.', example_ko_2 = '노동자들이 3일 동안 공장 밖에서 시위했어요.', example_en_3 = 'People protested against the government''s decision to cut health spending.', example_ko_3 = '사람들이 정부의 의료 지출 삭감 결정에 반대하여 시위했어요.', example_en_4 = 'Thousands protested peacefully in the main square.', example_ko_4 = '수천 명이 중앙 광장에서 평화롭게 시위했어요.', example_en_5 = 'She protested by refusing to eat for several days.', example_ko_5 = '그녀는 며칠 동안 음식을 거부하며 시위했어요.' WHERE id = 'w_news_A2_33';

UPDATE words SET example_en_2 = 'The prime minister called for unity during the crisis.', example_ko_2 = '총리가 위기 동안 단결을 촉구했어요.', example_en_3 = 'The prime minister''s party lost the election.', example_ko_3 = '총리의 당이 선거에서 졌어요.', example_en_4 = 'The two prime ministers agreed on a new trade deal.', example_ko_4 = '두 총리가 새로운 무역 협정에 합의했어요.', example_en_5 = 'The prime minister announced that she would step down.', example_ko_5 = '총리가 물러나겠다고 발표했어요.' WHERE id = 'w_news_A2_34';

UPDATE words SET example_en_2 = 'The government''s budget did not include funding for new schools.', example_ko_2 = '정부 예산에는 새 학교를 위한 자금이 포함되지 않았어요.', example_en_3 = 'The opposition criticized the budget for cutting health spending.', example_ko_3 = '야당은 의료 지출을 삭감한 예산을 비판했어요.', example_en_4 = 'The budget was passed by a majority in parliament.', example_ko_4 = '예산이 의회에서 다수결로 통과됐어요.', example_en_5 = 'Rising costs have put pressure on the national budget.', example_ko_5 = '비용 상승이 국가 예산에 압박을 가하고 있어요.' WHERE id = 'w_news_A2_35';

-- ══════════════════════════════════════
-- B1 (35 words)
-- ══════════════════════════════════════

UPDATE words SET example_en_2 = 'The party published its new education policy before the election.', example_ko_2 = '정당이 선거 전에 새로운 교육 정책을 발표했어요.', example_en_3 = 'Critics say the policy has failed to reduce unemployment.', example_ko_3 = '비평가들은 그 정책이 실업을 줄이는 데 실패했다고 말해요.', example_en_4 = 'The president''s foreign policy has been praised internationally.', example_ko_4 = '대통령의 외교 정책이 국제적으로 찬사를 받았어요.', example_en_5 = 'A new immigration policy was announced this morning.', example_ko_5 = '오늘 아침 새로운 이민 정책이 발표됐어요.' WHERE id = 'w_news_B1_01';

UPDATE words SET example_en_2 = 'The country''s healthcare reform reduced costs significantly.', example_ko_2 = '그 나라의 의료 개혁이 비용을 크게 줄였어요.', example_en_3 = 'Education reform is needed to prepare students for the future.', example_ko_3 = '학생들이 미래를 준비할 수 있도록 교육 개혁이 필요해요.', example_en_4 = 'The prime minister called reform an urgent national priority.', example_ko_4 = '총리는 개혁이 시급한 국가적 우선 과제라고 말했어요.', example_en_5 = 'Tax reform proposals were debated in parliament all week.', example_ko_5 = '세금 개혁 제안이 일주일 내내 의회에서 논의됐어요.' WHERE id = 'w_news_B1_02';

UPDATE words SET example_en_2 = 'The bill was debated in parliament for three months.', example_ko_2 = '그 법안은 3개월 동안 의회에서 논의됐어요.', example_en_3 = 'Parliament voted to reject the proposed budget cuts.', example_ko_3 = '의회가 예산 삭감안을 거부하는 표결을 했어요.', example_en_4 = 'The new parliament opened with a speech from the president.', example_ko_4 = '새 의회는 대통령의 연설로 시작됐어요.', example_en_5 = 'The opposition boycotted parliament in protest at the new rules.', example_ko_5 = '야당이 새 규칙에 항의하여 의회를 보이콧했어요.' WHERE id = 'w_news_B1_03';

UPDATE words SET example_en_2 = 'The new tax law sparked controversy among business owners.', example_ko_2 = '새 세금법이 사업주들 사이에서 논란을 일으켰어요.', example_en_3 = 'The appointment caused controversy because the candidate had no experience.', example_ko_3 = '후보자에게 경험이 없었기 때문에 임명이 논란이 됐어요.', example_en_4 = 'The decision to close the hospital was met with controversy.', example_ko_4 = '병원 폐쇄 결정이 논란에 부딪혔어요.', example_en_5 = 'The minister tried to avoid controversy by staying silent.', example_ko_5 = '장관은 침묵을 유지하여 논란을 피하려 했어요.' WHERE id = 'w_news_B1_04';

UPDATE words SET example_en_2 = 'The scandal led to a dramatic fall in the party''s poll ratings.', example_ko_2 = '스캔들로 인해 당의 지지율이 급락했어요.', example_en_3 = 'A financial scandal has engulfed the ministry of trade.', example_ko_3 = '금융 스캔들이 무역부를 뒤흔들었어요.', example_en_4 = 'Three officials were fired as a result of the scandal.', example_ko_4 = '스캔들의 결과로 관리 세 명이 해고됐어요.', example_en_5 = 'The media covered the corruption scandal for months.', example_ko_5 = '미디어가 수개월 동안 부패 스캔들을 다뤘어요.' WHERE id = 'w_news_B1_05';

UPDATE words SET example_en_2 = 'The minister promised to address the housing crisis immediately.', example_ko_2 = '장관은 주택 위기를 즉각 해결하겠다고 약속했어요.', example_en_3 = 'The health minister presented a new national vaccination plan.', example_ko_3 = '보건 장관이 새로운 국가 예방 접종 계획을 발표했어요.', example_en_4 = 'The finance minister resigned after the scandal became public.', example_ko_4 = '재무 장관이 스캔들이 공개된 후 사임했어요.', example_en_5 = 'The environment minister launched a new recycling campaign.', example_ko_5 = '환경 장관이 새 재활용 캠페인을 시작했어요.' WHERE id = 'w_news_B1_06';

UPDATE words SET example_en_2 = 'The government pushed new legislation on renewable energy.', example_ko_2 = '정부가 재생 에너지에 관한 새로운 입법을 추진했어요.', example_en_3 = 'Critics argue the legislation is too weak to be effective.', example_ko_3 = '비평가들은 그 입법이 효과적이기에는 너무 약하다고 주장해요.', example_en_4 = 'Anti-corruption legislation was approved after years of debate.', example_ko_4 = '반부패 입법이 수년간의 논쟁 끝에 승인됐어요.', example_en_5 = 'The legislation will come into effect from next January.', example_ko_5 = '입법은 내년 1월부터 시행될 거예요.' WHERE id = 'w_news_B1_07';

UPDATE words SET example_en_2 = 'The opposition staged a walkout in protest at the vote.', example_ko_2 = '야당이 투표에 항의하여 퇴장 시위를 했어요.', example_en_3 = 'A united opposition forced the prime minister to step down.', example_ko_3 = '단결된 야당이 총리를 사임하게 만들었어요.', example_en_4 = 'The opposition called the budget a threat to public services.', example_ko_4 = '야당은 그 예산이 공공 서비스에 대한 위협이라고 말했어요.', example_en_5 = 'The opposition won a surprise majority in the election.', example_ko_5 = '야당이 선거에서 예상 밖의 과반수를 차지했어요.' WHERE id = 'w_news_B1_08';

UPDATE words SET example_en_2 = 'Forming a coalition government took six weeks of negotiations.', example_ko_2 = '연립 정부 구성에 6주간의 협상이 걸렸어요.', example_en_3 = 'The coalition collapsed when the smaller party left.', example_ko_3 = '소규모 정당이 탈퇴하면서 연립이 붕괴됐어요.', example_en_4 = 'A broad coalition of parties supported the peace deal.', example_ko_4 = '광범위한 정당 연립이 평화 협정을 지지했어요.', example_en_5 = 'The ruling coalition lost its majority in the vote.', example_ko_5 = '집권 연립이 투표에서 과반수를 잃었어요.' WHERE id = 'w_news_B1_09';

UPDATE words SET example_en_2 = 'The bilateral summit produced a joint statement on trade.', example_ko_2 = '양자 정상 회담에서 무역에 관한 공동 성명이 나왔어요.', example_en_3 = 'Bilateral relations between the two countries have improved.', example_ko_3 = '두 나라 사이의 양자 관계가 개선됐어요.', example_en_4 = 'Both sides agreed to continue bilateral talks on security.', example_ko_4 = '양측이 안보에 대한 양자 회담을 계속하기로 합의했어요.', example_en_5 = 'A bilateral investment agreement was signed this week.', example_ko_5 = '이번 주 양자 투자 협정이 체결됐어요.' WHERE id = 'w_news_B1_10';

UPDATE words SET example_en_2 = 'A public inquiry found that the government had misled parliament.', example_ko_2 = '공개 조사에서 정부가 의회를 오도했음이 밝혀졌어요.', example_en_3 = 'The opposition demanded an independent inquiry into the matter.', example_ko_3 = '야당이 그 문제에 대한 독립 조사를 요구했어요.', example_en_4 = 'The inquiry is expected to take at least twelve months.', example_ko_4 = '조사는 최소 12개월이 걸릴 것으로 예상돼요.', example_en_5 = 'Witnesses refused to cooperate with the official inquiry.', example_ko_5 = '증인들이 공식 조사에 협조하기를 거부했어요.' WHERE id = 'w_news_B1_11';

UPDATE words SET example_en_2 = 'The campaign raised awareness about water pollution.', example_ko_2 = '캠페인이 수질 오염에 대한 인식을 높였어요.', example_en_3 = 'She ran a successful campaign for the local council.', example_ko_3 = '그녀는 지역 의회를 위한 성공적인 캠페인을 벌였어요.', example_en_4 = 'The campaign focused on economic inequality and job creation.', example_ko_4 = '캠페인은 경제적 불평등과 일자리 창출에 집중했어요.', example_en_5 = 'The health campaign encouraged people to exercise regularly.', example_ko_5 = '건강 캠페인이 사람들에게 규칙적으로 운동하도록 권장했어요.' WHERE id = 'w_news_B1_12';

UPDATE words SET example_en_2 = 'The CEO was forced to resign after the company lost millions.', example_ko_2 = '회사가 수백만 달러를 잃은 후 CEO는 사임해야 했어요.', example_en_3 = 'She decided to resign rather than implement the unpopular policy.', example_ko_3 = '그녀는 인기 없는 정책을 시행하는 대신 사임하기로 결정했어요.', example_en_4 = 'Two senior officials resigned over the data breach scandal.', example_ko_4 = '고위 관리 두 명이 데이터 유출 스캔들로 사임했어요.', example_en_5 = 'He announced his decision to resign at a press conference.', example_ko_5 = '그는 기자 회견에서 사임 결정을 발표했어요.' WHERE id = 'w_news_B1_13';

UPDATE words SET example_en_2 = 'The investigation revealed widespread corruption inside the police force.', example_ko_2 = '조사에서 경찰 내부의 광범위한 부패가 드러났어요.', example_en_3 = 'Voters punished the party because of corruption allegations.', example_ko_3 = '유권자들이 부패 혐의 때문에 그 당을 처벌했어요.', example_en_4 = 'The new government promised to tackle corruption aggressively.', example_ko_4 = '새 정부는 부패에 적극적으로 대처하겠다고 약속했어요.', example_en_5 = 'International monitors were brought in to help fight corruption.', example_ko_5 = '부패 퇴치를 돕기 위해 국제 감시단이 초청됐어요.' WHERE id = 'w_news_B1_14';

UPDATE words SET example_en_2 = 'Inflation is eroding the purchasing power of ordinary families.', example_ko_2 = '인플레이션이 일반 가정의 구매력을 잠식하고 있어요.', example_en_3 = 'The central bank raised interest rates to fight inflation.', example_ko_3 = '중앙은행이 인플레이션과 싸우기 위해 금리를 올렸어요.', example_en_4 = 'Inflation fell to two percent for the first time in years.', example_ko_4 = '인플레이션이 몇 년 만에 처음으로 2퍼센트로 떨어졌어요.', example_en_5 = 'Workers demanded higher wages to keep up with inflation.', example_ko_5 = '노동자들이 인플레이션을 따라잡기 위해 더 높은 임금을 요구했어요.' WHERE id = 'w_news_B1_15';

UPDATE words SET example_en_2 = 'The senate is debating whether to ratify the new treaty.', example_ko_2 = '상원이 새 조약을 비준할지 논의하고 있어요.', example_en_3 = 'The treaty reduced tariffs on goods traded between the nations.', example_ko_3 = '조약이 나라들 사이에 거래되는 상품의 관세를 낮췄어요.', example_en_4 = 'She argued the treaty violated the country''s sovereignty.', example_ko_4 = '그녀는 조약이 나라의 주권을 침해한다고 주장했어요.', example_en_5 = 'The security treaty obliged both nations to defend each other.', example_ko_5 = '안보 조약은 두 나라가 서로를 방어하도록 의무화했어요.' WHERE id = 'w_news_B1_16';

UPDATE words SET example_en_2 = 'The ceasefire gave civilians a chance to receive aid.', example_ko_2 = '휴전은 민간인들이 원조를 받을 기회를 줬어요.', example_en_3 = 'The ceasefire broke down after only forty-eight hours.', example_ko_3 = '휴전은 48시간도 안 돼 무너졌어요.', example_en_4 = 'International observers monitored the ceasefire closely.', example_ko_4 = '국제 관찰자들이 휴전을 면밀히 감시했어요.', example_en_5 = 'The ceasefire allowed families to bury their dead.', example_ko_5 = '휴전으로 가족들이 사망자를 매장할 수 있게 됐어요.' WHERE id = 'w_news_B1_17';

UPDATE words SET example_en_2 = 'World leaders gathered at the summit to discuss climate finance.', example_ko_2 = '세계 지도자들이 기후 금융을 논의하기 위해 정상 회담에 모였어요.', example_en_3 = 'The summit ended without a final agreement being reached.', example_ko_3 = '정상 회담은 최종 합의 없이 끝났어요.', example_en_4 = 'The host city spent millions preparing for the summit.', example_ko_4 = '개최 도시는 정상 회담을 준비하는 데 수백만 달러를 썼어요.', example_en_5 = 'A historic agreement was signed at the summit.', example_ko_5 = '정상 회담에서 역사적인 협정이 체결됐어요.' WHERE id = 'w_news_B1_18';

UPDATE words SET example_en_2 = 'The UN imposed sanctions on the country after the military coup.', example_ko_2 = '군사 쿠데타 이후 유엔이 그 나라에 제재를 부과했어요.', example_en_3 = 'Tougher sanctions are being considered to change the regime''s behavior.', example_ko_3 = '정권의 행동을 변화시키기 위해 더 강력한 제재가 검토되고 있어요.', example_en_4 = 'The sanctions have severely damaged the country''s economy.', example_ko_4 = '제재가 그 나라의 경제에 심각한 피해를 입혔어요.', example_en_5 = 'Several European countries refused to join the sanctions.', example_ko_5 = '여러 유럽 국가들이 제재에 참여하기를 거부했어요.' WHERE id = 'w_news_B1_19';

UPDATE words SET example_en_2 = 'The charity is calling for greater humanitarian access to the region.', example_ko_2 = '자선단체가 그 지역에 대한 더 큰 인도주의적 접근을 요구하고 있어요.', example_en_3 = 'The UN sent a humanitarian mission to assess the situation.', example_ko_3 = '유엔이 상황을 평가하기 위해 인도주의적 임무단을 보냈어요.', example_en_4 = 'The government was accused of blocking humanitarian aid.', example_ko_4 = '정부가 인도주의적 지원을 막고 있다는 비난을 받았어요.', example_en_5 = 'Humanitarian organizations are working around the clock in the war zone.', example_ko_5 = '인도주의 단체들이 전쟁 지역에서 24시간 내내 일하고 있어요.' WHERE id = 'w_news_B1_20';

UPDATE words SET example_en_2 = 'Years of conflict have left the country''s infrastructure in ruins.', example_ko_2 = '수년간의 분쟁으로 그 나라의 사회 기반 시설이 폐허가 됐어요.', example_en_3 = 'Investing in infrastructure creates jobs and boosts the economy.', example_ko_3 = '사회 기반 시설에 투자하면 일자리가 창출되고 경제가 활성화돼요.', example_en_4 = 'The flood caused massive damage to transport infrastructure.', example_ko_4 = '홍수가 교통 사회 기반 시설에 막대한 피해를 입혔어요.', example_en_5 = 'The new government pledged billions for infrastructure development.', example_ko_5 = '새 정부가 사회 기반 시설 개발을 위해 수십억 달러를 약속했어요.' WHERE id = 'w_news_B1_21';

UPDATE words SET example_en_2 = 'Negotiations between the two sides broke down after three days.', example_ko_2 = '양측 간의 협상이 3일 후 결렬됐어요.', example_en_3 = 'The negotiation process is slow but both sides remain committed.', example_ko_3 = '협상 과정이 느리지만 양측 모두 헌신적이에요.', example_en_4 = 'Successful negotiation requires patience and mutual compromise.', example_ko_4 = '성공적인 협상에는 인내와 상호 타협이 필요해요.', example_en_5 = 'The final negotiation lasted thirty-six hours without a break.', example_ko_5 = '최종 협상은 36시간 동안 쉬지 않고 계속됐어요.' WHERE id = 'w_news_B1_22';

UPDATE words SET example_en_2 = 'Workers demonstrated in front of the parliament building.', example_ko_2 = '노동자들이 의회 건물 앞에서 시위했어요.', example_en_3 = 'Citizens demonstrated their support for the president on the street.', example_ko_3 = '시민들이 거리에서 대통령에 대한 지지를 시위로 나타냈어요.', example_en_4 = 'Farmers demonstrated against the new agricultural import rules.', example_ko_4 = '농부들이 새로운 농산물 수입 규정에 반대하여 시위했어요.', example_en_5 = 'Tens of thousands demonstrated peacefully in the city center.', example_ko_5 = '수만 명이 도시 중심부에서 평화롭게 시위했어요.' WHERE id = 'w_news_B1_23';

UPDATE words SET example_en_2 = 'Unemployment fell to its lowest level in a decade.', example_ko_2 = '실업이 10년 만에 최저 수준으로 떨어졌어요.', example_en_3 = 'Young people are hardest hit by unemployment in this region.', example_ko_3 = '이 지역에서 청년들이 실업으로 가장 심하게 타격받아요.', example_en_4 = 'The government plans to create jobs to reduce unemployment.', example_ko_4 = '정부는 실업을 줄이기 위해 일자리를 만들 계획이에요.', example_en_5 = 'Long-term unemployment leads to serious social problems.', example_ko_5 = '장기 실업은 심각한 사회 문제로 이어져요.' WHERE id = 'w_news_B1_24';

UPDATE words SET example_en_2 = 'The jury deliberated for three days before reaching a verdict.', example_ko_2 = '배심원은 판결에 도달하기 전 3일 동안 심의했어요.', example_en_3 = 'The guilty verdict was welcomed by the victim''s family.', example_ko_3 = '유죄 판결이 피해자 가족에게 환영받았어요.', example_en_4 = 'Many people were surprised by the not-guilty verdict.', example_ko_4 = '많은 사람들이 무죄 판결에 놀랐어요.', example_en_5 = 'The verdict was read out in court on Thursday morning.', example_ko_5 = '판결은 목요일 아침 법정에서 낭독됐어요.' WHERE id = 'w_news_B1_25';

UPDATE words SET example_en_2 = 'The president held a press conference to deny the allegations.', example_ko_2 = '대통령이 혐의를 부인하기 위해 기자 회견을 열었어요.', example_en_3 = 'The minister walked out of the press conference unexpectedly.', example_ko_3 = '장관이 갑자기 기자 회견장을 떠났어요.', example_en_4 = 'Several difficult questions were raised at the press conference.', example_ko_4 = '기자 회견에서 여러 어려운 질문들이 제기됐어요.', example_en_5 = 'The press conference was broadcast live on national television.', example_ko_5 = '기자 회견이 국영 텔레비전에서 생방송으로 중계됐어요.' WHERE id = 'w_news_B1_26';

UPDATE words SET example_en_2 = 'The ruling party secured a comfortable majority in parliament.', example_ko_2 = '집권당이 의회에서 편안한 과반수를 확보했어요.', example_en_3 = 'The motion failed to win a majority and was rejected.', example_ko_3 = '그 안건은 과반수를 얻지 못해 부결됐어요.', example_en_4 = 'A two-thirds majority is needed to change the constitution.', example_ko_4 = '헌법을 바꾸려면 3분의 2의 과반수가 필요해요.', example_en_5 = 'The majority of voters chose to stay in the trading bloc.', example_ko_5 = '대다수 유권자들이 무역 블록에 남기로 선택했어요.' WHERE id = 'w_news_B1_27';

UPDATE words SET example_en_2 = 'The senator denied all accusations of taking bribes.', example_ko_2 = '상원 의원은 뇌물 수수 혐의를 모두 부인했어요.', example_en_3 = 'Accusations of misconduct were leveled at the police chief.', example_ko_3 = '경찰서장에게 비위 혐의가 제기됐어요.', example_en_4 = 'The accusations were investigated but no evidence was found.', example_ko_4 = '혐의가 조사됐지만 증거가 발견되지 않았어요.', example_en_5 = 'Making false accusations can damage someone''s reputation seriously.', example_ko_5 = '거짓 혐의를 제기하면 누군가의 평판을 심각하게 훼손할 수 있어요.' WHERE id = 'w_news_B1_28';

UPDATE words SET example_en_2 = 'Low turnout has become a problem for democracy.', example_ko_2 = '낮은 투표율이 민주주의의 문제가 됐어요.', example_en_3 = 'The party was shocked by the high turnout among young voters.', example_ko_3 = '당은 젊은 유권자들의 높은 투표율에 놀랐어요.', example_en_4 = 'The turnout at the meeting was far lower than expected.', example_ko_4 = '회의 참여율이 예상보다 훨씬 낮았어요.', example_en_5 = 'Analysts said high turnout helped the opposition win the election.', example_ko_5 = '분석가들은 높은 투표율이 야당의 선거 승리에 도움이 됐다고 말했어요.' WHERE id = 'w_news_B1_29';

UPDATE words SET example_en_2 = 'The court imposed a fine of ten million dollars on the company.', example_ko_2 = '법원이 그 회사에 1,000만 달러의 벌금을 부과했어요.', example_en_3 = 'The government threatened to impose tariffs on imported goods.', example_ko_3 = '정부는 수입품에 관세를 부과하겠다고 위협했어요.', example_en_4 = 'New restrictions were imposed on travel to the affected region.', example_ko_4 = '피해 지역으로의 여행에 새로운 제한이 부과됐어요.', example_en_5 = 'Authorities imposed a curfew to maintain order after the riot.', example_ko_5 = '당국이 폭동 이후 질서를 유지하기 위해 통행금지를 부과했어요.' WHERE id = 'w_news_B1_30';

UPDATE words SET example_en_2 = 'The country''s closest ally offered to help with the crisis.', example_ko_2 = '그 나라의 가장 가까운 동맹국이 위기를 도와주겠다고 제안했어요.', example_en_3 = 'NATO allies agreed to increase defense spending.', example_ko_3 = 'NATO 동맹국들이 방위 지출을 늘리기로 합의했어요.', example_en_4 = 'Relations with key allies were strained by the trade dispute.', example_ko_4 = '무역 분쟁으로 주요 동맹국들과의 관계가 긴장됐어요.', example_en_5 = 'The president consulted his allies before announcing the decision.', example_ko_5 = '대통령이 결정을 발표하기 전에 동맹국들과 상의했어요.' WHERE id = 'w_news_B1_31';

UPDATE words SET example_en_2 = 'Prosecutors presented new evidence linking the suspect to the crime.', example_ko_2 = '검사들이 용의자를 범죄와 연결하는 새로운 증거를 제출했어요.', example_en_3 = 'The evidence was dismissed as unreliable by the defense lawyer.', example_ko_3 = '증거가 변호인에 의해 신뢰할 수 없다고 기각됐어요.', example_en_4 = 'Scientists published evidence showing the link between pollution and disease.', example_ko_4 = '과학자들이 오염과 질병 사이의 연관성을 보여주는 증거를 발표했어요.', example_en_5 = 'There is growing evidence that the data was manipulated.', example_ko_5 = '데이터가 조작됐다는 증거가 늘어나고 있어요.' WHERE id = 'w_news_B1_32';

UPDATE words SET example_en_2 = 'A free press and fair elections are the foundations of democracy.', example_ko_2 = '자유 언론과 공정한 선거는 민주주의의 기반이에요.', example_en_3 = 'The new government promised to restore democracy after the coup.', example_ko_3 = '새 정부는 쿠데타 이후 민주주의를 회복하겠다고 약속했어요.', example_en_4 = 'Citizens marched to defend democracy and free expression.', example_ko_4 = '시민들이 민주주의와 표현의 자유를 지키기 위해 행진했어요.', example_en_5 = 'International observers praised the election as a triumph for democracy.', example_ko_5 = '국제 관찰자들이 선거를 민주주의의 승리라고 찬사했어요.' WHERE id = 'w_news_B1_33';

UPDATE words SET example_en_2 = 'Aid agencies report more refugees are arriving at the border.', example_ko_2 = '구호 단체들이 더 많은 난민이 국경에 도착하고 있다고 보고해요.', example_en_3 = 'Many refugees have been waiting in camps for over three years.', example_ko_3 = '많은 난민들이 3년 이상 캠프에서 기다리고 있어요.', example_en_4 = 'The government pledged to double the number of refugees it accepts.', example_ko_4 = '정부는 받아들이는 난민 수를 두 배로 늘리겠다고 약속했어요.', example_en_5 = 'Refugees are often among the most vulnerable people in the world.', example_ko_5 = '난민들은 종종 세계에서 가장 취약한 사람들에 속해요.' WHERE id = 'w_news_B1_34';

UPDATE words SET example_en_2 = 'Negotiators missed the deadline for reaching a peace deal.', example_ko_2 = '협상가들이 평화 협정을 위한 시한을 놓쳤어요.', example_en_3 = 'The government set a deadline of three months for the reform.', example_ko_3 = '정부가 개혁을 위한 3개월의 시한을 설정했어요.', example_en_4 = 'Reporters had to meet a tight deadline to file their stories.', example_ko_4 = '기자들은 기사를 제출하기 위해 촉박한 마감 시한을 맞춰야 했어요.', example_en_5 = 'International monitors warned that the deadline must not be extended again.', example_ko_5 = '국제 감시단은 시한이 다시 연장되어서는 안 된다고 경고했어요.' WHERE id = 'w_news_B1_35';

