-- EngCat — Environment (환경) topic
-- 210 words (35 per CEFR level A1~C2) + 42 patterns (7 per level)
-- Columns: id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword

-- ══════════════════════════════════════
-- WORDS — A1 (기초 환경 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_environment_A1_01','tree','/triː/','noun','나무','A tall plant with a woody trunk, branches, and leaves.','We planted a {tree} in the garden.','우리는 정원에 나무를 심었어요.','tree','A1','environment',1,'tree nature green park forest'),
('w_environment_A1_02','water','/ˈwɔːtər/','noun','물','A clear liquid that is essential for all living things.','Please don''t waste {water} when you brush your teeth.','양치할 때 물을 낭비하지 마세요.','water','A1','environment',1,'water tap running faucet clean'),
('w_environment_A1_03','air','/ɛr/','noun','공기','The invisible mixture of gases that surrounds the Earth.','Fresh {air} is good for your health.','신선한 공기는 건강에 좋아요.','air','A1','environment',1,'fresh air sky clouds outdoor'),
('w_environment_A1_04','clean','/kliːn/','adjective','깨끗한','Free from dirt, pollution, or harmful substances.','We should keep our streets {clean}.','우리는 거리를 깨끗하게 유지해야 해요.','clean','A1','environment',1,'clean street tidy neighborhood outdoor'),
('w_environment_A1_05','nature','/ˈneɪtʃər/','noun','자연','The physical world including plants, animals, and landscape.','I love spending time in {nature}.','저는 자연 속에서 시간을 보내는 걸 좋아해요.','nature','A1','environment',1,'nature landscape forest mountains outdoor'),
('w_environment_A1_06','sun','/sʌn/','noun','태양','The star at the centre of our solar system that gives light and heat.','The {sun} provides energy for plants to grow.','태양은 식물이 자랄 수 있는 에너지를 제공해요.','sun','A1','environment',1,'sun sunlight sky blue bright'),
('w_environment_A1_07','earth','/ɜːrθ/','noun','지구','The planet on which we live; also the soil of the ground.','We must take care of the {earth}.','우리는 지구를 소중히 지켜야 해요.','earth','A1','environment',1,'earth planet globe space view'),
('w_environment_A1_08','green','/ɡriːn/','adjective','초록의, 친환경의','The colour of plants; also meaning environmentally friendly.','Let''s try to live a more {green} lifestyle.','더 친환경적인 생활 방식을 실천해 봐요.','green','A1','environment',1,'green lifestyle eco bag bicycle'),
('w_environment_A1_09','plant','/plænt/','noun','식물','A living organism that grows in the ground and uses sunlight for food.','Each {plant} needs water and sunlight to survive.','모든 식물은 살기 위해 물과 햇빛이 필요해요.','plant','A1','environment',1,'plant pot indoor green leaf'),
('w_environment_A1_10','animal','/ˈænɪməl/','noun','동물','A living creature that can move and is not a plant.','Every {animal} needs a clean habitat to survive.','모든 동물은 살아남기 위해 깨끗한 서식지가 필요해요.','animal','A1','environment',1,'animal wildlife forest nature habitat'),
('w_environment_A1_11','rain','/reɪn/','noun','비','Water that falls from the sky as small drops.','The {rain} fills rivers and provides fresh water.','비는 강을 채우고 담수를 공급해요.','rain','A1','environment',1,'rain drops water puddle street'),
('w_environment_A1_12','sky','/skaɪ/','noun','하늘','The region of the atmosphere seen from the earth.','The {sky} turns orange at sunset.','해질 때 하늘이 주황빛으로 변해요.','sky','A1','environment',1,'sky blue clouds sunset horizon'),
('w_environment_A1_13','flower','/ˈflaʊər/','noun','꽃','The colourful part of a plant that attracts insects for pollination.','Bees visit each {flower} to collect pollen.','벌들은 꽃가루를 모으기 위해 꽃마다 찾아다녀요.','flower','A1','environment',1,'flower garden bee pollen bloom'),
('w_environment_A1_14','river','/ˈrɪvər/','noun','강','A large natural stream of water flowing to the sea or a lake.','Children love playing by the {river}.','아이들은 강가에서 노는 걸 좋아해요.','river','A1','environment',1,'river flowing water nature landscape'),
('w_environment_A1_15','snow','/snəʊ/','noun','눈','Frozen water that falls from the sky in white flakes.','Heavy {snow} covered the forest overnight.','밤새 많은 눈이 숲을 덮었어요.','snow','A1','environment',1,'snow winter forest white landscape'),
('w_environment_A1_16','wind','/wɪnd/','noun','바람','The natural movement of air across the Earth''s surface.','The {wind} turned the blades of the windmill.','바람이 풍차 날개를 돌렸어요.','wind','A1','environment',1,'wind turbine windmill energy field'),
('w_environment_A1_17','sea','/siː/','noun','바다','The large area of salt water that covers most of the Earth.','Millions of species live in the {sea}.','수백만 종의 생물이 바다에 살아요.','sea','A1','environment',1,'sea ocean blue waves horizon'),
('w_environment_A1_18','mountain','/ˈmaʊntɪn/','noun','산','A large natural elevation of the Earth''s surface.','Snow never melts at the top of that {mountain}.','저 산 꼭대기에는 눈이 절대 녹지 않아요.','mountain','A1','environment',1,'mountain snow peak landscape scenic'),
('w_environment_A1_19','grass','/ɡræs/','noun','풀, 잔디','Small green plants that cover the ground in fields and gardens.','The {grass} was wet with morning dew.','잔디가 아침 이슬로 촉촉했어요.','grass','A1','environment',1,'grass green field meadow dew'),
('w_environment_A1_20','bird','/bɜːrd/','noun','새','A warm-blooded animal with feathers, wings, and a beak.','The {bird} sang in the tree at sunrise.','새는 해가 뜰 때 나무 위에서 노래했어요.','bird','A1','environment',1,'bird singing tree branch sunrise'),
('w_environment_A1_21','fish','/fɪʃ/','noun','물고기','A cold-blooded animal that lives in water and breathes through gills.','Many {fish} are disappearing because of ocean pollution.','해양 오염으로 많은 물고기가 사라지고 있어요.','fish','A1','environment',1,'fish underwater ocean coral reef'),
('w_environment_A1_22','forest','/ˈfɔːrɪst/','noun','숲','A large area of land covered with trees.','The {forest} provides oxygen for us to breathe.','숲은 우리가 숨 쉴 수 있는 산소를 제공해요.','forest','A1','environment',1,'forest trees dense green sunlight'),
('w_environment_A1_23','light','/laɪt/','noun','빛','The natural energy from the sun that allows us to see.','Turn off the {light} when you leave the room.','방을 나갈 때 불을 꺼 주세요.','light','A1','environment',1,'light switch saving electricity room'),
('w_environment_A1_24','park','/pɑːrk/','noun','공원','A public area of land with grass and trees for recreation.','People enjoy walking in the {park} on weekends.','사람들은 주말에 공원 산책을 즐겨요.','park','A1','environment',1,'park green trees people walking'),
('w_environment_A1_25','leaf','/liːf/','noun','나뭇잎','A flat, thin part of a plant that absorbs sunlight.','Each {leaf} turns red and gold in autumn.','가을이 되면 나뭇잎이 빨갛고 금색으로 변해요.','leaf','A1','environment',1,'leaf autumn fall red orange yellow'),
('w_environment_A1_26','soil','/sɔɪl/','noun','흙, 토양','The top layer of the earth in which plants grow.','Healthy {soil} is the foundation of all farming.','건강한 토양은 모든 농업의 기초예요.','soil','A1','environment',1,'soil earth ground fertile farming'),
('w_environment_A1_27','lake','/leɪk/','noun','호수','A large area of water surrounded by land.','The {lake} reflects the mountains behind it.','호수는 뒤의 산을 반영해요.','lake','A1','environment',1,'lake mountain reflection calm water'),
('w_environment_A1_28','cloud','/klaʊd/','noun','구름','A white or grey mass of water vapour in the sky.','Dark {cloud}s filled the sky before the storm.','폭풍 전에 검은 구름이 하늘을 가득 채웠어요.','cloud','A1','environment',1,'clouds storm sky dramatic dark'),
('w_environment_A1_29','sand','/sænd/','noun','모래','Tiny grains of rock found on beaches and in deserts.','The {sand} on the beach was warm under my feet.','해변의 모래가 발 아래에서 따뜻했어요.','sand','A1','environment',1,'sand beach warm summer ocean'),
('w_environment_A1_30','ice','/aɪs/','noun','얼음','Frozen water; the solid form of water.','The {ice} on the pond was melting in spring.','봄이 되자 연못의 얼음이 녹고 있었어요.','ice','A1','environment',1,'ice melting spring pond nature'),
('w_environment_A1_31','rock','/rɒk/','noun','바위, 돌','A hard mineral material that forms part of the earth''s surface.','The climber gripped the {rock} tightly.','등반가는 바위를 꼭 잡았어요.','rock','A1','environment',1,'rock cliff nature landscape hiking'),
('w_environment_A1_32','field','/fiːld/','noun','들판','An open area of land, usually covered with grass or crops.','Sunflowers grew across the entire {field}.','해바라기가 들판 전체에 피어 있었어요.','field','A1','environment',1,'sunflower field yellow rural summer'),
('w_environment_A1_33','hot','/hɒt/','adjective','더운','Having a high temperature; the opposite of cold.','It is getting {hot}ter every summer due to climate change.','기후 변화로 인해 매년 여름이 더 더워지고 있어요.','hotter','A1','environment',1,'hot summer heat heatwave sun'),
('w_environment_A1_34','cold','/kəʊld/','adjective','추운','Having a low temperature; the opposite of hot.','Winters are getting longer and more {cold} in some regions.','일부 지역에서는 겨울이 더 길고 추워지고 있어요.','cold','A1','environment',1,'cold winter frost snow landscape'),
('w_environment_A1_35','bush','/bʊʃ/','noun','덤불, 관목','A shrub or small thick tree with many branches.','A rabbit hid behind the {bush} in the garden.','토끼 한 마리가 정원의 덤불 뒤에 숨었어요.','bush','A1','environment',1,'bush shrub garden nature rabbit');

-- ══════════════════════════════════════
-- WORDS — A2 (환경 실천 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_environment_A2_01','recycle','/riːˈsaɪkəl/','verb','재활용하다','To process used materials so they can be used again.','Please {recycle} your plastic bottles.','플라스틱 병을 재활용해 주세요.','recycle','A2','environment',1,'recycling bin plastic bottles sorting'),
('w_environment_A2_02','pollution','/pəˈluːʃən/','noun','오염','The presence of harmful substances in the environment.','Air {pollution} in cities affects people''s health.','도시의 대기 오염은 사람들의 건강에 영향을 미쳐요.','pollution','A2','environment',1,'air pollution smog city skyline haze'),
('w_environment_A2_03','energy','/ˈenədʒi/','noun','에너지','Power from sources such as electricity, fuel, or the sun.','We need to use less {energy} at home.','집에서 에너지를 덜 사용해야 해요.','energy','A2','environment',1,'energy saving lightbulb electricity home'),
('w_environment_A2_04','waste','/weɪst/','noun','쓰레기, 낭비','Material that is no longer useful and is thrown away.','Reducing food {waste} helps the environment.','음식 쓰레기를 줄이면 환경에 도움이 돼요.','waste','A2','environment',1,'food waste bin kitchen organic'),
('w_environment_A2_05','solar','/ˈsəʊlər/','adjective','태양의, 태양 에너지의','Relating to energy from the sun.','They installed {solar} panels on the roof.','그들은 지붕에 태양광 패널을 설치했어요.','solar','A2','environment',1,'solar panels roof rooftop sunlight'),
('w_environment_A2_06','protect','/prəˈtekt/','verb','보호하다','To keep someone or something safe from harm.','We must {protect} endangered animals.','우리는 멸종 위기 동물들을 보호해야 해요.','protect','A2','environment',1,'protect wildlife animal endangered sanctuary'),
('w_environment_A2_07','reduce','/rɪˈdjuːs/','verb','줄이다','To make something smaller in amount or degree.','Try to {reduce} the amount of plastic you use.','사용하는 플라스틱의 양을 줄여 보세요.','reduce','A2','environment',1,'reduce plastic bag reusable shopping'),
('w_environment_A2_08','reuse','/riːˈjuːz/','verb','재사용하다','To use something again instead of throwing it away.','You can {reuse} glass jars for storage.','유리병을 수납에 재사용할 수 있어요.','reuse','A2','environment',1,'reuse glass jar storage kitchen'),
('w_environment_A2_09','trash','/træʃ/','noun','쓰레기','Waste material that is thrown away; rubbish.','Don''t throw {trash} on the ground.','바닥에 쓰레기를 버리지 마세요.','trash','A2','environment',1,'trash rubbish litter street cleanup'),
('w_environment_A2_10','save','/seɪv/','verb','절약하다, 아끼다','To avoid spending or wasting something.','Turn off the tap to {save} water.','물을 아끼려면 수도꼭지를 잠그세요.','save','A2','environment',1,'save water tap off faucet'),
('w_environment_A2_11','clean up','/kliːn ʌp/','phrase','청소하다, 정화하다','To remove dirt, rubbish, or pollution from a place.','Volunteers met to {clean up} the beach.','자원봉사자들이 해변을 청소하기 위해 모였어요.','clean up','A2','environment',1,'beach cleanup volunteers plastic bags'),
('w_environment_A2_12','smoke','/sməʊk/','noun','연기, 매연','Gas and particles produced when something burns.','Factory {smoke} is a major cause of air pollution.','공장 매연은 대기 오염의 주요 원인이에요.','smoke','A2','environment',1,'factory smoke pollution chimney industrial'),
('w_environment_A2_13','electric','/ɪˈlektrɪk/','adjective','전기의','Powered by electricity rather than fuel.','More people are buying {electric} cars.','전기차를 구매하는 사람들이 늘고 있어요.','electric','A2','environment',1,'electric car charging station clean energy'),
('w_environment_A2_14','natural','/ˈnætʃərəl/','adjective','자연의','Existing in or produced by nature.','We should protect {natural} habitats.','우리는 자연 서식지를 보호해야 해요.','natural','A2','environment',1,'natural habitat wildlife forest river'),
('w_environment_A2_15','ocean','/ˈəʊʃən/','noun','바다, 해양','The vast body of salt water that covers most of the earth.','Plastic in the {ocean} harms sea life.','바다 속 플라스틱은 해양 생물에게 해를 끼쳐요.','ocean','A2','environment',1,'ocean plastic pollution sea turtle'),
('w_environment_A2_16','plant','/plænt/','verb','심다','To put a seed or young plant into the ground to grow.','We {plant} trees every year on Earth Day.','지구의 날마다 나무를 심어요.','plant','A2','environment',1,'planting tree earth day volunteers'),
('w_environment_A2_17','environment','/ɪnˈvaɪrənmənt/','noun','환경','The natural world around us, including air, water, and land.','We must protect the {environment} for future generations.','미래 세대를 위해 환경을 보호해야 해요.','environment','A2','environment',1,'environment nature green earth planet'),
('w_environment_A2_18','garbage','/ˈɡɑːrbɪdʒ/','noun','쓰레기','Waste food and other material that is thrown away.','There was {garbage} scattered along the riverbank.','강둑을 따라 쓰레기가 흩어져 있었어요.','garbage','A2','environment',1,'garbage river bank littering pollution'),
('w_environment_A2_19','toxic','/ˈtɒksɪk/','adjective','독성의, 유해한','Poisonous or harmful to living organisms.','The factory was releasing {toxic} chemicals into the river.','공장이 강에 독성 화학 물질을 방류하고 있었어요.','toxic','A2','environment',1,'toxic chemicals warning sign industrial'),
('w_environment_A2_20','cut down','/kʌt daʊn/','phrase','벌목하다, 줄이다','To fell a tree; or to reduce the amount of something.','We should not {cut down} trees unnecessarily.','불필요하게 나무를 베어서는 안 돼요.','cut down','A2','environment',1,'logging deforestation tree cutting chainsaw'),
('w_environment_A2_21','fuel','/fjuːəl/','noun','연료','A material that is burned to produce energy.','Cars that run on fossil {fuel} produce a lot of CO₂.','화석 연료로 달리는 차는 이산화탄소를 많이 배출해요.','fuel','A2','environment',1,'fuel gas station petrol car filling'),
('w_environment_A2_22','melt','/melt/','verb','녹다','To change from solid to liquid due to heat.','Polar ice caps are {melting} because of global warming.','지구 온난화로 인해 극지방 빙하가 녹고 있어요.','melting','A2','environment',1,'melting ice arctic polar glacier'),
('w_environment_A2_23','wildlife','/ˈwaɪldlaɪf/','noun','야생 동식물','Animals and plants living in their natural environment.','National parks help preserve {wildlife}.','국립공원은 야생 동식물을 보존하는 데 도움을 줘요.','wildlife','A2','environment',1,'wildlife national park safari animals'),
('w_environment_A2_24','flood','/flʌd/','noun','홍수','A large amount of water covering land that is usually dry.','Heavy rain caused a {flood} in the low-lying area.','폭우로 저지대에 홍수가 발생했어요.','flood','A2','environment',1,'flood water street submerged disaster'),
('w_environment_A2_25','drought','/draʊt/','noun','가뭄','A long period of very dry weather with little or no rain.','The {drought} destroyed crops across the region.','가뭄이 지역 전체의 농작물을 망쳤어요.','drought','A2','environment',1,'drought cracked earth dry farmland'),
('w_environment_A2_26','bottle','/ˈbɒtəl/','noun','병','A glass or plastic container used for liquids.','Bring a reusable {bottle} instead of buying plastic ones.','플라스틱 병을 사는 대신 다회용 병을 가져오세요.','bottle','A2','environment',1,'reusable water bottle eco friendly'),
('w_environment_A2_27','bag','/bæɡ/','noun','가방, 봉투','A container made of paper, plastic, or cloth.','Bring a cloth {bag} when you go shopping.','장을 볼 때 천 가방을 가져오세요.','bag','A2','environment',1,'cloth bag reusable shopping eco'),
('w_environment_A2_28','compost','/ˈkɒmpɒst/','noun','퇴비','A mixture of decayed plant material used to improve soil.','We turn kitchen scraps into {compost}.','우리는 음식 찌꺼기를 퇴비로 만들어요.','compost','A2','environment',1,'compost bin kitchen scraps organic'),
('w_environment_A2_29','litter','/ˈlɪtər/','verb','쓰레기를 버리다','To drop rubbish carelessly in a public place.','It is illegal to {litter} in many countries.','많은 나라에서 쓰레기를 버리는 것은 불법이에요.','litter','A2','environment',1,'littering fine sign public space'),
('w_environment_A2_30','endangered','/ɪnˈdeɪndʒərd/','adjective','멸종 위기의','At risk of no longer existing because of very small numbers.','The {endangered} species needs urgent protection.','멸종 위기 종은 긴급한 보호가 필요해요.','endangered','A2','environment',1,'endangered species tiger wildlife sanctuary'),
('w_environment_A2_31','atmosphere','/ˈætməsfɪr/','noun','대기','The layer of gases surrounding the Earth.','Pollution is damaging our {atmosphere}.','오염이 우리의 대기를 손상시키고 있어요.','atmosphere','A2','environment',1,'atmosphere earth layer ozone space'),
('w_environment_A2_32','global','/ˈɡləʊbəl/','adjective','전 세계적인','Relating to the whole world.','{Global} temperatures have risen by one degree in a century.','전 세계 기온이 100년 동안 1도 상승했어요.','Global','A2','environment',1,'global world map temperature rising'),
('w_environment_A2_33','warming','/ˈwɔːrmɪŋ/','noun','온난화','The process of becoming warmer.','Global {warming} is causing sea levels to rise.','지구 온난화로 해수면이 상승하고 있어요.','warming','A2','environment',1,'global warming thermometer heat earth'),
('w_environment_A2_34','recycle bin','/riːˈsaɪkəl bɪn/','noun','재활용 통','A container used to collect materials for recycling.','Put your empty cans in the {recycle bin}.','빈 캔은 재활용 통에 넣어 주세요.','recycle bin','A2','environment',1,'recycle bin colorful sorting waste'),
('w_environment_A2_35','organic','/ɔːrˈɡænɪk/','adjective','유기농의, 유기적인','Produced without artificial chemicals; relating to living matter.','Buying {organic} food supports sustainable farming.','유기농 식품을 구매하면 지속 가능한 농업을 지원해요.','organic','A2','environment',1,'organic food market farm fresh');

-- ══════════════════════════════════════
-- WORDS — B1 (기후 변화 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_environment_B1_01','climate change','/ˈklaɪmɪt tʃeɪndʒ/','noun','기후 변화','Long-term shifts in global temperatures and weather patterns.','Scientists say {climate change} is accelerating.','과학자들은 기후 변화가 가속화되고 있다고 말해요.','climate change','B1','environment',1,'climate change data graph temperature rising'),
('w_environment_B1_02','carbon','/ˈkɑːrbən/','noun','탄소','A chemical element found in all living things and fossil fuels.','Reducing {carbon} emissions is a global priority.','탄소 배출을 줄이는 것이 전 세계적인 우선 과제예요.','carbon','B1','environment',1,'carbon molecule chemistry emissions'),
('w_environment_B1_03','emission','/ɪˈmɪʃən/','noun','배출, 배기가스','Gas or other substances released into the environment.','Cars are responsible for a large share of CO₂ {emission}s.','자동차는 이산화탄소 배출의 큰 부분을 차지해요.','emissions','B1','environment',1,'car exhaust emissions CO2 pollution'),
('w_environment_B1_04','sustainable','/səˈsteɪnəbəl/','adjective','지속 가능한','Able to be maintained without harming the environment.','We need to shift to {sustainable} energy sources.','지속 가능한 에너지원으로 전환해야 해요.','sustainable','B1','environment',1,'sustainable energy solar wind green'),
('w_environment_B1_05','renewable','/rɪˈnjuːəbəl/','adjective','재생 가능한','Able to be replaced naturally and not used up permanently.','Wind and solar are examples of {renewable} energy.','풍력과 태양광은 재생 가능한 에너지의 예예요.','renewable','B1','environment',1,'renewable energy wind turbine solar farm'),
('w_environment_B1_06','ecosystem','/ˈiːkəʊˌsɪstəm/','noun','생태계','A community of organisms and their physical environment.','Plastic waste is destroying marine {ecosystem}s.','플라스틱 쓰레기가 해양 생태계를 파괴하고 있어요.','ecosystems','B1','environment',1,'ecosystem coral reef marine life ocean'),
('w_environment_B1_07','biodiversity','/ˌbaɪəʊdaɪˈvɜːrsɪti/','noun','생물 다양성','The variety of plant and animal life in a particular habitat.','Protecting forests preserves {biodiversity}.','숲을 보호하는 것이 생물 다양성을 보전해요.','biodiversity','B1','environment',1,'biodiversity rainforest plants animals variety'),
('w_environment_B1_08','habitat','/ˈhæbɪtæt/','noun','서식지','The natural environment in which a species lives.','Urban sprawl destroys natural {habitat}s.','도시 확장은 자연 서식지를 파괴해요.','habitats','B1','environment',1,'habitat wildlife nature forest animals'),
('w_environment_B1_09','conservation','/ˌkɒnsəˈveɪʃən/','noun','자연 보전','The protection of plants, animals, and natural resources.','Wildlife {conservation} requires both funding and policy.','야생동물 보전에는 자금과 정책 모두 필요해요.','conservation','B1','environment',1,'conservation wildlife ranger national park'),
('w_environment_B1_10','greenhouse gas','/ˈɡriːnhaʊs ɡæs/','noun','온실 가스','A gas that traps heat in the atmosphere, such as CO₂.','Burning coal releases large amounts of {greenhouse gas}es.','석탄을 태우면 대량의 온실 가스가 방출돼요.','greenhouse gases','B1','environment',1,'greenhouse gas factory smoke emissions'),
('w_environment_B1_11','fossil fuel','/ˈfɒsəl fjuːəl/','noun','화석 연료','Coal, oil, or gas formed from ancient organisms.','We depend too heavily on {fossil fuel}s.','우리는 화석 연료에 너무 의존하고 있어요.','fossil fuels','B1','environment',1,'fossil fuel oil rig coal power plant'),
('w_environment_B1_12','sea level','/siː ˈlevəl/','noun','해수면','The average height of the sea''s surface.','Rising {sea level}s threaten coastal cities.','해수면 상승이 해안 도시를 위협해요.','sea levels','B1','environment',1,'sea level rising flood coastal city'),
('w_environment_B1_13','extinction','/ɪkˈstɪŋkʃən/','noun','멸종','The state of no longer existing as a species.','Habitat loss is the main driver of species {extinction}.','서식지 손실이 종 멸종의 주요 원인이에요.','extinction','B1','environment',1,'extinction endangered species museum fossil'),
('w_environment_B1_14','deforestation','/dɪˌfɒrɪˈsteɪʃən/','noun','삼림 벌채','The cutting down of forests over a large area.','{Deforestation} in the Amazon has accelerated in recent years.','최근 몇 년 동안 아마존의 삼림 벌채가 가속화됐어요.','Deforestation','B1','environment',1,'deforestation amazon logging forest cleared'),
('w_environment_B1_15','carbon footprint','/ˈkɑːrbən ˈfʊtprɪnt/','noun','탄소 발자국','The total amount of greenhouse gases produced by a person or activity.','You can reduce your {carbon footprint} by using public transport.','대중교통을 이용하면 탄소 발자국을 줄일 수 있어요.','carbon footprint','B1','environment',1,'carbon footprint calculator transport lifestyle'),
('w_environment_B1_16','recycle','/riːˈsaɪkəl/','verb','재활용하다','To convert waste into reusable material.','Our city {recycle}s over sixty percent of its waste.','우리 도시는 폐기물의 60% 이상을 재활용해요.','recycles','B1','environment',1,'recycling plant sorting conveyor belt'),
('w_environment_B1_17','pollution','/pəˈluːʃən/','noun','오염','Harmful substances introduced into the environment.','Noise and light {pollution} affect urban wildlife.','소음과 빛 공해는 도시 야생 동물에게 영향을 미쳐요.','pollution','B1','environment',1,'light pollution city night sky'),
('w_environment_B1_18','landfill','/ˈlændfɪl/','noun','매립지','A site where waste is buried in the ground.','Much of our plastic ends up in a {landfill}.','우리 플라스틱의 상당 부분이 매립지에 버려져요.','landfill','B1','environment',1,'landfill waste dump garbage pollution'),
('w_environment_B1_19','activist','/ˈæktɪvɪst/','noun','활동가','A person who campaigns for social or environmental change.','Environmental {activist}s marched through the city.','환경 활동가들이 도시를 행진했어요.','activists','B1','environment',1,'environmental activist march protest sign'),
('w_environment_B1_20','species','/ˈspiːʃiːz/','noun','종 (생물학)','A group of living organisms that can interbreed.','About one million {species} are at risk of extinction.','약 100만 종이 멸종 위기에 처해 있어요.','species','B1','environment',1,'species variety animals insects birds'),
('w_environment_B1_21','temperature','/ˈtemprɪtʃər/','noun','온도, 기온','The degree of heat in the atmosphere or a body.','Average global {temperature}s have risen by over 1°C.','전 세계 평균 기온이 1°C 이상 상승했어요.','temperatures','B1','environment',1,'temperature thermometer heat rising climate'),
('w_environment_B1_22','solar energy','/ˈsəʊlər ˈenədʒi/','noun','태양 에너지','Energy produced by converting sunlight into electricity.','{Solar energy} is now cheaper than coal power.','태양 에너지는 이제 석탄 발전보다 저렴해요.','Solar energy','B1','environment',1,'solar energy panels farm sunlight power'),
('w_environment_B1_23','wind power','/wɪnd ˈpaʊər/','noun','풍력','Electricity generated from the force of the wind.','The country gets twenty percent of its power from {wind power}.','그 나라는 전력의 20%를 풍력으로 얻어요.','wind power','B1','environment',1,'wind power turbine offshore farm'),
('w_environment_B1_24','water cycle','/ˈwɔːtər ˈsaɪkəl/','noun','물의 순환','The continuous movement of water through evaporation, clouds, and rain.','Climate change is disrupting the natural {water cycle}.','기후 변화가 자연적인 물의 순환을 방해하고 있어요.','water cycle','B1','environment',1,'water cycle diagram evaporation rain'),
('w_environment_B1_25','reforestation','/ˌriːˌfɒrɪˈsteɪʃən/','noun','재조림','The process of replanting trees in a deforested area.','{Reforestation} projects help restore damaged ecosystems.','재조림 프로젝트는 훼손된 생태계 복원에 도움이 돼요.','Reforestation','B1','environment',2,'reforestation planting trees saplings volunteers'),
('w_environment_B1_26','impact','/ˈɪmpækt/','noun','영향','A strong effect or influence on something.','The {impact} of plastic on oceans is severe.','플라스틱이 해양에 미치는 영향은 심각해요.','impact','B1','environment',2,'environmental impact ocean plastic wildlife'),
('w_environment_B1_27','carbon dioxide','/ˌkɑːrbən daɪˈɒksaɪd/','noun','이산화탄소','A gas produced by burning carbon fuels and by breathing.','Plants absorb {carbon dioxide} to produce oxygen.','식물은 이산화탄소를 흡수하여 산소를 생산해요.','carbon dioxide','B1','environment',1,'carbon dioxide molecule plant photosynthesis'),
('w_environment_B1_28','organic farming','/ɔːrˈɡænɪk ˈfɑːrmɪŋ/','noun','유기농 농업','Farming without synthetic chemicals or genetically modified crops.','{Organic farming} improves both soil and human health.','유기농 농업은 토양과 인체 건강 모두를 개선해요.','Organic farming','B1','environment',2,'organic farm vegetables fresh field'),
('w_environment_B1_29','acid rain','/ˈæsɪd reɪn/','noun','산성비','Rain made acidic by pollutants, harmful to plants and buildings.','{Acid rain} damaged the forests in northern Europe.','산성비가 북유럽의 숲을 손상시켰어요.','Acid rain','B1','environment',2,'acid rain damaged trees forest pollution'),
('w_environment_B1_30','ozone layer','/ˈəʊzəʊn ˈleɪər/','noun','오존층','A region of the upper atmosphere that absorbs UV radiation.','{Ozone layer} depletion increases skin cancer risk.','오존층 감소는 피부암 위험을 높여요.','Ozone layer','B1','environment',1,'ozone layer earth atmosphere UV radiation'),
('w_environment_B1_31','natural disaster','/ˈnætʃərəl dɪˈzɑːstər/','noun','자연재해','A severe event caused by natural processes such as floods or earthquakes.','{Natural disaster}s are becoming more frequent due to climate change.','기후 변화로 인해 자연재해가 더 자주 발생하고 있어요.','Natural disasters','B1','environment',1,'natural disaster flood hurricane drought'),
('w_environment_B1_32','policy','/ˈpɒlɪsi/','noun','정책','A set of rules or plans adopted by a government or organisation.','{Policy} changes are needed to reduce carbon emissions.','탄소 배출을 줄이기 위한 정책 변화가 필요해요.','Policy','B1','environment',2,'environmental policy government sign law'),
('w_environment_B1_33','awareness','/əˈweənəs/','noun','인식, 의식','Knowledge and understanding of a situation or subject.','{Awareness} of environmental issues is growing globally.','환경 문제에 대한 인식이 전 세계적으로 높아지고 있어요.','Awareness','B1','environment',2,'awareness campaign environment banner people'),
('w_environment_B1_34','resource','/ˈrɪzɔːrs/','noun','자원','A stock or supply of materials, money, staff, or other assets.','We must manage natural {resource}s wisely.','천연자원을 현명하게 관리해야 해요.','resources','B1','environment',1,'natural resources water forest minerals earth'),
('w_environment_B1_35','heat wave','/hiːt weɪv/','noun','폭염','A prolonged period of abnormally hot weather.','The summer {heat wave} broke temperature records.','여름 폭염이 기온 기록을 경신했어요.','heat wave','B1','environment',1,'heat wave summer sun hot temperature');

-- ══════════════════════════════════════
-- WORDS — B2 (환경 정책 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_environment_B2_01','greenhouse effect','/ˈɡriːnhaʊs ɪˈfekt/','noun','온실 효과','The warming of the Earth caused by gases trapping solar heat.','The {greenhouse effect} is intensifying due to human activity.','인간 활동으로 인해 온실 효과가 심화되고 있어요.','greenhouse effect','B2','environment',1,'greenhouse effect diagram earth atmosphere'),
('w_environment_B2_02','carbon sequestration','/ˈkɑːrbən ˌsiːkwɪˈstreɪʃən/','noun','탄소 격리','The process of capturing and storing CO₂ from the atmosphere.','Forests play a key role in {carbon sequestration}.','숲은 탄소 격리에 핵심적인 역할을 해요.','carbon sequestration','B2','environment',2,'carbon capture forest trees absorption'),
('w_environment_B2_03','mitigation','/ˌmɪtɪˈɡeɪʃən/','noun','완화, 경감','The reduction of the severity or impact of something.','Climate {mitigation} strategies include switching to renewables.','기후 완화 전략에는 재생 에너지로의 전환이 포함돼요.','mitigation','B2','environment',1,'climate mitigation solar wind renewable strategy'),
('w_environment_B2_04','adaptation','/ˌædæpˈteɪʃən/','noun','적응','The process of adjusting to new conditions, such as a changing climate.','Cities are investing in flood {adaptation} measures.','도시들이 홍수 적응 대책에 투자하고 있어요.','adaptation','B2','environment',1,'flood adaptation barrier city coastal'),
('w_environment_B2_05','desertification','/dɪˌzɜːrtɪfɪˈkeɪʃən/','noun','사막화','The process by which fertile land becomes desert.','{Desertification} threatens food security across sub-Saharan Africa.','사막화가 사하라 이남 아프리카 전역의 식량 안보를 위협하고 있어요.','Desertification','B2','environment',2,'desertification dry cracked earth Africa'),
('w_environment_B2_06','ozone depletion','/ˈəʊzəʊn dɪˈpliːʃən/','noun','오존층 파괴','The thinning of the ozone layer caused by chemical pollutants.','{Ozone depletion} was largely caused by CFC gases.','오존층 파괴는 주로 CFC 가스로 인해 발생했어요.','Ozone depletion','B2','environment',1,'ozone hole depletion CFC spray atmosphere'),
('w_environment_B2_07','toxin','/ˈtɒksɪn/','noun','독소','A poisonous substance produced by organisms or released by pollutants.','{Toxin}s in polluted water endanger both humans and animals.','오염된 물의 독소는 인간과 동물 모두를 위험에 빠뜨려요.','Toxins','B2','environment',2,'toxin polluted water contamination warning'),
('w_environment_B2_08','carbon tax','/ˈkɑːrbən tæks/','noun','탄소세','A tax levied on fossil fuels to reduce greenhouse gas emissions.','Several countries have introduced a {carbon tax}.','여러 나라가 탄소세를 도입했어요.','carbon tax','B2','environment',1,'carbon tax policy government environment'),
('w_environment_B2_09','net zero','/net ˈzɪərəʊ/','noun','탄소 중립','Balancing the amount of greenhouse gas emitted and removed.','The company pledged to reach {net zero} by 2040.','회사는 2040년까지 탄소 중립을 달성하겠다고 약속했어요.','net zero','B2','environment',1,'net zero target carbon neutral pledge'),
('w_environment_B2_10','renewable energy','/rɪˈnjuːəbəl ˈenədʒi/','noun','재생 가능 에너지','Energy from natural sources that are constantly replenished.','Investment in {renewable energy} has grown rapidly.','재생 가능 에너지에 대한 투자가 빠르게 성장했어요.','renewable energy','B2','environment',1,'renewable energy wind solar hydro farm'),
('w_environment_B2_11','emissions trading','/ɪˈmɪʃənz ˈtreɪdɪŋ/','noun','배출권 거래','A market-based approach to controlling greenhouse gas pollution.','The EU uses an {emissions trading} scheme.','EU는 배출권 거래 제도를 사용해요.','emissions trading','B2','environment',2,'emissions trading stock market environment EU'),
('w_environment_B2_12','water scarcity','/ˈwɔːtər ˈskeərsɪti/','noun','물 부족','The lack of sufficient available water resources.','{Water scarcity} affects over two billion people globally.','물 부족은 전 세계 20억 명 이상에게 영향을 미쳐요.','Water scarcity','B2','environment',1,'water scarcity dry tap Africa poverty'),
('w_environment_B2_13','geothermal','/ˌdʒiːəʊˈθɜːrməl/','adjective','지열의','Relating to heat generated within the Earth.','Iceland relies heavily on {geothermal} energy.','아이슬란드는 지열 에너지에 크게 의존해요.','geothermal','B2','environment',2,'geothermal energy Iceland steam power'),
('w_environment_B2_14','biodegradable','/ˌbaɪəʊdɪˈɡreɪdəbəl/','adjective','생분해성의','Able to be broken down naturally by bacteria or other organisms.','Replace plastic bags with {biodegradable} alternatives.','플라스틱 봉투를 생분해성 대안으로 교체하세요.','biodegradable','B2','environment',1,'biodegradable packaging leaf material'),
('w_environment_B2_15','microplastic','/ˈmaɪkrəʊˌplæstɪk/','noun','미세 플라스틱','Tiny pieces of plastic less than five millimetres in size.','Scientists found {microplastic}s in human blood.','과학자들이 인간의 혈액에서 미세 플라스틱을 발견했어요.','microplastics','B2','environment',1,'microplastics ocean water microscope plastic'),
('w_environment_B2_16','carbon offset','/ˈkɑːrbən ˈɒfset/','noun','탄소 상쇄','A reduction in CO₂ emissions to compensate for emissions elsewhere.','The airline offers passengers the option to buy a {carbon offset}.','항공사는 승객에게 탄소 상쇄권 구매 옵션을 제공해요.','carbon offset','B2','environment',2,'carbon offset tree planting reforestation'),
('w_environment_B2_17','circular economy','/ˈsɜːrkjʊlər ɪˈkɒnəmi/','noun','순환 경제','An economic system aimed at eliminating waste by reusing materials.','The {circular economy} model keeps products in use longer.','순환 경제 모델은 제품을 더 오래 사용하도록 유지해요.','circular economy','B2','environment',2,'circular economy recycling reuse cycle diagram'),
('w_environment_B2_18','deforestation rate','/dɪˌfɒrɪˈsteɪʃən reɪt/','noun','삼림 벌채율','The speed at which forests are being destroyed.','The {deforestation rate} in the tropics remains alarmingly high.','열대 지방의 삼림 벌채율은 여전히 우려스러울 정도로 높아요.','deforestation rate','B2','environment',2,'deforestation rate satellite image forest loss'),
('w_environment_B2_19','habitat loss','/ˈhæbɪtæt lɒs/','noun','서식지 손실','The destruction or degradation of natural habitats.','{Habitat loss} is the leading cause of species extinction.','서식지 손실은 종 멸종의 주요 원인이에요.','Habitat loss','B2','environment',1,'habitat loss deforestation bulldozer forest'),
('w_environment_B2_20','ecosystem services','/ˈiːkəʊˌsɪstəm ˈsɜːrvɪsɪz/','noun','생태계 서비스','The benefits that ecosystems provide to humans.','Wetlands provide vital {ecosystem services} including water filtration.','습지는 수질 정화를 포함한 중요한 생태계 서비스를 제공해요.','ecosystem services','B2','environment',2,'wetlands ecosystem water birds nature'),
('w_environment_B2_21','carbon neutral','/ˈkɑːrbən ˈnjuːtrəl/','adjective','탄소 중립적인','Achieving a balance between emitting and absorbing carbon.','The city aims to be {carbon neutral} by 2035.','그 도시는 2035년까지 탄소 중립을 달성하는 것을 목표로 해요.','carbon neutral','B2','environment',1,'carbon neutral city green buildings bikes'),
('w_environment_B2_22','sustainability','/səˌsteɪnəˈbɪlɪti/','noun','지속 가능성','The ability to maintain or preserve something over the long term.','{Sustainability} has become a core value for many businesses.','지속 가능성은 많은 기업의 핵심 가치가 됐어요.','Sustainability','B2','environment',1,'sustainability business green office eco'),
('w_environment_B2_23','Paris Agreement','/ˈpærɪs əˈɡriːmənt/','noun','파리 협정','A 2015 international treaty on climate change mitigation.','The {Paris Agreement} aims to limit warming to 1.5°C.','파리 협정은 온난화를 1.5°C로 제한하는 것을 목표로 해요.','Paris Agreement','B2','environment',1,'Paris Agreement COP climate treaty signing'),
('w_environment_B2_24','COP (Conference of Parties)','/kɒp/','noun','당사국 총회','The annual UN climate conference where governments negotiate.','World leaders gathered for {COP} to set new climate targets.','세계 지도자들이 새로운 기후 목표 설정을 위해 당사국 총회에 모였어요.','COP','B2','environment',1,'COP climate conference UN diplomacy leaders'),
('w_environment_B2_25','tipping point','/ˈtɪpɪŋ pɔɪnt/','noun','임계점','A threshold beyond which a system undergoes an irreversible change.','Scientists warn we may be approaching a climate {tipping point}.','과학자들은 기후 임계점에 다가가고 있을 수 있다고 경고해요.','tipping point','B2','environment',1,'tipping point climate balance edge threshold'),
('w_environment_B2_26','greenwashing','/ˈɡriːnwɒʃɪŋ/','noun','그린워싱','False or exaggerated environmental claims made by companies.','Consumers are increasingly able to identify {greenwashing}.','소비자들이 그린워싱을 점점 더 잘 식별하게 됐어요.','greenwashing','B2','environment',1,'greenwashing fake eco label packaging'),
('w_environment_B2_27','biodiversity hotspot','/ˌbaɪəʊdaɪˈvɜːrsɪti ˈhɒtspɒt/','noun','생물 다양성 핫스팟','A region with exceptionally high biodiversity that is threatened.','The Amazon is the world''s most important {biodiversity hotspot}.','아마존은 세계에서 가장 중요한 생물 다양성 핫스팟이에요.','biodiversity hotspot','B2','environment',2,'biodiversity hotspot amazon rainforest species'),
('w_environment_B2_28','invasive species','/ɪnˈveɪsɪv ˈspiːʃiːz/','noun','침입 종','Non-native organisms that harm local ecosystems.','{Invasive species} can outcompete native plants and animals.','침입 종은 토착 식물과 동물을 경쟁에서 앞설 수 있어요.','Invasive species','B2','environment',2,'invasive species plant kudzu spreading'),
('w_environment_B2_29','permafrost','/ˈpɜːrməfrɒst/','noun','영구 동토층','Soil that remains frozen for more than two years.','Thawing {permafrost} releases large amounts of methane.','영구 동토층이 녹으면 대량의 메탄이 방출돼요.','permafrost','B2','environment',2,'permafrost thawing arctic ground ice'),
('w_environment_B2_30','methane','/ˈmiːθeɪn/','noun','메탄','A greenhouse gas produced by livestock, wetlands, and landfills.','Cattle farming is a significant source of {methane}.','소 사육은 메탄의 중요한 공급원이에요.','methane','B2','environment',1,'methane cow livestock farm emissions'),
('w_environment_B2_31','coral reef','/ˈkɒrəl riːf/','noun','산호초','An underwater ecosystem built by colonies of tiny marine organisms.','Warming seas are causing {coral reef} bleaching.','따뜻해지는 바다로 인해 산호초 백화 현상이 일어나고 있어요.','coral reef','B2','environment',1,'coral reef bleaching ocean underwater'),
('w_environment_B2_32','erosion','/ɪˈrəʊʒən/','noun','침식','The gradual wearing away of land by water, wind, or ice.','Deforestation speeds up soil {erosion}.','삼림 벌채는 토양 침식을 가속화해요.','erosion','B2','environment',2,'soil erosion hillside rain water damage'),
('w_environment_B2_33','hydropower','/ˈhaɪdrəʊˌpaʊər/','noun','수력 발전','Electricity generated from the movement of water.','{Hydropower} provides a reliable source of renewable energy.','수력 발전은 신뢰할 수 있는 재생 에너지를 제공해요.','Hydropower','B2','environment',2,'hydropower dam river electricity renewable'),
('w_environment_B2_34','smog','/smɒɡ/','noun','스모그','A thick haze of pollution, especially in cities.','Beijing has taken steps to reduce {smog} levels.','베이징은 스모그 수준을 줄이기 위한 조치를 취했어요.','smog','B2','environment',1,'smog city skyline haze pollution Beijing'),
('w_environment_B2_35','pollutant','/pəˈluːtənt/','noun','오염 물질','A substance that contaminates the environment.','Car exhausts release several harmful {pollutant}s.','자동차 배기가스는 여러 유해한 오염 물질을 방출해요.','pollutants','B2','environment',1,'pollutants car exhaust smoke air dirty');

-- ══════════════════════════════════════
-- WORDS — C1 (기후 과학 심화 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_environment_C1_01','anthropogenic','/ˌænθrəpəˈdʒenɪk/','adjective','인위적인, 인간이 야기한','Caused or produced by human activities.','Most climate scientists agree that warming is {anthropogenic}.','대부분의 기후 과학자들은 온난화가 인위적이라는 데 동의해요.','anthropogenic','C1','environment',2,'anthropogenic human activity pollution factory'),
('w_environment_C1_02','biogeochemical cycle','/ˌbaɪəʊˌdʒiːəʊˈkemɪkəl ˈsaɪkəl/','noun','생지화학적 순환','The pathways by which elements cycle through living and non-living systems.','The carbon {biogeochemical cycle} regulates atmospheric CO₂.','탄소 생지화학적 순환은 대기 중 이산화탄소를 조절해요.','biogeochemical cycle','C1','environment',3,'carbon nitrogen cycle diagram ecosystem'),
('w_environment_C1_03','ecological footprint','/ˌiːkəˈlɒdʒɪkəl ˈfʊtprɪnt/','noun','생태 발자국','The area of land needed to sustain a person''s or group''s lifestyle.','Our {ecological footprint} exceeds the Earth''s regenerative capacity.','우리의 생태 발자국은 지구의 재생 능력을 초과하고 있어요.','ecological footprint','C1','environment',2,'ecological footprint earth overshoot calculation'),
('w_environment_C1_04','paleoclimatology','/ˌpeɪliəʊˌklaɪməˈtɒlədʒi/','noun','고기후학','The study of past climates using geological and biological records.','{Paleoclimatology} uses ice cores to reconstruct ancient temperatures.','고기후학은 빙하 코어를 사용하여 고대 기온을 재구성해요.','Paleoclimatology','C1','environment',3,'ice core drilling paleoclimatology arctic research'),
('w_environment_C1_05','decarbonization','/diːˌkɑːrbənaɪˈzeɪʃən/','noun','탈탄소화','The process of reducing or eliminating carbon dioxide from energy systems.','{Decarbonization} of the energy sector is essential for net zero.','에너지 부문의 탈탄소화는 탄소 중립을 위해 필수적이에요.','Decarbonization','C1','environment',1,'decarbonization energy transition clean power'),
('w_environment_C1_06','sequester','/sɪˈkwestər/','verb','격리하다, 포집하다','To isolate and store a substance, especially CO₂.','Trees {sequester} carbon for decades.','나무는 수십 년 동안 탄소를 격리해요.','sequester','C1','environment',2,'sequester carbon tree forest absorption'),
('w_environment_C1_07','geoengineering','/ˌdʒiːəʊˌendʒɪˈnɪərɪŋ/','noun','지구공학','Large-scale technological interventions to counteract climate change.','Some scientists propose {geoengineering} to cool the planet.','일부 과학자들은 지구를 냉각시키기 위해 지구공학을 제안해요.','geoengineering','C1','environment',2,'geoengineering solar radiation management atmosphere'),
('w_environment_C1_08','biome','/ˈbaɪəʊm/','noun','생물군계','A large community of plants and animals occupying a major habitat.','The boreal forest is the largest terrestrial {biome}.','한대 수림은 지구에서 가장 큰 육상 생물군계예요.','biome','C1','environment',2,'biome map world forest tundra desert'),
('w_environment_C1_09','carbon sink','/ˈkɑːrbən sɪŋk/','noun','탄소 흡수원','A natural system that absorbs more CO₂ than it releases.','Oceans act as a major {carbon sink}, absorbing human emissions.','바다는 인간이 배출하는 탄소를 흡수하는 주요 탄소 흡수원 역할을 해요.','carbon sink','C1','environment',1,'carbon sink ocean forest absorption diagram'),
('w_environment_C1_10','stratospheric aerosol','/ˌstrætəˈsferɪk ˈeərəsɒl/','noun','성층권 에어로졸','Fine particles injected into the stratosphere that reflect sunlight.','Volcanic eruptions release {stratospheric aerosol}s that cool the Earth.','화산 폭발은 지구를 냉각시키는 성층권 에어로졸을 방출해요.','stratospheric aerosols','C1','environment',3,'stratosphere aerosol volcano cooling earth'),
('w_environment_C1_11','resilience','/rɪˈzɪliəns/','noun','회복 탄력성','The capacity to recover quickly from difficulties or disturbances.','Ecosystem {resilience} determines how quickly nature bounces back.','생태계 회복 탄력성은 자연이 얼마나 빨리 회복되는지를 결정해요.','resilience','C1','environment',2,'resilience ecosystem recovery forest regrowth'),
('w_environment_C1_12','threshold effect','/ˈθreʃhəʊld ɪˈfekt/','noun','임계값 효과','A sudden change in a system that occurs when a critical limit is crossed.','Beyond a certain temperature, a {threshold effect} can trigger abrupt change.','특정 온도를 넘으면 임계값 효과가 급격한 변화를 촉발할 수 있어요.','threshold effect','C1','environment',3,'tipping point threshold diagram climate system'),
('w_environment_C1_13','albedo','/ælˈbiːdəʊ/','noun','반사율 (알베도)','The proportion of sunlight reflected by a surface.','Snow has a high {albedo}, reflecting most incoming solar radiation.','눈은 반사율이 높아 태양 복사의 대부분을 반사해요.','albedo','C1','environment',2,'albedo ice snow reflection sunlight'),
('w_environment_C1_14','blue carbon','/bluː ˈkɑːrbən/','noun','블루 카본','Carbon stored in coastal and marine ecosystems such as mangroves.','Mangroves store five times more {blue carbon} per hectare than forests.','맹그로브는 숲보다 헥타르당 5배 더 많은 블루 카본을 저장해요.','blue carbon','C1','environment',2,'mangrove coastal blue carbon wetland'),
('w_environment_C1_15','phytoplankton','/ˌfaɪtəʊˈplæŋktən/','noun','식물성 플랑크톤','Microscopic plants in the ocean that produce oxygen through photosynthesis.','Ocean {phytoplankton} generate about half of Earth''s oxygen.','해양 식물성 플랑크톤은 지구 산소의 약 절반을 생산해요.','phytoplankton','C1','environment',3,'phytoplankton ocean microscope bloom green'),
('w_environment_C1_16','feedback loop','/ˈfiːdbæk luːp/','noun','피드백 루프','A process where a change amplifies or dampens itself over time.','Melting ice creates a warming {feedback loop}.','얼음이 녹으면 온난화 피드백 루프가 생성돼요.','feedback loop','C1','environment',1,'feedback loop climate diagram amplify cycle'),
('w_environment_C1_17','land use change','/lænd juːs tʃeɪndʒ/','noun','토지 이용 변화','The conversion of land from one use to another, such as forest to farmland.','{Land use change} accounts for about ten percent of CO₂ emissions.','토지 이용 변화는 이산화탄소 배출의 약 10%를 차지해요.','land use change','C1','environment',2,'land use deforestation farmland satellite'),
('w_environment_C1_18','ocean acidification','/ˈəʊʃən ˌæsɪdɪfɪˈkeɪʃən/','noun','해양 산성화','The decrease in ocean pH caused by absorption of atmospheric CO₂.','{Ocean acidification} dissolves shells and harms marine life.','해양 산성화는 껍질을 녹이고 해양 생물에게 해를 끼쳐요.','Ocean acidification','C1','environment',1,'ocean acidification coral shell dissolving pH'),
('w_environment_C1_19','climate sensitivity','/ˈklaɪmɪt senˈsɪtɪvɪti/','noun','기후 민감도','The temperature increase expected from a doubling of atmospheric CO₂.','{Climate sensitivity} estimates range from 2.5 to 4°C.','기후 민감도 추정치는 2.5°C에서 4°C 범위예요.','Climate sensitivity','C1','environment',3,'climate sensitivity graph model projection'),
('w_environment_C1_20','sustainable development goals','/səˈsteɪnəbəl dɪˈveləpmənt ɡəʊlz/','noun','지속 가능한 개발 목표 (SDGs)','The UN''s 17 goals for a better and more sustainable future.','Many nations are failing to meet the {sustainable development goals}.','많은 나라들이 지속 가능한 개발 목표를 달성하지 못하고 있어요.','sustainable development goals','C1','environment',1,'SDGs sustainable development goals UN icons'),
('w_environment_C1_21','rewilding','/riːˈwaɪldɪŋ/','noun','자연 재야생화','Restoring land to its natural state by reintroducing native species.','{Rewilding} projects are reviving depleted ecosystems across Europe.','재야생화 프로젝트가 유럽 전역의 고갈된 생태계를 부활시키고 있어요.','Rewilding','C1','environment',2,'rewilding wolf reintroduction nature Europe'),
('w_environment_C1_22','peatland','/ˈpiːtlænd/','noun','이탄 지대','Wetlands where partially decomposed plant matter accumulates as peat.','Draining {peatland}s releases huge amounts of stored carbon.','이탄 지대를 배수하면 저장된 탄소가 대량으로 방출돼요.','peatlands','C1','environment',2,'peatland bog wetland carbon storage'),
('w_environment_C1_23','atmospheric CO₂','/ˌætməˈsferɪk siːˈəʊˈtuː/','noun','대기 중 이산화탄소','The concentration of carbon dioxide in the Earth''s atmosphere.','{Atmospheric CO₂} has exceeded 420 parts per million.','대기 중 이산화탄소 농도가 420ppm을 초과했어요.','atmospheric CO₂','C1','environment',1,'atmospheric CO2 Mauna Loa graph ppm'),
('w_environment_C1_24','stranded assets','/ˈstrændɪd ˈæsets/','noun','좌초 자산','Assets that lose value due to changes in policy or technology.','Fossil fuel companies face the risk of {stranded assets}.','화석 연료 기업들은 좌초 자산의 위험에 직면해 있어요.','stranded assets','C1','environment',2,'stranded assets oil field abandoned energy'),
('w_environment_C1_25','planetary health','/ˈplænɪtri helθ/','noun','지구 건강','The interconnected health of human societies and the natural systems they depend on.','{Planetary health} links ecosystems, climate, and human well-being.','지구 건강은 생태계, 기후, 인간의 웰빙을 연결해요.','Planetary health','C1','environment',2,'planetary health one health ecosystem human'),
('w_environment_C1_26','photovoltaic','/ˌfəʊtəʊvɒlˈteɪɪk/','adjective','광전지의','Converting light directly into electricity using semiconductors.','{Photovoltaic} cells are becoming cheaper each year.','광전지 셀은 매년 점점 더 저렴해지고 있어요.','Photovoltaic','C1','environment',2,'photovoltaic solar cell panel close up'),
('w_environment_C1_27','bioenergy','/ˌbaɪəʊˈenədʒi/','noun','바이오 에너지','Energy derived from biological materials such as wood or crops.','Burning waste wood for {bioenergy} can be carbon-neutral.','폐목재를 바이오 에너지로 태우면 탄소 중립적일 수 있어요.','bioenergy','C1','environment',2,'bioenergy biomass wood chips burning'),
('w_environment_C1_28','carbon budget','/ˈkɑːrbən ˈbʌdʒɪt/','noun','탄소 예산','The total amount of CO₂ that can be emitted to stay within a temperature limit.','The world is rapidly exhausting its remaining {carbon budget}.','세계는 남은 탄소 예산을 빠르게 소진하고 있어요.','carbon budget','C1','environment',1,'carbon budget clock countdown global'),
('w_environment_C1_29','atmospheric river','/ˌætməˈsferɪk ˈrɪvər/','noun','대기 강','A narrow band of water vapour in the atmosphere that carries huge amounts of moisture.','The {atmospheric river} dumped record rainfall on the coast.','대기 강이 해안에 기록적인 강우량을 쏟아 냈어요.','atmospheric river','C1','environment',3,'atmospheric river satellite image rain storm'),
('w_environment_C1_30','ecological collapse','/ˌiːkəˈlɒdʒɪkəl kəˈlæps/','noun','생태계 붕괴','The deterioration of an ecosystem to a point where it can no longer function.','{Ecological collapse} can render regions uninhabitable.','생태계 붕괴는 지역을 거주 불가능하게 만들 수 있어요.','Ecological collapse','C1','environment',2,'ecological collapse barren land wildlife loss'),
('w_environment_C1_31','methane hydrate','/ˈmiːθeɪn ˈhaɪdreɪt/','noun','메탄 하이드레이트','Frozen water containing methane gas, found in deep seabed sediments.','{Methane hydrate}s could release massive amounts of gas as oceans warm.','바다가 따뜻해지면 메탄 하이드레이트에서 엄청난 양의 가스가 방출될 수 있어요.','Methane hydrates','C1','environment',3,'methane hydrate seabed ice crystal'),
('w_environment_C1_32','green hydrogen','/ɡriːn ˈhaɪdrədʒən/','noun','그린 수소','Hydrogen produced by electrolysis using renewable energy.','Airlines are exploring {green hydrogen} as a sustainable aviation fuel.','항공사들은 지속 가능한 항공 연료로 그린 수소를 탐색하고 있어요.','green hydrogen','C1','environment',1,'green hydrogen electrolysis plant fuel cell'),
('w_environment_C1_33','carbon leakage','/ˈkɑːrbən ˈliːkɪdʒ/','noun','탄소 누출','The shift of emissions to countries with less strict climate policies.','{Carbon leakage} undermines ambitious domestic climate policies.','탄소 누출은 야심찬 국내 기후 정책을 약화시켜요.','Carbon leakage','C1','environment',3,'carbon leakage industry relocation map'),
('w_environment_C1_34','thermal expansion','/ˈθɜːrməl ɪkˈspænʃən/','noun','열팽창','The increase in volume of ocean water as its temperature rises.','{Thermal expansion} of seawater contributes to rising sea levels.','해수의 열팽창은 해수면 상승에 기여해요.','Thermal expansion','C1','environment',2,'thermal expansion sea level ocean temperature'),
('w_environment_C1_35','urban heat island','/ˈɜːrbən hiːt ˈaɪlənd/','noun','도시 열섬','The phenomenon where cities are significantly warmer than surrounding areas.','Green roofs can reduce the {urban heat island} effect.','녹색 지붕은 도시 열섬 효과를 줄일 수 있어요.','urban heat island','C1','environment',1,'urban heat island city rooftop green buildings');

-- ══════════════════════════════════════
-- WORDS — C2 (기후 과학 최고급 어휘)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_environment_C2_01','radiative forcing','/ˈreɪdiətɪv ˈfɔːrsɪŋ/','noun','복사 강제력','The change in energy flux in the atmosphere caused by a climate driver.','{Radiative forcing} from CO₂ is the dominant cause of recent warming.','이산화탄소로 인한 복사 강제력이 최근 온난화의 주요 원인이에요.','Radiative forcing','C2','environment',2,'radiative forcing energy balance diagram earth'),
('w_environment_C2_02','thermohaline circulation','/ˌθɜːrməʊˈheɪlaɪn ˌsɜːrkjʊˈleɪʃən/','noun','열염 순환','The global ocean circulation driven by differences in water temperature and salinity.','{Thermohaline circulation} distributes heat around the planet.','열염 순환은 지구 전체에 열을 분배해요.','Thermohaline circulation','C2','environment',2,'thermohaline circulation ocean conveyor belt diagram'),
('w_environment_C2_03','albedo feedback','/ælˈbiːdəʊ ˈfiːdbæk/','noun','알베도 피드백','The climate feedback where reduced ice cover decreases reflectivity and accelerates warming.','{Albedo feedback} amplifies Arctic warming significantly.','알베도 피드백은 북극 온난화를 크게 증폭시켜요.','Albedo feedback','C2','environment',2,'albedo feedback arctic ice melting ocean dark'),
('w_environment_C2_04','cryosphere','/ˈkraɪəsfɪr/','noun','빙권','The part of the Earth''s surface that is permanently frozen, including glaciers and sea ice.','Rapid changes in the {cryosphere} are accelerating sea level rise.','빙권의 급격한 변화가 해수면 상승을 가속화하고 있어요.','cryosphere','C2','environment',2,'cryosphere glacier ice sheet arctic'),
('w_environment_C2_05','permafrost thaw','/ˈpɜːrməfrɒst θɔː/','noun','영구 동토층 해빙','The melting of permanently frozen ground, releasing stored carbon.','{Permafrost thaw} in Siberia is releasing ancient methane stores.','시베리아의 영구 동토층 해빙이 고대 메탄 저장량을 방출하고 있어요.','Permafrost thaw','C2','environment',2,'permafrost thaw siberia methane bubbles lake'),
('w_environment_C2_06','climate tipping point','/ˈklaɪmɪt ˈtɪpɪŋ pɔɪnt/','noun','기후 임계점','A threshold in the climate system beyond which change becomes self-perpetuating.','{Climate tipping point}s, once crossed, may be impossible to reverse.','기후 임계점은 한 번 넘으면 되돌리기 불가능할 수 있어요.','Climate tipping points','C2','environment',1,'climate tipping point domino effect cascade'),
('w_environment_C2_07','teleconnection','/ˌtelɪkəˈnekʃən/','noun','원거리 연결 (기상학)','The link between weather or climate patterns in distant parts of the world.','The El Niño {teleconnection} affects monsoon patterns in South Asia.','엘니뇨 원거리 연결이 남아시아 몬순 패턴에 영향을 미쳐요.','teleconnection','C2','environment',3,'teleconnection El Nino global weather map'),
('w_environment_C2_08','planetary boundary','/ˈplænɪtri ˈbaʊndri/','noun','지구 한계선','The safe operating boundaries for Earth''s systems within which humanity can thrive.','We have already crossed six of the nine {planetary boundaries}.','우리는 이미 아홉 개의 지구 한계선 중 여섯 개를 초과했어요.','planetary boundaries','C2','environment',1,'planetary boundaries diagram nine earth system'),
('w_environment_C2_09','Holocene','/ˈhɒləsiːn/','noun','홀로세','The current geological epoch, beginning about 11,700 years ago, noted for stable climate.','Human civilisation developed during the stable {Holocene} climate.','인류 문명은 안정적인 홀로세 기후 속에서 발전했어요.','Holocene','C2','environment',2,'Holocene epoch geological timeline climate'),
('w_environment_C2_10','technosphere','/ˈteknəsfɪr/','noun','기술권','The part of the environment consisting of human-made structures and systems.','The {technosphere} now weighs more than all living biomass on Earth.','기술권의 무게는 이제 지구상 모든 생물 바이오매스보다 무거워요.','technosphere','C2','environment',3,'technosphere cities infrastructure human made'),
('w_environment_C2_11','abrupt climate change','/əˈbrʌpt ˈklaɪmɪt tʃeɪndʒ/','noun','급격한 기후 변화','A rapid, large-scale shift in the climate system.','{Abrupt climate change} can happen within decades, not centuries.','급격한 기후 변화는 수세기가 아닌 수십 년 안에 일어날 수 있어요.','Abrupt climate change','C2','environment',2,'abrupt climate change rapid shift data graph'),
('w_environment_C2_12','nitrogen cycle','/ˈnaɪtrədʒən ˈsaɪkəl/','noun','질소 순환','The biogeochemical cycle by which nitrogen moves through ecosystems.','Excessive fertiliser use disrupts the {nitrogen cycle}.','과도한 비료 사용은 질소 순환을 방해해요.','nitrogen cycle','C2','environment',2,'nitrogen cycle fertilizer agriculture soil'),
('w_environment_C2_13','solar radiation management','/ˈsəʊlər reɪˈdieɪʃən ˈmænɪdʒmənt/','noun','태양 복사 관리','A form of geoengineering that reflects sunlight to reduce warming.','{Solar radiation management} could have unpredictable side effects.','태양 복사 관리는 예측 불가능한 부작용을 초래할 수 있어요.','Solar radiation management','C2','environment',3,'solar radiation management aerosol injection atmosphere'),
('w_environment_C2_14','integrated assessment model','/ˈɪntɪɡreɪtɪd əˈsesmənt ˈmɒdəl/','noun','통합 평가 모델','A computational tool combining climate, economic, and social data for projections.','{Integrated assessment models} inform the IPCC''s future scenarios.','통합 평가 모델은 IPCC의 미래 시나리오에 정보를 제공해요.','Integrated assessment models','C2','environment',3,'climate model computer simulation IPCC data'),
('w_environment_C2_15','biospheric integrity','/ˌbaɪəˈsferɪk ɪnˈteɡrɪti/','noun','생물권 무결성','The degree to which living systems maintain their natural diversity and function.','Loss of {biospheric integrity} is the most critical planetary boundary.','생물권 무결성의 손실은 가장 중요한 지구 한계선 위반이에요.','biospheric integrity','C2','environment',3,'biosphere biodiversity integrity nature intact'),
('w_environment_C2_16','deep adaptation','/diːp ˌædæpˈteɪʃən/','noun','심층 적응','A framework for preparing for potential societal collapse due to climate change.','{Deep adaptation} asks society to consider worst-case climate scenarios.','심층 적응은 사회가 최악의 기후 시나리오를 고려하도록 요청해요.','Deep adaptation','C2','environment',3,'deep adaptation resilience community prepare'),
('w_environment_C2_17','flux density','/flʌks ˈdensɪti/','noun','플럭스 밀도','The rate of flow of energy through a given surface per unit area.','{Flux density} measurements help scientists track ocean heat content.','플럭스 밀도 측정은 과학자들이 해양 열 함량을 추적하는 데 도움을 줘요.','Flux density','C2','environment',3,'flux density ocean heat measurement buoy'),
('w_environment_C2_18','carbon cycle feedback','/ˈkɑːrbən ˈsaɪkəl ˈfiːdbæk/','noun','탄소 순환 피드백','Processes in the carbon cycle that amplify or dampen climate change.','{Carbon cycle feedback}s are one of the biggest uncertainties in climate projections.','탄소 순환 피드백은 기후 예측에서 가장 큰 불확실성 중 하나예요.','Carbon cycle feedbacks','C2','environment',2,'carbon cycle feedback diagram climate'),
('w_environment_C2_19','Milankovitch cycles','/mɪˈlænkəvɪtʃ ˈsaɪkəlz/','noun','밀란코비치 주기','Variations in Earth''s orbit and axial tilt that affect long-term climate.','{Milankovitch cycles} explain the pattern of ice ages.','밀란코비치 주기는 빙하기 패턴을 설명해요.','Milankovitch cycles','C2','environment',3,'Milankovitch cycle orbital variation earth ice age'),
('w_environment_C2_20','loss and damage','/lɒs ænd ˈdæmɪdʒ/','noun','손실과 피해','The economic and non-economic impacts of climate change that cannot be adapted to.','{Loss and damage} funding is a key demand from vulnerable nations.','손실과 피해 기금은 취약 국가의 핵심 요구 사항이에요.','Loss and damage','C2','environment',1,'loss damage flood island climate vulnerable'),
('w_environment_C2_21','stoichiometry','/ˌstɔɪkiˈɒmɪtri/','noun','화학량론','The calculation of relative quantities of reactants and products in chemical reactions.','Marine {stoichiometry} helps predict how ocean chemistry responds to CO₂.','해양 화학량론은 이산화탄소에 대한 해양 화학의 반응을 예측하는 데 도움을 줘요.','stoichiometry','C2','environment',3,'stoichiometry chemistry equation ocean reaction'),
('w_environment_C2_22','zoonotic spillover','/ˌzuːəˈnɒtɪk ˈspɪləʊvər/','noun','인수 공통 감염 전파','The transmission of a disease from animals to humans, often triggered by habitat loss.','{Zoonotic spillover} risk increases as deforestation brings humans closer to wildlife.','삼림 벌채로 인간이 야생동물에 가까워지면서 인수 공통 감염 전파 위험이 높아지고 있어요.','Zoonotic spillover','C2','environment',2,'zoonotic disease bat wildlife deforestation jungle'),
('w_environment_C2_23','ocean stratification','/ˈəʊʃən ˌstrætɪfɪˈkeɪʃən/','noun','해양 성층화','The layering of the ocean by density, which affects mixing and nutrient circulation.','{Ocean stratification} is increasing, reducing oxygen in deep water.','해양 성층화가 심화되면서 심해의 산소가 줄어들고 있어요.','Ocean stratification','C2','environment',3,'ocean stratification layers temperature depth'),
('w_environment_C2_24','Anthropocene epoch','/ænˈθrɒpəsiːn ˈiːpɒk/','noun','인류세','The proposed geological epoch defined by significant human impact on Earth.','{Anthropocene epoch} is characterised by mass extinction and synthetic chemicals.','인류세는 대멸종과 합성 화학 물질로 특징지어져요.','Anthropocene epoch','C2','environment',2,'Anthropocene human impact earth geology'),
('w_environment_C2_25','negative emissions technology','/ˈneɡətɪv ɪˈmɪʃənz tekˈnɒlədʒi/','noun','음의 배출 기술','Technologies that remove CO₂ from the atmosphere.','Most net zero pathways require large-scale {negative emissions technology}.','대부분의 탄소 중립 경로에는 대규모 음의 배출 기술이 필요해요.','negative emissions technology','C2','environment',2,'negative emissions CCS BECCS carbon removal'),
('w_environment_C2_26','jet stream disruption','/dʒet striːm dɪsˈrʌpʃən/','noun','제트 기류 교란','The weakening or shifting of the jet stream due to Arctic warming.','{Jet stream disruption} is linked to more extreme weather events.','제트 기류 교란은 더 극단적인 기상 현상과 연관돼 있어요.','Jet stream disruption','C2','environment',2,'jet stream disruption weather map extreme'),
('w_environment_C2_27','biomagnification','/ˌbaɪəʊmæɡnɪfɪˈkeɪʃən/','noun','생물 농축','The increasing concentration of a toxin as it moves up the food chain.','{Biomagnification} of mercury poses serious risks to predators.','수은의 생물 농축은 포식자에게 심각한 위험을 초래해요.','Biomagnification','C2','environment',2,'biomagnification food chain toxin fish eagle'),
('w_environment_C2_28','epigenetic climate response','/ˌepɪdʒəˈnetɪk ˈklaɪmɪt rɪˈspɒns/','noun','후성유전학적 기후 반응','Heritable changes in gene expression triggered by climate stressors.','{Epigenetic climate response}s may help species adapt faster than evolution.','후성유전학적 기후 반응은 진화보다 더 빨리 종의 적응을 도울 수 있어요.','Epigenetic climate responses','C2','environment',3,'epigenetics genetics adaptation climate species'),
('w_environment_C2_29','solar geoengineering governance','/ˈsəʊlər ˌdʒiːəʊˌendʒɪˈnɪərɪŋ ˈɡʌvənəns/','noun','태양 지구공학 거버넌스','International rules and norms for controlling solar geoengineering experiments.','{Solar geoengineering governance} is a key challenge for the international community.','태양 지구공학 거버넌스는 국제 사회의 핵심 과제예요.','Solar geoengineering governance','C2','environment',3,'solar geoengineering governance UN diplomacy'),
('w_environment_C2_30','climate justice','/ˈklaɪmɪt ˈdʒʌstɪs/','noun','기후 정의','The equitable distribution of climate benefits and burdens across societies.','{Climate justice} demands that wealthier nations pay for damages they caused.','기후 정의는 부유한 나라들이 자신들이 초래한 피해를 보상하도록 요구해요.','Climate justice','C2','environment',1,'climate justice protest sign march equity'),
('w_environment_C2_31','irreversibility','/ɪˌrɪvɜːrsɪˈbɪlɪti/','noun','비가역성','The quality of a change that cannot be undone once it has occurred.','The {irreversibility} of species extinction makes prevention crucial.','종 멸종의 비가역성은 예방을 매우 중요하게 만들어요.','irreversibility','C2','environment',2,'irreversible change extinct species fossil'),
('w_environment_C2_32','downwelling','/ˈdaʊnwelɪŋ/','noun','침강','The sinking of surface ocean water, transporting heat and CO₂ to the deep ocean.','{Downwelling} in the North Atlantic is a critical component of ocean circulation.','북대서양의 침강은 해양 순환의 핵심 구성 요소예요.','Downwelling','C2','environment',3,'downwelling ocean circulation thermohaline North Atlantic'),
('w_environment_C2_33','endocrine disruptor','/ˈendəkrɪn dɪsˈrʌptər/','noun','내분비 교란 물질','A chemical that interferes with hormone systems in animals and humans.','{Endocrine disruptor}s found in pesticides are harming amphibians.','살충제에서 발견된 내분비 교란 물질이 양서류에게 해를 끼치고 있어요.','Endocrine disruptors','C2','environment',2,'endocrine disruptor pesticide frog amphibian'),
('w_environment_C2_34','synoptic weather pattern','/sɪˈnɒptɪk ˈweðər ˈpætərn/','noun','종관 기상 패턴','Large-scale weather patterns spanning hundreds to thousands of kilometres.','{Synoptic weather pattern}s are shifting poleward due to climate change.','기후 변화로 인해 종관 기상 패턴이 극지방 방향으로 이동하고 있어요.','Synoptic weather patterns','C2','environment',3,'synoptic weather map pressure front system'),
('w_environment_C2_35','socio-ecological resilience','/ˌsəʊsiəʊˌiːkəˈlɒdʒɪkəl rɪˈzɪliəns/','noun','사회-생태적 회복 탄력성','The capacity of linked human and natural systems to absorb and adapt to disturbances.','{Socio-ecological resilience} must be built at both community and ecosystem levels.','사회-생태적 회복 탄력성은 지역 사회와 생태계 수준 모두에서 구축되어야 해요.','Socio-ecological resilience','C2','environment',3,'socio ecological resilience community nature');

-- ══════════════════════════════════════
-- PATTERNS — A1 (환경 실천 패턴)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_environment_A1_01','Let''s recycle this.','이거 재활용해요.','Let''s recycle','Let''s...는 함께 무언가를 하자고 제안할 때 써요. 가장 쉬운 환경 실천 표현이에요.','환경 실천','A1','environment','pattern',NULL,1),
('s_environment_A1_02','Don''t throw trash here.','여기에 쓰레기 버리지 마세요.','Don''t throw trash','Don''t + 동사 패턴으로 간단하게 금지를 표현해요.','공공장소','A1','environment','pattern',NULL,2),
('s_environment_A1_03','Please save water.','물을 아껴 주세요.','save water','Please + 동사 패턴은 정중하게 부탁할 때 써요. save는 아끼다, 절약하다의 뜻이에요.','환경 실천','A1','environment','pattern',NULL,3),
('s_environment_A1_04','Turn off the light.','불 꺼 주세요.','Turn off the light','Turn off은 전원을 끈다는 뜻. 에너지 절약 표현에서 가장 많이 쓰는 동사예요.','에너지 절약','A1','environment','pattern',NULL,4),
('s_environment_A1_05','The air is fresh here.','여기 공기가 신선해요.','air is fresh','주어 + is + 형용사 패턴으로 현재 상태를 표현해요. 자연 환경을 묘사할 때 유용해요.','자연 묘사','A1','environment','pattern',NULL,5),
('s_environment_A1_06','I like green spaces.','저는 녹지 공간을 좋아해요.','I like green spaces','I like + 명사 패턴으로 취향을 간단하게 표현해요.','일상 대화','A1','environment','pattern',NULL,6),
('s_environment_A1_07','We need clean water.','깨끗한 물이 필요해요.','We need clean water','We need + 명사 패턴으로 필요를 표현해요. clean water는 환경 주제의 핵심 표현이에요.','환경 문제','A1','environment','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — A2 (재활용·절약 패턴)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_environment_A2_01','You should recycle your plastic bottles.','플라스틱 병은 재활용해야 해요.','You should recycle','You should + 동사 패턴은 권유나 조언을 줄 때 써요.','환경 조언','A2','environment','pattern',NULL,1),
('s_environment_A2_02','Try to use less plastic.','플라스틱을 덜 사용하려고 노력해 보세요.','Try to use less','Try to + 동사 패턴은 어떤 행동을 시도해 보라고 권유할 때 써요.','환경 실천','A2','environment','pattern',NULL,2),
('s_environment_A2_03','It''s important to save energy.','에너지를 절약하는 것이 중요해요.','It''s important to','It''s important to + 동사 패턴은 어떤 행동의 중요성을 강조할 때 써요.','환경 교육','A2','environment','pattern',NULL,3),
('s_environment_A2_04','We can reduce waste by reusing things.','물건을 재사용하면 쓰레기를 줄일 수 있어요.','reduce waste by reusing','by + -ing 패턴은 수단이나 방법을 설명할 때 써요.','환경 실천','A2','environment','pattern',NULL,4),
('s_environment_A2_05','I always bring my own bag.','저는 항상 제 가방을 가져와요.','I always bring my own','I always + 동사 패턴은 자신의 습관을 설명할 때 써요.','일상 습관','A2','environment','pattern',NULL,5),
('s_environment_A2_06','We shouldn''t waste food.','음식을 낭비해서는 안 돼요.','We shouldn''t waste','shouldn''t + 동사 패턴으로 하지 말아야 할 것을 부드럽게 표현해요.','환경 인식','A2','environment','pattern',NULL,6),
('s_environment_A2_07','Electric cars are better for the environment.','전기차는 환경에 더 좋아요.','better for the environment','better for는 무언가가 더 유익함을 비교할 때 쓰는 표현이에요.','친환경 제품','A2','environment','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — B1 (기후 변화 패턴)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_environment_B1_01','Climate change is affecting our daily lives.','기후 변화가 우리의 일상에 영향을 미치고 있어요.','is affecting','현재진행형은 지금 이 순간에도 계속 진행 중인 변화를 강조할 때 써요.','기후 변화','B1','environment','pattern',NULL,1),
('s_environment_B1_02','We need to reduce our carbon footprint.','우리는 탄소 발자국을 줄여야 해요.','reduce our carbon footprint','need to + 동사는 해야 하는 의무나 필요성을 강조할 때 써요.','환경 의식','B1','environment','pattern',NULL,2),
('s_environment_B1_03','If we don''t act now, the consequences will be severe.','지금 행동하지 않으면 결과가 심각할 거예요.','If we don''t act now','if + 현재, will + 동사 패턴은 미래의 결과를 경고할 때 써요.','환경 경고','B1','environment','pattern',NULL,3),
('s_environment_B1_04','Renewable energy is becoming cheaper every year.','재생 가능 에너지가 매년 더 저렴해지고 있어요.','is becoming cheaper','is becoming은 점진적인 변화를 나타낼 때 쓰는 현재진행형이에요.','에너지 전환','B1','environment','pattern',NULL,4),
('s_environment_B1_05','One of the main causes is deforestation.','주요 원인 중 하나는 삼림 벌채예요.','One of the main causes is','One of the + 복수명사 + is 패턴은 여러 원인 중 하나를 언급할 때 써요.','환경 설명','B1','environment','pattern',NULL,5),
('s_environment_B1_06','Governments should invest more in renewable energy.','정부는 재생 가능 에너지에 더 많이 투자해야 해요.','should invest more in','should + 동사는 조언이나 의견을 부드럽게 전달할 때 써요.','환경 정책','B1','environment','pattern',NULL,6),
('s_environment_B1_07','I''m concerned about the state of our oceans.','저는 우리 바다의 상태가 걱정돼요.','I''m concerned about','I''m concerned about + 명사 패턴은 걱정이나 우려를 표현할 때 써요.','환경 우려','B1','environment','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — B2 (환경 정책 패턴)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_environment_B2_01','Without urgent policy action, we risk crossing irreversible tipping points.','긴급한 정책 조치 없이는 돌이킬 수 없는 임계점을 넘을 위험이 있어요.','risk crossing irreversible tipping points','risk + -ing는 어떤 부정적 결과가 일어날 가능성을 표현할 때 써요.','환경 정책','B2','environment','pattern',NULL,1),
('s_environment_B2_02','The transition to a low-carbon economy requires both investment and regulation.','저탄소 경제로의 전환에는 투자와 규제가 모두 필요해요.','transition to a low-carbon economy','transition to + 명사는 어떤 체제나 상태로의 전환을 설명할 때 써요.','경제 환경','B2','environment','pattern',NULL,2),
('s_environment_B2_03','It is argued that a carbon tax would be the most effective solution.','탄소세가 가장 효과적인 해결책이라는 주장이 있어요.','It is argued that','It is argued that + 절은 논쟁의 여지가 있는 주장을 객관적으로 제시할 때 써요.','토론 및 논의','B2','environment','pattern',NULL,3),
('s_environment_B2_04','Biodiversity loss poses as great a threat as climate change itself.','생물 다양성 손실은 기후 변화 자체만큼 큰 위협이에요.','poses as great a threat as','as + 형용사 + as 구조는 두 가지를 동등하게 비교할 때 써요.','환경 비교','B2','environment','pattern',NULL,4),
('s_environment_B2_05','Wealthier nations have a moral obligation to support climate adaptation in developing countries.','부유한 나라들은 개발도상국의 기후 적응을 지원할 도덕적 의무가 있어요.','have a moral obligation to','have a moral obligation to + 동사는 도덕적 책임을 강조하는 격식체 표현이에요.','기후 정의','B2','environment','pattern',NULL,5),
('s_environment_B2_06','Greenwashing misleads consumers and undermines genuine environmental efforts.','그린워싱은 소비자를 오도하고 진정한 환경 노력을 약화시켜요.','misleads and undermines','두 동사를 and로 연결하면 두 가지 부정적 결과를 함께 강조할 수 있어요.','소비 환경','B2','environment','pattern',NULL,6),
('s_environment_B2_07','The evidence strongly suggests that immediate action is no longer optional.','증거는 즉각적인 행동이 더 이상 선택 사항이 아니라는 것을 강하게 시사해요.','The evidence strongly suggests that','The evidence suggests that + 절은 데이터를 근거로 주장할 때 쓰는 학술적 표현이에요.','학술 토론','B2','environment','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — C1 (기후 과학 패턴)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_environment_C1_01','The IPCC''s findings underscore the urgency of decarbonizing the global energy system.','IPCC의 조사 결과는 전 세계 에너지 시스템 탈탄소화의 시급성을 강조해요.','underscore the urgency of','underscore + 명사는 어떤 사실의 중요성이나 긴급성을 강조할 때 쓰는 격식 표현이에요.','기후 과학','C1','environment','pattern',NULL,1),
('s_environment_C1_02','Anthropogenic emissions have already committed the planet to further warming.','인위적 배출로 인해 지구는 이미 추가 온난화가 예정되어 있어요.','have already committed the planet to','have committed to는 미래에 피할 수 없는 결과를 나타낼 때 쓰는 표현이에요.','기후 과학','C1','environment','pattern',NULL,2),
('s_environment_C1_03','What remains debated is the precise timeline of non-linear climate feedbacks.','여전히 논쟁 중인 것은 비선형 기후 피드백의 정확한 시간표예요.','What remains debated is','What remains debated is + 명사 패턴은 학문적 불확실성을 강조할 때 써요.','기후 토론','C1','environment','pattern',NULL,3),
('s_environment_C1_04','Rewilding initiatives have shown promising results in restoring ecosystem resilience.','재야생화 이니셔티브는 생태계 회복 탄력성을 복원하는 데 유망한 결과를 보여줬어요.','have shown promising results in','have shown promising results in + -ing는 성과를 보고할 때 쓰는 학술적 표현이에요.','환경 연구','C1','environment','pattern',NULL,4),
('s_environment_C1_05','Geoengineering proposals must be evaluated against their potential unintended consequences.','지구공학 제안은 잠재적 의도치 않은 결과에 대해 평가되어야 해요.','must be evaluated against','must be + 과거분사 패턴은 수동태로 강한 의무를 표현해요.','정책 논의','C1','environment','pattern',NULL,5),
('s_environment_C1_06','The concept of planetary boundaries offers a scientific framework for sustainable governance.','지구 한계선 개념은 지속 가능한 거버넌스를 위한 과학적 틀을 제공해요.','offers a scientific framework for','offer a framework for + 명사는 어떤 개념이 제공하는 구조적 역할을 설명할 때 써요.','학술 발표','C1','environment','pattern',NULL,6),
('s_environment_C1_07','Carbon capture technology, while promising, cannot substitute for rapid emissions cuts.','탄소 포집 기술은 유망하지만 신속한 배출 감축을 대체할 수는 없어요.','while promising, cannot substitute for','while + 형용사 패턴은 장점을 인정하면서도 한계를 지적할 때 써요.','기술 논의','C1','environment','pattern',NULL,7);

-- ══════════════════════════════════════
-- PATTERNS — C2 (기후 과학 최고급 패턴)
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_environment_C2_01','The interplay between thermohaline circulation and radiative forcing determines long-term climate trajectories.','열염 순환과 복사 강제력 간의 상호 작용이 장기적인 기후 궤적을 결정해요.','interplay between A and B determines','the interplay between A and B determines는 두 시스템의 상호작용이 결과를 결정한다는 것을 표현해요.','기후 과학 논문','C2','environment','pattern',NULL,1),
('s_environment_C2_02','It is precisely the irreversibility of biospheric integrity loss that makes precautionary governance imperative.','생물권 무결성 손실의 비가역성이 바로 예방적 거버넌스를 필수적으로 만드는 이유예요.','It is precisely... that','It is precisely + 명사 + that 강조 구문은 핵심 논점을 강조할 때 쓰는 학술적 표현이에요.','학술 논의','C2','environment','pattern',NULL,2),
('s_environment_C2_03','Were we to cross multiple tipping points simultaneously, the resulting cascade could be civilisation-threatening.','여러 임계점을 동시에 넘게 된다면 그 결과로 나타나는 연쇄 반응은 문명을 위협할 수 있어요.','Were we to cross','Were + 주어 + to + 동사는 가정법 도치 구문으로 가능성이 낮지만 심각한 시나리오를 표현해요.','시나리오 분석','C2','environment','pattern',NULL,3),
('s_environment_C2_04','Teleconnections between Arctic amplification and mid-latitude weather extremes remain an active area of research.','북극 증폭과 중위도 극단적 기상 현상 사이의 원거리 연결은 여전히 활발한 연구 분야예요.','remain an active area of research','remain an active area of research는 아직 결론이 나지 않은 연구 주제를 학술적으로 표현해요.','학술 발표','C2','environment','pattern',NULL,4),
('s_environment_C2_05','The Holocene''s climatic stability, which underpinned all human civilisations, is now under unprecedented threat.','모든 인류 문명의 기반이 된 홀로세의 기후 안정성이 이제 전례 없는 위협에 처해 있어요.','which underpinned all human civilisations','관계절 which underpinned + 명사는 앞 내용에 맥락과 역사적 의미를 덧붙일 때 써요.','역사적 맥락','C2','environment','pattern',NULL,5),
('s_environment_C2_06','Notwithstanding the political obstacles, the trajectory toward net zero is arguably irreversible.','정치적 장애물에도 불구하고 탄소 중립을 향한 궤적은 논란의 여지 없이 되돌릴 수 없어요.','Notwithstanding the political obstacles','Notwithstanding + 명사는 반론을 인정하면서도 주장을 이어나갈 때 쓰는 격식 표현이에요.','정책 토론','C2','environment','pattern',NULL,6),
('s_environment_C2_07','Loss and damage reparations represent perhaps the most contentious frontier in international climate diplomacy.','손실과 피해 배상은 아마도 국제 기후 외교에서 가장 논쟁적인 영역을 나타내요.','represent perhaps the most contentious frontier in','represent + the most + 형용사 + 명사 in + 분야는 어떤 주제가 특정 분야에서 차지하는 위치를 표현해요.','국제 외교','C2','environment','pattern',NULL,7);
