-- EngCat — Academic (학술) 주제 단어 + 패턴
-- 210 words (35 per CEFR level A1~C2) + 42 patterns (7 per level)
-- IDs: w_academic_{CEFR}_{nn}, s_academic_{CEFR}_{nn}

-- ══════════════════════════════════════════════════════════════════════════════
-- WORDS — A1 (35개)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_academic_A1_01','learn','/lɜːrn/','verb','배우다','To gain knowledge or skill through study or experience.','I want to {learn} English every day.','저는 매일 영어를 배우고 싶어요.','learn','A1','academic',1,'student learning books desk study'),
('w_academic_A1_02','know','/noʊ/','verb','알다','To have information in your mind about something.','Do you {know} the answer to this question?','이 질문의 답을 알고 있나요?','know','A1','academic',1,'person thinking knowledge lightbulb'),
('w_academic_A1_03','understand','/ˌʌndərˈstænd/','verb','이해하다','To know what something means or how it works.','I don''t {understand} this lesson.','저는 이 수업을 이해하지 못해요.','understand','A1','academic',1,'student confused thinking classroom'),
('w_academic_A1_04','read','/riːd/','verb','읽다','To look at and comprehend written words.','I {read} one chapter every morning.','저는 매일 아침 한 챕터씩 읽어요.','read','A1','academic',1,'person reading book library'),
('w_academic_A1_05','write','/raɪt/','verb','쓰다','To make letters or words on a surface.','Please {write} your name on the paper.','종이에 이름을 써 주세요.','write','A1','academic',1,'hand writing pen notebook'),
('w_academic_A1_06','question','/ˈkwɛstʃən/','noun','질문','A sentence asking for information.','Do you have a {question} about today''s lesson?','오늘 수업에 대해 질문이 있나요?','question','A1','academic',1,'student raising hand classroom'),
('w_academic_A1_07','answer','/ˈænsər/','noun','답','A reply to a question or problem.','The {answer} is on page ten.','답은 10쪽에 있어요.','answer','A1','academic',1,'answer key test paper correct'),
('w_academic_A1_08','right','/raɪt/','adjective','맞는','Correct; in accordance with fact.','Your {right} answer gets a star.','맞는 답에는 별표가 붙어요.','right','A1','academic',1,'correct checkmark answer right'),
('w_academic_A1_09','wrong','/rɒŋ/','adjective','틀린','Not correct; mistaken.','That answer is {wrong} — try again.','그 답은 틀렸어요 — 다시 해 보세요.','wrong','A1','academic',1,'wrong answer cross mistake'),
('w_academic_A1_10','class','/klæs/','noun','수업, 반','A group of students taught together, or a lesson.','Our {class} starts at nine o''clock.','우리 수업은 9시에 시작해요.','class','A1','academic',1,'classroom students teacher board'),
('w_academic_A1_11','teacher','/ˈtiːtʃər/','noun','선생님','A person who teaches, especially in a school.','Our {teacher} explains things very clearly.','우리 선생님은 아주 명확하게 설명해 주세요.','teacher','A1','academic',1,'teacher classroom whiteboard teaching'),
('w_academic_A1_12','student','/ˈstuːdənt/','noun','학생','A person who is studying at a school or university.','Every {student} needs a pencil today.','오늘은 모든 학생이 연필이 필요해요.','student','A1','academic',1,'student backpack school uniform'),
('w_academic_A1_13','book','/bʊk/','noun','책','A written or printed work consisting of pages.','Please open your {book} to page five.','책 5쪽을 펼쳐 주세요.','book','A1','academic',1,'open book pages reading close-up'),
('w_academic_A1_14','word','/wɜːrd/','noun','단어','A unit of language that has meaning.','What does this {word} mean?','이 단어는 무슨 뜻이에요?','word','A1','academic',1,'dictionary word close-up vocabulary'),
('w_academic_A1_15','sentence','/ˈsɛntəns/','noun','문장','A group of words that expresses a complete thought.','Can you make a {sentence} with this word?','이 단어로 문장을 만들 수 있나요?','sentence','A1','academic',1,'writing sentence lined paper pencil'),
('w_academic_A1_16','repeat','/rɪˈpiːt/','verb','반복하다','To say or do something again.','Please {repeat} after me.','저를 따라 반복해 주세요.','repeat','A1','academic',1,'echo repeat cycle arrows loop'),
('w_academic_A1_17','spell','/spɛl/','verb','철자를 말하다','To write or say the letters that form a word.','How do you {spell} "beautiful"?','"beautiful"의 철자가 어떻게 되나요?','spell','A1','academic',1,'alphabet letters spelling board'),
('w_academic_A1_18','meaning','/ˈmiːnɪŋ/','noun','의미','What a word, sign, or text signifies.','Can you tell me the {meaning} of this word?','이 단어의 의미를 알려주실 수 있나요?','meaning','A1','academic',1,'dictionary definition meaning open book'),
('w_academic_A1_19','listen','/ˈlɪsən/','verb','듣다','To pay attention in order to hear something.','Please {listen} carefully to the instructions.','지시 사항을 잘 들어 주세요.','listen','A1','academic',1,'listening earphones attentive student'),
('w_academic_A1_20','speak','/spiːk/','verb','말하다','To say words aloud; to communicate verbally.','Can you {speak} more slowly, please?','좀 더 천천히 말씀해 주실 수 있나요?','speak','A1','academic',1,'person speaking microphone presentation'),
('w_academic_A1_21','number','/ˈnʌmbər/','noun','숫자','A mathematical value or symbol.','Write the {number} on the board.','칠판에 숫자를 써 주세요.','number','A1','academic',1,'numbers math blackboard chalk'),
('w_academic_A1_22','letter','/ˈlɛtər/','noun','글자','A character of the alphabet.','The first {letter} of the alphabet is A.','알파벳의 첫 번째 글자는 A예요.','letter','A1','academic',1,'alphabet letters wooden blocks'),
('w_academic_A1_23','page','/peɪdʒ/','noun','쪽, 페이지','One side of a sheet of paper in a book.','Turn to {page} twenty-three.','23쪽으로 넘겨 주세요.','page','A1','academic',1,'book pages turning open notebook'),
('w_academic_A1_24','test','/tɛst/','noun','시험','A series of questions to measure knowledge.','We have a {test} on Friday.','금요일에 시험이 있어요.','test','A1','academic',1,'exam test paper pencil desk'),
('w_academic_A1_25','true','/truː/','adjective','사실인, 참인','In accordance with fact; correct.','Is that statement {true} or false?','그 문장이 사실인가요, 거짓인가요?','true','A1','academic',1,'true false quiz card checkmark'),
('w_academic_A1_26','false','/fɔːls/','adjective','거짓인','Not correct; untrue.','Mark the sentence {false} if it is wrong.','틀린 문장에는 거짓이라고 표시해 주세요.','false','A1','academic',1,'false cross mark quiz answer'),
('w_academic_A1_27','grade','/ɡreɪd/','noun','점수, 학점','A mark given to show the quality of work.','I got a good {grade} on my test.','시험에서 좋은 점수를 받았어요.','grade','A1','academic',1,'report card grade A score'),
('w_academic_A1_28','study','/ˈstʌdi/','verb','공부하다','To spend time learning about a subject.','I {study} for two hours every day.','저는 매일 두 시간씩 공부해요.','study','A1','academic',1,'student desk lamp night studying'),
('w_academic_A1_29','homework','/ˈhoʊmwɜːrk/','noun','숙제','Work that a student is asked to do at home.','Did you finish your {homework}?','숙제 다 했나요?','homework','A1','academic',1,'homework notebook pen kitchen table'),
('w_academic_A1_30','practice','/ˈpræktɪs/','verb','연습하다','To do something repeatedly to improve your skill.','You need to {practice} every day.','매일 연습해야 해요.','practice','A1','academic',1,'practice repetition piano keys skill'),
('w_academic_A1_31','example','/ɪɡˈzæmpəl/','noun','예시','Something that shows or explains a general rule.','Can you give me an {example}?','예시를 들어주실 수 있나요?','example','A1','academic',1,'example whiteboard explanation illustration'),
('w_academic_A1_32','explain','/ɪkˈspleɪn/','verb','설명하다','To make something clear or easy to understand.','Could you {explain} that word again?','그 단어를 다시 설명해 주실 수 있나요?','explain','A1','academic',1,'teacher explaining pointing whiteboard'),
('w_academic_A1_33','notebook','/ˈnoʊtbʊk/','noun','공책','A book with blank pages for writing notes.','Please open your {notebook}.','공책을 펼쳐 주세요.','notebook','A1','academic',1,'open notebook pen writing notes'),
('w_academic_A1_34','pencil','/ˈpɛnsəl/','noun','연필','A thin stick of graphite used for writing.','Do you have a spare {pencil}?','여분의 연필이 있나요?','pencil','A1','academic',1,'pencil writing paper close-up'),
('w_academic_A1_35','dictionary','/ˈdɪkʃəˌnɛri/','noun','사전','A book listing words with their definitions.','Look it up in the {dictionary}.','사전에서 찾아 보세요.','dictionary','A1','academic',1,'dictionary open reference book');

-- ══════════════════════════════════════════════════════════════════════════════
-- WORDS — A2 (35개)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_academic_A2_01','research','/ˈriːsɜːrtʃ/','noun','연구, 조사','The systematic investigation of a subject to discover facts.','I did some {research} on climate change.','기후 변화에 대해 조사를 했어요.','research','A2','academic',1,'research laptop data papers desk'),
('w_academic_A2_02','theory','/ˈθɪəri/','noun','이론','A set of ideas intended to explain something.','Darwin''s {theory} changed science.','다윈의 이론은 과학을 바꿨어요.','theory','A2','academic',2,'theory diagram equation blackboard'),
('w_academic_A2_03','fact','/fækt/','noun','사실','Something that is known to be true.','That is an interesting {fact}.','그것은 흥미로운 사실이에요.','fact','A2','academic',1,'fact check newspaper magnifying glass'),
('w_academic_A2_04','idea','/aɪˈdiə/','noun','생각, 아이디어','A thought or suggestion about what to do.','That''s a great {idea} for the project.','그건 프로젝트에 좋은 아이디어예요.','idea','A2','academic',1,'lightbulb idea thinking creativity'),
('w_academic_A2_05','subject','/ˈsʌbdʒɪkt/','noun','과목, 주제','A branch of knowledge studied in school.','What is your favourite {subject}?','가장 좋아하는 과목이 뭐예요?','subject','A2','academic',1,'school subjects books colourful'),
('w_academic_A2_06','paper','/ˈpeɪpər/','noun','논문, 보고서','A piece of academic writing on a topic.','She wrote a {paper} on renewable energy.','그녀는 재생 에너지에 관한 논문을 썼어요.','paper','A2','academic',2,'academic paper writing desk research'),
('w_academic_A2_07','present','/prɪˈzɛnt/','verb','발표하다','To give a formal talk to an audience.','I will {present} my findings next week.','다음 주에 연구 결과를 발표할 거예요.','present','A2','academic',2,'presentation slides projector audience'),
('w_academic_A2_08','method','/ˈmɛθəd/','noun','방법','A particular way of doing something.','What {method} did you use for the experiment?','실험에 어떤 방법을 사용했나요?','method','A2','academic',2,'method steps flowchart process'),
('w_academic_A2_09','result','/rɪˈzʌlt/','noun','결과','The consequence or outcome of an action.','The {result} of the experiment was surprising.','실험 결과가 놀라웠어요.','result','A2','academic',1,'results chart data graph outcome'),
('w_academic_A2_10','review','/rɪˈvjuː/','verb','검토하다, 복습하다','To look at something again carefully.','Let''s {review} the main points.','주요 내용을 복습해 봅시다.','review','A2','academic',1,'review checklist notes revision'),
('w_academic_A2_11','note','/noʊt/','noun','필기, 메모','A short written record to help you remember.','Please take {note} of the key terms.','핵심 용어를 필기해 주세요.','note','A2','academic',1,'notes notebook pen handwriting'),
('w_academic_A2_12','compare','/kəmˈpɛr/','verb','비교하다','To examine the similarities or differences between things.','{Compare} the two graphs on page six.','6쪽의 두 그래프를 비교해 보세요.','Compare','A2','academic',2,'compare contrast two items side by side'),
('w_academic_A2_13','difference','/ˈdɪfərəns/','noun','차이점','A way in which two things are not the same.','What is the {difference} between these two words?','이 두 단어의 차이점이 뭐예요?','difference','A2','academic',1,'difference compare Venn diagram'),
('w_academic_A2_14','similar','/ˈsɪmɪlər/','adjective','비슷한','Almost the same but not exactly.','These two results are {similar}.','이 두 결과는 비슷해요.','similar','A2','academic',1,'similar shapes comparison pattern'),
('w_academic_A2_15','opposite','/ˈɒpəzɪt/','adjective','반대의','Completely different; contrary in direction.','Hot and cold are {opposite} temperatures.','뜨거운 것과 차가운 것은 반대 온도예요.','opposite','A2','academic',1,'opposite arrows left right contrast'),
('w_academic_A2_16','discuss','/dɪˈskʌs/','verb','토론하다','To talk about a subject in detail.','We will {discuss} this topic in class.','수업 시간에 이 주제를 토론할 거예요.','discuss','A2','academic',2,'group discussion students talking'),
('w_academic_A2_17','opinion','/əˈpɪnjən/','noun','의견','A personal view or judgement about something.','In my {opinion}, that theory is wrong.','제 의견으로는 그 이론이 틀렸어요.','opinion','A2','academic',1,'opinion speech bubble debate'),
('w_academic_A2_18','important','/ɪmˈpɔːrtənt/','adjective','중요한','Of great significance or value.','This concept is very {important}.','이 개념은 매우 중요해요.','important','A2','academic',1,'important highlight star marker'),
('w_academic_A2_19','information','/ˌɪnfərˈmeɪʃən/','noun','정보','Facts or knowledge provided or learned.','I need more {information} about this topic.','이 주제에 대해 정보가 더 필요해요.','information','A2','academic',1,'information data search online'),
('w_academic_A2_20','describe','/dɪˈskraɪb/','verb','묘사하다','To give a detailed account of something.','Can you {describe} the process?','그 과정을 묘사해 주실 수 있나요?','describe','A2','academic',2,'describe explanation writing diagram'),
('w_academic_A2_21','example','/ɪɡˈzæmpəl/','noun','예시','An instance that illustrates a rule or principle.','Give an {example} to support your point.','요점을 뒷받침할 예시를 들어 주세요.','example','A2','academic',1,'example case study illustration'),
('w_academic_A2_22','solve','/sɒlv/','verb','풀다, 해결하다','To find an answer or solution to a problem.','Can you {solve} this math problem?','이 수학 문제를 풀 수 있나요?','solve','A2','academic',2,'math problem solving equation chalkboard'),
('w_academic_A2_23','topic','/ˈtɒpɪk/','noun','주제','The subject of a discussion or piece of writing.','What is the {topic} of your essay?','에세이 주제가 뭐예요?','topic','A2','academic',1,'topic mind map brainstorm'),
('w_academic_A2_24','essay','/ˈɛseɪ/','noun','에세이','A short piece of writing on a particular topic.','Hand in your {essay} by Monday.','에세이를 월요일까지 제출해 주세요.','essay','A2','academic',2,'essay writing laptop student'),
('w_academic_A2_25','conclusion','/kənˈkluːʒən/','noun','결론','The final part of a text or argument.','What is the {conclusion} of the study?','연구의 결론이 무엇인가요?','conclusion','A2','academic',2,'conclusion end summary paragraph'),
('w_academic_A2_26','introduction','/ˌɪntrəˈdʌkʃən/','noun','서론, 소개','The opening section of a text or presentation.','Write a clear {introduction} for your essay.','에세이에 명확한 서론을 써 주세요.','introduction','A2','academic',2,'introduction opening paragraph writing'),
('w_academic_A2_27','paragraph','/ˈpærəɡrɑːf/','noun','단락','A distinct section of a piece of writing.','Start a new {paragraph} for each idea.','아이디어마다 새 단락을 시작하세요.','paragraph','A2','academic',2,'paragraph writing indent text'),
('w_academic_A2_28','report','/rɪˈpɔːrt/','noun','보고서','A document presenting information on a topic.','Submit your {report} before noon.','정오 전에 보고서를 제출해 주세요.','report','A2','academic',1,'report document writing professional'),
('w_academic_A2_29','project','/ˈprɒdʒɛkt/','noun','프로젝트','A planned piece of work to achieve a goal.','Our group {project} is due next week.','우리 그룹 프로젝트가 다음 주에 마감이에요.','project','A2','academic',1,'group project teamwork students'),
('w_academic_A2_30','score','/skɔːr/','noun','점수','The number of points someone gets in a test.','What was your {score} on the quiz?','퀴즈에서 몇 점을 받았나요?','score','A2','academic',1,'score result test percentage'),
('w_academic_A2_31','improve','/ɪmˈpruːv/','verb','향상시키다','To make something better than it was before.','How can I {improve} my writing?','제 글쓰기를 어떻게 향상시킬 수 있나요?','improve','A2','academic',1,'improve growth chart progress arrow'),
('w_academic_A2_32','difficult','/ˈdɪfɪkəlt/','adjective','어려운','Not easy; requiring effort or skill.','This chapter is quite {difficult}.','이 챕터는 꽤 어렵네요.','difficult','A2','academic',1,'difficult challenge thinking hard problem'),
('w_academic_A2_33','clear','/klɪr/','adjective','명확한','Easy to understand; not confusing.','Your explanation was very {clear}.','설명이 매우 명확했어요.','clear','A2','academic',1,'clear window transparency bright'),
('w_academic_A2_34','correct','/kəˈrɛkt/','adjective','올바른','Free from errors; right.','That is the {correct} answer.','그것이 올바른 답이에요.','correct','A2','academic',1,'correct answer checkmark green tick'),
('w_academic_A2_35','remember','/rɪˈmɛmbər/','verb','기억하다','To have information come back to mind.','Try to {remember} the main vocabulary.','핵심 어휘를 기억하려고 노력해 보세요.','remember','A2','academic',1,'memory brain remember sticky note');

-- ══════════════════════════════════════════════════════════════════════════════
-- WORDS — B1 (35개)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_academic_B1_01','hypothesis','/haɪˈpɒθɪsɪs/','noun','가설','A proposed explanation for an observation, to be tested.','We need to form a {hypothesis} before starting.','시작 전에 가설을 세워야 해요.','hypothesis','B1','academic',1,'hypothesis test experiment science lab'),
('w_academic_B1_02','evidence','/ˈɛvɪdəns/','noun','증거, 근거','Information that supports or refutes a claim.','You need {evidence} to support your argument.','주장을 뒷받침하는 근거가 필요해요.','evidence','B1','academic',1,'evidence research data documents'),
('w_academic_B1_03','analyze','/ˈænəlaɪz/','verb','분석하다','To examine something in detail to understand it.','Let''s {analyze} the survey data together.','설문 데이터를 함께 분석해 봅시다.','analyze','B1','academic',1,'data analysis chart laptop'),
('w_academic_B1_04','conclude','/kənˈkluːd/','verb','결론짓다','To arrive at a judgment from reasoning or evidence.','We can {conclude} that the hypothesis was correct.','가설이 옳았다고 결론지을 수 있어요.','conclude','B1','academic',2,'conclusion research findings summary'),
('w_academic_B1_05','cite','/saɪt/','verb','인용하다','To refer to a source of information in writing.','You must {cite} all sources in your paper.','논문에서 모든 출처를 인용해야 해요.','cite','B1','academic',2,'citation reference bibliography footnote'),
('w_academic_B1_06','abstract','/ˈæbstrækt/','noun','초록, 요약','A short summary of a research paper.','Read the {abstract} before the full paper.','전문을 읽기 전에 초록을 읽으세요.','abstract','B1','academic',2,'abstract summary research paper top'),
('w_academic_B1_07','journal','/ˈdʒɜːrnəl/','noun','학술지, 저널','A publication containing academic articles.','The study was published in a peer-reviewed {journal}.','그 연구는 동료 심사 학술지에 게재되었어요.','journal','B1','academic',2,'academic journal magazine library shelf'),
('w_academic_B1_08','empirical','/ɛmˈpɪrɪkəl/','adjective','경험적인','Based on observation or experiment, not theory.','We need {empirical} data to test this claim.','이 주장을 검증하려면 경험적 데이터가 필요해요.','empirical','B1','academic',3,'experiment lab data collection observation'),
('w_academic_B1_09','variable','/ˈvɛriəbəl/','noun','변수','A factor that can change in an experiment.','Control for every {variable} in your experiment.','실험에서 모든 변수를 통제하세요.','variable','B1','academic',2,'variable equation graph axis data'),
('w_academic_B1_10','methodology','/ˌmɛθəˈdɒlədʒi/','noun','방법론','The system of methods used in a field of study.','Explain the {methodology} in your research paper.','연구 논문에서 방법론을 설명해 주세요.','methodology','B1','academic',2,'research methodology diagram flowchart'),
('w_academic_B1_11','argument','/ˈɑːrɡjəmənt/','noun','논거, 주장','A reason given to support or disprove a claim.','Your {argument} lacks sufficient evidence.','당신의 논거에 충분한 근거가 부족해요.','argument','B1','academic',1,'argument debate discussion points'),
('w_academic_B1_12','source','/sɔːrs/','noun','출처, 자료','The origin of information used in research.','Always check your {source} for reliability.','항상 출처의 신뢰성을 확인하세요.','source','B1','academic',1,'source reference book citation credible'),
('w_academic_B1_13','survey','/ˈsɜːrveɪ/','noun','설문, 조사','A set of questions asked to gather information.','We conducted a {survey} of 500 students.','500명의 학생을 대상으로 설문 조사를 실시했어요.','survey','B1','academic',2,'survey questionnaire clipboard research'),
('w_academic_B1_14','objective','/əbˈdʒɛktɪv/','adjective','객관적인','Not influenced by personal feelings; impartial.','Try to remain {objective} in your analysis.','분석에서 객관적인 태도를 유지하려고 노력하세요.','objective','B1','academic',2,'objective balance scale impartial'),
('w_academic_B1_15','subjective','/səbˈdʒɛktɪv/','adjective','주관적인','Based on personal feelings or opinions.','Beauty is a {subjective} concept.','아름다움은 주관적인 개념이에요.','subjective','B1','academic',2,'subjective personal opinion perspective'),
('w_academic_B1_16','significant','/sɪɡˈnɪfɪkənt/','adjective','유의미한, 중요한','Large enough to be noticed or to have an effect.','The difference was statistically {significant}.','그 차이는 통계적으로 유의미했어요.','significant','B1','academic',2,'significant impact statistics graph'),
('w_academic_B1_17','assume','/əˈsjuːm/','verb','가정하다','To suppose something is true without proof.','We {assume} that all participants were honest.','모든 참가자가 정직했다고 가정해요.','assume','B1','academic',2,'assume suppose think implication'),
('w_academic_B1_18','interpret','/ɪnˈtɜːrprɪt/','verb','해석하다','To explain or understand the meaning of something.','How do you {interpret} these results?','이 결과를 어떻게 해석하나요?','interpret','B1','academic',2,'interpret reading graph analysis'),
('w_academic_B1_19','outline','/ˈaʊtlaɪn/','noun','개요','A summary of the main points of a text.','Write an {outline} before starting your essay.','에세이를 시작하기 전에 개요를 작성하세요.','outline','B1','academic',2,'outline plan structure list'),
('w_academic_B1_20','reference','/ˈrɛfrəns/','noun','참고 문헌','A source of information cited in academic work.','Add the {reference} to your bibliography.','참고 문헌 목록에 참고 문헌을 추가하세요.','reference','B1','academic',2,'reference list bibliography book'),
('w_academic_B1_21','statistic','/stəˈtɪstɪk/','noun','통계 수치','A fact or piece of data from a study.','The {statistic} shows a rise in literacy rates.','그 통계 수치는 문해율 상승을 보여줘요.','statistic','B1','academic',2,'statistics data chart bar graph'),
('w_academic_B1_22','experiment','/ɪkˈspɛrɪmənt/','noun','실험','A scientific test to find out if something is true.','The {experiment} confirmed our hypothesis.','실험이 우리의 가설을 확인해 줬어요.','experiment','B1','academic',1,'science experiment lab flask chemistry'),
('w_academic_B1_23','observation','/ˌɒbzərˈveɪʃən/','noun','관찰','The act of watching something carefully to gain information.','Record your {observation} in the data table.','데이터 표에 관찰 내용을 기록하세요.','observation','B1','academic',2,'observation nature field notes scientist'),
('w_academic_B1_24','support','/səˈpɔːrt/','verb','뒷받침하다','To provide evidence that confirms a claim.','This data {supports} the original hypothesis.','이 데이터는 원래 가설을 뒷받침해요.','supports','B1','academic',1,'support evidence pillar structure'),
('w_academic_B1_25','contrast','/ˈkɒntrɑːst/','noun','대조','The difference between two or more compared things.','In {contrast}, the control group showed no change.','반면에 대조군은 변화가 없었어요.','contrast','B1','academic',2,'contrast comparison side by side'),
('w_academic_B1_26','define','/dɪˈfaɪn/','verb','정의하다','To explain the exact meaning of a word or concept.','First, {define} your key terms.','먼저 핵심 용어를 정의하세요.','define','B1','academic',1,'definition dictionary key term'),
('w_academic_B1_27','finding','/ˈfaɪndɪŋ/','noun','발견, 연구 결과','A result or conclusion from research.','The main {finding} was unexpected.','주요 연구 결과가 예상치 못한 것이었어요.','finding','B1','academic',2,'research finding discovery data'),
('w_academic_B1_28','propose','/prəˈpoʊz/','verb','제안하다','To suggest a plan or theory for consideration.','I would like to {propose} a new approach.','새로운 접근 방식을 제안하고 싶어요.','propose','B1','academic',2,'proposal idea meeting presentation'),
('w_academic_B1_29','evaluate','/ɪˈvæljueɪt/','verb','평가하다','To judge the value or quality of something.','We need to {evaluate} the reliability of the data.','데이터의 신뢰성을 평가해야 해요.','evaluate','B1','academic',2,'evaluation rubric assessment scoring'),
('w_academic_B1_30','sample','/ˈsæmpəl/','noun','표본, 샘플','A small part representing the whole group studied.','The {sample} size was three hundred people.','표본 크기는 300명이었어요.','sample','B1','academic',2,'sample size statistics research group'),
('w_academic_B1_31','data','/ˈdeɪtə/','noun','데이터, 자료','Facts and statistics collected for analysis.','The {data} was collected over six months.','데이터는 6개월에 걸쳐 수집됐어요.','data','B1','academic',1,'data collection spreadsheet numbers'),
('w_academic_B1_32','publish','/ˈpʌblɪʃ/','verb','출판하다, 발표하다','To make research available to others in print or online.','Her study was {published} in 2023.','그녀의 연구는 2023년에 발표되었어요.','published','B1','academic',2,'publish journal paper online academic'),
('w_academic_B1_33','relevant','/ˈrɛlɪvənt/','adjective','관련 있는','Closely connected to the subject being discussed.','Only include {relevant} information in the report.','보고서에는 관련 있는 정보만 포함하세요.','relevant','B1','academic',2,'relevant connection related link'),
('w_academic_B1_34','precise','/prɪˈsaɪs/','adjective','정확한','Exact and accurate, with no ambiguity.','Use {precise} language in academic writing.','학술 글쓰기에서는 정확한 언어를 사용하세요.','precise','B1','academic',2,'precise measurement ruler accurate'),
('w_academic_B1_35','critical','/ˈkrɪtɪkəl/','adjective','비판적인','Involving careful analysis and judgment.','Develop your {critical} thinking skills.','비판적 사고 능력을 개발하세요.','critical','B1','academic',2,'critical thinking brain analysis puzzle');

-- ══════════════════════════════════════════════════════════════════════════════
-- WORDS — B2 (35개)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_academic_B2_01','peer review','/pɪr rɪˈvjuː/','noun','동료 심사','Evaluation of research by experts in the same field before publication.','The paper passed {peer review} in two weeks.','그 논문은 2주 만에 동료 심사를 통과했어요.','peer review','B2','academic',2,'peer review journal evaluation academics'),
('w_academic_B2_02','dissertation','/ˌdɪsərˈteɪʃən/','noun','학위 논문','A long piece of written research for an advanced degree.','She spent three years writing her {dissertation}.','그녀는 학위 논문을 쓰는 데 3년을 보냈어요.','dissertation','B2','academic',2,'dissertation thesis writing university'),
('w_academic_B2_03','framework','/ˈfreɪmwɜːrk/','noun','이론적 틀','A structure of ideas used to understand a concept.','The study uses a social-cognitive {framework}.','그 연구는 사회인지적 이론적 틀을 사용해요.','framework','B2','academic',2,'framework structure theory diagram'),
('w_academic_B2_04','paradigm','/ˈpærədaɪm/','noun','패러다임','A typical model or pattern; a school of thought.','This discovery shifted the scientific {paradigm}.','이 발견이 과학적 패러다임을 바꿨어요.','paradigm','B2','academic',3,'paradigm shift model thinking evolution'),
('w_academic_B2_05','qualitative','/ˈkwɒlɪtətɪv/','adjective','질적인','Relating to non-numerical data such as interviews.','A {qualitative} approach was used to explore experiences.','경험을 탐구하기 위해 질적 접근법을 사용했어요.','qualitative','B2','academic',2,'qualitative interview research notes'),
('w_academic_B2_06','quantitative','/ˈkwɒntɪtətɪv/','adjective','양적인','Relating to numerical data and statistical measurement.','The {quantitative} data was analyzed using regression.','양적 데이터는 회귀 분석으로 분석했어요.','quantitative','B2','academic',2,'quantitative data statistics numbers graph'),
('w_academic_B2_07','epistemology','/ɪˌpɪstɪˈmɒlədʒi/','noun','인식론','The branch of philosophy concerned with the nature of knowledge.','{Epistemology} asks: what can we know and how?','인식론은 우리가 무엇을 알 수 있고 어떻게 알 수 있는지를 물어요.','Epistemology','B2','academic',3,'philosophy knowledge mind thinking'),
('w_academic_B2_08','inference','/ˈɪnfərəns/','noun','추론','A conclusion reached from evidence and reasoning.','Drawing a valid {inference} requires solid data.','유효한 추론을 도출하려면 견고한 데이터가 필요해요.','inference','B2','academic',3,'inference logic deduction reasoning'),
('w_academic_B2_09','validity','/vəˈlɪdɪti/','noun','타당성','The quality of being logically or factually sound.','Question the {validity} of every source you use.','사용하는 모든 출처의 타당성을 의심하세요.','validity','B2','academic',2,'validity scale measurement research'),
('w_academic_B2_10','reliability','/rɪˌlaɪəˈbɪlɪti/','noun','신뢰성','The quality of producing consistent and dependable results.','Test-retest {reliability} was above 0.9.','검사-재검사 신뢰성은 0.9 이상이었어요.','reliability','B2','academic',2,'reliability testing consistency data'),
('w_academic_B2_11','bias','/ˈbaɪəs/','noun','편향','An unfair tendency to favour one thing over another.','Researcher {bias} can skew the results.','연구자 편향이 결과를 왜곡할 수 있어요.','bias','B2','academic',2,'bias scale tipped unfair research'),
('w_academic_B2_12','correlation','/ˌkɒrəˈleɪʃən/','noun','상관관계','A mutual relationship between two or more variables.','There is a strong {correlation} between the two factors.','두 요인 사이에 강한 상관관계가 있어요.','correlation','B2','academic',2,'correlation scatter plot graph data'),
('w_academic_B2_13','causation','/kɔːˈzeɪʃən/','noun','인과관계','The action of causing something; cause and effect.','{Causation} is harder to prove than correlation.','인과관계는 상관관계보다 증명하기 더 어려워요.','Causation','B2','academic',3,'causation cause effect arrows'),
('w_academic_B2_14','replicate','/ˈrɛplɪkeɪt/','verb','재현하다','To repeat an experiment to verify its results.','Other labs could not {replicate} the findings.','다른 연구실들이 결과를 재현할 수 없었어요.','replicate','B2','academic',3,'replication experiment duplicate science'),
('w_academic_B2_15','longitudinal','/ˌlɒŋɡɪˈtjuːdɪnəl/','adjective','종단적인','Conducted over a long period to track changes.','The {longitudinal} study tracked participants for ten years.','종단 연구는 10년 동안 참가자를 추적했어요.','longitudinal','B2','academic',3,'longitudinal study timeline years data'),
('w_academic_B2_16','cross-sectional','/krɒs ˈsɛkʃənəl/','adjective','횡단적인','Carried out at a single point in time across a group.','A {cross-sectional} survey was administered in March.','3월에 횡단 설문이 실시되었어요.','cross-sectional','B2','academic',3,'cross section survey snapshot population'),
('w_academic_B2_17','synthesis','/ˈsɪnθɪsɪs/','noun','종합, 합성','The combination of ideas or sources into a coherent whole.','A literature review requires {synthesis} of many sources.','문헌 검토는 많은 출처의 종합을 필요로 해요.','synthesis','B2','academic',2,'synthesis combine ideas mind map'),
('w_academic_B2_18','critique','/krɪˈtiːk/','noun','비평','A detailed analysis and assessment of something.','Write a {critique} of the assigned reading.','지정된 읽기 자료에 대한 비평을 써 주세요.','critique','B2','academic',2,'critique analysis essay writing pen'),
('w_academic_B2_19','hypothesis testing','/haɪˈpɒθɪsɪs ˈtɛstɪŋ/','noun','가설 검증','A statistical method to accept or reject a hypothesis.','{Hypothesis testing} uses p-values and significance levels.','가설 검증은 p값과 유의 수준을 사용해요.','Hypothesis testing','B2','academic',3,'hypothesis test statistics significance'),
('w_academic_B2_20','discourse','/ˈdɪskɔːrs/','noun','담론','Written or spoken communication and its social context.','Academic {discourse} follows strict conventions.','학문적 담론은 엄격한 관행을 따라요.','discourse','B2','academic',3,'discourse communication text context'),
('w_academic_B2_21','conceptual','/kənˈsɛptʃuəl/','adjective','개념적인','Relating to concepts or ideas rather than concrete things.','Build a {conceptual} model before collecting data.','데이터 수집 전에 개념적 모델을 구축하세요.','conceptual','B2','academic',3,'concept map abstract diagram theory'),
('w_academic_B2_22','implicit','/ɪmˈplɪsɪt/','adjective','암묵적인','Suggested but not directly stated.','The study has {implicit} assumptions about gender.','그 연구에는 성별에 대한 암묵적 가정이 있어요.','implicit','B2','academic',3,'implicit hidden assumption underlying'),
('w_academic_B2_23','explicit','/ɪkˈsplɪsɪt/','adjective','명시적인','Stated clearly and in detail with no room for confusion.','Make your research question {explicit} in the introduction.','서론에서 연구 질문을 명시적으로 제시하세요.','explicit','B2','academic',3,'explicit clear statement writing'),
('w_academic_B2_24','assertion','/əˈsɜːrʃən/','noun','주장','A confident and forceful statement of fact.','Back every {assertion} with evidence.','모든 주장을 근거로 뒷받침하세요.','assertion','B2','academic',3,'assertion claim argument point'),
('w_academic_B2_25','scope','/skoʊp/','noun','범위','The extent of the area or subject matter covered.','Define the {scope} of your study early on.','연구 범위를 초반에 정의하세요.','scope','B2','academic',2,'scope boundary research limitations'),
('w_academic_B2_26','limitation','/ˌlɪmɪˈteɪʃən/','noun','한계','A restriction or shortcoming in a study.','Acknowledge the {limitation} of a small sample size.','작은 표본 크기의 한계를 인정하세요.','limitation','B2','academic',2,'limitation boundary research constraint'),
('w_academic_B2_27','implication','/ˌɪmplɪˈkeɪʃən/','noun','함의, 시사점','A possible consequence suggested by the findings.','Discuss the {implication} of the results for policy.','결과가 정책에 주는 함의를 논의하세요.','implication','B2','academic',2,'implication consequence suggestion arrow'),
('w_academic_B2_28','transparency','/trænsˈpærənsi/','noun','투명성','The quality of being open and easy to verify.','Methodological {transparency} builds trust in research.','방법론적 투명성은 연구에 대한 신뢰를 높여요.','transparency','B2','academic',3,'transparency open research clear'),
('w_academic_B2_29','generalize','/ˈdʒɛnərəlaɪz/','verb','일반화하다','To apply a conclusion from one case to a wider group.','You cannot {generalize} from such a small sample.','그렇게 작은 표본에서는 일반화할 수 없어요.','generalize','B2','academic',3,'generalize population sample arrow'),
('w_academic_B2_30','theoretical','/ˌθɪəˈrɛtɪkəl/','adjective','이론적인','Concerned with ideas and principles rather than practice.','Build a strong {theoretical} foundation for your study.','연구를 위한 탄탄한 이론적 토대를 구축하세요.','theoretical','B2','academic',2,'theory books abstract diagram'),
('w_academic_B2_31','literature review','/ˈlɪtərətʃər rɪˈvjuː/','noun','문헌 검토','A survey of existing published research on a topic.','Chapter two is a {literature review}.','2장은 문헌 검토예요.','literature review','B2','academic',2,'literature review books research library'),
('w_academic_B2_32','operationalize','/ˌɒpərˈeɪʃənəlaɪz/','verb','조작적으로 정의하다','To define a concept in measurable terms.','You must {operationalize} abstract concepts before measuring.','측정 전에 추상적 개념을 조작적으로 정의해야 해요.','operationalize','B2','academic',3,'operationalize measure define scale'),
('w_academic_B2_33','triangulation','/traɪˌæŋɡjʊˈleɪʃən/','noun','삼각 측정법','Using multiple methods or sources to confirm findings.','{Triangulation} strengthens the credibility of qualitative research.','삼각 측정법은 질적 연구의 신뢰성을 강화해요.','Triangulation','B2','academic',3,'triangulation methods research credibility'),
('w_academic_B2_34','ethics','/ˈɛθɪks/','noun','윤리','The moral principles governing research conduct.','The study was approved by the {ethics} committee.','연구는 윤리 위원회의 승인을 받았어요.','ethics','B2','academic',1,'ethics moral principles research committee'),
('w_academic_B2_35','consent','/kənˈsɛnt/','noun','동의','Voluntary agreement to participate in research.','All participants gave informed {consent}.','모든 참가자가 충분한 설명을 들은 후 동의했어요.','consent','B2','academic',1,'consent form signature agreement');

-- ══════════════════════════════════════════════════════════════════════════════
-- WORDS — C1 (35개)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_academic_C1_01','ontology','/ɒnˈtɒlədʒi/','noun','존재론','The branch of metaphysics dealing with the nature of being.','Her thesis is grounded in social {ontology}.','그녀의 논문은 사회 존재론에 기반을 두고 있어요.','ontology','C1','academic',3,'philosophy being existence abstract'),
('w_academic_C1_02','axiology','/ˌæksiˈɒlədʒi/','noun','가치론','The philosophical study of value and worth.','{Axiology} guides the ethical stance of a study.','가치론은 연구의 윤리적 입장을 안내해요.','Axiology','C1','academic',3,'value ethics philosophy study'),
('w_academic_C1_03','deductive','/dɪˈdʌktɪv/','adjective','연역적인','Moving from general principles to specific conclusions.','A {deductive} approach tests an existing theory.','연역적 접근법은 기존 이론을 검증해요.','deductive','C1','academic',3,'deductive logic arrow general specific'),
('w_academic_C1_04','inductive','/ɪnˈdʌktɪv/','adjective','귀납적인','Moving from specific observations to general conclusions.','{Inductive} reasoning builds theory from data.','귀납적 추론은 데이터에서 이론을 구축해요.','Inductive','C1','academic',3,'inductive reasoning observation general'),
('w_academic_C1_05','abductive','/æbˈdʌktɪv/','adjective','귀추적인','Reasoning that infers the most plausible explanation.','{Abductive} logic is common in exploratory research.','귀추적 논리는 탐색적 연구에서 흔해요.','Abductive','C1','academic',3,'abductive inference best explanation'),
('w_academic_C1_06','hermeneutics','/ˌhɜːrmɪˈnjuːtɪks/','noun','해석학','The theory and methodology of interpretation of texts.','{Hermeneutics} shapes how we read historical documents.','해석학은 우리가 역사적 문서를 읽는 방식을 형성해요.','Hermeneutics','C1','academic',3,'hermeneutics interpretation text philosophy'),
('w_academic_C1_07','phenomenology','/fɪˌnɒmɪˈnɒlədʒi/','noun','현상학','The philosophical study of structures of subjective experience.','The researcher used {phenomenology} to explore lived experience.','연구자는 살아있는 경험을 탐구하기 위해 현상학을 사용했어요.','phenomenology','C1','academic',3,'phenomenology experience consciousness'),
('w_academic_C1_08','positivism','/ˈpɒzɪtɪvɪzəm/','noun','실증주의','The view that knowledge comes only from empirical evidence.','{Positivism} underpins most quantitative research designs.','실증주의는 대부분의 양적 연구 설계의 기반이 돼요.','Positivism','C1','academic',3,'positivism science empirical evidence'),
('w_academic_C1_09','constructivism','/kənˈstrʌktɪvɪzəm/','noun','구성주의','The view that knowledge is constructed through social interaction.','{Constructivism} sees reality as socially built.','구성주의는 현실이 사회적으로 구축된다고 봐요.','Constructivism','C1','academic',3,'constructivism knowledge build social'),
('w_academic_C1_10','pragmatism','/ˈpræɡmətɪzəm/','noun','실용주의','The view that truth is determined by practical outcomes.','{Pragmatism} justifies using both methods.','실용주의는 두 방법을 모두 사용하는 것을 정당화해요.','Pragmatism','C1','academic',3,'pragmatism practical outcome philosophy'),
('w_academic_C1_11','reflexivity','/ˌriːflɛkˈsɪvɪti/','noun','반성성','The researcher''s awareness of their influence on the study.','Demonstrate {reflexivity} by acknowledging your own biases.','자신의 편향을 인정함으로써 반성성을 보여주세요.','reflexivity','C1','academic',3,'reflexivity self-awareness mirror research'),
('w_academic_C1_12','epistemological','/ɪˌpɪstɪməˈlɒdʒɪkəl/','adjective','인식론적인','Relating to the theory of knowledge.','State your {epistemological} stance in the methodology.','방법론에서 인식론적 입장을 밝히세요.','epistemological','C1','academic',3,'epistemology knowledge philosophy'),
('w_academic_C1_13','ontological','/ˌɒntəˈlɒdʒɪkəl/','adjective','존재론적인','Relating to the nature of reality and existence.','Make your {ontological} assumptions explicit.','존재론적 가정을 명시적으로 밝히세요.','ontological','C1','academic',3,'ontology reality existence abstract'),
('w_academic_C1_14','dialectical','/ˌdaɪəˈlɛktɪkəl/','adjective','변증법적인','Relating to the resolution of opposing ideas or forces.','A {dialectical} analysis weighs competing viewpoints.','변증법적 분석은 경쟁하는 관점들을 따져봐요.','dialectical','C1','academic',3,'dialectic thesis antithesis synthesis'),
('w_academic_C1_15','normative','/ˈnɔːrmətɪv/','adjective','규범적인','Relating to an ideal standard or model.','The paper takes a {normative} stance on justice.','그 논문은 정의에 대해 규범적 입장을 취해요.','normative','C1','academic',3,'normative standard rule society'),
('w_academic_C1_16','empiricism','/ɪmˈpɪrɪsɪzəm/','noun','경험론','The doctrine that knowledge comes primarily from sensory experience.','Locke''s {empiricism} rejected innate ideas.','로크의 경험론은 선천적 관념을 거부했어요.','empiricism','C1','academic',3,'empiricism observation senses philosophy'),
('w_academic_C1_17','rationalism','/ˈræʃənəlɪzəm/','noun','합리론','The theory that reason rather than experience is the source of knowledge.','Descartes exemplified {rationalism} in philosophy.','데카르트는 철학에서 합리론을 예시했어요.','rationalism','C1','academic',3,'rationalism reason logic Descartes'),
('w_academic_C1_18','heuristic','/hjʊˈrɪstɪk/','adjective','발견적인','Enabling discovery or problem-solving through experience.','A {heuristic} approach helps in exploratory studies.','발견적 접근법은 탐색적 연구에 도움이 돼요.','heuristic','C1','academic',3,'heuristic discovery trial method'),
('w_academic_C1_19','reductionism','/rɪˈdʌkʃənɪzəm/','noun','환원주의','Explaining complex things by reducing them to simpler parts.','Critics argue that {reductionism} oversimplifies human behaviour.','비평가들은 환원주의가 인간 행동을 지나치게 단순화한다고 주장해요.','reductionism','C1','academic',3,'reductionism parts whole simplify'),
('w_academic_C1_20','holism','/ˈhoʊlɪzəm/','noun','전체론','The view that systems are more than the sum of their parts.','{Holism} argues for studying the whole context.','전체론은 전체적인 맥락 연구를 주장해요.','Holism','C1','academic',3,'holism whole system interconnected'),
('w_academic_C1_21','agency','/ˈeɪdʒənsi/','noun','행위성','The capacity of individuals to act independently.','The study examines {agency} in marginalized communities.','그 연구는 소외된 공동체의 행위성을 조사해요.','agency','C1','academic',3,'agency power individual action'),
('w_academic_C1_22','hegemony','/hɪˈdʒɛməni/','noun','헤게모니','Dominance of one group over others in society.','Gramsci''s concept of {hegemony} remains influential.','그람시의 헤게모니 개념은 여전히 영향력이 있어요.','hegemony','C1','academic',3,'hegemony power structure dominance'),
('w_academic_C1_23','ideology','/ˌaɪdiˈɒlədʒi/','noun','이데올로기','A system of ideas forming the basis of social or economic theory.','The text reproduces a neoliberal {ideology}.','그 텍스트는 신자유주의적 이데올로기를 재생산해요.','ideology','C1','academic',3,'ideology belief system political'),
('w_academic_C1_24','discursive','/dɪˈskɜːrsɪv/','adjective','담론적인','Relating to discourse and the structures of language and power.','Use {discursive} analysis to examine power relations.','권력 관계를 조사하기 위해 담론 분석을 사용하세요.','discursive','C1','academic',3,'discourse analysis text language'),
('w_academic_C1_25','critical theory','/ˈkrɪtɪkəl ˈθɪəri/','noun','비판 이론','A social philosophy opposing oppressive social structures.','{Critical theory} challenges taken-for-granted assumptions.','비판 이론은 당연하게 여겨지는 가정에 도전해요.','Critical theory','C1','academic',3,'critical theory society power analysis'),
('w_academic_C1_26','positionality','/pəˌzɪʃəˈnælɪti/','noun','위치성','The researcher''s social and political identity affecting research.','Discuss your {positionality} in the methodology section.','방법론 섹션에서 위치성을 논의하세요.','positionality','C1','academic',3,'positionality researcher identity'),
('w_academic_C1_27','transferability','/trænsˌfɜːrəˈbɪlɪti/','noun','전이 가능성','The degree to which findings apply to other contexts.','Thick description enhances {transferability}.','두꺼운 묘사는 전이 가능성을 높여요.','transferability','C1','academic',3,'transferability context research'),
('w_academic_C1_28','credibility','/ˌkrɛdɪˈbɪlɪti/','noun','신뢰 가능성','The trustworthiness of qualitative research findings.','Member checking enhances {credibility}.','구성원 확인 절차는 신뢰 가능성을 높여요.','credibility','C1','academic',3,'credibility trust research validation'),
('w_academic_C1_29','confirmability','/kənˌfɜːrməˈbɪlɪti/','noun','확인 가능성','The degree to which findings are shaped by participants, not the researcher.','An audit trail supports {confirmability}.','감사 추적은 확인 가능성을 뒷받침해요.','confirmability','C1','academic',3,'audit trail research transparency'),
('w_academic_C1_30','dependability','/dɪˌpɛndəˈbɪlɪti/','noun','신빙성','The stability of findings over time in qualitative research.','Peer debriefing strengthens {dependability}.','동료 논의는 신빙성을 강화해요.','dependability','C1','academic',3,'dependability stability qualitative research'),
('w_academic_C1_31','thick description','/θɪk dɪˈskrɪpʃən/','noun','두꺼운 묘사','Rich, detailed contextual description of a research setting.','Geertz called for {thick description} in ethnography.','기어츠는 문화기술지에서 두꺼운 묘사를 요구했어요.','thick description','C1','academic',3,'thick description ethnography context'),
('w_academic_C1_32','saturation','/ˌsætʃəˈreɪʃən/','noun','포화 (데이터)','The point where no new themes emerge from data.','Data collection stopped upon reaching {saturation}.','포화 상태에 도달하자 데이터 수집을 중단했어요.','saturation','C1','academic',3,'data saturation qualitative theme'),
('w_academic_C1_33','grounded theory','/ˈɡraʊndɪd ˈθɪəri/','noun','근거이론','A qualitative methodology generating theory from data.','She used {grounded theory} to study patient experiences.','그녀는 환자 경험을 연구하기 위해 근거이론을 사용했어요.','grounded theory','C1','academic',3,'grounded theory data qualitative coding'),
('w_academic_C1_34','ethnography','/ɛθˈnɒɡrəfi/','noun','문화기술지','The scientific description of peoples and cultures.','He conducted {ethnography} in a rural community.','그는 농촌 공동체에서 문화기술지 연구를 수행했어요.','ethnography','C1','academic',3,'ethnography fieldwork culture community'),
('w_academic_C1_35','narrative inquiry','/ˈnærətɪv ˈɪŋkwaɪri/','noun','서사 탐구','Research based on stories of lived experience.','{Narrative inquiry} centred on teachers'' life histories.','서사 탐구는 교사들의 생애사를 중심으로 했어요.','Narrative inquiry','C1','academic',3,'narrative story inquiry research');

-- ══════════════════════════════════════════════════════════════════════════════
-- WORDS — C2 (35개)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_academic_C2_01','deconstruction','/ˌdiːkənˈstrʌkʃən/','noun','해체 (철학)','A critical method that exposes hidden assumptions in texts.','Derrida''s {deconstruction} challenges fixed meanings.','데리다의 해체는 고정된 의미에 도전해요.','deconstruction','C2','academic',4,'deconstruction text layers meaning'),
('w_academic_C2_02','logocentrism','/ˌloʊɡoʊˈsɛntrɪzəm/','noun','로고중심주의','The privileging of speech over writing in Western thought.','Derrida critiqued {logocentrism} in Western philosophy.','데리다는 서양 철학의 로고중심주의를 비판했어요.','logocentrism','C2','academic',4,'logocentrism word speech center Derrida'),
('w_academic_C2_03','différance','/ˌdɪfɪˈrɑːns/','noun','차연','Derrida''s term for the endless deferral of meaning in language.','The concept of {différance} resists fixed definitions.','차연의 개념은 고정된 정의에 저항해요.','différance','C2','academic',4,'différance Derrida language meaning'),
('w_academic_C2_04','praxis','/ˈpræksɪs/','noun','프락시스','The practice and practical application of a theory.','Freire''s pedagogy unites theory and {praxis}.','프레이리의 교육학은 이론과 프락시스를 결합해요.','praxis','C2','academic',4,'praxis practice theory action'),
('w_academic_C2_05','intersubjectivity','/ˌɪntərsəbdʒɛkˈtɪvɪti/','noun','상호주관성','The shared understanding between two or more subjects.','Knowledge emerges through {intersubjectivity} in dialogue.','지식은 대화에서 상호주관성을 통해 생성돼요.','intersubjectivity','C2','academic',4,'intersubjectivity dialogue shared understanding'),
('w_academic_C2_06','rhizome','/ˈraɪzoʊm/','noun','리좀 (철학)','Deleuze and Guattari''s metaphor for non-hierarchical knowledge structures.','The internet resembles a {rhizome} more than a tree.','인터넷은 나무보다 리좀에 더 가까워요.','rhizome','C2','academic',4,'rhizome network philosophy Deleuze'),
('w_academic_C2_07','bricolage','/ˌbrɪkəˈlɑːʒ/','noun','브리콜라주','Using whatever tools and methods are available to solve a problem.','Lévi-Strauss used {bricolage} to describe mythological thinking.','레비스트로스는 신화적 사고를 설명하기 위해 브리콜라주를 사용했어요.','bricolage','C2','academic',4,'bricolage mixed methods tools research'),
('w_academic_C2_08','heteroglossia','/ˌhɛtərəˈɡlɒsiə/','noun','이종언어성','Bakhtin''s term for the diversity of social speech types.','The novel exemplifies {heteroglossia} through its many voices.','그 소설은 다양한 목소리를 통해 이종언어성을 예시해요.','heteroglossia','C2','academic',4,'heteroglossia Bakhtin voice language'),
('w_academic_C2_09','aporia','/əˈpɔːriə/','noun','아포리아 (해결 불가능한 난제)','A philosophical puzzle or state of being at a loss.','The essay reaches an {aporia} it cannot resolve.','그 에세이는 해결할 수 없는 아포리아에 이르러요.','aporia','C2','academic',4,'aporia paradox unsolvable puzzle'),
('w_academic_C2_10','episteme','/ɛˈpɪstəmiː/','noun','에피스테메 (지식 체계)','Foucault''s term for the dominant knowledge structures of an era.','The Enlightenment created a new {episteme}.','계몽주의는 새로운 에피스테메를 창조했어요.','episteme','C2','academic',4,'episteme Foucault knowledge era'),
('w_academic_C2_11','genealogy','/ˌdʒɛniˈælədʒi/','noun','계보학 (푸코적 의미)','Foucault''s method tracing the historical formation of concepts.','The paper uses Foucauldian {genealogy} to study madness.','그 논문은 광기를 연구하기 위해 푸코적 계보학을 사용해요.','genealogy','C2','academic',4,'genealogy history trace Foucault'),
('w_academic_C2_12','archaeology of knowledge','/ˌɑːrkiˈɒlədʒi əv ˈnɒlɪdʒ/','noun','지식의 고고학','Foucault''s method for uncovering historical conditions of knowledge.','The {archaeology of knowledge} reveals hidden rules of discourse.','지식의 고고학은 담론의 숨겨진 규칙을 드러내요.','archaeology of knowledge','C2','academic',4,'archaeology knowledge Foucault history'),
('w_academic_C2_13','simulacrum','/ˌsɪmjʊˈleɪkrəm/','noun','시뮬라크르','Baudrillard''s term for a copy without an original.','Baudrillard argues that media produces {simulacra}.','보드리야르는 미디어가 시뮬라크르를 생산한다고 주장해요.','simulacra','C2','academic',4,'simulacrum copy image Baudrillard'),
('w_academic_C2_14','hyperreality','/ˌhaɪpərˈriːæləti/','noun','초현실','A condition where the simulation replaces reality.','Disneyland is Baudrillard''s model of {hyperreality}.','디즈니랜드는 보드리야르의 초현실 모델이에요.','hyperreality','C2','academic',4,'hyperreality simulation media Baudrillard'),
('w_academic_C2_15','subaltern','/ˈsʌbəltərn/','noun','서발턴','Spivak''s term for marginalized groups excluded from power structures.','The paper asks: can the {subaltern} speak?','그 논문은 서발턴이 말할 수 있는가를 묻는 에세이예요.','subaltern','C2','academic',4,'subaltern marginalized voice power'),
('w_academic_C2_16','liminality','/ˌlɪmɪˈnælɪti/','noun','경계성','The transitional state between two distinct phases or categories.','Immigrants often live in a state of {liminality}.','이민자들은 종종 경계성의 상태에서 살아가요.','liminality','C2','academic',4,'liminality threshold transition boundary'),
('w_academic_C2_17','performativity','/pərˌfɔːrmæˈtɪvɪti/','noun','수행성','Butler''s concept that identity is enacted through repeated actions.','Gender is understood through {performativity}.','성별은 수행성을 통해 이해돼요.','performativity','C2','academic',4,'performativity Butler gender identity'),
('w_academic_C2_18','interpellation','/ɪnˌtɜːrpəˈleɪʃən/','noun','호명','Althusser''s concept of ideology calling subjects into being.','{Interpellation} explains how ideology shapes identity.','호명은 이데올로기가 정체성을 어떻게 형성하는지를 설명해요.','Interpellation','C2','academic',4,'interpellation Althusser ideology subject'),
('w_academic_C2_19','intertextuality','/ˌɪntərtɛkstʃuˈælɪti/','noun','상호텍스트성','The relationship between texts and how they reference each other.','The novel is rich in {intertextuality} with classical texts.','그 소설은 고전 텍스트와의 상호텍스트성이 풍부해요.','intertextuality','C2','academic',4,'intertextuality texts references connections'),
('w_academic_C2_20','polysemy','/pɒˈlɪsɪmi/','noun','다의성','The coexistence of many possible meanings in a single word or phrase.','The {polysemy} of "culture" complicates its definition.','문화의 다의성은 그 정의를 복잡하게 만들어요.','polysemy','C2','academic',4,'polysemy word meaning language'),
('w_academic_C2_21','semiosis','/ˌsiːmiˈoʊsɪs/','noun','기호 작용','The process by which signs and meanings are produced.','Peirce''s theory of {semiosis} has three elements.','퍼스의 기호 작용 이론에는 세 가지 요소가 있어요.','semiosis','C2','academic',4,'semiosis sign meaning Peirce'),
('w_academic_C2_22','discourse formation','/ˈdɪskɔːrs fɔːrˈmeɪʃən/','noun','담론 형성','A group of statements that constitute a domain of knowledge.','A {discourse formation} governs what can be said.','담론 형성은 무엇을 말할 수 있는지를 지배해요.','discourse formation','C2','academic',4,'discourse formation Foucault rules'),
('w_academic_C2_23','biopolitics','/ˌbaɪoʊˈpɒlɪtɪks/','noun','생명정치','Foucault''s concept of the regulation of life by state power.','{Biopolitics} governs populations through health policy.','생명정치는 보건 정책을 통해 인구를 통제해요.','Biopolitics','C2','academic',4,'biopolitics power life regulation'),
('w_academic_C2_24','alterity','/ɔːlˈtɛrɪti/','noun','타자성','The state of being other or different; otherness.','Levinas placed {alterity} at the centre of ethics.','레비나스는 타자성을 윤리의 중심에 두었어요.','alterity','C2','academic',4,'alterity other difference philosophy'),
('w_academic_C2_25','phenomenological reduction','/fɪˌnɒmɪnəˈlɒdʒɪkəl rɪˈdʌkʃən/','noun','현상학적 환원','Husserl''s method of suspending assumptions to examine pure experience.','Apply {phenomenological reduction} to focus on raw experience.','순수한 경험에 집중하기 위해 현상학적 환원을 적용하세요.','phenomenological reduction','C2','academic',4,'phenomenology reduction Husserl experience'),
('w_academic_C2_26','metacognition','/ˌmɛtəkɒɡˈnɪʃən/','noun','메타인지','Awareness and understanding of one''s own thought processes.','Good learners exercise strong {metacognition}.','훌륭한 학습자는 강한 메타인지를 발휘해요.','metacognition','C2','academic',3,'metacognition thinking about thinking brain'),
('w_academic_C2_27','epistemological rupture','/ɪˌpɪstɪməˈlɒdʒɪkəl ˈrʌptʃər/','noun','인식론적 단절','Bachelard''s term for a radical break in how knowledge is understood.','Bachelard described scientific progress as an {epistemological rupture}.','바슐라르는 과학적 진보를 인식론적 단절로 묘사했어요.','epistemological rupture','C2','academic',4,'rupture break knowledge paradigm shift'),
('w_academic_C2_28','dialectics of enlightenment','/daɪəˈlɛktɪks əv ɪnˈlaɪtənmənt/','noun','계몽의 변증법','Adorno and Horkheimer''s critique of rationality turning into domination.','The {dialectics of enlightenment} reveals reason''s dark side.','계몽의 변증법은 이성의 어두운 면을 드러내요.','dialectics of enlightenment','C2','academic',4,'dialectics enlightenment critique reason'),
('w_academic_C2_29','communicative rationality','/kəˌmjuːnɪkətɪv ˌræʃəˈnælɪti/','noun','의사소통적 합리성','Habermas''s theory of reason grounded in mutual understanding through dialogue.','{Communicative rationality} underpins democratic discourse.','의사소통적 합리성은 민주적 담론의 기반이 돼요.','Communicative rationality','C2','academic',4,'communicative rationality Habermas dialogue'),
('w_academic_C2_30','trace','/treɪs/','noun','흔적 (데리다)','Derrida''s term for the mark of an absent other that shapes meaning.','Every sign carries the {trace} of what it excludes.','모든 기호는 자신이 배제하는 것의 흔적을 담고 있어요.','trace','C2','academic',4,'trace Derrida absence mark meaning'),
('w_academic_C2_31','supplement','/ˈsʌplɪmənt/','noun','보충 (데리다)','Derrida''s concept of an addition that reveals an original lack.','Writing is the {supplement} that destabilises speech.','글쓰기는 말하기를 불안정하게 만드는 보충이에요.','supplement','C2','academic',4,'supplement addition Derrida writing'),
('w_academic_C2_32','hauntology','/hɔːnˈtɒlədʒi/','noun','유령론','Derrida''s term for how the past haunts the present.','Fisher applied {hauntology} to popular culture.','피셔는 대중문화에 유령론을 적용했어요.','hauntology','C2','academic',4,'hauntology Derrida ghost past present'),
('w_academic_C2_33','negative dialectics','/ˈnɛɡətɪv daɪəˈlɛktɪks/','noun','부정 변증법','Adorno''s method refusing any positive synthesis of contradictions.','Adorno''s {negative dialectics} resists reconciliation.','아도르노의 부정 변증법은 화해에 저항해요.','negative dialectics','C2','academic',4,'negative dialectics Adorno contradiction'),
('w_academic_C2_34','spectral','/ˈspɛktrəl/','adjective','유령적인','Relating to or resembling a ghost; present yet absent.','The {spectral} traces of colonialism persist today.','식민주의의 유령적 흔적이 오늘날에도 지속돼요.','spectral','C2','academic',4,'spectral ghost trace colonialism'),
('w_academic_C2_35','non-representational','/nɒn ˌrɛprɪzɛnˈteɪʃənəl/','adjective','비표상적인','Relating to theories that focus on practices rather than meanings.','Thrift advocated a {non-representational} geography.','스리프트는 비표상적 지리학을 주창했어요.','non-representational','C2','academic',4,'non-representational theory practice geography');

-- ══════════════════════════════════════════════════════════════════════════════
-- PATTERNS — A1 (7개) — 수업 중 표현
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_academic_A1_01','Can you explain that again?','다시 설명해 주실 수 있나요?','explain that again','이해 못했을 때 정중하게 다시 설명을 요청하는 표현이에요. "once more"를 덧붙이면 더 자연스러워요.','수업 중','A1','academic','pattern',NULL,1),
('s_academic_A1_02','How do you spell that?','그거 철자가 어떻게 되나요?','How do you spell','새 단어를 들었을 때 철자를 확인하는 가장 기본적인 표현이에요.','수업 중','A1','academic','pattern',NULL,2),
('s_academic_A1_03','What does this word mean?','이 단어는 무슨 뜻이에요?','What does ... mean','모르는 단어를 물어볼 때 필수 패턴이에요. "this" 자리에 원하는 단어를 넣으세요.','수업 중','A1','academic','pattern',NULL,3),
('s_academic_A1_04','Can you say that more slowly, please?','좀 더 천천히 말씀해 주실 수 있나요?','more slowly','말하는 속도가 빠를 때 정중하게 늦춰달라고 요청하는 표현이에요.','수업 중','A1','academic','pattern',NULL,4),
('s_academic_A1_05','Is this right?','이게 맞나요?','Is this right','자신의 답이 맞는지 확인할 때 쓰는 간단한 표현이에요.','수업 중','A1','academic','pattern',NULL,5),
('s_academic_A1_06','I don''t understand. Can you help me?','이해가 안 돼요. 도와주실 수 있나요?','I don''t understand','어려움을 솔직하게 표현하고 도움을 요청하는 패턴이에요. 수업 중 언제든 쓸 수 있어요.','수업 중','A1','academic','pattern',NULL,6),
('s_academic_A1_07','Can I have more time, please?','시간을 좀 더 주실 수 있나요?','Can I have more time','시험이나 과제에서 추가 시간을 요청할 때 쓰는 공손한 표현이에요.','수업 중','A1','academic','pattern',NULL,7);

-- ══════════════════════════════════════════════════════════════════════════════
-- PATTERNS — A2 (7개) — 질문·이해
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_academic_A2_01','Could you give me an example of that?','그것에 대한 예시를 들어주실 수 있나요?','give me an example','추상적인 개념을 이해하기 위해 예시를 요청할 때 쓰는 표현이에요.','수업·강의','A2','academic','pattern',NULL,1),
('s_academic_A2_02','What is the difference between A and B?','A와 B의 차이점이 무엇인가요?','the difference between','두 개념을 구분할 때 쓰는 핵심 질문 패턴이에요. between 다음에 두 단어를 넣으세요.','수업·강의','A2','academic','pattern',NULL,2),
('s_academic_A2_03','I think I understand, but could you check my answer?','이해한 것 같은데, 제 답을 확인해 주실 수 있나요?','could you check my answer','자신의 이해를 점검받을 때 쓰는 표현이에요. "I think I understand, but..."으로 겸손하게 시작해요.','수업·강의','A2','academic','pattern',NULL,3),
('s_academic_A2_04','In other words, you mean...?','다시 말하면, ...이라는 뜻인가요?','In other words','상대방의 말을 자신의 언어로 확인할 때 쓰는 패턴이에요. 이해를 확인하는 데 아주 유용해요.','수업·강의','A2','academic','pattern',NULL,4),
('s_academic_A2_05','What is this topic about?','이 주제는 어떤 내용인가요?','What is this topic about','처음 보는 주제나 텍스트의 내용을 물어볼 때 쓰는 기본 질문이에요.','수업·강의','A2','academic','pattern',NULL,5),
('s_academic_A2_06','Can you repeat the question, please?','질문을 다시 한 번 말씀해 주실 수 있나요?','repeat the question','질문을 잘 못 들었을 때 다시 요청하는 정중한 표현이에요.','수업·강의','A2','academic','pattern',NULL,6),
('s_academic_A2_07','What are the main points of this chapter?','이 챕터의 주요 내용이 무엇인가요?','the main points','챕터나 텍스트의 핵심을 요약해달라고 요청할 때 쓰는 표현이에요.','수업·강의','A2','academic','pattern',NULL,7);

-- ══════════════════════════════════════════════════════════════════════════════
-- PATTERNS — B1 (7개) — 논거 제시
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_academic_B1_01','According to the evidence, we can conclude that...','근거에 따르면, ...라고 결론지을 수 있어요.','According to the evidence','결론을 제시할 때 근거를 먼저 언급하는 학술적 표현이에요. 논문과 발표 모두에서 자주 써요.','발표·토론','B1','academic','pattern',NULL,1),
('s_academic_B1_02','This supports the hypothesis that...','이것은 ...라는 가설을 뒷받침해요.','supports the hypothesis','연구 결과와 가설을 연결할 때 쓰는 핵심 학술 표현이에요.','발표·논문','B1','academic','pattern',NULL,2),
('s_academic_B1_03','On the other hand, some researchers argue that...','반면에, 일부 연구자들은 ...라고 주장해요.','On the other hand','반론을 소개할 때 쓰는 균형 잡힌 표현이에요. 비판적 글쓰기의 필수 패턴이에요.','발표·논문','B1','academic','pattern',NULL,3),
('s_academic_B1_04','The data suggests that there is a correlation between A and B.','데이터는 A와 B 사이에 상관관계가 있음을 시사해요.','suggests that there is a correlation','상관관계를 언급할 때 쓰는 표현이에요. "suggests"는 인과관계를 단정하지 않아 학술적으로 안전해요.','연구 발표','B1','academic','pattern',NULL,4),
('s_academic_B1_05','To illustrate this point, consider the following example.','이 요점을 설명하기 위해 다음 예시를 살펴봐요.','To illustrate this point','논거를 예시로 뒷받침할 때 쓰는 전환 표현이에요.','발표·논문','B1','academic','pattern',NULL,5),
('s_academic_B1_06','One limitation of this study is the small sample size.','이 연구의 한 가지 한계는 작은 표본 크기예요.','One limitation of this study','연구의 약점을 솔직하게 인정하는 학술적 표현이에요. 이런 표현이 논문의 신뢰도를 높여요.','논문·보고서','B1','academic','pattern',NULL,6),
('s_academic_B1_07','These findings suggest that further research is needed.','이 결과들은 추가 연구가 필요함을 시사해요.','further research is needed','연구의 후속 과제를 제안할 때 쓰는 클리셰지만 필수적인 표현이에요.','논문·보고서','B1','academic','pattern',NULL,7);

-- ══════════════════════════════════════════════════════════════════════════════
-- PATTERNS — B2 (7개) — 연구 방법
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_academic_B2_01','A mixed-methods approach was adopted to triangulate the findings.','결과를 삼각 검증하기 위해 혼합 방법 접근법을 채택했어요.','triangulate the findings','혼합 방법 연구에서 신뢰도를 설명할 때 쓰는 표현이에요. "triangulate"는 복수의 방법으로 결과를 확인한다는 뜻이에요.','방법론 서술','B2','academic','pattern',NULL,1),
('s_academic_B2_02','Semi-structured interviews were conducted with twenty participants.','20명의 참가자를 대상으로 반구조화 인터뷰를 실시했어요.','Semi-structured interviews were conducted','질적 연구 방법을 설명하는 전형적인 수동태 표현이에요. 학술 논문에서 자주 등장해요.','방법론 서술','B2','academic','pattern',NULL,2),
('s_academic_B2_03','The sample was selected using purposive sampling.','표본은 목적 표집을 사용하여 선정되었어요.','purposive sampling','특정 기준으로 참가자를 선정할 때 쓰는 표현이에요. 질적 연구의 대표적인 표집 방법이에요.','방법론 서술','B2','academic','pattern',NULL,3),
('s_academic_B2_04','Thematic analysis was used to identify patterns in the data.','데이터에서 패턴을 확인하기 위해 주제 분석을 사용했어요.','Thematic analysis was used','질적 데이터 분석 방법을 설명할 때 쓰는 표현이에요. Braun & Clarke의 6단계 방법이 기준이에요.','방법론 서술','B2','academic','pattern',NULL,4),
('s_thematic_B2_05','The validity and reliability of the instrument were established through pilot testing.','도구의 타당성과 신뢰성은 파일럿 테스트를 통해 확보되었어요.','validity and reliability','연구 도구의 질을 설명할 때 쓰는 표현이에요. 양적 연구에서는 이 두 개념이 필수예요.','방법론 서술','B2','academic','pattern',NULL,5),
('s_academic_B2_06','Informed consent was obtained from all participants prior to data collection.','데이터 수집 전 모든 참가자로부터 충분한 설명을 들은 동의를 받았어요.','Informed consent was obtained','윤리적 절차를 기술할 때 반드시 포함해야 하는 표현이에요.','방법론·윤리','B2','academic','pattern',NULL,6),
('s_academic_B2_07','The findings cannot be generalised beyond the specific context of this study.','이 결과들은 본 연구의 특정 맥락 너머로 일반화될 수 없어요.','cannot be generalised beyond','연구 한계를 명시하는 표현이에요. 질적 연구의 한계를 솔직하게 인정하는 것이 오히려 신뢰도를 높여요.','논문·토론','B2','academic','pattern',NULL,7);

-- ══════════════════════════════════════════════════════════════════════════════
-- PATTERNS — C1 (7개) — 학술 토론
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_academic_C1_01','This argument rests on an epistemological assumption that merits scrutiny.','이 논거는 면밀한 검토가 필요한 인식론적 가정에 기반을 두고 있어요.','epistemological assumption that merits scrutiny','학술 토론에서 상대방의 전제를 분석적으로 지적할 때 쓰는 고급 표현이에요.','학술 토론','C1','academic','pattern',NULL,1),
('s_academic_C1_02','The ontological stance adopted here is broadly interpretivist.','여기서 채택된 존재론적 입장은 대체로 해석주의적이에요.','ontological stance ... interpretivist','방법론 챕터에서 연구자의 철학적 입장을 밝힐 때 쓰는 표현이에요.','논문 서술','C1','academic','pattern',NULL,2),
('s_academic_C1_03','Drawing on a constructivist framework, this study examines how meaning is socially negotiated.','구성주의적 틀을 바탕으로, 본 연구는 의미가 어떻게 사회적으로 협상되는지를 검토해요.','Drawing on a constructivist framework','이론적 틀을 소개할 때 쓰는 전형적인 학술 표현이에요. "Drawing on"으로 시작하면 세련된 느낌을 줘요.','논문 서술','C1','academic','pattern',NULL,3),
('s_academic_C1_04','The reflexivity of the researcher is acknowledged as a potential source of bias.','연구자의 반성성은 편향의 잠재적 원인으로 인정돼요.','reflexivity of the researcher','질적 연구에서 연구자의 영향을 투명하게 밝히는 표현이에요. 요즘 학술 논문에서 거의 필수예요.','논문 서술','C1','academic','pattern',NULL,4),
('s_academic_C1_05','The theoretical saturation was reached after the twelfth interview.','열두 번째 인터뷰 이후 이론적 포화 상태에 도달했어요.','theoretical saturation was reached','질적 연구에서 데이터 수집을 중단한 근거를 설명하는 표현이에요.','논문 서술','C1','academic','pattern',NULL,5),
('s_academic_C1_06','A dialectical tension exists between agency and structure in this context.','이 맥락에서 행위성과 구조 사이에 변증법적 긴장이 존재해요.','dialectical tension exists between','사회과학에서 두 개념 간의 갈등을 논할 때 쓰는 고급 표현이에요.','학술 토론','C1','academic','pattern',NULL,6),
('s_academic_C1_07','The credibility of the findings was enhanced through member checking and peer debriefing.','결과의 신뢰 가능성은 구성원 확인과 동료 논의를 통해 강화되었어요.','credibility of the findings was enhanced','질적 연구의 엄밀성을 설명할 때 쓰는 표현이에요. Lincoln & Guba의 기준에서 나온 표현이에요.','논문 서술','C1','academic','pattern',NULL,7);

-- ══════════════════════════════════════════════════════════════════════════════
-- PATTERNS — C2 (7개) — 논문 표현 / 철학적 담론
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_academic_C2_01','Derrida''s notion of différance destabilises the binary opposition between presence and absence.','데리다의 차연 개념은 현존과 부재 사이의 이항 대립을 불안정하게 만들어요.','différance destabilises the binary opposition','해체주의적 분석을 수행할 때 쓰는 전형적인 표현이에요. "destabilise"는 학술 비평에서 자주 사용돼요.','철학 논문','C2','academic','pattern',NULL,1),
('s_academic_C2_02','Foucauldian genealogy traces the conditions of possibility for contemporary discursive formations.','푸코적 계보학은 현대 담론 형성의 가능성 조건을 추적해요.','traces the conditions of possibility','푸코의 방법론을 적용하는 논문에서 쓰는 고급 표현이에요.','철학 논문','C2','academic','pattern',NULL,2),
('s_academic_C2_03','The subaltern''s capacity to speak is foreclosed by the very structures that constitute discourse.','서발턴의 발언 능력은 담론을 구성하는 바로 그 구조에 의해 봉쇄돼요.','foreclosed by the very structures','스피박의 "서발턴은 말할 수 있는가"를 논의할 때 쓰는 표현이에요. "foreclose"는 가능성을 닫는다는 뜻이에요.','철학 논문','C2','academic','pattern',NULL,3),
('s_academic_C2_04','Butler''s theory of performativity reconceptualises identity as an iterative enactment rather than an essence.','버틀러의 수행성 이론은 정체성을 본질이 아닌 반복적 실천으로 재개념화해요.','reconceptualises identity as an iterative enactment','수행성 이론을 설명할 때 쓰는 핵심 표현이에요. "iterative enactment"는 반복 행위를 뜻해요.','철학 논문','C2','academic','pattern',NULL,4),
('s_academic_C2_05','The text is haunted by the spectral traces of a colonial past it can neither acknowledge nor escape.','그 텍스트는 인정할 수도 피할 수도 없는 식민지 과거의 유령적 흔적에 시달려요.','haunted by the spectral traces','유령론(hauntology)적 비평을 적용할 때 쓰는 표현이에요. 포스트식민 연구에서 자주 쓰여요.','문학·비평','C2','academic','pattern',NULL,5),
('s_academic_C2_06','This analysis foregrounds the aporia inherent in any attempt to fix meaning.','이 분석은 의미를 고정하려는 모든 시도에 내재된 아포리아를 전면에 내세워요.','foregrounds the aporia inherent in','해체주의 비평에서 텍스트의 내적 모순을 지적할 때 쓰는 표현이에요. "foreground"는 주목하다는 뜻이에요.','철학 논문','C2','academic','pattern',NULL,6),
('s_academic_C2_07','The rhizomatic structure of the argument resists any singular or hierarchical reading.','그 논거의 리좀적 구조는 단일하거나 위계적인 독해에 저항해요.','rhizomatic structure resists any singular or hierarchical reading','들뢰즈와 가타리의 리좀 개념을 적용할 때 쓰는 표현이에요. "rhizomatic"은 비위계적이고 다방향적인 구조를 뜻해요.','철학 논문','C2','academic','pattern',NULL,7);
