-- EngCat Idioms — ex3/ex4/ex5 backfill (hand-written)
-- 345 rows × 3 examples (en + ko), with COALESCE to preserve existing ex3
-- Style: natural B1-B2 English, polite Korean (해요/입니다)
-- Run once in Supabase SQL Editor

-- ══════════════════════════════════════
-- GREETING
-- ══════════════════════════════════════
UPDATE idioms SET ex3 = COALESCE(ex3, 'She smiled and introduced herself to break the ice.'), ex3_ko = COALESCE(ex3_ko, '그녀는 미소를 지으며 자기소개를 해서 어색한 분위기를 깼어요.'), ex4 = 'He brought snacks to break the ice on the team retreat.', ex4_ko = '그는 팀 워크숍에서 어색한 분위기를 깨기 위해 간식을 가져왔어요.', ex5 = 'A simple question can break the ice with strangers on a flight.', ex5_ko = '간단한 질문 하나가 비행기에서 낯선 사람과의 어색한 분위기를 깰 수 있어요.' WHERE id = 'idm_greeting_01';
UPDATE idioms SET ex3 = COALESCE(ex3, 'She warmed up to her new neighbors over a few weekend chats.'), ex3_ko = COALESCE(ex3_ko, '그녀는 주말 몇 번의 대화를 통해 새 이웃들과 친해졌어요.'), ex4 = 'He slowly warmed up to his stepfather over the years.', ex4_ko = '그는 몇 년에 걸쳐 새아버지와 천천히 친해졌어요.', ex5 = 'My cat finally warmed up to my partner after a month.', ex5_ko = '저희 고양이는 한 달 만에 마침내 제 파트너와 친해졌어요.' WHERE id = 'idm_greeting_02';
UPDATE idioms SET ex3 = COALESCE(ex3, 'She made every visitor feel at home with a cup of tea.'), ex3_ko = COALESCE(ex3_ko, '그녀는 차 한 잔으로 모든 방문객을 편안하게 해줬어요.'), ex4 = 'He made his shy guests feel at home with gentle humor.', ex4_ko = '그는 부드러운 유머로 부끄러워하는 손님들을 편안하게 해줬어요.', ex5 = 'A good host knows how to make people feel at home immediately.', ex5_ko = '좋은 호스트는 사람들을 즉시 편안하게 해주는 법을 알아요.' WHERE id = 'idm_greeting_03';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I knew we''d hit it off — we have so much in common.'), ex3_ko = COALESCE(ex3_ko, '우리가 금세 친해질 거라고 알았어요 — 공통점이 너무 많거든요.'), ex4 = 'My parents hit it off with my partner''s family right away.', ex4_ko = '저희 부모님은 제 파트너의 가족과 바로 친해지셨어요.', ex5 = 'They hit it off through a shared love of old movies.', ex5_ko = '그들은 옛 영화에 대한 공통된 사랑으로 금세 친해졌어요.' WHERE id = 'idm_greeting_04';
UPDATE idioms SET ex3 = COALESCE(ex3, 'They got on like a house on fire during the road trip.'), ex3_ko = COALESCE(ex3_ko, '그들은 자동차 여행 동안 아주 잘 지냈어요.'), ex4 = 'Our dogs got on like a house on fire from the moment they met.', ex4_ko = '저희 개들은 만나자마자 아주 잘 지냈어요.', ex5 = 'The two old friends still get on like a house on fire.', ex5_ko = '그 두 오랜 친구는 여전히 아주 잘 지내요.' WHERE id = 'idm_greeting_05';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I put my foot in my mouth when I mentioned the surprise party.'), ex3_ko = COALESCE(ex3_ko, '깜짝 파티를 언급해서 실언을 했어요.'), ex4 = 'She put her foot in her mouth by asking about his recent divorce.', ex4_ko = '그녀는 그의 최근 이혼에 대해 물어서 실언을 했어요.', ex5 = 'I keep putting my foot in my mouth at networking events.', ex5_ko = '저는 네트워킹 행사에서 자꾸 실언을 해요.' WHERE id = 'idm_greeting_06';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Within a week of working together, we were on first-name terms.'), ex3_ko = COALESCE(ex3_ko, '함께 일한 지 일주일 만에 우리는 이름을 부르는 사이가 됐어요.'), ex4 = 'They were on first-name terms after just one project.', ex4_ko = '단 하나의 프로젝트 후에 그들은 이름을 부르는 사이가 됐어요.', ex5 = 'Some companies are on first-name terms from day one.', ex5_ko = '어떤 회사들은 첫날부터 이름을 부르는 사이예요.' WHERE id = 'idm_greeting_07';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I know the librarian by sight from picking up my hold books.'), ex3_ko = COALESCE(ex3_ko, '저는 예약 도서를 받으러 다니면서 사서를 얼굴만 알아요.'), ex4 = 'He knows his neighbors by sight but they''ve never chatted.', ex4_ko = '그는 이웃들을 얼굴만 알지만 한 번도 대화한 적이 없어요.', ex5 = 'Many regulars only know each other by sight at the local gym.', ex5_ko = '동네 헬스장의 단골들은 서로 얼굴만 아는 경우가 많아요.' WHERE id = 'idm_greeting_08';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I passed the time of day with the cashier while waiting.'), ex3_ko = COALESCE(ex3_ko, '저는 기다리는 동안 계산원과 가벼운 인사를 나눴어요.'), ex4 = 'They passed the time of day at the dog park every morning.', ex4_ko = '그들은 매일 아침 강아지 공원에서 가벼운 인사를 나눴어요.', ex5 = 'Passing the time of day with strangers feels warmer than texting.', ex5_ko = '낯선 사람과 가벼운 인사를 나누는 게 문자보다 더 따뜻하게 느껴져요.' WHERE id = 'idm_greeting_09';
UPDATE idioms SET ex3 = COALESCE(ex3, 'He''s a familiar face at the bookstore down the street.'), ex3_ko = COALESCE(ex3_ko, '그는 거리 끝 서점에서 낯익은 얼굴이에요.'), ex4 = 'She''s a familiar face at every neighborhood event.', ex4_ko = '그녀는 모든 동네 행사에서 낯익은 얼굴이에요.', ex5 = 'After a year of going to the gym, I became a familiar face there.', ex5_ko = '1년간 헬스장을 다닌 후 저는 그곳의 낯익은 얼굴이 됐어요.' WHERE id = 'idm_greeting_10';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I ran into my college roommate in Tokyo — it''s a small world.'), ex3_ko = COALESCE(ex3_ko, '도쿄에서 대학 룸메이트를 마주쳤어요 — 세상 참 좁아요.'), ex4 = 'She works with my cousin? It really is a small world!', ex4_ko = '그녀가 제 사촌과 일한다고요? 정말 세상 참 좁네요!', ex5 = 'My old neighbor turned out to be my boss — small world.', ex5_ko = '제 옛 이웃이 제 상사로 밝혀졌어요 — 세상 참 좁아요.' WHERE id = 'idm_greeting_11';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Long time no see — you look exactly the same!'), ex3_ko = COALESCE(ex3_ko, '오랜만이에요 — 똑같이 보이세요!'), ex4 = 'We hugged and said "long time no see" at the reunion.', ex4_ko = '우리는 동창회에서 안으며 "오랜만이에요"라고 말했어요.', ex5 = '"Long time no see," he laughed as we met by the elevator.', ex5_ko = '"오랜만이에요," 그는 엘리베이터에서 만나며 웃었어요.' WHERE id = 'idm_greeting_12';
UPDATE idioms SET ex3 = COALESCE(ex3, 'The choir gave the new member a warm welcome.'), ex3_ko = COALESCE(ex3_ko, '합창단은 새 멤버를 따뜻하게 환영했어요.'), ex4 = 'They gave us a warm welcome with handmade signs and snacks.', ex4_ko = '그들은 손으로 만든 사인과 간식으로 우리를 따뜻하게 환영했어요.', ex5 = 'The audience gave the young performer a warm welcome.', ex5_ko = '청중은 어린 공연자를 따뜻하게 환영했어요.' WHERE id = 'idm_greeting_13';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Arriving early helped me get off on the right foot at the new job.'), ex3_ko = COALESCE(ex3_ko, '일찍 도착한 것이 새 직장에서 좋은 출발을 하는 데 도움이 됐어요.'), ex4 = 'They got off on the right foot by sharing their expectations openly.', ex4_ko = '그들은 기대를 솔직하게 공유함으로써 좋은 출발을 했어요.', ex5 = 'Apologizing first helped them get off on the right foot again.', ex5_ko = '먼저 사과한 것이 그들이 다시 좋은 출발을 하는 데 도움이 됐어요.' WHERE id = 'idm_greeting_14';
UPDATE idioms SET ex3 = COALESCE(ex3, 'We promised to keep in touch despite the distance.'), ex3_ko = COALESCE(ex3_ko, '거리에도 불구하고 우리는 연락하며 지내자고 약속했어요.'), ex4 = 'She keeps in touch with her host family through monthly video calls.', ex4_ko = '그녀는 매달 영상 통화로 호스트 가족과 연락하며 지내요.', ex5 = 'It''s hard to keep in touch with friends across time zones.', ex5_ko = '시차를 두고 친구들과 연락하며 지내는 건 어려워요.' WHERE id = 'idm_greeting_15';

-- ══════════════════════════════════════
-- EMOTION
-- ══════════════════════════════════════
UPDATE idioms SET ex3 = COALESCE(ex3, 'She''s been on cloud nine since meeting her new partner.'), ex3_ko = COALESCE(ex3_ko, '새 파트너를 만난 이후로 그녀는 매우 행복해하고 있어요.'), ex4 = 'I was on cloud nine when I got accepted into my dream school.', ex4_ko = '꿈에 그리던 학교에 합격했을 때 저는 매우 행복했어요.', ex5 = 'They''ve been on cloud nine since the baby was born.', ex5_ko = '아기가 태어난 후 그들은 매우 행복해하고 있어요.' WHERE id = 'idm_emotion_01';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I get down in the dumps every February without enough sunshine.'), ex3_ko = COALESCE(ex3_ko, '저는 햇빛이 부족한 매년 2월마다 우울해져요.'), ex4 = 'He was down in the dumps for weeks after his pet passed away.', ex4_ko = '그는 반려동물이 세상을 떠난 후 몇 주간 우울해했어요.', ex5 = 'Talking to friends helps when you''re feeling down in the dumps.', ex5_ko = '우울할 때는 친구들과 이야기하는 것이 도움이 돼요.' WHERE id = 'idm_emotion_02';
UPDATE idioms SET ex3 = COALESCE(ex3, 'After a long week, she was at the end of her rope.'), ex3_ko = COALESCE(ex3_ko, '긴 한 주 끝에 그녀는 더 이상 버티기 힘든 상태였어요.'), ex4 = 'He was at the end of his rope when his car broke down again.', ex4_ko = '차가 또 고장 났을 때 그는 더 이상 버티기 힘들었어요.', ex5 = 'Many parents reach the end of their rope during the holidays.', ex5_ko = '많은 부모들이 휴일 기간에 더 이상 버티기 힘든 상태에 이르러요.' WHERE id = 'idm_emotion_03';
UPDATE idioms SET ex3 = COALESCE(ex3, 'She bit the bullet and made the difficult phone call.'), ex3_ko = COALESCE(ex3_ko, '그녀는 참고 어려운 전화를 걸었어요.'), ex4 = 'I bit the bullet and signed up for a marathon.', ex4_ko = '저는 참고 마라톤에 신청했어요.', ex5 = 'Sometimes you just have to bite the bullet and get started.', ex5_ko = '때로는 그저 참고 시작해야 할 때가 있어요.' WHERE id = 'idm_emotion_04';
UPDATE idioms SET ex3 = COALESCE(ex3, 'She kept a stiff upper lip during the funeral.'), ex3_ko = COALESCE(ex3_ko, '그녀는 장례식 동안 감정을 억제했어요.'), ex4 = 'He kept a stiff upper lip even when he received the bad news.', ex4_ko = '그는 나쁜 소식을 받았을 때도 감정을 억제했어요.', ex5 = 'British culture has traditionally valued keeping a stiff upper lip.', ex5_ko = '영국 문화는 전통적으로 감정을 억제하는 것을 중시해 왔어요.' WHERE id = 'idm_emotion_05';
UPDATE idioms SET ex3 = COALESCE(ex3, 'My grandmother wears her heart on her sleeve and we love her for it.'), ex3_ko = COALESCE(ex3_ko, '저희 할머니는 감정을 숨기지 않으시고 우리는 그런 모습을 사랑해요.'), ex4 = 'He wears his heart on his sleeve and that''s why people trust him.', ex4_ko = '그는 감정을 숨기지 않아서 사람들이 그를 신뢰해요.', ex5 = 'Wearing your heart on your sleeve can be a strength, not a weakness.', ex5_ko = '감정을 솔직하게 드러내는 것은 약점이 아닌 강점이 될 수 있어요.' WHERE id = 'idm_emotion_06';
UPDATE idioms SET ex3 = COALESCE(ex3, 'He had butterflies in his stomach before asking her out.'), ex3_ko = COALESCE(ex3_ko, '그는 그녀에게 데이트를 신청하기 전 너무 긴장했어요.'), ex4 = 'I get butterflies in my stomach before every audition.', ex4_ko = '저는 오디션마다 너무 긴장돼요.', ex5 = 'Even seasoned speakers feel butterflies in their stomach.', ex5_ko = '경험 많은 연사들도 긴장을 느껴요.' WHERE id = 'idm_emotion_07';
UPDATE idioms SET ex3 = COALESCE(ex3, 'She paints in the garage to let off steam after long days.'), ex3_ko = COALESCE(ex3_ko, '그녀는 긴 하루 후 차고에서 그림을 그리며 감정을 발산해요.'), ex4 = 'Sometimes a good cry is all you need to let off steam.', ex4_ko = '때로는 시원하게 우는 것이 감정을 발산하는 데 필요한 전부예요.', ex5 = 'He lets off steam by playing drums in his basement.', ex5_ko = '그는 지하실에서 드럼을 치며 감정을 발산해요.' WHERE id = 'idm_emotion_08';
UPDATE idioms SET ex3 = COALESCE(ex3, 'The kids were in high spirits all morning after their team won.'), ex3_ko = COALESCE(ex3_ko, '팀이 이긴 후 아이들은 아침 내내 기분이 좋았어요.'), ex4 = 'She was in high spirits after the surprise birthday party.', ex4_ko = '깜짝 생일 파티 후 그녀는 기분이 매우 좋았어요.', ex5 = 'Everyone arrived in high spirits despite the rainy weather.', ex5_ko = '비 오는 날씨에도 모두 기분 좋게 도착했어요.' WHERE id = 'idm_emotion_09';
UPDATE idioms SET ex3 = COALESCE(ex3, 'He blew a fuse when the cancellation came through last minute.'), ex3_ko = COALESCE(ex3_ko, '취소가 막판에 들어오자 그는 화를 폭발시켰어요.'), ex4 = 'She blew a fuse over a small misunderstanding.', ex4_ko = '그녀는 작은 오해로 화를 폭발시켰어요.', ex5 = 'Blowing a fuse rarely solves the actual problem.', ex5_ko = '화를 폭발시키는 것은 실제 문제를 해결하는 경우가 거의 없어요.' WHERE id = 'idm_emotion_10';
UPDATE idioms SET ex3 = COALESCE(ex3, 'The thriller kept us on the edge of our seats until the credits.'), ex3_ko = COALESCE(ex3_ko, '그 스릴러는 엔딩 크레딧까지 우리를 긴장하며 집중하게 했어요.'), ex4 = 'I was on the edge of my seat during the final play of the game.', ex4_ko = '저는 경기의 마지막 플레이 동안 긴장하며 집중했어요.', ex5 = 'Her storytelling kept the kids on the edge of their seats.', ex5_ko = '그녀의 이야기는 아이들을 긴장하며 집중하게 했어요.' WHERE id = 'idm_emotion_11';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I''ve been feeling blue ever since my best friend moved away.'), ex3_ko = COALESCE(ex3_ko, '저는 가장 친한 친구가 이사 간 이후로 우울해요.'), ex4 = 'A long walk in the park helps when I''m feeling blue.', ex4_ko = '저는 우울할 때 공원에서 긴 산책을 하는 것이 도움이 돼요.', ex5 = 'He''s been feeling blue and not sure why.', ex5_ko = '그는 우울한데 이유를 잘 모르겠어요.' WHERE id = 'idm_emotion_12';
UPDATE idioms SET ex3 = COALESCE(ex3, 'My dad went through the roof when he saw the phone bill.'), ex3_ko = COALESCE(ex3_ko, '아빠는 전화 요금 청구서를 보고 매우 화내셨어요.'), ex4 = 'The fans went through the roof when their team scored.', ex4_ko = '팬들은 그들의 팀이 골을 넣었을 때 매우 흥분했어요.', ex5 = 'House prices have gone through the roof this year.', ex5_ko = '집값이 올해 천정부지로 올랐어요.' WHERE id = 'idm_emotion_13';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Take heart — many people overcome this and so will you.'), ex3_ko = COALESCE(ex3_ko, '용기를 내세요 — 많은 사람들이 이를 극복했고 당신도 그럴 거예요.'), ex4 = 'She took heart from her doctor''s reassuring words.', ex4_ko = '그녀는 의사의 안심시키는 말에 용기를 냈어요.', ex5 = 'I took heart from the kind notes my students sent me.', ex5_ko = '학생들이 보내 준 다정한 편지로 용기를 냈어요.' WHERE id = 'idm_emotion_14';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I have mixed feelings about moving back to my hometown.'), ex3_ko = COALESCE(ex3_ko, '고향으로 다시 이사하는 것에 대해 복잡한 감정이에요.'), ex4 = 'She has mixed feelings about getting promoted into management.', ex4_ko = '그녀는 관리직으로 승진하는 것에 대해 복잡한 감정이에요.', ex5 = 'Watching the kids grow up brings mixed feelings every year.', ex5_ko = '아이들이 자라는 것을 보며 매년 복잡한 감정을 느껴요.' WHERE id = 'idm_emotion_15';

-- ══════════════════════════════════════
-- WEATHER
-- ══════════════════════════════════════
UPDATE idioms SET ex3 = COALESCE(ex3, 'Take heart — every cloud has a silver lining.'), ex3_ko = COALESCE(ex3_ko, '용기를 내세요 — 고생 끝에 낙이 와요.'), ex4 = 'When the cafe closed, she opened her own — every cloud has a silver lining.', ex4_ko = '카페가 문을 닫자 그녀는 자기 가게를 열었어요 — 고생 끝에 낙이 와요.', ex5 = 'It took years to see it, but every cloud really does have a silver lining.', ex5_ko = '보이는 데 몇 년이 걸렸지만 정말로 고생 끝에 낙이 와요.' WHERE id = 'idm_weather_01';
UPDATE idioms SET ex3 = COALESCE(ex3, 'My phone died, then my laptop crashed — it never rains but it pours.'), ex3_ko = COALESCE(ex3_ko, '핸드폰이 죽고 노트북도 다운됐어요 — 불행은 겹쳐서 와요.'), ex4 = 'They lost their jobs the same week the rent went up — it never rains but it pours.', ex4_ko = '월세가 오른 같은 주에 그들은 일자리를 잃었어요 — 불행은 겹쳐서 와요.', ex5 = 'First the leak, then the storm — it never rains but it pours.', ex5_ko = '먼저 누수, 그다음에 폭풍 — 불행은 겹쳐서 와요.' WHERE id = 'idm_weather_02';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Their public argument turned out to be a storm in a teacup.'), ex3_ko = COALESCE(ex3_ko, '그들의 공개 다툼은 결국 사소한 일을 크게 부풀린 것으로 드러났어요.'), ex4 = 'The controversy was a storm in a teacup that fizzled out by morning.', ex4_ko = '그 논란은 아침이면 사그라드는 사소한 일이었어요.', ex5 = 'Most online dramas are just a storm in a teacup.', ex5_ko = '대부분의 온라인 드라마는 사소한 일을 크게 부풀린 것이에요.' WHERE id = 'idm_weather_03';
UPDATE idioms SET ex3 = COALESCE(ex3, 'She called in sick because she was feeling under the weather.'), ex3_ko = COALESCE(ex3_ko, '그녀는 몸이 좋지 않아서 병가를 냈어요.'), ex4 = 'He''s been a bit under the weather since the trip.', ex4_ko = '그는 여행 이후로 몸이 조금 좋지 않아요.', ex5 = 'I''m feeling under the weather and need an early night.', ex5_ko = '몸이 좋지 않아서 일찍 자야 할 것 같아요.' WHERE id = 'idm_weather_04';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Don''t steal her thunder — let her share the news herself.'), ex3_ko = COALESCE(ex3_ko, '그녀의 주목을 빼앗지 마세요 — 그녀가 직접 소식을 전하게 해주세요.'), ex4 = 'I didn''t mean to steal her thunder at the meeting.', ex4_ko = '회의에서 그녀의 주목을 빼앗으려던 게 아니었어요.', ex5 = 'He tried to steal his sister''s thunder on her graduation day.', ex5_ko = '그는 누나의 졸업식 날 누나의 주목을 빼앗으려 했어요.' WHERE id = 'idm_weather_05';
UPDATE idioms SET ex3 = COALESCE(ex3, 'They weathered the storm by sticking together through hard times.'), ex3_ko = COALESCE(ex3_ko, '그들은 힘든 시기를 함께 버티며 어려움을 이겨냈어요.'), ex4 = 'The cafe weathered the storm of the lockdowns and reopened stronger.', ex4_ko = '그 카페는 봉쇄의 어려움을 이겨내고 더 강하게 재개했어요.', ex5 = 'Her career has weathered storm after storm.', ex5_ko = '그녀의 경력은 폭풍에 또 폭풍을 이겨냈어요.' WHERE id = 'idm_weather_06';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Make hay while the sun shines — these prices won''t last.'), ex3_ko = COALESCE(ex3_ko, '기회가 있을 때 활용하세요 — 이 가격은 오래 가지 않아요.'), ex4 = 'Freelancers learn to make hay while the sun shines.', ex4_ko = '프리랜서들은 기회가 있을 때 활용하는 법을 배워요.', ex5 = 'She made hay while the sun shone, working overtime during peak season.', ex5_ko = '그녀는 성수기에 초과 근무를 하며 기회가 있을 때 활용했어요.' WHERE id = 'idm_weather_07';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I''ve been in a fog since the time change last week.'), ex3_ko = COALESCE(ex3_ko, '지난주 시간 변경 이후로 멍한 상태였어요.'), ex4 = 'New parents often spend the first months in a fog.', ex4_ko = '신생아 부모들은 종종 처음 몇 달을 멍한 상태로 보내요.', ex5 = 'She walked through the meeting in a fog after a sleepless night.', ex5_ko = '잠 못 이룬 밤 후 그녀는 회의를 멍한 상태로 다녀왔어요.' WHERE id = 'idm_weather_08';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I''ll have to take a rain check on lunch — work is too busy today.'), ex3_ko = COALESCE(ex3_ko, '점심은 다음으로 미뤄야 할 것 같아요 — 오늘 일이 너무 바빠요.'), ex4 = 'She politely took a rain check on the dinner invitation.', ex4_ko = '그녀는 정중하게 저녁 식사 초대를 다음으로 미뤘어요.', ex5 = 'Let''s take a rain check on the hike until the weather improves.', ex5_ko = '날씨가 좋아질 때까지 등산을 다음으로 미뤄요.' WHERE id = 'idm_weather_09';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Their toddler is like a ray of sunshine in the family.'), ex3_ko = COALESCE(ex3_ko, '그 가족의 어린아이는 햇살 같은 존재예요.'), ex4 = 'Our new colleague is like a ray of sunshine in the office.', ex4_ko = '저희 새 동료는 사무실의 햇살 같은 존재예요.', ex5 = 'Her smile is like a ray of sunshine on the worst days.', ex5_ko = '그녀의 미소는 최악의 날에도 햇살 같아요.' WHERE id = 'idm_weather_10';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Cooking is a breeze when you''ve done it for years.'), ex3_ko = COALESCE(ex3_ko, '오랫동안 해온 사람에게 요리는 쉬운 일이에요.'), ex4 = 'The math test was a breeze for her.', ex4_ko = '그녀에게 수학 시험은 쉬운 일이었어요.', ex5 = 'Setting up the app was a breeze — even my grandmother managed.', ex5_ko = '앱 설정은 쉬운 일이었어요 — 저희 할머니도 하셨어요.' WHERE id = 'idm_weather_11';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Stop chasing rainbows and look at what you already have.'), ex3_ko = COALESCE(ex3_ko, '비현실적인 꿈을 그만 좇고 이미 가진 것을 봐요.'), ex4 = 'He spent his twenties chasing rainbows and never settled down.', ex4_ko = '그는 20대를 비현실적인 꿈을 좇으며 보냈고 정착하지 않았어요.', ex5 = 'There''s a difference between dreaming and chasing rainbows.', ex5_ko = '꿈을 꾸는 것과 비현실적인 꿈을 좇는 것은 다르죠.' WHERE id = 'idm_weather_12';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I''ll be snowed under for at least the next two weeks.'), ex3_ko = COALESCE(ex3_ko, '저는 적어도 앞으로 2주간은 일에 파묻혀 있을 거예요.'), ex4 = 'She''s snowed under preparing for the year-end report.', ex4_ko = '그녀는 연말 보고서 준비로 일에 파묻혀 있어요.', ex5 = 'Don''t add to her workload — she''s already snowed under.', ex5_ko = '그녀의 업무량을 더하지 마세요 — 이미 일에 파묻혀 있어요.' WHERE id = 'idm_weather_13';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Her response was lightning fast and surprised everyone.'), ex3_ko = COALESCE(ex3_ko, '그녀의 반응이 매우 빨라서 모두를 놀라게 했어요.'), ex4 = 'The internet here is lightning fast compared to my hometown.', ex4_ko = '여기 인터넷은 제 고향에 비해 매우 빨라요.', ex5 = 'He''s lightning fast at solving puzzles.', ex5_ko = '그는 퍼즐을 매우 빠르게 풀어요.' WHERE id = 'idm_weather_14';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I realized he was a fair-weather friend when I needed help moving.'), ex3_ko = COALESCE(ex3_ko, '이사할 때 도움이 필요했을 때 그가 어려울 때 곁에 없는 친구라는 걸 깨달았어요.'), ex4 = 'Real friends, not fair-weather ones, show up in tough times.', ex4_ko = '진짜 친구들은, 좋을 때만의 친구가 아니라, 힘든 시기에 나타나요.', ex5 = 'She lost a few fair-weather friends but gained truer ones.', ex5_ko = '그녀는 좋을 때만의 친구 몇 명을 잃었지만 더 진실한 친구들을 얻었어요.' WHERE id = 'idm_weather_15';

-- ══════════════════════════════════════
-- SHOPPING
-- ══════════════════════════════════════
UPDATE idioms SET ex3 = COALESCE(ex3, 'Those designer shoes cost an arm and a leg, but she loved them.'), ex3_ko = COALESCE(ex3_ko, '그 디자이너 신발은 매우 비쌌지만 그녀는 그것을 좋아했어요.'), ex4 = 'A new car costs an arm and a leg these days.', ex4_ko = '요즘 새 차는 매우 비싸요.', ex5 = 'The medication costs an arm and a leg without insurance.', ex5_ko = '보험 없이는 그 약이 매우 비싸요.' WHERE id = 'idm_shopping_01';
UPDATE idioms SET ex3 = COALESCE(ex3, 'A picnic in the park doesn''t need to break the bank.'), ex3_ko = COALESCE(ex3_ko, '공원에서의 소풍이 엄청난 돈을 쓸 필요는 없어요.'), ex4 = 'You can decorate a room beautifully without breaking the bank.', ex4_ko = '엄청난 돈을 쓰지 않고도 방을 아름답게 꾸밀 수 있어요.', ex5 = 'They had a wonderful wedding without breaking the bank.', ex5_ko = '그들은 엄청난 돈을 쓰지 않고도 멋진 결혼식을 올렸어요.' WHERE id = 'idm_shopping_02';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I paid through the nose for parking near the stadium.'), ex3_ko = COALESCE(ex3_ko, '저는 경기장 근처 주차에 터무니없는 값을 치렀어요.'), ex4 = 'We paid through the nose to fix our old laptop.', ex4_ko = '우리는 오래된 노트북을 고치는 데 터무니없는 값을 치렀어요.', ex5 = 'She paid through the nose for a last-minute flight home.', ex5_ko = '그녀는 막판 귀국 항공편에 터무니없는 값을 치렀어요.' WHERE id = 'idm_shopping_03';
UPDATE idioms SET ex3 = COALESCE(ex3, 'She got a bargain on the dining set at an estate sale.'), ex3_ko = COALESCE(ex3_ko, '그녀는 유산 정리 세일에서 식탁 세트를 싸게 샀어요.'), ex4 = 'I got a bargain on a winter coat at the end of the season.', ex4_ko = '저는 시즌 말에 겨울 코트를 싸게 샀어요.', ex5 = 'They always get a bargain at thrift stores.', ex5_ko = '그들은 항상 중고품 가게에서 싸게 사요.' WHERE id = 'idm_shopping_04';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I love going window shopping when it''s raining outside.'), ex3_ko = COALESCE(ex3_ko, '저는 밖에 비가 올 때 윈도우 쇼핑하는 걸 좋아해요.'), ex4 = 'They went window shopping along the main street after dinner.', ex4_ko = '그들은 저녁 식사 후 메인 거리를 따라 윈도우 쇼핑을 했어요.', ex5 = 'Going window shopping helps me relax without spending money.', ex5_ko = '윈도우 쇼핑은 제가 돈을 쓰지 않고 휴식하는 데 도움이 돼요.' WHERE id = 'idm_shopping_05';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Limited edition sneakers tend to sell like hotcakes.'), ex3_ko = COALESCE(ex3_ko, '한정판 운동화는 불티나게 팔리는 경향이 있어요.'), ex4 = 'The new cookbook is selling like hotcakes online.', ex4_ko = '그 새 요리책은 온라인에서 불티나게 팔리고 있어요.', ex5 = 'Her handmade candles sold like hotcakes at the fair.', ex5_ko = '그녀의 수제 양초들이 행사에서 불티나게 팔렸어요.' WHERE id = 'idm_shopping_06';
UPDATE idioms SET ex3 = COALESCE(ex3, 'The boutique was in the red until they launched online sales.'), ex3_ko = COALESCE(ex3_ko, '그 부티크는 온라인 판매를 시작하기 전까지 적자였어요.'), ex4 = 'After three solid quarters, the cafe is finally in the black.', ex4_ko = '안정적인 세 분기 후, 카페는 마침내 흑자로 돌아섰어요.', ex5 = 'It took the gym a year to move from in the red to in the black.', ex5_ko = '그 헬스장이 적자에서 흑자로 가는 데 1년이 걸렸어요.' WHERE id = 'idm_shopping_07';
UPDATE idioms SET ex3 = COALESCE(ex3, 'They cut corners on packaging and customers noticed immediately.'), ex3_ko = COALESCE(ex3_ko, '그들은 포장을 대충 했고 고객들이 즉시 알아챘어요.'), ex4 = 'It''s tempting to cut corners on a tight budget, but quality matters.', ex4_ko = '빠듯한 예산에서는 대충하고 싶지만 품질이 중요해요.', ex5 = 'The contractor cut corners and the roof started leaking.', ex5_ko = '시공업자가 대충 했고 지붕에서 물이 새기 시작했어요.' WHERE id = 'idm_shopping_08';
UPDATE idioms SET ex3 = COALESCE(ex3, 'The local market sells fresh produce that''s cheap as chips.'), ex3_ko = COALESCE(ex3_ko, '동네 시장은 매우 저렴한 신선한 농산물을 팔아요.'), ex4 = 'These notebooks are cheap as chips at the dollar store.', ex4_ko = '이 노트들은 1달러 가게에서 매우 저렴해요.', ex5 = 'Renting a bike here is cheap as chips compared to taxis.', ex5_ko = '여기서 자전거를 빌리는 것은 택시에 비해 매우 저렴해요.' WHERE id = 'idm_shopping_09';
UPDATE idioms SET ex3 = COALESCE(ex3, 'They threw a great birthday party on a tight budget.'), ex3_ko = COALESCE(ex3_ko, '그들은 빠듯한 예산으로 멋진 생일 파티를 열었어요.'), ex4 = 'She furnished her flat on a tight budget using second-hand finds.', ex4_ko = '그녀는 중고품으로 빠듯한 예산으로 아파트를 꾸몄어요.', ex5 = 'Eating well on a tight budget is possible with some planning.', ex5_ko = '약간의 계획만 있으면 빠듯한 예산으로도 잘 먹을 수 있어요.' WHERE id = 'idm_shopping_10';
UPDATE idioms SET ex3 = COALESCE(ex3, 'The vintage chair was a steal at that flea market price.'), ex3_ko = COALESCE(ex3_ko, '그 벼룩시장 가격으로 빈티지 의자는 헐값이었어요.'), ex4 = 'For someone who loves cooking, that food processor is a steal.', ex4_ko = '요리를 좋아하는 사람에게 그 푸드 프로세서는 헐값이에요.', ex5 = 'These tickets are a steal — they''re usually three times the price.', ex5_ko = '이 티켓들은 헐값이에요 — 보통 가격의 세 배예요.' WHERE id = 'idm_shopping_11';
UPDATE idioms SET ex3 = COALESCE(ex3, 'They splashed out on a beach holiday for their twentieth anniversary.'), ex3_ko = COALESCE(ex3_ko, '그들은 결혼 20주년을 위해 해변 휴가에 돈을 아낌없이 썼어요.'), ex4 = 'I splashed out on a really good winter coat this year.', ex4_ko = '저는 올해 정말 좋은 겨울 코트에 돈을 아낌없이 썼어요.', ex5 = 'They rarely splash out, but birthdays are an exception.', ex5_ko = '그들은 거의 돈을 아낌없이 쓰지 않지만 생일은 예외예요.' WHERE id = 'idm_shopping_12';
UPDATE idioms SET ex3 = COALESCE(ex3, 'The all-you-can-eat brunch lets you get your money''s worth.'), ex3_ko = COALESCE(ex3_ko, '무한 브런치는 돈 값을 할 수 있게 해줘요.'), ex4 = 'You really get your money''s worth from this online course.', ex4_ko = '이 온라인 강좌는 정말 돈 값을 해요.', ex5 = 'She got her money''s worth from her gym membership this year.', ex5_ko = '그녀는 올해 헬스장 회원권의 돈 값을 했어요.' WHERE id = 'idm_shopping_13';
UPDATE idioms SET ex3 = COALESCE(ex3, 'The store put the necklace on hold for me overnight.'), ex3_ko = COALESCE(ex3_ko, '가게에서 목걸이를 하룻밤 보류해뒀어요.'), ex4 = 'She put the decision on hold until she could think it over.', ex4_ko = '그녀는 깊이 생각해 볼 수 있을 때까지 결정을 보류해뒀어요.', ex5 = 'They put the renovation on hold during the busy season.', ex5_ko = '그들은 성수기 동안 리노베이션을 보류해뒀어요.' WHERE id = 'idm_shopping_14';
UPDATE idioms SET ex3 = COALESCE(ex3, 'We shopped till we dropped at the outlet mall last weekend.'), ex3_ko = COALESCE(ex3_ko, '지난 주말 우리는 아울렛에서 쓰러질 때까지 쇼핑했어요.'), ex4 = 'After exams, they shopped till they dropped in celebration.', ex4_ko = '시험 후 그들은 축하하며 쓰러질 때까지 쇼핑했어요.', ex5 = 'On vacation, I always shop till I drop in the local markets.', ex5_ko = '휴가 때 저는 항상 현지 시장에서 쓰러질 때까지 쇼핑해요.' WHERE id = 'idm_shopping_15';

-- ══════════════════════════════════════
-- CAFE
-- ══════════════════════════════════════
UPDATE idioms SET ex3 = COALESCE(ex3, 'She spilled the beans about the engagement at brunch.'), ex3_ko = COALESCE(ex3_ko, '그녀는 브런치 자리에서 약혼에 대한 비밀을 누설했어요.'), ex4 = 'Don''t spill the beans before the surprise party.', ex4_ko = '깜짝 파티 전에 비밀을 누설하지 마세요.', ex5 = 'He spilled the beans about the new restaurant location.', ex5_ko = '그는 새 식당 위치에 대한 비밀을 누설했어요.' WHERE id = 'idm_cafe_01';
UPDATE idioms SET ex3 = COALESCE(ex3, 'He had to eat humble pie after his loud prediction was wrong.'), ex3_ko = COALESCE(ex3_ko, '큰소리치던 예측이 틀린 후 그는 자존심을 굽혀야 했어요.'), ex4 = 'Eating humble pie is hard, but it builds character.', ex4_ko = '자존심을 굽히는 건 어렵지만 인격을 형성해요.', ex5 = 'She ate humble pie and apologized to the whole team.', ex5_ko = '그녀는 자존심을 굽히고 팀 전체에게 사과했어요.' WHERE id = 'idm_cafe_02';
UPDATE idioms SET ex3 = COALESCE(ex3, 'In a nutshell, we need more time to finish properly.'), ex3_ko = COALESCE(ex3_ko, '간단히 말하면, 제대로 끝내려면 시간이 더 필요해요.'), ex4 = 'In a nutshell, the meeting was about budget cuts.', ex4_ko = '간단히 말하면, 회의는 예산 삭감에 관한 것이었어요.', ex5 = 'She summarised the issue in a nutshell within one sentence.', ex5_ko = '그녀는 한 문장 안에 그 문제를 간단히 요약했어요.' WHERE id = 'idm_cafe_03';
UPDATE idioms SET ex3 = COALESCE(ex3, 'He buttered up his boss before bringing up the time-off request.'), ex3_ko = COALESCE(ex3_ko, '그는 휴가 요청을 꺼내기 전에 상사에게 아첨했어요.'), ex4 = 'Stop trying to butter me up and just say what you need.', ex4_ko = '아첨 그만하고 필요한 걸 말해요.', ex5 = 'She buttered up her teacher hoping for an extension.', ex5_ko = '그녀는 연장을 바라며 선생님에게 아첨했어요.' WHERE id = 'idm_cafe_04';
UPDATE idioms SET ex3 = COALESCE(ex3, 'His talk on resilience gave me a lot of food for thought.'), ex3_ko = COALESCE(ex3_ko, '회복력에 대한 그의 강연은 저에게 많은 생각할 거리를 줬어요.'), ex4 = 'The book offers food for thought on what success really means.', ex4_ko = '그 책은 성공이 진정 무엇을 의미하는지에 대한 생각할 거리를 줘요.', ex5 = 'Her question gave the team food for thought for the rest of the week.', ex5_ko = '그녀의 질문은 팀에 그 주 내내 생각할 거리를 줬어요.' WHERE id = 'idm_cafe_05';
UPDATE idioms SET ex3 = COALESCE(ex3, 'I bit off more than I could chew by volunteering for two committees.'), ex3_ko = COALESCE(ex3_ko, '두 위원회에 자원해서 감당할 수 없는 일을 맡았어요.'), ex4 = 'He bit off more than he could chew with that DIY project.', ex4_ko = '그는 그 DIY 프로젝트로 감당할 수 없는 일을 맡았어요.', ex5 = 'Sometimes I bite off more than I can chew because I want to help.', ex5_ko = '저는 돕고 싶어서 때로 감당할 수 없는 일을 맡곤 해요.' WHERE id = 'idm_cafe_06';
UPDATE idioms SET ex3 = COALESCE(ex3, 'She has a lot on her plate balancing work and elder care.'), ex3_ko = COALESCE(ex3_ko, '그녀는 일과 노인 돌봄 사이에서 처리할 일이 많아요.'), ex4 = 'I''ve got a lot on my plate this month — please be patient.', ex4_ko = '이번 달 처리할 일이 많아요 — 인내해 주세요.', ex5 = 'He has a lot on his plate but never complains.', ex5_ko = '그는 처리할 일이 많지만 절대 불평하지 않아요.' WHERE id = 'idm_cafe_07';
UPDATE idioms SET ex3 = COALESCE(ex3, 'A heartfelt thank-you note was the icing on the cake.'), ex3_ko = COALESCE(ex3_ko, '진심 어린 감사 노트는 금상첨화였어요.'), ex4 = 'Meeting my favorite author was the icing on the cake of the trip.', ex4_ko = '제가 좋아하는 작가를 만난 건 여행의 금상첨화였어요.', ex5 = 'The wedding was beautiful, and the surprise fireworks were the icing on the cake.', ex5_ko = '결혼식은 아름다웠고 깜짝 불꽃놀이는 금상첨화였어요.' WHERE id = 'idm_cafe_08';
UPDATE idioms SET ex3 = COALESCE(ex3, 'For her, parallel parking is a piece of cake.'), ex3_ko = COALESCE(ex3_ko, '그녀에게 평행 주차는 식은 죽 먹기예요.'), ex4 = 'Once you know the trick, it''s a piece of cake.', ex4_ko = '비결을 알면 식은 죽 먹기예요.', ex5 = 'The driving test was a piece of cake after months of practice.', ex5_ko = '몇 달의 연습 후 운전 시험은 식은 죽 먹기였어요.' WHERE id = 'idm_cafe_09';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Saying you didn''t really want it sounds like sour grapes.'), ex3_ko = COALESCE(ex3_ko, '진짜 원하지 않았다고 말하는 건 신 포도처럼 들려요.'), ex4 = 'He claims he didn''t want the role, but it''s just sour grapes.', ex4_ko = '그는 그 역할을 원하지 않았다고 주장하지만 그냥 신 포도예요.', ex5 = 'Don''t let sour grapes ruin a real friendship.', ex5_ko = '신 포도 같은 마음이 진짜 우정을 망치지 않게 하세요.' WHERE id = 'idm_cafe_10';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Take his stories with a pinch of salt — he loves exaggerating.'), ex3_ko = COALESCE(ex3_ko, '그의 이야기를 반신반의하세요 — 그는 과장하기를 좋아해요.'), ex4 = 'We took the rumor with a pinch of salt and waited for confirmation.', ex4_ko = '우리는 그 소문을 반신반의하며 확인을 기다렸어요.', ex5 = 'I take social media posts with a pinch of salt.', ex5_ko = '저는 소셜 미디어 게시물을 반신반의하며 봐요.' WHERE id = 'idm_cafe_11';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Loud parties just aren''t my cup of tea.'), ex3_ko = COALESCE(ex3_ko, '시끄러운 파티는 그냥 제 취향이 아니에요.'), ex4 = 'Spicy food isn''t his cup of tea, but he loves the smell.', ex4_ko = '매운 음식은 그의 취향이 아니지만 향은 좋아해요.', ex5 = 'Crowded beaches are not really my cup of tea.', ex5_ko = '북적이는 해변은 제 취향이 아니에요.' WHERE id = 'idm_cafe_12';
UPDATE idioms SET ex3 = COALESCE(ex3, 'She''s got a full plate with three kids and a startup.'), ex3_ko = COALESCE(ex3_ko, '그녀는 아이 셋과 스타트업으로 할 일이 가득해요.'), ex4 = 'He has a full plate this semester with five courses.', ex4_ko = '그는 다섯 과목으로 이번 학기 할 일이 가득해요.', ex5 = 'Having a full plate teaches you to prioritize.', ex5_ko = '할 일이 가득하면 우선순위를 정하는 법을 배우게 돼요.' WHERE id = 'idm_cafe_13';
UPDATE idioms SET ex3 = COALESCE(ex3, 'Only the cream of the crop get into the program each year.'), ex3_ko = COALESCE(ex3_ko, '매년 최상위 그룹만 그 프로그램에 들어가요.'), ex4 = 'They hire the cream of the crop from each graduating class.', ex4_ko = '그들은 매 졸업반에서 최상위 그룹을 채용해요.', ex5 = 'Her team is widely considered the cream of the crop in the industry.', ex5_ko = '그녀의 팀은 업계에서 최상위 그룹으로 널리 여겨져요.' WHERE id = 'idm_cafe_14';
UPDATE idioms SET ex3 = COALESCE(ex3, 'You can''t have your cake and eat it — work and infinite free time don''t mix.'), ex3_ko = COALESCE(ex3_ko, '두 마리 토끼를 다 잡을 수는 없어요 — 일과 무한한 자유 시간은 양립할 수 없어요.'), ex4 = 'She wants to keep her job and travel year-round — having her cake and eating it.', ex4_ko = '그녀는 직장을 유지하면서 일 년 내내 여행하고 싶어해요 — 두 마리 토끼를 다 잡으려는 거예요.', ex5 = 'You can''t always have your cake and eat it too in business decisions.', ex5_ko = '비즈니스 결정에서 두 마리 토끼를 다 잡을 수는 없어요.' WHERE id = 'idm_cafe_15';
