-- EngCat — 시사·뉴스 (news) 단어 예문 추가
-- example_en_2~5 + example_ko_2~5 for all 210 words
-- Generated: 2026-05-27

-- ══════════════════════════════════════
-- A1 (35 words)
-- ══════════════════════════════════════

UPDATE words SET example_en_2 = 'She reads the news every morning before work.', example_ko_2 = '그녀는 매일 아침 출근 전에 뉴스를 읽어요.', example_en_3 = 'The news about the storm surprised everyone.', example_ko_3 = '폭풍에 관한 뉴스가 모든 사람을 놀라게 했어요.', example_en_4 = 'He shared the news with his family at dinner.', example_ko_4 = '그는 저녁 식사 때 가족들과 뉴스를 나눴어요.', example_en_5 = 'Breaking news appeared on the screen suddenly.', example_ko_5 = '속보가 갑자기 화면에 나타났어요.' WHERE id = 'w_news_A1_01';

UPDATE words SET example_en_2 = 'The teacher asked students to write a report about the event.', example_ko_2 = '선생님이 학생들에게 그 사건에 대한 보고서를 쓰라고 했어요.', example_en_3 = 'The weather report says it will rain tomorrow.', example_ko_3 = '날씨 보도에 따르면 내일 비가 온대요.', example_en_4 = 'She gave a report on the accident to the police.', example_ko_4 = '그녀는 경찰에게 사고 보고서를 제출했어요.', example_en_5 = 'The hospital report showed that everyone was safe.', example_ko_5 = '병원 보고서에는 모두 안전하다고 나왔어요.' WHERE id = 'w_news_A1_02';

UPDATE words SET example_en_2 = 'He wants to travel to every country in the world.', example_ko_2 = '그는 세계 모든 나라를 여행하고 싶어요.', example_en_3 = 'This country has a very large population.', example_ko_3 = '이 나라는 인구가 매우 많아요.', example_en_4 = 'The two countries signed a new agreement.', example_ko_4 = '두 나라가 새로운 협정에 서명했어요.', example_en_5 = 'Which country do you want to visit next?', example_ko_5 = '다음에 어느 나라를 방문하고 싶어요?' WHERE id = 'w_news_A1_03';

UPDATE words SET example_en_2 = 'The people in this city are very friendly.', example_ko_2 = '이 도시 사람들은 매우 친절해요.', example_en_3 = 'Many people lost their homes in the flood.', example_ko_3 = '많은 사람들이 홍수로 집을 잃었어요.', example_en_4 = 'People around the world watched the game on TV.', example_ko_4 = '전 세계 사람들이 TV로 경기를 봤어요.', example_en_5 = 'The government is listening to what people want.', example_ko_5 = '정부는 사람들이 원하는 것을 듣고 있어요.' WHERE id = 'w_news_A1_04';

UPDATE words SET example_en_2 = 'The government is building new hospitals this year.', example_ko_2 = '정부가 올해 새 병원을 짓고 있어요.', example_en_3 = 'People are angry at the government''s decision.', example_ko_3 = '사람들은 정부의 결정에 화가 났어요.', example_en_4 = 'The government sent help to the flood victims.', example_ko_4 = '정부가 홍수 피해자들에게 도움을 보냈어요.', example_en_5 = 'The new government wants to improve schools.', example_ko_5 = '새 정부는 학교를 개선하고 싶어해요.' WHERE id = 'w_news_A1_05';

UPDATE words SET example_en_2 = 'The war caused many people to leave their homes.', example_ko_2 = '전쟁으로 많은 사람들이 집을 떠나야 했어요.', example_en_3 = 'Both sides agreed to stop the war.', example_ko_3 = '양측이 전쟁을 멈추기로 합의했어요.', example_en_4 = 'Children suffer the most during a war.', example_ko_4 = '전쟁 중에 아이들이 가장 많이 고통받아요.', example_en_5 = 'The country has been at war for three years.', example_ko_5 = '그 나라는 3년 동안 전쟁 중이에요.' WHERE id = 'w_news_A1_06';

UPDATE words SET example_en_2 = 'Millions of people voted in the election today.', example_ko_2 = '수백만 명이 오늘 선거에서 투표했어요.', example_en_3 = 'The election result was very close this time.', example_ko_3 = '이번 선거 결과는 매우 박빙이었어요.', example_en_4 = 'She is running in the election for mayor.', example_ko_4 = '그녀는 시장 선거에 출마하고 있어요.', example_en_5 = 'The election was free and fair, observers said.', example_ko_5 = '관찰자들은 선거가 자유롭고 공정했다고 말했어요.' WHERE id = 'w_news_A1_07';

UPDATE words SET example_en_2 = 'The city needs more money to fix the roads.', example_ko_2 = '그 도시는 도로를 고치기 위해 더 많은 돈이 필요해요.', example_en_3 = 'He saved money every month to buy a house.', example_ko_3 = '그는 집을 사기 위해 매달 돈을 모았어요.', example_en_4 = 'The charity raised a lot of money for the victims.', example_ko_4 = '자선단체가 피해자들을 위해 많은 돈을 모았어요.', example_en_5 = 'Without money, the hospital cannot buy medicine.', example_ko_5 = '돈이 없으면 병원이 약을 살 수 없어요.' WHERE id = 'w_news_A1_08';

UPDATE words SET example_en_2 = 'The sports event attracted thousands of fans.', example_ko_2 = '스포츠 행사에 수천 명의 팬이 몰렸어요.', example_en_3 = 'A serious event happened in the city last night.', example_ko_3 = '어젯밤 도시에서 심각한 사건이 일어났어요.', example_en_4 = 'The news covered the event for several days.', example_ko_4 = '뉴스가 며칠 동안 그 사건을 다뤘어요.', example_en_5 = 'Nobody expected this event to happen so quickly.', example_ko_5 = '아무도 이 사건이 이렇게 빨리 일어날 줄 몰랐어요.' WHERE id = 'w_news_A1_09';

UPDATE words SET example_en_2 = 'The world needs to work together to stop climate change.', example_ko_2 = '기후 변화를 막으려면 세계가 함께 협력해야 해요.', example_en_3 = 'People all over the world watched the ceremony live.', example_ko_3 = '전 세계 사람들이 행사를 생방송으로 봤어요.', example_en_4 = 'The disaster shocked the whole world.', example_ko_4 = '재난이 온 세계를 충격에 빠뜨렸어요.', example_en_5 = 'This invention changed the world forever.', example_ko_5 = '이 발명은 세상을 영원히 바꿨어요.' WHERE id = 'w_news_A1_10';

UPDATE words SET example_en_2 = 'She wrote a story about the accident for the newspaper.', example_ko_2 = '그녀는 신문에 실을 사고 기사를 썼어요.', example_en_3 = 'The story about the fire was on every channel.', example_ko_3 = '화재 기사가 모든 채널에 나왔어요.', example_en_4 = 'The reporter worked hard to get the full story.', example_ko_4 = '기자는 전체 기사를 얻기 위해 열심히 일했어요.', example_en_5 = 'That story about the missing children moved everyone.', example_ko_5 = '실종 어린이들에 관한 그 기사는 모든 사람을 감동시켰어요.' WHERE id = 'w_news_A1_11';

UPDATE words SET example_en_2 = 'Today is a very important day for the country.', example_ko_2 = '오늘은 나라에 매우 중요한 날이에요.', example_en_3 = 'The news today is all about the election.', example_ko_3 = '오늘 뉴스는 온통 선거에 관한 것이에요.', example_en_4 = 'The president will speak to the nation today.', example_ko_4 = '대통령이 오늘 국민에게 연설할 거예요.', example_en_5 = 'We learned today that the ceasefire has begun.', example_ko_5 = '우리는 오늘 휴전이 시작됐다는 것을 알게 됐어요.' WHERE id = 'w_news_A1_12';

UPDATE words SET example_en_2 = 'The reporter spoke live from the scene of the fire.', example_ko_2 = '기자가 화재 현장에서 생방송으로 말했어요.', example_en_3 = 'Millions watched the ceremony live on television.', example_ko_3 = '수백만 명이 텔레비전으로 행사를 생방송으로 봤어요.', example_en_4 = 'The press conference was broadcast live.', example_ko_4 = '기자 회견이 생방송으로 중계됐어요.', example_en_5 = 'She went live on social media to share the news.', example_ko_5 = '그녀는 소셜 미디어에서 생방송으로 소식을 전했어요.' WHERE id = 'w_news_A1_13';

UPDATE words SET example_en_2 = 'Firefighters worked all night to put out the fire.', example_ko_2 = '소방관들이 화재를 진화하기 위해 밤새 일했어요.', example_en_3 = 'The fire destroyed several houses in the area.', example_ko_3 = '화재로 그 지역의 여러 집이 불에 탔어요.', example_en_4 = 'Nobody was hurt in the fire, police confirmed.', example_ko_4 = '경찰이 화재에서 아무도 다치지 않았다고 확인했어요.', example_en_5 = 'The cause of the fire is still under investigation.', example_ko_5 = '화재 원인은 아직 조사 중이에요.' WHERE id = 'w_news_A1_14';

UPDATE words SET example_en_2 = 'The police are looking for the missing child.', example_ko_2 = '경찰이 실종된 아이를 찾고 있어요.', example_en_3 = 'Police stopped the car at the border checkpoint.', example_ko_3 = '경찰이 국경 검문소에서 차를 세웠어요.', example_en_4 = 'The police made an announcement about the investigation.', example_ko_4 = '경찰이 조사에 대한 발표를 했어요.', example_en_5 = 'More police were sent to control the large crowd.', example_ko_5 = '큰 군중을 통제하기 위해 더 많은 경찰이 파견됐어요.' WHERE id = 'w_news_A1_15';

UPDATE words SET example_en_2 = 'The flood left many families with nothing.', example_ko_2 = '홍수는 많은 가족을 빈손으로 만들었어요.', example_en_3 = 'Rescue teams saved people trapped by the flood.', example_ko_3 = '구조대가 홍수에 갇힌 사람들을 구했어요.', example_en_4 = 'The flood destroyed roads and bridges in the region.', example_ko_4 = '홍수로 그 지역의 도로와 다리가 파괴됐어요.', example_en_5 = 'Aid workers are helping those affected by the flood.', example_ko_5 = '구호 요원들이 홍수 피해자들을 돕고 있어요.' WHERE id = 'w_news_A1_16';

UPDATE words SET example_en_2 = 'The city announced new plans for public transportation.', example_ko_2 = '그 도시는 대중교통에 대한 새로운 계획을 발표했어요.', example_en_3 = 'Thousands of people in the city came out to protest.', example_ko_3 = '도시에서 수천 명이 시위를 위해 나왔어요.', example_en_4 = 'The city is growing fast and needs more schools.', example_ko_4 = '도시가 빠르게 성장하고 있어서 학교가 더 필요해요.', example_en_5 = 'Pollution is a big problem in this city.', example_ko_5 = '오염은 이 도시의 큰 문제예요.' WHERE id = 'w_news_A1_17';

UPDATE words SET example_en_2 = 'The law was changed for the first time in ten years.', example_ko_2 = '법이 10년 만에 처음으로 바뀌었어요.', example_en_3 = 'The economy grew faster this year than last year.', example_ko_3 = '올해 경제는 지난해보다 더 빠르게 성장했어요.', example_en_4 = 'Next year, the government plans to increase spending.', example_ko_4 = '내년에 정부는 지출을 늘릴 계획이에요.', example_en_5 = 'The disaster happened exactly one year ago today.', example_ko_5 = '재난은 정확히 1년 전 오늘 일어났어요.' WHERE id = 'w_news_A1_18';

UPDATE words SET example_en_2 = 'Many countries sent money to help after the earthquake.', example_ko_2 = '지진 이후 많은 나라들이 돕기 위해 돈을 보냈어요.', example_en_3 = 'Neighbors helped each other after the storm.', example_ko_3 = '이웃들이 폭풍 이후 서로 도왔어요.', example_en_4 = 'The government called on citizens to help the victims.', example_ko_4 = '정부는 시민들에게 피해자들을 돕도록 촉구했어요.', example_en_5 = 'She volunteers every weekend to help at the shelter.', example_ko_5 = '그녀는 매주 주말 대피소에서 봉사해요.' WHERE id = 'w_news_A1_19';

UPDATE words SET example_en_2 = 'The government introduced a new tax on sugary drinks.', example_ko_2 = '정부가 설탕이 든 음료에 새로운 세금을 도입했어요.', example_en_3 = 'A new report says air quality is improving.', example_ko_3 = '새 보고서에 따르면 대기 질이 개선되고 있어요.', example_en_4 = 'The new bridge will open next month.', example_ko_4 = '새 다리가 다음 달에 개통할 거예요.', example_en_5 = 'Voters chose a new leader in yesterday''s election.', example_ko_5 = '유권자들이 어제 선거에서 새 지도자를 선택했어요.' WHERE id = 'w_news_A1_20';

UPDATE words SET example_en_2 = 'The reporter confirmed that the story was true.', example_ko_2 = '기자가 그 기사가 사실임을 확인했어요.', example_en_3 = 'It is not true that the minister resigned.', example_ko_3 = '장관이 사임했다는 것은 사실이 아니에요.', example_en_4 = 'Everything in the report was found to be true.', example_ko_4 = '보고서의 모든 내용이 사실로 밝혀졌어요.', example_en_5 = 'People want to know if the information is true.', example_ko_5 = '사람들은 그 정보가 사실인지 알고 싶어해요.' WHERE id = 'w_news_A1_21';

UPDATE words SET example_en_2 = 'The press was invited to the official announcement.', example_ko_2 = '공식 발표에 언론이 초대됐어요.', example_en_3 = 'Freedom of the press is important in a democracy.', example_ko_3 = '언론의 자유는 민주주의에서 중요해요.', example_en_4 = 'The leader spoke to the press after the meeting.', example_ko_4 = '지도자가 회의 후 언론에 말했어요.', example_en_5 = 'The press reported the scandal in great detail.', example_ko_5 = '언론이 스캔들을 매우 자세히 보도했어요.' WHERE id = 'w_news_A1_22';

UPDATE words SET example_en_2 = 'The leader gave a strong speech about the economy.', example_ko_2 = '지도자가 경제에 대해 강력한 연설을 했어요.', example_en_3 = 'People are looking for a new leader for the country.', example_ko_3 = '사람들은 나라를 이끌 새 지도자를 찾고 있어요.', example_en_4 = 'The leader met with foreign officials today.', example_ko_4 = '지도자가 오늘 외국 관리들과 만났어요.', example_en_5 = 'The world leader arrived in the capital this morning.', example_ko_5 = '세계 지도자가 오늘 아침 수도에 도착했어요.' WHERE id = 'w_news_A1_23';

UPDATE words SET example_en_2 = 'The army was called in to help with flood relief.', example_ko_2 = '홍수 구호를 위해 군대가 투입됐어요.', example_en_3 = 'The army protected the city from attack.', example_ko_3 = '군대가 공격으로부터 도시를 보호했어요.', example_en_4 = 'Thousands of young people joined the army.', example_ko_4 = '수천 명의 젊은이들이 군대에 입대했어요.', example_en_5 = 'The army set up camps for displaced families.', example_ko_5 = '군대가 피난민 가족들을 위한 캠프를 설치했어요.' WHERE id = 'w_news_A1_24';

UPDATE words SET example_en_2 = 'Police are investigating the attack on the marketplace.', example_ko_2 = '경찰이 시장 공격을 조사하고 있어요.', example_en_3 = 'The attack left several people injured.', example_ko_3 = '공격으로 여러 명이 부상을 입었어요.', example_en_4 = 'Security was increased after the attack.', example_ko_4 = '공격 이후 보안이 강화됐어요.', example_en_5 = 'No group has claimed responsibility for the attack yet.', example_ko_5 = '아직 어떤 단체도 공격에 대한 책임을 주장하지 않았어요.' WHERE id = 'w_news_A1_25';

UPDATE words SET example_en_2 = 'The two leaders held a meeting to discuss the crisis.', example_ko_2 = '두 지도자가 위기를 논의하기 위한 회의를 열었어요.', example_en_3 = 'The meeting lasted three hours and ended without a deal.', example_ko_3 = '회의는 세 시간 동안 진행됐고 합의 없이 끝났어요.', example_en_4 = 'The UN called an emergency meeting about the conflict.', example_ko_4 = '유엔이 분쟁에 대한 긴급 회의를 소집했어요.', example_en_5 = 'All ministers attended the meeting at the parliament.', example_ko_5 = '모든 장관이 의회에서 열린 회의에 참석했어요.' WHERE id = 'w_news_A1_26';

UPDATE words SET example_en_2 = 'Aid organizations are delivering food to the affected areas.', example_ko_2 = '구호 단체들이 피해 지역에 식량을 전달하고 있어요.', example_en_3 = 'The lack of food is causing a serious crisis.', example_ko_3 = '식량 부족이 심각한 위기를 일으키고 있어요.', example_en_4 = 'The government promised to provide food for all families.', example_ko_4 = '정부가 모든 가정에 식량을 제공하겠다고 약속했어요.', example_en_5 = 'Food prices have risen sharply due to the conflict.', example_ko_5 = '분쟁으로 인해 식량 가격이 급격히 올랐어요.' WHERE id = 'w_news_A1_27';

UPDATE words SET example_en_2 = 'Schools were closed for two weeks after the disaster.', example_ko_2 = '재난 이후 학교가 2주 동안 문을 닫았어요.', example_en_3 = 'The government is building new schools in rural areas.', example_ko_3 = '정부가 농촌 지역에 새 학교를 짓고 있어요.', example_en_4 = 'Children are returning to school after the ceasefire.', example_ko_4 = '휴전 이후 아이들이 학교로 돌아오고 있어요.', example_en_5 = 'The school was used as a shelter during the flood.', example_ko_5 = '홍수 동안 학교가 대피소로 사용됐어요.' WHERE id = 'w_news_A1_28';

UPDATE words SET example_en_2 = 'The nearest hospital is forty kilometers away.', example_ko_2 = '가장 가까운 병원까지 40킬로미터예요.', example_en_3 = 'Injured people were rushed to the hospital after the attack.', example_ko_3 = '공격 이후 부상자들이 병원으로 급히 이송됐어요.', example_en_4 = 'The hospital is treating hundreds of patients a day.', example_ko_4 = '병원이 하루에 수백 명의 환자를 치료하고 있어요.', example_en_5 = 'More doctors are needed at the hospital in the north.', example_ko_5 = '북부 병원에 더 많은 의사가 필요해요.' WHERE id = 'w_news_A1_29';

UPDATE words SET example_en_2 = 'The army gained more power after the election.', example_ko_2 = '선거 이후 군대가 더 많은 권력을 얻었어요.', example_en_3 = 'The power went out during the storm last night.', example_ko_3 = '어젯밤 폭풍 동안 전력이 나갔어요.', example_en_4 = 'Citizens want to limit the power of the government.', example_ko_4 = '시민들은 정부의 권력을 제한하고 싶어해요.', example_en_5 = 'The president used emergency power to pass the law.', example_ko_5 = '대통령이 법을 통과시키기 위해 비상 권한을 사용했어요.' WHERE id = 'w_news_A1_30';

UPDATE words SET example_en_2 = 'Temperatures in the north dropped to minus twenty degrees.', example_ko_2 = '북쪽 기온이 영하 20도까지 떨어졌어요.', example_en_3 = 'Fighting was reported in the north of the country.', example_ko_3 = '나라 북쪽에서 전투가 보고됐어요.', example_en_4 = 'The north and south of the country have different climates.', example_ko_4 = '나라의 북쪽과 남쪽은 기후가 달라요.', example_en_5 = 'Troops are moving toward the north of the border.', example_ko_5 = '군대가 국경 북쪽으로 이동하고 있어요.' WHERE id = 'w_news_A1_31';

UPDATE words SET example_en_2 = 'The winner of the prize will be announced tomorrow.', example_ko_2 = '상의 수상자는 내일 발표될 거예요.', example_en_3 = 'The winner gave a short speech after the result.', example_ko_3 = '당선자가 결과 이후 짧은 연설을 했어요.', example_en_4 = 'There was no clear winner after the first round of voting.', example_ko_4 = '첫 번째 투표 라운드 후 명확한 승자가 없었어요.', example_en_5 = 'The winner promised to lead the country with honesty.', example_ko_5 = '당선자는 정직하게 나라를 이끌겠다고 약속했어요.' WHERE id = 'w_news_A1_32';

UPDATE words SET example_en_2 = 'Rescue workers found many people dead at the scene.', example_ko_2 = '구조대원들이 현장에서 많은 사람이 사망한 것을 발견했어요.', example_en_3 = 'The report says at least five people are dead.', example_ko_3 = '보도에 따르면 최소 5명이 사망했어요.', example_en_4 = 'The soldier died a hero protecting his country.', example_ko_4 = '그 군인은 나라를 지키다 영웅으로 사망했어요.', example_en_5 = 'The number of dead has risen to over a hundred.', example_ko_5 = '사망자 수가 100명을 넘어섰어요.' WHERE id = 'w_news_A1_33';

UPDATE words SET example_en_2 = 'The government said all hostages are now safe.', example_ko_2 = '정부는 모든 인질이 이제 안전하다고 말했어요.', example_en_3 = 'People are not safe walking alone at night there.', example_ko_3 = '그곳에서 밤에 혼자 걷는 것은 안전하지 않아요.', example_en_4 = 'Aid workers tried to move people to a safe location.', example_ko_4 = '구호 요원들이 사람들을 안전한 장소로 이동시키려고 했어요.', example_en_5 = 'The children were kept safe during the emergency.', example_ko_5 = '비상 사태 동안 아이들이 안전하게 보호됐어요.' WHERE id = 'w_news_A1_34';

UPDATE words SET example_en_2 = 'Reporters used a map to show where the attack happened.', example_ko_2 = '기자들이 공격이 일어난 곳을 보여주기 위해 지도를 사용했어요.', example_en_3 = 'The map shows all the areas hit by the storm.', example_ko_3 = '지도에는 폭풍이 강타한 모든 지역이 나와 있어요.', example_en_4 = 'They looked at a map to plan the evacuation route.', example_ko_4 = '그들은 대피 경로를 계획하기 위해 지도를 봤어요.', example_en_5 = 'The map on the screen showed where the flood was worst.', example_ko_5 = '화면의 지도는 홍수가 가장 심각한 곳을 보여줬어요.' WHERE id = 'w_news_A1_35';

-- ══════════════════════════════════════
-- A2 (35 words)
-- ══════════════════════════════════════

UPDATE words SET example_en_2 = 'She is very interested in politics and reads the news every day.', example_ko_2 = '그녀는 정치에 매우 관심이 있어서 매일 뉴스를 읽어요.', example_en_3 = 'Young people are becoming more engaged in politics.', example_ko_3 = '젊은이들이 정치에 더 많이 참여하고 있어요.', example_en_4 = 'The scandal affected politics in the country for years.', example_ko_4 = '스캔들이 몇 년 동안 그 나라의 정치에 영향을 미쳤어요.', example_en_5 = 'Politics can be difficult to understand for many people.', example_ko_5 = '정치는 많은 사람들이 이해하기 어려울 수 있어요.' WHERE id = 'w_news_A2_01';

UPDATE words SET example_en_2 = 'The economy is growing slowly after the pandemic.', example_ko_2 = '팬데믹 이후 경제가 천천히 성장하고 있어요.', example_en_3 = 'Many families struggled when the economy was weak.', example_ko_3 = '경제가 약했을 때 많은 가족들이 힘들었어요.', example_en_4 = 'The government has a plan to improve the economy.', example_ko_4 = '정부는 경제를 개선할 계획이 있어요.', example_en_5 = 'A strong economy means more jobs for people.', example_ko_5 = '강한 경제는 사람들에게 더 많은 일자리를 의미해요.' WHERE id = 'w_news_A2_02';

UPDATE words SET example_en_2 = 'The protest lasted for three days in the capital.', example_ko_2 = '수도에서 시위가 3일간 계속됐어요.', example_en_3 = 'Workers organized a protest against the new law.', example_ko_3 = '노동자들이 새 법에 반대하는 시위를 조직했어요.', example_en_4 = 'The protest was mostly peaceful but some violence was reported.', example_ko_4 = '시위는 대체로 평화로웠지만 일부 폭력이 보고됐어요.', example_en_5 = 'Students joined the protest to demand better education.', example_ko_5 = '학생들이 더 나은 교육을 요구하는 시위에 합류했어요.' WHERE id = 'w_news_A2_03';

UPDATE words SET example_en_2 = 'Citizens can vote online in this country.', example_ko_2 = '이 나라에서는 시민들이 온라인으로 투표할 수 있어요.', example_en_3 = 'Young people are encouraged to vote in every election.', example_ko_3 = '젊은이들이 모든 선거에서 투표하도록 권장돼요.', example_en_4 = 'The candidate asked everyone to vote for change.', example_ko_4 = '후보자는 모두에게 변화를 위해 투표해 달라고 요청했어요.', example_en_5 = 'About sixty percent of voters chose to vote in the referendum.', example_ko_5 = '유권자의 약 60퍼센트가 국민 투표에 참여하기로 했어요.' WHERE id = 'w_news_A2_04';

UPDATE words SET example_en_2 = 'The president visited the disaster area to show support.', example_ko_2 = '대통령이 지지를 보여주기 위해 재난 지역을 방문했어요.', example_en_3 = 'The president''s speech was watched by millions of people.', example_ko_3 = '대통령의 연설을 수백만 명이 시청했어요.', example_en_4 = 'The two presidents met to discuss the peace agreement.', example_ko_4 = '두 대통령이 평화 협정을 논의하기 위해 만났어요.', example_en_5 = 'The president declared a state of emergency after the flood.', example_ko_5 = '대통령이 홍수 이후 비상사태를 선포했어요.' WHERE id = 'w_news_A2_05';

UPDATE words SET example_en_2 = 'The new law requires all drivers to wear seatbelts.', example_ko_2 = '새 법은 모든 운전자가 안전벨트를 착용하도록 요구해요.', example_en_3 = 'The court decided the law was unfair.', example_ko_3 = '법원은 그 법이 불공평하다고 판결했어요.', example_en_4 = 'People must follow the law or face punishment.', example_ko_4 = '사람들은 법을 따르지 않으면 처벌을 받아요.', example_en_5 = 'A new law was introduced to protect the environment.', example_ko_5 = '환경을 보호하기 위한 새 법이 도입됐어요.' WHERE id = 'w_news_A2_06';

UPDATE words SET example_en_2 = 'Crime rates have fallen in the city over the past year.', example_ko_2 = '지난 한 해 동안 도시의 범죄율이 감소했어요.', example_en_3 = 'She reported the crime to the police immediately.', example_ko_3 = '그녀는 즉시 경찰에 범죄를 신고했어요.', example_en_4 = 'The documentary explored crime in the city''s poorest areas.', example_ko_4 = '다큐멘터리는 도시의 가장 빈곤한 지역의 범죄를 탐구했어요.', example_en_5 = 'Preventing crime requires cooperation between police and communities.', example_ko_5 = '범죄를 예방하려면 경찰과 지역 사회의 협력이 필요해요.' WHERE id = 'w_news_A2_07';

UPDATE words SET example_en_2 = 'Good health is the most important thing in life.', example_ko_2 = '건강은 인생에서 가장 중요한 것이에요.', example_en_3 = 'The government increased spending on health care this year.', example_ko_3 = '정부가 올해 의료에 대한 지출을 늘렸어요.', example_en_4 = 'Air pollution has a negative effect on public health.', example_ko_4 = '대기 오염은 공중 보건에 부정적인 영향을 미쳐요.', example_en_5 = 'The charity works to improve health in developing countries.', example_ko_5 = '자선단체는 개발도상국의 건강을 개선하기 위해 노력해요.' WHERE id = 'w_news_A2_08';

UPDATE words SET example_en_2 = 'The natural disaster caused billions of dollars in damage.', example_ko_2 = '자연재난으로 수십억 달러의 피해가 발생했어요.', example_en_3 = 'Countries around the world helped after the disaster.', example_ko_3 = '재난 이후 전 세계 나라들이 도움을 주었어요.', example_en_4 = 'The disaster left thousands of people without homes.', example_ko_4 = '재난으로 수천 명이 집을 잃었어요.', example_en_5 = 'The government declared the area a disaster zone.', example_ko_5 = '정부가 그 지역을 재난 지역으로 선포했어요.' WHERE id = 'w_news_A2_09';

UPDATE words SET example_en_2 = 'The agreement has the support of the international community.', example_ko_2 = '그 협정은 국제 사회의 지지를 받고 있어요.', example_en_3 = 'An international team of doctors arrived to help.', example_ko_3 = '국제 의사 팀이 도움을 위해 도착했어요.', example_en_4 = 'The issue requires an international solution.', example_ko_4 = '그 문제는 국제적인 해결책이 필요해요.', example_en_5 = 'International pressure is growing on the government to act.', example_ko_5 = '정부가 행동하도록 국제적 압력이 커지고 있어요.' WHERE id = 'w_news_A2_10';

UPDATE words SET example_en_2 = 'The prime minister and her cabinet ministers met this morning.', example_ko_2 = '총리와 내각 장관들이 오늘 아침 만났어요.', example_en_3 = 'The foreign minister flew to the capital for talks.', example_ko_3 = '외무 장관이 회담을 위해 수도로 비행했어요.', example_en_4 = 'The minister of education announced free school meals.', example_ko_4 = '교육부 장관이 무상 급식을 발표했어요.', example_en_5 = 'Three ministers resigned after the scandal became public.', example_ko_5 = '스캔들이 공개된 후 장관 세 명이 사임했어요.' WHERE id = 'w_news_A2_11';

UPDATE words SET example_en_2 = 'The agreement will come into force next January.', example_ko_2 = '협정은 내년 1월에 발효될 거예요.', example_en_3 = 'Reaching an agreement took more than six months of talks.', example_ko_3 = '합의에 도달하는 데 6개월 이상의 회담이 걸렸어요.', example_en_4 = 'Both sides broke the agreement within a week.', example_ko_4 = '양측이 일주일 이내에 합의를 어겼어요.', example_en_5 = 'The trade agreement will benefit farmers on both sides.', example_ko_5 = '무역 협정은 양측 농민들에게 이익이 될 거예요.' WHERE id = 'w_news_A2_12';

UPDATE words SET example_en_2 = 'Soldiers guarded the border to prevent illegal crossings.', example_ko_2 = '군인들이 불법 월경을 막기 위해 국경을 지켰어요.', example_en_3 = 'The border between the two countries was closed suddenly.', example_ko_3 = '두 나라 사이의 국경이 갑자기 폐쇄됐어요.', example_en_4 = 'Many families were separated at the border.', example_ko_4 = '많은 가족이 국경에서 헤어졌어요.', example_en_5 = 'The two sides agreed to open the border for trade.', example_ko_5 = '양측이 무역을 위해 국경을 열기로 합의했어요.' WHERE id = 'w_news_A2_13';

UPDATE words SET example_en_2 = 'The camp provides shelter and food for thousands of refugees.', example_ko_2 = '캠프는 수천 명의 난민에게 피난처와 식량을 제공해요.', example_en_3 = 'Refugees face many difficulties in their new countries.', example_ko_3 = '난민들은 새 나라에서 많은 어려움에 직면해요.', example_en_4 = 'The government promised to accept five thousand refugees.', example_ko_4 = '정부가 5,000명의 난민을 수용하겠다고 약속했어요.', example_en_5 = 'Aid workers are distributing blankets to refugees at the border.', example_ko_5 = '구호 요원들이 국경의 난민들에게 담요를 나눠주고 있어요.' WHERE id = 'w_news_A2_14';

UPDATE words SET example_en_2 = 'The government issued a statement apologizing for the mistake.', example_ko_2 = '정부가 실수에 대해 사과하는 성명을 발표했어요.', example_en_3 = 'The leader''s statement caused anger among opposition parties.', example_ko_3 = '지도자의 성명이 야당 사이에서 분노를 일으켰어요.', example_en_4 = 'She read a prepared statement to the reporters.', example_ko_4 = '그녀는 기자들에게 준비된 성명을 낭독했어요.', example_en_5 = 'The statement confirmed that elections will be held in June.', example_ko_5 = '성명은 선거가 6월에 열릴 것임을 확인했어요.' WHERE id = 'w_news_A2_15';

UPDATE words SET example_en_2 = 'The mayor will announce a new transport plan next week.', example_ko_2 = '시장이 다음 주에 새로운 교통 계획을 발표할 거예요.', example_en_3 = 'The company announced that it would close three factories.', example_ko_3 = '회사가 공장 세 곳을 폐쇄할 것이라고 발표했어요.', example_en_4 = 'She announced her decision to run in the election.', example_ko_4 = '그녀가 선거에 출마하기로 한 결정을 발표했어요.', example_en_5 = 'The UN announced emergency aid for the flood victims.', example_ko_5 = '유엔이 홍수 피해자들을 위한 긴급 지원을 발표했어요.' WHERE id = 'w_news_A2_16';

UPDATE words SET example_en_2 = 'Millions of people must pay more tax under the new plan.', example_ko_2 = '새 계획 아래 수백만 명이 더 많은 세금을 내야 해요.', example_en_3 = 'The opposition says the new tax is unfair to poor families.', example_ko_3 = '야당은 새 세금이 가난한 가족에게 불공평하다고 말해요.', example_en_4 = 'The government uses tax money to pay for schools and hospitals.', example_ko_4 = '정부는 세금을 학교와 병원에 사용해요.', example_en_5 = 'A tax on carbon emissions was introduced this year.', example_ko_5 = '올해 탄소 배출에 대한 세금이 도입됐어요.' WHERE id = 'w_news_A2_17';

UPDATE words SET example_en_2 = 'Trade between the two countries increased by ten percent.', example_ko_2 = '두 나라 사이의 무역이 10퍼센트 증가했어요.', example_en_3 = 'The conflict has badly affected trade in the region.', example_ko_3 = '분쟁이 지역 무역에 심각한 영향을 미쳤어요.', example_en_4 = 'Both sides hope to expand trade after the agreement.', example_ko_4 = '양측은 협정 이후 무역을 확대하기를 희망해요.', example_en_5 = 'The port is one of the busiest trade centers in Asia.', example_ko_5 = '그 항구는 아시아에서 가장 바쁜 무역 중심지 중 하나예요.' WHERE id = 'w_news_A2_18';

UPDATE words SET example_en_2 = 'The climate in this region has become drier over decades.', example_ko_2 = '이 지역의 기후가 수십 년에 걸쳐 더 건조해졌어요.', example_en_3 = 'Scientists are warning about rapid climate change.', example_ko_3 = '과학자들이 급격한 기후 변화에 대해 경고하고 있어요.', example_en_4 = 'The government signed an agreement to fight climate change.', example_ko_4 = '정부가 기후 변화에 맞서 싸우기 위한 협정에 서명했어요.', example_en_5 = 'Climate change is causing more frequent and severe floods.', example_ko_5 = '기후 변화로 인해 홍수가 더 자주, 더 심하게 발생하고 있어요.' WHERE id = 'w_news_A2_19';

UPDATE words SET example_en_2 = 'The charity set up centers to help victims of the disaster.', example_ko_2 = '자선단체가 재난 피해자들을 돕기 위한 센터를 세웠어요.', example_en_3 = 'Victims of the crime received support from the government.', example_ko_3 = '범죄 피해자들이 정부로부터 지원을 받았어요.', example_en_4 = 'The victims spoke about their experiences at the hearing.', example_ko_4 = '피해자들이 청문회에서 자신들의 경험에 대해 이야기했어요.', example_en_5 = 'International organizations are helping victims rebuild their lives.', example_ko_5 = '국제 단체들이 피해자들이 삶을 재건하도록 돕고 있어요.' WHERE id = 'w_news_A2_20';

UPDATE words SET example_en_2 = 'The judge asked both sides to present their evidence.', example_ko_2 = '판사는 양측에게 증거를 제출하라고 요청했어요.', example_en_3 = 'The judge delayed the verdict until next month.', example_ko_3 = '판사가 다음 달까지 판결을 연기했어요.', example_en_4 = 'Both sides argued their cases in front of the judge.', example_ko_4 = '양측이 판사 앞에서 자신들의 사건을 주장했어요.', example_en_5 = 'The judge ruled that the new law was unconstitutional.', example_ko_5 = '판사는 새 법이 위헌이라고 판결했어요.' WHERE id = 'w_news_A2_21';

UPDATE words SET example_en_2 = 'The survey found that most people support the new policy.', example_ko_2 = '여론 조사에 따르면 대부분의 사람들이 새 정책을 지지해요.', example_en_3 = 'A government survey showed rising levels of dissatisfaction.', example_ko_3 = '정부 여론 조사에서 불만족 수준이 높아지고 있는 것으로 나타났어요.', example_en_4 = 'The survey was conducted online with five thousand people.', example_ko_4 = '여론 조사는 5,000명을 대상으로 온라인으로 실시됐어요.', example_en_5 = 'Survey results show more people want stricter environmental laws.', example_ko_5 = '여론 조사 결과 더 많은 사람들이 더 엄격한 환경법을 원한다는 것을 보여줘요.' WHERE id = 'w_news_A2_22';

UPDATE words SET example_en_2 = 'A senior official from the ministry spoke to reporters.', example_ko_2 = '부처의 고위 관리가 기자들에게 이야기했어요.', example_en_3 = 'The official denied any connection to the scandal.', example_ko_3 = '관리는 스캔들과의 어떤 연관도 부인했어요.', example_en_4 = 'Local officials are working to repair the flood damage.', example_ko_4 = '지역 관리들이 홍수 피해를 수리하기 위해 노력하고 있어요.', example_en_5 = 'The official said the investigation would take several weeks.', example_ko_5 = '관리는 조사에 몇 주가 걸릴 것이라고 말했어요.' WHERE id = 'w_news_A2_23';

UPDATE words SET example_en_2 = 'The two leaders spoke about the need for lasting peace.', example_ko_2 = '두 지도자는 지속적인 평화의 필요성에 대해 이야기했어요.', example_en_3 = 'The region has enjoyed peace for twenty years now.', example_ko_3 = '그 지역은 이제 20년 동안 평화를 누리고 있어요.', example_en_4 = 'Citizens marched in the streets to call for peace.', example_ko_4 = '시민들이 평화를 요구하기 위해 거리를 행진했어요.', example_en_5 = 'A peace deal was reached after months of negotiation.', example_ko_5 = '수개월의 협상 끝에 평화 협정이 타결됐어요.' WHERE id = 'w_news_A2_24';

UPDATE words SET example_en_2 = 'The charity works to lift families out of poverty.', example_ko_2 = '자선단체는 가족들을 빈곤에서 구제하기 위해 노력해요.', example_en_3 = 'Poverty in the region increased after the conflict.', example_ko_3 = '분쟁 이후 그 지역의 빈곤이 증가했어요.', example_en_4 = 'The government has a ten-year plan to end poverty.', example_ko_4 = '정부는 빈곤을 종식시키기 위한 10년 계획을 가지고 있어요.', example_en_5 = 'Children living in poverty often lack access to education.', example_ko_5 = '빈곤 속에서 사는 아이들은 종종 교육을 받을 수 없어요.' WHERE id = 'w_news_A2_25';

UPDATE words SET example_en_2 = 'Social media has changed the way people consume news media.', example_ko_2 = '소셜 미디어는 사람들이 뉴스 미디어를 소비하는 방식을 바꿨어요.', example_en_3 = 'The media focused heavily on the election results.', example_ko_3 = '미디어가 선거 결과에 집중적으로 초점을 맞췄어요.', example_en_4 = 'The government accused the media of being biased.', example_ko_4 = '정부는 미디어가 편향됐다고 비난했어요.', example_en_5 = 'Media freedom is protected by the constitution in this country.', example_ko_5 = '이 나라에서는 헌법이 미디어의 자유를 보호해요.' WHERE id = 'w_news_A2_26';

UPDATE words SET example_en_2 = 'The population of the country is expected to decline by 2050.', example_ko_2 = '그 나라 인구는 2050년까지 감소할 것으로 예상돼요.', example_en_3 = 'A large population makes it harder to provide public services.', example_ko_3 = '인구가 많으면 공공 서비스를 제공하기가 더 어려워요.', example_en_4 = 'The disaster forced a large part of the population to flee.', example_ko_4 = '재난으로 인해 인구의 많은 부분이 피난해야 했어요.', example_en_5 = 'The aging population is putting pressure on health services.', example_ko_5 = '고령화 인구가 의료 서비스에 압박을 주고 있어요.' WHERE id = 'w_news_A2_27';

UPDATE words SET example_en_2 = 'Better education leads to better job opportunities.', example_ko_2 = '더 나은 교육은 더 나은 취업 기회로 이어져요.', example_en_3 = 'The government doubled its budget for education.', example_ko_3 = '정부가 교육 예산을 두 배로 늘렸어요.', example_en_4 = 'Children in conflict zones often miss out on education.', example_ko_4 = '분쟁 지역의 아이들은 종종 교육을 받지 못해요.', example_en_5 = 'Access to quality education is a basic human right.', example_ko_5 = '양질의 교육에 대한 접근은 기본적인 인권이에요.' WHERE id = 'w_news_A2_28';

UPDATE words SET example_en_2 = 'The country improved its security after the series of attacks.', example_ko_2 = '그 나라는 일련의 공격 이후 보안을 강화했어요.', example_en_3 = 'Security cameras were installed throughout the city center.', example_ko_3 = '도시 중심부 전역에 보안 카메라가 설치됐어요.', example_en_4 = 'The summit required thousands of security personnel.', example_ko_4 = '정상 회담에는 수천 명의 보안 인력이 필요했어요.', example_en_5 = 'National security is a top priority for the government.', example_ko_5 = '국가 안보는 정부의 최우선 과제예요.' WHERE id = 'w_news_A2_29';

UPDATE words SET example_en_2 = 'The player suffered a serious injury and left the field.', example_ko_2 = '선수가 심각한 부상을 입고 경기장을 떠났어요.', example_en_3 = 'The government counted the number of injuries in the disaster.', example_ko_3 = '정부가 재난에서 부상자 수를 집계했어요.', example_en_4 = 'Injuries from the accident were treated at the local hospital.', example_ko_4 = '사고 부상자들이 지역 병원에서 치료를 받았어요.', example_en_5 = 'Several road workers suffered injuries in the construction accident.', example_ko_5 = '여러 도로 노동자들이 공사 사고로 부상을 입었어요.' WHERE id = 'w_news_A2_30';

UPDATE words SET example_en_2 = 'The country is facing a political crisis after the election.', example_ko_2 = '그 나라는 선거 이후 정치 위기에 직면해 있어요.', example_en_3 = 'The crisis led to emergency talks between the two leaders.', example_ko_3 = '위기로 인해 두 지도자 사이에 긴급 회담이 열렸어요.', example_en_4 = 'International aid arrived to help during the humanitarian crisis.', example_ko_4 = '인도주의적 위기 동안 국제 원조가 도착했어요.', example_en_5 = 'The banking crisis caused millions of people to lose their savings.', example_ko_5 = '금융 위기로 수백만 명이 저축을 잃었어요.' WHERE id = 'w_news_A2_31';

UPDATE words SET example_en_2 = 'The army was placed on high alert after the border incident.', example_ko_2 = '국경 사건 이후 군대가 최고 경계 태세에 들어갔어요.', example_en_3 = 'The army helped build shelters for flood survivors.', example_ko_3 = '군대가 홍수 생존자들을 위해 대피소를 짓는 것을 도왔어요.', example_en_4 = 'The size of the army was reduced after the peace agreement.', example_ko_4 = '평화 협정 이후 군대 규모가 줄었어요.', example_en_5 = 'Both countries agreed not to move their armies closer to the border.', example_ko_5 = '양국은 군대를 국경에 더 가까이 이동하지 않기로 합의했어요.' WHERE id = 'w_news_A2_32';

UPDATE words SET example_en_2 = 'Workers protested outside the factory for three days.', example_ko_2 = '노동자들이 3일 동안 공장 밖에서 시위했어요.', example_en_3 = 'People protested against the government''s decision to cut health spending.', example_ko_3 = '사람들이 정부의 의료 지출 삭감 결정에 반대하여 시위했어요.', example_en_4 = 'Thousands protested peacefully in the main square.', example_ko_4 = '수천 명이 중앙 광장에서 평화롭게 시위했어요.', example_en_5 = 'She protested by refusing to eat for several days.', example_ko_5 = '그녀는 며칠 동안 음식을 거부하며 시위했어요.' WHERE id = 'w_news_A2_33';

UPDATE words SET example_en_2 = 'The prime minister called for unity during the crisis.', example_ko_2 = '총리가 위기 동안 단결을 촉구했어요.', example_en_3 = 'The prime minister''s party lost the election.', example_ko_3 = '총리의 당이 선거에서 졌어요.', example_en_4 = 'The two prime ministers agreed on a new trade deal.', example_ko_4 = '두 총리가 새로운 무역 협정에 합의했어요.', example_en_5 = 'The prime minister announced that she would step down.', example_ko_5 = '총리가 물러나겠다고 발표했어요.' WHERE id = 'w_news_A2_34';

UPDATE words SET example_en_2 = 'The government''s budget did not include funding for new schools.', example_ko_2 = '정부 예산에는 새 학교를 위한 자금이 포함되지 않았어요.', example_en_3 = 'The opposition criticized the budget for cutting health spending.', example_ko_3 = '야당은 의료 지출을 삭감한 예산을 비판했어요.', example_en_4 = 'The budget was passed by a majority in parliament.', example_ko_4 = '예산이 의회에서 다수결로 통과됐어요.', example_en_5 = 'Rising costs have put pressure on the national budget.', example_ko_5 = '비용 상승이 국가 예산에 압박을 가하고 있어요.' WHERE id = 'w_news_A2_35';

-- ══════════════════════════════════════
-- B1 (35 words)
-- ══════════════════════════════════════

UPDATE words SET example_en_2 = 'The party published its new education policy before the election.', example_ko_2 = '정당이 선거 전에 새로운 교육 정책을 발표했어요.', example_en_3 = 'Critics say the policy has failed to reduce unemployment.', example_ko_3 = '비평가들은 그 정책이 실업을 줄이는 데 실패했다고 말해요.', example_en_4 = 'The president''s foreign policy has been praised internationally.', example_ko_4 = '대통령의 외교 정책이 국제적으로 찬사를 받았어요.', example_en_5 = 'A new immigration policy was announced this morning.', example_ko_5 = '오늘 아침 새로운 이민 정책이 발표됐어요.' WHERE id = 'w_news_B1_01';

UPDATE words SET example_en_2 = 'The country''s healthcare reform reduced costs significantly.', example_ko_2 = '그 나라의 의료 개혁이 비용을 크게 줄였어요.', example_en_3 = 'Education reform is needed to prepare students for the future.', example_ko_3 = '학생들이 미래를 준비할 수 있도록 교육 개혁이 필요해요.', example_en_4 = 'The prime minister called reform an urgent national priority.', example_ko_4 = '총리는 개혁이 시급한 국가적 우선 과제라고 말했어요.', example_en_5 = 'Tax reform proposals were debated in parliament all week.', example_ko_5 = '세금 개혁 제안이 일주일 내내 의회에서 논의됐어요.' WHERE id = 'w_news_B1_02';

UPDATE words SET example_en_2 = 'The bill was debated in parliament for three months.', example_ko_2 = '그 법안은 3개월 동안 의회에서 논의됐어요.', example_en_3 = 'Parliament voted to reject the proposed budget cuts.', example_ko_3 = '의회가 예산 삭감안을 거부하는 표결을 했어요.', example_en_4 = 'The new parliament opened with a speech from the president.', example_ko_4 = '새 의회는 대통령의 연설로 시작됐어요.', example_en_5 = 'The opposition boycotted parliament in protest at the new rules.', example_ko_5 = '야당이 새 규칙에 항의하여 의회를 보이콧했어요.' WHERE id = 'w_news_B1_03';

UPDATE words SET example_en_2 = 'The new tax law sparked controversy among business owners.', example_ko_2 = '새 세금법이 사업주들 사이에서 논란을 일으켰어요.', example_en_3 = 'The appointment caused controversy because the candidate had no experience.', example_ko_3 = '후보자에게 경험이 없었기 때문에 임명이 논란이 됐어요.', example_en_4 = 'The decision to close the hospital was met with controversy.', example_ko_4 = '병원 폐쇄 결정이 논란에 부딪혔어요.', example_en_5 = 'The minister tried to avoid controversy by staying silent.', example_ko_5 = '장관은 침묵을 유지하여 논란을 피하려 했어요.' WHERE id = 'w_news_B1_04';

UPDATE words SET example_en_2 = 'The scandal led to a dramatic fall in the party''s poll ratings.', example_ko_2 = '스캔들로 인해 당의 지지율이 급락했어요.', example_en_3 = 'A financial scandal has engulfed the ministry of trade.', example_ko_3 = '금융 스캔들이 무역부를 뒤흔들었어요.', example_en_4 = 'Three officials were fired as a result of the scandal.', example_ko_4 = '스캔들의 결과로 관리 세 명이 해고됐어요.', example_en_5 = 'The media covered the corruption scandal for months.', example_ko_5 = '미디어가 수개월 동안 부패 스캔들을 다뤘어요.' WHERE id = 'w_news_B1_05';

UPDATE words SET example_en_2 = 'The minister promised to address the housing crisis immediately.', example_ko_2 = '장관은 주택 위기를 즉각 해결하겠다고 약속했어요.', example_en_3 = 'The health minister presented a new national vaccination plan.', example_ko_3 = '보건 장관이 새로운 국가 예방 접종 계획을 발표했어요.', example_en_4 = 'The finance minister resigned after the scandal became public.', example_ko_4 = '재무 장관이 스캔들이 공개된 후 사임했어요.', example_en_5 = 'The environment minister launched a new recycling campaign.', example_ko_5 = '환경 장관이 새 재활용 캠페인을 시작했어요.' WHERE id = 'w_news_B1_06';

UPDATE words SET example_en_2 = 'The government pushed new legislation on renewable energy.', example_ko_2 = '정부가 재생 에너지에 관한 새로운 입법을 추진했어요.', example_en_3 = 'Critics argue the legislation is too weak to be effective.', example_ko_3 = '비평가들은 그 입법이 효과적이기에는 너무 약하다고 주장해요.', example_en_4 = 'Anti-corruption legislation was approved after years of debate.', example_ko_4 = '반부패 입법이 수년간의 논쟁 끝에 승인됐어요.', example_en_5 = 'The legislation will come into effect from next January.', example_ko_5 = '입법은 내년 1월부터 시행될 거예요.' WHERE id = 'w_news_B1_07';

UPDATE words SET example_en_2 = 'The opposition staged a walkout in protest at the vote.', example_ko_2 = '야당이 투표에 항의하여 퇴장 시위를 했어요.', example_en_3 = 'A united opposition forced the prime minister to step down.', example_ko_3 = '단결된 야당이 총리를 사임하게 만들었어요.', example_en_4 = 'The opposition called the budget a threat to public services.', example_ko_4 = '야당은 그 예산이 공공 서비스에 대한 위협이라고 말했어요.', example_en_5 = 'The opposition won a surprise majority in the election.', example_ko_5 = '야당이 선거에서 예상 밖의 과반수를 차지했어요.' WHERE id = 'w_news_B1_08';

UPDATE words SET example_en_2 = 'Forming a coalition government took six weeks of negotiations.', example_ko_2 = '연립 정부 구성에 6주간의 협상이 걸렸어요.', example_en_3 = 'The coalition collapsed when the smaller party left.', example_ko_3 = '소규모 정당이 탈퇴하면서 연립이 붕괴됐어요.', example_en_4 = 'A broad coalition of parties supported the peace deal.', example_ko_4 = '광범위한 정당 연립이 평화 협정을 지지했어요.', example_en_5 = 'The ruling coalition lost its majority in the vote.', example_ko_5 = '집권 연립이 투표에서 과반수를 잃었어요.' WHERE id = 'w_news_B1_09';

UPDATE words SET example_en_2 = 'The bilateral summit produced a joint statement on trade.', example_ko_2 = '양자 정상 회담에서 무역에 관한 공동 성명이 나왔어요.', example_en_3 = 'Bilateral relations between the two countries have improved.', example_ko_3 = '두 나라 사이의 양자 관계가 개선됐어요.', example_en_4 = 'Both sides agreed to continue bilateral talks on security.', example_ko_4 = '양측이 안보에 대한 양자 회담을 계속하기로 합의했어요.', example_en_5 = 'A bilateral investment agreement was signed this week.', example_ko_5 = '이번 주 양자 투자 협정이 체결됐어요.' WHERE id = 'w_news_B1_10';

UPDATE words SET example_en_2 = 'A public inquiry found that the government had misled parliament.', example_ko_2 = '공개 조사에서 정부가 의회를 오도했음이 밝혀졌어요.', example_en_3 = 'The opposition demanded an independent inquiry into the matter.', example_ko_3 = '야당이 그 문제에 대한 독립 조사를 요구했어요.', example_en_4 = 'The inquiry is expected to take at least twelve months.', example_ko_4 = '조사는 최소 12개월이 걸릴 것으로 예상돼요.', example_en_5 = 'Witnesses refused to cooperate with the official inquiry.', example_ko_5 = '증인들이 공식 조사에 협조하기를 거부했어요.' WHERE id = 'w_news_B1_11';

UPDATE words SET example_en_2 = 'The campaign raised awareness about water pollution.', example_ko_2 = '캠페인이 수질 오염에 대한 인식을 높였어요.', example_en_3 = 'She ran a successful campaign for the local council.', example_ko_3 = '그녀는 지역 의회를 위한 성공적인 캠페인을 벌였어요.', example_en_4 = 'The campaign focused on economic inequality and job creation.', example_ko_4 = '캠페인은 경제적 불평등과 일자리 창출에 집중했어요.', example_en_5 = 'The health campaign encouraged people to exercise regularly.', example_ko_5 = '건강 캠페인이 사람들에게 규칙적으로 운동하도록 권장했어요.' WHERE id = 'w_news_B1_12';

UPDATE words SET example_en_2 = 'The CEO was forced to resign after the company lost millions.', example_ko_2 = '회사가 수백만 달러를 잃은 후 CEO는 사임해야 했어요.', example_en_3 = 'She decided to resign rather than implement the unpopular policy.', example_ko_3 = '그녀는 인기 없는 정책을 시행하는 대신 사임하기로 결정했어요.', example_en_4 = 'Two senior officials resigned over the data breach scandal.', example_ko_4 = '고위 관리 두 명이 데이터 유출 스캔들로 사임했어요.', example_en_5 = 'He announced his decision to resign at a press conference.', example_ko_5 = '그는 기자 회견에서 사임 결정을 발표했어요.' WHERE id = 'w_news_B1_13';

UPDATE words SET example_en_2 = 'The investigation revealed widespread corruption inside the police force.', example_ko_2 = '조사에서 경찰 내부의 광범위한 부패가 드러났어요.', example_en_3 = 'Voters punished the party because of corruption allegations.', example_ko_3 = '유권자들이 부패 혐의 때문에 그 당을 처벌했어요.', example_en_4 = 'The new government promised to tackle corruption aggressively.', example_ko_4 = '새 정부는 부패에 적극적으로 대처하겠다고 약속했어요.', example_en_5 = 'International monitors were brought in to help fight corruption.', example_ko_5 = '부패 퇴치를 돕기 위해 국제 감시단이 초청됐어요.' WHERE id = 'w_news_B1_14';

UPDATE words SET example_en_2 = 'Inflation is eroding the purchasing power of ordinary families.', example_ko_2 = '인플레이션이 일반 가정의 구매력을 잠식하고 있어요.', example_en_3 = 'The central bank raised interest rates to fight inflation.', example_ko_3 = '중앙은행이 인플레이션과 싸우기 위해 금리를 올렸어요.', example_en_4 = 'Inflation fell to two percent for the first time in years.', example_ko_4 = '인플레이션이 몇 년 만에 처음으로 2퍼센트로 떨어졌어요.', example_en_5 = 'Workers demanded higher wages to keep up with inflation.', example_ko_5 = '노동자들이 인플레이션을 따라잡기 위해 더 높은 임금을 요구했어요.' WHERE id = 'w_news_B1_15';

UPDATE words SET example_en_2 = 'The senate is debating whether to ratify the new treaty.', example_ko_2 = '상원이 새 조약을 비준할지 논의하고 있어요.', example_en_3 = 'The treaty reduced tariffs on goods traded between the nations.', example_ko_3 = '조약이 나라들 사이에 거래되는 상품의 관세를 낮췄어요.', example_en_4 = 'She argued the treaty violated the country''s sovereignty.', example_ko_4 = '그녀는 조약이 나라의 주권을 침해한다고 주장했어요.', example_en_5 = 'The security treaty obliged both nations to defend each other.', example_ko_5 = '안보 조약은 두 나라가 서로를 방어하도록 의무화했어요.' WHERE id = 'w_news_B1_16';

UPDATE words SET example_en_2 = 'The ceasefire gave civilians a chance to receive aid.', example_ko_2 = '휴전은 민간인들이 원조를 받을 기회를 줬어요.', example_en_3 = 'The ceasefire broke down after only forty-eight hours.', example_ko_3 = '휴전은 48시간도 안 돼 무너졌어요.', example_en_4 = 'International observers monitored the ceasefire closely.', example_ko_4 = '국제 관찰자들이 휴전을 면밀히 감시했어요.', example_en_5 = 'The ceasefire allowed families to bury their dead.', example_ko_5 = '휴전으로 가족들이 사망자를 매장할 수 있게 됐어요.' WHERE id = 'w_news_B1_17';

UPDATE words SET example_en_2 = 'World leaders gathered at the summit to discuss climate finance.', example_ko_2 = '세계 지도자들이 기후 금융을 논의하기 위해 정상 회담에 모였어요.', example_en_3 = 'The summit ended without a final agreement being reached.', example_ko_3 = '정상 회담은 최종 합의 없이 끝났어요.', example_en_4 = 'The host city spent millions preparing for the summit.', example_ko_4 = '개최 도시는 정상 회담을 준비하는 데 수백만 달러를 썼어요.', example_en_5 = 'A historic agreement was signed at the summit.', example_ko_5 = '정상 회담에서 역사적인 협정이 체결됐어요.' WHERE id = 'w_news_B1_18';

UPDATE words SET example_en_2 = 'The UN imposed sanctions on the country after the military coup.', example_ko_2 = '군사 쿠데타 이후 유엔이 그 나라에 제재를 부과했어요.', example_en_3 = 'Tougher sanctions are being considered to change the regime''s behavior.', example_ko_3 = '정권의 행동을 변화시키기 위해 더 강력한 제재가 검토되고 있어요.', example_en_4 = 'The sanctions have severely damaged the country''s economy.', example_ko_4 = '제재가 그 나라의 경제에 심각한 피해를 입혔어요.', example_en_5 = 'Several European countries refused to join the sanctions.', example_ko_5 = '여러 유럽 국가들이 제재에 참여하기를 거부했어요.' WHERE id = 'w_news_B1_19';

UPDATE words SET example_en_2 = 'The charity is calling for greater humanitarian access to the region.', example_ko_2 = '자선단체가 그 지역에 대한 더 큰 인도주의적 접근을 요구하고 있어요.', example_en_3 = 'The UN sent a humanitarian mission to assess the situation.', example_ko_3 = '유엔이 상황을 평가하기 위해 인도주의적 임무단을 보냈어요.', example_en_4 = 'The government was accused of blocking humanitarian aid.', example_ko_4 = '정부가 인도주의적 지원을 막고 있다는 비난을 받았어요.', example_en_5 = 'Humanitarian organizations are working around the clock in the war zone.', example_ko_5 = '인도주의 단체들이 전쟁 지역에서 24시간 내내 일하고 있어요.' WHERE id = 'w_news_B1_20';

UPDATE words SET example_en_2 = 'Years of conflict have left the country''s infrastructure in ruins.', example_ko_2 = '수년간의 분쟁으로 그 나라의 사회 기반 시설이 폐허가 됐어요.', example_en_3 = 'Investing in infrastructure creates jobs and boosts the economy.', example_ko_3 = '사회 기반 시설에 투자하면 일자리가 창출되고 경제가 활성화돼요.', example_en_4 = 'The flood caused massive damage to transport infrastructure.', example_ko_4 = '홍수가 교통 사회 기반 시설에 막대한 피해를 입혔어요.', example_en_5 = 'The new government pledged billions for infrastructure development.', example_ko_5 = '새 정부가 사회 기반 시설 개발을 위해 수십억 달러를 약속했어요.' WHERE id = 'w_news_B1_21';

UPDATE words SET example_en_2 = 'Negotiations between the two sides broke down after three days.', example_ko_2 = '양측 간의 협상이 3일 후 결렬됐어요.', example_en_3 = 'The negotiation process is slow but both sides remain committed.', example_ko_3 = '협상 과정이 느리지만 양측 모두 헌신적이에요.', example_en_4 = 'Successful negotiation requires patience and mutual compromise.', example_ko_4 = '성공적인 협상에는 인내와 상호 타협이 필요해요.', example_en_5 = 'The final negotiation lasted thirty-six hours without a break.', example_ko_5 = '최종 협상은 36시간 동안 쉬지 않고 계속됐어요.' WHERE id = 'w_news_B1_22';

UPDATE words SET example_en_2 = 'Workers demonstrated in front of the parliament building.', example_ko_2 = '노동자들이 의회 건물 앞에서 시위했어요.', example_en_3 = 'Citizens demonstrated their support for the president on the street.', example_ko_3 = '시민들이 거리에서 대통령에 대한 지지를 시위로 나타냈어요.', example_en_4 = 'Farmers demonstrated against the new agricultural import rules.', example_ko_4 = '농부들이 새로운 농산물 수입 규정에 반대하여 시위했어요.', example_en_5 = 'Tens of thousands demonstrated peacefully in the city center.', example_ko_5 = '수만 명이 도시 중심부에서 평화롭게 시위했어요.' WHERE id = 'w_news_B1_23';

UPDATE words SET example_en_2 = 'Unemployment fell to its lowest level in a decade.', example_ko_2 = '실업이 10년 만에 최저 수준으로 떨어졌어요.', example_en_3 = 'Young people are hardest hit by unemployment in this region.', example_ko_3 = '이 지역에서 청년들이 실업으로 가장 심하게 타격받아요.', example_en_4 = 'The government plans to create jobs to reduce unemployment.', example_ko_4 = '정부는 실업을 줄이기 위해 일자리를 만들 계획이에요.', example_en_5 = 'Long-term unemployment leads to serious social problems.', example_ko_5 = '장기 실업은 심각한 사회 문제로 이어져요.' WHERE id = 'w_news_B1_24';

UPDATE words SET example_en_2 = 'The jury deliberated for three days before reaching a verdict.', example_ko_2 = '배심원은 판결에 도달하기 전 3일 동안 심의했어요.', example_en_3 = 'The guilty verdict was welcomed by the victim''s family.', example_ko_3 = '유죄 판결이 피해자 가족에게 환영받았어요.', example_en_4 = 'Many people were surprised by the not-guilty verdict.', example_ko_4 = '많은 사람들이 무죄 판결에 놀랐어요.', example_en_5 = 'The verdict was read out in court on Thursday morning.', example_ko_5 = '판결은 목요일 아침 법정에서 낭독됐어요.' WHERE id = 'w_news_B1_25';

UPDATE words SET example_en_2 = 'The president held a press conference to deny the allegations.', example_ko_2 = '대통령이 혐의를 부인하기 위해 기자 회견을 열었어요.', example_en_3 = 'The minister walked out of the press conference unexpectedly.', example_ko_3 = '장관이 갑자기 기자 회견장을 떠났어요.', example_en_4 = 'Several difficult questions were raised at the press conference.', example_ko_4 = '기자 회견에서 여러 어려운 질문들이 제기됐어요.', example_en_5 = 'The press conference was broadcast live on national television.', example_ko_5 = '기자 회견이 국영 텔레비전에서 생방송으로 중계됐어요.' WHERE id = 'w_news_B1_26';

UPDATE words SET example_en_2 = 'The ruling party secured a comfortable majority in parliament.', example_ko_2 = '집권당이 의회에서 편안한 과반수를 확보했어요.', example_en_3 = 'The motion failed to win a majority and was rejected.', example_ko_3 = '그 안건은 과반수를 얻지 못해 부결됐어요.', example_en_4 = 'A two-thirds majority is needed to change the constitution.', example_ko_4 = '헌법을 바꾸려면 3분의 2의 과반수가 필요해요.', example_en_5 = 'The majority of voters chose to stay in the trading bloc.', example_ko_5 = '대다수 유권자들이 무역 블록에 남기로 선택했어요.' WHERE id = 'w_news_B1_27';

UPDATE words SET example_en_2 = 'The senator denied all accusations of taking bribes.', example_ko_2 = '상원 의원은 뇌물 수수 혐의를 모두 부인했어요.', example_en_3 = 'Accusations of misconduct were leveled at the police chief.', example_ko_3 = '경찰서장에게 비위 혐의가 제기됐어요.', example_en_4 = 'The accusations were investigated but no evidence was found.', example_ko_4 = '혐의가 조사됐지만 증거가 발견되지 않았어요.', example_en_5 = 'Making false accusations can damage someone''s reputation seriously.', example_ko_5 = '거짓 혐의를 제기하면 누군가의 평판을 심각하게 훼손할 수 있어요.' WHERE id = 'w_news_B1_28';

UPDATE words SET example_en_2 = 'Low turnout has become a problem for democracy.', example_ko_2 = '낮은 투표율이 민주주의의 문제가 됐어요.', example_en_3 = 'The party was shocked by the high turnout among young voters.', example_ko_3 = '당은 젊은 유권자들의 높은 투표율에 놀랐어요.', example_en_4 = 'The turnout at the meeting was far lower than expected.', example_ko_4 = '회의 참여율이 예상보다 훨씬 낮았어요.', example_en_5 = 'Analysts said high turnout helped the opposition win the election.', example_ko_5 = '분석가들은 높은 투표율이 야당의 선거 승리에 도움이 됐다고 말했어요.' WHERE id = 'w_news_B1_29';

UPDATE words SET example_en_2 = 'The court imposed a fine of ten million dollars on the company.', example_ko_2 = '법원이 그 회사에 1,000만 달러의 벌금을 부과했어요.', example_en_3 = 'The government threatened to impose tariffs on imported goods.', example_ko_3 = '정부는 수입품에 관세를 부과하겠다고 위협했어요.', example_en_4 = 'New restrictions were imposed on travel to the affected region.', example_ko_4 = '피해 지역으로의 여행에 새로운 제한이 부과됐어요.', example_en_5 = 'Authorities imposed a curfew to maintain order after the riot.', example_ko_5 = '당국이 폭동 이후 질서를 유지하기 위해 통행금지를 부과했어요.' WHERE id = 'w_news_B1_30';

UPDATE words SET example_en_2 = 'The country''s closest ally offered to help with the crisis.', example_ko_2 = '그 나라의 가장 가까운 동맹국이 위기를 도와주겠다고 제안했어요.', example_en_3 = 'NATO allies agreed to increase defense spending.', example_ko_3 = 'NATO 동맹국들이 방위 지출을 늘리기로 합의했어요.', example_en_4 = 'Relations with key allies were strained by the trade dispute.', example_ko_4 = '무역 분쟁으로 주요 동맹국들과의 관계가 긴장됐어요.', example_en_5 = 'The president consulted his allies before announcing the decision.', example_ko_5 = '대통령이 결정을 발표하기 전에 동맹국들과 상의했어요.' WHERE id = 'w_news_B1_31';

UPDATE words SET example_en_2 = 'Prosecutors presented new evidence linking the suspect to the crime.', example_ko_2 = '검사들이 용의자를 범죄와 연결하는 새로운 증거를 제출했어요.', example_en_3 = 'The evidence was dismissed as unreliable by the defense lawyer.', example_ko_3 = '증거가 변호인에 의해 신뢰할 수 없다고 기각됐어요.', example_en_4 = 'Scientists published evidence showing the link between pollution and disease.', example_ko_4 = '과학자들이 오염과 질병 사이의 연관성을 보여주는 증거를 발표했어요.', example_en_5 = 'There is growing evidence that the data was manipulated.', example_ko_5 = '데이터가 조작됐다는 증거가 늘어나고 있어요.' WHERE id = 'w_news_B1_32';

UPDATE words SET example_en_2 = 'A free press and fair elections are the foundations of democracy.', example_ko_2 = '자유 언론과 공정한 선거는 민주주의의 기반이에요.', example_en_3 = 'The new government promised to restore democracy after the coup.', example_ko_3 = '새 정부는 쿠데타 이후 민주주의를 회복하겠다고 약속했어요.', example_en_4 = 'Citizens marched to defend democracy and free expression.', example_ko_4 = '시민들이 민주주의와 표현의 자유를 지키기 위해 행진했어요.', example_en_5 = 'International observers praised the election as a triumph for democracy.', example_ko_5 = '국제 관찰자들이 선거를 민주주의의 승리라고 찬사했어요.' WHERE id = 'w_news_B1_33';

UPDATE words SET example_en_2 = 'Aid agencies report more refugees are arriving at the border.', example_ko_2 = '구호 단체들이 더 많은 난민이 국경에 도착하고 있다고 보고해요.', example_en_3 = 'Many refugees have been waiting in camps for over three years.', example_ko_3 = '많은 난민들이 3년 이상 캠프에서 기다리고 있어요.', example_en_4 = 'The government pledged to double the number of refugees it accepts.', example_ko_4 = '정부는 받아들이는 난민 수를 두 배로 늘리겠다고 약속했어요.', example_en_5 = 'Refugees are often among the most vulnerable people in the world.', example_ko_5 = '난민들은 종종 세계에서 가장 취약한 사람들에 속해요.' WHERE id = 'w_news_B1_34';

UPDATE words SET example_en_2 = 'Negotiators missed the deadline for reaching a peace deal.', example_ko_2 = '협상가들이 평화 협정을 위한 시한을 놓쳤어요.', example_en_3 = 'The government set a deadline of three months for the reform.', example_ko_3 = '정부가 개혁을 위한 3개월의 시한을 설정했어요.', example_en_4 = 'Reporters had to meet a tight deadline to file their stories.', example_ko_4 = '기자들은 기사를 제출하기 위해 촉박한 마감 시한을 맞춰야 했어요.', example_en_5 = 'International monitors warned that the deadline must not be extended again.', example_ko_5 = '국제 감시단은 시한이 다시 연장되어서는 안 된다고 경고했어요.' WHERE id = 'w_news_B1_35';

-- ══════════════════════════════════════
-- B2 (35 words)
-- ══════════════════════════════════════

UPDATE words SET example_en_2 = 'Geopolitics is reshaping energy trade routes across Asia.', example_ko_2 = '지정학이 아시아 전역의 에너지 무역 경로를 재편하고 있어요.', example_en_3 = 'The professor explained how geopolitics drives military alliances.', example_ko_3 = '교수는 지정학이 어떻게 군사 동맹을 이끄는지 설명했어요.', example_en_4 = 'The conflict is driven as much by geopolitics as by ideology.', example_ko_4 = '분쟁은 이념만큼이나 지정학에 의해 촉발되고 있어요.', example_en_5 = 'Understanding geopolitics is essential for analyzing today''s crises.', example_ko_5 = '지정학을 이해하는 것은 오늘날의 위기를 분석하는 데 필수적이에요.' WHERE id = 'w_news_B2_01';

UPDATE words SET example_en_2 = 'The new sanctions targeted the country''s oil and gas exports.', example_ko_2 = '새로운 제재는 그 나라의 석유·가스 수출을 겨냥했어요.', example_en_3 = 'European allies debated how effective the sanctions have been.', example_ko_3 = '유럽 동맹국들이 제재가 얼마나 효과적이었는지 논의했어요.', example_en_4 = 'The sanctions prohibit any trade in military equipment.', example_ko_4 = '제재는 군사 장비의 모든 거래를 금지해요.', example_en_5 = 'Lifting sanctions was made conditional on verified disarmament.', example_ko_5 = '제재 해제는 검증된 무장 해제를 조건으로 걸었어요.' WHERE id = 'w_news_B2_02';

UPDATE words SET example_en_2 = 'Diplomatic channels were used to resolve the border dispute.', example_ko_2 = '국경 분쟁을 해결하기 위해 외교 경로가 사용됐어요.', example_en_3 = 'The two countries have not had diplomatic relations since 2015.', example_ko_3 = '두 나라는 2015년 이후 외교 관계가 없었어요.', example_en_4 = 'The new ambassador is expected to improve diplomatic ties.', example_ko_4 = '새 대사가 외교 관계를 개선할 것으로 기대돼요.', example_en_5 = 'A diplomatic solution is preferable to military action.', example_ko_5 = '외교적 해결책이 군사 행동보다 바람직해요.' WHERE id = 'w_news_B2_03';

UPDATE words SET example_en_2 = 'The incumbent prime minister is facing a strong challenge.', example_ko_2 = '현직 총리가 강력한 도전에 직면해 있어요.', example_en_3 = 'Polls suggest the incumbent could lose the election.', example_ko_3 = '여론 조사는 현직자가 선거에서 질 수 있음을 시사해요.', example_en_4 = 'The incumbent ran on a record of economic stability.', example_ko_4 = '현직자는 경제 안정의 실적을 내세워 출마했어요.', example_en_5 = 'Being an incumbent usually gives a candidate an advantage.', example_ko_5 = '현직자임은 보통 후보자에게 유리하게 작용해요.' WHERE id = 'w_news_B2_04';

UPDATE words SET example_en_2 = 'The independence movement argued that sovereignty is non-negotiable.', example_ko_2 = '독립 운동은 주권은 협상 불가라고 주장했어요.', example_en_3 = 'National sovereignty was at the center of the debate.', example_ko_3 = '국가 주권이 논쟁의 중심에 있었어요.', example_en_4 = 'The agreement was seen as an infringement on sovereignty.', example_ko_4 = '협정은 주권 침해로 여겨졌어요.', example_en_5 = 'Small nations often struggle to protect their sovereignty.', example_ko_5 = '소국들은 종종 주권을 보호하기 위해 힘겨워해요.' WHERE id = 'w_news_B2_05';

UPDATE words SET example_en_2 = 'A multilateral response was agreed after days of difficult talks.', example_ko_2 = '며칠간의 어려운 회담 끝에 다자간 대응이 합의됐어요.', example_en_3 = 'Some countries prefer bilateral deals over multilateral agreements.', example_ko_3 = '일부 나라는 다자간 협정보다 양자 협정을 선호해요.', example_en_4 = 'The UN provides a multilateral forum for resolving disputes.', example_ko_4 = '유엔은 분쟁을 해결하기 위한 다자간 포럼을 제공해요.', example_en_5 = 'Multilateral cooperation is essential to address the climate emergency.', example_ko_5 = '기후 비상사태에 대처하려면 다자간 협력이 필수적이에요.' WHERE id = 'w_news_B2_06';

UPDATE words SET example_en_2 = 'The referendum produced a narrow majority in favor of independence.', example_ko_2 = '국민 투표에서 독립에 찬성하는 근소한 다수결이 나왔어요.', example_en_3 = 'The opposition demanded a referendum on the new constitution.', example_ko_3 = '야당이 새 헌법에 대한 국민 투표를 요구했어요.', example_en_4 = 'A referendum was held to decide whether to join the monetary union.', example_ko_4 = '화폐 동맹 가입 여부를 결정하기 위해 국민 투표가 열렸어요.', example_en_5 = 'Turnout in the referendum was unexpectedly high at eighty percent.', example_ko_5 = '국민 투표 투표율이 예상 밖으로 80퍼센트로 높았어요.' WHERE id = 'w_news_B2_07';

UPDATE words SET example_en_2 = 'Austerity measures were imposed after the country requested a bailout.', example_ko_2 = '국가가 구제 금융을 요청한 후 긴축 조치가 부과됐어요.', example_en_3 = 'Years of austerity left public services severely underfunded.', example_ko_3 = '수년간의 긴축으로 공공 서비스가 심각하게 자금 부족 상태가 됐어요.', example_en_4 = 'The prime minister defended austerity as the only responsible option.', example_ko_4 = '총리는 긴축이 유일한 책임 있는 선택이라고 옹호했어요.', example_en_5 = 'Public anger at austerity helped the opposition win the election.', example_ko_5 = '긴축에 대한 공분이 야당의 선거 승리를 도왔어요.' WHERE id = 'w_news_B2_08';

UPDATE words SET example_en_2 = 'The coup was condemned by every major democracy in the world.', example_ko_2 = '쿠데타는 세계 모든 주요 민주주의 국가에 의해 규탄됐어요.', example_en_3 = 'The general who led the coup promised elections within two years.', example_ko_3 = '쿠데타를 이끈 장군은 2년 내에 선거를 약속했어요.', example_en_4 = 'The coup toppled a government that had ruled for thirty years.', example_ko_4 = '쿠데타가 30년간 집권한 정부를 무너뜨렸어요.', example_en_5 = 'Sanctions were immediately imposed following the coup.', example_ko_5 = '쿠데타 직후 제재가 즉각 부과됐어요.' WHERE id = 'w_news_B2_09';

UPDATE words SET example_en_2 = 'The insurgency has spread from the mountains to the cities.', example_ko_2 = '반란이 산악 지대에서 도시로 퍼졌어요.', example_en_3 = 'The government struggled to suppress the insurgency for years.', example_ko_3 = '정부는 수년간 반란을 진압하기 위해 힘겨워했어요.', example_en_4 = 'Foreign support helped the insurgency gain new territory.', example_ko_4 = '외국의 지원이 반란군이 새 영토를 확보하는 데 도움이 됐어요.', example_en_5 = 'Analysts say the insurgency is fueled by economic grievances.', example_ko_5 = '분석가들은 반란이 경제적 불만에 의해 촉발됐다고 말해요.' WHERE id = 'w_news_B2_10';

UPDATE words SET example_en_2 = 'The report called for stronger accountability mechanisms in government.', example_ko_2 = '보고서는 정부에서 더 강력한 책임 메커니즘을 요구했어요.', example_en_3 = 'Voters want to see accountability for the corruption that occurred.', example_ko_3 = '유권자들은 발생한 부패에 대한 책임 추궁을 원해요.', example_en_4 = 'Transparency is essential for accountability in public institutions.', example_ko_4 = '공공 기관에서 책임을 위해 투명성이 필수적이에요.', example_en_5 = 'The court ruling established a new standard of accountability for officials.', example_ko_5 = '법원 판결이 관리들에 대한 새로운 책임 기준을 확립했어요.' WHERE id = 'w_news_B2_11';

UPDATE words SET example_en_2 = 'Populism often exploits fear and distrust of institutions.', example_ko_2 = '포퓰리즘은 종종 기관에 대한 두려움과 불신을 이용해요.', example_en_3 = 'Analysts disagree on what is driving the rise of populism.', example_ko_3 = '분석가들은 포퓰리즘 부상을 촉진하는 것이 무엇인지에 대해 의견이 달라요.', example_en_4 = 'Economic inequality can create fertile ground for populism.', example_ko_4 = '경제적 불평등은 포퓰리즘이 자랄 수 있는 비옥한 토양을 만들 수 있어요.', example_en_5 = 'The president''s campaign relied heavily on populism to win votes.', example_ko_5 = '대통령의 선거 운동은 표를 얻기 위해 포퓰리즘에 크게 의존했어요.' WHERE id = 'w_news_B2_12';

UPDATE words SET example_en_2 = 'The report documented authoritarian practices in the country''s prisons.', example_ko_2 = '보고서는 그 나라 감옥에서의 권위주의적 관행을 기록했어요.', example_en_3 = 'The authoritarian leader expelled foreign journalists.', example_ko_3 = '권위주의 지도자가 외국 기자들을 추방했어요.', example_en_4 = 'Citizens are resisting what they call an authoritarian takeover.', example_ko_4 = '시민들이 권위주의적 장악이라고 부르는 것에 저항하고 있어요.', example_en_5 = 'The authoritarian government censored all independent media.', example_ko_5 = '권위주의 정부가 모든 독립 미디어를 검열했어요.' WHERE id = 'w_news_B2_13';

UPDATE words SET example_en_2 = 'State-controlled media is used to spread government propaganda.', example_ko_2 = '국가 통제 미디어가 정부 선전을 퍼뜨리기 위해 사용돼요.', example_en_3 = 'The documentary exposed how propaganda shaped public opinion during the war.', example_ko_3 = '다큐멘터리는 전쟁 중 선전이 어떻게 여론을 형성했는지 폭로했어요.', example_en_4 = 'Social media has made it easier to spread propaganda.', example_ko_4 = '소셜 미디어는 선전을 퍼뜨리는 것을 더 쉽게 만들었어요.', example_en_5 = 'Critical thinking skills help people identify propaganda.', example_ko_5 = '비판적 사고 능력은 사람들이 선전을 식별하는 데 도움이 돼요.' WHERE id = 'w_news_B2_14';

UPDATE words SET example_en_2 = 'The platform was criticized for hosting disinformation about the election.', example_ko_2 = '그 플랫폼은 선거에 관한 허위 정보를 호스팅한다고 비판받았어요.', example_en_3 = 'Journalists trained to spot disinformation before it spreads.', example_ko_3 = '기자들이 허위 정보가 퍼지기 전에 식별하도록 훈련받았어요.', example_en_4 = 'Disinformation campaigns have targeted health-care workers online.', example_ko_4 = '허위 정보 캠페인이 온라인에서 의료 종사자들을 겨냥했어요.', example_en_5 = 'The government launched a task force to fight disinformation.', example_ko_5 = '정부가 허위 정보와 싸우기 위한 태스크포스를 출범시켰어요.' WHERE id = 'w_news_B2_15';

UPDATE words SET example_en_2 = 'A trade embargo was imposed after negotiations completely broke down.', example_ko_2 = '협상이 완전히 결렬된 후 무역 금수 조치가 부과됐어요.', example_en_3 = 'The embargo has prevented the country from exporting its main products.', example_ko_3 = '금수 조치가 그 나라가 주요 상품을 수출하는 것을 막았어요.', example_en_4 = 'The embargo was lifted after the country agreed to disarm.', example_ko_4 = '나라가 무장 해제에 동의한 후 금수 조치가 해제됐어요.', example_en_5 = 'Humanitarian goods are exempt from the trade embargo.', example_ko_5 = '인도주의적 물자는 무역 금수 조치에서 제외돼요.' WHERE id = 'w_news_B2_16';

UPDATE words SET example_en_2 = 'The UN offered to provide mediation in the dispute.', example_ko_2 = '유엔이 분쟁에서 조정을 제공하겠다고 제안했어요.', example_en_3 = 'Without effective mediation the talks could collapse again.', example_ko_3 = '효과적인 조정 없이는 회담이 다시 결렬될 수 있어요.', example_en_4 = 'Both parties agreed to accept mediation from a neutral country.', example_ko_4 = '양 당사자가 중립국의 조정을 받아들이기로 합의했어요.', example_en_5 = 'Successful mediation requires trust from both sides of the conflict.', example_ko_5 = '성공적인 조정은 분쟁 양측의 신뢰가 필요해요.' WHERE id = 'w_news_B2_17';

UPDATE words SET example_en_2 = 'Social media is accelerating political polarization in many countries.', example_ko_2 = '소셜 미디어가 많은 나라에서 정치적 양극화를 가속화하고 있어요.', example_en_3 = 'Polarization makes it nearly impossible for parties to compromise.', example_ko_3 = '양극화는 정당들이 타협하는 것을 거의 불가능하게 만들어요.', example_en_4 = 'The polarization of the electorate worried many political scientists.', example_ko_4 = '유권자의 양극화가 많은 정치학자들을 우려하게 했어요.', example_en_5 = 'Reducing polarization requires dialogue across the political divide.', example_ko_5 = '양극화를 줄이려면 정치적 분열을 넘는 대화가 필요해요.' WHERE id = 'w_news_B2_18';

UPDATE words SET example_en_2 = 'The two sides are fighting to control the political narrative.', example_ko_2 = '양측이 정치적 서사를 통제하기 위해 싸우고 있어요.', example_en_3 = 'The government''s narrative about the economy was challenged by economists.', example_ko_3 = '경제에 대한 정부의 서사가 경제학자들에 의해 도전받았어요.', example_en_4 = 'A powerful narrative can shape public attitudes for generations.', example_ko_4 = '강력한 서사는 세대를 넘어 대중의 태도를 형성할 수 있어요.', example_en_5 = 'The documentary offered a counter-narrative to the official story.', example_ko_5 = '그 다큐멘터리는 공식 이야기에 대한 반서사를 제시했어요.' WHERE id = 'w_news_B2_19';

UPDATE words SET example_en_2 = 'Transparency in public spending would help rebuild trust in government.', example_ko_2 = '공공 지출의 투명성이 정부에 대한 신뢰를 회복하는 데 도움이 될 거예요.', example_en_3 = 'The new law requires greater transparency from campaign donors.', example_ko_3 = '새 법은 선거 후원자들에게 더 큰 투명성을 요구해요.', example_en_4 = 'Lack of transparency led to widespread suspicion about the result.', example_ko_4 = '투명성 부족이 결과에 대한 광범위한 의혹을 낳았어요.', example_en_5 = 'International observers praised the election''s transparency.', example_ko_5 = '국제 관찰자들이 선거의 투명성을 칭찬했어요.' WHERE id = 'w_news_B2_20';

UPDATE words SET example_en_2 = 'The minister dismissed the allegations as politically motivated.', example_ko_2 = '장관은 혐의를 정치적 동기에 의한 것이라고 일축했어요.', example_en_3 = 'New allegations of corruption emerged in the latest report.', example_ko_3 = '최신 보고서에서 새로운 부패 혐의가 나왔어요.', example_en_4 = 'The allegations were investigated by an independent watchdog.', example_ko_4 = '혐의는 독립 감시 기관에 의해 조사됐어요.', example_en_5 = 'Serious allegations have damaged public trust in the judiciary.', example_ko_5 = '심각한 혐의가 사법부에 대한 공공 신뢰를 훼손했어요.' WHERE id = 'w_news_B2_21';

UPDATE words SET example_en_2 = 'The ratification process has been delayed by opposition in parliament.', example_ko_2 = '비준 절차가 의회의 반대로 지연됐어요.', example_en_3 = 'Ratification by all member states is required for the accord to take effect.', example_ko_3 = '협약이 발효하려면 모든 회원국의 비준이 필요해요.', example_en_4 = 'The senate voted in favor of ratification of the trade deal.', example_ko_4 = '상원이 무역 협정 비준에 찬성 표결을 했어요.', example_en_5 = 'Without ratification the agreement has no legal force.', example_ko_5 = '비준 없이는 협정에 법적 효력이 없어요.' WHERE id = 'w_news_B2_22';

UPDATE words SET example_en_2 = 'The resolution was blocked after one country exercised its veto.', example_ko_2 = '한 나라가 거부권을 행사한 후 결의안이 저지됐어요.', example_en_3 = 'The threat of a veto made negotiators water down their proposals.', example_ko_3 = '거부권 위협이 협상가들로 하여금 제안을 약화시키도록 만들었어요.', example_en_4 = 'The veto power of permanent members is controversial at the UN.', example_ko_4 = '상임이사국의 거부권 행사는 유엔에서 논란이 되고 있어요.', example_en_5 = 'Reformers want to limit the use of the veto in humanitarian crises.', example_ko_5 = '개혁론자들은 인도주의적 위기에서 거부권 사용을 제한하고 싶어해요.' WHERE id = 'w_news_B2_23';

UPDATE words SET example_en_2 = 'The party''s credibility has been severely damaged by the scandal.', example_ko_2 = '당의 신뢰성이 스캔들로 심각하게 훼손됐어요.', example_en_3 = 'The government needs to restore its credibility with voters.', example_ko_3 = '정부는 유권자들과의 신뢰성을 회복해야 해요.', example_en_4 = 'Credibility depends on actions, not just words.', example_ko_4 = '신뢰성은 말만이 아니라 행동에 달려 있어요.', example_en_5 = 'The report lent credibility to claims of misconduct.', example_ko_5 = '보고서가 비위 주장에 신뢰성을 부여했어요.' WHERE id = 'w_news_B2_24';

UPDATE words SET example_en_2 = 'The president argued that his mandate gave him the right to act.', example_ko_2 = '대통령은 자신의 권한이 행동할 권리를 줬다고 주장했어요.', example_en_3 = 'The party''s large majority gave it a clear mandate to reform.', example_ko_3 = '당의 큰 과반수가 개혁을 위한 명확한 권한을 줬어요.', example_en_4 = 'The UN mandate required troops to protect civilians.', example_ko_4 = '유엔 권한은 군이 민간인을 보호하도록 요구했어요.', example_en_5 = 'Without a proper mandate, the government cannot implement major changes.', example_ko_5 = '적절한 권한 없이는 정부가 주요 변화를 시행할 수 없어요.' WHERE id = 'w_news_B2_25';

UPDATE words SET example_en_2 = 'Dissent within the party has grown as elections approach.', example_ko_2 = '선거가 다가오면서 당 내 반대 의견이 커졌어요.', example_en_3 = 'The general was accused of suppressing political dissent.', example_ko_3 = '장군은 정치적 반대 의견을 탄압했다는 비난을 받았어요.', example_en_4 = 'A culture of dissent is vital for a functioning democracy.', example_ko_4 = '기능하는 민주주의에는 반대 의견 문화가 필수적이에요.', example_en_5 = 'Several ministers expressed dissent over the new austerity plan.', example_ko_5 = '여러 장관이 새 긴축 계획에 대한 반대 의견을 표명했어요.' WHERE id = 'w_news_B2_26';

UPDATE words SET example_en_2 = 'The diplomat worked for months to broker a ceasefire.', example_ko_2 = '외교관이 수개월 동안 휴전 중재를 위해 노력했어요.', example_en_3 = 'The two sides asked the UN to broker an agreement.', example_ko_3 = '양측이 유엔에게 협정 중재를 요청했어요.', example_en_4 = 'A regional organization offered to broker peace talks.', example_ko_4 = '지역 기구가 평화 회담 중재를 제안했어요.', example_en_5 = 'She played a critical role in brokering the landmark deal.', example_ko_5 = '그녀는 역사적인 협정 중재에서 중요한 역할을 했어요.' WHERE id = 'w_news_B2_27';

UPDATE words SET example_en_2 = 'A broad consensus on climate action proved difficult to achieve.', example_ko_2 = '기후 행동에 대한 광범위한 합의를 이루는 것은 어렵다는 것이 밝혀졌어요.', example_en_3 = 'The party leadership built consensus before announcing the new policy.', example_ko_3 = '당 지도부가 새 정책을 발표하기 전에 합의를 이끌어냈어요.', example_en_4 = 'Scientific consensus on the causes of climate change is overwhelming.', example_ko_4 = '기후 변화 원인에 대한 과학적 합의는 압도적이에요.', example_en_5 = 'Reaching consensus among twenty-seven member states took years.', example_ko_5 = '27개 회원국 사이에서 합의에 도달하는 데 몇 년이 걸렸어요.' WHERE id = 'w_news_B2_28';

UPDATE words SET example_en_2 = 'Calls for military intervention were rejected by the Security Council.', example_ko_2 = '군사 개입에 대한 요구가 안보리에 의해 거부됐어요.', example_en_3 = 'Early intervention could have prevented the crisis from worsening.', example_ko_3 = '조기 개입이 위기가 악화되는 것을 막을 수 있었을 거예요.', example_en_4 = 'The government opposed foreign intervention in its internal affairs.', example_ko_4 = '정부는 내정에 대한 외국의 개입에 반대했어요.', example_en_5 = 'Humanitarian intervention is justified when civilian lives are at risk.', example_ko_5 = '민간인의 생명이 위험에 처했을 때 인도주의적 개입이 정당화돼요.' WHERE id = 'w_news_B2_29';

UPDATE words SET example_en_2 = 'The talks appeared to reach an impasse over the security issue.', example_ko_2 = '회담이 안보 문제로 교착 상태에 빠진 것처럼 보였어요.', example_en_3 = 'The impasse was broken when both sides made new concessions.', example_ko_3 = '양측이 새로운 양보를 하자 교착 상태가 해소됐어요.', example_en_4 = 'A diplomatic impasse can sometimes last for decades.', example_ko_4 = '외교적 교착 상태는 때로는 수십 년간 지속될 수 있어요.', example_en_5 = 'Mediators worked to find a way past the political impasse.', example_ko_5 = '조정자들이 정치적 교착 상태를 극복할 방법을 찾기 위해 노력했어요.' WHERE id = 'w_news_B2_30';

UPDATE words SET example_en_2 = 'The annexation was condemned in a UN General Assembly resolution.', example_ko_2 = '합병은 유엔 총회 결의안에서 규탄됐어요.', example_en_3 = 'The annexation of the territory was declared illegal under international law.', example_ko_3 = '그 영토의 합병은 국제법상 불법이라고 선언됐어요.', example_en_4 = 'The annexation triggered an international sanctions regime.', example_ko_4 = '합병이 국제 제재 체제를 촉발했어요.', example_en_5 = 'The annexation fundamentally changed the map of the region.', example_ko_5 = '합병이 그 지역의 지도를 근본적으로 바꿨어요.' WHERE id = 'w_news_B2_31';

UPDATE words SET example_en_2 = 'A rebel faction within the military attempted to seize power.', example_ko_2 = '군 내 반란 파벌이 권력을 장악하려 했어요.', example_en_3 = 'The hardline faction opposed any compromise with the opposition.', example_ko_3 = '강경 파벌은 야당과의 어떠한 타협도 반대했어요.', example_en_4 = 'The ruling party is divided between two powerful factions.', example_ko_4 = '집권당은 두 강력한 파벌로 나뉘어 있어요.', example_en_5 = 'A faction of the movement broke away and formed a new party.', example_ko_5 = '운동의 한 파벌이 분리되어 새로운 정당을 만들었어요.' WHERE id = 'w_news_B2_32';

UPDATE words SET example_en_2 = 'All fighting must cease before aid can be delivered.', example_ko_2 = '원조가 전달되기 전에 모든 전투가 중단되어야 해요.', example_en_3 = 'Protests ceased after the government agreed to open talks.', example_ko_3 = '정부가 회담 개시에 동의한 후 시위가 멈췄어요.', example_en_4 = 'The organization ceased operations after losing funding.', example_ko_4 = '단체는 자금을 잃은 후 운영을 중단했어요.', example_en_5 = 'Violence must cease immediately for the ceasefire to hold.', example_ko_5 = '휴전이 유지되려면 폭력이 즉각 중단되어야 해요.' WHERE id = 'w_news_B2_33';

UPDATE words SET example_en_2 = 'Several human rights groups denounced the treatment of prisoners.', example_ko_2 = '여러 인권 단체들이 수감자 처우를 규탄했어요.', example_en_3 = 'The opposition denounced the election results as fraudulent.', example_ko_3 = '야당은 선거 결과를 사기라고 규탄했어요.', example_en_4 = 'World leaders denounced the attack as an act of terrorism.', example_ko_4 = '세계 지도자들이 그 공격을 테러 행위라고 규탄했어요.', example_en_5 = 'The journalist publicly denounced the government''s censorship.', example_ko_5 = '기자가 공개적으로 정부의 검열을 규탄했어요.' WHERE id = 'w_news_B2_34';

UPDATE words SET example_en_2 = 'The opposition coalition demanded fresh elections.', example_ko_2 = '야당 연합이 새로운 선거를 요구했어요.', example_en_3 = 'The ruling coalition survived a vote of no confidence.', example_ko_3 = '집권 연합이 불신임 투표를 통과했어요.', example_en_4 = 'Building a coalition of disparate parties proved very difficult.', example_ko_4 = '다양한 정당의 연합을 구성하는 것은 매우 어렵다는 것이 밝혀졌어요.', example_en_5 = 'A broad coalition united behind the candidate for change.', example_ko_5 = '광범위한 연합이 변화의 후보를 지지하기 위해 단결했어요.' WHERE id = 'w_news_B2_35';

-- ══════════════════════════════════════
-- C1 (35 words)
-- ══════════════════════════════════════

UPDATE words SET example_en_2 = 'American hegemony in global finance has long shaped trade norms.', example_ko_2 = '글로벌 금융에서 미국의 패권이 오랫동안 무역 규범을 형성해 왔어요.', example_en_3 = 'Analysts debate whether China will eventually challenge US hegemony.', example_ko_3 = '분석가들은 중국이 결국 미국의 패권에 도전할지를 논의해요.', example_en_4 = 'Military hegemony does not guarantee soft-power dominance.', example_ko_4 = '군사적 패권이 소프트파워 지배를 보장하지는 않아요.', example_en_5 = 'The summit was seen as a challenge to Western hegemony.', example_ko_5 = '정상 회담은 서방의 패권에 대한 도전으로 여겨졌어요.' WHERE id = 'w_news_C1_01';

UPDATE words SET example_en_2 = 'The foreign minister cited realpolitik in defending the deal.', example_ko_2 = '외무 장관이 협정을 옹호하면서 현실 정치를 언급했어요.', example_en_3 = 'Realpolitik often demands uncomfortable alliances.', example_ko_3 = '현실 정치는 종종 불편한 동맹을 요구해요.', example_en_4 = 'Critics accused the government of abandoning principles for realpolitik.', example_ko_4 = '비평가들은 정부가 현실 정치를 위해 원칙을 버렸다고 비난했어요.', example_en_5 = 'Realpolitik shaped the alliance decisions of the Cold War era.', example_ko_5 = '현실 정치가 냉전 시대의 동맹 결정을 형성했어요.' WHERE id = 'w_news_C1_02';

UPDATE words SET example_en_2 = 'The extraterritorial reach of the law upset several allied governments.', example_ko_2 = '그 법의 역외 범위가 여러 동맹 정부를 화나게 했어요.', example_en_3 = 'Companies fear extraterritorial sanctions imposed by Washington.', example_ko_3 = '기업들은 워싱턴이 부과하는 역외 제재를 두려워해요.', example_en_4 = 'The treaty limits the extraterritorial powers of each signatory.', example_ko_4 = '조약은 각 서명국의 역외 권한을 제한해요.', example_en_5 = 'Extraterritorial enforcement raises complex sovereignty questions.', example_ko_5 = '역외 집행은 복잡한 주권 문제를 제기해요.' WHERE id = 'w_news_C1_03';

UPDATE words SET example_en_2 = 'The ruling advanced international jurisprudence on crimes against humanity.', example_ko_2 = '그 판결은 반인도적 범죄에 관한 국제 법리학을 발전시켰어요.', example_en_3 = 'She specialized in the jurisprudence of human rights treaties.', example_ko_3 = '그녀는 인권 조약의 법리학을 전공했어요.', example_en_4 = 'The case raised fundamental questions of constitutional jurisprudence.', example_ko_4 = '그 사건은 헌법 법리학의 근본적인 질문을 제기했어요.', example_en_5 = 'Comparative jurisprudence reveals how different systems handle similar crimes.', example_ko_5 = '비교 법리학은 다른 시스템이 유사한 범죄를 어떻게 처리하는지 보여줘요.' WHERE id = 'w_news_C1_04';

UPDATE words SET example_en_2 = 'Multilateralism faces its greatest test in decades as tensions rise.', example_ko_2 = '긴장이 고조되면서 다자주의가 수십 년 만에 가장 큰 시험에 직면했어요.', example_en_3 = 'Critics argue that multilateralism has failed to prevent conflicts.', example_ko_3 = '비평가들은 다자주의가 분쟁을 막는 데 실패했다고 주장해요.', example_en_4 = 'Multilateralism requires great powers to sacrifice short-term interests.', example_ko_4 = '다자주의는 강대국들이 단기적 이익을 희생할 것을 요구해요.', example_en_5 = 'The summit reaffirmed the parties'' commitment to multilateralism.', example_ko_5 = '정상 회담은 당사국들의 다자주의에 대한 의지를 재확인했어요.' WHERE id = 'w_news_C1_05';

UPDATE words SET example_en_2 = 'The tribunal''s verdict set a powerful precedent for future cases.', example_ko_2 = '재판소의 판결은 향후 사건에 강력한 선례를 남겼어요.', example_en_3 = 'This court has never before seen a precedent for this situation.', example_ko_3 = '이 법원은 이런 상황에 대한 선례를 전혀 본 적이 없어요.', example_en_4 = 'The legislation overturned a precedent dating back to the 1950s.', example_ko_4 = '입법이 1950년대로 거슬러 올라가는 선례를 뒤집었어요.', example_en_5 = 'Lawyers argued the court should not follow the existing precedent.', example_ko_5 = '변호사들은 법원이 기존 선례를 따르지 말아야 한다고 주장했어요.' WHERE id = 'w_news_C1_06';

UPDATE words SET example_en_2 = 'The case fell outside the court''s territorial jurisdiction.', example_ko_2 = '그 사건은 법원의 영토 관할권 밖에 있었어요.', example_en_3 = 'The treaty established shared jurisdiction over certain maritime disputes.', example_ko_3 = '조약은 특정 해양 분쟁에 대한 공동 관할권을 확립했어요.', example_en_4 = 'Questions of jurisdiction complicated the extradition process.', example_ko_4 = '관할권 문제가 범죄인 인도 절차를 복잡하게 만들었어요.', example_en_5 = 'Universal jurisdiction allows states to prosecute certain crimes globally.', example_ko_5 = '보편적 관할권은 국가가 특정 범죄를 전 세계적으로 기소할 수 있게 해요.' WHERE id = 'w_news_C1_07';

UPDATE words SET example_en_2 = 'The ratification of the accord was blocked by the upper house.', example_ko_2 = '협약의 비준이 상원에 의해 저지됐어요.', example_en_3 = 'Slow ratification has delayed the treaty coming into force.', example_ko_3 = '느린 비준이 조약 발효를 지연시켰어요.', example_en_4 = 'Domestic politics often complicate the ratification of international treaties.', example_ko_4 = '국내 정치는 종종 국제 조약의 비준을 복잡하게 만들어요.', example_en_5 = 'The ratification vote was closer than many had expected.', example_ko_5 = '비준 표결은 많은 사람들이 예상했던 것보다 더 접전이었어요.' WHERE id = 'w_news_C1_08';

UPDATE words SET example_en_2 = 'The oil embargo was designed to pressure the regime into talks.', example_ko_2 = '석유 금수 조치는 정권을 회담으로 압박하기 위해 설계됐어요.', example_en_3 = 'Lifting the embargo required compliance with all UN resolutions.', example_ko_3 = '금수 조치 해제는 모든 유엔 결의안 준수가 필요했어요.', example_en_4 = 'An arms embargo was imposed after evidence of atrocities emerged.', example_ko_4 = '잔학 행위의 증거가 나온 후 무기 금수 조치가 부과됐어요.', example_en_5 = 'Enforcing an embargo requires cooperation from many trading partners.', example_ko_5 = '금수 조치를 집행하려면 많은 무역 파트너들의 협력이 필요해요.' WHERE id = 'w_news_C1_09';

UPDATE words SET example_en_2 = 'Extended deterrence requires credible commitments from allies.', example_ko_2 = '확장 억제는 동맹국들의 신뢰할 수 있는 약속이 필요해요.', example_en_3 = 'Conventional deterrence was seen as insufficient against cyberattacks.', example_ko_3 = '재래식 억제는 사이버 공격에는 불충분한 것으로 여겨졌어요.', example_en_4 = 'The threat of economic sanctions acts as a form of deterrence.', example_ko_4 = '경제 제재의 위협이 억제의 한 형태로 작용해요.', example_en_5 = 'Deterrence relies on the adversary believing the threat is real.', example_ko_5 = '억제는 적이 위협이 실제라고 믿는 데 달려 있어요.' WHERE id = 'w_news_C1_10';

UPDATE words SET example_en_2 = 'The pipeline''s route carries huge geopolitical implications.', example_ko_2 = '그 파이프라인의 경로는 엄청난 지정학적 함의를 가지고 있어요.', example_en_3 = 'The analyst warned of growing geopolitical risks in the region.', example_ko_3 = '분석가는 그 지역에서 지정학적 위험이 커지고 있다고 경고했어요.', example_en_4 = 'Geopolitical competition is reshaping investment in emerging markets.', example_ko_4 = '지정학적 경쟁이 신흥 시장에 대한 투자를 재편하고 있어요.', example_en_5 = 'The election outcome will have significant geopolitical consequences.', example_ko_5 = '선거 결과는 중요한 지정학적 결과를 가져올 거예요.' WHERE id = 'w_news_C1_11';

UPDATE words SET example_en_2 = 'The prime minister''s bellicose language alarmed neighboring states.', example_ko_2 = '총리의 호전적인 언어가 인접 국가들을 불안하게 했어요.', example_en_3 = 'A bellicose posture can signal strength but risks escalation.', example_ko_3 = '호전적인 자세는 강인함을 신호할 수 있지만 확전의 위험이 있어요.', example_en_4 = 'The bellicose speech was condemned by international partners.', example_ko_4 = '호전적인 연설이 국제 파트너들에 의해 규탄됐어요.', example_en_5 = 'Critics accused the president of a bellicose foreign policy.', example_ko_5 = '비평가들은 대통령이 호전적인 외교 정책을 추구한다고 비난했어요.' WHERE id = 'w_news_C1_12';

UPDATE words SET example_en_2 = 'Political scientists warn that the country is sliding toward oligarchy.', example_ko_2 = '정치학자들은 그 나라가 과두 정치로 미끄러지고 있다고 경고해요.', example_en_3 = 'A small oligarchy controls the country''s major media outlets.', example_ko_3 = '소수의 과두 세력이 나라의 주요 미디어를 통제해요.', example_en_4 = 'Economic oligarchy can undermine democratic institutions.', example_ko_4 = '경제적 과두 지배는 민주주의 제도를 약화시킬 수 있어요.', example_en_5 = 'The revolution was meant to end the oligarchy but replaced it with another.', example_ko_5 = '혁명은 과두 정치를 끝내기 위한 것이었지만 또 다른 것으로 대체됐어요.' WHERE id = 'w_news_C1_13';

UPDATE words SET example_en_2 = 'The missile strike was carried out as a reprisal for the bombing.', example_ko_2 = '미사일 공격은 폭격에 대한 보복으로 감행됐어요.', example_en_3 = 'Human rights groups warned against reprisal attacks on civilians.', example_ko_3 = '인권 단체들이 민간인에 대한 보복 공격에 경고했어요.', example_en_4 = 'Fear of reprisal prevents many people from speaking to journalists.', example_ko_4 = '보복에 대한 두려움이 많은 사람들이 기자들에게 말하는 것을 막아요.', example_en_5 = 'Economic reprisal was threatened if the deal was not honored.', example_ko_5 = '협정이 이행되지 않으면 경제적 보복이 위협됐어요.' WHERE id = 'w_news_C1_14';

UPDATE words SET example_en_2 = 'The journalist was charged with subversion after criticizing the government.', example_ko_2 = '기자는 정부를 비판한 후 체제 전복 혐의로 기소됐어요.', example_en_3 = 'Charges of subversion are often used to silence political opposition.', example_ko_3 = '체제 전복 혐의는 종종 정치적 반대를 침묵시키는 데 사용돼요.', example_en_4 = 'The report documented years of alleged subversion by foreign agents.', example_ko_4 = '보고서는 외국 요원들의 수년간 혐의받는 체제 전복을 기록했어요.', example_en_5 = 'Anti-subversion laws have been criticized as tools of repression.', example_ko_5 = '반체제 전복법은 탄압의 도구로 비판받아왔어요.' WHERE id = 'w_news_C1_15';

UPDATE words SET example_en_2 = 'Both superpowers funded proxy groups to fight on their behalf.', example_ko_2 = '두 강대국 모두 자신들을 대신해 싸울 대리 세력을 지원했어요.', example_en_3 = 'The conflict has many characteristics of a proxy war.', example_ko_3 = '분쟁은 대리전의 특성을 많이 가지고 있어요.', example_en_4 = 'A proxy vote was submitted on behalf of the absent member.', example_ko_4 = '부재 회원을 대신하여 위임 투표가 제출됐어요.', example_en_5 = 'The senator voted by proxy due to illness.', example_ko_5 = '상원 의원은 병으로 인해 위임 투표를 했어요.' WHERE id = 'w_news_C1_16';

UPDATE words SET example_en_2 = 'The country was ostracized from international forums for years.', example_ko_2 = '그 나라는 수년간 국제 포럼에서 추방됐어요.', example_en_3 = 'She was ostracized by her party for breaking ranks.', example_ko_3 = '그녀는 이탈 행위로 인해 당에서 따돌림을 당했어요.', example_en_4 = 'The regime was effectively ostracized from the global financial system.', example_ko_4 = '정권은 사실상 글로벌 금융 시스템에서 추방됐어요.', example_en_5 = 'Diplomatic ostracism rarely changes a regime''s core behavior.', example_ko_5 = '외교적 추방은 정권의 핵심 행동을 좀처럼 바꾸지 못해요.' WHERE id = 'w_news_C1_17';

UPDATE words SET example_en_2 = 'The treaty aims to halt the proliferation of ballistic missiles.', example_ko_2 = '조약은 탄도 미사일 확산을 막는 것을 목표로 해요.', example_en_3 = 'The proliferation of fake news threatens informed democracy.', example_ko_3 = '가짜 뉴스의 확산이 정보에 기반한 민주주의를 위협해요.', example_en_4 = 'Analysts fear the proliferation of armed factions in the region.', example_ko_4 = '분석가들은 그 지역에서 무장 파벌의 확산을 두려워해요.', example_en_5 = 'Nuclear proliferation remains a defining security challenge of our time.', example_ko_5 = '핵 확산은 우리 시대의 결정적인 안보 도전으로 남아 있어요.' WHERE id = 'w_news_C1_18';

UPDATE words SET example_en_2 = 'The military junta announced it would hold elections in two years.', example_ko_2 = '군사 정권은 2년 내에 선거를 열겠다고 발표했어요.', example_en_3 = 'The junta banned political parties and arrested opposition leaders.', example_ko_3 = '군사 정권이 정당을 금지하고 야당 지도자들을 체포했어요.', example_en_4 = 'International sanctions were imposed on the junta after the coup.', example_ko_4 = '쿠데타 이후 군사 정권에 국제 제재가 부과됐어요.', example_en_5 = 'The junta''s grip on power weakened as protests grew.', example_ko_5 = '시위가 커지면서 군사 정권의 권력 장악이 약해졌어요.' WHERE id = 'w_news_C1_19';

UPDATE words SET example_en_2 = 'The new voter ID rules will disenfranchise many elderly citizens.', example_ko_2 = '새 유권자 신분증 규정이 많은 노인 시민들의 선거권을 박탈할 거예요.', example_en_3 = 'Economic hardship can effectively disenfranchise working-class voters.', example_ko_3 = '경제적 어려움이 사실상 노동 계층 유권자들의 선거권을 박탈할 수 있어요.', example_en_4 = 'The law was challenged in court for attempting to disenfranchise minorities.', example_ko_4 = '그 법은 소수 집단의 선거권을 박탈하려 한다는 이유로 법원에서 이의 제기됐어요.', example_en_5 = 'Critics say gerrymandering is used to disenfranchise entire communities.', example_ko_5 = '비평가들은 게리맨더링이 지역 사회 전체의 선거권을 박탈하는 데 사용된다고 말해요.' WHERE id = 'w_news_C1_20';

UPDATE words SET example_en_2 = 'The international criminal tribunal began hearing evidence today.', example_ko_2 = '국제 형사 재판소가 오늘 증거 청취를 시작했어요.', example_en_3 = 'The tribunal was established specifically to investigate war crimes.', example_ko_3 = '재판소는 전쟁 범죄를 조사하기 위해 특별히 설립됐어요.', example_en_4 = 'Several generals were indicted by the tribunal for crimes against civilians.', example_ko_4 = '여러 장군이 민간인에 대한 범죄로 재판소에 기소됐어요.', example_en_5 = 'The tribunal''s proceedings were broadcast to the public.', example_ko_5 = '재판소의 절차가 공개적으로 방송됐어요.' WHERE id = 'w_news_C1_21';

UPDATE words SET example_en_2 = 'Determining culpability for the disaster took years of investigation.', example_ko_2 = '재난에 대한 유책성 결정에 수년간의 조사가 걸렸어요.', example_en_3 = 'The inquiry examined the culpability of both the company and the regulator.', example_ko_3 = '조사는 회사와 규제 기관 모두의 유책성을 검토했어요.', example_en_4 = 'Shared culpability made it difficult to assign individual blame.', example_ko_4 = '공동 유책성은 개인의 잘못을 지정하는 것을 어렵게 만들었어요.', example_en_5 = 'The verdict established the culpability of the entire leadership.', example_ko_5 = '판결은 전체 지도부의 유책성을 확립했어요.' WHERE id = 'w_news_C1_22';

UPDATE words SET example_en_2 = 'The concessions were seen by hardliners as a capitulation.', example_ko_2 = '강경파들은 양보를 굴복으로 봤어요.', example_en_3 = 'Total capitulation was never an option for the negotiating team.', example_ko_3 = '완전한 굴복은 협상 팀에게 결코 선택지가 아니었어요.', example_en_4 = 'The prime minister''s reversal was described as a capitulation to pressure.', example_ko_4 = '총리의 입장 번복은 압력에 대한 굴복으로 묘사됐어요.', example_en_5 = 'Strategic capitulation can sometimes preserve longer-term interests.', example_ko_5 = '전략적 굴복이 때로는 장기적 이익을 보존할 수 있어요.' WHERE id = 'w_news_C1_23';

UPDATE words SET example_en_2 = 'Descendants of colonial subjects are demanding reparations.', example_ko_2 = '식민지 신민의 후손들이 배상을 요구하고 있어요.', example_en_3 = 'The conference debated whether reparations could heal historical wounds.', example_ko_3 = '회의에서 배상이 역사적 상처를 치유할 수 있는지 논의됐어요.', example_en_4 = 'Reparations after the war ran into billions of dollars.', example_ko_4 = '전쟁 이후 배상금은 수십억 달러에 달했어요.', example_en_5 = 'The government rejected all calls for colonial reparations.', example_ko_5 = '정부는 식민지 배상에 대한 모든 요구를 거부했어요.' WHERE id = 'w_news_C1_24';

UPDATE words SET example_en_2 = 'The acquittal came after new DNA evidence was presented to the court.', example_ko_2 = '새로운 DNA 증거가 법원에 제출된 후 무죄 선고가 내려졌어요.', example_en_3 = 'The prosecution vowed to appeal the acquittal.', example_ko_3 = '검찰은 무죄 선고에 항소하겠다고 다짐했어요.', example_en_4 = 'The high-profile acquittal led to calls for judicial reform.', example_ko_4 = '세간의 이목을 끈 무죄 선고가 사법 개혁 요구로 이어졌어요.', example_en_5 = 'After the acquittal, she spoke to the press for the first time.', example_ko_5 = '무죄 선고 후 그녀는 처음으로 언론에 이야기했어요.' WHERE id = 'w_news_C1_25';

UPDATE words SET example_en_2 = 'The opposition accused the judiciary of complicity in the cover-up.', example_ko_2 = '야당은 사법부가 은폐에 공모했다고 비난했어요.', example_en_3 = 'Evidence of official complicity undermined the government''s credibility.', example_ko_3 = '공식 공모의 증거가 정부의 신뢰성을 약화시켰어요.', example_en_4 = 'The investigation found no evidence of complicity among senior officials.', example_ko_4 = '조사에서 고위 관리들 사이의 공모 증거가 발견되지 않았어요.', example_en_5 = 'The court found the officer guilty of complicity in the attack.', example_ko_5 = '법원은 장교가 공격에 공모한 것에 대해 유죄로 판결했어요.' WHERE id = 'w_news_C1_26';

UPDATE words SET example_en_2 = 'The rapprochement between the two rivals surprised the diplomatic community.', example_ko_2 = '두 경쟁국 사이의 화해가 외교계를 놀라게 했어요.', example_en_3 = 'Trade was reopened as part of a gradual rapprochement process.', example_ko_3 = '무역이 점진적인 관계 개선 과정의 일환으로 재개됐어요.', example_en_4 = 'The rapprochement ended decades of diplomatic isolation.', example_ko_4 = '화해가 수십 년간의 외교적 고립을 끝냈어요.', example_en_5 = 'Cultural exchanges are often the first step toward rapprochement.', example_ko_5 = '문화 교류는 종종 화해를 향한 첫 걸음이에요.' WHERE id = 'w_news_C1_27';

UPDATE words SET example_en_2 = 'The crackdown involved coercive interrogation methods.', example_ko_2 = '단속에는 강압적인 심문 방법이 포함됐어요.', example_en_3 = 'The law was condemned for its coercive effect on free speech.', example_ko_3 = '그 법은 표현의 자유에 대한 강압적인 효과로 규탄됐어요.', example_en_4 = 'Coercive diplomacy can work but risks serious miscalculation.', example_ko_4 = '강압적 외교는 효과가 있을 수 있지만 심각한 오판의 위험이 있어요.', example_en_5 = 'The committee ruled that the confession was obtained through coercive means.', example_ko_5 = '위원회는 자백이 강압적인 수단을 통해 얻어졌다고 판결했어요.' WHERE id = 'w_news_C1_28';

UPDATE words SET example_en_2 = 'The senator''s demagogue tactics polarized the electorate.', example_ko_2 = '상원 의원의 선동가 전술이 유권자들을 양극화했어요.', example_en_3 = 'A skilled demagogue can exploit economic anxiety to gain power.', example_ko_3 = '능숙한 선동가는 경제적 불안을 이용해 권력을 얻을 수 있어요.', example_en_4 = 'History shows that demagogues often rise during periods of crisis.', example_ko_4 = '역사는 선동가들이 종종 위기 기간에 부상함을 보여줘요.', example_en_5 = 'Calling someone a demagogue does not itself disprove their arguments.', example_ko_5 = '누군가를 선동가라고 부르는 것이 그들의 주장을 반증하지는 않아요.' WHERE id = 'w_news_C1_29';

UPDATE words SET example_en_2 = 'The peace process broke down because of the government''s intransigence.', example_ko_2 = '평화 과정이 정부의 완고함 때문에 결렬됐어요.', example_en_3 = 'Analysts blamed mutual intransigence for the failure of negotiations.', example_ko_3 = '분석가들은 협상 실패를 상호 비타협성 탓으로 돌렸어요.', example_en_4 = 'The president''s intransigence blocked any chance of compromise.', example_ko_4 = '대통령의 완고함이 타협의 어떤 가능성도 차단했어요.', example_en_5 = 'Critics point to the minister''s intransigence as a key obstacle.', example_ko_5 = '비평가들은 장관의 비타협성을 주요 장애물로 지적해요.' WHERE id = 'w_news_C1_30';

UPDATE words SET example_en_2 = 'The union won major concessions after weeks of strike action.', example_ko_2 = '노동 조합이 수주간의 파업 행동 끝에 큰 양보를 얻어냈어요.', example_en_3 = 'The government made limited concessions to end the protest.', example_ko_3 = '정부가 시위를 끝내기 위해 제한적인 양보를 했어요.', example_en_4 = 'Both sides must make concessions for a deal to be possible.', example_ko_4 = '협상이 가능하려면 양측이 양보를 해야 해요.', example_en_5 = 'Concessions on trade were seen as necessary to secure the alliance.', example_ko_5 = '동맹을 확보하기 위해 무역에서의 양보가 필요한 것으로 여겨졌어요.' WHERE id = 'w_news_C1_31';

UPDATE words SET example_en_2 = 'The asymmetric nature of the conflict favors smaller guerrilla units.', example_ko_2 = '분쟁의 비대칭적 특성이 소규모 게릴라 부대에 유리해요.', example_en_3 = 'Asymmetric warfare poses new challenges for conventional militaries.', example_ko_3 = '비대칭 전쟁은 재래식 군대에 새로운 도전을 제기해요.', example_en_4 = 'The power asymmetric between the two parties made talks unequal.', example_ko_4 = '두 당사자 사이의 권력 비대칭이 회담을 불평등하게 만들었어요.', example_en_5 = 'Asymmetric information can give one side a decisive advantage.', example_ko_5 = '비대칭 정보는 한 측에게 결정적인 우위를 줄 수 있어요.' WHERE id = 'w_news_C1_32';

UPDATE words SET example_en_2 = 'The minister''s incendiary comments were widely condemned.', example_ko_2 = '장관의 선동적인 발언이 광범위하게 규탄됐어요.', example_en_3 = 'The newspaper editorial was accused of publishing incendiary rhetoric.', example_ko_3 = '신문 사설이 선동적인 수사를 게재했다는 비난을 받았어요.', example_en_4 = 'Incendiary language from leaders can provoke violence on the streets.', example_ko_4 = '지도자들의 선동적인 언어가 거리에서 폭력을 유발할 수 있어요.', example_en_5 = 'The broadcaster was fined for airing incendiary propaganda.', example_ko_5 = '방송사는 선동적인 선전을 방송한 것에 대해 벌금을 받았어요.' WHERE id = 'w_news_C1_33';

UPDATE words SET example_en_2 = 'Budget sequestration forced agencies to cut services immediately.', example_ko_2 = '예산 강제 삭감으로 기관들이 즉시 서비스를 삭감해야 했어요.', example_en_3 = 'Asset sequestration was used to recover stolen state funds.', example_ko_3 = '유용된 국가 자금을 회수하기 위해 자산 동결이 사용됐어요.', example_en_4 = 'The court ordered the sequestration of the company''s overseas assets.', example_ko_4 = '법원이 회사의 해외 자산 동결을 명령했어요.', example_en_5 = 'The jury was placed in sequestration during the high-profile trial.', example_ko_5 = '배심원단이 세간의 주목을 받은 재판 동안 격리됐어요.' WHERE id = 'w_news_C1_34';

UPDATE words SET example_en_2 = 'The judge issued a peremptory instruction to the jury.', example_ko_2 = '판사가 배심원단에 강압적인 지시를 내렸어요.', example_en_3 = 'A peremptory challenge allows lawyers to dismiss potential jurors.', example_ko_3 = '기피 신청은 변호사가 잠재적 배심원을 기각할 수 있게 해요.', example_en_4 = 'His peremptory tone in negotiations angered the other side.', example_ko_4 = '협상에서 그의 강압적인 어조가 상대방을 화나게 했어요.', example_en_5 = 'The peremptory dismissal of the evidence surprised the courtroom.', example_ko_5 = '증거의 강압적인 기각이 법정을 놀라게 했어요.' WHERE id = 'w_news_C1_35';

