-- ============================================================
-- C2-level Collocations and Idioms — Batch 1
-- Topics: cafe, work, travel, home, shopping
-- 5 collocations + 5 idioms per topic = 50 total entries
-- ============================================================

-- ============================================================
-- CAFE — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_cafe_C2_01', 'savor', 'aroma', 'savor the aroma', '향을 음미하다', 'smell', '향이나 맛을 천천히 즐길 때 ''savor''를 써요. ''smell''은 단순히 냄새를 맡는 의미라서 격이 떨어져요.', 'She paused to savor the aroma of the freshly ground Ethiopian beans.', '그녀는 잠시 멈춰 갓 갈아낸 에티오피아 원두의 향을 음미했어요.', 'Connoisseurs savor the aroma before taking the first sip.', '감정가들은 첫 모금을 마시기 전에 향을 음미해요.', 'C2', 'cafe', 3, 'coffee aroma'),
('col_cafe_C2_02', 'cultivate', 'palate', 'cultivate a palate', '미각을 기르다', 'make', '미각이나 취향을 시간을 들여 발달시킨다는 격식 있는 표현이에요. 와인, 커피, 음식 비평에서 자주 써요.', 'Years of tasting rare brews have helped him cultivate a discerning palate.', '수년간 희귀한 커피를 시음하며 그는 까다로운 미각을 길렀어요.', 'A sommelier must cultivate a palate sensitive to the subtlest notes.', '소믈리에는 미묘한 향에도 예민한 미각을 길러야 해요.', 'C2', 'cafe', 3, 'coffee tasting'),
('col_cafe_C2_03', 'frequent', 'establishment', 'frequent an establishment', '한 가게를 자주 다니다', 'visit', '카페나 식당 같은 가게를 자주 방문한다는 문어체 표현이에요. ''visit''보다 훨씬 격식 있어요.', 'Literary figures of the era frequented the establishment on Boulevard Saint-Germain.', '그 시대의 문인들은 생제르맹 대로의 그 가게를 자주 드나들었어요.', 'He has frequented this establishment for over two decades.', '그는 20년 넘게 이 가게를 다니고 있어요.', 'C2', 'cafe', 3, 'cafe interior'),
('col_cafe_C2_04', 'exude', 'ambiance', 'exude ambiance', '분위기를 자아내다', 'have', '공간이 특정한 분위기를 강하게 풍긴다는 뜻이에요. 인테리어 평론이나 여행 기사에 자주 등장해요.', 'The candlelit corner exudes an ambiance reminiscent of 1920s Vienna.', '촛불이 켜진 그 구석은 1920년대 빈을 연상시키는 분위기를 풍겨요.', 'Their flagship cafe exudes an ambiance of understated luxury.', '그들의 플래그십 카페는 은은한 고급스러움의 분위기를 자아내요.', 'C2', 'cafe', 3, 'candlelit cafe'),
('col_cafe_C2_05', 'extol', 'virtues', 'extol the virtues', '장점을 극찬하다', 'praise', '무언가의 장점을 강하게, 또는 다소 과장되게 칭찬할 때 써요. 격식 있고 약간 비꼬는 뉘앙스도 가능해요.', 'The barista extolled the virtues of single-origin Geisha coffee.', '바리스타는 싱글 오리진 게이샤 커피의 장점을 극찬했어요.', 'Critics have long extolled the virtues of slow brewing.', '비평가들은 오랫동안 슬로우 브루잉의 장점을 극찬해 왔어요.', 'C2', 'cafe', 3, 'barista pour over')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- CAFE — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_cafe_C2_01', 'an acquired taste', '천천히 좋아하게 되는 것', '습득된 맛', '처음에는 별로지만 익숙해지면서 좋아하게 되는 음식이나 취향을 말해요. 격식 있는 대화나 글에서 사람의 성격에도 비유적으로 써요.', 'Espresso is very much an acquired taste for most newcomers.', '에스프레소는 대부분의 입문자에게 천천히 좋아하게 되는 맛이에요.', 'Their avant-garde menu is an acquired taste, but devotees swear by it.', '그들의 전위적인 메뉴는 익숙해져야 좋아지는 맛이지만, 단골들은 극찬해요.', 'His dry humor is an acquired taste.', '그의 무미건조한 유머는 익숙해져야 좋아지는 스타일이에요.', 'C2', 'cafe', 3, 'espresso cup', 1),
('idm_cafe_C2_02', 'the proof of the pudding is in the eating', '직접 해봐야 안다', '푸딩의 증거는 먹는 데 있다', '말이나 외관만으로는 알 수 없고, 실제 결과로만 평가할 수 있다는 격언이에요. 비즈니스 회의나 격식 있는 토론에 적절해요.', 'Their marketing is impressive, but the proof of the pudding is in the eating.', '마케팅은 인상적이지만, 결국 직접 맛봐야 알 수 있어요.', 'They claim to roast the finest beans in the city — well, the proof of the pudding is in the eating.', '그들은 시내 최고의 원두를 로스팅한다고 주장하는데, 직접 마셔봐야 알겠죠.', 'The proof of the pudding is in the eating, so let us taste the new blend.', '직접 해봐야 아는 법이니, 새 블렌드를 시음해 봅시다.', 'C2', 'cafe', 3, 'pudding dessert', 2),
('idm_cafe_C2_03', 'take something with a grain of salt', '걸러서 듣다', '소금 한 알과 함께 받아들이다', '들은 정보를 완전히 믿지 말고 의심하며 받아들이라는 뜻이에요. 평론, 리뷰, 비즈니스 보고서 등에서 자주 써요.', 'Take online cafe reviews with a grain of salt — many are sponsored.', '온라인 카페 리뷰는 걸러서 보세요. 많은 게 협찬이에요.', 'I would take his claim of ''the best coffee in town'' with a grain of salt.', '''시내 최고의 커피''라는 그의 주장은 걸러 들을 거예요.', 'Critics'' verdicts should be taken with a grain of salt.', '비평가들의 평결은 걸러서 받아들여야 해요.', 'C2', 'cafe', 3, 'salt grain', 3),
('idm_cafe_C2_04', 'wake up and smell the coffee', '현실을 직시하다', '깨어나서 커피 향을 맡다', '상대방이 현실을 모르거나 외면할 때, 정신 차리라는 뉘앙스로 써요. 다소 단호한 격식 표현이라 직장에서 신중하게 써야 해요.', 'It is time to wake up and smell the coffee — the market has shifted dramatically.', '이제 현실을 직시할 때예요. 시장이 극적으로 변했어요.', 'He needs to wake up and smell the coffee about his declining sales.', '그는 감소하는 매출에 대해 현실을 직시해야 해요.', 'Wake up and smell the coffee: independent cafes are thriving again.', '현실을 직시해요. 독립 카페가 다시 부흥하고 있어요.', 'C2', 'cafe', 3, 'morning coffee', 4),
('idm_cafe_C2_05', 'spill the beans', '비밀을 누설하다', '콩을 쏟다', '비밀이나 숨겨둔 정보를 무심코, 혹은 일부러 말해버린다는 뜻이에요. 격식과 비격식 모두에서 폭넓게 써요.', 'Over a quiet espresso, she finally spilled the beans about the merger.', '조용한 에스프레소 한 잔을 두고 그녀는 마침내 합병에 대한 비밀을 털어놨어요.', 'Please do not spill the beans before the official announcement.', '공식 발표 전에 비밀을 누설하지 마세요.', 'The journalist spilled the beans on the chain''s closure plans.', '기자는 그 체인점의 폐점 계획을 폭로했어요.', 'C2', 'cafe', 3, 'coffee beans', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- WORK — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_work_C2_01', 'exercise', 'discretion', 'exercise discretion', '재량을 발휘하다', 'use', '재량껏 판단해서 결정한다는 격식 있는 표현이에요. 비즈니스, 법률, 정책 문서에서 표준이에요.', 'Managers are expected to exercise discretion when handling client complaints.', '관리자들은 고객 불만을 처리할 때 재량을 발휘해야 해요.', 'The judge exercised discretion in reducing the sentence.', '판사는 형량을 줄이는 데 재량을 발휘했어요.', 'C2', 'work', 3, 'executive office'),
('col_work_C2_02', 'garner', 'support', 'garner support', '지지를 얻다', 'get', '시간과 노력을 들여 지지나 인정을 모은다는 뜻이에요. 정치, 비즈니스 기사에서 자주 보여요.', 'The proposal garnered widespread support across departments.', '그 제안은 부서 전반에 걸쳐 폭넓은 지지를 얻었어요.', 'She garnered the board''s support for the restructuring plan.', '그녀는 구조조정 계획에 대해 이사회의 지지를 얻었어요.', 'C2', 'work', 3, 'boardroom meeting'),
('col_work_C2_03', 'exert', 'influence', 'exert influence', '영향력을 행사하다', 'have', '의도적으로 영향력을 작용시킨다는 격식 표현이에요. ''have influence''보다 능동적이고 강한 뉘앙스예요.', 'Senior partners exert considerable influence over hiring decisions.', '시니어 파트너들은 채용 결정에 상당한 영향력을 행사해요.', 'Lobbyists exert influence behind the scenes.', '로비스트들은 뒤에서 영향력을 행사해요.', 'C2', 'work', 3, 'corporate negotiation'),
('col_work_C2_04', 'spearhead', 'initiative', 'spearhead an initiative', '주도하다', 'lead', '새 프로젝트나 운동을 가장 앞장서서 이끈다는 뜻이에요. 임원급 업적을 설명할 때 적절해요.', 'She spearheaded the diversity initiative across the firm''s global offices.', '그녀는 회사 전 세계 지사에 걸쳐 다양성 이니셔티브를 주도했어요.', 'He has spearheaded several pioneering initiatives in fintech.', '그는 핀테크 분야에서 여러 선구적인 이니셔티브를 주도했어요.', 'C2', 'work', 3, 'leadership conference'),
('col_work_C2_05', 'mitigate', 'risk', 'mitigate risk', '위험을 완화하다', 'reduce', '리스크의 영향이나 가능성을 체계적으로 줄인다는 의미예요. 금융, 컨설팅, 감사 보고서의 표준 표현이에요.', 'The new compliance framework is designed to mitigate operational risk.', '새 컴플라이언스 체계는 운영 리스크를 완화하기 위해 설계됐어요.', 'Diversification helps mitigate investment risk.', '분산 투자는 투자 위험을 완화하는 데 도움이 돼요.', 'C2', 'work', 3, 'risk management chart')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- WORK — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_work_C2_01', 'throw someone under the bus', '동료를 희생시키다', '누군가를 버스 밑으로 던지다', '자신의 이익을 위해 동료나 부하를 배신해 책임을 떠넘긴다는 뜻이에요. 사내 정치 대화에서 자주 등장해요.', 'He threw his junior analyst under the bus to save his own reputation.', '그는 자기 평판을 지키려고 후배 애널리스트를 희생시켰어요.', 'I refuse to throw my team under the bus, even if it costs me the promotion.', '승진을 못 하더라도 저는 팀원들을 희생시키지 않을 거예요.', 'The CEO threw the entire department under the bus during the press conference.', 'CEO는 기자회견에서 부서 전체를 희생시켰어요.', 'C2', 'work', 3, 'office betrayal', 1),
('idm_work_C2_02', 'play hardball', '강경하게 나가다', '하드볼을 하다', '협상이나 경쟁에서 단호하고 양보 없는 태도를 취한다는 뜻이에요. M&A, 협상 기사에 자주 나와요.', 'The acquirer is prepared to play hardball during the final round of negotiations.', '인수자는 협상 최종 라운드에서 강경하게 나갈 준비가 돼 있어요.', 'If they play hardball, we will need to escalate to legal counsel.', '그들이 강경하게 나오면, 법무팀까지 동원해야 할 거예요.', 'She knows when to play hardball and when to compromise.', '그녀는 언제 강경하게 나가고 언제 타협할지 알아요.', 'C2', 'work', 3, 'negotiation table', 2),
('idm_work_C2_03', 'burn the candle at both ends', '과로하다', '양초를 양쪽에서 태우다', '낮과 밤 모두 일하거나 무리해서 건강을 해친다는 뜻이에요. 격식 있는 자리에서도 자연스럽게 써요.', 'She has been burning the candle at both ends to meet the IPO deadline.', '그녀는 IPO 마감을 맞추려고 양쪽으로 태우듯 과로하고 있어요.', 'You cannot burn the candle at both ends indefinitely without burning out.', '번아웃 없이 영원히 과로할 수는 없어요.', 'Junior associates often burn the candle at both ends during deal season.', '주니어들은 딜 시즌에 종종 양쪽으로 태우듯 일해요.', 'C2', 'work', 3, 'candle burning', 3),
('idm_work_C2_04', 'move the goalposts', '기준을 바꾸다', '골대를 옮기다', '약속이나 합의 후에 일방적으로 조건이나 기대치를 바꾼다는 비판적 표현이에요. 협상이나 평가 맥락에서 자주 써요.', 'It is frustrating when management keeps moving the goalposts on bonus criteria.', '경영진이 보너스 기준을 자꾸 바꾸는 게 답답해요.', 'They moved the goalposts halfway through the project.', '그들은 프로젝트 중간에 기준을 바꿔버렸어요.', 'Do not let the client move the goalposts after the contract is signed.', '계약 체결 후에 고객이 기준을 바꾸지 못하게 하세요.', 'C2', 'work', 3, 'soccer goalpost', 4),
('idm_work_C2_05', 'cut corners', '날림으로 하다', '모서리를 자르다', '비용이나 시간을 아끼려고 절차를 생략하거나 대충 한다는 뜻이에요. 품질 관리나 컴플라이언스 논의에서 자주 써요.', 'Cutting corners on safety protocols is simply not negotiable.', '안전 절차에서 날림으로 하는 건 절대 용납할 수 없어요.', 'The contractor cut corners, and the audit revealed serious deficiencies.', '도급업체가 날림으로 일해서 감사에서 심각한 결함이 드러났어요.', 'Resist the temptation to cut corners under deadline pressure.', '마감 압박 속에서 날림으로 하려는 유혹을 이겨내세요.', 'C2', 'work', 3, 'construction site', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TRAVEL — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_travel_C2_01', 'embark', 'journey', 'embark on a journey', '여정을 시작하다', 'start', '뜻깊은 여행이나 모험을 시작한다는 문학적이고 격식 있는 표현이에요. 단순한 ''start''보다 훨씬 의미가 깊어요.', 'They embarked on a transcontinental journey aboard the Trans-Siberian Railway.', '그들은 시베리아 횡단철도를 타고 대륙 횡단 여정을 시작했어요.', 'She embarked on a solo journey through Patagonia.', '그녀는 파타고니아를 가로지르는 홀로 여정을 시작했어요.', 'C2', 'travel', 3, 'train journey'),
('col_travel_C2_02', 'traverse', 'continent', 'traverse a continent', '대륙을 횡단하다', 'cross', '광활한 지역을 가로질러 이동한다는 격식 있는 동사예요. 여행 회고록이나 다큐멘터리에 자주 등장해요.', 'The explorers traversed the African continent on foot.', '탐험가들은 도보로 아프리카 대륙을 횡단했어요.', 'Few have traversed the continent of Antarctica unsupported.', '도움 없이 남극 대륙을 횡단한 사람은 거의 없어요.', 'C2', 'travel', 3, 'desert expedition'),
('col_travel_C2_03', 'immerse', 'oneself', 'immerse oneself in culture', '문화에 흠뻑 빠지다', 'enjoy', '단순히 즐기는 것이 아니라 그 문화에 깊이 몰입한다는 의미예요. 여행 에세이나 인터뷰에 어울려요.', 'He spent six months in Kyoto immersing himself in tea ceremony culture.', '그는 교토에서 여섯 달을 보내며 다도 문화에 흠뻑 빠졌어요.', 'To learn a language, you must immerse yourself in the culture.', '언어를 배우려면 그 문화에 흠뻑 빠져야 해요.', 'C2', 'travel', 3, 'tea ceremony'),
('col_travel_C2_04', 'savor', 'experience', 'savor the experience', '경험을 음미하다', 'enjoy', '경험을 천천히 깊이 즐긴다는 격식 있는 표현이에요. 여행, 미식, 공연 후기에 적절해요.', 'Rather than rushing through Rome, take time to savor the experience.', '로마를 서둘러 둘러보지 말고, 천천히 경험을 음미해 보세요.', 'They savored every moment of their once-in-a-lifetime safari.', '그들은 일생에 한 번뿐인 사파리의 모든 순간을 음미했어요.', 'C2', 'travel', 3, 'safari sunset'),
('col_travel_C2_05', 'venture', 'territory', 'venture into uncharted territory', '미지의 영역으로 나아가다', 'go', '잘 알려지지 않은 곳으로 위험을 무릅쓰고 나아간다는 뜻이에요. 비유적으로 비즈니스에서도 자주 써요.', 'The expedition ventured into uncharted territory deep in the Amazon basin.', '탐험대는 아마존 분지 깊숙한 미지의 영역으로 나아갔어요.', 'By launching the new line, the brand ventured into uncharted territory.', '새 라인을 출시하며 그 브랜드는 미지의 영역에 발을 들였어요.', 'C2', 'travel', 3, 'amazon jungle')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TRAVEL — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_travel_C2_01', 'off the beaten path', '잘 알려지지 않은 곳', '다져진 길에서 벗어난', '관광객이 잘 가지 않는 한적하고 진정성 있는 장소를 가리켜요. 여행 잡지에서 빈번하게 등장해요.', 'For an authentic experience, seek out restaurants off the beaten path.', '진짜 경험을 원한다면, 잘 알려지지 않은 식당을 찾아보세요.', 'The village lies entirely off the beaten path, untouched by mass tourism.', '그 마을은 대중 관광에 닿지 않은, 완전히 외진 곳에 있어요.', 'She prefers destinations off the beaten path to crowded resorts.', '그녀는 붐비는 리조트보다 한적한 곳을 선호해요.', 'C2', 'travel', 3, 'remote village', 1),
('idm_travel_C2_02', 'the world is your oyster', '세상은 당신 것이다', '세상은 당신의 굴이다', '원하는 것을 무엇이든 이룰 기회가 활짝 열려 있다는 뜻이에요. 졸업 축사나 격려의 자리에 자주 등장하는 셰익스피어 유래 표현이에요.', 'With your skills and ambition, the world is your oyster.', '당신의 능력과 야망이라면, 세상은 당신 것이에요.', 'After receiving the scholarship, she felt the world was her oyster.', '장학금을 받은 후, 그녀는 세상이 자기 것 같았어요.', 'For a fresh graduate fluent in three languages, the world is your oyster.', '3개 국어가 유창한 신입생에게 세상은 활짝 열린 무대예요.', 'C2', 'travel', 3, 'oyster shell', 2),
('idm_travel_C2_03', 'live out of a suitcase', '여행하며 살다', '여행 가방에서 꺼내 살다', '집에 머무르지 못하고 계속 여행하며 산다는 뜻이에요. 글로벌 컨설턴트, 외교관, 저널리스트의 삶을 묘사할 때 적합해요.', 'As a foreign correspondent, she has lived out of a suitcase for years.', '해외 특파원으로서 그녀는 수년간 여행 가방 하나로 살아왔어요.', 'Consultants often live out of a suitcase, flying between clients each week.', '컨설턴트들은 매주 고객사 사이를 오가며 여행 가방 하나로 살곤 해요.', 'After a decade of living out of a suitcase, he settled in Lisbon.', '10년간 여행하며 살다가 그는 리스본에 정착했어요.', 'C2', 'travel', 3, 'suitcase packed', 3),
('idm_travel_C2_04', 'a stone''s throw away', '아주 가까운', '돌을 던지면 닿을 거리', '걸어서 매우 가깝다는 격식 있고 우아한 표현이에요. 부동산 광고나 여행 가이드에 자주 등장해요.', 'The boutique hotel is a stone''s throw away from the Louvre.', '그 부티크 호텔은 루브르 박물관에서 아주 가까워요.', 'Our villa is a stone''s throw away from the Mediterranean coast.', '저희 빌라는 지중해 해안에서 정말 가까워요.', 'The cathedral stands a stone''s throw away from the central square.', '대성당은 중앙 광장에서 엎어지면 코 닿을 거리예요.', 'C2', 'travel', 3, 'cobblestone street', 4),
('idm_travel_C2_05', 'wanderlust takes hold', '여행 욕구가 솟다', '방랑벽이 사로잡다', '갑자기 강렬한 여행 욕구가 생긴다는 문학적이고 격식 있는 표현이에요. 회고록이나 에세이에 잘 어울려요.', 'Each spring, wanderlust takes hold and she begins planning her next adventure.', '매년 봄이면 방랑벽이 솟구쳐 그녀는 다음 모험을 계획해요.', 'After reading the travelogue, wanderlust took hold of him completely.', '여행기를 읽고 나니 그는 여행 욕구에 완전히 사로잡혔어요.', 'When wanderlust takes hold, no spreadsheet can keep me at my desk.', '방랑벽이 솟구치면 어떤 스프레드시트도 저를 책상에 붙잡지 못해요.', 'C2', 'travel', 3, 'wanderer mountain', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- HOME — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_home_C2_01', 'exude', 'warmth', 'exude warmth', '따스함이 흘러나오다', 'have', '공간이나 사람이 따스한 분위기를 자연스럽게 풍긴다는 표현이에요. 인테리어 잡지에서 자주 봐요.', 'The reclaimed-oak interiors exude warmth and quiet sophistication.', '재생 오크로 마감한 인테리어는 따스함과 차분한 세련됨을 풍겨요.', 'Her countryside cottage exudes warmth from every corner.', '그녀의 시골 코티지는 구석구석에서 따스함이 흘러나와요.', 'C2', 'home', 3, 'cozy cottage'),
('col_home_C2_02', 'epitomize', 'elegance', 'epitomize elegance', '우아함의 전형이 되다', 'show', '특정 사물이 우아함의 완벽한 본보기라는 격식 있는 표현이에요. 디자인 비평에서 표준이에요.', 'The marble foyer epitomizes timeless elegance.', '대리석 현관은 시대를 초월한 우아함의 전형이에요.', 'Her interior choices epitomize understated elegance.', '그녀의 인테리어 선택은 절제된 우아함의 전형이에요.', 'C2', 'home', 3, 'marble foyer'),
('col_home_C2_03', 'cultivate', 'ambiance', 'cultivate ambiance', '분위기를 조성하다', 'make', '의도적으로 시간을 들여 특정한 분위기를 만들어 낸다는 뜻이에요. 호스피탈리티 분야에서 자주 써요.', 'Dim lighting and soft jazz cultivate an intimate ambiance for guests.', '은은한 조명과 부드러운 재즈가 손님을 위한 친밀한 분위기를 조성해요.', 'They have cultivated an ambiance that feels both refined and welcoming.', '그들은 세련되면서도 환영하는 분위기를 조성했어요.', 'C2', 'home', 3, 'living room ambient'),
('col_home_C2_04', 'evoke', 'nostalgia', 'evoke nostalgia', '향수를 불러일으키다', 'remind', '과거에 대한 그리움을 강하게 떠올리게 한다는 격식 표현이에요. 디자인, 영화, 음악 평론에 어울려요.', 'The vintage wallpaper evokes nostalgia for postwar Parisian apartments.', '빈티지 벽지는 전후 파리 아파트에 대한 향수를 불러일으켜요.', 'Family photographs lining the hallway evoke a deep sense of nostalgia.', '복도에 걸린 가족 사진들은 깊은 향수를 불러일으켜요.', 'C2', 'home', 3, 'vintage wallpaper'),
('col_home_C2_05', 'preserve', 'heritage', 'preserve a heritage', '유산을 보존하다', 'keep', '문화적, 가문의 유산을 의식적으로 지킨다는 격식 표현이에요. 역사적 주택, 박물관 글에 자주 보여요.', 'The family has painstakingly preserved the heritage of the eighteenth-century manor.', '그 가문은 18세기 저택의 유산을 정성껏 보존해 왔어요.', 'Architects worked closely with historians to preserve the building''s heritage.', '건축가들은 건물의 유산을 보존하기 위해 역사학자들과 긴밀히 협업했어요.', 'C2', 'home', 3, 'heritage manor')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- HOME — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_home_C2_01', 'an Englishman''s home is his castle', '집은 자신만의 성이다', '영국인의 집은 그의 성이다', '집은 외부의 간섭으로부터 완전히 보호되는 사적 공간이라는 영국 격언이에요. 프라이버시나 거주 권리 논쟁에서 인용돼요.', 'As they say, an Englishman''s home is his castle — privacy is sacrosanct.', '말 그대로 집은 자신만의 성이고, 사생활은 신성불가침이에요.', 'The court invoked the principle that an Englishman''s home is his castle.', '법원은 집은 자신만의 성이라는 원칙을 인용했어요.', 'He maintains, in the truest sense, that an Englishman''s home is his castle.', '그는 가장 진정한 의미에서 집은 자신만의 성이라고 믿어요.', 'C2', 'home', 3, 'english manor', 1),
('idm_home_C2_02', 'home is where the heart is', '마음이 있는 곳이 집이다', '집은 마음이 있는 곳이다', '물리적 장소보다 사랑하는 사람들이 있는 곳이 진정한 집이라는 뜻이에요. 격식 있는 연설이나 글에서 자주 인용돼요.', 'After years abroad, he realized that home is truly where the heart is.', '오랜 해외 생활 끝에 그는 마음이 있는 곳이 진짜 집이라는 걸 깨달았어요.', 'For her, home is where the heart is — wherever her family gathers.', '그녀에게 가족이 모이는 곳, 그곳이 진짜 집이에요.', 'They moved often, but home was always where the heart is.', '그들은 자주 이사했지만, 집은 늘 마음이 있는 곳이었어요.', 'C2', 'home', 3, 'family gathering', 2),
('idm_home_C2_03', 'a roof over one''s head', '머물 곳', '머리 위의 지붕', '최소한의 거처나 살 곳을 가리키는 격식 있는 표현이에요. 사회 정책, 자선 캠페인 글에 자주 등장해요.', 'The charity ensures that every family has a roof over their head this winter.', '그 자선단체는 올겨울 모든 가정이 머물 곳을 갖게 보장해요.', 'She worked three jobs to keep a roof over her children''s heads.', '그녀는 아이들에게 머물 곳을 마련해 주려고 세 가지 일을 했어요.', 'Having a roof over one''s head should be a basic right, not a privilege.', '머물 곳을 갖는 건 특권이 아니라 기본 권리여야 해요.', 'C2', 'home', 3, 'rooftop house', 3),
('idm_home_C2_04', 'hit close to home', '뼈아프게 와닿다', '집 가까이에 맞다', '어떤 이야기나 사건이 자신의 경험과 너무 비슷해서 마음을 깊이 흔든다는 뜻이에요. 격식 있는 토론에서도 자연스러워요.', 'The documentary on caregiver burnout hit close to home for many viewers.', '간병인 번아웃에 관한 다큐멘터리는 많은 시청자에게 뼈아프게 와닿았어요.', 'Her speech about losing one''s parents hit close to home.', '부모를 잃는 것에 대한 그녀의 연설은 정말 와닿았어요.', 'The novel''s themes of estrangement hit close to home for him.', '소설의 소외라는 주제가 그에게 뼈아프게 와닿았어요.', 'C2', 'home', 3, 'emotional family', 4),
('idm_home_C2_05', 'put down roots', '뿌리를 내리다', '뿌리를 내리다', '한곳에 정착해 안정된 삶을 시작한다는 격식 있는 표현이에요. 이민, 정착 관련 글에 자주 등장해요.', 'After two decades of relocations, the family finally put down roots in Edinburgh.', '20년간 이사를 거듭한 끝에 그 가족은 마침내 에든버러에 뿌리를 내렸어요.', 'They put down roots in a quiet seaside town after retirement.', '그들은 은퇴 후 조용한 해변 마을에 뿌리를 내렸어요.', 'It takes courage to put down roots in an unfamiliar country.', '낯선 나라에 뿌리를 내리는 데는 용기가 필요해요.', 'C2', 'home', 3, 'tree roots', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- SHOPPING — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_shopping_C2_01', 'indulge', 'luxury', 'indulge in luxury', '사치를 누리다', 'buy', '죄책감을 약간 동반한 채 호화로움을 즐긴다는 격식 있는 표현이에요. 마케팅 카피에 자주 등장해요.', 'Once a year, she indulges in the luxury of a Savile Row bespoke suit.', '일 년에 한 번, 그녀는 새빌로 비스포크 정장이라는 사치를 누려요.', 'Travelers can indulge in the luxury of private butler service.', '여행자들은 개인 집사 서비스라는 사치를 누릴 수 있어요.', 'C2', 'shopping', 3, 'luxury boutique'),
('col_shopping_C2_02', 'scrutinize', 'quality', 'scrutinize quality', '품질을 꼼꼼히 살피다', 'check', '단순히 확인하는 게 아니라 세세한 부분까지 면밀히 검토한다는 뜻이에요. 명품, 보석, 시계 구매 맥락에 어울려요.', 'Discerning buyers scrutinize the quality of every stitch before purchase.', '안목 있는 구매자들은 구매 전 모든 박음질의 품질을 꼼꼼히 살펴요.', 'The auctioneer scrutinized the quality of the antique under a loupe.', '경매사는 루페로 골동품의 품질을 면밀히 살폈어요.', 'C2', 'shopping', 3, 'jewelry inspection'),
('col_shopping_C2_03', 'haggle', 'price', 'haggle over the price', '가격을 흥정하다', 'discuss', '가격을 두고 끈질기게 협상한다는 표현이에요. 시장, 골동품, B2B 거래에서 모두 써요.', 'Seasoned collectors haggle over the price at every Sotheby''s preview.', '노련한 수집가들은 소더비 프리뷰마다 가격을 흥정해요.', 'It is customary to haggle over the price in the souks of Marrakesh.', '마라케시 시장에서는 가격을 흥정하는 게 관례예요.', 'C2', 'shopping', 3, 'moroccan souk'),
('col_shopping_C2_04', 'incur', 'expense', 'incur an expense', '비용이 발생하다', 'pay', '비용이 자연스럽게 발생한다는 회계, 비즈니스 표준 표현이에요. ''pay''보다 훨씬 격식 있어요.', 'Importing rare vintages inevitably incurs significant expense.', '희귀 빈티지를 수입하면 상당한 비용이 불가피하게 발생해요.', 'The renovation incurred expenses well beyond the initial estimate.', '리노베이션은 초기 견적을 훨씬 넘는 비용을 발생시켰어요.', 'C2', 'shopping', 3, 'wine cellar'),
('col_shopping_C2_05', 'discern', 'value', 'discern value', '가치를 분별하다', 'see', '겉으로 잘 드러나지 않는 진정한 가치를 알아본다는 격식 표현이에요. 미술, 빈티지, 투자 맥락에 어울려요.', 'An experienced dealer can discern value where amateurs see only clutter.', '경험 많은 딜러는 아마추어가 잡동사니로만 보는 것에서 가치를 분별해요.', 'It takes years to discern value in the secondary art market.', '미술 2차 시장에서 가치를 분별하려면 수년이 걸려요.', 'C2', 'shopping', 3, 'art gallery')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- SHOPPING — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_shopping_C2_01', 'money is no object', '돈은 문제가 아니다', '돈은 대상이 아니다', '비용이 얼마든 상관없다는 격식 있는 표현이에요. 럭셔리 마케팅이나 부유한 고객 응대 맥락에 어울려요.', 'For their wedding venue, money was no object.', '결혼식 장소에 있어서 돈은 문제가 아니었어요.', 'When commissioning the yacht, money was no object to the buyer.', '요트를 주문 제작할 때, 구매자에게 돈은 문제가 아니었어요.', 'If money is no object, I would recommend the Penthouse Suite.', '돈이 문제가 아니라면, 펜트하우스 스위트룸을 추천해요.', 'C2', 'shopping', 3, 'luxury yacht', 1),
('idm_shopping_C2_02', 'pay through the nose', '바가지를 쓰다', '코를 통해 지불하다', '터무니없이 비싼 값을 치른다는 표현이에요. 격식 있는 글이나 회화 모두에서 자연스러워요.', 'Tourists often pay through the nose for souvenirs near the cathedral.', '관광객들은 대성당 근처 기념품에 종종 바가지를 써요.', 'You will pay through the nose for last-minute first-class tickets.', '막판 일등석 티켓은 바가지를 쓰게 될 거예요.', 'They paid through the nose for the limited-edition release.', '그들은 한정판 발매에 바가지를 썼어요.', 'C2', 'shopping', 3, 'expensive receipt', 2),
('idm_shopping_C2_03', 'a steal at that price', '그 가격이면 횡재', '그 가격에는 도둑질', '그 가격에 사면 너무 이득이라는 격식 있고 자연스러운 표현이에요. 명품, 골동품, 부동산 거래에 어울려요.', 'A first-edition Hemingway at that price is an absolute steal.', '그 가격에 헤밍웨이 초판본이라니, 완전 횡재예요.', 'The vintage Rolex was a steal at that price.', '그 빈티지 롤렉스는 그 가격이면 횡재였어요.', 'Given the condition, the townhouse is a steal at that price.', '상태를 고려하면, 그 타운하우스는 그 가격이면 횡재예요.', 'C2', 'shopping', 3, 'vintage watch', 3),
('idm_shopping_C2_04', 'break the bank', '돈을 너무 많이 쓰다', '은행을 부수다', '감당할 수 없을 만큼 큰 돈을 쓴다는 격식 있는 표현이에요. 부정문에서 ''파산은 아니지만 부담된다'' 식으로도 자주 써요.', 'A weekend at the spa need not break the bank.', '스파에서 보내는 주말이 꼭 무리한 지출일 필요는 없어요.', 'Refurbishing the apartment will not break the bank if we phase it carefully.', '아파트 리노베이션은 단계적으로 하면 무리한 지출은 아닐 거예요.', 'Designer pieces can break the bank if you are not selective.', '안목 없이 사면 디자이너 제품에 돈을 너무 많이 쓰게 돼요.', 'C2', 'shopping', 3, 'luxury spending', 4),
('idm_shopping_C2_05', 'on a shoestring budget', '쥐꼬리만 한 예산으로', '신발끈 예산으로', '아주 적은 예산으로 무언가를 한다는 격식 있는 표현이에요. 창업, 여행, 영화 제작 맥락에서 자주 써요.', 'They furnished the entire flat on a shoestring budget.', '그들은 쥐꼬리만 한 예산으로 아파트 전체를 꾸몄어요.', 'The indie film was produced on a shoestring budget yet won critical acclaim.', '그 독립영화는 쥐꼬리만 한 예산으로 제작됐지만 평단의 호평을 받았어요.', 'Decorating on a shoestring budget demands creativity and patience.', '쥐꼬리만 한 예산으로 꾸미려면 창의력과 인내가 필요해요.', 'C2', 'shopping', 3, 'shoestring budget', 5)
ON CONFLICT (id) DO NOTHING;
