-- ============================================================
-- C2-level Collocations and Idioms — Batch 3
-- Topics: economy, technology, environment, news, sports
-- 5 collocations + 5 idioms per topic = 50 total entries
-- ============================================================

-- ============================================================
-- ECONOMY — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_economy_C2_01', 'weather', 'downturn', 'weather a downturn', '경기 침체를 견뎌내다', 'survive', '경제적 어려움을 견뎌낸다는 격식 표현이에요. ''survive''보다 능동적으로 버틴다는 뉘앙스가 강해요.', 'Well-capitalised firms are better positioned to weather a prolonged downturn.', '자본이 탄탄한 기업들이 장기 침체를 견뎌낼 입지가 더 좋아요.', 'The conglomerate weathered the 2008 downturn without layoffs.', '그 대기업은 해고 없이 2008년 침체를 견뎌냈어요.', 'C2', 'economy', 3, 'stock market chart'),
('col_economy_C2_02', 'stimulate', 'growth', 'stimulate growth', '성장을 촉진하다', 'make', '정책이나 투자가 경제 성장을 자극한다는 표준 경제 용어예요. 금융 기사와 정책 보고서에 자주 등장해요.', 'The central bank cut rates to stimulate growth in the manufacturing sector.', '중앙은행은 제조업 성장을 촉진하기 위해 금리를 인하했어요.', 'Tax incentives are designed to stimulate growth in green industries.', '세제 혜택은 친환경 산업의 성장을 촉진하기 위해 설계됐어요.', 'C2', 'economy', 3, 'economic growth chart'),
('col_economy_C2_03', 'curb', 'inflation', 'curb inflation', '인플레이션을 억제하다', 'stop', '인플레이션의 상승세를 통제하고 억제한다는 의미예요. ''stop''은 너무 단정적이라 경제 맥락에 어울리지 않아요.', 'Aggressive rate hikes were necessary to curb runaway inflation.', '폭주하는 인플레이션을 억제하기 위해 공격적인 금리 인상이 필요했어요.', 'The new fiscal policy aims to curb inflation without triggering a recession.', '새 재정 정책은 경기 침체 없이 인플레이션을 억제하는 것이 목표예요.', 'C2', 'economy', 3, 'inflation graph'),
('col_economy_C2_04', 'hedge', 'risk', 'hedge against risk', '위험을 헤지하다', 'protect', '금융 상품으로 위험을 상쇄한다는 전문 용어예요. ''protect against''보다 정확하고 기술적이에요.', 'Institutional investors hedge against currency risk using derivatives.', '기관 투자자들은 파생상품으로 환위험을 헤지해요.', 'Gold has traditionally been used to hedge against inflation risk.', '금은 전통적으로 인플레이션 위험을 헤지하는 데 사용돼 왔어요.', 'C2', 'economy', 3, 'financial derivatives'),
('col_economy_C2_05', 'fuel', 'speculation', 'fuel speculation', '추측을 부추기다', 'cause', '소문이나 추측에 불을 지핀다는 뉘앙스예요. 시장이나 인수합병 기사에서 자주 보여요.', 'The CEO''s sudden resignation fuelled speculation about an imminent takeover.', 'CEO의 갑작스러운 사임은 임박한 인수에 대한 추측을 부추겼어요.', 'Vague guidance fuelled speculation among analysts.', '모호한 가이던스가 애널리스트들 사이에서 추측을 부추겼어요.', 'C2', 'economy', 3, 'speculation news')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ECONOMY — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_economy_C2_01', 'tighten one''s belt', '허리띠를 졸라매다', '벨트를 조이다', '지출을 줄이고 검소하게 산다는 뜻이에요. 한국어와 거의 똑같은 비유라서 격식·비격식 모두에 자연스러워요.', 'Households across the country are tightening their belts amid soaring energy costs.', '치솟는 에너지 비용 속에서 전국의 가계가 허리띠를 졸라매고 있어요.', 'The firm has had to tighten its belt following the loss of its largest client.', '그 회사는 최대 고객을 잃은 뒤 허리띠를 졸라매야 했어요.', 'Consumers tend to tighten their belts during periods of uncertainty.', '소비자들은 불확실성이 큰 시기에 허리띠를 졸라매는 경향이 있어요.', 'C2', 'economy', 3, 'belt budget', 1),
('idm_economy_C2_02', 'money talks', '돈이 말한다', '돈이 말한다', '결국 돈이 가장 큰 영향력을 발휘한다는 냉소적인 표현이에요. 정치·비즈니스 평론에서 자주 써요.', 'In lobbying circles, money talks louder than any policy paper.', '로비 업계에서는 어떤 정책 보고서보다 돈이 더 크게 말해요.', 'The deal was finalised within hours — money talks, after all.', '딜은 몇 시간 만에 마무리됐어요. 결국 돈이 말하는 거죠.', 'However noble the cause, money talks in the end.', '아무리 명분이 좋아도 결국엔 돈이 말해요.', 'C2', 'economy', 3, 'cash banknotes', 2),
('idm_economy_C2_03', 'the bottom line', '핵심은, 최종 손익', '맨 아래 줄', '회계상 최종 손익을 가리키거나, 비유적으로 ''핵심 결론''을 뜻해요. 격식 있는 회의에서 결론을 강조할 때 써요.', 'The bottom line is that without restructuring, the firm will not survive the year.', '핵심은 구조조정 없이는 회사가 올해를 못 버틴다는 거예요.', 'Investors care first and foremost about the bottom line.', '투자자들은 무엇보다 먼저 최종 손익을 신경 써요.', 'Sustainability initiatives can ultimately strengthen the bottom line.', '지속가능성 이니셔티브는 결국 손익을 강화할 수 있어요.', 'C2', 'economy', 3, 'financial statement', 3),
('idm_economy_C2_04', 'a drop in the ocean', '바다에 물 한 방울', '바다 속 물 한 방울', '엄청난 규모에 비하면 아주 미미한 양이라는 뜻이에요. 예산이나 기부 규모 논의에서 자주 등장해요.', 'A million-dollar grant is a drop in the ocean compared with the trillions needed.', '필요한 수조 달러에 비하면 백만 달러 보조금은 바다에 물 한 방울이에요.', 'Their charitable contribution, while generous, was a drop in the ocean.', '그들의 기부는 후한 편이지만 바다에 물 한 방울이었어요.', 'Tax breaks for the wealthy address only a drop in the ocean of inequality.', '부유층 세금 감면은 불평등의 바다에 물 한 방울 정도밖에 안 돼요.', 'C2', 'economy', 3, 'ocean drop', 4),
('idm_economy_C2_05', 'cash cow', '꾸준한 수익원', '현금 젖소', '꾸준히 큰 수익을 내는 사업이나 제품을 뜻해요. 비즈니스 전략 논의에서 표준 용어처럼 쓰여요.', 'The legacy software remains the company''s most reliable cash cow.', '레거시 소프트웨어는 여전히 회사의 가장 든든한 캐시카우예요.', 'Streaming subscriptions have become an unexpected cash cow for the studio.', '스트리밍 구독은 그 스튜디오에 뜻밖의 캐시카우가 됐어요.', 'Diversifying away from a single cash cow is essential for long-term resilience.', '하나의 캐시카우에서 벗어나 다각화하는 게 장기 회복력에 필수예요.', 'C2', 'economy', 3, 'dairy cow money', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TECHNOLOGY — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_technology_C2_01', 'leverage', 'innovation', 'leverage innovation', '혁신을 활용하다', 'use', '기술 혁신을 전략적으로 활용해 성과를 낸다는 비즈니스 표현이에요. ''use''보다 훨씬 격식 있고 능동적이에요.', 'Startups must leverage innovation to compete with established incumbents.', '스타트업은 기존 강자들과 경쟁하려면 혁신을 활용해야 해요.', 'The firm leveraged AI-driven innovation to streamline its supply chain.', '그 회사는 AI 기반 혁신을 활용해 공급망을 간소화했어요.', 'C2', 'technology', 3, 'innovation lab'),
('col_technology_C2_02', 'pioneer', 'advancement', 'pioneer an advancement', '발전을 선도하다', 'start', '새로운 기술 발전을 가장 먼저 개척하고 이끈다는 뜻이에요. 학술 논문과 산업 보고서에 자주 쓰여요.', 'The lab pioneered key advancements in quantum computing.', '그 연구소는 양자 컴퓨팅의 핵심 발전을 선도했어요.', 'Her team pioneered an advancement in low-power chip design.', '그녀의 팀은 저전력 칩 설계 분야의 발전을 선도했어요.', 'C2', 'technology', 3, 'research lab'),
('col_technology_C2_03', 'harness', 'algorithms', 'harness algorithms', '알고리즘을 활용하다', 'use', '복잡한 알고리즘의 힘을 효과적으로 끌어내 활용한다는 뜻이에요. AI/ML 관련 글에 표준적으로 등장해요.', 'Modern logistics firms harness algorithms to optimise delivery routes in real time.', '현대 물류 기업들은 알고리즘을 활용해 실시간으로 배송 경로를 최적화해요.', 'Researchers harness algorithms to detect anomalies in genomic data.', '연구자들은 알고리즘을 활용해 유전체 데이터의 이상을 탐지해요.', 'C2', 'technology', 3, 'algorithm code'),
('col_technology_C2_04', 'circumvent', 'security', 'circumvent security', '보안을 우회하다', 'avoid', '보안 조치를 교묘하게 우회한다는 격식 표현이에요. 사이버보안과 법률 문서에서 표준 용어예요.', 'The hackers found a novel way to circumvent the firm''s multi-factor security.', '해커들은 그 회사의 다중 인증 보안을 우회하는 새로운 방법을 찾아냈어요.', 'Insiders can sometimes circumvent security protocols undetected.', '내부자는 때때로 보안 프로토콜을 들키지 않고 우회할 수 있어요.', 'C2', 'technology', 3, 'cybersecurity breach'),
('col_technology_C2_05', 'facilitate', 'integration', 'facilitate integration', '통합을 용이하게 하다', 'help', '시스템 간 통합을 매끄럽게 만든다는 뜻이에요. IT 컨설팅과 엔터프라이즈 소프트웨어 문서에 자주 등장해요.', 'Standardised APIs facilitate seamless integration across platforms.', '표준화된 API가 플랫폼 간 매끄러운 통합을 가능하게 해요.', 'Middleware is designed to facilitate integration between legacy and cloud systems.', '미들웨어는 레거시 시스템과 클라우드 시스템 간의 통합을 용이하게 하도록 설계됐어요.', 'C2', 'technology', 3, 'system integration')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TECHNOLOGY — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_technology_C2_01', 'cutting edge', '최첨단의', '자르는 날', '가장 앞선 기술이나 분야를 뜻해요. 형용사로도 자주 쓰여요 — ''cutting-edge technology''처럼요.', 'The startup operates at the cutting edge of generative AI research.', '그 스타트업은 생성형 AI 연구의 최첨단에서 활동해요.', 'Their robotics lab is widely regarded as cutting edge.', '그들의 로봇공학 연구소는 최첨단으로 널리 인정받아요.', 'Staying at the cutting edge requires sustained R&D investment.', '최첨단에 머무르려면 지속적인 R&D 투자가 필요해요.', 'C2', 'technology', 3, 'futuristic tech', 1),
('idm_technology_C2_02', 'ahead of the curve', '앞서가는', '곡선보다 앞에', '시대나 경쟁자들보다 한발 앞서 있다는 뜻이에요. 기술 트렌드나 전략 칭찬에 적합한 격식 표현이에요.', 'Their early bet on cloud computing kept them ahead of the curve.', '클라우드 컴퓨팅에 대한 초기 투자가 그들을 앞서가게 했어요.', 'Companies that stay ahead of the curve tend to dominate emerging markets.', '앞서가는 기업들이 신흥 시장을 장악하는 경향이 있어요.', 'To remain ahead of the curve, the firm reinvests heavily in R&D.', '계속 앞서가기 위해 그 회사는 R&D에 막대하게 재투자해요.', 'C2', 'technology', 3, 'curve graph', 2),
('idm_technology_C2_03', 'on the back burner', '뒤로 미루다', '뒷쪽 화구 위에', '당장 처리하지 않고 우선순위를 낮춰 둔다는 뜻이에요. 프로젝트 관리 회의에서 매우 자주 등장해요.', 'The legacy system upgrade has been put on the back burner until next quarter.', '레거시 시스템 업그레이드는 다음 분기까지 뒤로 미뤄졌어요.', 'They placed the AI ethics review on the back burner during the product launch.', '제품 출시 기간 동안 그들은 AI 윤리 검토를 뒤로 미뤘어요.', 'Important but non-urgent initiatives often sit on the back burner.', '중요하지만 시급하지 않은 일은 종종 뒤로 미뤄지곤 해요.', 'C2', 'technology', 3, 'stove burner', 3),
('idm_technology_C2_04', 'plug and play', '바로 사용 가능한', '꽂으면 작동', '복잡한 설정 없이 바로 작동하는 시스템이나 솔루션을 뜻해요. 형용사처럼 쓰는 게 일반적이에요.', 'The new SaaS platform is essentially plug and play for mid-sized firms.', '새 SaaS 플랫폼은 중견 기업에게 사실상 플러그앤플레이예요.', 'Enterprise clients increasingly expect plug-and-play integrations.', '엔터프라이즈 고객들은 점점 더 플러그앤플레이 통합을 기대해요.', 'Few enterprise solutions are truly plug and play in practice.', '실제로 진정한 플러그앤플레이인 엔터프라이즈 솔루션은 드물어요.', 'C2', 'technology', 3, 'usb plug', 4),
('idm_technology_C2_05', 'a moving target', '계속 변하는 목표', '움직이는 표적', '기준이나 목표가 끊임없이 변해서 맞추기 어렵다는 뜻이에요. 규제, 기술 표준 논의에서 자주 써요.', 'Cybersecurity compliance is very much a moving target in this jurisdiction.', '이 관할권에서 사이버보안 컴플라이언스는 계속 변하는 목표예요.', 'Estimating user behaviour on a new platform is a moving target.', '신규 플랫폼에서의 사용자 행동을 예측하는 건 계속 변하는 목표예요.', 'Regulators are trying to hit a moving target as AI evolves rapidly.', 'AI가 빠르게 진화하면서 규제 당국은 움직이는 표적을 맞히려 애쓰고 있어요.', 'C2', 'technology', 3, 'archery target', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ENVIRONMENT — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_environment_C2_01', 'mitigate', 'emissions', 'mitigate emissions', '배출을 완화하다', 'reduce', '배출량의 영향을 완화한다는 표준 환경 용어예요. IPCC 보고서나 ESG 문서에서 표준 표현이에요.', 'Carbon capture technologies aim to mitigate industrial emissions at the source.', '탄소 포집 기술은 산업 배출을 발생원에서 완화하는 것을 목표로 해요.', 'Governments are under pressure to mitigate emissions ahead of the summit.', '정부는 정상회담을 앞두고 배출을 완화하라는 압박을 받고 있어요.', 'C2', 'environment', 3, 'factory emissions'),
('col_environment_C2_02', 'preserve', 'biodiversity', 'preserve biodiversity', '생물 다양성을 보존하다', 'keep', '생물 다양성을 적극적으로 보존한다는 학술·정책 표현이에요. ''keep''은 캐주얼해서 어울리지 않아요.', 'Protected marine reserves help preserve biodiversity in fragile ecosystems.', '해양 보호구역은 취약한 생태계의 생물 다양성을 보존하는 데 도움이 돼요.', 'Indigenous land stewardship has preserved biodiversity for millennia.', '원주민들의 토지 관리가 수천 년간 생물 다양성을 보존해 왔어요.', 'C2', 'environment', 3, 'rainforest wildlife'),
('col_environment_C2_03', 'exacerbate', 'degradation', 'exacerbate degradation', '훼손을 악화시키다', 'worsen', '환경 훼손을 더 심각하게 만든다는 격식 표현이에요. ''worsen''보다 학술 글에 더 잘 어울려요.', 'Unchecked deforestation exacerbates soil degradation across the basin.', '통제되지 않은 벌목이 유역 전반의 토양 훼손을 악화시켜요.', 'Industrial runoff exacerbates the degradation of coastal wetlands.', '산업 폐수는 연안 습지의 훼손을 악화시켜요.', 'C2', 'environment', 3, 'deforestation'),
('col_environment_C2_04', 'champion', 'sustainability', 'champion sustainability', '지속가능성을 옹호하다', 'support', '지속가능성을 앞장서서 옹호하고 추진한다는 뜻이에요. ESG 리더십을 묘사하는 표준 표현이에요.', 'The CEO has championed sustainability across the firm''s global supply chain.', 'CEO는 전 세계 공급망 전반에 걸쳐 지속가능성을 옹호해 왔어요.', 'NGOs have long championed sustainability in fashion manufacturing.', 'NGO들은 오랫동안 패션 제조에서의 지속가능성을 옹호해 왔어요.', 'C2', 'environment', 3, 'sustainability leader'),
('col_environment_C2_05', 'deplete', 'resources', 'deplete resources', '자원을 고갈시키다', 'use', '자원을 점차 고갈시킨다는 격식 환경 용어예요. ''use''는 너무 중립적이라 위기감을 전달하지 못해요.', 'Intensive agriculture rapidly depletes soil nutrients and groundwater resources.', '집약적 농업은 토양 영양분과 지하수 자원을 빠르게 고갈시켜요.', 'Overfishing has depleted resources in once-thriving coastal communities.', '남획은 한때 번성했던 연안 공동체의 자원을 고갈시켰어요.', 'C2', 'environment', 3, 'dry riverbed')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ENVIRONMENT — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_environment_C2_01', 'going green', '친환경으로 가다', '초록으로 가는 중', '개인이나 조직이 친환경 행동을 채택한다는 뜻이에요. 마케팅과 정책 글에 자주 등장해요.', 'More multinational firms are going green to meet investor expectations.', '더 많은 다국적 기업이 투자자 기대에 부응하려고 친환경으로 전환하고 있어요.', 'The city''s campaign encourages households to go green.', '그 도시의 캠페인은 가정들이 친환경으로 전환하도록 장려해요.', 'Going green is no longer optional for publicly listed companies.', '상장사에게 친환경 전환은 더 이상 선택이 아니에요.', 'C2', 'environment', 3, 'green leaves', 1),
('idm_environment_C2_02', 'a green thumb', '식물을 잘 키우는 재능', '초록색 엄지', '식물을 키우는 데 타고난 재능이 있다는 뜻이에요. 격식 있는 글에서도 부드러운 뉘앙스로 써요.', 'She has a remarkable green thumb — her urban garden flourishes year-round.', '그녀는 식물 키우는 재능이 뛰어나서 도심 정원이 일 년 내내 무성해요.', 'Not everyone is born with a green thumb, but gardening can be learned.', '모두가 식물 키우는 재능을 타고나는 건 아니지만, 정원 가꾸기는 배울 수 있어요.', 'His green thumb has transformed the rooftop into a small ecosystem.', '그의 재능 덕분에 옥상이 작은 생태계로 바뀌었어요.', 'C2', 'environment', 3, 'gardening hands', 2),
('idm_environment_C2_03', 'tree-hugger', '환경 운동가 (다소 비꼬는)', '나무 껴안는 사람', '환경 운동가를 다소 조롱조로 부르는 말이에요. 본인이 자조적으로 쓰거나 비판적 맥락에서 신중하게 써야 해요.', 'Critics dismiss the activists as tree-huggers, but the science is on their side.', '비평가들은 그 활동가들을 환경광이라 깎아내리지만, 과학은 그들 편이에요.', 'Once labelled a tree-hugger, she now advises Fortune 500 firms on ESG.', '한때 환경광이라 불렸던 그녀가 이제 포춘 500대 기업에 ESG 자문을 해요.', 'Calling someone a tree-hugger is increasingly seen as outdated.', '누군가를 트리허거라 부르는 건 점점 시대에 뒤떨어진 표현이 돼가요.', 'C2', 'environment', 3, 'tree forest', 3),
('idm_environment_C2_04', 'tip of the iceberg', '빙산의 일각', '빙산의 끝', '문제의 극히 일부만 드러난 상태를 뜻해요. 환경, 보안, 비즈니스 등 광범위한 격식 맥락에 두루 써요.', 'The reported pollution levels are merely the tip of the iceberg.', '보고된 오염 수치는 빙산의 일각에 불과해요.', 'These violations represent the tip of the iceberg of corporate malpractice.', '이런 위반은 기업 비위의 빙산의 일각이에요.', 'What we know about microplastic contamination is just the tip of the iceberg.', '우리가 미세 플라스틱 오염에 대해 아는 건 빙산의 일각이에요.', 'C2', 'environment', 3, 'iceberg ocean', 4),
('idm_environment_C2_05', 'the last straw', '인내의 한계', '마지막 지푸라기', '오랫동안 쌓여온 문제 위에 결정타가 된 일을 뜻해요. ''the straw that broke the camel''s back''의 줄임 표현이에요.', 'The oil spill was the last straw for the coastal community.', '기름 유출은 그 연안 공동체에게 인내의 한계였어요.', 'Lax enforcement was the last straw that pushed activists to litigate.', '느슨한 집행이 활동가들이 소송에 나서게 한 결정타였어요.', 'For many voters, the deforestation scandal was the last straw.', '많은 유권자에게 그 벌목 스캔들은 인내의 한계였어요.', 'C2', 'environment', 3, 'straw broken', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEWS — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_news_C2_01', 'break', 'story', 'break a story', '특종을 보도하다', 'tell', '다른 매체보다 먼저 뉴스를 보도한다는 저널리즘 표준 표현이에요. 한국어 ''특종''에 해당해요.', 'The investigative team broke the story of the offshore tax scheme.', '탐사 보도팀이 역외 탈세 스킴 특종을 보도했어요.', 'She broke the story that ultimately led to the minister''s resignation.', '그녀가 결국 장관 사임으로 이어진 특종을 보도했어요.', 'C2', 'news', 3, 'newspaper headline'),
('col_news_C2_02', 'fan', 'flames', 'fan the flames', '불에 기름을 붓다', 'increase', '논쟁이나 갈등을 더욱 격화시킨다는 비유적 표현이에요. 언론 비평에서 자주 등장해요.', 'Sensationalist coverage only fans the flames of public outrage.', '선정적인 보도는 대중의 분노에 기름만 부을 뿐이에요.', 'Anonymous leaks have fanned the flames of the diplomatic dispute.', '익명의 유출이 외교 분쟁의 불씨에 기름을 부었어요.', 'C2', 'news', 3, 'flame fire'),
('col_news_C2_03', 'sway', 'opinion', 'sway opinion', '여론을 흔들다', 'change', '여론이나 사람들의 견해를 움직인다는 격식 표현이에요. 정치 보도와 미디어 분석에 표준이에요.', 'Front-page editorials can decisively sway public opinion before an election.', '1면 사설은 선거 직전 여론을 결정적으로 흔들 수 있어요.', 'The documentary swayed opinion against the proposed pipeline.', '그 다큐멘터리는 송유관 계획에 반대하는 여론을 형성했어요.', 'C2', 'news', 3, 'public opinion poll'),
('col_news_C2_04', 'uncover', 'scandal', 'uncover a scandal', '스캔들을 폭로하다', 'find', '오랫동안 숨겨진 스캔들을 파헤쳐 드러낸다는 뜻이에요. 탐사 보도의 핵심 동사예요.', 'A junior reporter uncovered the scandal that engulfed three cabinet ministers.', '한 신참 기자가 세 명의 장관을 휩쓴 스캔들을 폭로했어요.', 'Their nine-month investigation uncovered a sprawling corruption scandal.', '그들의 9개월간의 조사가 광범위한 부패 스캔들을 폭로했어요.', 'C2', 'news', 3, 'investigative journalism'),
('col_news_C2_05', 'circulate', 'rumours', 'circulate rumours', '소문을 퍼뜨리다', 'tell', '소문이 매체나 사람들 사이에 퍼져나간다는 격식 표현이에요. ''spread''보다 좀 더 문어체예요.', 'Tabloids have been circulating rumours of the actress''s engagement for weeks.', '타블로이드들이 그 여배우의 약혼설을 몇 주째 퍼뜨리고 있어요.', 'Online forums circulated rumours that turned out to be fabricated.', '온라인 포럼에서 퍼진 소문은 조작된 것으로 드러났어요.', 'C2', 'news', 3, 'gossip tabloid')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEWS — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_news_C2_01', 'old news', '이미 다 아는 얘기', '오래된 뉴스', '더 이상 새롭지 않거나 모두가 이미 아는 정보를 뜻해요. 격식 있는 자리에서도 가볍게 쓸 수 있어요.', 'The merger rumour is old news in financial circles.', '그 합병설은 금융권에서는 이미 다 아는 얘기예요.', 'By the time the press conference was held, the announcement was old news.', '기자회견이 열렸을 때쯤엔 그 발표는 이미 다 아는 얘기였어요.', 'For seasoned analysts, the policy shift was old news.', '베테랑 애널리스트들에게 그 정책 변화는 이미 다 아는 얘기였어요.', 'C2', 'news', 3, 'old newspaper', 1),
('idm_news_C2_02', 'front page news', '대서특필감', '1면 뉴스', '큰 사건이라 신문 1면에 실릴 만하다는 뜻이에요. 비유적으로 ''엄청난 일''이라는 뉘앙스로도 써요.', 'The CEO''s indictment was front page news across every major outlet.', 'CEO의 기소는 모든 주요 매체에서 대서특필됐어요.', 'A century ago, this scientific breakthrough would have been front page news.', '한 세기 전이었다면 이 과학적 돌파구는 대서특필됐을 거예요.', 'Their wedding was front page news in the celebrity press.', '그들의 결혼은 연예 매체에서 대서특필됐어요.', 'C2', 'news', 3, 'front page headline', 2),
('idm_news_C2_03', 'no news is good news', '무소식이 희소식', '소식 없음이 좋은 소식', '연락이 없다는 건 별일 없다는 뜻이라는 격언이에요. 한국 속담과 거의 동일해서 직관적이에요.', 'Negotiations remain confidential, but no news is good news at this stage.', '협상은 여전히 비공개지만, 이 단계에서는 무소식이 희소식이에요.', 'The audit team has been silent — no news is good news, I suppose.', '감사팀이 조용한데, 무소식이 희소식이겠죠.', 'Sometimes in diplomacy, no news is good news.', '외교에서는 때때로 무소식이 희소식이에요.', 'C2', 'news', 3, 'silent phone', 3),
('idm_news_C2_04', 'hot off the press', '갓 나온 따끈따끈한 소식', '인쇄기에서 막 나온', '방금 막 발표되거나 출간된 따끈따끈한 정보라는 뜻이에요. 보고서나 책의 출시 발표에 잘 어울려요.', 'Hot off the press: the central bank has just announced an emergency rate cut.', '따끈따끈한 소식이에요. 중앙은행이 방금 긴급 금리 인하를 발표했어요.', 'The annual report is hot off the press and ready for distribution.', '연차 보고서가 막 인쇄돼서 배포 준비가 됐어요.', 'Her latest monograph, hot off the press, is already being reviewed widely.', '갓 출간된 그녀의 최신 단행본이 벌써 폭넓게 서평을 받고 있어요.', 'C2', 'news', 3, 'printing press', 4),
('idm_news_C2_05', 'a slow news day', '뉴스가 한가한 날', '느린 뉴스 날', '중요한 사건이 없어서 사소한 이야기가 뉴스를 채우는 날을 뜻해요. 언론 비평에서 자주 등장해요.', 'Such trivial coverage suggests it was a particularly slow news day.', '그런 시시한 보도를 보면 뉴스가 유난히 한가한 날이었나 봐요.', 'On a slow news day, even minor celebrity gossip makes the front page.', '뉴스가 한가한 날엔 사소한 연예 가십도 1면을 장식해요.', 'The story only gained traction because it was a slow news day.', '뉴스가 한가한 날이었기에 그 기사가 주목받은 거예요.', 'C2', 'news', 3, 'empty newsroom', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- SPORTS — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_sports_C2_01', 'demonstrate', 'prowess', 'demonstrate prowess', '기량을 보여주다', 'show', '특히 운동이나 전문 분야의 뛰어난 기량을 격식 있게 드러낸다는 표현이에요. ''show''보다 훨씬 문어체예요.', 'She demonstrated extraordinary prowess on the balance beam in the final round.', '그녀는 결선에서 평균대에서 엄청난 기량을 보여줬어요.', 'The young midfielder demonstrated tactical prowess beyond his years.', '그 어린 미드필더는 나이를 뛰어넘는 전술적 기량을 보여줬어요.', 'C2', 'sports', 3, 'athlete performance'),
('col_sports_C2_02', 'uphold', 'sportsmanship', 'uphold sportsmanship', '스포츠맨십을 지키다', 'keep', '경기 윤리를 일관되게 지킨다는 격식 표현이에요. 올림픽 헌장이나 스포츠 평론에서 자주 보여요.', 'Even in defeat, the captain upheld the highest standards of sportsmanship.', '패배 속에서도 주장은 가장 높은 수준의 스포츠맨십을 지켰어요.', 'Coaches are expected to uphold sportsmanship as a model for younger players.', '코치들은 어린 선수들의 본보기로서 스포츠맨십을 지켜야 해요.', 'C2', 'sports', 3, 'handshake sports'),
('col_sports_C2_03', 'secure', 'victory', 'secure victory', '승리를 거머쥐다', 'get', '경기 끝까지 우위를 지켜 승리를 확정한다는 격식 표현이에요. 스포츠 기사 헤드라인에 단골이에요.', 'A late penalty secured victory for the home side in injury time.', '추가 시간에 막판 페널티킥으로 홈팀이 승리를 거머쥐었어요.', 'They secured victory after a gruelling five-set match.', '그들은 격렬한 5세트 경기 끝에 승리를 거머쥐었어요.', 'C2', 'sports', 3, 'victory celebration'),
('col_sports_C2_04', 'concede', 'defeat', 'concede defeat', '패배를 인정하다', 'lose', '패배를 공식적으로, 품위 있게 인정한다는 격식 표현이에요. 스포츠와 정치 양쪽에서 자주 써요.', 'After a valiant comeback attempt, she finally conceded defeat in the fifth set.', '용감한 역전 시도 끝에 그녀는 5세트에서 결국 패배를 인정했어요.', 'The challenger conceded defeat with a gracious post-match speech.', '도전자는 경기 후 품위 있는 연설로 패배를 인정했어요.', 'C2', 'sports', 3, 'match end'),
('col_sports_C2_05', 'exhibit', 'stamina', 'exhibit stamina', '체력을 보여주다', 'show', '지구력을 격식 있게 드러낸다는 표현이에요. 스포츠 기자나 코칭 보고서에 자주 등장해요.', 'Marathon runners must exhibit remarkable stamina over the final ten kilometres.', '마라톤 선수들은 마지막 10km에서 놀라운 체력을 보여줘야 해요.', 'The veteran goalkeeper exhibited the stamina of a player half his age.', '베테랑 골키퍼는 절반 나이의 선수다운 체력을 보여줬어요.', 'C2', 'sports', 3, 'marathon runner')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- SPORTS — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_sports_C2_01', 'throw in the towel', '포기하다', '수건을 던지다', '복싱에서 유래한 표현으로, 더 이상 못 버티고 포기한다는 뜻이에요. 비즈니스 협상에서도 자주 써요.', 'After three failed funding rounds, the founders finally threw in the towel.', '세 번의 펀딩 실패 끝에 창업자들은 결국 포기했어요.', 'She refused to throw in the towel despite mounting injuries.', '쌓이는 부상에도 그녀는 포기하기를 거부했어요.', 'Throwing in the towel was not an option for the seasoned negotiator.', '노련한 협상가에게 포기란 선택지가 아니었어요.', 'C2', 'sports', 3, 'boxing towel', 1),
('idm_sports_C2_02', 'a level playing field', '공정한 경쟁의 장', '평평한 경기장', '모두에게 공평한 조건이 보장된 환경을 뜻해요. 경제·정책 토론에서 표준 격식 표현이에요.', 'Regulators are tasked with ensuring a level playing field for new entrants.', '규제 당국은 신규 진입자에게 공정한 경쟁의 장을 보장해야 해요.', 'Trade agreements aim to create a level playing field across markets.', '무역 협정은 시장 전반에 공정한 경쟁의 장을 만드는 것이 목표예요.', 'Without a level playing field, small firms cannot compete effectively.', '공정한 경쟁의 장이 없으면 소규모 기업은 효과적으로 경쟁할 수 없어요.', 'C2', 'sports', 3, 'sports field', 2),
('idm_sports_C2_03', 'on the ropes', '코너에 몰린', '로프에 기댄', '복싱에서 유래한 표현으로, 패배 직전의 곤경에 처한 상태를 뜻해요. 스포츠, 정치, 비즈니스 모두에 잘 어울려요.', 'The defending champion was on the ropes by the end of the eighth round.', '디펜딩 챔피언은 8라운드 끝 무렵 코너에 몰려 있었어요.', 'The opposition party has been on the ropes since the corruption hearings began.', '야당은 부패 청문회가 시작된 이래 코너에 몰려 있어요.', 'After two consecutive quarterly losses, the firm was on the ropes.', '연속 두 분기 손실 후 그 회사는 코너에 몰렸어요.', 'C2', 'sports', 3, 'boxing ring', 3),
('idm_sports_C2_04', 'down to the wire', '막판까지 가는', '결승선 와이어까지', '결과가 마지막 순간까지 결정되지 않을 정도로 박빙이라는 뜻이에요. 경마에서 유래했어요.', 'The election went down to the wire, with results announced after midnight.', '선거는 막판까지 갔고, 자정이 지나서야 결과가 발표됐어요.', 'The contract negotiations are likely to go down to the wire.', '계약 협상은 막판까지 갈 가능성이 높아요.', 'A photo finish — the race went right down to the wire.', '사진 판독 — 그 경주는 정말 막판까지 갔어요.', 'C2', 'sports', 3, 'finish line', 4),
('idm_sports_C2_05', 'play hardball', '강경하게 밀어붙이다', '하드볼을 하다', '야구에서 유래해, 협상이나 경쟁에서 단호하고 양보 없이 임한다는 뜻이에요. 비즈니스와 정치에 표준이에요.', 'The federation is prepared to play hardball over broadcasting rights.', '연맹은 중계권 문제로 강경하게 밀어붙일 준비가 돼 있어요.', 'When star players play hardball in contract talks, clubs often blink first.', '스타 선수들이 계약 협상에서 강경하게 나오면 구단이 먼저 양보하는 경우가 많아요.', 'She is not afraid to play hardball when the stakes are high.', '판이 클 때 그녀는 강경하게 밀어붙이는 걸 두려워하지 않아요.', 'C2', 'sports', 3, 'baseball pitch', 5)
ON CONFLICT (id) DO NOTHING;
