-- ============================================================
-- C2-level Collocations and Idioms — Batch 4
-- Topics: emotion, culture, humanities, presentation, greeting
-- 5 collocations + 5 idioms per topic = 50 total entries
-- ============================================================

-- ============================================================
-- EMOTION — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_emotion_C2_01', 'harbor', 'resentment', 'harbor resentment', '원한을 품다', 'have', '오랜 시간 마음속에 부정적 감정을 간직한다는 격식 있는 문어체 표현이에요. 문학이나 심리 분석에서 자주 보여요.', 'She had harbored resentment toward her former mentor for nearly a decade.', '그녀는 거의 10년 동안 옛 멘토에 대한 원한을 품어왔어요.', 'Harboring resentment only corrodes one''s own peace of mind.', '원한을 품는 것은 자신의 평정심을 갉아먹을 뿐이에요.', 'C2', 'emotion', 3, 'pensive woman shadow'),
('col_emotion_C2_02', 'exhibit', 'composure', 'exhibit composure', '침착함을 보이다', 'show', '위기 상황에서도 평정을 드러낸다는 격식 표현이에요. 외교, 위기 관리, 법정 보도에 적절해요.', 'The diplomat exhibited remarkable composure during the heated exchange.', '그 외교관은 격렬한 논쟁 중에도 놀라운 침착함을 보였어요.', 'She exhibited composure even as the verdict was read aloud.', '판결문이 낭독되는 순간에도 그녀는 침착함을 보였어요.', 'C2', 'emotion', 3, 'calm executive'),
('col_emotion_C2_03', 'succumb', 'despair', 'succumb to despair', '절망에 굴복하다', 'feel', '저항하다가 결국 부정적 감정에 무너진다는 문학적 표현이에요. ''succumb to''는 격식 있는 동사구예요.', 'Even in exile, the poet refused to succumb to despair.', '망명 중에도 그 시인은 절망에 굴복하기를 거부했어요.', 'After months of setbacks, he nearly succumbed to despair.', '몇 달간의 좌절 끝에 그는 거의 절망에 굴복할 뻔했어요.', 'C2', 'emotion', 3, 'lonely figure rain'),
('col_emotion_C2_04', 'evoke', 'nostalgia', 'evoke nostalgia', '향수를 불러일으키다', 'make', '기억이나 감정을 자연스럽게 떠오르게 한다는 우아한 표현이에요. 예술 평론과 광고 카피에서 자주 등장해요.', 'The faded photograph evoked a profound nostalgia for his childhood village.', '바랜 사진은 그의 어린 시절 마을에 대한 깊은 향수를 불러일으켰어요.', 'The melody evokes a quiet nostalgia in anyone who hears it.', '그 선율은 듣는 누구에게나 잔잔한 향수를 불러일으켜요.', 'C2', 'emotion', 3, 'old photograph'),
('col_emotion_C2_05', 'betray', 'emotion', 'betray emotion', '감정을 드러내다', 'show', '숨기려 했던 감정이 무심코 드러난다는 문학적 표현이에요. 표정이나 목소리가 ''배신''한다는 뉘앙스예요.', 'Her steady voice did not betray the slightest emotion.', '그녀의 차분한 목소리는 어떤 감정도 드러내지 않았어요.', 'A faint tremor in his hand betrayed his emotion.', '미세하게 떨리는 손이 그의 감정을 드러냈어요.', 'C2', 'emotion', 3, 'subtle expression')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- EMOTION — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_emotion_C2_01', 'wear one''s heart on one''s sleeve', '감정을 솔직하게 드러내다', '심장을 소매에 달고 다니다', '자신의 감정을 숨기지 않고 그대로 드러낸다는 뜻이에요. 문학과 인물 평가에서 자주 써요.', 'Unlike his stoic father, he wears his heart on his sleeve.', '금욕적인 아버지와 달리, 그는 감정을 솔직하게 드러내요.', 'Diplomats rarely wear their hearts on their sleeves.', '외교관들은 감정을 좀처럼 드러내지 않아요.', 'She has always worn her heart on her sleeve, for better or worse.', '좋든 나쁘든, 그녀는 늘 감정을 솔직하게 드러내요.', 'C2', 'emotion', 3, 'heart on sleeve', 1),
('idm_emotion_C2_02', 'bottle up feelings', '감정을 억누르다', '감정을 병에 담아두다', '감정을 표현하지 않고 속에 가둬둔다는 뜻이에요. 심리 상담이나 인간관계 글에서 자주 등장해요.', 'Bottling up feelings rarely leads to lasting peace of mind.', '감정을 억누르는 것은 좀처럼 지속적인 평정심으로 이어지지 않아요.', 'He had bottled up his grief for years before finally seeking help.', '그는 도움을 청하기 전 몇 년간 슬픔을 억눌러왔어요.', 'Do not bottle up your feelings — share them with someone you trust.', '감정을 억누르지 마세요. 믿는 사람과 나누세요.', 'C2', 'emotion', 3, 'bottled emotion', 2),
('idm_emotion_C2_03', 'lose one''s cool', '냉정을 잃다', '쿨함을 잃다', '평소의 침착함이나 자제력을 잃고 화를 낸다는 뜻이에요. 격식과 비격식 모두에서 폭넓게 써요.', 'Even seasoned negotiators occasionally lose their cool under pressure.', '노련한 협상가들도 압박 속에서 가끔 냉정을 잃어요.', 'She lost her cool when the same question was asked for the fourth time.', '같은 질문을 네 번째 받자 그녀는 냉정을 잃었어요.', 'A true leader rarely loses their cool in a crisis.', '진정한 리더는 위기 속에서 좀처럼 냉정을 잃지 않아요.', 'C2', 'emotion', 3, 'frustrated executive', 3),
('idm_emotion_C2_04', 'down in the dumps', '의기소침한', '쓰레기장에 빠진', '뚜렷한 이유 없이 우울하고 풀이 죽은 상태를 가리키는 격식 있는 구어 표현이에요. 인물 묘사에서 자연스러워요.', 'He has been down in the dumps ever since the manuscript was rejected.', '그는 원고가 거절당한 이후로 줄곧 의기소침해 있어요.', 'A long walk often lifts her out of being down in the dumps.', '오래 걷는 것은 종종 그녀를 의기소침함에서 끌어올려줘요.', 'Whenever I am down in the dumps, I revisit my favorite novel.', '의기소침할 때마다 저는 가장 좋아하는 소설을 다시 읽어요.', 'C2', 'emotion', 3, 'gloomy figure window', 4),
('idm_emotion_C2_05', 'head over heels', '푹 빠진', '머리가 발 위에 있는', '주로 사랑에 완전히 빠진 상태를 가리키지만, 어떤 것에 깊이 매료된 상황에도 써요. 문학과 회고록에서 우아하게 활용돼요.', 'They were head over heels from the moment they met at the embassy reception.', '그들은 대사관 리셉션에서 만난 순간부터 푹 빠졌어요.', 'He fell head over heels for the world of Renaissance literature.', '그는 르네상스 문학의 세계에 푹 빠졌어요.', 'She was head over heels in love with the city''s quiet elegance.', '그녀는 그 도시의 조용한 우아함에 푹 빠져 있었어요.', 'C2', 'emotion', 3, 'romantic embrace', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- CULTURE — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_culture_C2_01', 'embrace', 'tradition', 'embrace tradition', '전통을 받아들이다', 'follow', '전통을 적극적이고 긍정적으로 수용한다는 뉘앙스예요. 문화 평론, 정책 담론에서 자주 써요.', 'The contemporary chef embraces tradition while reinventing classic recipes.', '그 현대 셰프는 전통을 받아들이면서도 고전적 레시피를 재해석해요.', 'Many designers embrace tradition as a source of innovation, not constraint.', '많은 디자이너들은 전통을 제약이 아닌 혁신의 원천으로 받아들여요.', 'C2', 'culture', 3, 'traditional craft hands'),
('col_culture_C2_02', 'transcend', 'boundaries', 'transcend boundaries', '경계를 초월하다', 'cross', '단순히 ''넘는다''가 아니라 한계 자체를 초월하여 새로운 차원에 이른다는 격식 표현이에요. 예술 평론의 단골 표현이에요.', 'Her installations transcend the boundaries between sculpture and performance.', '그녀의 설치 작품은 조각과 퍼포먼스의 경계를 초월해요.', 'Truly great cinema transcends linguistic and cultural boundaries.', '진정으로 위대한 영화는 언어와 문화의 경계를 초월해요.', 'C2', 'culture', 3, 'art installation gallery'),
('col_culture_C2_03', 'epitomize', 'elegance', 'epitomize elegance', '우아함의 전형이 되다', 'show', '어떤 자질의 완벽한 본보기가 된다는 격식 동사예요. 패션, 인물 평론, 디자인 평가에 적합해요.', 'Her tailored silhouette epitomizes mid-century elegance.', '그녀의 재단된 실루엣은 20세기 중반 우아함의 전형이에요.', 'The opera house epitomizes the elegance of the Belle Epoque.', '그 오페라 하우스는 벨 에포크 시대 우아함의 전형이에요.', 'C2', 'culture', 3, 'elegant ballroom'),
('col_culture_C2_04', 'challenge', 'convention', 'challenge convention', '관습에 도전하다', 'break', '기존의 통념이나 관습에 의문을 제기하며 맞선다는 격식 표현이에요. 예술과 학술 비평에서 표준이에요.', 'The avant-garde movement sought to challenge every convention of academic painting.', '아방가르드 운동은 학파 회화의 모든 관습에 도전하려 했어요.', 'Her debut novel challenges convention in both form and content.', '그녀의 데뷔작은 형식과 내용 모두에서 관습에 도전해요.', 'C2', 'culture', 3, 'avant-garde art'),
('col_culture_C2_05', 'blend', 'influences', 'blend influences', '영향을 융합하다', 'mix', '서로 다른 문화나 양식의 영향을 조화롭게 결합한다는 표현이에요. 음악, 요리, 디자인 평론에서 자주 보여요.', 'The composer skillfully blends European and East Asian musical influences.', '그 작곡가는 유럽과 동아시아의 음악적 영향을 능숙하게 융합해요.', 'Their cuisine blends Andalusian and North African influences with quiet sophistication.', '그들의 요리는 안달루시아와 북아프리카의 영향을 잔잔한 세련됨으로 융합해요.', 'C2', 'culture', 3, 'fusion cuisine')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- CULTURE — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_culture_C2_01', 'the toast of the town', '장안의 화제', '도시의 건배', '사교계나 예술계에서 큰 찬사를 받는 인물이나 작품을 뜻해요. 문화 비평과 사교 칼럼에서 우아하게 써요.', 'After her debut at the Royal Opera, she became the toast of the town.', '왕립 오페라 데뷔 이후, 그녀는 장안의 화제가 되었어요.', 'His latest exhibition has made him the toast of the contemporary art scene.', '그의 최근 전시는 그를 현대 미술계의 화제로 만들었어요.', 'The young pianist was the toast of the town all season.', '그 젊은 피아니스트는 시즌 내내 장안의 화제였어요.', 'C2', 'culture', 3, 'opera applause', 1),
('idm_culture_C2_02', 'the writing on the wall', '불길한 징조', '벽에 적힌 글', '피할 수 없는 결과나 몰락의 조짐이 명백히 보일 때 써요. 문화 쇠퇴, 시대 변화 담론에서 격식 있게 활용돼요.', 'For traditional print media, the writing has long been on the wall.', '전통 인쇄 매체에는 오래전부터 불길한 징조가 보였어요.', 'Critics saw the writing on the wall for the gallery years before it closed.', '비평가들은 갤러리가 문을 닫기 몇 년 전부터 불길한 징조를 봤어요.', 'The writing was on the wall for that opulent style of theatre.', '그 호화로운 양식의 연극에는 불길한 징조가 보였어요.', 'C2', 'culture', 3, 'old graffiti wall', 2),
('idm_culture_C2_03', 'in vogue', '유행하는', '유행 안에 있는', '특정 양식이나 사상이 현재 유행 중이라는 격식 있는 표현이에요. 패션, 예술, 학문 트렌드 모두에 자연스러워요.', 'Minimalist interiors have been in vogue for nearly a decade.', '미니멀리즘 인테리어가 거의 10년째 유행 중이에요.', 'Such ornate rhetoric is no longer in vogue among serious essayists.', '그런 화려한 수사는 진지한 에세이스트들 사이에서 더 이상 유행하지 않아요.', 'Slow fashion is increasingly in vogue among discerning consumers.', '슬로우 패션이 안목 있는 소비자들 사이에서 점점 유행하고 있어요.', 'C2', 'culture', 3, 'fashion runway', 3),
('idm_culture_C2_04', 'all the rage', '대유행인', '온통 격분 상태인', '폭발적으로 인기 있는 유행을 가리키는 격식 있는 관용구예요. ''in vogue''보다 더 강한 열풍을 암시해요.', 'Japanese minimalism is all the rage in interior design circles.', '일본식 미니멀리즘이 인테리어 디자인계에서 대유행이에요.', 'That particular shade of olive was all the rage last autumn.', '그 특정 올리브색이 작년 가을에 대유행이었어요.', 'Immersive theatre is all the rage among younger audiences.', '몰입형 연극이 젊은 관객들 사이에서 대유행이에요.', 'C2', 'culture', 3, 'trendy interior', 4),
('idm_culture_C2_05', 'a feather in one''s cap', '자랑할 만한 업적', '모자에 꽂는 깃털', '경력이나 명성에 자랑이 되는 명예로운 성취를 뜻해요. 시상식, 회고, 격식 있는 인물 소개에서 우아해요.', 'Winning the prestigious literary prize is a feather in any author''s cap.', '그 권위 있는 문학상 수상은 어떤 작가에게나 자랑할 만한 업적이에요.', 'Curating the retrospective was a real feather in her cap.', '그 회고전을 큐레이팅한 것은 그녀에게 진정한 자랑거리였어요.', 'A Cannes nomination is a feather in any young director''s cap.', '칸 노미네이션은 어떤 신인 감독에게나 자랑할 만한 업적이에요.', 'C2', 'culture', 3, 'award trophy', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- HUMANITIES — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_humanities_C2_01', 'interrogate', 'assumptions', 'interrogate assumptions', '전제를 비판적으로 검토하다', 'question', '단순한 의심이 아니라 학문적으로 철저히 따져본다는 인문학·사회과학 학술 용어예요. ''question''보다 훨씬 무거운 무게감이에요.', 'The seminar urged students to interrogate the assumptions underlying classical economic theory.', '그 세미나는 학생들에게 고전 경제 이론의 전제를 비판적으로 검토하라고 촉구했어요.', 'Good scholarship interrogates its own assumptions before critiquing others''.', '훌륭한 학문은 타인을 비판하기에 앞서 자기 자신의 전제를 비판적으로 검토해요.', 'C2', 'humanities', 3, 'philosophy seminar'),
('col_humanities_C2_02', 'deconstruct', 'narrative', 'deconstruct a narrative', '서사를 해체하다', 'analyze', '데리다 이후 문학 비평의 표준 용어로, 서사의 이면 구조와 모순을 드러내는 작업이에요. 학술 논문에서 표준이에요.', 'Postcolonial scholars deconstruct the dominant narrative of colonial benevolence.', '탈식민주의 학자들은 식민지 자비라는 지배적 서사를 해체해요.', 'The essay deconstructs the narrative of inevitable progress.', '그 에세이는 필연적 진보라는 서사를 해체해요.', 'C2', 'humanities', 3, 'library deconstruction'),
('col_humanities_C2_03', 'contextualize', 'discourse', 'contextualize discourse', '담론을 맥락화하다', 'place', '담론을 역사적·사회적 맥락 속에서 이해할 수 있도록 자리매김한다는 학술 표현이에요. 인문학 논문의 핵심 동작이에요.', 'The chapter contextualizes the discourse on liberty within Enlightenment thought.', '그 장은 자유에 관한 담론을 계몽주의 사상의 맥락 속에 자리매김해요.', 'We must contextualize the discourse before pronouncing judgment.', '판단을 내리기 전에 담론을 맥락화해야 해요.', 'C2', 'humanities', 3, 'open archive book'),
('col_humanities_C2_04', 'trace', 'lineage', 'trace a lineage', '계보를 추적하다', 'find', '사상이나 양식의 기원과 흐름을 학술적으로 거슬러 올라간다는 표현이에요. 사상사·미술사·문학사에 필수적이에요.', 'The monograph traces the intellectual lineage from Kant to contemporary critical theory.', '그 논문은 칸트부터 현대 비판 이론까지의 지적 계보를 추적해요.', 'She traced the lineage of feminist thought across three continents.', '그녀는 세 대륙에 걸친 페미니즘 사상의 계보를 추적했어요.', 'C2', 'humanities', 3, 'genealogy chart'),
('col_humanities_C2_05', 'elucidate', 'meaning', 'elucidate meaning', '의미를 명확히 밝히다', 'explain', '불분명한 의미를 학술적이고 체계적으로 해명한다는 격식 동사예요. ''explain''보다 훨씬 무거운 학문적 어조예요.', 'The footnotes elucidate the meaning of arcane theological terms.', '각주들은 난해한 신학 용어의 의미를 명확히 밝혀요.', 'A careful reading of the original Greek elucidates the meaning lost in translation.', '원전 그리스어를 세심히 읽으면 번역에서 사라진 의미가 명확히 드러나요.', 'C2', 'humanities', 3, 'ancient text annotation')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- HUMANITIES — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_humanities_C2_01', 'the proof is in the pudding', '결과로 증명된다', '증거는 푸딩 안에 있다', '이론이나 주장이 옳은지는 실제 결과를 통해서만 알 수 있다는 학술적 격언이에요. 토론과 논평에서 우아하게 써요.', 'The theory is elegant, but the proof is in the pudding when applied to real data.', '그 이론은 우아하지만, 실제 데이터에 적용했을 때 비로소 결과로 증명돼요.', 'For any pedagogical method, the proof is ultimately in the pudding.', '어떤 교수법이든, 결국 결과로 증명돼요.', 'They claim the model is universal — but the proof is in the pudding.', '그들은 그 모델이 보편적이라 주장하지만, 결과로 증명돼야 해요.', 'C2', 'humanities', 3, 'scholarly proof', 1),
('idm_humanities_C2_02', 'splitting hairs', '지나치게 따지다', '머리카락을 가르다', '사소한 차이를 놓고 끝없이 따진다는 뜻이에요. 학술 토론에서 상대의 미세한 구분을 지적할 때 격식 있게 써요.', 'At this point we are merely splitting hairs over translation choices.', '이쯤 되면 우리는 번역 선택을 두고 지나치게 따지고 있을 뿐이에요.', 'Critics accused him of splitting hairs over a single comma.', '비평가들은 그가 쉼표 하나를 두고 지나치게 따진다고 비난했어요.', 'Let us not split hairs and instead address the central argument.', '지나치게 따지지 말고 핵심 논증을 다뤄봅시다.', 'C2', 'humanities', 3, 'magnifying glass text', 2),
('idm_humanities_C2_03', 'to coin a phrase', '말하자면', '문구를 주조하자면', '새로운 표현이나 이미 진부한 표현을 쓸 때 미리 양해를 구하는 격식 있는 삽입구예요. 학술 강연과 논문에서 우아한 효과를 줘요.', 'The corpus is, to coin a phrase, an archive of silences.', '그 코퍼스는 말하자면 침묵의 기록보관소예요.', 'Her style is, to coin a phrase, calculated spontaneity.', '그녀의 문체는 말하자면 계산된 즉흥성이에요.', 'The era was, to coin a phrase, an age of anxious modernity.', '그 시대는 말하자면 불안한 근대의 시대였어요.', 'C2', 'humanities', 3, 'fountain pen writing', 3),
('idm_humanities_C2_04', 'in a nutshell', '요컨대', '호두 껍데기 속에 넣어', '복잡한 논의를 핵심만 간결히 요약할 때 쓰는 격식 있는 표현이에요. 학술 강연의 결론부에 자연스러워요.', 'In a nutshell, the author argues that history is irreducibly plural.', '요컨대, 저자는 역사가 본질적으로 복수적이라고 주장해요.', 'In a nutshell, modernism dethroned the omniscient narrator.', '요컨대, 모더니즘은 전지적 서술자의 권위를 무너뜨렸어요.', 'The thesis, in a nutshell, redefines the very concept of authorship.', '그 논문은 요컨대, 저자성이라는 개념 자체를 재정의해요.', 'C2', 'humanities', 3, 'walnut shell', 4),
('idm_humanities_C2_05', 'the long and short of it', '결론은', '그것의 길고 짧음', '긴 논의 끝에 결론을 간결히 정리할 때 쓰는 격식 있는 표현이에요. 학술 발표의 마무리에 우아해요.', 'The long and short of it is that the manuscript predates the conventional dating by a century.', '결론은, 그 필사본이 통상 추정 연대보다 100년 앞선다는 거예요.', 'The long and short of it: structuralism cannot fully account for affect.', '결론은, 구조주의가 정동을 온전히 설명할 수 없다는 거예요.', 'The long and short of it is that the archive must be reread.', '결론은, 그 기록보관소를 다시 읽어야 한다는 거예요.', 'C2', 'humanities', 3, 'old manuscript', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- PRESENTATION — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_presentation_C2_01', 'captivate', 'audience', 'captivate an audience', '청중을 사로잡다', 'interest', '청중을 완전히 매혹시켜 시선을 떼지 못하게 한다는 강한 표현이에요. 발표 평론과 강연 후기에 표준이에요.', 'Her opening anecdote captivated the audience from the very first sentence.', '그녀의 도입부 일화는 첫 문장부터 청중을 사로잡았어요.', 'A skilled keynote speaker knows precisely how to captivate an audience.', '능숙한 기조 연설자는 어떻게 청중을 사로잡을지 정확히 알아요.', 'C2', 'presentation', 3, 'keynote speaker stage'),
('col_presentation_C2_02', 'marshal', 'evidence', 'marshal evidence', '증거를 정연하게 제시하다', 'show', '증거를 체계적이고 설득력 있게 동원·배열한다는 격식 표현이에요. 법정, 학술, 임원 보고에서 표준이에요.', 'The consultant marshaled compelling evidence to support the restructuring proposal.', '그 컨설턴트는 구조조정 제안을 뒷받침할 설득력 있는 증거를 정연하게 제시했어요.', 'You must marshal evidence carefully before the board challenges the assumptions.', '이사회가 가정에 의문을 제기하기 전에 증거를 신중히 정렬해야 해요.', 'C2', 'presentation', 3, 'boardroom evidence'),
('col_presentation_C2_03', 'articulate', 'vision', 'articulate a vision', '비전을 분명히 표현하다', 'tell', '추상적인 비전을 청중이 이해하고 공감할 수 있도록 명료하게 풀어낸다는 격식 표현이에요. CEO 연설의 표준 동사예요.', 'The new CEO articulated a vision of sustainable, decade-long growth.', '신임 CEO는 지속 가능하고 10년에 걸친 성장 비전을 분명히 표현했어요.', 'Great leaders articulate a vision their teams can rally behind.', '훌륭한 리더는 팀원들이 결집할 수 있는 비전을 분명히 표현해요.', 'C2', 'presentation', 3, 'CEO town hall'),
('col_presentation_C2_04', 'underscore', 'points', 'underscore key points', '핵심을 강조하다', 'show', '발표 중 핵심 메시지를 의도적으로 강조한다는 격식 동사예요. ''emphasize''보다 더 차분하고 세련된 어조예요.', 'Throughout the address, she underscored three key points with quiet authority.', '연설 내내 그녀는 차분한 권위로 세 가지 핵심을 강조했어요.', 'The closing slide underscored the key points of the entire presentation.', '마지막 슬라이드는 발표 전체의 핵심을 강조했어요.', 'C2', 'presentation', 3, 'slide deck close'),
('col_presentation_C2_05', 'field', 'questions', 'field questions', '질문을 받아 응대하다', 'answer', '질문을 능숙하게 받아 적절히 응대한다는 격식 표현이에요. 기자회견, Q&A 세션 보도에서 표준이에요.', 'After the keynote, she fielded questions from international journalists for over an hour.', '기조연설 이후, 그녀는 한 시간 넘게 국제 기자들의 질문을 받아 응대했어요.', 'The minister fielded difficult questions with characteristic poise.', '그 장관은 특유의 침착함으로 어려운 질문들을 받아 응대했어요.', 'C2', 'presentation', 3, 'press conference qa')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- PRESENTATION — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_presentation_C2_01', 'get the ball rolling', '시작을 알리다', '공을 굴리기 시작하다', '회의나 발표를 처음 시작해 흐름을 만든다는 뜻이에요. 격식과 비격식 모두에서 폭넓게 활용돼요.', 'Let me get the ball rolling with a brief overview of our methodology.', '저희 방법론에 대한 간략한 개요로 시작을 알리겠습니다.', 'She got the ball rolling by acknowledging the elephant in the room.', '그녀는 모두가 알지만 말하지 않는 문제를 짚으며 시작을 알렸어요.', 'To get the ball rolling, allow me to introduce our distinguished panel.', '시작을 알리며, 저희 권위 있는 패널을 소개해 드리겠습니다.', 'C2', 'presentation', 3, 'conference opening', 1),
('idm_presentation_C2_02', 'drive home a point', '요점을 확실히 전달하다', '요점을 집까지 몰고 가다', '핵심 메시지를 청중의 마음에 깊이 각인시킨다는 뜻이에요. 발표·연설 평론에서 자주 써요.', 'She drove home the point with three carefully chosen case studies.', '그녀는 세심하게 고른 세 가지 사례 연구로 요점을 확실히 전달했어요.', 'The speaker drove home the point that complacency is the real enemy.', '그 연설자는 자만이 진짜 적이라는 요점을 확실히 전달했어요.', 'Repetition, when used judiciously, helps drive home a point.', '반복은 신중하게 쓰일 때 요점을 확실히 전달하는 데 도움이 돼요.', 'C2', 'presentation', 3, 'speaker emphasis', 2),
('idm_presentation_C2_03', 'cut to the chase', '본론으로 들어가다', '추격 장면으로 자르다', '서론을 줄이고 곧장 핵심으로 들어간다는 뜻이에요. 임원 회의나 시간 제약이 있는 발표에서 정중하게 활용돼요.', 'Given our time constraints, allow me to cut to the chase.', '시간 제약을 감안하여, 곧장 본론으로 들어가겠습니다.', 'The chairman, ever pragmatic, asked her to cut to the chase.', '늘 실용적인 의장은 그녀에게 본론으로 들어가달라고 요청했어요.', 'Let us cut to the chase: the merger is the only viable path forward.', '본론으로 들어가죠. 합병이 유일한 실행 가능한 길이에요.', 'C2', 'presentation', 3, 'business meeting clock', 3),
('idm_presentation_C2_04', 'thinking on one''s feet', '즉석에서 대응하기', '발 위에서 생각하기', '준비 없이도 빠르게 판단하고 답한다는 뜻이에요. Q&A 세션, 외교 협상 묘사에서 우아하게 써요.', 'Excellent diplomats are masters at thinking on their feet.', '뛰어난 외교관들은 즉석 대응의 달인이에요.', 'Her ability to think on her feet won over the skeptical analysts.', '즉석에서 대응하는 그녀의 능력은 회의적인 애널리스트들을 설득했어요.', 'Public speaking trains you to think on your feet under pressure.', '대중 연설은 압박 속에서도 즉석에서 대응하도록 훈련시켜요.', 'C2', 'presentation', 3, 'quick response speaker', 4),
('idm_presentation_C2_05', 'lay one''s cards on the table', '솔직히 다 털어놓다', '카드를 테이블에 놓다', '의도나 입장을 숨김없이 공개한다는 격식 있는 표현이에요. 협상이나 전략 발표에서 솔직함을 강조할 때 적절해요.', 'Allow me to lay my cards on the table: our margins simply cannot sustain this trajectory.', '솔직히 다 털어놓겠습니다. 저희 마진은 이런 흐름을 도저히 지탱할 수 없어요.', 'She laid her cards on the table during the final round of negotiations.', '그녀는 협상 최종 라운드에서 모든 것을 솔직히 털어놨어요.', 'Investors appreciate it when founders lay their cards on the table.', '투자자들은 창업자가 솔직히 다 털어놓을 때 그것을 높이 평가해요.', 'C2', 'presentation', 3, 'cards on table', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- GREETING — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_greeting_C2_01', 'extend', 'pleasantries', 'extend pleasantries', '의례적 인사를 건네다', 'say', '격식 있는 자리에서 정중한 인사말을 정성껏 건넨다는 뜻이에요. 외교, 비즈니스 미팅 보도의 표준이에요.', 'The ambassador extended pleasantries before turning to the substantive agenda.', '대사는 본격적인 안건으로 넘어가기 전에 의례적 인사를 건넸어요.', 'They extended pleasantries over tea in the embassy garden.', '그들은 대사관 정원에서 차를 마시며 의례적 인사를 건넸어요.', 'C2', 'greeting', 3, 'diplomatic handshake'),
('col_greeting_C2_02', 'exchange', 'formalities', 'exchange formalities', '의례를 주고받다', 'do', '서로 정중한 격식의 말을 주고받는 절차적 행위를 가리켜요. 의전적 만남 묘사에서 표준 표현이에요.', 'The two delegations exchanged formalities before the negotiations commenced.', '두 대표단은 협상이 시작되기 전 의례를 주고받았어요.', 'After exchanging formalities, they settled into a more candid discussion.', '의례를 주고받은 후, 그들은 더 솔직한 논의로 들어갔어요.', 'C2', 'greeting', 3, 'formal meeting bow'),
('col_greeting_C2_03', 'convey', 'regards', 'convey regards', '안부를 전하다', 'say', '직접 만나지 못한 사람에게 정중히 안부를 전달한다는 격식 표현이에요. 편지, 외교 전문, 공식 인사말에 적합해요.', 'Please convey my warmest regards to your esteemed family.', '존경하는 가족분들께 가장 따뜻한 안부를 전해 주세요.', 'She asked me to convey her regards to the entire faculty.', '그녀는 저에게 교수진 전체에게 안부를 전해달라고 부탁했어요.', 'C2', 'greeting', 3, 'handwritten letter'),
('col_greeting_C2_04', 'make', 'acquaintance', 'make one''s acquaintance', '인사를 나누다', 'meet', '처음 만나 인사하게 되어 영광이라는 매우 격식 있는 표현이에요. ''Pleased to make your acquaintance''는 표준 격식 인사예요.', 'I am delighted to make your acquaintance at last, Professor.', '교수님, 마침내 인사를 나누게 되어 기쁩니다.', 'It was a privilege to make her acquaintance at the embassy reception.', '대사관 리셉션에서 그녀와 인사를 나눈 것은 영광이었어요.', 'C2', 'greeting', 3, 'formal introduction'),
('col_greeting_C2_05', 'tender', 'greetings', 'tender greetings', '인사를 정중히 전하다', 'send', '정중하고 의례적으로 인사를 ''올린다''는 매우 격식 있는 동사예요. 공식 서신과 의전 연설에서 보여요.', 'On behalf of the council, I tender greetings to our distinguished guests.', '의회를 대표하여, 귀한 손님들께 인사를 정중히 올립니다.', 'The chairperson tendered greetings to the assembly before opening the session.', '의장은 회의를 개시하기 전 의회에 인사를 정중히 전했어요.', 'C2', 'greeting', 3, 'formal podium')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- GREETING — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_greeting_C2_01', 'long time no see', '오랜만이에요', '오랜 시간 보지 못했다', '오랜만에 만난 사람에게 건네는 친근한 인사예요. 격식 있는 자리에서도 자연스럽게 활용돼요.', 'Long time no see, Professor — how have you been keeping?', '교수님, 오랜만이에요. 그동안 어떻게 지내셨어요?', 'Long time no see! Your last paper was nothing short of brilliant.', '오랜만이에요. 지난번 논문은 정말 훌륭했어요.', 'Long time no see — shall we catch up over coffee?', '오랜만이에요. 커피 한 잔하며 근황을 나눌까요?', 'C2', 'greeting', 3, 'reunion handshake', 1),
('idm_greeting_C2_02', 'speak of the devil', '호랑이도 제 말 하면 온다', '악마를 말하다', '마침 이야기하던 사람이 등장했을 때 쓰는 친근한 격식 표현이에요. 비즈니스 점심이나 사교 모임에서 자연스러워요.', 'Speak of the devil — here she is, just as we were singing her praises.', '호랑이도 제 말 하면 온다더니, 마침 그녀 칭찬을 하고 있었는데 왔네요.', 'We were just discussing your latest article — speak of the devil!', '마침 당신의 최근 기사를 논의하고 있었는데, 호랑이도 제 말 하면 오네요.', 'Speak of the devil, here comes our keynote speaker.', '호랑이도 제 말 하면 온다고, 기조연설자가 오시네요.', 'C2', 'greeting', 3, 'surprise arrival', 2),
('idm_greeting_C2_03', 'the elephant in the room', '모두 알지만 말하지 않는 문제', '방 안의 코끼리', '모두가 인식하지만 일부러 언급을 피하는 민감한 사안을 가리켜요. 격식 있는 회의를 열며 솔직히 거론할 때 우아해요.', 'Before we begin, let us address the elephant in the room.', '시작하기에 앞서, 모두 알지만 말하지 않는 문제부터 다루어 봅시다.', 'No one was willing to acknowledge the elephant in the room.', '아무도 그 민감한 문제를 인정하려 하지 않았어요.', 'The chairperson, with characteristic candor, named the elephant in the room.', '의장은 특유의 솔직함으로 그 민감한 문제를 지적했어요.', 'C2', 'greeting', 3, 'meeting room elephant', 3),
('idm_greeting_C2_04', 'make small talk', '간단한 잡담을 나누다', '작은 이야기를 하다', '본 주제로 들어가기 전 가벼운 대화로 분위기를 푼다는 표현이에요. 외교, 사교, 비즈니스 만남에 필수적이에요.', 'They made small talk about the weather before turning to the contract.', '계약 이야기로 넘어가기 전, 그들은 날씨에 대해 잡담을 나눴어요.', 'Making small talk is itself a refined diplomatic skill.', '잡담을 나누는 것 자체가 세련된 외교 기술이에요.', 'He is surprisingly skilled at making small talk in three languages.', '그는 놀랍게도 세 가지 언어로 잡담을 나누는 데 능숙해요.', 'C2', 'greeting', 3, 'cocktail reception', 4),
('idm_greeting_C2_05', 'break the ice with grace', '우아하게 어색함을 풀다', '얼음을 우아하게 깨다', '처음 만난 자리에서 세련되게 어색함을 풀어 친밀한 분위기를 만든다는 뜻이에요. 외교와 사교 칼럼에서 우아해요.', 'A well-chosen anecdote can break the ice with grace at any reception.', '잘 고른 일화 하나는 어떤 리셉션에서도 우아하게 어색함을 풀 수 있어요.', 'She broke the ice with grace by recalling their shared acquaintance.', '그녀는 공통의 지인을 언급하며 우아하게 어색함을 풀었어요.', 'The host broke the ice with grace, setting a warm tone for the evening.', '주최자는 우아하게 어색함을 풀며 저녁의 따뜻한 분위기를 만들었어요.', 'C2', 'greeting', 3, 'elegant reception', 5)
ON CONFLICT (id) DO NOTHING;
