-- ============================================================
-- C2-level Collocations and Idioms — Batch 5
-- Topics: academic, discussion, negotiation
-- 5 collocations + 5 idioms per topic = 30 total entries
-- ============================================================

-- ============================================================
-- ACADEMIC — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_academic_C2_01', 'advance', 'thesis', 'advance a thesis', '논지를 제시하다', 'say', '논문이나 학술 토론에서 자신의 주장을 공식적으로 내세울 때 써요. ''say''는 단순 발화라 학술 맥락에 부족해요.', 'In her keynote, she advanced a provocative thesis on post-colonial historiography.', '기조 연설에서 그녀는 탈식민 역사 서술에 관한 도발적인 논지를 제시했어요.', 'The author advances the thesis that institutional inertia underpins systemic failure.', '저자는 제도적 관성이 체계적 실패의 근간이라는 논지를 제시해요.', 'C2', 'academic', 3, 'lecture podium'),
('col_academic_C2_02', 'substantiate', 'claim', 'substantiate a claim', '주장을 입증하다', 'prove', '근거와 자료로 주장을 뒷받침한다는 학술적 표현이에요. ''prove''는 결론적인 증명, ''substantiate''는 근거 제시에 가까워요.', 'The reviewers asked the authors to substantiate their claims with longitudinal data.', '심사위원들은 저자들에게 종단 자료로 주장을 입증하라고 요청했어요.', 'Without primary sources, it is difficult to substantiate such a sweeping claim.', '1차 사료 없이는 그렇게 광범위한 주장을 입증하기 어려워요.', 'C2', 'academic', 3, 'research data'),
('col_academic_C2_03', 'rebut', 'argument', 'rebut an argument', '논거를 반박하다', 'deny', '상대의 논거를 근거를 들어 정식으로 반박할 때 써요. ''deny''는 단순 부정이라 학술 토론에 약해요.', 'The discussant rebutted the central argument with a series of counterexamples.', '토론자는 일련의 반례를 들어 핵심 논거를 반박했어요.', 'Her latest paper rebuts the prevailing argument on monetary neutrality.', '그녀의 최신 논문은 화폐 중립성에 관한 지배적인 논거를 반박해요.', 'C2', 'academic', 3, 'academic debate'),
('col_academic_C2_04', 'synthesize', 'findings', 'synthesize findings', '연구 결과를 종합하다', 'combine', '여러 연구의 결과를 비판적으로 통합한다는 학술 전문 용어예요. ''combine''은 단순 결합이라 의미가 약해요.', 'The meta-analysis synthesizes findings from forty-three randomized trials.', '메타분석은 43건의 무작위 시험 결과를 종합해요.', 'In her dissertation she synthesizes findings across three disciplines.', '박사 논문에서 그녀는 세 학문 분야의 연구 결과를 종합해요.', 'C2', 'academic', 3, 'research papers'),
('col_academic_C2_05', 'operationalize', 'concept', 'operationalize a concept', '개념을 조작화하다', 'define', '추상적 개념을 측정 가능하게 정의하는 사회과학·심리학 전문 표현이에요. ''define''보다 한 단계 정교한 학술어예요.', 'The study operationalizes the concept of resilience through three composite indices.', '이 연구는 회복탄력성 개념을 세 가지 종합 지수로 조작화해요.', 'Operationalizing such a nebulous concept poses methodological challenges.', '그런 모호한 개념을 조작화하는 일은 방법론적 난제를 낳아요.', 'C2', 'academic', 3, 'statistical analysis')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ACADEMIC — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_academic_C2_01', 'ivory tower', '상아탑', '상아 탑', '현실과 동떨어진 학계나 지식인의 세계를 비판적으로 가리키는 표현이에요. 격식 있는 평론과 사설에서 자주 써요.', 'Critics accuse the panel of issuing recommendations from an ivory tower.', '비평가들은 그 위원회가 상아탑에서 권고를 내린다고 비난해요.', 'She left her ivory tower to consult for grassroots organizations.', '그녀는 상아탑을 떠나 풀뿌리 단체의 자문을 맡았어요.', 'Such theories rarely survive contact with the world outside the ivory tower.', '그런 이론은 상아탑 밖 세상과 부딪히면 좀처럼 살아남지 못해요.', 'C2', 'academic', 3, 'university tower', 1),
('idm_academic_C2_02', 'armchair scholar', '탁상공론자', '안락의자 학자', '실제 경험 없이 책으로만 이론을 펼치는 사람을 비판적으로 가리켜요. 학계 비평이나 정책 토론에서 자주 써요.', 'He dismissed the report as the work of an armchair scholar with no field experience.', '그는 그 보고서를 현장 경험 없는 탁상공론자의 작업이라며 일축했어요.', 'Armchair scholars often underestimate the complexity of implementation.', '탁상공론자들은 흔히 실행의 복잡성을 과소평가해요.', 'NULL', 'NULL', 'C2', 'academic', 3, 'reading armchair', 2),
('idm_academic_C2_03', 'a labour of love', '애정으로 한 일', '사랑의 노동', '금전적 보상 없이 순전히 애정과 헌신으로 오랜 시간 매달린 작업을 가리켜요. 학술 출판, 예술, 번역 등에서 격식 있게 써요.', 'Her decade-long translation of the medieval text was truly a labour of love.', '그 중세 문헌에 대한 그녀의 10년에 걸친 번역은 진정 애정으로 한 일이었어요.', 'The annotated edition is a labour of love by three retired professors.', '그 주석본은 은퇴한 세 교수의 애정 어린 노작이에요.', 'Compiling this archive has been a labour of love for the entire research team.', '이 아카이브 편찬은 연구팀 전체에게 애정으로 한 일이었어요.', 'C2', 'academic', 3, 'old manuscripts', 3),
('idm_academic_C2_04', 'off the cuff', '즉흥적으로', '소맷부리에서 떼서', '준비 없이 즉석에서 말하거나 답하는 것을 가리켜요. 학회 질의응답, 인터뷰, 회의에서 격식 있게 써요.', 'When pressed for a figure, the economist offered an estimate off the cuff.', '수치를 묻자 경제학자는 즉흥적으로 추정치를 제시했어요.', 'Her off-the-cuff remarks during the Q&A drew considerable attention.', '질의응답 중 그녀의 즉흥 발언은 상당한 주목을 받았어요.', 'I would rather not comment off the cuff on such a sensitive matter.', '그렇게 민감한 사안을 즉흥적으로 논평하고 싶지는 않아요.', 'C2', 'academic', 3, 'microphone speaker', 4),
('idm_academic_C2_05', 'splitting hairs', '사소한 것에 집착하다', '머리카락을 쪼개다', '본질과 무관한 미세한 구분에 매달리는 행위를 비판적으로 가리켜요. 학술 토론, 법정, 정책 논쟁에서 격식 있게 써요.', 'With respect, you are splitting hairs over terminology rather than addressing the substance.', '실례지만, 본질을 다루는 대신 용어를 두고 사소한 것에 집착하고 있어요.', 'The reviewers were splitting hairs over a minor methodological footnote.', '심사위원들은 사소한 방법론 각주를 두고 트집을 잡고 있었어요.', 'Let us not split hairs — the central conclusion remains intact.', '사소한 데 집착하지 맙시다. 핵심 결론은 그대로예요.', 'C2', 'academic', 3, 'magnifying glass', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- DISCUSSION — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_discussion_C2_01', 'reach', 'consensus', 'reach consensus', '합의에 이르다', 'make', '논의 끝에 참석자 다수가 동의에 도달했다는 격식 표현이에요. ''make''는 어색하고, ''reach''가 표준 학술·외교 용어예요.', 'After three days of deliberation, the committee finally reached consensus on the wording.', '사흘간의 숙의 끝에 위원회는 마침내 문안에 합의를 이루었어요.', 'Reaching consensus on such a contentious issue will require sustained dialogue.', '그렇게 첨예한 사안에서 합의에 이르려면 지속적인 대화가 필요해요.', 'C2', 'discussion', 3, 'meeting handshake'),
('col_discussion_C2_02', 'raise', 'objections', 'raise objections', '이의를 제기하다', 'say', '회의나 토론에서 공식적으로 반대 의견을 제기할 때 쓰는 격식 표현이에요. ''say''는 격이 떨어져요.', 'Several board members raised objections to the proposed restructuring.', '여러 이사회 구성원이 제안된 구조조정에 이의를 제기했어요.', 'If you wish to raise objections, please do so before the vote is called.', '이의를 제기하시려면 표결 전에 해 주세요.', 'C2', 'discussion', 3, 'board meeting'),
('col_discussion_C2_03', 'voice', 'concerns', 'voice concerns', '우려를 표명하다', 'tell', '걱정이나 우려를 공개적으로 표현한다는 외교적·격식 표현이에요. ''tell''은 격이 부족해요.', 'Stakeholders voiced grave concerns over the environmental impact assessment.', '이해관계자들은 환경 영향 평가에 대해 심각한 우려를 표명했어요.', 'She voiced her concerns directly to the steering committee.', '그녀는 운영위원회에 직접 우려를 표명했어요.', 'C2', 'discussion', 3, 'concerned speaker'),
('col_discussion_C2_04', 'challenge', 'assumptions', 'challenge assumptions', '전제에 의문을 제기하다', 'doubt', '논의의 바탕이 되는 전제를 근본부터 재검토하자는 비판적 사고 표현이에요. ''doubt''보다 학술적이고 적극적이에요.', 'The keynote speaker urged delegates to challenge their assumptions about productivity.', '기조 연사는 대표단에게 생산성에 대한 전제를 재검토하라고 촉구했어요.', 'A good moderator challenges assumptions rather than reinforcing them.', '좋은 사회자는 전제를 강화하기보다 의문을 제기해요.', 'C2', 'discussion', 3, 'debate forum'),
('col_discussion_C2_05', 'concede', 'point', 'concede a point', '논점을 인정하다', 'agree', '토론에서 상대의 주장이 일리 있다고 일부 인정하는 격식 표현이에요. ''agree''보다 부분적이고 외교적인 뉘앙스예요.', 'The minister graciously conceded the point on fiscal accountability.', '장관은 재정 책임 문제에 관한 논점을 정중히 인정했어요.', 'Conceding a point does not weaken your overall position.', '한 논점을 인정한다고 해서 전체 입장이 약해지지는 않아요.', 'C2', 'discussion', 3, 'panel discussion')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- DISCUSSION — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_discussion_C2_01', 'agree to disagree', '이견을 인정하다', '동의하지 않기로 동의하다', '서로 합의할 수 없음을 인정하고 논쟁을 정중히 끝낼 때 써요. 격식 있는 회의와 외교 대화에 적합해요.', 'After hours of debate, the panelists chose to agree to disagree on the matter.', '몇 시간의 토론 끝에 패널들은 그 사안에 대해 이견을 인정하기로 했어요.', 'Sometimes the most diplomatic outcome is simply to agree to disagree.', '때로는 가장 외교적인 결론이 그저 이견을 인정하는 것이에요.', 'We agreed to disagree on policy specifics while affirming our shared values.', '우리는 공유 가치를 확인하면서도 정책 세부에 대한 이견은 인정했어요.', 'C2', 'discussion', 3, 'handshake disagreement', 1),
('idm_discussion_C2_02', 'play devil''s advocate', '일부러 반론을 펴다', '악마의 변호인 역할을 하다', '논의를 풍부하게 하기 위해 일부러 반대 입장을 취해보는 행위를 가리켜요. 학술 세미나와 전략 회의에서 격식 있게 써요.', 'Let me play devil''s advocate for a moment and question the central premise.', '잠시 반론을 펴 보자면, 핵심 전제에 의문을 제기하고 싶어요.', 'A good chair occasionally plays devil''s advocate to test the group''s reasoning.', '좋은 의장은 가끔 일부러 반론을 펴서 집단의 추론을 검증해요.', 'She often plays devil''s advocate in board discussions to stress-test proposals.', '그녀는 이사회 토론에서 자주 일부러 반론을 펴 제안을 검증해요.', 'C2', 'discussion', 3, 'thinking debate', 2),
('idm_discussion_C2_03', 'beat a dead horse', '같은 얘기를 반복하다', '죽은 말을 때리다', '이미 결론이 난 사안을 무익하게 계속 거론하는 것을 비판적으로 가리켜요. 회의 진행이 정체될 때 격식 있게 써요.', 'With respect, I think we are beating a dead horse — the decision has been made.', '실례지만, 같은 얘기를 반복하고 있는 것 같아요. 결정은 이미 났어요.', 'There is no point beating a dead horse; let us move to the next agenda item.', '같은 얘기를 반복할 필요는 없어요. 다음 안건으로 넘어갑시다.', 'The chair gently noted that the discussion was beating a dead horse.', '의장은 그 논의가 같은 얘기의 반복이라고 점잖게 지적했어요.', 'C2', 'discussion', 3, 'tired meeting', 3),
('idm_discussion_C2_04', 'common ground', '공통 기반', '공통의 땅', '서로 다른 입장 사이에서 합의 가능한 지점을 가리켜요. 외교, 협상, 다자 논의의 표준 격식 표현이에요.', 'Despite ideological differences, the delegations found significant common ground on climate policy.', '이념적 차이에도 불구하고 대표단들은 기후 정책에서 상당한 공통 기반을 찾았어요.', 'Finding common ground is the first task of any productive dialogue.', '공통 기반을 찾는 것이 모든 생산적 대화의 첫 과제예요.', 'The mediator skillfully identified common ground between the warring parties.', '중재자는 갈등 당사자들 사이의 공통 기반을 능숙하게 찾아냈어요.', 'C2', 'discussion', 3, 'overlapping circles', 4),
('idm_discussion_C2_05', 'go round in circles', '제자리걸음하다', '원을 따라 돌다', '논의가 진전 없이 같은 지점을 맴도는 상황을 가리켜요. 회의 평가나 진행 비평에 격식 있게 써요.', 'We have been going round in circles for an hour — perhaps we need a tie-breaking vote.', '한 시간째 제자리걸음이에요. 결선 투표가 필요할 것 같아요.', 'Without clear terms of reference, the committee kept going round in circles.', '명확한 위임 범위 없이 위원회는 계속 제자리걸음을 했어요.', 'The negotiations went round in circles until a new mediator was appointed.', '새 중재자가 임명되기 전까지 협상은 제자리걸음을 거듭했어요.', 'C2', 'discussion', 3, 'circular arrows', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEGOTIATION — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_negotiation_C2_01', 'broker', 'deal', 'broker a deal', '거래를 중개하다', 'make', '제3자가 양측 사이에서 협상을 이끌어 거래를 성사시킨다는 외교·금융 격식 표현이에요. ''make''는 단순 체결이라 의미가 약해요.', 'The envoy spent six months brokering a deal between the two governments.', '특사는 두 정부 사이의 거래를 중개하는 데 6개월을 썼어요.', 'Investment bankers were brought in to broker the deal.', '거래를 중개하기 위해 투자 은행가들이 투입되었어요.', 'C2', 'negotiation', 3, 'diplomatic meeting'),
('col_negotiation_C2_02', 'drive', 'bargain', 'drive a bargain', '흥정을 강하게 이끌다', 'make', '협상에서 자신에게 유리하도록 강하게 밀어붙인다는 비즈니스 격식 표현이에요. ''drive a hard bargain''으로도 자주 써요.', 'Their lead negotiator drove a bargain that exceeded the board''s expectations.', '그들의 수석 협상가는 이사회의 기대를 넘는 흥정을 이끌었어요.', 'She drives a bargain with the discipline of a seasoned trader.', '그녀는 노련한 트레이더의 절도로 흥정을 이끌어요.', 'C2', 'negotiation', 3, 'business negotiation'),
('col_negotiation_C2_03', 'yield', 'concessions', 'yield concessions', '양보를 끌어내다', 'get', '협상 끝에 상대로부터 양보를 받아낸다는 외교·노사 협상 격식 표현이에요. ''get''은 격이 떨어져요.', 'Sustained pressure finally yielded concessions on labor standards.', '지속적인 압박이 마침내 노동 기준에 관한 양보를 끌어냈어요.', 'The strategy yielded significant concessions from the opposing delegation.', '그 전략은 상대 대표단으로부터 상당한 양보를 끌어냈어요.', 'C2', 'negotiation', 3, 'negotiation table'),
('col_negotiation_C2_04', 'leverage', 'influence', 'leverage influence', '영향력을 활용하다', 'use', '자신의 영향력이나 자원을 전략적으로 활용한다는 비즈니스·정치 격식 표현이에요. ''use''보다 훨씬 전략적인 뉘앙스예요.', 'She leveraged her influence with regulators to secure a favorable ruling.', '그녀는 규제 당국에 대한 영향력을 활용해 유리한 결정을 끌어냈어요.', 'The coalition leveraged its collective influence at the summit.', '연합체는 정상회담에서 집단적 영향력을 활용했어요.', 'C2', 'negotiation', 3, 'corporate boardroom'),
('col_negotiation_C2_05', 'stall', 'proceedings', 'stall proceedings', '회의 진행을 지연시키다', 'stop', '협상이나 절차의 진행을 의도적으로 늦춘다는 외교·법정 격식 표현이에요. ''stop''은 완전 중단을 뜻해 의미가 달라요.', 'The opposing counsel repeatedly stalled proceedings with procedural motions.', '상대 측 변호인은 절차 동의로 회의 진행을 거듭 지연시켰어요.', 'Stalling proceedings may buy time, but it erodes goodwill.', '진행 지연은 시간을 벌어주지만, 호의를 깎아내요.', 'C2', 'negotiation', 3, 'courtroom delay')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEGOTIATION — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_negotiation_C2_01', 'drive a hard bargain', '강하게 흥정하다', '단단한 흥정을 몰다', '자신에게 매우 유리한 조건을 끈질기게 요구하는 협상 태도를 가리켜요. 비즈니스 협상에서 격식 있는 칭찬이나 평가로 써요.', 'Their CFO is known to drive a hard bargain in licensing negotiations.', '그들의 CFO는 라이선스 협상에서 강하게 흥정하기로 유명해요.', 'You drive a hard bargain, but I respect your discipline.', '강하게 흥정하시지만, 그 절도는 존경해요.', 'She drove a hard bargain and walked away with terms few thought possible.', '그녀는 강하게 흥정해서 누구도 가능하다고 생각하지 않던 조건을 따냈어요.', 'C2', 'negotiation', 3, 'tough negotiator', 1),
('idm_negotiation_C2_02', 'have the upper hand', '우위를 점하다', '위쪽 손을 가지다', '협상이나 경쟁에서 유리한 위치에 있다는 격식 표현이에요. 외교, 비즈니스, 법정 등 다양한 격식 맥락에서 써요.', 'With exclusive supplier contracts, they clearly have the upper hand at the table.', '독점 공급 계약을 가진 그들은 협상 자리에서 명백히 우위를 점하고 있어요.', 'The party that controls the timeline often has the upper hand.', '일정을 통제하는 쪽이 흔히 우위를 점해요.', 'After the audit findings, regulators have the upper hand in the talks.', '감사 결과 이후 규제 당국이 협상에서 우위를 점하고 있어요.', 'C2', 'negotiation', 3, 'chess king', 2),
('idm_negotiation_C2_03', 'meet halfway', '서로 양보하다', '중간에서 만나다', '양측이 각자 양보해 중간 지점에서 합의한다는 외교·협상 표준 격식 표현이에요. 분쟁 조정에 자주 써요.', 'If both sides are willing to meet halfway, a settlement is within reach.', '양측이 서로 양보할 의향이 있다면 합의는 손에 닿아 있어요.', 'The mediator urged the parties to meet halfway on the contested clause.', '중재자는 양측에 쟁점 조항에서 서로 양보하라고 촉구했어요.', 'We are prepared to meet you halfway on the delivery timeline.', '납기 일정에 대해서는 저희도 양보할 준비가 되어 있어요.', 'C2', 'negotiation', 3, 'bridge meeting', 3),
('idm_negotiation_C2_04', 'back to square one', '원점으로 돌아가다', '1번 칸으로 돌아가다', '협상이나 계획이 무산되어 처음부터 다시 시작해야 하는 상황을 가리켜요. 비즈니스·외교 보고에서 격식 있게 써요.', 'With the deal collapsing, the negotiating team is back to square one.', '거래가 무산되어 협상 팀은 원점으로 돌아갔어요.', 'A single veto sent the entire framework back to square one.', '거부권 한 번이 전체 틀을 원점으로 되돌렸어요.', 'After two years of talks, we cannot afford to be back to square one.', '2년에 걸친 협상 끝에 원점으로 돌아갈 여유는 없어요.', 'C2', 'negotiation', 3, 'board game start', 4),
('idm_negotiation_C2_05', 'throw down the gauntlet', '도전장을 내밀다', '장갑을 던지다', '공식적으로 도전을 선언하거나 강한 대결 의지를 표명할 때 써요. 외교, 비즈니스 경쟁, 학술 토론의 격식 표현이에요.', 'By unveiling the new patent portfolio, the company threw down the gauntlet to its rivals.', '새 특허 포트폴리오를 공개함으로써 그 회사는 경쟁사들에게 도전장을 내밀었어요.', 'The keynote speech effectively threw down the gauntlet on climate accountability.', '기조 연설은 사실상 기후 책임 문제에 도전장을 내밀었어요.', 'She threw down the gauntlet, demanding a public debate on the proposal.', '그녀는 도전장을 내밀어 그 제안에 대한 공개 토론을 요구했어요.', 'C2', 'negotiation', 3, 'medieval gauntlet', 5)
ON CONFLICT (id) DO NOTHING;
