-- ============================================
-- C2 Collocations & Idioms — Batches 2~5 Combined
-- 18 topics × 10 entries = 180 entries total
-- Topics:
--   Batch 2: health, weather, transport, media, education
--   Batch 3: economy, technology, environment, news, sports
--   Batch 4: emotion, culture, humanities, presentation, greeting
--   Batch 5: academic, discussion, negotiation
-- ============================================


-- ============================================
-- 03-c2-colloc-idioms-batch2.sql
-- ============================================
-- ============================================================
-- C2-level Collocations and Idioms — Batch 2
-- Topics: health, weather, transport, media, education
-- 5 collocations + 5 idioms per topic = 50 total entries
-- ============================================================

-- ============================================================
-- HEALTH — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_health_C2_01', 'exhibit', 'symptoms', 'exhibit symptoms', '증상을 보이다', 'show', '의학 논문이나 임상 보고서에서 증상의 발현을 기술할 때 표준이에요. ''show''보다 객관적이고 격식 있어요.', 'The patient began to exhibit symptoms consistent with early-onset Parkinson''s disease.', '환자는 조기 발병 파킨슨병과 일치하는 증상을 보이기 시작했어요.', 'Approximately 30 percent of subjects exhibited symptoms within 72 hours of exposure.', '피험자의 약 30%가 노출 후 72시간 이내에 증상을 보였어요.', 'C2', 'health', 3, 'clinical examination'),
('col_health_C2_02', 'alleviate', 'discomfort', 'alleviate discomfort', '불편함을 완화하다', 'reduce', '통증이나 불쾌감을 부드럽게 줄여준다는 의학적·격식 표현이에요. 처방 안내문이나 의료 광고에 자주 등장해요.', 'A warm compress can alleviate discomfort in the affected joint.', '온찜질은 환부 관절의 불편함을 완화할 수 있어요.', 'The new formulation is designed to alleviate discomfort without inducing drowsiness.', '새 제형은 졸음을 유발하지 않으면서 불편함을 완화하도록 설계됐어요.', 'C2', 'health', 3, 'medical relief'),
('col_health_C2_03', 'administer', 'treatment', 'administer treatment', '치료를 시행하다', 'give', '의료진이 공식적으로 치료를 시행한다는 뜻으로, 진료 기록이나 의학 저널의 표준 표현이에요.', 'Paramedics administered treatment at the scene before transferring the patient.', '구급대원은 환자를 이송하기 전에 현장에서 치료를 시행했어요.', 'The trial assessed how quickly clinicians could administer treatment in remote areas.', '그 임상 시험은 의료진이 오지에서 얼마나 빨리 치료를 시행할 수 있는지 평가했어요.', 'C2', 'health', 3, 'emergency treatment'),
('col_health_C2_04', 'succumb', 'illness', 'succumb to illness', '병에 굴복하다', 'lose', '병을 이기지 못하고 결국 사망하거나 압도된다는 문어체·격식 표현이에요. 부고나 역사적 기술에 자주 써요.', 'The renowned scholar succumbed to a prolonged illness at the age of eighty-two.', '저명한 학자는 82세에 오랜 투병 끝에 별세했어요.', 'Without timely intervention, vulnerable patients may succumb to the illness within days.', '적시 개입이 없으면 취약한 환자는 며칠 안에 병에 굴복할 수 있어요.', 'C2', 'health', 3, 'hospital bedside'),
('col_health_C2_05', 'warrant', 'intervention', 'warrant intervention', '개입을 요하다', 'need', '심각도나 위험도가 개입을 정당화한다는 의학적·정책적 표현이에요. 임상 가이드라인이나 보고서에 표준이에요.', 'Elevated troponin levels typically warrant immediate cardiac intervention.', '트로포닌 수치 상승은 대개 즉각적인 심장 개입을 요해요.', 'The committee concluded that the situation warranted intervention at the federal level.', '위원회는 그 상황이 연방 차원의 개입을 요한다고 결론지었어요.', 'C2', 'health', 3, 'medical chart')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- HEALTH — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_health_C2_01', 'under the weather', '몸이 좋지 않은', '날씨 아래에 있는', '가벼운 컨디션 난조를 완곡하게 표현해요. 직장이나 격식 있는 자리에서 결석 사유로 자주 써요.', 'I am afraid I will have to postpone our meeting; I am feeling rather under the weather.', '죄송하지만 회의를 미뤄야겠어요. 몸이 좀 좋지 않아요.', 'She has been under the weather since returning from her trip abroad.', '그녀는 해외여행에서 돌아온 뒤로 컨디션이 좋지 않아요.', 'If you are under the weather, please do not hesitate to take a sick day.', '몸이 안 좋으시면, 주저 말고 병가를 쓰세요.', 'C2', 'health', 3, 'feeling unwell', 1),
('idm_health_C2_02', 'a clean bill of health', '건강 이상 없음', '깨끗한 건강 증명서', '검진이나 검사 후 아무 이상이 없다는 공식적 결과예요. 의료 맥락뿐 아니라 감사나 점검 결과에도 비유적으로 써요.', 'After a battery of tests, the cardiologist gave him a clean bill of health.', '여러 검사를 거친 끝에 심장 전문의는 그에게 건강 이상 없음 판정을 내렸어요.', 'The auditors gave the firm''s financials a clean bill of health.', '감사인은 그 회사의 재무 상태에 이상이 없다고 평가했어요.', 'She was relieved to receive a clean bill of health from her oncologist.', '그녀는 종양 전문의로부터 이상 없음 판정을 받고 안도했어요.', 'C2', 'health', 3, 'medical checkup', 2),
('idm_health_C2_03', 'on the mend', '회복 중인', '고치는 중인', '병이나 부상에서 점차 나아지고 있다는 부드러운 표현이에요. 의사 소견이나 안부 인사에 격식 있게 어울려요.', 'Following the surgery, the patient is reportedly on the mend.', '수술 후 환자는 회복 중인 것으로 알려졌어요.', 'I am relieved to hear your mother is on the mend.', '어머님께서 회복 중이시라니 다행이에요.', 'The economy, much like a convalescent patient, appears to be on the mend.', '경제는 회복 중인 환자처럼 점차 나아지고 있는 듯해요.', 'C2', 'health', 3, 'recovery hospital', 3),
('idm_health_C2_04', 'in the prime of life', '인생의 전성기에', '인생의 절정에', '신체적·정신적으로 가장 왕성한 시기를 묘사하는 문어체 표현이에요. 부고나 전기, 격식 있는 글에서 자주 보여요.', 'It is a tragedy that he was struck down in the prime of life.', '그가 인생의 전성기에 쓰러진 건 비극이에요.', 'She founded the institute while still in the prime of life.', '그녀는 인생의 전성기에 그 연구소를 설립했어요.', 'Many great works of art are produced when artists are in the prime of life.', '많은 위대한 예술 작품은 예술가가 전성기에 있을 때 탄생해요.', 'C2', 'health', 3, 'middle age portrait', 4),
('idm_health_C2_05', 'burning the candle at both ends', '몸을 혹사하다', '양초를 양쪽에서 태우다', '쉬지 않고 일하거나 놀아 몸을 망가뜨린다는 격식 있는 비유예요. 의사 권고나 사설에서 건강 경고로 자주 써요.', 'Physicians warn that burning the candle at both ends can precipitate serious health consequences.', '의사들은 몸을 혹사하면 심각한 건강 문제를 초래할 수 있다고 경고해요.', 'After months of burning the candle at both ends, she was diagnosed with chronic fatigue.', '몇 달간 몸을 혹사한 끝에 그녀는 만성피로 진단을 받았어요.', 'He admitted that burning the candle at both ends had finally caught up with him.', '그는 몸을 혹사해온 대가를 결국 치르게 됐다고 인정했어요.', 'C2', 'health', 3, 'exhausted professional', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- WEATHER — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_weather_C2_01', 'weather', 'storm', 'weather a storm', '위기를 견뎌내다', 'survive', '실제 폭풍을 견디는 뜻과 비유적으로 위기를 헤쳐나간다는 뜻 모두로 써요. 비즈니스 사설이나 정치 기사의 단골 표현이에요.', 'The vessel weathered the storm despite sustaining considerable damage.', '그 선박은 상당한 손상을 입었지만 폭풍을 견뎌냈어요.', 'The firm has weathered numerous economic storms over its centenary history.', '그 회사는 100년 역사 동안 수많은 경제 위기를 헤쳐왔어요.', 'C2', 'weather', 3, 'ship in storm'),
('col_weather_C2_02', 'brave', 'elements', 'brave the elements', '악천후를 무릅쓰다', 'face', '비, 눈, 바람 등 자연의 가혹한 조건에도 굴하지 않고 나선다는 문학적·격식 표현이에요. 여행기나 등반 기사에 자주 등장해요.', 'Hundreds of pilgrims braved the elements to attend the dawn ceremony.', '수백 명의 순례자들이 악천후를 무릅쓰고 새벽 의식에 참석했어요.', 'The expedition team braved the elements for six gruelling weeks.', '원정대는 6주간의 혹독한 시간 동안 악천후를 무릅썼어요.', 'C2', 'weather', 3, 'hiker in blizzard'),
('col_weather_C2_03', 'endure', 'inclement weather', 'endure inclement weather', '궂은 날씨를 견디다', 'have', '''inclement weather''는 격식 있는 ''궂은 날씨''예요. 항공 안내, 공식 발표, 기상 보고서의 표준 표현이에요.', 'Passengers were asked to endure the inclement weather while the runway was cleared.', '활주로 정리 동안 승객들은 궂은 날씨를 견뎌야 했어요.', 'The infrastructure must endure inclement weather throughout the winter months.', '그 기반 시설은 겨울 내내 궂은 날씨를 견뎌야 해요.', 'C2', 'weather', 3, 'airport delay snow'),
('col_weather_C2_04', 'herald', 'change', 'herald a change', '변화를 알리다', 'show', '어떤 사건이나 현상이 더 큰 변화의 신호탄이 된다는 문학적·언론적 표현이에요. 사설이나 분석 기사에 잘 어울려요.', 'The early frost may herald a change in the region''s growing season.', '이른 서리는 그 지역 농작기의 변화를 알리는 신호일 수 있어요.', 'Falling barometric pressure heralds a change in the prevailing weather pattern.', '기압 하락은 우세한 기상 패턴의 변화를 예고해요.', 'C2', 'weather', 3, 'autumn frost'),
('col_weather_C2_05', 'shroud', 'fog', 'shroud in fog', '안개로 뒤덮다', 'cover', '안개나 어둠이 무언가를 완전히 가려 신비롭거나 음울한 분위기를 자아낼 때 써요. 문학적·서술적 표현이에요.', 'The valley was shrouded in fog so dense that visibility fell to mere metres.', '계곡은 가시거리가 몇 미터에 불과할 정도로 짙은 안개로 뒤덮였어요.', 'At dawn, the medieval town remained shrouded in fog.', '동틀 무렵, 그 중세 도시는 여전히 안개에 휩싸여 있었어요.', 'C2', 'weather', 3, 'foggy valley')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- WEATHER — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_weather_C2_01', 'the calm before the storm', '폭풍 전의 고요', '폭풍 전의 고요', '큰 일이 벌어지기 직전의 부자연스러운 평온함을 묘사해요. 정치, 비즈니스, 군사 분석에서 자주 인용돼요.', 'The eerie silence in the market may well be the calm before the storm.', '시장의 섬뜩한 침묵은 어쩌면 폭풍 전의 고요일지도 몰라요.', 'Diplomats fear the ceasefire is merely the calm before the storm.', '외교관들은 그 휴전이 폭풍 전의 고요에 불과할까 봐 우려해요.', 'Election week was the calm before the storm of legal challenges that followed.', '선거 주간은 뒤이은 법적 다툼의 폭풍 전 고요였어요.', 'C2', 'weather', 3, 'still ocean before storm', 1),
('idm_weather_C2_02', 'weather permitting', '날씨가 허락한다면', '날씨가 허락하면', '야외 행사나 일정의 조건을 격식 있게 덧붙일 때 써요. 공식 초대장이나 안내문에 표준이에요.', 'The garden ceremony will commence at five o''clock, weather permitting.', '정원 행사는 날씨가 허락한다면 5시에 시작해요.', 'Weather permitting, the regatta will proceed as scheduled.', '날씨가 허락한다면, 보트 경기는 예정대로 진행돼요.', 'The outdoor lecture, weather permitting, will be held on the quadrangle.', '날씨가 허락한다면 야외 강연은 안뜰에서 열려요.', 'C2', 'weather', 3, 'outdoor wedding', 2),
('idm_weather_C2_03', 'raining cats and dogs', '비가 억수같이 오다', '고양이와 개가 비처럼 오다', '폭우를 묘사하는 전통적이고 다소 옛스러운 표현이에요. 격식 있는 글보다는 일상 대화나 문학적 묘사에 어울려요.', 'It was raining cats and dogs when we emerged from the theatre.', '우리가 극장에서 나왔을 때 비가 억수같이 쏟아지고 있었어요.', 'I shall lend you an umbrella; it is raining cats and dogs.', '우산 빌려드릴게요. 비가 억수같이 와요.', 'Despite the fact that it was raining cats and dogs, the procession continued.', '비가 억수같이 쏟아지는데도 행렬은 계속됐어요.', 'C2', 'weather', 3, 'heavy rain street', 3),
('idm_weather_C2_04', 'every cloud has a silver lining', '나쁜 일에도 좋은 면이 있다', '모든 구름에는 은빛 가장자리가 있다', '어려운 상황에서도 긍정적인 측면이 있다는 격언이에요. 위로나 격려를 격식 있게 표현할 때 잘 어울려요.', 'The recession was devastating, yet every cloud has a silver lining: it spurred innovation.', '경기 침체는 참혹했지만, 나쁜 일에도 좋은 면이 있다고, 그것이 혁신을 자극했어요.', 'She reminded us that every cloud has a silver lining, even in the darkest of times.', '그녀는 가장 어두운 시기에도 좋은 면이 있다고 우리를 일깨워줬어요.', 'Losing the contract was a blow, but every cloud has a silver lining — we found a better client.', '계약을 잃은 건 타격이었지만, 나쁜 일에도 좋은 면이 있어서 더 좋은 고객을 찾았어요.', 'C2', 'weather', 3, 'sunlit cloud', 4),
('idm_weather_C2_05', 'a fair-weather friend', '잘 나갈 때만 친구인 사람', '좋은 날씨일 때만의 친구', '평소엔 잘 지내다가 어려울 때 곁에 없는 친구를 비판하는 격식 있는 표현이에요. 사설이나 회고록에 자주 인용돼요.', 'He proved to be a fair-weather friend, vanishing the moment my fortunes turned.', '그는 잘 나갈 때만 친구였어요. 제 처지가 어려워지자마자 사라졌거든요.', 'Adversity reveals the difference between true allies and fair-weather friends.', '역경은 진정한 동지와 잘 나갈 때만 친구인 사람의 차이를 드러내요.', 'I have no patience for fair-weather friends in this industry.', '저는 이 업계에서 잘 나갈 때만 친구인 사람들을 참아줄 인내가 없어요.', 'C2', 'weather', 3, 'lonely figure', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TRANSPORT — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_transport_C2_01', 'navigate', 'congestion', 'navigate congestion', '혼잡을 헤쳐 나가다', 'drive', '단순한 운전이 아니라 복잡한 교통 상황을 능숙하게 통과한다는 격식 있는 표현이에요. 도시 계획, 물류 보고서에서 자주 써요.', 'Delivery drivers must navigate congestion that has worsened markedly in recent years.', '배송 기사들은 최근 몇 년간 현저히 악화된 혼잡을 헤쳐 나가야 해요.', 'The new ring road allows commuters to navigate congestion more efficiently.', '새 순환도로는 출퇴근하는 사람들이 더 효율적으로 혼잡을 헤쳐 나갈 수 있게 해줘요.', 'C2', 'transport', 3, 'city traffic jam'),
('col_transport_C2_02', 'embark', 'voyage', 'embark on a voyage', '항해를 시작하다', 'start', '배나 비행기로 긴 여정을 시작한다는 문어체 표현이에요. 비유적으로 ''중요한 여정을 시작하다''로도 자주 써요.', 'The vessel embarked on a voyage that would circumnavigate the globe.', '그 선박은 세계 일주가 될 항해를 시작했어요.', 'She embarked on a voyage of self-discovery after leaving the firm.', '그녀는 회사를 떠난 뒤 자아를 찾는 여정을 시작했어요.', 'C2', 'transport', 3, 'cruise ship departure'),
('col_transport_C2_03', 'traverse', 'terrain', 'traverse terrain', '지형을 가로지르다', 'cross', '험하거나 광대한 지형을 가로지른다는 문학적·기술적 표현이에요. 탐험기, 차량 광고, 군사 문서에 잘 어울려요.', 'The all-terrain vehicle is engineered to traverse rugged terrain with ease.', '그 사륜구동차는 험준한 지형을 손쉽게 가로지르도록 설계됐어요.', 'The explorers traversed inhospitable terrain for nearly a year.', '탐험가들은 거의 1년 동안 척박한 지형을 가로질렀어요.', 'C2', 'transport', 3, 'mountain off-road'),
('col_transport_C2_04', 'expedite', 'delivery', 'expedite delivery', '배송을 신속히 처리하다', 'speed up', '공식적이고 절차적인 신속 처리를 의미해요. 물류, 무역, 정부 문서의 표준 표현이에요.', 'A surcharge applies if you wish to expedite delivery to international destinations.', '국제 배송을 신속히 처리하고 싶으시면 추가 요금이 부과돼요.', 'The agency expedited delivery of medical supplies to the disaster zone.', '그 기관은 재난 지역으로의 의료품 배송을 신속히 처리했어요.', 'C2', 'transport', 3, 'express courier'),
('col_transport_C2_05', 'circumvent', 'traffic', 'circumvent traffic', '교통체증을 우회하다', 'avoid', '교통 체증을 영리하게 돌아간다는 격식 표현이에요. ''circumvent''는 규칙이나 장애물을 회피한다는 뉘앙스도 있어요.', 'Seasoned commuters know which back streets to take to circumvent traffic.', '노련한 출퇴근자들은 교통체증을 우회하려고 어느 뒷길로 가야 하는지 알아요.', 'The new app suggests routes designed to circumvent traffic in real time.', '새 앱은 실시간으로 교통체증을 우회하도록 설계된 경로를 제안해요.', 'C2', 'transport', 3, 'navigation app')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TRANSPORT — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_transport_C2_01', 'hit the road', '길을 떠나다', '도로를 치다', '여정을 시작하거나 떠난다는 활기찬 표현이에요. 격식 있는 대화에서는 ''set off''이 더 어울리지만, 신문 기고나 여행기에서도 자주 보여요.', 'After three days of meetings, the delegation was eager to hit the road.', '사흘간의 회의 끝에 대표단은 어서 떠나고 싶어 했어요.', 'We shall hit the road at first light to avoid the morning rush.', '아침 혼잡을 피하려고 동틀 녘에 출발할 거예요.', 'The author hit the road for a six-month sabbatical across the continent.', '그 작가는 6개월의 안식을 위해 대륙 횡단 여행을 떠났어요.', 'C2', 'transport', 3, 'road trip departure', 1),
('idm_transport_C2_02', 'off the beaten track', '인적이 드문 곳에', '다져진 길에서 벗어나서', '관광객이 잘 가지 않는 외진 곳을 묘사하는 문학적·여행 기사 표현이에요. 격식 있는 가이드북이나 칼럼에서 표준이에요.', 'The villa lies somewhat off the beaten track, which is precisely its charm.', '그 별장은 인적이 드문 곳에 있는데, 그 점이 바로 매력이에요.', 'Travellers seeking authenticity often venture off the beaten track.', '진정성을 찾는 여행자들은 종종 인적이 드문 곳까지 모험해요.', 'The journalist preferred destinations off the beaten track to crowded resorts.', '그 기자는 붐비는 리조트보다 인적이 드문 곳을 선호했어요.', 'C2', 'transport', 3, 'remote village road', 2),
('idm_transport_C2_03', 'in the same boat', '같은 처지에 있는', '같은 배에 타고 있는', '여러 사람이 같은 어려움이나 상황을 공유한다는 표현이에요. 격식 있는 연설이나 협상에서 공감을 표할 때 자주 써요.', 'During the pandemic, small businesses found themselves in the same boat.', '팬데믹 동안 소상공인들은 모두 같은 처지에 놓여 있었어요.', 'We are all in the same boat, and only collective action will see us through.', '우리는 모두 같은 처지에 있고, 집단적 행동만이 우리를 헤쳐 나가게 해줄 거예요.', 'The minister acknowledged that European allies were in the same boat economically.', '장관은 유럽 동맹국들이 경제적으로 같은 처지라고 인정했어요.', 'C2', 'transport', 3, 'shared boat', 3),
('idm_transport_C2_04', 'miss the boat', '기회를 놓치다', '배를 놓치다', '결정적인 기회를 시기를 놓쳐 잡지 못했다는 비유예요. 비즈니스 분석, 투자 칼럼에서 자주 인용돼요.', 'Investors who hesitated in 2010 effectively missed the boat on the tech boom.', '2010년에 망설였던 투자자들은 사실상 기술 붐의 기회를 놓쳤어요.', 'If we do not act now, we shall miss the boat entirely.', '지금 행동하지 않으면 기회를 완전히 놓칠 거예요.', 'The publisher missed the boat on streaming and never recovered.', '그 출판사는 스트리밍 기회를 놓쳐 결국 회복하지 못했어요.', 'C2', 'transport', 3, 'departing ship', 4),
('idm_transport_C2_05', 'drive a hard bargain', '강하게 흥정하다', '단단한 거래를 운전하다', '협상에서 자기에게 매우 유리한 조건을 끈질기게 요구한다는 뜻이에요. 협상 기사나 비즈니스 회고록의 단골 표현이에요.', 'The acquiring firm is known to drive a hard bargain in cross-border deals.', '그 인수 회사는 국경 간 거래에서 강하게 흥정하기로 유명해요.', 'She drove a hard bargain and walked away with terms few thought possible.', '그녀는 강하게 흥정해서 거의 불가능하다고 여겨졌던 조건을 얻어냈어요.', 'You will need to drive a hard bargain if you hope to secure the property at that price.', '그 가격에 부동산을 확보하려면 강하게 흥정해야 할 거예요.', 'C2', 'transport', 3, 'negotiation handshake', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- MEDIA — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_media_C2_01', 'garner', 'attention', 'garner attention', '주목을 받다', 'get', '시간과 가치를 들여 주목이나 인정을 모은다는 격식 있는 표현이에요. 언론, 학술, 마케팅 보도자료에서 자주 보여요.', 'The documentary garnered widespread attention upon its festival debut.', '그 다큐멘터리는 영화제 데뷔와 동시에 폭넓은 주목을 받았어요.', 'The whistleblower''s allegations garnered international attention.', '내부 고발자의 폭로는 국제적 주목을 받았어요.', 'C2', 'media', 3, 'press conference'),
('col_media_C2_02', 'disseminate', 'information', 'disseminate information', '정보를 전파하다', 'share', '정보를 광범위하고 체계적으로 퍼뜨린다는 의미예요. 정부, 학술, 저널리즘 문서의 표준 표현이에요.', 'Public health officials worked to disseminate information about the outbreak.', '공중보건 관리들은 그 발병에 대한 정보를 전파하기 위해 애썼어요.', 'Social media platforms can disseminate information at unprecedented speed.', '소셜 미디어 플랫폼은 전례 없는 속도로 정보를 전파할 수 있어요.', 'C2', 'media', 3, 'news broadcast'),
('col_media_C2_03', 'shape', 'public opinion', 'shape public opinion', '여론을 형성하다', 'change', '대중의 인식과 태도에 의도적으로 영향을 미친다는 정치·언론 분석의 표준 표현이에요.', 'Editorial cartoons have long served to shape public opinion in subtle ways.', '시사 만평은 오랫동안 여론을 미묘하게 형성하는 역할을 해왔어요.', 'Algorithms increasingly shape public opinion in ways we do not fully understand.', '알고리즘은 우리가 완전히 이해하지 못하는 방식으로 점점 더 여론을 형성하고 있어요.', 'C2', 'media', 3, 'newspaper editorial'),
('col_media_C2_04', 'fabricate', 'narrative', 'fabricate a narrative', '서사를 조작하다', 'make', '사실이 아닌 이야기를 의도적으로 꾸며낸다는 비판적 표현이에요. 미디어 비평, 정치 보도에 자주 등장해요.', 'Critics accused the tabloid of fabricating a narrative to vilify the candidate.', '비평가들은 그 타블로이드가 후보자를 비방하기 위해 서사를 조작했다고 비난했어요.', 'It is dangerous when state-controlled outlets fabricate narratives unchallenged.', '국가가 통제하는 매체가 견제 없이 서사를 조작하는 건 위험해요.', 'C2', 'media', 3, 'fake news headline'),
('col_media_C2_05', 'court', 'controversy', 'court controversy', '논란을 자초하다', 'cause', '논란이 될 만한 발언이나 행동을 일부러, 혹은 기꺼이 한다는 격식 표현이에요. 명사 분석이나 인물 평론에서 자주 보여요.', 'The author has consistently courted controversy throughout her career.', '그 작가는 경력 내내 일관되게 논란을 자초해 왔어요.', 'The director''s latest film courts controversy by depicting historical events provocatively.', '그 감독의 최신 영화는 역사적 사건을 도발적으로 묘사하며 논란을 자초해요.', 'C2', 'media', 3, 'provocative artist')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- MEDIA — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_media_C2_01', 'read between the lines', '행간을 읽다', '줄 사이를 읽다', '명시적으로 쓰지 않은 의도나 함의를 파악한다는 뜻이에요. 미디어 비평, 외교 분석, 문학 평론의 단골 표현이에요.', 'Diplomats are trained to read between the lines of carefully worded communiqués.', '외교관들은 신중하게 작성된 공동성명의 행간을 읽도록 훈련받아요.', 'If you read between the lines, the report is unmistakably critical of the regulator.', '행간을 읽어보면, 그 보고서는 분명히 규제 기관을 비판하고 있어요.', 'Skilled readers know to read between the lines of any press release.', '능숙한 독자는 어떤 보도자료든 행간을 읽을 줄 알아요.', 'C2', 'media', 3, 'newspaper close-up', 1),
('idm_media_C2_02', 'in the limelight', '스포트라이트를 받는', '석회 조명 안에', '대중의 관심과 미디어 노출의 중심에 있다는 격식 있는 표현이에요. 셀러브리티, 정치인, 학자에 대한 글에 자주 써요.', 'The young laureate has been in the limelight ever since the prize was announced.', '그 젊은 수상자는 상이 발표된 뒤로 줄곧 스포트라이트를 받고 있어요.', 'Few politicians thrive when permanently in the limelight.', '계속 스포트라이트를 받으면서도 잘 해내는 정치인은 드물어요.', 'She prefers to work behind the scenes rather than be in the limelight.', '그녀는 스포트라이트를 받기보다는 무대 뒤에서 일하는 걸 선호해요.', 'C2', 'media', 3, 'stage spotlight', 2),
('idm_media_C2_03', 'spin a yarn', '꾸며낸 이야기를 하다', '실을 잣다', '길고 흥미진진하지만 진실성은 의심스러운 이야기를 들려준다는 뜻이에요. 문학 비평, 인물 평전에 격식 있게 어울려요.', 'The veteran reporter could spin a yarn that held the newsroom in rapt attention.', '그 베테랑 기자는 편집실 전체를 집중시킬 만한 흥미진진한 이야기를 풀어낼 줄 알았어요.', 'Critics suggested the memoirist was spinning a yarn rather than recording history.', '비평가들은 그 회고록 작가가 역사를 기록하기보다는 이야기를 꾸며내고 있다고 했어요.', 'He has a remarkable gift for spinning a yarn that few can match.', '그는 누구도 따라잡기 힘든, 이야기를 풀어내는 비범한 재능이 있어요.', 'C2', 'media', 3, 'storyteller', 3),
('idm_media_C2_04', 'stir up a hornet''s nest', '벌집을 쑤시다', '말벌 둥지를 휘젓다', '큰 반발이나 분노를 불러일으키는 발언이나 행동을 한다는 표현이에요. 정치 칼럼, 사설에서 자주 인용돼요.', 'The op-ed stirred up a hornet''s nest among the academy''s senior fellows.', '그 사설은 학회 시니어 회원들 사이에 벌집을 쑤신 듯한 반발을 일으켰어요.', 'By naming names, the journalist stirred up a hornet''s nest she may come to regret.', '실명을 거론함으로써 그 기자는 후회할 수도 있는 벌집을 쑤셔놓았어요.', 'The proposal threatens to stir up a hornet''s nest within the committee.', '그 제안은 위원회 안에서 벌집을 쑤셔놓을 우려가 있어요.', 'C2', 'media', 3, 'controversy debate', 4),
('idm_media_C2_05', 'the cat is out of the bag', '비밀이 새다', '고양이가 가방 밖으로 나왔다', '숨겨두던 비밀이 의도치 않게 공개됐다는 뜻이에요. 격식 있는 보도에서도 자연스러우며, 폭로 기사의 헤드라인에 자주 쓰여요.', 'Once the merger documents leaked, the cat was well and truly out of the bag.', '합병 서류가 유출되자, 비밀은 완전히 다 새 버렸어요.', 'There is no point denying it now — the cat is out of the bag.', '이제 부인해도 소용없어요. 비밀은 다 새 버렸어요.', 'The cat was out of the bag the moment the journalist began asking specific questions.', '기자가 구체적인 질문을 시작한 순간, 비밀은 다 새 버렸어요.', 'C2', 'media', 3, 'leaked document', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- EDUCATION — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_education_C2_01', 'pursue', 'scholarship', 'pursue scholarship', '학문을 추구하다', 'study', '단순한 공부가 아니라 평생에 걸친 학문적 탐구를 의미하는 격식 표현이에요. 학술 추천서나 학자의 약력에 잘 어울려요.', 'After completing her doctorate, she chose to pursue scholarship at Oxford.', '박사 학위를 마친 뒤, 그녀는 옥스퍼드에서 학문을 추구하기로 했어요.', 'The institute supports those who wish to pursue scholarship in the humanities.', '그 연구소는 인문학 분야에서 학문을 추구하고자 하는 이들을 지원해요.', 'C2', 'education', 3, 'university library'),
('col_education_C2_02', 'expand', 'horizons', 'expand horizons', '시야를 넓히다', 'open', '경험이나 학습을 통해 사고와 가능성의 범위를 확장한다는 격식 있는 표현이에요. 대학 안내서, 추천사에 자주 등장해요.', 'A semester abroad invariably expands students'' horizons in profound ways.', '한 학기의 해외 연수는 어김없이 학생들의 시야를 깊이 있게 넓혀줘요.', 'Reading widely is the surest means of expanding one''s horizons.', '폭넓은 독서는 시야를 넓히는 가장 확실한 방법이에요.', 'C2', 'education', 3, 'study abroad students'),
('col_education_C2_03', 'impart', 'knowledge', 'impart knowledge', '지식을 전수하다', 'give', '지식이나 지혜를 정성껏 전달한다는 격식 있는 교육적 표현이에요. 교수, 멘토, 장인에 관한 글의 표준 표현이에요.', 'A great mentor does more than impart knowledge; she shapes character.', '훌륭한 멘토는 지식을 전수하는 것 이상으로 인격을 형성해줘요.', 'The professor sought to impart knowledge that would outlast any single lecture.', '그 교수는 어떤 한 강의보다 더 오래 남을 지식을 전수하고자 했어요.', 'C2', 'education', 3, 'professor lecturing'),
('col_education_C2_04', 'foster', 'critical thinking', 'foster critical thinking', '비판적 사고를 기르다', 'teach', '비판적 사고력을 자연스럽게 길러준다는 교육학 표준 표현이에요. 커리큘럼 설명서, 교육 정책 문서에 자주 보여요.', 'The new curriculum is explicitly designed to foster critical thinking from an early age.', '새 교육과정은 어린 나이부터 비판적 사고를 기르도록 명시적으로 설계됐어요.', 'Socratic seminars foster critical thinking far more effectively than rote learning.', '소크라테스식 세미나는 암기 학습보다 훨씬 효과적으로 비판적 사고를 길러줘요.', 'C2', 'education', 3, 'classroom discussion'),
('col_education_C2_05', 'cultivate', 'expertise', 'cultivate expertise', '전문성을 함양하다', 'get', '시간과 노력을 들여 깊은 전문성을 키운다는 격식 있는 표현이에요. 경력 개발, 학술 약력, 채용 공고에 자주 써요.', 'It takes a decade of focused practice to cultivate expertise of this calibre.', '이 정도 수준의 전문성을 함양하려면 10년의 집중적인 수련이 필요해요.', 'The fellowship enables scholars to cultivate expertise in emerging fields.', '그 펠로우십은 학자들이 신흥 분야에서 전문성을 함양할 수 있게 해줘요.', 'C2', 'education', 3, 'researcher laboratory')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- EDUCATION — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_education_C2_01', 'learn the ropes', '요령을 익히다', '밧줄들을 배우다', '새 일이나 환경의 기본적인 일 처리 방법을 배운다는 표현이에요. 인사·온보딩 자료나 회고록에서 격식 있게 자주 써요.', 'New associates spend their first six months learning the ropes under senior partners.', '신입 변호사들은 첫 6개월 동안 시니어 파트너 밑에서 요령을 익혀요.', 'Even seasoned professionals need time to learn the ropes in a new institution.', '경험 많은 전문가라도 새 기관에서 요령을 익히려면 시간이 필요해요.', 'She learned the ropes quickly and was promoted within a year.', '그녀는 요령을 빨리 익혀 1년 안에 승진했어요.', 'C2', 'education', 3, 'mentor trainee', 1),
('idm_education_C2_02', 'hit the books', '본격적으로 공부하다', '책을 치다', '시험이나 큰 과제를 앞두고 집중해서 공부하기 시작한다는 표현이에요. 격식과 비격식 모두에서 자연스럽게 써요.', 'With finals fast approaching, even the most relaxed students began to hit the books.', '기말고사가 다가오자, 가장 느긋한 학생들조차 본격적으로 공부하기 시작했어요.', 'I shall have to hit the books in earnest if I hope to pass the bar examination.', '변호사 시험에 합격하려면 정말 본격적으로 공부해야 할 거예요.', 'He hit the books for three solid months before sitting the entrance examination.', '그는 입학 시험을 보기 전 꼬박 3개월간 본격적으로 공부했어요.', 'C2', 'education', 3, 'student late night study', 2),
('idm_education_C2_03', 'pass with flying colours', '우수한 성적으로 통과하다', '깃발을 휘날리며 통과하다', '시험이나 평가를 매우 우수한 성적으로 통과한다는 격식 있는 표현이에요. 추천서나 학업 성과 보고에 잘 어울려요.', 'She passed her viva with flying colours, much to the delight of her supervisor.', '그녀는 지도교수가 매우 기뻐할 만큼 박사 구술시험을 우수하게 통과했어요.', 'Despite the difficulty of the assessment, he passed with flying colours.', '평가의 난도에도 불구하고 그는 우수한 성적으로 통과했어요.', 'The audit team passed the regulatory review with flying colours.', '감사팀은 규제 검토를 매우 우수한 성적으로 통과했어요.', 'C2', 'education', 3, 'graduation ceremony', 3),
('idm_education_C2_04', 'back to the drawing board', '처음부터 다시 시작해야 한다', '제도판으로 돌아가다', '시도가 실패해서 처음 단계부터 다시 구상해야 한다는 표현이에요. 연구 발표, 프로젝트 회고에 격식 있게 어울려요.', 'When the experiment failed to replicate, the team went back to the drawing board.', '실험 재현에 실패하자, 연구팀은 처음부터 다시 시작해야 했어요.', 'The committee rejected the proposal, sending us back to the drawing board.', '위원회가 제안을 거부해서, 우리는 처음부터 다시 시작해야 했어요.', 'After three rejected drafts, it was time to go back to the drawing board.', '거절된 초안 셋 끝에, 처음부터 다시 시작해야 할 때가 됐어요.', 'C2', 'education', 3, 'drafting blueprint', 4),
('idm_education_C2_05', 'old school', '고전적인', '옛 학교의', '전통적이고 고전적인 방식이나 사람을 의미해요. 보통 존경 어린 뉘앙스를 띠며, 학자나 장인에 대한 평론에 자주 등장해요.', 'Professor Hartley is decidedly old school: lectures from handwritten notes, no slides.', '하틀리 교수님은 단연 고전적이세요. 손글씨 노트로 강의하시고 슬라이드는 안 쓰세요.', 'There is something refreshing about her old-school approach to mentorship.', '그녀의 고전적인 멘토링 방식에는 신선한 무언가가 있어요.', 'Old-school scholarship demanded a fluency in three or four classical languages.', '고전적인 학문은 서너 개 고전어에 대한 능통함을 요구했어요.', 'C2', 'education', 3, 'vintage classroom', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- 04-c2-colloc-idioms-batch3.sql
-- ============================================
-- ============================================================
-- C2-level Collocations and Idioms — Batch 3
-- Topics: economy, technology, environment, news, sports
-- 5 collocations + 5 idioms per topic = 50 total entries
-- ============================================================

-- ============================================================
-- ECONOMY — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_economy_C2_01', 'weather', 'downturn', 'weather a downturn', '경기 침체를 견뎌내다', 'survive', '경제적 어려움을 견뎌낸다는 격식 표현이에요. ''survive''보다 능동적으로 버틴다는 뉘앙스가 강해요.', 'Well-capitalised firms are better positioned to weather a prolonged downturn.', '자본이 탄탄한 기업들이 장기 침체를 견뎌낼 입지가 더 좋아요.', 'The conglomerate weathered the 2008 downturn without layoffs.', '그 대기업은 해고 없이 2008년 침체를 견뎌냈어요.', 'C2', 'economy', 3, 'stock market chart'),
('col_economy_C2_02', 'stimulate', 'growth', 'stimulate growth', '성장을 촉진하다', 'make', '정책이나 투자가 경제 성장을 자극한다는 표준 경제 용어예요. 금융 기사와 정책 보고서에 자주 등장해요.', 'The central bank cut rates to stimulate growth in the manufacturing sector.', '중앙은행은 제조업 성장을 촉진하기 위해 금리를 인하했어요.', 'Tax incentives are designed to stimulate growth in green industries.', '세제 혜택은 친환경 산업의 성장을 촉진하기 위해 설계됐어요.', 'C2', 'economy', 3, 'economic growth chart'),
('col_economy_C2_03', 'curb', 'inflation', 'curb inflation', '인플레이션을 억제하다', 'stop', '인플레이션의 상승세를 통제하고 억제한다는 의미예요. ''stop''은 너무 단정적이라 경제 맥락에 어울리지 않아요.', 'Aggressive rate hikes were necessary to curb runaway inflation.', '폭주하는 인플레이션을 억제하기 위해 공격적인 금리 인상이 필요했어요.', 'The new fiscal policy aims to curb inflation without triggering a recession.', '새 재정 정책은 경기 침체 없이 인플레이션을 억제하는 것이 목표예요.', 'C2', 'economy', 3, 'inflation graph'),
('col_economy_C2_04', 'hedge', 'risk', 'hedge against risk', '위험을 헤지하다', 'protect', '금융 상품으로 위험을 상쇄한다는 전문 용어예요. ''protect against''보다 정확하고 기술적이에요.', 'Institutional investors hedge against currency risk using derivatives.', '기관 투자자들은 파생상품으로 환위험을 헤지해요.', 'Gold has traditionally been used to hedge against inflation risk.', '금은 전통적으로 인플레이션 위험을 헤지하는 데 사용돼 왔어요.', 'C2', 'economy', 3, 'financial derivatives'),
('col_economy_C2_05', 'fuel', 'speculation', 'fuel speculation', '추측을 부추기다', 'cause', '소문이나 추측에 불을 지핀다는 뉘앙스예요. 시장이나 인수합병 기사에서 자주 보여요.', 'The CEO''s sudden resignation fuelled speculation about an imminent takeover.', 'CEO의 갑작스러운 사임은 임박한 인수에 대한 추측을 부추겼어요.', 'Vague guidance fuelled speculation among analysts.', '모호한 가이던스가 애널리스트들 사이에서 추측을 부추겼어요.', 'C2', 'economy', 3, 'speculation news')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ECONOMY — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_economy_C2_01', 'tighten one''s belt', '허리띠를 졸라매다', '벨트를 조이다', '지출을 줄이고 검소하게 산다는 뜻이에요. 한국어와 거의 똑같은 비유라서 격식·비격식 모두에 자연스러워요.', 'Households across the country are tightening their belts amid soaring energy costs.', '치솟는 에너지 비용 속에서 전국의 가계가 허리띠를 졸라매고 있어요.', 'The firm has had to tighten its belt following the loss of its largest client.', '그 회사는 최대 고객을 잃은 뒤 허리띠를 졸라매야 했어요.', 'Consumers tend to tighten their belts during periods of uncertainty.', '소비자들은 불확실성이 큰 시기에 허리띠를 졸라매는 경향이 있어요.', 'C2', 'economy', 3, 'belt budget', 1),
('idm_economy_C2_02', 'money talks', '돈이 말한다', '돈이 말한다', '결국 돈이 가장 큰 영향력을 발휘한다는 냉소적인 표현이에요. 정치·비즈니스 평론에서 자주 써요.', 'In lobbying circles, money talks louder than any policy paper.', '로비 업계에서는 어떤 정책 보고서보다 돈이 더 크게 말해요.', 'The deal was finalised within hours — money talks, after all.', '딜은 몇 시간 만에 마무리됐어요. 결국 돈이 말하는 거죠.', 'However noble the cause, money talks in the end.', '아무리 명분이 좋아도 결국엔 돈이 말해요.', 'C2', 'economy', 3, 'cash banknotes', 2),
('idm_economy_C2_03', 'the bottom line', '핵심은, 최종 손익', '맨 아래 줄', '회계상 최종 손익을 가리키거나, 비유적으로 ''핵심 결론''을 뜻해요. 격식 있는 회의에서 결론을 강조할 때 써요.', 'The bottom line is that without restructuring, the firm will not survive the year.', '핵심은 구조조정 없이는 회사가 올해를 못 버틴다는 거예요.', 'Investors care first and foremost about the bottom line.', '투자자들은 무엇보다 먼저 최종 손익을 신경 써요.', 'Sustainability initiatives can ultimately strengthen the bottom line.', '지속가능성 이니셔티브는 결국 손익을 강화할 수 있어요.', 'C2', 'economy', 3, 'financial statement', 3),
('idm_economy_C2_04', 'a drop in the ocean', '바다에 물 한 방울', '바다 속 물 한 방울', '엄청난 규모에 비하면 아주 미미한 양이라는 뜻이에요. 예산이나 기부 규모 논의에서 자주 등장해요.', 'A million-dollar grant is a drop in the ocean compared with the trillions needed.', '필요한 수조 달러에 비하면 백만 달러 보조금은 바다에 물 한 방울이에요.', 'Their charitable contribution, while generous, was a drop in the ocean.', '그들의 기부는 후한 편이지만 바다에 물 한 방울이었어요.', 'Tax breaks for the wealthy address only a drop in the ocean of inequality.', '부유층 세금 감면은 불평등의 바다에 물 한 방울 정도밖에 안 돼요.', 'C2', 'economy', 3, 'ocean drop', 4),
('idm_economy_C2_05', 'cash cow', '꾸준한 수익원', '현금 젖소', '꾸준히 큰 수익을 내는 사업이나 제품을 뜻해요. 비즈니스 전략 논의에서 표준 용어처럼 쓰여요.', 'The legacy software remains the company''s most reliable cash cow.', '레거시 소프트웨어는 여전히 회사의 가장 든든한 캐시카우예요.', 'Streaming subscriptions have become an unexpected cash cow for the studio.', '스트리밍 구독은 그 스튜디오에 뜻밖의 캐시카우가 됐어요.', 'Diversifying away from a single cash cow is essential for long-term resilience.', '하나의 캐시카우에서 벗어나 다각화하는 게 장기 회복력에 필수예요.', 'C2', 'economy', 3, 'dairy cow money', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TECHNOLOGY — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_technology_C2_01', 'leverage', 'innovation', 'leverage innovation', '혁신을 활용하다', 'use', '기술 혁신을 전략적으로 활용해 성과를 낸다는 비즈니스 표현이에요. ''use''보다 훨씬 격식 있고 능동적이에요.', 'Startups must leverage innovation to compete with established incumbents.', '스타트업은 기존 강자들과 경쟁하려면 혁신을 활용해야 해요.', 'The firm leveraged AI-driven innovation to streamline its supply chain.', '그 회사는 AI 기반 혁신을 활용해 공급망을 간소화했어요.', 'C2', 'technology', 3, 'innovation lab'),
('col_technology_C2_02', 'pioneer', 'advancement', 'pioneer an advancement', '발전을 선도하다', 'start', '새로운 기술 발전을 가장 먼저 개척하고 이끈다는 뜻이에요. 학술 논문과 산업 보고서에 자주 쓰여요.', 'The lab pioneered key advancements in quantum computing.', '그 연구소는 양자 컴퓨팅의 핵심 발전을 선도했어요.', 'Her team pioneered an advancement in low-power chip design.', '그녀의 팀은 저전력 칩 설계 분야의 발전을 선도했어요.', 'C2', 'technology', 3, 'research lab'),
('col_technology_C2_03', 'harness', 'algorithms', 'harness algorithms', '알고리즘을 활용하다', 'use', '복잡한 알고리즘의 힘을 효과적으로 끌어내 활용한다는 뜻이에요. AI/ML 관련 글에 표준적으로 등장해요.', 'Modern logistics firms harness algorithms to optimise delivery routes in real time.', '현대 물류 기업들은 알고리즘을 활용해 실시간으로 배송 경로를 최적화해요.', 'Researchers harness algorithms to detect anomalies in genomic data.', '연구자들은 알고리즘을 활용해 유전체 데이터의 이상을 탐지해요.', 'C2', 'technology', 3, 'algorithm code'),
('col_technology_C2_04', 'circumvent', 'security', 'circumvent security', '보안을 우회하다', 'avoid', '보안 조치를 교묘하게 우회한다는 격식 표현이에요. 사이버보안과 법률 문서에서 표준 용어예요.', 'The hackers found a novel way to circumvent the firm''s multi-factor security.', '해커들은 그 회사의 다중 인증 보안을 우회하는 새로운 방법을 찾아냈어요.', 'Insiders can sometimes circumvent security protocols undetected.', '내부자는 때때로 보안 프로토콜을 들키지 않고 우회할 수 있어요.', 'C2', 'technology', 3, 'cybersecurity breach'),
('col_technology_C2_05', 'facilitate', 'integration', 'facilitate integration', '통합을 용이하게 하다', 'help', '시스템 간 통합을 매끄럽게 만든다는 뜻이에요. IT 컨설팅과 엔터프라이즈 소프트웨어 문서에 자주 등장해요.', 'Standardised APIs facilitate seamless integration across platforms.', '표준화된 API가 플랫폼 간 매끄러운 통합을 가능하게 해요.', 'Middleware is designed to facilitate integration between legacy and cloud systems.', '미들웨어는 레거시 시스템과 클라우드 시스템 간의 통합을 용이하게 하도록 설계됐어요.', 'C2', 'technology', 3, 'system integration')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TECHNOLOGY — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_technology_C2_01', 'cutting edge', '최첨단의', '자르는 날', '가장 앞선 기술이나 분야를 뜻해요. 형용사로도 자주 쓰여요 — ''cutting-edge technology''처럼요.', 'The startup operates at the cutting edge of generative AI research.', '그 스타트업은 생성형 AI 연구의 최첨단에서 활동해요.', 'Their robotics lab is widely regarded as cutting edge.', '그들의 로봇공학 연구소는 최첨단으로 널리 인정받아요.', 'Staying at the cutting edge requires sustained R&D investment.', '최첨단에 머무르려면 지속적인 R&D 투자가 필요해요.', 'C2', 'technology', 3, 'futuristic tech', 1),
('idm_technology_C2_02', 'ahead of the curve', '앞서가는', '곡선보다 앞에', '시대나 경쟁자들보다 한발 앞서 있다는 뜻이에요. 기술 트렌드나 전략 칭찬에 적합한 격식 표현이에요.', 'Their early bet on cloud computing kept them ahead of the curve.', '클라우드 컴퓨팅에 대한 초기 투자가 그들을 앞서가게 했어요.', 'Companies that stay ahead of the curve tend to dominate emerging markets.', '앞서가는 기업들이 신흥 시장을 장악하는 경향이 있어요.', 'To remain ahead of the curve, the firm reinvests heavily in R&D.', '계속 앞서가기 위해 그 회사는 R&D에 막대하게 재투자해요.', 'C2', 'technology', 3, 'curve graph', 2),
('idm_technology_C2_03', 'on the back burner', '뒤로 미루다', '뒷쪽 화구 위에', '당장 처리하지 않고 우선순위를 낮춰 둔다는 뜻이에요. 프로젝트 관리 회의에서 매우 자주 등장해요.', 'The legacy system upgrade has been put on the back burner until next quarter.', '레거시 시스템 업그레이드는 다음 분기까지 뒤로 미뤄졌어요.', 'They placed the AI ethics review on the back burner during the product launch.', '제품 출시 기간 동안 그들은 AI 윤리 검토를 뒤로 미뤘어요.', 'Important but non-urgent initiatives often sit on the back burner.', '중요하지만 시급하지 않은 일은 종종 뒤로 미뤄지곤 해요.', 'C2', 'technology', 3, 'stove burner', 3),
('idm_technology_C2_04', 'plug and play', '바로 사용 가능한', '꽂으면 작동', '복잡한 설정 없이 바로 작동하는 시스템이나 솔루션을 뜻해요. 형용사처럼 쓰는 게 일반적이에요.', 'The new SaaS platform is essentially plug and play for mid-sized firms.', '새 SaaS 플랫폼은 중견 기업에게 사실상 플러그앤플레이예요.', 'Enterprise clients increasingly expect plug-and-play integrations.', '엔터프라이즈 고객들은 점점 더 플러그앤플레이 통합을 기대해요.', 'Few enterprise solutions are truly plug and play in practice.', '실제로 진정한 플러그앤플레이인 엔터프라이즈 솔루션은 드물어요.', 'C2', 'technology', 3, 'usb plug', 4),
('idm_technology_C2_05', 'a moving target', '계속 변하는 목표', '움직이는 표적', '기준이나 목표가 끊임없이 변해서 맞추기 어렵다는 뜻이에요. 규제, 기술 표준 논의에서 자주 써요.', 'Cybersecurity compliance is very much a moving target in this jurisdiction.', '이 관할권에서 사이버보안 컴플라이언스는 계속 변하는 목표예요.', 'Estimating user behaviour on a new platform is a moving target.', '신규 플랫폼에서의 사용자 행동을 예측하는 건 계속 변하는 목표예요.', 'Regulators are trying to hit a moving target as AI evolves rapidly.', 'AI가 빠르게 진화하면서 규제 당국은 움직이는 표적을 맞히려 애쓰고 있어요.', 'C2', 'technology', 3, 'archery target', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ENVIRONMENT — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_environment_C2_01', 'mitigate', 'emissions', 'mitigate emissions', '배출을 완화하다', 'reduce', '배출량의 영향을 완화한다는 표준 환경 용어예요. IPCC 보고서나 ESG 문서에서 표준 표현이에요.', 'Carbon capture technologies aim to mitigate industrial emissions at the source.', '탄소 포집 기술은 산업 배출을 발생원에서 완화하는 것을 목표로 해요.', 'Governments are under pressure to mitigate emissions ahead of the summit.', '정부는 정상회담을 앞두고 배출을 완화하라는 압박을 받고 있어요.', 'C2', 'environment', 3, 'factory emissions'),
('col_environment_C2_02', 'preserve', 'biodiversity', 'preserve biodiversity', '생물 다양성을 보존하다', 'keep', '생물 다양성을 적극적으로 보존한다는 학술·정책 표현이에요. ''keep''은 캐주얼해서 어울리지 않아요.', 'Protected marine reserves help preserve biodiversity in fragile ecosystems.', '해양 보호구역은 취약한 생태계의 생물 다양성을 보존하는 데 도움이 돼요.', 'Indigenous land stewardship has preserved biodiversity for millennia.', '원주민들의 토지 관리가 수천 년간 생물 다양성을 보존해 왔어요.', 'C2', 'environment', 3, 'rainforest wildlife'),
('col_environment_C2_03', 'exacerbate', 'degradation', 'exacerbate degradation', '훼손을 악화시키다', 'worsen', '환경 훼손을 더 심각하게 만든다는 격식 표현이에요. ''worsen''보다 학술 글에 더 잘 어울려요.', 'Unchecked deforestation exacerbates soil degradation across the basin.', '통제되지 않은 벌목이 유역 전반의 토양 훼손을 악화시켜요.', 'Industrial runoff exacerbates the degradation of coastal wetlands.', '산업 폐수는 연안 습지의 훼손을 악화시켜요.', 'C2', 'environment', 3, 'deforestation'),
('col_environment_C2_04', 'champion', 'sustainability', 'champion sustainability', '지속가능성을 옹호하다', 'support', '지속가능성을 앞장서서 옹호하고 추진한다는 뜻이에요. ESG 리더십을 묘사하는 표준 표현이에요.', 'The CEO has championed sustainability across the firm''s global supply chain.', 'CEO는 전 세계 공급망 전반에 걸쳐 지속가능성을 옹호해 왔어요.', 'NGOs have long championed sustainability in fashion manufacturing.', 'NGO들은 오랫동안 패션 제조에서의 지속가능성을 옹호해 왔어요.', 'C2', 'environment', 3, 'sustainability leader'),
('col_environment_C2_05', 'deplete', 'resources', 'deplete resources', '자원을 고갈시키다', 'use', '자원을 점차 고갈시킨다는 격식 환경 용어예요. ''use''는 너무 중립적이라 위기감을 전달하지 못해요.', 'Intensive agriculture rapidly depletes soil nutrients and groundwater resources.', '집약적 농업은 토양 영양분과 지하수 자원을 빠르게 고갈시켜요.', 'Overfishing has depleted resources in once-thriving coastal communities.', '남획은 한때 번성했던 연안 공동체의 자원을 고갈시켰어요.', 'C2', 'environment', 3, 'dry riverbed')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ENVIRONMENT — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_environment_C2_01', 'going green', '친환경으로 가다', '초록으로 가는 중', '개인이나 조직이 친환경 행동을 채택한다는 뜻이에요. 마케팅과 정책 글에 자주 등장해요.', 'More multinational firms are going green to meet investor expectations.', '더 많은 다국적 기업이 투자자 기대에 부응하려고 친환경으로 전환하고 있어요.', 'The city''s campaign encourages households to go green.', '그 도시의 캠페인은 가정들이 친환경으로 전환하도록 장려해요.', 'Going green is no longer optional for publicly listed companies.', '상장사에게 친환경 전환은 더 이상 선택이 아니에요.', 'C2', 'environment', 3, 'green leaves', 1),
('idm_environment_C2_02', 'a green thumb', '식물을 잘 키우는 재능', '초록색 엄지', '식물을 키우는 데 타고난 재능이 있다는 뜻이에요. 격식 있는 글에서도 부드러운 뉘앙스로 써요.', 'She has a remarkable green thumb — her urban garden flourishes year-round.', '그녀는 식물 키우는 재능이 뛰어나서 도심 정원이 일 년 내내 무성해요.', 'Not everyone is born with a green thumb, but gardening can be learned.', '모두가 식물 키우는 재능을 타고나는 건 아니지만, 정원 가꾸기는 배울 수 있어요.', 'His green thumb has transformed the rooftop into a small ecosystem.', '그의 재능 덕분에 옥상이 작은 생태계로 바뀌었어요.', 'C2', 'environment', 3, 'gardening hands', 2),
('idm_environment_C2_03', 'tree-hugger', '환경 운동가 (다소 비꼬는)', '나무 껴안는 사람', '환경 운동가를 다소 조롱조로 부르는 말이에요. 본인이 자조적으로 쓰거나 비판적 맥락에서 신중하게 써야 해요.', 'Critics dismiss the activists as tree-huggers, but the science is on their side.', '비평가들은 그 활동가들을 환경광이라 깎아내리지만, 과학은 그들 편이에요.', 'Once labelled a tree-hugger, she now advises Fortune 500 firms on ESG.', '한때 환경광이라 불렸던 그녀가 이제 포춘 500대 기업에 ESG 자문을 해요.', 'Calling someone a tree-hugger is increasingly seen as outdated.', '누군가를 트리허거라 부르는 건 점점 시대에 뒤떨어진 표현이 돼가요.', 'C2', 'environment', 3, 'tree forest', 3),
('idm_environment_C2_04', 'tip of the iceberg', '빙산의 일각', '빙산의 끝', '문제의 극히 일부만 드러난 상태를 뜻해요. 환경, 보안, 비즈니스 등 광범위한 격식 맥락에 두루 써요.', 'The reported pollution levels are merely the tip of the iceberg.', '보고된 오염 수치는 빙산의 일각에 불과해요.', 'These violations represent the tip of the iceberg of corporate malpractice.', '이런 위반은 기업 비위의 빙산의 일각이에요.', 'What we know about microplastic contamination is just the tip of the iceberg.', '우리가 미세 플라스틱 오염에 대해 아는 건 빙산의 일각이에요.', 'C2', 'environment', 3, 'iceberg ocean', 4),
('idm_environment_C2_05', 'the last straw', '인내의 한계', '마지막 지푸라기', '오랫동안 쌓여온 문제 위에 결정타가 된 일을 뜻해요. ''the straw that broke the camel''s back''의 줄임 표현이에요.', 'The oil spill was the last straw for the coastal community.', '기름 유출은 그 연안 공동체에게 인내의 한계였어요.', 'Lax enforcement was the last straw that pushed activists to litigate.', '느슨한 집행이 활동가들이 소송에 나서게 한 결정타였어요.', 'For many voters, the deforestation scandal was the last straw.', '많은 유권자에게 그 벌목 스캔들은 인내의 한계였어요.', 'C2', 'environment', 3, 'straw broken', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEWS — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_news_C2_01', 'break', 'story', 'break a story', '특종을 보도하다', 'tell', '다른 매체보다 먼저 뉴스를 보도한다는 저널리즘 표준 표현이에요. 한국어 ''특종''에 해당해요.', 'The investigative team broke the story of the offshore tax scheme.', '탐사 보도팀이 역외 탈세 스킴 특종을 보도했어요.', 'She broke the story that ultimately led to the minister''s resignation.', '그녀가 결국 장관 사임으로 이어진 특종을 보도했어요.', 'C2', 'news', 3, 'newspaper headline'),
('col_news_C2_02', 'fan', 'flames', 'fan the flames', '불에 기름을 붓다', 'increase', '논쟁이나 갈등을 더욱 격화시킨다는 비유적 표현이에요. 언론 비평에서 자주 등장해요.', 'Sensationalist coverage only fans the flames of public outrage.', '선정적인 보도는 대중의 분노에 기름만 부을 뿐이에요.', 'Anonymous leaks have fanned the flames of the diplomatic dispute.', '익명의 유출이 외교 분쟁의 불씨에 기름을 부었어요.', 'C2', 'news', 3, 'flame fire'),
('col_news_C2_03', 'sway', 'opinion', 'sway opinion', '여론을 흔들다', 'change', '여론이나 사람들의 견해를 움직인다는 격식 표현이에요. 정치 보도와 미디어 분석에 표준이에요.', 'Front-page editorials can decisively sway public opinion before an election.', '1면 사설은 선거 직전 여론을 결정적으로 흔들 수 있어요.', 'The documentary swayed opinion against the proposed pipeline.', '그 다큐멘터리는 송유관 계획에 반대하는 여론을 형성했어요.', 'C2', 'news', 3, 'public opinion poll'),
('col_news_C2_04', 'uncover', 'scandal', 'uncover a scandal', '스캔들을 폭로하다', 'find', '오랫동안 숨겨진 스캔들을 파헤쳐 드러낸다는 뜻이에요. 탐사 보도의 핵심 동사예요.', 'A junior reporter uncovered the scandal that engulfed three cabinet ministers.', '한 신참 기자가 세 명의 장관을 휩쓴 스캔들을 폭로했어요.', 'Their nine-month investigation uncovered a sprawling corruption scandal.', '그들의 9개월간의 조사가 광범위한 부패 스캔들을 폭로했어요.', 'C2', 'news', 3, 'investigative journalism'),
('col_news_C2_05', 'circulate', 'rumours', 'circulate rumours', '소문을 퍼뜨리다', 'tell', '소문이 매체나 사람들 사이에 퍼져나간다는 격식 표현이에요. ''spread''보다 좀 더 문어체예요.', 'Tabloids have been circulating rumours of the actress''s engagement for weeks.', '타블로이드들이 그 여배우의 약혼설을 몇 주째 퍼뜨리고 있어요.', 'Online forums circulated rumours that turned out to be fabricated.', '온라인 포럼에서 퍼진 소문은 조작된 것으로 드러났어요.', 'C2', 'news', 3, 'gossip tabloid')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEWS — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_news_C2_01', 'old news', '이미 다 아는 얘기', '오래된 뉴스', '더 이상 새롭지 않거나 모두가 이미 아는 정보를 뜻해요. 격식 있는 자리에서도 가볍게 쓸 수 있어요.', 'The merger rumour is old news in financial circles.', '그 합병설은 금융권에서는 이미 다 아는 얘기예요.', 'By the time the press conference was held, the announcement was old news.', '기자회견이 열렸을 때쯤엔 그 발표는 이미 다 아는 얘기였어요.', 'For seasoned analysts, the policy shift was old news.', '베테랑 애널리스트들에게 그 정책 변화는 이미 다 아는 얘기였어요.', 'C2', 'news', 3, 'old newspaper', 1),
('idm_news_C2_02', 'front page news', '대서특필감', '1면 뉴스', '큰 사건이라 신문 1면에 실릴 만하다는 뜻이에요. 비유적으로 ''엄청난 일''이라는 뉘앙스로도 써요.', 'The CEO''s indictment was front page news across every major outlet.', 'CEO의 기소는 모든 주요 매체에서 대서특필됐어요.', 'A century ago, this scientific breakthrough would have been front page news.', '한 세기 전이었다면 이 과학적 돌파구는 대서특필됐을 거예요.', 'Their wedding was front page news in the celebrity press.', '그들의 결혼은 연예 매체에서 대서특필됐어요.', 'C2', 'news', 3, 'front page headline', 2),
('idm_news_C2_03', 'no news is good news', '무소식이 희소식', '소식 없음이 좋은 소식', '연락이 없다는 건 별일 없다는 뜻이라는 격언이에요. 한국 속담과 거의 동일해서 직관적이에요.', 'Negotiations remain confidential, but no news is good news at this stage.', '협상은 여전히 비공개지만, 이 단계에서는 무소식이 희소식이에요.', 'The audit team has been silent — no news is good news, I suppose.', '감사팀이 조용한데, 무소식이 희소식이겠죠.', 'Sometimes in diplomacy, no news is good news.', '외교에서는 때때로 무소식이 희소식이에요.', 'C2', 'news', 3, 'silent phone', 3),
('idm_news_C2_04', 'hot off the press', '갓 나온 따끈따끈한 소식', '인쇄기에서 막 나온', '방금 막 발표되거나 출간된 따끈따끈한 정보라는 뜻이에요. 보고서나 책의 출시 발표에 잘 어울려요.', 'Hot off the press: the central bank has just announced an emergency rate cut.', '따끈따끈한 소식이에요. 중앙은행이 방금 긴급 금리 인하를 발표했어요.', 'The annual report is hot off the press and ready for distribution.', '연차 보고서가 막 인쇄돼서 배포 준비가 됐어요.', 'Her latest monograph, hot off the press, is already being reviewed widely.', '갓 출간된 그녀의 최신 단행본이 벌써 폭넓게 서평을 받고 있어요.', 'C2', 'news', 3, 'printing press', 4),
('idm_news_C2_05', 'a slow news day', '뉴스가 한가한 날', '느린 뉴스 날', '중요한 사건이 없어서 사소한 이야기가 뉴스를 채우는 날을 뜻해요. 언론 비평에서 자주 등장해요.', 'Such trivial coverage suggests it was a particularly slow news day.', '그런 시시한 보도를 보면 뉴스가 유난히 한가한 날이었나 봐요.', 'On a slow news day, even minor celebrity gossip makes the front page.', '뉴스가 한가한 날엔 사소한 연예 가십도 1면을 장식해요.', 'The story only gained traction because it was a slow news day.', '뉴스가 한가한 날이었기에 그 기사가 주목받은 거예요.', 'C2', 'news', 3, 'empty newsroom', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- SPORTS — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_sports_C2_01', 'demonstrate', 'prowess', 'demonstrate prowess', '기량을 보여주다', 'show', '특히 운동이나 전문 분야의 뛰어난 기량을 격식 있게 드러낸다는 표현이에요. ''show''보다 훨씬 문어체예요.', 'She demonstrated extraordinary prowess on the balance beam in the final round.', '그녀는 결선에서 평균대에서 엄청난 기량을 보여줬어요.', 'The young midfielder demonstrated tactical prowess beyond his years.', '그 어린 미드필더는 나이를 뛰어넘는 전술적 기량을 보여줬어요.', 'C2', 'sports', 3, 'athlete performance'),
('col_sports_C2_02', 'uphold', 'sportsmanship', 'uphold sportsmanship', '스포츠맨십을 지키다', 'keep', '경기 윤리를 일관되게 지킨다는 격식 표현이에요. 올림픽 헌장이나 스포츠 평론에서 자주 보여요.', 'Even in defeat, the captain upheld the highest standards of sportsmanship.', '패배 속에서도 주장은 가장 높은 수준의 스포츠맨십을 지켰어요.', 'Coaches are expected to uphold sportsmanship as a model for younger players.', '코치들은 어린 선수들의 본보기로서 스포츠맨십을 지켜야 해요.', 'C2', 'sports', 3, 'handshake sports'),
('col_sports_C2_03', 'secure', 'victory', 'secure victory', '승리를 거머쥐다', 'get', '경기 끝까지 우위를 지켜 승리를 확정한다는 격식 표현이에요. 스포츠 기사 헤드라인에 단골이에요.', 'A late penalty secured victory for the home side in injury time.', '추가 시간에 막판 페널티킥으로 홈팀이 승리를 거머쥐었어요.', 'They secured victory after a gruelling five-set match.', '그들은 격렬한 5세트 경기 끝에 승리를 거머쥐었어요.', 'C2', 'sports', 3, 'victory celebration'),
('col_sports_C2_04', 'concede', 'defeat', 'concede defeat', '패배를 인정하다', 'lose', '패배를 공식적으로, 품위 있게 인정한다는 격식 표현이에요. 스포츠와 정치 양쪽에서 자주 써요.', 'After a valiant comeback attempt, she finally conceded defeat in the fifth set.', '용감한 역전 시도 끝에 그녀는 5세트에서 결국 패배를 인정했어요.', 'The challenger conceded defeat with a gracious post-match speech.', '도전자는 경기 후 품위 있는 연설로 패배를 인정했어요.', 'C2', 'sports', 3, 'match end'),
('col_sports_C2_05', 'exhibit', 'stamina', 'exhibit stamina', '체력을 보여주다', 'show', '지구력을 격식 있게 드러낸다는 표현이에요. 스포츠 기자나 코칭 보고서에 자주 등장해요.', 'Marathon runners must exhibit remarkable stamina over the final ten kilometres.', '마라톤 선수들은 마지막 10km에서 놀라운 체력을 보여줘야 해요.', 'The veteran goalkeeper exhibited the stamina of a player half his age.', '베테랑 골키퍼는 절반 나이의 선수다운 체력을 보여줬어요.', 'C2', 'sports', 3, 'marathon runner')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- SPORTS — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_sports_C2_01', 'throw in the towel', '포기하다', '수건을 던지다', '복싱에서 유래한 표현으로, 더 이상 못 버티고 포기한다는 뜻이에요. 비즈니스 협상에서도 자주 써요.', 'After three failed funding rounds, the founders finally threw in the towel.', '세 번의 펀딩 실패 끝에 창업자들은 결국 포기했어요.', 'She refused to throw in the towel despite mounting injuries.', '쌓이는 부상에도 그녀는 포기하기를 거부했어요.', 'Throwing in the towel was not an option for the seasoned negotiator.', '노련한 협상가에게 포기란 선택지가 아니었어요.', 'C2', 'sports', 3, 'boxing towel', 1),
('idm_sports_C2_02', 'a level playing field', '공정한 경쟁의 장', '평평한 경기장', '모두에게 공평한 조건이 보장된 환경을 뜻해요. 경제·정책 토론에서 표준 격식 표현이에요.', 'Regulators are tasked with ensuring a level playing field for new entrants.', '규제 당국은 신규 진입자에게 공정한 경쟁의 장을 보장해야 해요.', 'Trade agreements aim to create a level playing field across markets.', '무역 협정은 시장 전반에 공정한 경쟁의 장을 만드는 것이 목표예요.', 'Without a level playing field, small firms cannot compete effectively.', '공정한 경쟁의 장이 없으면 소규모 기업은 효과적으로 경쟁할 수 없어요.', 'C2', 'sports', 3, 'sports field', 2),
('idm_sports_C2_03', 'on the ropes', '코너에 몰린', '로프에 기댄', '복싱에서 유래한 표현으로, 패배 직전의 곤경에 처한 상태를 뜻해요. 스포츠, 정치, 비즈니스 모두에 잘 어울려요.', 'The defending champion was on the ropes by the end of the eighth round.', '디펜딩 챔피언은 8라운드 끝 무렵 코너에 몰려 있었어요.', 'The opposition party has been on the ropes since the corruption hearings began.', '야당은 부패 청문회가 시작된 이래 코너에 몰려 있어요.', 'After two consecutive quarterly losses, the firm was on the ropes.', '연속 두 분기 손실 후 그 회사는 코너에 몰렸어요.', 'C2', 'sports', 3, 'boxing ring', 3),
('idm_sports_C2_04', 'down to the wire', '막판까지 가는', '결승선 와이어까지', '결과가 마지막 순간까지 결정되지 않을 정도로 박빙이라는 뜻이에요. 경마에서 유래했어요.', 'The election went down to the wire, with results announced after midnight.', '선거는 막판까지 갔고, 자정이 지나서야 결과가 발표됐어요.', 'The contract negotiations are likely to go down to the wire.', '계약 협상은 막판까지 갈 가능성이 높아요.', 'A photo finish — the race went right down to the wire.', '사진 판독 — 그 경주는 정말 막판까지 갔어요.', 'C2', 'sports', 3, 'finish line', 4),
('idm_sports_C2_05', 'play hardball', '강경하게 밀어붙이다', '하드볼을 하다', '야구에서 유래해, 협상이나 경쟁에서 단호하고 양보 없이 임한다는 뜻이에요. 비즈니스와 정치에 표준이에요.', 'The federation is prepared to play hardball over broadcasting rights.', '연맹은 중계권 문제로 강경하게 밀어붙일 준비가 돼 있어요.', 'When star players play hardball in contract talks, clubs often blink first.', '스타 선수들이 계약 협상에서 강경하게 나오면 구단이 먼저 양보하는 경우가 많아요.', 'She is not afraid to play hardball when the stakes are high.', '판이 클 때 그녀는 강경하게 밀어붙이는 걸 두려워하지 않아요.', 'C2', 'sports', 3, 'baseball pitch', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- 05-c2-colloc-idioms-batch4.sql
-- ============================================
-- ============================================================
-- C2-level Collocations and Idioms — Batch 4
-- Topics: emotion, culture, humanities, presentation, greeting
-- 5 collocations + 5 idioms per topic = 50 total entries
-- ============================================================

-- ============================================================
-- EMOTION — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_emotion_C2_01', 'harbor', 'resentment', 'harbor resentment', '원한을 품다', 'have', '오랜 시간 마음속에 부정적 감정을 간직한다는 격식 있는 문어체 표현이에요. 문학이나 심리 분석에서 자주 보여요.', 'She had harbored resentment toward her former mentor for nearly a decade.', '그녀는 거의 10년 동안 옛 멘토에 대한 원한을 품어왔어요.', 'Harboring resentment only corrodes one''s own peace of mind.', '원한을 품는 것은 자신의 평정심을 갉아먹을 뿐이에요.', 'C2', 'emotion', 3, 'pensive woman shadow'),
('col_emotion_C2_02', 'exhibit', 'composure', 'exhibit composure', '침착함을 보이다', 'show', '위기 상황에서도 평정을 드러낸다는 격식 표현이에요. 외교, 위기 관리, 법정 보도에 적절해요.', 'The diplomat exhibited remarkable composure during the heated exchange.', '그 외교관은 격렬한 논쟁 중에도 놀라운 침착함을 보였어요.', 'She exhibited composure even as the verdict was read aloud.', '판결문이 낭독되는 순간에도 그녀는 침착함을 보였어요.', 'C2', 'emotion', 3, 'calm executive'),
('col_emotion_C2_03', 'succumb', 'despair', 'succumb to despair', '절망에 굴복하다', 'feel', '저항하다가 결국 부정적 감정에 무너진다는 문학적 표현이에요. ''succumb to''는 격식 있는 동사구예요.', 'Even in exile, the poet refused to succumb to despair.', '망명 중에도 그 시인은 절망에 굴복하기를 거부했어요.', 'After months of setbacks, he nearly succumbed to despair.', '몇 달간의 좌절 끝에 그는 거의 절망에 굴복할 뻔했어요.', 'C2', 'emotion', 3, 'lonely figure rain'),
('col_emotion_C2_04', 'evoke', 'nostalgia', 'evoke nostalgia', '향수를 불러일으키다', 'make', '기억이나 감정을 자연스럽게 떠오르게 한다는 우아한 표현이에요. 예술 평론과 광고 카피에서 자주 등장해요.', 'The faded photograph evoked a profound nostalgia for his childhood village.', '바랜 사진은 그의 어린 시절 마을에 대한 깊은 향수를 불러일으켰어요.', 'The melody evokes a quiet nostalgia in anyone who hears it.', '그 선율은 듣는 누구에게나 잔잔한 향수를 불러일으켜요.', 'C2', 'emotion', 3, 'old photograph'),
('col_emotion_C2_05', 'betray', 'emotion', 'betray emotion', '감정을 드러내다', 'show', '숨기려 했던 감정이 무심코 드러난다는 문학적 표현이에요. 표정이나 목소리가 ''배신''한다는 뉘앙스예요.', 'Her steady voice did not betray the slightest emotion.', '그녀의 차분한 목소리는 어떤 감정도 드러내지 않았어요.', 'A faint tremor in his hand betrayed his emotion.', '미세하게 떨리는 손이 그의 감정을 드러냈어요.', 'C2', 'emotion', 3, 'subtle expression')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- EMOTION — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_emotion_C2_01', 'wear one''s heart on one''s sleeve', '감정을 솔직하게 드러내다', '심장을 소매에 달고 다니다', '자신의 감정을 숨기지 않고 그대로 드러낸다는 뜻이에요. 문학과 인물 평가에서 자주 써요.', 'Unlike his stoic father, he wears his heart on his sleeve.', '금욕적인 아버지와 달리, 그는 감정을 솔직하게 드러내요.', 'Diplomats rarely wear their hearts on their sleeves.', '외교관들은 감정을 좀처럼 드러내지 않아요.', 'She has always worn her heart on her sleeve, for better or worse.', '좋든 나쁘든, 그녀는 늘 감정을 솔직하게 드러내요.', 'C2', 'emotion', 3, 'heart on sleeve', 1),
('idm_emotion_C2_02', 'bottle up feelings', '감정을 억누르다', '감정을 병에 담아두다', '감정을 표현하지 않고 속에 가둬둔다는 뜻이에요. 심리 상담이나 인간관계 글에서 자주 등장해요.', 'Bottling up feelings rarely leads to lasting peace of mind.', '감정을 억누르는 것은 좀처럼 지속적인 평정심으로 이어지지 않아요.', 'He had bottled up his grief for years before finally seeking help.', '그는 도움을 청하기 전 몇 년간 슬픔을 억눌러왔어요.', 'Do not bottle up your feelings — share them with someone you trust.', '감정을 억누르지 마세요. 믿는 사람과 나누세요.', 'C2', 'emotion', 3, 'bottled emotion', 2),
('idm_emotion_C2_03', 'lose one''s cool', '냉정을 잃다', '쿨함을 잃다', '평소의 침착함이나 자제력을 잃고 화를 낸다는 뜻이에요. 격식과 비격식 모두에서 폭넓게 써요.', 'Even seasoned negotiators occasionally lose their cool under pressure.', '노련한 협상가들도 압박 속에서 가끔 냉정을 잃어요.', 'She lost her cool when the same question was asked for the fourth time.', '같은 질문을 네 번째 받자 그녀는 냉정을 잃었어요.', 'A true leader rarely loses their cool in a crisis.', '진정한 리더는 위기 속에서 좀처럼 냉정을 잃지 않아요.', 'C2', 'emotion', 3, 'frustrated executive', 3),
('idm_emotion_C2_04', 'down in the dumps', '의기소침한', '쓰레기장에 빠진', '뚜렷한 이유 없이 우울하고 풀이 죽은 상태를 가리키는 격식 있는 구어 표현이에요. 인물 묘사에서 자연스러워요.', 'He has been down in the dumps ever since the manuscript was rejected.', '그는 원고가 거절당한 이후로 줄곧 의기소침해 있어요.', 'A long walk often lifts her out of being down in the dumps.', '오래 걷는 것은 종종 그녀를 의기소침함에서 끌어올려줘요.', 'Whenever I am down in the dumps, I revisit my favorite novel.', '의기소침할 때마다 저는 가장 좋아하는 소설을 다시 읽어요.', 'C2', 'emotion', 3, 'gloomy figure window', 4),
('idm_emotion_C2_05', 'head over heels', '푹 빠진', '머리가 발 위에 있는', '주로 사랑에 완전히 빠진 상태를 가리키지만, 어떤 것에 깊이 매료된 상황에도 써요. 문학과 회고록에서 우아하게 활용돼요.', 'They were head over heels from the moment they met at the embassy reception.', '그들은 대사관 리셉션에서 만난 순간부터 푹 빠졌어요.', 'He fell head over heels for the world of Renaissance literature.', '그는 르네상스 문학의 세계에 푹 빠졌어요.', 'She was head over heels in love with the city''s quiet elegance.', '그녀는 그 도시의 조용한 우아함에 푹 빠져 있었어요.', 'C2', 'emotion', 3, 'romantic embrace', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- CULTURE — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_culture_C2_01', 'embrace', 'tradition', 'embrace tradition', '전통을 받아들이다', 'follow', '전통을 적극적이고 긍정적으로 수용한다는 뉘앙스예요. 문화 평론, 정책 담론에서 자주 써요.', 'The contemporary chef embraces tradition while reinventing classic recipes.', '그 현대 셰프는 전통을 받아들이면서도 고전적 레시피를 재해석해요.', 'Many designers embrace tradition as a source of innovation, not constraint.', '많은 디자이너들은 전통을 제약이 아닌 혁신의 원천으로 받아들여요.', 'C2', 'culture', 3, 'traditional craft hands'),
('col_culture_C2_02', 'transcend', 'boundaries', 'transcend boundaries', '경계를 초월하다', 'cross', '단순히 ''넘는다''가 아니라 한계 자체를 초월하여 새로운 차원에 이른다는 격식 표현이에요. 예술 평론의 단골 표현이에요.', 'Her installations transcend the boundaries between sculpture and performance.', '그녀의 설치 작품은 조각과 퍼포먼스의 경계를 초월해요.', 'Truly great cinema transcends linguistic and cultural boundaries.', '진정으로 위대한 영화는 언어와 문화의 경계를 초월해요.', 'C2', 'culture', 3, 'art installation gallery'),
('col_culture_C2_03', 'epitomize', 'elegance', 'epitomize elegance', '우아함의 전형이 되다', 'show', '어떤 자질의 완벽한 본보기가 된다는 격식 동사예요. 패션, 인물 평론, 디자인 평가에 적합해요.', 'Her tailored silhouette epitomizes mid-century elegance.', '그녀의 재단된 실루엣은 20세기 중반 우아함의 전형이에요.', 'The opera house epitomizes the elegance of the Belle Epoque.', '그 오페라 하우스는 벨 에포크 시대 우아함의 전형이에요.', 'C2', 'culture', 3, 'elegant ballroom'),
('col_culture_C2_04', 'challenge', 'convention', 'challenge convention', '관습에 도전하다', 'break', '기존의 통념이나 관습에 의문을 제기하며 맞선다는 격식 표현이에요. 예술과 학술 비평에서 표준이에요.', 'The avant-garde movement sought to challenge every convention of academic painting.', '아방가르드 운동은 학파 회화의 모든 관습에 도전하려 했어요.', 'Her debut novel challenges convention in both form and content.', '그녀의 데뷔작은 형식과 내용 모두에서 관습에 도전해요.', 'C2', 'culture', 3, 'avant-garde art'),
('col_culture_C2_05', 'blend', 'influences', 'blend influences', '영향을 융합하다', 'mix', '서로 다른 문화나 양식의 영향을 조화롭게 결합한다는 표현이에요. 음악, 요리, 디자인 평론에서 자주 보여요.', 'The composer skillfully blends European and East Asian musical influences.', '그 작곡가는 유럽과 동아시아의 음악적 영향을 능숙하게 융합해요.', 'Their cuisine blends Andalusian and North African influences with quiet sophistication.', '그들의 요리는 안달루시아와 북아프리카의 영향을 잔잔한 세련됨으로 융합해요.', 'C2', 'culture', 3, 'fusion cuisine')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- CULTURE — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_culture_C2_01', 'the toast of the town', '장안의 화제', '도시의 건배', '사교계나 예술계에서 큰 찬사를 받는 인물이나 작품을 뜻해요. 문화 비평과 사교 칼럼에서 우아하게 써요.', 'After her debut at the Royal Opera, she became the toast of the town.', '왕립 오페라 데뷔 이후, 그녀는 장안의 화제가 되었어요.', 'His latest exhibition has made him the toast of the contemporary art scene.', '그의 최근 전시는 그를 현대 미술계의 화제로 만들었어요.', 'The young pianist was the toast of the town all season.', '그 젊은 피아니스트는 시즌 내내 장안의 화제였어요.', 'C2', 'culture', 3, 'opera applause', 1),
('idm_culture_C2_02', 'the writing on the wall', '불길한 징조', '벽에 적힌 글', '피할 수 없는 결과나 몰락의 조짐이 명백히 보일 때 써요. 문화 쇠퇴, 시대 변화 담론에서 격식 있게 활용돼요.', 'For traditional print media, the writing has long been on the wall.', '전통 인쇄 매체에는 오래전부터 불길한 징조가 보였어요.', 'Critics saw the writing on the wall for the gallery years before it closed.', '비평가들은 갤러리가 문을 닫기 몇 년 전부터 불길한 징조를 봤어요.', 'The writing was on the wall for that opulent style of theatre.', '그 호화로운 양식의 연극에는 불길한 징조가 보였어요.', 'C2', 'culture', 3, 'old graffiti wall', 2),
('idm_culture_C2_03', 'in vogue', '유행하는', '유행 안에 있는', '특정 양식이나 사상이 현재 유행 중이라는 격식 있는 표현이에요. 패션, 예술, 학문 트렌드 모두에 자연스러워요.', 'Minimalist interiors have been in vogue for nearly a decade.', '미니멀리즘 인테리어가 거의 10년째 유행 중이에요.', 'Such ornate rhetoric is no longer in vogue among serious essayists.', '그런 화려한 수사는 진지한 에세이스트들 사이에서 더 이상 유행하지 않아요.', 'Slow fashion is increasingly in vogue among discerning consumers.', '슬로우 패션이 안목 있는 소비자들 사이에서 점점 유행하고 있어요.', 'C2', 'culture', 3, 'fashion runway', 3),
('idm_culture_C2_04', 'all the rage', '대유행인', '온통 격분 상태인', '폭발적으로 인기 있는 유행을 가리키는 격식 있는 관용구예요. ''in vogue''보다 더 강한 열풍을 암시해요.', 'Japanese minimalism is all the rage in interior design circles.', '일본식 미니멀리즘이 인테리어 디자인계에서 대유행이에요.', 'That particular shade of olive was all the rage last autumn.', '그 특정 올리브색이 작년 가을에 대유행이었어요.', 'Immersive theatre is all the rage among younger audiences.', '몰입형 연극이 젊은 관객들 사이에서 대유행이에요.', 'C2', 'culture', 3, 'trendy interior', 4),
('idm_culture_C2_05', 'a feather in one''s cap', '자랑할 만한 업적', '모자에 꽂는 깃털', '경력이나 명성에 자랑이 되는 명예로운 성취를 뜻해요. 시상식, 회고, 격식 있는 인물 소개에서 우아해요.', 'Winning the prestigious literary prize is a feather in any author''s cap.', '그 권위 있는 문학상 수상은 어떤 작가에게나 자랑할 만한 업적이에요.', 'Curating the retrospective was a real feather in her cap.', '그 회고전을 큐레이팅한 것은 그녀에게 진정한 자랑거리였어요.', 'A Cannes nomination is a feather in any young director''s cap.', '칸 노미네이션은 어떤 신인 감독에게나 자랑할 만한 업적이에요.', 'C2', 'culture', 3, 'award trophy', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- HUMANITIES — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_humanities_C2_01', 'interrogate', 'assumptions', 'interrogate assumptions', '전제를 비판적으로 검토하다', 'question', '단순한 의심이 아니라 학문적으로 철저히 따져본다는 인문학·사회과학 학술 용어예요. ''question''보다 훨씬 무거운 무게감이에요.', 'The seminar urged students to interrogate the assumptions underlying classical economic theory.', '그 세미나는 학생들에게 고전 경제 이론의 전제를 비판적으로 검토하라고 촉구했어요.', 'Good scholarship interrogates its own assumptions before critiquing others''.', '훌륭한 학문은 타인을 비판하기에 앞서 자기 자신의 전제를 비판적으로 검토해요.', 'C2', 'humanities', 3, 'philosophy seminar'),
('col_humanities_C2_02', 'deconstruct', 'narrative', 'deconstruct a narrative', '서사를 해체하다', 'analyze', '데리다 이후 문학 비평의 표준 용어로, 서사의 이면 구조와 모순을 드러내는 작업이에요. 학술 논문에서 표준이에요.', 'Postcolonial scholars deconstruct the dominant narrative of colonial benevolence.', '탈식민주의 학자들은 식민지 자비라는 지배적 서사를 해체해요.', 'The essay deconstructs the narrative of inevitable progress.', '그 에세이는 필연적 진보라는 서사를 해체해요.', 'C2', 'humanities', 3, 'library deconstruction'),
('col_humanities_C2_03', 'contextualize', 'discourse', 'contextualize discourse', '담론을 맥락화하다', 'place', '담론을 역사적·사회적 맥락 속에서 이해할 수 있도록 자리매김한다는 학술 표현이에요. 인문학 논문의 핵심 동작이에요.', 'The chapter contextualizes the discourse on liberty within Enlightenment thought.', '그 장은 자유에 관한 담론을 계몽주의 사상의 맥락 속에 자리매김해요.', 'We must contextualize the discourse before pronouncing judgment.', '판단을 내리기 전에 담론을 맥락화해야 해요.', 'C2', 'humanities', 3, 'open archive book'),
('col_humanities_C2_04', 'trace', 'lineage', 'trace a lineage', '계보를 추적하다', 'find', '사상이나 양식의 기원과 흐름을 학술적으로 거슬러 올라간다는 표현이에요. 사상사·미술사·문학사에 필수적이에요.', 'The monograph traces the intellectual lineage from Kant to contemporary critical theory.', '그 논문은 칸트부터 현대 비판 이론까지의 지적 계보를 추적해요.', 'She traced the lineage of feminist thought across three continents.', '그녀는 세 대륙에 걸친 페미니즘 사상의 계보를 추적했어요.', 'C2', 'humanities', 3, 'genealogy chart'),
('col_humanities_C2_05', 'elucidate', 'meaning', 'elucidate meaning', '의미를 명확히 밝히다', 'explain', '불분명한 의미를 학술적이고 체계적으로 해명한다는 격식 동사예요. ''explain''보다 훨씬 무거운 학문적 어조예요.', 'The footnotes elucidate the meaning of arcane theological terms.', '각주들은 난해한 신학 용어의 의미를 명확히 밝혀요.', 'A careful reading of the original Greek elucidates the meaning lost in translation.', '원전 그리스어를 세심히 읽으면 번역에서 사라진 의미가 명확히 드러나요.', 'C2', 'humanities', 3, 'ancient text annotation')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- HUMANITIES — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_humanities_C2_01', 'the proof is in the pudding', '결과로 증명된다', '증거는 푸딩 안에 있다', '이론이나 주장이 옳은지는 실제 결과를 통해서만 알 수 있다는 학술적 격언이에요. 토론과 논평에서 우아하게 써요.', 'The theory is elegant, but the proof is in the pudding when applied to real data.', '그 이론은 우아하지만, 실제 데이터에 적용했을 때 비로소 결과로 증명돼요.', 'For any pedagogical method, the proof is ultimately in the pudding.', '어떤 교수법이든, 결국 결과로 증명돼요.', 'They claim the model is universal — but the proof is in the pudding.', '그들은 그 모델이 보편적이라 주장하지만, 결과로 증명돼야 해요.', 'C2', 'humanities', 3, 'scholarly proof', 1),
('idm_humanities_C2_02', 'splitting hairs', '지나치게 따지다', '머리카락을 가르다', '사소한 차이를 놓고 끝없이 따진다는 뜻이에요. 학술 토론에서 상대의 미세한 구분을 지적할 때 격식 있게 써요.', 'At this point we are merely splitting hairs over translation choices.', '이쯤 되면 우리는 번역 선택을 두고 지나치게 따지고 있을 뿐이에요.', 'Critics accused him of splitting hairs over a single comma.', '비평가들은 그가 쉼표 하나를 두고 지나치게 따진다고 비난했어요.', 'Let us not split hairs and instead address the central argument.', '지나치게 따지지 말고 핵심 논증을 다뤄봅시다.', 'C2', 'humanities', 3, 'magnifying glass text', 2),
('idm_humanities_C2_03', 'to coin a phrase', '말하자면', '문구를 주조하자면', '새로운 표현이나 이미 진부한 표현을 쓸 때 미리 양해를 구하는 격식 있는 삽입구예요. 학술 강연과 논문에서 우아한 효과를 줘요.', 'The corpus is, to coin a phrase, an archive of silences.', '그 코퍼스는 말하자면 침묵의 기록보관소예요.', 'Her style is, to coin a phrase, calculated spontaneity.', '그녀의 문체는 말하자면 계산된 즉흥성이에요.', 'The era was, to coin a phrase, an age of anxious modernity.', '그 시대는 말하자면 불안한 근대의 시대였어요.', 'C2', 'humanities', 3, 'fountain pen writing', 3),
('idm_humanities_C2_04', 'in a nutshell', '요컨대', '호두 껍데기 속에 넣어', '복잡한 논의를 핵심만 간결히 요약할 때 쓰는 격식 있는 표현이에요. 학술 강연의 결론부에 자연스러워요.', 'In a nutshell, the author argues that history is irreducibly plural.', '요컨대, 저자는 역사가 본질적으로 복수적이라고 주장해요.', 'In a nutshell, modernism dethroned the omniscient narrator.', '요컨대, 모더니즘은 전지적 서술자의 권위를 무너뜨렸어요.', 'The thesis, in a nutshell, redefines the very concept of authorship.', '그 논문은 요컨대, 저자성이라는 개념 자체를 재정의해요.', 'C2', 'humanities', 3, 'walnut shell', 4),
('idm_humanities_C2_05', 'the long and short of it', '결론은', '그것의 길고 짧음', '긴 논의 끝에 결론을 간결히 정리할 때 쓰는 격식 있는 표현이에요. 학술 발표의 마무리에 우아해요.', 'The long and short of it is that the manuscript predates the conventional dating by a century.', '결론은, 그 필사본이 통상 추정 연대보다 100년 앞선다는 거예요.', 'The long and short of it: structuralism cannot fully account for affect.', '결론은, 구조주의가 정동을 온전히 설명할 수 없다는 거예요.', 'The long and short of it is that the archive must be reread.', '결론은, 그 기록보관소를 다시 읽어야 한다는 거예요.', 'C2', 'humanities', 3, 'old manuscript', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- PRESENTATION — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_presentation_C2_01', 'captivate', 'audience', 'captivate an audience', '청중을 사로잡다', 'interest', '청중을 완전히 매혹시켜 시선을 떼지 못하게 한다는 강한 표현이에요. 발표 평론과 강연 후기에 표준이에요.', 'Her opening anecdote captivated the audience from the very first sentence.', '그녀의 도입부 일화는 첫 문장부터 청중을 사로잡았어요.', 'A skilled keynote speaker knows precisely how to captivate an audience.', '능숙한 기조 연설자는 어떻게 청중을 사로잡을지 정확히 알아요.', 'C2', 'presentation', 3, 'keynote speaker stage'),
('col_presentation_C2_02', 'marshal', 'evidence', 'marshal evidence', '증거를 정연하게 제시하다', 'show', '증거를 체계적이고 설득력 있게 동원·배열한다는 격식 표현이에요. 법정, 학술, 임원 보고에서 표준이에요.', 'The consultant marshaled compelling evidence to support the restructuring proposal.', '그 컨설턴트는 구조조정 제안을 뒷받침할 설득력 있는 증거를 정연하게 제시했어요.', 'You must marshal evidence carefully before the board challenges the assumptions.', '이사회가 가정에 의문을 제기하기 전에 증거를 신중히 정렬해야 해요.', 'C2', 'presentation', 3, 'boardroom evidence'),
('col_presentation_C2_03', 'articulate', 'vision', 'articulate a vision', '비전을 분명히 표현하다', 'tell', '추상적인 비전을 청중이 이해하고 공감할 수 있도록 명료하게 풀어낸다는 격식 표현이에요. CEO 연설의 표준 동사예요.', 'The new CEO articulated a vision of sustainable, decade-long growth.', '신임 CEO는 지속 가능하고 10년에 걸친 성장 비전을 분명히 표현했어요.', 'Great leaders articulate a vision their teams can rally behind.', '훌륭한 리더는 팀원들이 결집할 수 있는 비전을 분명히 표현해요.', 'C2', 'presentation', 3, 'CEO town hall'),
('col_presentation_C2_04', 'underscore', 'points', 'underscore key points', '핵심을 강조하다', 'show', '발표 중 핵심 메시지를 의도적으로 강조한다는 격식 동사예요. ''emphasize''보다 더 차분하고 세련된 어조예요.', 'Throughout the address, she underscored three key points with quiet authority.', '연설 내내 그녀는 차분한 권위로 세 가지 핵심을 강조했어요.', 'The closing slide underscored the key points of the entire presentation.', '마지막 슬라이드는 발표 전체의 핵심을 강조했어요.', 'C2', 'presentation', 3, 'slide deck close'),
('col_presentation_C2_05', 'field', 'questions', 'field questions', '질문을 받아 응대하다', 'answer', '질문을 능숙하게 받아 적절히 응대한다는 격식 표현이에요. 기자회견, Q&A 세션 보도에서 표준이에요.', 'After the keynote, she fielded questions from international journalists for over an hour.', '기조연설 이후, 그녀는 한 시간 넘게 국제 기자들의 질문을 받아 응대했어요.', 'The minister fielded difficult questions with characteristic poise.', '그 장관은 특유의 침착함으로 어려운 질문들을 받아 응대했어요.', 'C2', 'presentation', 3, 'press conference qa')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- PRESENTATION — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_presentation_C2_01', 'get the ball rolling', '시작을 알리다', '공을 굴리기 시작하다', '회의나 발표를 처음 시작해 흐름을 만든다는 뜻이에요. 격식과 비격식 모두에서 폭넓게 활용돼요.', 'Let me get the ball rolling with a brief overview of our methodology.', '저희 방법론에 대한 간략한 개요로 시작을 알리겠습니다.', 'She got the ball rolling by acknowledging the elephant in the room.', '그녀는 모두가 알지만 말하지 않는 문제를 짚으며 시작을 알렸어요.', 'To get the ball rolling, allow me to introduce our distinguished panel.', '시작을 알리며, 저희 권위 있는 패널을 소개해 드리겠습니다.', 'C2', 'presentation', 3, 'conference opening', 1),
('idm_presentation_C2_02', 'drive home a point', '요점을 확실히 전달하다', '요점을 집까지 몰고 가다', '핵심 메시지를 청중의 마음에 깊이 각인시킨다는 뜻이에요. 발표·연설 평론에서 자주 써요.', 'She drove home the point with three carefully chosen case studies.', '그녀는 세심하게 고른 세 가지 사례 연구로 요점을 확실히 전달했어요.', 'The speaker drove home the point that complacency is the real enemy.', '그 연설자는 자만이 진짜 적이라는 요점을 확실히 전달했어요.', 'Repetition, when used judiciously, helps drive home a point.', '반복은 신중하게 쓰일 때 요점을 확실히 전달하는 데 도움이 돼요.', 'C2', 'presentation', 3, 'speaker emphasis', 2),
('idm_presentation_C2_03', 'cut to the chase', '본론으로 들어가다', '추격 장면으로 자르다', '서론을 줄이고 곧장 핵심으로 들어간다는 뜻이에요. 임원 회의나 시간 제약이 있는 발표에서 정중하게 활용돼요.', 'Given our time constraints, allow me to cut to the chase.', '시간 제약을 감안하여, 곧장 본론으로 들어가겠습니다.', 'The chairman, ever pragmatic, asked her to cut to the chase.', '늘 실용적인 의장은 그녀에게 본론으로 들어가달라고 요청했어요.', 'Let us cut to the chase: the merger is the only viable path forward.', '본론으로 들어가죠. 합병이 유일한 실행 가능한 길이에요.', 'C2', 'presentation', 3, 'business meeting clock', 3),
('idm_presentation_C2_04', 'thinking on one''s feet', '즉석에서 대응하기', '발 위에서 생각하기', '준비 없이도 빠르게 판단하고 답한다는 뜻이에요. Q&A 세션, 외교 협상 묘사에서 우아하게 써요.', 'Excellent diplomats are masters at thinking on their feet.', '뛰어난 외교관들은 즉석 대응의 달인이에요.', 'Her ability to think on her feet won over the skeptical analysts.', '즉석에서 대응하는 그녀의 능력은 회의적인 애널리스트들을 설득했어요.', 'Public speaking trains you to think on your feet under pressure.', '대중 연설은 압박 속에서도 즉석에서 대응하도록 훈련시켜요.', 'C2', 'presentation', 3, 'quick response speaker', 4),
('idm_presentation_C2_05', 'lay one''s cards on the table', '솔직히 다 털어놓다', '카드를 테이블에 놓다', '의도나 입장을 숨김없이 공개한다는 격식 있는 표현이에요. 협상이나 전략 발표에서 솔직함을 강조할 때 적절해요.', 'Allow me to lay my cards on the table: our margins simply cannot sustain this trajectory.', '솔직히 다 털어놓겠습니다. 저희 마진은 이런 흐름을 도저히 지탱할 수 없어요.', 'She laid her cards on the table during the final round of negotiations.', '그녀는 협상 최종 라운드에서 모든 것을 솔직히 털어놨어요.', 'Investors appreciate it when founders lay their cards on the table.', '투자자들은 창업자가 솔직히 다 털어놓을 때 그것을 높이 평가해요.', 'C2', 'presentation', 3, 'cards on table', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- GREETING — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_greeting_C2_01', 'extend', 'pleasantries', 'extend pleasantries', '의례적 인사를 건네다', 'say', '격식 있는 자리에서 정중한 인사말을 정성껏 건넨다는 뜻이에요. 외교, 비즈니스 미팅 보도의 표준이에요.', 'The ambassador extended pleasantries before turning to the substantive agenda.', '대사는 본격적인 안건으로 넘어가기 전에 의례적 인사를 건넸어요.', 'They extended pleasantries over tea in the embassy garden.', '그들은 대사관 정원에서 차를 마시며 의례적 인사를 건넸어요.', 'C2', 'greeting', 3, 'diplomatic handshake'),
('col_greeting_C2_02', 'exchange', 'formalities', 'exchange formalities', '의례를 주고받다', 'do', '서로 정중한 격식의 말을 주고받는 절차적 행위를 가리켜요. 의전적 만남 묘사에서 표준 표현이에요.', 'The two delegations exchanged formalities before the negotiations commenced.', '두 대표단은 협상이 시작되기 전 의례를 주고받았어요.', 'After exchanging formalities, they settled into a more candid discussion.', '의례를 주고받은 후, 그들은 더 솔직한 논의로 들어갔어요.', 'C2', 'greeting', 3, 'formal meeting bow'),
('col_greeting_C2_03', 'convey', 'regards', 'convey regards', '안부를 전하다', 'say', '직접 만나지 못한 사람에게 정중히 안부를 전달한다는 격식 표현이에요. 편지, 외교 전문, 공식 인사말에 적합해요.', 'Please convey my warmest regards to your esteemed family.', '존경하는 가족분들께 가장 따뜻한 안부를 전해 주세요.', 'She asked me to convey her regards to the entire faculty.', '그녀는 저에게 교수진 전체에게 안부를 전해달라고 부탁했어요.', 'C2', 'greeting', 3, 'handwritten letter'),
('col_greeting_C2_04', 'make', 'acquaintance', 'make one''s acquaintance', '인사를 나누다', 'meet', '처음 만나 인사하게 되어 영광이라는 매우 격식 있는 표현이에요. ''Pleased to make your acquaintance''는 표준 격식 인사예요.', 'I am delighted to make your acquaintance at last, Professor.', '교수님, 마침내 인사를 나누게 되어 기쁩니다.', 'It was a privilege to make her acquaintance at the embassy reception.', '대사관 리셉션에서 그녀와 인사를 나눈 것은 영광이었어요.', 'C2', 'greeting', 3, 'formal introduction'),
('col_greeting_C2_05', 'tender', 'greetings', 'tender greetings', '인사를 정중히 전하다', 'send', '정중하고 의례적으로 인사를 ''올린다''는 매우 격식 있는 동사예요. 공식 서신과 의전 연설에서 보여요.', 'On behalf of the council, I tender greetings to our distinguished guests.', '의회를 대표하여, 귀한 손님들께 인사를 정중히 올립니다.', 'The chairperson tendered greetings to the assembly before opening the session.', '의장은 회의를 개시하기 전 의회에 인사를 정중히 전했어요.', 'C2', 'greeting', 3, 'formal podium')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- GREETING — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_greeting_C2_01', 'long time no see', '오랜만이에요', '오랜 시간 보지 못했다', '오랜만에 만난 사람에게 건네는 친근한 인사예요. 격식 있는 자리에서도 자연스럽게 활용돼요.', 'Long time no see, Professor — how have you been keeping?', '교수님, 오랜만이에요. 그동안 어떻게 지내셨어요?', 'Long time no see! Your last paper was nothing short of brilliant.', '오랜만이에요. 지난번 논문은 정말 훌륭했어요.', 'Long time no see — shall we catch up over coffee?', '오랜만이에요. 커피 한 잔하며 근황을 나눌까요?', 'C2', 'greeting', 3, 'reunion handshake', 1),
('idm_greeting_C2_02', 'speak of the devil', '호랑이도 제 말 하면 온다', '악마를 말하다', '마침 이야기하던 사람이 등장했을 때 쓰는 친근한 격식 표현이에요. 비즈니스 점심이나 사교 모임에서 자연스러워요.', 'Speak of the devil — here she is, just as we were singing her praises.', '호랑이도 제 말 하면 온다더니, 마침 그녀 칭찬을 하고 있었는데 왔네요.', 'We were just discussing your latest article — speak of the devil!', '마침 당신의 최근 기사를 논의하고 있었는데, 호랑이도 제 말 하면 오네요.', 'Speak of the devil, here comes our keynote speaker.', '호랑이도 제 말 하면 온다고, 기조연설자가 오시네요.', 'C2', 'greeting', 3, 'surprise arrival', 2),
('idm_greeting_C2_03', 'the elephant in the room', '모두 알지만 말하지 않는 문제', '방 안의 코끼리', '모두가 인식하지만 일부러 언급을 피하는 민감한 사안을 가리켜요. 격식 있는 회의를 열며 솔직히 거론할 때 우아해요.', 'Before we begin, let us address the elephant in the room.', '시작하기에 앞서, 모두 알지만 말하지 않는 문제부터 다루어 봅시다.', 'No one was willing to acknowledge the elephant in the room.', '아무도 그 민감한 문제를 인정하려 하지 않았어요.', 'The chairperson, with characteristic candor, named the elephant in the room.', '의장은 특유의 솔직함으로 그 민감한 문제를 지적했어요.', 'C2', 'greeting', 3, 'meeting room elephant', 3),
('idm_greeting_C2_04', 'make small talk', '간단한 잡담을 나누다', '작은 이야기를 하다', '본 주제로 들어가기 전 가벼운 대화로 분위기를 푼다는 표현이에요. 외교, 사교, 비즈니스 만남에 필수적이에요.', 'They made small talk about the weather before turning to the contract.', '계약 이야기로 넘어가기 전, 그들은 날씨에 대해 잡담을 나눴어요.', 'Making small talk is itself a refined diplomatic skill.', '잡담을 나누는 것 자체가 세련된 외교 기술이에요.', 'He is surprisingly skilled at making small talk in three languages.', '그는 놀랍게도 세 가지 언어로 잡담을 나누는 데 능숙해요.', 'C2', 'greeting', 3, 'cocktail reception', 4),
('idm_greeting_C2_05', 'break the ice with grace', '우아하게 어색함을 풀다', '얼음을 우아하게 깨다', '처음 만난 자리에서 세련되게 어색함을 풀어 친밀한 분위기를 만든다는 뜻이에요. 외교와 사교 칼럼에서 우아해요.', 'A well-chosen anecdote can break the ice with grace at any reception.', '잘 고른 일화 하나는 어떤 리셉션에서도 우아하게 어색함을 풀 수 있어요.', 'She broke the ice with grace by recalling their shared acquaintance.', '그녀는 공통의 지인을 언급하며 우아하게 어색함을 풀었어요.', 'The host broke the ice with grace, setting a warm tone for the evening.', '주최자는 우아하게 어색함을 풀며 저녁의 따뜻한 분위기를 만들었어요.', 'C2', 'greeting', 3, 'elegant reception', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- 06-c2-colloc-idioms-batch5.sql
-- ============================================
-- ============================================================
-- C2-level Collocations and Idioms — Batch 5
-- Topics: academic, discussion, negotiation
-- 5 collocations + 5 idioms per topic = 30 total entries
-- ============================================================

-- ============================================================
-- ACADEMIC — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_academic_C2_01', 'advance', 'thesis', 'advance a thesis', '논지를 제시하다', 'say', '논문이나 학술 토론에서 자신의 주장을 공식적으로 내세울 때 써요. ''say''는 단순 발화라 학술 맥락에 부족해요.', 'In her keynote, she advanced a provocative thesis on post-colonial historiography.', '기조 연설에서 그녀는 탈식민 역사 서술에 관한 도발적인 논지를 제시했어요.', 'The author advances the thesis that institutional inertia underpins systemic failure.', '저자는 제도적 관성이 체계적 실패의 근간이라는 논지를 제시해요.', 'C2', 'academic', 3, 'lecture podium'),
('col_academic_C2_02', 'substantiate', 'claim', 'substantiate a claim', '주장을 입증하다', 'prove', '근거와 자료로 주장을 뒷받침한다는 학술적 표현이에요. ''prove''는 결론적인 증명, ''substantiate''는 근거 제시에 가까워요.', 'The reviewers asked the authors to substantiate their claims with longitudinal data.', '심사위원들은 저자들에게 종단 자료로 주장을 입증하라고 요청했어요.', 'Without primary sources, it is difficult to substantiate such a sweeping claim.', '1차 사료 없이는 그렇게 광범위한 주장을 입증하기 어려워요.', 'C2', 'academic', 3, 'research data'),
('col_academic_C2_03', 'rebut', 'argument', 'rebut an argument', '논거를 반박하다', 'deny', '상대의 논거를 근거를 들어 정식으로 반박할 때 써요. ''deny''는 단순 부정이라 학술 토론에 약해요.', 'The discussant rebutted the central argument with a series of counterexamples.', '토론자는 일련의 반례를 들어 핵심 논거를 반박했어요.', 'Her latest paper rebuts the prevailing argument on monetary neutrality.', '그녀의 최신 논문은 화폐 중립성에 관한 지배적인 논거를 반박해요.', 'C2', 'academic', 3, 'academic debate'),
('col_academic_C2_04', 'synthesize', 'findings', 'synthesize findings', '연구 결과를 종합하다', 'combine', '여러 연구의 결과를 비판적으로 통합한다는 학술 전문 용어예요. ''combine''은 단순 결합이라 의미가 약해요.', 'The meta-analysis synthesizes findings from forty-three randomized trials.', '메타분석은 43건의 무작위 시험 결과를 종합해요.', 'In her dissertation she synthesizes findings across three disciplines.', '박사 논문에서 그녀는 세 학문 분야의 연구 결과를 종합해요.', 'C2', 'academic', 3, 'research papers'),
('col_academic_C2_05', 'operationalize', 'concept', 'operationalize a concept', '개념을 조작화하다', 'define', '추상적 개념을 측정 가능하게 정의하는 사회과학·심리학 전문 표현이에요. ''define''보다 한 단계 정교한 학술어예요.', 'The study operationalizes the concept of resilience through three composite indices.', '이 연구는 회복탄력성 개념을 세 가지 종합 지수로 조작화해요.', 'Operationalizing such a nebulous concept poses methodological challenges.', '그런 모호한 개념을 조작화하는 일은 방법론적 난제를 낳아요.', 'C2', 'academic', 3, 'statistical analysis')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ACADEMIC — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_academic_C2_01', 'ivory tower', '상아탑', '상아 탑', '현실과 동떨어진 학계나 지식인의 세계를 비판적으로 가리키는 표현이에요. 격식 있는 평론과 사설에서 자주 써요.', 'Critics accuse the panel of issuing recommendations from an ivory tower.', '비평가들은 그 위원회가 상아탑에서 권고를 내린다고 비난해요.', 'She left her ivory tower to consult for grassroots organizations.', '그녀는 상아탑을 떠나 풀뿌리 단체의 자문을 맡았어요.', 'Such theories rarely survive contact with the world outside the ivory tower.', '그런 이론은 상아탑 밖 세상과 부딪히면 좀처럼 살아남지 못해요.', 'C2', 'academic', 3, 'university tower', 1),
('idm_academic_C2_02', 'armchair scholar', '탁상공론자', '안락의자 학자', '실제 경험 없이 책으로만 이론을 펼치는 사람을 비판적으로 가리켜요. 학계 비평이나 정책 토론에서 자주 써요.', 'He dismissed the report as the work of an armchair scholar with no field experience.', '그는 그 보고서를 현장 경험 없는 탁상공론자의 작업이라며 일축했어요.', 'Armchair scholars often underestimate the complexity of implementation.', '탁상공론자들은 흔히 실행의 복잡성을 과소평가해요.', 'NULL', 'NULL', 'C2', 'academic', 3, 'reading armchair', 2),
('idm_academic_C2_03', 'a labour of love', '애정으로 한 일', '사랑의 노동', '금전적 보상 없이 순전히 애정과 헌신으로 오랜 시간 매달린 작업을 가리켜요. 학술 출판, 예술, 번역 등에서 격식 있게 써요.', 'Her decade-long translation of the medieval text was truly a labour of love.', '그 중세 문헌에 대한 그녀의 10년에 걸친 번역은 진정 애정으로 한 일이었어요.', 'The annotated edition is a labour of love by three retired professors.', '그 주석본은 은퇴한 세 교수의 애정 어린 노작이에요.', 'Compiling this archive has been a labour of love for the entire research team.', '이 아카이브 편찬은 연구팀 전체에게 애정으로 한 일이었어요.', 'C2', 'academic', 3, 'old manuscripts', 3),
('idm_academic_C2_04', 'off the cuff', '즉흥적으로', '소맷부리에서 떼서', '준비 없이 즉석에서 말하거나 답하는 것을 가리켜요. 학회 질의응답, 인터뷰, 회의에서 격식 있게 써요.', 'When pressed for a figure, the economist offered an estimate off the cuff.', '수치를 묻자 경제학자는 즉흥적으로 추정치를 제시했어요.', 'Her off-the-cuff remarks during the Q&A drew considerable attention.', '질의응답 중 그녀의 즉흥 발언은 상당한 주목을 받았어요.', 'I would rather not comment off the cuff on such a sensitive matter.', '그렇게 민감한 사안을 즉흥적으로 논평하고 싶지는 않아요.', 'C2', 'academic', 3, 'microphone speaker', 4),
('idm_academic_C2_05', 'splitting hairs', '사소한 것에 집착하다', '머리카락을 쪼개다', '본질과 무관한 미세한 구분에 매달리는 행위를 비판적으로 가리켜요. 학술 토론, 법정, 정책 논쟁에서 격식 있게 써요.', 'With respect, you are splitting hairs over terminology rather than addressing the substance.', '실례지만, 본질을 다루는 대신 용어를 두고 사소한 것에 집착하고 있어요.', 'The reviewers were splitting hairs over a minor methodological footnote.', '심사위원들은 사소한 방법론 각주를 두고 트집을 잡고 있었어요.', 'Let us not split hairs — the central conclusion remains intact.', '사소한 데 집착하지 맙시다. 핵심 결론은 그대로예요.', 'C2', 'academic', 3, 'magnifying glass', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- DISCUSSION — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_discussion_C2_01', 'reach', 'consensus', 'reach consensus', '합의에 이르다', 'make', '논의 끝에 참석자 다수가 동의에 도달했다는 격식 표현이에요. ''make''는 어색하고, ''reach''가 표준 학술·외교 용어예요.', 'After three days of deliberation, the committee finally reached consensus on the wording.', '사흘간의 숙의 끝에 위원회는 마침내 문안에 합의를 이루었어요.', 'Reaching consensus on such a contentious issue will require sustained dialogue.', '그렇게 첨예한 사안에서 합의에 이르려면 지속적인 대화가 필요해요.', 'C2', 'discussion', 3, 'meeting handshake'),
('col_discussion_C2_02', 'raise', 'objections', 'raise objections', '이의를 제기하다', 'say', '회의나 토론에서 공식적으로 반대 의견을 제기할 때 쓰는 격식 표현이에요. ''say''는 격이 떨어져요.', 'Several board members raised objections to the proposed restructuring.', '여러 이사회 구성원이 제안된 구조조정에 이의를 제기했어요.', 'If you wish to raise objections, please do so before the vote is called.', '이의를 제기하시려면 표결 전에 해 주세요.', 'C2', 'discussion', 3, 'board meeting'),
('col_discussion_C2_03', 'voice', 'concerns', 'voice concerns', '우려를 표명하다', 'tell', '걱정이나 우려를 공개적으로 표현한다는 외교적·격식 표현이에요. ''tell''은 격이 부족해요.', 'Stakeholders voiced grave concerns over the environmental impact assessment.', '이해관계자들은 환경 영향 평가에 대해 심각한 우려를 표명했어요.', 'She voiced her concerns directly to the steering committee.', '그녀는 운영위원회에 직접 우려를 표명했어요.', 'C2', 'discussion', 3, 'concerned speaker'),
('col_discussion_C2_04', 'challenge', 'assumptions', 'challenge assumptions', '전제에 의문을 제기하다', 'doubt', '논의의 바탕이 되는 전제를 근본부터 재검토하자는 비판적 사고 표현이에요. ''doubt''보다 학술적이고 적극적이에요.', 'The keynote speaker urged delegates to challenge their assumptions about productivity.', '기조 연사는 대표단에게 생산성에 대한 전제를 재검토하라고 촉구했어요.', 'A good moderator challenges assumptions rather than reinforcing them.', '좋은 사회자는 전제를 강화하기보다 의문을 제기해요.', 'C2', 'discussion', 3, 'debate forum'),
('col_discussion_C2_05', 'concede', 'point', 'concede a point', '논점을 인정하다', 'agree', '토론에서 상대의 주장이 일리 있다고 일부 인정하는 격식 표현이에요. ''agree''보다 부분적이고 외교적인 뉘앙스예요.', 'The minister graciously conceded the point on fiscal accountability.', '장관은 재정 책임 문제에 관한 논점을 정중히 인정했어요.', 'Conceding a point does not weaken your overall position.', '한 논점을 인정한다고 해서 전체 입장이 약해지지는 않아요.', 'C2', 'discussion', 3, 'panel discussion')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- DISCUSSION — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_discussion_C2_01', 'agree to disagree', '이견을 인정하다', '동의하지 않기로 동의하다', '서로 합의할 수 없음을 인정하고 논쟁을 정중히 끝낼 때 써요. 격식 있는 회의와 외교 대화에 적합해요.', 'After hours of debate, the panelists chose to agree to disagree on the matter.', '몇 시간의 토론 끝에 패널들은 그 사안에 대해 이견을 인정하기로 했어요.', 'Sometimes the most diplomatic outcome is simply to agree to disagree.', '때로는 가장 외교적인 결론이 그저 이견을 인정하는 것이에요.', 'We agreed to disagree on policy specifics while affirming our shared values.', '우리는 공유 가치를 확인하면서도 정책 세부에 대한 이견은 인정했어요.', 'C2', 'discussion', 3, 'handshake disagreement', 1),
('idm_discussion_C2_02', 'play devil''s advocate', '일부러 반론을 펴다', '악마의 변호인 역할을 하다', '논의를 풍부하게 하기 위해 일부러 반대 입장을 취해보는 행위를 가리켜요. 학술 세미나와 전략 회의에서 격식 있게 써요.', 'Let me play devil''s advocate for a moment and question the central premise.', '잠시 반론을 펴 보자면, 핵심 전제에 의문을 제기하고 싶어요.', 'A good chair occasionally plays devil''s advocate to test the group''s reasoning.', '좋은 의장은 가끔 일부러 반론을 펴서 집단의 추론을 검증해요.', 'She often plays devil''s advocate in board discussions to stress-test proposals.', '그녀는 이사회 토론에서 자주 일부러 반론을 펴 제안을 검증해요.', 'C2', 'discussion', 3, 'thinking debate', 2),
('idm_discussion_C2_03', 'beat a dead horse', '같은 얘기를 반복하다', '죽은 말을 때리다', '이미 결론이 난 사안을 무익하게 계속 거론하는 것을 비판적으로 가리켜요. 회의 진행이 정체될 때 격식 있게 써요.', 'With respect, I think we are beating a dead horse — the decision has been made.', '실례지만, 같은 얘기를 반복하고 있는 것 같아요. 결정은 이미 났어요.', 'There is no point beating a dead horse; let us move to the next agenda item.', '같은 얘기를 반복할 필요는 없어요. 다음 안건으로 넘어갑시다.', 'The chair gently noted that the discussion was beating a dead horse.', '의장은 그 논의가 같은 얘기의 반복이라고 점잖게 지적했어요.', 'C2', 'discussion', 3, 'tired meeting', 3),
('idm_discussion_C2_04', 'common ground', '공통 기반', '공통의 땅', '서로 다른 입장 사이에서 합의 가능한 지점을 가리켜요. 외교, 협상, 다자 논의의 표준 격식 표현이에요.', 'Despite ideological differences, the delegations found significant common ground on climate policy.', '이념적 차이에도 불구하고 대표단들은 기후 정책에서 상당한 공통 기반을 찾았어요.', 'Finding common ground is the first task of any productive dialogue.', '공통 기반을 찾는 것이 모든 생산적 대화의 첫 과제예요.', 'The mediator skillfully identified common ground between the warring parties.', '중재자는 갈등 당사자들 사이의 공통 기반을 능숙하게 찾아냈어요.', 'C2', 'discussion', 3, 'overlapping circles', 4),
('idm_discussion_C2_05', 'go round in circles', '제자리걸음하다', '원을 따라 돌다', '논의가 진전 없이 같은 지점을 맴도는 상황을 가리켜요. 회의 평가나 진행 비평에 격식 있게 써요.', 'We have been going round in circles for an hour — perhaps we need a tie-breaking vote.', '한 시간째 제자리걸음이에요. 결선 투표가 필요할 것 같아요.', 'Without clear terms of reference, the committee kept going round in circles.', '명확한 위임 범위 없이 위원회는 계속 제자리걸음을 했어요.', 'The negotiations went round in circles until a new mediator was appointed.', '새 중재자가 임명되기 전까지 협상은 제자리걸음을 거듭했어요.', 'C2', 'discussion', 3, 'circular arrows', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEGOTIATION — Collocations (C2)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_negotiation_C2_01', 'broker', 'deal', 'broker a deal', '거래를 중개하다', 'make', '제3자가 양측 사이에서 협상을 이끌어 거래를 성사시킨다는 외교·금융 격식 표현이에요. ''make''는 단순 체결이라 의미가 약해요.', 'The envoy spent six months brokering a deal between the two governments.', '특사는 두 정부 사이의 거래를 중개하는 데 6개월을 썼어요.', 'Investment bankers were brought in to broker the deal.', '거래를 중개하기 위해 투자 은행가들이 투입되었어요.', 'C2', 'negotiation', 3, 'diplomatic meeting'),
('col_negotiation_C2_02', 'drive', 'bargain', 'drive a bargain', '흥정을 강하게 이끌다', 'make', '협상에서 자신에게 유리하도록 강하게 밀어붙인다는 비즈니스 격식 표현이에요. ''drive a hard bargain''으로도 자주 써요.', 'Their lead negotiator drove a bargain that exceeded the board''s expectations.', '그들의 수석 협상가는 이사회의 기대를 넘는 흥정을 이끌었어요.', 'She drives a bargain with the discipline of a seasoned trader.', '그녀는 노련한 트레이더의 절도로 흥정을 이끌어요.', 'C2', 'negotiation', 3, 'business negotiation'),
('col_negotiation_C2_03', 'yield', 'concessions', 'yield concessions', '양보를 끌어내다', 'get', '협상 끝에 상대로부터 양보를 받아낸다는 외교·노사 협상 격식 표현이에요. ''get''은 격이 떨어져요.', 'Sustained pressure finally yielded concessions on labor standards.', '지속적인 압박이 마침내 노동 기준에 관한 양보를 끌어냈어요.', 'The strategy yielded significant concessions from the opposing delegation.', '그 전략은 상대 대표단으로부터 상당한 양보를 끌어냈어요.', 'C2', 'negotiation', 3, 'negotiation table'),
('col_negotiation_C2_04', 'leverage', 'influence', 'leverage influence', '영향력을 활용하다', 'use', '자신의 영향력이나 자원을 전략적으로 활용한다는 비즈니스·정치 격식 표현이에요. ''use''보다 훨씬 전략적인 뉘앙스예요.', 'She leveraged her influence with regulators to secure a favorable ruling.', '그녀는 규제 당국에 대한 영향력을 활용해 유리한 결정을 끌어냈어요.', 'The coalition leveraged its collective influence at the summit.', '연합체는 정상회담에서 집단적 영향력을 활용했어요.', 'C2', 'negotiation', 3, 'corporate boardroom'),
('col_negotiation_C2_05', 'stall', 'proceedings', 'stall proceedings', '회의 진행을 지연시키다', 'stop', '협상이나 절차의 진행을 의도적으로 늦춘다는 외교·법정 격식 표현이에요. ''stop''은 완전 중단을 뜻해 의미가 달라요.', 'The opposing counsel repeatedly stalled proceedings with procedural motions.', '상대 측 변호인은 절차 동의로 회의 진행을 거듭 지연시켰어요.', 'Stalling proceedings may buy time, but it erodes goodwill.', '진행 지연은 시간을 벌어주지만, 호의를 깎아내요.', 'C2', 'negotiation', 3, 'courtroom delay')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEGOTIATION — Idioms (C2)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_negotiation_C2_01', 'drive a hard bargain', '강하게 흥정하다', '단단한 흥정을 몰다', '자신에게 매우 유리한 조건을 끈질기게 요구하는 협상 태도를 가리켜요. 비즈니스 협상에서 격식 있는 칭찬이나 평가로 써요.', 'Their CFO is known to drive a hard bargain in licensing negotiations.', '그들의 CFO는 라이선스 협상에서 강하게 흥정하기로 유명해요.', 'You drive a hard bargain, but I respect your discipline.', '강하게 흥정하시지만, 그 절도는 존경해요.', 'She drove a hard bargain and walked away with terms few thought possible.', '그녀는 강하게 흥정해서 누구도 가능하다고 생각하지 않던 조건을 따냈어요.', 'C2', 'negotiation', 3, 'tough negotiator', 1),
('idm_negotiation_C2_02', 'have the upper hand', '우위를 점하다', '위쪽 손을 가지다', '협상이나 경쟁에서 유리한 위치에 있다는 격식 표현이에요. 외교, 비즈니스, 법정 등 다양한 격식 맥락에서 써요.', 'With exclusive supplier contracts, they clearly have the upper hand at the table.', '독점 공급 계약을 가진 그들은 협상 자리에서 명백히 우위를 점하고 있어요.', 'The party that controls the timeline often has the upper hand.', '일정을 통제하는 쪽이 흔히 우위를 점해요.', 'After the audit findings, regulators have the upper hand in the talks.', '감사 결과 이후 규제 당국이 협상에서 우위를 점하고 있어요.', 'C2', 'negotiation', 3, 'chess king', 2),
('idm_negotiation_C2_03', 'meet halfway', '서로 양보하다', '중간에서 만나다', '양측이 각자 양보해 중간 지점에서 합의한다는 외교·협상 표준 격식 표현이에요. 분쟁 조정에 자주 써요.', 'If both sides are willing to meet halfway, a settlement is within reach.', '양측이 서로 양보할 의향이 있다면 합의는 손에 닿아 있어요.', 'The mediator urged the parties to meet halfway on the contested clause.', '중재자는 양측에 쟁점 조항에서 서로 양보하라고 촉구했어요.', 'We are prepared to meet you halfway on the delivery timeline.', '납기 일정에 대해서는 저희도 양보할 준비가 되어 있어요.', 'C2', 'negotiation', 3, 'bridge meeting', 3),
('idm_negotiation_C2_04', 'back to square one', '원점으로 돌아가다', '1번 칸으로 돌아가다', '협상이나 계획이 무산되어 처음부터 다시 시작해야 하는 상황을 가리켜요. 비즈니스·외교 보고에서 격식 있게 써요.', 'With the deal collapsing, the negotiating team is back to square one.', '거래가 무산되어 협상 팀은 원점으로 돌아갔어요.', 'A single veto sent the entire framework back to square one.', '거부권 한 번이 전체 틀을 원점으로 되돌렸어요.', 'After two years of talks, we cannot afford to be back to square one.', '2년에 걸친 협상 끝에 원점으로 돌아갈 여유는 없어요.', 'C2', 'negotiation', 3, 'board game start', 4),
('idm_negotiation_C2_05', 'throw down the gauntlet', '도전장을 내밀다', '장갑을 던지다', '공식적으로 도전을 선언하거나 강한 대결 의지를 표명할 때 써요. 외교, 비즈니스 경쟁, 학술 토론의 격식 표현이에요.', 'By unveiling the new patent portfolio, the company threw down the gauntlet to its rivals.', '새 특허 포트폴리오를 공개함으로써 그 회사는 경쟁사들에게 도전장을 내밀었어요.', 'The keynote speech effectively threw down the gauntlet on climate accountability.', '기조 연설은 사실상 기후 책임 문제에 도전장을 내밀었어요.', 'She threw down the gauntlet, demanding a public debate on the proposal.', '그녀는 도전장을 내밀어 그 제안에 대한 공개 토론을 요구했어요.', 'C2', 'negotiation', 3, 'medieval gauntlet', 5)
ON CONFLICT (id) DO NOTHING;
