-- ============================================================
-- C1-level Collocations and Idioms — Batch B
-- Topics: health, weather, transport, media, education
-- 5 collocations + 5 idioms per topic = 50 total entries
-- ============================================================

-- ============================================================
-- HEALTH — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_health_C1_01', 'seek', 'treatment', 'seek treatment', '치료를 받다', 'get', '병원이나 전문가의 도움을 적극적으로 찾는다는 격식 있는 표현이에요. 의료 기사나 상담 자리에서 자주 써요.', 'You should seek treatment as soon as the symptoms worsen.', '증상이 악화되면 즉시 치료를 받아야 해요.', 'Many patients hesitate to seek treatment for mental health issues.', '많은 환자들이 정신 건강 문제로 치료받기를 망설여요.', 'C1', 'health', 2, 'doctor consultation'),
('col_health_C1_02', 'follow', 'doctor''s orders', 'follow doctor''s orders', '의사의 지시를 따르다', 'listen', '처방이나 권고 사항을 충실히 지킨다는 관용적 표현이에요. 격식 있는 회복 안내에서 흔히 써요.', 'She made a full recovery because she followed her doctor''s orders to the letter.', '그녀는 의사의 지시를 철저히 따라서 완전히 회복했어요.', 'Patients who follow doctor''s orders tend to heal faster.', '의사의 지시를 따르는 환자들이 더 빨리 낫는 경향이 있어요.', 'C1', 'health', 2, 'doctor prescription'),
('col_health_C1_03', 'make', 'recovery', 'make a recovery', '회복하다', 'do', '병이나 부상에서 회복하는 과정을 격식 있게 표현해요. ''make a full/speedy/remarkable recovery''처럼 형용사를 자주 동반해요.', 'He made a remarkable recovery after the surgery.', '그는 수술 후에 놀라울 정도로 회복했어요.', 'The patient is expected to make a full recovery within weeks.', '환자는 몇 주 안에 완전히 회복할 것으로 예상돼요.', 'C1', 'health', 2, 'hospital recovery'),
('col_health_C1_04', 'boost', 'immunity', 'boost immunity', '면역력을 높이다', 'increase', '면역 체계를 강화한다는 건강 분야의 전형적인 콜로케이션이에요. 잡지나 광고에서 자주 등장해요.', 'Eating a balanced diet helps boost your immunity during winter.', '균형 잡힌 식단은 겨울철 면역력을 높이는 데 도움이 돼요.', 'Regular exercise has been shown to boost immunity over time.', '규칙적인 운동은 시간이 지나면서 면역력을 높이는 것으로 밝혀졌어요.', 'C1', 'health', 2, 'healthy food vitamins'),
('col_health_C1_05', 'manage', 'stress', 'manage stress', '스트레스를 관리하다', 'control', '스트레스를 완전히 없애기보다 잘 다룬다는 의미예요. 자기계발과 건강 칼럼에서 표준 표현이에요.', 'Meditation can help you manage stress more effectively.', '명상은 스트레스를 더 효과적으로 관리하는 데 도움이 돼요.', 'Learning to manage stress is essential for long-term well-being.', '스트레스 관리법을 배우는 것은 장기적인 웰빙에 필수적이에요.', 'C1', 'health', 2, 'meditation calm')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- HEALTH — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_health_C1_01', 'on the mend', '회복 중인', '수선되는 중', '아픈 사람이 회복되고 있다는 다정한 표현이에요. 친구나 가족의 안부를 물을 때 자연스럽게 써요.', 'She caught a nasty flu but she''s on the mend now.', '독한 독감에 걸렸지만 지금은 회복 중이에요.', 'I''m glad to hear your father is on the mend.', '아버님이 회복 중이시라니 다행이에요.', 'After a week of rest, he''s finally on the mend.', '일주일간 쉬고 나니 그는 마침내 회복 중이에요.', 'C1', 'health', 2, 'patient resting', 1),
('idm_health_C1_02', 'as fit as a fiddle', '아주 건강한', '바이올린처럼 건강한', '나이에 비해 또는 아픔에서 회복한 뒤 매우 건강한 상태를 묘사해요. 일상 대화에서 가볍게 칭찬할 때 써요.', 'My grandmother is 85 but she''s as fit as a fiddle.', '할머니는 85세이신데 아주 정정하세요.', 'After three months of training, he was as fit as a fiddle.', '3개월간의 훈련 후 그는 아주 건강해졌어요.', 'Despite his age, the marathoner remains as fit as a fiddle.', '나이에도 불구하고 그 마라토너는 여전히 정정해요.', 'C1', 'health', 2, 'fit elderly person', 2),
('idm_health_C1_03', 'under the weather', '몸이 좀 안 좋은', '날씨 아래에', '심하게 아프지는 않지만 컨디션이 좋지 않을 때 써요. 직장에서 결근 사유를 부드럽게 말할 때 자주 써요.', 'I''m feeling a bit under the weather today, so I''ll work from home.', '오늘은 컨디션이 좀 안 좋아서 재택근무할게요.', 'She''s been under the weather all week and skipped the gym.', '그녀는 일주일 내내 컨디션이 안 좋아서 헬스장을 빠졌어요.', 'If you''re under the weather, please don''t push yourself.', '컨디션이 안 좋으시면 무리하지 마세요.', 'C1', 'health', 2, 'tired person tea', 3),
('idm_health_C1_04', 'a clean bill of health', '건강 이상 없음 판정', '깨끗한 건강 증명서', '검진 결과 아무 문제가 없다는 의학적 평가를 가리켜요. 정기 검진이나 사업 비유에서도 자주 등장해요.', 'The doctor gave him a clean bill of health after the annual checkup.', '의사는 그에게 건강 검진 후 이상 없음 판정을 내렸어요.', 'I won''t relax until I get a clean bill of health.', '건강 이상 없음 판정을 받기 전까지는 안심이 안 돼요.', 'The auditors gave the company a clean bill of health.', '감사관들은 회사에 아무 문제가 없다고 판정했어요.', 'C1', 'health', 2, 'medical checkup', 4),
('idm_health_C1_05', 'the picture of health', '건강 그 자체', '건강의 그림', '겉으로 보기에도 매우 건강해 보이는 사람을 묘사할 때 써요. 칭찬이나 묘사적 글에서 자연스러워요.', 'Tanned and smiling, she was the picture of health.', '햇볕에 그을리고 환하게 웃는 그녀는 건강 그 자체였어요.', 'At 70, he looks the picture of health.', '70세인 그는 건강 그 자체로 보여요.', 'After her holiday, she returned the picture of health.', '휴가 후에 그녀는 건강 그 자체로 돌아왔어요.', 'C1', 'health', 2, 'healthy smiling person', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- WEATHER — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_weather_C1_01', 'brave', 'cold', 'brave the cold', '추위를 무릅쓰다', 'face', '나쁜 날씨를 용감하게 견뎌낸다는 다소 문어적 표현이에요. 뉴스 기사나 여행기에 자주 등장해요.', 'Thousands braved the cold to watch the parade.', '수천 명이 추위를 무릅쓰고 퍼레이드를 봤어요.', 'We braved the cold for a sunrise hike up the mountain.', '우리는 추위를 무릅쓰고 일출 등산을 했어요.', 'C1', 'weather', 2, 'people in snow coats'),
('col_weather_C1_02', 'battle', 'heat', 'battle the heat', '더위와 싸우다', 'fight', '극심한 더위에 맞서 버틴다는 비유적 표현이에요. 여름 기사나 스포츠 보도에서 자주 써요.', 'Construction workers battle the heat throughout July and August.', '건설 노동자들은 7월과 8월 내내 더위와 싸워요.', 'Marathon runners had to battle the heat during the final stretch.', '마라톤 선수들은 마지막 구간에서 더위와 싸워야 했어요.', 'C1', 'weather', 2, 'hot summer sun'),
('col_weather_C1_03', 'endure', 'downpour', 'endure a downpour', '폭우를 견뎌내다', 'pass', '강한 비를 오랜 시간 참고 견딘다는 격식 있는 표현이에요. 야외 행사 보도나 여행기에서 자주 써요.', 'Spectators endured a torrential downpour to witness the match.', '관중들은 경기를 보기 위해 억수같은 폭우를 견뎌냈어요.', 'We endured a downpour while waiting for the bus.', '버스를 기다리며 폭우를 견뎌냈어요.', 'C1', 'weather', 2, 'heavy rain crowd'),
('col_weather_C1_04', 'shelter', 'rain', 'shelter from rain', '비를 피하다', 'hide', '비를 피하기 위해 잠시 어딘가에 들어간다는 자연스러운 표현이에요. ''hide''는 약간 부자연스러워요.', 'We sheltered from the rain under a shop awning.', '우리는 가게 차양 아래에서 비를 피했어요.', 'Hikers sheltered from the rain in a nearby cabin.', '등산객들은 근처 오두막에서 비를 피했어요.', 'C1', 'weather', 2, 'rain shelter awning'),
('col_weather_C1_05', 'wrap', 'up warm', 'wrap up warm', '따뜻하게 껴입다', 'dress', '추운 날 두꺼운 옷으로 몸을 감싼다는 영국식 표현이에요. ''dress warm''보다 훨씬 자연스러워요.', 'Wrap up warm — it''s freezing outside.', '따뜻하게 껴입어요. 밖이 정말 추워요.', 'The children wrapped up warm before heading out to play in the snow.', '아이들은 눈 속에서 놀러 나가기 전에 따뜻하게 껴입었어요.', 'C1', 'weather', 2, 'winter coat scarf')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- WEATHER — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_weather_C1_01', 'a perfect storm', '여러 악재가 겹친 상황', '완벽한 폭풍', '여러 부정적 요소들이 동시에 겹쳐 최악의 상황을 만들었다는 뜻이에요. 뉴스와 비즈니스 분석에서 매우 자주 써요.', 'Rising costs and falling demand created a perfect storm for the industry.', '비용 상승과 수요 감소가 그 산업에 최악의 상황을 만들었어요.', 'The economy is facing a perfect storm of inflation and unemployment.', '경제는 인플레이션과 실업이 겹친 최악의 상황에 직면해 있어요.', 'It was a perfect storm of bad decisions and bad luck.', '잘못된 결정과 불운이 겹친 최악의 상황이었어요.', 'C1', 'weather', 2, 'storm clouds dramatic', 1),
('idm_weather_C1_02', 'under the weather', '몸이 좀 안 좋은', '날씨 아래에', '몸이 살짝 아프거나 컨디션이 안 좋을 때 부드럽게 표현해요. 격식과 비격식 모두에서 자연스러워요.', 'I''m feeling a bit under the weather, so I''ll skip dinner.', '컨디션이 좀 안 좋아서 저녁은 거를게요.', 'He''s been under the weather since Monday.', '그는 월요일부터 컨디션이 안 좋아요.', 'If you''re under the weather, take the day off.', '컨디션이 안 좋으면 하루 쉬세요.', 'C1', 'weather', 2, 'sick person bed', 2),
('idm_weather_C1_03', 'calm before the storm', '폭풍 전의 고요', '폭풍 전의 고요', '큰 사건이나 혼란이 닥치기 직전의 일시적인 평온함을 뜻해요. 뉴스, 비즈니스, 일상 대화에서 두루 써요.', 'The office is unusually quiet — it''s the calm before the storm.', '사무실이 이상하게 조용해요. 폭풍 전의 고요예요.', 'Enjoy this calm before the storm; tomorrow will be hectic.', '폭풍 전의 고요를 즐기세요. 내일은 정신없을 거예요.', 'The calm before the storm lasted only an hour.', '폭풍 전의 고요는 한 시간밖에 지속되지 않았어요.', 'C1', 'weather', 2, 'calm sea before storm', 3),
('idm_weather_C1_04', 'raining cats and dogs', '비가 억수같이 오는', '고양이와 개가 비처럼 내리는', '비가 매우 세차게 내릴 때 쓰는 전형적인 영어 관용구예요. 친근한 대화에서 흔히 써요.', 'You can''t go out now — it''s raining cats and dogs!', '지금 나가면 안 돼요. 비가 억수같이 와요!', 'It was raining cats and dogs when we left the theater.', '극장을 나올 때 비가 억수같이 왔어요.', 'Bring an umbrella; it''s raining cats and dogs out there.', '우산 챙기세요. 밖에 비가 억수같이 와요.', 'C1', 'weather', 2, 'heavy downpour street', 4),
('idm_weather_C1_05', 'a fair-weather friend', '잘 나갈 때만 친한 친구', '좋은 날씨일 때만의 친구', '내가 어려울 때는 멀어지고, 잘 지낼 때만 가까이 오는 사람을 뜻해요. 약간의 비판적 뉘앙스가 있어요.', 'When I lost my job, I realized he was just a fair-weather friend.', '제가 일자리를 잃었을 때 그가 잘 나갈 때만의 친구였다는 걸 깨달았어요.', 'True friends stand by you; fair-weather friends disappear.', '진정한 친구는 곁에 있어주고, 잘 나갈 때만의 친구는 사라져요.', 'Don''t waste your loyalty on fair-weather friends.', '잘 나갈 때만의 친구에게 의리를 낭비하지 마세요.', 'C1', 'weather', 2, 'two friends sunshine', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TRANSPORT — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_transport_C1_01', 'hail', 'cab', 'hail a cab', '택시를 잡다', 'call', '길에서 손을 들어 지나가는 택시를 세운다는 의미예요. ''call''은 전화로 부르는 거라 어감이 달라요.', 'It''s nearly impossible to hail a cab in this rainstorm.', '이 폭우 속에서는 택시를 잡기가 거의 불가능해요.', 'She stepped onto the curb and hailed a cab.', '그녀는 인도로 나가서 택시를 잡았어요.', 'C1', 'transport', 2, 'hailing taxi street'),
('col_transport_C1_02', 'miss', 'bus', 'miss the bus', '버스를 놓치다', 'lose', '교통수단을 시간 안에 못 타는 것은 ''miss''를 써요. ''lose''는 의미가 달라져요.', 'I missed the last bus and had to walk home.', '막차를 놓쳐서 집까지 걸어가야 했어요.', 'If we don''t leave now, we''ll miss the bus.', '지금 출발하지 않으면 버스를 놓칠 거예요.', 'C1', 'transport', 2, 'missed bus stop'),
('col_transport_C1_03', 'catch', 'train', 'catch the train', '기차를 잡아타다', 'take', '출발 직전의 기차를 타는 데 성공한다는 뉘앙스예요. ''take the train''보다 시간 압박이 있어요.', 'We caught the train just before it left the platform.', '우리는 기차가 플랫폼을 떠나기 직전에 잡아탔어요.', 'Hurry, or we won''t catch the train.', '서둘러요, 안 그러면 기차를 못 타요.', 'C1', 'transport', 2, 'train platform departure'),
('col_transport_C1_04', 'navigate', 'traffic', 'navigate traffic', '교통 체증을 헤쳐 나가다', 'pass', '혼잡한 도로를 능숙하게 운전해 빠져나간다는 표현이에요. 격식 있는 글이나 운전 칼럼에서 자주 써요.', 'Experienced drivers know how to navigate traffic during rush hour.', '능숙한 운전자는 출퇴근 시간에 교통 체증을 헤쳐 나갈 줄 알아요.', 'It took us two hours to navigate the city traffic.', '도심 교통을 헤쳐 나가는 데 두 시간이 걸렸어요.', 'C1', 'transport', 2, 'city traffic jam'),
('col_transport_C1_05', 'make', 'connections', 'make connections', '환승하다', 'change', '비행기, 기차 등을 갈아탄다는 격식 있는 표현이에요. 항공 안내나 여행기에서 자주 등장해요.', 'Passengers must make connections in Frankfurt before flying to Seoul.', '승객들은 서울행 비행 전에 프랑크푸르트에서 환승해야 해요.', 'I had only 30 minutes to make connections at the airport.', '공항에서 환승할 시간이 30분밖에 없었어요.', 'C1', 'transport', 2, 'airport connection terminal')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TRANSPORT — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_transport_C1_01', 'hit the road', '출발하다', '길을 치다', '여행이나 외출을 시작한다는 캐주얼하지만 표준적인 관용 표현이에요. 친구들과의 대화에서 자연스러워요.', 'It''s getting late — we should hit the road.', '늦어지고 있네요. 이제 출발해요.', 'We hit the road at dawn to beat the traffic.', '우리는 교통 체증을 피하려고 새벽에 출발했어요.', 'Pack your bags; we hit the road tomorrow.', '짐 싸세요. 내일 출발해요.', 'C1', 'transport', 2, 'road trip car', 1),
('idm_transport_C1_02', 'out of pocket', '자비로 부담한', '주머니 밖의', '자기 돈으로 비용을 부담했다는 의미예요. 비즈니스나 출장 비용 정산에서 자주 써요.', 'I was out of pocket for the taxi fare during the business trip.', '출장 중 택시비를 자비로 부담했어요.', 'Don''t worry — you won''t be out of pocket; the company will reimburse you.', '걱정 마세요. 자비 부담은 없을 거예요. 회사가 환급해 줄 거예요.', 'She was out of pocket by 200 dollars after the trip.', '여행 후 그녀는 200달러를 자비로 부담했어요.', 'C1', 'transport', 2, 'wallet money receipt', 2),
('idm_transport_C1_03', 'miss the boat', '기회를 놓치다', '배를 놓치다', '좋은 기회를 너무 늦게 알아서 놓쳤다는 뜻이에요. 비즈니스, 투자, 여행 등 다양한 상황에서 써요.', 'If you don''t book early, you''ll miss the boat on cheap flights.', '미리 예약하지 않으면 저렴한 항공권 기회를 놓칠 거예요.', 'Investors who hesitated missed the boat on the tech boom.', '망설였던 투자자들은 IT 붐의 기회를 놓쳤어요.', 'Don''t miss the boat — sign up before the discount ends.', '기회를 놓치지 마세요. 할인이 끝나기 전에 신청하세요.', 'C1', 'transport', 2, 'boat leaving dock', 3),
('idm_transport_C1_04', 'off the beaten path', '잘 알려지지 않은', '많이 다닌 길에서 벗어난', '관광객들이 잘 가지 않는 숨겨진 장소를 가리켜요. 여행 잡지와 블로그에서 표준 표현이에요.', 'This little village is wonderfully off the beaten path.', '이 작은 마을은 정말 잘 알려지지 않은 곳이에요.', 'We prefer destinations off the beaten path.', '우리는 잘 알려지지 않은 곳을 선호해요.', 'The café is off the beaten path but worth the detour.', '그 카페는 잘 알려지지 않은 곳이지만 돌아갈 만한 가치가 있어요.', 'C1', 'transport', 2, 'hidden village trail', 4),
('idm_transport_C1_05', 'go off the rails', '엇나가다', '레일에서 벗어나다', '계획이나 사람의 삶이 정상 궤도를 벗어나 잘못된 방향으로 간다는 뜻이에요. 뉴스와 일상 대화 모두에서 써요.', 'The project went off the rails after the manager quit.', '매니저가 그만둔 후 프로젝트가 엇나가기 시작했어요.', 'His career went off the rails during the scandal.', '그의 경력은 스캔들 중 엇나가기 시작했어요.', 'The negotiations have gone completely off the rails.', '협상이 완전히 엇나갔어요.', 'C1', 'transport', 2, 'derailed train tracks', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- MEDIA — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_media_C1_01', 'go', 'viral', 'go viral', '입소문 나다', 'become', '콘텐츠가 인터넷에서 급속도로 퍼지는 현상을 뜻해요. 미디어, 마케팅 분야의 핵심 표현이에요.', 'Her dance video went viral overnight.', '그녀의 댄스 영상은 하룻밤 사이에 입소문이 났어요.', 'Brands dream of creating content that goes viral.', '브랜드들은 입소문 나는 콘텐츠를 만드는 걸 꿈꿔요.', 'C1', 'media', 2, 'viral video phone'),
('col_media_C1_02', 'draw', 'attention', 'draw attention', '주목을 끌다', 'pull', '사람들의 시선이나 관심을 모은다는 격식 있는 표현이에요. 뉴스, 광고, 학술 글에서 두루 써요.', 'The documentary drew attention to climate change.', '그 다큐멘터리는 기후 변화에 대한 주목을 끌었어요.', 'The campaign successfully drew attention to youth literacy.', '그 캠페인은 청소년 문해력 문제에 성공적으로 주목을 끌었어요.', 'C1', 'media', 2, 'spotlight news camera'),
('col_media_C1_03', 'shape', 'narrative', 'shape the narrative', '담론을 형성하다', 'make', '이야기나 여론의 흐름을 의도적으로 만든다는 정치·미디어 분야의 핵심 표현이에요.', 'Social media now shapes the narrative around political events.', '소셜 미디어는 이제 정치 이슈의 담론을 형성해요.', 'Public relations teams work to shape the narrative.', '홍보팀은 담론을 형성하기 위해 노력해요.', 'C1', 'media', 2, 'news headlines media'),
('col_media_C1_04', 'stir', 'controversy', 'stir controversy', '논란을 일으키다', 'cause', '사회적으로 뜨거운 논쟁을 불러일으킨다는 격식 있는 저널리즘 표현이에요.', 'The advertisement stirred controversy across social media.', '그 광고는 소셜 미디어 전반에 논란을 일으켰어요.', 'His remarks stirred controversy among critics.', '그의 발언은 비평가들 사이에 논란을 일으켰어요.', 'C1', 'media', 2, 'controversial news'),
('col_media_C1_05', 'make', 'headlines', 'make headlines', '머리기사를 장식하다', 'get', '사건이 신문 1면을 차지할 만큼 큰 화제가 된다는 의미예요. 뉴스 보도와 일상 대화에서 모두 써요.', 'The merger made headlines around the world.', '그 합병은 전 세계 머리기사를 장식했어요.', 'Her humanitarian work made headlines last week.', '그녀의 인도주의적 활동이 지난주 머리기사를 장식했어요.', 'C1', 'media', 2, 'newspaper front page')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- MEDIA — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_media_C1_01', 'in the spotlight', '주목받는', '스포트라이트 안에', '대중이나 언론의 관심을 한 몸에 받는 상태를 뜻해요. 연예, 정치, 비즈니스 모든 분야에서 써요.', 'The young actress found herself in the spotlight after the film''s release.', '그 어린 여배우는 영화 개봉 후 주목을 받게 되었어요.', 'CEOs are constantly in the spotlight.', 'CEO들은 끊임없이 주목받아요.', 'Being in the spotlight is not always a blessing.', '주목받는 것이 항상 축복은 아니에요.', 'C1', 'media', 2, 'spotlight stage performer', 1),
('idm_media_C1_02', 'behind the scenes', '비공식적으로, 무대 뒤에서', '장면 뒤에서', '공식적으로 드러나지 않는 곳에서 일이 진행된다는 의미예요. 비즈니스와 미디어 보도에서 표준 표현이에요.', 'A lot of negotiation happens behind the scenes.', '많은 협상이 비공식적으로 이루어져요.', 'Behind the scenes, the team worked tirelessly on the launch.', '뒤에서는 팀이 출시를 위해 쉴 새 없이 일했어요.', 'The documentary shows what happens behind the scenes.', '그 다큐멘터리는 무대 뒤에서 일어나는 일을 보여줘요.', 'C1', 'media', 2, 'film crew behind scenes', 2),
('idm_media_C1_03', 'make a splash', '큰 화제를 일으키다', '물 튀기다', '강한 인상을 남기며 주목받는다는 뜻이에요. 신제품 출시, 데뷔, 발표 등에 자주 써요.', 'The new app made a splash in the tech industry.', '그 새 앱은 IT 업계에서 큰 화제를 일으켰어요.', 'Her debut novel made quite a splash.', '그녀의 데뷔 소설은 상당한 화제를 일으켰어요.', 'The brand made a splash with its bold campaign.', '그 브랜드는 대담한 캠페인으로 큰 화제를 일으켰어요.', 'C1', 'media', 2, 'splashing water impact', 3),
('idm_media_C1_04', 'the talk of the town', '동네의 화젯거리', '동네의 이야기', '많은 사람들이 화제 삼아 이야기하는 인물이나 사건을 가리켜요. 일상 대화에서 자연스럽게 써요.', 'The new restaurant is the talk of the town.', '그 새 식당이 동네의 화젯거리예요.', 'Her surprise wedding became the talk of the town.', '그녀의 깜짝 결혼식이 동네의 화젯거리가 됐어요.', 'That scandal was the talk of the town for weeks.', '그 스캔들은 몇 주간 동네의 화젯거리였어요.', 'C1', 'media', 2, 'town gossip people', 4),
('idm_media_C1_05', 'no smoke without fire', '아니 땐 굴뚝에 연기 나랴', '불 없이 연기 없다', '소문이 돈다면 그 안에 어느 정도 사실이 있다는 뜻이에요. 토론이나 가십 분석에서 자주 인용돼요.', 'There must be some truth to the rumors — no smoke without fire.', '그 소문에는 어느 정도 사실이 있을 거예요. 아니 땐 굴뚝에 연기 나겠어요.', 'I don''t trust him; there''s no smoke without fire.', '그를 못 믿겠어요. 아니 땐 굴뚝에 연기 나겠어요.', 'As they say, no smoke without fire — investigators are looking into it.', '말 그대로 아니 땐 굴뚝에 연기 안 나죠. 조사관들이 들여다보고 있어요.', 'C1', 'media', 2, 'smoke rising chimney', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- EDUCATION — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_education_C1_01', 'earn', 'degree', 'earn a degree', '학위를 취득하다', 'get', '시간과 노력을 들여 학위를 받았다는 격식 있는 표현이에요. ''get a degree''보다 더 무게감 있게 들려요.', 'She earned a master''s degree in linguistics.', '그녀는 언어학 석사 학위를 취득했어요.', 'He earned his degree while working full-time.', '그는 풀타임으로 일하면서 학위를 취득했어요.', 'C1', 'education', 2, 'graduation diploma'),
('col_education_C1_02', 'broaden', 'horizons', 'broaden horizons', '시야를 넓히다', 'open', '경험이나 학습을 통해 사고와 관점을 확장한다는 의미예요. 교육·여행 분야에서 매우 자주 써요.', 'Studying abroad really broadens your horizons.', '해외 유학은 시야를 정말 넓혀줘요.', 'Reading widely is one of the best ways to broaden your horizons.', '폭넓게 읽는 것은 시야를 넓히는 가장 좋은 방법 중 하나예요.', 'C1', 'education', 2, 'student abroad horizon'),
('col_education_C1_03', 'grasp', 'concept', 'grasp a concept', '개념을 이해하다', 'catch', '추상적인 개념을 정확히 이해한다는 학술적 표현이에요. ''catch''는 부자연스러워요.', 'Most students grasp the concept of supply and demand quickly.', '대부분의 학생들은 수요와 공급 개념을 빠르게 이해해요.', 'It took me a while to grasp the concept of quantum mechanics.', '양자역학 개념을 이해하는 데 시간이 좀 걸렸어요.', 'C1', 'education', 2, 'student understanding book'),
('col_education_C1_04', 'master', 'subject', 'master a subject', '한 과목을 통달하다', 'learn', '단순히 배우는 것을 넘어 매우 깊이 있게 익혔다는 뜻이에요. 학업과 전문 분야에서 두루 써요.', 'It takes years of practice to master a subject like calculus.', '미적분 같은 과목을 통달하는 데는 수년간의 연습이 필요해요.', 'She has mastered the subject of medieval history.', '그녀는 중세사 분야를 통달했어요.', 'C1', 'education', 2, 'student studying mastery'),
('col_education_C1_05', 'ace', 'exam', 'ace an exam', '시험을 잘 보다', 'win', '시험을 매우 잘 봐서 최고 점수를 받는다는 미국식 표현이에요. 캐주얼하지만 C1 수준에서 흔히 써요.', 'She aced her final exam without breaking a sweat.', '그녀는 땀 한 방울 흘리지 않고 기말고사를 잘 봤어요.', 'If you study hard, you''ll ace the exam.', '열심히 공부하면 시험을 잘 볼 거예요.', 'C1', 'education', 2, 'exam test perfect score')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- EDUCATION — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_education_C1_01', 'hit the books', '공부에 매진하다', '책을 치다', '공부를 본격적으로 시작하거나 열심히 한다는 친근한 학생 표현이에요. 대학생들 사이에서 매우 자연스러워요.', 'Finals are next week — time to hit the books.', '다음 주가 기말이에요. 이제 공부에 매진할 때예요.', 'I can''t go out tonight; I have to hit the books.', '오늘 밤은 못 나가요. 공부해야 해요.', 'She''s been hitting the books for weeks.', '그녀는 몇 주째 공부에 매진하고 있어요.', 'C1', 'education', 2, 'student studying books', 1),
('idm_education_C1_02', 'make the grade', '기준에 부합하다', '학점을 만들다', '요구되는 수준이나 기준에 도달한다는 뜻이에요. 학업뿐 아니라 직장과 스포츠에서도 자주 써요.', 'Only a handful of applicants made the grade.', '극소수의 지원자만이 기준에 부합했어요.', 'You need to study harder to make the grade.', '기준에 부합하려면 더 열심히 공부해야 해요.', 'The team didn''t quite make the grade for the playoffs.', '그 팀은 플레이오프 기준에 살짝 못 미쳤어요.', 'C1', 'education', 2, 'report card grade', 2),
('idm_education_C1_03', 'old school', '구식의, 전통적인', '오래된 학교', '전통적이고 옛 방식을 고수한다는 뜻으로, 종종 긍정적이고 멋스럽다는 뉘앙스도 가져요. 패션, 음악, 교육 등 다양한 분야에서 써요.', 'My professor is very old school — no laptops in class.', '제 교수님은 굉장히 구식이에요. 수업에 노트북도 못 가져와요.', 'He prefers an old-school approach to teaching.', '그는 구식의 교육 방식을 선호해요.', 'There''s something charming about her old-school manners.', '그녀의 구식 매너에는 매력적인 면이 있어요.', 'C1', 'education', 2, 'vintage classroom', 3),
('idm_education_C1_04', 'learn the ropes', '요령을 배우다', '밧줄을 배우다', '새로운 일이나 환경의 기본을 익힌다는 뜻이에요. 신입사원이나 새로운 학생에게 흔히 써요.', 'It took me a few months to learn the ropes at the new job.', '새 직장에서 요령을 배우는 데 몇 달 걸렸어요.', 'Don''t worry — you''ll learn the ropes soon enough.', '걱정 마세요. 곧 요령을 익힐 거예요.', 'The mentor helped her learn the ropes quickly.', '멘토 덕분에 그녀는 빠르게 요령을 익혔어요.', 'C1', 'education', 2, 'mentor training new hire', 4),
('idm_education_C1_05', 'pass with flying colors', '우수한 성적으로 통과하다', '깃발을 휘날리며 통과하다', '시험이나 평가를 매우 훌륭하게 통과했다는 격식 있는 표현이에요. 학업과 검증 절차 모두에서 써요.', 'She passed her driving test with flying colors.', '그녀는 우수한 성적으로 운전 면허 시험을 통과했어요.', 'The product passed safety inspections with flying colors.', '그 제품은 안전 검사를 우수하게 통과했어요.', 'He passed the bar exam with flying colors.', '그는 변호사 시험을 우수한 성적으로 통과했어요.', 'C1', 'education', 2, 'success colorful flags', 5)
ON CONFLICT (id) DO NOTHING;
