-- ============================================================
-- C1-level Collocations and Idioms — Batch C
-- Topics: economy, technology, environment, news, sports
-- 5 collocations + 5 idioms per topic = 50 total entries
-- Priority = 2 for C1
-- ============================================================

-- ============================================================
-- ECONOMY — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_economy_C1_01', 'boost', 'growth', 'boost growth', '성장을 촉진하다', 'rise', '경제 성장률을 끌어올린다는 표준 표현이에요. 정책, 투자, 무역 관련 기사에서 자주 등장해요.', 'The central bank lowered rates to boost growth in the manufacturing sector.', '중앙은행은 제조업 성장을 촉진하기 위해 금리를 인하했어요.', 'Tax incentives are designed to boost growth among small businesses.', '세제 혜택은 중소기업 성장을 촉진하기 위해 설계됐어요.', 'C1', 'economy', 2, 'rising chart'),
('col_economy_C1_02', 'tackle', 'inflation', 'tackle inflation', '인플레이션에 대응하다', 'fight', '''fight''도 가능하지만 ''tackle''이 정책적·전략적으로 문제를 다룬다는 뉘앙스라 신문에서 더 흔해요.', 'The government unveiled a new package to tackle inflation and stabilize prices.', '정부는 인플레이션에 대응하고 물가를 안정시키기 위한 새 패키지를 공개했어요.', 'Policymakers are under pressure to tackle inflation without triggering a recession.', '정책 입안자들은 경기 침체를 유발하지 않고 인플레이션에 대응해야 한다는 압박을 받고 있어요.', 'C1', 'economy', 2, 'inflation chart'),
('col_economy_C1_03', 'raise', 'interest rates', 'raise interest rates', '금리를 인상하다', 'lift', '중앙은행이 기준 금리를 올린다는 정확한 표현이에요. ''lift''는 일상 영어라 금융 보도에는 어울리지 않아요.', 'The Federal Reserve is expected to raise interest rates again next quarter.', '연준은 다음 분기에 다시 금리를 인상할 것으로 예상돼요.', 'Raising interest rates too quickly could slow the housing market.', '금리를 너무 빨리 인상하면 주택 시장이 둔화될 수 있어요.', 'C1', 'economy', 2, 'federal reserve'),
('col_economy_C1_04', 'spur', 'demand', 'spur demand', '수요를 자극하다', 'make', '소비자 수요를 단시간에 늘린다는 격식 있는 표현이에요. 마케팅이나 정책 보고서에 자주 써요.', 'Holiday discounts spurred demand for electronics across the region.', '연휴 할인이 지역 전반에 걸쳐 전자제품 수요를 자극했어요.', 'Government subsidies have spurred demand for electric vehicles.', '정부 보조금이 전기차 수요를 자극했어요.', 'C1', 'economy', 2, 'shopping demand'),
('col_economy_C1_05', 'rebound', 'recession', 'rebound from recession', '불황에서 회복하다', 'come', '경제가 침체기 이후 다시 활기를 되찾는다는 표현이에요. 분기 실적이나 거시 경제 분석에 자주 나와요.', 'The economy is finally rebounding from the deepest recession in a decade.', '경제가 마침내 10년 만의 가장 깊은 불황에서 회복하고 있어요.', 'Tourism has rebounded from the recession faster than analysts predicted.', '관광업은 분석가들의 예상보다 빠르게 불황에서 회복했어요.', 'C1', 'economy', 2, 'economic recovery')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ECONOMY — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_economy_C1_01', 'tighten your belt', '허리띠를 졸라매다', '벨트를 조이다', '지출을 줄이고 절약 생활을 한다는 뜻이에요. 개인 재정과 기업 비용 절감 양쪽에 다 써요.', 'Many households have had to tighten their belts as energy prices surged.', '에너지 가격이 급등하면서 많은 가정이 허리띠를 졸라매야 했어요.', 'The company is tightening its belt by freezing all non-essential spending.', '회사는 비필수 지출을 모두 동결하며 허리띠를 졸라매고 있어요.', 'We may need to tighten our belts until the bonus comes through.', '보너스가 나올 때까지 허리띠를 졸라매야 할 수도 있어요.', 'C1', 'economy', 2, 'tight belt', 1),
('idm_economy_C1_02', 'make ends meet', '겨우 먹고살다', '양쪽 끝을 만나게 하다', '수입이 빠듯해서 겨우 생활비를 충당한다는 뜻이에요. 인터뷰나 사회 기사에서 자주 등장해요.', 'With rent rising, many young workers struggle to make ends meet.', '월세가 오르면서 많은 청년 근로자가 겨우 먹고살기도 힘들어해요.', 'She took on a second job just to make ends meet.', '그녀는 겨우 생활비를 충당하려고 부업을 하나 더 시작했어요.', 'Single parents often find it hard to make ends meet on one salary.', '한부모 가정은 한 사람 월급으로 생활하기 어려운 경우가 많아요.', 'C1', 'economy', 2, 'wallet budget', 2),
('idm_economy_C1_03', 'in the red', '적자 상태인', '빨간색 안에 있는', '회계상 손실 상태를 가리키는 표준 표현이에요. 회사 실적이나 개인 계좌 모두에 써요.', 'The airline has been in the red for three consecutive quarters.', '그 항공사는 3분기 연속 적자 상태예요.', 'Her checking account slipped into the red after the unexpected bill.', '예상치 못한 청구서로 그녀의 입출금 계좌가 적자로 돌아섰어요.', 'Several startups remain in the red despite strong revenue growth.', '여러 스타트업이 매출 성장에도 불구하고 적자 상태에 머물러 있어요.', 'C1', 'economy', 2, 'red financial chart', 3),
('idm_economy_C1_04', 'in the black', '흑자 상태인', '검은색 안에 있는', '''in the red''의 반대로, 이익을 내고 있다는 뜻이에요. 분기 실적 발표에서 자주 들을 수 있어요.', 'After two tough years, the firm is finally back in the black.', '힘든 2년을 보낸 끝에 그 회사는 마침내 흑자로 돌아왔어요.', 'The streaming division has been in the black since last spring.', '스트리밍 사업부는 지난봄부터 흑자 상태예요.', 'Cost-cutting measures pushed the bank firmly into the black.', '비용 절감 조치로 그 은행은 확실한 흑자 상태가 됐어요.', 'C1', 'economy', 2, 'profit chart', 4),
('idm_economy_C1_05', 'a penny saved is a penny earned', '한 푼을 아끼면 한 푼을 번 것', '아낀 1페니는 번 1페니와 같다', '절약이 곧 수입이라는 격언이에요. 재테크 칼럼이나 가족 간 대화에서 자연스럽게 써요.', 'My grandmother always said that a penny saved is a penny earned.', '저희 할머니는 늘 한 푼을 아끼면 한 푼을 번 것이라고 말씀하셨어요.', 'Investing in energy-efficient appliances pays off — a penny saved is a penny earned.', '에너지 효율 가전에 투자하는 건 보람이 있어요. 한 푼을 아끼면 한 푼을 번 것이니까요.', 'In this economy, a penny saved really is a penny earned.', '요즘 같은 경제에서는 한 푼을 아끼는 게 정말 버는 것과 같아요.', 'C1', 'economy', 2, 'penny coin jar', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TECHNOLOGY — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_technology_C1_01', 'adopt', 'innovation', 'adopt innovation', '혁신을 도입하다', 'take', '새로운 기술이나 방식을 조직 차원에서 받아들인다는 뜻이에요. 비즈니스 보고서의 표준 표현이에요.', 'Hospitals have been slow to adopt innovation in patient record systems.', '병원들은 환자 기록 시스템 혁신을 도입하는 데 느렸어요.', 'Successful firms continually adopt innovation to stay competitive.', '성공하는 기업은 경쟁력을 유지하기 위해 끊임없이 혁신을 도입해요.', 'C1', 'technology', 2, 'modern office tech'),
('col_technology_C1_02', 'integrate', 'systems', 'integrate systems', '시스템을 통합하다', 'join', '서로 다른 IT 시스템을 하나로 연동시킨다는 기술 표현이에요. ''join''은 단순 결합이라 정확하지 않아요.', 'The acquisition will require us to integrate systems across three continents.', '이번 인수로 3개 대륙에 걸친 시스템을 통합해야 해요.', 'It took six months to fully integrate the new CRM system with our database.', '새 CRM 시스템을 우리 데이터베이스와 완전히 통합하는 데 6개월이 걸렸어요.', 'C1', 'technology', 2, 'server room'),
('col_technology_C1_03', 'deploy', 'software', 'deploy software', '소프트웨어를 배포하다', 'put', '소프트웨어를 운영 환경에 설치하고 가동시킨다는 IT 표준 동사예요. ''put''은 너무 일상적이에요.', 'The team will deploy the software update across all servers tonight.', '팀은 오늘 밤 모든 서버에 소프트웨어 업데이트를 배포할 거예요.', 'We deploy software in stages to minimize disruption.', '우리는 지장을 최소화하기 위해 단계적으로 소프트웨어를 배포해요.', 'C1', 'technology', 2, 'developer screen'),
('col_technology_C1_04', 'tackle', 'bugs', 'tackle bugs', '버그를 해결하다', 'kill', '''kill bugs''도 쓰이지만, ''tackle''이 체계적으로 문제를 해결한다는 전문적인 뉘앙스라 더 격식 있어요.', 'Our QA engineers are tackling the most critical bugs before launch.', '우리 QA 엔지니어들이 출시 전에 가장 심각한 버그를 해결하고 있어요.', 'The patch tackles several long-standing bugs reported by users.', '이 패치는 사용자들이 보고한 여러 고질적인 버그를 해결해요.', 'C1', 'technology', 2, 'debugging code'),
('col_technology_C1_05', 'scale', 'operations', 'scale operations', '운영 규모를 확장하다', 'grow', '''grow''는 일반적이지만, ''scale''은 효율을 유지하며 규모를 키운다는 스타트업/테크 용어예요.', 'Cloud infrastructure allows startups to scale operations rapidly.', '클라우드 인프라 덕분에 스타트업이 운영 규모를 빠르게 확장할 수 있어요.', 'We need a better hiring strategy before we scale operations into Asia.', '아시아로 운영을 확장하기 전에 더 나은 채용 전략이 필요해요.', 'C1', 'technology', 2, 'data center')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- TECHNOLOGY — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_technology_C1_01', 'cutting edge', '최첨단의', '날카로운 가장자리', '가장 앞선 기술이나 발전을 뜻해요. 형용사처럼 ''cutting-edge''로 자주 써요.', 'Their lab develops cutting-edge AI tools used by researchers worldwide.', '그들의 연구실은 전 세계 연구자들이 쓰는 최첨단 AI 도구를 개발해요.', 'The new headset is at the cutting edge of virtual reality.', '새 헤드셋은 가상현실의 최첨단에 있어요.', 'She wants to work somewhere on the cutting edge of biotech.', '그녀는 생명공학 최첨단 분야에서 일하고 싶어 해요.', 'C1', 'technology', 2, 'futuristic tech', 1),
('idm_technology_C1_02', 'tech savvy', '기술에 밝은', '기술 능숙한', '디지털 기기와 소프트웨어를 능숙하게 다룬다는 뜻이에요. 채용 공고나 일상 대화에 자연스럽게 써요.', 'You do not need to be tech savvy to use the new app — it is very intuitive.', '새 앱을 쓰는 데 기술에 밝을 필요는 없어요. 매우 직관적이에요.', 'Our marketing team is increasingly tech savvy thanks to ongoing training.', '저희 마케팅팀은 꾸준한 교육 덕분에 점점 기술에 밝아지고 있어요.', 'Tech-savvy consumers expect seamless mobile experiences.', '기술에 밝은 소비자들은 매끄러운 모바일 경험을 기대해요.', 'C1', 'technology', 2, 'person using laptop', 2),
('idm_technology_C1_03', 'out of date', '구식의', '날짜 밖의', '더 이상 최신이 아니라는 뜻이에요. 소프트웨어, 정보, 디자인 등에 폭넓게 써요.', 'This operating system is out of date and no longer receives security patches.', '이 운영체제는 구식이라 더 이상 보안 패치를 받지 못해요.', 'Their website looks badly out of date compared to competitors.', '그들의 웹사이트는 경쟁사에 비해 한참 구식으로 보여요.', 'Most of the data in the report is already out of date.', '보고서 데이터 대부분이 이미 구식이에요.', 'C1', 'technology', 2, 'old computer', 3),
('idm_technology_C1_04', 'user friendly', '사용하기 쉬운', '사용자 친화적인', '복잡한 기능 없이 누구나 쉽게 쓸 수 있다는 뜻이에요. 제품 리뷰의 표준 표현이에요.', 'The redesign made the app significantly more user friendly.', '새 디자인 덕분에 앱이 훨씬 더 사용하기 쉬워졌어요.', 'We prioritize user-friendly interfaces in every product we ship.', '저희는 모든 제품에서 사용하기 쉬운 인터페이스를 우선시해요.', 'Older customers appreciate how user friendly the device is.', '연령대가 높은 고객들은 그 기기가 얼마나 쓰기 쉬운지를 좋아해요.', 'C1', 'technology', 2, 'simple interface', 4),
('idm_technology_C1_05', 'push the boundaries', '한계를 뛰어넘다', '경계를 밀다', '기존의 한계를 넘어 새로운 영역을 개척한다는 뜻이에요. 기술, 예술, 과학 모든 분야에서 써요.', 'This research team continues to push the boundaries of quantum computing.', '이 연구팀은 양자 컴퓨팅의 한계를 계속 뛰어넘고 있어요.', 'Their latest album pushes the boundaries of electronic music.', '그들의 최신 앨범은 일렉트로닉 음악의 한계를 뛰어넘어요.', 'We hire engineers who love to push the boundaries of what is possible.', '저희는 가능성의 한계를 뛰어넘기를 좋아하는 엔지니어를 채용해요.', 'C1', 'technology', 2, 'innovation lab', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ENVIRONMENT — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_environment_C1_01', 'reduce', 'emissions', 'reduce emissions', '배출을 줄이다', 'lower', '''lower''도 가능하지만, 환경 정책에서는 ''reduce emissions''가 표준 표현이에요. 모든 기후 보고서에 등장해요.', 'The new policy aims to reduce emissions by 40 percent by 2030.', '새 정책은 2030년까지 배출량을 40퍼센트 줄이는 것을 목표로 해요.', 'Electric buses help cities reduce emissions in dense urban areas.', '전기 버스는 도시가 인구 밀집 지역의 배출을 줄이는 데 도움이 돼요.', 'C1', 'environment', 2, 'factory emissions'),
('col_environment_C1_02', 'protect', 'wildlife', 'protect wildlife', '야생동물을 보호하다', 'save', '''save''는 위급한 구조의 뉘앙스, ''protect''는 지속적인 보호 활동이라는 뜻이에요. 보전 정책에서는 ''protect''가 표준이에요.', 'National parks were established to protect wildlife and natural habitats.', '국립공원은 야생동물과 자연 서식지를 보호하기 위해 설립됐어요.', 'Stronger laws are needed to protect wildlife from illegal trade.', '야생동물을 불법 거래로부터 보호하려면 더 강력한 법이 필요해요.', 'C1', 'environment', 2, 'wildlife reserve'),
('col_environment_C1_03', 'tackle', 'pollution', 'tackle pollution', '오염에 대처하다', 'stop', '오염 문제를 체계적으로 다룬다는 정책 표현이에요. ''stop''은 너무 단순해서 신문이나 보고서에 안 어울려요.', 'The city launched a bold plan to tackle air pollution.', '시는 대기 오염에 대처하기 위해 과감한 계획을 시작했어요.', 'Tackling plastic pollution requires global cooperation.', '플라스틱 오염에 대처하려면 글로벌 협력이 필요해요.', 'C1', 'environment', 2, 'polluted river'),
('col_environment_C1_04', 'adopt', 'sustainable practices', 'adopt sustainable practices', '지속 가능한 관행을 도입하다', 'use', '회사나 개인이 친환경 방식을 받아들인다는 격식 표현이에요. ESG 보고서에 자주 나와요.', 'More farms are adopting sustainable practices to preserve soil health.', '더 많은 농장이 토양 건강을 지키기 위해 지속 가능한 관행을 도입하고 있어요.', 'Companies that adopt sustainable practices often see long-term cost savings.', '지속 가능한 관행을 도입하는 회사는 장기적으로 비용 절감 효과를 보는 경우가 많아요.', 'C1', 'environment', 2, 'sustainable farm'),
('col_environment_C1_05', 'raise', 'awareness', 'raise awareness', '인식을 높이다', 'tell', '캠페인을 통해 사회적 관심을 끌어올린다는 표준 표현이에요. 비영리, 정책, 마케팅 모두에서 써요.', 'The documentary helped raise awareness of declining bee populations.', '그 다큐멘터리는 감소하는 벌 개체수에 대한 인식을 높이는 데 기여했어요.', 'School programs raise awareness about recycling among young children.', '학교 프로그램은 어린이들 사이에서 재활용에 대한 인식을 높여요.', 'C1', 'environment', 2, 'environmental campaign')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ENVIRONMENT — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_environment_C1_01', 'go green', '친환경적으로 바꾸다', '초록색이 되다', '생활이나 사업 방식을 친환경적으로 전환한다는 뜻이에요. 광고와 정책 캠페인에서 흔히 보여요.', 'Many small businesses are choosing to go green to attract eco-conscious customers.', '많은 소상공인이 친환경 의식이 있는 고객을 끌기 위해 친환경 전환을 선택하고 있어요.', 'Our office went green by switching to LED lighting and paperless workflows.', '저희 사무실은 LED 조명과 종이 없는 업무로 친환경 전환을 했어요.', 'Going green can also save money in the long run.', '친환경으로 전환하는 건 장기적으로 비용도 절약돼요.', 'C1', 'environment', 2, 'green leaves', 1),
('idm_environment_C1_02', 'carbon footprint', '탄소 발자국', '탄소 발자국', '개인이나 조직이 배출하는 온실가스의 총량을 가리켜요. ESG 보고서와 일상 대화 모두에서 표준이에요.', 'Flying less is one of the most effective ways to reduce your carbon footprint.', '비행을 줄이는 게 탄소 발자국을 줄이는 가장 효과적인 방법 중 하나예요.', 'The company published its carbon footprint for the first time this year.', '그 회사는 올해 처음으로 탄소 발자국을 공개했어요.', 'Eating locally grown food can lower your carbon footprint significantly.', '지역에서 생산된 음식을 먹으면 탄소 발자국을 크게 줄일 수 있어요.', 'C1', 'environment', 2, 'carbon footprint', 2),
('idm_environment_C1_03', 'tree-hugger', '환경운동가', '나무를 껴안는 사람', '환경 보호에 열성적인 사람을 가리키는 표현이에요. 때로 가볍게 비꼬는 뉘앙스가 있으니 친근한 자리에서 써요.', 'I used to think recycling was just for tree-huggers, but now I do it religiously.', '예전엔 재활용은 환경운동가들만 하는 거라 생각했지만, 지금은 철저히 하고 있어요.', 'He is not really a tree-hugger, but he cares deeply about clean water.', '그가 진짜 환경운동가는 아니지만, 깨끗한 물에 대해서는 깊이 신경 써요.', 'The brand is popular with tree-huggers and trend-followers alike.', '그 브랜드는 환경운동가와 유행을 따르는 사람 모두에게 인기가 있어요.', 'C1', 'environment', 2, 'tree hugging', 3),
('idm_environment_C1_04', 'a drop in the ocean', '새 발의 피', '바다의 물 한 방울', '필요한 양에 비해 너무 적은 양이라 큰 영향이 없다는 뜻이에요. 사회 문제나 정책 토론에 자주 등장해요.', 'Recycling one bottle is a drop in the ocean, but collective action matters.', '병 하나를 재활용하는 건 새 발의 피지만, 다 함께 행동하면 의미가 있어요.', 'The donation is appreciated, but it is a drop in the ocean compared to what is needed.', '기부는 감사하지만, 필요한 액수에 비하면 새 발의 피예요.', 'Individual efforts can feel like a drop in the ocean, yet they add up.', '개인의 노력은 새 발의 피처럼 느껴지지만, 모이면 커져요.', 'C1', 'environment', 2, 'water drop ocean', 4),
('idm_environment_C1_05', 'weather the storm', '난관을 견뎌내다', '폭풍을 견디다', '어려운 시기를 끝까지 버텨낸다는 뜻이에요. 기후 문제뿐 아니라 경제, 정치, 개인 일상에도 두루 써요.', 'Coastal communities have learned to weather the storm of increasingly extreme weather.', '해안 지역사회는 점점 극심해지는 기상의 난관을 견뎌내는 법을 배웠어요.', 'With careful planning, the firm weathered the storm of the recession.', '신중한 계획으로 그 회사는 불황의 난관을 견뎌냈어요.', 'We will weather the storm together as a team.', '우리는 한 팀으로 난관을 함께 견뎌낼 거예요.', 'C1', 'environment', 2, 'storm clouds', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEWS — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_news_C1_01', 'cover', 'story', 'cover a story', '기사를 취재하다', 'write', '''write''는 단순 작성이지만, ''cover''는 취재·보도 전체 과정을 의미하는 저널리즘 표준 동사예요.', 'She has covered every major election story for the past decade.', '그녀는 지난 10년간 주요 선거 기사를 모두 취재해 왔어요.', 'Foreign correspondents cover stories from conflict zones around the world.', '해외 특파원들은 전 세계 분쟁 지역에서 기사를 취재해요.', 'C1', 'news', 2, 'journalist reporting'),
('col_news_C1_02', 'leak', 'information', 'leak information', '정보를 누설하다', 'tell', '비공개 정보를 외부에 흘린다는 정확한 동사예요. ''tell''은 너무 일반적이라 보도 맥락에 안 맞아요.', 'An anonymous source leaked information about the upcoming merger.', '익명의 소식통이 다가오는 합병에 대한 정보를 누설했어요.', 'Employees who leak information may face legal consequences.', '정보를 누설한 직원은 법적 처벌을 받을 수 있어요.', 'C1', 'news', 2, 'leaked documents'),
('col_news_C1_03', 'issue', 'statement', 'issue a statement', '성명을 발표하다', 'say', '공식 입장을 정식으로 발표한다는 격식 표현이에요. 기업이나 정부 발표 기사에서 표준이에요.', 'The minister issued a statement denying any wrongdoing.', '장관은 어떠한 잘못도 없다고 부인하는 성명을 발표했어요.', 'The studio issued a statement late last night about the casting change.', '스튜디오는 어젯밤 늦게 캐스팅 변경에 대한 성명을 발표했어요.', 'C1', 'news', 2, 'press release'),
('col_news_C1_04', 'hold', 'press conference', 'hold a press conference', '기자회견을 열다', 'make', '기자회견을 ''열다''는 ''hold''가 표준이에요. ''make''는 영어에서 어색해요.', 'The mayor will hold a press conference at noon to address the crisis.', '시장은 위기를 다루기 위해 정오에 기자회견을 열 거예요.', 'They held a press conference to announce the partnership.', '그들은 파트너십을 발표하기 위해 기자회견을 열었어요.', 'C1', 'news', 2, 'press conference'),
('col_news_C1_05', 'verify', 'sources', 'verify sources', '출처를 확인하다', 'check', '''check''도 통하지만, ''verify''가 저널리즘과 정보 검증에서 표준 동사예요. 팩트체크 보도의 핵심 표현이에요.', 'Responsible journalists always verify sources before publishing.', '책임감 있는 기자는 보도 전에 항상 출처를 확인해요.', 'In the age of social media, it is harder than ever to verify sources.', '소셜 미디어 시대에는 출처를 확인하기가 그 어느 때보다 어려워요.', 'C1', 'news', 2, 'fact checking')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEWS — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_news_C1_01', 'breaking news', '속보', '깨지는 뉴스', '방금 들어온 중요한 뉴스를 가리켜요. TV 자막, 뉴스 헤드라인에서 항상 보이는 표준 표현이에요.', 'We interrupt this programme to bring you breaking news from the capital.', '수도에서 들어온 속보를 전해드리기 위해 방송을 중단합니다.', 'Breaking news alerts on my phone have become impossible to ignore.', '제 휴대폰의 속보 알림은 무시할 수 없게 됐어요.', 'The breaking news of the verdict spread across social media within minutes.', '평결 속보가 몇 분 만에 소셜 미디어 전반에 퍼졌어요.', 'C1', 'news', 2, 'breaking news banner', 1),
('idm_news_C1_02', 'in the headlines', '주요 뉴스에 오른', '헤드라인 안에 있는', '특정 주제가 언론의 주목을 받고 있다는 뜻이에요. 시사 토론과 보도 분석에서 자주 써요.', 'Climate change has been in the headlines all week following the new report.', '새 보고서 이후 기후 변화가 한 주 내내 주요 뉴스에 올라 있어요.', 'The scandal kept the senator in the headlines for months.', '그 스캔들로 그 상원의원은 몇 달간 주요 뉴스에 올랐어요.', 'Tech layoffs are back in the headlines this morning.', '오늘 아침 테크업계 정리해고가 다시 주요 뉴스에 올랐어요.', 'C1', 'news', 2, 'newspaper headlines', 2),
('idm_news_C1_03', 'off the record', '비보도를 전제로', '기록 밖에서', '말한 내용이 보도되지 않는 조건으로 한다는 저널리즘 용어예요. 인터뷰 협상에서 자주 등장해요.', 'Off the record, the official admitted that negotiations had stalled.', '비보도를 전제로, 그 관리는 협상이 교착 상태에 빠졌다고 인정했어요.', 'Can I tell you something off the record? I do not want this in your article.', '비보도를 전제로 하나 말해도 될까요? 기사에 나가지 않았으면 해요.', 'Several sources spoke off the record about internal disagreements.', '여러 소식통이 내부 갈등에 대해 비보도를 전제로 말했어요.', 'C1', 'news', 2, 'private interview', 3),
('idm_news_C1_04', 'scoop a story', '특종을 잡다', '이야기를 퍼올리다', '경쟁사보다 먼저 중요한 기사를 보도한다는 저널리즘 표현이에요. 명사 ''scoop''으로도 자주 써요.', 'The young reporter scooped the story of the year on her very first assignment.', '그 신입 기자는 첫 임무에서 올해의 특종을 잡았어요.', 'Independent outlets often scoop stories that big newspapers miss.', '독립 매체들은 대형 신문이 놓치는 기사를 종종 특종으로 잡아요.', 'They scooped the story by interviewing the whistleblower first.', '그들은 내부 고발자를 먼저 인터뷰해서 특종을 잡았어요.', 'C1', 'news', 2, 'reporter notebook', 4),
('idm_news_C1_05', 'a hot topic', '화제거리', '뜨거운 주제', '많은 사람들이 활발히 논의하고 있는 주제를 뜻해요. 토크쇼, 칼럼, 일상 대화 모두에서 자연스럽게 써요.', 'Artificial intelligence regulation has become a hot topic in policy circles.', '인공지능 규제는 정책 분야에서 화제거리가 됐어요.', 'Housing affordability is a hot topic ahead of the local elections.', '주거 비용 부담은 지방선거를 앞두고 화제거리예요.', 'Remote work remains a hot topic among HR professionals.', '원격 근무는 인사 담당자들 사이에서 여전히 화제거리예요.', 'C1', 'news', 2, 'discussion panel', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- SPORTS — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_sports_C1_01', 'win', 'match', 'win a match', '경기에서 이기다', 'beat', '''beat''는 상대를 이기는 것, ''win a match''는 시합 자체를 이긴다는 뜻이라 미묘하게 달라요. 경기 결과 표현의 기본이에요.', 'They need to win the next match to qualify for the finals.', '그들이 결승에 진출하려면 다음 경기에서 이겨야 해요.', 'She has won every match in straight sets this tournament.', '그녀는 이번 토너먼트에서 모든 경기를 스트레이트 세트로 이겼어요.', 'C1', 'sports', 2, 'tennis match'),
('col_sports_C1_02', 'make', 'comeback', 'make a comeback', '재기하다', 'do', '부진이나 부상 후 다시 활약한다는 표준 표현이에요. ''do a comeback''은 영어에서 어색해요.', 'The veteran striker is hoping to make a comeback next season.', '그 베테랑 공격수는 다음 시즌에 재기하기를 바라고 있어요.', 'After two surgeries, she made a remarkable comeback at the Olympics.', '두 차례 수술 후 그녀는 올림픽에서 놀라운 재기를 이뤄냈어요.', 'C1', 'sports', 2, 'athlete returning'),
('col_sports_C1_03', 'set', 'record', 'set a record', '기록을 세우다', 'make', '새로운 최고 기록을 만든다는 표준 동사 조합이에요. ''make a record''는 음반 만들 때 써서 헷갈리기 쉬워요.', 'He set a world record in the 200 meters at last summer''s championships.', '그는 지난여름 챔피언십에서 200미터 세계 기록을 세웠어요.', 'The team set a new club record for consecutive wins.', '그 팀은 연승 부문에서 새로운 구단 기록을 세웠어요.', 'C1', 'sports', 2, 'stadium record'),
('col_sports_C1_04', 'score', 'goal', 'score a goal', '골을 넣다', 'make', '축구, 하키 등에서 득점한다는 가장 기본적이고 정확한 동사예요. ''make a goal''은 어색해요.', 'He scored a stunning goal from outside the penalty box.', '그는 페널티 박스 밖에서 멋진 골을 넣었어요.', 'She has scored a goal in every match this season.', '그녀는 이번 시즌 모든 경기에서 골을 넣었어요.', 'C1', 'sports', 2, 'soccer goal'),
('col_sports_C1_05', 'claim', 'victory', 'claim victory', '승리를 거머쥐다', 'get', '경쟁 후 승리를 공식적으로 차지한다는 격식 있는 표현이에요. 스포츠 헤드라인의 단골이에요.', 'The underdogs claimed victory after a thrilling penalty shootout.', '약체 팀이 짜릿한 승부차기 끝에 승리를 거머쥐었어요.', 'She claimed victory in her debut tournament with surprising ease.', '그녀는 데뷔 토너먼트에서 의외로 수월하게 승리를 거머쥐었어요.', 'C1', 'sports', 2, 'victory celebration')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- SPORTS — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_sports_C1_01', 'level the playing field', '공평한 조건을 만들다', '경기장을 평평하게 하다', '모두에게 동등한 기회를 만든다는 뜻이에요. 스포츠뿐 아니라 비즈니스, 정책 토론에서도 자주 써요.', 'Salary caps were introduced to level the playing field between rich and small-market clubs.', '연봉 상한제는 부유한 구단과 소형 시장 구단 사이의 공평한 조건을 만들기 위해 도입됐어요.', 'New regulations aim to level the playing field for small startups.', '새 규제는 작은 스타트업에게 공평한 조건을 만들어주기 위한 거예요.', 'Scholarships help level the playing field for talented athletes from any background.', '장학금은 어떤 배경의 재능 있는 선수에게도 공평한 조건을 만들어줘요.', 'C1', 'sports', 2, 'soccer field', 1),
('idm_sports_C1_02', 'in the running', '유력 후보인', '달리기 안에 있는', '경쟁이나 선발에서 아직 유력한 후보 자리에 있다는 뜻이에요. 스포츠, 채용, 시상 등 폭넓게 써요.', 'Three teams are still in the running for the championship title.', '세 팀이 아직 우승 타이틀의 유력 후보로 남아 있어요.', 'She is in the running for the head coach position next season.', '그녀는 다음 시즌 수석 코치직의 유력 후보예요.', 'After this round, only two candidates remain in the running.', '이번 라운드 후 단 두 후보만 유력 후보로 남아 있어요.', 'C1', 'sports', 2, 'race competitors', 2),
('idm_sports_C1_03', 'down to the wire', '끝까지 가는 접전', '와이어 끝까지', '결과가 마지막 순간까지 결정되지 않는 접전이라는 뜻이에요. 스포츠 중계와 선거 보도 모두에서 자주 들려요.', 'The marathon went down to the wire, with the winner deciding it in the final 100 metres.', '마라톤은 끝까지 가는 접전이었고, 우승은 마지막 100미터에서 결정됐어요.', 'Negotiations went down to the wire before the deadline expired.', '협상은 마감 만료 직전까지 가는 접전이었어요.', 'Both teams are evenly matched — this will go down to the wire.', '두 팀이 막상막하예요. 끝까지 가는 접전이 될 거예요.', 'C1', 'sports', 2, 'finish line', 3),
('idm_sports_C1_04', 'on the ropes', '궁지에 몰린', '로프에 몰린', '권투에서 유래한 표현으로, 패배 직전의 위기 상황을 가리켜요. 스포츠와 비즈니스에서 모두 써요.', 'The defending champion was on the ropes after losing two consecutive sets.', '디펜딩 챔피언이 두 세트 연속 패배 후 궁지에 몰렸어요.', 'The startup was on the ropes until a last-minute investor stepped in.', '그 스타트업은 막판에 투자자가 등장하기 전까지 궁지에 몰려 있었어요.', 'Critics suggest the manager is on the ropes after another disappointing result.', '비평가들은 또 다른 실망스러운 결과 후 그 감독이 궁지에 몰렸다고 봐요.', 'C1', 'sports', 2, 'boxing ring', 4),
('idm_sports_C1_05', 'the home stretch', '막바지', '집까지의 마지막 직선 구간', '경마에서 유래한 표현으로, 일이나 시즌의 마지막 단계를 뜻해요. 스포츠뿐 아니라 프로젝트 마감에도 자주 써요.', 'We are in the home stretch of the regular season, with playoffs just weeks away.', '플레이오프가 불과 몇 주 앞이고, 정규 시즌의 막바지에 와 있어요.', 'The project is in the home stretch — just one more week of testing left.', '프로젝트는 막바지예요. 테스트가 일주일만 남았어요.', 'Athletes often peak as they enter the home stretch of training.', '선수들은 훈련의 막바지에 들어설 때 최고조에 이르는 경우가 많아요.', 'C1', 'sports', 2, 'race finish line', 5)
ON CONFLICT (id) DO NOTHING;
