-- ============================================================
-- C1-level Collocations and Idioms — Batch D
-- Topics: emotion, culture, humanities, presentation, greeting
-- 5 collocations + 5 idioms per topic = 50 total entries
-- Priority = 2 (C1)
-- ============================================================

-- ============================================================
-- EMOTION — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_emotion_C1_01', 'vent', 'frustration', 'vent frustration', '답답함을 토로하다', 'say', '쌓인 부정적 감정을 말이나 행동으로 풀어낸다는 뜻이에요. 직장 상담이나 인터뷰에서 자주 쓰는 격식 표현이에요.', 'She needed a trusted colleague to vent her frustration after the meeting.', '그녀는 회의 후 답답함을 토로할 믿을 만한 동료가 필요했어요.', 'Employees often vent their frustration in anonymous surveys.', '직원들은 익명 설문에서 답답함을 토로하곤 해요.', 'C1', 'emotion', 2, 'person venting'),
('col_emotion_C1_02', 'express', 'gratitude', 'express gratitude', '감사를 표하다', 'say', '감사한 마음을 격식 있게 전한다는 뜻이에요. ''say thanks''보다 훨씬 정중하고 글쓰기에서 표준 표현이에요.', 'He took a moment to express his gratitude to the entire research team.', '그는 잠시 시간을 내어 연구팀 전체에 감사를 표했어요.', 'In her acceptance speech, she expressed gratitude to her mentors.', '수상 소감에서 그녀는 멘토들에게 감사를 표했어요.', 'C1', 'emotion', 2, 'thank you note'),
('col_emotion_C1_03', 'hide', 'disappointment', 'hide disappointment', '실망감을 감추다', 'cover', '속으로는 실망했지만 겉으로는 드러내지 않으려 한다는 뜻이에요. 인터뷰, 협상, 가족 대화에서 자주 보여요.', 'She tried to hide her disappointment when the promotion went to someone else.', '승진이 다른 사람에게 갔을 때 그녀는 실망감을 감추려 했어요.', 'He could barely hide his disappointment at the verdict.', '그는 판결에 대한 실망감을 거의 감추지 못했어요.', 'C1', 'emotion', 2, 'sad face'),
('col_emotion_C1_04', 'show', 'empathy', 'show empathy', '공감을 보이다', 'feel', '단순히 느끼는 것을 넘어 상대에게 공감하는 태도를 드러낸다는 뜻이에요. 리더십, 상담, 의료 현장에서 핵심 표현이에요.', 'Effective managers show empathy without losing their professional edge.', '유능한 관리자는 전문성을 잃지 않으면서 공감을 보여요.', 'Nurses are trained to show empathy under stressful conditions.', '간호사들은 스트레스 상황에서도 공감을 보이도록 훈련받아요.', 'C1', 'emotion', 2, 'caring conversation'),
('col_emotion_C1_05', 'bottle up', 'emotions', 'bottle up emotions', '감정을 억누르다', 'keep', '감정을 표현하지 않고 속에 쌓아둔다는 뜻이에요. 심리학, 자기계발 글에서 표준으로 쓰는 표현이에요.', 'Bottling up your emotions for years can take a serious toll on your health.', '수년간 감정을 억누르면 건강에 큰 타격을 줄 수 있어요.', 'He has a tendency to bottle up his emotions instead of talking them through.', '그는 감정을 털어놓기보다 억누르는 경향이 있어요.', 'C1', 'emotion', 2, 'bottle silhouette')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- EMOTION — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_emotion_C1_01', 'wear your heart on your sleeve', '감정을 숨김없이 드러내다', '심장을 소매 위에 달다', '자기 감정을 솔직하게 다 보여준다는 뜻이에요. 칭찬과 비판 모두 가능하니 상황에 맞게 써야 해요.', 'She wears her heart on her sleeve, which makes her a wonderfully sincere friend.', '그녀는 감정을 숨김없이 드러내는데, 그래서 정말 진솔한 친구예요.', 'In leadership, wearing your heart on your sleeve can be both a strength and a vulnerability.', '리더십에서 감정을 그대로 드러내는 건 강점이자 약점이 될 수 있어요.', 'He is not the type to wear his heart on his sleeve at work.', '그는 직장에서 감정을 그대로 드러내는 타입은 아니에요.', 'C1', 'emotion', 2, 'heart sleeve', 1),
('idm_emotion_C1_02', 'have a heart of gold', '마음이 따뜻하다', '황금의 심장을 가지다', '겉모습과 상관없이 본성이 한없이 친절하고 너그럽다는 뜻이에요. 사람을 칭찬할 때 격식 자리에서도 자연스러워요.', 'Despite his gruff exterior, he has a heart of gold.', '그는 무뚝뚝해 보이지만 마음이 따뜻해요.', 'My grandmother had a heart of gold and never turned anyone away.', '저희 할머니는 마음이 따뜻해서 누구도 외면하지 않으셨어요.', 'Volunteers with a heart of gold sustain the entire organization.', '마음이 따뜻한 자원봉사자들이 조직 전체를 지탱해요.', 'C1', 'emotion', 2, 'gold heart', 2),
('idm_emotion_C1_03', 'head over heels', '푹 빠지다', '머리가 발꿈치 위로', '주로 사랑에 완전히 빠진 상태를 가리키는 표현이에요. 일이나 취미에 푹 빠졌다고 비유적으로도 써요.', 'They have been head over heels in love since their college years.', '그들은 대학 시절부터 서로에게 푹 빠져 있어요.', 'She fell head over heels for the city of Lisbon during her sabbatical.', '그녀는 안식년 동안 리스본이라는 도시에 푹 빠졌어요.', 'He is head over heels about his new research topic.', '그는 새 연구 주제에 푹 빠져 있어요.', 'C1', 'emotion', 2, 'couple in love', 3),
('idm_emotion_C1_04', 'down in the dumps', '의기소침하다', '쓰레기 더미 안에 있는', '특별한 이유 없이 우울하거나 기운이 없다는 뜻이에요. 친한 동료나 가족과의 대화에서 자연스럽게 써요.', 'He has been down in the dumps ever since the project was cancelled.', '그는 그 프로젝트가 취소된 이후 계속 의기소침해 있어요.', 'Rainy weeks always leave her down in the dumps.', '비가 오는 주가 길어지면 그녀는 항상 의기소침해져요.', 'Why are you so down in the dumps today?', '오늘 왜 그렇게 기운이 없어요?', 'C1', 'emotion', 2, 'gloomy person', 4),
('idm_emotion_C1_05', 'on cloud nine', '하늘을 날 듯 기쁘다', '아홉 번째 구름 위에', '아주 행복하고 신이 난 상태를 묘사하는 표현이에요. 좋은 소식을 전할 때 격식과 비격식 모두에서 자연스러워요.', 'She has been on cloud nine since her paper was accepted by the journal.', '논문이 학술지에 채택된 이후 그녀는 하늘을 날 듯 기뻐하고 있어요.', 'After the engagement, they were both on cloud nine.', '약혼 후 두 사람은 모두 하늘을 날 듯 기뻤어요.', 'Winning the contract put the whole team on cloud nine.', '계약을 따낸 일로 팀 전체가 하늘을 날 듯 기뻐했어요.', 'C1', 'emotion', 2, 'clouds sky', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- CULTURE — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_culture_C1_01', 'embrace', 'diversity', 'embrace diversity', '다양성을 포용하다', 'accept', '단순히 받아들이는 것이 아니라 적극적으로 환영하고 가치를 둔다는 뜻이에요. 조직 가치 선언문에 자주 등장해요.', 'The university actively embraces diversity in its student body and faculty.', '그 대학은 학생과 교수진의 다양성을 적극적으로 포용해요.', 'Modern workplaces must embrace diversity to remain competitive.', '현대 직장은 경쟁력을 유지하려면 다양성을 포용해야 해요.', 'C1', 'culture', 2, 'diverse group'),
('col_culture_C1_02', 'preserve', 'heritage', 'preserve heritage', '유산을 보존하다', 'keep', '문화적, 역사적 가치를 후대에 전하기 위해 지킨다는 격식 표현이에요. UNESCO 문서에서 표준이에요.', 'The foundation works tirelessly to preserve the heritage of indigenous communities.', '그 재단은 원주민 공동체의 유산을 보존하기 위해 끊임없이 노력해요.', 'Local artisans help preserve a heritage that spans generations.', '지역 장인들은 여러 세대에 걸친 유산을 보존하는 데 기여해요.', 'C1', 'culture', 2, 'historic building'),
('col_culture_C1_03', 'challenge', 'stereotypes', 'challenge stereotypes', '고정관념에 도전하다', 'change', '기존의 편견이나 고정관념에 정면으로 맞선다는 뜻이에요. 사회 비평, 광고 캠페인에서 자주 보여요.', 'Her documentary boldly challenges stereotypes about rural communities.', '그녀의 다큐멘터리는 농촌 공동체에 대한 고정관념에 과감히 도전해요.', 'The campaign was designed to challenge stereotypes about ageing.', '그 캠페인은 노화에 대한 고정관념에 도전하기 위해 기획됐어요.', 'C1', 'culture', 2, 'breaking barriers'),
('col_culture_C1_04', 'appreciate', 'art', 'appreciate art', '예술을 감상하다', 'like', '단순한 호감을 넘어 가치를 이해하며 감상한다는 격식 표현이에요. 미술관 안내문이나 평론에 어울려요.', 'Learning to appreciate art often begins with understanding its historical context.', '예술을 감상하는 법은 보통 그 역사적 맥락을 이해하는 데서 시작해요.', 'She has cultivated an ability to appreciate art across many periods.', '그녀는 다양한 시대의 예술을 감상할 수 있는 안목을 길렀어요.', 'C1', 'culture', 2, 'art gallery'),
('col_culture_C1_05', 'celebrate', 'traditions', 'celebrate traditions', '전통을 기리다', 'do', '문화 전통을 의식적으로 기념하고 가치를 인정한다는 뜻이에요. 명절, 축제 보도에서 표준 표현이에요.', 'The festival celebrates the traditions of the Andean highlands.', '그 축제는 안데스 고원의 전통을 기려요.', 'Families gather every autumn to celebrate the traditions of Chuseok.', '가족들은 매년 가을 추석의 전통을 기리기 위해 모여요.', 'C1', 'culture', 2, 'traditional festival')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- CULTURE — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_culture_C1_01', 'when in Rome', '로마에서는 로마법을 따르라', '로마에 있을 때는', '낯선 곳에 가면 그곳의 관습을 따르라는 뜻이에요. 격식 자리에서도 자연스럽게 쓰는 고전적 표현이에요.', 'I do not usually eat raw fish, but when in Rome.', '저는 보통 회를 먹지 않지만, 로마에서는 로마법을 따라야죠.', 'She bowed deeply at the meeting — when in Rome, after all.', '그녀는 회의에서 깊이 인사했어요. 로마에서는 로마법을 따라야 하니까요.', 'When in Rome, you take off your shoes before entering a Korean home.', '한국 가정에 들어갈 때는 신발을 벗어야 해요. 그게 그곳의 법이니까요.', 'C1', 'culture', 2, 'rome colosseum', 1),
('idm_culture_C1_02', 'a melting pot', '여러 문화가 섞인 곳', '녹는 냄비', '다양한 인종, 문화, 배경이 한곳에 어우러진 공간을 가리켜요. 도시나 국가를 설명하는 격식 표현이에요.', 'New York has long been described as a melting pot of cultures.', '뉴욕은 오랫동안 여러 문화가 섞인 곳으로 묘사돼 왔어요.', 'The campus is a true melting pot, with students from over eighty countries.', '그 캠퍼스는 80개국 이상에서 온 학생들로 이루어진 진정한 용광로예요.', 'Their neighbourhood became a melting pot after the 1990s.', '그들의 동네는 1990년대 이후 여러 문화가 섞인 곳이 됐어요.', 'C1', 'culture', 2, 'diverse city', 2),
('idm_culture_C1_03', 'a cultural icon', '문화적 상징', '문화적 우상', '특정 문화나 시대를 대표하는 인물이나 작품을 가리켜요. 평론, 부고, 인터뷰에서 표준 표현이에요.', 'Audrey Hepburn remains a cultural icon decades after her death.', '오드리 헵번은 사후 수십 년이 지난 지금도 문화적 상징으로 남아 있어요.', 'The film quickly became a cultural icon of the 1980s.', '그 영화는 1980년대의 문화적 상징이 됐어요.', 'For many Koreans, that drama is now a cultural icon.', '많은 한국인에게 그 드라마는 이제 문화적 상징이에요.', 'C1', 'culture', 2, 'famous portrait', 3),
('idm_culture_C1_04', 'stand the test of time', '세월의 시험을 견디다', '시간의 시험을 견디다', '오랜 시간이 지나도 가치나 인기가 유지된다는 뜻이에요. 예술, 디자인, 사상 평론에서 자주 써요.', 'Few literary works truly stand the test of time.', '진정으로 세월의 시험을 견디는 문학 작품은 드물어요.', 'Their minimalist design has stood the test of time.', '그들의 미니멀한 디자인은 세월의 시험을 견뎌왔어요.', 'Whether this trend will stand the test of time remains to be seen.', '이 트렌드가 세월을 견딜지는 두고 봐야 해요.', 'C1', 'culture', 2, 'old monument', 4),
('idm_culture_C1_05', 'lost in translation', '번역 과정에서 의미가 사라진', '번역 안에서 길을 잃은', '한 언어에서 다른 언어로 옮기는 과정에서 미묘한 의미가 빠진다는 뜻이에요. 비유적으로 문화 간 소통에서도 자주 써요.', 'Much of the original poem''s rhythm is lost in translation.', '그 시 원작의 운율은 번역 과정에서 많이 사라져요.', 'His joke seemed to get lost in translation during the keynote.', '기조 연설에서 그의 농담은 번역 과정에서 의미가 사라진 듯했어요.', 'Subtle cultural cues are often lost in translation.', '미묘한 문화적 단서는 번역 과정에서 종종 사라져요.', 'C1', 'culture', 2, 'translation books', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- HUMANITIES — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_humanities_C1_01', 'explore', 'themes', 'explore themes', '주제를 탐구하다', 'see', '문학, 영화, 예술 작품의 주제를 깊이 파헤친다는 격식 표현이에요. 비평이나 학술 글의 표준이에요.', 'The novel explores themes of memory, loss, and identity.', '그 소설은 기억, 상실, 정체성이라는 주제를 탐구해요.', 'Her latest essay explores themes that recur throughout postwar literature.', '그녀의 최신 에세이는 전후 문학 전반에 반복되는 주제를 탐구해요.', 'C1', 'humanities', 2, 'open book'),
('col_humanities_C1_02', 'analyze', 'texts', 'analyze texts', '텍스트를 분석하다', 'read', '텍스트의 구조, 의미, 맥락을 비판적으로 살핀다는 학문적 표현이에요. 인문학 강의실의 핵심 동사예요.', 'Students learn to analyze texts using a range of critical frameworks.', '학생들은 다양한 비평 틀을 활용해 텍스트를 분석하는 법을 배워요.', 'She analyzed the texts side by side to trace the author''s evolution.', '그녀는 작가의 변천을 추적하기 위해 텍스트들을 나란히 분석했어요.', 'C1', 'humanities', 2, 'literary analysis'),
('col_humanities_C1_03', 'trace', 'origins', 'trace the origins', '기원을 추적하다', 'find', '어떤 개념이나 관습의 역사적 출처를 거슬러 올라간다는 뜻이에요. 역사학, 어원학에서 자주 써요.', 'The book traces the origins of modern democracy to ancient Athens.', '그 책은 현대 민주주의의 기원을 고대 아테네까지 추적해요.', 'Linguists trace the origins of the word to a medieval Latin root.', '언어학자들은 그 단어의 기원을 중세 라틴어 어근까지 추적해요.', 'C1', 'humanities', 2, 'ancient ruins'),
('col_humanities_C1_04', 'draw', 'parallels', 'draw parallels', '유사점을 끌어내다', 'find', '서로 다른 두 가지 사이의 닮은 점을 짚어낸다는 격식 표현이에요. 비교 분석 글에서 표준이에요.', 'The essay draws parallels between Roman and modern American politics.', '그 에세이는 로마와 현대 미국 정치 사이의 유사점을 끌어내요.', 'Critics have drawn parallels between the two filmmakers'' visual styles.', '비평가들은 두 영화감독의 시각적 스타일 사이에서 유사점을 끌어냈어요.', 'C1', 'humanities', 2, 'parallel lines'),
('col_humanities_C1_05', 'challenge', 'interpretations', 'challenge interpretations', '해석에 이의를 제기하다', 'change', '기존의 학설이나 해석에 비판적으로 도전한다는 뜻이에요. 학술 논문 서론에서 자주 보이는 표현이에요.', 'Her dissertation challenges long-standing interpretations of the text.', '그녀의 박사 논문은 그 텍스트에 대한 오랜 해석에 이의를 제기해요.', 'Newly discovered manuscripts have challenged earlier interpretations of the war.', '새로 발견된 사본들은 그 전쟁에 대한 기존 해석에 이의를 제기해 왔어요.', 'C1', 'humanities', 2, 'manuscript study')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- HUMANITIES — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_humanities_C1_01', 'ivory tower', '상아탑', '상아로 된 탑', '현실과 동떨어진 학문 세계나 사람을 비유하는 표현이에요. 학계 비판이나 자조적 농담에 자주 써요.', 'Critics accuse the professor of writing from an ivory tower.', '비평가들은 그 교수가 상아탑에서 글을 쓴다고 비판해요.', 'Policy must connect with practice, not remain in the ivory tower.', '정책은 상아탑에 머물지 말고 현장과 연결돼야 해요.', 'She left the ivory tower to work in community education.', '그녀는 상아탑을 떠나 지역사회 교육 분야로 옮겼어요.', 'C1', 'humanities', 2, 'university tower', 1),
('idm_humanities_C1_02', 'food for thought', '생각할 거리', '생각을 위한 음식', '곱씹어 볼 만한 흥미로운 주제나 의견을 가리키는 표현이에요. 강연, 토론 후기에 자연스럽게 써요.', 'His closing remarks gave us plenty of food for thought.', '그의 마무리 발언은 우리에게 생각할 거리를 많이 줬어요.', 'The article offers genuine food for thought on the future of higher education.', '그 기사는 고등교육의 미래에 대해 진정한 생각할 거리를 제공해요.', 'Here is some food for thought before our next meeting.', '다음 회의 전에 생각해 볼 거리를 좀 드릴게요.', 'C1', 'humanities', 2, 'thinking person', 2),
('idm_humanities_C1_03', 'in a nutshell', '한마디로 말하면', '견과 껍데기 안에', '복잡한 내용을 아주 간결하게 요약할 때 쓰는 표현이에요. 발표, 보고서, 학술 대화에서 모두 자연스러워요.', 'In a nutshell, the author argues that language shapes thought.', '한마디로 말하면, 저자는 언어가 사고를 형성한다고 주장해요.', 'The reform, in a nutshell, prioritizes accessibility over prestige.', '그 개혁은 한마디로 명성보다 접근성을 우선시해요.', 'In a nutshell, we need more time and more data.', '한마디로 우리는 더 많은 시간과 데이터가 필요해요.', 'C1', 'humanities', 2, 'walnut shell', 3),
('idm_humanities_C1_04', 'the gist of it', '요지', '그것의 핵심', '글이나 말의 핵심 뜻을 가리키는 표현이에요. 회의에서 ''요점은 이거예요''라고 정리할 때 자주 써요.', 'I have not read the full report, but I got the gist of it.', '보고서를 다 읽지는 않았지만, 요지는 파악했어요.', 'Could you give me the gist of it before the call?', '통화 전에 요지만 간단히 알려 주실 수 있어요?', 'The gist of it is that we need to revise our approach.', '요지는 우리가 접근 방식을 수정해야 한다는 거예요.', 'C1', 'humanities', 2, 'summary notes', 4),
('idm_humanities_C1_05', 'to make a long story short', '간단히 말하자면', '긴 이야기를 짧게 만들자면', '복잡한 배경 설명을 건너뛰고 결론으로 바로 가겠다는 신호예요. 회의나 발표 도입부에 자주 써요.', 'To make a long story short, the experiment ultimately succeeded.', '간단히 말하자면, 그 실험은 결국 성공했어요.', 'To make a long story short, the merger was called off at the last minute.', '간단히 말하자면, 그 합병은 막판에 무산됐어요.', 'To make a long story short, we are going back to the original design.', '간단히 말하자면, 우리는 원래 디자인으로 돌아가요.', 'C1', 'humanities', 2, 'long scroll', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- PRESENTATION — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_presentation_C1_01', 'deliver', 'speech', 'deliver a speech', '연설을 하다', 'say', '준비된 연설을 청중 앞에서 전달한다는 격식 표현이에요. ''give''도 가능하지만 ''deliver''가 더 전문적이에요.', 'She delivered a powerful keynote speech at the global summit.', '그녀는 글로벌 정상회의에서 강력한 기조연설을 했어요.', 'He has been invited to deliver a commencement speech at his alma mater.', '그는 모교에서 졸업 연설을 해 달라는 초청을 받았어요.', 'C1', 'presentation', 2, 'speaker podium'),
('col_presentation_C1_02', 'engage', 'audience', 'engage the audience', '청중을 사로잡다', 'interest', '청중의 주의를 끌고 적극적으로 참여시킨다는 뜻이에요. 발표 코칭에서 가장 자주 쓰는 표현 중 하나예요.', 'A great presenter knows how to engage the audience from the first slide.', '훌륭한 발표자는 첫 슬라이드부터 청중을 사로잡는 법을 알아요.', 'She engaged the audience by opening with a personal story.', '그녀는 개인적인 이야기로 시작하며 청중을 사로잡았어요.', 'C1', 'presentation', 2, 'engaged crowd'),
('col_presentation_C1_03', 'highlight', 'key points', 'highlight key points', '핵심을 강조하다', 'show', '발표나 글의 중요한 부분을 두드러지게 보여준다는 뜻이에요. 비즈니스 미팅과 학회 발표에서 표준이에요.', 'Let me highlight the key points before we open the floor for questions.', '질의응답을 열기 전에 핵심을 강조해 드릴게요.', 'The executive summary highlights the key points of the report.', '요약본은 보고서의 핵심을 강조해요.', 'C1', 'presentation', 2, 'highlighted text'),
('col_presentation_C1_04', 'field', 'question', 'field a question', '질문에 답하다', 'answer', '청중의 질문을 능숙하게 받아 답한다는 격식 표현이에요. 기자회견과 Q&A 세션에서 표준이에요.', 'The CEO fielded a difficult question about layoffs with composure.', 'CEO는 정리해고에 대한 까다로운 질문에 침착하게 답했어요.', 'She skillfully fielded questions from skeptical investors.', '그녀는 회의적인 투자자들의 질문에 능숙하게 답했어요.', 'C1', 'presentation', 2, 'press conference'),
('col_presentation_C1_05', 'wrap up', 'talk', 'wrap up a talk', '발표를 마무리하다', 'finish', '발표나 강연을 깔끔하게 마무리한다는 뜻이에요. 격식 자리에서도 자연스러운 비즈니스 표현이에요.', 'Let me wrap up this talk with three actionable takeaways.', '실행 가능한 시사점 세 가지로 이 발표를 마무리할게요.', 'She wrapped up her talk by inviting the audience to continue the conversation online.', '그녀는 청중에게 온라인에서 대화를 이어가자고 제안하며 발표를 마무리했어요.', 'C1', 'presentation', 2, 'closing slide')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- PRESENTATION — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_presentation_C1_01', 'break the ice', '어색한 분위기를 풀다', '얼음을 깨다', '처음 만난 사람들 사이의 어색함을 없애기 위해 가볍게 시작한다는 뜻이에요. 발표나 워크숍 오프닝의 핵심 표현이에요.', 'She broke the ice with a witty anecdote about her morning commute.', '그녀는 출근길 일화로 재치 있게 어색한 분위기를 풀었어요.', 'A quick poll is a useful way to break the ice with a new audience.', '간단한 설문은 새 청중과의 어색한 분위기를 푸는 좋은 방법이에요.', 'He broke the ice by asking everyone to introduce themselves in one word.', '그는 모두에게 한 단어로 자기소개를 하라며 어색한 분위기를 풀었어요.', 'C1', 'presentation', 2, 'ice breaking', 1),
('idm_presentation_C1_02', 'get to the point', '본론으로 들어가다', '요점에 도달하다', '잡담이나 빙빙 도는 설명을 그만두고 핵심으로 가자는 뜻이에요. 회의를 효율적으로 진행할 때 자주 써요.', 'We are short on time, so let me get to the point.', '시간이 부족하니 본론으로 바로 들어갈게요.', 'Could you get to the point? We need a decision by noon.', '본론으로 들어가 주실래요? 정오까지 결정해야 해요.', 'A good presenter gets to the point within the first two minutes.', '훌륭한 발표자는 첫 2분 안에 본론으로 들어가요.', 'C1', 'presentation', 2, 'arrow target', 2),
('idm_presentation_C1_03', 'think on your feet', '즉석에서 대응하다', '발 위에서 생각하다', '준비되지 않은 상황에서도 빠르고 유연하게 대처한다는 뜻이에요. 면접, 협상, Q&A에서 핵심 역량이에요.', 'A skilled moderator has to think on their feet during live Q&A.', '능숙한 사회자는 라이브 Q&A에서 즉석에서 대응할 줄 알아야 해요.', 'She thinks on her feet better than anyone I have worked with.', '그녀는 제가 함께 일해 본 누구보다 즉석 대응을 잘해요.', 'Sales reps are trained to think on their feet under pressure.', '영업 직원들은 압박 속에서 즉석 대응하도록 훈련받아요.', 'C1', 'presentation', 2, 'quick response', 3),
('idm_presentation_C1_04', 'cut to the chase', '핵심으로 바로 가다', '추격 장면으로 자르다', '서두를 건너뛰고 결론이나 본론으로 바로 가자는 뜻이에요. ''get to the point''보다 약간 더 단호한 뉘앙스예요.', 'Let me cut to the chase: we need to rethink the launch date.', '핵심으로 바로 갈게요. 출시일을 다시 생각해야 해요.', 'Investors appreciate it when founders cut to the chase.', '투자자들은 창업자가 핵심으로 바로 가는 것을 좋아해요.', 'Cutting to the chase, the proposal lacks a clear budget.', '핵심으로 가자면, 그 제안서에는 명확한 예산이 없어요.', 'C1', 'presentation', 2, 'fast motion', 4),
('idm_presentation_C1_05', 'lay it on the line', '솔직하게 말하다', '그것을 선 위에 놓다', '주저하지 않고 분명하고 솔직하게 의견이나 사실을 밝힌다는 뜻이에요. 진솔한 피드백이나 경고 자리에 어울려요.', 'Let me lay it on the line — the current strategy is not working.', '솔직하게 말씀드릴게요. 현재 전략은 효과가 없어요.', 'She laid it on the line during the performance review.', '그녀는 성과 평가에서 솔직하게 말했어요.', 'It is time to lay it on the line with the client about the delay.', '지연에 대해 고객에게 솔직히 말할 때예요.', 'C1', 'presentation', 2, 'honest conversation', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- GREETING — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_greeting_C1_01', 'exchange', 'pleasantries', 'exchange pleasantries', '인사말을 주고받다', 'say', '본론에 들어가기 전에 격식 있는 가벼운 인사말을 주고받는다는 뜻이에요. 비즈니스 미팅 도입부 표준 표현이에요.', 'The two delegations exchanged pleasantries before the negotiations began.', '두 대표단은 협상이 시작되기 전에 인사말을 주고받았어요.', 'After exchanging pleasantries, we got straight to the agenda.', '인사말을 주고받은 뒤 우리는 곧바로 안건으로 들어갔어요.', 'C1', 'greeting', 2, 'handshake meeting'),
('col_greeting_C1_02', 'make', 'small talk', 'make small talk', '잡담을 나누다', 'do', '날씨나 가벼운 주제로 짧게 대화한다는 뜻이에요. 네트워킹 자리에서 가장 자주 쓰는 격식 표현이에요.', 'He is excellent at making small talk with clients before formal meetings.', '그는 공식 회의 전에 고객들과 잡담을 나누는 데 능숙해요.', 'Making small talk in a second language can feel surprisingly demanding.', '제2외국어로 잡담을 나누는 일은 의외로 부담스러울 수 있어요.', 'C1', 'greeting', 2, 'networking event'),
('col_greeting_C1_03', 'extend', 'welcome', 'extend a welcome', '환영을 표하다', 'give', '공식적이고 따뜻한 환영의 뜻을 전한다는 격식 표현이에요. 행사 개회사에서 표준이에요.', 'On behalf of the board, I would like to extend a warm welcome to our guests.', '이사회를 대표해 손님 여러분께 따뜻한 환영을 표하고 싶어요.', 'The mayor extended a welcome to the visiting delegation.', '시장은 방문단에게 환영을 표했어요.', 'C1', 'greeting', 2, 'welcome ceremony'),
('col_greeting_C1_04', 'introduce', 'yourself', 'introduce yourself', '자기소개를 하다', 'tell', '이름과 소속을 격식 있게 밝힌다는 표현이에요. 면접, 회의, 워크숍에서 표준이에요.', 'Please introduce yourself briefly so the panel can get to know you.', '심사위원단이 알 수 있도록 자기소개를 간단히 해 주세요.', 'She introduced herself as the new head of research.', '그녀는 신임 연구 책임자로 자기소개를 했어요.', 'C1', 'greeting', 2, 'introduction badge'),
('col_greeting_C1_05', 'shake', 'hands', 'shake hands', '악수하다', 'do', '인사로 손을 맞잡는다는 표준 표현이에요. ''do handshake'' 같은 표현은 어색하니 ''shake hands''로 기억하세요.', 'It is customary to shake hands firmly during a business introduction.', '비즈니스 자리에서 자기소개를 할 때는 손을 단단히 잡고 악수하는 게 관례예요.', 'They shook hands warmly after signing the agreement.', '그들은 합의서에 서명한 뒤 따뜻하게 악수했어요.', 'C1', 'greeting', 2, 'handshake business')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- GREETING — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_greeting_C1_01', 'speak of the devil', '호랑이도 제 말하면 온다', '악마의 이야기를 하다', '방금 화제에 올린 사람이 우연히 나타났을 때 쓰는 표현이에요. 비격식이지만 직장에서도 자연스럽게 통해요.', 'Speak of the devil — I was just telling them about your new project.', '호랑이도 제 말하면 온다더니, 마침 새 프로젝트 얘기를 하고 있었어요.', 'Speak of the devil, here she comes now.', '호랑이도 제 말하면 온다더니, 마침 그녀가 오네요.', 'Well, speak of the devil, look who just joined the call.', '호랑이도 제 말하면 온다더니, 통화에 누가 들어왔는지 보세요.', 'C1', 'greeting', 2, 'surprise meeting', 1),
('idm_greeting_C1_02', 'long time no see', '오랜만이에요', '오랜 시간 보지 못함', '오랜만에 만난 사람에게 반갑게 건네는 표현이에요. 일상과 비즈니스 자리 모두에서 자연스럽게 써요.', 'Long time no see — how have you been since the conference?', '오랜만이에요. 학회 이후로 어떻게 지내셨어요?', 'Long time no see! You have not changed a bit.', '오랜만이에요! 하나도 안 변하셨네요.', 'Long time no see — last time was the Tokyo office, I believe.', '오랜만이에요. 마지막으로 뵌 게 도쿄 사무소였던 것 같아요.', 'C1', 'greeting', 2, 'reunion hug', 2),
('idm_greeting_C1_03', 'what brings you here', '여긴 어쩐 일이세요', '무엇이 당신을 여기 데려왔나요', '예상치 못한 장소에서 만난 사람에게 격식 있게 묻는 표현이에요. 친근하면서도 정중한 느낌이에요.', 'What brings you here on a Tuesday afternoon?', '화요일 오후에 여긴 어쩐 일이세요?', 'I did not expect to see you at the gallery — what brings you here?', '여기 미술관에서 뵐 줄 몰랐어요. 어쩐 일이세요?', 'What brings you here all the way from Busan?', '부산에서 여기까지 어쩐 일이세요?', 'C1', 'greeting', 2, 'unexpected meeting', 3),
('idm_greeting_C1_04', 'make yourself at home', '편하게 계세요', '집에 있는 것처럼 하세요', '손님에게 편안히 있으라고 권하는 정중한 표현이에요. 가정뿐 아니라 사무실, 호텔, 워크숍 자리에서도 자연스러워요.', 'Please come in and make yourself at home — the others will arrive shortly.', '들어오셔서 편하게 계세요. 다른 분들도 곧 오실 거예요.', 'Help yourself to tea and make yourself at home.', '차 드시고 편하게 계세요.', 'Welcome to the team — make yourself at home in the lounge.', '팀에 오신 걸 환영해요. 라운지에서 편하게 계세요.', 'C1', 'greeting', 2, 'cozy living room', 4),
('idm_greeting_C1_05', 'nice to put a face to the name', '실제로 뵙게 되어 반가워요', '이름에 얼굴을 붙여서 좋아요', '이메일이나 전화로만 알던 사람을 처음 직접 만났을 때 쓰는 격식 표현이에요. 비즈니스 자리에서 매우 자연스러워요.', 'Nice to finally put a face to the name after all those emails.', '그동안 이메일만 주고받다가 드디어 실제로 뵙게 되어 반가워요.', 'It is great to put a face to the name — your reputation precedes you.', '실제로 뵙게 되어 정말 반가워요. 명성은 익히 들었어요.', 'After two years of calls, it is wonderful to put a face to the name.', '2년간 통화만 하다가 직접 뵙게 되어 정말 좋아요.', 'C1', 'greeting', 2, 'business introduction', 5)
ON CONFLICT (id) DO NOTHING;
