-- ============================================================
-- C1-level Collocations and Idioms — Batch E
-- Topics: academic, discussion, negotiation
-- 5 collocations + 5 idioms per topic = 30 total entries
-- priority = 2 (C1)
-- ============================================================

-- ============================================================
-- ACADEMIC — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_academic_C1_01', 'conduct', 'research', 'conduct research', '연구를 수행하다', 'do', '학술적 맥락에서는 ''do research''보다 ''conduct research''가 표준이에요. 논문, 보고서, 학회 발표에서 자주 써요.', 'Her team conducted research on bilingual cognition over five years.', '그녀의 팀은 5년에 걸쳐 이중 언어 인지에 관한 연구를 수행했어요.', 'The institute conducts research into renewable energy policy.', '그 연구소는 재생에너지 정책에 관한 연구를 수행해요.', 'C1', 'academic', 2, 'research laboratory'),
('col_academic_C1_02', 'publish', 'findings', 'publish findings', '연구 결과를 발표하다', 'show', '연구 결과를 학술지나 보고서 형태로 공식 공개한다는 표현이에요. 학계의 핵심 동사예요.', 'The professor published her findings in a peer-reviewed journal last month.', '그 교수는 지난달 동료 심사 저널에 자신의 연구 결과를 발표했어요.', 'They plan to publish their findings at the international conference.', '그들은 국제 학회에서 연구 결과를 발표할 계획이에요.', 'C1', 'academic', 2, 'academic journal'),
('col_academic_C1_03', 'review', 'literature', 'review the literature', '선행 연구를 검토하다', 'read', '논문 작성 초기에 관련 선행 연구를 체계적으로 살펴본다는 학술적 표현이에요. ''literature review''라는 명사형도 자주 써요.', 'Before formulating her hypothesis, she reviewed the literature thoroughly.', '가설을 세우기 전에 그녀는 선행 연구를 철저히 검토했어요.', 'Doctoral candidates must review the literature in their field extensively.', '박사 과정 학생들은 자신의 분야에서 선행 연구를 폭넓게 검토해야 해요.', 'C1', 'academic', 2, 'library bookshelves'),
('col_academic_C1_04', 'test', 'hypotheses', 'test hypotheses', '가설을 검증하다', 'try', '가설이 맞는지 실험이나 데이터 분석으로 확인한다는 과학적 표현이에요. ''hypothesis''의 복수형은 ''hypotheses''예요.', 'The experiment was designed to test several competing hypotheses.', '그 실험은 경쟁하는 여러 가설들을 검증하기 위해 설계됐어요.', 'Researchers test hypotheses using rigorous statistical methods.', '연구자들은 엄격한 통계 방법을 사용해 가설을 검증해요.', 'C1', 'academic', 2, 'scientific experiment'),
('col_academic_C1_05', 'draw', 'conclusions', 'draw conclusions', '결론을 도출하다', 'make', '데이터나 증거를 바탕으로 결론에 이른다는 학술적 표현이에요. ''make a conclusion''은 자연스럽지 않아요.', 'It is premature to draw conclusions from such a small sample size.', '이렇게 작은 표본에서 결론을 도출하기에는 시기상조예요.', 'The author draws compelling conclusions from the data.', '저자는 데이터로부터 설득력 있는 결론을 도출해요.', 'C1', 'academic', 2, 'data analysis chart')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- ACADEMIC — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_academic_C1_01', 'back to the drawing board', '처음부터 다시 시작하다', '제도판으로 돌아가다', '계획이나 시도가 실패해서 처음부터 다시 설계해야 할 때 써요. 연구나 프로젝트 회의에서 자주 등장해요.', 'The initial model failed peer review, so it''s back to the drawing board.', '초기 모델이 동료 심사를 통과하지 못해서, 처음부터 다시 시작해야 해요.', 'After the experiment yielded no significant results, the team went back to the drawing board.', '실험에서 유의미한 결과가 나오지 않자, 팀은 처음부터 다시 시작했어요.', 'If this approach doesn''t work, it''s back to the drawing board.', '이 접근이 안 통하면, 다시 처음부터 시작해야 해요.', 'C1', 'academic', 2, 'drawing board sketch', 1),
('idm_academic_C1_02', 'a labour of love', '애정으로 하는 일', '사랑의 노동', '돈이나 보상보다는 순수한 열정과 애정으로 하는 일을 뜻해요. 장기 연구나 저술 작업을 묘사할 때 잘 어울려요.', 'Her ten-year ethnographic study was truly a labour of love.', '그녀의 10년에 걸친 민족지 연구는 진정 애정으로 한 일이었어요.', 'Writing this monograph has been a labour of love for the professor.', '이 단행본을 쓰는 일은 그 교수에게 애정으로 하는 일이었어요.', 'The dictionary project was a labour of love spanning three decades.', '그 사전 프로젝트는 30년에 걸친 애정의 결실이었어요.', 'C1', 'academic', 2, 'researcher writing', 2),
('idm_academic_C1_03', 'the proof of the pudding', '결과가 말해준다', '푸딩의 증거', '''the proof of the pudding is in the eating''의 축약형으로, 이론보다 실제 결과가 중요하다는 뜻이에요. 학술 발표에서 응용 가능성을 논할 때 써요.', 'The theory is elegant, but the proof of the pudding is in real-world application.', '이론은 우아하지만, 결국 실제 적용 결과가 말해줘요.', 'Reviewers will judge the model on accuracy — the proof of the pudding.', '심사자들은 정확도로 모델을 평가할 거예요. 결과가 말해주죠.', NULL, NULL, 'C1', 'academic', 2, 'pudding dessert', 3),
('idm_academic_C1_04', 'armchair scholar', '탁상공론 학자', '안락의자 학자', '직접 현장 연구나 실험 없이 책상에서만 이론을 펴는 사람을 비판적으로 부르는 표현이에요. 학계 토론에서 신중히 써야 해요.', 'Critics dismissed him as an armchair scholar with no fieldwork experience.', '비평가들은 그를 현장 경험 없는 탁상공론 학자로 치부했어요.', 'Don''t be an armchair scholar — go and collect the data yourself.', '탁상공론 학자가 되지 마세요. 직접 가서 데이터를 모으세요.', 'Her work distinguishes her from the armchair scholars of the discipline.', '그녀의 연구는 그녀를 이 분야의 탁상공론 학자들과 구별 짓게 해요.', 'C1', 'academic', 2, 'armchair library', 4),
('idm_academic_C1_05', 'in the same boat', '같은 처지에 있다', '같은 배에 있다', '같은 어려움이나 상황을 공유한다는 뜻이에요. 대학원생들이 논문 압박을 이야기할 때처럼 격식 있는 자리에서도 자연스러워요.', 'All doctoral candidates are in the same boat when it comes to thesis pressure.', '논문 압박에 관해서는 모든 박사 과정 학생들이 같은 처지예요.', 'We''re all in the same boat with the funding cuts this year.', '올해 연구비 삭감에 관해서는 우리 모두 같은 처지예요.', 'Junior faculty are in the same boat regarding tenure requirements.', '신임 교수들은 종신직 요건에 관해 같은 처지에 있어요.', 'C1', 'academic', 2, 'rowing boat', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- DISCUSSION — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_discussion_C1_01', 'raise', 'point', 'raise a point', '의견을 제기하다', 'say', '회의나 토론에서 새로운 논점을 정중하게 꺼낼 때 써요. ''say a point''는 자연스럽지 않아요.', 'May I raise a point about the proposed timeline?', '제안된 일정에 관해 한 가지 의견을 제기해도 될까요?', 'She raised an important point about ethical considerations.', '그녀는 윤리적 고려사항에 관한 중요한 의견을 제기했어요.', 'C1', 'discussion', 2, 'meeting discussion'),
('col_discussion_C1_02', 'build', 'consensus', 'build consensus', '합의를 형성하다', 'make', '여러 사람의 의견을 모아 동의를 끌어낸다는 격식 표현이에요. 정책, 회의, 협의 맥락에서 자주 써요.', 'The chair worked hard to build consensus among committee members.', '의장은 위원들 사이의 합의를 형성하기 위해 열심히 노력했어요.', 'Building consensus takes time but produces lasting decisions.', '합의를 형성하는 데는 시간이 걸리지만 지속 가능한 결정을 낳아요.', 'C1', 'discussion', 2, 'roundtable meeting'),
('col_discussion_C1_03', 'voice', 'opinion', 'voice an opinion', '의견을 표명하다', 'tell', '자신의 의견을 공개적으로 분명하게 표현한다는 격식 표현이에요. ''give an opinion''보다 더 적극적인 뉘앙스예요.', 'Everyone was encouraged to voice their opinion during the open forum.', '공개 토론에서 모두가 의견을 표명하도록 권장됐어요.', 'She voiced a dissenting opinion at the board meeting.', '그녀는 이사회에서 반대 의견을 표명했어요.', 'C1', 'discussion', 2, 'public speaker'),
('col_discussion_C1_04', 'address', 'concerns', 'address concerns', '우려 사항을 다루다', 'answer', '제기된 걱정거리를 진지하게 검토하고 대응한다는 표현이에요. 비즈니스, 정치, 학술 토론의 표준 어휘예요.', 'The CEO took time to address employees'' concerns about restructuring.', 'CEO는 구조조정에 대한 직원들의 우려를 다루는 데 시간을 들였어요.', 'Please address any concerns before we proceed with the vote.', '투표를 진행하기 전에 우려 사항이 있으면 다뤄 주세요.', 'C1', 'discussion', 2, 'town hall meeting'),
('col_discussion_C1_05', 'weigh', 'options', 'weigh the options', '선택지를 저울질하다', 'think', '여러 가능성의 장단점을 신중히 비교 검토한다는 표현이에요. 의사결정 회의에서 자주 써요.', 'The committee weighed the options carefully before announcing its decision.', '위원회는 결정을 발표하기 전에 선택지를 신중히 저울질했어요.', 'We need to weigh the options before committing resources.', '자원을 투입하기 전에 선택지를 저울질해야 해요.', 'C1', 'discussion', 2, 'balance scale')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- DISCUSSION — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_discussion_C1_01', 'see eye to eye', '의견이 일치하다', '눈과 눈을 마주 보다', '두 사람이나 집단이 같은 의견을 가진다는 뜻이에요. 보통 ''not see eye to eye'' 형태로 의견 차이를 표현할 때도 자주 써요.', 'The two directors don''t always see eye to eye on strategy.', '두 이사가 전략 면에서 항상 의견이 일치하는 건 아니에요.', 'We see eye to eye on the broader vision, even if details differ.', '세부 사항은 다를지언정 우리는 큰 비전에 관해서는 의견이 일치해요.', 'It took hours, but they finally saw eye to eye.', '몇 시간 걸렸지만 결국 그들은 의견 일치를 봤어요.', 'C1', 'discussion', 2, 'two people talking', 1),
('idm_discussion_C1_02', 'agree to disagree', '서로의 견해 차이를 인정하다', '의견 불일치에 동의하다', '서로 합의에 이르지 못해도 상대의 입장을 존중하며 논쟁을 마무리한다는 표현이에요. 외교적이고 성숙한 톤이에요.', 'After two hours of debate, we agreed to disagree on the policy.', '두 시간의 토론 끝에 우리는 그 정책에 관해 견해 차이를 인정하기로 했어요.', 'On this matter, the panelists ultimately agreed to disagree.', '이 사안에 관해 패널들은 결국 서로의 견해 차이를 인정했어요.', 'Let''s agree to disagree and move on to the next item.', '서로의 견해 차이를 인정하고 다음 안건으로 넘어갑시다.', 'C1', 'discussion', 2, 'handshake disagreement', 2),
('idm_discussion_C1_03', 'common ground', '공통점', '공통의 땅', '의견이 다른 양측이 동의할 수 있는 지점을 뜻해요. 토론, 협상, 외교에서 핵심 표현이에요.', 'The mediator helped both sides find common ground.', '중재자는 양측이 공통점을 찾도록 도왔어요.', 'Despite our differences, we share common ground on sustainability.', '차이에도 불구하고 우리는 지속 가능성에 관해 공통점을 가지고 있어요.', 'Finding common ground is the first step toward resolution.', '공통점을 찾는 것이 해결을 향한 첫걸음이에요.', 'C1', 'discussion', 2, 'overlapping circles', 3),
('idm_discussion_C1_04', 'play devil''s advocate', '일부러 반대 입장을 취하다', '악마의 변호인 역할을 하다', '논의를 깊이 있게 하기 위해 자신의 진짜 입장과 무관하게 반대 의견을 펴는 것을 뜻해요. 학술 토론과 비즈니스 회의에서 자주 써요.', 'Let me play devil''s advocate for a moment and challenge that assumption.', '잠시 일부러 반대 입장을 취해서 그 전제에 이의를 제기해 볼게요.', 'A good seminar leader will play devil''s advocate to sharpen the debate.', '훌륭한 세미나 진행자는 토론을 날카롭게 하기 위해 일부러 반대 입장을 취해요.', 'I''m playing devil''s advocate here, but have you considered the downside?', '일부러 반대 입장을 취하는 거지만, 단점은 고려해 보셨나요?', 'C1', 'discussion', 2, 'debate stage', 4),
('idm_discussion_C1_05', 'hit a brick wall', '난관에 부딪히다', '벽돌 벽에 부딪치다', '논의나 협상이 진전 없이 막혔다는 뜻이에요. 격식 있는 자리에서도 자연스럽게 써요.', 'Negotiations hit a brick wall over the compensation clause.', '협상이 보상 조항에서 난관에 부딪혔어요.', 'Every time we raise that topic, we hit a brick wall.', '그 주제를 꺼낼 때마다 난관에 부딪혀요.', 'The committee hit a brick wall and adjourned the meeting.', '위원회는 난관에 부딪혀 회의를 휴회했어요.', 'C1', 'discussion', 2, 'brick wall barrier', 5)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEGOTIATION — Collocations (C1)
-- ============================================================
INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, cefr, topic_id, priority, image_keyword) VALUES
('col_negotiation_C1_01', 'reach', 'agreement', 'reach an agreement', '합의에 이르다', 'make', '협상 끝에 양측이 동의에 이른다는 표준 표현이에요. ''make an agreement''보다 협상 과정의 결실이라는 뉘앙스가 강해요.', 'After months of talks, the two parties finally reached an agreement.', '몇 달간의 협상 끝에 양측은 마침내 합의에 이르렀어요.', 'We hope to reach an agreement by the end of the quarter.', '분기 말까지 합의에 이르기를 바라요.', 'C1', 'negotiation', 2, 'business handshake'),
('col_negotiation_C1_02', 'make', 'concession', 'make a concession', '양보를 하다', 'give', '협상에서 자신의 요구를 일부 포기한다는 격식 표현이에요. 외교, 노사 협상, 비즈니스 딜에서 자주 써요.', 'Both sides will need to make concessions to close this deal.', '이 딜을 성사시키려면 양측이 양보를 해야 할 거예요.', 'The union made a significant concession on overtime pay.', '노조는 초과근무 수당에 관해 중요한 양보를 했어요.', 'C1', 'negotiation', 2, 'negotiation handshake'),
('col_negotiation_C1_03', 'set', 'terms', 'set the terms', '조건을 정하다', 'put', '계약이나 협상의 조건을 정한다는 표현이에요. 누가 ''set the terms''하는지가 협상력의 핵심이에요.', 'The acquiring company sought to set the terms of the merger.', '인수 회사는 합병 조건을 정하려 했어요.', 'Whoever sets the terms first often shapes the deal.', '먼저 조건을 정하는 쪽이 종종 딜의 형태를 결정해요.', 'C1', 'negotiation', 2, 'contract terms'),
('col_negotiation_C1_04', 'walk', 'away', 'walk away from', '협상을 결렬시키다', 'leave', '협상이 자신에게 불리할 때 그만두고 나간다는 표현이에요. ''walk away from the table''로도 자주 써요.', 'They were prepared to walk away from the deal if their terms weren''t met.', '그들은 조건이 받아들여지지 않으면 딜을 결렬시킬 준비가 돼 있었어요.', 'Sometimes the best negotiation tactic is being willing to walk away.', '때로는 결렬시킬 의향을 보이는 게 최고의 협상 전술이에요.', 'C1', 'negotiation', 2, 'businessperson leaving'),
('col_negotiation_C1_05', 'drive', 'bargain', 'drive a hard bargain', '강하게 흥정하다', 'do', '협상에서 자신에게 유리한 조건을 단호하게 끌어낸다는 표현이에요. 보통 ''drive a hard bargain'' 형태로 써요.', 'She drives a hard bargain — expect lengthy negotiations.', '그녀는 강하게 흥정하니까, 긴 협상을 예상하세요.', 'The supplier drove a hard bargain on bulk pricing.', '공급업체는 대량 가격에서 강하게 흥정했어요.', 'C1', 'negotiation', 2, 'business bargaining')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NEGOTIATION — Idioms (C1)
-- ============================================================
INSERT INTO idioms (id, en, ko, literal_ko, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, cefr, topic_id, priority, image_keyword, sort_order) VALUES
('idm_negotiation_C1_01', 'meet halfway', '서로 양보해 타협하다', '중간 지점에서 만나다', '양측이 각자 양보해서 중간 지점에서 합의한다는 뜻이에요. 협상이나 갈등 해결의 핵심 표현이에요.', 'If you can lower the price, we''ll meet you halfway on the delivery terms.', '가격을 낮춰 주시면 배송 조건에서 저희가 절반 양보할게요.', 'Let''s meet halfway and split the additional costs.', '서로 양보해서 추가 비용을 반반 부담합시다.', 'A good negotiator knows when to meet the other side halfway.', '훌륭한 협상가는 언제 상대와 타협할지 알아요.', 'C1', 'negotiation', 2, 'middle ground meeting', 1),
('idm_negotiation_C1_02', 'deal breaker', '협상 결렬 요인', '딜을 깨는 것', '협상에서 절대 받아들일 수 없어 딜 자체를 무산시키는 조건을 뜻해요. 비즈니스 협상의 핵심 어휘예요.', 'Non-compete clauses are a deal breaker for many senior executives.', '경업 금지 조항은 많은 임원들에게 협상 결렬 요인이에요.', 'For us, that pricing structure is a deal breaker.', '저희에게 그 가격 구조는 협상 결렬 요인이에요.', 'They identified three potential deal breakers early in the talks.', '그들은 협상 초기에 세 가지 잠재적 결렬 요인을 식별했어요.', 'C1', 'negotiation', 2, 'contract negotiation', 2),
('idm_negotiation_C1_03', 'have the upper hand', '우위를 점하다', '윗손을 가지다', '협상이나 경쟁에서 더 유리한 위치에 있다는 뜻이에요. 비즈니스, 정치, 스포츠 등에서 두루 써요.', 'With multiple offers on the table, she had the upper hand in salary talks.', '여러 제안이 들어와 있어서 그녀는 연봉 협상에서 우위를 점했어요.', 'Market conditions gave the buyer the upper hand this quarter.', '시장 상황이 이번 분기 구매자에게 우위를 줬어요.', 'They held the upper hand until competitors entered the market.', '경쟁사들이 시장에 진입할 때까지 그들은 우위를 점하고 있었어요.', 'C1', 'negotiation', 2, 'chess strategy', 3),
('idm_negotiation_C1_04', 'common ground', '공통의 입장', '공통의 땅', '협상에서 양측이 동의할 수 있는 지점을 뜻해요. 외교와 비즈니스 협상의 핵심 개념이에요.', 'The mediator helped the two parties find common ground on key issues.', '중재자는 양측이 주요 사안에서 공통의 입장을 찾도록 도왔어요.', 'There''s common ground here — let''s build on it.', '여기 공통의 입장이 있어요. 이를 바탕으로 발전시킵시다.', 'Even rival firms can find common ground on industry standards.', '경쟁 기업들도 업계 표준에 관해서는 공통의 입장을 찾을 수 있어요.', 'C1', 'negotiation', 2, 'overlapping circles', 4),
('idm_negotiation_C1_05', 'back to square one', '원점으로 돌아가다', '1번 칸으로 돌아가다', '진전이 무산되어 처음부터 다시 시작해야 한다는 뜻이에요. 협상이 결렬되거나 진척이 사라졌을 때 써요.', 'The contract fell through, so we''re back to square one.', '계약이 무산돼서 우리는 원점으로 돌아갔어요.', 'If they reject this offer, we''re back to square one.', '그들이 이 제안을 거절하면 원점으로 돌아가요.', 'After six months of talks, the talks collapsed and they were back to square one.', '6개월간의 협상 끝에 회담이 결렬되어 그들은 원점으로 돌아갔어요.', 'C1', 'negotiation', 2, 'board game square', 5)
ON CONFLICT (id) DO NOTHING;
