-- EngCat — Phase 2: 40 new nuance pairs (learner confusion focus)
-- Adds commonly confused word pairs across 18 topics
-- IDs continue from existing per-topic numbering (nuc_{topic}_14+)

INSERT INTO nuances (id, word_a, word_b, word_c, ko_a, ko_b, ko_c, comparison, ex_a, ex_b, ex_c, ex4, ex4_ko, ex5, ex5_ko, tip, cefr, topic_id, priority, image_keyword) VALUES

-- discussion (nuc_discussion_14~16)
('nuc_discussion_14','do','make',null,'하다 (행위·임무)','만들다 (창조·생산)',null,
 'do는 추상적 행동·과제·임무를 할 때, make는 무언가를 새로 창조·생산할 때 써요.',
 'I have to do my homework before dinner.','Can you make me a sandwich?',null,
 'You do exercise, but you make a cake.','운동은 do로, 케이크는 make로 만들어요.',
 'She does the laundry while he makes dinner.','그녀는 빨래를 하고, 그는 저녁을 만들어요.',
 'do는 활동·임무, make는 창조·생산. 결과물이 손에 잡히면 make가 자연스러워요.',
 'B1','discussion',1,'cooking chores activity making'),

('nuc_discussion_15','explain','describe',null,'설명하다 (이유·원리)','묘사하다 (모습·특징)',null,
 'explain은 "왜·어떻게"를 설명할 때, describe는 "어떻게 생겼는지·어떤 모습인지" 묘사할 때 써요.',
 'Can you explain why this works?','Can you describe what he looks like?',null,
 'I explained the process; she described the result.','저는 과정을 설명했고, 그녀는 결과를 묘사했어요.',
 'The teacher explained the rule and described an example.','선생님은 규칙을 설명하고 예시를 묘사했어요.',
 'explain은 원리·이유, describe는 모습·특징. "왜?"는 explain, "어떻게 생겼어?"는 describe.',
 'B1','discussion',1,'teacher explaining describing chalkboard'),

('nuc_discussion_16','continue','keep',null,'계속하다','계속 ~하다',null,
 'continue는 동작/상태가 이어진다, keep + -ing는 "멈추지 않고 계속" 하는 느낌으로 더 일상적이에요.',
 'Please continue your story.','He kept talking for an hour.',null,
 'I continued working; he kept distracting me.','저는 일을 계속했고, 그는 계속 방해했어요.',
 'She continued the project but couldn''t keep going alone.','그녀는 프로젝트를 계속했지만 혼자 계속할 수는 없었어요.',
 'continue는 동작을 이어가는 자체, keep + -ing는 반복/지속의 뉘앙스가 강해요.',
 'B1','discussion',1,'persistence ongoing work flow'),

-- emotion (nuc_emotion_14~16)
('nuc_emotion_14','hope','wish',null,'바라다 (실현 가능)','바라다 (비현실적·후회)',null,
 'hope는 일어날 가능성 있는 일에 대한 기대, wish는 비현실적이거나 과거에 못 한 일에 대한 아쉬움.',
 'I hope you have a great day!','I wish I could fly.',null,
 'I hope it doesn''t rain; I wish I had brought an umbrella.','비가 안 오기를 바라요; 우산을 가져왔으면 좋았을 텐데요.',
 'She hopes to pass the exam; he wishes he had studied harder.','그녀는 시험에 합격하기를 바라고, 그는 더 열심히 공부했더라면 좋았을 거라고 해요.',
 'hope는 실현 가능, wish는 가정·후회. wish 뒤에는 보통 가정법(could/would/had pp).',
 'B1','emotion',1,'hopeful person wishing dream'),

('nuc_emotion_15','like','love','adore','좋아하다','정말 좋아하다, 사랑하다','매우 좋아하다, 흠모하다',
 'like < love < adore 강도 순. like는 호감, love는 깊은 애정, adore는 거의 숭배 수준의 애정.',
 'I like coffee in the morning.','I love my family.','She adores her grandchildren.',
 'I like ice cream, love chocolate, and adore cheesecake.','아이스크림 좋아하고, 초콜릿 사랑하고, 치즈케이크는 정말 좋아해요.',
 'He likes her, loves her cooking, and adores her laugh.','그는 그녀를 좋아하고, 그녀 요리를 사랑하고, 그녀 웃음을 흠모해요.',
 'like<love<adore. love는 가족·연인에 강력하고 적절, adore는 강한 애정 표현으로 약간 과장된 표현.',
 'B1','emotion',1,'love affection heart relationships'),

('nuc_emotion_16','feel','think',null,'느끼다 (감정·직관)','생각하다 (논리·의견)',null,
 'feel은 감정·직관적 판단, think는 논리적 판단·의견. "I feel that..."도 가능하지만 더 부드러운 느낌.',
 'I feel happy today.','I think this is the best option.',null,
 'I feel something is wrong, but I think we should still try.','뭔가 잘못된 느낌이지만 그래도 시도해 봐야 한다고 생각해요.',
 'She feels anxious; he thinks she''s overreacting.','그녀는 불안하다고 느끼지만, 그는 그녀가 과민 반응한다고 생각해요.',
 'feel은 감정/직감, think는 의견/추론. "I feel that..."은 부드러운 의견 표현으로도 쓰여요.',
 'A2','emotion',1,'feeling thinking introspection emotion'),

-- greeting (nuc_greeting_14~16)
('nuc_greeting_14','listen','hear',null,'듣다 (의식적 집중)','들리다 (수동적 수신)',null,
 'listen은 의도적으로 귀 기울이는 행위, hear는 그냥 소리가 들리는 수동적 수신.',
 'Please listen carefully.','I heard a strange noise outside.',null,
 'I was listening to music when I heard someone knock.','음악을 듣고 있는데 누가 노크하는 소리가 들렸어요.',
 'You can hear without listening, but you can''t listen without hearing.','들리기만 할 수도 있지만, 들으려면 들려야 해요.',
 'listen은 의도적, hear는 우연적. "Listen!"은 집중 요청, "Did you hear that?"는 그냥 들렸냐는 확인.',
 'A2','greeting',1,'listening attention focus headphones conversation'),

('nuc_greeting_15','look','see',null,'(의도적) 보다','(우연히/시각적으로) 보다',null,
 'look은 의식적으로 시선을 두는 행위, see는 시각적으로 인지·발견하는 결과.',
 'Look at this beautiful painting.','I see a bird outside the window.',null,
 'I looked everywhere but didn''t see my keys.','곳곳을 봤지만 열쇠가 보이지 않았어요.',
 'Look at the sky — do you see the stars?','하늘을 봐요 — 별이 보여요?',
 'look은 의도, see는 인지. "Look!"은 시선 끌기, "I see"는 이해/인지의 표현.',
 'A2','greeting',1,'looking watching binoculars eyes attention'),

('nuc_greeting_16','believe','trust',null,'믿다 (사실/존재)','신뢰하다 (사람·관계)',null,
 'believe는 어떤 사실/존재를 진실로 여기는 것, trust는 사람·관계를 신뢰하는 것 (의존 포함).',
 'I believe in ghosts.','I trust my best friend completely.',null,
 'I believe her story, but I don''t fully trust her yet.','그녀 이야기를 믿지만, 그녀를 완전히 신뢰하지는 않아요.',
 'You can believe a fact, but you trust a person.','사실은 믿을 수 있지만, 사람은 신뢰해야 해요.',
 'believe는 진위 판단, trust는 의존·신뢰. 사람에 대해서는 둘 다 가능하지만 의미 다름.',
 'B1','greeting',1,'trust relationship handshake confidence'),

-- education (nuc_education_14~16)
('nuc_education_14','remember','remind',null,'기억하다 (스스로)','상기시키다 (남에게)',null,
 'remember는 스스로 기억해내는 것, remind는 누군가에게 기억하라고 알려주는 행위. 한국어는 둘 다 "기억"이라 헷갈림.',
 'I remember my first day of school.','Please remind me to call her.',null,
 'I tried to remember her name, so she had to remind me.','이름을 기억해내려 했지만 그녀가 상기시켜 줘야 했어요.',
 'Remember to lock the door; I''ll remind you again later.','문 잠그는 거 기억하세요; 나중에 다시 상기시킬게요.',
 'remember는 주체가 본인, remind는 남에게 알려주는 동작. "remind me of X"는 "X를 떠올리게 한다".',
 'B1','education',1,'memory reminder notes phone alarm'),

('nuc_education_15','explain','tell',null,'설명하다 (원리·이유)','말하다 (사실·정보)',null,
 'explain은 "왜·어떻게"를 풀어주는 설명, tell은 단순히 정보를 전달하는 것.',
 'Can you explain how this works?','He told me the news.',null,
 'She told me the answer but didn''t explain why.','그녀는 답은 말해줬지만 이유는 설명하지 않았어요.',
 'Tell me the time; explain how to read a clock.','시간을 말해 줘요; 시계 보는 법을 설명해 줘요.',
 'explain은 풀이/이유, tell은 정보 전달. "Tell me why"도 가능하지만 explain이 더 정확.',
 'B1','education',1,'teacher explaining student information'),

('nuc_education_16','prepare','ready',null,'준비하다 (동사)','준비된 (형용사)',null,
 'prepare는 행위(동사), ready는 상태(형용사). "be ready"는 상태, "prepare"는 그 상태를 만드는 행위.',
 'I need to prepare for the exam.','Are you ready to go?',null,
 'I prepared for hours and now I''m ready.','몇 시간 준비했고 이제 준비됐어요.',
 'She prepared lunch; now lunch is ready.','그녀는 점심을 준비했고, 이제 점심이 준비됐어요.',
 'prepare는 동사(행위), ready는 형용사(상태). "get ready"는 "준비되다" = "준비를 마치다".',
 'B1','education',1,'student preparing exam ready studying'),

-- work (nuc_work_14~16)
('nuc_work_14','finish','complete',null,'끝내다 (일반)','완료하다 (격식·전체)',null,
 'finish는 일상적이고 광범위, complete는 좀 더 격식 있고 "끝까지 마쳤다"는 완결성 강조.',
 'I finished the book last night.','She completed the marathon in 4 hours.',null,
 'I finished the draft, but I need to complete the final version.','초안은 끝냈지만 최종본을 완성해야 해요.',
 'He finished work early; she completed the project on time.','그는 일을 일찍 끝냈고, 그녀는 프로젝트를 제때 완료했어요.',
 'finish는 일상적·간단, complete는 격식·완결. 양식 작성·과제 제출은 complete가 자연스러워요.',
 'B1','work',1,'project completion finished tasks checklist'),

('nuc_work_15','begin','start',null,'시작하다 (격식)','시작하다 (일반)',null,
 'begin과 start는 거의 동의어. 다만 begin이 약간 더 격식·문어체적, start는 일상·구어체적.',
 'The meeting begins at 9 AM.','Let''s start cooking.',null,
 'The ceremony begins now; the party starts later.','의식은 지금 시작하고, 파티는 나중에 시작해요.',
 'Begin with the introduction; start with a smile.','서론부터 시작하세요; 미소로 시작하세요.',
 'begin과 start는 대부분 호환. 다만 자동차·기계는 start만 (start the engine).',
 'A2','work',1,'beginning starting fresh sunrise launch'),

('nuc_work_16','earn','gain',null,'벌다 (노동·자격)','얻다 (이익·결과)',null,
 'earn은 노력·자격으로 얻는 것 (돈·존경·자격), gain은 결과로 얻는 것 (이익·체중·경험).',
 'She earns a high salary as an engineer.','He gained valuable experience abroad.',null,
 'I earn money by working; I gain happiness by helping others.','저는 일해서 돈을 벌고, 남을 도와 행복을 얻어요.',
 'She earned the promotion; he gained confidence over time.','그녀는 승진을 얻었고, 그는 시간이 지나면서 자신감을 얻었어요.',
 'earn은 노력·자격의 대가, gain은 결과로서의 획득. 돈은 보통 earn (gain은 갑작스러운 이익 뉘앙스).',
 'B2','work',1,'money career earning success career'),

-- economy (nuc_economy_14~15)
('nuc_economy_14','spend','use',null,'쓰다 (돈·시간)','사용하다 (도구·자원)',null,
 'spend는 돈·시간을 소비할 때, use는 도구·자원을 활용할 때.',
 'I spent fifty dollars on books.','Use the calculator if you need to.',null,
 'I spent two hours using the computer.','컴퓨터를 사용하면서 두 시간을 보냈어요.',
 'She spends her free time using language apps.','그녀는 여가 시간을 언어 앱을 사용하면서 보내요.',
 'spend는 소비(돈·시간 한정), use는 사용(도구·서비스). 시간은 둘 다 가능하지만 spend가 더 자연스러워요.',
 'A2','economy',1,'money time using spending budget'),

('nuc_economy_15','save','keep',null,'저축하다, 절약하다','보관하다, 유지하다',null,
 'save는 미래를 위해 모으거나 아끼는 것, keep은 단순히 가지고 있는 것·유지하는 것.',
 'I save money every month.','I keep my passport in a safe place.',null,
 'I save money but keep my receipts just in case.','돈을 저축하지만 영수증은 만일을 대비해 보관해요.',
 'Save energy; keep the lights off.','에너지를 절약하세요; 불은 꺼두세요.',
 'save는 미래 대비(모으기·아끼기), keep은 현재 유지·소지. save the date는 일정 확보, keep in mind는 마음에 새기기.',
 'A2','economy',1,'savings piggy bank money keeping safe'),

-- shopping (nuc_shopping_14~15)
('nuc_shopping_14','choose','select',null,'고르다 (일상)','선택하다 (격식·정확)',null,
 'choose는 일상적·일반적, select는 좀 더 격식·정확한 선택 (메뉴, 옵션, 후보 등).',
 'I choose chocolate over vanilla.','Please select your preferred language.',null,
 'I chose the red shirt after selecting from 10 options.','10가지 옵션에서 고른 끝에 빨간 셔츠를 선택했어요.',
 'Choose carefully; select the best candidate.','신중하게 고르세요; 최고의 후보자를 선택하세요.',
 'choose는 자유로운 선택, select는 정해진 옵션에서 골라내는 느낌. UI 버튼은 보통 "Select".',
 'A2','shopping',1,'choosing selecting options shopping decision'),

('nuc_shopping_15','borrow','lend',null,'빌리다 (받는 입장)','빌려주다 (주는 입장)',null,
 'borrow는 빌려서 받는 행위, lend는 빌려주는 행위. 한국어는 둘 다 "빌리다"라 자주 헷갈림.',
 'Can I borrow your pen?','Could you lend me your pen?',null,
 'I borrowed her book; she lent it to me.','저는 그녀 책을 빌렸고, 그녀가 저에게 빌려줬어요.',
 'Borrow money from a bank; the bank lends you money.','은행에서 돈을 빌리세요; 은행이 당신에게 돈을 빌려줘요.',
 'borrow는 받는 쪽(나에게로), lend는 주는 쪽(나로부터). "Can I borrow X?"가 "Can you lend X?"보다 더 자주 쓰여요.',
 'A2','shopping',1,'lending borrowing book money exchange'),

-- transport (nuc_transport_14~15)
('nuc_transport_14','bring','take',null,'가져오다 (이쪽으로)','가져가다 (저쪽으로)',null,
 'bring은 화자/청자가 있는 곳으로 가져오는 것, take는 다른 곳으로 가져가는 것. 방향이 핵심.',
 'Bring your umbrella to the party.','Take your umbrella when you leave.',null,
 'Please bring me the book; I''ll take it to the library.','저에게 책을 가져다 주세요; 제가 도서관에 가져갈게요.',
 'Bring snacks to my place; take leftovers home.','우리 집에 간식 가져오세요; 남은 음식은 집에 가져가세요.',
 'bring은 화자·청자 쪽으로, take는 다른 곳으로. 헷갈리면 "to here = bring, away = take"로 기억.',
 'A2','transport',1,'bringing taking direction moving carrying'),

('nuc_transport_15','arrive','reach',null,'도착하다 (장소)','도달하다 (목표·장소)',null,
 'arrive는 일반적 "도착", reach는 (특히 노력 후) "도달했다"는 성취 느낌이 있어요.',
 'We arrived at the airport at 6.','It took hours to reach the summit.',null,
 'They arrived in the city safely and reached their hotel by 8.','그들은 도시에 무사히 도착했고 8시까지 호텔에 도달했어요.',
 'I arrived at the meeting; we reached an agreement.','회의에 도착했고, 합의에 도달했어요.',
 'arrive는 "도착" 자체, reach는 "닿다·도달"의 뉘앙스. arrive at(작은 곳)/in(큰 곳), reach는 전치사 없이 reach + 목적어.',
 'A2','transport',1,'arrival airport destination journey ending'),

-- home (nuc_home_14~15)
('nuc_home_14','live','stay',null,'살다 (장기 거주)','머물다 (임시)',null,
 'live는 장기 거주(집), stay는 임시 체류(호텔·친구 집·여행).',
 'I live in Seoul with my family.','I''m staying at a hotel for the weekend.',null,
 'I live in London but stay at my parents'' on holidays.','저는 런던에 살지만 휴가 때는 부모님 집에 머물러요.',
 'She lives alone; he stays with her on weekends.','그녀는 혼자 살고, 그는 주말마다 그녀 집에 머물러요.',
 'live는 거주(영구·장기), stay는 머묾(임시). 호텔은 stay, 본인 집은 live.',
 'A2','home',1,'home apartment travel hotel staying'),

('nuc_home_15','big','large',null,'큰 (일상)','큰 (격식·면적)',null,
 'big과 large는 대부분 호환. big이 더 일상·구어체, large는 면적·격식 표현에 자주 쓰여요.',
 'That''s a big house!','We need a large room for the event.',null,
 'A big idea can require a large team.','큰 아이디어는 큰 팀이 필요할 수 있어요.',
 'She has a big smile and a large suitcase.','그녀는 활짝 웃는 얼굴과 큰 가방을 가지고 있어요.',
 'big은 일상, large는 측정·격식 (a large coffee, a large room). 가족·문제·차이는 보통 big.',
 'A2','home',1,'big house spacious large room'),

-- health (nuc_health_14~15)
('nuc_health_14','hurt','pain',null,'아프다 (동사)','통증 (명사)',null,
 'hurt는 동사 (아프다, 다치게 하다), pain은 명사 (통증). 한국어는 둘 다 "아픔"이라 헷갈림.',
 'My back hurts after sitting all day.','I have a sharp pain in my back.',null,
 'My head hurts; the pain is unbearable.','머리가 아파요; 통증이 참기 어려워요.',
 'It hurts when I move; the pain comes and goes.','움직이면 아파요; 통증이 왔다 갔다 해요.',
 'hurt는 동사(아프다), pain은 명사(통증). "I have a pain"은 OK, "I have a hurt"는 어색.',
 'A2','health',1,'pain headache hurt body health'),

('nuc_health_15','recover','heal',null,'회복하다 (전체적)','낫다 (상처·신체)',null,
 'recover는 병·수술·심리에서 전체적으로 회복, heal은 주로 상처·뼈 등이 낫는 신체적 치유.',
 'She''s recovering from surgery quickly.','The wound healed in two weeks.',null,
 'My broken arm healed, and I''ve fully recovered.','부러진 팔이 나았고, 완전히 회복했어요.',
 'It takes time to heal physically and recover emotionally.','신체적으로 낫는 데도, 감정적으로 회복하는 데도 시간이 필요해요.',
 'heal은 상처가 닫히고 낫는 것, recover는 병·상태로부터의 전반적 회복. 마음의 상처도 heal이 가능.',
 'B1','health',1,'recovery healing wound bandage health'),

-- cafe (nuc_cafe_14~15)
('nuc_cafe_14','tasty','delicious',null,'맛있는 (일상)','정말 맛있는 (강조)',null,
 'tasty는 일반적으로 맛있는 정도, delicious는 더 강한 칭찬 (매우 맛있는).',
 'That sandwich was tasty.','This cake is absolutely delicious!',null,
 'The soup was tasty, but the dessert was delicious.','수프는 맛있었고, 디저트는 정말 맛있었어요.',
 'Everyday meals are tasty; special meals are delicious.','일상 식사는 맛있고, 특별한 식사는 정말 맛있어요.',
 'tasty < delicious 강도. delicious는 칭찬을 강조할 때 자주 써요. 음식 후기엔 delicious가 만점.',
 'A2','cafe',1,'delicious food tasty meal happy eating'),

('nuc_cafe_15','huge','big',null,'엄청 큰 (강조)','큰 (일반)',null,
 'big은 큰 정도, huge는 매우 큰 (강조). big < huge.',
 'We had a big pizza.','That portion is huge!',null,
 'The cake was big, but the wedding cake was huge.','케이크가 컸지만 결혼식 케이크는 어마어마했어요.',
 'A big coffee for me; a huge espresso for him.','저는 큰 커피요; 그는 엄청 큰 에스프레소예요.',
 'big < huge 강도. enormous, gigantic도 비슷한 강조 (huge보다 더 강함).',
 'A2','cafe',1,'huge portion big food meal large'),

-- culture (nuc_culture_14~15)
('nuc_culture_14','celebrate','commemorate',null,'축하·기념하다 (기쁨)','기리다 (엄숙·추모)',null,
 'celebrate는 즐거운 일을 축하 (생일, 결혼, 명절), commemorate는 엄숙히 기념 (역사적 사건, 추모일).',
 'We celebrated her birthday at a restaurant.','The country commemorates its independence every year.',null,
 'We celebrate the new year; we commemorate the fallen heroes.','새해는 축하하고, 전사한 영웅들은 기려요.',
 'Celebrate joyful events; commemorate solemn occasions.','즐거운 행사는 축하하고, 엄숙한 일은 기려요.',
 'celebrate는 기쁨·축하, commemorate는 엄숙·추모. 광복절·전쟁기념일은 commemorate가 적절.',
 'B2','culture',1,'celebration commemoration ceremony memorial respect'),

('nuc_culture_15','modern','contemporary',null,'현대의 (시기적)','동시대의 (지금 살아있는)',null,
 'modern은 "현대 = 산업혁명 이후" 정도, contemporary는 "지금 이 시대에 살아있는·만들어진".',
 'Modern art started in the late 19th century.','Contemporary art refers to art made today.',null,
 'Modern architecture differs from contemporary architecture.','현대 건축은 동시대 건축과 달라요.',
 'She studies modern history but loves contemporary novels.','그녀는 현대사를 공부하지만 동시대 소설을 좋아해요.',
 'modern은 폭넓은 시대 구분 (현대), contemporary는 "지금 우리 시대" 강조. 미술·건축·문학에서 자주 구분돼요.',
 'B2','culture',1,'modern art contemporary gallery architecture'),

-- travel (nuc_travel_14~15)
('nuc_travel_14','pack','prepare',null,'짐을 싸다','준비하다 (일반)',null,
 'pack은 짐(가방)을 싸는 행위에 한정, prepare는 일반적인 모든 준비.',
 'I need to pack for my trip.','I need to prepare for my trip.',null,
 'First prepare a list, then pack accordingly.','먼저 목록을 준비하고, 그에 맞춰 짐을 싸세요.',
 'She prepared snacks and packed them in her bag.','그녀는 간식을 준비하고 가방에 짐을 쌌어요.',
 'pack은 짐 싸기에 한정, prepare는 광범위 (정신적·물리적 준비 모두). 식사 준비는 prepare a meal.',
 'A2','travel',1,'packing suitcase luggage preparing trip'),

('nuc_travel_15','explore','discover',null,'탐험하다 (행위)','발견하다 (결과)',null,
 'explore는 탐구·탐험하는 과정, discover는 새로운 것을 발견하는 결과.',
 'We explored the old town for hours.','I discovered a hidden cafe in the alley.',null,
 'While exploring the city, I discovered a beautiful park.','도시를 탐험하다가 아름다운 공원을 발견했어요.',
 'Explore new places; discover new things.','새 장소를 탐험하고, 새로운 것을 발견하세요.',
 'explore는 과정·행위, discover는 결과·발견. 처음 발견하는 것은 discover, 둘러보는 것은 explore.',
 'B1','travel',1,'exploring discovering travel adventure hidden'),

-- media (nuc_media_14~15)
('nuc_media_14','post','publish',null,'(SNS에) 올리다','출판·발행하다 (정식)',null,
 'post는 SNS·블로그·게시판에 올리는 비공식 행위, publish는 책·기사·논문 등 정식 출판.',
 'I posted a photo on Instagram.','She published her first novel last year.',null,
 'I post tweets daily, but I dream of publishing a book someday.','매일 트윗을 올리지만, 언젠가 책을 출간하는 게 꿈이에요.',
 'Bloggers post articles; journalists publish stories.','블로거는 글을 올리고, 기자는 기사를 발행해요.',
 'post는 캐주얼(SNS·게시판), publish는 공식·정식(책·논문·신문). 출판물은 publish.',
 'A2','media',1,'social media post publishing book online'),

('nuc_media_15','share','distribute',null,'공유하다 (SNS·비공식)','배포하다 (공식·대규모)',null,
 'share는 친구·SNS에서 공유하는 비공식적인 행위, distribute는 공식·대규모로 배포하는 행위.',
 'I shared the article with my friends.','The company distributes products worldwide.',null,
 'She shared the post; the news outlet distributed it widely.','그녀는 그 게시물을 공유했고, 그 매체가 이를 광범위하게 배포했어요.',
 'Share with one; distribute to many.','한 명과 공유하고, 다수에게 배포하세요.',
 'share는 개인 단위, distribute는 공식·대규모 단위. 전단지·상품은 distribute, 링크·소식은 share.',
 'B1','media',1,'sharing distributing online viral link'),

-- news (nuc_news_14~15)
('nuc_news_14','announce','declare',null,'발표하다 (정보 공개)','선언하다 (공식·강력)',null,
 'announce는 정보를 공개적으로 알리는 것, declare는 공식적·강력하게 선언하는 것 (전쟁, 독립, 의지).',
 'The CEO announced new policies today.','The country declared independence in 1948.',null,
 'They announced the merger; he declared his support publicly.','그들은 합병을 발표했고, 그는 공개적으로 지지를 선언했어요.',
 'Announce a birthday party; declare a state of emergency.','생일 파티를 알리세요; 비상사태를 선포하세요.',
 'announce는 일반 발표, declare는 강한 공식 선언. 결혼 발표는 announce, 전쟁 선포는 declare.',
 'B2','news',1,'announcement declaration podium speech press'),

('nuc_news_15','cover','report',null,'(현장을) 취재하다','(정리해서) 보도하다',null,
 'cover는 사건 현장을 취재하는 폭넓은 활동, report는 정리해서 보도하는 결과.',
 'She covered the election for CNN.','He reported the news from the scene.',null,
 'Journalists cover events and report findings.','기자들은 사건을 취재하고 결과를 보도해요.',
 'They covered the war zone and reported casualties daily.','그들은 전쟁 지역을 취재하고 매일 사상자를 보도했어요.',
 'cover는 취재 활동(현장 포함), report는 정리·전달. 같은 사건도 cover는 "다룬다", report는 "전한다".',
 'B1','news',1,'journalist reporter coverage news camera'),

-- presentation (nuc_presentation_14~15)
('nuc_presentation_14','show','display',null,'보여주다 (일상)','전시·표시하다 (격식·시각적)',null,
 'show는 일반적인 "보여주다", display는 진열·전시하거나 화면에 표시하는 좀 더 시각적·격식 표현.',
 'Let me show you the report.','The museum displays ancient artifacts.',null,
 'I''ll show you the slide where the data is displayed.','데이터가 표시된 슬라이드를 보여 드릴게요.',
 'The store displays new items; staff show customers around.','매장은 신상품을 진열하고, 직원은 고객을 안내해요.',
 'show는 일상·동작, display는 시각적·격식. 가게 진열·화면 표시는 display, 그냥 보여주기는 show.',
 'A2','presentation',1,'presentation slide showing display screen'),

('nuc_presentation_15','demonstrate','explain',null,'시연하다 (보여주며 증명)','설명하다 (말로)',null,
 'demonstrate는 행동·예시로 보여주며 증명, explain은 말로 풀어 설명.',
 'Let me demonstrate how this app works.','Let me explain how this app works.',null,
 'I''ll explain the concept and demonstrate it step by step.','개념을 설명하고 단계별로 시연할게요.',
 'She demonstrated the product while he explained its features.','그녀는 제품을 시연하고, 그는 기능을 설명했어요.',
 'demonstrate는 행동·시각적 증명, explain은 언어·논리적 풀이. 실험·기능은 demonstrate가 효과적.',
 'B1','presentation',1,'demonstration product showing presentation hands-on'),

-- sports (nuc_sports_14)
('nuc_sports_14','run','jog',null,'뛰다 (속도·강도)','조깅하다 (느린 걸음으로 뛰다)',null,
 'run은 일반적인 "뛰다" (속도 빠름), jog는 운동 목적으로 느리게 뛰는 행위.',
 'I run sprints at the track.','I jog in the park every morning.',null,
 'I jog three times a week and run a marathon once a year.','일주일에 세 번 조깅하고, 일 년에 한 번 마라톤을 뛰어요.',
 'Running burns more calories; jogging is easier on the knees.','뛰기는 칼로리 소모가 더 크고, 조깅은 무릎에 더 부담이 적어요.',
 'run > jog 속도. 무릎 부담은 jog가 적어서 일상 운동으로 인기. 마라톤은 run.',
 'A2','sports',1,'running jogging exercise park morning'),

-- negotiation (nuc_negotiation_14)
('nuc_negotiation_14','compromise','settle',null,'타협하다 (서로 양보)','합의·해결하다 (마무리)',null,
 'compromise는 서로 양보해 중간점 찾기, settle은 분쟁·이슈를 최종 해결하는 마무리.',
 'We compromised on the price.','They settled the dispute out of court.',null,
 'After compromising on several points, they settled the deal.','여러 부분에서 타협한 후 거래를 마무리 지었어요.',
 'You compromise to reach an agreement; you settle the matter.','합의에 이르려면 타협하고, 사안을 마무리하세요.',
 'compromise는 양보·중간점, settle은 최종 해결. settle a bill은 청구서 정산, settle down은 안정.',
 'B2','negotiation',1,'handshake agreement compromise negotiation business'),

-- environment (nuc_environment_14)
('nuc_environment_14','clean','pure',null,'깨끗한 (오염 없음)','순수한 (불순물 없음)',null,
 'clean은 오염·먼지가 없는 상태, pure는 다른 성분이 섞이지 않은 순수한 상태.',
 'The river is clean again after the cleanup.','This water is pure and safe to drink.',null,
 'Clean water has no pollution; pure water has no minerals.','깨끗한 물은 오염이 없고, 순수한 물은 미네랄도 없어요.',
 'Clean the air; keep your intentions pure.','공기를 깨끗하게 하세요; 의도를 순수하게 유지하세요.',
 'clean은 더러움이 없는 상태, pure는 다른 것이 섞이지 않은 상태. clean energy는 깨끗한 에너지, pure gold는 순금.',
 'B1','environment',1,'clean pure water nature pristine'),

-- academic (nuc_academic_14)
('nuc_academic_14','theory','hypothesis',null,'이론 (검증된 설명)','가설 (검증 전 추측)',null,
 'theory는 검증·관찰을 통해 확립된 설명, hypothesis는 검증 전의 추측·예측.',
 'Darwin''s theory of evolution is well-established.','My hypothesis is that students learn better in groups.',null,
 'A hypothesis becomes a theory only after extensive testing.','가설은 광범위한 검증을 거쳐야 이론이 돼요.',
 'She proposed a hypothesis; later studies turned it into a theory.','그녀는 가설을 제시했고, 이후 연구를 통해 이론이 됐어요.',
 'hypothesis < theory. 일상에서 "I have a theory"는 "내 추측"으로 쓰이기도 하지만 학술적으로는 다름.',
 'B2','academic',1,'science research hypothesis theory laboratory'),

-- technology (nuc_technology_14)
('nuc_technology_14','click','tap',null,'클릭하다 (마우스)','탭하다 (터치 화면)',null,
 'click은 마우스로 누르는 동작, tap은 터치 화면을 손가락으로 누르는 동작.',
 'Click the link to continue.','Tap the icon to open the app.',null,
 'On a computer, click; on a phone, tap.','컴퓨터에서는 클릭하고, 휴대폰에서는 탭하세요.',
 'I clicked the button and then tapped Send on my phone.','버튼을 클릭한 다음 휴대폰에서 보내기를 탭했어요.',
 'click은 마우스·트랙패드, tap은 터치 화면. 더블 클릭 = double-click, 두 번 탭 = double-tap.',
 'A2','technology',1,'phone tap click finger screen mouse'),

-- humanities (nuc_humanities_14)
('nuc_humanities_14','novel','fiction',null,'소설 (책 한 권)','허구·픽션 (장르 전체)',null,
 'novel은 소설책 한 권 (긴 산문 픽션), fiction은 허구·픽션 장르 전체 (소설, 단편, 동화 포함).',
 'I read three novels this summer.','I prefer fiction over non-fiction.',null,
 'A novel is a type of fiction.','소설은 픽션의 한 종류예요.',
 'She writes novels; he reads science fiction.','그녀는 소설을 쓰고, 그는 SF 픽션을 읽어요.',
 'novel은 한 작품 (책 한 권), fiction은 장르. "fiction"은 셀 수 없는 명사, "novel"은 셀 수 있어요.',
 'B1','humanities',1,'novel book fiction library reading')

ON CONFLICT (id) DO NOTHING;
