-- EngCat — Phase 1B: 60 more high-frequency collocations
-- Adds verb+noun combos across 21 topics
-- IDs continue from existing per-topic numbering

INSERT INTO collocations (id, verb, noun, en, ko, wrong_verb, tip, ex1, ex1_ko, ex2, ex2_ko, ex3, ex3_ko, ex4, ex4_ko, ex5, ex5_ko, cefr, topic_id, priority, image_keyword) VALUES

-- work (col_work_23~26)
('col_work_23','give','presentation','give a presentation','발표를 하다','make',
 '"make a presentation"도 가능하지만 give a presentation이 더 자연스러워요.',
 'I have to give a presentation tomorrow morning.','내일 아침에 발표를 해야 해요.',
 'She gave a great presentation about market trends.','그녀는 시장 동향에 관한 훌륭한 발표를 했어요.',
 'Have you ever given a presentation in English?','영어로 발표해 본 적 있어요?',
 'He gave a presentation to the entire department.','그는 부서 전체에게 발표를 했어요.',
 'I''m nervous about giving a presentation to the board.','이사회 앞에서 발표하려니 긴장돼요.',
 'B1','work',1,'business presentation slide screen audience'),

('col_work_24','run','business','run a business','사업을 운영하다','do',
 '"do business"는 거래/장사를 한다는 다른 의미예요. 운영 자체는 run a business.',
 'It''s hard work to run a small business.','작은 사업을 운영하는 건 힘든 일이에요.',
 'She runs a successful online business.','그녀는 성공적인 온라인 사업을 운영해요.',
 'My uncle has been running a bakery for 20 years.','우리 삼촌은 20년째 빵집을 운영하고 있어요.',
 'You need a license to run a business here.','여기서 사업을 운영하려면 면허가 필요해요.',
 'They run a family-owned business together.','그들은 함께 가족 사업을 운영해요.',
 'B1','work',1,'business owner shop entrepreneur store'),

('col_work_25','run','late','run late','늦어지다','go',
 '"go late"는 어색해요. 일정이 늦어질 때는 run late를 써요.',
 'Sorry, I''m running late for the meeting.','죄송해요, 회의에 늦어지고 있어요.',
 'The train is running 15 minutes late today.','오늘 기차가 15분 늦게 운행되고 있어요.',
 'We''re running a bit late — start without us.','조금 늦어지고 있어요 — 먼저 시작하세요.',
 'She always runs late to morning classes.','그녀는 항상 아침 수업에 늦어요.',
 'The project is running late due to delays.','프로젝트가 지연 때문에 늦어지고 있어요.',
 'A2','work',1,'person running late watch clock office'),

('col_work_26','close','deal','close a deal','거래를 성사시키다','make',
 '"make a deal"은 거래를 제안/타결 의미. close a deal은 최종 마무리에 초점.',
 'We closed the deal after weeks of negotiation.','몇 주간의 협상 끝에 거래를 성사시켰어요.',
 'She closed a major deal with the new client.','그녀는 새 고객과 큰 거래를 성사시켰어요.',
 'They closed the deal at the last minute.','그들은 마지막 순간에 거래를 성사시켰어요.',
 'Closing this deal will boost our quarterly results.','이 거래를 성사시키면 분기 실적이 크게 오를 거예요.',
 'He''s known for closing deals quickly.','그는 거래를 빠르게 성사시키는 것으로 유명해요.',
 'B2','work',1,'business handshake contract signing executives'),

-- education (col_education_23~25)
('col_education_23','make','progress','make progress','진전을 이루다','do',
 '"do progress"는 틀린 표현. 어떤 일이 나아가는 건 항상 make progress.',
 'You''re making great progress with your English!','영어 실력이 정말 많이 늘고 있어요!',
 'We''ve made significant progress on the project.','프로젝트에서 상당한 진전을 이뤘어요.',
 'It''s slow, but I''m making progress.','느리지만 진전을 이루고 있어요.',
 'She made remarkable progress in just one month.','그녀는 한 달 만에 놀라운 진전을 이뤘어요.',
 'Are you making any progress on your thesis?','논문에 진전이 있나요?',
 'B1','education',1,'student studying improvement progress chart'),

('col_education_24','pass','exam','pass an exam','시험에 합격하다','do',
 '"do an exam"은 시험을 본다는 뜻. 합격은 pass an exam (반대는 fail).',
 'She passed the exam with flying colors.','그녀는 우수한 성적으로 시험에 합격했어요.',
 'I need to pass this exam to graduate.','졸업하려면 이 시험에 합격해야 해요.',
 'He passed his driving exam on the first try.','그는 운전 시험을 처음에 합격했어요.',
 'Did you pass the certification exam?','자격증 시험 합격했어요?',
 'Studying hard pays off when you pass an exam.','열심히 공부하면 시험 합격으로 보상받아요.',
 'A2','education',1,'student exam paper passed grade certificate'),

('col_education_25','fail','test','fail a test','시험에 떨어지다','lose',
 '"lose a test"는 틀린 표현. 시험을 떨어지면 fail. (lose는 시합에서 짐)',
 'I failed the test because I didn''t study.','공부를 안 해서 시험에 떨어졌어요.',
 'Failing a test isn''t the end of the world.','시험에 떨어진다고 세상이 끝나는 건 아니에요.',
 'She was upset about failing the math test.','그녀는 수학 시험에 떨어진 것에 속상해했어요.',
 'He failed the test by just one point.','그는 단 1점 차이로 시험에 떨어졌어요.',
 'You won''t fail the test if you prepare well.','잘 준비하면 시험에 떨어지지 않을 거예요.',
 'A2','education',1,'student failed test paper disappointed grade'),

-- academic (col_academic_21~24)
('col_academic_21','do','research','do research','연구하다','make',
 '"make research"는 틀린 표현. 연구 활동은 do/conduct research.',
 'She''s doing research on climate change.','그녀는 기후 변화에 관한 연구를 하고 있어요.',
 'I did extensive research before writing the paper.','논문을 쓰기 전에 광범위한 연구를 했어요.',
 'They do research at one of the top universities.','그들은 최고 대학 중 한 곳에서 연구를 해요.',
 'Doing research requires patience and discipline.','연구는 인내와 규율이 필요해요.',
 'How long did you do research for this project?','이 프로젝트를 위해 얼마나 오래 연구했어요?',
 'A2','academic',1,'researcher lab books data analysis'),

('col_academic_22','write','paper','write a paper','논문을 쓰다','make',
 '"make a paper"는 종이접기에 가까운 표현. 학술 논문은 write a paper.',
 'I''m writing a paper on renewable energy.','신재생 에너지에 관한 논문을 쓰고 있어요.',
 'She wrote her first paper as an undergraduate.','그녀는 학부생 때 첫 논문을 썼어요.',
 'Writing a paper takes weeks of preparation.','논문을 쓰려면 몇 주의 준비가 필요해요.',
 'He wrote a paper that was later published.','그는 나중에 출판된 논문을 썼어요.',
 'I need to write a paper for the conference.','학회 발표를 위한 논문을 써야 해요.',
 'B1','academic',1,'researcher writing laptop academic paper desk'),

('col_academic_23','attend','class','attend a class','수업에 출석하다','take',
 '"take a class"는 수강 신청한다는 의미. 그날 출석한다는 의미는 attend a class.',
 'She attends every class without missing one.','그녀는 모든 수업에 빠지지 않고 출석해요.',
 'I attended a fascinating class on philosophy.','저는 흥미로운 철학 수업에 출석했어요.',
 'Students are required to attend at least 80% of classes.','학생들은 수업의 80% 이상을 출석해야 해요.',
 'He didn''t attend class because he was sick.','그는 아파서 수업에 출석하지 못했어요.',
 'I plan to attend the morning class instead.','대신 아침 수업에 출석할 계획이에요.',
 'A2','academic',1,'classroom students lecture attendance university'),

('col_academic_24','give','lecture','give a lecture','강의를 하다','do',
 '"do a lecture"는 어색해요. 강의는 give a lecture가 표준.',
 'Professor Kim is giving a lecture on quantum physics.','김 교수는 양자물리학에 관한 강의를 해요.',
 'She gave a brilliant lecture last Tuesday.','그녀는 지난 화요일 멋진 강의를 했어요.',
 'I''ve given lectures at several universities.','저는 여러 대학에서 강의를 한 적이 있어요.',
 'The visiting scholar will give a lecture tonight.','초청 학자가 오늘 밤 강의를 할 거예요.',
 'He gives a lecture every Friday morning.','그는 매주 금요일 아침에 강의를 해요.',
 'B1','academic',1,'professor lecture podium auditorium audience'),

-- shopping (col_shopping_24)
('col_shopping_24','make','payment','make a payment','결제를 하다','do',
 '"do a payment"은 어색해요. 결제 행위는 make a payment.',
 'You can make a payment online or in person.','온라인이나 직접 방문해서 결제할 수 있어요.',
 'She made the payment using her credit card.','그녀는 신용카드로 결제를 했어요.',
 'Please make the payment within seven days.','7일 이내에 결제해 주세요.',
 'I made a partial payment for the deposit.','보증금으로 부분 결제를 했어요.',
 'Can I make a payment by bank transfer?','계좌 이체로 결제할 수 있나요?',
 'B1','shopping',1,'payment credit card terminal checkout transaction'),

-- economy (col_economy_21~24)
('col_economy_21','earn','living','earn a living','생계를 꾸리다','make',
 '"make a living"도 흔히 쓰여요. 둘 다 정답이지만 earn은 노동으로 번다는 뉘앙스가 강해요.',
 'He earns a living as a freelance designer.','그는 프리랜서 디자이너로 생계를 꾸려요.',
 'It''s hard to earn a living in this town.','이 동네에서 생계를 꾸리기는 어려워요.',
 'She earns a comfortable living as a translator.','그녀는 번역가로 안정적인 생계를 꾸려요.',
 'My parents worked hard to earn a living.','부모님은 생계를 꾸리기 위해 열심히 일하셨어요.',
 'How do you earn a living these days?','요즘 어떻게 생계를 꾸리세요?',
 'B2','economy',1,'working person job income livelihood paycheck'),

('col_economy_22','invest','money','invest money','돈을 투자하다','put',
 '"put money"도 쓰이지만 정식 투자는 invest money. put money in은 더 캐주얼.',
 'She invests money in tech stocks.','그녀는 기술주에 돈을 투자해요.',
 'I''ve invested money in real estate for years.','저는 수년간 부동산에 돈을 투자해 왔어요.',
 'Don''t invest money you can''t afford to lose.','잃어도 괜찮을 돈만 투자하세요.',
 'He invested all his money in his startup.','그는 자기 스타트업에 모든 돈을 투자했어요.',
 'Where''s the best place to invest money right now?','지금 돈을 투자하기 가장 좋은 곳은 어디예요?',
 'B1','economy',1,'investor money stocks chart growth portfolio'),

('col_economy_23','open','account','open an account','계좌를 개설하다','start',
 '"start an account"도 비공식적으로 쓰이지만 은행 표준은 open an account.',
 'I''d like to open a savings account.','저축 계좌를 개설하고 싶어요.',
 'You need ID to open an account.','계좌를 개설하려면 신분증이 필요해요.',
 'She opened an account at the local bank.','그녀는 지역 은행에서 계좌를 개설했어요.',
 'Can I open an account online?','온라인으로 계좌를 개설할 수 있나요?',
 'He opened a joint account with his spouse.','그는 배우자와 공동 계좌를 개설했어요.',
 'A2','economy',1,'bank account opening teller paperwork desk'),

('col_economy_24','take','loan','take out a loan','대출을 받다','get',
 '"get a loan"도 가능하지만 take out a loan이 더 공식적인 표현이에요.',
 'They took out a loan to buy their first home.','그들은 첫 집을 사기 위해 대출을 받았어요.',
 'I''m thinking of taking out a student loan.','학자금 대출을 받을까 생각 중이에요.',
 'She took out a loan to start her business.','그녀는 사업을 시작하기 위해 대출을 받았어요.',
 'Be careful before you take out a loan.','대출을 받기 전에 신중하세요.',
 'He took out a small loan to cover medical bills.','그는 의료비를 충당하기 위해 소액 대출을 받았어요.',
 'B2','economy',1,'bank loan documents signing mortgage finance'),

-- emotion (col_emotion_24~25)
('col_emotion_24','get','angry','get angry','화가 나다','become',
 '"become angry"는 격식 있는 문어체. 일상에서는 get angry가 훨씬 자연스러워요.',
 'Don''t get angry — let''s talk about it calmly.','화내지 말고 차분히 얘기해요.',
 'She got angry when she heard the rumor.','그녀는 그 소문을 듣고 화가 났어요.',
 'I rarely get angry, but this time I was furious.','저는 거의 화내지 않지만 이번엔 격분했어요.',
 'He gets angry when people are late.','그는 사람들이 늦으면 화를 내요.',
 'Why are you getting angry over such a small thing?','왜 그렇게 사소한 일에 화를 내요?',
 'A2','emotion',1,'angry person frowning frustrated emotion face'),

('col_emotion_25','break','heart','break someone''s heart','마음을 아프게 하다','hurt',
 '"hurt someone''s heart"는 어색해요. 깊이 상심하게 만들 때는 break someone''s heart.',
 'It broke her heart when he moved away.','그가 멀리 이사 갔을 때 그녀의 마음이 찢어졌어요.',
 'Don''t break his heart — be honest from the start.','그의 마음을 아프게 하지 말고 처음부터 솔직해지세요.',
 'The news broke my heart.','그 소식에 마음이 찢어졌어요.',
 'She broke his heart when she ended the relationship.','그녀가 관계를 끝냈을 때 그의 마음을 아프게 했어요.',
 'It broke their hearts to leave their pet behind.','반려동물을 두고 가는 게 그들의 마음을 아프게 했어요.',
 'B2','emotion',1,'broken heart sad goodbye breakup emotion'),

-- discussion (col_discussion_24~25)
('col_discussion_24','have','idea','have an idea','아이디어가 있다','get',
 '"get an idea"는 떠올랐다는 순간의 표현. 보유 중이라는 의미는 have an idea.',
 'I have an idea for our next project.','다음 프로젝트 아이디어가 있어요.',
 'Do you have any idea what time it is?','지금 몇 시인지 짐작이 가요?',
 'She has lots of creative ideas.','그녀는 창의적인 아이디어가 많아요.',
 'I have an idea — let''s try a different approach.','아이디어가 있어요 — 다른 방법을 시도해 봐요.',
 'He had an idea that turned out to be brilliant.','그는 결국 훌륭한 것으로 밝혀진 아이디어가 있었어요.',
 'A1','discussion',1,'lightbulb idea inspiration person thinking'),

('col_discussion_25','take','position','take a position','입장을 정하다','hold',
 '"hold a position"은 자리(직위)를 가진다는 의미. 의견 표명은 take a position on...',
 'She took a strong position on the issue.','그녀는 그 문제에 대해 강한 입장을 정했어요.',
 'It''s time for the company to take a position.','회사가 입장을 정할 때예요.',
 'He took the position that we should wait.','그는 우리가 기다려야 한다는 입장을 취했어요.',
 'Don''t be afraid to take a position in the debate.','토론에서 입장을 정하는 걸 두려워하지 마세요.',
 'The government took a neutral position on the matter.','정부는 그 사안에 중립적 입장을 취했어요.',
 'B2','discussion',1,'debate stance opinion confident speaker'),

-- greeting (col_greeting_22~23)
('col_greeting_22','keep','touch','keep in touch','계속 연락하다','stay',
 '"stay in touch"도 가능. 둘 다 자연스러워요. keep이 약간 더 형식적.',
 'Let''s keep in touch after you move.','이사 가도 계속 연락해요.',
 'We''ve kept in touch for over ten years.','우리는 10년 넘게 연락을 유지해 왔어요.',
 'It''s easier to keep in touch with social media.','SNS 덕분에 연락 유지가 더 쉬워요.',
 'I want to keep in touch with my old classmates.','옛 동창들과 계속 연락하고 싶어요.',
 'Promise me you''ll keep in touch.','계속 연락한다고 약속해 주세요.',
 'B1','greeting',1,'friends phone message keeping in touch communication'),

('col_greeting_23','give','hand','give a hand','도와주다','lend',
 '"lend a hand"도 같은 의미예요. give a hand는 박수치다 의미로도 쓰여서 맥락 주의.',
 'Could you give me a hand with this box?','이 상자 옮기는 거 도와줄 수 있어요?',
 'She always gives a hand when I''m busy.','그녀는 제가 바쁠 때 항상 도와줘요.',
 'He gave us a hand moving into the new apartment.','그는 우리가 새 아파트로 이사하는 것을 도와줬어요.',
 'Let''s give him a hand — he looks overwhelmed.','그를 도와줘요 — 너무 힘들어 보여요.',
 'Thanks for giving me a hand earlier.','아까 도와줘서 고마워요.',
 'B1','greeting',1,'people helping moving box assistance friends'),

-- health (col_health_23~24)
('col_health_23','get','sick','get sick','병에 걸리다, 아프다','become',
 '"become sick"는 문어체. 일상에서는 get sick이 압도적으로 자연스러워요.',
 'I got sick last week and missed three days of work.','지난주에 아파서 3일 결근했어요.',
 'Wash your hands so you don''t get sick.','아프지 않으려면 손을 씻으세요.',
 'She got really sick after the long flight.','그녀는 장거리 비행 후에 정말 아팠어요.',
 'Kids often get sick during the winter.','아이들은 겨울에 자주 아파요.',
 'I got sick from eating something bad.','상한 음식을 먹어서 아팠어요.',
 'A1','health',1,'sick person bed thermometer flu tissue'),

('col_health_24','break','sweat','break a sweat','땀을 흘리다, 힘을 쓰다','have',
 '"have a sweat"는 어색해요. 운동이나 노력으로 땀이 날 때는 break a sweat.',
 'I didn''t even break a sweat during the workout.','운동하면서 땀도 안 났어요.',
 'She broke a sweat just walking up the stairs.','그녀는 계단을 오르기만 해도 땀이 났어요.',
 'The test was so easy — I didn''t break a sweat.','시험이 너무 쉬워서 식은땀도 안 났어요.',
 'You need to break a sweat to see real results.','진짜 결과를 보려면 땀을 흘려야 해요.',
 'He broke a sweat trying to fix the bike.','그는 자전거를 고치려고 진땀을 흘렸어요.',
 'B2','health',1,'person exercising sweating workout effort gym'),

-- transport (col_transport_21~24)
('col_transport_21','catch','bus','catch the bus','버스를 타다 (시간 맞춰)','get',
 '"get the bus"도 영국에서 흔해요. catch는 시간 맞춰 잡아탄다는 뉘앙스.',
 'I have to run to catch the bus.','버스 타려면 뛰어가야 해요.',
 'Did you catch the early bus this morning?','오늘 아침에 일찍 버스 탔어요?',
 'She caught the bus just in time.','그녀는 가까스로 버스를 탔어요.',
 'I missed the bus, so I had to catch the next one.','버스를 놓쳐서 다음 거를 타야 했어요.',
 'We caught the bus to the airport at 6 AM.','우리는 새벽 6시에 공항행 버스를 탔어요.',
 'A2','transport',1,'bus stop person running boarding morning'),

('col_transport_22','miss','train','miss the train','기차를 놓치다','lose',
 '"lose the train"은 틀린 표현. 시간 맞춰 못 탄 건 miss.',
 'I missed the train by just two minutes.','단 2분 차이로 기차를 놓쳤어요.',
 'She missed the last train and had to take a taxi.','그녀는 막차를 놓쳐서 택시를 타야 했어요.',
 'Don''t miss the train — it''s the only one tonight.','기차 놓치지 마세요 — 오늘 밤 유일한 거예요.',
 'They missed the train because of traffic.','그들은 교통 체증 때문에 기차를 놓쳤어요.',
 'I''d rather wait than miss the train.','기차를 놓치느니 차라리 기다릴래요.',
 'A2','transport',1,'train platform missed running late station'),

('col_transport_23','hit','traffic','hit traffic','교통 체증에 걸리다','meet',
 '"meet traffic"은 틀린 표현. 갑자기 교통 체증을 만나면 hit traffic.',
 'We hit terrible traffic on the way home.','집에 오는 길에 끔찍한 교통 체증에 걸렸어요.',
 'I''ll be late — I hit some traffic.','늦을 것 같아요 — 교통 체증에 걸렸어요.',
 'They hit traffic and missed the start of the movie.','그들은 교통 체증에 걸려 영화 시작을 놓쳤어요.',
 'We always hit traffic at this time of day.','이 시간엔 항상 교통 체증에 걸려요.',
 'Leave early so you don''t hit rush hour traffic.','출근 시간 체증에 안 걸리게 일찍 나가세요.',
 'B1','transport',1,'traffic jam cars highway congestion road'),

('col_transport_24','take','flight','take a flight','비행기를 타다','do',
 '"do a flight"은 틀린 표현. 비행기 이용은 take a flight.',
 'I''m taking a flight to Seoul tomorrow.','내일 서울행 비행기를 타요.',
 'She took a red-eye flight to New York.','그녀는 뉴욕행 야간 비행기를 탔어요.',
 'How often do you take flights for work?','업무로 비행기를 얼마나 자주 타세요?',
 'We took a direct flight to avoid layovers.','우리는 경유를 피하려고 직항을 탔어요.',
 'He''s nervous about taking long flights.','그는 장거리 비행을 타는 게 긴장돼요.',
 'A2','transport',1,'airplane airport flight passenger boarding'),

-- cafe (col_cafe_23~24)
('col_cafe_23','order','takeout','order takeout','음식을 포장 주문하다','take',
 '"take takeout"은 어색해요. 포장 주문은 order takeout (미국식). 영국에서는 takeaway.',
 'Let''s order takeout tonight — I''m too tired to cook.','오늘 밤은 포장 주문해요 — 요리하기 너무 피곤해요.',
 'We ordered takeout from our favorite Thai place.','우리는 즐겨 가는 태국 식당에서 포장 주문했어요.',
 'I order takeout twice a week.','저는 일주일에 두 번 포장 주문을 해요.',
 'Did you order takeout for the office?','사무실용 포장 주문했어요?',
 'They ordered takeout instead of going out.','그들은 외출 대신 포장 주문을 했어요.',
 'A2','cafe',1,'takeout containers food delivery bag restaurant'),

('col_cafe_24','grab','bite','grab a bite','간단히 먹다','get',
 '"get a bite"는 살짝 어색. grab a bite는 가볍게 식사 한다는 캐주얼 표현.',
 'Let''s grab a bite before the movie.','영화 보기 전에 간단히 먹어요.',
 'I only have time to grab a bite for lunch.','점심은 간단히 먹을 시간만 있어요.',
 'We grabbed a bite at the food truck.','우리는 푸드트럭에서 간단히 먹었어요.',
 'Do you want to grab a bite after work?','퇴근 후에 간단히 먹을래요?',
 'She grabbed a quick bite between meetings.','그녀는 회의 사이에 간단히 끼니를 때웠어요.',
 'B1','cafe',1,'quick meal snack street food casual eating'),

-- home (col_home_23~24)
('col_home_23','take','nap','take a nap','낮잠을 자다','do',
 '"do a nap"은 틀린 표현. 낮잠은 take a nap.',
 'I usually take a nap after lunch.','저는 보통 점심 후에 낮잠을 자요.',
 'She took a quick nap before the meeting.','그녀는 회의 전에 빠르게 낮잠을 잤어요.',
 'Babies need to take regular naps.','아기들은 정기적으로 낮잠을 자야 해요.',
 'Why don''t you take a nap if you''re tired?','피곤하면 낮잠 좀 자는 게 어때요?',
 'He takes a 20-minute nap to recharge.','그는 충전하려고 20분 낮잠을 자요.',
 'A2','home',1,'person napping sofa cozy resting blanket'),

('col_home_24','throw','party','throw a party','파티를 열다','have',
 '"have a party"도 가능하지만 throw a party가 더 활기차고 자연스러워요.',
 'We''re throwing a party for her birthday.','그녀 생일 파티를 열 거예요.',
 'They threw a huge party last weekend.','그들은 지난 주말 큰 파티를 열었어요.',
 'I''ve never thrown a party at my apartment.','저는 우리 아파트에서 파티를 열어본 적이 없어요.',
 'She loves throwing parties for her friends.','그녀는 친구들에게 파티 열어주는 걸 좋아해요.',
 'Let''s throw a surprise party for him.','그를 위해 깜짝 파티를 열어요.',
 'B1','home',1,'party guests home celebration friends'),

-- culture (col_culture_21~23)
('col_culture_21','watch','movie','watch a movie','영화를 보다','see',
 '"see a movie"는 극장에서 본다는 뉘앙스. 집에서 보는 건 watch a movie가 더 자연스러워요.',
 'Let''s watch a movie tonight.','오늘 밤 영화 봐요.',
 'I watched a great movie on Netflix yesterday.','어제 넷플릭스에서 좋은 영화를 봤어요.',
 'We watched the movie twice — it was that good.','너무 좋아서 영화를 두 번 봤어요.',
 'She watches movies in English to practice.','그녀는 연습 삼아 영어 영화를 봐요.',
 'Have you watched the new Korean movie?','새로 나온 한국 영화 봤어요?',
 'A1','culture',1,'movie watching couch popcorn screen home'),

('col_culture_22','play','music','play music','음악을 연주하다/틀다','do',
 '"do music"은 어색해요. 악기 연주든 음악 재생이든 play music.',
 'He plays music every evening to relax.','그는 매일 저녁 긴장을 풀려고 음악을 틀어요.',
 'She plays beautiful piano music.','그녀는 아름다운 피아노 연주를 해요.',
 'The DJ played music all night long.','DJ가 밤새 음악을 틀었어요.',
 'My neighbor plays music too loud.','옆집 사람이 음악을 너무 크게 틀어요.',
 'Can you play some music while we cook?','요리하는 동안 음악 좀 틀어 줄래요?',
 'A1','culture',1,'music speakers piano playing instrument'),

('col_culture_23','read','book','read a book','책을 읽다','do',
 '"do a book"은 틀린 표현. 독서는 read a book.',
 'I read a book before bed every night.','저는 매일 밤 자기 전에 책을 읽어요.',
 'She read three books during her vacation.','그녀는 휴가 동안 책 세 권을 읽었어요.',
 'Have you read any good books lately?','최근에 좋은 책 읽은 거 있어요?',
 'He read the entire book in one sitting.','그는 한 자리에서 책을 다 읽었어요.',
 'Reading books is a great way to relax.','책 읽기는 좋은 휴식 방법이에요.',
 'A1','culture',1,'person reading book cozy library quiet'),

-- sports (col_sports_21~24)
('col_sports_21','score','goal','score a goal','득점하다','make',
 '"make a goal"은 어색. 축구·하키 등에서 골을 넣는 건 score a goal.',
 'He scored the winning goal in the final minute.','그는 마지막 1분에 결승골을 넣었어요.',
 'She scored two goals in the match.','그녀는 경기에서 두 골을 넣었어요.',
 'The striker scored a beautiful goal.','공격수가 멋진 골을 넣었어요.',
 'They scored a goal from outside the penalty box.','그들은 페널티 박스 밖에서 골을 넣었어요.',
 'It''s rare to score a goal from such a distance.','그렇게 먼 거리에서 골을 넣는 건 드물어요.',
 'A2','sports',1,'soccer goal celebration scored stadium'),

('col_sports_22','win','match','win a match','경기를 이기다','take',
 '"take a match"는 어색. 경기 승리는 win a match.',
 'They won the match 3-1.','그들은 3:1로 경기를 이겼어요.',
 'She won her first match of the season.','그녀는 시즌 첫 경기에서 승리했어요.',
 'We need to win this match to qualify.','우리는 진출하려면 이 경기를 이겨야 해요.',
 'He''s never won a match against her.','그는 그녀를 상대로 경기를 이겨본 적이 없어요.',
 'Winning the match was a huge moment.','그 경기를 이긴 건 엄청난 순간이었어요.',
 'A2','sports',1,'team celebration victory trophy match'),

('col_sports_23','set','record','set a record','기록을 세우다','make',
 '"make a record"는 음반을 만들거나 다른 의미. 신기록은 set a record.',
 'She set a new world record yesterday.','그녀는 어제 새 세계 기록을 세웠어요.',
 'He set a record for the fastest time.','그는 최단 시간 기록을 세웠어요.',
 'The team set a record for most wins this season.','그 팀은 이번 시즌 최다승 기록을 세웠어요.',
 'Setting a record requires years of training.','기록을 세우려면 수년의 훈련이 필요해요.',
 'She set the record while still a teenager.','그녀는 10대 때 그 기록을 세웠어요.',
 'B1','sports',1,'athlete record stadium scoreboard achievement'),

('col_sports_24','break','record','break a record','기록을 깨다','beat',
 '"beat a record"도 쓰이지만 break a record가 더 강력한 표현이에요.',
 'He broke the school''s long jump record.','그는 학교 멀리뛰기 기록을 깼어요.',
 'She broke the world record by 0.3 seconds.','그녀는 0.3초 차이로 세계 기록을 깼어요.',
 'Records are made to be broken.','기록은 깨지기 위해 만들어진다.',
 'The team broke several records this year.','그 팀은 올해 여러 기록을 깼어요.',
 'Few athletes break records in their first year.','첫 해에 기록을 깨는 선수는 드물어요.',
 'B1','sports',1,'athlete record breaking finish line celebration'),

-- technology (col_technology_21~24)
('col_technology_21','send','email','send an email','이메일을 보내다','do',
 '"do an email"은 틀린 표현. 이메일 발송은 send.',
 'I''ll send you an email with the details.','자세한 내용을 이메일로 보내 드릴게요.',
 'She sends emails throughout the day.','그녀는 하루 종일 이메일을 보내요.',
 'Did you send the email to the client?','고객에게 이메일 보냈어요?',
 'Please send an email confirming the booking.','예약 확인 이메일을 보내 주세요.',
 'He sent dozens of emails before noon.','그는 정오 전에 수십 통의 이메일을 보냈어요.',
 'A2','technology',1,'laptop email inbox typing sending'),

('col_technology_22','download','file','download a file','파일을 다운로드하다','take',
 '"take a file"은 다른 의미. 인터넷에서 받는 건 download.',
 'I downloaded the file from the company portal.','회사 포털에서 파일을 다운로드했어요.',
 'Can you download the attached file?','첨부된 파일 다운로드할 수 있어요?',
 'She accidentally downloaded a malicious file.','그녀는 실수로 악성 파일을 다운로드했어요.',
 'It takes a few minutes to download the file.','파일 다운로드에 몇 분 걸려요.',
 'Always scan a file before downloading.','다운로드하기 전에 항상 파일을 검사하세요.',
 'A2','technology',1,'computer download progress bar file transfer'),

('col_technology_23','install','software','install software','소프트웨어를 설치하다','put',
 '"put software"는 어색해요. 컴퓨터 프로그램 설치는 install.',
 'I installed the new design software yesterday.','어제 새 디자인 소프트웨어를 설치했어요.',
 'You need admin rights to install software.','소프트웨어를 설치하려면 관리자 권한이 필요해요.',
 'She installed antivirus software on all computers.','그녀는 모든 컴퓨터에 백신 소프트웨어를 설치했어요.',
 'Don''t install software from unknown sources.','출처 모르는 소프트웨어는 설치하지 마세요.',
 'Installing the software took about ten minutes.','소프트웨어 설치에 약 10분 걸렸어요.',
 'B1','technology',1,'computer installation progress screen software setup'),

('col_technology_24','update','app','update an app','앱을 업데이트하다','refresh',
 '"refresh an app"은 새로고침. 새 버전 적용은 update an app.',
 'I need to update the app — it''s outdated.','앱이 구버전이라 업데이트해야 해요.',
 'She updates her apps automatically.','그녀는 앱을 자동으로 업데이트해요.',
 'Did you update the banking app this week?','이번 주에 은행 앱 업데이트했어요?',
 'You should update apps regularly for security.','보안을 위해 앱을 정기적으로 업데이트해야 해요.',
 'He hates updating apps — they always change.','그는 앱 업데이트를 싫어해요 — 항상 바뀌니까.',
 'A2','technology',1,'phone app update screen download progress'),

-- weather (col_weather_21~22)
('col_weather_21','take','umbrella','take an umbrella','우산을 챙기다','bring',
 '"bring an umbrella"도 가능. take는 가져갈 때, bring은 도착지로 가져갈 때.',
 'Take an umbrella — it''s going to rain.','우산 챙기세요 — 비 올 거예요.',
 'I forgot to take an umbrella this morning.','오늘 아침에 우산 챙기는 걸 잊었어요.',
 'She always takes an umbrella in her bag.','그녀는 항상 가방에 우산을 챙겨 다녀요.',
 'You should take an umbrella just in case.','만일을 대비해 우산 챙기세요.',
 'He took a small umbrella for the hike.','그는 등산을 위해 작은 우산을 챙겼어요.',
 'A2','weather',1,'umbrella rain person walking street'),

('col_weather_22','wear','sunscreen','wear sunscreen','자외선 차단제를 바르다','put',
 '"put sunscreen"도 쓰이지만 wear sunscreen이 더 자연스러워요 (apply도 가능).',
 'Wear sunscreen even on cloudy days.','흐린 날에도 자외선 차단제를 바르세요.',
 'She always wears sunscreen at the beach.','그녀는 해변에서 항상 자외선 차단제를 발라요.',
 'I forgot to wear sunscreen and got a burn.','자외선 차단제 바르는 걸 잊어서 화상 입었어요.',
 'Doctors recommend wearing sunscreen daily.','의사들은 매일 자외선 차단제 바르기를 권장해요.',
 'He wears sunscreen on his face year-round.','그는 일년 내내 얼굴에 자외선 차단제를 발라요.',
 'A2','weather',1,'sunscreen sunny beach skincare protection'),

-- presentation (col_presentation_21~23)
('col_presentation_21','give','speech','give a speech','연설을 하다','do',
 '"do a speech"는 틀린 표현. 연설은 give a speech (또는 deliver a speech 격식체).',
 'She gave a powerful speech at the conference.','그녀는 학회에서 강력한 연설을 했어요.',
 'I have to give a speech at my friend''s wedding.','친구 결혼식에서 축사를 해야 해요.',
 'He gave a speech about climate action.','그는 기후 행동에 관한 연설을 했어요.',
 'Giving a speech in front of strangers is scary.','낯선 사람들 앞에서 연설하는 건 무서워요.',
 'She gave a moving speech that brought tears.','그녀는 눈물을 자아내는 감동적인 연설을 했어요.',
 'B1','presentation',1,'speaker podium speech audience microphone'),

('col_presentation_22','make','point','make a point','요점을 말하다, 강조하다','do',
 '"do a point"는 틀린 표현. 의견·요점을 강조할 때는 make a point.',
 'You made a great point in the meeting.','회의에서 좋은 요점을 짚었어요.',
 'I want to make a point about transparency.','투명성에 관한 요점을 짚고 싶어요.',
 'She made several important points.','그녀는 몇 가지 중요한 요점을 말했어요.',
 'He made the point that we''re running low on time.','그는 우리에게 시간이 부족하다는 점을 강조했어요.',
 'Let me make one more point before we move on.','넘어가기 전에 한 가지만 더 말할게요.',
 'B1','presentation',1,'speaker pointing chart presentation key point'),

('col_presentation_23','answer','questions','answer questions','질문에 답하다','respond',
 '"respond to questions"도 가능 (격식). 일상에서는 answer questions가 자연스러워요.',
 'I''ll answer questions at the end of the presentation.','발표 마지막에 질문에 답할게요.',
 'She answered all the questions confidently.','그녀는 모든 질문에 자신 있게 답했어요.',
 'He refused to answer questions about his past.','그는 자신의 과거에 관한 질문에 답하기를 거부했어요.',
 'Please raise your hand if you want to answer.','답하고 싶으면 손을 들어 주세요.',
 'The CEO answered questions for thirty minutes.','CEO는 30분간 질문에 답했어요.',
 'A2','presentation',1,'Q&A session speaker microphone audience hand raised'),

-- negotiation (col_negotiation_21~23)
('col_negotiation_21','reach','agreement','reach an agreement','합의에 도달하다','make',
 '"make an agreement"는 계약을 체결한다는 의미에 더 가까워요. 합의 과정의 결과는 reach an agreement.',
 'After hours of talks, they reached an agreement.','몇 시간의 협상 끝에 합의에 도달했어요.',
 'We need to reach an agreement by Friday.','금요일까지 합의에 도달해야 해요.',
 'The two parties finally reached an agreement.','두 당사자는 마침내 합의에 도달했어요.',
 'Reaching an agreement on price was the hardest part.','가격 합의가 가장 어려운 부분이었어요.',
 'They couldn''t reach an agreement on terms.','그들은 조건에 대해 합의에 도달하지 못했어요.',
 'B2','negotiation',1,'business handshake agreement contract negotiation'),

('col_negotiation_22','sign','contract','sign a contract','계약서에 서명하다','do',
 '"do a contract"는 어색해요. 계약서 서명은 sign a contract.',
 'We''ll sign the contract tomorrow.','내일 계약서에 서명할 거예요.',
 'Read carefully before you sign a contract.','계약서에 서명하기 전에 신중하게 읽으세요.',
 'She signed the contract without hesitation.','그녀는 망설임 없이 계약서에 서명했어요.',
 'I''m not signing the contract until lawyers review it.','변호사가 검토할 때까지 계약서에 서명하지 않을 거예요.',
 'Both parties signed the contract on Monday.','월요일에 양 당사자가 계약서에 서명했어요.',
 'A2','negotiation',1,'contract signing pen document business'),

('col_negotiation_23','set','deadline','set a deadline','마감일을 정하다','make',
 '"make a deadline"은 마감 시간을 맞춘다는 다른 의미예요. 마감일을 정하는 건 set a deadline.',
 'Let''s set a deadline for the project.','프로젝트 마감일을 정해요.',
 'The boss set a tight deadline.','상사가 빡빡한 마감일을 정했어요.',
 'We set the deadline for end of month.','우리는 마감일을 월말로 정했어요.',
 'Setting a realistic deadline is important.','현실적인 마감일을 정하는 게 중요해요.',
 'She set a deadline that everyone could meet.','그녀는 모두가 맞출 수 있는 마감일을 정했어요.',
 'B1','negotiation',1,'deadline calendar planning office stress'),

-- media (col_media_21~23)
('col_media_21','take','photo','take a photo','사진을 찍다','make',
 '"make a photo"는 어색해요. 사진 촬영은 take a photo (또는 take a picture).',
 'Can you take a photo of us?','우리 사진 좀 찍어 줄 수 있어요?',
 'She took hundreds of photos on her trip.','그녀는 여행에서 수백 장의 사진을 찍었어요.',
 'I love taking photos of sunsets.','저는 석양 사진 찍는 걸 좋아해요.',
 'Don''t take photos in the museum.','박물관에서는 사진을 찍지 마세요.',
 'He took a perfect photo of the city skyline.','그는 도시 스카이라인의 완벽한 사진을 찍었어요.',
 'A1','media',1,'camera photo person photographer landscape'),

('col_media_22','post','comment','post a comment','댓글을 달다','do',
 '"do a comment"는 어색해요. SNS에 댓글 달 때는 post a comment 또는 leave a comment.',
 'She posted a thoughtful comment on the article.','그녀는 그 기사에 사려 깊은 댓글을 달았어요.',
 'I posted a comment but no one replied.','댓글을 달았는데 아무도 답하지 않았어요.',
 'Don''t post negative comments online.','온라인에 부정적인 댓글을 달지 마세요.',
 'He posts comments on every photo she shares.','그는 그녀가 공유하는 모든 사진에 댓글을 달아요.',
 'I post comments to support creators I follow.','제가 팔로우하는 크리에이터를 응원하려고 댓글을 달아요.',
 'A2','media',1,'phone social media comment section typing'),

('col_media_23','share','link','share a link','링크를 공유하다','send',
 '"send a link"도 가능하지만 1:1 메신저에 가까운 느낌. 공개 공유는 share a link.',
 'Could you share the link with the team?','팀에 그 링크를 공유해 줄 수 있어요?',
 'I shared the article link on social media.','SNS에 그 기사 링크를 공유했어요.',
 'She shared a link to a great podcast.','그녀는 좋은 팟캐스트 링크를 공유했어요.',
 'Don''t share links from suspicious websites.','의심스러운 사이트의 링크는 공유하지 마세요.',
 'He shared the link with everyone in the group chat.','그는 그룹 채팅의 모두에게 링크를 공유했어요.',
 'A2','media',1,'phone link sharing social media chat'),

-- news (col_news_21~23)
('col_news_21','break','news','break news','뉴스를 전하다, 속보를 알리다','tell',
 '"tell news"는 평범한 전달. break the news는 (특히 어려운/큰) 소식을 알린다는 의미.',
 'Who''s going to break the news to her?','누가 그녀에게 그 소식을 전할 거예요?',
 'The journalist broke the news first.','그 기자가 속보를 가장 먼저 전했어요.',
 'I''m sorry to break the news, but he passed away.','이런 소식 전해 미안하지만, 그가 세상을 떠나셨어요.',
 'She broke the news of her resignation today.','그녀는 오늘 사임 소식을 전했어요.',
 'The network broke the news of the merger.','그 방송사가 합병 소식을 가장 먼저 전했어요.',
 'B1','news',1,'breaking news reporter studio screen broadcast'),

('col_news_22','follow','story','follow a story','뉴스 이야기를 따라가다','chase',
 '"chase a story"는 기자가 취재 활동하는 거예요. 일반 시청자가 뉴스를 따라가는 건 follow.',
 'I''ve been following this story for weeks.','이 뉴스 이야기를 몇 주째 따라가고 있어요.',
 'It''s hard to follow the story when details keep changing.','세부 사항이 계속 바뀌어서 따라가기 어려워요.',
 'She follows political stories closely.','그녀는 정치 뉴스를 면밀히 따라가요.',
 'Let''s follow this story to see how it ends.','어떻게 끝나는지 보려고 이 뉴스를 따라가요.',
 'I stopped following the story — too depressing.','그 뉴스 따라가는 거 그만뒀어요 — 너무 우울해서요.',
 'B1','news',1,'newspaper headlines reader following story tracking'),

('col_news_23','cover','event','cover an event','행사를 취재하다','do',
 '"do an event"는 행사 자체를 진행한다는 의미. 취재·보도는 cover an event.',
 'Major networks covered the event live.','주요 방송사들이 그 행사를 생중계 취재했어요.',
 'She covered the Olympics for the newspaper.','그녀는 그 신문사를 위해 올림픽을 취재했어요.',
 'I''m sending a reporter to cover the event.','기자를 보내 그 행사를 취재할 거예요.',
 'They covered the protest from multiple angles.','그들은 여러 각도에서 시위를 취재했어요.',
 'No journalists covered the small ceremony.','어떤 기자도 그 작은 의식을 취재하지 않았어요.',
 'B2','news',1,'reporter camera microphone event coverage live'),

-- environment (col_environment_21~23)
('col_environment_21','plant','tree','plant a tree','나무를 심다','grow',
 '"grow a tree"는 키운다는 의미. 처음 심는 건 plant a tree.',
 'We planted a tree in the backyard.','뒤뜰에 나무를 심었어요.',
 'She plants a tree every year on her birthday.','그녀는 매년 생일에 나무를 심어요.',
 'The community planted hundreds of trees.','지역 사회는 수백 그루의 나무를 심었어요.',
 'Planting a tree is a small but meaningful act.','나무를 심는 건 작지만 의미 있는 행동이에요.',
 'They planted trees to restore the forest.','그들은 숲을 복원하기 위해 나무를 심었어요.',
 'A2','environment',1,'planting tree garden shovel earth nature'),

('col_environment_22','reduce','waste','reduce waste','쓰레기를 줄이다','cut',
 '"cut waste"도 가능하지만 환경 맥락에서는 reduce waste가 표준 표현이에요.',
 'We need to reduce waste at home and work.','집과 직장에서 쓰레기를 줄여야 해요.',
 'She reduces waste by composting food scraps.','그녀는 음식 찌꺼기를 퇴비화해서 쓰레기를 줄여요.',
 'The company is trying to reduce waste in production.','회사는 생산 과정에서 쓰레기 줄이기를 시도해요.',
 'Simple changes can reduce waste significantly.','간단한 변화로도 쓰레기를 크게 줄일 수 있어요.',
 'How can we reduce waste in this office?','이 사무실에서 어떻게 쓰레기를 줄일 수 있을까요?',
 'B1','environment',1,'recycling bins waste reduction sustainability green'),

('col_environment_23','protect','nature','protect nature','자연을 보호하다','save',
 '"save nature"도 가능하지만 protect nature가 더 자연스러운 일상 표현이에요.',
 'It''s our duty to protect nature.','자연을 보호하는 건 우리의 의무예요.',
 'They work hard to protect nature in the park.','그들은 공원의 자연을 보호하기 위해 열심히 일해요.',
 'Protecting nature starts with small actions.','자연 보호는 작은 행동에서 시작해요.',
 'We must protect nature for future generations.','미래 세대를 위해 자연을 보호해야 해요.',
 'Volunteers help protect nature in this reserve.','자원봉사자들이 이 보호 구역의 자연 보호를 도와요.',
 'A2','environment',1,'nature forest conservation protected green landscape')

ON CONFLICT (id) DO NOTHING;
