-- EngCat Patterns — greeting topic, ex1~ex5 backfill (hand-written)
-- Target: 42 patterns × 5 examples (en + ko) = 210 example sentences
-- Style: natural B1-B2 English, polite Korean (해요/입니다)
-- Run once in Supabase SQL Editor

-- ══════════════════════════════════════
-- GREETING — A1
-- ══════════════════════════════════════
UPDATE sentences SET ex1 = 'Nice to meet you, Mr. Park — I''ve been looking forward to today.', ex1_ko = '만나서 반갑습니다, 박 선생님 — 오늘을 기다리고 있었어요.', ex2 = 'Nice to meet you! I''m Jiwon, your new neighbor.', ex2_ko = '만나서 반가워요! 저는 새 이웃 지원이에요.', ex3 = 'Nice to meet you — Minho has told me so much about your work.', ex3_ko = '만나서 반가워요 — 민호한테 일하시는 얘기 정말 많이 들었어요.', ex4 = 'Nice to meet you in person finally, after all those emails.', ex4_ko = '그 많던 이메일 끝에 드디어 직접 만나서 반갑습니다.', ex5 = 'Nice to meet you! Please feel free to call me Sarah.', ex5_ko = '만나서 반가워요! 그냥 사라라고 불러 주세요.' WHERE id = 's_greeting_A1_01';
UPDATE sentences SET ex1 = 'How are you? I haven''t seen you since last Christmas.', ex1_ko = '어떻게 지내세요? 작년 크리스마스 이후로 못 봤네요.', ex2 = 'How are you today, Ms. Kim? Did you have a good weekend?', ex2_ko = '오늘 어떻게 지내세요, 김 선생님? 주말은 잘 보내셨어요?', ex3 = 'How are you? You look like you''ve been busy lately.', ex3_ko = '어떻게 지내세요? 요즘 바빠 보이시네요.', ex4 = 'How are you? I heard you started a new job last month.', ex4_ko = '어떻게 지내세요? 지난달에 새 직장 시작하셨다고 들었어요.', ex5 = 'How are you doing? Long time no see!', ex5_ko = '어떻게 지내세요? 진짜 오랜만이에요!' WHERE id = 's_greeting_A1_02';
UPDATE sentences SET ex1 = 'Good morning! How are you today? It''s a beautiful day, isn''t it?', ex1_ko = '좋은 아침이에요! 오늘 어떻게 지내세요? 날씨가 정말 좋네요, 그렇죠?', ex2 = 'Good morning, everyone! How are you today? Ready for the meeting?', ex2_ko = '좋은 아침이에요, 여러분! 오늘 어떻게 지내세요? 회의 준비됐어요?', ex3 = 'Good morning, Mr. Lee! How are you today? Did you sleep well?', ex3_ko = '좋은 아침이에요, 이 선생님! 오늘 어떻게 지내세요? 잘 주무셨어요?', ex4 = 'Good morning! How are you today? You look much better than yesterday.', ex4_ko = '좋은 아침이에요! 오늘 어떻게 지내세요? 어제보다 훨씬 좋아 보이시네요.', ex5 = 'Good morning, Sue! How are you today? Hope you had your coffee.', ex5_ko = '좋은 아침이에요, 수! 오늘 어떻게 지내세요? 커피는 드셨길 바라요.' WHERE id = 's_greeting_A1_03';
UPDATE sentences SET ex1 = 'My name is Suyeon. What''s your name?', ex1_ko = '제 이름은 수연이에요. 성함이 어떻게 되세요?', ex2 = 'Hi, my name is David. What''s your name? Are you here for the workshop?', ex2_ko = '안녕하세요, 제 이름은 데이비드예요. 성함이 어떻게 되세요? 워크숍 때문에 오셨어요?', ex3 = 'My name is Hana — I''m new here. What''s your name?', ex3_ko = '제 이름은 하나예요 — 여기 처음이에요. 성함이 어떻게 되세요?', ex4 = 'My name is Joon. What''s your name? Which class are you in?', ex4_ko = '제 이름은 준이에요. 성함이 어떻게 되세요? 어떤 반이세요?', ex5 = 'My name is Mr. Choi. What''s your name, young man?', ex5_ko = '제 이름은 최 선생이에요. 성함이 어떻게 되시나요, 학생?' WHERE id = 's_greeting_A1_04';
UPDATE sentences SET ex1 = 'Thank you so much for the gift! You''re very kind.', ex1_ko = '선물 정말 감사해요! 정말 친절하시네요.', ex2 = 'Thank you so much for helping me move yesterday. You''re very kind.', ex2_ko = '어제 이사 도와주셔서 정말 감사해요. 정말 친절하시네요.', ex3 = 'Thank you so much for staying late with me. You''re very kind.', ex3_ko = '저랑 늦게까지 같이 있어 주셔서 정말 감사해요. 정말 친절하시네요.', ex4 = 'Thank you so much for the warm welcome! You''re very kind.', ex4_ko = '따뜻하게 맞아 주셔서 정말 감사해요! 정말 친절하시네요.', ex5 = 'Thank you so much for the home-cooked meal — you''re very kind.', ex5_ko = '집밥 차려 주셔서 정말 감사해요 — 정말 친절하시네요.' WHERE id = 's_greeting_A1_05';
UPDATE sentences SET ex1 = 'Goodbye! See you later — I had a great time tonight.', ex1_ko = '안녕히 가세요! 나중에 봐요 — 오늘 밤 정말 즐거웠어요.', ex2 = 'Goodbye, everyone! See you later at the cafe!', ex2_ko = '여러분 안녕히 가세요! 카페에서 이따 봐요!', ex3 = 'Goodbye, Mom! See you later this weekend.', ex3_ko = '엄마 안녕히 계세요! 이번 주말에 봐요.', ex4 = 'Goodbye! See you later — text me when you get home, okay?', ex4_ko = '안녕히 가세요! 나중에 봐요 — 집에 도착하면 문자해요, 알았죠?', ex5 = 'Goodbye! See you later — drive safely!', ex5_ko = '안녕히 가세요! 나중에 봐요 — 운전 조심히 하세요!' WHERE id = 's_greeting_A1_06';
UPDATE sentences SET ex1 = 'I''m sorry, I don''t understand. Can you say that again more slowly?', ex1_ko = '죄송해요, 이해를 못 했어요. 좀 더 천천히 다시 말씀해 주시겠어요?', ex2 = 'I''m sorry, I don''t understand. Can you say that again in English?', ex2_ko = '죄송해요, 이해를 못 했어요. 영어로 다시 말씀해 주시겠어요?', ex3 = 'I''m sorry, I don''t understand the question. Can you say that again?', ex3_ko = '죄송해요, 질문을 이해 못 했어요. 다시 말씀해 주시겠어요?', ex4 = 'I''m sorry, I don''t understand the last word. Can you say that again?', ex4_ko = '죄송해요, 마지막 단어를 이해 못 했어요. 다시 말씀해 주시겠어요?', ex5 = 'I''m sorry, I don''t understand — the line is bad. Can you say that again?', ex5_ko = '죄송해요, 이해 못 했어요 — 연결 상태가 안 좋아요. 다시 말씀해 주시겠어요?' WHERE id = 's_greeting_A1_07';

-- ══════════════════════════════════════
-- GREETING — A2
-- ══════════════════════════════════════
UPDATE sentences SET ex1 = 'Let me introduce myself — I''m Jiyeon and I work as a designer at a startup.', ex1_ko = '제 소개를 할게요 — 저는 지연이고 스타트업에서 디자이너로 일해요.', ex2 = 'Let me introduce myself — I''m Mark and I work as a translator from home.', ex2_ko = '제 소개를 할게요 — 저는 마크이고 집에서 번역가로 일해요.', ex3 = 'Let me introduce myself before we start — I''m Hyunwoo and I work as an engineer.', ex3_ko = '시작하기 전에 제 소개를 할게요 — 저는 현우이고 엔지니어로 일해요.', ex4 = 'Let me introduce myself properly — I''m Soyeon and I work as a music teacher.', ex4_ko = '제대로 제 소개를 할게요 — 저는 소연이고 음악 선생님으로 일해요.', ex5 = 'Let me introduce myself — I''m Daniel and I work as a freelance writer.', ex5_ko = '제 소개를 할게요 — 저는 다니엘이고 프리랜서 작가로 일해요.' WHERE id = 's_greeting_A2_01';
UPDATE sentences SET ex1 = 'It''s lovely to meet you. I''ve heard a lot about you from your sister.', ex1_ko = '만나서 반가워요. 동생분한테 얘기 많이 들었어요.', ex2 = 'It''s lovely to meet you, Dr. Han. I''ve heard a lot about your research.', ex2_ko = '만나서 반가워요, 한 박사님. 연구에 관한 얘기 많이 들었어요.', ex3 = 'It''s lovely to meet you. I''ve heard a lot about you from the team.', ex3_ko = '만나서 반가워요. 팀원들한테 얘기 많이 들었어요.', ex4 = 'It''s lovely to meet you. I''ve heard a lot about your travels in Europe.', ex4_ko = '만나서 반가워요. 유럽 여행 얘기 많이 들었어요.', ex5 = 'It''s lovely to meet you. I''ve heard a lot about your cooking — Junho can''t stop talking about it.', ex5_ko = '만나서 반가워요. 요리 얘기 많이 들었어요 — 준호가 계속 얘기하더라고요.' WHERE id = 's_greeting_A2_02';
UPDATE sentences SET ex1 = 'Please call me Sue. It''s easier than my full name, Soohyun.', ex1_ko = '그냥 수라고 불러 주세요. 풀네임 수현보다 편해요.', ex2 = 'Please call me Tom. It''s easier than Thomas Edward Lawrence.', ex2_ko = '그냥 톰이라고 불러 주세요. 토마스 에드워드 로렌스보다 편해요.', ex3 = 'Please call me Jay. It''s easier than my full name in Korean.', ex3_ko = '그냥 제이라고 불러 주세요. 한국어 풀네임보다 편해요.', ex4 = 'Please call me Ms. Park. It''s easier than my full title in the office.', ex4_ko = '그냥 박 매니저라고 불러 주세요. 사무실 정식 직함보다 편해요.', ex5 = 'Please call me by my first name. It''s easier than the formal one.', ex5_ko = '이름으로 그냥 불러 주세요. 격식 있는 호칭보다 편해요.' WHERE id = 's_greeting_A2_03';
UPDATE sentences SET ex1 = 'It was great seeing you. Take care — and say hi to your family for me.', ex1_ko = '만나서 좋았어요. 잘 지내요 — 가족분들께도 안부 전해 주세요.', ex2 = 'It was great seeing you again after so long. Take care!', ex2_ko = '오랜만에 다시 만나서 좋았어요. 잘 지내요!', ex3 = 'It was great seeing you tonight. Take care driving home.', ex3_ko = '오늘 밤 만나서 좋았어요. 운전 조심해서 가세요.', ex4 = 'It was great seeing you at the wedding. Take care, and we''ll catch up soon.', ex4_ko = '결혼식에서 만나서 좋았어요. 잘 지내요, 곧 다시 만나요.', ex5 = 'It was great seeing you at the conference. Take care and keep in touch.', ex5_ko = '컨퍼런스에서 만나서 좋았어요. 잘 지내고 연락해요.' WHERE id = 's_greeting_A2_04';
UPDATE sentences SET ex1 = 'I''m originally from Busan but I''ve lived in Seoul for ten years. Where are you from?', ex1_ko = '저는 원래 부산 출신인데 서울에서 10년 살았어요. 어디서 오셨어요?', ex2 = 'I''m originally from a small town near Daegu. Where are you from?', ex2_ko = '저는 원래 대구 근처의 작은 동네 출신이에요. 어디서 오셨어요?', ex3 = 'I''m originally from Jeju Island, actually. Where are you from?', ex3_ko = '저는 사실 원래 제주도 출신이에요. 어디서 오셨어요?', ex4 = 'I''m originally from Canada but I moved here after college. Where are you from?', ex4_ko = '저는 원래 캐나다 출신인데 대학 졸업하고 여기로 왔어요. 어디서 오셨어요?', ex5 = 'I''m originally from a coastal city. Where are you from? You sound like you''re not from around here.', ex5_ko = '저는 원래 바닷가 도시 출신이에요. 어디서 오셨어요? 여기 분 같지 않으셔서요.' WHERE id = 's_greeting_A2_05';
UPDATE sentences SET ex1 = 'Would you mind if I joined you for lunch? The other tables are all full.', ex1_ko = '점심 합석해도 될까요? 다른 자리는 다 찼어요.', ex2 = 'Would you mind if I joined you on the walk back to the office?', ex2_ko = '사무실 돌아가는 길에 같이 걸어가도 될까요?', ex3 = 'Would you mind if I joined you at this table? It looks like a quiet spot.', ex3_ko = '이 자리에 합석해도 될까요? 조용해 보여서요.', ex4 = 'Would you mind if I joined you on the project? I have some free time.', ex4_ko = '그 프로젝트에 함께 해도 될까요? 시간이 좀 있어서요.', ex5 = 'Would you mind if I joined you for a drink after work tonight?', ex5_ko = '오늘 퇴근 후에 같이 한잔해도 될까요?' WHERE id = 's_greeting_A2_06';
UPDATE sentences SET ex1 = 'Thanks for having me — I really enjoyed the dinner and conversation.', ex1_ko = '초대해 주셔서 감사해요 — 저녁과 대화 정말 즐거웠어요.', ex2 = 'Thanks for having me at your housewarming — I really enjoyed it.', ex2_ko = '집들이에 초대해 주셔서 감사해요 — 정말 즐거웠어요.', ex3 = 'Thanks for having me on the show today — I really enjoyed our chat.', ex3_ko = '오늘 방송에 초대해 주셔서 감사해요 — 대화 정말 즐거웠어요.', ex4 = 'Thanks for having me over for the weekend — I really enjoyed it.', ex4_ko = '주말 동안 초대해 주셔서 감사해요 — 정말 즐거웠어요.', ex5 = 'Thanks for having me at the office tour — I really enjoyed it.', ex5_ko = '사무실 투어에 초대해 주셔서 감사해요 — 정말 즐거웠어요.' WHERE id = 's_greeting_A2_07';

-- ══════════════════════════════════════
-- GREETING — B1
-- ══════════════════════════════════════
UPDATE sentences SET ex1 = 'I don''t think we''ve been formally introduced — I''m Jihye, the new project manager.', ex1_ko = '공식적으로 소개받지 못한 것 같아요 — 저는 새 프로젝트 매니저 지혜예요.', ex2 = 'I don''t think we''ve been formally introduced — I''m Lucas, Hana''s husband.', ex2_ko = '공식적으로 소개받지 못한 것 같아요 — 저는 하나 남편 루카스예요.', ex3 = 'I don''t think we''ve been formally introduced, though I''ve seen you around — I''m Soomin.', ex3_ko = '본 적은 있지만 공식적으로 소개받지 못한 것 같아요 — 저는 수민이에요.', ex4 = 'I don''t think we''ve been formally introduced at the meetings — I''m from the design team.', ex4_ko = '회의에서 공식적으로 소개받지 못한 것 같아요 — 디자인팀에서 일해요.', ex5 = 'I don''t think we''ve been formally introduced, although we''ve emailed before — I''m Mira.', ex5_ko = '이메일로는 주고받았지만 공식적으로 소개받지는 못한 것 같아요 — 저는 미라예요.' WHERE id = 's_greeting_B1_01';
UPDATE sentences SET ex1 = 'It''s great to finally put a face to the name — your emails have been so helpful.', ex1_ko = '드디어 얼굴을 보게 되어 반가워요 — 이메일이 정말 도움이 됐어요.', ex2 = 'It''s great to finally put a face to the name. I''ve been working with you for months!', ex2_ko = '드디어 얼굴을 보게 되어 반가워요. 몇 달 동안 같이 일했었네요!', ex3 = 'It''s great to finally put a face to the name after all those phone calls.', ex3_ko = '그렇게 많이 통화한 끝에 드디어 얼굴을 보게 되어 반가워요.', ex4 = 'It''s great to finally put a face to the name — you sound just like you do on Zoom.', ex4_ko = '드디어 얼굴을 보게 되어 반가워요 — 줌으로 들었을 때랑 목소리가 똑같으시네요.', ex5 = 'It''s great to finally put a face to the name. I imagined you taller, somehow.', ex5_ko = '드디어 얼굴을 보게 되어 반가워요. 왠지 키가 더 크실 줄 알았는데요.' WHERE id = 's_greeting_B1_02';
UPDATE sentences SET ex1 = 'I believe we have some mutual friends — do you know Sangwoo from the engineering team?', ex1_ko = '공통 친구가 있는 것 같은데요 — 엔지니어링 팀의 상우 아세요?', ex2 = 'I believe we have some mutual friends — do you know Sumin? She used to work with you.', ex2_ko = '공통 친구가 있는 것 같은데요 — 수민 아세요? 같이 일하셨었어요.', ex3 = 'I believe we have some mutual friends — do you know the Park sisters from college?', ex3_ko = '공통 친구가 있는 것 같은데요 — 대학 시절 박씨 자매들 아세요?', ex4 = 'I believe we have some mutual friends — do you know Jenny from the climbing gym?', ex4_ko = '공통 친구가 있는 것 같은데요 — 클라이밍짐의 제니 아세요?', ex5 = 'I believe we have some mutual friends — do you know anyone from the Wednesday book club?', ex5_ko = '공통 친구가 있는 것 같은데요 — 수요일 독서모임에 아는 분 있으세요?' WHERE id = 's_greeting_B1_03';
UPDATE sentences SET ex1 = 'Long time no see! How have you been keeping since the kids started school?', ex1_ko = '오랜만이에요! 아이들 학교 들어간 뒤로 어떻게 지내셨어요?', ex2 = 'Long time no see! How have you been keeping? I heard you moved to Seoul.', ex2_ko = '오랜만이에요! 그동안 어떻게 지내셨어요? 서울로 이사가셨다고 들었어요.', ex3 = 'Long time no see! How have you been keeping since the company restructuring?', ex3_ko = '오랜만이에요! 회사 구조조정 이후로 어떻게 지내셨어요?', ex4 = 'Long time no see! How have you been keeping? You look really well.', ex4_ko = '오랜만이에요! 그동안 어떻게 지내셨어요? 정말 좋아 보이시네요.', ex5 = 'Long time no see! How have you been keeping these days? Still painting?', ex5_ko = '오랜만이에요! 요즘 어떻게 지내세요? 아직 그림 그리세요?' WHERE id = 's_greeting_B1_04';
UPDATE sentences SET ex1 = 'Allow me to introduce my colleague, Mr. Choi, who heads our research division.', ex1_ko = '저희 연구 부서를 이끄는 동료 최 부장님을 소개해 드릴게요.', ex2 = 'Allow me to introduce my colleague, Jiyeon — she''ll be joining the negotiations.', ex2_ko = '제 동료 지연을 소개해 드릴게요 — 협상에 함께 참여할 거예요.', ex3 = 'Allow me to introduce my colleague, Dr. Han, who specializes in machine learning.', ex3_ko = '머신러닝을 전공하시는 동료 한 박사님을 소개해 드릴게요.', ex4 = 'Allow me to introduce my colleague, Soyoung — she''ll be your point of contact today.', ex4_ko = '제 동료 소영을 소개해 드릴게요 — 오늘 담당으로 도와드릴 거예요.', ex5 = 'Allow me to introduce my colleague, Mark, who flew in from London this morning.', ex5_ko = '오늘 아침 런던에서 오신 동료 마크를 소개해 드릴게요.' WHERE id = 's_greeting_B1_05';
UPDATE sentences SET ex1 = 'I''ve been looking forward to this meeting for a while — your proposal is impressive.', ex1_ko = '이 만남을 한동안 기대하고 있었어요 — 제안서가 인상적이었어요.', ex2 = 'I''ve been looking forward to this meeting for a while, especially after reading your book.', ex2_ko = '이 만남을 한동안 기대하고 있었어요, 특히 책을 읽고 나서요.', ex3 = 'I''ve been looking forward to this meeting for a while — Jung-ho mentioned your ideas.', ex3_ko = '이 만남을 한동안 기대하고 있었어요 — 정호가 아이디어 얘기를 해주더라고요.', ex4 = 'I''ve been looking forward to this meeting for a while, ever since we connected on LinkedIn.', ex4_ko = '링크드인에서 연락드린 이후로 이 만남을 한동안 기대하고 있었어요.', ex5 = 'I''ve been looking forward to this meeting for a while — thank you for making time.', ex5_ko = '이 만남을 한동안 기대하고 있었어요 — 시간 내주셔서 감사해요.' WHERE id = 's_greeting_B1_06';
UPDATE sentences SET ex1 = 'It was wonderful catching up — we should do this more often, maybe every month.', ex1_ko = '근황 나눠서 좋았어요 — 더 자주, 한 달에 한 번씩 만나요.', ex2 = 'It was wonderful catching up — we should do this more often, not just at weddings.', ex2_ko = '근황 나눠서 좋았어요 — 결혼식에서만 만나지 말고 더 자주 만나요.', ex3 = 'It was wonderful catching up after all these years — we should do this more often.', ex3_ko = '오랜만에 근황 나눠서 좋았어요 — 더 자주 만나요.', ex4 = 'It was wonderful catching up over dinner — we should do this more often.', ex4_ko = '저녁 먹으면서 근황 나눠서 좋았어요 — 더 자주 만나요.', ex5 = 'It was wonderful catching up at the reunion — we should do this more often.', ex5_ko = '동창회에서 근황 나눠서 좋았어요 — 더 자주 만나요.' WHERE id = 's_greeting_B1_07';

-- ══════════════════════════════════════
-- GREETING — B2
-- ══════════════════════════════════════
UPDATE sentences SET ex1 = 'On behalf of our organization, it is my pleasure to welcome you to our annual conference.', ex1_ko = '저희 기관을 대표하여 연례 컨퍼런스에 여러분을 환영해 드립니다.', ex2 = 'On behalf of the entire team, it is my pleasure to welcome you to your first day.', ex2_ko = '팀 전체를 대표하여 첫 출근을 환영해 드립니다.', ex3 = 'On behalf of our school, it is my pleasure to welcome you to the new semester.', ex3_ko = '저희 학교를 대표하여 새 학기를 맞아 여러분을 환영해 드립니다.', ex4 = 'On behalf of the host country, it is my pleasure to welcome our distinguished guests.', ex4_ko = '주최국을 대표하여 귀한 손님들을 환영해 드립니다.', ex5 = 'On behalf of the board, it is my pleasure to welcome our new chairman.', ex5_ko = '이사회를 대표하여 새 의장님을 환영해 드립니다.' WHERE id = 's_greeting_B2_01';
UPDATE sentences SET ex1 = 'Your reputation precedes you — it''s an honor to finally meet the founder of this company.', ex1_ko = '명성은 익히 들었어요 — 이 회사 창립자를 드디어 만나게 되어 영광이에요.', ex2 = 'Your reputation precedes you, Professor — it''s an honor to finally meet you in person.', ex2_ko = '교수님 명성은 익히 들었어요 — 직접 만나게 되어 영광이에요.', ex3 = 'Your reputation precedes you in this industry — it''s an honor to finally meet.', ex3_ko = '이 업계에서 명성은 익히 들었어요 — 드디어 만나게 되어 영광이에요.', ex4 = 'Your reputation precedes you as a kind teacher — it''s an honor to finally meet you.', ex4_ko = '훌륭한 선생님이시라는 명성은 익히 들었어요 — 드디어 만나게 되어 영광이에요.', ex5 = 'Your reputation precedes you, of course — it''s an honor to finally meet face to face.', ex5_ko = '물론 명성은 익히 들었어요 — 드디어 마주하게 되어 영광이에요.' WHERE id = 's_greeting_B2_02';
UPDATE sentences SET ex1 = 'I''ve heard excellent things about your work in this field — your last paper especially.', ex1_ko = '이 분야에서 하신 일에 대해 정말 좋은 이야기를 들었어요 — 특히 지난 논문이요.', ex2 = 'I''ve heard excellent things about your work in this field from several colleagues.', ex2_ko = '이 분야에서 하신 일에 대해 여러 동료들한테서 정말 좋은 이야기를 들었어요.', ex3 = 'I''ve heard excellent things about your work in this field — the documentary was inspiring.', ex3_ko = '이 분야에서 하신 일에 대해 정말 좋은 이야기를 들었어요 — 다큐멘터리가 감동적이었어요.', ex4 = 'I''ve heard excellent things about your work in this field, especially the new framework.', ex4_ko = '이 분야에서 하신 일에 대해 정말 좋은 이야기를 들었어요, 특히 새 프레임워크요.', ex5 = 'I''ve heard excellent things about your work in this field for years now.', ex5_ko = '이 분야에서 하신 일에 대해 몇 년째 정말 좋은 이야기를 들었어요.' WHERE id = 's_greeting_B2_03';
UPDATE sentences SET ex1 = 'Please, allow me to extend a warm welcome on this occasion of your retirement.', ex1_ko = '귀하의 정년퇴임을 맞은 이 자리에서 따뜻한 환영의 말씀을 전할 수 있어 기쁩니다.', ex2 = 'Please, allow me to extend a warm welcome on behalf of the alumni association.', ex2_ko = '동문회를 대표하여 따뜻한 환영의 말씀을 전할 수 있어 기쁩니다.', ex3 = 'Please, allow me to extend a warm welcome on this very special evening.', ex3_ko = '이 매우 특별한 저녁 자리에서 따뜻한 환영의 말씀을 전할 수 있어 기쁩니다.', ex4 = 'Please, allow me to extend a warm welcome on this milestone occasion.', ex4_ko = '이 기념비적인 자리에서 따뜻한 환영의 말씀을 전할 수 있어 기쁩니다.', ex5 = 'Please, allow me to extend a warm welcome to all of you who travelled to be here.', ex5_ko = '여기까지 와 주신 여러분께 따뜻한 환영의 말씀을 전할 수 있어 기쁩니다.' WHERE id = 's_greeting_B2_04';
UPDATE sentences SET ex1 = 'We are delighted to have such distinguished guests with us today at the launch.', ex1_ko = '오늘 출시 행사에 이렇게 귀한 분들과 함께할 수 있어 기쁩니다.', ex2 = 'We are delighted to have such distinguished guests joining us from overseas.', ex2_ko = '해외에서 오신 이렇게 귀한 분들과 함께할 수 있어 기쁩니다.', ex3 = 'We are delighted to have such distinguished guests at our anniversary dinner.', ex3_ko = '저희 기념 만찬에 이렇게 귀한 분들과 함께할 수 있어 기쁩니다.', ex4 = 'We are delighted to have such distinguished guests grace our humble venue.', ex4_ko = '저희 소박한 자리에 이렇게 귀한 분들과 함께할 수 있어 기쁩니다.', ex5 = 'We are delighted to have such distinguished guests in attendance this evening.', ex5_ko = '오늘 저녁 이렇게 귀한 분들이 참석해 주셔서 기쁩니다.' WHERE id = 's_greeting_B2_05';
UPDATE sentences SET ex1 = 'I was hoping we''d get a chance to connect at this event — your panel was fascinating.', ex1_ko = '이 행사에서 연락이 닿을 기회를 바라고 있었어요 — 패널 발표가 흥미로웠어요.', ex2 = 'I was hoping we''d get a chance to connect at this event — let''s grab coffee tomorrow?', ex2_ko = '이 행사에서 연락이 닿을 기회를 바라고 있었어요 — 내일 커피 어떠세요?', ex3 = 'I was hoping we''d get a chance to connect at this event before everyone leaves.', ex3_ko = '모두가 떠나기 전에 이 행사에서 연락이 닿을 기회를 바라고 있었어요.', ex4 = 'I was hoping we''d get a chance to connect at this event — Jay mentioned you''d be here.', ex4_ko = '이 행사에서 연락이 닿을 기회를 바라고 있었어요 — 제이가 오신다고 했어요.', ex5 = 'I was hoping we''d get a chance to connect at this event — we have a lot to discuss.', ex5_ko = '이 행사에서 연락이 닿을 기회를 바라고 있었어요 — 얘기 나눌 게 많아서요.' WHERE id = 's_greeting_B2_06';
UPDATE sentences SET ex1 = 'It''s been far too long — I''m so glad we managed to reconnect at this reunion.', ex1_ko = '너무 오래됐어요 — 이번 동창회에서 다시 연락이 닿아서 정말 기뻐요.', ex2 = 'It''s been far too long — I''m so glad we managed to reconnect after the move.', ex2_ko = '너무 오래됐어요 — 이사 후에 다시 연락이 닿아서 정말 기뻐요.', ex3 = 'It''s been far too long — I''m so glad we managed to reconnect through Instagram.', ex3_ko = '너무 오래됐어요 — 인스타그램으로 다시 연락이 닿아서 정말 기뻐요.', ex4 = 'It''s been far too long — I''m so glad we managed to reconnect for your wedding.', ex4_ko = '너무 오래됐어요 — 결혼식 덕분에 다시 연락이 닿아서 정말 기뻐요.', ex5 = 'It''s been far too long — I''m so glad we managed to reconnect over the holidays.', ex5_ko = '너무 오래됐어요 — 명절 동안 다시 연락이 닿아서 정말 기뻐요.' WHERE id = 's_greeting_B2_07';

-- ══════════════════════════════════════
-- GREETING — C1
-- ══════════════════════════════════════
UPDATE sentences SET ex1 = 'It is a distinct honor to be in the company of such accomplished individuals tonight.', ex1_ko = '오늘 밤 이렇게 탁월한 분들과 함께하게 된 것은 특별한 영광입니다.', ex2 = 'It is a distinct honor to be in the company of such accomplished individuals at this symposium.', ex2_ko = '이 심포지엄에서 이렇게 탁월한 분들과 함께하게 된 것은 특별한 영광입니다.', ex3 = 'It is a distinct honor to be in the company of such accomplished individuals from across the globe.', ex3_ko = '전 세계에서 모인 이렇게 탁월한 분들과 함께하게 된 것은 특별한 영광입니다.', ex4 = 'It is a distinct honor to be in the company of such accomplished individuals representing our field.', ex4_ko = '저희 분야를 대표하는 이렇게 탁월한 분들과 함께하게 된 것은 특별한 영광입니다.', ex5 = 'It is a distinct honor to be in the company of such accomplished individuals, mentors and pioneers alike.', ex5_ko = '멘토이자 선구자이신 이렇게 탁월한 분들과 함께하게 된 것은 특별한 영광입니다.' WHERE id = 's_greeting_C1_01';
UPDATE sentences SET ex1 = 'Your contributions to the field are well recognized and deeply appreciated by all of us here.', ex1_ko = '이 분야에 대한 귀하의 공헌은 이 자리의 모두에게 널리 인정받고 깊이 감사하게 여겨지고 있습니다.', ex2 = 'Your contributions to the field are well recognized and deeply appreciated, especially the early work.', ex2_ko = '이 분야에 대한 귀하의 공헌은 널리 인정받고 깊이 감사하게 여겨지고 있으며, 특히 초창기 연구가 그렇습니다.', ex3 = 'Your contributions to the field are well recognized and deeply appreciated by the next generation.', ex3_ko = '이 분야에 대한 귀하의 공헌은 다음 세대에게 널리 인정받고 깊이 감사하게 여겨지고 있습니다.', ex4 = 'Your contributions to the field are well recognized and deeply appreciated across borders.', ex4_ko = '이 분야에 대한 귀하의 공헌은 국경을 넘어 널리 인정받고 깊이 감사하게 여겨지고 있습니다.', ex5 = 'Your contributions to the field are well recognized and deeply appreciated by this institution.', ex5_ko = '이 분야에 대한 귀하의 공헌은 본 기관에서 널리 인정받고 깊이 감사하게 여겨지고 있습니다.' WHERE id = 's_greeting_C1_02';
UPDATE sentences SET ex1 = 'Permit me to extend my sincerest greetings and warmest regards on behalf of the foundation.', ex1_ko = '재단을 대표하여 진심 어린 인사와 따뜻한 안부를 전하도록 허락해 주십시오.', ex2 = 'Permit me to extend my sincerest greetings and warmest regards to your esteemed delegation.', ex2_ko = '귀하의 영예로운 사절단에 진심 어린 인사와 따뜻한 안부를 전하도록 허락해 주십시오.', ex3 = 'Permit me to extend my sincerest greetings and warmest regards on this auspicious day.', ex3_ko = '이 길한 날에 진심 어린 인사와 따뜻한 안부를 전하도록 허락해 주십시오.', ex4 = 'Permit me to extend my sincerest greetings and warmest regards to all attending dignitaries.', ex4_ko = '참석하신 모든 귀빈께 진심 어린 인사와 따뜻한 안부를 전하도록 허락해 주십시오.', ex5 = 'Permit me to extend my sincerest greetings and warmest regards as we open this assembly.', ex5_ko = '이 자리를 여는 데 있어 진심 어린 인사와 따뜻한 안부를 전하도록 허락해 주십시오.' WHERE id = 's_greeting_C1_03';
UPDATE sentences SET ex1 = 'I must say, your presence here lends a great deal of prestige to this event, Ambassador.', ex1_ko = '솔직히 말씀드리면, 대사님 참석이 이 행사에 큰 품격을 더해 줍니다.', ex2 = 'I must say, your presence here lends a great deal of prestige to this gala dinner.', ex2_ko = '솔직히 말씀드리면, 귀하의 참석이 이 갈라 만찬에 큰 품격을 더해 줍니다.', ex3 = 'I must say, your presence here lends a great deal of prestige to our humble award ceremony.', ex3_ko = '솔직히 말씀드리면, 귀하의 참석이 저희 소박한 시상식에 큰 품격을 더해 줍니다.', ex4 = 'I must say, your presence here lends a great deal of prestige to the inaugural lecture.', ex4_ko = '솔직히 말씀드리면, 귀하의 참석이 이 개회 강연에 큰 품격을 더해 줍니다.', ex5 = 'I must say, your presence here lends a great deal of prestige to today''s proceedings.', ex5_ko = '솔직히 말씀드리면, 귀하의 참석이 오늘 일정에 큰 품격을 더해 줍니다.' WHERE id = 's_greeting_C1_04';
UPDATE sentences SET ex1 = 'It goes without saying that we are truly privileged to have you among us this evening.', ex1_ko = '귀하를 오늘 저녁 모실 수 있다는 것은 두말할 나위 없이 큰 영광입니다.', ex2 = 'It goes without saying that we are truly privileged to have you among us, Dr. Lee.', ex2_ko = '이 박사님을 모실 수 있다는 것은 두말할 나위 없이 큰 영광입니다.', ex3 = 'It goes without saying that we are truly privileged to have you among us at this critical juncture.', ex3_ko = '이 중요한 시점에 귀하를 모실 수 있다는 것은 두말할 나위 없이 큰 영광입니다.', ex4 = 'It goes without saying that we are truly privileged to have you among us as our keynote speaker.', ex4_ko = '귀하를 기조연설자로 모실 수 있다는 것은 두말할 나위 없이 큰 영광입니다.', ex5 = 'It goes without saying that we are truly privileged to have you among us at our centennial.', ex5_ko = '저희 100주년 기념식에 귀하를 모실 수 있다는 것은 두말할 나위 없이 큰 영광입니다.' WHERE id = 's_greeting_C1_05';
UPDATE sentences SET ex1 = 'Your eloquence and expertise have long been an inspiration to those of us in this field of law.', ex1_ko = '귀하의 표현력과 전문성은 법조계의 우리에게 오랫동안 영감이 되어 왔습니다.', ex2 = 'Your eloquence and expertise have long been an inspiration to those of us in this field of journalism.', ex2_ko = '귀하의 표현력과 전문성은 언론계의 우리에게 오랫동안 영감이 되어 왔습니다.', ex3 = 'Your eloquence and expertise have long been an inspiration to those of us in this field of medicine.', ex3_ko = '귀하의 표현력과 전문성은 의료계의 우리에게 오랫동안 영감이 되어 왔습니다.', ex4 = 'Your eloquence and expertise have long been an inspiration to those of us in this field of diplomacy.', ex4_ko = '귀하의 표현력과 전문성은 외교계의 우리에게 오랫동안 영감이 되어 왔습니다.', ex5 = 'Your eloquence and expertise have long been an inspiration to those of us in this field of education.', ex5_ko = '귀하의 표현력과 전문성은 교육계의 우리에게 오랫동안 영감이 되어 왔습니다.' WHERE id = 's_greeting_C1_06';
UPDATE sentences SET ex1 = 'I hope this occasion will mark the beginning of a fruitful and enduring relationship between our institutions.', ex1_ko = '이 자리가 양 기관 간의 풍요롭고 오래 지속될 관계의 시작이 되기를 바랍니다.', ex2 = 'I hope this occasion will mark the beginning of a fruitful and enduring partnership.', ex2_ko = '이 자리가 풍요롭고 오래 지속될 파트너십의 시작이 되기를 바랍니다.', ex3 = 'I hope this occasion will mark the beginning of a fruitful and enduring collaboration between our nations.', ex3_ko = '이 자리가 양국 간의 풍요롭고 오래 지속될 협력의 시작이 되기를 바랍니다.', ex4 = 'I hope this occasion will mark the beginning of a fruitful and enduring exchange of ideas.', ex4_ko = '이 자리가 풍요롭고 오래 지속될 아이디어 교류의 시작이 되기를 바랍니다.', ex5 = 'I hope this occasion will mark the beginning of a fruitful and enduring dialogue.', ex5_ko = '이 자리가 풍요롭고 오래 지속될 대화의 시작이 되기를 바랍니다.' WHERE id = 's_greeting_C1_07';

-- ══════════════════════════════════════
-- GREETING — C2
-- ══════════════════════════════════════
UPDATE sentences SET ex1 = 'We are gathered here today to honor an individual whose contributions have shaped the very fabric of our discipline.', ex1_ko = '오늘 우리는 우리 학문의 근본 자체를 만들어온 인물을 기리기 위해 이 자리에 모였습니다.', ex2 = 'We are gathered here today to honor a leader whose vision has shaped the very fabric of modern policy.', ex2_ko = '오늘 우리는 현대 정책의 근본 자체를 만들어온 지도자를 기리기 위해 이 자리에 모였습니다.', ex3 = 'We are gathered here today to honor a teacher whose dedication has shaped the very fabric of this school.', ex3_ko = '오늘 우리는 이 학교의 근본 자체를 만들어온 선생님을 기리기 위해 이 자리에 모였습니다.', ex4 = 'We are gathered here today to honor a pioneer whose research has shaped the very fabric of artificial intelligence.', ex4_ko = '오늘 우리는 인공지능의 근본 자체를 만들어온 선구자를 기리기 위해 이 자리에 모였습니다.', ex5 = 'We are gathered here today to honor an artist whose work has shaped the very fabric of contemporary culture.', ex5_ko = '오늘 우리는 현대 문화의 근본 자체를 만들어온 예술가를 기리기 위해 이 자리에 모였습니다.' WHERE id = 's_greeting_C2_01';
UPDATE sentences SET ex1 = 'The distinction and gravitas you bring to this assembly are, without exaggeration, unparalleled in our time.', ex1_ko = '귀하가 이 자리에 가져오시는 품격과 위엄은, 과장 없이 말씀드리면, 우리 시대에 비할 데가 없습니다.', ex2 = 'The distinction and gravitas you bring to this assembly are, without exaggeration, unparalleled in living memory.', ex2_ko = '귀하가 이 자리에 가져오시는 품격과 위엄은, 과장 없이 말씀드리면, 기억하는 한 비할 데가 없습니다.', ex3 = 'The distinction and gravitas you bring to this assembly are, without exaggeration, unparalleled in academic life.', ex3_ko = '귀하가 이 자리에 가져오시는 품격과 위엄은, 과장 없이 말씀드리면, 학계에서 비할 데가 없습니다.', ex4 = 'The distinction and gravitas you bring to this assembly are, without exaggeration, unparalleled among your peers.', ex4_ko = '귀하가 이 자리에 가져오시는 품격과 위엄은, 과장 없이 말씀드리면, 동료들 중에 비할 데가 없습니다.', ex5 = 'The distinction and gravitas you bring to this assembly are, without exaggeration, unparalleled across generations.', ex5_ko = '귀하가 이 자리에 가져오시는 품격과 위엄은, 과장 없이 말씀드리면, 세대를 가로질러 비할 데가 없습니다.' WHERE id = 's_greeting_C2_02';
UPDATE sentences SET ex1 = 'Allow me to formally inaugurate this meeting with a word of profound gratitude for your esteemed presence.', ex1_ko = '귀하의 영예로운 참석에 깊은 감사의 말씀으로 이 회의를 공식적으로 개회하도록 허락해 주십시오.', ex2 = 'Allow me to formally inaugurate this conference with a word of profound gratitude for your tireless work.', ex2_ko = '귀하의 헌신적인 노고에 깊은 감사의 말씀으로 이 컨퍼런스를 공식적으로 개회하도록 허락해 주십시오.', ex3 = 'Allow me to formally inaugurate this ceremony with a word of profound gratitude to all the donors.', ex3_ko = '모든 후원자분들께 깊은 감사의 말씀으로 이 행사를 공식적으로 개회하도록 허락해 주십시오.', ex4 = 'Allow me to formally inaugurate this academic year with a word of profound gratitude for your dedication.', ex4_ko = '여러분의 헌신에 깊은 감사의 말씀으로 새 학년도를 공식적으로 개회하도록 허락해 주십시오.', ex5 = 'Allow me to formally inaugurate this gathering with a word of profound gratitude for the founders.', ex5_ko = '창립자분들께 깊은 감사의 말씀으로 이 모임을 공식적으로 개회하도록 허락해 주십시오.' WHERE id = 's_greeting_C2_03';
UPDATE sentences SET ex1 = 'Seldom has it been my privilege to stand before an assembly of such rare collective wisdom and experience.', ex1_ko = '이처럼 드문 집단적 지혜와 경험을 가진 자리 앞에 설 수 있는 영광은 쉽사리 주어지지 않습니다.', ex2 = 'Seldom has it been my privilege to stand before an audience of such distinguished scholars.', ex2_ko = '이처럼 뛰어난 학자들 앞에 설 수 있는 영광은 쉽사리 주어지지 않습니다.', ex3 = 'Seldom has it been my privilege to stand before a gathering of such moral courage and integrity.', ex3_ko = '이처럼 도덕적 용기와 진정성을 가진 분들 앞에 설 수 있는 영광은 쉽사리 주어지지 않습니다.', ex4 = 'Seldom has it been my privilege to stand before a panel of such legendary practitioners.', ex4_ko = '이처럼 전설적인 분들 앞에 설 수 있는 영광은 쉽사리 주어지지 않습니다.', ex5 = 'Seldom has it been my privilege to stand before friends of such longstanding loyalty.', ex5_ko = '이처럼 오랜 의리를 지켜온 친구들 앞에 설 수 있는 영광은 쉽사리 주어지지 않습니다.' WHERE id = 's_greeting_C2_04';
UPDATE sentences SET ex1 = 'May I take this opportunity to convey, on behalf of all present, our deepest respect and admiration to the laureate.', ex1_ko = '이 자리를 빌려, 여기 계신 모든 분들을 대표하여 수상자께 가장 깊은 존경과 감사를 전하고자 합니다.', ex2 = 'May I take this opportunity to convey, on behalf of the faculty, our deepest respect and admiration.', ex2_ko = '이 자리를 빌려, 교수진을 대표하여 가장 깊은 존경과 감사를 전하고자 합니다.', ex3 = 'May I take this opportunity to convey, on behalf of the alumni, our deepest respect and admiration for the late dean.', ex3_ko = '이 자리를 빌려, 동문을 대표하여 故 학장님께 가장 깊은 존경과 감사를 전하고자 합니다.', ex4 = 'May I take this opportunity to convey, on behalf of every member here, our deepest respect and admiration for your service.', ex4_ko = '이 자리를 빌려, 여기 모든 회원을 대표하여 귀하의 봉사에 가장 깊은 존경과 감사를 전하고자 합니다.', ex5 = 'May I take this opportunity to convey, on behalf of the institute, our deepest respect and admiration for your lifetime of work.', ex5_ko = '이 자리를 빌려, 본 연구소를 대표하여 평생의 업적에 가장 깊은 존경과 감사를 전하고자 합니다.' WHERE id = 's_greeting_C2_05';
UPDATE sentences SET ex1 = 'Your stewardship of this discipline has been nothing short of exemplary, and your presence here today is a testament to that legacy.', ex1_ko = '이 학문에 대한 귀하의 헌신은 더할 나위 없이 모범적이었으며, 오늘 이 자리의 참석이 그 유산을 증명합니다.', ex2 = 'Your stewardship of this organization has been nothing short of exemplary, and your presence here today is a testament to that legacy.', ex2_ko = '이 기관에 대한 귀하의 헌신은 더할 나위 없이 모범적이었으며, 오늘 이 자리의 참석이 그 유산을 증명합니다.', ex3 = 'Your stewardship of this profession has been nothing short of exemplary, and your presence here today is a testament to that legacy.', ex3_ko = '이 직업에 대한 귀하의 헌신은 더할 나위 없이 모범적이었으며, 오늘 이 자리의 참석이 그 유산을 증명합니다.', ex4 = 'Your stewardship of this community has been nothing short of exemplary, and your presence here today is a testament to that legacy.', ex4_ko = '이 공동체에 대한 귀하의 헌신은 더할 나위 없이 모범적이었으며, 오늘 이 자리의 참석이 그 유산을 증명합니다.', ex5 = 'Your stewardship of this cause has been nothing short of exemplary, and your presence here today is a testament to that legacy.', ex5_ko = '이 대의에 대한 귀하의 헌신은 더할 나위 없이 모범적이었으며, 오늘 이 자리의 참석이 그 유산을 증명합니다.' WHERE id = 's_greeting_C2_06';
UPDATE sentences SET ex1 = 'It is with the utmost reverence and collegial warmth that I bid you welcome to this convocation.', ex1_ko = '최고의 경의와 동료적 따뜻함으로 이 모임에 여러분을 환영합니다.', ex2 = 'It is with the utmost reverence and collegial warmth that I bid you welcome to this commencement.', ex2_ko = '최고의 경의와 동료적 따뜻함으로 이 졸업식에 여러분을 환영합니다.', ex3 = 'It is with the utmost reverence and collegial warmth that I bid you welcome to this learned society.', ex3_ko = '최고의 경의와 동료적 따뜻함으로 이 학회에 여러분을 환영합니다.', ex4 = 'It is with the utmost reverence and collegial warmth that I bid you welcome to this distinguished gathering.', ex4_ko = '최고의 경의와 동료적 따뜻함으로 이 영예로운 모임에 여러분을 환영합니다.', ex5 = 'It is with the utmost reverence and collegial warmth that I bid you welcome to our centenary celebration.', ex5_ko = '최고의 경의와 동료적 따뜻함으로 저희 100주년 기념식에 여러분을 환영합니다.' WHERE id = 's_greeting_C2_07';
