-- EngCat — Economy (경제) 단어 & 패턴 데이터
-- 210 words (35 per CEFR level: A1~C2) + 42 patterns (7 per level)
-- Generated: 2026-05-24

-- ══════════════════════════════════════
-- WORDS — A1 (기초: 돈·가격·구매)
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_economy_A1_01','money','/ˈmʌni/','noun','돈','Coins or notes used to pay for things.','Do you have {money} with you?','돈 가지고 있어요?','money','A1','economy',1,'money coins bills wallet cash'),
('w_economy_A1_02','price','/praɪs/','noun','가격','The amount of money required to buy something.','What is the {price} of this jacket?','이 재킷의 가격이 얼마예요?','price','A1','economy',1,'price tag shopping retail store'),
('w_economy_A1_03','buy','/baɪ/','verb','사다','To get something by paying money for it.','I want to {buy} a new phone.','새 휴대폰을 사고 싶어요.','buy','A1','economy',1,'shopping buying store purchase'),
('w_economy_A1_04','sell','/sel/','verb','팔다','To exchange something for money.','They {sell} fresh vegetables here.','여기서 신선한 채소를 팔아요.','sell','A1','economy',1,'market selling vendor stall produce'),
('w_economy_A1_05','pay','/peɪ/','verb','지불하다','To give money in exchange for goods or services.','Can I {pay} by credit card?','신용카드로 계산할 수 있나요?','pay','A1','economy',1,'payment cashier counter card terminal'),
('w_economy_A1_06','cheap','/tʃiːp/','adjective','저렴한','Low in price; not expensive.','This market has very {cheap} fruit.','이 시장에는 아주 저렴한 과일이 있어요.','cheap','A1','economy',1,'cheap market bargain low price sale'),
('w_economy_A1_07','save','/seɪv/','verb','저축하다','To keep money instead of spending it.','I try to {save} a little each month.','매달 조금씩 저축하려고 해요.','save','A1','economy',1,'piggy bank saving money jar coins'),
('w_economy_A1_08','bank','/bæŋk/','noun','은행','A place where people keep and borrow money.','I need to go to the {bank} today.','오늘 은행에 가야 해요.','bank','A1','economy',1,'bank building finance ATM entrance'),
('w_economy_A1_09','cost','/kɒst/','verb','(비용이) 들다','To have a particular price.','How much does it {cost}?','얼마예요?','cost','A1','economy',1,'price label receipt shopping cost'),
('w_economy_A1_10','spend','/spend/','verb','쓰다','To use money to pay for something.','I don''t want to {spend} too much today.','오늘 너무 많이 쓰고 싶지 않아요.','spend','A1','economy',1,'spending wallet shopping budget'),
('w_economy_A1_11','cash','/kæʃ/','noun','현금','Money in the form of coins or banknotes.','Do you accept {cash} or only cards?','현금도 받나요, 아니면 카드만 되나요?','cash','A1','economy',1,'cash banknotes currency hand payment'),
('w_economy_A1_12','free','/friː/','adjective','무료의','Costing nothing.','Is the Wi-Fi {free} here?','여기 와이파이 무료예요?','free','A1','economy',2,'free sign promotion offer gift'),
('w_economy_A1_13','change','/tʃeɪndʒ/','noun','거스름돈','Money returned when you pay more than the cost.','Here is your {change}.','거스름돈 받으세요.','change','A1','economy',2,'coins change receipt cashier counter'),
('w_economy_A1_14','shop','/ʃɒp/','noun','가게','A place where goods are sold.','There is a nice little {shop} nearby.','근처에 아담한 가게가 있어요.','shop','A1','economy',2,'small shop storefront retail street'),
('w_economy_A1_15','bill','/bɪl/','noun','지폐; 청구서','A piece of paper money; or a request for payment.','Could I have the {bill}, please?','계산서 주세요.','bill','A1','economy',1,'restaurant bill receipt paper payment'),
('w_economy_A1_16','coin','/kɔɪn/','noun','동전','A small metal disc used as money.','I only have {coins} in my pocket.','주머니에 동전밖에 없어요.','coin','A1','economy',2,'coins pocket change metal currency'),
('w_economy_A1_17','wallet','/ˈwɒlɪt/','noun','지갑','A small flat case for carrying money and cards.','I left my {wallet} at home.','지갑을 집에 두고 왔어요.','wallet','A1','economy',2,'wallet leather cards money pocket'),
('w_economy_A1_18','receipt','/rɪˈsiːt/','noun','영수증','A piece of paper confirming payment.','Can I have a {receipt}?','영수증 받을 수 있나요?','receipt','A1','economy',2,'receipt paper store cashier transaction'),
('w_economy_A1_19','market','/ˈmɑːrkɪt/','noun','시장','A place where goods are bought and sold.','The {market} opens at seven.','시장은 7시에 열어요.','market','A1','economy',1,'outdoor market fresh produce stalls people'),
('w_economy_A1_20','expensive','/ɪkˈspensɪv/','adjective','비싼','Costing a lot of money.','This restaurant is too {expensive} for me.','이 식당은 저한테 너무 비싸요.','expensive','A1','economy',1,'luxury expensive store high price display'),
('w_economy_A1_21','discount','/ˈdɪskaʊnt/','noun','할인','A reduction in the usual price.','Is there a student {discount}?','학생 할인이 있나요?','discount','A1','economy',2,'sale discount tag sign store retail'),
('w_economy_A1_22','sale','/seɪl/','noun','세일','A period when goods are sold at reduced prices.','Everything is on {sale} this weekend.','이번 주말에 모든 상품이 세일이에요.','sale','A1','economy',2,'sale sign shop window retail bargain'),
('w_economy_A1_23','afford','/əˈfɔːrd/','verb','(돈이 있어) ~할 수 있다','To have enough money to pay for something.','I can''t {afford} a new car right now.','지금은 새 차를 살 여유가 없어요.','afford','A1','economy',2,'thinking budget person worried finance'),
('w_economy_A1_24','total','/ˈtoʊtl/','noun','합계','The complete sum of an amount.','The {total} comes to thirty dollars.','합계가 30달러예요.','total','A1','economy',2,'receipt total checkout shopping payment'),
('w_economy_A1_25','fee','/fiː/','noun','수수료; 요금','A charge for a service.','There is an entry {fee} of five dollars.','5달러의 입장료가 있어요.','fee','A1','economy',2,'fee sign entrance payment ticket'),
('w_economy_A1_26','gift','/ɡɪft/','noun','선물','Something given without payment.','I bought a {gift} for my friend.','친구에게 선물을 샀어요.','gift','A1','economy',3,'gift wrap present box ribbon shopping'),
('w_economy_A1_27','order','/ˈɔːrdər/','verb','주문하다','To request something to be made or supplied.','I''d like to {order} the blue one.','파란 것으로 주문하고 싶어요.','order','A1','economy',2,'online order shopping delivery package'),
('w_economy_A1_28','price tag','/praɪs tæɡ/','noun','가격표','A label attached to an item showing its price.','Let me check the {price tag}.','가격표를 확인해 볼게요.','price tag','A1','economy',3,'price tag retail clothing store label'),
('w_economy_A1_29','ATM','/ˌeɪ tiː ˈem/','noun','자동화기기 (현금인출기)','A machine that dispenses cash from a bank account.','Is there an {ATM} nearby?','근처에 ATM이 있나요?','ATM','A1','economy',2,'ATM cash machine bank street'),
('w_economy_A1_30','borrow','/ˈbɒroʊ/','verb','빌리다','To take and use something that belongs to someone else.','Can I {borrow} some money until Friday?','금요일까지 돈 좀 빌릴 수 있을까요?','borrow','A1','economy',2,'borrowing lending hand money help'),
('w_economy_A1_31','lend','/lend/','verb','빌려주다','To give something to someone temporarily.','Could you {lend} me a few dollars?','몇 달러만 빌려줄 수 있어요?','lend','A1','economy',2,'lending hand giving money friend help'),
('w_economy_A1_32','exchange','/ɪkˈstʃeɪndʒ/','noun','환전; 교환','Converting one currency to another; or swapping goods.','Where can I {exchange} my money?','어디서 환전할 수 있나요?','exchange','A1','economy',2,'currency exchange counter travel money'),
('w_economy_A1_33','rich','/rɪtʃ/','adjective','부유한','Having a lot of money.','She is very {rich} and owns many businesses.','그녀는 매우 부유하고 많은 사업체를 가지고 있어요.','rich','A1','economy',3,'wealthy luxury car mansion success'),
('w_economy_A1_34','poor','/pʊər/','adjective','가난한','Having little money.','Many people are still very {poor}.','아직도 많은 사람들이 매우 가난해요.','poor','A1','economy',3,'poverty street urban hardship community'),
('w_economy_A1_35','number','/ˈnʌmbər/','noun','숫자','A mathematical value used to count or calculate.','What {number} should I call?','어떤 번호로 전화해야 하나요?','number','A1','economy',3,'numbers calculator math finance digits')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — A2 (초급: 저축·대출·수입)
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_economy_A2_01','tax','/tæks/','noun','세금','Money that must be paid to the government.','The price includes {tax}.','가격에 세금이 포함되어 있어요.','tax','A2','economy',1,'tax form documents government finance'),
('w_economy_A2_02','income','/ˈɪnkʌm/','noun','수입','Money received regularly from work or investments.','My monthly {income} is enough to cover my expenses.','월 수입이 생활비를 충당하기에 충분해요.','income','A2','economy',1,'income salary paycheck money earning'),
('w_economy_A2_03','budget','/ˈbʌdʒɪt/','noun','예산','A plan for how to spend money.','I need to stick to my {budget} this month.','이번 달은 예산을 지켜야 해요.','budget','A2','economy',1,'budget planning notebook spreadsheet finance'),
('w_economy_A2_04','profit','/ˈprɒfɪt/','noun','이익','Money made after costs are paid.','The company made a big {profit} last year.','그 회사는 작년에 큰 이익을 냈어요.','profit','A2','economy',1,'profit growth chart business success'),
('w_economy_A2_05','loan','/loʊn/','noun','대출','Money borrowed from a bank that must be repaid.','I took out a {loan} to buy my car.','차를 사려고 대출을 받았어요.','loan','A2','economy',1,'loan bank signature document agreement'),
('w_economy_A2_06','credit','/ˈkredɪt/','noun','신용; 외상','The ability to borrow money based on trust.','My {credit} score is very good.','제 신용 점수는 아주 좋아요.','credit','A2','economy',1,'credit card score finance bank'),
('w_economy_A2_07','invest','/ɪnˈvest/','verb','투자하다','To put money into something to make more money.','It is smart to {invest} in your education.','교육에 투자하는 것은 현명해요.','invest','A2','economy',1,'investing money growth chart arrow up'),
('w_economy_A2_08','earn','/ɜːrn/','verb','(돈을) 벌다','To receive money as payment for work.','How much do you {earn} a month?','한 달에 얼마나 버나요?','earn','A2','economy',1,'earning money work office salary'),
('w_economy_A2_09','debt','/det/','noun','빚, 부채','Money owed to someone.','I want to pay off all my {debt} by next year.','내년까지 모든 빚을 갚고 싶어요.','debt','A2','economy',1,'debt stressed worried bills payment'),
('w_economy_A2_10','salary','/ˈsæləri/','noun','월급, 급여','Fixed regular payment from an employer.','My {salary} is paid at the end of each month.','급여는 매월 말에 지급돼요.','salary','A2','economy',1,'salary paycheck office work compensation'),
('w_economy_A2_11','account','/əˈkaʊnt/','noun','계좌','An arrangement with a bank to deposit or borrow money.','I just opened a new bank {account}.','방금 새 은행 계좌를 개설했어요.','account','A2','economy',2,'bank account card application form'),
('w_economy_A2_12','interest','/ˈɪntrəst/','noun','이자','Extra money paid for borrowing or earned from saving.','The {interest} on this loan is quite high.','이 대출의 이자가 꽤 높아요.','interest','A2','economy',1,'interest rate bank chart percentage'),
('w_economy_A2_13','rent','/rent/','noun','임대료, 집세','Regular payment for using a property.','The {rent} goes up every year.','임대료가 매년 올라요.','rent','A2','economy',1,'apartment rent keys housing building'),
('w_economy_A2_14','insurance','/ɪnˈʃʊərəns/','noun','보험','A contract providing financial protection against loss.','I have health {insurance} through my company.','회사를 통해 건강 보험이 있어요.','insurance','A2','economy',2,'insurance document pen signing protection'),
('w_economy_A2_15','refund','/ˈriːfʌnd/','noun','환불','Money returned after returning goods or cancelling.','Can I get a {refund} on this?','이것 환불받을 수 있나요?','refund','A2','economy',2,'refund receipt customer service counter'),
('w_economy_A2_16','deposit','/dɪˈpɒzɪt/','noun','보증금; 입금','Money paid as security or placed in a bank account.','I paid a {deposit} for the apartment.','아파트 보증금을 냈어요.','deposit','A2','economy',2,'deposit bank teller counter transaction'),
('w_economy_A2_17','withdraw','/wɪðˈdrɔː/','verb','인출하다','To take money out of a bank account.','I need to {withdraw} some cash.','현금을 좀 인출해야 해요.','withdraw','A2','economy',2,'ATM withdraw cash machine bank'),
('w_economy_A2_18','transfer','/ˈtrænsfɜːr/','verb','이체하다','To move money from one account to another.','Can you {transfer} the money by tomorrow?','내일까지 돈을 이체해 줄 수 있나요?','transfer','A2','economy',2,'bank transfer mobile phone app finance'),
('w_economy_A2_19','pension','/ˈpenʃən/','noun','연금','Regular payment to retired people.','My grandfather lives on his {pension}.','우리 할아버지는 연금으로 생활하세요.','pension','A2','economy',2,'elderly pension retirement savings comfortable'),
('w_economy_A2_20','tip','/tɪp/','noun','팁, 봉사료','Extra money given to a worker for good service.','Should I leave a {tip}?','팁을 남겨야 하나요?','tip','A2','economy',2,'restaurant tip cash service waiter'),
('w_economy_A2_21','wage','/weɪdʒ/','noun','임금 (시급)','Money paid for work, especially hourly.','The minimum {wage} was raised this year.','최저 임금이 올해 인상됐어요.','wage','A2','economy',1,'wage work factory labor salary'),
('w_economy_A2_22','raise','/reɪz/','noun','임금 인상','An increase in salary.','I asked my boss for a {raise}.','상사에게 임금 인상을 요청했어요.','raise','A2','economy',2,'salary raise office meeting discussion'),
('w_economy_A2_23','charge','/tʃɑːrdʒ/','verb','청구하다','To ask for a payment for goods or services.','How much do you {charge} for delivery?','배달료는 얼마예요?','charge','A2','economy',2,'charge payment service fee receipt'),
('w_economy_A2_24','afford','/əˈfɔːrd/','verb','여유가 되다','To have enough money to pay for something.','I can {afford} to travel once a year.','1년에 한 번은 여행할 여유가 돼요.','afford','A2','economy',2,'budget travel planning holiday finance'),
('w_economy_A2_25','mortgage','/ˈmɔːrɡɪdʒ/','noun','주택 담보 대출','A loan to buy a property.','We applied for a {mortgage} last week.','지난주에 주택 담보 대출을 신청했어요.','mortgage','A2','economy',2,'house mortgage keys bank loan home'),
('w_economy_A2_26','invest in','/ɪnˈvest ɪn/','phrase','~에 투자하다','To spend money on something expecting a future return.','She decided to {invest in} real estate.','그녀는 부동산에 투자하기로 결정했어요.','invest in','A2','economy',2,'real estate investment property chart'),
('w_economy_A2_27','fixed cost','/fɪkst kɒst/','noun','고정 비용','A cost that does not change, such as rent.','Rent is our biggest {fixed cost}.','임대료가 우리의 가장 큰 고정 비용이에요.','fixed cost','A2','economy',3,'budget fixed cost rent bills planning'),
('w_economy_A2_28','expense','/ɪkˈspens/','noun','지출, 경비','Money spent for a particular purpose.','Business {expenses} must be reported.','사업 경비는 신고해야 해요.','expense','A2','economy',2,'expense report receipt business documents'),
('w_economy_A2_29','coupon','/ˈkuːpɒn/','noun','쿠폰','A voucher giving a discount on goods.','I have a {coupon} for twenty percent off.','20% 할인 쿠폰이 있어요.','coupon','A2','economy',3,'coupon discount voucher shopping saving'),
('w_economy_A2_30','value','/ˈvæljuː/','noun','가치','The worth of something in money or importance.','The {value} of this painting has doubled.','이 그림의 가치가 두 배로 올랐어요.','value','A2','economy',2,'value art investment worth gallery'),
('w_economy_A2_31','profit margin','/ˈprɒfɪt ˌmɑːrdʒɪn/','noun','수익률','The percentage of revenue that is profit.','Our {profit margin} is around fifteen percent.','우리의 수익률은 약 15%예요.','profit margin','A2','economy',3,'profit margin chart business analytics'),
('w_economy_A2_32','currency','/ˈkɜːrənsi/','noun','통화, 화폐','The money used in a particular country.','The {currency} in Japan is the yen.','일본의 통화는 엔이에요.','currency','A2','economy',2,'currency exchange world money coins'),
('w_economy_A2_33','poverty','/ˈpɒvərti/','noun','빈곤','The state of being extremely poor.','Many families still live in {poverty}.','많은 가정이 아직도 빈곤 속에 살아요.','poverty','A2','economy',2,'poverty community urban hardship aid'),
('w_economy_A2_34','wealth','/welθ/','noun','부, 재산','A large amount of money or valuable possessions.','Education can be a path to {wealth}.','교육은 부를 이루는 길이 될 수 있어요.','wealth','A2','economy',2,'wealth success business growth prosperity'),
('w_economy_A2_35','transaction','/træˈnzækʃən/','noun','거래, 거래 내역','An act of buying or selling something.','Check your recent {transactions} online.','온라인에서 최근 거래 내역을 확인하세요.','transaction','A2','economy',2,'transaction bank app mobile screen finance')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — B1 (중급: 경제 지표·시장)
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_economy_B1_01','inflation','/ɪnˈfleɪʃən/','noun','인플레이션','A general increase in prices over time.','High {inflation} is reducing people''s purchasing power.','높은 인플레이션이 구매력을 줄이고 있어요.','inflation','B1','economy',1,'inflation prices rising chart graph economy'),
('w_economy_B1_02','recession','/rɪˈseʃən/','noun','경기 침체','A period of economic decline lasting several months.','The country entered a {recession} last year.','그 나라는 작년에 경기 침체에 들어갔어요.','recession','B1','economy',1,'recession economy decline graph business'),
('w_economy_B1_03','interest rate','/ˈɪntrəst reɪt/','noun','금리','The percentage charged on borrowed money.','The central bank raised the {interest rate}.','중앙은행이 금리를 올렸어요.','interest rate','B1','economy',1,'interest rate central bank chart percentage'),
('w_economy_B1_04','stock','/stɒk/','noun','주식','A share in the ownership of a company.','She owns {stock} in several tech companies.','그녀는 여러 기술 회사의 주식을 가지고 있어요.','stock','B1','economy',1,'stock market trading screen ticker'),
('w_economy_B1_05','market','/ˈmɑːrkɪt/','noun','시장 (금융)','The trade in a particular type of commodity.','The housing {market} has slowed down.','주택 시장이 둔화되었어요.','market','B1','economy',1,'financial market trading floor investors'),
('w_economy_B1_06','GDP','/ˌdʒiː diː ˈpiː/','noun','국내총생산','Gross Domestic Product — the total value of goods and services produced.','The country''s {GDP} grew by three percent.','그 나라의 GDP가 3% 성장했어요.','GDP','B1','economy',1,'GDP economy data chart growth country'),
('w_economy_B1_07','fiscal','/ˈfɪskəl/','adjective','재정의','Relating to government revenue and expenditure.','The government announced its new {fiscal} policy.','정부가 새 재정 정책을 발표했어요.','fiscal','B1','economy',2,'fiscal policy government budget parliament'),
('w_economy_B1_08','monetary','/ˈmɒnɪtəri/','adjective','통화의','Relating to money or currency in circulation.','The central bank uses {monetary} tools to control inflation.','중앙은행은 인플레이션을 조절하기 위해 통화 수단을 사용해요.','monetary','B1','economy',2,'monetary policy central bank board meeting'),
('w_economy_B1_09','trade','/treɪd/','noun','무역; 거래','The activity of buying and selling between countries.','Free {trade} benefits both sides.','자유 무역은 양측 모두에게 이익이 돼요.','trade','B1','economy',1,'international trade shipping containers port'),
('w_economy_B1_10','surplus','/ˈsɜːrpləs/','noun','흑자; 잉여','An amount left over when needs are met.','South Korea runs a trade {surplus}.','한국은 무역 흑자를 기록하고 있어요.','surplus','B1','economy',2,'surplus export trade data chart positive'),
('w_economy_B1_11','unemployment','/ˌʌnɪmˈplɔɪmənt/','noun','실업','The state of being without paid work.','{Unemployment} rose to eight percent.','실업률이 8%로 올랐어요.','unemployment','B1','economy',1,'unemployment job search office resume'),
('w_economy_B1_12','export','/ˈeksˌpɔːrt/','noun','수출','Goods sold and sent to another country.','Car {exports} increased this quarter.','이번 분기에 자동차 수출이 증가했어요.','export','B1','economy',1,'export shipping port cargo containers'),
('w_economy_B1_13','import','/ˈɪmpɔːrt/','noun','수입 (무역)','Goods bought from another country.','Fuel {imports} are costly for this country.','연료 수입은 이 나라에 비용이 많이 들어요.','import','B1','economy',1,'import cargo ship logistics port'),
('w_economy_B1_14','supply','/səˈplaɪ/','noun','공급','The amount of a good available for purchase.','A shortage in {supply} drives up prices.','공급 부족이 가격을 끌어올려요.','supply','B1','economy',1,'supply chain warehouse logistics goods'),
('w_economy_B1_15','demand','/dɪˈmɑːnd/','noun','수요','The desire of consumers to purchase goods.','High {demand} for housing has raised prices.','주택에 대한 높은 수요가 가격을 올렸어요.','demand','B1','economy',1,'demand graph economics supply arrow'),
('w_economy_B1_16','growth','/ɡroʊθ/','noun','성장','An increase in economic output over time.','Annual economic {growth} slowed to two percent.','연간 경제 성장이 2%로 둔화됐어요.','growth','B1','economy',1,'economic growth graph chart arrow upward'),
('w_economy_B1_17','investment','/ɪnˈvestmənt/','noun','투자','The act of putting money into something for a return.','Foreign {investment} is vital for development.','외국 투자는 개발에 필수적이에요.','investment','B1','economy',1,'investment business handshake deal finance'),
('w_economy_B1_18','bankruptcy','/ˈbæŋkrʌptsi/','noun','파산','The legal state of not being able to pay debts.','The company filed for {bankruptcy}.','그 회사는 파산 신청을 했어요.','bankruptcy','B1','economy',2,'bankruptcy closed store sign business failure'),
('w_economy_B1_19','competition','/ˌkɒmpɪˈtɪʃən/','noun','경쟁','The activity of striving against others for the same goal.','Healthy {competition} keeps prices down.','건전한 경쟁은 가격을 낮게 유지해요.','competition','B1','economy',2,'market competition rivals business strategy'),
('w_economy_B1_20','consumer','/kənˈsjuːmər/','noun','소비자','A person who buys goods or services.','{Consumer} confidence fell sharply.','소비자 신뢰가 급격히 떨어졌어요.','consumer','B1','economy',1,'consumer shopping mall retail spending'),
('w_economy_B1_21','producer','/prəˈdjuːsər/','noun','생산자','A person or company that makes goods.','Local {producers} benefit from fair prices.','현지 생산자들은 공정한 가격으로 혜택을 받아요.','producer','B1','economy',2,'producer farm factory manufacturing goods'),
('w_economy_B1_22','revenue','/ˈrevənjuː/','noun','수익, 세입','Income generated by a business or government.','The government''s {revenue} from taxes increased.','세금으로 인한 정부 세입이 증가했어요.','revenue','B1','economy',1,'revenue chart business income bar graph'),
('w_economy_B1_23','expenditure','/ɪkˈspendɪtʃər/','noun','지출, 지출액','The total amount of money spent.','Public {expenditure} on education was cut.','교육에 대한 공공 지출이 삭감됐어요.','expenditure','B1','economy',2,'government expenditure budget spending policy'),
('w_economy_B1_24','exchange rate','/ɪkˈstʃeɪndʒ reɪt/','noun','환율','The rate at which one currency is exchanged for another.','The {exchange rate} affects travel costs.','환율은 여행 비용에 영향을 미쳐요.','exchange rate','B1','economy',1,'exchange rate currency board airport travel'),
('w_economy_B1_25','capital','/ˈkæpɪtl/','noun','자본','Wealth used to produce more wealth.','The startup needed more {capital} to grow.','스타트업은 성장하기 위해 더 많은 자본이 필요했어요.','capital','B1','economy',1,'capital investment startup office whiteboard'),
('w_economy_B1_26','labor','/ˈleɪbər/','noun','노동','Work done by people, especially physical work.','The country has a large {labor} force.','그 나라는 큰 노동 인력을 보유하고 있어요.','labor','B1','economy',2,'labor workers factory manufacturing hard work'),
('w_economy_B1_27','industry','/ˈɪndəstri/','noun','산업','Economic activity concerned with processing goods.','The tech {industry} is growing rapidly.','기술 산업이 빠르게 성장하고 있어요.','industry','B1','economy',2,'industry factory technology business sector'),
('w_economy_B1_28','output','/ˈaʊtpʊt/','noun','생산량, 산출량','The amount of something produced.','Industrial {output} fell last quarter.','지난 분기 산업 생산량이 감소했어요.','output','B1','economy',2,'output factory production manufacturing chart'),
('w_economy_B1_29','sector','/ˈsektər/','noun','분야, 부문','A distinct part of an economy.','The service {sector} now dominates the economy.','서비스 부문이 이제 경제를 지배하고 있어요.','sector','B1','economy',2,'sector economy chart pie graph business'),
('w_economy_B1_30','subsidy','/ˈsʌbsɪdi/','noun','보조금','Money given by the government to support an industry.','Farmers receive a government {subsidy}.','농부들은 정부 보조금을 받아요.','subsidy','B1','economy',2,'subsidy farming government agriculture support'),
('w_economy_B1_31','cost of living','/kɒst əv ˈlɪvɪŋ/','noun','생활비','The amount of money needed for basic needs.','The {cost of living} in Seoul is rising.','서울의 생활비가 오르고 있어요.','cost of living','B1','economy',1,'cost of living city apartment grocery bills'),
('w_economy_B1_32','trade deficit','/treɪd ˈdefɪsɪt/','noun','무역 적자','When imports exceed exports in value.','The nation''s {trade deficit} widened.','그 나라의 무역 적자가 확대됐어요.','trade deficit','B1','economy',2,'trade deficit graph negative import export'),
('w_economy_B1_33','merger','/ˈmɜːrdʒər/','noun','기업 합병','The combining of two companies into one.','The {merger} created the largest bank in the region.','그 합병으로 지역 최대 은행이 탄생했어요.','merger','B1','economy',2,'merger business handshake corporate deal'),
('w_economy_B1_34','shareholder','/ˈʃeərhoʊldər/','noun','주주','A person who owns shares in a company.','{Shareholders} voted against the proposal.','주주들이 제안에 반대표를 던졌어요.','shareholder','B1','economy',2,'shareholder meeting boardroom vote corporate'),
('w_economy_B1_35','forecast','/ˈfɔːrkæst/','noun','전망, 예측','A prediction of future economic trends.','The economic {forecast} for next year is positive.','내년의 경제 전망은 긍정적이에요.','forecast','B1','economy',2,'economic forecast data chart analyst presentation')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — B2 (중상급: 투자·시장 심화)
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_economy_B2_01','deficit','/ˈdefɪsɪt/','noun','적자, 결손','When expenditure exceeds revenue.','The government ran a large budget {deficit}.','정부는 큰 재정 적자를 기록했어요.','deficit','B2','economy',1,'deficit budget government spending debt chart'),
('w_economy_B2_02','quantitative easing','/ˌkwɒntɪteɪtɪv ˈiːzɪŋ/','noun','양적 완화','A monetary policy where central banks buy assets to inject money.','The Fed used {quantitative easing} to stimulate the economy.','연준은 경제를 부양하기 위해 양적 완화를 사용했어요.','quantitative easing','B2','economy',1,'quantitative easing central bank policy money'),
('w_economy_B2_03','liquidity','/lɪˈkwɪdɪti/','noun','유동성','The ease of converting assets to cash.','The bank faces a serious {liquidity} problem.','그 은행은 심각한 유동성 문제에 직면했어요.','liquidity','B2','economy',1,'liquidity cash flow bank finance chart'),
('w_economy_B2_04','equity','/ˈekwɪti/','noun','자기자본; 주식','The value of shares issued by a company; or fairness.','Investors prefer {equity} over bonds in a bull market.','강세장에서 투자자들은 채권보다 주식을 선호해요.','equity','B2','economy',1,'equity stock market investor trading screen'),
('w_economy_B2_05','hedge','/hedʒ/','verb','위험을 분산하다','To reduce risk by making an offsetting investment.','Investors {hedge} against currency risk with derivatives.','투자자들은 파생상품으로 환위험을 분산해요.','hedge','B2','economy',1,'hedge fund risk management finance strategy'),
('w_economy_B2_06','portfolio','/pɔːrtˈfoʊliˌoʊ/','noun','포트폴리오','A range of investments held by a person or organization.','Diversifying your {portfolio} reduces risk.','포트폴리오를 다양화하면 위험이 줄어요.','portfolio','B2','economy',1,'portfolio investment diversified stocks bonds'),
('w_economy_B2_07','bond','/bɒnd/','noun','채권','A certificate of debt issued by a government or company.','Government {bonds} are considered safe investments.','국채는 안전한 투자로 여겨져요.','bond','B2','economy',1,'bond certificate government treasury investment'),
('w_economy_B2_08','derivative','/dɪˈrɪvətɪv/','noun','파생상품','A financial product derived from another asset.','Options are a common type of financial {derivative}.','옵션은 흔한 금융 파생상품의 유형이에요.','derivative','B2','economy',2,'derivative finance trading options futures'),
('w_economy_B2_09','commodity','/kəˈmɒdɪti/','noun','원자재, 상품','A raw material or primary agricultural product.','Oil is the world''s most traded {commodity}.','석유는 세계에서 가장 많이 거래되는 원자재예요.','commodity','B2','economy',1,'commodity oil gold raw material trade'),
('w_economy_B2_10','index','/ˈɪndeks/','noun','지수','A statistical measure of economic or financial performance.','The stock market {index} hit a record high.','주가 지수가 사상 최고를 기록했어요.','index','B2','economy',1,'stock index chart market screen trading'),
('w_economy_B2_11','volatility','/ˌvɒləˈtɪlɪti/','noun','변동성','The degree of rapid and unpredictable change.','Market {volatility} increased after the announcement.','발표 이후 시장 변동성이 높아졌어요.','volatility','B2','economy',1,'market volatility chart spike finance'),
('w_economy_B2_12','yield','/jiːld/','noun','수익률, 이율','The income returned on an investment.','The bond''s {yield} fell as prices rose.','채권 가격이 오르면서 수익률이 하락했어요.','yield','B2','economy',1,'yield bond return investment finance chart'),
('w_economy_B2_13','leverage','/ˈlevərɪdʒ/','noun','레버리지, 차입 투자','The use of borrowed money to increase potential return.','The firm used too much {leverage} and collapsed.','그 회사는 레버리지를 너무 많이 사용하다 붕괴됐어요.','leverage','B2','economy',2,'leverage finance risk debt investment'),
('w_economy_B2_14','diversification','/daɪˌvɜːrsɪfɪˈkeɪʃən/','noun','분산투자','Spreading investments to reduce risk.','{Diversification} is key to managing investment risk.','분산투자는 투자 위험 관리의 핵심이에요.','diversification','B2','economy',2,'diversification portfolio investment various'),
('w_economy_B2_15','bear market','/beər ˈmɑːrkɪt/','noun','약세장','A period of declining stock prices.','Investors struggled during the {bear market}.','투자자들은 약세장 동안 어려움을 겪었어요.','bear market','B2','economy',2,'bear market stock decline chart red arrow down'),
('w_economy_B2_16','bull market','/bʊl ˈmɑːrkɪt/','noun','강세장','A period of rising stock prices.','The {bull market} lasted nearly a decade.','강세장이 거의 10년간 지속됐어요.','bull market','B2','economy',2,'bull market stock rise chart green arrow'),
('w_economy_B2_17','asset','/ˈæset/','noun','자산','A resource with economic value.','Property is her most valuable {asset}.','부동산이 그녀의 가장 가치 있는 자산이에요.','asset','B2','economy',1,'asset property investment wealth finance'),
('w_economy_B2_18','liability','/ˌlaɪəˈbɪlɪti/','noun','부채, 채무','Something a company or person owes.','Long-term {liabilities} appear on the balance sheet.','장기 부채는 대차대조표에 나타나요.','liability','B2','economy',2,'liability balance sheet accounting finance'),
('w_economy_B2_19','fiscal policy','/ˈfɪskəl ˈpɒlɪsi/','noun','재정 정책','Government decisions about spending and taxation.','Expansionary {fiscal policy} aims to stimulate growth.','확장적 재정 정책은 성장을 자극하는 것을 목표로 해요.','fiscal policy','B2','economy',2,'fiscal policy government budget parliament vote'),
('w_economy_B2_20','austerity','/ɒˈsterɪti/','noun','긴축','Government policies to reduce public spending.','Years of {austerity} caused widespread hardship.','수년간의 긴축 정책이 광범위한 어려움을 초래했어요.','austerity','B2','economy',1,'austerity protest cuts budget government'),
('w_economy_B2_21','currency depreciation','/ˈkɜːrənsi dɪˌpriːʃɪˈeɪʃən/','noun','통화 가치 하락','A decrease in the value of a currency relative to others.','{Currency depreciation} made exports more competitive.','통화 가치 하락으로 수출이 더 경쟁력을 갖게 됐어요.','currency depreciation','B2','economy',2,'currency exchange rate falling depreciation'),
('w_economy_B2_22','monetary policy','/ˈmɒnɪtəri ˈpɒlɪsi/','noun','통화 정책','Central bank actions to control money supply and rates.','The central bank tightened its {monetary policy}.','중앙은행이 통화 정책을 긴축했어요.','monetary policy','B2','economy',2,'monetary policy central bank interest rate board'),
('w_economy_B2_23','capitalization','/ˌkæpɪtələˈzeɪʃən/','noun','시가총액; 자본화','The total market value of a company''s shares.','Apple''s market {capitalization} exceeds two trillion dollars.','애플의 시가총액은 2조 달러를 넘어요.','capitalization','B2','economy',2,'market capitalization big tech company stock screen'),
('w_economy_B2_24','stagflation','/stæɡˈfleɪʃən/','noun','스태그플레이션','High inflation combined with stagnant growth and unemployment.','The 1970s saw severe {stagflation} in many countries.','1970년대에 많은 나라에서 심각한 스태그플레이션이 있었어요.','stagflation','B2','economy',2,'stagflation economy crisis vintage newspaper'),
('w_economy_B2_25','credit rating','/ˈkredɪt ˌreɪtɪŋ/','noun','신용 등급','An assessment of the ability to repay debts.','A country''s {credit rating} affects borrowing costs.','한 나라의 신용 등급은 차입 비용에 영향을 줘요.','credit rating','B2','economy',2,'credit rating agency finance document analysis'),
('w_economy_B2_26','venture capital','/ˈventʃər ˈkæpɪtl/','noun','벤처 캐피털','Funding provided to startup companies with high growth potential.','They raised funds from {venture capital} investors.','그들은 벤처 캐피털 투자자들로부터 자금을 조달했어요.','venture capital','B2','economy',2,'venture capital startup pitch investors office'),
('w_economy_B2_27','dividend','/ˈdɪvɪdend/','noun','배당금','A sum of money paid to shareholders from a company''s profits.','The company paid a generous {dividend} this year.','그 회사는 올해 넉넉한 배당금을 지급했어요.','dividend','B2','economy',2,'dividend payment investor stock check'),
('w_economy_B2_28','hedge fund','/hedʒ fʌnd/','noun','헤지펀드','A pooled investment fund using complex strategies.','The {hedge fund} posted a thirty percent return.','그 헤지펀드는 30%의 수익을 냈어요.','hedge fund','B2','economy',2,'hedge fund trading desk screens analysts'),
('w_economy_B2_29','private equity','/praɪvɪt ˈekwɪti/','noun','사모펀드','Investment in companies not listed on public exchanges.','{Private equity} firms acquired several hospitals.','사모펀드 회사들이 여러 병원을 인수했어요.','private equity','B2','economy',2,'private equity deal boardroom signing contract'),
('w_economy_B2_30','stock exchange','/stɒk ɪksˈtʃeɪndʒ/','noun','주식 거래소','A market where shares are bought and sold.','The company listed on the {stock exchange} today.','그 회사가 오늘 주식 거래소에 상장됐어요.','stock exchange','B2','economy',1,'stock exchange trading floor NYSE screens'),
('w_economy_B2_31','collateral','/kəˈlætərəl/','noun','담보','An asset pledged as security for a loan.','They used their house as {collateral} for the loan.','그들은 대출 담보로 집을 사용했어요.','collateral','B2','economy',2,'collateral loan document property house bank'),
('w_economy_B2_32','inflation rate','/ɪnˈfleɪʃən reɪt/','noun','물가상승률','The rate at which prices increase over time.','The {inflation rate} reached a forty-year high.','물가상승률이 40년 만에 최고치를 기록했어요.','inflation rate','B2','economy',2,'inflation rate CPI chart economy data'),
('w_economy_B2_33','benchmark','/ˈbentʃmɑːrk/','noun','기준, 벤치마크','A standard used for comparing performance.','The fund underperformed its {benchmark} index.','그 펀드는 기준 지수를 밑도는 성과를 냈어요.','benchmark','B2','economy',2,'benchmark comparison chart performance finance'),
('w_economy_B2_34','speculation','/ˌspekjʊˈleɪʃən/','noun','투기','Buying risky assets hoping for profit.','Property {speculation} drove up house prices.','부동산 투기가 주택 가격을 올렸어요.','speculation','B2','economy',2,'speculation real estate risk investment market'),
('w_economy_B2_35','economic cycle','/ˌiːkəˈnɒmɪk ˈsaɪkəl/','noun','경기 순환','The recurring pattern of expansion and contraction in an economy.','Understanding the {economic cycle} helps investors plan.','경기 순환을 이해하면 투자자들이 계획을 세우는 데 도움이 돼요.','economic cycle','B2','economy',2,'economic cycle wave chart boom recession')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — C1 (고급: 경제 정책 분석)
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_economy_C1_01','macroeconomics','/ˌmækroʊˌiːkəˈnɒmɪks/','noun','거시경제학','The branch of economics studying large-scale economic factors.','{Macroeconomics} focuses on GDP, inflation, and employment as a whole.','거시경제학은 GDP, 인플레이션, 고용 전체에 초점을 맞춰요.','macroeconomics','C1','economy',1,'macroeconomics lecture university economics textbook'),
('w_economy_C1_02','microeconomics','/ˌmaɪkroʊˌiːkəˈnɒmɪks/','noun','미시경제학','The branch of economics studying individual consumers and firms.','{Microeconomics} examines how prices are set in individual markets.','미시경제학은 개별 시장에서 가격이 어떻게 결정되는지 살펴봐요.','microeconomics','C1','economy',1,'microeconomics individual market supply demand graph'),
('w_economy_C1_03','stagflation','/stæɡˈfleɪʃən/','noun','스태그플레이션','A simultaneous occurrence of stagnation and inflation.','Policymakers struggled to address {stagflation} in the 1970s.','정책 입안자들은 1970년대 스태그플레이션 해결에 애를 먹었어요.','stagflation','C1','economy',1,'stagflation crisis newspaper headline economic history'),
('w_economy_C1_04','arbitrage','/ˈɑːrbɪtrɑːʒ/','noun','차익거래','Profiting from price differences in different markets.','Currency {arbitrage} requires speed and capital.','통화 차익거래는 속도와 자본이 필요해요.','arbitrage','C1','economy',2,'arbitrage trading screens currency price difference'),
('w_economy_C1_05','austerity','/ɒˈsterɪti/','noun','긴축 재정 정책','Severe economic policies to reduce government debt.','The IMF imposed strict {austerity} measures on the country.','IMF는 그 나라에 엄격한 긴축 조치를 부과했어요.','austerity','C1','economy',1,'austerity IMF government cuts protest economy'),
('w_economy_C1_06','deregulation','/ˌdiːˌreɡjʊˈleɪʃən/','noun','규제 완화','Reduction of government rules over an industry.','Financial {deregulation} in the 1980s allowed banks greater freedom.','1980년대 금융 규제 완화로 은행들은 더 큰 자유를 얻었어요.','deregulation','C1','economy',1,'deregulation finance bank building government law'),
('w_economy_C1_07','privatization','/ˌpraɪvətaɪˈzeɪʃən/','noun','민영화','Transferring a public service to private ownership.','The {privatization} of the railway was controversial.','철도 민영화는 논란이 됐어요.','privatization','C1','economy',1,'privatization railway public private corporation'),
('w_economy_C1_08','subsidy','/ˈsʌbsɪdi/','noun','보조금 (정책적)','Government financial support to encourage an activity.','Agricultural {subsidies} keep food prices stable.','농업 보조금이 식품 가격을 안정적으로 유지해요.','subsidy','C1','economy',1,'subsidy agriculture government support farm policy'),
('w_economy_C1_09','tariff','/ˈtærɪf/','noun','관세','A tax on imported goods.','The government imposed a twenty percent {tariff} on steel.','정부는 철강에 20% 관세를 부과했어요.','tariff','C1','economy',1,'tariff trade customs import border tax'),
('w_economy_C1_10','cartel','/kɑːrˈtel/','noun','카르텔','A group of companies agreeing to fix prices.','The oil {cartel} agreed to cut production.','석유 카르텔이 생산을 줄이기로 합의했어요.','cartel','C1','economy',1,'cartel oil OPEC meeting agreement energy'),
('w_economy_C1_11','oligopoly','/ˌɒlɪˈɡɒpəli/','noun','과점','A market controlled by a small number of firms.','The telecom sector is an {oligopoly} in most countries.','통신 분야는 대부분의 나라에서 과점이에요.','oligopoly','C1','economy',2,'oligopoly few companies market dominance'),
('w_economy_C1_12','externality','/ˌekstɜːrˈnælɪti/','noun','외부 효과','A cost or benefit affecting a third party outside a transaction.','Pollution is a classic negative {externality}.','오염은 전형적인 부정적 외부 효과예요.','externality','C1','economy',2,'externality pollution factory smoke environment'),
('w_economy_C1_13','fiscal stimulus','/ˈfɪskəl ˈstɪmjʊləs/','noun','재정 부양책','Government spending to boost economic activity.','The government announced a large {fiscal stimulus} package.','정부가 대규모 재정 부양 패키지를 발표했어요.','fiscal stimulus','C1','economy',1,'fiscal stimulus government spending infrastructure project'),
('w_economy_C1_14','central bank','/ˈsentrəl bæŋk/','noun','중앙은행','The national institution managing monetary policy.','The {central bank} raised rates by fifty basis points.','중앙은행이 기준금리를 50bp 인상했어요.','central bank','C1','economy',1,'central bank federal reserve building architecture'),
('w_economy_C1_15','austerity measure','/ɒˈsterɪti ˈmeʒər/','noun','긴축 조치','A specific policy action to cut government spending.','New {austerity measures} sparked nationwide protests.','새 긴축 조치가 전국적인 시위를 촉발시켰어요.','austerity measure','C1','economy',2,'austerity protest street signs economy crisis'),
('w_economy_C1_16','structural reform','/ˈstrʌktʃərəl rɪˈfɔːrm/','noun','구조 개혁','Long-term policy changes to improve economic efficiency.','The IMF called for deep {structural reforms}.','IMF는 심도 있는 구조 개혁을 촉구했어요.','structural reform','C1','economy',2,'structural reform policy government parliament document'),
('w_economy_C1_17','protectionism','/prəˈtekʃənɪzəm/','noun','보호무역주의','Economic policy restricting imports to protect domestic industry.','Rising {protectionism} threatens global trade.','높아지는 보호무역주의가 세계 무역을 위협하고 있어요.','protectionism','C1','economy',2,'protectionism trade wall tariff border policy'),
('w_economy_C1_18','moral hazard','/ˈmɒrəl ˈhæzərd/','noun','도덕적 해이','The tendency to take more risk because of protection from consequences.','Bank bailouts create {moral hazard}.','은행 구제금융은 도덕적 해이를 만들어요.','moral hazard','C1','economy',2,'moral hazard risk banking finance responsibility'),
('w_economy_C1_19','comparative advantage','/kəmˈpærətɪv ədˈvɑːntɪdʒ/','noun','비교우위','The ability to produce a good at a lower opportunity cost than another.','Trade is based on each country''s {comparative advantage}.','무역은 각 나라의 비교우위를 기반으로 해요.','comparative advantage','C1','economy',2,'comparative advantage trade global specialization'),
('w_economy_C1_20','purchasing power','/ˈpɜːrtʃəsɪŋ ˌpaʊər/','noun','구매력','The amount of goods a unit of currency can buy.','Inflation erodes {purchasing power} over time.','인플레이션은 시간이 지남에 따라 구매력을 잠식해요.','purchasing power','C1','economy',2,'purchasing power money shopping cart inflation'),
('w_economy_C1_21','free market','/friː ˈmɑːrkɪt/','noun','자유 시장','An economic system with minimal government intervention.','A {free market} allocates resources through supply and demand.','자유 시장은 수요와 공급을 통해 자원을 배분해요.','free market','C1','economy',1,'free market economy trade global business'),
('w_economy_C1_22','planned economy','/plænd ɪˈkɒnəmi/','noun','계획 경제','An economy in which production is controlled by the state.','A {planned economy} aims to distribute resources equally.','계획 경제는 자원을 균등하게 배분하는 것을 목표로 해요.','planned economy','C1','economy',2,'planned economy government factory state control'),
('w_economy_C1_23','sovereign debt','/ˈsɒvrən det/','noun','국가 채무','Money owed by a national government.','Rising {sovereign debt} alarmed investors.','증가하는 국가 채무가 투자자들을 놀라게 했어요.','sovereign debt','C1','economy',2,'sovereign debt government bond finance crisis'),
('w_economy_C1_24','crowding out','/ˈkraʊdɪŋ aʊt/','noun','구축 효과','When government borrowing reduces private sector investment.','Heavy state spending can cause {crowding out}.','과도한 국가 지출은 구축 효과를 일으킬 수 있어요.','crowding out','C1','economy',3,'crowding out government spending private sector'),
('w_economy_C1_25','natural monopoly','/ˈnætʃərəl məˈnɒpəli/','noun','자연독점','A market dominated by a single firm due to high entry costs.','Utilities are often considered {natural monopolies}.','공익 서비스는 종종 자연독점으로 여겨져요.','natural monopoly','C1','economy',2,'natural monopoly utility infrastructure power'),
('w_economy_C1_26','price elasticity','/praɪs ˌiːlæˈstɪsɪti/','noun','가격 탄력성','How sensitive demand is to a change in price.','Cigarettes have low {price elasticity} of demand.','담배는 수요의 가격 탄력성이 낮아요.','price elasticity','C1','economy',2,'price elasticity demand graph economics curve'),
('w_economy_C1_27','market failure','/ˈmɑːrkɪt ˈfeɪljər/','noun','시장 실패','When a free market does not efficiently allocate resources.','Pollution is a sign of {market failure}.','오염은 시장 실패의 신호예요.','market failure','C1','economy',2,'market failure environment pollution government'),
('w_economy_C1_28','balance of payments','/ˈbæləns əv ˈpeɪmənts/','noun','국제수지','A record of all transactions between a country and the world.','A deficit in the {balance of payments} weakens the currency.','국제수지 적자는 통화를 약화시켜요.','balance of payments','C1','economy',2,'balance of payments trade data statistics report'),
('w_economy_C1_29','lender of last resort','/ˈlendər əv lɑːst rɪˈzɔːrt/','noun','최종 대부자','An institution that provides emergency funds to banks.','The central bank acted as the {lender of last resort}.','중앙은행이 최종 대부자로 역할을 했어요.','lender of last resort','C1','economy',3,'central bank emergency loan crisis finance'),
('w_economy_C1_30','Keynesian economics','/ˈkeɪnziən ˌiːkəˈnɒmɪks/','noun','케인즈 경제학','Economic theory advocating government intervention to stabilize economies.','{Keynesian economics} supports deficit spending during recessions.','케인즈 경제학은 경기 침체 시 적자 지출을 지지해요.','Keynesian economics','C1','economy',2,'Keynes economics book theory government spending'),
('w_economy_C1_31','supply-side economics','/səˈplaɪ saɪd ˌiːkəˈnɒmɪks/','noun','공급 중심 경제학','Economic theory focusing on increasing production.','{Supply-side economics} promotes tax cuts for businesses.','공급 중심 경제학은 기업을 위한 세금 감면을 촉진해요.','supply-side economics','C1','economy',2,'supply side tax cut business production economics'),
('w_economy_C1_32','opportunity cost','/ˌɒpəˈtjuːnɪti kɒst/','noun','기회 비용','The value of the next best option forgone.','Going to university has an {opportunity cost} of lost wages.','대학 진학에는 포기된 임금이라는 기회 비용이 있어요.','opportunity cost','C1','economy',2,'opportunity cost decision choice trade-off economics'),
('w_economy_C1_33','hyperinflation','/ˌhaɪpərɪnˈfleɪʃən/','noun','초인플레이션','Extremely rapid and out-of-control price increases.','Zimbabwe suffered severe {hyperinflation} in the 2000s.','짐바브웨는 2000년대 심각한 초인플레이션을 겪었어요.','hyperinflation','C1','economy',2,'hyperinflation banknotes wheelbarrow crisis Zimbabwe'),
('w_economy_C1_34','fiscal consolidation','/ˈfɪskəl kənsɒlɪˈdeɪʃən/','noun','재정 건전화','Reducing budget deficits through spending cuts or tax rises.','{Fiscal consolidation} was necessary to restore investor confidence.','재정 건전화는 투자자 신뢰 회복에 필요했어요.','fiscal consolidation','C1','economy',2,'fiscal consolidation budget government documents finance'),
('w_economy_C1_35','income inequality','/ˈɪnkʌm ˌɪnɪˈkwɒlɪti/','noun','소득 불평등','The unequal distribution of income in society.','Rising {income inequality} is a global concern.','증가하는 소득 불평등은 세계적인 우려예요.','income inequality','C1','economy',1,'income inequality wealth gap poverty rich poor')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — C2 (최고급: 경제 이론·전문 용어)
-- ══════════════════════════════════════

INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_economy_C2_01','econometrics','/ɪˌkɒnəˈmetrɪks/','noun','계량경제학','The application of statistical methods to economic data.','{Econometrics} is used to test economic theories empirically.','계량경제학은 경제 이론을 실증적으로 검증하는 데 사용돼요.','econometrics','C2','economy',1,'econometrics statistics regression data research university'),
('w_economy_C2_02','fiduciary','/fɪˈdjuːʃɪəri/','adjective','수탁자의; 신의 성실의','Relating to a legal duty to act in another''s best interest.','Fund managers have a {fiduciary} duty to their clients.','펀드 매니저는 고객에 대한 수탁 의무가 있어요.','fiduciary','C2','economy',1,'fiduciary duty trust fund manager legal documents'),
('w_economy_C2_03','securitization','/sɪˌkjʊərɪtaɪˈzeɪʃən/','noun','유동화, 증권화','The process of pooling assets to create tradable securities.','Mortgage {securitization} contributed to the 2008 financial crisis.','주택담보대출 유동화가 2008년 금융 위기에 기여했어요.','securitization','C2','economy',1,'securitization mortgage CDO finance crisis 2008'),
('w_economy_C2_04','collateralized','/kəˈlætərəlaɪzd/','adjective','담보화된','Backed by pledged assets as security.','{Collateralized} debt obligations were at the heart of the crisis.','담보부 채무증권이 위기의 핵심에 있었어요.','collateralized','C2','economy',2,'collateralized debt obligation CDO finance complex'),
('w_economy_C2_05','monopsony','/məˈnɒpsəni/','noun','수요 독점','A market where there is only one buyer.','A {monopsony} can suppress wages by controlling hiring.','수요 독점은 채용을 통제함으로써 임금을 억제할 수 있어요.','monopsony','C2','economy',2,'monopsony single buyer labor market wage'),
('w_economy_C2_06','rent-seeking','/rent ˈsiːkɪŋ/','noun','지대추구','Gaining wealth through manipulation of the economic environment.','Lobbying for special privileges is a form of {rent-seeking}.','특권을 위한 로비는 지대추구의 한 형태예요.','rent-seeking','C2','economy',2,'rent seeking lobbying politician influence wealth'),
('w_economy_C2_07','Keynesian','/ˈkeɪnziən/','adjective','케인즈주의적','Relating to the economic theories of John Maynard Keynes.','The government adopted a {Keynesian} approach to the recession.','정부는 경기 침체에 케인즈주의적 접근법을 채택했어요.','Keynesian','C2','economy',1,'Keynesian economics government stimulus spending policy'),
('w_economy_C2_08','neoliberal','/ˌniːoʊˈlɪbərəl/','adjective','신자유주의의','Relating to a free-market economic ideology with minimal state intervention.','Critics argue {neoliberal} policies have widened inequality.','비평가들은 신자유주의 정책이 불평등을 심화시켰다고 주장해요.','neoliberal','C2','economy',1,'neoliberal economics free market globalization policy'),
('w_economy_C2_09','heterodox','/ˈhetərədɒks/','adjective','비주류의; 이단적인','Not following conventional economic thinking.','{Heterodox} economists challenge mainstream assumptions.','비주류 경제학자들은 주류적 가정에 도전해요.','heterodox','C2','economy',2,'heterodox economics alternative theory debate academia'),
('w_economy_C2_10','exogenous','/ɛkˈsɒdʒɪnəs/','adjective','외생적인','Originating from outside the economic model.','Oil price shocks are often treated as {exogenous} variables.','유가 충격은 종종 외생 변수로 취급돼요.','exogenous','C2','economy',2,'exogenous variable model economics external shock'),
('w_economy_C2_11','endogenous growth','/enˈdɒdʒɪnəs ɡroʊθ/','noun','내생적 성장','Growth driven by factors within the economic model such as innovation.','{Endogenous growth} theory emphasizes R&D investment.','내생적 성장 이론은 R&D 투자를 강조해요.','endogenous growth','C2','economy',2,'endogenous growth innovation research technology lab'),
('w_economy_C2_12','Pareto efficiency','/pəˈreɪtoʊ ɪˈfɪʃənsi/','noun','파레토 효율성','A state where no one can be made better off without making someone worse off.','Perfect competition tends toward {Pareto efficiency}.','완전 경쟁은 파레토 효율성을 향해 가는 경향이 있어요.','Pareto efficiency','C2','economy',2,'Pareto efficiency economics optimal allocation graph'),
('w_economy_C2_13','Nash equilibrium','/næʃ ˌiːkwɪˈlɪbriəm/','noun','내시 균형','A stable state in game theory where no player benefits from changing strategy.','The {Nash equilibrium} predicts mutual defection in the prisoner''s dilemma.','내시 균형은 죄수의 딜레마에서 상호 배신을 예측해요.','Nash equilibrium','C2','economy',2,'Nash equilibrium game theory strategy mathematics'),
('w_economy_C2_14','asymmetric information','/ˌeɪsɪˈmetrɪk ˌɪnfəˈmeɪʃən/','noun','정보 비대칭','A situation where one party has more information than another.','Insurance markets suffer from {asymmetric information}.','보험 시장은 정보 비대칭으로 어려움을 겪어요.','asymmetric information','C2','economy',2,'asymmetric information market buyer seller knowledge'),
('w_economy_C2_15','moral suasion','/ˈmɒrəl ˈsweɪʒən/','noun','도의적 압박','Persuasion by appealing to morality or patriotism.','The central bank used {moral suasion} to discourage risky lending.','중앙은행은 위험한 대출을 막기 위해 도의적 압박을 사용했어요.','moral suasion','C2','economy',3,'moral suasion central bank speech policy persuasion'),
('w_economy_C2_16','credit default swap','/ˈkredɪt dɪˈfɔːlt swɒp/','noun','신용부도스왑','A financial derivative used to hedge credit risk.','{Credit default swaps} amplified losses during the 2008 crisis.','신용부도스왑은 2008년 위기 중 손실을 증폭시켰어요.','credit default swap','C2','economy',2,'credit default swap CDS finance derivative risk'),
('w_economy_C2_17','quantitative tightening','/ˌkwɒntɪteɪtɪv ˈtaɪtənɪŋ/','noun','양적 긴축','A monetary policy reducing central bank balance sheet size.','{Quantitative tightening} removes liquidity from the market.','양적 긴축은 시장에서 유동성을 제거해요.','quantitative tightening','C2','economy',2,'quantitative tightening central bank balance sheet'),
('w_economy_C2_18','fiscal multiplier','/ˈfɪskəl ˈmʌltɪplaɪər/','noun','재정 승수','The ratio of change in output to fiscal stimulus.','A high {fiscal multiplier} means spending has a large economic impact.','높은 재정 승수는 지출이 경제에 큰 영향을 미친다는 것을 의미해요.','fiscal multiplier','C2','economy',3,'fiscal multiplier government spending economic impact'),
('w_economy_C2_19','Gini coefficient','/ˈdʒiːni ˌkoʊɪˈfɪʃənt/','noun','지니 계수','A measure of income inequality in a population.','A higher {Gini coefficient} indicates greater inequality.','지니 계수가 높을수록 불평등이 더 크다는 것을 나타내요.','Gini coefficient','C2','economy',2,'Gini coefficient inequality statistics data chart'),
('w_economy_C2_20','deadweight loss','/ˈdedweɪt lɒs/','noun','사중 손실','The loss of economic efficiency due to market distortion.','Taxes create {deadweight loss} by reducing transactions.','세금은 거래를 줄임으로써 사중 손실을 만들어요.','deadweight loss','C2','economy',2,'deadweight loss economics graph supply demand triangle'),
('w_economy_C2_21','adverse selection','/ˈædvɜːrs sɪˈlekʃən/','noun','역선택','When one party takes advantage of better information before a deal.','Health insurance faces the problem of {adverse selection}.','건강 보험은 역선택 문제에 직면해 있어요.','adverse selection','C2','economy',2,'adverse selection insurance market lemons problem'),
('w_economy_C2_22','Dutch disease','/dʌtʃ dɪˈziːz/','noun','네덜란드병','Economic harm from a natural resource boom weakening other sectors.','Countries with oil revenues risk {Dutch disease}.','석유 수입이 있는 나라들은 네덜란드병의 위험이 있어요.','Dutch disease','C2','economy',2,'Dutch disease oil natural resource economy'),
('w_economy_C2_23','liquidity trap','/lɪˈkwɪdɪti træp/','noun','유동성 함정','A situation where monetary policy becomes ineffective at zero interest rates.','Japan experienced a prolonged {liquidity trap}.','일본은 장기간의 유동성 함정을 경험했어요.','liquidity trap','C2','economy',2,'liquidity trap Japan zero interest rate deflation'),
('w_economy_C2_24','principal-agent problem','/ˈprɪnsɪpəl ˈeɪdʒənt ˈprɒbləm/','noun','주인-대리인 문제','Conflict of interest between a principal and their agent.','Corporate governance tries to address the {principal-agent problem}.','기업 거버넌스는 주인-대리인 문제를 해결하려 해요.','principal-agent problem','C2','economy',2,'principal agent conflict interest corporate governance'),
('w_economy_C2_25','velocity of money','/vɪˈlɒsɪti əv ˈmʌni/','noun','화폐 유통 속도','How frequently money is exchanged in an economy.','A falling {velocity of money} signals reduced economic activity.','화폐 유통 속도의 하락은 경제 활동 감소를 알려요.','velocity of money','C2','economy',3,'velocity of money circulation economy activity chart'),
('w_economy_C2_26','crowdfunding','/ˈkraʊdfʌndɪŋ/','noun','크라우드펀딩','Raising capital from a large number of people online.','The startup raised a million dollars through {crowdfunding}.','그 스타트업은 크라우드펀딩으로 백만 달러를 조달했어요.','crowdfunding','C2','economy',2,'crowdfunding startup online platform investors community'),
('w_economy_C2_27','shadow banking','/ˈʃædoʊ ˈbæŋkɪŋ/','noun','그림자 금융','Financial activities outside regular banking regulations.','{Shadow banking} grew rapidly before the 2008 crisis.','그림자 금융은 2008년 위기 전에 급격히 성장했어요.','shadow banking','C2','economy',2,'shadow banking financial system unregulated risk'),
('w_economy_C2_28','behavioral economics','/bɪˈheɪvjərəl ˌiːkəˈnɒmɪks/','noun','행동경제학','The study of psychological influences on economic decisions.','Nudge theory is a key concept in {behavioral economics}.','넛지 이론은 행동경제학의 핵심 개념이에요.','behavioral economics','C2','economy',1,'behavioral economics psychology choice nudge experiment'),
('w_economy_C2_29','helicopter money','/ˈhelɪkɒptər ˈmʌni/','noun','헬리콥터 머니','Direct distribution of money to the public by a central bank.','Some economists proposed {helicopter money} during the pandemic.','일부 경제학자들은 팬데믹 중 헬리콥터 머니를 제안했어요.','helicopter money','C2','economy',2,'helicopter money cash drop stimulus economic policy'),
('w_economy_C2_30','seigniorage','/ˈseɪnjərɪdʒ/','noun','화폐발행이익','Profit made by a government from issuing currency.','{Seigniorage} is the difference between face value and production cost of money.','화폐발행이익은 화폐의 액면가와 생산비 차이예요.','seigniorage','C2','economy',3,'seigniorage central bank currency printing money'),
('w_economy_C2_31','Austrian school','/ˈɒstriən skuːl/','noun','오스트리아 학파','An economic school emphasizing individual action and free markets.','The {Austrian school} opposes central bank intervention.','오스트리아 학파는 중앙은행 개입에 반대해요.','Austrian school','C2','economy',2,'Austrian school economics Hayek Mises free market'),
('w_economy_C2_32','modern monetary theory','/ˈmɒdərn ˈmʌnɪtəri ˈθɪəri/','noun','현대화폐이론 (MMT)','A theory arguing governments can spend freely as currency issuers.','Proponents of {modern monetary theory} reject deficit concerns.','현대화폐이론 지지자들은 재정 적자 우려를 거부해요.','modern monetary theory','C2','economy',2,'MMT modern monetary theory policy debate economists'),
('w_economy_C2_33','trickle-down economics','/ˈtrɪkəl daʊn ˌiːkəˈnɒmɪks/','noun','낙수 경제학','The theory that tax cuts for the rich benefit everyone.','Critics say {trickle-down economics} mostly benefits the wealthy.','비평가들은 낙수 경제학이 주로 부유층에게 이익이 된다고 해요.','trickle-down economics','C2','economy',2,'trickle down economics wealth gap inequality debate'),
('w_economy_C2_34','information asymmetry','/ˌɪnfəˈmeɪʃən eɪˈsɪmɪtri/','noun','정보 비대칭','When different parties have access to different amounts of information.','{Information asymmetry} causes market inefficiency.','정보 비대칭은 시장 비효율을 초래해요.','information asymmetry','C2','economy',2,'information asymmetry market buyer seller knowledge'),
('w_economy_C2_35','general equilibrium','/ˈdʒenərəl ˌiːkwɪˈlɪbriəm/','noun','일반 균형','A state where all markets in an economy clear simultaneously.','Walras developed the theory of {general equilibrium}.','왈라스는 일반 균형 이론을 발전시켰어요.','general equilibrium','C2','economy',3,'general equilibrium economics theory mathematics model')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — A1 (가격·계산 패턴, 7개)
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_economy_A1_01','How much does this cost?','이게 얼마예요?','How much does this cost','가장 기본적인 가격 질문. "How much is this?"로도 써요.','가격 물어보기','A1','economy','pattern',NULL,1),
('s_economy_A1_02','Can I pay by card?','카드로 계산할 수 있나요?','pay by card','계산 방법을 물을 때 pay by card/cash 표현을 써요.','계산','A1','economy','pattern',NULL,2),
('s_economy_A1_03','Do you have anything cheaper?','더 저렴한 것이 있나요?','anything cheaper','anything + 비교급으로 더 나은 선택지를 물어봐요.','쇼핑 협상','A1','economy','pattern',NULL,3),
('s_economy_A1_04','I''ll take it.','이것으로 할게요.','I''ll take it','구매를 결정할 때 쓰는 짧고 자연스러운 표현이에요.','구매 결정','A1','economy','pattern',NULL,4),
('s_economy_A1_05','Can I get a receipt, please?','영수증 주실 수 있나요?','Can I get a receipt','정중한 요청에 "Can I get ~?"은 아주 자연스러운 표현이에요.','계산 후','A1','economy','pattern',NULL,5),
('s_economy_A1_06','Is there a discount?','할인이 있나요?','Is there a discount','세일이나 특별가를 물을 때 가장 많이 쓰는 표현이에요.','쇼핑','A1','economy','pattern',NULL,6),
('s_economy_A1_07','Keep the change.','거스름돈은 괜찮아요.','Keep the change','팁을 주거나 소액 거스름돈을 포기할 때 쓰는 표현이에요.','현금 계산','A1','economy','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — A2 (저축·대출 패턴, 7개)
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_economy_A2_01','I''m trying to save up for a trip.','여행을 위해 저축하려고 해요.','save up for','save up for + 명사: 특정 목표를 위해 돈을 모을 때 써요.','저축 목표','A2','economy','pattern',NULL,1),
('s_economy_A2_02','I need to stick to my budget this month.','이번 달은 예산을 지켜야 해요.','stick to my budget','stick to my budget: 계획된 금액 안에서 쓰겠다는 의미예요.','예산 관리','A2','economy','pattern',NULL,2),
('s_economy_A2_03','Can I apply for a loan here?','여기서 대출 신청을 할 수 있나요?','apply for a loan','apply for + 명사: 대출, 직업, 비자 등을 신청할 때 사용해요.','은행 방문','A2','economy','pattern',NULL,3),
('s_economy_A2_04','My credit card bill came out to a lot this month.','이번 달 신용카드 명세서가 많이 나왔어요.','came out to','came out to + 금액: 최종 금액이 얼마가 나왔다고 말할 때 써요.','카드 명세서','A2','economy','pattern',NULL,4),
('s_economy_A2_05','I get paid at the end of the month.','월말에 급여를 받아요.','get paid','get paid: 급여가 지급된다는 표현. 능동형보다 훨씬 자연스러워요.','급여 관련','A2','economy','pattern',NULL,5),
('s_economy_A2_06','I''m in debt right now, so I can''t afford it.','지금 빚이 있어서 그것을 살 여유가 없어요.','in debt','in debt: 빚이 있는 상태. "I owe money"보다 더 자연스러운 표현이에요.','금전 상황','A2','economy','pattern',NULL,6),
('s_economy_A2_07','Could you transfer the money to my account?','제 계좌로 이체해 주실 수 있나요?','transfer the money to my account','transfer A to B: A를 B로 이체하다. 은행 업무에서 자주 써요.','송금 요청','A2','economy','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — B1 (경제 지표 논의 패턴, 7개)
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_economy_B1_01','Inflation has been rising steadily over the past few months.','지난 몇 달 동안 인플레이션이 꾸준히 상승해 왔어요.','has been rising steadily','현재완료 진행형은 과거부터 지금까지 계속되는 변화를 표현할 때 써요.','경제 뉴스 토론','B1','economy','pattern',NULL,1),
('s_economy_B1_02','The unemployment rate dropped to its lowest level in a decade.','실업률이 10년 만에 최저 수준으로 떨어졌어요.','dropped to its lowest level in','drop to + 최상급 + in + 기간: 기록적 수치를 표현하는 패턴이에요.','경제 지표 설명','B1','economy','pattern',NULL,2),
('s_economy_B1_03','The central bank is expected to raise interest rates next month.','중앙은행이 다음 달 금리를 인상할 것으로 예상돼요.','is expected to','be expected to + 동사: 예상되는 일을 말할 때 자연스러운 표현이에요.','금리 전망 토론','B1','economy','pattern',NULL,3),
('s_economy_B1_04','GDP grew by two percent compared to last year.','GDP가 작년 대비 2% 성장했어요.','compared to last year','compared to: 수치 비교에 가장 많이 쓰이는 표현이에요.','경제 성장 발표','B1','economy','pattern',NULL,4),
('s_economy_B1_05','There is a growing concern about the trade deficit.','무역 적자에 대한 우려가 커지고 있어요.','growing concern about','there is a growing concern about: 점점 심각해지는 문제를 언급할 때 써요.','경제 뉴스','B1','economy','pattern',NULL,5),
('s_economy_B1_06','The economy is showing signs of recovery.','경제가 회복 조짐을 보이고 있어요.','showing signs of recovery','show signs of + 명사: 징후가 나타나다는 표현이에요.','경기 회복 토론','B1','economy','pattern',NULL,6),
('s_economy_B1_07','Consumer spending has slowed down significantly this quarter.','소비자 지출이 이번 분기에 크게 둔화됐어요.','has slowed down significantly','현재완료 + significantly: 주목할 만한 변화를 강조하는 패턴이에요.','경제 분석','B1','economy','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — B2 (투자·시장 패턴, 7개)
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_economy_B2_01','Diversifying your portfolio is key to managing risk.','포트폴리오를 다양화하는 것이 위험 관리의 핵심이에요.','diversifying your portfolio is key to','S + is key to + -ing: "~하는 데 핵심이다"라는 표현이에요.','투자 조언','B2','economy','pattern',NULL,1),
('s_economy_B2_02','The market correction was sharper than analysts had predicted.','시장 조정이 애널리스트들의 예상보다 훨씬 가파르게 나타났어요.','sharper than analysts had predicted','과거완료(had predicted)는 기준 시점보다 이전에 일어난 일을 표현해요.','시장 분석','B2','economy','pattern',NULL,2),
('s_economy_B2_03','Liquidity dried up quickly as investors panicked.','투자자들이 공황 상태에 빠지면서 유동성이 빠르게 말랐어요.','dried up','dry up: 자원·유동성이 갑자기 고갈되다는 생생한 표현이에요.','금융 위기 논의','B2','economy','pattern',NULL,3),
('s_economy_B2_04','Hedge funds tend to perform well in volatile markets.','헤지펀드는 변동성이 높은 시장에서 좋은 성과를 내는 경향이 있어요.','tend to perform well in','tend to: 일반적 경향을 설명할 때 쓰는 표현이에요.','투자 전략','B2','economy','pattern',NULL,4),
('s_economy_B2_05','The bond yield rose sharply following the Fed''s announcement.','연준 발표 이후 채권 수익률이 급격히 상승했어요.','rose sharply following','following + 명사: "~ 이후에"라는 뜻으로 인과관계를 연결해요.','채권 시장','B2','economy','pattern',NULL,5),
('s_economy_B2_06','Investors are fleeing to safe-haven assets amid uncertainty.','불확실성 속에서 투자자들이 안전 자산으로 이동하고 있어요.','fleeing to safe-haven assets amid','amid + 명사: "~ 속에서"라는 표현으로 배경 상황을 나타내요.','위험 회피 전략','B2','economy','pattern',NULL,6),
('s_economy_B2_07','The equity market rebounded after the initial sell-off.','초기 매도세 이후 주식 시장이 반등했어요.','rebounded after the initial sell-off','rebound after: 하락 이후 반등을 표현하는 금융 뉴스의 핵심 패턴이에요.','시장 동향','B2','economy','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — C1 (경제 정책 분석 패턴, 7개)
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_economy_C1_01','Austerity measures have been criticized for deepening inequality rather than reducing the deficit.','긴축 조치는 적자를 줄이기보다 불평등을 심화시켰다는 비판을 받아왔어요.','criticized for deepening','be criticized for + -ing: 비판의 근거를 제시하는 고급 표현이에요.','경제 정책 비판','C1','economy','pattern',NULL,1),
('s_economy_C1_02','Deregulation of the financial sector in the 1980s is often linked to greater systemic risk.','1980년대 금융 부문 규제 완화는 종종 더 큰 시스템 위험과 연결지어져요.','is often linked to','be linked to: 두 현상 간의 인과 혹은 연관성을 표현할 때 써요.','역사적 정책 분석','C1','economy','pattern',NULL,2),
('s_economy_C1_03','The government''s privatization drive has faced strong opposition from trade unions.','정부의 민영화 추진은 노동조합의 강한 반대에 직면했어요.','faced strong opposition from','face opposition from: 반대에 부딪히다는 표현으로 정치 논의에서 자주 써요.','정책 논쟁','C1','economy','pattern',NULL,3),
('s_economy_C1_04','Protectionist tariffs may shield domestic producers but ultimately harm consumers.','보호무역 관세는 국내 생산자를 보호할 수 있지만 결국 소비자에게 해를 끼쳐요.','may shield ... but ultimately','may ... but ultimately: 단기 효과와 장기 결과를 대조할 때 쓰는 구조예요.','무역 정책 논의','C1','economy','pattern',NULL,4),
('s_economy_C1_05','Comparative advantage theory suggests that specialization leads to greater overall welfare.','비교우위 이론은 특화가 전체적인 복지 향상으로 이어진다고 주장해요.','theory suggests that','theory suggests that: 이론의 주장을 소개하는 학술적 표현이에요.','경제 이론 설명','C1','economy','pattern',NULL,5),
('s_economy_C1_06','Excessive reliance on subsidies can distort market signals and reduce efficiency.','보조금에 대한 과도한 의존은 시장 신호를 왜곡하고 효율성을 낮출 수 있어요.','distort market signals','distort market signals: 시장 메커니즘이 제대로 작동하지 않을 때 쓰는 표현이에요.','시장 왜곡 분석','C1','economy','pattern',NULL,6),
('s_economy_C1_07','Moral hazard arises when one party is insulated from the consequences of their decisions.','도덕적 해이는 한쪽이 자신의 결정 결과로부터 보호받을 때 발생해요.','is insulated from the consequences','be insulated from: 결과나 영향을 받지 않는 상태를 표현해요.','경제 인센티브 분석','C1','economy','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — C2 (경제 이론·학술 분석 패턴, 7개)
-- ══════════════════════════════════════

INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_economy_C2_01','Econometric models rely on large datasets to identify causal relationships between variables.','계량경제 모델은 변수 간의 인과 관계를 파악하기 위해 대규모 데이터셋에 의존해요.','identify causal relationships between','identify causal relationships: 인과성 파악이라는 계량경제학의 핵심 목표를 표현해요.','학술 연구 방법론','C2','economy','pattern',NULL,1),
('s_economy_C2_02','The securitization of mortgage-backed assets obscured the underlying credit risk from investors.','주택담보대출 기반 자산의 유동화는 투자자들로부터 내재된 신용 위험을 가렸어요.','obscured the underlying credit risk','obscure + risk: 위험이 감춰지다는 표현으로 금융 위기 분석에 자주 쓰여요.','2008 금융 위기 분석','C2','economy','pattern',NULL,2),
('s_economy_C2_03','Rent-seeking behavior undermines allocative efficiency by redirecting resources toward unproductive activities.','지대추구 행동은 자원을 비생산적 활동으로 전환시켜 배분 효율성을 훼손해요.','undermines allocative efficiency','undermine efficiency: 효율성을 잠식하다는 표현으로 경제 왜곡을 비판할 때 써요.','경제적 비효율 분석','C2','economy','pattern',NULL,3),
('s_economy_C2_04','Heterodox economists challenge the assumption that markets naturally tend toward equilibrium.','비주류 경제학자들은 시장이 자연적으로 균형을 향해 가는 경향이 있다는 가정에 도전해요.','challenge the assumption that','challenge the assumption that: 주류 이론의 전제를 의문시하는 학술적 표현이에요.','경제학 패러다임 토론','C2','economy','pattern',NULL,4),
('s_economy_C2_05','Asymmetric information between buyers and sellers leads to adverse selection and market inefficiency.','구매자와 판매자 간의 정보 비대칭은 역선택과 시장 비효율로 이어져요.','leads to adverse selection','leads to: 결과를 도출하는 인과 표현으로 학술 글쓰기에 필수적이에요.','정보 경제학','C2','economy','pattern',NULL,5),
('s_economy_C2_06','The Gini coefficient measures the extent to which income distribution deviates from perfect equality.','지니 계수는 소득 분배가 완전한 평등에서 얼마나 벗어나는지를 측정해요.','measures the extent to which','measures the extent to which: 정도·수준을 객관적으로 측정하는 학술 표현이에요.','소득 불평등 측정','C2','economy','pattern',NULL,6),
('s_economy_C2_07','A liquidity trap renders conventional monetary policy ineffective, as near-zero rates fail to stimulate demand.','유동성 함정은 제로에 가까운 금리가 수요를 자극하지 못하면서 기존 통화 정책을 무효화해요.','renders conventional monetary policy ineffective','render + O + adjective: "~을 ~한 상태로 만들다"라는 C1+ 핵심 동사 패턴이에요.','통화 정책 한계 분석','C2','economy','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;
