-- EngCat — Presentation topic word examples backfill
-- example_en_2 ~ example_en_5 추가
-- 톤: 공손한 존댓말, B1-B2 학습자 친화 단순 문장
-- Idempotent (UPDATE)

-- ══════════════════════════════════════════════════════════════════
-- A1 (35단어)
-- ══════════════════════════════════════════════════════════════════
UPDATE words SET example_en_2 = 'Can I talk to you after class?', example_ko_2 = '수업 후에 이야기할 수 있을까요?', example_en_3 = 'She will talk about her trip.', example_ko_3 = '그녀는 여행에 대해 이야기할 거예요.', example_en_4 = 'He loves to talk in front of people.', example_ko_4 = '그는 사람들 앞에서 말하는 걸 좋아해요.', example_en_5 = 'We will talk about the results now.', example_ko_5 = '지금 결과에 대해 이야기하겠습니다.' WHERE id = 'w_presentation_A1_01';
UPDATE words SET example_en_2 = 'Let me show you the next slide.', example_ko_2 = '다음 슬라이드를 보여드리겠습니다.', example_en_3 = 'Can you show me the chart again?', example_ko_3 = '차트를 다시 보여주실 수 있나요?', example_en_4 = 'I will show a short video now.', example_ko_4 = '이제 짧은 영상을 보여드리겠습니다.', example_en_5 = 'She showed us the final results.', example_ko_5 = '그녀가 우리에게 최종 결과를 보여줬어요.' WHERE id = 'w_presentation_A1_02';
UPDATE words SET example_en_2 = 'I will tell you more in a moment.', example_ko_2 = '잠시 후에 더 말씀드리겠습니다.', example_en_3 = 'Can you tell us your name?', example_ko_3 = '이름을 말씀해 주시겠어요?', example_en_4 = 'Tell me what you think.', example_ko_4 = '어떻게 생각하시는지 말씀해 주세요.', example_en_5 = 'He told the audience a short story.', example_ko_5 = '그는 청중에게 짧은 이야기를 해줬어요.' WHERE id = 'w_presentation_A1_03';
UPDATE words SET example_en_2 = 'We start every meeting with a review.', example_ko_2 = '우리는 모든 회의를 복습으로 시작해요.', example_en_3 = 'Please start your talk when ready.', example_ko_3 = '준비되시면 발표를 시작해 주세요.', example_en_4 = 'She started by introducing herself.', example_ko_4 = '그녀는 자기소개로 시작했어요.', example_en_5 = 'Let us start with the first slide.', example_ko_5 = '첫 번째 슬라이드부터 시작하겠습니다.' WHERE id = 'w_presentation_A1_04';
UPDATE words SET example_en_2 = 'We will end with a short Q&A.', example_ko_2 = '짧은 질의응답으로 마무리하겠습니다.', example_en_3 = 'The meeting ends at noon.', example_ko_3 = '회의는 정오에 끝나요.', example_en_4 = 'Please end your talk on time.', example_ko_4 = '발표를 제시간에 마무리해 주세요.', example_en_5 = 'How do you plan to end the session?', example_ko_5 = '세션을 어떻게 마무리할 계획인가요?' WHERE id = 'w_presentation_A1_05';
UPDATE words SET example_en_2 = 'First, I want to thank everyone here.', example_ko_2 = '먼저, 여기 계신 모든 분께 감사드리고 싶습니다.', example_en_3 = 'First, let us look at the problem.', example_ko_3 = '먼저 문제를 살펴보겠습니다.', example_en_4 = 'First, check the data carefully.', example_ko_4 = '먼저 데이터를 꼼꼼히 확인하세요.', example_en_5 = 'First, I will give a short overview.', example_ko_5 = '먼저 간단한 개요를 드리겠습니다.' WHERE id = 'w_presentation_A1_06';
UPDATE words SET example_en_2 = 'Next, we will look at the data.', example_ko_2 = '다음으로 데이터를 살펴보겠습니다.', example_en_3 = 'What should we do next?', example_ko_3 = '다음에 무엇을 해야 할까요?', example_en_4 = 'Next, please turn to page two.', example_ko_4 = '다음으로 2페이지로 넘어가 주세요.', example_en_5 = 'Next, I will explain the solution.', example_ko_5 = '다음으로 해결책을 설명하겠습니다.' WHERE id = 'w_presentation_A1_07';
UPDATE words SET example_en_2 = 'The last slide has the key takeaways.', example_ko_2 = '마지막 슬라이드에 핵심 내용이 있습니다.', example_en_3 = 'This is the last topic for today.', example_ko_3 = '오늘의 마지막 주제입니다.', example_en_4 = 'Last week''s data shows a big change.', example_ko_4 = '지난주 데이터가 큰 변화를 보여줍니다.', example_en_5 = 'This is my last point before questions.', example_ko_5 = '질문 전 제 마지막 요점입니다.' WHERE id = 'w_presentation_A1_08';
UPDATE words SET example_en_2 = 'This slide shows our sales numbers.', example_ko_2 = '이 슬라이드는 우리의 매출 수치를 보여줍니다.', example_en_3 = 'Can you move to the next slide?', example_ko_3 = '다음 슬라이드로 넘어가 주실 수 있나요?', example_en_4 = 'The slide has a chart and some text.', example_ko_4 = '슬라이드에 차트와 텍스트가 있습니다.', example_en_5 = 'Please keep each slide simple and clear.', example_ko_5 = '각 슬라이드를 간단하고 명확하게 유지해 주세요.' WHERE id = 'w_presentation_A1_09';
UPDATE words SET example_en_2 = 'I have three points to make today.', example_ko_2 = '오늘 말씀드릴 요점이 세 가지 있습니다.', example_en_3 = 'Can you explain that point again?', example_ko_3 = '그 요점을 다시 설명해 주실 수 있나요?', example_en_4 = 'That is a very good point.', example_ko_4 = '그것은 매우 좋은 요점입니다.', example_en_5 = 'The key point is on this slide.', example_ko_5 = '핵심 요점이 이 슬라이드에 있습니다.' WHERE id = 'w_presentation_A1_10';
UPDATE words SET example_en_2 = 'That is a good question, thank you.', example_ko_2 = '좋은 질문이에요, 감사합니다.', example_en_3 = 'She gave a good presentation today.', example_ko_3 = '그녀는 오늘 좋은 발표를 했어요.', example_en_4 = 'It is good to practice every day.', example_ko_4 = '매일 연습하는 것은 좋아요.', example_en_5 = 'Good morning, everyone. Let us begin.', example_ko_5 = '좋은 아침이에요, 여러분. 시작하겠습니다.' WHERE id = 'w_presentation_A1_11';
UPDATE words SET example_en_2 = 'Today I will talk about our new plan.', example_ko_2 = '오늘 우리의 새로운 계획에 대해 이야기하겠습니다.', example_en_3 = 'Today''s topic is very important.', example_ko_3 = '오늘의 주제는 매우 중요합니다.', example_en_4 = 'What did you learn today?', example_ko_4 = '오늘 무엇을 배웠나요?', example_en_5 = 'Today, let us focus on communication.', example_ko_5 = '오늘은 의사소통에 집중해 보겠습니다.' WHERE id = 'w_presentation_A1_12';
UPDATE words SET example_en_2 = 'Here are three reasons for this change.', example_ko_2 = '이 변화에 대한 세 가지 이유가 여기 있습니다.', example_en_3 = 'Please look here for more details.', example_ko_3 = '더 자세한 내용은 여기를 봐주세요.', example_en_4 = 'Here is our plan for next quarter.', example_ko_4 = '다음 분기 계획이 여기 있습니다.', example_en_5 = 'Here we can see the total numbers.', example_ko_5 = '여기서 총 수치를 볼 수 있습니다.' WHERE id = 'w_presentation_A1_13';
UPDATE words SET example_en_2 = 'Look at how the numbers changed.', example_ko_2 = '숫자가 어떻게 변했는지 보세요.', example_en_3 = 'Please look at the graph on the right.', example_ko_3 = '오른쪽 그래프를 봐주세요.', example_en_4 = 'Look at this example carefully.', example_ko_4 = '이 예시를 주의 깊게 보세요.', example_en_5 = 'Look at the trend over five years.', example_ko_5 = '5년간의 추세를 봐주세요.' WHERE id = 'w_presentation_A1_14';
UPDATE words SET example_en_2 = 'As you can see, sales went up.', example_ko_2 = '보시다시피 매출이 올랐습니다.', example_en_3 = 'I see. That makes sense now.', example_ko_3 = '이해했어요. 이제 말이 되네요.', example_en_4 = 'You can see the results on this slide.', example_ko_4 = '이 슬라이드에서 결과를 볼 수 있습니다.', example_en_5 = 'Do you see any pattern in this data?', example_ko_5 = '이 데이터에서 패턴이 보이나요?' WHERE id = 'w_presentation_A1_15';
UPDATE words SET example_en_2 = 'Do you know how many users we have?', example_ko_2 = '우리가 사용자를 얼마나 보유하고 있는지 아시나요?', example_en_3 = 'I know this topic very well.', example_ko_3 = '이 주제를 매우 잘 알고 있어요.', example_en_4 = 'Let me know if you have questions.', example_ko_4 = '질문이 있으시면 알려주세요.', example_en_5 = 'You may know this chart already.', example_ko_5 = '이 차트를 이미 알고 계실 수도 있어요.' WHERE id = 'w_presentation_A1_16';
UPDATE words SET example_en_2 = 'I hope this slide helps clarify things.', example_ko_2 = '이 슬라이드가 이해에 도움이 되길 바랍니다.', example_en_3 = 'These notes will help you study later.', example_ko_3 = '이 노트가 나중에 공부하는 데 도움이 될 거예요.', example_en_4 = 'Can I help you with the projector?', example_ko_4 = '프로젝터 도움이 필요하신가요?', example_en_5 = 'A simple example will help explain this.', example_ko_5 = '간단한 예시가 이것을 설명하는 데 도움이 될 거예요.' WHERE id = 'w_presentation_A1_17';
UPDATE words SET example_en_2 = 'I think the second option is better.', example_ko_2 = '두 번째 옵션이 더 낫다고 생각해요.', example_en_3 = 'What do you think about this idea?', example_ko_3 = '이 아이디어에 대해 어떻게 생각하세요?', example_en_4 = 'I think we need more data first.', example_ko_4 = '먼저 데이터가 더 필요하다고 생각해요.', example_en_5 = 'Think about what this means for us.', example_ko_5 = '이것이 우리에게 무엇을 의미하는지 생각해 보세요.' WHERE id = 'w_presentation_A1_18';
UPDATE words SET example_en_2 = 'This chart means we are growing fast.', example_ko_2 = '이 차트는 우리가 빠르게 성장하고 있다는 것을 의미해요.', example_en_3 = 'What does this graph mean exactly?', example_ko_3 = '이 그래프는 정확히 무엇을 의미하나요?', example_en_4 = 'I mean that the trend is positive.', example_ko_4 = '추세가 긍정적이라는 뜻이에요.', example_en_5 = 'That does not mean we should stop.', example_ko_5 = '그게 우리가 멈춰야 한다는 뜻은 아니에요.' WHERE id = 'w_presentation_A1_19';
UPDATE words SET example_en_2 = 'Are you ready for the next section?', example_ko_2 = '다음 섹션 준비가 되셨나요?', example_en_3 = 'She was ready with all the slides.', example_ko_3 = '그녀는 모든 슬라이드를 준비해 두었어요.', example_en_4 = 'Get ready — we start in two minutes.', example_ko_4 = '준비하세요 — 2분 후에 시작합니다.', example_en_5 = 'Is the projector ready to use?', example_ko_5 = '프로젝터가 사용 준비가 됐나요?' WHERE id = 'w_presentation_A1_20';
UPDATE words SET example_en_2 = 'The number on the left is last year''s total.', example_ko_2 = '왼쪽의 숫자는 작년 총계입니다.', example_en_3 = 'What does this number tell us?', example_ko_3 = '이 숫자는 우리에게 무엇을 말해주나요?', example_en_4 = 'Can you read the number on the screen?', example_ko_4 = '화면의 숫자를 읽어주실 수 있나요?', example_en_5 = 'The number of users doubled last year.', example_ko_5 = '작년에 사용자 수가 두 배로 늘었습니다.' WHERE id = 'w_presentation_A1_21';
UPDATE words SET example_en_2 = 'Please save your questions for the end.', example_ko_2 = '질문은 마지막까지 가지고 계세요.', example_en_3 = 'That is a great question — thank you.', example_ko_3 = '훌륭한 질문이에요 — 감사합니다.', example_en_4 = 'Does anyone have a question so far?', example_ko_4 = '지금까지 질문이 있으신 분 계신가요?', example_en_5 = 'I will answer every question at the end.', example_ko_5 = '모든 질문은 마지막에 답하겠습니다.' WHERE id = 'w_presentation_A1_22';
UPDATE words SET example_en_2 = 'This is a big opportunity for our team.', example_ko_2 = '이것은 우리 팀에 큰 기회입니다.', example_en_3 = 'The big challenge is time and cost.', example_ko_3 = '큰 과제는 시간과 비용입니다.', example_en_4 = 'We made a big improvement this year.', example_ko_4 = '올해 큰 개선이 이루어졌습니다.', example_en_5 = 'That is a big number — let me explain.', example_ko_5 = '큰 숫자네요 — 설명해 드리겠습니다.' WHERE id = 'w_presentation_A1_23';
UPDATE words SET example_en_2 = 'The first part is about the background.', example_ko_2 = '첫 번째 부분은 배경에 관한 것입니다.', example_en_3 = 'This part of the talk is very important.', example_ko_3 = '발표의 이 부분이 매우 중요합니다.', example_en_4 = 'Each part will take about ten minutes.', example_ko_4 = '각 부분은 약 10분 정도 소요됩니다.', example_en_5 = 'The best part of the project is the data.', example_ko_5 = '프로젝트에서 가장 좋은 부분은 데이터입니다.' WHERE id = 'w_presentation_A1_24';
UPDATE words SET example_en_2 = 'Our plan is to launch next quarter.', example_ko_2 = '우리의 계획은 다음 분기에 출시하는 것입니다.', example_en_3 = 'Do you have a plan for this problem?', example_ko_3 = '이 문제에 대한 계획이 있나요?', example_en_4 = 'Let me walk you through the plan.', example_ko_4 = '계획을 순서대로 안내해 드리겠습니다.', example_en_5 = 'The plan has four clear steps.', example_ko_5 = '계획에는 네 가지 명확한 단계가 있습니다.' WHERE id = 'w_presentation_A1_25';
UPDATE words SET example_en_2 = 'My idea is to change the schedule.', example_ko_2 = '제 아이디어는 일정을 바꾸는 것입니다.', example_en_3 = 'That is a great idea — let''s try it.', example_ko_3 = '훌륭한 아이디어네요 — 시도해 봐요.', example_en_4 = 'The core idea of this talk is simple.', example_ko_4 = '이 발표의 핵심 아이디어는 간단합니다.', example_en_5 = 'I got this idea from user feedback.', example_ko_5 = '이 아이디어는 사용자 피드백에서 얻었습니다.' WHERE id = 'w_presentation_A1_26';
UPDATE words SET example_en_2 = 'Step two is to collect the data.', example_ko_2 = '두 번째 단계는 데이터를 수집하는 것입니다.', example_en_3 = 'Follow these steps and you will succeed.', example_ko_3 = '이 단계들을 따르면 성공할 수 있어요.', example_en_4 = 'We are now on step three.', example_ko_4 = '우리는 지금 세 번째 단계에 있습니다.', example_en_5 = 'Each step is shown on this slide.', example_ko_5 = '각 단계가 이 슬라이드에 나와 있습니다.' WHERE id = 'w_presentation_A1_27';
UPDATE words SET example_en_2 = 'The key word here is "growth".', example_ko_2 = '여기서 핵심 단어는 "성장"입니다.', example_en_3 = 'I would like to say a few words about this.', example_ko_3 = '이에 대해 몇 말씀 드리고 싶습니다.', example_en_4 = 'In other words, the results are positive.', example_ko_4 = '다시 말해, 결과는 긍정적입니다.', example_en_5 = 'What word best describes this trend?', example_ko_5 = '이 추세를 가장 잘 설명하는 단어는 무엇인가요?' WHERE id = 'w_presentation_A1_28';
UPDATE words SET example_en_2 = 'I will keep this short — no extra time needed.', example_ko_2 = '짧게 하겠습니다 — 추가 시간이 필요 없어요.', example_en_3 = 'Is there enough time for a demo?', example_ko_3 = '데모를 할 시간이 충분한가요?', example_en_4 = 'Time management is key in a presentation.', example_ko_4 = '발표에서 시간 관리가 핵심입니다.', example_en_5 = 'We are running out of time — let me summarize.', example_ko_5 = '시간이 부족합니다 — 요약해 드리겠습니다.' WHERE id = 'w_presentation_A1_29';
UPDATE words SET example_en_2 = 'What is the name of this process?', example_ko_2 = '이 과정의 이름이 무엇인가요?', example_en_3 = 'My name is on the first slide.', example_ko_3 = '제 이름이 첫 번째 슬라이드에 있습니다.', example_en_4 = 'Let me write my name on the board.', example_ko_4 = '칠판에 제 이름을 쓰겠습니다.', example_en_5 = 'The name of our project is "Spark".', example_ko_5 = '우리 프로젝트의 이름은 "Spark"입니다.' WHERE id = 'w_presentation_A1_30';
UPDATE words SET example_en_2 = 'Right, that brings me to my next point.', example_ko_2 = '좋아요, 그것이 다음 요점으로 이어집니다.', example_en_3 = 'Right, let us continue with the plan.', example_ko_3 = '좋아요, 계획을 계속 진행하겠습니다.', example_en_4 = 'Is that right? Please correct me if not.', example_ko_4 = '맞나요? 아니라면 수정해 주세요.', example_en_5 = 'Right, I think we all understand now.', example_ko_5 = '좋아요, 이제 모두 이해하신 것 같습니다.' WHERE id = 'w_presentation_A1_31';
UPDATE words SET example_en_2 = 'Let me give you the context first.', example_ko_2 = '먼저 맥락을 말씀드리겠습니다.', example_en_3 = 'I will give you a few examples.', example_ko_3 = '몇 가지 예를 들어드리겠습니다.', example_en_4 = 'She will give the closing remarks.', example_ko_4 = '그녀가 마무리 발언을 할 것입니다.', example_en_5 = 'Can you give me a moment to check?', example_ko_5 = '확인할 시간을 조금 주시겠어요?' WHERE id = 'w_presentation_A1_32';
UPDATE words SET example_en_2 = 'This section covers our main findings.', example_ko_2 = '이 섹션은 우리의 주요 발견을 다룹니다.', example_en_3 = 'We will not cover everything today.', example_ko_3 = '오늘 모든 것을 다루지는 않을 거예요.', example_en_4 = 'The first part covers the background.', example_ko_4 = '첫 번째 부분은 배경을 다룹니다.', example_en_5 = 'I will cover the key points quickly.', example_ko_5 = '핵심 요점을 빠르게 다루겠습니다.' WHERE id = 'w_presentation_A1_33';
UPDATE words SET example_en_2 = 'This picture shows a clear trend.', example_ko_2 = '이 그림은 명확한 추세를 보여줍니다.', example_en_3 = 'Look at the picture on the right.', example_ko_3 = '오른쪽 그림을 봐주세요.', example_en_4 = 'The picture makes the idea very clear.', example_ko_4 = '그림이 아이디어를 매우 명확하게 만들어 줍니다.', example_en_5 = 'I chose this picture to illustrate the point.', example_ko_5 = '이 그림은 요점을 설명하기 위해 선택했습니다.' WHERE id = 'w_presentation_A1_34';
UPDATE words SET example_en_2 = 'This slide is about our target users.', example_ko_2 = '이 슬라이드는 우리의 목표 사용자에 대한 것입니다.', example_en_3 = 'Do you have any concerns about this?', example_ko_3 = '이에 대해 우려하시는 점이 있나요?', example_en_4 = 'Tell me more about your experience.', example_ko_4 = '경험에 대해 더 말씀해 주세요.', example_en_5 = 'This is about improving our process.', example_ko_5 = '이것은 우리 과정을 개선하는 것에 관한 것입니다.' WHERE id = 'w_presentation_A1_35';

-- ══════════════════════════════════════════════════════════════════
-- A2 (35단어)
-- ══════════════════════════════════════════════════════════════════
UPDATE words SET example_en_2 = 'I will introduce the agenda for today.', example_ko_2 = '오늘의 안건을 소개해 드리겠습니다.', example_en_3 = 'Please introduce yourself to the group.', example_ko_3 = '그룹에 자기소개를 해주세요.', example_en_4 = 'Let me introduce our new team member.', example_ko_4 = '새 팀원을 소개해 드리겠습니다.', example_en_5 = 'She introduced the topic with a story.', example_ko_5 = '그녀는 이야기로 주제를 소개했어요.' WHERE id = 'w_presentation_A2_01';
UPDATE words SET example_en_2 = 'The outline shows four main sections.', example_ko_2 = '개요는 네 개의 주요 섹션을 보여줍니다.', example_en_3 = 'Can you share the outline with us?', example_ko_3 = '개요를 공유해 주실 수 있나요?', example_en_4 = 'Follow the outline and stay on track.', example_ko_4 = '개요를 따라 진행해 주세요.', example_en_5 = 'I prepared a clear outline for this talk.', example_ko_5 = '이 발표를 위해 명확한 개요를 준비했습니다.' WHERE id = 'w_presentation_A2_02';
UPDATE words SET example_en_2 = 'Here is a summary of the key points.', example_ko_2 = '핵심 요점의 요약이 여기 있습니다.', example_en_3 = 'The summary is on the last slide.', example_ko_3 = '요약은 마지막 슬라이드에 있습니다.', example_en_4 = 'Write a short summary of what you heard.', example_ko_4 = '들은 내용의 짧은 요약을 써보세요.', example_en_5 = 'The executive summary fits on one page.', example_ko_5 = '요약 개요는 한 페이지에 맞습니다.' WHERE id = 'w_presentation_A2_03';
UPDATE words SET example_en_2 = 'Let me explain the topic first.', example_ko_2 = '먼저 주제를 설명하겠습니다.', example_en_3 = 'This topic is relevant to all of us.', example_ko_3 = '이 주제는 우리 모두와 관련이 있습니다.', example_en_4 = 'The topic comes up often in meetings.', example_ko_4 = '이 주제는 회의에서 자주 나옵니다.', example_en_5 = 'Choose a topic you know well.', example_ko_5 = '잘 아는 주제를 선택하세요.' WHERE id = 'w_presentation_A2_04';
UPDATE words SET example_en_2 = 'Let me explain why this matters.', example_ko_2 = '이것이 왜 중요한지 설명해 드리겠습니다.', example_en_3 = 'Can you explain the graph more clearly?', example_ko_3 = '그래프를 더 명확하게 설명해 주실 수 있나요?', example_en_4 = 'I will explain each step one by one.', example_ko_4 = '각 단계를 하나씩 설명하겠습니다.', example_en_5 = 'She explained the idea very simply.', example_ko_5 = '그녀는 아이디어를 매우 간단하게 설명했어요.' WHERE id = 'w_presentation_A2_05';
UPDATE words SET example_en_2 = 'Feel free to ask a question anytime.', example_ko_2 = '언제든지 자유롭게 질문해 주세요.', example_en_3 = 'I have one question about the data.', example_ko_3 = '데이터에 대해 질문이 하나 있어요.', example_en_4 = 'The question came from the audience.', example_ko_4 = '질문은 청중에게서 나왔습니다.', example_en_5 = 'Answer each question clearly and calmly.', example_ko_5 = '각 질문에 명확하고 침착하게 답하세요.' WHERE id = 'w_presentation_A2_06';
UPDATE words SET example_en_2 = 'She answered every question with confidence.', example_ko_2 = '그녀는 모든 질문에 자신 있게 답했어요.', example_en_3 = 'I will answer your question after the talk.', example_ko_3 = '발표 후에 질문에 답해드리겠습니다.', example_en_4 = 'He could not answer the last question.', example_ko_4 = '그는 마지막 질문에 답하지 못했어요.', example_en_5 = 'Please answer in one or two sentences.', example_ko_5 = '한두 문장으로 답해 주세요.' WHERE id = 'w_presentation_A2_07';
UPDATE words SET example_en_2 = 'The audience was very engaged today.', example_ko_2 = '오늘 청중이 매우 적극적으로 참여했어요.', example_en_3 = 'Make eye contact with your audience.', example_ko_3 = '청중과 눈을 마주치세요.', example_en_4 = 'The audience asked many great questions.', example_ko_4 = '청중이 훌륭한 질문을 많이 했어요.', example_en_5 = 'Know your audience before you start.', example_ko_5 = '시작하기 전에 청중을 파악하세요.' WHERE id = 'w_presentation_A2_08';
UPDATE words SET example_en_2 = 'She will present the new product today.', example_ko_2 = '그녀가 오늘 새 제품을 발표할 거예요.', example_en_3 = 'I will present the findings next week.', example_ko_3 = '다음 주에 발견 사항을 발표하겠습니다.', example_en_4 = 'He presented clearly and with confidence.', example_ko_4 = '그는 명확하고 자신 있게 발표했어요.', example_en_5 = 'We will present to the board on Friday.', example_ko_5 = '금요일에 이사회에 발표하겠습니다.' WHERE id = 'w_presentation_A2_09';
UPDATE words SET example_en_2 = 'The conclusion is on the final slide.', example_ko_2 = '결론은 마지막 슬라이드에 있습니다.', example_en_3 = 'What conclusion can we draw from this?', example_ko_3 = '이것으로부터 어떤 결론을 도출할 수 있나요?', example_en_4 = 'Her conclusion was clear and memorable.', example_ko_4 = '그녀의 결론은 명확하고 기억에 남았어요.', example_en_5 = 'End with a strong conclusion every time.', example_ko_5 = '매번 강력한 결론으로 마무리하세요.' WHERE id = 'w_presentation_A2_10';
UPDATE words SET example_en_2 = 'This section focuses on our findings.', example_ko_2 = '이 섹션은 우리의 발견에 초점을 맞춥니다.', example_en_3 = 'The first section covers the background.', example_ko_3 = '첫 번째 섹션은 배경을 다룹니다.', example_en_4 = 'Each section is about ten minutes long.', example_ko_4 = '각 섹션은 약 10분 길이입니다.', example_en_5 = 'Move to the next section when ready.', example_ko_5 = '준비가 되면 다음 섹션으로 넘어가세요.' WHERE id = 'w_presentation_A2_11';
UPDATE words SET example_en_2 = 'The main idea is shown on this slide.', example_ko_2 = '주요 아이디어가 이 슬라이드에 나와 있습니다.', example_en_3 = 'What is the main message of this chart?', example_ko_3 = '이 차트의 주요 메시지는 무엇인가요?', example_en_4 = 'The main challenge is budget and time.', example_ko_4 = '주요 과제는 예산과 시간입니다.', example_en_5 = 'Focus on the main point — do not add too much.', example_ko_5 = '주요 요점에 집중하세요 — 너무 많이 추가하지 마세요.' WHERE id = 'w_presentation_A2_12';
UPDATE words SET example_en_2 = 'Here is a real-life example for you.', example_ko_2 = '실제 사례를 하나 들어드리겠습니다.', example_en_3 = 'Can you give another example?', example_ko_3 = '다른 예시를 들어주실 수 있나요?', example_en_4 = 'This example shows the problem clearly.', example_ko_4 = '이 예시는 문제를 명확하게 보여줍니다.', example_en_5 = 'Use real examples to make your point.', example_ko_5 = '요점을 전달하기 위해 실제 예시를 사용하세요.' WHERE id = 'w_presentation_A2_13';
UPDATE words SET example_en_2 = 'The chart on the left shows last year.', example_ko_2 = '왼쪽 차트는 작년을 보여줍니다.', example_en_3 = 'Can you make the chart bigger?', example_ko_3 = '차트를 더 크게 만들어 주실 수 있나요?', example_en_4 = 'This bar chart compares two products.', example_ko_4 = '이 막대 차트는 두 제품을 비교합니다.', example_en_5 = 'The chart makes the numbers easy to read.', example_ko_5 = '차트가 숫자를 읽기 쉽게 만들어 줍니다.' WHERE id = 'w_presentation_A2_14';
UPDATE words SET example_en_2 = 'The graph shows a steady rise.', example_ko_2 = '그래프가 꾸준한 상승을 보여줍니다.', example_en_3 = 'Look at the graph — the trend is clear.', example_ko_3 = '그래프를 보세요 — 추세가 명확합니다.', example_en_4 = 'This line graph covers five years.', example_ko_4 = '이 꺾은선 그래프는 5년을 다룹니다.', example_en_5 = 'Use a graph to show changes over time.', example_ko_5 = '시간에 따른 변화를 보여주려면 그래프를 사용하세요.' WHERE id = 'w_presentation_A2_15';
UPDATE words SET example_en_2 = 'The figure on page three is very helpful.', example_ko_2 = '3페이지의 수치가 매우 도움이 됩니다.', example_en_3 = 'What does this figure represent?', example_ko_3 = '이 수치는 무엇을 나타내나요?', example_en_4 = 'The figure went up by thirty percent.', example_ko_4 = '수치가 30% 올랐습니다.', example_en_5 = 'Please check the figure in the appendix.', example_ko_5 = '부록의 수치를 확인해 주세요.' WHERE id = 'w_presentation_A2_16';
UPDATE words SET example_en_2 = 'What is the goal of this project?', example_ko_2 = '이 프로젝트의 목표는 무엇인가요?', example_en_3 = 'Our goal is to improve customer service.', example_ko_3 = '우리의 목표는 고객 서비스를 개선하는 것입니다.', example_en_4 = 'Set a clear goal before you start.', example_ko_4 = '시작하기 전에 명확한 목표를 설정하세요.', example_en_5 = 'Did we meet our goal this quarter?', example_ko_5 = '이번 분기에 목표를 달성했나요?' WHERE id = 'w_presentation_A2_17';
UPDATE words SET example_en_2 = 'The result surprised our whole team.', example_ko_2 = '결과가 우리 팀 전체를 놀라게 했습니다.', example_en_3 = 'What was the result of the survey?', example_ko_3 = '설문 조사의 결과가 어떠했나요?', example_en_4 = 'The result shows that users are satisfied.', example_ko_4 = '결과는 사용자들이 만족한다는 것을 보여줍니다.', example_en_5 = 'We will share the final results tomorrow.', example_ko_5 = '최종 결과는 내일 공유하겠습니다.' WHERE id = 'w_presentation_A2_18';
UPDATE words SET example_en_2 = 'The reason we changed was user feedback.', example_ko_2 = '우리가 변경한 이유는 사용자 피드백이었습니다.', example_en_3 = 'Can you explain the reason for this drop?', example_ko_3 = '이 하락의 이유를 설명해 주실 수 있나요?', example_en_4 = 'Give a reason for each recommendation.', example_ko_4 = '각 권장 사항에 대한 이유를 제시하세요.', example_en_5 = 'The reason is clear from the data.', example_ko_5 = '이유는 데이터에서 명확합니다.' WHERE id = 'w_presentation_A2_19';
UPDATE words SET example_en_2 = 'The problem is easy to see in the chart.', example_ko_2 = '문제는 차트에서 쉽게 볼 수 있습니다.', example_en_3 = 'What is the main problem we face?', example_ko_3 = '우리가 직면한 주요 문제는 무엇인가요?', example_en_4 = 'Define the problem before finding a solution.', example_ko_4 = '해결책을 찾기 전에 문제를 정의하세요.', example_en_5 = 'The problem affects many users today.', example_ko_5 = '문제는 오늘날 많은 사용자들에게 영향을 미칩니다.' WHERE id = 'w_presentation_A2_20';
UPDATE words SET example_en_2 = 'The solution is both simple and effective.', example_ko_2 = '해결책은 간단하면서도 효과적입니다.', example_en_3 = 'We found a solution to the problem.', example_ko_3 = '우리는 문제에 대한 해결책을 찾았습니다.', example_en_4 = 'Present the solution after the problem.', example_ko_4 = '문제 다음에 해결책을 제시하세요.', example_en_5 = 'The solution works for all user groups.', example_ko_5 = '해결책은 모든 사용자 그룹에 효과가 있습니다.' WHERE id = 'w_presentation_A2_21';
UPDATE words SET example_en_2 = 'The project is on track to finish on time.', example_ko_2 = '프로젝트는 제시간에 완료할 예정입니다.', example_en_3 = 'Let me show you the project timeline.', example_ko_3 = '프로젝트 타임라인을 보여드리겠습니다.', example_en_4 = 'The project involves three departments.', example_ko_4 = '프로젝트에는 세 부서가 관여합니다.', example_en_5 = 'This project started in January this year.', example_ko_5 = '이 프로젝트는 올해 1월에 시작됐습니다.' WHERE id = 'w_presentation_A2_22';
UPDATE words SET example_en_2 = 'The data comes from a survey of 500 users.', example_ko_2 = '데이터는 500명의 사용자 설문에서 나왔습니다.', example_en_3 = 'All data has been verified carefully.', example_ko_3 = '모든 데이터는 신중하게 검증되었습니다.', example_en_4 = 'What does the data tell us?', example_ko_4 = '데이터는 우리에게 무엇을 말해주나요?', example_en_5 = 'Use data to support every claim you make.', example_ko_5 = '하는 모든 주장을 데이터로 뒷받침하세요.' WHERE id = 'w_presentation_A2_23';
UPDATE words SET example_en_2 = 'Our full report is available online.', example_ko_2 = '전체 보고서는 온라인에서 확인할 수 있습니다.', example_en_3 = 'This slide summarizes the report.', example_ko_3 = '이 슬라이드는 보고서를 요약합니다.', example_en_4 = 'Please read the report before the meeting.', example_ko_4 = '회의 전에 보고서를 읽어주세요.', example_en_5 = 'The report includes charts and tables.', example_ko_5 = '보고서에는 차트와 표가 포함되어 있습니다.' WHERE id = 'w_presentation_A2_24';
UPDATE words SET example_en_2 = 'This change will reduce costs by 20%.', example_ko_2 = '이 변화는 비용을 20% 줄일 것입니다.', example_en_3 = 'What caused this change in the data?', example_ko_3 = '데이터의 이 변화는 무엇이 원인인가요?', example_en_4 = 'Change takes time and planning.', example_ko_4 = '변화에는 시간과 계획이 필요합니다.', example_en_5 = 'The change happened in the third quarter.', example_ko_5 = '변화는 3분기에 발생했습니다.' WHERE id = 'w_presentation_A2_25';
UPDATE words SET example_en_2 = 'There was a 15% increase in revenue.', example_ko_2 = '매출이 15% 증가했습니다.', example_en_3 = 'The increase is shown in the blue bar.', example_ko_3 = '증가는 파란 막대에 나타납니다.', example_en_4 = 'We expect an increase next quarter too.', example_ko_4 = '다음 분기에도 증가를 기대합니다.', example_en_5 = 'What caused the sudden increase in users?', example_ko_5 = '사용자의 갑작스러운 증가는 무엇이 원인인가요?' WHERE id = 'w_presentation_A2_26';
UPDATE words SET example_en_2 = 'The decrease in cost was unexpected.', example_ko_2 = '비용 감소는 예상치 못한 것이었습니다.', example_en_3 = 'We saw a decrease in complaints last month.', example_ko_3 = '지난달 불만이 감소했습니다.', example_en_4 = 'The decrease is visible on the graph.', example_ko_4 = '감소는 그래프에서 볼 수 있습니다.', example_en_5 = 'What caused this decrease in engagement?', example_ko_5 = '참여 감소의 원인이 무엇인가요?' WHERE id = 'w_presentation_A2_27';
UPDATE words SET example_en_2 = 'The total number of responses is 240.', example_ko_2 = '총 응답 수는 240개입니다.', example_en_3 = 'Add everything up to get the total.', example_ko_3 = '모든 것을 더해 합계를 구하세요.', example_en_4 = 'The total cost is shown at the bottom.', example_ko_4 = '총 비용은 하단에 나와 있습니다.', example_en_5 = 'The total includes all departments.', example_ko_5 = '합계에는 모든 부서가 포함됩니다.' WHERE id = 'w_presentation_A2_28';
UPDATE words SET example_en_2 = 'Let us compare the results from both years.', example_ko_2 = '두 해의 결과를 비교해 보겠습니다.', example_en_3 = 'Compare option A with option B.', example_ko_3 = '옵션 A와 옵션 B를 비교하세요.', example_en_4 = 'This slide helps us compare the data.', example_ko_4 = '이 슬라이드는 데이터를 비교하는 데 도움이 됩니다.', example_en_5 = 'It is easy to compare using a bar chart.', example_ko_5 = '막대 차트를 사용하면 비교하기 쉽습니다.' WHERE id = 'w_presentation_A2_29';
UPDATE words SET example_en_2 = 'Do you agree with this interpretation?', example_ko_2 = '이 해석에 동의하시나요?', example_en_3 = 'Most of the team agrees with the plan.', example_ko_3 = '팀 대부분이 계획에 동의합니다.', example_en_4 = 'We agree that more research is needed.', example_ko_4 = '더 많은 연구가 필요하다는 데 동의합니다.', example_en_5 = 'If you agree, we can move to the next step.', example_ko_5 = '동의하시면 다음 단계로 넘어갈 수 있습니다.' WHERE id = 'w_presentation_A2_30';
UPDATE words SET example_en_2 = 'Is the message on this slide clear?', example_ko_2 = '이 슬라이드의 메시지가 명확한가요?', example_en_3 = 'Please make your conclusion clear.', example_ko_3 = '결론을 명확하게 해주세요.', example_en_4 = 'Speak in a clear and calm voice.', example_ko_4 = '명확하고 침착한 목소리로 말하세요.', example_en_5 = 'Her slides were clean and very clear.', example_ko_5 = '그녀의 슬라이드는 깔끔하고 매우 명확했어요.' WHERE id = 'w_presentation_A2_31';
UPDATE words SET example_en_2 = 'I will be brief — just five minutes.', example_ko_2 = '짧게 하겠습니다 — 5분만요.', example_en_3 = 'Give a brief summary at the end.', example_ko_3 = '마지막에 간략한 요약을 해주세요.', example_en_4 = 'Keep your introduction brief and clear.', example_ko_4 = '소개를 간략하고 명확하게 유지하세요.', example_en_5 = 'A brief pause can help the audience think.', example_ko_5 = '짧은 멈춤이 청중이 생각하는 데 도움이 됩니다.' WHERE id = 'w_presentation_A2_32';
UPDATE words SET example_en_2 = 'Background information helps the audience understand.', example_ko_2 = '배경 정보가 청중이 이해하는 데 도움이 됩니다.', example_en_3 = 'Let me give you some quick background.', example_ko_3 = '간단한 배경 정보를 드리겠습니다.', example_en_4 = 'The background section is very short.', example_ko_4 = '배경 섹션은 매우 짧습니다.', example_en_5 = 'Start with background before the data.', example_ko_5 = '데이터 전에 배경으로 시작하세요.' WHERE id = 'w_presentation_A2_33';
UPDATE words SET example_en_2 = 'Let us focus on the key numbers.', example_ko_2 = '핵심 숫자에 집중해 보겠습니다.', example_en_3 = 'Focus on what the audience needs.', example_ko_3 = '청중이 필요한 것에 집중하세요.', example_en_4 = 'I will focus on two main areas today.', example_ko_4 = '오늘은 두 가지 주요 영역에 집중하겠습니다.', example_en_5 = 'Keep your slides focused on one idea.', example_ko_5 = '슬라이드를 하나의 아이디어에 집중시키세요.' WHERE id = 'w_presentation_A2_34';
UPDATE words SET example_en_2 = 'I would like to share a quick story.', example_ko_2 = '짧은 이야기를 공유하고 싶습니다.', example_en_3 = 'Please share your feedback with us.', example_ko_3 = '피드백을 공유해 주세요.', example_en_4 = 'We share our slides after every talk.', example_ko_4 = '우리는 매 발표 후에 슬라이드를 공유합니다.', example_en_5 = 'She shared the report with the whole team.', example_ko_5 = '그녀는 팀 전체와 보고서를 공유했어요.' WHERE id = 'w_presentation_A2_35';

-- ══════════════════════════════════════════════════════════════════
-- B1 (35단어)
-- ══════════════════════════════════════════════════════════════════
UPDATE words SET example_en_2 = 'I want to highlight the third finding.', example_ko_2 = '세 번째 발견을 강조하고 싶습니다.', example_en_3 = 'She highlighted the most important data.', example_ko_3 = '그녀는 가장 중요한 데이터를 강조했어요.', example_en_4 = 'Please highlight the key takeaways.', example_ko_4 = '핵심 내용을 강조해 주세요.', example_en_5 = 'The chart highlights the growth trend.', example_ko_5 = '차트가 성장 추세를 강조합니다.' WHERE id = 'w_presentation_B1_01';
UPDATE words SET example_en_2 = 'Let me make a smooth transition here.', example_ko_2 = '여기서 부드럽게 전환하겠습니다.', example_en_3 = 'The transition between sections was clear.', example_ko_3 = '섹션 간 전환이 명확했습니다.', example_en_4 = 'Use a sentence to signal the transition.', example_ko_4 = '전환을 알리는 문장을 사용하세요.', example_en_5 = 'Now let''s make a transition to our findings.', example_ko_5 = '이제 발견 사항으로 전환하겠습니다.' WHERE id = 'w_presentation_B1_02';
UPDATE words SET example_en_2 = 'A case study will illustrate the point.', example_ko_2 = '사례 연구가 요점을 설명할 것입니다.', example_en_3 = 'This diagram illustrates the process.', example_ko_3 = '이 다이어그램이 과정을 설명합니다.', example_en_4 = 'Let me illustrate with a simple example.', example_ko_4 = '간단한 예시로 설명해 드리겠습니다.', example_en_5 = 'The video illustrates the concept well.', example_ko_5 = '영상이 개념을 잘 설명합니다.' WHERE id = 'w_presentation_B1_03';
UPDATE words SET example_en_2 = 'I need to emphasize this point again.', example_ko_2 = '이 요점을 다시 강조해야 합니다.', example_en_3 = 'She emphasized the deadline clearly.', example_ko_3 = '그녀는 마감일을 명확하게 강조했어요.', example_en_4 = 'Emphasize your strongest evidence first.', example_ko_4 = '가장 강력한 증거를 먼저 강조하세요.', example_en_5 = 'The bold text emphasizes the key word.', example_ko_5 = '굵은 텍스트가 핵심 단어를 강조합니다.' WHERE id = 'w_presentation_B1_04';
UPDATE words SET example_en_2 = 'Could you elaborate on that last point?', example_ko_2 = '마지막 요점에 대해 더 자세히 설명해 주시겠어요?', example_en_3 = 'She elaborated on the risks clearly.', example_ko_3 = '그녀는 위험 요소를 명확하게 자세히 설명했어요.', example_en_4 = 'I will elaborate on this in the next section.', example_ko_4 = '다음 섹션에서 이에 대해 더 자세히 설명하겠습니다.', example_en_5 = 'Please elaborate — we have time.', example_ko_5 = '자세히 설명해 주세요 — 시간이 있습니다.' WHERE id = 'w_presentation_B1_05';
UPDATE words SET example_en_2 = 'I will start with a brief overview.', example_ko_2 = '간단한 개요로 시작하겠습니다.', example_en_3 = 'The overview helps the audience understand.', example_ko_3 = '개요가 청중이 이해하는 데 도움이 됩니다.', example_en_4 = 'Here is an overview of today''s agenda.', example_ko_4 = '오늘 안건의 개요입니다.', example_en_5 = 'The overview slide has three main points.', example_ko_5 = '개요 슬라이드에는 세 가지 주요 요점이 있습니다.' WHERE id = 'w_presentation_B1_06';
UPDATE words SET example_en_2 = 'The objective is to reduce cost by 10%.', example_ko_2 = '목적은 비용을 10% 줄이는 것입니다.', example_en_3 = 'State your objective on the first slide.', example_ko_3 = '첫 번째 슬라이드에 목적을 명시하세요.', example_en_4 = 'Did we achieve our original objective?', example_ko_4 = '원래의 목적을 달성했나요?', example_en_5 = 'The objective guides the whole presentation.', example_ko_5 = '목적이 전체 발표를 이끌어 줍니다.' WHERE id = 'w_presentation_B1_07';
UPDATE words SET example_en_2 = 'Our main finding is that costs dropped.', example_ko_2 = '우리의 주요 발견은 비용이 줄었다는 것입니다.', example_en_3 = 'Each finding is supported by data.', example_ko_3 = '각 발견은 데이터로 뒷받침됩니다.', example_en_4 = 'Present your findings in order of importance.', example_ko_4 = '발견 사항을 중요도 순으로 제시하세요.', example_en_5 = 'The finding was unexpected but positive.', example_ko_5 = '발견은 예상치 못했지만 긍정적이었습니다.' WHERE id = 'w_presentation_B1_08';
UPDATE words SET example_en_2 = 'The results were better than expected.', example_ko_2 = '결과가 예상보다 좋았습니다.', example_en_3 = 'I will now present the final results.', example_ko_3 = '이제 최종 결과를 발표하겠습니다.', example_en_4 = 'The results confirm our original hypothesis.', example_ko_4 = '결과가 원래의 가설을 확인해 줍니다.', example_en_5 = 'These results have real business implications.', example_ko_5 = '이 결과는 실제 비즈니스 시사점이 있습니다.' WHERE id = 'w_presentation_B1_09';
UPDATE words SET example_en_2 = 'I recommend starting the pilot next month.', example_ko_2 = '다음 달에 파일럿을 시작할 것을 권장합니다.', example_en_3 = 'What solution do you recommend?', example_ko_3 = '어떤 해결책을 권장하시나요?', example_en_4 = 'We recommend option B for its lower cost.', example_ko_4 = '낮은 비용 때문에 옵션 B를 권장합니다.', example_en_5 = 'Our team strongly recommends this approach.', example_ko_5 = '우리 팀은 이 접근법을 강력히 권장합니다.' WHERE id = 'w_presentation_B1_10';
UPDATE words SET example_en_2 = 'Our approach is both fast and affordable.', example_ko_2 = '우리의 접근법은 빠르고 저렴합니다.', example_en_3 = 'Let me explain the approach we used.', example_ko_3 = '우리가 사용한 접근법을 설명하겠습니다.', example_en_4 = 'The approach was tested with real users.', example_ko_4 = '접근법은 실제 사용자로 테스트되었습니다.', example_en_5 = 'Consider a different approach next time.', example_ko_5 = '다음에는 다른 접근법을 고려해 보세요.' WHERE id = 'w_presentation_B1_11';
UPDATE words SET example_en_2 = 'Let me demonstrate how this tool is used.', example_ko_2 = '이 도구가 어떻게 사용되는지 시연해 드리겠습니다.', example_en_3 = 'She demonstrated the process live.', example_ko_3 = '그녀는 과정을 생중계로 시연했어요.', example_en_4 = 'The data demonstrates a clear trend.', example_ko_4 = '데이터가 명확한 추세를 보여줍니다.', example_en_5 = 'A live demo will demonstrate the product.', example_ko_5 = '라이브 데모가 제품을 시연할 것입니다.' WHERE id = 'w_presentation_B1_12';
UPDATE words SET example_en_2 = 'The structure helps the audience follow.', example_ko_2 = '구조가 청중이 따라오는 데 도움이 됩니다.', example_en_3 = 'Plan the structure before writing slides.', example_ko_3 = '슬라이드를 쓰기 전에 구조를 계획하세요.', example_en_4 = 'A good structure makes every talk better.', example_ko_4 = '좋은 구조가 모든 발표를 더 좋게 만듭니다.', example_en_5 = 'The structure has an intro, body, and close.', example_ko_5 = '구조에는 도입, 본문, 마무리가 있습니다.' WHERE id = 'w_presentation_B1_13';
UPDATE words SET example_en_2 = 'The evidence is shown in the table.', example_ko_2 = '증거가 표에 나와 있습니다.', example_en_3 = 'We need strong evidence to support this.', example_ko_3 = '이것을 뒷받침하기 위해 강력한 증거가 필요합니다.', example_en_4 = 'All evidence comes from reliable sources.', example_ko_4 = '모든 증거는 신뢰할 수 있는 출처에서 나옵니다.', example_en_5 = 'The evidence points to a clear conclusion.', example_ko_5 = '증거가 명확한 결론을 가리킵니다.' WHERE id = 'w_presentation_B1_14';
UPDATE words SET example_en_2 = 'The implication for our team is clear.', example_ko_2 = '우리 팀에 대한 시사점이 명확합니다.', example_en_3 = 'Think about the implications carefully.', example_ko_3 = '시사점을 신중하게 생각해 보세요.', example_en_4 = 'The implication is that we need to act now.', example_ko_4 = '시사점은 지금 행동해야 한다는 것입니다.', example_en_5 = 'What are the implications for our strategy?', example_ko_5 = '우리 전략에 대한 시사점이 무엇인가요?' WHERE id = 'w_presentation_B1_15';
UPDATE words SET example_en_2 = 'Every challenge is a learning opportunity.', example_ko_2 = '모든 과제는 학습 기회입니다.', example_en_3 = 'The biggest challenge was collecting data.', example_ko_3 = '가장 큰 과제는 데이터 수집이었습니다.', example_en_4 = 'Acknowledge the challenge before proposing a fix.', example_ko_4 = '해결책을 제안하기 전에 과제를 인정하세요.', example_en_5 = 'This challenge requires a creative solution.', example_ko_5 = '이 과제에는 창의적인 해결책이 필요합니다.' WHERE id = 'w_presentation_B1_16';
UPDATE words SET example_en_2 = 'Our strategy is based on user research.', example_ko_2 = '우리의 전략은 사용자 연구를 기반으로 합니다.', example_en_3 = 'The strategy has three clear phases.', example_ko_3 = '전략에는 세 가지 명확한 단계가 있습니다.', example_en_4 = 'Define your strategy before the presentation.', example_ko_4 = '발표 전에 전략을 정의하세요.', example_en_5 = 'We will evaluate the strategy after six months.', example_ko_5 = '6개월 후에 전략을 평가하겠습니다.' WHERE id = 'w_presentation_B1_17';
UPDATE words SET example_en_2 = 'The impact of this change was immediate.', example_ko_2 = '이 변화의 영향은 즉각적이었습니다.', example_en_3 = 'Measure the impact after implementation.', example_ko_3 = '구현 후에 영향을 측정하세요.', example_en_4 = 'What impact did this have on the users?', example_ko_4 = '이것이 사용자에게 어떤 영향을 미쳤나요?', example_en_5 = 'The impact is visible in the graph.', example_ko_5 = '영향이 그래프에서 보입니다.' WHERE id = 'w_presentation_B1_18';
UPDATE words SET example_en_2 = 'The trend is moving in a positive direction.', example_ko_2 = '추세가 긍정적인 방향으로 이동하고 있습니다.', example_en_3 = 'What trend do you see in this data?', example_ko_3 = '이 데이터에서 어떤 추세가 보이나요?', example_en_4 = 'The trend started three years ago.', example_ko_4 = '추세는 3년 전에 시작되었습니다.', example_en_5 = 'Track the trend over at least two years.', example_ko_5 = '추세를 최소 2년간 추적하세요.' WHERE id = 'w_presentation_B1_19';
UPDATE words SET example_en_2 = 'This is a significant improvement over last year.', example_ko_2 = '이것은 작년에 비해 상당한 개선입니다.', example_en_3 = 'The difference is statistically significant.', example_ko_3 = '차이가 통계적으로 유의미합니다.', example_en_4 = 'This is a significant finding for the team.', example_ko_4 = '이것은 팀에게 중요한 발견입니다.', example_en_5 = 'The significant rise was caused by marketing.', example_ko_5 = '상당한 상승은 마케팅에 의해 발생했습니다.' WHERE id = 'w_presentation_B1_20';
UPDATE words SET example_en_2 = 'Our key assumption is that demand will grow.', example_ko_2 = '우리의 핵심 가정은 수요가 증가할 것이라는 점입니다.', example_en_3 = 'State your assumption clearly to the audience.', example_ko_3 = '청중에게 가정을 명확하게 진술하세요.', example_en_4 = 'This assumption was later confirmed by data.', example_ko_4 = '이 가정은 나중에 데이터로 확인되었습니다.', example_en_5 = 'Challenge every assumption before presenting.', example_ko_5 = '발표 전에 모든 가정에 도전해 보세요.' WHERE id = 'w_presentation_B1_21';
UPDATE words SET example_en_2 = 'We modeled three scenarios for next year.', example_ko_2 = '내년을 위한 세 가지 시나리오를 모델링했습니다.', example_en_3 = 'In the worst scenario, sales drop by 5%.', example_ko_3 = '최악의 시나리오에서는 매출이 5% 감소합니다.', example_en_4 = 'The scenario is based on current trends.', example_ko_4 = '시나리오는 현재 추세를 기반으로 합니다.', example_en_5 = 'Let me walk you through each scenario.', example_ko_5 = '각 시나리오를 순서대로 설명해 드리겠습니다.' WHERE id = 'w_presentation_B1_22';
UPDATE words SET example_en_2 = 'The proposal was well received by the board.', example_ko_2 = '제안서가 이사회에서 좋은 반응을 얻었습니다.', example_en_3 = 'Our proposal includes a detailed timeline.', example_ko_3 = '우리의 제안서에는 상세한 타임라인이 포함됩니다.', example_en_4 = 'Submit the proposal before the deadline.', example_ko_4 = '마감일 전에 제안서를 제출하세요.', example_en_5 = 'The proposal covers cost, time, and risk.', example_ko_5 = '제안서는 비용, 시간, 위험을 다룹니다.' WHERE id = 'w_presentation_B1_23';
UPDATE words SET example_en_2 = 'The benefit of this plan is lower cost.', example_ko_2 = '이 계획의 이점은 낮은 비용입니다.', example_en_3 = 'List each benefit clearly on the slide.', example_ko_3 = '각 이점을 슬라이드에 명확하게 나열하세요.', example_en_4 = 'The greatest benefit is saved time.', example_ko_4 = '가장 큰 이점은 절약된 시간입니다.', example_en_5 = 'Explain the benefit before asking for approval.', example_ko_5 = '승인을 요청하기 전에 이점을 설명하세요.' WHERE id = 'w_presentation_B1_24';
UPDATE words SET example_en_2 = 'A valid concern is the cost of change.', example_ko_2 = '타당한 우려 사항은 변화의 비용입니다.', example_en_3 = 'I understand your concern about the timeline.', example_ko_3 = '타임라인에 대한 우려를 이해합니다.', example_en_4 = 'Address each concern before it becomes a problem.', example_ko_4 = '각 우려가 문제가 되기 전에 해결하세요.', example_en_5 = 'The main concern is the project budget.', example_ko_5 = '주요 우려 사항은 프로젝트 예산입니다.' WHERE id = 'w_presentation_B1_25';
UPDATE words SET example_en_2 = 'The process has been improved this year.', example_ko_2 = '과정이 올해 개선되었습니다.', example_en_3 = 'This slide explains each step of the process.', example_ko_3 = '이 슬라이드는 과정의 각 단계를 설명합니다.', example_en_4 = 'Simplify the process to save time.', example_ko_4 = '시간을 절약하기 위해 과정을 단순화하세요.', example_en_5 = 'The process diagram is on the next slide.', example_ko_5 = '과정 다이어그램이 다음 슬라이드에 있습니다.' WHERE id = 'w_presentation_B1_26';
UPDATE words SET example_en_2 = 'The desired outcome is 20% more efficiency.', example_ko_2 = '목표 성과는 20% 더 높은 효율성입니다.', example_en_3 = 'What outcome are you expecting from this?', example_ko_3 = '이것으로 어떤 성과를 기대하시나요?', example_en_4 = 'The outcome was positive for both teams.', example_ko_4 = '성과는 두 팀 모두에게 긍정적이었습니다.', example_en_5 = 'Define a clear outcome before you start.', example_ko_5 = '시작하기 전에 명확한 성과를 정의하세요.' WHERE id = 'w_presentation_B1_27';
UPDATE words SET example_en_2 = 'This approach has been proven effective.', example_ko_2 = '이 접근법이 효과적임이 증명되었습니다.', example_en_3 = 'What makes this method so effective?', example_ko_3 = '이 방법이 그렇게 효과적인 이유가 무엇인가요?', example_en_4 = 'The new process is more effective than before.', example_ko_4 = '새 과정이 이전보다 더 효과적입니다.', example_en_5 = 'Simple slides are often the most effective.', example_ko_5 = '간단한 슬라이드가 종종 가장 효과적입니다.' WHERE id = 'w_presentation_B1_28';
UPDATE words SET example_en_2 = 'Only relevant data has been included here.', example_ko_2 = '여기에는 관련성 있는 데이터만 포함되었습니다.', example_en_3 = 'Is this example relevant to the topic?', example_ko_3 = '이 예시가 주제와 관련이 있나요?', example_en_4 = 'Choose relevant examples for each point.', example_ko_4 = '각 요점에 관련성 있는 예시를 선택하세요.', example_en_5 = 'The most relevant finding is highlighted.', example_ko_5 = '가장 관련성 있는 발견이 강조되어 있습니다.' WHERE id = 'w_presentation_B1_29';
UPDATE words SET example_en_2 = 'I will expand on this in the Q&A.', example_ko_2 = '질의응답에서 이에 대해 자세히 설명하겠습니다.', example_en_3 = 'Can you expand on your last comment?', example_ko_3 = '마지막 의견을 더 자세히 설명해 주시겠어요?', example_en_4 = 'Expand the explanation if needed.', example_ko_4 = '필요하다면 설명을 확장하세요.', example_en_5 = 'She expanded on the topic with new examples.', example_ko_5 = '그녀는 새로운 예시로 주제를 자세히 설명했어요.' WHERE id = 'w_presentation_B1_30';
UPDATE words SET example_en_2 = 'The current data shows steady growth.', example_ko_2 = '현재 데이터가 꾸준한 성장을 보여줍니다.', example_en_3 = 'What is the current state of the project?', example_ko_3 = '프로젝트의 현재 상태가 어떤가요?', example_en_4 = 'Compare current results with last year.', example_ko_4 = '현재 결과와 작년을 비교하세요.', example_en_5 = 'Our current plan needs to be updated.', example_ko_5 = '우리의 현재 계획을 업데이트해야 합니다.' WHERE id = 'w_presentation_B1_31';
UPDATE words SET example_en_2 = 'The methodology is explained on slide four.', example_ko_2 = '방법론은 4번 슬라이드에 설명되어 있습니다.', example_en_3 = 'Our methodology follows industry standards.', example_ko_3 = '우리의 방법론은 업계 표준을 따릅니다.', example_en_4 = 'Explain your methodology before the results.', example_ko_4 = '결과 전에 방법론을 설명하세요.', example_en_5 = 'A solid methodology builds credibility.', example_ko_5 = '탄탄한 방법론이 신뢰성을 구축합니다.' WHERE id = 'w_presentation_B1_32';
UPDATE words SET example_en_2 = 'The timeline shows key milestones.', example_ko_2 = '타임라인이 주요 이정표를 보여줍니다.', example_en_3 = 'Please keep the timeline realistic.', example_ko_3 = '타임라인을 현실적으로 유지하세요.', example_en_4 = 'The timeline fits on one slide.', example_ko_4 = '타임라인이 슬라이드 하나에 맞습니다.', example_en_5 = 'We are on track according to the timeline.', example_ko_5 = '타임라인에 따르면 우리는 순조롭게 진행 중입니다.' WHERE id = 'w_presentation_B1_33';
UPDATE words SET example_en_2 = 'This data gives us a new insight.', example_ko_2 = '이 데이터가 새로운 인사이트를 줍니다.', example_en_3 = 'The key insight surprised everyone in the room.', example_ko_3 = '핵심 인사이트가 방 안의 모든 사람을 놀라게 했습니다.', example_en_4 = 'Share your insight in a clear, brief statement.', example_ko_4 = '인사이트를 명확하고 간결한 문장으로 공유하세요.', example_en_5 = 'Customer interviews gave us our best insight.', example_ko_5 = '고객 인터뷰가 우리에게 최고의 인사이트를 주었습니다.' WHERE id = 'w_presentation_B1_34';
UPDATE words SET example_en_2 = 'The initiative covers three business units.', example_ko_2 = '이니셔티브는 세 개의 사업 부서를 포함합니다.', example_en_3 = 'The initiative is backed by senior leadership.', example_ko_3 = '이니셔티브는 시니어 리더십의 지원을 받습니다.', example_en_4 = 'Present the initiative with a clear goal.', example_ko_4 = '명확한 목표와 함께 이니셔티브를 발표하세요.', example_en_5 = 'This initiative could transform our workflow.', example_ko_5 = '이 이니셔티브가 우리의 워크플로우를 변화시킬 수 있습니다.' WHERE id = 'w_presentation_B1_35';

-- ══════════════════════════════════════════════════════════════════
-- B2 (35단어)
-- ══════════════════════════════════════════════════════════════════
UPDATE words SET example_en_2 = 'We need to quantify the time savings too.', example_ko_2 = '시간 절감도 수치화해야 합니다.', example_en_3 = 'How do you quantify customer satisfaction?', example_ko_3 = '고객 만족도를 어떻게 수치화하나요?', example_en_4 = 'Quantify the impact before making a decision.', example_ko_4 = '결정을 내리기 전에 영향을 수치화하세요.', example_en_5 = 'It is hard to quantify brand value exactly.', example_ko_5 = '브랜드 가치를 정확하게 수치화하기는 어렵습니다.' WHERE id = 'w_presentation_B2_01';
UPDATE words SET example_en_2 = 'I will juxtapose last year and this year.', example_ko_2 = '작년과 올해를 나란히 비교하겠습니다.', example_en_3 = 'Juxtaposing the two graphs reveals the gap.', example_ko_3 = '두 그래프를 나란히 놓으면 격차가 드러납니다.', example_en_4 = 'She juxtaposed old and new methods clearly.', example_ko_4 = '그녀는 구 방법과 신 방법을 명확하게 병치했어요.', example_en_5 = 'Juxtapose the results to make your argument.', example_ko_5 = '논거를 강화하기 위해 결과를 나란히 놓으세요.' WHERE id = 'w_presentation_B2_02';
UPDATE words SET example_en_2 = 'Let me contextualize this data first.', example_ko_2 = '먼저 이 데이터를 맥락화하겠습니다.', example_en_3 = 'It helps to contextualize findings with examples.', example_ko_3 = '예시로 발견을 맥락화하면 도움이 됩니다.', example_en_4 = 'She contextualized the data for the audience.', example_ko_4 = '그녀는 청중을 위해 데이터를 맥락화했어요.', example_en_5 = 'Contextualize before presenting the numbers.', example_ko_5 = '수치를 제시하기 전에 맥락화하세요.' WHERE id = 'w_presentation_B2_03';
UPDATE words SET example_en_2 = 'He can articulate the strategy very well.', example_ko_2 = '그는 전략을 매우 잘 표현할 수 있어요.', example_en_3 = 'Articulate your main message in one sentence.', example_ko_3 = '주요 메시지를 한 문장으로 명확히 표현하세요.', example_en_4 = 'She articulated the problem clearly and calmly.', example_ko_4 = '그녀는 문제를 명확하고 침착하게 표현했어요.', example_en_5 = 'Articulate your conclusion at the very end.', example_ko_5 = '맨 마지막에 결론을 명확히 표현하세요.' WHERE id = 'w_presentation_B2_04';
UPDATE words SET example_en_2 = 'Good visuals facilitate audience understanding.', example_ko_2 = '좋은 시각 자료가 청중의 이해를 촉진합니다.', example_en_3 = 'This tool will facilitate the Q&A session.', example_ko_3 = '이 도구가 질의응답 세션을 촉진할 것입니다.', example_en_4 = 'She facilitated the discussion very smoothly.', example_ko_4 = '그녀는 토론을 매우 원활하게 진행했어요.', example_en_5 = 'Facilitate knowledge sharing across teams.', example_ko_5 = '팀 간 지식 공유를 촉진하세요.' WHERE id = 'w_presentation_B2_05';
UPDATE words SET example_en_2 = 'This is a compelling reason to change.', example_ko_2 = '이것은 변화를 위한 설득력 있는 이유입니다.', example_en_3 = 'Your data makes a compelling case.', example_ko_3 = '귀하의 데이터가 설득력 있는 근거를 만듭니다.', example_en_4 = 'She delivered a compelling and clear presentation.', example_ko_4 = '그녀는 설득력 있고 명확한 발표를 했어요.', example_en_5 = 'Use a compelling story to open your talk.', example_ko_5 = '설득력 있는 이야기로 발표를 시작하세요.' WHERE id = 'w_presentation_B2_06';
UPDATE words SET example_en_2 = 'The speaker was persuasive and well prepared.', example_ko_2 = '발표자는 설득력 있고 잘 준비되어 있었어요.', example_en_3 = 'Use evidence to make your argument persuasive.', example_ko_3 = '논거를 설득력 있게 만들기 위해 증거를 사용하세요.', example_en_4 = 'A persuasive introduction sets the tone.', example_ko_4 = '설득력 있는 도입부가 분위기를 설정합니다.', example_en_5 = 'She was persuasive without being aggressive.', example_ko_5 = '그녀는 공격적이지 않으면서도 설득력이 있었어요.' WHERE id = 'w_presentation_B2_07';
UPDATE words SET example_en_2 = 'The argument needs to be more coherent.', example_ko_2 = '주장이 더 일관되어야 합니다.', example_en_3 = 'A coherent narrative helps the audience follow.', example_ko_3 = '일관된 내러티브가 청중이 따라오는 데 도움이 됩니다.', example_en_4 = 'Make sure your slides tell a coherent story.', example_ko_4 = '슬라이드가 일관된 이야기를 전달하는지 확인하세요.', example_en_5 = 'Her presentation was coherent from start to finish.', example_ko_5 = '그녀의 발표는 처음부터 끝까지 일관되었어요.' WHERE id = 'w_presentation_B2_08';
UPDATE words SET example_en_2 = 'Strong data builds your credibility fast.', example_ko_2 = '강력한 데이터가 빠르게 신뢰성을 구축합니다.', example_en_3 = 'Always cite your sources to gain credibility.', example_ko_3 = '신뢰성을 얻으려면 항상 출처를 인용하세요.', example_en_4 = 'Her credibility as an expert was clear.', example_ko_4 = '전문가로서의 그녀의 신뢰성이 분명했습니다.', example_en_5 = 'Credibility is earned through preparation.', example_ko_5 = '신뢰성은 준비를 통해 얻어집니다.' WHERE id = 'w_presentation_B2_09';
UPDATE words SET example_en_2 = 'Build a narrative around the user journey.', example_ko_2 = '사용자 여정을 중심으로 내러티브를 구성하세요.', example_en_3 = 'The narrative connects all the data points.', example_ko_3 = '내러티브가 모든 데이터 포인트를 연결합니다.', example_en_4 = 'A clear narrative keeps the audience engaged.', example_ko_4 = '명확한 내러티브가 청중의 참여를 유지합니다.', example_en_5 = 'Her narrative made the numbers come alive.', example_ko_5 = '그녀의 내러티브가 숫자를 생생하게 만들었어요.' WHERE id = 'w_presentation_B2_10';
UPDATE words SET example_en_2 = 'Our data refutes that common assumption.', example_ko_2 = '우리 데이터가 그 일반적인 가정을 반박합니다.', example_en_3 = 'He refuted the claim with strong evidence.', example_ko_3 = '그는 강력한 증거로 주장을 반박했어요.', example_en_4 = 'Be ready to refute objections from the audience.', example_ko_4 = '청중의 반론을 반박할 준비를 하세요.', example_en_5 = 'The graph refutes the competitor''s argument.', example_ko_5 = '그래프가 경쟁사의 주장을 반박합니다.' WHERE id = 'w_presentation_B2_11';
UPDATE words SET example_en_2 = 'We can substantiate this with three data points.', example_ko_2 = '세 가지 데이터 포인트로 이것을 뒷받침할 수 있습니다.', example_en_3 = 'Substantiate each claim before presenting.', example_ko_3 = '발표 전에 각 주장을 뒷받침하세요.', example_en_4 = 'She substantiated her argument with research.', example_ko_4 = '그녀는 연구로 자신의 주장을 뒷받침했어요.', example_en_5 = 'Can you substantiate that figure?', example_ko_5 = '그 수치를 뒷받침할 수 있나요?' WHERE id = 'w_presentation_B2_12';
UPDATE words SET example_en_2 = 'There is an important nuance in the data.', example_ko_2 = '데이터에 중요한 뉘앙스가 있습니다.', example_en_3 = 'The nuance was missed by the first analysis.', example_ko_3 = '뉘앙스가 첫 번째 분석에서 놓쳤습니다.', example_en_4 = 'Acknowledge the nuance — it matters here.', example_ko_4 = '뉘앙스를 인정하세요 — 여기서 중요합니다.', example_en_5 = 'Language nuance can change the whole meaning.', example_ko_5 = '언어 뉘앙스가 전체 의미를 바꿀 수 있습니다.' WHERE id = 'w_presentation_B2_13';
UPDATE words SET example_en_2 = 'We outperformed the industry benchmark by 12%.', example_ko_2 = '우리는 업계 기준을 12% 초과했습니다.', example_en_3 = 'Set a clear benchmark at the start.', example_ko_3 = '시작 시 명확한 기준점을 설정하세요.', example_en_4 = 'The benchmark helps us track real progress.', example_ko_4 = '기준점이 실제 진전을 추적하는 데 도움이 됩니다.', example_en_5 = 'Compare results against the benchmark each month.', example_ko_5 = '매달 기준점과 결과를 비교하세요.' WHERE id = 'w_presentation_B2_14';
UPDATE words SET example_en_2 = 'Leverage your data to tell a stronger story.', example_ko_2 = '데이터를 활용해 더 강력한 이야기를 전하세요.', example_en_3 = 'We leverage user research in every decision.', example_ko_3 = '우리는 모든 결정에서 사용자 연구를 활용합니다.', example_en_4 = 'Leverage existing tools before building new ones.', example_ko_4 = '새 도구를 만들기 전에 기존 도구를 활용하세요.', example_en_5 = 'She leveraged the Q&A to reinforce her point.', example_ko_5 = '그녀는 질의응답을 활용해 요점을 강화했어요.' WHERE id = 'w_presentation_B2_15';
UPDATE words SET example_en_2 = 'We took steps to mitigate the risk early.', example_ko_2 = '우리는 위험을 일찍 완화하기 위한 조치를 취했습니다.', example_en_3 = 'How do you plan to mitigate this concern?', example_ko_3 = '이 우려를 어떻게 완화할 계획인가요?', example_en_4 = 'Mitigate the impact by acting now.', example_ko_4 = '지금 행동해 영향을 완화하세요.', example_en_5 = 'The new process will mitigate delays.', example_ko_5 = '새 과정이 지연을 완화할 것입니다.' WHERE id = 'w_presentation_B2_16';
UPDATE words SET example_en_2 = 'All key stakeholders have been briefed.', example_ko_2 = '모든 주요 이해관계자에게 브리핑이 완료되었습니다.', example_en_3 = 'Identify stakeholders before the presentation.', example_ko_3 = '발표 전에 이해관계자를 파악하세요.', example_en_4 = 'Stakeholder feedback shaped our final plan.', example_ko_4 = '이해관계자 피드백이 최종 계획을 형성했습니다.', example_en_5 = 'Present results to stakeholders every quarter.', example_ko_5 = '분기마다 이해관계자에게 결과를 발표하세요.' WHERE id = 'w_presentation_B2_17';
UPDATE words SET example_en_2 = 'The platform is designed to be scalable.', example_ko_2 = '플랫폼은 확장 가능하도록 설계되었습니다.', example_en_3 = 'Is the process scalable across all regions?', example_ko_3 = '과정이 모든 지역에서 확장 가능한가요?', example_en_4 = 'A scalable solution saves money long-term.', example_ko_4 = '확장 가능한 솔루션이 장기적으로 비용을 절감합니다.', example_en_5 = 'She proved the model is scalable with data.', example_ko_5 = '그녀는 데이터로 모델이 확장 가능함을 증명했어요.' WHERE id = 'w_presentation_B2_18';
UPDATE words SET example_en_2 = 'Let us prioritize the items with most impact.', example_ko_2 = '영향력이 가장 큰 항목을 우선시해 봅시다.', example_en_3 = 'Prioritize your slides by importance.', example_ko_3 = '중요도별로 슬라이드 우선순위를 정하세요.', example_en_4 = 'She prioritized customer feedback above all.', example_ko_4 = '그녀는 모든 것 위에 고객 피드백을 우선시했어요.', example_en_5 = 'Prioritize the most urgent recommendation first.', example_ko_5 = '가장 긴급한 권장 사항을 먼저 우선시하세요.' WHERE id = 'w_presentation_B2_19';
UPDATE words SET example_en_2 = 'The team will optimize the process next month.', example_ko_2 = '팀이 다음 달에 과정을 최적화할 것입니다.', example_en_3 = 'How can we optimize the current workflow?', example_ko_3 = '현재 워크플로우를 어떻게 최적화할 수 있나요?', example_en_4 = 'Optimize your slides for a fifteen-minute talk.', example_ko_4 = '15분 발표에 맞게 슬라이드를 최적화하세요.', example_en_5 = 'We optimized the system and cut costs by 30%.', example_ko_5 = '시스템을 최적화해 비용을 30% 절감했습니다.' WHERE id = 'w_presentation_B2_20';
UPDATE words SET example_en_2 = 'The growth trajectory looks very promising.', example_ko_2 = '성장 궤적이 매우 유망하게 보입니다.', example_en_3 = 'The trajectory shifted after the product launch.', example_ko_3 = '제품 출시 후 궤적이 바뀌었습니다.', example_en_4 = 'Plot the trajectory on a simple line graph.', example_ko_4 = '간단한 꺾은선 그래프에 궤적을 표시하세요.', example_en_5 = 'We want to maintain this positive trajectory.', example_ko_5 = '이 긍정적인 궤적을 유지하고 싶습니다.' WHERE id = 'w_presentation_B2_21';
UPDATE words SET example_en_2 = 'The new regulation was a catalyst for change.', example_ko_2 = '새 규정이 변화의 촉매제가 되었습니다.', example_en_3 = 'Identify the catalyst behind the growth spike.', example_ko_3 = '성장 급등 뒤의 촉매제를 파악하세요.', example_en_4 = 'The merger acted as a catalyst for innovation.', example_ko_4 = '합병이 혁신의 촉매제 역할을 했습니다.', example_en_5 = 'Data can be the catalyst for a better decision.', example_ko_5 = '데이터가 더 나은 결정의 촉매제가 될 수 있습니다.' WHERE id = 'w_presentation_B2_22';
UPDATE words SET example_en_2 = 'The most viable option is shown on slide six.', example_ko_2 = '가장 실행 가능한 옵션이 6번 슬라이드에 있습니다.', example_en_3 = 'Is this approach commercially viable?', example_ko_3 = '이 접근법이 상업적으로 실행 가능한가요?', example_en_4 = 'She proved the idea was financially viable.', example_ko_4 = '그녀는 아이디어가 재정적으로 실행 가능함을 증명했어요.', example_en_5 = 'Only present viable options to the audience.', example_ko_5 = '청중에게는 실행 가능한 옵션만 제시하세요.' WHERE id = 'w_presentation_B2_23';
UPDATE words SET example_en_2 = 'The granular breakdown is in the appendix.', example_ko_2 = '세밀한 분석은 부록에 있습니다.', example_en_3 = 'We need a more granular view of the data.', example_ko_3 = '데이터의 더 세밀한 관점이 필요합니다.', example_en_4 = 'Granular data can reveal hidden patterns.', example_ko_4 = '세밀한 데이터가 숨겨진 패턴을 드러낼 수 있습니다.', example_en_5 = 'Avoid granular details on the main slides.', example_ko_5 = '메인 슬라이드에서는 세밀한 세부 사항을 피하세요.' WHERE id = 'w_presentation_B2_24';
UPDATE words SET example_en_2 = 'The report synthesizes three major studies.', example_ko_2 = '보고서는 세 가지 주요 연구를 종합합니다.', example_en_3 = 'Synthesize the findings into one clear message.', example_ko_3 = '발견을 하나의 명확한 메시지로 종합하세요.', example_en_4 = 'She synthesized complex data beautifully.', example_ko_4 = '그녀는 복잡한 데이터를 아름답게 종합했어요.', example_en_5 = 'Synthesize before you conclude.', example_ko_5 = '결론 내리기 전에 종합하세요.' WHERE id = 'w_presentation_B2_25';
UPDATE words SET example_en_2 = 'We value transparency in all our reporting.', example_ko_2 = '우리는 모든 보고에서 투명성을 소중히 여깁니다.', example_en_3 = 'Transparency builds trust with your audience.', example_ko_3 = '투명성이 청중과의 신뢰를 구축합니다.', example_en_4 = 'Show transparency by sharing your limitations.', example_ko_4 = '한계를 공유함으로써 투명성을 보여주세요.', example_en_5 = 'Transparency in data is always appreciated.', example_ko_5 = '데이터의 투명성은 항상 감사히 여겨집니다.' WHERE id = 'w_presentation_B2_26';
UPDATE words SET example_en_2 = 'We validated the model with actual users.', example_ko_2 = '실제 사용자로 모델을 검증했습니다.', example_en_3 = 'Validate your assumptions before presenting.', example_ko_3 = '발표 전에 가정을 검증하세요.', example_en_4 = 'The test results validated our hypothesis.', example_ko_4 = '테스트 결과가 우리의 가설을 검증했습니다.', example_en_5 = 'Can you validate this number independently?', example_ko_5 = '이 숫자를 독립적으로 검증할 수 있나요?' WHERE id = 'w_presentation_B2_27';
UPDATE words SET example_en_2 = 'The methodology is robust and well-tested.', example_ko_2 = '방법론은 견고하고 잘 테스트되어 있습니다.', example_en_3 = 'We built a robust framework for analysis.', example_ko_3 = '분석을 위한 견고한 프레임워크를 구축했습니다.', example_en_4 = 'Robust evidence makes your case stronger.', example_ko_4 = '견고한 증거가 논거를 더 강력하게 만듭니다.', example_en_5 = 'The robust design survived multiple reviews.', example_ko_5 = '견고한 설계가 여러 차례의 검토를 통과했습니다.' WHERE id = 'w_presentation_B2_28';
UPDATE words SET example_en_2 = 'We take a holistic view of user experience.', example_ko_2 = '우리는 사용자 경험을 전체론적 관점으로 봅니다.', example_en_3 = 'A holistic approach considers all stakeholders.', example_ko_3 = '전체론적 접근법은 모든 이해관계자를 고려합니다.', example_en_4 = 'Think holistically before proposing a solution.', example_ko_4 = '해결책을 제안하기 전에 전체적으로 생각하세요.', example_en_5 = 'The holistic model covers cost, time, and risk.', example_ko_5 = '전체론적 모델은 비용, 시간, 위험을 다룹니다.' WHERE id = 'w_presentation_B2_29';
UPDATE words SET example_en_2 = 'The team is building momentum toward the goal.', example_ko_2 = '팀이 목표를 향한 기세를 쌓아가고 있습니다.', example_en_3 = 'We must not lose the momentum we have built.', example_ko_3 = '우리가 쌓아온 기세를 잃어서는 안 됩니다.', example_en_4 = 'A strong opening creates positive momentum.', example_ko_4 = '강력한 도입부가 긍정적인 기세를 만듭니다.', example_en_5 = 'Celebrate small wins to keep momentum going.', example_ko_5 = '기세를 유지하기 위해 작은 성과를 축하하세요.' WHERE id = 'w_presentation_B2_30';
UPDATE words SET example_en_2 = 'The discrepancy is explained on slide nine.', example_ko_2 = '불일치는 9번 슬라이드에 설명되어 있습니다.', example_en_3 = 'Address the discrepancy before questions arise.', example_ko_3 = '질문이 나오기 전에 불일치를 해결하세요.', example_en_4 = 'There is a discrepancy between the two reports.', example_ko_4 = '두 보고서 사이에 불일치가 있습니다.', example_en_5 = 'Explain the discrepancy clearly and honestly.', example_ko_5 = '불일치를 명확하고 솔직하게 설명하세요.' WHERE id = 'w_presentation_B2_31';
UPDATE words SET example_en_2 = 'These are actionable steps you can take today.', example_ko_2 = '오늘 바로 실행할 수 있는 단계들입니다.', example_en_3 = 'End with actionable recommendations always.', example_ko_3 = '항상 바로 실행 가능한 권장 사항으로 마무리하세요.', example_en_4 = 'Keep your suggestions actionable and specific.', example_ko_4 = '제안을 실행 가능하고 구체적으로 유지하세요.', example_en_5 = 'Actionable insights drive real business change.', example_ko_5 = '실행 가능한 인사이트가 실제 비즈니스 변화를 이끕니다.' WHERE id = 'w_presentation_B2_32';
UPDATE words SET example_en_2 = 'Each iteration improved the design noticeably.', example_ko_2 = '각 이터레이션이 디자인을 눈에 띄게 개선했습니다.', example_en_3 = 'How many iterations did the project go through?', example_ko_3 = '프로젝트가 몇 번의 이터레이션을 거쳤나요?', example_en_4 = 'Show the progress across each iteration.', example_ko_4 = '각 이터레이션에 걸친 진전을 보여주세요.', example_en_5 = 'Iteration leads to a better final product.', example_ko_5 = '이터레이션이 더 나은 최종 제품으로 이어집니다.' WHERE id = 'w_presentation_B2_33';
UPDATE words SET example_en_2 = 'We need strategic alignment across all teams.', example_ko_2 = '모든 팀 전반의 전략적 정렬이 필요합니다.', example_en_3 = 'Check alignment before the final presentation.', example_ko_3 = '최종 발표 전에 정렬을 확인하세요.', example_en_4 = 'Alignment between teams leads to better results.', example_ko_4 = '팀 간 정렬이 더 나은 결과로 이어집니다.', example_en_5 = 'The alignment is clear from the shared goals.', example_ko_5 = '정렬은 공유된 목표에서 명확하게 드러납니다.' WHERE id = 'w_presentation_B2_34';
UPDATE words SET example_en_2 = 'The projection is based on current market data.', example_ko_2 = '전망은 현재 시장 데이터를 기반으로 합니다.', example_en_3 = 'Our projection for Q3 is very optimistic.', example_ko_3 = '3분기 전망은 매우 낙관적입니다.', example_en_4 = 'Show the projection alongside actual results.', example_ko_4 = '실제 결과와 함께 전망을 보여주세요.', example_en_5 = 'The projection assumes 10% market growth.', example_ko_5 = '전망은 10% 시장 성장을 가정합니다.' WHERE id = 'w_presentation_B2_35';

-- ══════════════════════════════════════════════════════════════════
-- C1 (35단어)
-- ══════════════════════════════════════════════════════════════════
UPDATE words SET example_en_2 = 'Her use of rhetoric was very effective.', example_ko_2 = '그녀의 수사법 활용이 매우 효과적이었어요.', example_en_3 = 'Political rhetoric often obscures the facts.', example_ko_3 = '정치적 수사법은 종종 사실을 모호하게 합니다.', example_en_4 = 'Study rhetoric to improve your public speaking.', example_ko_4 = '대중 연설을 향상시키기 위해 수사학을 공부하세요.', example_en_5 = 'The rhetoric was powerful and moved the audience.', example_ko_5 = '수사법이 강력해 청중을 감동시켰습니다.' WHERE id = 'w_presentation_C1_01';
UPDATE words SET example_en_2 = 'The discourse around AI is changing rapidly.', example_ko_2 = 'AI에 관한 담론이 빠르게 변화하고 있습니다.', example_en_3 = 'Academic discourse requires precise language.', example_ko_3 = '학문적 담론은 정확한 언어를 요구합니다.', example_en_4 = 'Public discourse shapes policy decisions.', example_ko_4 = '공공 담론이 정책 결정을 형성합니다.', example_en_5 = 'Contribute to the discourse with new evidence.', example_ko_5 = '새로운 증거로 담론에 기여하세요.' WHERE id = 'w_presentation_C1_02';
UPDATE words SET example_en_2 = 'She deconstructed the argument step by step.', example_ko_2 = '그녀는 논거를 단계별로 분해했어요.', example_en_3 = 'Deconstruct the problem before solving it.', example_ko_3 = '문제를 해결하기 전에 분해해서 분석하세요.', example_en_4 = 'He deconstructed the myth with clear evidence.', example_ko_4 = '그는 명확한 증거로 신화를 분해했어요.', example_en_5 = 'Deconstruct complex ideas to make them clear.', example_ko_5 = '복잡한 아이디어를 명확하게 만들기 위해 분해하세요.' WHERE id = 'w_presentation_C1_03';
UPDATE words SET example_en_2 = 'This technology represents a new paradigm.', example_ko_2 = '이 기술은 새로운 패러다임을 나타냅니다.', example_en_3 = 'A paradigm shift is happening in our industry.', example_ko_3 = '우리 업계에서 패러다임 전환이 일어나고 있습니다.', example_en_4 = 'Question the dominant paradigm in your field.', example_ko_4 = '자신의 분야에서 지배적인 패러다임에 의문을 제기하세요.', example_en_5 = 'AI is the new paradigm for data analysis.', example_ko_5 = 'AI는 데이터 분석의 새로운 패러다임입니다.' WHERE id = 'w_presentation_C1_04';
UPDATE words SET example_en_2 = 'Our framework guides every design decision.', example_ko_2 = '우리의 프레임워크가 모든 설계 결정을 안내합니다.', example_en_3 = 'Use a clear framework to organize your talk.', example_ko_3 = '발표를 구성하기 위해 명확한 프레임워크를 사용하세요.', example_en_4 = 'The framework has four interconnected parts.', example_ko_4 = '프레임워크는 네 개의 상호 연결된 부분으로 이루어져 있습니다.', example_en_5 = 'She presented the framework with great clarity.', example_ko_5 = '그녀는 프레임워크를 매우 명확하게 발표했어요.' WHERE id = 'w_presentation_C1_05';
UPDATE words SET example_en_2 = 'Our value proposition is clear and compelling.', example_ko_2 = '우리의 가치 명제는 명확하고 설득력 있습니다.', example_en_3 = 'State your core proposition in the first slide.', example_ko_3 = '첫 번째 슬라이드에 핵심 명제를 진술하세요.', example_en_4 = 'The proposition was accepted by the committee.', example_ko_4 = '명제가 위원회에서 받아들여졌습니다.', example_en_5 = 'Test your proposition against real data.', example_ko_5 = '실제 데이터로 명제를 검증하세요.' WHERE id = 'w_presentation_C1_06';
UPDATE words SET example_en_2 = 'Our conclusions rest on empirical evidence.', example_ko_2 = '우리의 결론은 실증적 증거에 기반합니다.', example_en_3 = 'Empirical data is more reliable than opinion.', example_ko_3 = '실증적 데이터는 의견보다 신뢰할 수 있습니다.', example_en_4 = 'The empirical findings are presented clearly.', example_ko_4 = '실증적 발견이 명확하게 제시되었습니다.', example_en_5 = 'Always ground your argument in empirical facts.', example_ko_5 = '항상 논거를 실증적 사실에 근거하세요.' WHERE id = 'w_presentation_C1_07';
UPDATE words SET example_en_2 = 'An analytical mind is essential for research.', example_ko_2 = '분석적인 사고방식이 연구에 필수적입니다.', example_en_3 = 'Take an analytical look at the user data.', example_ko_3 = '사용자 데이터를 분석적으로 살펴보세요.', example_en_4 = 'Her analytical framework impressed the panel.', example_ko_4 = '그녀의 분석적 프레임워크가 패널에 깊은 인상을 줬어요.', example_en_5 = 'Strong analytical skills make better presentations.', example_ko_5 = '강력한 분석 능력이 더 나은 발표를 만듭니다.' WHERE id = 'w_presentation_C1_08';
UPDATE words SET example_en_2 = 'We synthesize findings from five studies.', example_ko_2 = '다섯 개의 연구에서 발견을 종합합니다.', example_en_3 = 'Synthesize the information into a clear message.', example_ko_3 = '정보를 명확한 메시지로 종합하세요.', example_en_4 = 'She synthesized ideas from multiple disciplines.', example_ko_4 = '그녀는 여러 분야의 아이디어를 종합했어요.', example_en_5 = 'Synthesize your research before writing the talk.', example_ko_5 = '발표를 작성하기 전에 연구를 종합하세요.' WHERE id = 'w_presentation_C1_09';
UPDATE words SET example_en_2 = 'What can we infer from this pattern?', example_ko_2 = '이 패턴에서 무엇을 추론할 수 있나요?', example_en_3 = 'Do not infer too much from a single data point.', example_ko_3 = '단일 데이터 포인트에서 너무 많이 추론하지 마세요.', example_en_4 = 'We can infer user intent from the behavior data.', example_ko_4 = '행동 데이터에서 사용자 의도를 추론할 수 있습니다.', example_en_5 = 'She inferred the cause from the observed effect.', example_ko_5 = '그녀는 관찰된 결과에서 원인을 추론했어요.' WHERE id = 'w_presentation_C1_10';
UPDATE words SET example_en_2 = 'Engagement correlates strongly with retention.', example_ko_2 = '참여도가 유지율과 강하게 상관관계가 있습니다.', example_en_3 = 'These two variables correlate in the data.', example_ko_3 = '이 두 변수는 데이터에서 상관관계가 있습니다.', example_en_4 = 'Satisfaction scores correlate with repeat visits.', example_ko_4 = '만족도 점수가 재방문과 상관관계가 있습니다.', example_en_5 = 'Show how the variables correlate on the graph.', example_ko_5 = '그래프에서 변수들이 어떻게 상관관계가 있는지 보여주세요.' WHERE id = 'w_presentation_C1_11';
UPDATE words SET example_en_2 = 'I will critique each approach fairly.', example_ko_2 = '각 접근법을 공정하게 비평하겠습니다.', example_en_3 = 'Critique the existing model before proposing a new one.', example_ko_3 = '새 모델을 제안하기 전에 기존 모델을 비평하세요.', example_en_4 = 'Her critique was sharp but constructive.', example_ko_4 = '그녀의 비평은 날카롭지만 건설적이었어요.', example_en_5 = 'A good presenter can critique their own work.', example_ko_5 = '좋은 발표자는 자신의 작업을 비평할 수 있습니다.' WHERE id = 'w_presentation_C1_12';
UPDATE words SET example_en_2 = 'We conceptualized the product as a journey.', example_ko_2 = '우리는 제품을 여정으로 개념화했습니다.', example_en_3 = 'Conceptualize the problem before designing a solution.', example_ko_3 = '솔루션을 설계하기 전에 문제를 개념화하세요.', example_en_4 = 'She conceptualized the data as a living system.', example_ko_4 = '그녀는 데이터를 살아있는 시스템으로 개념화했어요.', example_en_5 = 'Conceptualize the user need before building.', example_ko_5 = '만들기 전에 사용자 필요를 개념화하세요.' WHERE id = 'w_presentation_C1_13';
UPDATE words SET example_en_2 = 'The two models produced divergent outcomes.', example_ko_2 = '두 모델이 다른 결과를 만들어냈습니다.', example_en_3 = 'Divergent views can lead to better decisions.', example_ko_3 = '다른 견해가 더 나은 결정으로 이어질 수 있습니다.', example_en_4 = 'The data showed divergent trends by region.', example_ko_4 = '데이터가 지역별로 다른 추세를 보였습니다.', example_en_5 = 'Use divergent thinking to generate more ideas.', example_ko_5 = '더 많은 아이디어를 생성하기 위해 발산적 사고를 사용하세요.' WHERE id = 'w_presentation_C1_14';
UPDATE words SET example_en_2 = 'All the evidence shows convergent results.', example_ko_2 = '모든 증거가 수렴하는 결과를 보여줍니다.', example_en_3 = 'The convergent data strengthens the argument.', example_ko_3 = '수렴하는 데이터가 논거를 강화합니다.', example_en_4 = 'Look for convergent patterns across data sets.', example_ko_4 = '데이터 세트 전반에서 수렴하는 패턴을 찾으세요.', example_en_5 = 'Convergent findings give us high confidence.', example_ko_5 = '수렴하는 발견이 우리에게 높은 확신을 줍니다.' WHERE id = 'w_presentation_C1_15';
UPDATE words SET example_en_2 = 'Her nuanced reading of the data was impressive.', example_ko_2 = '데이터에 대한 그녀의 세밀한 해석이 인상적이었어요.', example_en_3 = 'Take a nuanced view instead of a simple one.', example_ko_3 = '단순한 관점 대신 세밀한 관점을 취하세요.', example_en_4 = 'The nuanced argument held up under questioning.', example_ko_4 = '세밀한 논거가 질문에도 굳건히 유지되었습니다.', example_en_5 = 'A nuanced presentation earns more respect.', example_ko_5 = '세밀한 발표가 더 많은 존경을 받습니다.' WHERE id = 'w_presentation_C1_16';
UPDATE words SET example_en_2 = 'The normative framework guides our analysis.', example_ko_2 = '규범적 프레임워크가 우리의 분석을 안내합니다.', example_en_3 = 'We move from descriptive to normative claims.', example_ko_3 = '기술적 주장에서 규범적 주장으로 이동합니다.', example_en_4 = 'Normative recommendations follow the findings.', example_ko_4 = '규범적 권장 사항이 발견에 뒤따릅니다.', example_en_5 = 'The normative case for change is compelling.', example_ko_5 = '변화를 위한 규범적 논거가 설득력 있습니다.' WHERE id = 'w_presentation_C1_17';
UPDATE words SET example_en_2 = 'We can extrapolate to the next five years.', example_ko_2 = '향후 5년으로 추정 연장할 수 있습니다.', example_en_3 = 'Be careful when you extrapolate from small samples.', example_ko_3 = '작은 표본에서 추정 연장할 때는 주의하세요.', example_en_4 = 'She extrapolated the trend convincingly.', example_ko_4 = '그녀는 추세를 설득력 있게 추정 연장했어요.', example_en_5 = 'Extrapolate only when the data trend is stable.', example_ko_5 = '데이터 추세가 안정적일 때만 추정 연장하세요.' WHERE id = 'w_presentation_C1_18';
UPDATE words SET example_en_2 = 'Our hypothesis was supported by the findings.', example_ko_2 = '가설이 발견으로 뒷받침되었습니다.', example_en_3 = 'State your hypothesis clearly at the start.', example_ko_3 = '시작 시 가설을 명확하게 진술하세요.', example_en_4 = 'The hypothesis was rejected based on the data.', example_ko_4 = '가설이 데이터를 기반으로 기각되었습니다.', example_en_5 = 'A strong hypothesis shapes the whole study.', example_ko_5 = '강력한 가설이 전체 연구를 형성합니다.' WHERE id = 'w_presentation_C1_19';
UPDATE words SET example_en_2 = 'We prepared a contingency for every major risk.', example_ko_2 = '모든 주요 위험에 대한 비상 계획을 준비했습니다.', example_en_3 = 'A contingency plan shows careful preparation.', example_ko_3 = '비상 계획은 신중한 준비를 보여줍니다.', example_en_4 = 'Include a contingency budget in the proposal.', example_ko_4 = '제안서에 예비 예산을 포함하세요.', example_en_5 = 'The contingency was activated during the crisis.', example_ko_5 = '비상 계획이 위기 동안 발동되었습니다.' WHERE id = 'w_presentation_C1_20';
UPDATE words SET example_en_2 = 'Let me delineate the scope of this research.', example_ko_2 = '이 연구의 범위를 명확히 구분해 드리겠습니다.', example_en_3 = 'Delineate roles and responsibilities clearly.', example_ko_3 = '역할과 책임을 명확하게 구분하세요.', example_en_4 = 'She delineated the timeline in detail.', example_ko_4 = '그녀는 타임라인을 자세히 명확히 구분했어요.', example_en_5 = 'Delineate the problem space before solving.', example_ko_5 = '해결하기 전에 문제 영역을 명확히 구분하세요.' WHERE id = 'w_presentation_C1_21';
UPDATE words SET example_en_2 = 'Causality is different from correlation.', example_ko_2 = '인과관계는 상관관계와 다릅니다.', example_en_3 = 'Establish causality with a controlled experiment.', example_ko_3 = '통제된 실험으로 인과관계를 확립하세요.', example_en_4 = 'The causality is not yet proven by this data.', example_ko_4 = '이 데이터로는 인과관계가 아직 증명되지 않았습니다.', example_en_5 = 'She explained the causality clearly and simply.', example_ko_5 = '그녀는 인과관계를 명확하고 간단하게 설명했어요.' WHERE id = 'w_presentation_C1_22';
UPDATE words SET example_en_2 = 'We will disseminate the report next week.', example_ko_2 = '다음 주에 보고서를 전파하겠습니다.', example_en_3 = 'How do you plan to disseminate these findings?', example_ko_3 = '이 발견들을 어떻게 전파할 계획인가요?', example_en_4 = 'Disseminate results to all relevant teams.', example_ko_4 = '모든 관련 팀에 결과를 전파하세요.', example_en_5 = 'The conference will help disseminate our research.', example_ko_5 = '컨퍼런스가 우리의 연구를 전파하는 데 도움이 될 것입니다.' WHERE id = 'w_presentation_C1_23';
UPDATE words SET example_en_2 = 'Avoid the false dichotomy of speed vs. quality.', example_ko_2 = '속도 대 품질의 거짓 이분법을 피하세요.', example_en_3 = 'The dichotomy is more complex than it seems.', example_ko_3 = '이분법은 보이는 것보다 더 복잡합니다.', example_en_4 = 'She challenged the data/intuition dichotomy.', example_ko_4 = '그녀는 데이터/직관 이분법에 도전했어요.', example_en_5 = 'The dichotomy between theory and practice is false.', example_ko_5 = '이론과 실천 사이의 이분법은 잘못된 것입니다.' WHERE id = 'w_presentation_C1_24';
UPDATE words SET example_en_2 = 'Interrogate the data before drawing conclusions.', example_ko_2 = '결론을 내리기 전에 데이터를 면밀히 검토하세요.', example_en_3 = 'We need to interrogate these assumptions.', example_ko_3 = '이 가정들을 면밀히 검토해야 합니다.', example_en_4 = 'She interrogated the methodology thoroughly.', example_ko_4 = '그녀는 방법론을 철저하게 검토했어요.', example_en_5 = 'Interrogate every claim before presenting.', example_ko_5 = '발표 전에 모든 주장을 면밀히 검토하세요.' WHERE id = 'w_presentation_C1_25';
UPDATE words SET example_en_2 = 'We should not over-generalize from one study.', example_ko_2 = '하나의 연구에서 과도하게 일반화해서는 안 됩니다.', example_en_3 = 'Generalize carefully and acknowledge limits.', example_ko_3 = '신중하게 일반화하고 한계를 인정하세요.', example_en_4 = 'It is tempting but dangerous to over-generalize.', example_ko_4 = '과도한 일반화는 매력적이지만 위험합니다.', example_en_5 = 'She generalized the findings to all markets.', example_ko_5 = '그녀는 발견을 모든 시장으로 일반화했어요.' WHERE id = 'w_presentation_C1_26';
UPDATE words SET example_en_2 = 'This case sets a precedent for future projects.', example_ko_2 = '이 사례가 향후 프로젝트의 선례를 세웁니다.', example_en_3 = 'Is there a precedent for this kind of result?', example_ko_3 = '이런 종류의 결과에 대한 선례가 있나요?', example_en_4 = 'We looked at precedents from other companies.', example_ko_4 = '다른 회사의 선례를 살펴봤습니다.', example_en_5 = 'The precedent supports our proposed approach.', example_ko_5 = '선례가 우리가 제안한 접근법을 뒷받침합니다.' WHERE id = 'w_presentation_C1_27';
UPDATE words SET example_en_2 = 'The quantitative findings are shown in the chart.', example_ko_2 = '정량적 발견이 차트에 나와 있습니다.', example_en_3 = 'Quantitative data tells us the what, not the why.', example_ko_3 = '정량적 데이터는 이유가 아닌 무엇을 알려줍니다.', example_en_4 = 'Use quantitative metrics to track progress.', example_ko_4 = '진행 상황을 추적하기 위해 정량적 지표를 사용하세요.', example_en_5 = 'Combine quantitative and qualitative methods.', example_ko_5 = '정량적 방법과 정성적 방법을 결합하세요.' WHERE id = 'w_presentation_C1_28';
UPDATE words SET example_en_2 = 'The qualitative data reveals user motivations.', example_ko_2 = '정성적 데이터가 사용자 동기를 드러냅니다.', example_en_3 = 'Qualitative interviews gave us deep insight.', example_ko_3 = '정성적 인터뷰가 깊은 인사이트를 주었습니다.', example_en_4 = 'Use qualitative evidence to add human context.', example_ko_4 = '인간적 맥락을 추가하기 위해 정성적 증거를 사용하세요.', example_en_5 = 'She presented qualitative themes from ten interviews.', example_ko_5 = '그녀는 10번의 인터뷰에서 정성적 주제를 발표했어요.' WHERE id = 'w_presentation_C1_29';
UPDATE words SET example_en_2 = 'We used an iterative process to refine the design.', example_ko_2 = '반복적인 과정으로 디자인을 개선했습니다.', example_en_3 = 'An iterative approach leads to better outcomes.', example_ko_3 = '반복적인 접근법이 더 나은 결과로 이어집니다.', example_en_4 = 'The iterative cycle ran for three months.', example_ko_4 = '반복적인 사이클이 세 달간 진행되었습니다.', example_en_5 = 'Show the iterative improvement across versions.', example_ko_5 = '버전별 반복적인 개선을 보여주세요.' WHERE id = 'w_presentation_C1_30';
UPDATE words SET example_en_2 = 'I posit that the root cause is poor onboarding.', example_ko_2 = '근본 원인이 열악한 온보딩이라고 주장합니다.', example_en_3 = 'She posited a bold but testable claim.', example_ko_3 = '그녀는 대담하지만 검증 가능한 주장을 제기했어요.', example_en_4 = 'Posit your central claim early in the talk.', example_ko_4 = '발표 초반에 핵심 주장을 제기하세요.', example_en_5 = 'I posit that simplicity drives higher adoption.', example_ko_5 = '단순성이 더 높은 채택을 이끈다고 주장합니다.' WHERE id = 'w_presentation_C1_31';
UPDATE words SET example_en_2 = 'We need substantive action, not just words.', example_ko_2 = '말뿐만 아니라 실질적인 행동이 필요합니다.', example_en_3 = 'She made a substantive contribution to the debate.', example_ko_3 = '그녀는 토론에 실질적인 기여를 했어요.', example_en_4 = 'The report contains several substantive findings.', example_ko_4 = '보고서에는 여러 실질적인 발견이 포함됩니다.', example_en_5 = 'Make a substantive point in every section.', example_ko_5 = '모든 섹션에서 실질적인 요점을 제시하세요.' WHERE id = 'w_presentation_C1_32';
UPDATE words SET example_en_2 = 'The granularity of the dataset is impressive.', example_ko_2 = '데이터셋의 세분화 수준이 인상적입니다.', example_en_3 = 'Increase the granularity for a deeper analysis.', example_ko_3 = '더 깊은 분석을 위해 세분화 수준을 높이세요.', example_en_4 = 'The granularity allows us to spot anomalies.', example_ko_4 = '세분화 수준이 이상 징후를 발견할 수 있게 해줍니다.', example_en_5 = 'Match the granularity to your audience''s needs.', example_ko_5 = '세분화 수준을 청중의 필요에 맞추세요.' WHERE id = 'w_presentation_C1_33';
UPDATE words SET example_en_2 = 'The first axiom is that users want simplicity.', example_ko_2 = '첫 번째 공리는 사용자가 단순함을 원한다는 것입니다.', example_en_3 = 'State your axioms before building the argument.', example_ko_3 = '논거를 구축하기 전에 공리를 진술하세요.', example_en_4 = 'Challenge the axiom and see what changes.', example_ko_4 = '공리에 도전하고 무엇이 바뀌는지 보세요.', example_en_5 = 'The axiom is widely accepted in the field.', example_ko_5 = '그 공리는 해당 분야에서 널리 받아들여집니다.' WHERE id = 'w_presentation_C1_34';
UPDATE words SET example_en_2 = 'Reframe the issue as a growth opportunity.', example_ko_2 = '문제를 성장 기회로 재구성하세요.', example_en_3 = 'She reframed the failure as a valuable lesson.', example_ko_3 = '그녀는 실패를 귀중한 교훈으로 재구성했어요.', example_en_4 = 'Reframe the question to change the conversation.', example_ko_4 = '질문을 재구성해 대화를 바꾸세요.', example_en_5 = 'Reframing the problem led to a better solution.', example_ko_5 = '문제를 재구성함으로써 더 나은 해결책이 나왔습니다.' WHERE id = 'w_presentation_C1_35';

-- ══════════════════════════════════════════════════════════════════
-- C2 (35단어)
-- ══════════════════════════════════════════════════════════════════
UPDATE words SET example_en_2 = 'The epistemological stance shapes the research design.', example_ko_2 = '인식론적 입장이 연구 설계를 형성합니다.', example_en_3 = 'She raised epistemological questions about validity.', example_ko_3 = '그녀는 타당성에 관한 인식론적 질문을 제기했어요.', example_en_4 = 'An epistemological framework underpins the study.', example_ko_4 = '인식론적 프레임워크가 연구의 기반을 이룹니다.', example_en_5 = 'Epistemological humility improves research quality.', example_ko_5 = '인식론적 겸손이 연구 품질을 향상시킵니다.' WHERE id = 'w_presentation_C2_01';
UPDATE words SET example_en_2 = 'A heuristic shortcut can be useful but risky.', example_ko_2 = '발견적 지름길은 유용하지만 위험할 수 있습니다.', example_en_3 = 'We applied a heuristic to classify the data.', example_ko_3 = '데이터를 분류하기 위해 발견적 방법을 적용했습니다.', example_en_4 = 'Heuristic reasoning speeds up decision-making.', example_ko_4 = '발견적 추론이 의사결정을 가속화합니다.', example_en_5 = 'The heuristic proved accurate in most cases.', example_ko_5 = '발견적 방법이 대부분의 경우 정확한 것으로 입증되었습니다.' WHERE id = 'w_presentation_C2_02';
UPDATE words SET example_en_2 = 'Ontological assumptions must be made explicit.', example_ko_2 = '존재론적 가정을 명시적으로 밝혀야 합니다.', example_en_3 = 'Her ontological framework shapes every claim.', example_ko_3 = '그녀의 존재론적 프레임워크가 모든 주장을 형성합니다.', example_en_4 = 'The ontological question is rarely asked.', example_ko_4 = '존재론적 질문은 거의 제기되지 않습니다.', example_en_5 = 'Clarify ontological assumptions in the methodology.', example_ko_5 = '방법론에서 존재론적 가정을 명확히 하세요.' WHERE id = 'w_presentation_C2_03';
UPDATE words SET example_en_2 = 'A phenomenological study captures lived experience.', example_ko_2 = '현상학적 연구는 살아있는 경험을 포착합니다.', example_en_3 = 'She used a phenomenological lens for the analysis.', example_ko_3 = '그녀는 분석에 현상학적 렌즈를 사용했어요.', example_en_4 = 'Phenomenological research requires deep interviews.', example_ko_4 = '현상학적 연구는 심층 인터뷰가 필요합니다.', example_en_5 = 'The phenomenological approach reveals user experience.', example_ko_5 = '현상학적 접근법이 사용자 경험을 드러냅니다.' WHERE id = 'w_presentation_C2_04';
UPDATE words SET example_en_2 = 'The dialectical tension drove creative innovation.', example_ko_2 = '변증법적 긴장이 창의적 혁신을 이끌었습니다.', example_en_3 = 'She presented both sides in a dialectical way.', example_ko_3 = '그녀는 양쪽 면을 변증법적으로 발표했어요.', example_en_4 = 'A dialectical argument considers opposing views.', example_ko_4 = '변증법적 논거는 반대 견해를 고려합니다.', example_en_5 = 'The dialectical method leads to deeper insight.', example_ko_5 = '변증법적 방법이 더 깊은 인사이트로 이어집니다.' WHERE id = 'w_presentation_C2_05';
UPDATE words SET example_en_2 = 'Theory without praxis is merely academic.', example_ko_2 = '실천이 없는 이론은 단순히 학문적입니다.', example_en_3 = 'Praxis bridges the gap between theory and action.', example_ko_3 = '실천이 이론과 행동 사이의 격차를 메웁니다.', example_en_4 = 'The conference focused on praxis over theory.', example_ko_4 = '컨퍼런스는 이론보다 실천에 초점을 맞췄습니다.', example_en_5 = 'Strong praxis makes research more impactful.', example_ko_5 = '강력한 실천이 연구를 더 영향력 있게 만듭니다.' WHERE id = 'w_presentation_C2_06';
UPDATE words SET example_en_2 = 'A hermeneutic reading reveals hidden meaning.', example_ko_2 = '해석학적 독해가 숨겨진 의미를 드러냅니다.', example_en_3 = 'The hermeneutic circle guides interpretation.', example_ko_3 = '해석학적 순환이 해석을 안내합니다.', example_en_4 = 'She applied a hermeneutic lens to the interview data.', example_ko_4 = '그녀는 인터뷰 데이터에 해석학적 렌즈를 적용했어요.', example_en_5 = 'Hermeneutic analysis requires depth and patience.', example_ko_5 = '해석학적 분석은 깊이와 인내가 필요합니다.' WHERE id = 'w_presentation_C2_07';
UPDATE words SET example_en_2 = 'The meta-analysis covered twenty primary studies.', example_ko_2 = '메타분석은 20개의 기본 연구를 다루었습니다.', example_en_3 = 'Conduct a meta-analysis to increase statistical power.', example_ko_3 = '통계적 검정력을 높이기 위해 메타분석을 수행하세요.', example_en_4 = 'The meta-analysis confirmed the main hypothesis.', example_ko_4 = '메타분석이 주요 가설을 확인했습니다.', example_en_5 = 'She presented meta-analysis results with forest plots.', example_ko_5 = '그녀는 메타분석 결과를 포레스트 플롯으로 발표했어요.' WHERE id = 'w_presentation_C2_08';
UPDATE words SET example_en_2 = 'A positivist assumes objective measurable truth.', example_ko_2 = '실증주의자는 객관적으로 측정 가능한 진실을 가정합니다.', example_en_3 = 'The study took a strictly positivist approach.', example_ko_3 = '연구는 엄격히 실증주의적 접근법을 취했습니다.', example_en_4 = 'Positivist research relies heavily on statistics.', example_ko_4 = '실증주의 연구는 통계에 크게 의존합니다.', example_en_5 = 'She questioned the positivist assumptions in the field.', example_ko_5 = '그녀는 해당 분야의 실증주의적 가정에 의문을 제기했어요.' WHERE id = 'w_presentation_C2_09';
UPDATE words SET example_en_2 = 'A constructivist approach values context deeply.', example_ko_2 = '구성주의 접근법은 맥락을 깊이 중시합니다.', example_en_3 = 'Constructivist researchers co-create knowledge.', example_ko_3 = '구성주의 연구자들은 지식을 공동 창조합니다.', example_en_4 = 'She used a constructivist framework for the study.', example_ko_4 = '그녀는 연구에 구성주의 프레임워크를 사용했어요.', example_en_5 = 'A constructivist lens enriches qualitative analysis.', example_ko_5 = '구성주의 렌즈가 정성적 분석을 풍부하게 합니다.' WHERE id = 'w_presentation_C2_10';
UPDATE words SET example_en_2 = 'Begin with an axiom the board already accepts.', example_ko_2 = '이사회가 이미 받아들이는 공리로 시작하세요.', example_en_3 = 'The axiom of user rationality is often questioned.', example_ko_3 = '사용자 합리성의 공리는 종종 의문시됩니다.', example_en_4 = 'Challenge the axiom to open a new discussion.', example_ko_4 = '새로운 토론을 열기 위해 공리에 도전하세요.', example_en_5 = 'State the axiom explicitly before building on it.', example_ko_5 = '공리를 기반으로 구축하기 전에 명시적으로 진술하세요.' WHERE id = 'w_presentation_C2_11';
UPDATE words SET example_en_2 = 'Reification of abstract models can mislead.', example_ko_2 = '추상적 모델의 실물화는 오도할 수 있습니다.', example_en_3 = 'Avoid reification when presenting complex ideas.', example_ko_3 = '복잡한 아이디어를 발표할 때 실물화를 피하세요.', example_en_4 = 'The reification of data obscured the real meaning.', example_ko_4 = '데이터의 실물화가 진짜 의미를 모호하게 했습니다.', example_en_5 = 'She warned against reification in her talk.', example_ko_5 = '그녀는 발표에서 실물화에 대해 경고했어요.' WHERE id = 'w_presentation_C2_12';
UPDATE words SET example_en_2 = 'High verisimilitude makes data more convincing.', example_ko_2 = '높은 사실성이 데이터를 더 설득력 있게 만듭니다.', example_en_3 = 'Verisimilitude is critical in qualitative research.', example_ko_3 = '사실성은 정성적 연구에서 매우 중요합니다.', example_en_4 = 'The story had verisimilitude that engaged the audience.', example_ko_4 = '이야기에 청중을 사로잡는 사실성이 있었습니다.', example_en_5 = 'Verisimilitude is achieved through detail and precision.', example_ko_5 = '사실성은 세부 사항과 정밀도를 통해 달성됩니다.' WHERE id = 'w_presentation_C2_13';
UPDATE words SET example_en_2 = 'The exegesis revealed unexpected patterns.', example_ko_2 = '주석이 예상치 못한 패턴을 드러냈습니다.', example_en_3 = 'A careful exegesis is needed before conclusions.', example_ko_3 = '결론 전에 신중한 주석 작업이 필요합니다.', example_en_4 = 'She provided a rigorous exegesis of the data.', example_ko_4 = '그녀는 데이터의 엄격한 주석을 제공했어요.', example_en_5 = 'Exegesis of the survey required expert knowledge.', example_ko_5 = '설문의 주석 작업에는 전문 지식이 필요했습니다.' WHERE id = 'w_presentation_C2_14';
UPDATE words SET example_en_2 = 'The syllogism was presented clearly on the slide.', example_ko_2 = '삼단논법이 슬라이드에 명확하게 제시되었습니다.', example_en_3 = 'A flawed syllogism will undermine your argument.', example_ko_3 = '결함 있는 삼단논법이 논거를 훼손할 것입니다.', example_en_4 = 'She used a classic syllogism to open her talk.', example_ko_4 = '그녀는 발표를 시작하기 위해 고전적 삼단논법을 사용했어요.', example_en_5 = 'The syllogism helped structure the core argument.', example_ko_5 = '삼단논법이 핵심 논거를 구성하는 데 도움이 되었습니다.' WHERE id = 'w_presentation_C2_15';
UPDATE words SET example_en_2 = 'Tautology weakens your presentation logic.', example_ko_2 = '동어반복이 발표 논리를 약화시킵니다.', example_en_3 = 'Remove tautology to make your writing sharper.', example_ko_3 = '글을 더 날카롭게 만들기 위해 동어반복을 제거하세요.', example_en_4 = 'She identified tautology in the draft and corrected it.', example_ko_4 = '그녀는 초안에서 동어반복을 발견하고 수정했어요.', example_en_5 = 'Tautological arguments fail to advance the claim.', example_ko_5 = '동어반복적 논거는 주장을 발전시키지 못합니다.' WHERE id = 'w_presentation_C2_16';
UPDATE words SET example_en_2 = 'The award was the apotheosis of her career.', example_ko_2 = '그 상은 그녀 경력의 절정이었어요.', example_en_3 = 'This slide is the apotheosis of the argument.', example_ko_3 = '이 슬라이드는 논거의 절정입니다.', example_en_4 = 'The final case study is the apotheosis of the talk.', example_ko_4 = '최종 사례 연구가 발표의 절정입니다.', example_en_5 = 'The apotheosis of the research is this single finding.', example_ko_5 = '연구의 절정은 이 단일 발견입니다.' WHERE id = 'w_presentation_C2_17';
UPDATE words SET example_en_2 = 'Her polemic challenged every assumption.', example_ko_2 = '그녀의 논박이 모든 가정에 도전했어요.', example_en_3 = 'A polemic can sharpen discourse if done well.', example_ko_3 = '논박이 잘 수행되면 담론을 날카롭게 할 수 있습니다.', example_en_4 = 'He wrote a polemic against outdated practices.', example_ko_4 = '그는 구식 관행에 반하는 논박을 썼어요.', example_en_5 = 'A polemic should be evidence-based, not personal.', example_ko_5 = '논박은 개인적이 아닌 증거에 기반해야 합니다.' WHERE id = 'w_presentation_C2_18';
UPDATE words SET example_en_2 = 'Triangulation of methods increases confidence.', example_ko_2 = '방법의 삼각검증이 확신을 높입니다.', example_en_3 = 'She used triangulation to validate the findings.', example_ko_3 = '그녀는 발견을 검증하기 위해 삼각검증을 사용했어요.', example_en_4 = 'Triangulation reduces the risk of bias.', example_ko_4 = '삼각검증이 편향의 위험을 줄입니다.', example_en_5 = 'Include triangulation in every mixed-methods study.', example_ko_5 = '모든 혼합 방법 연구에 삼각검증을 포함하세요.' WHERE id = 'w_presentation_C2_19';
UPDATE words SET example_en_2 = 'Abductive reasoning led us to the best explanation.', example_ko_2 = '귀추적 추론이 우리를 최선의 설명으로 이끌었습니다.', example_en_3 = 'She used abductive logic to form the hypothesis.', example_ko_3 = '그녀는 가설을 형성하기 위해 귀추적 논리를 사용했어요.', example_en_4 = 'Abductive reasoning is common in early-stage research.', example_ko_4 = '귀추적 추론은 초기 단계 연구에서 일반적입니다.', example_en_5 = 'The team used abductive reasoning to explain anomalies.', example_ko_5 = '팀은 이상 징후를 설명하기 위해 귀추적 추론을 사용했습니다.' WHERE id = 'w_presentation_C2_20';
UPDATE words SET example_en_2 = 'Intersubjectivity strengthens qualitative validity.', example_ko_2 = '상호주관성이 정성적 타당성을 강화합니다.', example_en_3 = 'She built intersubjectivity through member checking.', example_ko_3 = '그녀는 구성원 확인을 통해 상호주관성을 구축했어요.', example_en_4 = 'Intersubjectivity requires transparent reflexivity.', example_ko_4 = '상호주관성은 투명한 성찰성을 요구합니다.', example_en_5 = 'The team achieved intersubjectivity after three rounds.', example_ko_5 = '팀은 세 차례의 라운드 후에 상호주관성을 달성했습니다.' WHERE id = 'w_presentation_C2_21';
UPDATE words SET example_en_2 = 'Her heterodox model challenged the mainstream.', example_ko_2 = '그녀의 비정통적 모델이 주류에 도전했어요.', example_en_3 = 'A heterodox view can spark productive debate.', example_ko_3 = '비정통적 관점이 생산적인 토론을 불러일으킬 수 있습니다.', example_en_4 = 'The heterodox approach is gaining more acceptance.', example_ko_4 = '비정통적 접근법이 점점 더 많은 수용을 얻고 있습니다.', example_en_5 = 'She presented a heterodox reading of the data.', example_ko_5 = '그녀는 데이터의 비정통적 해석을 발표했어요.' WHERE id = 'w_presentation_C2_22';
UPDATE words SET example_en_2 = 'Semiotics shapes how visuals communicate meaning.', example_ko_2 = '기호학이 시각 자료가 의미를 전달하는 방식을 형성합니다.', example_en_3 = 'She applied semiotics to analyze the ad campaign.', example_ko_3 = '그녀는 광고 캠페인을 분석하기 위해 기호학을 적용했어요.', example_en_4 = 'Semiotics helps us understand non-verbal communication.', example_ko_4 = '기호학이 비언어적 의사소통을 이해하는 데 도움이 됩니다.', example_en_5 = 'Color semiotics varies significantly across cultures.', example_ko_5 = '색채 기호학은 문화에 따라 크게 다릅니다.' WHERE id = 'w_presentation_C2_23';
UPDATE words SET example_en_2 = 'Reflexivity requires acknowledging your own biases.', example_ko_2 = '성찰성은 자신의 편향을 인정하는 것을 요구합니다.', example_en_3 = 'She demonstrated reflexivity throughout the study.', example_ko_3 = '그녀는 연구 전반에 걸쳐 성찰성을 보여줬어요.', example_en_4 = 'Reflexivity improves the trustworthiness of findings.', example_ko_4 = '성찰성이 발견의 신뢰성을 향상시킵니다.', example_en_5 = 'Include a reflexivity statement in the methodology.', example_ko_5 = '방법론에 성찰성 진술을 포함하세요.' WHERE id = 'w_presentation_C2_24';
UPDATE words SET example_en_2 = 'The teleological argument assumes a final purpose.', example_ko_2 = '목적론적 논거는 최종 목적을 가정합니다.', example_en_3 = 'She presented a teleological view of progress.', example_ko_3 = '그녀는 진보에 대한 목적론적 관점을 발표했어요.', example_en_4 = 'A teleological framework guides long-term planning.', example_ko_4 = '목적론적 프레임워크가 장기 계획을 안내합니다.', example_en_5 = 'The teleological assumption was challenged in Q&A.', example_ko_5 = '목적론적 가정이 질의응답에서 도전받았습니다.' WHERE id = 'w_presentation_C2_25';
UPDATE words SET example_en_2 = 'Reductionism misses the emergent complexity.', example_ko_2 = '환원주의는 창발적 복잡성을 놓칩니다.', example_en_3 = 'She criticized the reductionism in the model.', example_ko_3 = '그녀는 모델의 환원주의를 비판했어요.', example_en_4 = 'Avoid reductionism when studying human behavior.', example_ko_4 = '인간 행동을 연구할 때 환원주의를 피하세요.', example_en_5 = 'Reductionism can simplify but also distort findings.', example_ko_5 = '환원주의는 단순화하지만 발견을 왜곡할 수도 있습니다.' WHERE id = 'w_presentation_C2_26';
UPDATE words SET example_en_2 = 'The hypothesis must have falsifiability to be scientific.', example_ko_2 = '가설은 과학적이려면 반증가능성을 가져야 합니다.', example_en_3 = 'She checked the falsifiability of each claim.', example_ko_3 = '그녀는 각 주장의 반증가능성을 확인했어요.', example_en_4 = 'Falsifiability is the foundation of good science.', example_ko_4 = '반증가능성이 좋은 과학의 기반입니다.', example_en_5 = 'Without falsifiability, the claim is not testable.', example_ko_5 = '반증가능성 없이는 주장을 검증할 수 없습니다.' WHERE id = 'w_presentation_C2_27';
UPDATE words SET example_en_2 = 'The methodology was a bricolage of approaches.', example_ko_2 = '방법론은 다양한 접근법의 브리콜라주였습니다.', example_en_3 = 'Creative bricolage led to a unique solution.', example_ko_3 = '창의적인 브리콜라주가 독특한 솔루션으로 이어졌습니다.', example_en_4 = 'She described the project as intellectual bricolage.', example_ko_4 = '그녀는 프로젝트를 지적 브리콜라주로 설명했어요.', example_en_5 = 'Bricolage is common in interdisciplinary research.', example_ko_5 = '브리콜라주는 학제간 연구에서 일반적입니다.' WHERE id = 'w_presentation_C2_28';
UPDATE words SET example_en_2 = 'This case study instantiates the core theory.', example_ko_2 = '이 사례 연구가 핵심 이론을 구현합니다.', example_en_3 = 'She instantiated the abstract concept with a story.', example_ko_3 = '그녀는 이야기로 추상적 개념을 구현했어요.', example_en_4 = 'The example instantiates the pattern perfectly.', example_ko_4 = '예시가 패턴을 완벽하게 구현합니다.', example_en_5 = 'Use data to instantiate your theoretical claims.', example_ko_5 = '데이터를 사용해 이론적 주장을 구현하세요.' WHERE id = 'w_presentation_C2_29';
UPDATE words SET example_en_2 = 'Only probative evidence was included in the study.', example_ko_2 = '연구에는 증명력 있는 증거만 포함되었습니다.', example_en_3 = 'The court found the testimony probative.', example_ko_3 = '법원은 증언이 증명력 있다고 판단했습니다.', example_en_4 = 'Present only probative evidence in the main talk.', example_ko_4 = '메인 발표에서는 증명력 있는 증거만 제시하세요.', example_en_5 = 'Probative value must outweigh prejudicial effect.', example_ko_5 = '증명력이 편견 효과를 능가해야 합니다.' WHERE id = 'w_presentation_C2_30';
UPDATE words SET example_en_2 = 'Avoid circumlocution to hold audience attention.', example_ko_2 = '청중의 주의를 유지하기 위해 우회적 표현을 피하세요.', example_en_3 = 'His circumlocution lost the audience quickly.', example_ko_3 = '그의 우회적 표현이 빠르게 청중을 잃었어요.', example_en_4 = 'Edit for circumlocution before the final draft.', example_ko_4 = '최종 초안 전에 우회적 표현을 편집하세요.', example_en_5 = 'She replaced circumlocution with clear statements.', example_ko_5 = '그녀는 우회적 표현을 명확한 진술로 교체했어요.' WHERE id = 'w_presentation_C2_31';
UPDATE words SET example_en_2 = 'Apophenia leads analysts to false conclusions.', example_ko_2 = '패턴 착각 현상이 분석가들을 잘못된 결론으로 이끕니다.', example_en_3 = 'She warned against apophenia in data analysis.', example_ko_3 = '그녀는 데이터 분석에서 패턴 착각 현상에 대해 경고했어요.', example_en_4 = 'Apophenia can make noise look like signal.', example_ko_4 = '패턴 착각 현상이 노이즈를 신호처럼 보이게 할 수 있습니다.', example_en_5 = 'Statistical testing helps guard against apophenia.', example_ko_5 = '통계적 검정이 패턴 착각 현상을 방지하는 데 도움이 됩니다.' WHERE id = 'w_presentation_C2_32';
UPDATE words SET example_en_2 = 'The dominant episteme shapes what counts as knowledge.', example_ko_2 = '지배적인 에피스테메가 지식으로 인정되는 것을 형성합니다.', example_en_3 = 'She traced the episteme through two centuries.', example_ko_3 = '그녀는 2세기에 걸쳐 에피스테메를 추적했어요.', example_en_4 = 'Every discipline operates within an episteme.', example_ko_4 = '모든 학문 분야는 에피스테메 안에서 작동합니다.', example_en_5 = 'Challenge the episteme to open new possibilities.', example_ko_5 = '새로운 가능성을 열기 위해 에피스테메에 도전하세요.' WHERE id = 'w_presentation_C2_33';
UPDATE words SET example_en_2 = 'The isomorphism revealed a deep structural parallel.', example_ko_2 = '동형성이 깊은 구조적 유사성을 드러냈습니다.', example_en_3 = 'There is a clear isomorphism between the two frameworks.', example_ko_3 = '두 프레임워크 사이에 명확한 동형성이 있습니다.', example_en_4 = 'She exploited the isomorphism to simplify the proof.', example_ko_4 = '그녀는 증명을 단순화하기 위해 동형성을 활용했어요.', example_en_5 = 'Isomorphism allows findings to transfer across domains.', example_ko_5 = '동형성이 발견이 여러 분야에 걸쳐 전이되도록 합니다.' WHERE id = 'w_presentation_C2_34';
UPDATE words SET example_en_2 = 'Polysemy in key terms can confuse the audience.', example_ko_2 = '핵심 용어의 다의성이 청중을 혼란스럽게 할 수 있습니다.', example_en_3 = 'She flagged the polysemy of "value" in the talk.', example_ko_3 = '그녀는 발표에서 "가치"의 다의성을 표시했어요.', example_en_4 = 'Address polysemy early to avoid misunderstanding.', example_ko_4 = '오해를 피하기 위해 초반에 다의성을 다루세요.', example_en_5 = 'Polysemy is a challenge in cross-cultural presentations.', example_ko_5 = '다의성은 다문화 발표에서 도전 과제입니다.' WHERE id = 'w_presentation_C2_35';
