-- EngCat — culture (문화·예술) 단어 210개 + 패턴 42개
-- CEFR A1~C2, 각 레벨 35단어 × 6 + 7패턴 × 6
-- generated 2026-05-24

-- ══════════════════════════════════════
-- A1 — 문화·예술 기초 단어 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_culture_A1_01','music','/ˈmjuːzɪk/','noun','음악','Sounds arranged in a pleasing or expressive way.','I love {music}.','저는 음악을 좋아해요.','music','A1','culture',1,'music concert stage performance art'),
('w_culture_A1_02','art','/ɑːrt/','noun','예술, 미술','The expression of creative skill through painting, drawing, or other forms.','I enjoy looking at {art} in galleries.','저는 갤러리에서 그림 보는 것을 즐겨요.','art','A1','culture',1,'art gallery painting colorful wall'),
('w_culture_A1_03','movie','/ˈmuːvi/','noun','영화','A story told through moving pictures shown on a screen.','Let''s watch a {movie} tonight.','오늘 밤 영화 봐요.','movie','A1','culture',1,'cinema movie theater popcorn screen'),
('w_culture_A1_04','book','/bʊk/','noun','책','A set of printed pages bound together.','I read a {book} every week.','저는 매주 책을 읽어요.','book','A1','culture',1,'open book reading cozy library'),
('w_culture_A1_05','dance','/dæns/','noun','춤','Movement of the body in a rhythmic way, usually to music.','She loves to {dance} with her friends.','그녀는 친구들과 춤추는 것을 좋아해요.','dance','A1','culture',1,'dance performance stage spotlight'),
('w_culture_A1_06','paint','/peɪnt/','verb','그리다, 칠하다','To apply colour to a surface to create a picture or decoration.','She likes to {paint} on weekends.','그녀는 주말에 그림 그리는 것을 좋아해요.','paint','A1','culture',2,'painting artist canvas brush studio'),
('w_culture_A1_07','sing','/sɪŋ/','verb','노래하다','To make musical sounds with the voice.','He can {sing} very well.','그는 노래를 매우 잘해요.','sing','A1','culture',1,'singer microphone performance stage'),
('w_culture_A1_08','play','/pleɪ/','verb','(악기를) 연주하다','To perform music on an instrument.','I want to {play} the piano.','저는 피아노를 연주하고 싶어요.','play','A1','culture',1,'piano playing hands keyboard music'),
('w_culture_A1_09','show','/ʃoʊ/','noun','공연, 쇼','A performance or entertainment for an audience.','The {show} starts at seven.','공연은 7시에 시작해요.','show','A1','culture',1,'stage show performance audience theater'),
('w_culture_A1_10','story','/ˈstɔːri/','noun','이야기','An account of events, real or fictional.','She told me a beautiful {story}.','그녀가 저에게 아름다운 이야기를 해줬어요.','story','A1','culture',1,'storytelling book open pages warm light'),
('w_culture_A1_11','photo','/ˈfoʊtoʊ/','noun','사진','A picture made using a camera.','I took a {photo} of the painting.','저는 그림 사진을 찍었어요.','photo','A1','culture',2,'photography camera photo gallery wall'),
('w_culture_A1_12','draw','/drɔː/','verb','그리다 (선으로)','To make a picture using a pencil or pen.','Can you {draw} a simple picture?','간단한 그림을 그려줄 수 있나요?','draw','A1','culture',2,'drawing sketch pencil sketchbook'),
('w_culture_A1_13','song','/sɒŋ/','noun','노래','A piece of music with words.','That {song} is very popular.','그 노래는 매우 인기 있어요.','song','A1','culture',1,'song music notes headphones'),
('w_culture_A1_14','color','/ˈkʌlər/','noun','색깔','The property of an object that appears different under different light.','I love the {color} of this painting.','저는 이 그림의 색깔이 마음에 들어요.','color','A1','culture',2,'colorful painting palette bright art'),
('w_culture_A1_15','stage','/steɪdʒ/','noun','무대','The raised platform in a theatre where performers act.','The singer walked onto the {stage}.','가수가 무대 위로 걸어갔어요.','stage','A1','culture',1,'stage spotlight theater performance empty'),
('w_culture_A1_16','actor','/ˈæktər/','noun','배우','A person who performs roles in films or theatre.','My favourite {actor} is in this film.','제가 좋아하는 배우가 이 영화에 나와요.','actor','A1','culture',1,'actor film set scene performance'),
('w_culture_A1_17','film','/fɪlm/','noun','영화, 필름','A story recorded as a moving image for cinema or television.','Have you seen the new {film}?','새 영화 보셨어요?','film','A1','culture',1,'film cinema reel dark theater'),
('w_culture_A1_18','listen','/ˈlɪsən/','verb','듣다','To give attention to a sound.','I like to {listen} to music before bed.','자기 전에 음악 듣는 걸 좋아해요.','listen','A1','culture',2,'headphones listening music relax'),
('w_culture_A1_19','read','/riːd/','verb','읽다','To look at written words and understand them.','She loves to {read} novels.','그녀는 소설 읽는 것을 좋아해요.','read','A1','culture',1,'reading book cozy window light'),
('w_culture_A1_20','write','/raɪt/','verb','쓰다','To form letters or words on paper or a screen.','He can {write} beautiful poems.','그는 아름다운 시를 쓸 수 있어요.','write','A1','culture',2,'writing pen notebook poetry'),
('w_culture_A1_21','band','/bænd/','noun','밴드, 악단','A group of musicians who play together.','I love this {band}''s new album.','이 밴드의 새 앨범이 너무 좋아요.','band','A1','culture',2,'rock band performance concert stage'),
('w_culture_A1_22','drum','/drʌm/','noun','드럼, 북','A musical instrument that you hit to make sound.','He plays the {drum} in a band.','그는 밴드에서 드럼을 쳐요.','drum','A1','culture',3,'drums percussion musician performance'),
('w_culture_A1_23','guitar','/ɡɪˈtɑːr/','noun','기타','A stringed musical instrument played by plucking.','She plays the {guitar} every day.','그녀는 매일 기타를 쳐요.','guitar','A1','culture',1,'guitar acoustic playing music'),
('w_culture_A1_24','visit','/ˈvɪzɪt/','verb','방문하다','To go to a place in order to see it.','We should {visit} the art gallery.','미술관에 가봐야 해요.','visit','A1','culture',2,'art gallery visit people walking'),
('w_culture_A1_25','watch','/wɒtʃ/','verb','보다, 관람하다','To look at something for a period of time.','I like to {watch} musicals.','저는 뮤지컬 보는 것을 좋아해요.','watch','A1','culture',1,'watching performance theater audience'),
('w_culture_A1_26','ticket','/ˈtɪkɪt/','noun','티켓, 입장권','A piece of paper that lets you enter an event.','I bought a {ticket} for the concert.','콘서트 티켓을 샀어요.','ticket','A1','culture',1,'concert ticket stub event entrance'),
('w_culture_A1_27','poem','/ˈpoʊɪm/','noun','시','A piece of writing arranged in short lines.','She wrote a short {poem} about spring.','그녀는 봄에 대한 짧은 시를 썼어요.','poem','A1','culture',3,'poetry book open page writing'),
('w_culture_A1_28','picture','/ˈpɪktʃər/','noun','그림, 사진','A drawing, painting, or photograph.','I drew a {picture} of my family.','가족 그림을 그렸어요.','picture','A1','culture',2,'picture frame wall gallery art'),
('w_culture_A1_29','instrument','/ˈɪnstrəmənt/','noun','악기','An object used to make music.','Can you play a musical {instrument}?','악기를 연주할 수 있나요?','instrument','A1','culture',1,'musical instruments collection orchestra'),
('w_culture_A1_30','audience','/ˈɔːdiəns/','noun','관객, 청중','The people watching or listening to a performance.','The {audience} clapped loudly.','관객들이 크게 박수를 쳤어요.','audience','A1','culture',1,'audience applause theater clapping'),
('w_culture_A1_31','favourite','/ˈfeɪvərɪt/','adjective','가장 좋아하는','Preferred above all others.','What is your {favourite} song?','가장 좋아하는 노래가 뭐예요?','favourite','A1','culture',2,'favourite music headphones smiling'),
('w_culture_A1_32','character','/ˈkærɪktər/','noun','등장인물','A person in a book, film, or play.','My favourite {character} is in the story.','제가 가장 좋아하는 등장인물이 이야기에 나와요.','character','A1','culture',2,'story character book illustration'),
('w_culture_A1_33','colour','/ˈkʌlər/','noun','색채 (영국식)','Visual quality seen in paintings and art.','The painting uses many bright {colour}s.','그 그림은 밝은 색채를 많이 사용해요.','colour','A1','culture',2,'colorful bright painting abstract'),
('w_culture_A1_34','happy','/ˈhæpi/','adjective','행복한, 기쁜','Feeling or showing pleasure or contentment.','Music makes me feel {happy}.','음악을 들으면 기분이 행복해져요.','happy','A1','culture',3,'happy joyful concert music smiling'),
('w_culture_A1_35','new','/njuː/','adjective','새로운','Not existing before; recently made or introduced.','There is a {new} exhibition downtown.','시내에 새로운 전시회가 있어요.','new','A1','culture',3,'new exhibition gallery opening art')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- A2 — 공연·전시 관련 단어 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_culture_A2_01','festival','/ˈfestɪvəl/','noun','축제','A special event or celebration, often involving music or art.','We went to a music {festival} last summer.','지난 여름에 음악 축제에 갔어요.','festival','A2','culture',1,'music festival crowd outdoor summer stage'),
('w_culture_A2_02','museum','/mjuːˈziːəm/','noun','박물관','A building where objects of historical or cultural interest are kept.','The {museum} has a great collection of ancient art.','그 박물관에는 훌륭한 고대 미술 컬렉션이 있어요.','museum','A2','culture',1,'museum interior art exhibit hall'),
('w_culture_A2_03','theatre','/ˈθɪətər/','noun','극장, 연극','A building where plays, shows, or films are performed.','We saw a wonderful play at the {theatre}.','극장에서 훌륭한 연극을 봤어요.','theatre','A2','culture',1,'theater stage curtain interior seats'),
('w_culture_A2_04','concert','/ˈkɒnsərt/','noun','콘서트, 연주회','A live musical performance.','The {concert} was absolutely amazing.','콘서트가 정말 놀라웠어요.','concert','A2','culture',1,'concert live music crowd lights stage'),
('w_culture_A2_05','exhibition','/ˌeksɪˈbɪʃən/','noun','전시회','A public display of works of art or items of interest.','I visited the photography {exhibition} yesterday.','어제 사진 전시회에 갔어요.','exhibition','A2','culture',1,'art exhibition gallery white walls photos'),
('w_culture_A2_06','tradition','/trəˈdɪʃən/','noun','전통','A belief or practice passed down over generations.','Music is a big part of our {tradition}.','음악은 우리 전통의 중요한 부분이에요.','tradition','A2','culture',1,'traditional costume ceremony cultural heritage'),
('w_culture_A2_07','costume','/ˈkɒstjuːm/','noun','의상, 복장','Clothes worn by performers or at special events.','The dancers wore beautiful {costume}s.','무용수들이 아름다운 의상을 입었어요.','costume','A2','culture',2,'traditional costume dancer colorful performance'),
('w_culture_A2_08','sculpture','/ˈskʌlptʃər/','noun','조각품','A three-dimensional work of art made from stone, metal, or other materials.','That bronze {sculpture} is stunning.','저 청동 조각품은 정말 멋져요.','sculpture','A2','culture',2,'sculpture bronze museum art gallery'),
('w_culture_A2_09','gallery','/ˈɡæləri/','noun','갤러리, 화랑','A room or building for displaying works of art.','The new art {gallery} opens next month.','새 미술관이 다음 달에 문을 열어요.','gallery','A2','culture',1,'art gallery white walls paintings modern'),
('w_culture_A2_10','performance','/pərˈfɔːrməns/','noun','공연, 퍼포먼스','An act of presenting a play, concert, or other entertainment.','Her {performance} received a standing ovation.','그녀의 공연은 기립 박수를 받았어요.','performance','A2','culture',1,'dance performance stage spotlight applause'),
('w_culture_A2_11','choir','/kwaɪər/','noun','합창단','A group of singers who perform together.','She sings in the school {choir}.','그녀는 학교 합창단에서 노래해요.','choir','A2','culture',2,'choir singing performance church hall'),
('w_culture_A2_12','orchestra','/ˈɔːrkɪstrə/','noun','오케스트라','A large group of musicians playing together.','The {orchestra} played beautifully.','오케스트라가 아름답게 연주했어요.','orchestra','A2','culture',1,'orchestra classical music concert hall'),
('w_culture_A2_13','comedy','/ˈkɒmədi/','noun','코미디, 희극','A type of entertainment designed to make people laugh.','We watched a {comedy} at the theatre.','극장에서 코미디를 봤어요.','comedy','A2','culture',2,'comedy theater laughter audience smiling'),
('w_culture_A2_14','drama','/ˈdrɑːmə/','noun','드라마, 연극','A serious play for theatre, television, or radio.','The historical {drama} was very moving.','그 역사 드라마는 매우 감동적이었어요.','drama','A2','culture',1,'drama theater stage performance actors'),
('w_culture_A2_15','musical','/ˈmjuːzɪkəl/','noun','뮤지컬','A theatrical play that uses songs and dancing to tell a story.','I love watching Broadway {musical}s.','저는 브로드웨이 뮤지컬 보는 것을 좋아해요.','musical','A2','culture',1,'musical theater stage dancers singers'),
('w_culture_A2_16','ballet','/ˈbæleɪ/','noun','발레','A type of artistic dance performed to classical music.','She has been doing {ballet} since she was five.','그녀는 다섯 살 때부터 발레를 해왔어요.','ballet','A2','culture',2,'ballet dancer pointe shoes performance stage'),
('w_culture_A2_17','opera','/ˈɒpərə/','noun','오페라','A drama set to music in which the words are sung.','Have you ever been to an {opera}?','오페라 공연에 가본 적 있어요?','opera','A2','culture',2,'opera singer stage dramatic performance'),
('w_culture_A2_18','photography','/fəˈtɒɡrəfi/','noun','사진 촬영, 사진 예술','The art or practice of taking and developing photographs.','She studied {photography} at art school.','그녀는 미술학교에서 사진을 공부했어요.','photography','A2','culture',1,'photography camera lens artistic black white'),
('w_culture_A2_19','exhibition hall','/ˌeksɪˈbɪʃən hɔːl/','noun','전시 홀','A large room designed to host exhibitions.','The {exhibition hall} was full of visitors.','전시 홀이 방문객으로 가득 찼어요.','exhibition hall','A2','culture',2,'exhibition hall interior spacious art visitors'),
('w_culture_A2_20','admission','/ədˈmɪʃən/','noun','입장료, 입장','The fee charged for entering a place.','{Admission} to the museum is free on Sundays.','박물관 입장은 일요일에 무료예요.','Admission','A2','culture',2,'museum entrance admission ticket counter'),
('w_culture_A2_21','rehearsal','/rɪˈhɜːrsəl/','noun','리허설, 예행 연습','A practice session for a public performance.','The band has a {rehearsal} tonight.','밴드가 오늘 밤 리허설이 있어요.','rehearsal','A2','culture',2,'rehearsal practice musicians stage empty theater'),
('w_culture_A2_22','classic','/ˈklæsɪk/','adjective','고전적인, 대표적인','Judged over a period of time to be of the highest quality.','This is a {classic} piece of jazz.','이건 대표적인 재즈 곡이에요.','classic','A2','culture',1,'classic vinyl record jazz music warm'),
('w_culture_A2_23','style','/staɪl/','noun','스타일, 양식','A particular way of doing or presenting something.','I love the {style} of impressionist paintings.','인상주의 그림의 양식이 마음에 들어요.','style','A2','culture',1,'painting style impressionist art museum'),
('w_culture_A2_24','culture','/ˈkʌltʃər/','noun','문화','The ideas, customs, and artistic achievements of a society.','Korean {culture} has become popular worldwide.','한국 문화가 전 세계적으로 인기를 얻고 있어요.','culture','A2','culture',1,'korean culture traditional modern city'),
('w_culture_A2_25','artist','/ˈɑːrtɪst/','noun','예술가, 화가','A person who creates works of art.','The {artist} painted every day for a year.','그 예술가는 1년 동안 매일 그림을 그렸어요.','artist','A2','culture',1,'artist painting studio creative workspace'),
('w_culture_A2_26','audience clap','/ˈɔːdiəns klæp/','phrase','박수치다','When an audience shows appreciation by clapping.','The {audience clap}ped after every song.','모든 노래 후에 관객들이 박수를 쳤어요.','audience clap','A2','culture',3,'audience applause clapping concert hall'),
('w_culture_A2_27','singer','/ˈsɪŋər/','noun','가수','A person who sings, especially professionally.','The {singer} has a beautiful voice.','그 가수는 아름다운 목소리를 갖고 있어요.','singer','A2','culture',1,'singer microphone stage spotlight performance'),
('w_culture_A2_28','pianist','/piˈænɪst/','noun','피아니스트','A person who plays the piano.','The {pianist} performed a Chopin sonata.','피아니스트가 쇼팽 소나타를 연주했어요.','pianist','A2','culture',2,'pianist piano classical performance concert'),
('w_culture_A2_29','preview','/ˈpriːvjuː/','noun','시사회, 미리보기','A showing of a film or performance before its official release.','We attended the {preview} of the new musical.','새 뮤지컬 시사회에 참석했어요.','preview','A2','culture',2,'movie preview screening film audience'),
('w_culture_A2_30','souvenir','/ˌsuːvəˈnɪr/','noun','기념품','A thing kept as a reminder of a place or event.','I bought a {souvenir} at the museum shop.','박물관 기념품 가게에서 기념품을 샀어요.','souvenir','A2','culture',3,'museum souvenir shop gifts'),
('w_culture_A2_31','applaud','/əˈplɔːd/','verb','박수를 치다','To show approval by clapping hands.','The crowd {applaud}ed at the end of the show.','공연이 끝날 때 관객들이 박수를 쳤어요.','applaud','A2','culture',2,'applause audience clapping theater bravo'),
('w_culture_A2_32','costume design','/ˈkɒstjuːm dɪˈzaɪn/','noun','의상 디자인','The art of creating costumes for theatre or film.','She studied {costume design} in college.','그녀는 대학에서 의상 디자인을 공부했어요.','costume design','A2','culture',3,'costume design fashion sewing theater'),
('w_culture_A2_33','narrator','/ˈnærɪtər/','noun','나레이터, 해설자','A person who narrates a story or gives a commentary.','The {narrator} had a wonderful voice.','나레이터는 훌륭한 목소리를 갖고 있었어요.','narrator','A2','culture',2,'narrator reading microphone storytelling'),
('w_culture_A2_34','interval','/ˈɪntərvəl/','noun','인터미션, 막간','A pause or break in a performance.','We had drinks during the {interval}.','인터미션 동안 음료를 마셨어요.','interval','A2','culture',3,'theater lobby intermission drinks people'),
('w_culture_A2_35','programme','/ˈproʊɡræm/','noun','프로그램 (공연)','A booklet with information about a performance or event.','I kept the {programme} as a souvenir.','기념으로 공연 프로그램을 간직했어요.','programme','A2','culture',2,'concert program booklet theater event')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- B1 — 예술 감상·장르 단어 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_culture_B1_01','heritage','/ˈherɪtɪdʒ/','noun','유산, 문화유산','Property, tradition, or culture passed down from the past.','We must protect our cultural {heritage}.','우리는 문화유산을 보호해야 해요.','heritage','B1','culture',1,'cultural heritage ancient ruins historic site'),
('w_culture_B1_02','contemporary','/kənˈtempəreri/','adjective','현대적인, 동시대의','Existing or happening at the same time as the present.','I prefer {contemporary} art to classical styles.','저는 고전 양식보다 현대 미술을 선호해요.','contemporary','B1','culture',1,'contemporary art gallery modern sculpture'),
('w_culture_B1_03','genre','/ˈʒɑːnrə/','noun','장르','A category of art, music, or literature defined by style.','What {genre} of music do you prefer?','어떤 장르의 음악을 선호하세요?','genre','B1','culture',1,'music genre vinyl record collection'),
('w_culture_B1_04','curator','/kjʊˈreɪtər/','noun','큐레이터','A person responsible for selecting and looking after items in a museum.','The {curator} explained the meaning of each painting.','큐레이터가 각 그림의 의미를 설명해 줬어요.','curator','B1','culture',2,'museum curator art gallery explaining'),
('w_culture_B1_05','aesthetic','/esˈθetɪk/','adjective','미학적인, 심미적인','Concerned with beauty and the appreciation of art.','I admire the {aesthetic} quality of Japanese design.','저는 일본 디자인의 미학적 품질을 감탄해요.','aesthetic','B1','culture',2,'aesthetic minimalist design art japanese'),
('w_culture_B1_06','classical','/ˈklæsɪkəl/','adjective','고전적인, 클래식의','Relating to ancient Greek or Roman culture, or traditional art forms.','She plays {classical} violin at a conservatory.','그녀는 음악원에서 클래식 바이올린을 연주해요.','classical','B1','culture',1,'classical music violin concert hall'),
('w_culture_B1_07','modern','/ˈmɒdərn/','adjective','현대적인, 근대의','Of or relating to the present or recent times.','{Modern} art can be difficult to interpret.','현대 미술은 해석하기 어려울 수 있어요.','modern','B1','culture',1,'modern art museum abstract painting'),
('w_culture_B1_08','folk','/foʊk/','adjective','민속의, 전통 민요의','Relating to the traditional art, music, or culture of a community.','The {folk} music festival was very lively.','민속 음악 축제가 매우 활기찼어요.','folk','B1','culture',2,'folk music traditional instrument village'),
('w_culture_B1_09','indigenous','/ɪnˈdɪdʒɪnəs/','adjective','토착의, 원주민의','Originating or occurring naturally in a particular place.','The exhibition showcased {indigenous} art forms.','그 전시회는 토착 예술 형태를 선보였어요.','indigenous','B1','culture',2,'indigenous art traditional tribal cultural'),
('w_culture_B1_10','symbolism','/ˈsɪmbəlɪzəm/','noun','상징주의, 상징성','The use of symbols to represent ideas or qualities.','The {symbolism} in this painting is very layered.','이 그림의 상징성은 매우 다층적이에요.','symbolism','B1','culture',2,'symbolism painting art meaning mysterious'),
('w_culture_B1_11','inspired','/ɪnˈspaɪərd/','adjective','영감 받은','Of extraordinary quality, as if from a divine source.','The sculpture was clearly {inspired} by nature.','그 조각품은 분명히 자연에서 영감을 받았어요.','inspired','B1','culture',1,'inspired artist creative nature landscape'),
('w_culture_B1_12','rhythm','/ˈrɪðəm/','noun','리듬, 박자','A strong regular repeated pattern of sound or movement.','The {rhythm} of the drum was hypnotic.','드럼의 리듬이 최면적이었어요.','rhythm','B1','culture',1,'rhythm drum beats music performance'),
('w_culture_B1_13','composition','/ˌkɒmpəˈzɪʃən/','noun','구성, 작곡','A piece of music, writing, or art; the way elements are arranged.','The {composition} uses bold contrasts of colour.','그 구성은 색채의 강렬한 대조를 사용해요.','composition','B1','culture',2,'musical composition score notes piano'),
('w_culture_B1_14','masterpiece','/ˈmɑːstərpiːs/','noun','걸작','A work of outstanding artistry, skill, or workmanship.','This painting is considered a {masterpiece}.','이 그림은 걸작으로 여겨져요.','masterpiece','B1','culture',1,'masterpiece famous painting museum louvre'),
('w_culture_B1_15','portrait','/ˈpɔːrtrɪt/','noun','초상화, 인물 사진','A painting, drawing, or photograph of a person.','She sat for a {portrait} by a local artist.','그녀는 지역 화가에게 초상화를 그려달라고 앉았어요.','portrait','B1','culture',2,'portrait painting face oil canvas museum'),
('w_culture_B1_16','landscape','/ˈlændskeɪp/','noun','풍경화, 경치','A painting that shows natural scenery.','The {landscape} paintings in this gallery are breathtaking.','이 갤러리의 풍경화들은 숨막히게 아름다워요.','landscape','B1','culture',1,'landscape painting countryside field oil'),
('w_culture_B1_17','biography','/baɪˈɒɡrəfi/','noun','전기, 자서전','A written account of someone''s life.','The {biography} of the composer was fascinating.','그 작곡가의 전기는 매우 흥미로웠어요.','biography','B1','culture',2,'biography book musician composer reading'),
('w_culture_B1_18','narrative','/ˈnærətɪv/','noun','서사, 이야기 방식','A spoken or written account of events; a story.','The film''s {narrative} is told from multiple perspectives.','그 영화의 서사는 여러 시각에서 전달돼요.','narrative','B1','culture',2,'narrative story film cinema storytelling'),
('w_culture_B1_19','technique','/tekˈniːk/','noun','기법, 기술','A way of carrying out a particular task in art or music.','Her {technique} on the violin is flawless.','그녀의 바이올린 기법은 완벽해요.','technique','B1','culture',1,'painting technique brush canvas art studio'),
('w_culture_B1_20','influence','/ˈɪnfluəns/','noun','영향, 영향력','The power to have an effect on others.','His work had a huge {influence} on modern jazz.','그의 작품은 현대 재즈에 큰 영향을 미쳤어요.','influence','B1','culture',1,'artistic influence inspiration creative history'),
('w_culture_B1_21','movement','/ˈmuːvmənt/','noun','(예술) 운동, 사조','A group of people working together to advance shared ideas.','Impressionism was a revolutionary art {movement}.','인상주의는 혁명적인 예술 운동이었어요.','movement','B1','culture',1,'impressionism art movement painting monet'),
('w_culture_B1_22','exhibition tour','/ˌeksɪˈbɪʃən tʊr/','noun','전시 투어','A guided walk through an exhibition with explanation.','We joined a guided {exhibition tour}.','저희는 안내 전시 투어에 참여했어요.','exhibition tour','B1','culture',2,'guided tour museum art exhibit group'),
('w_culture_B1_23','melody','/ˈmelədi/','noun','멜로디, 선율','A sequence of musical notes forming a pleasing tune.','The {melody} stayed in my head all day.','멜로디가 하루 종일 머릿속에 맴돌았어요.','melody','B1','culture',1,'melody music notes piano soft'),
('w_culture_B1_24','chorus','/ˈkɔːrəs/','noun','후렴구, 코러스','The part of a song repeated after each verse.','Everyone sang along to the {chorus}.','모두가 후렴구를 따라 불렀어요.','chorus','B1','culture',1,'chorus singing concert crowd stage'),
('w_culture_B1_25','tribute','/ˈtrɪbjuːt/','noun','헌정, 경의','Something done to show respect or admiration.','The concert was a {tribute} to a legendary musician.','그 콘서트는 전설적인 음악가에 대한 헌정이었어요.','tribute','B1','culture',2,'tribute concert musician legacy performance'),
('w_culture_B1_26','collaboration','/kəˌlæbəˈreɪʃən/','noun','협업, 공동 작업','Working jointly with others on a creative project.','The album was a {collaboration} between two artists.','그 앨범은 두 예술가의 협업이었어요.','collaboration','B1','culture',2,'collaboration artists creative studio together'),
('w_culture_B1_27','venue','/ˈvenjuː/','noun','공연 장소, 베뉴','The place where an event takes place.','The {venue} holds up to five thousand people.','그 공연 장소는 최대 5천 명을 수용해요.','venue','B1','culture',1,'concert venue hall building entrance'),
('w_culture_B1_28','acoustic','/əˈkuːstɪk/','adjective','어쿠스틱의, 음향의','Not electrically amplified; relating to sound.','I prefer {acoustic} guitar to electric guitar.','저는 일렉트릭 기타보다 어쿠스틱 기타를 선호해요.','acoustic','B1','culture',2,'acoustic guitar coffee shop intimate performance'),
('w_culture_B1_29','showcase','/ˈʃoʊkeɪs/','verb','선보이다, 전시하다','To display or exhibit something prominently.','The festival {showcase}s emerging local talent.','그 축제는 신흥 지역 인재를 선보여요.','showcase','B1','culture',2,'showcase talent performance stage spotlight'),
('w_culture_B1_30','revival','/rɪˈvaɪvəl/','noun','재현, 부활','A new performance of an old play or musical.','The {revival} of the classic musical was well received.','그 고전 뮤지컬의 재현은 호평을 받았어요.','revival','B1','culture',2,'revival theater classic musical performance'),
('w_culture_B1_31','dramatic','/drəˈmætɪk/','adjective','극적인, 연극적인','Relating to drama; sudden and striking.','The {dramatic} ending of the play left everyone speechless.','연극의 극적인 결말이 모두를 말문이 막히게 했어요.','dramatic','B1','culture',1,'dramatic stage performance theater lighting'),
('w_culture_B1_32','improvise','/ˈɪmprəvaɪz/','verb','즉흥 연주하다, 즉흥으로 하다','To create and perform spontaneously.','Jazz musicians often {improvise} during a performance.','재즈 음악가들은 공연 중에 자주 즉흥 연주를 해요.','improvise','B1','culture',2,'jazz improvise saxophone musician night'),
('w_culture_B1_33','gallery opening','/ˈɡæləri ˈoʊpənɪŋ/','noun','갤러리 오프닝','A special event to launch a new art exhibition.','I was invited to the {gallery opening} last Friday.','지난 금요일 갤러리 오프닝에 초대받았어요.','gallery opening','B1','culture',2,'gallery opening art event people socializing'),
('w_culture_B1_34','solo','/ˈsoʊloʊ/','noun','독주, 솔로','A performance done by one person alone.','He played a beautiful piano {solo}.','그는 아름다운 피아노 독주를 연주했어요.','solo','B1','culture',1,'solo performance musician stage spotlight'),
('w_culture_B1_35','atmosphere','/ˈætməsfɪər/','noun','분위기','The mood or feeling of a place or artistic work.','The concert hall had a magical {atmosphere}.','콘서트홀은 마법 같은 분위기가 있었어요.','atmosphere','B1','culture',1,'concert hall atmosphere warm lighting audience')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- B2 — 문화 비교·비평 단어 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_culture_B2_01','avant-garde','/ˌævɑːnt ˈɡɑːrd/','adjective','전위적인, 아방가르드','New and experimental ideas in art, music, or literature.','His {avant-garde} compositions divided critics.','그의 전위적인 작품은 비평가들 사이에 의견이 갈렸어요.','avant-garde','B2','culture',2,'avant-garde art experimental gallery abstract'),
('w_culture_B2_02','abstract','/ˈæbstrækt/','adjective','추상적인','Not representing real things but expressing ideas through shapes and colours.','{Abstract} painting requires a different way of seeing.','추상화는 다른 방식의 시각을 요구해요.','abstract','B2','culture',1,'abstract painting colorful shapes modern art'),
('w_culture_B2_03','surrealism','/səˈrɪəlɪzəm/','noun','초현실주의','An art movement that uses strange, dreamlike imagery.','Dalí is the most famous figure of {surrealism}.','달리는 초현실주의의 가장 유명한 인물이에요.','surrealism','B2','culture',2,'surrealism dali dreamlike painting bizarre'),
('w_culture_B2_04','patronage','/ˈpeɪtrənɪdʒ/','noun','후원, 예술 지원','The support given by a patron to an artist or institution.','The arts depend heavily on corporate {patronage}.','예술은 기업 후원에 크게 의존해요.','patronage','B2','culture',2,'art patronage sponsor donation museum'),
('w_culture_B2_05','iconography','/ˌaɪkəˈnɒɡrəfi/','noun','도상학, 도상','Symbols and imagery associated with a subject in art.','Understanding the {iconography} enriches the viewing experience.','도상학을 이해하면 감상 경험이 풍부해져요.','iconography','B2','culture',3,'religious iconography painting symbols art museum'),
('w_culture_B2_06','postmodern','/ˌpoʊstˈmɒdərn/','adjective','포스트모던의','Relating to or denoting an artistic style that questions established norms.','The building''s design is unmistakably {postmodern}.','그 건물의 디자인은 명백히 포스트모던이에요.','postmodern','B2','culture',2,'postmodern architecture design building quirky'),
('w_culture_B2_07','critique','/krɪˈtiːk/','noun','비평, 평론','A detailed analysis and assessment of something.','The {critique} pointed out flaws in the film''s structure.','그 비평은 영화 구조의 결함을 지적했어요.','critique','B2','culture',1,'film critique review writing analysis'),
('w_culture_B2_08','interpretation','/ɪnˌtɜːrprɪˈteɪʃən/','noun','해석, 이해','An explanation of the meaning of something.','Each viewer brought their own {interpretation} to the work.','각 관람객은 작품에 자신만의 해석을 가져왔어요.','interpretation','B2','culture',1,'art interpretation gallery viewer thinking'),
('w_culture_B2_09','aesthetic movement','/esˈθetɪk ˈmuːvmənt/','noun','미학 운동','An artistic philosophy emphasising beauty for its own sake.','The {aesthetic movement} rejected Victorian moralism.','미학 운동은 빅토리아 시대의 도덕주의를 거부했어요.','aesthetic movement','B2','culture',2,'aesthetic art movement beauty decoration victorian'),
('w_culture_B2_10','cross-cultural','/ˌkrɒs ˈkʌltʃərəl/','adjective','다문화적인, 문화 간의','Relating to or involving different cultures.','The exhibition explored {cross-cultural} influences on design.','그 전시회는 디자인에 대한 다문화적 영향을 탐구했어요.','cross-cultural','B2','culture',2,'cross cultural diversity art multicultural'),
('w_culture_B2_11','curator''s note','/kjʊˈreɪtərz noʊt/','noun','큐레이터 노트','A written explanation provided by a curator about exhibits.','I read the {curator''s note} before entering the gallery.','갤러리에 들어가기 전에 큐레이터 노트를 읽었어요.','curator''s note','B2','culture',3,'curator note gallery text wall art'),
('w_culture_B2_12','controversy','/ˈkɒntrəvɜːrsi/','noun','논란, 논쟁','A prolonged public disagreement about a topic.','The painting caused considerable {controversy} when first shown.','그 그림은 처음 전시됐을 때 상당한 논란을 일으켰어요.','controversy','B2','culture',2,'art controversy debate media headlines'),
('w_culture_B2_13','commission','/kəˈmɪʃən/','noun','의뢰, 커미션','An instruction to produce a work of art.','The artist received a {commission} from the city council.','그 예술가는 시의회로부터 의뢰를 받았어요.','commission','B2','culture',2,'art commission artist studio painting'),
('w_culture_B2_14','installation','/ˌɪnstəˈleɪʃən/','noun','설치 미술','A large-scale artwork created for a specific space.','The {installation} filled the entire room with sound.','그 설치 미술이 방 전체를 소리로 채웠어요.','installation','B2','culture',2,'art installation contemporary museum space'),
('w_culture_B2_15','provenance','/ˈprɒvənəns/','noun','출처, 유래','The place of origin or earliest known history of a work.','The {provenance} of this sculpture is disputed.','이 조각품의 출처는 논쟁 중이에요.','provenance','B2','culture',3,'art provenance museum auction history'),
('w_culture_B2_16','retrospective','/ˌretrəˈspektɪv/','noun','회고전','An exhibition reviewing an artist''s work over many years.','A major {retrospective} of her paintings opens next spring.','그녀의 그림 대규모 회고전이 내년 봄에 열려요.','retrospective','B2','culture',2,'retrospective exhibition museum artist career'),
('w_culture_B2_17','multimedia','/ˌmʌltiˈmiːdiə/','adjective','멀티미디어의','Using more than one medium of expression.','The {multimedia} exhibition combined video, sound, and sculpture.','그 멀티미디어 전시는 영상, 소리, 조각을 결합했어요.','multimedia','B2','culture',2,'multimedia art installation video projection'),
('w_culture_B2_18','satire','/ˈsætaɪər/','noun','풍자','The use of humour or exaggeration to criticise society.','Political {satire} has a long history in literature.','정치적 풍자는 문학에서 오랜 역사를 갖고 있어요.','satire','B2','culture',2,'satire art political cartoon magazine'),
('w_culture_B2_19','censorship','/ˈsensərʃɪp/','noun','검열','The suppression of material considered harmful or offensive.','The film was altered due to {censorship}.','그 영화는 검열로 인해 수정됐어요.','censorship','B2','culture',2,'censorship media banned art freedom'),
('w_culture_B2_20','fusion','/ˈfjuːʒən/','noun','융합, 퓨전','The combination of different styles or cultures.','The band plays a {fusion} of jazz and traditional folk music.','그 밴드는 재즈와 전통 민속 음악의 퓨전을 연주해요.','fusion','B2','culture',1,'fusion music cultural blend performance'),
('w_culture_B2_21','immersive','/ɪˈmɜːrsɪv/','adjective','몰입형의','Providing deep mental involvement.','The {immersive} theatre experience blurred reality and fiction.','그 몰입형 연극 경험은 현실과 허구를 모호하게 했어요.','immersive','B2','culture',2,'immersive theater art experience vr projection'),
('w_culture_B2_22','groundbreaking','/ˈɡraʊndbreɪkɪŋ/','adjective','획기적인, 선구적인','Innovative and pioneering.','The director''s {groundbreaking} style changed cinema.','그 감독의 획기적인 스타일이 영화를 바꿨어요.','groundbreaking','B2','culture',1,'groundbreaking film cinema director innovation'),
('w_culture_B2_23','transcript','/ˈtrænskrɪpt/','noun','대본, 기록문','A written version of spoken or recorded text.','The {transcript} of the lecture was published online.','강의 대본이 온라인에 게시됐어요.','transcript','B2','culture',3,'lecture transcript text document reading'),
('w_culture_B2_24','acclaim','/əˈkleɪm/','noun','찬사, 호평','Enthusiastic and public praise.','The film received widespread {acclaim} from critics.','그 영화는 비평가들로부터 광범위한 찬사를 받았어요.','acclaim','B2','culture',1,'acclaim award ceremony applause film'),
('w_culture_B2_25','censure','/ˈsenʃər/','noun','비난, 견책','Strong disapproval or criticism.','The artwork faced widespread {censure} for its content.','그 예술 작품은 내용으로 인해 광범위한 비난을 받았어요.','censure','B2','culture',3,'criticism media controversy art reaction'),
('w_culture_B2_26','pastiche','/pæˈstiːʃ/','noun','패스티시, 혼성 모방','A work of art that imitates or is inspired by another work.','The film is a deliberate {pastiche} of 1950s noir.','그 영화는 1950년대 누아르를 의도적으로 모방한 작품이에요.','pastiche','B2','culture',3,'pastiche film noir retro cinema style'),
('w_culture_B2_27','depiction','/dɪˈpɪkʃən/','noun','묘사, 표현','A representation or portrayal of something in art.','The {depiction} of war in this painting is vivid.','이 그림에서 전쟁의 묘사는 생생해요.','depiction','B2','culture',2,'painting depiction war history art museum'),
('w_culture_B2_28','subversive','/səbˈvɜːrsɪv/','adjective','전복적인, 기존 체제에 도전하는','Seeking to undermine established ideas or authority.','The artist is known for her {subversive} installations.','그 예술가는 전복적인 설치 미술로 알려져 있어요.','subversive','B2','culture',3,'subversive street art urban graffiti'),
('w_culture_B2_29','commentary','/ˈkɒməntri/','noun','해설, 논평','A spoken or written explanation of events.','The documentary includes an insightful {commentary} on art history.','그 다큐멘터리는 미술사에 대한 통찰력 있는 해설을 포함해요.','commentary','B2','culture',2,'art documentary commentary film analysis'),
('w_culture_B2_30','stereotype','/ˈsteriətaɪp/','noun','고정관념','A widely held but fixed and oversimplified idea about a group.','The film challenges cultural {stereotype}s.','그 영화는 문화적 고정관념에 도전해요.','stereotype','B2','culture',2,'stereotype challenge diversity culture art'),
('w_culture_B2_31','benchmark','/ˈbentʃmɑːrk/','noun','기준, 척도','A standard against which things may be compared.','This film set the {benchmark} for visual effects.','이 영화는 시각 효과의 기준을 세웠어요.','benchmark','B2','culture',2,'benchmark excellence film industry award'),
('w_culture_B2_32','canon','/ˈkænən/','noun','정전, 기준 작품 목록','The accepted body of work considered most important in a field.','Shakespeare is central to the literary {canon}.','셰익스피어는 문학 정전의 핵심이에요.','canon','B2','culture',2,'literary canon books classic literature shelf'),
('w_culture_B2_33','motif','/moʊˈtiːf/','noun','모티프, 반복되는 주제','A recurring element or theme in a creative work.','Water is a key {motif} in Impressionist painting.','물은 인상주의 회화의 핵심 모티프예요.','motif','B2','culture',2,'monet water lilies impressionist motif art'),
('w_culture_B2_34','medium','/ˈmiːdiəm/','noun','매체, 재료 (예술)','The material or form used by an artist to create their work.','Oil paint is her chosen {medium}.','유화 물감은 그녀가 선택한 매체예요.','medium','B2','culture',1,'oil paint medium canvas art studio brushes'),
('w_culture_B2_35','allusion','/əˈluːʒən/','noun','암시, 인유','An indirect reference to another work or event.','The poem contains an {allusion} to Greek mythology.','그 시는 그리스 신화에 대한 암시를 담고 있어요.','allusion','B2','culture',3,'poetry myth reference classical literature')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- C1 — 예술 비평·이론 단어 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_culture_C1_01','semiotics','/ˌsiːmiˈɒtɪks/','noun','기호학','The study of signs and symbols and their use or interpretation.','The professor lectured on {semiotics} and visual art.','교수가 기호학과 시각 예술에 대해 강의했어요.','semiotics','C1','culture',2,'semiotics signs symbols lecture university'),
('w_culture_C1_02','hermeneutics','/ˌhɜːrmɪˈnjuːtɪks/','noun','해석학','The theory of interpretation, especially of texts or art.','{Hermeneutics} offers a framework for reading literary works.','해석학은 문학 작품을 읽는 틀을 제공해요.','hermeneutics','C1','culture',3,'hermeneutics text interpretation study academic'),
('w_culture_C1_03','deconstruction','/ˌdiːkənˈstrʌkʃən/','noun','해체주의, 해체적 읽기','A method of critical analysis that questions assumed meanings.','Derrida''s {deconstruction} challenged stable textual meaning.','데리다의 해체주의는 안정된 텍스트의 의미에 도전했어요.','deconstruction','C1','culture',2,'deconstruction philosophy text theory academic'),
('w_culture_C1_04','phenomenology','/fɪˌnɒmɪˈnɒlədʒi/','noun','현상학','The philosophical study of the structures of experience.','{Phenomenology} helps explain how art is perceived.','현상학은 예술이 어떻게 인식되는지 설명하는 데 도움이 돼요.','phenomenology','C1','culture',3,'phenomenology experience philosophy art perception'),
('w_culture_C1_05','structuralism','/ˈstrʌktʃərəlɪzəm/','noun','구조주의','An approach that analyses elements of human culture as part of a larger system.','{Structuralism} views culture as a system of signs.','구조주의는 문화를 기호 체계로 봐요.','structuralism','C1','culture',2,'structuralism theory analysis diagram university'),
('w_culture_C1_06','intertextuality','/ˌɪntəˌtekstʃuˈælɪti/','noun','상호텍스트성','The relationship between texts and how they influence each other.','The novel is rich in {intertextuality}, referencing dozens of classic works.','그 소설은 수십 편의 고전 작품을 인용하며 상호텍스트성이 풍부해요.','intertextuality','C1','culture',2,'books library references intertextuality literature'),
('w_culture_C1_07','dialectic','/ˌdaɪəˈlektɪk/','noun','변증법','A method of argument by which contradictions are resolved.','Hegel''s {dialectic} influenced many art historians.','헤겔의 변증법은 많은 미술사가에게 영향을 미쳤어요.','dialectic','C1','culture',3,'dialectic philosophy argument debate theory'),
('w_culture_C1_08','mimesis','/mɪˈmiːsɪs/','noun','미메시스, 모방','The imitation of the real world in art and literature.','Aristotle introduced the concept of {mimesis} in the Poetics.','아리스토텔레스는 시학에서 미메시스 개념을 소개했어요.','mimesis','C1','culture',3,'aristotle poetics philosophy art imitation'),
('w_culture_C1_09','catharsis','/kəˈθɑːrsɪs/','noun','카타르시스, 정화','Emotional release brought about by art, drama, or music.','Greek tragedy was designed to produce {catharsis} in the audience.','그리스 비극은 관객에게 카타르시스를 일으키도록 설계됐어요.','catharsis','C1','culture',2,'catharsis theater audience emotion dramatic'),
('w_culture_C1_10','sublime','/səˈblaɪm/','adjective','숭고한, 장엄한','Of great beauty or awe that inspires moral elevation.','Turner''s seascapes evoke the {sublime} in nature.','터너의 해양화는 자연의 숭고함을 불러일으켜요.','sublime','C1','culture',2,'sublime landscape nature dramatic storm painting'),
('w_culture_C1_11','aestheticism','/esˈθetɪsɪzəm/','noun','유미주의','A 19th-century doctrine that art exists for its own sake.','Wilde embodied the spirit of {aestheticism}.','와일드는 유미주의의 정신을 구현했어요.','aestheticism','C1','culture',3,'oscar wilde aestheticism art beauty 19th century'),
('w_culture_C1_12','hyperrealism','/ˌhaɪpərˈriːəlɪzəm/','noun','극사실주의','An art movement producing images that appear more real than photographs.','His paintings belong to the tradition of {hyperrealism}.','그의 그림은 극사실주의 전통에 속해요.','hyperrealism','C1','culture',2,'hyperrealism painting photorealistic art detail'),
('w_culture_C1_13','zeitgeist','/ˈzaɪtɡaɪst/','noun','시대정신','The defining spirit or mood of a particular period.','The artist''s work captured the {zeitgeist} of the 1980s.','그 예술가의 작품은 1980년대의 시대정신을 포착했어요.','zeitgeist','C1','culture',2,'zeitgeist 80s culture art era spirit'),
('w_culture_C1_14','discourse','/ˈdɪskɔːrs/','noun','담론, 논의','A formal discussion or debate about a subject.','Critical {discourse} around the film was polarised.','그 영화를 둘러싼 비평적 담론은 양극화됐어요.','discourse','C1','culture',2,'academic discourse lecture panel discussion'),
('w_culture_C1_15','polyphony','/pəˈlɪfəni/','noun','폴리포니, 다성 음악','Music with several independent melody lines played at once.','Bach''s fugues demonstrate extraordinary {polyphony}.','바흐의 푸가는 놀라운 다성 음악을 보여줘요.','polyphony','C1','culture',2,'polyphony bach fugue classical music'),
('w_culture_C1_16','vernacular','/vərˈnækjʊlər/','noun','토착어, 일상 언어','The language or style used by ordinary people.','The poem was written in the {vernacular} of the working class.','그 시는 노동 계급의 일상 언어로 쓰였어요.','vernacular','C1','culture',2,'vernacular language poetry common people'),
('w_culture_C1_17','allegory','/ˈæləɡɔːri/','noun','우화, 알레고리','A story or artwork with a hidden symbolic meaning.','Orwell''s Animal Farm is a political {allegory}.','오웰의 동물 농장은 정치적 우화예요.','allegory','C1','culture',2,'allegory orwell animals painting symbolic'),
('w_culture_C1_18','trope','/troʊp/','noun','비유, 진부한 관용구','A figure of speech or an overused theme.','The "chosen one" is a common {trope} in fantasy literature.','선택받은 자는 판타지 문학에서 흔한 비유예요.','trope','C1','culture',2,'trope fantasy literature cliche narrative'),
('w_culture_C1_19','canonicity','/ˌkænəˈnɪsɪti/','noun','정전성','The state of being accepted as part of the literary or artistic canon.','Questions of {canonicity} often reflect cultural biases.','정전성 문제는 종종 문화적 편견을 반영해요.','canonicity','C1','culture',3,'canon literature books academic selection'),
('w_culture_C1_20','ekphrasis','/ekˈfreɪsɪs/','noun','에크프라시스','A literary description of a work of visual art.','Keats'' poem is a famous example of {ekphrasis}.','키츠의 시는 에크프라시스의 유명한 예시예요.','ekphrasis','C1','culture',3,'keats poem urn art description literary'),
('w_culture_C1_21','pathos','/ˈpeɪθɒs/','noun','파토스, 비애감','A quality that evokes pity or sadness in a work of art.','The final scene was full of {pathos}.','마지막 장면은 파토스로 가득 찼어요.','pathos','C1','culture',2,'theater drama final scene emotion tears'),
('w_culture_C1_22','ethos','/ˈiːθɒs/','noun','에토스, 특성, 정신','The characteristic spirit or values of a community or work.','The {ethos} of the Bauhaus was form follows function.','바우하우스의 에토스는 형태는 기능을 따른다는 것이었어요.','ethos','C1','culture',2,'bauhaus design ethos modernism school'),
('w_culture_C1_23','logos','/ˈloʊɡɒs/','noun','로고스, 논리적 호소','Rational appeal in persuasion; logical argument.','The documentary builds its case through {logos}.','그 다큐멘터리는 논리적 호소를 통해 주장을 구성해요.','logos','C1','culture',3,'documentary logic argument persuasion analysis'),
('w_culture_C1_24','liminal','/ˈlɪmɪnəl/','adjective','경계적인, 과도기적인','Relating to a transitional stage or threshold.','The painting depicts a {liminal} space between day and night.','그 그림은 낮과 밤 사이의 경계적 공간을 묘사해요.','liminal','C1','culture',3,'liminal space dusk twilight threshold painting'),
('w_culture_C1_25','polemic','/pəˈlemɪk/','noun','논쟁적 글, 논쟁','A strong verbal or written attack on someone''s opinions.','His essay reads as a {polemic} against commercialism in art.','그의 에세이는 예술의 상업주의에 대한 논쟁적 글로 읽혀요.','polemic','C1','culture',3,'debate essay critique art criticism writing'),
('w_culture_C1_26','meta-narrative','/ˈmetə ˈnærətɪv/','noun','메타 내러티브','An overarching story that gives structure to a culture.','Postmodernism questions grand {meta-narrative}s.','포스트모더니즘은 거대한 메타 내러티브에 의문을 제기해요.','meta-narrative','C1','culture',2,'postmodern narrative theory books academic'),
('w_culture_C1_27','synaesthesia','/ˌsɪnɪsˈθiːziə/','noun','공감각','A condition in which one sense is stimulated and another is also experienced.','His {synaesthesia} made music visible as colour.','그의 공감각은 음악을 색깔로 볼 수 있게 했어요.','synaesthesia','C1','culture',3,'synaesthesia colour sound music art brain'),
('w_culture_C1_28','appropriation','/əˌproʊpriˈeɪʃən/','noun','전용, 차용','Taking elements from existing works and using them in new art.','Pop art relied heavily on cultural {appropriation}.','팝 아트는 문화적 전용에 크게 의존했어요.','appropriation','C1','culture',2,'appropriation pop art warhol culture remix'),
('w_culture_C1_29','hegemony','/hɪˈdʒeməni/','noun','헤게모니, 문화적 지배','Dominance of one cultural or social group over others.','Western {hegemony} has shaped global art institutions.','서구 헤게모니는 글로벌 예술 기관을 형성해왔어요.','hegemony','C1','culture',2,'hegemony power culture western global art'),
('w_culture_C1_30','plurality','/plʊˈrælɪti/','noun','다원성, 복수성','The state of being numerous or diverse.','Contemporary curating celebrates cultural {plurality}.','현대 큐레이팅은 문화적 다원성을 기념해요.','plurality','C1','culture',2,'diversity plural cultures museum exhibition'),
('w_culture_C1_31','contingency','/kənˈtɪndʒənsi/','noun','우연성, 상황 의존성','The quality of being dependent on uncertain conditions.','The meaning of art is marked by {contingency}.','예술의 의미는 우연성으로 특징지어져요.','contingency','C1','culture',3,'chance contingency art philosophy abstract'),
('w_culture_C1_32','reflexivity','/ˌriːflekˈsɪvɪti/','noun','반성성, 자기 인식','The quality of examining one''s own assumptions.','Documentary filmmaking requires a degree of {reflexivity}.','다큐멘터리 제작은 어느 정도의 반성성을 요구해요.','reflexivity','C1','culture',3,'reflexivity documentary filmmaker camera self'),
('w_culture_C1_33','transmedial','/trænsˈmiːdiəl/','adjective','트랜스미디어의','Relating to a narrative that extends across multiple media.','The franchise is a {transmedial} storytelling project.','그 프랜차이즈는 트랜스미디어 스토리텔링 프로젝트예요.','transmedial','C1','culture',3,'transmedia storytelling franchise media narrative'),
('w_culture_C1_34','diegesis','/ˌdaɪˈdʒiːsɪs/','noun','디에게시스, 이야기 세계','The world of the story as opposed to the real world.','The narrator exists outside the {diegesis} of the film.','나레이터는 영화의 이야기 세계 밖에 존재해요.','diegesis','C1','culture',3,'film narrator story world theory'),
('w_culture_C1_35','bricoleur','/ˌbrɪkəˈlɜːr/','noun','브리콜뢰르 (창의적 조합가)','Someone who creates something from diverse materials at hand.','The artist sees herself as a cultural {bricoleur}.','그 예술가는 자신을 문화적 브리콜뢰르로 봐요.','bricoleur','C1','culture',3,'bricolage artist found objects creative assemblage')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- C2 — 예술철학·포스트구조주의 단어 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_culture_C2_01','ontology','/ɒnˈtɒlədʒi/','noun','존재론','The branch of philosophy dealing with the nature of being.','The {ontology} of the artwork is contested by critics.','작품의 존재론은 비평가들 사이에서 논쟁 중이에요.','ontology','C2','culture',3,'ontology philosophy being existence academic'),
('w_culture_C2_02','episteme','/ˈepɪstiːm/','noun','에피스테메, 지식 체계','A system of understanding that defines what counts as knowledge in an era.','Foucault''s concept of {episteme} transformed cultural theory.','푸코의 에피스테메 개념은 문화 이론을 변화시켰어요.','episteme','C2','culture',3,'foucault episteme knowledge structure theory'),
('w_culture_C2_03','heteroglossia','/ˌhetərəˈɡlɒsiə/','noun','헤테로글로시아, 다성성','The coexistence of multiple voices and languages in a text.','Bakhtin''s notion of {heteroglossia} celebrates linguistic diversity.','바흐친의 헤테로글로시아 개념은 언어적 다양성을 기념해요.','heteroglossia','C2','culture',3,'bakhtin language diversity voices text theory'),
('w_culture_C2_04','aporia','/əˈpɔːriə/','noun','아포리아, 논리적 교착','An irresolvable contradiction or logical impasse in a text or argument.','The text exposes an {aporia} at the heart of Western humanism.','그 텍스트는 서구 인문주의의 핵심에 있는 아포리아를 드러내요.','aporia','C2','culture',3,'aporia derrida philosophy contradiction text'),
('w_culture_C2_05','palimpsest','/ˈpælɪmpsest/','noun','팔림프세스트, 흔적의 중첩','A manuscript on which old writing has been overwritten; a place marked by history.','The city functions as a cultural {palimpsest}.','도시는 문화적 팔림프세스트로 기능해요.','palimpsest','C2','culture',3,'palimpsest history layers city manuscript'),
('w_culture_C2_06','bricolage','/ˈbrɪkəlɑːʒ/','noun','브리콜라주, 혼합적 창작','Construction or creation from diverse elements already available.','Her film is a {bricolage} of archive footage and personal memoir.','그녀의 영화는 아카이브 영상과 개인 회고록의 브리콜라주예요.','bricolage','C2','culture',3,'bricolage film collage archive mixed media art'),
('w_culture_C2_07','logocentrism','/ˌloʊɡoʊˈsentrɪzəm/','noun','로고중심주의','The tendency in Western thought to privilege speech and reason over writing.','Derrida''s critique targets {logocentrism} in philosophy.','데리다의 비판은 철학의 로고중심주의를 겨냥해요.','logocentrism','C2','culture',3,'derrida logocentrism philosophy text western'),
('w_culture_C2_08','differance','/ˌdɪfəˈrɑːns/','noun','디페랑스 (데리다 개념)','Derrida''s term for the way meaning is endlessly deferred in language.','The concept of {differance} resists fixed meaning.','디페랑스 개념은 고정된 의미에 저항해요.','differance','C2','culture',3,'derrida differance language meaning philosophy'),
('w_culture_C2_09','rhizome','/ˈraɪzoʊm/','noun','리좀 (들뢰즈 개념)','Deleuze and Guattari''s model of culture as non-hierarchical and interconnected.','Their theory proposes a {rhizome} model of knowledge.','그들의 이론은 지식의 리좀 모델을 제안해요.','rhizome','C2','culture',3,'rhizome deleuze network diagram philosophy'),
('w_culture_C2_10','hypertext','/ˈhaɪpərtekst/','noun','하이퍼텍스트','Text with embedded links connecting to other texts or resources.','{Hypertext} has transformed how we read and write.','하이퍼텍스트는 우리가 읽고 쓰는 방식을 변화시켰어요.','hypertext','C2','culture',2,'hypertext internet links digital reading'),
('w_culture_C2_11','simulacrum','/ˌsɪmjʊˈleɪkrəm/','noun','시뮬라크르 (보드리야르)','A copy of something that no longer has an original.','Baudrillard argues that media creates a world of pure {simulacrum}.','보드리야르는 미디어가 순수한 시뮬라크르의 세계를 만든다고 주장해요.','simulacrum','C2','culture',3,'baudrillard simulacrum media image reality'),
('w_culture_C2_12','subaltern','/ˈsʌbəltərn/','noun','하위주체','A person or group with no significant social power.','Spivak asks whether the {subaltern} can speak.','스피박은 하위주체가 말할 수 있는가를 물어요.','subaltern','C2','culture',3,'spivak subaltern postcolonial theory marginalized'),
('w_culture_C2_13','genealogy','/ˌdʒiːniˈælədʒi/','noun','계보학 (푸코)','Foucault''s method of tracing the historical development of discourses.','His {genealogy} of modern art traced its origins to enlightenment ideals.','그의 현대 미술 계보학은 그 기원을 계몽주의 이상으로 추적했어요.','genealogy','C2','culture',3,'genealogy foucault history discourse analysis'),
('w_culture_C2_14','hauntology','/hɔːnˈtɒlədʒi/','noun','유령론','Derrida''s concept of cultures haunted by the past.','Fisher applied {hauntology} to describe contemporary pop music.','피셔는 유령론을 현대 팝 음악을 묘사하는 데 적용했어요.','hauntology','C2','culture',3,'hauntology ghost past culture music derrida'),
('w_culture_C2_15','jouissance','/ʒuˈiːsɒns/','noun','쥬이상스 (라캉), 향유','Intense pleasure or enjoyment beyond the pleasure principle.','Lacan''s concept of {jouissance} influenced film theory greatly.','라캉의 쥬이상스 개념은 영화 이론에 큰 영향을 미쳤어요.','jouissance','C2','culture',3,'lacan jouissance film theory psychoanalysis'),
('w_culture_C2_16','abject','/ˈæbdʒekt/','adjective','비체의, 혐오감을 주는','Relating to Kristeva''s concept of what society rejects to define itself.','Horror films exploit the {abject} to disturb the viewer.','공포 영화는 관객을 불안하게 하기 위해 비체를 활용해요.','abject','C2','culture',3,'horror film uncanny abject theory kristeva'),
('w_culture_C2_17','heterotopia','/ˌhetərəˈtoʊpiə/','noun','헤테로토피아 (푸코)','A space that exists outside normal social order, yet mirrors it.','Foucault described the museum as a {heterotopia}.','푸코는 박물관을 헤테로토피아로 묘사했어요.','heterotopia','C2','culture',3,'foucault museum heterotopia space gallery'),
('w_culture_C2_18','deterritorialisation','/diːˌterɪˌtɔːriəlaɪˈzeɪʃən/','noun','탈영토화','Deleuze''s term for the dissolution of fixed cultural identities.','Globalisation is seen as a process of cultural {deterritorialisation}.','세계화는 문화적 탈영토화 과정으로 여겨져요.','deterritorialisation','C2','culture',3,'globalisation culture flux identity deleuze'),
('w_culture_C2_19','intersubjectivity','/ˌɪntəˌsʌbdʒekˈtɪvɪti/','noun','상호주관성','Shared understanding between subjects; the basis of communication.','Art''s meaning depends on {intersubjectivity} between viewer and work.','예술의 의미는 관람객과 작품 사이의 상호주관성에 달려 있어요.','intersubjectivity','C2','culture',3,'art viewer interaction gallery shared meaning'),
('w_culture_C2_20','paratext','/ˈpærətekst/','noun','주변텍스트 (제네트)','Elements surrounding a text, such as titles, prefaces, and covers.','Genette showed how the {paratext} frames the reader''s experience.','제네트는 주변텍스트가 독자의 경험을 어떻게 틀 짓는지 보여줬어요.','paratext','C2','culture',3,'book cover title preface paratext genette'),
('w_culture_C2_21','defamiliarisation','/diːfəˌmɪliəraɪˈzeɪʃən/','noun','낯설게하기','The artistic technique of presenting familiar objects as strange.','Shklovsky''s theory of {defamiliarisation} underpins formalist criticism.','슈클로프스키의 낯설게하기 이론은 형식주의 비평을 뒷받침해요.','defamiliarisation','C2','culture',3,'defamiliarisation art strange familiar formalism'),
('w_culture_C2_22','interpellation','/ɪnˌtɜːrpəˈleɪʃən/','noun','호명 (알튀세르)','Althusser''s concept of how ideology addresses individuals as subjects.','Advertising relies on {interpellation} to create loyal consumers.','광고는 충성스러운 소비자를 만들기 위해 호명에 의존해요.','interpellation','C2','culture',3,'althusser ideology advertising subject theory'),
('w_culture_C2_23','spectatorship','/ˈspektətərʃɪp/','noun','관람 행위, 관객성','The activity and theory of watching or viewing art or film.','Feminist film theory transformed debates on {spectatorship}.','페미니스트 영화 이론은 관객성 논쟁을 변화시켰어요.','spectatorship','C2','culture',3,'film spectatorship audience gaze feminist theory'),
('w_culture_C2_24','chronotope','/ˈkrɒnətoʊp/','noun','크로노토프 (바흐친)','Bakhtin''s term for the intrinsic connection of time and space in literature.','The road novel relies on a specific {chronotope}.','도로 소설은 특정 크로노토프에 의존해요.','chronotope','C2','culture',3,'bakhtin chronotope time space novel theory'),
('w_culture_C2_25','acousmatic','/ˌækʊzˈmætɪk/','adjective','아쿠스마틱의, 음원이 보이지 않는','Relating to sound heard without a visible source.','Schaeffer pioneered {acousmatic} music in the 1940s.','쉐페르는 1940년대에 아쿠스마틱 음악을 개척했어요.','acousmatic','C2','culture',3,'acousmatic sound music abstract speaker experimental'),
('w_culture_C2_26','clinamen','/klɪˈneɪmən/','noun','클리나멘 (창조적 일탈)','Harold Bloom''s term for a poet''s swerve away from a precursor.','Bloom sees originality as {clinamen} from the tradition.','블룸은 독창성을 전통으로부터의 클리나멘으로 봐요.','clinamen','C2','culture',3,'bloom poetry influence originality tradition'),
('w_culture_C2_27','pharmakon','/ˈfɑːrmækɒn/','noun','파르마콘 (데리다)','Derrida''s term for something that is simultaneously poison and remedy.','Writing is a {pharmakon}: both aid and threat to memory.','글쓰기는 파르마콘이에요: 기억에 대한 도움이자 위협이에요.','pharmakon','C2','culture',3,'derrida pharmakon writing memory poison remedy'),
('w_culture_C2_28','polysemy','/pəˈlɪsɪmi/','noun','다의성','The quality of having multiple meanings.','The poem''s {polysemy} invites many different readings.','그 시의 다의성은 다양한 해석을 초대해요.','polysemy','C2','culture',3,'polysemy language meaning ambiguity literary'),
('w_culture_C2_29','ekphrastic','/ekˈfræstɪk/','adjective','에크프라시스적인','Relating to a literary description of a work of visual art.','Keats'' ode is one of the great {ekphrastic} poems.','키츠의 송시는 위대한 에크프라시스 시 중 하나예요.','ekphrastic','C2','culture',3,'keats ode poem art description literary ekphrasis'),
('w_culture_C2_30','xenoglossy','/ˌziːnəˈɡlɒsi/','noun','이국어 사용 현상','The apparent ability to speak an unknown language.','The novel plays with the idea of cultural {xenoglossy}.','그 소설은 문화적 이국어 사용의 아이디어를 가지고 놀아요.','xenoglossy','C2','culture',3,'language unknown foreign speaking mystical'),
('w_culture_C2_31','praxis','/ˈprækˈsɪs/','noun','실천, 실천적 활동','Practice as opposed to theory; the application of theory to action.','For Brecht, theatre was always a form of political {praxis}.','브레히트에게 연극은 항상 정치적 실천의 형태였어요.','praxis','C2','culture',3,'brecht theater praxis practice theory political'),
('w_culture_C2_32','hybridity','/haɪˈbrɪdɪti/','noun','혼종성 (호미 바바)','Homi Bhabha''s concept of identity formed between cultures.','Postcolonial art celebrates {hybridity} as creative strength.','포스트식민주의 예술은 혼종성을 창조적 강점으로 기념해요.','hybridity','C2','culture',3,'bhabha hybridity postcolonial culture identity'),
('w_culture_C2_33','enunciation','/ɪˌnʌnsiˈeɪʃən/','noun','발화, 언표 행위','The act of stating or articulating something; in semiotics, the act of producing a sign.','The film''s mode of {enunciation} implicates the viewer.','그 영화의 발화 방식은 관람객을 연루시켜요.','enunciation','C2','culture',3,'semiotics film enunciation viewer speech act'),
('w_culture_C2_34','apophenia','/ˌæpəˈfiːniə/','noun','아포페니아, 임의 연결 지각','The tendency to perceive meaningful connections between unrelated things.','Conspiracy theories exploit our tendency toward {apophenia}.','음모론은 아포페니아를 향한 우리의 경향을 이용해요.','apophenia','C2','culture',3,'pattern recognition connection conspiracy theory mind'),
('w_culture_C2_35','thanatopolitics','/ˌθænətəˈpɒlɪtɪks/','noun','죽음 정치학 (아감벤)','Agamben''s concept of power exercised through the management of death.','{Thanatopolitics} shapes whose lives and deaths are mourned in culture.','죽음 정치학은 문화에서 누구의 삶과 죽음이 애도되는지를 형성해요.','thanatopolitics','C2','culture',3,'agamben politics death power culture mourning')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- A1 — 패턴 (취향 묻기) 7개
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_culture_A1_01','What kind of music do you like?','어떤 음악 좋아해요?','What kind of','What kind of...?는 종류나 취향을 물을 때 쓰는 기본 패턴이에요.','취향 묻기','A1','culture','pattern',NULL,1),
('s_culture_A1_02','Do you like movies or books more?','영화를 더 좋아해요, 아니면 책을 더 좋아해요?','Do you like ... more?','"Do you like A or B more?"는 둘 중 하나를 고르게 할 때 쓰는 간단한 패턴이에요.','취향 비교','A1','culture','pattern',NULL,2),
('s_culture_A1_03','What is your favourite song?','가장 좋아하는 노래가 뭐예요?','What is your favourite','What is your favourite...?는 영어로 취향을 가장 자연스럽게 묻는 방법이에요.','좋아하는 것 묻기','A1','culture','pattern',NULL,3),
('s_culture_A1_04','I love listening to music.','저는 음악 듣는 걸 좋아해요.','I love listening to','"I love -ing"는 자신이 좋아하는 활동을 말할 때 쓰는 패턴이에요.','취향 말하기','A1','culture','pattern',NULL,4),
('s_culture_A1_05','Can you dance?','춤출 수 있어요?','Can you','Can you...?는 상대방의 능력을 물어볼 때 가장 기본적인 패턴이에요.','능력 묻기','A1','culture','pattern',NULL,5),
('s_culture_A1_06','Do you play any instruments?','악기를 연주할 수 있어요?','Do you play','Do you play any...?는 취미나 특기를 물어볼 때 유용한 패턴이에요.','취미 묻기','A1','culture','pattern',NULL,6),
('s_culture_A1_07','I enjoy watching shows at the theatre.','저는 극장에서 공연 보는 것을 즐겨요.','I enjoy watching','"I enjoy -ing"는 자신의 즐거운 활동을 부드럽게 표현하는 패턴이에요.','취미 표현','A1','culture','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- A2 — 패턴 (공연·전시) 7개
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_culture_A2_01','Have you ever been to a music festival?','음악 축제에 가본 적 있어요?','Have you ever been to','Have you ever...?는 경험을 자연스럽게 물어볼 때 자주 쓰는 패턴이에요.','경험 묻기','A2','culture','pattern',NULL,1),
('s_culture_A2_02','What time does the concert start?','콘서트가 몇 시에 시작해요?','What time does','What time does...?는 시작 시간을 물을 때 기본적으로 쓰는 패턴이에요.','공연 정보 묻기','A2','culture','pattern',NULL,2),
('s_culture_A2_03','Is there a ticket office nearby?','근처에 매표소가 있나요?','Is there a','Is there a...?는 어떤 장소나 시설이 있는지 물을 때 쓰는 패턴이에요.','장소 묻기','A2','culture','pattern',NULL,3),
('s_culture_A2_04','I''d like two tickets for the evening show, please.','저녁 공연 티켓 두 장 주세요.','I''d like','I''d like...는 무언가를 정중하게 요청할 때 쓰는 가장 흔한 패턴이에요.','티켓 구매','A2','culture','pattern',NULL,4),
('s_culture_A2_05','The exhibition was really impressive.','전시회가 정말 인상적이었어요.','was really impressive','was/were really impressive는 무언가에 강한 긍정 반응을 나타낼 때 쓰는 패턴이에요.','공연 후기','A2','culture','pattern',NULL,5),
('s_culture_A2_06','Can I take photos inside the gallery?','갤러리 안에서 사진을 찍어도 될까요?','Can I take photos','Can I...?는 허락을 구할 때 쓰는 가장 기본적인 패턴이에요.','허락 구하기','A2','culture','pattern',NULL,6),
('s_culture_A2_07','How long does the performance last?','공연이 얼마나 걸려요?','How long does','How long does...?는 어떤 일이 얼마나 오래 걸리는지 물을 때 쓰는 패턴이에요.','시간 묻기','A2','culture','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- B1 — 패턴 (예술 감상) 7개
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_culture_B1_01','What I find most interesting about this painting is the use of colour.','이 그림에서 가장 흥미로운 점은 색채 사용 방식이에요.','What I find most interesting','"What I find most interesting is..."는 자신의 감상을 구체적으로 표현할 때 쓰는 세련된 패턴이에요.','예술 감상 표현','B1','culture','pattern',NULL,1),
('s_culture_B1_02','This piece really speaks to me on an emotional level.','이 작품은 감정적으로 정말 제 마음에 와닿아요.','really speaks to me','"speaks to me"는 예술 작품이 자신에게 감동이나 공명을 줄 때 원어민이 자주 쓰는 표현이에요.','예술 공감 표현','B1','culture','pattern',NULL,2),
('s_culture_B1_03','I wasn''t sure what to make of it at first, but it grew on me.','처음엔 어떻게 받아들여야 할지 몰랐지만, 점점 좋아졌어요.','grew on me','"grow on me"는 처음에는 마음에 들지 않다가 나중에 좋아지게 됐을 때 쓰는 표현이에요.','감상 변화 표현','B1','culture','pattern',NULL,3),
('s_culture_B1_04','There''s something deeply moving about the way the story unfolds.','이야기가 전개되는 방식에는 깊이 감동적인 무언가가 있어요.','There''s something ... about','"There''s something ... about"는 추상적이고 감동적인 인상을 표현할 때 쓰는 고급 패턴이에요.','작품 인상 표현','B1','culture','pattern',NULL,4),
('s_culture_B1_05','Have you had a chance to see the new exhibition at the gallery?','갤러리에서 새로운 전시회를 볼 기회가 있으셨어요?','Have you had a chance to','"Have you had a chance to...?"는 상대방의 경험을 자연스럽게 물어보는 패턴이에요.','경험 묻기 (공손)','B1','culture','pattern',NULL,5),
('s_culture_B1_06','The atmosphere in the concert hall was absolutely electric.','콘서트홀의 분위기가 완전히 전율적이었어요.','absolutely electric','absolutely + 강한 형용사는 감동적인 순간을 생생하게 전달하는 B1 표현 패턴이에요.','공연 분위기 표현','B1','culture','pattern',NULL,6),
('s_culture_B1_07','I''d strongly recommend this exhibition to anyone interested in modern art.','현대 미술에 관심 있는 분이라면 이 전시회를 강력히 추천해요.','I''d strongly recommend ... to anyone','"I''d strongly recommend ... to anyone interested in..."은 적극적인 추천을 표현하는 패턴이에요.','추천 표현','B1','culture','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- B2 — 패턴 (문화 비교) 7개
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_culture_B2_01','While Korean pop culture has a global reach, traditional art forms still hold a central place in national identity.','한국 팝 문화가 세계적으로 확산됐지만, 전통 예술 형태는 여전히 국가 정체성에서 중심적인 위치를 차지해요.','While ... still hold','While A, B still...는 두 가지 사실을 대조할 때 쓰는 B2 수준의 접속 패턴이에요.','문화 비교','B2','culture','pattern',NULL,1),
('s_culture_B2_02','There''s a growing tension between preserving cultural heritage and embracing contemporary influences.','문화유산을 보존하는 것과 현대적 영향을 받아들이는 것 사이의 긴장이 커지고 있어요.','tension between ... and','"tension between A and B"는 두 가지 상충하는 가치를 논의할 때 쓰는 고급 표현이에요.','문화 긴장 표현','B2','culture','pattern',NULL,2),
('s_culture_B2_03','The way a culture treats its artists says a lot about its values.','한 문화가 예술가를 대하는 방식은 그 문화의 가치관에 대해 많은 것을 말해줘요.','says a lot about','"says a lot about..."는 어떤 행동이나 상황이 더 깊은 의미를 드러낸다고 할 때 쓰는 표현이에요.','문화 가치관 논의','B2','culture','pattern',NULL,3),
('s_culture_B2_04','Cross-cultural exchange has always been central to artistic innovation.','문화 간 교류는 항상 예술적 혁신의 핵심이었어요.','Cross-cultural exchange has always been','Cross-cultural ... has always been...는 역사적 패턴을 논의할 때 쓰는 학문적 표현이에요.','문화 교류 논의','B2','culture','pattern',NULL,4),
('s_culture_B2_05','What sets this work apart is its willingness to challenge conventional expectations.','이 작품을 돋보이게 하는 것은 기존의 기대에 도전하려는 의지예요.','What sets this work apart','"What sets ... apart is..."는 무언가를 차별화하는 특징을 강조하는 세련된 패턴이에요.','작품 차별점 표현','B2','culture','pattern',NULL,5),
('s_culture_B2_06','It''s worth noting that the artist''s background heavily shaped the work''s cultural references.','예술가의 배경이 작품의 문화적 참조에 크게 영향을 미쳤다는 점은 주목할 만해요.','It''s worth noting that','"It''s worth noting that..."는 중요한 사실을 강조하며 논의에 도입할 때 쓰는 학술적 패턴이에요.','분석적 논의','B2','culture','pattern',NULL,6),
('s_culture_B2_07','The debate over cultural appropriation raises uncomfortable but necessary questions.','문화 전용에 관한 논쟁은 불편하지만 필요한 질문들을 제기해요.','raises uncomfortable but necessary questions','"raises ... questions"는 논쟁적 주제를 신중하게 도입할 때 쓰는 표현이에요.','문화 논쟁 표현','B2','culture','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- C1 — 패턴 (예술 비평 심화) 7개
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_culture_C1_01','The work''s power lies precisely in its refusal to offer easy resolution.','이 작품의 힘은 바로 쉬운 해결을 거부하는 데 있어요.','lies precisely in its refusal to','"lies precisely in its refusal to..."는 작품의 핵심 특질을 정확히 짚을 때 쓰는 고급 비평 표현이에요.','예술 비평','C1','culture','pattern',NULL,1),
('s_culture_C1_02','One might argue that the narrative structure mirrors the fragmented nature of modern consciousness.','서사 구조가 현대 의식의 파편화된 본성을 반영한다고 주장할 수 있어요.','One might argue that ... mirrors','"One might argue that..."는 비평적 주장을 신중하게 제시할 때 쓰는 학술적 표현이에요.','예술 비평 논의','C1','culture','pattern',NULL,2),
('s_culture_C1_03','The tension between form and content is never fully resolved in this piece.','이 작품에서 형식과 내용 사이의 긴장은 결코 완전히 해결되지 않아요.','tension between form and content is never fully resolved','"tension between ... is never fully resolved"는 예술 분석에서 양가성을 표현하는 고급 패턴이에요.','예술 분석','C1','culture','pattern',NULL,3),
('s_culture_C1_04','Rather than offering answers, the exhibition poses a series of provocative questions about identity.','답을 제시하기보다는 전시회가 정체성에 대한 일련의 도발적인 질문을 제기해요.','Rather than ... poses a series of provocative questions','"Rather than A, B poses questions about..."는 반전 구조로 작품의 의도를 설명하는 패턴이에요.','전시 분석','C1','culture','pattern',NULL,4),
('s_culture_C1_05','What distinguishes this director''s work is the interplay between the personal and the political.','이 감독의 작품을 구별하는 것은 개인적인 것과 정치적인 것 사이의 상호작용이에요.','What distinguishes ... is the interplay between','"What distinguishes ... is the interplay between A and B"는 비평적 특징 분석의 정교한 패턴이에요.','감독 분석','C1','culture','pattern',NULL,5),
('s_culture_C1_06','The film operates on multiple registers simultaneously — aesthetic, political, and psychological.','그 영화는 미학적, 정치적, 심리적으로 여러 차원에서 동시에 작동해요.','operates on multiple registers simultaneously','"operates on multiple registers"는 복잡한 예술 작품의 다층적 의미를 표현하는 C1 비평 표현이에요.','영화 비평','C1','culture','pattern',NULL,6),
('s_culture_C1_07','By foregrounding the constructedness of its own narrative, the novel invites us to question the nature of storytelling itself.','자신의 서사가 구성물임을 전면에 내세움으로써, 그 소설은 우리가 스토리텔링의 본질 자체를 의문시하도록 유도해요.','By foregrounding the constructedness of','"By foregrounding the constructedness of..."는 메타픽션적 기법을 분석하는 고급 비평 패턴이에요.','소설 비평','C1','culture','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- C2 — 패턴 (예술 철학·담론) 7개
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_culture_C2_01','The work enacts a deconstruction of the very categories it appears to celebrate.','그 작품은 자신이 기리는 것처럼 보이는 바로 그 범주들을 해체하는 것을 수행해요.','enacts a deconstruction of the very categories','"enacts a deconstruction of the very..."는 데리다적 독해를 수행할 때 쓰는 C2 수준의 비평 표현이에요.','해체주의 비평','C2','culture','pattern',NULL,1),
('s_culture_C2_02','To speak of aesthetic autonomy is already to invoke a historically contingent set of assumptions.','미학적 자율성을 말하는 것은 이미 역사적으로 우연적인 일련의 가정들을 불러오는 것이에요.','To speak of ... is already to invoke','"To speak of ... is already to invoke..."는 개념의 역사성을 드러내는 고도로 학술적인 패턴이에요.','미학 담론','C2','culture','pattern',NULL,2),
('s_culture_C2_03','The question is not whether the text has a meaning, but who has the authority to determine it.','문제는 텍스트가 의미를 가지느냐가 아니라 누가 그것을 결정할 권위를 갖느냐예요.','The question is not whether ... but who has the authority','"The question is not whether A but who..."는 권력과 해석에 관한 담론을 수행하는 C2 패턴이에요.','해석 권력 논의','C2','culture','pattern',NULL,3),
('s_culture_C2_04','Any attempt to stabilise the work''s meaning is already a political act.','작품의 의미를 안정화하려는 모든 시도는 이미 정치적 행위예요.','Any attempt to ... is already a political act','"Any attempt to... is already..."는 학술 비평에서 강한 주장을 펼칠 때 쓰는 C2 표현이에요.','정치적 비평','C2','culture','pattern',NULL,4),
('s_culture_C2_05','What the archive reveals is not just what was recorded but what was systematically excluded.','아카이브가 드러내는 것은 기록된 것뿐만 아니라 체계적으로 배제된 것이에요.','What the archive reveals is not just ... but what was systematically excluded','"What ... reveals is not just A but what was systematically excluded"는 권력과 기억을 분석하는 C2 패턴이에요.','아카이브 비평','C2','culture','pattern',NULL,5),
('s_culture_C2_06','The sublime, far from being a natural category, is a cultural construction that serves specific ideological ends.','숭고함은 자연적 범주이기는커녕 특정 이데올로기적 목적에 기여하는 문화적 구성물이에요.','far from being a natural category, is a cultural construction','far from being A, is a cultural construction that serves...는 개념을 역사화하는 고급 비평 패턴이에요.','숭고 이론 비평','C2','culture','pattern',NULL,6),
('s_culture_C2_07','In displacing the centre, the work opens up a rhizomatic field of possible meanings that resist hierarchical ordering.','중심을 이동시킴으로써, 그 작품은 위계적 정렬에 저항하는 의미의 리좀적 장을 열어요.','In displacing the centre ... opens up a rhizomatic field','"In displacing the centre, ... opens up a rhizomatic field"는 들뢰즈적 분석을 수행하는 최고 수준의 비평 패턴이에요.','리좀 비평','C2','culture','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;
