-- EngCat — Discussion (의견·토론) 단어 & 패턴
-- 210 words (A1~C2, 35 per level) + 42 patterns (7 per level)
-- topic_id = 'discussion'
-- Columns: words(id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword)
-- Columns: sentences(id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order)

-- ══════════════════════════════════════
-- WORDS — A1 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_A1_01','think','/θɪŋk/','verb','생각하다','To have an opinion or belief about something.','What do you {think} about this idea?','이 아이디어에 대해 어떻게 생각해요?','think','A1','discussion',1,'thinking person opinion discussion'),
('w_discussion_A1_02','say','/seɪ/','verb','말하다','To express something in words.','What did she {say} at the meeting?','그녀가 회의에서 뭐라고 했어요?','say','A1','discussion',1,'person speaking talking'),
('w_discussion_A1_03','agree','/əˈɡriː/','verb','동의하다','To have the same opinion as someone else.','I completely {agree} with you on that.','그 부분에서 완전히 동의해요.','agree','A1','discussion',1,'two people nodding agreement'),
('w_discussion_A1_04','want','/wɒnt/','verb','원하다','To have a desire or wish for something.','I {want} to share my opinion.','제 의견을 말하고 싶어요.','want','A1','discussion',1,'person raising hand speaking'),
('w_discussion_A1_05','know','/noʊ/','verb','알다','To be aware of or have information about something.','Do you {know} why they changed the plan?','왜 계획을 바꿨는지 알아요?','know','A1','discussion',1,'person thinking lightbulb'),
('w_discussion_A1_06','like','/laɪk/','verb','좋아하다; ~처럼','To find something enjoyable or to use as a comparison.','I {like} your idea very much.','당신의 아이디어가 정말 마음에 들어요.','like','A1','discussion',2,'person smiling thumbs up'),
('w_discussion_A1_07','maybe','/ˈmeɪbi/','adverb','아마도','Used to express possibility or uncertainty.','{Maybe} we should try a different approach.','아마도 다른 방법을 시도해야 할 것 같아요.','Maybe','A1','discussion',1,'person thinking maybe gesture'),
('w_discussion_A1_08','yes','/jes/','interjection','네, 맞아요','Used to give a positive answer or express agreement.','{Yes}, I think that is a great point.','네, 정말 좋은 의견이에요.','Yes','A1','discussion',1,'person nodding yes'),
('w_discussion_A1_09','no','/noʊ/','interjection','아니요','Used to give a negative answer or express disagreement.','{No}, I do not think that will work.','아니요, 그게 효과가 있을 것 같지 않아요.','No','A1','discussion',1,'person shaking head disagreeing'),
('w_discussion_A1_10','right','/raɪt/','adjective','맞는, 옳은','Correct or true; in agreement with what is expected.','That is {right}, we need to reconsider.','맞아요, 다시 생각해봐야 해요.','right','A1','discussion',1,'checkmark correct answer'),
('w_discussion_A1_11','good','/ɡʊd/','adjective','좋은','Of a high quality or standard; used to approve ideas.','That is a {good} point.','좋은 지적이에요.','good','A1','discussion',2,'thumbs up approval good'),
('w_discussion_A1_12','bad','/bæd/','adjective','나쁜','Of poor quality or a negative nature.','I think that is a {bad} idea.','그건 나쁜 생각 같아요.','bad','A1','discussion',2,'person disapproving frowning'),
('w_discussion_A1_13','talk','/tɔːk/','verb','이야기하다','To communicate by speaking.','Let us {talk} about this together.','이것에 대해 함께 이야기해요.','talk','A1','discussion',1,'two people talking conversation'),
('w_discussion_A1_14','help','/help/','verb','돕다','To make it easier for someone to do something.','Can you {help} me understand your view?','당신의 견해를 이해할 수 있게 도와줄 수 있나요?','help','A1','discussion',2,'person helping explain'),
('w_discussion_A1_15','look','/lʊk/','verb','보다; 생각되다','To direct your eyes at something; to seem or appear.','It {looks} like we have different ideas.','우리가 다른 생각을 가지고 있는 것 같아요.','looks','A1','discussion',2,'people looking discussing together'),
('w_discussion_A1_16','true','/truː/','adjective','사실인, 맞는','In accordance with fact or reality.','Is it {true} that they cancelled the event?','그들이 행사를 취소한 게 사실인가요?','true','A1','discussion',1,'fact truth document'),
('w_discussion_A1_17','question','/ˈkwestʃən/','noun','질문','A sentence or phrase used to find out information.','I have a {question} about your idea.','당신의 아이디어에 대해 질문이 있어요.','question','A1','discussion',1,'hand raised asking question'),
('w_discussion_A1_18','answer','/ˈɑːnsər/','noun','답변','A thing said, written, or done to deal with a question.','What is your {answer} to this problem?','이 문제에 대한 답이 뭐예요?','answer','A1','discussion',1,'person answering explaining'),
('w_discussion_A1_19','idea','/aɪˈdɪə/','noun','생각, 아이디어','A thought or suggestion about a possible course of action.','I have a new {idea} to share with everyone.','모두와 나눌 새로운 아이디어가 있어요.','idea','A1','discussion',1,'lightbulb new idea thinking'),
('w_discussion_A1_20','please','/pliːz/','adverb','제발, 부탁해요','Used to add politeness to a request.','{Please} tell me what you think.','어떻게 생각하시는지 말씀해 주세요.','Please','A1','discussion',2,'polite request gesture'),
('w_discussion_A1_21','sorry','/ˈsɒri/','adjective','미안한, 죄송한','Used to express regret or to introduce a different view.','I am {sorry}, but I disagree.','죄송하지만 동의하지 않아요.','sorry','A1','discussion',2,'person apologizing sorry'),
('w_discussion_A1_22','why','/waɪ/','adverb','왜','For what reason or purpose.','{Why} do you think that is the best option?','왜 그게 최선의 선택이라고 생각해요?','Why','A1','discussion',1,'person questioning curious why'),
('w_discussion_A1_23','how','/haʊ/','adverb','어떻게','In what way or manner.','{How} can we solve this problem together?','이 문제를 어떻게 함께 해결할 수 있을까요?','How','A1','discussion',1,'people problem solving together'),
('w_discussion_A1_24','what','/wɒt/','pronoun','무엇','Asking for information about something.','{What} do you think we should do?','우리가 어떻게 해야 한다고 생각해요?','What','A1','discussion',1,'person asking what question'),
('w_discussion_A1_25','this','/ðɪs/','determiner','이것','Used to refer to a specific thing nearby or just mentioned.','{This} is my opinion on the topic.','이게 그 주제에 대한 제 의견이에요.','This','A1','discussion',2,'person pointing presenting'),
('w_discussion_A1_26','more','/mɔːr/','adverb','더','To a greater extent or degree.','Can you tell me {more} about that?','그것에 대해 더 말해줄 수 있나요?','more','A1','discussion',2,'expanding idea more information'),
('w_discussion_A1_27','same','/seɪm/','adjective','같은','Identical; not different.','I feel the {same} way about it.','저도 그것에 대해 같은 생각이에요.','same','A1','discussion',1,'people sharing same opinion'),
('w_discussion_A1_28','different','/ˈdɪfrənt/','adjective','다른','Not the same; distinct.','We have {different} opinions on this.','우리는 이것에 대해 다른 의견을 가지고 있어요.','different','A1','discussion',1,'split opinion two sides'),
('w_discussion_A1_29','can','/kæn/','modal','할 수 있다','Expressing ability or possibility.','You {can} share your thoughts freely.','자유롭게 생각을 나눌 수 있어요.','can','A1','discussion',2,'open discussion free speech'),
('w_discussion_A1_30','let','/let/','verb','~하게 하다; 자 ~하자','To allow or suggest doing something together.','{Let} me explain what I mean.','제가 무슨 말인지 설명할게요.','Let','A1','discussion',2,'person explaining gesturing'),
('w_discussion_A1_31','ok','/ˌoʊˈkeɪ/','interjection','괜찮아요, 알겠어요','Used to express agreement or acceptance.','{OK}, I understand your point now.','알겠어요, 이제 당신의 요점을 이해해요.','OK','A1','discussion',2,'person nodding understanding ok'),
('w_discussion_A1_32','not','/nɒt/','adverb','아니','Used to make a word or phrase negative.','I do {not} agree with that idea.','그 생각에 동의하지 않아요.','not','A1','discussion',2,'person disagreeing negative'),
('w_discussion_A1_33','but','/bʌt/','conjunction','그런데, 하지만','Used to introduce a different or contrasting idea.','{But} there is another way to look at it.','하지만 다른 시각으로 볼 수도 있어요.','But','A1','discussion',1,'contrasting ideas two sides'),
('w_discussion_A1_34','because','/bɪˈkɒz/','conjunction','왜냐하면','For the reason that; used to give a reason.','{Because} I think it is more efficient.','왜냐하면 더 효율적이라고 생각하기 때문이에요.','Because','A1','discussion',1,'reason explanation arrow'),
('w_discussion_A1_35','so','/soʊ/','conjunction','그래서, 따라서','Therefore; with the result that.','{So}, what is our conclusion?','그래서 우리의 결론이 뭔가요?','So','A1','discussion',2,'conclusion summary decision')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — A2 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_A2_01','opinion','/əˈpɪnjən/','noun','의견, 견해','A view or judgment formed about something.','In my {opinion}, the plan needs more work.','제 의견으로는, 계획에 더 보완이 필요해요.','opinion','A2','discussion',1,'person sharing opinion speech bubble'),
('w_discussion_A2_02','suggest','/səˈdʒest/','verb','제안하다','To put forward an idea for consideration.','I would like to {suggest} a different approach.','다른 방법을 제안하고 싶어요.','suggest','A2','discussion',1,'person proposing idea whiteboard'),
('w_discussion_A2_03','believe','/bɪˈliːv/','verb','믿다, ~라고 생각하다','To accept that something is true or to hold an opinion.','I {believe} everyone should have a say.','모두가 발언권을 가져야 한다고 생각해요.','believe','A2','discussion',1,'person confident belief conviction'),
('w_discussion_A2_04','understand','/ˌʌndəˈstænd/','verb','이해하다','To know the meaning or reason for something.','I {understand} your concern, but I disagree.','당신의 우려를 이해하지만, 동의하지는 않아요.','understand','A2','discussion',1,'lightbulb comprehension understanding'),
('w_discussion_A2_05','disagree','/ˌdɪsəˈɡriː/','verb','동의하지 않다','To have a different opinion from someone else.','I have to {disagree} with that statement.','그 주장에는 동의하기 어려워요.','disagree','A2','discussion',1,'two people differing opinions'),
('w_discussion_A2_06','discuss','/dɪˈskʌs/','verb','토론하다, 논의하다','To talk about a topic, considering different opinions.','Let us {discuss} the pros and cons.','장단점에 대해 논의해 봐요.','discuss','A2','discussion',1,'group discussion meeting table'),
('w_discussion_A2_07','point','/pɔɪnt/','noun','요점, 핵심','The main idea or most important aspect of something.','You make a good {point} about the budget.','예산에 관해 좋은 지적을 해주셨어요.','point','A2','discussion',1,'arrow pointing key point'),
('w_discussion_A2_08','reason','/ˈriːzən/','noun','이유, 근거','A cause or explanation for a belief or action.','What is the main {reason} for your opinion?','당신 의견의 주된 이유가 뭔가요?','reason','A2','discussion',1,'why reason logic thinking'),
('w_discussion_A2_09','example','/ɪɡˈzɑːmpəl/','noun','예시','A thing characteristic of its kind; used to illustrate.','Could you give me an {example}?','예시를 들어주실 수 있나요?','example','A2','discussion',1,'for example presentation slide'),
('w_discussion_A2_10','explain','/ɪkˈspleɪn/','verb','설명하다','To make something clear or easy to understand.','Could you {explain} your reasoning?','당신의 논리를 설명해 주실 수 있나요?','explain','A2','discussion',1,'teacher explaining diagram'),
('w_discussion_A2_11','mean','/miːn/','verb','의미하다','To intend or to have as a meaning.','What exactly do you {mean} by that?','정확히 무슨 말씀이에요?','mean','A2','discussion',1,'person clarifying confused expression'),
('w_discussion_A2_12','wrong','/rɒŋ/','adjective','틀린','Not correct or true; mistaken.','I think that conclusion is {wrong}.','그 결론은 틀린 것 같아요.','wrong','A2','discussion',1,'X mark wrong incorrect'),
('w_discussion_A2_13','correct','/kəˈrekt/','adjective','올바른, 맞는','Free from error; conforming to fact.','You are {correct} about the statistics.','통계에 대해서는 맞아요.','correct','A2','discussion',1,'checkmark correct accurate'),
('w_discussion_A2_14','problem','/ˈprɒbləm/','noun','문제','A matter that is difficult to deal with.','The main {problem} with this idea is the cost.','이 아이디어의 주요 문제점은 비용이에요.','problem','A2','discussion',1,'obstacle problem solving'),
('w_discussion_A2_15','solution','/səˈluːʃən/','noun','해결책','A means of solving a problem.','Do you have a {solution} in mind?','생각해 둔 해결책이 있나요?','solution','A2','discussion',1,'lightbulb solution problem solved'),
('w_discussion_A2_16','both','/boʊθ/','determiner','둘 다','Used to refer to two things or people equally.','{Both} sides have valid arguments.','양쪽 모두 타당한 주장이 있어요.','Both','A2','discussion',2,'balance scale two sides'),
('w_discussion_A2_17','important','/ɪmˈpɔːrtənt/','adjective','중요한','Of great significance or value.','It is {important} to listen to everyone.','모두의 의견을 듣는 것이 중요해요.','important','A2','discussion',1,'important priority star'),
('w_discussion_A2_18','better','/ˈbetər/','adjective','더 나은','Of a higher standard or quality compared to something else.','I think this plan is {better}.','이 계획이 더 낫다고 생각해요.','better','A2','discussion',2,'improvement better arrow up'),
('w_discussion_A2_19','clear','/klɪər/','adjective','명확한','Easy to understand; not ambiguous.','Let me make this {clear} for everyone.','모두를 위해 이것을 명확히 할게요.','clear','A2','discussion',1,'clarity clear transparent'),
('w_discussion_A2_20','feel','/fiːl/','verb','느끼다, ~라고 생각하다','To experience an emotion or to have an opinion.','I {feel} strongly about this issue.','이 문제에 대해 강하게 느껴요.','feel','A2','discussion',1,'person feeling strong emotion'),
('w_discussion_A2_21','sure','/ʃʊər/','adjective','확신하는','Having no doubt; certain.','I am not {sure} about that claim.','그 주장에 대해 확신이 없어요.','sure','A2','discussion',2,'unsure uncertain thinking person'),
('w_discussion_A2_22','together','/təˈɡeðər/','adverb','함께','With or in proximity to another person or group.','Let us work on this {together}.','함께 이것을 해결해 봐요.','together','A2','discussion',2,'team collaboration together'),
('w_discussion_A2_23','compare','/kəmˈpeər/','verb','비교하다','To examine the differences and similarities between things.','{Compare} the two options before deciding.','결정하기 전에 두 가지 선택지를 비교해요.','Compare','A2','discussion',2,'comparison two options scale'),
('w_discussion_A2_24','choose','/tʃuːz/','verb','선택하다','To pick out or select as being the best of two or more.','How should we {choose} between these ideas?','이 아이디어들 중에서 어떻게 선택해야 할까요?','choose','A2','discussion',2,'decision choice crossroads'),
('w_discussion_A2_25','change','/tʃeɪndʒ/','verb','바꾸다','To make or become different.','I have {changed} my mind on this.','이것에 대해 마음이 바뀌었어요.','changed','A2','discussion',2,'change mind arrow turning'),
('w_discussion_A2_26','main','/meɪn/','adjective','주된, 핵심','Most important; principal.','What is the {main} argument here?','여기서 주된 논점이 뭔가요?','main','A2','discussion',2,'central main point highlight'),
('w_discussion_A2_27','prove','/pruːv/','verb','증명하다','To demonstrate that something is true or correct.','Can you {prove} that claim with data?','그 주장을 데이터로 증명할 수 있나요?','prove','A2','discussion',1,'data evidence proof document'),
('w_discussion_A2_28','fact','/fækt/','noun','사실','A thing that is known or proved to be true.','Let us stick to the {facts}.','사실에 근거해서 이야기해요.','facts','A2','discussion',1,'facts data truth document'),
('w_discussion_A2_29','mind','/maɪnd/','noun','마음, 생각','The element of a person that enables thinking and feeling.','Keep an open {mind} during the discussion.','토론 중에는 열린 마음을 가져요.','mind','A2','discussion',2,'open mind brain thinking'),
('w_discussion_A2_30','share','/ʃeər/','verb','나누다, 공유하다','To give a portion of something or to tell others your thoughts.','{Share} your thoughts with the group.','그룹과 생각을 나눠주세요.','Share','A2','discussion',1,'sharing ideas group discussion'),
('w_discussion_A2_31','positive','/ˈpɒzətɪv/','adjective','긍정적인','Constructive, optimistic, or indicating agreement.','Let us focus on the {positive} aspects.','긍정적인 측면에 집중해요.','positive','A2','discussion',2,'positive thinking bright optimistic'),
('w_discussion_A2_32','negative','/ˈneɡətɪv/','adjective','부정적인','Expressing refusal or disagreement; harmful or bad.','There are also some {negative} effects to consider.','고려해야 할 부정적인 영향도 있어요.','negative','A2','discussion',2,'negative downside risk warning'),
('w_discussion_A2_33','side','/saɪd/','noun','측면, 입장','One of the positions in a debate or argument.','I can see both {sides} of the argument.','논쟁의 양면을 다 볼 수 있어요.','sides','A2','discussion',1,'balance two sides debate'),
('w_discussion_A2_34','view','/vjuː/','noun','견해, 관점','A particular way of considering something; an opinion.','What is your {view} on this?','이것에 대한 당신의 견해는 뭔가요?','view','A2','discussion',1,'viewpoint perspective angle'),
('w_discussion_A2_35','respond','/rɪˈspɒnd/','verb','반응하다, 응답하다','To say or do something as a reply.','How would you {respond} to that argument?','그 주장에 어떻게 응답하시겠어요?','respond','A2','discussion',2,'reply response conversation')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — B1 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_B1_01','argue','/ˈɑːrɡjuː/','verb','주장하다, 논쟁하다','To give reasons or evidence in support of an idea.','She {argues} that the policy is unfair.','그녀는 그 정책이 불공평하다고 주장해요.','argues','B1','discussion',1,'person arguing debating seriously'),
('w_discussion_B1_02','perspective','/pərˈspektɪv/','noun','관점, 시각','A particular attitude toward or way of regarding something.','From my {perspective}, the risk is too high.','제 관점에서는 위험이 너무 커요.','perspective','B1','discussion',1,'viewpoint angle perspective thinking'),
('w_discussion_B1_03','evidence','/ˈevɪdəns/','noun','증거, 근거','Facts or information indicating whether something is true.','You need to provide {evidence} for that claim.','그 주장에 대한 증거를 제시해야 해요.','evidence','B1','discussion',1,'evidence documents data research'),
('w_discussion_B1_04','support','/səˈpɔːrt/','verb','뒷받침하다, 지지하다','To provide evidence for; to help strengthen an argument.','The data {supports} our conclusion.','데이터가 우리 결론을 뒷받침해요.','supports','B1','discussion',1,'supporting evidence pillar structure'),
('w_discussion_B1_05','counter','/ˈkaʊntər/','verb','반론하다','To say something in response to an argument or claim.','How would you {counter} that objection?','그 반대 의견에 어떻게 반론하시겠어요?','counter','B1','discussion',1,'counter argument response debate'),
('w_discussion_B1_06','stance','/stæns/','noun','입장, 태도','The attitude or position taken on an issue.','What is your {stance} on this matter?','이 문제에 대한 당신의 입장이 뭐예요?','stance','B1','discussion',1,'person standing firm position'),
('w_discussion_B1_07','elaborate','/ɪˈlæbəreɪt/','verb','자세히 설명하다','To explain something in more detail.','Could you {elaborate} on that point?','그 부분에 대해 자세히 설명해 주실 수 있나요?','elaborate','B1','discussion',1,'detailed explanation whiteboard'),
('w_discussion_B1_08','claim','/kleɪm/','noun','주장','An assertion of something as fact, without proof.','That is a bold {claim} without evidence.','그건 증거 없는 대담한 주장이에요.','claim','B1','discussion',1,'bold claim assertion statement'),
('w_discussion_B1_09','viewpoint','/ˈvjuːpɔɪnt/','noun','관점, 시각','A position or perspective from which something is considered.','Let us consider multiple {viewpoints}.','다양한 관점을 고려해 봐요.','viewpoints','B1','discussion',1,'multiple perspectives angles diverse'),
('w_discussion_B1_10','debate','/dɪˈbeɪt/','noun','토론','A formal discussion in which opposing arguments are presented.','The {debate} on climate policy was intense.','기후 정책에 관한 토론이 치열했어요.','debate','B1','discussion',1,'formal debate podium discussion'),
('w_discussion_B1_11','acknowledge','/əkˈnɒlɪdʒ/','verb','인정하다','To accept or admit that something is true.','I {acknowledge} that your point has merit.','당신의 주장에 타당성이 있음을 인정해요.','acknowledge','B1','discussion',1,'person conceding acknowledging'),
('w_discussion_B1_12','challenge','/ˈtʃælɪndʒ/','verb','이의를 제기하다','To question or dispute the truth or validity of something.','I want to {challenge} that assumption.','그 가정에 이의를 제기하고 싶어요.','challenge','B1','discussion',1,'challenge question debate assumption'),
('w_discussion_B1_13','logical','/ˈlɒdʒɪkəl/','adjective','논리적인','Consistent with sound reasoning; rational.','Your argument is not very {logical}.','당신의 주장은 그다지 논리적이지 않아요.','logical','B1','discussion',1,'logic diagram reasoning flowchart'),
('w_discussion_B1_14','conclude','/kənˈkluːd/','verb','결론 내리다','To arrive at a judgment or decision by reasoning.','What can we {conclude} from this data?','이 데이터에서 무엇을 결론 내릴 수 있을까요?','conclude','B1','discussion',1,'conclusion summary final decision'),
('w_discussion_B1_15','assume','/əˈsjuːm/','verb','가정하다','To suppose that something is true without proof.','Do not {assume} the outcome before we know.','알기 전에 결과를 가정하지 마세요.','assume','B1','discussion',1,'assumption guess uncertain thinking'),
('w_discussion_B1_16','relevant','/ˈreləvənt/','adjective','관련 있는','Closely connected with or appropriate to the topic.','Is this information {relevant} to our discussion?','이 정보가 우리 토론과 관련이 있나요?','relevant','B1','discussion',1,'relevant connected related topic'),
('w_discussion_B1_17','valid','/ˈvælɪd/','adjective','타당한, 유효한','Well-grounded or justifiable; logically sound.','That is a {valid} concern.','그건 타당한 우려예요.','valid','B1','discussion',1,'valid checkmark approved argument'),
('w_discussion_B1_18','consider','/kənˈsɪdər/','verb','고려하다','To think carefully about something.','We should {consider} all the options.','모든 선택지를 고려해야 해요.','consider','B1','discussion',1,'consideration thinking weighing options'),
('w_discussion_B1_19','raise','/reɪz/','verb','제기하다','To bring a subject to someone''s attention for discussion.','I''d like to {raise} an important issue.','중요한 문제를 제기하고 싶어요.','raise','B1','discussion',1,'raising issue hand up speaking'),
('w_discussion_B1_20','convince','/kənˈvɪns/','verb','설득하다','To persuade someone to believe something through reasoning.','I cannot {convince} you without evidence.','증거 없이는 설득할 수 없어요.','convince','B1','discussion',1,'persuade convince argument person'),
('w_discussion_B1_21','summarize','/ˈsʌməraɪz/','verb','요약하다','To give a brief statement of the main points.','Let me {summarize} the key points.','핵심 요점을 요약해 드릴게요.','summarize','B1','discussion',1,'summary brief outline key points'),
('w_discussion_B1_22','objective','/əbˈdʒektɪv/','adjective','객관적인','Not influenced by personal feelings; based on facts.','Try to be {objective} in your assessment.','평가할 때 객관적으로 하려고 해요.','objective','B1','discussion',1,'balanced scale objective fair'),
('w_discussion_B1_23','subjective','/səbˈdʒektɪv/','adjective','주관적인','Based on personal feelings or opinions rather than facts.','That is a very {subjective} judgment.','그건 매우 주관적인 판단이에요.','subjective','B1','discussion',1,'personal opinion subjective feeling'),
('w_discussion_B1_24','context','/ˈkɒntekst/','noun','맥락, 상황','The circumstances that form the setting for an event or idea.','You need to understand the {context}.','맥락을 이해할 필요가 있어요.','context','B1','discussion',1,'context background setting environment'),
('w_discussion_B1_25','imply','/ɪmˈplaɪ/','verb','암시하다','To strongly suggest something without directly stating it.','What are you {implying} with that comment?','그 발언으로 무엇을 암시하는 건가요?','implying','B1','discussion',1,'hint imply suggestion subtle meaning'),
('w_discussion_B1_26','impact','/ˈɪmpækt/','noun','영향, 충격','The effect or influence of one thing on another.','What is the {impact} of this decision?','이 결정의 영향이 뭔가요?','impact','B1','discussion',1,'impact influence effect ripple'),
('w_discussion_B1_27','oppose','/əˈpoʊz/','verb','반대하다','To be in conflict with or disagree strongly with something.','I strongly {oppose} this proposal.','이 제안에 강하게 반대해요.','oppose','B1','discussion',1,'opposition protest disagree strongly'),
('w_discussion_B1_28','maintain','/meɪnˈteɪn/','verb','주장을 유지하다','To continue to assert or uphold a position.','I still {maintain} that I was right.','저는 여전히 제가 맞다고 주장해요.','maintain','B1','discussion',1,'firm position maintain stance'),
('w_discussion_B1_29','emphasize','/ˈemfəsaɪz/','verb','강조하다','To give special importance or prominence to.','I want to {emphasize} the deadline.','마감일을 강조하고 싶어요.','emphasize','B1','discussion',1,'emphasize highlight underline important'),
('w_discussion_B1_30','fair','/feər/','adjective','공정한','Treating people equally; just and reasonable.','That does not seem {fair} to everyone.','그게 모두에게 공정해 보이지 않아요.','fair','B1','discussion',1,'fairness justice balance scale'),
('w_discussion_B1_31','admit','/ədˈmɪt/','verb','인정하다','To confess or acknowledge something as true.','I {admit} I had not thought of that.','그건 생각하지 못했다는 걸 인정해요.','admit','B1','discussion',1,'admit concede honest acknowledgment'),
('w_discussion_B1_32','alternative','/ɔːlˈtɜːrnətɪv/','noun','대안','One of two or more available possibilities.','Do you have any {alternative} suggestions?','다른 대안적 제안이 있나요?','alternative','B1','discussion',1,'alternative option choice branch'),
('w_discussion_B1_33','propose','/prəˈpoʊz/','verb','제안하다','To put forward a plan for consideration.','I would like to {propose} a compromise.','타협안을 제안하고 싶어요.','propose','B1','discussion',1,'proposal plan whiteboard meeting'),
('w_discussion_B1_34','reflect','/rɪˈflekt/','verb','반영하다; 깊이 생각하다','To think deeply about something; to show or express something.','Take a moment to {reflect} on what was said.','말해진 것에 대해 잠시 생각해 봐요.','reflect','B1','discussion',2,'reflection thinking deep thought mirror'),
('w_discussion_B1_35','exchange','/ɪksˈtʃeɪndʒ/','noun','교환, 의견 나눔','An act of giving and receiving ideas or opinions.','This {exchange} of ideas has been very helpful.','이런 의견 교환이 매우 유익했어요.','exchange','B1','discussion',2,'exchange ideas conversation dialogue')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — B2 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_B2_01','rebut','/rɪˈbʌt/','verb','반박하다','To claim or prove that something is false or mistaken.','She was quick to {rebut} his claims.','그녀는 그의 주장을 빠르게 반박했어요.','rebut','B2','discussion',1,'rebuttal counter argument debate'),
('w_discussion_B2_02','substantiate','/səbˈstænʃieɪt/','verb','입증하다','To provide evidence to prove the truth of something.','You need to {substantiate} your argument.','당신의 주장을 입증해야 해요.','substantiate','B2','discussion',1,'evidence proof substantiate document'),
('w_discussion_B2_03','critique','/krɪˈtiːk/','noun','비평, 비판적 분석','A detailed analysis and assessment of something.','Let me offer a {critique} of this proposal.','이 제안에 대한 비평을 해드릴게요.','critique','B2','discussion',1,'critical analysis review evaluation'),
('w_discussion_B2_04','nuance','/ˈnjuːɑːns/','noun','뉘앙스, 미묘한 차이','A subtle difference in meaning, expression, or response.','The {nuance} of her argument was lost on him.','그녀 주장의 뉘앙스가 그에게 전달되지 않았어요.','nuance','B2','discussion',1,'subtle nuance shades meaning'),
('w_discussion_B2_05','premise','/ˈpremɪs/','noun','전제','A previous statement or proposition from which a conclusion is drawn.','The {premise} of your argument is flawed.','당신 주장의 전제가 잘못됐어요.','premise','B2','discussion',1,'foundation premise logic argument'),
('w_discussion_B2_06','inference','/ˈɪnfərəns/','noun','추론','A conclusion reached on the basis of evidence and reasoning.','That is a reasonable {inference} from the data.','그건 데이터에서 나온 합리적인 추론이에요.','inference','B2','discussion',1,'inference conclusion logic data'),
('w_discussion_B2_07','fallacy','/ˈfæləsi/','noun','오류, 오류 논리','A mistaken belief or a flaw in reasoning.','That is a classic logical {fallacy}.','그건 전형적인 논리적 오류예요.','fallacy','B2','discussion',1,'logical fallacy error flaw reasoning'),
('w_discussion_B2_08','rhetoric','/ˈretərɪk/','noun','수사학; 미사여구','The art of effective persuasion; sometimes used to mean empty language.','Do not let {rhetoric} replace genuine reasoning.','수사로 진짜 논리를 대체하지 마세요.','rhetoric','B2','discussion',1,'rhetoric speech persuasion words'),
('w_discussion_B2_09','bias','/ˈbaɪəs/','noun','편견, 편향','Inclination or prejudice for or against one person or group.','We must be aware of our own {bias}.','우리 자신의 편향을 인식해야 해요.','bias','B2','discussion',1,'bias prejudice tilt scale'),
('w_discussion_B2_10','objectivity','/ˌɒbdʒekˈtɪvɪti/','noun','객관성','The quality of being impartial and not influenced by feelings.','Journalists should strive for {objectivity}.','기자들은 객관성을 위해 노력해야 해요.','objectivity','B2','discussion',1,'objectivity balance impartial journalism'),
('w_discussion_B2_11','concede','/kənˈsiːd/','verb','인정하다, 양보하다','To acknowledge, often reluctantly, that something is true.','I {concede} that you have a point there.','거기서 당신의 주장이 맞다는 것을 인정해요.','concede','B2','discussion',1,'concede admit defeat graceful'),
('w_discussion_B2_12','ambiguous','/æmˈbɪɡjuəs/','adjective','모호한','Open to more than one interpretation; not clear.','The wording of the statement is {ambiguous}.','그 진술의 표현이 모호해요.','ambiguous','B2','discussion',1,'ambiguous unclear multiple meanings'),
('w_discussion_B2_13','contradict','/ˌkɒntrəˈdɪkt/','verb','모순되다, 반박하다','To state the opposite of what someone else has said.','The evidence {contradicts} your claim.','증거가 당신의 주장과 모순돼요.','contradicts','B2','discussion',1,'contradiction clash opposing ideas'),
('w_discussion_B2_14','assert','/əˈsɜːrt/','verb','주장하다, 단언하다','To state a fact or belief confidently and forcefully.','She {asserts} that the research is flawed.','그녀는 그 연구가 결함이 있다고 단언해요.','asserts','B2','discussion',1,'assertion confident statement claim'),
('w_discussion_B2_15','underlying','/ˌʌndəˈlaɪɪŋ/','adjective','근본적인, 기저의','Existing beneath what is obvious; fundamental.','What is the {underlying} cause of this issue?','이 문제의 근본적인 원인이 뭔가요?','underlying','B2','discussion',1,'root cause foundation underlying layer'),
('w_discussion_B2_16','implication','/ˌɪmplɪˈkeɪʃən/','noun','함의, 암시','The conclusion that can be drawn from something; a suggestion.','What are the {implications} of this policy?','이 정책의 함의가 뭔가요?','implications','B2','discussion',1,'implication consequence ripple effect'),
('w_discussion_B2_17','coherent','/koʊˈhɪərənt/','adjective','일관성 있는','Logical and consistent; forming a unified whole.','Your argument is not {coherent}.','당신의 주장에 일관성이 없어요.','coherent','B2','discussion',1,'coherent logical flow connected'),
('w_discussion_B2_18','scrutinize','/ˈskruːtɪnaɪz/','verb','면밀히 검토하다','To examine closely and thoroughly.','We should {scrutinize} this data carefully.','이 데이터를 면밀히 검토해야 해요.','scrutinize','B2','discussion',1,'scrutiny close examination magnifying glass'),
('w_discussion_B2_19','refine','/rɪˈfaɪn/','verb','다듬다, 정제하다','To improve something by making small changes.','Let us {refine} the argument further.','주장을 더 다듬어 봐요.','refine','B2','discussion',2,'refine improve polish argument'),
('w_discussion_B2_20','discrepancy','/dɪˈskrepənsi/','noun','불일치, 차이','An illogical or surprising lack of compatibility between two facts.','There is a {discrepancy} in the data.','데이터에 불일치가 있어요.','discrepancy','B2','discussion',1,'discrepancy mismatch data conflict'),
('w_discussion_B2_21','advocate','/ˈædvəkeɪt/','verb','옹호하다, 지지하다','To publicly recommend or support a cause or policy.','She {advocates} for stricter environmental laws.','그녀는 더 엄격한 환경법을 옹호해요.','advocates','B2','discussion',1,'advocate support campaign speaking'),
('w_discussion_B2_22','inconsistency','/ˌɪnkənˈsɪstənsi/','noun','비일관성, 모순','The quality of not staying the same throughout.','Point out any {inconsistency} in the reasoning.','논리에서의 모순을 지적해 주세요.','inconsistency','B2','discussion',1,'inconsistency contradiction mismatch'),
('w_discussion_B2_23','compelling','/kəmˈpelɪŋ/','adjective','설득력 있는','Evoking interest, attention, or admiration powerfully.','That is a {compelling} argument.','그건 설득력 있는 주장이에요.','compelling','B2','discussion',1,'compelling powerful persuasive strong'),
('w_discussion_B2_24','mitigate','/ˈmɪtɪɡeɪt/','verb','완화하다','To make something less severe, serious, or painful.','How do we {mitigate} the risks?','위험을 어떻게 완화할 수 있을까요?','mitigate','B2','discussion',1,'mitigate reduce risk buffer'),
('w_discussion_B2_25','polarize','/ˈpoʊləraɪz/','verb','양극화시키다','To divide into two sharply opposing groups.','This issue tends to {polarize} opinions.','이 문제는 의견을 양극화시키는 경향이 있어요.','polarize','B2','discussion',1,'polarize divide two sides extreme'),
('w_discussion_B2_26','provisional','/prəˈvɪʒənəl/','adjective','잠정적인','Arranged or existing for the present, possibly to be changed later.','This is only a {provisional} conclusion.','이것은 잠정적인 결론에 불과해요.','provisional','B2','discussion',2,'provisional temporary pending review'),
('w_discussion_B2_27','explicit','/ɪkˈsplɪsɪt/','adjective','명시적인, 명확한','Stated clearly and in detail; leaving nothing implied.','Be more {explicit} about what you mean.','무슨 의미인지 더 명확하게 말해주세요.','explicit','B2','discussion',1,'explicit clear direct statement'),
('w_discussion_B2_28','critical','/ˈkrɪtɪkəl/','adjective','비판적인, 중요한','Expressing disapproval; or of great importance.','We need a {critical} analysis of these claims.','이 주장들에 대한 비판적 분석이 필요해요.','critical','B2','discussion',1,'critical thinking analysis evaluation'),
('w_discussion_B2_29','oversimplify','/ˌoʊvərˈsɪmplɪfaɪ/','verb','지나치게 단순화하다','To describe something in simpler terms than it really is.','Be careful not to {oversimplify} the issue.','문제를 지나치게 단순화하지 않도록 주의해요.','oversimplify','B2','discussion',2,'oversimplify complex issue reduction'),
('w_discussion_B2_30','hypothetical','/ˌhaɪpəˈθetɪkəl/','adjective','가상의, 가정의','Imagined or suggested as a possible scenario.','Let us consider a {hypothetical} situation.','가상의 상황을 생각해 봐요.','hypothetical','B2','discussion',2,'hypothetical scenario thought experiment'),
('w_discussion_B2_31','empirical','/ɪmˈpɪrɪkəl/','adjective','경험적인, 실증적인','Based on observation or experience rather than theory.','The {empirical} evidence does not support this.','실증적 증거가 이것을 지지하지 않아요.','empirical','B2','discussion',1,'empirical data research evidence'),
('w_discussion_B2_32','framework','/ˈfreɪmwɜːrk/','noun','틀, 체계','A basic structure underlying a system, concept, or text.','We need a clear {framework} for this debate.','이 토론을 위한 명확한 틀이 필요해요.','framework','B2','discussion',1,'framework structure system organization'),
('w_discussion_B2_33','concession','/kənˈseʃən/','noun','양보, 인정','An acknowledgment that something is true or valid.','Making a {concession} can strengthen your overall position.','양보를 하면 전체적인 입장이 강화될 수 있어요.','concession','B2','discussion',2,'concession compromise negotiate'),
('w_discussion_B2_34','diverge','/daɪˈvɜːrdʒ/','verb','갈라지다, 의견이 나뉘다','To differ in opinion or direction from something.','Our views {diverge} sharply on this point.','이 지점에서 우리 견해는 크게 갈려요.','diverge','B2','discussion',2,'diverge split difference opinion fork'),
('w_discussion_B2_35','consensus','/kənˈsensəs/','noun','합의, 의견 일치','A general agreement reached by a group.','Can we reach a {consensus} on this issue?','이 문제에 대해 합의에 도달할 수 있을까요?','consensus','B2','discussion',1,'consensus agreement group decision')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — C1 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_C1_01','dialectic','/ˌdaɪəˈlektɪk/','noun','변증법','The art of investigating the truth of opinions through discussion.','Hegel''s {dialectic} involves thesis, antithesis, and synthesis.','헤겔의 변증법은 정반합을 포함해요.','dialectic','C1','discussion',1,'dialectic philosophy Hegel thesis antithesis'),
('w_discussion_C1_02','proposition','/ˌprɒpəˈzɪʃən/','noun','명제, 제안','A statement that expresses a judgment or opinion.','The {proposition} that all humans are equal is debatable.','모든 인간이 평등하다는 명제는 논쟁의 여지가 있어요.','proposition','C1','discussion',1,'proposition statement logic philosophy'),
('w_discussion_C1_03','syllogism','/ˈsɪlədʒɪzəm/','noun','삼단논법','A form of reasoning in which a conclusion is drawn from two premises.','His argument followed a classic {syllogism}.','그의 주장은 고전적인 삼단논법을 따랐어요.','syllogism','C1','discussion',1,'syllogism logic deductive reasoning diagram'),
('w_discussion_C1_04','epistemology','/ɪˌpɪstɪˈmɒlədʒi/','noun','인식론','The branch of philosophy concerned with the theory of knowledge.','{Epistemology} asks how we can know anything at all.','인식론은 우리가 무엇인가를 어떻게 알 수 있는지 묻는 철학이에요.','Epistemology','C1','discussion',1,'epistemology knowledge philosophy books'),
('w_discussion_C1_05','sophistry','/ˈsɒfɪstri/','noun','궤변, 속임수 논리','The use of clever but false arguments, especially to deceive.','His debate technique was full of {sophistry}.','그의 토론 기술은 궤변으로 가득했어요.','sophistry','C1','discussion',1,'sophistry false argument deceptive reasoning'),
('w_discussion_C1_06','axiom','/ˈæksiəm/','noun','공리, 자명한 이치','A statement or proposition regarded as self-evidently true.','It is an {axiom} that equals should be treated equally.','평등한 사람은 평등하게 대우받아야 한다는 건 공리예요.','axiom','C1','discussion',1,'axiom self evident truth principle'),
('w_discussion_C1_07','inductive','/ɪnˈdʌktɪv/','adjective','귀납적','Relating to reasoning from specific cases to general principles.','{Inductive} reasoning moves from observation to theory.','귀납적 추론은 관찰에서 이론으로 나아가요.','Inductive','C1','discussion',1,'inductive reasoning specific to general'),
('w_discussion_C1_08','deductive','/dɪˈdʌktɪv/','adjective','연역적','Relating to reasoning from general principles to specific cases.','{Deductive} logic starts with a general premise.','연역적 논리는 일반적인 전제에서 시작해요.','Deductive','C1','discussion',1,'deductive reasoning general to specific'),
('w_discussion_C1_09','postulate','/ˈpɒstjʊleɪt/','verb','가정하다, 공리로 내세우다','To suggest or assume the existence of something as a basis for reasoning.','The theory {postulates} a fundamental connection.','이론은 근본적인 연결을 가정하고 있어요.','postulates','C1','discussion',1,'postulate assumption foundation theory'),
('w_discussion_C1_10','refutation','/ˌrefjʊˈteɪʃən/','noun','반박, 논박','The action of proving a statement to be wrong or false.','Her {refutation} of the theory was thorough.','그녀의 이론 반박은 철저했어요.','refutation','C1','discussion',1,'refutation disprove evidence argument'),
('w_discussion_C1_11','cogent','/ˈkoʊdʒənt/','adjective','논리적으로 설득력 있는','Appealing to the intellect or reason; convincing and well-reasoned.','She presented a {cogent} case for reform.','그녀는 개혁을 위한 설득력 있는 논거를 제시했어요.','cogent','C1','discussion',1,'cogent argument strong reasoning'),
('w_discussion_C1_12','pedantic','/pɪˈdæntɪk/','adjective','현학적인, 지나치게 꼼꼼한','Excessively concerned with minor details or formality.','His argument became overly {pedantic}.','그의 주장이 지나치게 현학적이 됐어요.','pedantic','C1','discussion',2,'pedantic detail obsessive academic'),
('w_discussion_C1_13','conjecture','/kənˈdʒektʃər/','noun','추측, 가설','An opinion formed without firm evidence; speculation.','This is {conjecture}, not established fact.','이건 확립된 사실이 아니라 추측이에요.','conjecture','C1','discussion',1,'conjecture speculation guess unproven'),
('w_discussion_C1_14','dichotomy','/daɪˈkɒtəmi/','noun','이분법, 양분','A division between two things that are opposite or different.','The {dichotomy} between reason and emotion is false.','이성과 감정 사이의 이분법은 잘못됐어요.','dichotomy','C1','discussion',1,'dichotomy two opposites division'),
('w_discussion_C1_15','tautology','/tɔːˈtɒlədʒi/','noun','동어반복','Saying the same thing twice in different words; circular reasoning.','Calling it a "free gift" is a {tautology}.','그것을 "무료 선물"이라고 부르는 건 동어반복이에요.','tautology','C1','discussion',2,'tautology circular redundant repetition'),
('w_discussion_C1_16','presuppose','/ˌpriːsəˈpoʊz/','verb','전제로 하다','To require something as a prior condition; to assume in advance.','That question {presupposes} a shared definition.','그 질문은 공유된 정의를 전제로 해요.','presupposes','C1','discussion',1,'presuppose assumption prior condition'),
('w_discussion_C1_17','reductive','/rɪˈdʌktɪv/','adjective','환원주의적인, 지나치게 단순화하는','Tending to present something in an oversimplified way.','Your explanation is a bit {reductive}.','당신의 설명이 좀 환원주의적이에요.','reductive','C1','discussion',2,'reductive oversimplified complex reduced'),
('w_discussion_C1_18','specious','/ˈspiːʃəs/','adjective','그럴듯해 보이지만 잘못된','Superficially plausible but actually wrong.','That is a {specious} argument at best.','그건 기껏해야 그럴듯해 보이는 주장이에요.','specious','C1','discussion',1,'specious misleading plausible false'),
('w_discussion_C1_19','tangential','/tænˈdʒenʃəl/','adjective','본론에서 벗어난, 주변적인','Only slightly related to the main topic; diverging.','That comment is {tangential} to the core issue.','그 발언은 핵심 문제에서 벗어난 이야기예요.','tangential','C1','discussion',2,'tangential off-topic diverging'),
('w_discussion_C1_20','iterate','/ˈɪtəreɪt/','verb','반복하다; 되풀이하여 강조하다','To repeat a process or idea, often to refine it.','I want to {iterate} the importance of this point.','이 점의 중요성을 반복해서 강조하고 싶어요.','iterate','C1','discussion',2,'iterate repeat refine process'),
('w_discussion_C1_21','predicate','/ˈpredɪkeɪt/','verb','~에 근거하다; 전제하다','To base an argument or statement on something.','The theory is {predicated} on a false assumption.','그 이론은 잘못된 가정에 근거하고 있어요.','predicated','C1','discussion',1,'predicate base foundation argument'),
('w_discussion_C1_22','arbitrate','/ˈɑːrbɪtreɪt/','verb','중재하다','To reach an authoritative judgment or settle a dispute.','A neutral party was called in to {arbitrate}.','중립적인 측에게 중재를 부탁했어요.','arbitrate','C1','discussion',2,'arbitrate mediate settle dispute neutral'),
('w_discussion_C1_23','reconcile','/ˈrekənsaɪl/','verb','화해시키다; 조화시키다','To find a way to make two opposing views compatible.','Can we {reconcile} these two positions?','이 두 입장을 조화시킬 수 있을까요?','reconcile','C1','discussion',1,'reconcile bridge gap two sides'),
('w_discussion_C1_24','warrant','/ˈwɒrənt/','verb','정당화하다, 근거가 되다','To justify or make necessary; to be a reason for.','Does the evidence {warrant} that conclusion?','증거가 그 결론을 정당화하나요?','warrant','C1','discussion',1,'warrant justify evidence conclusion'),
('w_discussion_C1_25','extrapolate','/ɪkˈstræpəleɪt/','verb','추론하다, 외삽하다','To extend a principle to a larger or different situation.','We should not {extrapolate} too broadly from one case.','한 사례에서 너무 광범위하게 추론하면 안 돼요.','extrapolate','C1','discussion',1,'extrapolate extend data trend'),
('w_discussion_C1_26','nuanced','/ˈnjuːɑːnst/','adjective','미묘한 차이가 있는, 섬세한','Characterized by subtle distinctions or fine shades of meaning.','The issue requires a more {nuanced} analysis.','그 문제는 더 섬세한 분석이 필요해요.','nuanced','C1','discussion',1,'nuanced subtle detail analysis'),
('w_discussion_C1_27','categorical','/ˌkætɪˈɡɒrɪkəl/','adjective','단호한, 범주적인','Unambiguously explicit and direct; relating to a category.','I make a {categorical} rejection of that claim.','그 주장을 단호하게 거부해요.','categorical','C1','discussion',1,'categorical clear definitive rejection'),
('w_discussion_C1_28','invoke','/ɪnˈvoʊk/','verb','들먹이다, 원용하다','To cite or appeal to a principle or authority as a justification.','She {invoked} the principle of fairness.','그녀는 공정성 원칙을 들먹였어요.','invoked','C1','discussion',1,'invoke cite appeal authority principle'),
('w_discussion_C1_29','deconstruct','/ˌdiːkənˈstrʌkt/','verb','해체하다, 분석하다','To analyze and break apart an argument or concept.','Let me {deconstruct} that claim piece by piece.','그 주장을 하나씩 분석해 볼게요.','deconstruct','C1','discussion',1,'deconstruct analyze break down argument'),
('w_discussion_C1_30','epistemic','/ˌepɪˈstemɪk/','adjective','인식론적인','Relating to knowledge or the degree of its validation.','There is an {epistemic} limit to what we can know.','우리가 알 수 있는 것에는 인식론적 한계가 있어요.','epistemic','C1','discussion',2,'epistemic knowledge limit philosophy'),
('w_discussion_C1_31','impute','/ɪmˈpjuːt/','verb','귀속시키다, ~탓으로 돌리다','To attribute a quality or action to someone.','Do not {impute} motives to others without evidence.','증거 없이 다른 사람에게 동기를 귀속시키지 마세요.','impute','C1','discussion',2,'impute attribute blame motive'),
('w_discussion_C1_32','modality','/moʊˈdælɪti/','noun','양상, 방식','A particular form or mode of expressing something.','The {modality} of the argument shifts throughout.','주장의 양상이 전반에 걸쳐 변해요.','modality','C1','discussion',2,'modality mode expression form'),
('w_discussion_C1_33','absolve','/əbˈzɒlv/','verb','면제하다, 책임을 벗기다','To declare someone free from blame or responsibility.','You cannot simply {absolve} yourself of responsibility.','단순히 책임에서 벗어날 수는 없어요.','absolve','C1','discussion',2,'absolution responsibility free blame'),
('w_discussion_C1_34','interpolate','/ɪnˈtɜːrpəleɪt/','verb','끼워 넣다; 보간하다','To insert something into a text or argument; to estimate.','Do not {interpolate} your own assumptions into the text.','텍스트에 자신의 가정을 끼워 넣지 마세요.','interpolate','C1','discussion',2,'interpolate insert estimate assumption'),
('w_discussion_C1_35','dissertation','/ˌdɪsəˈteɪʃən/','noun','논문, 상세한 논술','A long essay, especially one written for a university degree.','Her {dissertation} explored the ethics of AI.','그녀의 논문은 AI 윤리를 탐구했어요.','dissertation','C1','discussion',2,'dissertation thesis academic writing')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- WORDS — C2 (35개)
-- ══════════════════════════════════════
INSERT INTO words (id, en, ipa, pos, ko, definition, example_en, example_ko, highlight, cefr, topic_id, priority, image_keyword) VALUES
('w_discussion_C2_01','hermeneutic','/ˌhɜːrmɪˈnjuːtɪk/','adjective','해석학적인','Relating to interpretation, especially of texts or philosophical problems.','The {hermeneutic} approach reads texts in their historical context.','해석학적 접근법은 역사적 맥락에서 텍스트를 읽어요.','hermeneutic','C2','discussion',1,'hermeneutics interpretation text meaning'),
('w_discussion_C2_02','aporia','/əˈpɔːriə/','noun','아포리아, 철학적 난점','A state of puzzlement or irresolvable conflict in philosophical dialogue.','Socrates often led his interlocutors to {aporia}.','소크라테스는 종종 대화 상대자를 아포리아로 이끌었어요.','aporia','C2','discussion',1,'aporia Socrates philosophical impasse'),
('w_discussion_C2_03','deconstruction','/ˌdiːkənˈstrʌkʃən/','noun','해체주의','A method of critical analysis associated with Derrida that questions fixed meaning.','{Deconstruction} challenges stable meaning in language.','해체주의는 언어에서의 안정적 의미에 의문을 제기해요.','Deconstruction','C2','discussion',1,'deconstruction Derrida language meaning'),
('w_discussion_C2_04','logocentrism','/ˌloʊɡoʊˈsentrɪzəm/','noun','로고스 중심주의','The assumption that reason and the Word are at the centre of meaning.','{Logocentrism} privileges spoken language over written text.','로고스 중심주의는 문자보다 구어를 특권화해요.','Logocentrism','C2','discussion',1,'logocentrism logos reason language philosophy'),
('w_discussion_C2_05','intersubjectivity','/ˌɪntərˌsʌbdʒekˈtɪvɪti/','noun','상호주관성','The sharing of subjective states by two or more individuals.','{Intersubjectivity} is essential for meaningful communication.','상호주관성은 의미 있는 소통에 필수적이에요.','Intersubjectivity','C2','discussion',1,'intersubjectivity shared understanding mutual'),
('w_discussion_C2_06','discourse','/ˈdɪskɔːrs/','noun','담론, 담화','Written or spoken communication or debate; a system of knowledge.','His work analyzes the {discourse} of power.','그의 작업은 권력의 담론을 분석해요.','discourse','C2','discussion',1,'discourse power language Foucault'),
('w_discussion_C2_07','praxis','/ˈpræksɪs/','noun','실천, 프락시스','The process by which a theory is enacted or realized.','{Praxis} unites theory and practice in critical thought.','프락시스는 비판적 사고에서 이론과 실천을 통합해요.','Praxis','C2','discussion',1,'praxis theory practice action'),
('w_discussion_C2_08','ontological','/ˌɒntəˈlɒdʒɪkəl/','adjective','존재론적인','Relating to the branch of philosophy dealing with the nature of being.','The argument has {ontological} implications.','그 주장은 존재론적인 함의를 가져요.','ontological','C2','discussion',1,'ontology being existence philosophy'),
('w_discussion_C2_09','paradigmatic','/ˌpærədɪɡˈmætɪk/','adjective','패러다임적인, 전형적인','Relating to a paradigm; serving as a typical example of something.','This case is {paradigmatic} of the larger issue.','이 사례는 더 큰 문제의 전형적인 예시예요.','paradigmatic','C2','discussion',1,'paradigm example typical model Kuhn'),
('w_discussion_C2_10','phenomenological','/fɪˌnɒmɪnəˈlɒdʒɪkəl/','adjective','현상학적인','Relating to the study of consciousness and structures of experience.','The {phenomenological} approach focuses on lived experience.','현상학적 접근법은 살아있는 경험에 집중해요.','phenomenological','C2','discussion',1,'phenomenology experience consciousness Husserl'),
('w_discussion_C2_11','teleological','/ˌteliəˈlɒdʒɪkəl/','adjective','목적론적인','Relating to the explanation of phenomena by final causes or purposes.','A {teleological} argument infers design from order.','목적론적 논증은 질서로부터 설계를 추론해요.','teleological','C2','discussion',1,'teleology purpose design argument'),
('w_discussion_C2_12','dialectical','/ˌdaɪəˈlektɪkəl/','adjective','변증법적인','Relating to the Socratic or Hegelian method of argument and reasoning.','The {dialectical} process reveals hidden contradictions.','변증법적 과정은 숨겨진 모순을 드러내요.','dialectical','C2','discussion',1,'dialectical contradiction synthesis Hegel'),
('w_discussion_C2_13','epistemological','/ɪˌpɪstɪməˈlɒdʒɪkəl/','adjective','인식론적인','Relating to the theory of knowledge and its validity.','This raises an {epistemological} question about certainty.','이것은 확실성에 관한 인식론적 질문을 제기해요.','epistemological','C2','discussion',1,'epistemological knowledge validity certainty'),
('w_discussion_C2_14','incommensurable','/ˌɪnkəˈmenʃərəbəl/','adjective','공약 불가능한, 비교 불가능한','Having no common measure; not able to be judged by the same standard.','The two frameworks are largely {incommensurable}.','두 틀은 크게 비교 불가능해요.','incommensurable','C2','discussion',2,'incommensurable incomparable different standards'),
('w_discussion_C2_15','metatheory','/ˈmetəˌθɪəri/','noun','메타이론','A theory that considers the assumptions or methods of another theory.','The paper offers a {metatheory} of argumentation.','그 논문은 논증에 관한 메타이론을 제시해요.','metatheory','C2','discussion',2,'metatheory abstract higher order theory'),
('w_discussion_C2_16','apotheosis','/əˌpɒθiˈoʊsɪs/','noun','절정, 전형','The highest point of development; the quintessence of something.','This essay represents the {apotheosis} of the argument.','이 에세이는 그 주장의 절정을 대표해요.','apotheosis','C2','discussion',2,'apotheosis peak pinnacle excellence'),
('w_discussion_C2_17','heterodox','/ˈhetərədɒks/','adjective','이단적인, 비정통적인','Not conforming to established or accepted beliefs or doctrines.','{Heterodox} economic views challenge mainstream theory.','비정통적인 경제적 관점은 주류 이론에 도전해요.','Heterodox','C2','discussion',2,'heterodox unorthodox unconventional dissenting'),
('w_discussion_C2_18','apodictic','/ˌæpəˈdɪktɪk/','adjective','자명한, 필연적으로 참인','Clearly established or beyond dispute; incontrovertibly certain.','He presented it as an {apodictic} truth.','그는 그것을 자명한 진리로 제시했어요.','apodictic','C2','discussion',2,'apodictic certain absolute undeniable'),
('w_discussion_C2_19','semiotic','/ˌsiːmiˈɒtɪk/','adjective','기호학적인','Relating to the study of signs and symbols in communication.','The {semiotic} analysis revealed hidden cultural meanings.','기호학적 분석은 숨겨진 문화적 의미를 드러냈어요.','semiotic','C2','discussion',1,'semiotics signs symbols meaning language'),
('w_discussion_C2_20','defeasible','/dɪˈfiːzɪbəl/','adjective','논박 가능한, 조건부로 타당한','Capable of being annulled; valid but open to revision in light of new evidence.','This is a {defeasible} argument, subject to new evidence.','이건 새 증거에 따라 번복될 수 있는 논박 가능한 주장이에요.','defeasible','C2','discussion',2,'defeasible revisable conditional argument'),
('w_discussion_C2_21','polysemy','/ˈpɒlɪsiːmi/','noun','다의성','The coexistence of many possible meanings for a word or phrase.','The {polysemy} of the term creates ambiguity.','그 용어의 다의성이 모호함을 만들어요.','polysemy','C2','discussion',2,'polysemy multiple meanings word ambiguity'),
('w_discussion_C2_22','immanent','/ˈɪmənənt/','adjective','내재적인','Existing within or inherent in something; not transcendent.','The contradiction is {immanent} in the system itself.','그 모순은 시스템 자체에 내재적이에요.','immanent','C2','discussion',2,'immanent inherent internal within'),
('w_discussion_C2_23','exegesis','/ˌeksɪˈdʒiːsɪs/','noun','주석, 해석, 주해','Critical explanation or interpretation of a text.','His {exegesis} of the original text was illuminating.','그의 원문 주석은 매우 시사적이었어요.','exegesis','C2','discussion',1,'exegesis interpretation commentary text'),
('w_discussion_C2_24','prolegomena','/ˌproʊlɪˈɡɒmɪnə/','noun','서론, 예비적 고찰','Preliminary remarks or observations, especially as an introduction.','The essay begins with necessary {prolegomena}.','그 에세이는 필요한 예비적 고찰로 시작해요.','prolegomena','C2','discussion',2,'prolegomena introduction preliminary remarks'),
('w_discussion_C2_25','antinomy','/ænˈtɪnəmi/','noun','이율배반','A contradiction between two apparently reasonable principles.','Kant famously described the {antinomy} of pure reason.','칸트는 순수 이성의 이율배반을 유명하게 묘사했어요.','antinomy','C2','discussion',1,'antinomy contradiction Kant reason paradox'),
('w_discussion_C2_26','qualia','/ˈkwɑːliə/','noun','감각질, 주관적 경험의 질','The internal subjective component of sense perception.','Consciousness studies grapple with the problem of {qualia}.','의식 연구는 감각질 문제와 씨름해요.','qualia','C2','discussion',2,'qualia consciousness subjective experience'),
('w_discussion_C2_27','alterity','/ɒlˈterɪti/','noun','타자성','The state of being other or different; otherness.','Levinas grounds ethics in the recognition of {alterity}.','레비나스는 타자성의 인식에서 윤리를 정초해요.','alterity','C2','discussion',2,'alterity otherness difference Levinas ethics'),
('w_discussion_C2_28','reification','/ˌreɪɪfɪˈkeɪʃən/','noun','물화, 사물화','The process of treating an abstraction as if it were concrete.','Marx critiqued the {reification} of social relations.','마르크스는 사회적 관계의 물화를 비판했어요.','reification','C2','discussion',2,'reification abstraction concrete Marx'),
('w_discussion_C2_29','transcendental','/ˌtrænsənˈdentəl/','adjective','초월적인, 선험적인','Relating to a spiritual realm beyond the physical; or Kantian a priori conditions.','Kant''s {transcendental} idealism reshaped philosophy.','칸트의 선험적 관념론은 철학을 새롭게 형성했어요.','transcendental','C2','discussion',1,'transcendental Kant idealism beyond'),
('w_discussion_C2_30','elenchus','/ɪˈleŋkəs/','noun','엘렝코스, 소크라테스식 반박','The Socratic method of refutation through cross-examination.','The {elenchus} exposes the ignorance of the interlocutor.','엘렝코스는 대화 상대자의 무지를 드러내요.','elenchus','C2','discussion',1,'elenchus Socrates cross examination refutation'),
('w_discussion_C2_31','paraconsistency','/ˌpærəkənˈsɪstənsi/','noun','준일관성, 역설 허용 논리','A property of a logic that can tolerate contradictions without explosion.','{Paraconsistency} allows for reasoning under contradiction.','준일관성은 모순 속에서도 추론을 가능하게 해요.','Paraconsistency','C2','discussion',2,'paraconsistency logic contradiction tolerance'),
('w_discussion_C2_32','autopoiesis','/ˌɔːtəʊpɔɪˈiːsɪs/','noun','자기 생산, 자기 조직','A system capable of reproducing and maintaining itself.','The discourse functions as an {autopoiesis}.','그 담론은 자기 생산적인 기능을 해요.','autopoiesis','C2','discussion',2,'autopoiesis self organization system theory'),
('w_discussion_C2_33','apophatic','/ˌæpəˈfætɪk/','adjective','부정신학적인; 부정을 통해 정의하는','Relating to the approach of describing something by saying what it is not.','The {apophatic} method defines by negation.','부정신학적 방법은 부정을 통해 정의해요.','apophatic','C2','discussion',2,'apophatic via negativa theology definition'),
('w_discussion_C2_34','metalinguistic','/ˌmetəlɪŋˈɡwɪstɪk/','adjective','메타언어학적인','Relating to language used to analyse or describe language itself.','The debate became {metalinguistic} in nature.','토론이 본질적으로 메타언어학적이 됐어요.','metalinguistic','C2','discussion',2,'metalinguistic language about language analysis'),
('w_discussion_C2_35','undecidability','/ʌndɪˌsaɪdəˈbɪlɪti/','noun','결정 불가능성','The property of a statement that can be neither proved nor disproved.','Derrida linked {undecidability} to language itself.','데리다는 결정 불가능성을 언어 자체와 연결시켰어요.','undecidability','C2','discussion',2,'undecidability Derrida language uncertainty')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — A1 (7개): 의견 말하기
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_A1_01','I think so too.','저도 그렇게 생각해요.','I think so','동의를 표현할 때 "I think so too."는 가장 자연스러운 표현이에요. "Me too."보다 대화에서 더 자연스럽게 들려요.','동의','A1','discussion','pattern',NULL,1),
('s_discussion_A1_02','I do not think that is a good idea.','그건 좋은 생각이 아닌 것 같아요.','I do not think','부드럽게 반대 의견을 말할 때 "I do not think ~"를 쓰면 직접적인 거절보다 훨씬 공손하게 들려요.','반대','A1','discussion','pattern',NULL,2),
('s_discussion_A1_03','What do you think about that?','그것에 대해 어떻게 생각해요?','What do you think','상대방의 의견을 구할 때 가장 기본적인 표현이에요. 토론을 시작하는 데 꼭 필요해요.','의견 묻기','A1','discussion','pattern',NULL,3),
('s_discussion_A1_04','Maybe you are right.','아마도 당신이 맞을 수도 있어요.','Maybe you are right','완전히 확신하지 못할 때 "Maybe"를 붙여서 유연하게 동의를 표현해요. 대화 분위기를 부드럽게 유지해줘요.','부분 동의','A1','discussion','pattern',NULL,4),
('s_discussion_A1_05','I am not sure about that.','그것에 대해 잘 모르겠어요.','I am not sure','확신이 없을 때 "I am not sure"를 쓰면 솔직하면서도 공손하게 들려요.','불확실','A1','discussion','pattern',NULL,5),
('s_discussion_A1_06','That is a good idea.','그건 좋은 생각이에요.','That is a good idea','상대방의 아이디어를 긍정할 때 가장 간단하고 자연스러운 표현이에요. 대화를 활기차게 만들어줘요.','칭찬·긍정','A1','discussion','pattern',NULL,6),
('s_discussion_A1_07','I like your idea.','당신의 아이디어가 마음에 들어요.','I like your idea','"I like your idea."는 "Good idea."보다 더 개인적이고 따뜻한 느낌을 줘요. 상대방이 기분 좋게 느낄 수 있어요.','격려·지지','A1','discussion','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — A2 (7개): 동의/반대
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_A2_01','I agree with your opinion.','당신의 의견에 동의해요.','I agree with','단순히 "I agree."보다 "I agree with your opinion."이 더 구체적이고 진지하게 들려요.','동의','A2','discussion','pattern',NULL,1),
('s_discussion_A2_02','I see your point, but I disagree.','당신의 의견은 이해하지만, 동의하지 않아요.','I see your point, but','반대 의견을 말할 때 상대방의 입장을 먼저 인정하면 더 공손하게 들려요. "I see your point, but ~"은 매우 유용한 패턴이에요.','반대','A2','discussion','pattern',NULL,2),
('s_discussion_A2_03','In my opinion, we should try a different approach.','제 의견으로는 다른 방법을 시도해야 해요.','In my opinion','자신의 의견을 말할 때 "In my opinion"을 앞에 붙이면 주관적인 견해임을 분명히 해줘요.','의견 제시','A2','discussion','pattern',NULL,3),
('s_discussion_A2_04','Could you explain your reason?','이유를 설명해 주실 수 있나요?','explain your reason','상대방의 논거를 이해하고 싶을 때 쓰는 정중한 표현이에요. 토론을 더 깊이 있게 만들어줘요.','이유 묻기','A2','discussion','pattern',NULL,4),
('s_discussion_A2_05','I think both sides have a point.','양쪽 다 일리가 있다고 생각해요.','both sides have a point','양쪽 의견을 균형 있게 인정할 때 쓰는 표현이에요. 중립적인 입장에서 토론을 진행할 때 유용해요.','중립·균형','A2','discussion','pattern',NULL,5),
('s_discussion_A2_06','Can you give me an example?','예시를 들어 주실 수 있나요?','give me an example','이해를 높이기 위해 구체적인 예를 요청할 때 쓰는 표현이에요.','예시 요청','A2','discussion','pattern',NULL,6),
('s_discussion_A2_07','I suggest we discuss this more carefully.','이것을 더 신중하게 논의해 보는 게 어떨까요?','I suggest we discuss','"I suggest we ~"는 그룹 토론에서 방향을 제안할 때 자연스럽게 쓸 수 있는 표현이에요.','제안','A2','discussion','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — B1 (7개): 근거 제시
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_B1_01','The evidence suggests that this approach is more effective.','증거에 따르면 이 방법이 더 효과적이에요.','The evidence suggests','근거를 제시할 때 "The evidence suggests that ~"를 쓰면 주관적인 의견이 아니라 데이터에 기반한 주장처럼 들려요.','근거 제시','B1','discussion','pattern',NULL,1),
('s_discussion_B1_02','From my perspective, the main issue is the lack of funding.','제 관점에서, 주요 문제는 자금 부족이에요.','From my perspective','자신의 시각을 명확히 하면서 주장을 펼칠 때 쓰는 표현이에요. "In my opinion"보다 더 분석적인 느낌이에요.','관점 제시','B1','discussion','pattern',NULL,2),
('s_discussion_B1_03','To elaborate on that point, let me give you a concrete example.','그 부분을 더 설명하자면, 구체적인 예를 들어 드릴게요.','To elaborate on that point','"To elaborate on that point"는 앞서 말한 내용을 더 자세히 설명할 때 쓰는 고급 패턴이에요.','부연 설명','B1','discussion','pattern',NULL,3),
('s_discussion_B1_04','I would argue that the benefits outweigh the risks.','저는 이점이 위험보다 크다고 주장하겠어요.','I would argue that','"I would argue that ~"는 자신의 주장을 자신감 있게 펼칠 때 쓰는 B1 이상 필수 표현이에요.','주장','B1','discussion','pattern',NULL,4),
('s_discussion_B1_05','That is a valid concern, but consider the following.','그건 타당한 우려이지만, 다음을 고려해 주세요.','That is a valid concern, but','상대방의 주장을 인정하면서도 반론을 제기하는 세련된 방법이에요. 토론에서 균형감을 보여줘요.','인정 후 반론','B1','discussion','pattern',NULL,5),
('s_discussion_B1_06','Could you support that claim with evidence?','그 주장을 증거로 뒷받침해 주실 수 있나요?','support that claim with evidence','근거 없는 주장에 대해 정중하게 증거를 요구하는 표현이에요. 비판적 사고 능력을 보여줘요.','증거 요구','B1','discussion','pattern',NULL,6),
('s_discussion_B1_07','Taking everything into account, I believe this is the best option.','모든 것을 고려했을 때, 이것이 최선의 선택이라고 생각해요.','Taking everything into account','"Taking everything into account"는 결론을 내리기 전에 균형 잡힌 판단을 했음을 보여주는 표현이에요.','결론','B1','discussion','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — B2 (7개): 반론, 비판적 사고
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_B2_01','Your argument seems to rest on a flawed premise.','당신의 주장은 잘못된 전제에 기반하는 것 같아요.','rest on a flawed premise','전제 자체의 오류를 지적하는 강력한 반박 패턴이에요. 단순히 결론에 반대하는 것보다 더 설득력이 있어요.','전제 반박','B2','discussion','pattern',NULL,1),
('s_discussion_B2_02','I would like to rebut that point directly.','그 부분을 직접 반박하고 싶어요.','rebut that point directly','"rebut"은 공식적인 토론에서 반박할 때 쓰는 동사예요. "disagree"보다 훨씬 강하고 논리적인 어감이에요.','반박','B2','discussion','pattern',NULL,2),
('s_discussion_B2_03','That claim lacks empirical support.','그 주장에는 실증적 근거가 부족해요.','lacks empirical support','데이터나 연구 없이 이루어진 주장을 비판할 때 쓰는 표현이에요. 학술적이고 설득력 있게 들려요.','비판적 분석','B2','discussion','pattern',NULL,3),
('s_discussion_B2_04','We need to distinguish between correlation and causation here.','여기서 상관관계와 인과관계를 구분해야 해요.','distinguish between correlation and causation','논리적 오류 중 가장 흔한 인과 오류를 지적할 때 쓰는 표현이에요. 비판적 사고의 핵심 패턴이에요.','논리적 오류 지적','B2','discussion','pattern',NULL,4),
('s_discussion_B2_05','While I concede that point, the broader implication is more concerning.','그 부분은 인정하지만, 더 큰 함의가 더 걱정스러워요.','While I concede that point','부분적으로 동의하면서도 더 중요한 쟁점으로 이동하는 고급 토론 기술이에요.','부분 인정 후 전환','B2','discussion','pattern',NULL,5),
('s_discussion_B2_06','Your reasoning contains an implicit bias worth examining.','당신의 논리에는 검토할 만한 암묵적 편향이 있어요.','contains an implicit bias','논리의 구조적 편향을 지적하는 비판적 패턴이에요. 격식 있는 토론에서 매우 설득력 있게 들려요.','편향 지적','B2','discussion','pattern',NULL,6),
('s_discussion_B2_07','The nuance of this issue is often lost in simplistic narratives.','이 문제의 뉘앙스는 단순한 이야기에서 종종 사라져요.','The nuance of this issue','복잡한 문제를 지나치게 단순화하는 경향을 지적할 때 쓰는 표현이에요.','복잡성 강조','B2','discussion','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — C1 (7개): 논증
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_C1_01','The syllogism you presented is formally valid but materially unsound.','당신이 제시한 삼단논법은 형식적으로는 타당하지만 내용상 불건전해요.','formally valid but materially unsound','타당성(validity)과 건전성(soundness)을 구분하는 이 표현은 논리학의 핵심 구분을 활용해요.','논리 비판','C1','discussion','pattern',NULL,1),
('s_discussion_C1_02','Let me deconstruct the underlying assumptions of that argument.','그 주장의 근본 가정들을 해체해 볼게요.','deconstruct the underlying assumptions','가정 자체를 분석하는 것은 강력한 비판 전략이에요. 이 패턴은 매우 학문적이고 설득력 있어요.','가정 해체','C1','discussion','pattern',NULL,2),
('s_discussion_C1_03','That reasoning commits the fallacy of false dichotomy.','그 추론은 거짓 이분법의 오류를 범하고 있어요.','commits the fallacy of false dichotomy','논리적 오류의 이름을 정확히 지적하는 것은 고급 토론의 핵심 기술이에요.','논리 오류 지적','C1','discussion','pattern',NULL,3),
('s_discussion_C1_04','I would postulate that the causal chain is more complex than suggested.','인과 사슬이 제시된 것보다 더 복잡하다고 가정해 볼 수 있어요.','postulate that the causal chain','"postulate"를 사용하면 가설적인 논점을 학문적으로 제시할 수 있어요.','가설 제시','C1','discussion','pattern',NULL,4),
('s_discussion_C1_05','Your inductive generalization requires a much larger sample to hold.','당신의 귀납적 일반화는 성립하려면 훨씬 더 큰 표본이 필요해요.','inductive generalization requires a much larger sample','귀납적 오류 중 성급한 일반화를 지적하는 정교한 표현이에요.','귀납 오류 비판','C1','discussion','pattern',NULL,5),
('s_discussion_C1_06','The cogency of your case depends on whether we accept the axiom.','당신 논거의 설득력은 우리가 그 공리를 받아들이느냐에 달려 있어요.','cogency of your case depends on','논증의 전제 조건을 명확히 지적하는 고급 표현이에요. 학술 토론에서 매우 효과적이에요.','조건부 평가','C1','discussion','pattern',NULL,6),
('s_discussion_C1_07','Even if we grant the premise, the conclusion does not necessarily follow.','전제를 인정하더라도, 결론이 반드시 따라오는 것은 아니에요.','the conclusion does not necessarily follow','전제와 결론 사이의 논리적 비약을 지적하는 핵심 반박 패턴이에요.','논리적 비약 지적','C1','discussion','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════
-- PATTERNS — C2 (7개): 철학적 토론
-- ══════════════════════════════════════
INSERT INTO sentences (id, en, ko, highlight, tip, situation, cefr, topic_id, type, beats, sort_order) VALUES
('s_discussion_C2_01','The aporia here is that every attempt to define the term undermines itself.','여기서의 아포리아는 용어를 정의하려는 모든 시도가 스스로를 약화시킨다는 거예요.','The aporia here is','아포리아는 소크라테스 대화에서 나온 개념으로, 자기 모순적 난점을 지적할 때 사용해요.','철학적 역설','C2','discussion','pattern',NULL,1),
('s_discussion_C2_02','This discourse is inherently logocentric in its privileging of spoken reason.','이 담론은 구어적 이성을 특권화하는 점에서 본질적으로 로고스 중심주의적이에요.','inherently logocentric','데리다의 로고스 중심주의 비판을 적용하는 표현이에요. 언어와 의미의 권력 구조를 분석할 때 써요.','담론 비판','C2','discussion','pattern',NULL,2),
('s_discussion_C2_03','Without intersubjectivity, the very possibility of shared meaning collapses.','상호주관성 없이는 공유된 의미의 가능성 자체가 붕괴돼요.','Without intersubjectivity','후설과 하버마스의 개념을 활용해 의사소통의 근본 조건을 논할 때 쓰는 표현이에요.','소통의 조건','C2','discussion','pattern',NULL,3),
('s_discussion_C2_04','From a hermeneutic standpoint, we must read the text against its historical horizon.','해석학적 관점에서, 우리는 텍스트를 역사적 지평에 대비해서 읽어야 해요.','From a hermeneutic standpoint','가다머의 지평 융합 개념을 활용한 표현이에요. 텍스트 해석의 역사성을 강조할 때 써요.','해석학적 분석','C2','discussion','pattern',NULL,4),
('s_discussion_C2_05','The ontological claim embedded in that statement demands further scrutiny.','그 진술에 내재된 존재론적 주장은 더 면밀한 검토가 필요해요.','ontological claim embedded in','존재론적 가정을 명시적으로 드러내는 표현이에요. 철학적 토론에서 숨겨진 가정을 지적할 때 유용해요.','존재론적 비판','C2','discussion','pattern',NULL,5),
('s_discussion_C2_06','That paradigmatic case cannot be used to justify the broader theoretical framework.','그 패러다임적 사례는 더 광범위한 이론적 틀을 정당화하는 데 사용될 수 없어요.','paradigmatic case cannot be used to justify','쿤의 패러다임 개념을 활용해 사례와 이론 사이의 논리적 간격을 지적하는 표현이에요.','패러다임 비판','C2','discussion','pattern',NULL,6),
('s_discussion_C2_07','The praxis of this theory reveals a tension between its normative and descriptive claims.','이 이론의 실천은 규범적 주장과 서술적 주장 사이의 긴장을 드러내요.','praxis of this theory reveals a tension','이론과 실천의 긴장을 비판하는 고급 표현이에요. 프락시스 개념을 아는 C2 학습자에게 적합해요.','이론과 실천의 긴장','C2','discussion','pattern',NULL,7)
ON CONFLICT (id) DO NOTHING;
